### ISSUE TITLE
Client reply to email opens as a new ticket(it works with cc, but not ok with to)

### ISSUE THREAD

**Issue by nancykyo** [osTicket/osTicket#1048]
Client reply to email opens as a new ticket(it works with cc, but not ok with to)

this one is ok, for I do 'cc' while sending a mail to open a ticket
![image](https://cloud.githubusercontent.com/assets/1332885/3338377/d9419314-f85a-11e3-99c4-d1f4d53f143b.png)

![image](https://cloud.githubusercontent.com/assets/1332885/3338337/3c8a9fac-f85a-11e3-868f-ba20e4c3af0e.png)

it seems like a mailparse problem.
the belowing is seperated, for I using 'to', not 'cc' strictly.

![image](https://cloud.githubusercontent.com/assets/1332885/3338374/c7469cf4-f85a-11e3-9196-8dabd91c2fd3.png)

![image](https://cloud.githubusercontent.com/assets/1332885/3338333/2ed5d0f2-f85a-11e3-8db2-c2f9e2a3bd49.png)

Hope that I've describe the problem clearly..

**Comment by molul** [comment]
I'm having the same problem in osTicket 1.9.8 with a chinese customer who uses an email client called qqmail. Everytime he replies to a ticket through mail he opens a new ticket, and he's by far the client that writes to us the most, hehe.

I checked two of his emails and "references" or "in-reply-to" fields don't even appear in the mail's headers. I wonder if there might be something he could configure in his email client to make this work. If not, a merge tickets (already asked, I think) utility would do the trick.

Here are the headers. First email:

Return-Path: <litianyu@sanitec.net.cn>
X-Original-To: support@brainstorm.es
Delivered-To: support@brainstorm.es
Received: from regular1.263xmail.com (regular1.263xmail.com [211.150.99.137])
	(using TLSv1 with cipher ADH-AES256-SHA (256/256 bits))
	(No client certificate requested)
	by smtp.brainstorm.es (Postfix) with ESMTP id 3E01A399635;
	Mon, 19 Oct 2015 15:11:22 +0200 (CEST)
Received: from litianyu?sanitec.net.cn (unknown [192.168.167.211])
	by regular1.263xmail.com (Postfix) with SMTP id E5F60902A;
	Mon, 19 Oct 2015 21:11:12 +0800 (CST)
X-263anti-spam:RES:Ip;
X-MAIL-GRAY:0
X-MAIL-DELIVERY:1
Received: from wmthree-7 (localhost.localdomain [127.0.0.1])
	by smtp.263.net (Postfix) with ESMTP id 3DC5144B;
	Mon, 19 Oct 2015 21:11:15 +0800 (CST)
X-RL-SENDER:litianyu@sanitec.net.cn
X-FST-TO:support@brainstorm.es
X-SENDER-IP:192.168.167.111
X-LOGIN-NAME:wmsendmail@net263.com
X-UNIQUE-TAG:<567befbd1122f49741fdd0ec647085a8>
X-ATTACHMENT-NUM:0
X-SENDER:litianyu@sanitec.net.cn
X-DNS-TYPE:0
Received: from wmthree-7 (unknown [192.168.167.111])
	by smtp.263.net (Postfix) whith ESMTP id 11423KXRFT3;
	Mon, 19 Oct 2015 21:11:15 +0800 (CST)
Date: Mon, 19 Oct 2015 21:11:15 +0800 (CST)
From: =?UTF-8?B?5p2O5aSp5a6H?= <litianyu@sanitec.net.cn>
To: =?UTF-8?B?c3VwcG9ydA==?= <support@brainstorm.es>
Cc: =?UTF-8?B?ZGlzdHJpYnV0b3I=?= <distributor_support@brainstorm.es>, 
	=?UTF-8?B?Qm9yamEgQ2hpcml2ZWxsYQ==?= <bchirivella@brainstorm.es>, 
	=?UTF-8?B?bGl1Zg==?= <liuf@vip.163.com>, 
	=?UTF-8?B?bGl3ZW5xaW5n?= <liwenqing@sanitec.net.cn>, 
	=?UTF-8?B?5a6L5ram5p2w?= <songrunjie@sanitec.net.cn>
Message-ID: <1177553564.2090494.1445260275278.JavaMail.root@wmthree-7>
Subject: =?UTF-8?B?Rnc6aW1wb3J0YW50X3F1ZXN0aW9u?=
MIME-Version: 1.0
Content-Type: text/html;  charset=utf-8
Content-Transfer-Encoding: base64
X-Send-Individually: 0
X-Reply-Previous-EmailId: 
X-Priority: 3





And first reply:

Return-Path: <litianyu@sanitec.net.cn>
X-Original-To: support@brainstorm.es
Delivered-To: support@brainstorm.es
Received: from regular1.263xmail.com (regular1.263xmail.com [211.150.99.138])
	(using TLSv1 with cipher ADH-AES256-SHA (256/256 bits))
	(No client certificate requested)
	by smtp.brainstorm.es (Postfix) with ESMTP id AC522399635
	for <support@brainstorm.es>; Tue, 20 Oct 2015 11:55:34 +0200 (CEST)
Received: from litianyu?sanitec.net.cn (unknown [192.168.167.220])
	by regular1.263xmail.com (Postfix) with SMTP id 11009502F
	for <support@brainstorm.es>; Tue, 20 Oct 2015 17:55:26 +0800 (CST)
X-263anti-spam:bpcheck:1;
X-MAIL-GRAY:0
X-MAIL-DELIVERY:1
X-ADDR-CHECKED:0
Received: from wmthree-6 (localhost.localdomain [127.0.0.1])
	by smtp.263.net (Postfix) with ESMTP id 1478E449
	for <support@brainstorm.es>; Tue, 20 Oct 2015 17:55:26 +0800 (CST)
X-RL-SENDER:litianyu@sanitec.net.cn
X-FST-TO:support@brainstorm.es
X-SENDER-IP:192.168.166.104
X-LOGIN-NAME:wmsendmail@net263.com
X-UNIQUE-TAG:<285982298b484dd1c0c5fad16d9316ce>
X-ATTACHMENT-NUM:0
X-SENDER:litianyu@sanitec.net.cn
X-DNS-TYPE:0
Received: from wmthree-6 (unknown [192.168.166.104])
	by smtp.263.net (Postfix) whith ESMTP id 10533RMG0EX;
	Tue, 20 Oct 2015 17:55:27 +0800 (CST)
Date: Tue, 20 Oct 2015 17:55:27 +0800 (CST)
From: =?UTF-8?B?5p2O5aSp5a6H?= <litianyu@sanitec.net.cn>
To: =?UTF-8?B?QnJhaW5zdG9ybSBNdWx0aW1lZGlhIFN1cHBvcnQg?= <support@brainstorm.es>
Message-ID: <880251356.371460.1445334927965.JavaMail.xmail@wmthree-6>
Subject: =?UTF-8?B?UmU6UmU6IEZ3OmltcG9ydGFudF9xdWVzdGlvbg==?=
MIME-Version: 1.0
Content-Type: multipart/related; 
	boundary="----=_Part_371459_343762198.1445334927965"
X-Send-Individually: 0
X-Reply-Previous-EmailId: 
X-Priority: 3

**Comment by ntozier** [comment]
Have you tried adding the ticket number to the subject in the templates as described in other threads?

**Comment by molul** [comment]
Thanks, I've just done it. Hope it works :)
