### ISSUE TITLE
UTF-8 email body is stored as HTML entities in the DB

### ISSUE THREAD

**Issue by kioan** [osTicket/osTicket#1058]
When a new ticket is opened automatically from an incoming email, its message body is stored as a sequence of HTML entities in the database (ost_ticket_thread table).

For example the following email snippet

```
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 8bit

Παρακαλώ να φροντίσετε άμεσα 
```

...will be stored in the ost_ticket_thread.body field as:

```
<pre>&Pi;&alpha;&rho;&alpha;&kappa;&alpha;&lambda;ώ &nu;&alpha; &phi;&rho;&omicron;&nu;&tau;ί&sigma;&epsilon;&tau;&epsilon; ά&mu;&epsilon;&sigma;&alpha; 
```

I think that all fields should be inserted as UTF-8 strings because now it is impossible to run external queries to the database.

All data entered through the web interface are stored correctly in UTF-8.

**Comment by greezybacon** [comment]
I think this was officially fixed in 670bf5c58d3879b0e8c7a50ded1e39efe97be0df and released in v1.9.5. @kioan have you been able to confirm this?

**Comment by mlipok** [comment]
After this time, you can consider this as closed ?

**Comment by ntozier** [comment]
No one has posted to confirm that it has been fixed.
