### ISSUE TITLE
Wrong Time Displayed in Options Dropdown

### ISSUE THREAD

**Issue by urda** [osTicket/osTicket#1060]
Examine the following:

![wrongtimes-osticket](https://cloud.githubusercontent.com/assets/1648492/3364188/73870242-fb1c-11e3-96c4-f5ac84c13db7.png)

Notice something wrong here? Yup, the displayed time string (the text shown to the ticket admin user or what have you) doesn't match up to the actual selected value. Why is my osTicket pulling the wrong time values now? If I set the due date to 3:00pm, it will actually make it due at 11:00pm that day. So when myself, or another user edits the ticket (who may be in another time zone) we end up with an undesired due date on either end.

---

**Sanity Check**

I checked the following:
- Time create on a ticket (matched my timezone + the actual time)
- Time set on my preferences (GMT -8.0, California)
- I check the PHP install, also reported the proper time value.

---

**Version Information**

![about-this-install](https://cloud.githubusercontent.com/assets/1648492/3364223/de9b3706-fb1c-11e3-8ccf-a5d83c5950f7.png)

**Comment by Zuescho** [comment]
Hi, i have nearly the same problem so i would like to reopen this.
![snip-time](https://user-images.githubusercontent.com/13680959/27081990-54791c58-5043-11e7-84b3-d1f0261e5c1d.PNG)

All times around the System are the same and match up, only when creating a ticket the 12h format is still shown. i tried the fix but it only made times double appear.

here is a part of my _class.misc.php_ without making any changes.

```
$time = Misc::user2gmtime(mktime(0,0,0));
        ob_start();
        echo sprintf('<select name="%s" id="%s" style="display:inline-block;width:auto">',$name,$name);
        echo '<option value="" selected>'.__('Time').'</option>';
        for($i=23; $i>=0; $i--) {
            for ($minute=45; $minute>=0; $minute-=15) {
                $sel=($hr==$i && $min==$minute)?'selected="selected"':'';
                $_minute=str_pad($minute, 2, '0',STR_PAD_LEFT);
                $_hour=str_pad($i, 2, '0',STR_PAD_LEFT);
                $disp = Format::time($time + ($i*3600 + $minute*60 + 1), false);
                echo sprintf('<option value="%s:%s" %s>%s</option>',$_hour,$_minute,$sel,$disp);
            }
        }
```
