### ISSUE TITLE
Merging Tickets (Same user but different email accounts)

### ISSUE THREAD

**Issue by C4RLOCO** [osTicket/osTicket#1068]
Hi folks,
I have this problem: with the addition of Users and Organization in v1.9.2, we have a myriad of tickets that kind of belongs to the same users but they are spread in different accounts. Some of this accounts are result of email typos, etc.

I would like to clean up the user accounts a little bit and i could do this by merging all these tickets into the appropriate account. However, I can't find the way to effectively do this without having to go ticket by ticket and manually change the ownership.

Any thoughts?

**Comment by szemy** [comment]
+1 on virtual ticket. That looks like the best option as there are many issues with just merging (ticket properties, timeline ...)

**Comment by simonnzg** [comment]
I note this subject has been closed. However, the duplicate issue that prompted the closure has also been closed!!!

**Comment by szemy** [comment]
This one is still open: https://github.com/osTicket/osTicket-1.8/issues/1225

**Comment by simonnzg** [comment]
On 26/01/2015 12:47, szemy wrote:
> This one is still open: #1225
> <https://github.com/osTicket/osTicket-1.8/issues/1225>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/osTicket/osTicket-1.8/issues/1068#issuecomment-71455612>.
>


That's OK then!  ;-)

Simon

**Comment by richbodo** [comment]
This should be MERGED with [1225] (https://github.com/osTicket/osTicket-1.8/issues/1225) ;)
