### ISSUE TITLE
Response email doesn't work

### ISSUE THREAD

**Issue by multiaki** [osTicket/osTicket#1079]
OSticket 19.2.

We use Google groups to send an email to our help@support.domain.com. Then help@support.domain.com uses pipe.php to open a ticket. Recently I realized that auto-reponse emails don't work. 

I get "flags: Unexpected data received in API request" error in the log. 
Any help is appreciated. 
Thanks

here is email header:
Return-path: <help+bncBCEKHLNYXAERBRPJZSOQKGQERLBKMGA@domain.com>
Envelope-to: subdomain@support.domain.com
Delivery-date: Tue, 01 Jul 2014 18:23:03 -0400
Received: from mail-ie0-f200.google.com ([209.85.223.200]:40975)
    by jasmine.supportedns.com with esmtps (TLSv1:RC4-SHA:128)
    (Exim 4.82)
    (envelope-from <help+bncBCEKHLNYXAERBRPJZSOQKGQERLBKMGA@domain.com>)
    id 1X26S5-004Oi9-NT
    for subdomain@support.domain.com; Tue, 01 Jul 2014 18:23:03 -0400
Received: by mail-ie0-f200.google.com with SMTP id tr6sf63761873ieb.11
    for subdomain@support.domain.com; Tue, 01 Jul 2014 15:23:01 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
    d=1e100.net; s=20130820;
    h=x-gm-message-state:user-agent:date:subject:from:to:message-id
    :thread-topic:mime-version:x-original-sender
    :x-original-authentication-results:precedence:mailing-list:list-id
    :list-post:list-help:list-archive:list-unsubscribe:content-type;
    bh=l/Rol+7itq+g13kUkZUX408Ny1Hx1sxWITJqm5FT7GU=;
    b=l6neY6kuPTlEMsd6KdFsXXvbrT7fJb7dEH1K9grsZsJjSVHd6v4t1+7AnRlOqo8YLs
    QGC7NnARMZYtSN47dVtAAHSHSCmxKTaV8VQJ8ymcf5agVp4vROb0tveRnIuSvXFnLQj3
    3C36hXQqePi0DCKzYhPZwIh2negPMFYscnMWxvI70sToq9zn8oJO4cpMmKxS2E0WrMoH
    r74tKREqg3j1OS2lha43TGAmsOqLWZsOdAzEt39aDSMuMZN2SUDnSI80JH9iS4TGbyh7
    zTYI2f3t2UFtt65bXejbr3nQPf6fgniiHvO1g64pDKTP4xKfv9PGIOHiwWkptbNqYVDj
    +qYg==
X-Gm-Message-State: ALoCoQnV6iF5ilzPRED8jW9kcKWssWwQ3bk8iLq6SlN8SzY/F1Z1xRGp19tIvGZLVNofHRJKhSc/
X-Received: by 10.182.120.129 with SMTP id lc1mr25638795obb.21.1404253381322;
    Tue, 01 Jul 2014 15:23:01 -0700 (PDT)
X-BeenThere: help@domain.com
Received: by 10.140.84.239 with SMTP id l102ls2181711qgd.81.gmail; Tue, 01 Jul
    2014 15:23:01 -0700 (PDT)
X-Received: by 10.140.46.70 with SMTP id j64mr55686695qga.27.1404253381191;
    Tue, 01 Jul 2014 15:23:01 -0700 (PDT)
Received: from mail-qg0-f48.google.com (mail-qg0-f48.google.com [209.85.192.48])
    by mx.google.com with ESMTPS id w3si31050258qas.67.2014.07.01.15.23.00
    for help@domain.com
    (version=TLSv1 cipher=ECDHE-RSA-RC4-SHA bits=128/128);
    Tue, 01 Jul 2014 15:23:01 -0700 (PDT)
Received-SPF: neutral (google.com: 209.85.192.48 is neither permitted nor denied by domain of aki@customer.com) client-ip=209.85.192.48;
Received: by mail-qg0-f48.google.com with SMTP id q108so4069538qgd.35
    for help@domain.com; Tue, 01 Jul 2014 15:23:00 -0700 (PDT)
X-Received: by 11.1111.11.11 with SMTP id 1231231231231.69.1404253380887;
    Tue, 01 Jul 2014 15:23:00 -0700 (PDT)
Received: from [111.111.111.111](internetprovider,net. [11.11.111.1111])
    by mx.google.com with ESMTPSA id x1sm39480969qaj.11.11111.111.1111.11111.1111.1111
    for help@domain.com
    (version=TLSv1 cipher=RC4-SHA bits=128/128);
    Tue, 01 Jul 2014 15:22:59 -0700 (PDT)
User-Agent: Microsoft-MacOutlook/14.4.3.140616
Date: Tue, 01 Jul 2014 18:22:49 -0400
Subject: Test
From: Aki aki@customer.com
To: subdomain training support help@domain.com
Message-ID: <CFD8ACF9.2DE18%aki@customer.com>
Thread-Topic: Test
Mime-version: 1.0
X-Original-Sender: aki@customer.com
X-Original-Authentication-Results: mx.google.com; spf=neutral
    (google.com: 209.85.192.48 is neither permitted nor denied by domain of
    aki@customer.com) smtp.mail=aki@customer.com
Precedence: list
Mailing-list: list help@domain.com; contact help+owners@domain.com
List-ID: <help.domain.com>
X-Google-Group-Id: 123345454566
List-Post: http://groups.google.com/a/domain.com/group/help/post, mailto:help@domain.com
List-Help: http://support.google.com/a/domain.com/bin/topic.py?topic=25838, mailto:help+help@domain.com
List-Archive: http://groups.google.com/a/domain.com/group/help/
List-Unsubscribe: http://groups.google.com/a/domain.com/group/help/subscribe,
    mailto:googlegroups-manage+123345454566+unsubscribe@googlegroups.com
Content-type: multipart/alternative;
    boundary="B_3487083778_2074710"
X-Spam-Status: No, score=0.0
X-Spam-Score: 0
X-Spam-Bar: /
X-Ham-Report: Spam detection software, running on the system "jasmine.supportedns.com", has
    identified this incoming email as possible spam. The original message
    has been attached to this so you can view it (if it isn't spam) or label
    similar future email. If you have any questions, see
    root\@localhost for details.
    Content preview: Test Test [...]
    Content analysis details: (0.0 points, 5.0 required)
    pts rule name description
    ---- ---------------------- --------------------------------------------------
    0.0 HTML_MESSAGE BODY: HTML included in message
X-Spam-Flag: NO
HTMLText   <- <<- ->   []
Test

**Comment by Reyncor** [comment]
In my case, we use distribution lists to cut down the costs of an Office 360 / Google Apps account. Our Registrar doesn't provide email forwarding, not sure if it would count as a distribution list. Will try something else, like setting up gmail rules to forward emails sent to specific people, that has typically been spotty in my experience.

**Comment by Rahul-tyagi007** [comment]
@ greezybacon need some help regarding os ticket pls help me

**Comment by ntozier** [comment]
@Rahul-tyagi007 
Please utilize the support channels:
http://osticket.com/forum
-or-
http://osticket.com/commercial-support
