### ISSUE TITLE
User and organizations

### ISSUE THREAD

**Issue by cervedgroup** [osTicket/osTicket#1081]
Is possible to deny access to "user and organization feature" to staff memebers/groups ?

**Comment by cjtop** [comment]
I have a use case related to this enhancement request. 

We currently work with sub contractors that should only be able to see tickets they are assigned. We don't want them to be able to view our entire client list or organizations. If they are assigned a ticket then it is okay for them to see the contact details of the contacts and organization on only those particular tickets. It would be okay if they could only see the contact details of the user and not the organization too, but either option works for us.

Currently we have to keep sub contractors out of the system and double entry anything they are working on. This creates extra work for the account managers and a lot of stuff falls through the cracks this way.
