### ISSUE TITLE
OSTicket 1.9.2 No rich text on new ticket

### ISSUE THREAD

**Issue by bernardflach** [osTicket/osTicket#1095]
Just installed a fresh OSTicket 1.9.2. 
on the forum at OSticket.com is beeing said that when creating a new ticket (and when giving a response) the textfield is rich-text and showing a toolbar. 

But theres no toolbar to be seen.

Admin panel -> Settings -> Tickets -> Enable HTML Ticket Thread  is set to on.
Tried Webbrowsers : Firefox and Safari

**Comment by kaniket** [comment]
It has to do with "eol" , if this global(?) is not defined, Mime is going to assume it is running on a windows os and define it as "\r\n", which on unix systems will create the double line breaks in the header. Just went through the mime.php file and took out all the \r's from the defining of $eol vars and it worked fine.  

FYI
windows uses "\r\n"
mac uses "\r"
linux uses "\n"

**Comment by ntozier** [comment]
@kaniket any reason why you wouldn't just alter your /include/ost-config.php and set:
define(MAIL_EOL, "\n");?

**Comment by kaniket** [comment]
that should work too. And maybe it is hassle free to just add it there rather than at mime.php. Thanks

**Comment by greezybacon** [comment]
> Mime is going to assume it is running on a windows os and define it as "\r\n"

@kaniket that's not completely correct. The default code will always use "\r\n" as it is the defined standard in rfc 822.
