### ISSUE TITLE
Clear staff on transfer to dept

### ISSUE THREAD

**Issue by bcv1** [osTicket/osTicket#1100]
It would be great to have the option to unassign staff on dept transfer. 

Currently, when a ticket is assigned to a staff member and at some later point they transfer to a dept, it remains assigned to them and in their 'Answered' queue. When transferring to another dept, is it possible to clear the 'assigned staff' field?

Not sure how to make the changes, but I'm assuming it would be in these two files: scp/tickets.php and /include/class.ticket.php

**Comment by adrianoprospero** [comment]
Any news about that?

**Comment by BernhardHutter** [comment]
Dear adrianoprospero,

I solved the "problem" by myself, I changed the code and take care of that specific change, whenever I install a new update of osTicket.

This is the howto, as I did it:

include/class.ticket.php
Line 753
            .', staff_id=0, isanswered=0 WHERE ticket_id='.db_input($this->getId());

**Comment by adrianoprospero** [comment]
Thank you BernhardHutter!
I created a workaround in the workflow to deal with this issue without
change the code: I created an user to stay with the "unassigned" issues.
Then when an user must transfer an already assigned ticket to another
department, he must assign it to this "Unassigned user", turn back in the
browser an then transfer the ticket to the other department. This
"unassigned user" could also be an figurative "administrator" of the
destination department.
After the transfer, the user that transferred the ticket isn't seeing it
anymore in his list.

Best regards,

Adriano Gonçalves
Em 15/07/2015 06:07, "BernhardHutter" <notifications@github.com> escreveu:

**Comment by Atriusftw** [comment]
@greezybacon What version is this feature targeted for?

**Comment by clo** [comment]
Is this feature request still pending?

**Comment by BernhardHutter** [comment]
Yes, still pending :(

**Comment by ipAnything** [comment]
@BernhardHutter 

Have you done this for 1.10rc3? Could you supply previous and post lines of code to identify where to place:

> 
include/class.ticket.php
Line 753
.', staff_id=0, isanswered=0 WHERE ticket_id='.db_input($this->getId());

This would also be usefully for Transfer to a different Team. Ideally the Agent is also unassigned if he is transferring it to a different Team.

Thank you

**Comment by ebozzi** [comment]
I sorted this out modifying ~/osticket/upload/include/class.ticket.php

if someone is interested:

### modified function transfer:
2002     function transfer(TransferForm $form, &$errors, $alert=true) {

### after the department was changed 
2017             $this->dept_id = $dept->getId();

### I added a line to relase the ticket:
2018             $this->unassign(); 



### here are the first 20 lines of the function
2002     function transfer(TransferForm $form, &$errors, $alert=true) {
2003         global $thisstaff, $cfg;
2004
2005         // Check if staff can do the transfer
2006         if (!$this->checkStaffPerm($thisstaff, Ticket::PERM_TRANSFER))
2007             return false;
2008
2009         $cdept = $this->getDept(); // Current department
2010         $dept = $form->getDept(); // Target department
2011         if (!$dept || !($dept instanceof Dept))
2012             $errors['dept'] = __('Department selection required');
2013         elseif ($dept->getid() == $this->getDeptId())
2014             $errors['dept'] = sprintf(
2015                     __('%s already in the department'), __('Ticket'));
2016         else {
2017             $this->dept_id = $dept->getId();
2018             $this->unassign(); //to release the ticket after department is changed

**Comment by akash65** [comment]
can anyone tell me why i'm not getting transfer option once the ticket is created from agent?

**Comment by ntozier** [comment]
@akash65 your response does not appear to be on topic for this issue report unless you implemented a third partys code from this thread.  Otherwise I expect that it is because your account does not have "transfer" privileges. I would invite you to seek your support experience at the support forums.  http://osticket.com/forums
