### ISSUE TITLE
change system language after installation

### ISSUE THREAD

**Issue by nancykyo** [osTicket/osTicket#1102]
can i change system language after installation?
after I download the  Language Packs, I could find where to change the system language.
googling about it, then I finally know that I must install the  Language Packs before installation finished.

can it work like the plugin?

**Comment by c0mputerjunky** [comment]
Okay... but how to install it with the language pack at the beginning? Where i have to put the file in?

**Comment by andrelindner** [comment]
> can i change system language after installation?
> after I download the Language Packs, I could find where to change the system language.
> googling about it, then I finally know that I must install the Language Packs before installation finished.
> 
> can it work like the plugin?

still an issue?
