### ISSUE TITLE
Enable Post Reply to Collaborators only

### ISSUE THREAD

**Issue by kordianbruck** [osTicket/osTicket#1117]
Would be good to be able to reply to collaborators only. This can be done by adding all collaborators to the TO field or not hiding the colls. when selecting "do not reply"

**Comment by harrisyn** [comment]
This feature is very very very much needed, I made a comment in the "thread editing" feature and wasnt sure I was clear in what I attempted to describe and was also worried no one else shared the same concern and need. but this spells it out completely.

any hope of this getting done soon?

**Comment by greezybacon** [comment]
@harrisyn there is a pull request out, #1723 (tasks), we hope to have merged this week, which is the last milestone for the next major release. Tasks allows forking a ticket thread into multiple threads, each with separate assignees, descriptions, due dates, and collaborator lists. The visibility of the task threads can be controlled among agents and is never shared with the end user owner of the ticket.

We feel this is a more general answer to the need for multiple collaborator lists.

**Comment by harrisyn** [comment]
Sounds great. Will be waiting to test and provide feedback.  😊

**Comment by harrisyn** [comment]
Hi @greezybacon did this get merged yet? Can't wait to test this out 😊

**Comment by greezybacon** [comment]
@harrisyn no not yet. Hopefully it will happen late this week
