### ISSUE TITLE
Email reply by staff to alert gets posted as "Internal Note" since v1.9.2 ?

### ISSUE THREAD

**Issue by raj2ras** [osTicket/osTicket#1120]
Email reply by assigned staff to a ticket alert gets posted as "Internal Note" since v1.9.2 ? In previous versions its was posted as a reply to the ticket.

Is there any way to post the staff's email reply as a "proper reply" to the ticket  rather than as a internal note? This causes problems for mobile staff who reply from smartphones and expect that the client sees them.

Also posted here - http://osticket.com/forum/discussion/78348/email-reply-by-staff-to-alert-gets-posted-as-internal-note-since-v1-9-2

**Comment by pedro-nonfree** [comment]
I am surprised that such a nice feature (reply by email) is disabled to avoid concurrent responses from different agents.

I used request-tracker for several years in an organization with this plain-simple configuration of replying by email; and we got responses from different agents, in our case, as the different responses enrich the problem, that's fine. Also, the requestor, perceives that is getting help, time, care and love. Of course, we are talking about volunteers in a nonprofit organization.

I can understand that in a corporate environment with thousands of agents that select templated responses this is not OK.

But really we need to change core files to be able to do that? Why this is not a configurable option. Anyway, can you point or address what change is needed?
