### ISSUE TITLE
When ticket is created from email with collaborators in CC and/or TO fields, osTicket does not added that collaborators

### ISSUE THREAD

**Issue by spalekg** [osTicket/osTicket#1130]
When I try to create new ticket from email but with already defined collaborators in CC and/or TO, there is no any collaborator added when I am opening ticket in staff panel.

Adding collaborators works fine if ticket owner reply to created ticket message with added CC and/or TO collaborators. Also it works when you add collaborators from web (after ticket is created).

I am not sure is it worked before or not but it will be nice if osTicket can add all collaborators in create ticket phase (from email).

Thanks,
Aleksandar

**Comment by mckaygerhard** [comment]
**a year now** and **still not** implemented, **i think this its a bug due "missing from form"**

**Comment by pradeep1987oct22** [comment]
This feature will be useful for those clients who want to inform their team (collaborators) when a new ticket is raised & with status

**Comment by mckaygerhard** [comment]
howmany people said that this feature are good. but does not receive a good feedback
