### ISSUE TITLE
Performance tuning

### ISSUE THREAD

**Issue by cervedgroup** [osTicket/osTicket#1138]
1.9.2 around 5000 tickets in db (350Mb total db size) , 20 operators (server 4 Gb Ram 2 processors win2008r2X64), processor time always below 50% and used ram  around 2 Gb (we have HEIDISQL instance)

Sometimes the scp interface is very slow and/or opening tickets or "open queue" gets around 5-6 seconds to complete; 
since we are planning to use the osticket for many other "support areas" of our company (maybe the tickets and the operator will double), i'm asking information about table optimization of db:
http://www.xaprb.com/blog/2010/02/07/how-often-should-you-use-optimize-table/
is usefull to optimize table or not ? now we haven't the attachment plugin, so all the attachment is in the db, will be usefull to install that pluging ? can we install it now without loosing the attachment that is on the db ?

thank you!

**Comment by kest874** [comment]
> Add to the mix that we also support MariaDB, and we're beginning to come to the point to where we're having to pick a single setup and design for it exclusively. Currently that is MariaDB 5.6

I believe you mean MariaDB 5.5, and PHP 5.6?
