### ISSUE TITLE
Can't add a video to my landing page

### ISSUE THREAD

**Issue by gcozzens** [osTicket/osTicket#1141]
I want to add a video on my osTicket landing page and it doesn't seem to work regardless of what I try. Is there a process/secret to getting this to work?

I appreciate your help
Glenn Cozzens

**Comment by protich** [comment]
@greezybacon - Configuration option for TextareaField makes sense to me. I'm thinking a multiselect option when html is allowed to select trusted sites for embed & iframe from a custom list.  We can ship the "Trusted Sites" list with current sites - and user will be able to Select All (default) or whitelist specific sites for a specific field.

**Comment by gcozzens** [comment]
As long as I can embed an MP4 video hosted on Amazon S3 I will be happy.

**Comment by nobe-vs** [comment]
Hu Guys,

i´ve the same issue. Videos always disappear after click at the "save" button. I use V1.9.12, class.format.php, line 245 ha no such expression. So where i have to search for that?
Thanks in advance!

**Comment by tinboye** [comment]
I have tried this and updated the file and added drive.google

when I submit the form i get this error now
ERR_BLOCKED_BY_XSS_AUDITOR  but then i refresh the page and it does show its saved, but is this my browser giving this error or something else in the script?

**Comment by JediKev** [comment]
@tinboye

What version of osTicket are you using?

Cheers.

**Comment by tinboye** [comment]
1.10.4. I see now that it was chrome that gave the error.  

This page isn’t working
Chrome detected unusual code on this page and blocked it to protect your personal information (for example, passwords, phone numbers and credit cards).
Try visiting the site's homepage.
ERR_BLOCKED_BY_XSS_AUDITOR

**Comment by ntozier** [comment]
Version of Chrome?

https://stackoverflow.com/questions/43249998/chrome-err-blocked-by-xss-auditor-details

**Comment by tinboye** [comment]
Always run the latest versions. Does it on my phones chrome browser as well.

**Comment by JediKev** [comment]
@tinboye 

Try removing the headers added in this pull:
https://github.com/osTicket/osTicket/pull/4266

Cheers.
