### ISSUE TITLE
Feature Request: Allow Only E-Mail IDs with Specific Domains

### ISSUE THREAD

**Issue by iGattreX** [osTicket/osTicket#1143]
While opening a new ticket (or) while registering a new user,allow only e-mail ids with specific domains for registration.

For example: user@example.org should be configured to be allowed. E-mail addresses belonging to other domains such as xyz@sample.net should be denied for registratiion / to create tickets.

**Comment by cengbrecht** [comment]
I would like to see registered as a tick in the users profile, and have the rejection of a ticket send a reply that the ticket was rejected, and give you the option to choose a custom canned response while rejecting the ticket.
