### ISSUE TITLE
bad query in class.config.php, line 1206 (osTicket 1.9.3)

### ISSUE THREAD

**Issue by csiefer** [osTicket/osTicket#1145]
bad query in class.config.php, line 1206 (osTicket 1.9.3)

ost-session:
    $sql='SELECT `ostversion` FROM '.TABLE_PREFIX.'config '
            .'WHERE id=1';

```
No column 'ostversion'
```

Cannot find a 1.9 section, so posting to 1.8, sorry.

Regards, Chris

**Comment by AnonTester** [comment]
this is still present in v1.15.1 and current development branch and it's generating SQL errors in logs, the fix is at the end of include/class.config.php :
``
        $sql='SHOW columns FROM '.TABLE_PREFIX.'config '
            .'WHERE Field="ostversion"';
``

**Comment by JediKev** [comment]
@AnonTester 

Below is the pull request that addresses this issue (it will be merged into the next releases):
- https://github.com/osTicket/osTicket/pull/5926

Cheers.
