### ISSUE TITLE
1.9.3 max file size compared to 1.8

### ISSUE THREAD

**Issue by mrabino1** [osTicket/osTicket#1150]
In Admin Panel >> Settings >> Tickets >> Maximum File Size
in 1.8 it allows up to 50mb with standard increments... with 1.9.3 it appears the max has now been reduced to 2mb?

**Comment by Olegansoft** [comment]
Create a line in php.ini (create php.ini in osTicket folder is there's no access to webserver php.ini):
`upload_max_filesize = 32M`
No webserver restart is necessary.

**Comment by ntozier** [comment]
Ummm... All modern web servers require a restart when PHP directives are changed.
