### ISSUE TITLE
1.9.3 - Admin Page >> Settings >> Company >> Company Name - Update error

### ISSUE THREAD

**Issue by mrabino1** [osTicket/osTicket#1157]
On the Admin Page >> Settings >> Company >> Company Name... 

I modify the box.. hit submit.. I get the nice green box saying the content has been updated.. but then refresh, and the data was not actually updated... e.g. cannot change the company name after it has been initially set..

**Comment by mbarkichadi** [comment]
To Close this Issue i have an update the table is called ost_form_entry_values not ost_form_entry
id23: Company Name	
id24: Website
id25: Phone
id26: Adress
and everything is ok
