### ISSUE TITLE
SLA to consider non-24x7 timeframes (e.g. weekends) [feature request]

### ISSUE THREAD

**Issue by kristianrl** [osTicket/osTicket#1168]
I would like to see a feature for more customized SLA's.

The helpdesk function I'm running is not 24x7 (it's more like 9 hours 5 days a week) - so it is annoying that the system informs that tickets become overdue if they arrive during the weekend.
Right now, our settings is that the SLA is 24 hours, but the ideal solution would be to specify the helpdesk's opening hours, and then set the SLA to be 8 hours during opening hours.

**Comment by markus4000** [comment]
1+

**Comment by LeDistordu** [comment]
+1

**Comment by theking81** [comment]
+1

**Comment by cervedgroup** [comment]
:+1:  it could be very usefull to set working hours and sla coputed only during the working hours

**Comment by gaursh** [comment]
+1

**Comment by gaursh** [comment]
I requested for the same.

SLA custimization should have feature 
1> to set Client working hrs 
2> Exclude any Client Holdidays
3> Exclude Weekends(Saturday Sunday)

All tickets marked with SLA Plan should follow the time duration set.

Thanks

**Comment by gaursh** [comment]
#4969

**Comment by protich** [comment]
We now have a PR for the feature - #4984
