### ISSUE TITLE
How to show Full Name in User Dir and Staff Dir?

### ISSUE THREAD

**Issue by jhonny9696** [osTicket/osTicket#1169]
How to show Full Name in User Dir and Staff Dir?

As well as I also need to some Custom fields of Contact Information in User Directory.

I hope i found a BUG with sorting the Status in User Directory.

**Comment by dim09** [comment]
поле "от" не отображается полное имя а только точки, подскажите как исправить (And column "from" doesn't display a full name)

**Comment by dim09** [comment]
how to fix it?
![1](https://cloud.githubusercontent.com/assets/3490081/21996708/9796d06e-dc3c-11e6-892b-1040ef3d3be8.jpg)

**Comment by ntozier** [comment]
@dim09 
Google translate:
"From" field does not display the full name but only a point, tell me how to fix

I have no idea what you are trying to ask.  Probably doesn't help that your screen shot shows absolutely nothing and I have no idea where you are talking about.  Not have you indicated the version that you are running, etc.  Please help us to help you by providing a better description of how to reproduce your issue and where it occurs.  Also switch to the English language pack and see if the problem persists.

**Comment by dim09** [comment]
in the column "from" instead of the name on the application page displayed points

**Comment by ntozier** [comment]
There is no "Application" page in osTicket.
Well unless you install a plugin that uses the Application menu but there is no page associated with that menu option.  So I repeat: "I have no idea what you are trying to ask. Probably doesn't help that your screen shot shows absolutely nothing and I have no idea where you are talking about. Not have you indicated the version that you are running, etc. Please help us to help you by providing a better description of how to reproduce your issue and where it occurs. Also switch to the English language pack and see if the problem persists."

**Comment by dim09** [comment]
1.9.12 вервия

**Comment by dim09** [comment]
no name and point

**Comment by ntozier** [comment]
see previous comment.
