### ISSUE TITLE
Feature Request:  Allow attachments associated with a ticket to be sent along with the New Ticket Alert template email

### ISSUE THREAD

**Issue by motodave452** [osTicket/osTicket#1170]
If a user adds attachments to a ticket while opening a new one, allow these attachments to be added to the New Ticket Alert template email as an attribute so that the attachments are sent with the email.  Frequently at our organization certain issues arise that need to get passed on to other branches/departments/etc.  So when someone opens a ticket for an issue it would be nice to have the attachments included in the new ticket alert email so that all we have to do is forward that new ticket alert email to the proper parties to alert them of the issue.  Then this new ticket alert email would contain all of the relevant information needed to help the other party understand and diagnose what is actually occurring.  I feel that this would be a nice enhancement.

Thank you for your time!

**Comment by grantdowco** [comment]
This was recently closed, was the feature added?  I would like to be able to do this but can't see how - currently using v1.10

**Comment by artosx** [comment]
Following simple patch adds requested feature to OsTicket:
```
diff --git a/include/class.ticket.php b/include/class.ticket.php
index 6057511..23449ad 100644
--- a/include/class.ticket.php
+++ b/include/class.ticket.php
@@ -3631,9 +3631,6 @@ implements RestrictedAccess, Threadable {
             else
                 $signature='';
 
-            $attachments = ($cfg->emailAttachments() && $response)
-                ? $response->getAttachments() : array();
-
             $msg = $ticket->replaceVars($msg->asArray(),
                 array(
                     'message'   => $message,
@@ -3645,8 +3642,13 @@ implements RestrictedAccess, Threadable {
             );
             $message = $ticket->getLastMessage();
             $options = array(
                 'thread' => $message ?: $ticket->getThread(),
             );
+			
+			if($cfg->emailAttachments()) 
+				$attachments = $response ?
+					$response->getAttachments() : $message->getAttachments();
+					
             $email->send($ticket->getOwner(), $msg['subj'], $msg['body'], $attachments,
                 $options);
         }
```
