### ISSUE TITLE
Alow operator to edit his message. Alow admin to edit all messages.

### ISSUE THREAD

**Issue by PeopleInside** [osTicket/osTicket#1173]
Alow operator to edit user messages or himself operator message.

Alow admin to edit all messages in the ticket.

Also in the version 1.9

**Comment by greezybacon** [comment]
This is implemented in #1882. Any feedback is welcomed

**Comment by PeopleInside** [comment]
Ok thanks how to apply? I had to wait nex release or what? Thanks.

**Comment by greezybacon** [comment]
@PeopleInside you can download the preview release from the *Releases* page and check out the new features, including thread edits

**Comment by PeopleInside** [comment]
Thanks @greezybacon
