### ISSUE TITLE
User Login fails when ad username is all numeric

### ISSUE THREAD

**Issue by pfurches** [osTicket/osTicket#1176]
This issue came up with staff users whose ad samaccountname was all numbers.  Issue #464 addressed this and the workaround was fine.

The problem is that this will not fix user logins.  If the ad samaccoutname is all numeric, even the email address will not allow them to authenticate.  I have verified with OST 1.92 and 1.93.  Download 1.94 Preview and will test in AM.

I have verified that the ldap plugin allows client authentication.  I even removed the staff mod to verify that this mod did not break the client login.

If I create an AD user account that begins with a letter instead of a number, client login works for both staff and users.  But if the username begins with a number it fails with Access Denied.  The mod #464 fixes staff with all numeric usernames.  Any idea where to look to make a similar mod for client users?

Any help appreciated.  Other than this issue 1.9x has been awesome.

**Comment by greezybacon** [comment]
Maybe y'all could try #2393

**Comment by pfurches** [comment]
I can confirm that this is working with numeric usernames now in 1.10 RC2.  Thanks greezybacon!

**Comment by AlgorithMan-de** [comment]
I still have this issue with agent-usernames that are given manually (not LDAP) in osTicket 1.10.4
