### ISSUE TITLE
Encoding problems when replying by e-mail

### ISSUE THREAD

**Issue by cmalbertschw** [osTicket/osTicket#1177]
Hello,

After upgrading to 1.9.3, we experience encoding problems when somebody replies to a ticket using Outlook and when the text contains special characters like german umlauts (e. g. ü, ä, ö). 

Our enviornment:
Osticket 1.9.3, running on Ubuntu 14.04. PHP: 5.5.9-1ubuntu4.3, Server: Apache.
Microsoft Exchange Server 2013.
E-Mail Client: Microsoft Outlook 2013.

Steps to reproduce:
1) Create a ticket using the web-interface.
2) Write a reply to the person that created a ticket (in this case, yourself) using the web-interface. 
3) Answer to the mail notification you have received and use german umlauts for example.
4) Once Osticket fetches the mail from its mail account, you will see encoding problems in the web interface and the mail notification following that reply from step 3. 

Screenshot:
![image](https://cloud.githubusercontent.com/assets/3584201/4027430/98c6f682-2c2e-11e4-80ee-2493d2aac83d.png)

However, there are no problems when we use the webinterface to reply. (the umlauts will display fine there and in the e-mail).

We didn't experience this issue in Osticket 1.8 and didn't change our Outlook configuration after upgrading, so we believe it's a bug in Osticket itself.

**Comment by guidokuehler** [comment]
Have you found a Solution for your Problem?

We have the Same Problem 

osTicket-Version	v1.9.9-1-gbe2f138 (be2f138)
Server-Software	nginx/1.8.0
MySQL-Version	5.5.44
PHP-Version	5.6.4-4ubuntu6.2

From the Reply comes only the followed in the Ticket-System.

<html xmlns="http://www.w3.org/TR/REC

Thats all.

The Email comes also from outlook via Exchange!

Best Regards
Guido

**Comment by guidokuehler** [comment]
Our Body:


<html xmlns="http://www.w3.org/TR/REC-html40"><head><style></style></head><body lang="DE-AT"><div class="WordSection1"><p class="MsoNormal"><span style="font-size:10.0pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;color:#1F497D">K&ouml;nnen wir die PC&acute;s am Abend abschalten oder nicht??</span></p><p class="MsoNormal"><span style="font-size:10.0pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;color:#1F497D">&nbsp;</span></p><div><p class="MsoNormal"><span lang="DE" style="font-size:10.0pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;color:#1F497D">Mit freundlichen Gr&uuml;&szlig;en</span></p><p class="MsoNormal"><span lang="DE" style="font-size:10.0pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;color:#1F497D">&nbsp;</span></p><p class="MsoNormal"><b><span lang="DE" style="font-size:10.0pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;color:purple">Karl Pechacek</span></b><span lang="DE" style="color:#1F497D"></span></p><p class="MsoNormal"><i><span lang="DE" style="color:purple">Buchhaltung</span></i><i><span style="font-size:10.0pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;color:purple"></span></i></p><p class="MsoNormal"><span style="font-size:9.0pt;color:#1F497D">&nbsp;</span></p><p class="MsoNormal"><span lang="DE" style="font-size:9.0pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;color:#1F497D">&nbsp;</span></p><p class="MsoNormal"><span lang="DE" style="font-size:9.0pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;color:#1F497D">STEINEL Austria GmbH</span><span style="color:#1F497D"></span></p><p class="MsoNormal"><span lang="DE" style="font-size:9.0pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;color:#1F497D">Hirschstettner Stra&szlig;e 19/A/2/2</span><span style="color:#1F497D"></span></p><p class="MsoNormal"><span lang="DE" style="font-size:9.0pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;color:#1F497D">A-1220 WIEN</span><span style="color:#1F497D"></span></p><p class="MsoNormal"><span lang="DE" style="font-size:9.0pt;color:#1F497D">&nbsp;</span><span lang="DE" style="font-size:9.0pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;color:#1F497D"></span></p><p class="MsoNormal"><span lang="DE" style="font-size:9.0pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;color:#1F497D">Tel.: +43 1 202 34 70-21</span></p><p class="MsoNormal"><span lang="DE" style="font-size:9.0pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;color:#1F497D">Fax: +43 1 202 01 89-3</span></p><p class="MsoNormal"><span lang="DE" style="font-size:9.0pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;color:#1F497D">E-Mail&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; :&nbsp;&nbsp; <a href="mailto:kpechacek@steinel.at" title="blocked::mailto:kpechacek@imueller.at" target="_blank">kpechacek@steinel.at</a></span><span style="color:#1F497D"></span></p><p class="MsoNormal"><span lang="DE" style="font-size:9.0pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;color:black">Homepage:&nbsp; </span><span lang="EN-GB" style="font-size:9.0pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;color:black"><a href="http://www.steinel.at" title="blocked::http://www.imueller.at/" target="_blank"><span lang="DE">www.steinel.at</span></a></span><span lang="DE" style="font-size:9.0pt;color:#1F497D"></span></p><p class="MsoNormal"><span lang="DE" style="font-size:9.0pt;color:#1F497D">&nbsp;</span></p><p class="MsoNormal"><span lang="DE" style="font-size:9.0pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;color:black">----------------------------------------------------</span><span lang="DE" style="font-size:9.0pt;color:#1F497D"></span></p><p class="MsoNormal"><span lang="DE" style="font-size:9.0pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;color:black">Gesch&auml;ftsf&uuml;hrer: Otmar P&Uuml;RCHER</span><span lang="DE" style="color:#1F497D"></span></p><p class="MsoNormal"><span lang="DE" style="font-size:9.0pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;color:black">Gerichtsstand:&nbsp;&nbsp;&nbsp;&nbsp; HG Wien</span><span style="color:#1F497D"></span></p><p class="MsoNormal"><span lang="DE" style="font-size:9.0pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;color:black">Firmenbuch:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;FN 229046 h</span><span lang="DE" style="font-size:9.0pt;color:#1F497D"></span></p><p class="MsoNormal"><span lang="DE" style="font-size:9.0pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;color:black">UID-Nr.:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ATU56194969</span><span lang="DE" style="font-size:9.0pt;color:#1F497D"></span></p><p class="MsoNormal"><span lang="DE" style="font-size:9.0pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;color:black">----------------------------------------------------</span><span lang="DE" style="font-size:9.0pt;color:#1F497D"></span></p><p class="MsoNormal"><span lang="DE" style="color:#1F497D">&nbsp;</span></p><p class="MsoNormal"><span lang="DE" style="font-size:7.5pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;color:black">Diese Nachricht und allf&auml;llige angeh&auml;ngte Dokumente sind vertraulich und nur f&uuml;r den/die Adressaten bestimmt. Sollten Sie nicht der beabsichtigte Adressat sein, ist jede Offenlegung, Weiterleitung oder sonstige Verwendung dieser Information nicht gestattet. In diesem Fall bitten wir, den Absender zu verst&auml;ndigen und die Information zu vernichten. F&uuml;r &Uuml;bermittlungsfehler oder sonstige Irrt&uuml;mer bei &Uuml;bermittlung besteht keine Haftung.</span><span lang="DE" style="color:blue"></span></p><p class="MsoNormal"><span lang="DE" style="font-size:7.5pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;color:#999999"><br></span><span lang="EN-GB" style="font-size:7.5pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;color:black">This message and any attached files are confidential and intended solely for the addressee(s). Any publication, transmission or other use of the information by a person or entity other than the intended addressee is prohibited. If you receive this in error please contact the sender and delete the material. The sender does not accept liability for any errors or omissions as a result of the transmission. </span><span lang="EN-GB" style="font-size:7.5pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;color:#999999"></span></p></div><p class="MsoNormal"><span style="font-size:10.0pt;font-family:&quot;Arial&quot;,&quot;sans-serif&quot;;color:#1F497D">&nbsp;</span></p><p class="MsoNormal"><b><span lang="DE" style="font-size:10.0pt;font-family:&quot;Tahoma&quot;,&quot;sans-serif&quot;">Von:</span></b><span lang="DE" style="font-size:10.0pt;font-family:&quot;Tahoma&quot;,&quot;sans-serif&quot;"> ITP - Support [mailto:support@it-power.biz] <br><b>Gesendet:</b> Donnerstag, 23. Juli 2015 15:06<br><b>An:</b> Pechacek Karl<br><b>Betreff:</b> Erweiterung - Shutdown-Skripten [#TSID0002038]</span></p><p class="MsoNormal">&nbsp;</p><div><p class="MsoNormal" style="margin-bottom:12.0pt">-</p></div><p class="MsoNormal" style="margin-bottom:12.0pt">Sg.Kunde! <br><br>Ein Support-Mitarbeiter hat in Ihrem Namen das nachfolgende Ticket er&ouml;ffnet: <br><br></p><table class="MsoNormalTable" border="0" cellpadding="0"><tr><td style="padding:1.2pt 1.2pt 1.2pt 1.2pt"><p class="MsoNormal"><strong>Ticketnummer</strong> </p></td><td style="padding:1.2pt 1.2pt 1.2pt 1.2pt"><p class="MsoNormal"><a href="%25%7Bticket.staff_link%7D" target="_blank">#TSID0002038</a> </p></td></tr><tr><td style="padding:1.2pt 1.2pt 1.2pt 1.2pt"><p class="MsoNormal"><strong>Erstellt am</strong> </p></td><td style="padding:1.2pt 1.2pt 1.2pt 1.2pt"><p class="MsoNormal">23.07.2015 15:06 </p></td></tr><tr><td style="padding:1.2pt 1.2pt 1.2pt 1.2pt"><p class="MsoNormal"><strong>Priorit&auml;t</strong> </p></td><td style="padding:1.2pt 1.2pt 1.2pt 1.2pt"><p class="MsoNormal">Normal </p></td></tr><tr><td style="padding:1.2pt 1.2pt 1.2pt 1.2pt"><p class="MsoNormal"><strong>Hilfethema</strong> </p></td><td style="padding:1.2pt 1.2pt 1.2pt 1.2pt"><p class="MsoNormal">Firmenkunden </p></td></tr><tr><td style="padding:1.2pt 1.2pt 1.2pt 1.2pt"><p class="MsoNormal"><strong>Abteilung</strong> </p></td><td style="padding:1.2pt 1.2pt 1.2pt 1.2pt"><p class="MsoNormal">Firmenkunden-Support (DE) </p></td></tr><tr><td style="padding:1.2pt 1.2pt 1.2pt 1.2pt"><p class="MsoNormal"><strong>Bezeichnung</strong> </p></td><td style="padding:1.2pt 1.2pt 1.2pt 1.2pt"><p class="MsoNormal">Erweiterung - Shutdown-Skripten </p></td></tr></table><p class="MsoNormal" style="margin-bottom:12.0pt"><br><br><strong>Nachricht</strong> <br><br>Die Infrastruktur von Steinel muss wie folgt erweitert werden.<br><br>Implementierung von Shutdown-Skripten im Active-Directory und Filesystem.<br><br>Shutdown-Skripten werden dazu genutzt um auf zugewiesenen System beim Herunterfahren automatische Routinen bzw. &Auml;nderungen vorzunehmen.<br><br>Im Anlassfall handelt es sich aktuell&nbsp;um das Windows-Update von Microsoft welches einen Silent-Upgrader auf Windows 10 enth&auml;lt.<br><br>Die Erweiterung der Infrastruktur wurde soeben abgeschlossen.<br>Die Erweiterung wird dann sp&auml;testens morgen den 24.07.2015 auf den Clients greifen.<br><br><br>Sollte es notwendig sein, wird sich ein Support-Mitarbeiter so schnell wie m&ouml;glich mit Ihnen in Verbindung setzen. Sie k&ouml;nnen <a href="%25%7Brecipient.ticket_link%7D" target="_blank">den Verlauf Ihres Tickets online abrufen</a>. </p><div><p class="MsoNormal" style="margin-bottom:12.0pt"><span style="color:#7F7F7F">Ihr ITP - Business IT Power - Helpdesk Team, <br><br>Support&nbsp;1 Level -&nbsp;Firmenkunden&nbsp;(DE)</span></p></div><div class="MsoNormal" align="center" style="text-align:center"><hr size="3" width="100%" align="center"></div><div><p class="MsoNormal"><em><span style="color:#7F7F7F">Wenn Sie uns zus&auml;tzliche Kommentare oder Informationen zu Ihrem Anliegen mitteilen wollen, antworten Sie bitte einfach auf diese E-Mail oder <a href="%25%7Brecipient.ticket_link%7D" target="_blank"><span style="color:#548DD4">melden Sie sich an</span></a> f&uuml;r ein komplettes Archiv Ihrer Support-Anfragen.</span></em><span style="color:#7F7F7F"></span></p><div class="MsoNormal" align="center" style="text-align:center"><span style="color:#7F7F7F"><hr size="3" width="100%" align="center"></span></div><p class="MsoNormal"><span style="color:#7F7F7F"><br><em>Kundendaten: </em><i><br><br><em>Kundennummer: D000059 </em><br><em>UID: ATU56194969 </em><br><em>Firma: STEINEL Austria GmbH. </em><br><br><em>Hirschstettner Stra&szlig;e 19/A/2/2 </em><br><em>1220 Wien </em><br><em>Austria </em><br><br><em>Telefon: 4312023470 x21 </em><br><em>Fax: </em></i></span></p><div class="MsoNormal" align="center" style="text-align:center"><span style="color:#7F7F7F"><hr size="3" width="100%" align="center"></span></div><p class="MsoNormal"><i><span style="color:#7F7F7F"><br><br><img border="0" width="280" height="40" id="_x0000_i1028" src="cid:image001.png@01D0C55D.DD4DFAD0" alt="ITP_LOGO_HELPDESK_LOGO_EMAIL_FOOTER_V01.png"></span></i><span style="color:#7F7F7F"></span></p></div></div></body></html>

**Comment by guidokuehler** [comment]
Have you found a solution for your Problem?

Our Config:

osTicket-Version	v1.9.9-1-gbe2f138 (be2f138)
Server-Software	nginx/1.8.0
MySQL-Version	5.5.44
PHP-Version	5.6.4-4ubuntu6.2

The Email-Reply comes from an outllok Client via Exchange Server.

In the Ticket we see only  the follwed:

<html xmlns="http://www.w3.org/TR/REC


But the Email-Body begins how followed:

<html xmlns="http://www.w3.org/TR/REC-html40"><head><style><!--

@font-face
.
.
.

Best Regards
Guido

**Comment by guidokuehler** [comment]
We have seen in the Database and all was osticket write in the table from the original email is the followed.

&lt;html xmlns:v="urn:schemas

the format for this entry is html in the table
