### ISSUE TITLE
1.9.3 - feature request - auto save

### ISSUE THREAD

**Issue by mrabino1** [osTicket/osTicket#1182]
I would like to be able to disable the auto-save feature.. there are many times when I make an quick update and the system has not yet saved the draft that is constantly showing warnings...

**Comment by BillLinder** [comment]
I would suggest that this be a timed option for individual settings, where a time of 0 be disabling the option.  Not having looked at the code, is this a javascript event?  If so, then this ought not be too hard.

**Comment by mfelber** [comment]
This setting seems to change the behavior:
http://osticket.com/forum/discussion/86093/way-to-change-autosave-duration

**Comment by BillLinder** [comment]
Perfect.  Thank you very much.
Quoting mfelber <notifications@github.com>:

**Comment by davideakc** [comment]
Is it possible to let users decide the time of the autosave?
