### ISSUE TITLE
1.9.4-dpr db error (using auto assignment)

### ISSUE THREAD

**Issue by AZimmerhofer** [osTicket/osTicket#1215]
I Opened a new ticket by e-mail and two db error occur:
I am using PHP 5.3.18-nmm1 (CGI/FastCGI), Mysql 5.1.73 and Ubuntu/Linux

[INSERT INTO `ost__search` (`object_type`, `object_id`, `title`, `content`)
            VALUES ('H',50,'Ticket Assigned to First-Level-Support (IONA)','Auto Assignment'),('H',48,'Ticket Assigned to First-Level-Support (IONA)','Auto Assignment'),('T',16,'892662 ZZZZ','')]

Duplicate entry 'T-16' for key 'PRIMARY'<br /> <br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(182): osTicket->logDBError('DB Error #1062', '[INSERT INTO `o...')<br />
#1 (root)/include/class.search.php(553): db_query('INSERT INTO `os...')<br />
#2 (root)/include/class.search.php(533): MysqlSearchBackend->__index(NULL, true)<br />
#3 [internal function]: MysqlSearchBackend->IndexOldStuff(Array, NULL)<br />
#4 (root)/include/class.signal.php(98): call_user_func_array(Array, Array)<br />
#5 (root)/include/class.cron.php(106): Signal::send('cron', Array)<br />
#6 (root)/include/api.cron.php(19): Cron->run()<br />
#7 (root)/include/api.cron.php(12): CronApiController->run()<br />
#8 [internal function]: CronApiController->execute()<br />
#9 (root)/include/class.dispatcher.php(145): call_user_func_array(Array, Array)<br />
#10 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('cron', Array)<br />
#11 (root)/include/class.dispatcher.php(120): Dispatcher->resolve('cron', Array)<br />
#12 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/tasks/cron', NULL)<br />
#13 (root)/api/http.php(31): Dispatcher->resolve('/tasks/cron')<br />
#14 {main}

[INSERT INTO `ost__search` (`object_type`, `object_id`, `title`, `content`)
            VALUES ('H',50,'Ticket Assigned to First-Level-Support (IONA)','Auto Assignment'),('H',48,'Ticket Assigned to First-Level-Support (IONA)','Auto Assignment')]

Duplicate entry 'H-50' for key 'PRIMARY'<br /> <br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(182): osTicket->logDBError('DB Error #1062', '[INSERT INTO `o...')<br />
#1 (root)/include/class.search.php(553): db_query('INSERT INTO `os...')<br />
#2 (root)/include/class.search.php(533): MysqlSearchBackend->__index(NULL, true)<br />
#3 [internal function]: MysqlSearchBackend->IndexOldStuff(Array, NULL)<br />
#4 (root)/include/class.signal.php(98): call_user_func_array(Array, Array)<br />
#5 (root)/include/class.cron.php(106): Signal::send('cron', Array)<br />
#6 (root)/include/api.cron.php(19): Cron->run()<br />
#7 (root)/include/api.cron.php(12): CronApiController->run()<br />
#8 [internal function]: CronApiController->execute()<br />
#9 (root)/include/class.dispatcher.php(145): call_user_func_array(Array, Array)<br />
#10 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('cron', Array)<br />
#11 (root)/include/class.dispatcher.php(120): Dispatcher->resolve('cron', Array)<br />
#12 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/tasks/cron', NULL)<br />
#13 (root)/api/http.php(31): Dispatcher->resolve('/tasks/cron')<br />
#14 {main}

**Comment by gtulga** [comment]
how to fix this bug? I received hundred emails everyday only for this

**Comment by proudcommerce** [comment]
we also have this problem :-1:
