### ISSUE TITLE
How to upload attachments to Folder?

### ISSUE THREAD

**Issue by jhonny9696** [osTicket/osTicket#1243]
How to upload attachments to Folder instead of Database?

And attachments in Ticket Thread should open in new tab or windows in Staff Control Panel and user interface.

I hope Because of Upload in MySQL is hurting server more work load.

**Comment by simonnzg** [comment]
Done. All working. Never thought of that. Blinded by the "www-data"... ;-)

**Comment by theodorocaliari** [comment]
In the v1.10-rc.2 after install, set and active the plugin, the textarea of extensions not showing is that right?

**Comment by sim3083** [comment]
This isnt working for us with the storage-fs plugin

Running 1.9.4

The only console message we get when dropping a file is

`webkitURL' is deprecated. Please use 'URL' instead.`

On clicking the attachment in the ticket we get a 404 page with the following

_The requested URL /attachment.php was not found on this server._

Like simonnzg, the folders seem to be created but nothing inside, tried both 755 and 777 permissions

**Comment by JLCarbwood** [comment]
We are having issues with the storage-fs.phar. I uploaded to the include/plugin folder, but is not showing in the GUI. I chack using phpinfo to make sure phar extension is enable. Also change the permissions of the folder from 0755 to 0777, but no luck at all. We are using the latest version 1.9.14 and PHP 5.5. I also try with PHP 5.6 but same results. 

Any help will be highly appreciated!

**Comment by ntozier** [comment]
@JLCarbwood  
This appears to be a question better suited for the support forums at http:/osticket.com/forum
After you uploaded the code into the folder, did you go to Admin panel -> Manage -> Plugins -> and click Add New Plugin?

**Comment by JLCarbwood** [comment]
@ntozier 

Thank you for your quick reply. I will open a ticket there as well. I uploaded using FTP and check the permissions, In the osTicket interface it doesn't detect any file there. i upload other plugins to verify, but it doesn't see anything at all. Very strange in my opinion is like phar is not installed. But when I do phpinfo it shows.

**Comment by JediKev** [comment]
@nelsondcosta23 

What do you mean by "hidden"?

Cheers.

**Comment by nelsondcosta23** [comment]
So, the adice I give is...
You can trust the system, but when you need to empty your server or migrate to other machine you will have a pain in the ass XD but is worthy
