### ISSUE TITLE
Upgrade from 1.9.3 to 1.9.4rc2

### ISSUE THREAD

**Issue by etomer2014** [osTicket/osTicket#1266]
I started upgrade as follows:
- copied upload into webspace
- a Button to upgrade clicked
- error message was: [INSERT INTO `ost_config` (`namespace`, `key`, `value`)
  VALUES
  ('core', 'number_format', IF(@random, '######', '#')),
  ('core', 'sequence_id', IF(@random, 0, 1))] 
  Duplicate entry 'core-number_format' for key 'namespace'
- sequence id did exist with value 1 (it is okay) but error is throwen
- number_format set by singel INSERT to ######

But now i am loked into the "Upgrade broken" Screen, some links how to get helb but i only want to go forward in the Upgrade or start once more.

What ist to do?

**Comment by greezybacon** [comment]
@vicendominguez looks like a failed upgrade. Can you recover your data from before the upgrade and try again with an updated language pack?

**Comment by vicendominguez** [comment]
My last point here. Some weeks ago, finally I SOLVED this upgrade issue removing two keys from the ost_config table:

delete from ost_config where ost_config.id=79;
delete from ost_config where ost_config.id=80;

I think they were "number_format" and "sequence_id" fields. (i don't remember sorry).

Thanks to everybody for your help.
