### ISSUE TITLE
Upgrade v1.9.4-rc2 - DB Error #1062

### ISSUE THREAD

**Issue by jxcampos102030** [osTicket/osTicket#1268]
I have upgraded the system of v1.9.3 to v1.9.4 and I have received this message DB Error #1062.

[INSERT INTO `ost__search` (`object_type`, `object_id`, `title`, `content`) VALUES ('T', 408, '349232 CR-Retailer Service <101765> Habilitar ventas', ''), ('T', 407, '250325 CR-Retailer Service <101532> Habilitar ventas', ''), ('T', 406, '975590 CR-Retailservice<100255>solicitud de ajuste/Hold', ''), ('T', 405, '601751 CR-Retailer Service <101763> Habilitar ventas', ''), ('T', 404, '241422 CR-Retailservice<101392>solicitud de ajuste/Hold', ''), ('T', 403, '545687 <100817>Activar terminal', ''), ('T', 402, '316182 CR-Retailservice<101868>habilitar ventas', ''), ('T', 401, '241730 CR-Retailservice<101207>solicitud de ajuste/Hold', ''), ('T', 400, '493465 CR-Retailservice<101112>Actualización de datos', ''), ('T', 399, '486779 CR-Retailer Service <101545> Habilitar ventas', ''), ('T', 398, '942586 CR-Retailservice<100507>Solicitud de ajuste/hold', ''), ('T', 397, '103155 CR-Retailservice <101943> Solicitud de ajuste/h', ''), ('T', 396, '637208 Contrasena expirada', ''), ('T', 395, '539919 CR-Retailer Service <100699> Habilitar ventas', ''), ('T', 394, '919314 Problemas con el correo en el celular', ''), ('T', 393, '727443 Problemas con el excel', ''), ('T', 392, '242568 CR-Retailer Service <100561> Habilitar ventas', ''), ('T', 391, '867123 CR-Retailservice<101088>cambio de categoria premio', ''), ('T', 390, '287970 CR-Retailer Service <100467> Habilitar ventas', ''), ('T', 389, '764019 TEST 07072014', ''), ('T', 388, '305306 CR-Retailservice<100825>solicitud de ajuste/hold', ''), ('T', 387, '881123 CR-Retailservice<100825>solicitud de ajuste/hold', ''), ('T', 386, '446708 CR-Retailservice <101072> Solicitud de ajuste / h', ''), ('T', 385, '906648 CR-Retailservice <101191> Solicitud de ajuste/hold', ''), ('T', 384, '139939 CR-Retailservice<100910>solicitud de ajuste/hold', ''), ('T', 383, '260088 CR-Retailservice <100910> Solicitud de ajuste / ho', ''), ('T', 382, '557702 CR-Retailservice <100669>Habilitar ventas', ''), ('T', 381, '839367 CR-Retailservice <100763>habilitar ventas', ''), ('T', 380, '924963 CR-Retailservice <101392> Solicitud de ajuste / ho', ''), ('T', 379, '607454 CR-Retailservice<101011>solicitud de ajuste/Hold', '')] Duplicate entry 'T-408' for key 'PRIMARY

---- Recular ----
#0 C:\xampp\htdocs\osticket\upload\include\mysqli.php(182): osTicket->logDBError('DB Error #1062', '[INSERT INTO `o...')
#1 C:\xampp\htdocs\osticket\upload\include\class.search.php(573): db_query('INSERT INTO `os...')
#2 C:\xampp\htdocs\osticket\upload\include\class.search.php(474): MysqlSearchBackend->__index(Array)
#3 [internal function]: MysqlSearchBackend->IndexOldStuff(Array, NULL)
#4 C:\xampp\htdocs\osticket\upload\include\class.signal.php(98): call_user_func_array(Array, Array)
#5 C:\xampp\htdocs\osticket\upload\scp\autocron.php(53): Signal::send('cron', Array)
#6 {main}

Fecha de registro: Thu, Sep 11 2014 3:24pm Dirección IP: 127.0.0.1

**Comment by mckaygerhard** [comment]
i got same, but cuse troubles with filters, specially the not_contains filter rule type, does not apply when this are combined

if i delete the search table contens will be rebuild..

any temporally solution?
