### ISSUE TITLE
Staff Members Closed Tickets Showing as Closed(0)

### ISSUE THREAD

**Issue by jhonny9696** [osTicket/osTicket#1272]
Staff Members Closed Tickets Showing as Closed(0)

When Staff Members are closing Tickets its not adding up in menu

We are getting it as Closed(0)

Version Used v1.9.2

**Comment by MuhammadAhmadMir** [comment]
@greezybacon which feature i have to enable in group to grant access to an agent for closed ticket.
i have searched many option but problem is still there...

**Comment by ntozier** [comment]
You would have to grant them access to the department that the ticket is assigned to.

**Comment by poojagv** [comment]
@ntozier though the staff member has the access to the department on which the ticket has been raised, the count of closed tickets is not being displayed. it just shows as Closed (no number of tickets closed)
 pls get back to me asap!

**Comment by ntozier** [comment]
@poojagv I am not a coder... so that is not something that I can assist you with.
