### ISSUE TITLE
List view of tickets inside Organization

### ISSUE THREAD

**Issue by fictionedge** [osTicket/osTicket#1295]
Hi

The organization feature is just what I was needing but, there is something missing.
When we see the tickets list inside an organization, there is no way to filter by status. For instance, see only the opened tickets.
What would be even better is if we could in the advanced search add the filter to organization.
Great work on the new version
Cheers

**Comment by robcrossland** [comment]
Hi,
Did you ever get anywhere with this issue? 
Have you seen this thread? http://osticket.com/forum/discussion/78444/adding-organization-column-to-open-ticket-overview

Rob
