### ISSUE TITLE
error when using aliasing, for redirections

### ISSUE THREAD

**Issue by mckaygerhard** [osTicket/osTicket#1296]
redirections goes wrong due bad assignment or ROOT_DIR

ROOT_DIR takes place for filesystem instalation event server uri's so by example when user goes to request firts vistit to setup 

normal expected result ist that when visiting "localhost/osticket/" goes to "localhost/osticket/setup/install.php"

but due ROOT_DIR returns pthat from root serve when visit results are "localhost/setup/install.php"

**Comment by mckaygerhard** [comment]
...then i provide a solution in my little knowled around php, event use redirection with ROOT_PATH, detect the HTTP server root osticket install and use it.. https://github.com/osTicket/osTicket-1.8/blob/develop/bootstrap.php in the line 145 +/- 10 lines, change the usage of ROOT_PATH.'setup/' to  and also again later change the define "define('SETUP_DIR',ROOT_DIR.'setup/');" too..
**must use $_SERVER['PHP_SELF']; for  "domain/path1/path2/script.php" returns "/path1/path2/script.php" always..** and avoit usage of REQUES_URI that its an apache only var... and not standar.

this are not first time about this error, lets get note another issue similar in same file, around line 292 of bootstrap.php, u see "define('INCLUDE_DIR',ROOT_DIR.'include/');" and inmediatelly se the comment: "//Change this if include is moved outside the web path." this comment are done due the same error reported by me.. avanced and large environments have install files outside of the web path ALWAYS due security reasons...
i note and remenber that ridiculous setup its wen admins install a WAMP software and in 12 to 16 months gets an  attack!

remenber that paranoic admins use aliasing i explain what its: real instalation are in /opt/osticket and server listed and aliasing that "/support/" its a representation for "/opt/osticket"

in apache i tested, but a low professional and non-standar solution its using rewrite rules...

**Comment by greezybacon** [comment]
@mckaygerhard I have no idea what you're talking about or suggesting. Please use complete sentences, correctly spelled words, and clear indications of problems and fix suggestions.

**Comment by mckaygerhard** [comment]
i instaled in apache, but using aliasing (real installed osticket are in /opt/osticket, and in config file of apache i have and alias for that path represented in apache as /support/ that can be access in browser with http://<ip>/support/)

due in the setup sre using ROOT_DIR for redirections (and not standar method) in the browser the redirection goes to wrong path ( http://<ip>/opt/osticket/ ) of course, the UNIX absolute path and not the WEBSERVER path

to solver that situation, must be used the $_SERVER['PHP_SELF'] question event use the ROOT_DIR absolute path (that reveals info to clients about server) .. for security reason also for mayor compatibility with other servers.. 

its not hard and its good change

**Comment by greezybacon** [comment]
@mckaygerhard the code uses ROOT_DIR for file inclusions and ROOT_PATH for url paths and redirects. Where is ROOT_DIR used for a URL string?

**Comment by mckaygerhard** [comment]
look at the bootstrap.php:  see  Http::redirect(ROOT_PATH.'setup/');  do u read the previously messages? here root_path its a standar path that depends of filesystem.. ROOT_DIR that i mentioned in the lasted message are a example for ilustrate to u that are nonsense about avanced situations in large implementations

**Comment by novat0** [comment]
hello, i have the same problem, of course easyle workaround its input manually the path in browser, but mckaygerhard have right! seem developers assumed that the root path of the webserver are always so simple as apache its configured.

**Comment by greezybacon** [comment]
Could you post your apache configuration so I could attempt to reproduce the issue?

**Comment by novat0** [comment]
i setup normal apache, but for osticket support mount a network SAN in /media/webdata, and then configure a virtual path alias with this:

Alias /support /media/webdata/osticket-1.9
<Directory /media/webdata/osticket-1.9>
	Options FollowSymLinks
	DirectoryIndex index.php
</Directory>

i have apache2  2.2.16 with php 5.3.8 using suhoshin enabled with debian stable squeeze LTS support in a DELL t110 4Gb ram and 4 cores CPU XEON intel.

The network SAN can remenber the hardware (its remote) but its not problem i have already configura many other sites and no errors with NFS related.

**Comment by novat0** [comment]
previus messgae dont parse the configuration setting.. here the files i put in /etc/apache2/conf.d:

toch osticket.conf

content of file:

```make
Alias /support /media/webdata/osticket-1.9
<Directory /media/webdata/osticket-1.9>
Options FollowSymLinks
DirectoryIndex index.php
</Directory>
```

**Comment by mckaygerhard** [comment]
this issue was reported some time ago also and its still open also:

https://github.com/osTicket/osTicket-1.7/issues/538

**Comment by mckaygerhard** [comment]
ping!? still this issue not resolved and i not the only reported.. professional deploys does not used windose like setups..

**Comment by infectormp** [comment]
@mckaygerhard here osTicket/osTicket-1.7#538 discussion about nginx config. Nginx have completely different configuration. With nginx only canned response doesn't work as expected.

**Comment by mckaygerhard** [comment]
but i talking about the root assumtion and not the error on canned response.. this makes security very sweet and cannot play with settings on shared network deploys for clustering

**Comment by mckaygerhard** [comment]
ping? i not using nginx, in any case serious setupd does not use "lame windose setup" neither apache2, in my case i used powered faster ever hiawata and some lighttpd...

still this error.

**Comment by mckaygerhard** [comment]
for informational purposes: tagget incorrectly as cause unknow but the cause its that the path and url are not get from server environment correctly, this due compatibility with guindows env.. in this issue i explain why clarelly.

**Comment by ntozier** [comment]
This issue was closed on Dec 13th, 2016.
As @greezybacon previously statesd osTicket does not support lighttpd

**Comment by mckaygerhard** [comment]
the problem also happened in any webserver when using alias, i mean, osticket makes me to put a directory inside root/html event defined a valias as professional/secure way

**Comment by ntozier** [comment]
I have no idea what you are trying to say.

**Comment by mckaygerhard** [comment]
for u'r info: https://httpd.apache.org/docs/2.4/mod/mod_alias.html

the right setup of a environment in a bussines setup infraestructure is a fronend web server with many reverse proxy's, and many dedicated servers using aliasing as secure and organized os providers

**Comment by mckaygerhard** [comment]
due lack of knowledge of developer about "aliasing" (see apache documentation) i posted solution for this long time issue @tyronelucero @tomashastings  : http://osticket.com/forum/discussion/91640/invalid-redirection-setup-on-install-solution
