### ISSUE TITLE
Department manager gets "New ticket" alerts, even though it's disabled

### ISSUE THREAD

**Issue by MH-U** [osTicket/osTicket#1298]
Hi,

as I wrote here, this is really a bug:
http://www.osticket.com/forum/discussion/79269/department-manager-gets-new-ticket-alerts-even-though-it-s-disabled#latest

The fix is easy, just remove "OR d.manager_id=s.staff_id" from class.dept.php in the getMembers() function. You can find a more detailed explanation in the forum thread.

**Comment by MH-U** [comment]
Hi. I'm thinking about upgrading to the latest osticket version. Is this resolved in the latest release or do I have to patch it?

**Comment by greezybacon** [comment]
@MH-U I think the code still works as it did when you opened the issue. You should be using [git to manage your changes](http://osticket.com/blog/86) anyway.
