### ISSUE TITLE
Feature request - Make it easier for teams to find their tickets

### ISSUE THREAD

**Issue by ghost** [osTicket/osTicket#1304]
Currently, when a ticket is assigned to a team, it doesn't show up in any team member's "My Tickets" tab.  If it could be adjusted for the tickets to show up under "My Tickets" for all team members, that would be very helpful.  Alternatively, adding a new tab labeled "Team Tickets" would also work.

The reason for this request is because currently, our team members are having to use the advanced search to filter for open tickets assigned to their team.  This works, but they would love to have all assigned tickets easily viewable in a tickets tab.  We use teams extensively here, very few people are assigned tickets directly to themselves.

**Comment by bcamp** [comment]
Just posting an update here to confirm this still works with 1.9.5.1.
