### ISSUE TITLE
Attachments not being added when creating tickets

### ISSUE THREAD

**Issue by atwheeler** [osTicket/osTicket#1309]
HI All
When I create a new ticket and add an attachment, the attachment is stripped from the ticket. If I then reply to the ticket, and add an attachment, it works.

I created a fresh install of 1.8 to test and I'm getting the same problem, everything else works fine but attachments are dropped from new tickets. I have shared hosting with Hostgator, PHP5.3, and the problem happens in both Chrome and IE. 

Any ideas?

**Comment by mckaygerhard** [comment]
this still happened in lasted, i nfirme due pull request #1171 break now support for providers browser in enterprices internal orgaizations, also inclusivelly using firefox 28 max permited by my enterprice applications does not work due #1171 ..

so people thinks that "upgrading" and "upgrading" are the best, but as linux cowsay said: "if are working dont touch it"

**Comment by ntozier** [comment]
> but as linux cowsay said: "if are working dont touch it" 

How's that working out for you?

**Comment by mckaygerhard** [comment]
@ntozier was working before the change! read the context right!

**Comment by greezybacon** [comment]
Can we close this? I believe the last of the issues with the drag-and-drop file uploader were fixed in 1.9.x as of 048ac7f9921d8702fecec49dace99415d197520d

**Comment by mckaygerhard** [comment]
well currently does not work as spected, said works for any f¡browser but does not work in firefox 10

**Comment by mckaygerhard** [comment]
also for lasted does not work too, something fails, something works.. hit f12 developer console and cannot see any error.. dont work in midory too
