### ISSUE TITLE
Priority on Open new ticket not working correctly

### ISSUE THREAD

**Issue by MRSBPO** [osTicket/osTicket#1326]
When user specify the Priority when opening ticket, it always opens with default priority (normal) no matter what. There is no ticket filters, no rules nothing. Plain install of v1.9.4-rc2 and i want users to be able to specify priority when opening tickets. When i put this field as mandatory, they can choose from drop down menu what priority should it be. What ever they choose it opens with Normal priority. I already looked in:
http://osticket.com/forum/discussion/79249/priority-not-working/p1
and here:
http://osticket.com/forum/discussion/comment/86251/#Comment_86251
And they suggest to open this issue on GitHub as a bug. 
Can anyone confirm this is a bug and if so how to fix it?
Thank you.

**Comment by choczym** [comment]
@philaneous 
I use 1.9.3 version of osticket and where i must insert this code in class.ticket.php ?
Thank you in advance
