### ISSUE TITLE
custom fields control by javascript 

### ISSUE THREAD

**Issue by ukirfan** [osTicket/osTicket#135]
hi osTicket is fantastic with custom fields, i added dropdown lists perfectly, 

i am adding custom javascript to manipulate the fields which worked initially, but custom fields that are created are name driven rather than id driven and keeps changing .

example:
&lt;select name="f342056d2361264e">
                        <option value="">&mdash; Select Business Functions &mdash;</option>
                            <option value="1">GSE</option>
                            <option value="3">HR</option>
                            <option value="2">SECURITY</option>
                    </select&gt;

when i successfully made a javascript to control my drop downs the name tag keeps changing for every refersh , 

MY question is how to have custom javascript to handle custom fields as the name keeps changing for every page form updates f342056d2361264e this id changes  ?

example jquery code 

 $("select[name=f342056d2361264e]").hide();

**Comment by Dusza** [comment]
nice job.  this helped me out and i wasn't able to find anything in the forums. @greezybacon if i have my install of osticket non-public than i don't really need to worry about the spammers, correct?

**Comment by andsnake** [comment]
Or you could use $user_form->getField('email')->_widget->field->_widget->id); this will return (hopefully) the id of the field :)

**Comment by greezybacon** [comment]
@andsnake maybe I misunderstand your post, to fetch the javascript field name, use
```php
$id = $user_form->getField('email')->getFormName();
```

**Comment by andsnake** [comment]
really? hahah thanks (that makes this easier hahaha) 
well, for some reason it didn't cross my mind to use it directly like that :P
