### ISSUE TITLE
Possibility to edit/delete ticket response/internal note

### ISSUE THREAD

**Issue by hadoanngoc** [osTicket/osTicket#1387]
Issue since 1.7, is it available now in 1.9.3? https://github.com/osTicket/osTicket-1.7/issues/516

**Comment by fictionedge** [comment]
Please yes +1

**Comment by tha023** [comment]
i would love to see this, typo's look bad.
i can not understand why this isnt possible

**Comment by ericLemanissier** [comment]
It would be great ! +1

**Comment by infectormp** [comment]
edit ticket response/internal note implemented next version

**Comment by fictionedge** [comment]
Awesome!!!!

**Comment by apag96** [comment]
Thanks!

**Comment by balojs** [comment]
+1

**Comment by brgsousa** [comment]
Pleasseee add this feature. Based on permissions

**Comment by greezybacon** [comment]
This is implemented in `develop-next` and release on the releases page and osTicket.com under the name of v1.10-dpr. Feel free to try it out and report issues in #2056

**Comment by apag96** [comment]
Is that dev release stable enough to run in production?

**Comment by Chefkeks** [comment]
@apag96
The DPR tag behind v1.10 stands for <i>developer preview release</i> and so I think it's obviously not recommended to be used in production.

**Comment by greezybacon** [comment]
@apag96 I would recommend making a copy of your database and trying out the preview release with the copy. You can comment on how it works and prepare your upgrade strategy if you like it

**Comment by apag96** [comment]
Thanks for the recommendation, Jared.

**Comment by b2badmin** [comment]
is this feature available yet i still cant see this function?

**Comment by ntozier** [comment]
@b2badmin 
23 days ago greezybacon posted saying "This is implemented in develop-next and release on the releases page and osTicket.com under the name of v1.10-dpr. Feel free to try it out and report issues in #2056"

So yes it has been implemented in 1.10.
