### ISSUE TITLE
mPDF error: Text contains invalid UTF-8 character(s)

### ISSUE THREAD

**Issue by josh1856** [osTicket/osTicket#1395]
After upgrading to osTicket v1.9.1-556-gef79e44 when going to print a ticket either open or closed I am receiving the following error:  

mPDF error: Text contains invalid UTF-8 character(s)

ticket issue #204 did not fix my issue.

**Comment by mayonero** [comment]
$html = mb_convert_encoding($html, 'UTF-8', 'UTF-8');
before calling: "$mpdf->WriteHTML($html);"

I find this solution in: http://stackoverflow.com/questions/28736061/how-to-set-mpdf-html-contains-invalid-utf-8-characters
