### ISSUE TITLE
Hour not changing with timezone

### ISSUE THREAD

**Issue by Deepcuts** [osTicket/osTicket#1400]
Hello,
osTicket (v1.9.3)

Having some issues with the timezone.
Read all about it on forums.
Still, my timezone is messed up somehow.
At /scp/settings.php?t=system
No matter what timezone I choose, the hour remains the same and with 2 hours before my actual timezone.
Meaning if I choose -5 the hour will be 01:00
If I choose +5 or any other value, the hour will STILL be 01:00.

On the user page, the time is shown correctly and I have the same timezone setup as in /scp/settings.php

Short video about it: http://tinypic.com/r/2lxxk41/8

**Comment by abassanini** [comment]
I had the same problem
It solved when I changed the Timezone Configuration of the admin user.  Didn't have to adjust it in php.ini
