### ISSUE TITLE
v1.94-rc5 Problem listing tickets

### ISSUE THREAD

**Issue by quik87** [osTicket/osTicket#1404]
![captura de pantalla 2014-10-17 a las 0 36 50](https://cloud.githubusercontent.com/assets/9274116/4671747/2b45a042-5585-11e4-8f03-80b9a6869f8f.png)
![captura de pantalla 2014-10-17 a las 0 37 18](https://cloud.githubusercontent.com/assets/9274116/4671745/2b2b6c68-5585-11e4-8166-56a570f795f6.png)
![captura de pantalla 2014-10-17 a las 0 37 45](https://cloud.githubusercontent.com/assets/9274116/4671746/2b32c594-5585-11e4-9431-9055a55977b3.png)

The system created a ticket via checking with map protocol, but not listing at Tickets tab view. In addition yo can see it user view and access to the ticket an see the status at 'Open' but system say 0 ticket open.

**Comment by vicendominguez** [comment]
My last point here. Some weeks ago, finally I SOLVED this upgrade issue removing two keys from the ost_config table:

delete from ost_config where ost_config.id=79;
delete from ost_config where ost_config.id=80;

I think they were "number_format" and "sequence_id" fields. (i don't remember sorry).

Thanks to everybody for your help.
