### ISSUE TITLE
Feature Request - Ability to "Auto-Close" a ticket via EMail

### ISSUE THREAD

**Issue by fraser125** [osTicket/osTicket#1408]
Our manager wants my team to record all Walk Up, Chat and Phone Calls in OSTicket. 
Our Ideal Workflow would be to use Email Filters to AutoClose a ticket based on a specific Subject Line.
Example Subject Lines:  
Computer wont turn on [Other][Close]
Mouse isn't working [Phone][Close]
Then when the filter gets the email it could set the "Ticket Source" and "Close On Response" automatically. 

Using the New Ticket feature we can select these items manually, but we have a high volume of Chat interactions and it's more work to create a ticket than to respond most chats.
We are currently on v1.9.2 looking forward to upgrading to v1.9.4 once stable. If this is already solved and I'm missing it or there is a better solution to this please let me know. Thanks.

**Comment by tangchuanzhou** [comment]
ye, we want this feture too.
