### ISSUE TITLE
v1.9.4-rc5 Ticket filter  by priority appears broken.

### ISSUE THREAD

**Issue by PacCharles** [osTicket/osTicket#1421]
It looks like a ticket filter that triggers on Ticket / Priority Level of high will never actually execute.

If I send an email marked high priority, osTicket creates a new High priority ticket, as expected. 
I've set up a ticket filter to a auto-assign a ticket with Ticket / Priority Level of high, but it never triggers.

I've tried various combinations in the filter, when I pick "Ticket / Priority Level" , Match Any , and put "High" or "high" or "3"  (without quotes), in the comparison value field, the filter never triggers. I've tried Equal, Contains, Starts With, Ends With, and even Matches Regex with "High|high" in the box.

The filter triggers and auto-assigns correctly if I use some other criteria such as User/Email Address.  I just can't seem to get it to trigger on the ticket priority level.

EDIT: Oh, forgot to add, here's my setup:
osTicket version: v1.9.3 (bba9ccc) on Ubuntu 12.04.1
Plugin: LDAP Authentication and Lookup, authenticating against Active Directory on Win Server 2003 R2
Apache/2.2.22 (Ubuntu). MySQL Version 5.5.38
PHP Version 5.3.10-1ubuntu3.14. IMAP c-Client Version 2007e

**Comment by zukiblue** [comment]
I want to change the SLA if mail priority is High, but the filter don't work.
the "Emailed Tickets Priority" flag on Settings put the mail in High priority but the filter don't change the SLA.
v 1.9.12
