### ISSUE TITLE
v1.94-rc5 - Remote User Lookup Click Not Working - IE 8/9/10/11

### ISSUE THREAD

**Issue by grahamkeddie** [osTicket/osTicket#1422]
v1.94-rc5
I've found when I create a new ticket and look up a remote user nothing happens when you click the user.
The hand cursor highlights the name and the name disappears when you click but the fields are not populated.

Same thing happens with Chrome or Firefox.

Thanks
Graham

**Comment by greezybacon** [comment]
Would anyone be able to test the patch in osTicket/core-plugins#85?
