### ISSUE TITLE
1.9.3 - Add User error when Contact Form contains a Field of type Custom List

### ISSUE THREAD

**Issue by andreaplanet** [osTicket/osTicket#1431]
A) Admin Panel - Manage - Lists -  Add New Custom List
    Add a new Custom List "MyList" with a few items (strings)

B) Admin Panel - Manage - Forms - Contact Information
   Add a new Field of type "MyList", internal, variable name "mylist".

C) Staff Panel - Users - Add User
    C1) Create a new User and select a value for the MyList field.
    C2) Press the ADD USER button.
    C3) BUG: An error message is shown "Error adding user - try again!". The user was created but the value for the MyList field was not inserted (source of the error).

D) Staff Panel - Tickets - Create Ticket - Add User
     Same as C)

E) Staff Panel - Users - Update User
    I can successfully update and view the Custom List field for the user. Only on creation I have the error.

Server Information
osTicket Version v1.9.3 (bba9ccc)
Server Software Apache
PHP Version 5.4.31
MySQL Version 5.5.37
PHP Extensions

gdlib Used for image manipulation and PDF printing
imap Used for email fetching
xml XML API
xml-dom Used for HTML email processing
json Improves performance creating and processing JSON
gettext Improves performance for non US-English configurations
mbstring Highly recommended for non western european language content
phar Highly recommended for plugins and language packs
PHP Settings

cgi.fix_pathinfo = 1 "1" is recommended if AJAX is not working
Linux Shared Hosting

Browser: Firefox 33.0

**Comment by naerdinsul** [comment]
Confirmed on v1.9.14 (8b927a0).  There also seems to be a (related?) issue where the custom list selection is not saved to the database when a user account is autoregistered.  Editing the value in the user profile and saving or editing the value in the agent panel and saving both successfully update the value in the database.

osTicket Version           v1.9.14 (8b927a0) —  Up to date
Web Server Software   Apache/2.4.7 (Ubuntu)
MySQL Version            5.5.49
PHP Version                 5.5.9-1ubuntu4.17
