### ISSUE TITLE
1.9.3 - Inline images sometimes shown with size of 24x24 pixels

### ISSUE THREAD

**Issue by andreaplanet** [osTicket/osTicket#1432]
Sometimes an inlined image is shown with a size of 24 x 24 pixels. The problem lies in the html

This is an inconsistent behaviour. I noticed it first when sending emails, but hard to replicate it consistently. Sometimes inlined images are shown correctly and sometimes not. It happened also with some FAQ topics too.

The problem lies in the HTML I get "< img ... height="24" width="24" .. >. With emails the attached image is correct with it's original size always. But sometimes those wrong height/width values are present.

In a FAQ topic I got this html code by adding an inline image

< img src="http://www...png" style="box-sizing:border-box;max-width:100%;vertical-align:middle;border:0px none;cursor:default" height="24" width="24" alt="image" />

In this case in the Staff panel the image is still shown correctly due extra < div class="thread-body"> around the image and the main text of the FAQ. But the end-user will see the image incorrectly because when the topic is shown outside the Staff Panel it missed the < div class="thread-body"> tag.

I can't find a consistent way to replicate the behaviour of generating the html code. Sometimes we have 24x24 pixels sometimes the correct size.

A dummy workaround is to drag & resize always the inline image slightly so that I'm sure the 24x24 pixel size is not used. Unfortunately the issue is not shown in the preview only after the email was sent / FAQ opened on the user side.

Server Information
osTicket Version    v1.9.3 (bba9ccc)
Server Software     Apache
PHP Version     5.4.31
MySQL Version   5.5.37
PHP Extensions  
    gdlib   Used for image manipulation and PDF printing
    imap    Used for email fetching
    xml     XML API
    xml-dom     Used for HTML email processing
    json    Improves performance creating and processing JSON
    gettext     Improves performance for non US-English configurations
    mbstring    Highly recommended for non western european language content
    phar    Highly recommended for plugins and language packs
PHP Settings  
    cgi.fix_pathinfo = 1    "1" is recommended if AJAX is not working

Linux Shared Hosting, Browser: Firefox 33.0
Fresh install of osTicket 1.9.3, no mods.

**Comment by PsyMan2000** [comment]
1.9.12 is still having the same problem when adding an in line image in firefox (43.0.4 at time of typing) both Firefox for Windows and same issue in Firefox for Mac.

1. respond to ticket
2. add image (drag one in to the box)
3. hit reply

Recieving email has a 24x24 tiny image.

If you edit the image before hitting reply and save it is fine, the actual view of the reply in firefox is the right size, it is just the recipient who sees it shrunk.

Hope this helps as its a slight annoyance, I have to tell all of the staff to install and use Chrome (or Safari) when dealing with tickets, easier than reminding them to do the clumsy edit thing.

**Comment by bas-imst** [comment]
This issue still exists in v1.9.12 (19292ad): if an agent replies on a ticket **with an image only**, then this one is resized to a really small one in the mail to the customer.

**Comment by bas-imst** [comment]
I've made a diff between a correctly shown email and one with an imsge-size of 24x24. The image itself has no differences but the HTML differs at position 6 of the CSS-class-name:

mid-$J**g**EAAA==$1cb54e1bea@6962347a64
mid-$J**Q**EAAA==$1cb54e1bea@6962347a64

Maybe that helps to identify the bug?!
