### ISSUE TITLE
Department alert email has no effect

### ISSUE THREAD

**Issue by singularitytrav** [osTicket/osTicket#1433]
Our Default System Email is set to support@singularityu.org. Default Alert Email is set to "Use default system email. The legal department's Auto-Response Email is set to legal@singularityu.org however the alerts to agents come from support@singularityu.org. Incoming emails and emails to customers work fine to/from legal@. I've been able to duplicate this issue with other departments.

osTicket Version    v1.9.3 (bba9ccc)
Server Software Apache/2.4.7 (Ubuntu)
PHP Version 5.5.9-1ubuntu4.4
MySQL Version   5.5.38

Ideas? Thanks.

**Comment by singularitytrav** [comment]
Interesting, ok yeah the little [?] bubbles are confusing. So whatever we set as the outgoing email in a department should go to agents and users then? (that seems to be the results in my test)

**Comment by greezybacon** [comment]
@singularitytrav yes, the referenced pull request changed the system so the department address, if set, will be used for the reply to end users and alerts to agents
