### ISSUE TITLE
Advanced Search

### ISSUE THREAD

**Issue by johnhwyman** [osTicket/osTicket#1457]
Version 1.9.4
Advanced search with 2nd date field (I know that the field search isn't working). After an attempted search with say
Date Range From = 2014-10-01 to blank and my new field 2014-11-01 I do a search nothing found, now fill in another search date in custom field and the from date chages to 2014-10-31 everytime, reset from date , leave custom field same, hit search and custom date field changes to 2014-10-31

**Comment by maibarra** [comment]
Hi everyone. Is there any easy way to implement the "Date Range - Close Date" in this advanced search? Info on file and lines to modify will be deeply appreciated. osTicket version: v1.9.12 . Thanks in advance.
