### ISSUE TITLE
1.9.4 name formatting

### ISSUE THREAD

**Issue by cervedgroup** [osTicket/osTicket#1462]
The problem of the names with the spaces is still there when viewing the ticket thread and selected "Last, First" on name formatting pref)
the corrent name is "Del Pippo Michele", and is shown correctly on the queue lists of ticket.
![ost194nameformat](https://cloud.githubusercontent.com/assets/6535381/4883614/b6e763b0-6363-11e4-9bd4-6c9c67383416.JPG)

**Comment by rayfoss** [comment]
Have you tried
![screenshot from 2017-01-30 17-01-53](https://cloud.githubusercontent.com/assets/876076/22445608/e36ec70e-e70d-11e6-8f80-cbc3b6ce971f.png)
? Reply to reopen if that doesn't fix it
