### ISSUE TITLE
1.9.4 multi-select-choice-field is misplaced

### ISSUE THREAD

**Issue by ghost** [osTicket/osTicket#1463]
I create a multi-select-choice-field (via admin panel) for example in the user or organization form. Then I switch to the agent panel and click on the "create user" or the "create new organization" button. Now you see the field is not where it should be:

![multi-select-choice-field](https://cloud.githubusercontent.com/assets/5539456/4884174/1604de2c-6369-11e4-90c2-450d1ad8ef57.png)

**Comment by bluego78** [comment]
Did you found any solutions?
I have the same problem :-(

**Comment by mfelber** [comment]
I have just tested it with 1.9.12 and in this version this ui bug doesn't occur. So I think an upgrade will be a good solution. 

Not only therefore in the meantime were multiple issues fixed and multiple improvements made : 
https://github.com/osTicket/osTicket-1.8/releases

**Comment by bluego78** [comment]
Thanks, but i've edited to many files in my version and i can't update :-(

**Comment by mfelber** [comment]
Maybe you could look at the release notes to find the fix or compare the files between this versions to find it. I could imagine that this was a minor change that will be compatible with your special environment. 

Sorry, I have no better advice for you...

**Comment by bluego78** [comment]
Thank you, i've fixed, the problem was in: include/class.forms.php.
I've replaced it with the 1.9.12 version and it's ok now.
Hope this could helps.

**Comment by mfelber** [comment]
Good to hear that you find a way to fix this in your environment. Sharing those information could indeed help others (who are in a similar situation)..
