### ISSUE TITLE
"MSG" attachments v.1.9.4

### ISSUE THREAD

**Issue by simonretter** [osTicket/osTicket#1470]
Hi,

I updated to the new 1.9.4 version.

"Normal" attachments like PDF... TXT are working. In case of ".MSG" attachment OsTicket 1.9.4 seems to do a kind of parsing.

This happens when I use the attachment function in the tool directly:

![1](https://cloud.githubusercontent.com/assets/7000555/4914265/27ec6dbe-64c0-11e4-92de-ae0a6d1cdd5f.png)

But I also get an error when an email with an MSG attachment comes in.

![2](https://cloud.githubusercontent.com/assets/7000555/4914268/2858a3a8-64c0-11e4-993c-d3fa68b2f187.png)
(PNG is allowed as file type!)

Original email with MSG attachment:

![3](https://cloud.githubusercontent.com/assets/7000555/4914267/285569cc-64c0-11e4-9fa3-f0f81615e903.png)

I would like to have the .msg attached and not the content of the MSG file.

How/Where can I deactivate the parsing of MSG attachments?

Thanks.

Simon

**Comment by Chefkeks** [comment]
Hanging in on this here...

Wasn't aware of that "issue" until yesterday... Told a user to forward an email with 7 or 8 .msg attached (who got pdf, png etc. attachments itself inside the .msg) and so all I got, was a really long ticket thread with a lot of "unable to import errors" and thought to hopefully not be the first who run into that. Looks like I am not, so hoping for a plugin/option in a future version. :)

**Comment by cbiere** [comment]
I would also like to see this fixed. In my opinion, this borders on being a bug anyway. Is it really that difficult to treat a MSG-file just like any other opaque attachment? I don't know of any mail Client having a Problem with that.
