### ISSUE TITLE
get ticket api

### ISSUE THREAD

**Issue by snizzleorg** [osTicket/osTicket#1471]
It would be very nice to have a simple get ticket api. So that one can retrieve ticket data as xml or json. I have to get some of the ticket data for interfacing with different things and now I need to go through the data base which is quite ugly, especially since the database runs on a different server than the program that needs the data.

So a simple get ticket api function would be great. Any chances for implementing this? Or is there a easy (as in I know very little php) way of implementing it myself?

**Comment by lewiscawte** [comment]
I'm also quite interested in something like this. Is working on this going to be as simple as writing a set of functions for the GET requests, or will it require major modification to the existing API setup?

**Comment by SirLagz** [comment]
I also need something like this. I built a little DB query script for 1.9 but the upgrade to 1.10 has broken it.
