### ISSUE TITLE
Broaden the "group" concept to a "role"

### ISSUE THREAD

**Issue by jeffchulg** [osTicket/osTicket#148]
https://github.com/osTicket/osTicket-1.7/issues/845

Track : 
@jeffchulg
Hi, I've just noticed that a osticket user cannot be assigned to multiple groups. To me, a user can be at the same time for instance a common user (respond to tickets etc.) AND a manager for a group (assign tickets to users, etc.)
3 participants      

 @ntozier commented November 13, 2013
Here is my understanding of how this works.

Each user can belong to a Group, Department, and Team. (These are controlled in the Admin panel -> Staff -> Staff members -> theStaffMemberYouWantToEdit.)

Additionally:

Group

Groups control access to certain functions
Each Group can have any number of Departments (This is the part that's important to you)
Department

Each Department can have a Manager
Each Department can have any number of groups (This is the part that's important to you)
Team

Each Team can have a Team Leader
Each Team can have any number of users
So logically

UserA can belong to Dept1 which belongs to Group1 where she might be the Department manager.

UserA can also belong to Group2 which is part of Dept2.

UserA can also belong to Team1 where she is or is not the Team Lead. Tickets can be assigned to this Team and even though they are outside of UserA's department the user can answer them.

 @jeffchulg commented November 13, 2013 
To me, a manager of financial department should not be able to see tickets from the IT department for instance.
What I wanted to do is the following :

Create groups for all existing ways to access a ressource (read, update, assign, etc.) [ re-usable ]
Create a group which is mixing up some of the first created groups
assign a department to the group
For example, in the IT department, we have "cells", each cell has a manager and a team. The osTicket team concept could be used for project purpose. The manager is a member of the team and can don exactly the same things than a team member AND assign tickets etc.

Maybe it's possible to do so but I don't get it this way...

 @greezybacon commented November 14, 2013
We've mulled over changing the "Group" interface to one of "Roles". I think this is what you are describing. Basically the concept of a Group today changes to a Role (so you can define several "cells" of varying access) and you can associate several roles with one user.

I'll mark this as an enhancement to track it

**Comment by lkrms** [comment]
Can I please ask where this feature is up to? As we add more and more teams / tasks / projects to osTicket, managing quite complex access rights by creating additional groups (that don't properly address exec-level "inspection" privileges in one department with simultaneous "management" privileges in another) is both cumbersome and inadequate ...
