### ISSUE TITLE
1.9.4 - Cannot delete (empty) organization

### ISSUE THREAD

**Issue by ghost** [osTicket/osTicket#1485]
Im in screen Organizations. I Click 1 organisation open and try to delete that particular organization. I I confirm with " yes Delete" . I see "Loading" ,,, It stays on "loading forever" .. it does not delete the organization. I can only escape the screen by pressing "Esc"

**Comment by mckaygerhard** [comment]
similar to #3178

**Comment by mckaygerhard** [comment]
partially fixed with patch in #3178
