### ISSUE TITLE
How to customise osTicket the proper way?

### ISSUE THREAD

**Issue by snizzleorg** [osTicket/osTicket#1487]
Hi,

I need to change some thing sin the way forms are handled in order to integrate with our website. Question is how I sanely go about it without having to manually do all the changes again and again for every update.

I though I can checkout some specific version (tag 1.9.4 for example) do  my changes and then install that changed version.
I first create then

```
git pull https://github.com/snizzleorg/osTicket-1.8.git
```

then I create a branch matching the 1.9.4 tag:

```
git checkout -b my_edits v1.9.4
```

now, if v 1.9.5 comes along what exactly do i need to do?

Or is there a better way? 

Thanks for your help!

**Comment by melitus** [comment]
@greezybacon I want to add a new tab at the staff panel after Task tab to keep track of phones calls from a client. How do I go about it? I will be grateful if I can be told on how I can duplicate the task tab and modify necessary files. Thanks

**Comment by JediKev** [comment]
@melitus 

Honestly, I doubt you'd get a detailed outline of how to customize osTicket. osTicket is a free, open-source software giving you access to every bit of the code. You are able to look through any of the files for free and even edit them to your liking. The only thing you can't do is claim the codebase as your own. With this being said you'd probably want to watch some tutorials online on software development and how to understand object oriented programming. Once you get this down you'll be able to navigate through the files easily and understand which files to edit.

With all this being said I will provide the barebones for you to start:
This file generates the navigation.
- https://github.com/osTicket/osTicket/blob/develop-next/include/staff/templates/navigation.tmpl.php

This function generates and returns all the Tabs.
- https://github.com/osTicket/osTicket/blob/develop-next/include/class.nav.php#L125-L147

This function returns the submenus for each Tab.
- https://github.com/osTicket/osTicket/blob/develop-next/include/class.nav.php#L190-L193

Good luck 👍

Cheers.

**Comment by melitus** [comment]
@jediKev. Thanks for your explanation. I really appreciate. I'm new to php .if I can get correctly how to duplicate task tab and make changes on the field and database.That will help me to add call log tab locally
