### ISSUE TITLE
1.9.4: Different namings for user

### ISSUE THREAD

**Issue by ronnykrijt** [osTicket/osTicket#1498]
Owner, Submitter, User used to reflect the same person. I think that consistent naming should be used to describe the person meant. In the screenshot below, first  Owner and later Submitter are IMO meant to state the same user, being the user against whom the ticket was raised.

![image](https://cloud.githubusercontent.com/assets/897441/5058164/cba46926-6ce4-11e4-8421-7d0e17d74a5c.png)

**Comment by greezybacon** [comment]
@ronnykrijt I believe the distinction here is because the system will refuse to create the ticket and hence, there is no ticket owner, only the submitter or requester
