### ISSUE TITLE
1.9.4: Advanced search To-date before From-date shows all

### ISSUE THREAD

**Issue by ronnykrijt** [osTicket/osTicket#1499]
In the selection of Advanced Search, something is off, when an invalid date-selection is given. I tested with 15-11 until 08-11, so end-date before start-date. Below are the results, where I expected none, as in that date-range nothing is possible.:

![image](https://cloud.githubusercontent.com/assets/897441/5058789/ae2b237e-6cff-11e4-8356-bd8d84623b2e.png)

**Comment by greezybacon** [comment]
@ronnykrijt can you see if the patch in #1848 addresses the issue?

**Comment by ronnykrijt** [comment]
#1499 is not solved when applying this patched file to 1.9.6, still all tickets are showing, when having to-date before from-date.
