### ISSUE TITLE
[1.9.4] Wrong time

### ISSUE THREAD

**Issue by PeopleInside** [osTicket/osTicket#1503]
You can test this also in this demo URL of Softaculous.
https://www.softaculous.com/demos/osTicket

Time is wrong on Operator/Admin Panel but also in user register form.
TO REPRODUCE:
1. log in as administrator
2. click on admin panel
3. set time tp GMT 1.0 Paris
   Save settings and time printed will be not correct. Time printed is not the Paris, Rome GMT!
   Is one hurs hearly than correct one.

Also you can log out and go on the visitor side, click on Sign in, Create an account, change the time and time will be always not correct and not updated.

**Comment by PeopleInside** [comment]
Greezybacon,
For the botton one is not good time display is only to display he format configured and should be correct from the current .. you say is showed current http time? That is not correct for me, my server time is 10.30 and Osticket show 9.30.
Server time is correct, is only OsTicket who show wrong time.

Also when user register see wrong time. Why this issue still be unconfirmed and still be not fixxed yet?
There are other people who opened this issue to: https://github.com/osTicket/osTicket-1.8/issues/831 and still be unconfirmed and not fixxed.

**When this will be fixxed?**
http://postimg.org/image/pdodtwh4j/
http://postimg.org/image/peybnbiyb/

**Comment by greezybacon** [comment]
@PeopleInside I have devoted my efforts to removing the timezone drop down as it is and the daylight savings checkbox and replacing it with a more correct time zone handling in the `develop-next` branch.
