### ISSUE TITLE
1.9.4 Feature Request and Fix

### ISSUE THREAD

**Issue by fictionedge** [osTicket/osTicket#1508]
If the advanced search if we could add the Organization field, it would great help when searching for tickets of a given organization.
I also found out that when we click "export" in the bottom of the list, it doesn't matter if you selected any tickets, it will export everything.

Allow me to explain how in our everyday this feature would be so important.
When a member of the team is visiting an organization, we need to print/email the list of tickets he is going to take work. If we could add in the search the organization name and select the tickets, it would save allot of time searching for them. 

I know we can open the organization tab and see the tickets, the problem is we cannot change the sorting order, hide the closed tickets or export the list. This could be done easily in the normal ticket list.

Thanking for taking the time to read this.

Cheers

**Comment by mlipok** [comment]
> If the advanced search if we could add the Organization field, it would great help when searching for tickets of a given organization.

This would be very handy feature.

**Comment by mlipok** [comment]
Thanks just checked in osTicket 1.14.1 this feature works well.
