### ISSUE TITLE
Mass "ban & delete"

### ISSUE THREAD

**Issue by limer-org** [osTicket/osTicket#1518]
Is there a chance that such behavior has emerged in osticket ?? 
We could prepare commit to add this function, but is there a change to merge our code into production release.

**Comment by snizzleorg** [comment]
I think the banning is ok now. at least its possible after you open the ticket. We get about 10 spammers a day so its still ok.

However I want the spamming users deleted from the user database as well so I delete not the offending ticket but the user along with the ticket.

Thats at least 4 clicks per spam ticket which is not user friendly at all.

I suppose the spammers can somehow remain in the user database - thats probably necessary for blocking them as well BUT they should be excluded from the normal users view.
