### ISSUE TITLE
v1.9.4 - Admin should have access to all features including mark as overdue, etc

### ISSUE THREAD

**Issue by GeekSage** [osTicket/osTicket#1521]
Since I'm an admin and I set up the department managers as the actual managers of those departments I didn't even notice that the following options existed in the "More" area of the ticket dropdown:
- Release (unassign) Ticket
- Mark as Overdue
- Mark as Answered

I didn't even realize those were available until I saw someone put in a screenshot showing those options.  The "unassign" one would have come in especially useful as there have been times the manager of the department isn't available and a ticket was assigned to someone who also was out for the day.  Then I could have easily unassigned the ticket so that the other employees would know it's available to be claimed instead of trying to find the right person to assign it to myself.

I believe the admin should have access to all functionality of the system including these features as I sometimes help with moving the tickets around, etc and can imagine other people that are set up as admins would as well.

![image](https://cloud.githubusercontent.com/assets/3441198/5186129/520621a8-7492-11e4-993c-5769f0bbb39a.png)

**Comment by henrycoule** [comment]
It has been a while. ANy word on this issue ?

**Comment by henrycoule** [comment]
I have verified this and I can reproduce this at any time. Unless you are a manager for a department, you will never see the options to Mark tickets as answered or Release unassigned tickets. Not even if you are an administrator on the ticket system.  This didn't use to be like this.

**Comment by snizzleorg** [comment]
I personally would need the option to be available for all agents (or an option to make it available for selected agents) - not just for the department managers

**Comment by dwight-thinkbox** [comment]
I see in 1.10 that Roles and Permissions mentioned here are in, but I still see no way to enable Mark as Answered for the needed staff when they aren't the department manager. Please provide an ETA for this feature, which was removed long before it should have been, being once again available.
