### ISSUE TITLE
osTicket (v1.9.4) | DB Error #1104 "The SELECT would examine more than MAX_JOIN_SIZE rows; check your WHERE and use SET SQL_BIG_SELECTS=1 or SET MAX_JOIN_SIZE=# if the SELECT is okay"

### ISSUE THREAD

**Issue by jayvines** [osTicket/osTicket#1532]
Since a few weeks after our upgrade to 1.9.4, we're getting a DB Error #1104 whenever we try to search in osTicket (v1.9.4).  We only see the problem in searches.  Tickets open and close without a problem so far.

The issue is probably related to the number of records, not necessarily the version of OSTicket, which I believe we coincidentally upgraded a few weeks ago.  

We're hosted on Hostmonster, a CPanel shared server environment.  We have about 3500 tickets in the database.

Apache version  2.2.29
PHP version 5.4.34
MySQL version   5.5.40-36.1-log
Architecture    x86_64
Operating system    linux
Perl version    5.10.1
Kernel version  3.4.91-20140518.1.ul6.x86_64

Some MySQL forums suggest adding "SET SQL_BIG_SELECTS=1" before the query, and actually doing that results in a successful query if I submit the query through phpMyAdmin.  So, that's a positive sign.  Output results are further down.

Unfortunately, I don't have access to my.cnf, so I can't make those changes on my server.  The hosting provider doesn't allow changes to my.cnf to include changes like "SET SQL_BIG_SELECTS=1" because it's a shared environment.

Here's the error:

[SELECT DISTINCT COALESCE(B1.ticket_id, B2.ticket_id, B3.ticket_id, B4.ticket_id) FROM (
                SELECT object_type, object_id, MATCH (search.title, search.content) AGAINST ('jesus' IN BOOLEAN MODE) AS `relevance`
                FROM `cmg__search` `search`
                WHERE MATCH (search.title, search.content) AGAINST ('jesus' IN BOOLEAN MODE)
            ) `search` LEFT JOIN (select ticket_id as ticket_id from cmg_ticket
            ) B1 ON (B1.ticket_id = search.object_id and search.object_type = 'T') LEFT JOIN (select A2.id as thread_id, A1.ticket_id from cmg_ticket A1
                join cmg_ticket_thread A2 on (A1.ticket_id = A2.ticket_id)
            ) B2 ON (B2.thread_id = search.object_id and search.object_type = 'H') LEFT JOIN (select A3.id as user_id, A1.ticket_id from cmg_user A3
                join cmg_ticket A1 on (A1.user_id = A3.id)
            ) B3 ON (B3.user_id = search.object_id and search.object_type = 'U') LEFT JOIN (select A4.id as org_id, A1.ticket_id from cmg_organization A4
                join cmg_user A3 on (A3.org_id = A4.id) join cmg_ticket A1 on (A1.user_id = A3.id)
            ) B4 ON (B4.org_id = search.object_id and search.object_type = 'O') LEFT JOIN cmg_ticket A1 ON (A1.ticket_id = COALESCE(B1.ticket_id, B2.ticket_id, B3.ticket_id, B4.ticket_id)) LEFT JOIN cmg_ticket_status A2 ON (A1.status_id = A2.id) WHERE ((A1.staff_id=5 AND A2.state="open") OR A1.dept_id IN (1,3,5,6,7) OR A1.team_id IN (1) AND A2.state="open")ORDER BY `search`.`relevance` LIMIT 500]

The SELECT would examine more than MAX_JOIN_SIZE rows; check your WHERE and use SET SQL_BIG_SELECTS=1 or SET MAX_JOIN_SIZE=# if the SELECT is okay<br />
<br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(177): osTicket->logDBError('DB Error #1104', '[SELECT DISTINC...')<br />
#1 (root)/include/class.search.php(418): db_query('SELECT DISTINCT...', Object(Closure))<br />
#2 (root)/include/class.search.php(66): MysqlSearchBackend->find('jesus', Array, 'Ticket', Array)<br />
#3 (root)/include/ajax.tickets.php(239): SearchInterface->find('jesus', Array, 'Ticket')<br />
#4 (root)/include/staff/tickets.inc.php(141): TicketsAjaxAPI::_search(Array)<br />
#5 (root)/scp/tickets.php(492): require_once('/home1/vinesofa...')<br />
#6 {main}

and here's the output from an EXPLAIN EXTENDED

<table id="table_results">
  <thead>
    <tr>
      <th>id</th>
      <th>select_type</th>
      <th>table</th>
      <th>type</th>
      <th>possible_keys</th>
      <th>key</th>
      <th>key_len</th>
      <th>ref</th>
      <th>rows</th>
      <th>filtered</th>
      <th>Extra</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td align="right">1</td>
      <td>PRIMARY</td>
      <td>&lt;derived2&gt;</td>
      <td>ALL</td>
      <td>_NULL_</td>
      <td>_NULL_</td>
      <td>_NULL_</td>
      <td>_NULL_</td>
      <td align="right">26</td>
      <td align="right">100.00</td>
      <td>Using temporary; Using filesort</td>
    </tr>
    <tr>
      <td align="right">1</td>
      <td>PRIMARY</td>
      <td>&lt;derived3&gt;</td>
      <td>ALL</td>
      <td>_NULL_</td>
      <td>_NULL_</td>
      <td>_NULL_</td>
      <td>_NULL_</td>
      <td align="right">2936</td>
      <td align="right">100.00</td>
      <td></td>
    </tr>
    <tr>
      <td align="right">1</td>
      <td>PRIMARY</td>
      <td>&lt;derived4&gt;</td>
      <td>ALL</td>
      <td>_NULL_</td>
      <td>_NULL_</td>
      <td>_NULL_</td>
      <td>_NULL_</td>
      <td align="right">14355</td>
      <td align="right">100.00</td>
      <td></td>
    </tr>
    <tr>
      <td align="right">1</td>
      <td>PRIMARY</td>
      <td>&lt;derived5&gt;</td>
      <td>ALL</td>
      <td>_NULL_</td>
      <td>_NULL_</td>
      <td>_NULL_</td>
      <td>_NULL_</td>
      <td align="right">2936</td>
      <td align="right">100.00</td>
      <td></td>
    </tr>
    <tr>
      <td align="right">1</td>
      <td>PRIMARY</td>
      <td>&lt;derived6&gt;</td>
      <td>ALL</td>
      <td>_NULL_</td>
      <td>_NULL_</td>
      <td>_NULL_</td>
      <td>_NULL_</td>
      <td align="right">57</td>
      <td align="right">100.00</td>
      <td></td>
    </tr>
    <tr>
      <td align="right">1</td>
      <td>PRIMARY</td>
      <td>A1</td>
      <td>eq_ref</td>
      <td>PRIMARY,dept_id,staff_id,team_id</td>
      <td>PRIMARY</td>
      <td>4</td>
      <td>func</td>
      <td align="right">1</td>
      <td align="right">100.00</td>
      <td>Using where; Distinct</td>
    </tr>
    <tr>
      <td align="right">1</td>
      <td>PRIMARY</td>
      <td>A2</td>
      <td>eq_ref</td>
      <td>PRIMARY</td>
      <td>PRIMARY</td>
      <td>4</td>
      <td>vinesofa_ost1.A1.status_id</td>
      <td align="right">1</td>
      <td align="right">100.00</td>
      <td>Using where; Distinct</td>
    </tr>
    <tr>
      <td align="right">6</td>
      <td>DERIVED</td>
      <td>A4</td>
      <td>index</td>
      <td>PRIMARY</td>
      <td>PRIMARY</td>
      <td>4</td>
      <td>_NULL_</td>
      <td align="right">2</td>
      <td align="right">100.00</td>
      <td>Using index</td>
    </tr>
    <tr>
      <td align="right">6</td>
      <td>DERIVED</td>
      <td>A3</td>
      <td>ref</td>
      <td>PRIMARY,org_id,id,id_2</td>
      <td>org_id</td>
      <td>4</td>
      <td>vinesofa_ost1.A4.id</td>
      <td align="right">70</td>
      <td align="right">100.00</td>
      <td></td>
    </tr>
    <tr>
      <td align="right">6</td>
      <td>DERIVED</td>
      <td>A1</td>
      <td>ref</td>
      <td>user_id</td>
      <td>user_id</td>
      <td>4</td>
      <td>vinesofa_ost1.A3.id</td>
      <td align="right">16</td>
      <td align="right">100.00</td>
      <td></td>
    </tr>
    <tr>
      <td align="right">5</td>
      <td>DERIVED</td>
      <td>A1</td>
      <td>ALL</td>
      <td>user_id</td>
      <td>_NULL_</td>
      <td>_NULL_</td>
      <td>_NULL_</td>
      <td align="right">2936</td>
      <td align="right">100.00</td>
      <td></td>
    </tr>
    <tr>
      <td align="right">5</td>
      <td>DERIVED</td>
      <td>A3</td>
      <td>eq_ref</td>
      <td>PRIMARY,id,id_2</td>
      <td>PRIMARY</td>
      <td>4</td>
      <td>vinesofa_ost1.A1.user_id</td>
      <td align="right">1</td>
      <td align="right">100.00</td>
      <td>Using index</td>
    </tr>
    <tr>
      <td align="right">4</td>
      <td>DERIVED</td>
      <td>A1</td>
      <td>index</td>
      <td>PRIMARY</td>
      <td>PRIMARY</td>
      <td>4</td>
      <td>_NULL_</td>
      <td align="right">2936</td>
      <td align="right">100.00</td>
      <td>Using index</td>
    </tr>
    <tr>
      <td align="right">4</td>
      <td>DERIVED</td>
      <td>A2</td>
      <td>ref</td>
      <td>ticket_id</td>
      <td>ticket_id</td>
      <td>4</td>
      <td>vinesofa_ost1.A1.ticket_id</td>
      <td align="right">5</td>
      <td align="right">100.00</td>
      <td></td>
    </tr>
    <tr>
      <td align="right">3</td>
      <td>DERIVED</td>
      <td>cmg_ticket</td>
      <td>index</td>
      <td>_NULL_</td>
      <td>PRIMARY</td>
      <td>4</td>
      <td>_NULL_</td>
      <td align="right">2936</td>
      <td align="right">100.00</td>
      <td>Using index</td>
    </tr>
    <tr>
      <td align="right">2</td>
      <td>DERIVED</td>
      <td>search</td>
      <td>fulltext</td>
      <td>search</td>
      <td>search</td>
      <td>0</td>
      <td></td>
      <td align="right">1</td>
      <td align="right">100.00</td>
      <td>Using where</td>
    </tr>
  </tbody>
</table>

I don't really know what to do with that information, but it was suggested that I (or someone) could troubleshoot with it.

Is there any kind of workaround for this?  has anyone else seen this problem?  

I'd be happy to edit the SQL query if I knew where it was.  But I do not have that level of familiarity with OSTicket

Thank you in advance for your help.

If I run the query manually in phpMyAdmin with the prefix "SET SQL_BIG_SELECTS=1;", here are the results:

<table id="table_results">
  <thead>
    <tr>
      <th>COALESCE(B1.ticket_id, B2.ticket_id, B3.ticket_id, B4.ticket_id)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td align="right">2269</td>
    </tr>
    <tr>
      <td align="right">1098</td>
    </tr>
    <tr>
      <td align="right">2927</td>
    </tr>
    <tr>
      <td align="right">1735</td>
    </tr>
    <tr>
      <td align="right">1035</td>
    </tr>
    <tr>
      <td align="right">2668</td>
    </tr>
    <tr>
      <td align="right">1345</td>
    </tr>
    <tr>
      <td align="right">2158</td>
    </tr>
    <tr>
      <td align="right">1094</td>
    </tr>
    <tr>
      <td align="right">2845</td>
    </tr>
    <tr>
      <td align="right">1734</td>
    </tr>
    <tr>
      <td align="right">1470</td>
    </tr>
    <tr>
      <td align="right">2628</td>
    </tr>
    <tr>
      <td align="right">1344</td>
    </tr>
    <tr>
      <td align="right">3347</td>
    </tr>
    <tr>
      <td align="right">2083</td>
    </tr>
    <tr>
      <td align="right">1046</td>
    </tr>
    <tr>
      <td align="right">2843</td>
    </tr>
    <tr>
      <td align="right">1718</td>
    </tr>
    <tr>
      <td align="right">1769</td>
    </tr>
    <tr>
      <td align="right">2427</td>
    </tr>
    <tr>
      <td align="right">1317</td>
    </tr>
    <tr>
      <td align="right">3343</td>
    </tr>
    <tr>
      <td align="right">1971</td>
    </tr>
    <tr>
      <td align="right">1045</td>
    </tr>
    <tr>
      <td align="right">2802</td>
    </tr>
    <tr>
      <td align="right">1713</td>
    </tr>
    <tr>
      <td align="right">3414</td>
    </tr>
    <tr>
      <td align="right">2411</td>
    </tr>
    <tr>
      <td align="right">1316</td>
    </tr>
    <tr>
      <td align="right">3342</td>
    </tr>
    <tr>
      <td align="right">1955</td>
    </tr>
    <tr>
      <td align="right">1031</td>
    </tr>
    <tr>
      <td align="right">2787</td>
    </tr>
    <tr>
      <td align="right">1712</td>
    </tr>
    <tr>
      <td align="right">3448</td>
    </tr>
    <tr>
      <td align="right">2415</td>
    </tr>
    <tr>
      <td align="right">1255</td>
    </tr>
    <tr>
      <td align="right">3273</td>
    </tr>
    <tr>
      <td align="right">1935</td>
    </tr>
    <tr>
      <td align="right">1024</td>
    </tr>
    <tr>
      <td align="right">2709</td>
    </tr>
    <tr>
      <td align="right">1705</td>
    </tr>
    <tr>
      <td align="right">3493</td>
    </tr>
    <tr>
      <td align="right">2414</td>
    </tr>
    <tr>
      <td align="right">1254</td>
    </tr>
    <tr>
      <td align="right">3244</td>
    </tr>
    <tr>
      <td align="right">1914</td>
    </tr>
    <tr>
      <td align="right">1022</td>
    </tr>
    <tr>
      <td align="right">2706</td>
    </tr>
    <tr>
      <td align="right">1608</td>
    </tr>
    <tr>
      <td align="right">3558</td>
    </tr>
    <tr>
      <td align="right">2255</td>
    </tr>
    <tr>
      <td align="right">1207</td>
    </tr>
    <tr>
      <td align="right">3073</td>
    </tr>
    <tr>
      <td align="right">1913</td>
    </tr>
    <tr>
      <td align="right">931</td>
    </tr>
    <tr>
      <td align="right">2700</td>
    </tr>
    <tr>
      <td align="right">1536</td>
    </tr>
    <tr>
      <td align="right">3413</td>
    </tr>
    <tr>
      <td align="right">2386</td>
    </tr>
    <tr>
      <td align="right">1149</td>
    </tr>
    <tr>
      <td align="right">3072</td>
    </tr>
    <tr>
      <td align="right">1904</td>
    </tr>
    <tr>
      <td align="right">912</td>
    </tr>
    <tr>
      <td align="right">2699</td>
    </tr>
    <tr>
      <td align="right">1510</td>
    </tr>
    <tr>
      <td align="right">2283</td>
    </tr>
    <tr>
      <td align="right">1110</td>
    </tr>
    <tr>
      <td align="right">2889</td>
    </tr>
    <tr>
      <td align="right">1737</td>
    </tr>
    <tr>
      <td align="right">979</td>
    </tr>
    <tr>
      <td align="right">2679</td>
    </tr>
    <tr>
      <td align="right">1506</td>
    </tr>
    <tr>
      <td align="right">2296</td>
    </tr>
    <tr>
      <td align="right">1099</td>
    </tr>
    <tr>
      <td align="right">2991</td>
    </tr>
    <tr>
      <td align="right">1736</td>
    </tr>
    <tr>
      <td align="right">1021</td>
    </tr>
    <tr>
      <td align="right">2669</td>
    </tr>
    <tr>
      <td align="right">1469</td>
    </tr>
  </tbody>
</table>

**Comment by wingnut2dot0** [comment]
I am experiencing the same issue running v1.9.5.1 with
MySQL Version	5.5.40
PHP Version	5.4.34
Is the only solution to change DB's?

**Comment by jayvines** [comment]
i don't have the skills in my team to change DB.  we haven't seen any other option with OSTicket so we're moving the to free, hosted: http://ondemand.manageengine.com/service-desk/index.html

**Comment by praveen-l** [comment]
Even I'm not able to set up...
Www.new.askspider.com

But when i updated from old version it worked...
Www.Askspider.Com


On Thursday, January 29, 2015, jayvines <notifications@github.com> wrote:

> i don't have the skills in my team to change DB. we haven't seen any other
> option with OSTicket so we're moving the to free, hosted:
> http://ondemand.manageengine.com/service-desk/index.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/osTicket/osTicket-1.8/issues/1532#issuecomment-71893701>
> .
>


-- 
Sent from Gmail Mobile

**Comment by mfelber** [comment]
Sometimes it isn’t in your hand to decide changing the environment (hoster/hosting package/database).

So the solution „to change“ is not ever a solution for this kind of issue..

But maybe this help the helpless:

-> modify the file /include/class.search.php

insert the bold code after line 417 (osticket v 1.9.5.1)

// Create the search table automatically
            $class::createSearchTable();
        };
        **// SET SQL_BIG_SELECTS=1;**
        **db_query('SET SQL_BIG_SELECTS=1;');**        
        $res = db_query($sql, $auto_create);
        $object_ids = array();

In our case this seems to work fine (also a shared server without the possibility to change the mysql config)..

**Comment by jayvines** [comment]
i was so excited when this update from github showed up in my email.

thank you for trying @mfelber , but unfortunately, i am still helpless :(

[SELECT DISTINCT COALESCE(B1.ticket_id, B2.ticket_id, B3.ticket_id, B4.ticket_id) FROM (
                SELECT object_type, object_id, MATCH (search.title, search.content) AGAINST ('internet' IN BOOLEAN MODE) AS `relevance`
                FROM `cmg__search` `search`
                WHERE MATCH (search.title, search.content) AGAINST ('internet' IN BOOLEAN MODE)
            ) `search` LEFT JOIN (select ticket_id as ticket_id from cmg_ticket
            ) B1 ON (B1.ticket_id = search.object_id and search.object_type = 'T') LEFT JOIN (select A2.id as thread_id, A1.ticket_id from cmg_ticket A1
                join cmg_ticket_thread A2 on (A1.ticket_id = A2.ticket_id)
            ) B2 ON (B2.thread_id = search.object_id and search.object_type = 'H') LEFT JOIN (select A3.id as user_id, A1.ticket_id from cmg_user A3
                join cmg_ticket A1 on (A1.user_id = A3.id)
            ) B3 ON (B3.user_id = search.object_id and search.object_type = 'U') LEFT JOIN (select A4.id as org_id, A1.ticket_id from cmg_organization A4
                join cmg_user A3 on (A3.org_id = A4.id) join cmg_ticket A1 on (A1.user_id = A3.id)
            ) B4 ON (B4.org_id = search.object_id and search.object_type = 'O') LEFT JOIN cmg_ticket A1 ON (A1.ticket_id = COALESCE(B1.ticket_id, B2.ticket_id, B3.ticket_id, B4.ticket_id)) LEFT JOIN cmg_ticket_status A2 ON (A1.status_id = A2.id) WHERE ((A1.staff_id=2 AND A2.state="open") OR A1.dept_id IN (1,3,5,6,7) OR A1.team_id IN (1) AND A2.state="open")ORDER BY `search`.`relevance` LIMIT 500]

The SELECT would examine more than MAX_JOIN_SIZE rows; check your WHERE and use SET SQL_BIG_SELECTS=1 or SET MAX_JOIN_SIZE=# if the SELECT is okay<br />
<br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(177): osTicket->logDBError('DB Error #1104', '[SELECT DISTINC...')<br />
#1 (root)/include/class.search.php(421): db_query('SELECT DISTINCT...', Object(Closure))<br />
#2 (root)/include/class.search.php(66): MysqlSearchBackend->find('internet', Array, 'Ticket', Array)<br />
#3 (root)/include/ajax.tickets.php(242): SearchInterface->find('internet', Array, 'Ticket')<br />
#4 (root)/include/staff/tickets.inc.php(139): TicketsAjaxAPI::_search(Array)<br />
#5 (root)/scp/tickets.php(492): require_once('/home1/vinesofa...')<br />
#6 {main}

**Comment by jayvines** [comment]
thanks @mfelber ! it works!!!

**Comment by wingnut2dot0** [comment]
Same here. Thank you.

**Comment by mfelber** [comment]
nice to hear that it helps you :-)

greetings from cologne

**Comment by jayvines** [comment]
gracias from Argentina!

**Comment by ntozier** [comment]
I don't think that I would close this.  While the fix in the thread appears to fix your problem, it should really be addressed in the code by the devs.

**Comment by mfelber** [comment]
This would be the ideal solution. But will this really happen or will the rewritten advanced search 2.0 already solve this issue when it is out?

**Comment by jayvines** [comment]
surely they'll put this in the code now that they've seen our comments here! :D

**Comment by PrinceNG** [comment]
BIG BIG thanx from Germany @mfelber ! it works 4 me 2!!! :-D

**Comment by mfelber** [comment]
Freut mich, dass es Dir auch geholfen hat @PrinceNG . Schöne Grüße an die Alster..

**Comment by robertskiba** [comment]
I'm asking myself why this hasn't been fixed until now. I'm a customer at Hosteurope.de and it only works if I do this manual fix, but this isn't a solution. 

It should really be possible to opt-in the fixed setting.

**Comment by greezybacon** [comment]
The search query is much simpler in the `develop-next` branch, to be released as osTicket v1.10. Sorry for the trouble @robertskiba

**Comment by robertskiba** [comment]
1.10? Are you sure?

**Comment by greezybacon** [comment]
@robertskiba I wrote the release notes

**Comment by robertskiba** [comment]
Why do you go from 1.94 to 1.10? It's strange!

**Comment by Chefkeks** [comment]
Why not? :D
It's clearly how the version numbers are going / increasing:
1.7.x >> 1.8.x >> 1.9.x >> 1.10 (>> 1.11 >> 1.12 ...)

**Comment by ntozier** [comment]
"Why do you go from 1.94 to 1.10? It's strange"

ummm ... we're not?
We went from 1.9.0 to 1.9.1 to 1.9.2 to 1.9.3 to 1.9.4 to 1.9.5 to 1.9.5.1 to 1.9.6 to 1.9.7 (current) and are now going to 1.10.  That seems a pretty straight forward and logical progression to me.

**Comment by robertskiba** [comment]
OK, I forgot that it's called 1.9.x and not 1.9x. So I guess you meant 1.10.x. But 2.x would sound even more plausible!! ;-) 

Keep up the good work on this wonderful system!

**Comment by ntozier** [comment]
Nope.  The first version in a new sequence has always been 1.X, or 1.XST.  When and if there is a maintenance release for that version or an improvement does the third number get added.  But its safe to also assume that 1.10.0 is the same as 1.10 and 1.10ST.

2.x is already planned and has certain requirements.  Those requirements have not been achieved, so the 2.0 benchmark has not been reached.

**Comment by d003232** [comment]
Same problem with 1.9.12 at hoster STRATO. The fix from @mfelber also works very well for me.

**Comment by greezybacon** [comment]
Advanced search was redesigned for v1.10. Sorry it's taken so long to stabilize. It's also redesigned again in #2577. Hopefully it works better with each iteration.

**Comment by jayvines** [comment]
1.10 without problems.  thanks everyone

**Comment by jayvines** [comment]
well, without this problem!
