### ISSUE TITLE
Show & Sort Due dates on Answered Tab

### ISSUE THREAD

**Issue by henrycoule** [osTicket/osTicket#1540]
Is there a way to display due dates on the answered tab? and possibly also sort by the due date? Currently I do not see this possible anywhere.

**Comment by markus4000** [comment]
with the actual version you can do it with a MOD in file include/staff/ticket.inc.php

add around line 165:
'duedate'=>'duedate', in $sortoption

add a table header cell where you want it (around line 370):
![image](https://cloud.githubusercontent.com/assets/4391014/5597142/97c4dc38-929d-11e4-81e2-8164bec3c693.png)

add the table body cell where you need it (around line 460):
![image](https://cloud.githubusercontent.com/assets/4391014/5597147/a56e2e2a-929d-11e4-8664-f4cc76a6b044.png)
