### ISSUE TITLE
1.9.4 DB Error

### ISSUE THREAD

**Issue by gtulga** [osTicket/osTicket#1545]
Hi,

I installed latest stable version. Sometimes I receive email "Table 'ost_ticket__cdata' doesn't exist", but this table already existed. How to solve this problem?

Thanks,

**Comment by shoan** [comment]
I still have this problem in 1.9.7 and keep getting the following email

```
[SELECT ticket.ticket_id,tlock.lock_id,ticket.`number`,ticket.dept_id,ticket.staff_id,ticket.team_id  ,user.name ,email.address as email, dept.dept_name, status.state  ,status.name as status,ticket.source,ticket.isoverdue,ticket.isanswered,ticket.created  ,IF(ticket.duedate IS NULL,IF(sla.id IS NULL, NULL, DATE_ADD(ticket.created, INTERVAL sla.grace_period HOUR)), ticket.duedate) as duedate  ,CAST(GREATEST(IFNULL(ticket.lastmessage, 0), IFNULL(ticket.closed, 0), IFNULL(ticket.reopened, 0), ticket.created) as datetime) as effective_date  ,ticket.created as ticket_created, CONCAT_WS(" ", staff.firstname, staff.lastname) as staff, team.name as team  ,IF(staff.staff_id IS NULL,team.name,CONCAT_WS(" ", staff.lastname, staff.firstname)) as assigned  ,IF(ptopic.topic_pid IS NULL, topic.topic, CONCAT_WS(" / ", ptopic.topic, topic.topic)) as helptopic  ,cdata.priority as priority_id, cdata.subject, pri.priority_desc, pri.priority_color  FROM ost_ticket ticket  LEFT JOIN ost_ticket_status status
            ON (status.id = ticket.status_id)  LEFT JOIN ost_user user ON user.id = ticket.user_id LEFT JOIN ost_user_email email ON user.id = email.user_id LEFT JOIN ost_department dept ON ticket.dept_id=dept.dept_id  LEFT JOIN ost_ticket_lock tlock ON (ticket.ticket_id=tlock.ticket_id AND tlock.expire>NOW()
               AND tlock.staff_id!=28)  LEFT JOIN ost_staff staff ON (ticket.staff_id=staff.staff_id)  LEFT JOIN ost_team team ON (ticket.team_id=team.team_id)  LEFT JOIN ost_sla sla ON (ticket.sla_id=sla.id AND sla.isactive=1)  LEFT JOIN ost_help_topic topic ON (ticket.topic_id=topic.topic_id)  LEFT JOIN ost_help_topic ptopic ON (ptopic.topic_id=topic.topic_pid)  LEFT JOIN ost_ticket__cdata cdata ON (cdata.ticket_id = ticket.ticket_id)  LEFT JOIN ost_ticket_priority pri ON (pri.priority_id = cdata.priority)  WHERE (   ( ticket.staff_id=28 AND status.state="open")  OR ticket.dept_id IN (2) ) AND status.state IN (
                'open' )  AND ticket.isanswered=0  ORDER BY pri.priority_urgency ASC, effective_date DESC, ticket.created DESC LIMIT 0,25]



Table 'wfm_ticketing.ost_ticket__cdata' doesn't exist<br />
<br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(177): osTicket->logDBError('DB Error #1146', '[SELECT ticket....')<br />
#1 (root)/include/staff/tickets.inc.php(272): db_query('SELECT ticket.t...')<br />
#2 (root)/scp/tickets.php(501): require_once('/var/www/wfm.po...')<br />
#3 {main}
```

**Comment by gtulga** [comment]
me too

**Comment by ntozier** [comment]
@shoan and @gtulga Do both of you have the %ticket__cdata table?

**Comment by gtulga** [comment]
I have ost_ticket__cdata table and ~168K records

**Comment by shoan** [comment]
I also have it with ~90K records

**Comment by gtulga** [comment]
I still have this problem on v1.9.8.1. I received email:
```
[SELECT ticket.ticket_id,tlock.lock_id,ticket.`number`,ticket.dept_id,ticket.staff_id,ticket.team_id  ,user.name ,email.address as email, dept.dept_name, status.state  ,status.name as status,ticket.source,ticket.isoverdue,ticket.isanswered,ticket.created  ,IF(ticket.duedate IS NULL,IF(sla.id IS NULL, NULL, DATE_ADD(ticket.created, INTERVAL sla.grace_period HOUR)), ticket.duedate) as duedate  ,CAST(GREATEST(IFNULL(ticket.lastmessage, 0), IFNULL(ticket.closed, 0), IFNULL(ticket.reopened, 0), ticket.created) as datetime) as effective_date  ,ticket.created as ticket_created, CONCAT_WS(" ", staff.firstname, staff.lastname) as staff, team.name as team  ,IF(staff.staff_id IS NULL,team.name,CONCAT_WS(" ", staff.lastname, staff.firstname)) as assigned  ,IF(ptopic.topic_pid IS NULL, topic.topic, CONCAT_WS(" / ", ptopic.topic, topic.topic)) as helptopic  ,cdata.priority as priority_id, cdata.subject, pri.priority_desc, pri.priority_color  FROM ost_ticket ticket  LEFT JOIN ost_ticket_status status
            ON (status.id = ticket.status_id)  LEFT JOIN ost_user user ON user.id = ticket.user_id LEFT JOIN ost_user_email email ON user.id = email.user_id LEFT JOIN ost_department dept ON ticket.dept_id=dept.dept_id  LEFT JOIN ost_ticket_lock tlock ON (ticket.ticket_id=tlock.ticket_id AND tlock.expire>NOW()
               AND tlock.staff_id!=186)  LEFT JOIN ost_staff staff ON (ticket.staff_id=staff.staff_id)  LEFT JOIN ost_team team ON (ticket.team_id=team.team_id)  LEFT JOIN ost_sla sla ON (ticket.sla_id=sla.id AND sla.isactive=1)  LEFT JOIN ost_help_topic topic ON (ticket.topic_id=topic.topic_id)  LEFT JOIN ost_help_topic ptopic ON (ptopic.topic_id=topic.topic_pid)  LEFT JOIN ost_ticket__cdata cdata ON (cdata.ticket_id = ticket.ticket_id)  LEFT JOIN ost_ticket_priority pri ON (pri.priority_id = cdata.priority)  WHERE (   ( ticket.staff_id=186 AND status.state="open")  OR ticket.dept_id IN (13) ) AND status.state IN (
                'open' )  ORDER BY effective_date DESC LIMIT 0,25]
…


Table 'database.ost_ticket__cdata' doesn't exist<br />
<br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(177): osTicket->logDBError('DB Error #1146', '[SELECT ticket....')<br />
#1 (root)/include/staff/tickets.inc.php(275): db_query('SELECT ticket.t...')<br />
#2 (root)/scp/tickets.php(519): require_once('/usr/share/ngin...')<br />
#3 {main}
```

I run this query and it returned result. no error. So I think it is runtime error. maybe table locked or something?

**Comment by EnricoZogno** [comment]
Same error here, randomly appearing..... (using MySql ODBC to grab data....)

ERROR [42S02] [MySQL][ODBC 5.2(w) Driver][mysqld-5.6.16]Table 'osticket.ost_ticket__cdata' doesn't exist

**Comment by mfelber** [comment]
I'm using osticket 1.9.11 and I have observed that sometimes the cdata-table is temporarily missing.

You could reproduce it when you do the following:

Create a ticket, after ticket creating, edit this ticket via the "edit" button and set the sla plan to "none".
Save the ticket and now the cdata-table is gone! It only "comes back" when you navigate to the ticket tab.

You can only reproduce it with new tickets! When you set the sla plan to "none" for an existing ticket the data-table doesn't disappear! This at least could explain why some people have randomly problems to query this table..

**Comment by gtulga** [comment]
@greezybacon I think @mfelber explained problem. Our staff mostly use edit button.

**Comment by mfelber** [comment]
Hmm, I see a little difference in my case: even if the os_ticket__cdata table is missing and I run a query on this table I don't get a sql error in the system log of osticket (I get only an error in the sql client that runs the query that the table not exists). 

By the way: in osticket 1.10 it is also possible to reproduce this when you do the same steps I described before.

**Comment by mfelber** [comment]
When I'm looking at this comment from Jared from another issue, it looks to me that the thing I described is a wanted behavior: https://github.com/osTicket/osTicket-1.8/issues/1005 *"Has your system create a CDATA table in the mean time? It should be automatically created and populated when you visit the open tickets queue."* At least in my case where I get no errors in the system log...

**Comment by mfelber** [comment]
@gtulga @shoan The case that you have that dropping and recreating the cdata-table (which seems normal) creates errors in your log file (which I think should not happen) have not many people reported before. 

I only also know the issue report from holodoctor1 https://github.com/osTicket/osTicket-1.8/issues/2382 which describes the same. So it will be not easy to find the reason. When you all may report your environment like @ntozier has mentioned at the beginning of this thread (php version, mysql version, web server version, operating system version, if you customized osticket, used plugins, etc.) that could help to find the reason for this behavior. 

Screenshots like this for example are a good way to show the needed information: 
![systeminformation](https://cloud.githubusercontent.com/assets/5539456/9151656/7a7a50f4-3e0a-11e5-9ad2-b143898a032b.jpg)

**Comment by protich** [comment]
CDATA table provides materialized view of the custom data. It's expected behavior for the table to be dropped and rebuild, but I agree that we should mute the SQL errors and try to reduce the cap.

**Comment by mfelber** [comment]
@protich I never got this SQL errors in (my system log) when the table drops and rebuilds. I would guess that many people have reported this when this regularly happens. I have tried to reproduce it. So far I wasn't able to. Do you know a case when the dropping and rebuilding creates such an entry in the system log?

**Comment by protich** [comment]
The table get recreated when you visit ticket queues -- it will be rare to trigger it as a lone user. My assumption is we have cases where the table gets dropped when another agent is in the midst of querying the table. I also think v1.10 makes use (ticket object joins) of the table without ensuring it exists.

I think we need to some kind of locking mechanism and also make the rebuilding of the table instantaneous -- @greezybacon, would you concur?

**Comment by simonebracaloni** [comment]
I have exactly the same problem on 1.9.4
@greezybacon I think @protich  is right. The "drop and recreate view" process is not atomic neither is the ensureDynamicDataView and query (and the latter is actually the issue I guess).
Is there any update on this issue? What about protect ensure exist and query in a transaction?
Thanks in advance.

**Comment by AndiTopp** [comment]
i have the same Problem. is there a patch out already?

**Comment by AndiTopp** [comment]
PS: looks like this:

[SELECT a.ticket_id, concat(a.number,": ",b.subject) as label FROM `ost_ticket` as a LEFT JOIN ost_ticket__cdata as b on a.ticket_id = b.ticket_id LEFT JOIN ost_user_email as c on (a.user_id = c.user_id) WHERE c.address=(SELECT ab.address FROM ost_ticket AS aa LEFT JOIN ost_user_email AS ab ON ( aa.user_id = ab.user_id ) WHERE aa.ticket_id =3668) and a.status_id = 1  and a.ticket_id <> 3668 ORDER BY `created` DESC ]

Table 'syssto_ostickets.ost_ticket__cdata' doesn't exist<br />
<br />
---- Ablaufverfolgung ----<br />
#0 (root)/include/mysqli.php(177): osTicket->logDBError('DB Error #1146', '[SELECT a.ticke...')<br />
#1 (root)/include/staff/ticket-view.inc-mergeForm.php(26): db_query('SELECT a.ticket...')<br />
#2 (root)/include/staff/ticket-view.inc.php(744): include('/home/system-st...')<br />
#3 (root)/scp/tickets.php(514): require_once('/home/system-st...')<br />
#4 {main}
