### ISSUE TITLE
Staff couldn't attach documents for User

### ISSUE THREAD

**Issue by jhonny9696** [osTicket/osTicket#1547]
Staff couldn't attach, attachments for User while creating tickets, but we are able to see attachment button but not able to see in ticket

Checked with Extensions, in admin panel. Also its not working

**Comment by andrelindner** [comment]
> Staff couldn't attach, attachments for User while creating tickets, but we are able to see attachment button but not able to see in ticket
> 
> Checked with Extensions, in admin panel. Also its not working

still an issue? if not, please close this issue.
