### ISSUE TITLE
Show Recipients / Collaborators in user view

### ISSUE THREAD

**Issue by simonretter** [osTicket/osTicket#1567]
Hello,
several of our users are complaining that they can't see who else is linked in the ticket as Recipient / Collaborator. They sometimes even forward the ticket mail to others because they can't see in the user ticket view who is also added as Recipient / Collaborator.
Would be create if you add this.
Thanks!
/Simon

**Comment by simonretter** [comment]
Hi again,
we have almost daily issues that "Clients" are forwarding mails to colleagues or Superiors. Very often they were already included as "collaborator". We receive now complaints about double / tripple mails because of manual forwarding.

It would be very benefitial to inform the Clients somehow in the emails who else received this email.

I have two proposals:

1.)  Add a variable for the emails template to included the collaborator in the email text

2.) Add the collaborators of a ticket in the Header of the ticket in the client view

/Simon

**Comment by simonretter** [comment]
1.) is Ok with    %{ticket.recipients}

**Comment by greezybacon** [comment]
@simonretter v1.9.7 took care of duplicate collaborator emails. Have you upgraded?

**Comment by simonretter** [comment]
The double mails are not caused by OSTicket. 
Agent is answering a mail to a Client. Ticket contains a Collaborator. Client does not know about the Collaborator and forwards the mails manually to this Person (again).
But this is solved by adding the variable  %{ticket.recipients}   in the mail Body.

But still, several of our Clients work "online" and they would like to seein the Customer view on header level the Collaborators too.

**Comment by greezybacon** [comment]
@simonretter I agree the collaborators should be probably be displayed with the ticket owner at the top of the ticket too

**Comment by digitext** [comment]
Hi Simonretter,
Was this issue fixed.. ? is there a patch for this ? I am facing a similar issue, email recipients cannot find out which other recipients were copied in the email!.. This is important and needed by almost anybody using this tool.
Awaiting your response!

**Comment by mckaygerhard** [comment]
ping? what its the progres of this? collaborators not appears in clinet side ticket  due email recipients cannot find out which other recipients were copied in the email!..

**Comment by inphower** [comment]
Same problem here.

**Comment by mckaygerhard** [comment]
this problem its close related to issue #2509 @inphower see it, of course very long time passed and no solution.. only features and features that are not requested, its a hard pain for me that right now i cannot out from a largelly used system.. i'm too busy

**Comment by mckaygerhard** [comment]
hi @JediKev  before requested to open this issue, that are related to #2509 and seems similar to .. also seems partially solved in  #3353 but still older.. hwat about that?

**Comment by JediKev** [comment]
@mckaygerhard 

Read my comment to you here:
- https://github.com/osTicket/osTicket/issues/2509#issuecomment-571669379

Cheers.
