### ISSUE TITLE
enhancement: Ticket overdue with holiday and Weekends exclude

### ISSUE THREAD

**Issue by balojs** [osTicket/osTicket#1574]
Please  @greezybacon  and @protich  is posible this enhancement

**Comment by bwhatley87** [comment]
I just thought I'd bring this to the top of the list. I'm very much in favor of this since we are a school and we have many holidays, it seems all of our tickets are "overdue" because of the days off.

**Comment by balojs** [comment]
@JediKev  is posible this enhancement? 
Exclude of overdue holiday and Weekends

**Comment by balojs** [comment]
#419 duplicated
