### ISSUE TITLE
Duplicate Tickets and Ticket-Answers when Refreshing the Page

### ISSUE THREAD

**Issue by seegras3** [osTicket/osTicket#1577]
When Users create an Ticket and refresh the Page imediantly after that the Ticket will be created again

The same happens when replying to a ticket

I'm using the following Setup
![](http://puu.sh/dCOvl/37d94f19b5.png)

**Comment by davideakc** [comment]
In the 1.9.12 version this isn't been fixed.

Can someone suggest a code for avoid this problem?

**Comment by MohsenBahraminejad** [comment]
Hi,

i add java script to refresh page after posted replay.
in include > client > view.inc.php added this line :

`<script type="text/javascript">setTimeout(function(){ window.location.href = "tickets.php?id=<?php echo $ticket->getId(); ?>";}, 1200);</script>`

after:

`<div id="msg_notice"><?php echo $msg; ?></div>`

and summary :

`
<div id="msg_notice"><?php echo $msg; ?></div>
	<script type="text/javascript">setTimeout(function(){ window.location.href = "tickets.php?id=<?php echo $ticket->getId(); ?>";}, 1200);</script>
`

**Comment by DonCep** [comment]
Hi, MohsenBahraminejad 

Where exactly in view.inc.php I should put this two lines ?

**Comment by jthakilla9** [comment]
Does someone has a fix for this please, respond.

**Comment by Mohsnb** [comment]
> Hi, MohsenBahraminejad
> 
> Where exactly in view.inc.php I should put this two lines ?

find `<div id="msg_notice"><?php echo $msg; ?></div>` and write script after this.

**Comment by JediKev** [comment]
This will be addressed when #4509 is accepted/merged.

Cheers.

**Comment by jthakilla9** [comment]
> > Hi, MohsenBahraminejad
> > Where exactly in view.inc.php I should put this two lines ?
> 
> find `<div id="msg_notice"><?php echo $msg; ?></div>` and write script after it.

$urls = array();
foreach (AttachmentFile::objects()->filter(array(
    'attachments__thread_entry__thread__id' => $ticket->getThreadId(),
    'attachments__inline' => true,
)) as $file) {
    $urls[strtolower($file->getKey())] = array(
        'download_url' => $file->getDownloadUrl(),
        'filename' => $file->name,
    );
} ?>
showImagesInline(<?php echo JsonDataEncoder::encode($urls); ?>);
</script>
**<div id="msg_notice"><?php echo $msg; ?></div>
<script type="text/javascript">setTimeout(function(){ window.location.href = "tickets.php?id=<?php echo $ticket->getId(); ?>";}, 1200);</script>**

This is how i did it but it stil doesn't work, it creates a ticket after i refresh the page. is there a script that when i click refresh it brings me to the orginal page?

**Comment by jthakilla9** [comment]
It works i followed these steps  #4509

**Comment by JediKev** [comment]
Addressed with:
- https://github.com/osTicket/osTicket/pull/5253

**Comment by mrkylegp** [comment]
> Hi,
> 
> i add java script for refresh page to go same page without post data after posted replay. in **include > client > view.inc.php** added this line :
> 
> ```
> <script type="text/javascript">setTimeout(function(){ window.location.href = "tickets.php?id=<?php echo $ticket->getId(); ?>#reply";}, 1200);</script>
> ```
> 
> after:
> 
> `<div id="msg_notice"><?php echo $msg; ?></div>`
> 
> and summary :
> 
> ```
> <div id="msg_notice"><?php echo $msg; ?></div>
> <script type="text/javascript">setTimeout(function(){ window.location.href = "tickets.php?id=<?php echo $ticket->getId(); ?>#reply";}, 1200);</script>
> ```

This fix doesn't work for me in v1.18.2
