### ISSUE TITLE
develop-next - db error 1054  - agent panel dashboard

### ISSUE THREAD

**Issue by gmt-it** [osTicket/osTicket#1653]
This error is logged after clicking dashboard in agent panel the first time.
DB Error #1054

[SELECT T1.name, FORMAT(AVG(DATEDIFF(B2.created, B1.created)), 1) AS ResponseTime FROM ost_department T1 LEFT JOIN ost_ticket T2 ON (T2.id=T1.id) LEFT JOIN ost_thread B0 ON (B0.object_id=T2.ticket_id AND B0.object_type="T") LEFT JOIN ost_thread_entry B2 ON (B2.thread_id = B0.id AND B2.`type`="R") LEFT JOIN ost_thread_entry B1 ON (B2.pid = B1.id) LEFT JOIN ost_staff S1 ON (S1.staff_id=B2.staff_id) WHERE T1.id IN (1, 2, 3) AND B1.created BETWEEN FROM_UNIXTIME(1417802268) AND FROM_UNIXTIME(1420480668) GROUP BY T1.id ORDER BY T1.name] Unknown column 'T2.id' in 'on clause'

---- Backtrace ----
#0 (root)/include/mysqli.php(177): osTicket->logDBError('DB Error #1054', '[SELECT T1.name...')
#1 (root)/include/ajax.reports.php(128): db_query('SELECT T1.name, ...')
#2 (root)/include/ajax.reports.php(154): OverviewReportAjaxAPI->getData()
#3 [internal function]: OverviewReportAjaxAPI->getTabularData()
#4 (root)/include/class.dispatcher.php(145): call_user_func_array(Array, Array)
#5 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('table', Array)
#6 (root)/include/class.dispatcher.php(120): Dispatcher->resolve('table', Array)
#7 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/report/overvie...', NULL)
#8 (root)/scp/ajax.php(214): Dispatcher->resolve('/report/overvie...')
#9 {main}

**Comment by greezybacon** [comment]
Surprisingly, I noticed this earlier, but the fix seems daunting...
