### ISSUE TITLE
v1.10 feature req: default ticket number per year generation (prefix year in ramdom seq)

### ISSUE THREAD

**Issue by mckaygerhard** [osTicket/osTicket#1663]
in the admin panel , the ticket settings, the default format of ticket number generation only has two choices: ramdom or sequence... and only has one format, numeric.

there's a possibility to make a feature that can concatenates the year in the number generation, i show a example:
- format now in osticket are only "######" will result in "123456" depends of how many "#" will have many digits
- the feature can be: "Y######" and will result in "2015123456" or "2161234556" depending of the year and how many "#" will have the format
- another more exquisite the default complete time with nanoseconds as: "201501101339112340" for the complete time (year+month+date+hour+minuts+seconds+nanosecons)

why? in large enviroments this can easyle improve the reconition of tiockets by the users and agents for custon reports and data indicators, a very powerfully flags inside the ticket number!

**Comment by ntozier** [comment]
Please see https://github.com/osTicket/osTicket-1.8/pull/1128

**Comment by mckaygerhard** [comment]
hello, the pull only permit refers format, my feature request its only abut permit automatically added/update the date to firts fours or eigth digits of ticket number event any other configurations

by the way, interesting, maibe i must resear more over that feature, but i note not much documentation around that feature.. where are the documentation about usage of the tickets!??

**Comment by sycophantic** [comment]
This should also allow for month, day, etc as well.

**Comment by mckaygerhard** [comment]
yeah, good suggestion, maybe its better that admin can format the date appended to the format number generated. but not as complicated in custom format, as simples like "YYMMDD######" for generate "20150123109741" (20150123 + 109741)

**Comment by mckaygerhard** [comment]
this can be made in current v1.10 version

can i define a format in ticket numbre generation? by ex date format amont number digits?

**Comment by ntozier** [comment]
"can i define a format in ticket numbre generation? by ex date format amont number digits?"

I haven't the foggiest idea what you mean.

**Comment by mckaygerhard** [comment]
well if user put "YYYYMMDD#######" will be generated as "2015090912039784" why i just explain again that all users post here previusly for you? can u see the history!

**Comment by ntozier** [comment]
.... of course I can read the history of this open issue.
Your response(s) makes no sense.
This is a feature request that you started to be able to something.  Specifically to use arguments to create date based ticket numbers.  

You obviously know that you cannot do so currently, or you would not have made the feature request.  So then why then would you post [to your own feature request] asking if you can do what your requesting as a feature when you already know that answer?

**Comment by mckaygerhard** [comment]
@ntozier why try to silence my feature request, i can see a one user that also like my request, **and @greezybacon yet already market as "enhancement",** so i only ask for how are goin the work here and u seems to do not like my posts that are very "evolution-like" in way!

in this issue specifically i never threath that u said! again , please see the history!

**Comment by carlospea** [comment]
this its a nice feature, better that make a formula, currently this are not possible from custom number generation, at least not in 1.9.12 as easyle

**Comment by ntozier** [comment]
@mckaygerhard leap to conclusions much?  No one is trying to "silence" your feature request. 

On the contrary, I am trying to understand why you are asking if you can do something when you know that you cannot... since you created this thread in the first place to be able to do it.

**Comment by mckaygerhard** [comment]
well the request its for a option to able to put a format that includes the date in the number ticket generation, the explanation are in the second comment, but in resume that's all

currently i see that i can added letters, numbers per ticket filters or per king of tickets, but not a option to generate current date in the ticket number at the ticket creation!

**Comment by ntozier** [comment]
@mckaygerhard Yes. Which has little of nothing to do with actually answering my question.

**Comment by mckaygerhard** [comment]
u are the only that said "not possible"..  i posted many solutions in others ticket that users ask "when will be commited" solutions, not code requested..

that option of "date" in the ticket generatin number are possible, the issue are market as "enhanchement" and others people here seems like it!

**Comment by ntozier** [comment]
1.  I did not say it was not possible.  You obviously haven't read what I wrote.  I said.  
"You obviously know that you cannot do so currently, or you would not have made the feature request."

2. "i posted many solutions in others ticket that users ask "when will be commited" solutions, not code requested.."
This response appears to be completely off topic.

3. "that option of "date" in the ticket generatin number are possible,"
No, it is not currently possible.  That is, I presume, why you started this thread.
Yes, if the devs decide that they want to implement it ... then it is possible.
Yes, if someone else wants to implement it, file a pull request, and the devs accept it... then it is possible.

4. "the issue are market as "enhanchement" and others people here seems like it!"
Yes, I feel its a neat idea.  Although this appears to be off topic as well.

To sum this all up differently incase you feel I am not being clear:
You know it is **not currently possible**.
I still don't know why you posted and asked if you can do it.
Your answer is: no you **cannot currently** do it.

**Comment by mckaygerhard** [comment]
ok @ntozier i read all, post an in the fourth u posted that, but dont worry.. ok tell me what are to do to make it possible

please help with little tips what code (due there's no documentation) we must touch, i'm alone cannot do but maybe with other can be possible... 

i mean help with tips to do not read complety the code and make it more faster

ok u said that currently dont have the capacity to do, ok if something can doit what rules must follow to commit a pull request that solves this issue?

**Comment by ntozier** [comment]
I am not a dev. I'm a moderator.
I've already told you what needs to be done to make it possible (see 3. in previous post)
Anyone [with a github account] can file a pull request.

**Comment by mckaygerhard** [comment]
@ntozier custom ticket format not have capability to dinamically generate the date in ticket number

i'll try make and pull request wtih other to make this for both current versions

**Comment by Rankgel** [comment]
I am also interest in this enhancement ,+1

**Comment by kapatz** [comment]
I am also interest in this enhancement ,+1

**Comment by mckaygerhard** [comment]
ping¿?

**Comment by teslany** [comment]
I am also interest in this enhancement ,+1

**Comment by mckaygerhard** [comment]
@teslany @kapatz @Rankgel for the "+1" we must click in the face in the right corner ahd choose a "+1" to make noise in needed features!

**Comment by ntozier** [comment]
I'm not sure why you would think that who ever makes the most noise gets the most attention.

**Comment by mckaygerhard** [comment]
@JediKev  this issue has +4 in the first note and more.. people still are waithing this! and just close it? and developers only said "not possible"!

**Comment by JediKev** [comment]
@mckaygerhard 

You can batch close by what's in the first thread or how many likes it has unless you use a bot which I'm not willing to do. So all I had was by date range.

Cheers.
