### ISSUE TITLE
settings.php showing blank while upgrading to 19.5

### ISSUE THREAD

**Issue by admister** [osTicket/osTicket#1664]
hi, i copied the 19.5 files to a new folder and then copied the ost-config.php file from 19.4 installation.
then the setup page comes and suggests to go to admin panel for upgrade.
when i click the admin link it goes to settings.php. which shows nothing. i mean the page is blank. am i missing something. kindly help

running ubuntu 12.XX

**Comment by ntozier** [comment]
Sounds like you are getting a PHP error.  Please either turn on error displaying in osTicket or consuilt your PHP error log.

Here are directions on how to turn on error displaying: 
http://tmib.net/osticket-v19x-frequently-asked-questions-faq#2

**Comment by jagmohangupta** [comment]
sure i will check and share
