### ISSUE TITLE
Slack integration

### ISSUE THREAD

**Issue by mitchellknight** [osTicket/osTicket#1671]
Feature Request—

[Slack](http://slack.com) integration would be nice. It could allow your team to receive Slack notifications when a ticket is created, assigned, updated, replied to, and deleted. [Slack API](http://api.slack.com)

**Comment by snizzleorg** [comment]
there is this plugin: https://github.com/thammanna/osticket-slack

However not working for me (osTicket (v1.9.9-1-gbe2f138))
