### ISSUE TITLE
API submitting ticket sanity check

### ISSUE THREAD

**Issue by snizzleorg** [osTicket/osTicket#1679]
Is OSticket checking the submitted fields when submitting tickets via the API or is it necessary to do on the client side?

**Comment by greezybacon** [comment]
Did you test it?

**Comment by snizzleorg** [comment]
no. But I'm thinking of using it for submitting tickets via a web form (that needs to fit into a specific website).

Therefore I wanted to know whether it's safe as is or if it might be vulnerable to injections and the like.

thanks

**Comment by snizzleorg** [comment]
Is there anything I can do to help answer this question? I am debating whether to integrate the ticket submission in our web interface via the API. Right now I'm using a modified version of the Ticket submission form of osTicket... which is not ideal as upgrades seem to change the forms as well and then I have to redo the modifications....

**Comment by ntozier** [comment]
I'd recommend trying it and see what happens.
I would presume that it would check the data to make sure it was valid, and error otherwise.

**Comment by greezybacon** [comment]
> which is not ideal as upgrades seem to change the forms as well and then I have to redo the modifications....

Upgrading would allow you to define the forms in the admin panel and would relinquish your requirement for modifications.

**Comment by snizzleorg** [comment]
kind-of The forms yes can be prepared but still they do not match with the CI etc. for reference:

https://support.picoquant.com is the current form (adapted osticket form) This kind of form would be difficult to achieve with the included submission form.

**Comment by greezybacon** [comment]
@snizzleorg such a form can be created with the `develop-next` branch

**Comment by snizzleorg** [comment]
@greezybacon thanks for the info. Any ETA when this is in the release? I don't really want to switch to a development branch for a production system.

**Comment by greezybacon** [comment]
I would like to see a release candidate next week

**Comment by Chefkeks** [comment]
@greezybacon 
Nice! :+1:

**Comment by snizzleorg** [comment]
has there been any progress on the custom submit form? I just downloaded the latest osTicket (v1.9.8.1) but cannot find out how to create a custom submit form.
 
any hints ?

**Comment by infectormp** [comment]
@snizzleorg if you want put some data to custom form field you need fill Variable for this field in form. Then user Variable name as field name

**Comment by snizzleorg** [comment]
@infectormp maybe you got me wrong. I need to change the ticket submission from/page so that it fits into our CI. I did this with the current installation by changing the respective php files (open.php and the includes) but that of course doesn't service an update of osticket. therefore I either need the API to be able accept submissions or a really customisable page to submit tickets. I think the API would probably best. But it is still not clear whether osticket checks the submissions for html characters and the like - so whether it will prevent like sql injection etc.

**Comment by infectormp** [comment]
@snizzleorg you can send data via API in text or html format. To avoid sql injection you can send data in text format or strip html characters from data before send via API.

**Comment by greezybacon** [comment]
> To avoid sql injection you can send data in text format or strip html characters from data before send via API.

What?! Is there an SQL injection vulnerability I don't know about? The system designed to handle HTML well from the API, just use rfc 2937 format:
```json
{ "message": "data:text/html;charset=utf-8,Here is <b>html</b>" }
```

**Comment by emiliete1990** [comment]
Sorry to re-open this. When I try to put this line:

> { "message": "data:text/html;charset=utf-8,Here is <b>html</b>" } 

the API throws error 403.

If I remove the text/html part, it works OK, but it removes the HTML format from the email body. Currently I have it like this:
> { "message": "Here is <b>html</b>" } 

Do you know any way to keep the HTML format on OSTicket 1.10?

Thanks & Regards

**Comment by emiliete1990** [comment]
Finally, I managed to solve it.
For those experiencing the same issue, I solved it by adding the header MIME-Version: 1.0

**Comment by multiaki** [comment]
@emiliete1990 Could you post entire curl please. I added MIME-Version: 1.0 in the header. Are you using { "message": "data:text/html;charset=utf-8,Here is <b>html</b>" }

**Comment by emiliete1990** [comment]
@multiaki Hi. I don't remember because we decided to change it.
 Try with { "message": "Mime-Version: 1.0\r\ndata:text/html;charset=utf-8, Here is html" }
