### ISSUE TITLE
Problems while editting (Firefox 34.0.5)

### ISSUE THREAD

**Issue by send2nirwana** [osTicket/osTicket#1683]
- Somtimes the cursor isn't visible
- Sometimes the cursor-keys will stop working (no navigation of cursor with cursor-keys left/right/up/down in text window). Marking text (Ctrl+Shift+Cursor) will mark text in color, but no cursor is visible.

**Comment by send2nirwana** [comment]
... while composing a new response

**Comment by mckaygerhard** [comment]
same ocurrs to me but using firefox 7 and opera .. i prefer to work only in firefox 17 that are supported in enterprise environments and not lasted that are used only in guindows desktop at home's

**Comment by greezybacon** [comment]
As a general rule to all GitHub users, please, please, please, please submit a complete and total description of the problem that would help the developers who might fix the issue actually find it!

@send2nirwana where is this happening? osTicket is a large product.

**Comment by send2nirwana** [comment]
Problem while composing a new response:
- Sometimes the cursor isn't visible
- Sometimes the cursor-keys will stop working (cursor not moving when pressing the cursor-arrow-keys left/right/up/down while composing new message). Marking text (Ctrl+Shift+Cursor) will mark text in color, but no cursor is visible. In short words: the cursor are sometime unvisible, so have no idea where you are in the text (writing position).

**Comment by ntozier** [comment]
I think that maybe you would want to actually read and reply to @greezybacon when he asks you a question.  You have told him: 
* which version of Firefox your running
* which version of osTicket your running
* if this is agent or user side

**Comment by send2nirwana** [comment]
Version of osTicket: 1.9.4
Version of Firefox: 34.0.5
While composing new responses on agent side!

**Comment by greezybacon** [comment]
Firefox seems to be quickly replacing Internet Explorer as "that browser that is quirky and doesn't work right". I'll check it out.

**Comment by mckaygerhard** [comment]
err what paint internet winxplorer here? we are taking about firefox and internet browsers, not errors made by a megacompany..
