### ISSUE TITLE
to overdue or to not overdue?

### ISSUE THREAD

**Issue by andreaplanet** [osTicket/osTicket#1684]
Hello,

I would like to understand how the overdue system should work.

Scenario 1
A user opens a ticket. I answer. The user replies saying all ok. I close the ticket. OK

Scenario 2
A user opens a ticket. I answer. User disappears. Ticket got overdue. Why?? I did my job on answering. In this case when I am supposed to close the ticket to avoid overdue?

To avoid this I actually close every ticket right after answering. If the user replies then the ticket will be reopened automatically. And I close it after the next answer. This is actually my best workaround but I don't like it neither. And this isn't an overdue system at all. I can't find a solution. How should the overdue system be interpreted? I thought a ticket should go overdue when I don't handle it within a specific time.

Also why not offer the option to close the ticket by the user if it's ok for him (and for that specific installation).

Thank You,
Andrea

**Comment by mfelber** [comment]
I think this is the normal (wanted) behavior of this overdue mechanism. You must solve a ticket to avoid that it will be marked as overdue. It is explained in the wiki: https://github.com/osTicket/osTicket-1.8/wiki/Ticket-Lifecycle.

**Comment by andreaplanet** [comment]
What to do if the user doesn't answer? 
It is neither solved nor overdue (because I answered).

**Comment by ntozier** [comment]
It is over due if the ticket is open (regardless as to if you answered) after the SLA timer expires.

**Comment by andreaplanet** [comment]
I know how it works. I have difficuties to find it useful when the user doesn't answer. In that case it will always go overdue unless I close it. When should I close it then? My best use is to close it always after each answer, it's not the ideal situation.
An ideal solution would be to send the user an email reminding him to answer, and after some time close it automatically because the user doesn't answer.

**Comment by lewiscawte** [comment]
Can a different SLA be set for tickets that are in an answered state? Because I understand why answered tickets go overdue, but if I'm waiting on a user reply then I'm happy to leave it sit there a bit longer but I don't want my staff to have that extended period to reply back...

**Comment by andreaplanet** [comment]
Same here. A SLA for answering the user gives a degree of the quality of service. I like to have it relatively short, 8 hours. Then it's common for the user to reply after some days (or worse to not reply at all). In both case conceptually the 8 hours SLA for answering wasn't violated. 

I think I am understanding now. The actual SLA is intended as a SLA for solving the ticket, which should be quite high then (several days) because it have to consider the feedback of the user and often more than one comunication. It's not a SLA for the time needed to give an answer.

**Comment by andreaplanet** [comment]
I think then feature request would be to have an additional SLA time, for answering to each message (plus the actual SLA for solving the problem).

**Comment by Chefkeks** [comment]
As mentioned many times in the forum, the SLA feature needs to be revamped and is currently limited to mark open tickets (regardless of the fact that they are answered or unanswered) as overdue after passing by the SLA time. But the developers are already aware of that and will rework the SLA feature for future versions of osTicket. That said, please don't ask me when this will happen - I am not one of the developers nor have any insights.

**Comment by NetbearSoftware** [comment]
I'm also having a hard time understanding why tickets that have been answered and are awaiting a response from the customer get marked as overdue. The ball is usually in their court and therefore telling me the ticket is overdue (in my use-case at least) is redundant.

**Comment by ntozier** [comment]
because any ticket that isn't closed is subject to the SLA.
