### ISSUE TITLE
error: broken link on help tips to scp panel, asuming windoze/wamp server

### ISSUE THREAD

**Issue by mckaygerhard** [osTicket/osTicket#1686]
the help tips when the muse are over the "?" icon on inputs (in admin panel), the links to each different management settings are broken in some internationalization files, specially spanish and russian.

by example, in file manage.helptopic.yaml in line 63 the autoresponse link points to "/SCP/Settings.php?t=autoresp" and must be "/scp/Settings.php?t=autoresp" in lowercase for POSIX.

of course, sure work in poor OS's like windows, or the infamous WAMP-all-in-one installations that are not recommended for production usage (focused to windosers)...

.. production environments are deploiment in unix-like and for those case-sensitive must be care!

**Comment by mckaygerhard** [comment]
pings?

**Comment by ntozier** [comment]
The "manage.helptopic.yaml" in this repo does not exhibit the case that you have mentioned.
https://github.com/osTicket/osTicket-1.8/blob/24dbf6e571312a5098a981e5c05db55123eea991/include/i18n/en_US/help/tips/manage.helptopic.yaml

I would think that you would want to note this at the translation effort page for the lang that its borked in as it's not borked in the default language file.
http://i18n.osticket.com/

**Comment by mckaygerhard** [comment]
so u have right, all the lang files have broken links.. so then what should be do?.. i'm still must tune all files (russian, greek and spanish) on every update!!!!

**Comment by greezybacon** [comment]
Those lines should not be translated by the translators. Perhaps they should be hidden and reset on Crowdin

**Comment by mckaygerhard** [comment]
ah, eh ug, ok right but the case its not that. i'll try to colaborate and i joined to the i18n project and try to made some fixeds in the files. but that web system doest not work for that settings or those changes.. i can see those lines.. only translated lines

**Comment by mckaygerhard** [comment]
ping? the lang files still have broken links and translate tool are web based and dont showme the complete file, only strings to translate!

**Comment by mckaygerhard** [comment]
ping? the lang files still have broken links and translate tool are web based and dont showme the complete file, only strings to translate!

**Comment by greezybacon** [comment]
@mckaygerhard you can translate it in the browser at http://jipt.i18n.osticket.com/

**Comment by mckaygerhard** [comment]
i translated! then downloading and see that this tool (the browser translator) ignore the case sensitive and put a upercase in firs letters of a new line after a dot.

**Comment by greezybacon** [comment]
@mckaygerhard I found the strings you described, and I painstakingly went through the files on Crowdin and removed the incorrect and unnecessary translations of the URLs. Thanks for the report.

> of course, sure work in poor OS's like windows, or the infamous WAMP-all-in-one installations that are not recommended for production usage (focused to windosers)...

And for the record, when you post junk like this I tend to ignore your posts. Please stay on topic and I'll take you more seriously.

**Comment by mckaygerhard** [comment]
well, in nay case u must take more seriously.. currently guindows will take casesensitive for serveers in future ntfs v7 so in any way will take seriusly, this issue make unnusable in real os's not in fake os like MS's... massive deploys are in linux only,, take in consideration my company only use guindows for gammin in our homes..

i'll close the ticket when path are in respective brand.. currently i testing the feature of permission of agents to added or not added users... some notes i must commit.. i'll feedback later about

**Comment by mckaygerhard** [comment]
hello @greezybacon can u also fix (if u will touch these files) the #1347 issue, that also its a problem in the i18n file of spanish (the date format are wrong)

**Comment by mckaygerhard** [comment]
this issue still happened in lasted 1.9.11 release for some help topics.. 

the translations are the problem (and very few sources in code) the web translation tool does not allow edit the files only the fields

and as i said mayor deploys are on unix-like and those os are case sensitive!

NOTE: i report this as a bug in ostiket 1.9.2 (1.9 series not 1.10)

**Comment by mckaygerhard** [comment]
ping!? this still are not fixed in lasted neiter 1.9.12!!!

**Comment by carlospea** [comment]
please can fix them in 1.9.13?

**Comment by novat0** [comment]
please still this persist! the problem are in those files!

**Comment by greezybacon** [comment]
@mckaygerhard @carlospea @novat0 have you guys downloaded an updated language pack off the osTicket download page?

**Comment by mckaygerhard** [comment]
in my last response, yes, but today not, so i'll download a updated lang pack today and report feedback, please gime a few days, around a week and i'll post feedback

**Comment by mckaygerhard** [comment]
solved in osticket 1.9.14 puff so long for resolve a little strings..
