### ISSUE TITLE
Mail fetcher doesn't delete email

### ISSUE THREAD

**Issue by billmn** [osTicket/osTicket#1688]
Hi all,
I'm using osTicket v1.9.5.1 (1faad22) but I have problems with the email fetcher.

With this configuration, it download email correctly but it doesn't delete email on my mailbox:
![schermata 2015-01-19 alle 17 31 57](https://cloud.githubusercontent.com/assets/779534/5803807/5a52ca2e-a001-11e4-8174-f26a52f208c7.png)

I think the problem is related to POP + SSL protocol ... using standard POP3 protocol on our another support website it works fine.

The 2 support websites are on the same server and uses the same version of osTicket.

Thoughts?

**Comment by mckaygerhard** [comment]
i setup the oppossite and does the oppossite, setup to do nothing and deleted all emails..
but i not used pop, i used imap, with courier.. 

also i wish to know how to setup to move to folder, which are to set in the folder name prefix must be included? (in courier prefix are INBOX but with the dot or without?)
