### ISSUE TITLE
Feature Request : Auto Close Ticket in case of no reply for x days

### ISSUE THREAD

**Issue by supportreq** [osTicket/osTicket#1689]
This feature is very common for any ticket management system, where a ticket can be auto closed in case there is no reply from the client for x days.. the days can be defined based on the department or help topic..

**Comment by mckaygerhard** [comment]
this are the stack fature of the remedy software, this enhancement are one of the most wanted!!!

i hope will not be implemented with cron setup, or os touch... (sure not, due osticket seems run in mocosoft guindows)

**Comment by supportreq** [comment]
@greezybacon any plans to implement this soon

**Comment by adriencarbonne** [comment]
+1

**Comment by supportreq** [comment]
@greezybacon @protich can we use the Ticket Filter option for this? I didn't find a field of ticket creation date in the ticket filter..

Please advice..

**Comment by ntozier** [comment]
Q: can we use the Ticket Filter option for this?
A: Not at this time.

There is a mod on the forums discussing how to do this though.
http://osticket.com/forum/discussion/85900/auto-close-resolved-tickets-after-3-days

**Comment by amsut** [comment]
+1 for this.

**Comment by mohitbhatia1994** [comment]
+1

**Comment by mckaygerhard** [comment]
+1

umm the same code for delayed ticket s can be used for closed in "x" days?

**Comment by zener05** [comment]
+1

**Comment by wintstar** [comment]
+1

**Comment by jdelhome3578** [comment]
#2152 PR is waiting for someone to review

**Comment by Pablohn26** [comment]
+1

**Comment by kest874** [comment]
@Pablohn26 yes, the PR works, we use it here.   However I'm on 1.10

**Comment by mckaygerhard** [comment]
As @Pablohn26 said, me not have 1.10, i'm on 1.9 too why so many issues from 1.9 request are not attended?

**Comment by kest874** [comment]
Because 1.10 is final and current.

**Comment by mckaygerhard** [comment]
was not final when this issue was opened! more than a year to have a important feature!!!!

**Comment by mckaygerhard** [comment]
many important production sites still have 1.9 due better "mejor diablo conocido que nuevo por conocer"

reselers and vendors do not use software without well-knowed and well-tested and i know that 1.9 are well-knowed and -well-tested

the 1.10 are good for now when are well tested and the many issues in the github will close

**Comment by jdelhome3578** [comment]
@Pablohn26 @mckaygerhard what is wrong with #2152? It is written for 1.9.x and works fine.

**Comment by jdelhome3578** [comment]
@kest874 are you using #3450?

**Comment by mckaygerhard** [comment]
@jdelhome3578 i dont see this in 1.9.x brand, l must patch myselft my osticket installation with many usefully patches over the forum and network, due here seems users request usefully features are not allowed, i taking about simple and few lines patch's like open attached files into popup window very necesary and still pending

**Comment by ntozier** [comment]
I'm not sure why it is so hard to understand that new features are not back ported to old versions.

**Comment by mckaygerhard** [comment]
i'm not sure why its so hard to understand that need features are really little hacks NEED in current stable used versions, the patch for "open in new window" are not so hard to include that time when was proposed! a long long time ago... 

in any case, we have a job that we dont have the luxury to take the risk to take unknow newer versions if are not well knowed until are very well tested

**Comment by kest874** [comment]
@jdelhome3578 yes using #3450 @mckaygerhard use https://github.com/osTicket/osTicket/pull/2152

**Comment by mckaygerhard** [comment]
thanks @kest874 i right now patched the testing environment...
