### ISSUE TITLE
E-Mail templates & recipient.ticket_link: auto logon not working every 2nd access

### ISSUE THREAD

**Issue by jochenwezel** [osTicket/osTicket#1691]
After using %{recipient.ticket_link} in our e-mail templates, I've got following situation:

My e-mails contain a link like
http://mydomain/osticket/view.php?auth=abcdefghijklmnopqRstABCDEFGHIJve2xA%3D%3D. 

1st access to ticket using the created recipient.ticket_link seems to work
2nd access to the ticket a few seconds later DOESN'T work (independet from browser type MS IE, Firefox, independent of closing the complete browser session or entering the URL in the same tab again)

1st time:
![image](https://cloud.githubusercontent.com/assets/3033827/5821537/34b900d6-a0cd-11e4-9820-1c8d2951e4ba.png)

2nd time:
![image](https://cloud.githubusercontent.com/assets/3033827/5821551/4ae9fd88-a0cd-11e4-8b56-0e2a1fbaf00d.png)

3rd time works again, 4th time not, 5th time works again and so on...

Our osTicket System Info: osTicket (v1.9.3)

**Comment by greezybacon** [comment]
I've heard of this issue, but haven't been able to reproduce it. Thanks for the test data.
