### ISSUE TITLE
Duplication of internal notes in the ticket

### ISSUE THREAD

**Issue by msars** [osTicket/osTicket#1695]
Hi All,

When adding internal notes, we noticed a very strange thing. Occurs duplication of the internal notes.
To reproduce the problem it is necessary to take the next steps:
1. Add a internal note in the ticket.
2. After you see that note has been added successfully, after that, do the refresh on the page browser (F5).
3. After refreshing the page, you should see duplicating note.

osTicket v1.9.5.1
See image in attachment.

BR. Madi

![osticketnoteissue](https://cloud.githubusercontent.com/assets/9277655/5869636/7b6d1bbe-a2e6-11e4-919d-bd18a74d246b.jpg)

**Comment by ntozier** [comment]
duplicate thread.
see: https://github.com/osTicket/osTicket-1.8/issues/1577
