### ISSUE TITLE
Help popup (?) and configure links

### ISSUE THREAD

**Issue by iquidus** [osTicket/osTicket#1701]
The current UI design, having many of the 'edit/configure' links inside the help popup is a little confusing.  It took me far too long to figure out how to configure email properly for example. Although now I know where to look it's no longer a problem, I feel an edit button/icon next to the help icon (?) would be a better/less confusing approach and makes more sense as currently edit appears to be a child of help.

**Comment by ntozier** [comment]
This links are new... and not required to configure anything.

**Comment by greezybacon** [comment]
> having many of the 'edit/configure' links inside the help popup is a little confusing. 

The links help point you to other locations you might be interested in. They are not intended for primary navigation.
