### ISSUE TITLE
New token alert not sent to support/admin

### ISSUE THREAD

**Issue by Mijsons** [osTicket/osTicket#1705]
I am facing a little bit problem regarding email. When new ticket will create, email sent to the user but I also want that email will sent to support & admin on the creation of new ticket

**Comment by ntozier** [comment]
This does not appear to be a bug report and generally you would want to post this type of thing to the forums.  However:

Admin panel -> Settings -> Alerts And Notices -> New Ticket Alert.
tick the recipients that you want to receive the alert.

Make sure that your Department settings do not suppress it.
Admin panel -> Agents -> Departments -> your departments -> See Autoresponder Settings section.
