### ISSUE TITLE
develeop-next - Helptopic Forms

### ISSUE THREAD

**Issue by gmt-it** [osTicket/osTicket#1719]
Hello,
I'm testing the latest develop next at the moment. After adding a custom form I can select it under Helptopic Forms. 
![ht_001](https://cloud.githubusercontent.com/assets/10116166/6083383/6de468ba-ae28-11e4-8810-90b6b1fc74be.jpg)

After saving:
It is not seen anymore.
![ht_002](https://cloud.githubusercontent.com/assets/10116166/6083396/88e7b0a4-ae28-11e4-9307-642228ab64fd.jpg)

In Webinterface the Issue Detail Form is not shown. 
![ht_003](https://cloud.githubusercontent.com/assets/10116166/6083443/d8358744-ae28-11e4-8414-a6effdb34d41.jpg)

My osTicket Config:
![ht_004](https://cloud.githubusercontent.com/assets/10116166/6083474/1b170060-ae29-11e4-8ded-ec96ea69029b.jpg)

**Comment by greezybacon** [comment]
@gmt-it I believe this is fixed now. Can you confirm it?

**Comment by gmt-it** [comment]
@greezybacon Custom form is ok now and you can save it but there is no "Ticket Details" standardform shown after clean install.
