### ISSUE TITLE
Feature Request - HelpTopic Multilanguage

### ISSUE THREAD

**Issue by markus4000** [osTicket/osTicket#1720]
It would be great to be able to translate the help topics as well.
For example , for each language a checkbox in the Helptopic.
So the admin can choose, in what language this helptopic will be shown:
eg. : show in languag: English (x) German ( ), French ( ), always ( )
in that way even it would be possible to have its own workflow for each form and language.
What do you think? or how do you solve it?

**Comment by greezybacon** [comment]
This is implemented in the `develop-next` branch as part of our multilingual project, phase III

**Comment by greezybacon** [comment]
See #1410

**Comment by ntozier** [comment]
As a side note I would like to remind everyone that the Multi-language Feature is not complete at this time, and is in Phase III [of IV].

**Comment by heikod** [comment]
Is it foreseeable when this would be?

**Comment by greezybacon** [comment]
@heikod It's implemented already in the `develop-next` branch if you want to try it out and assist with stabilization

**Comment by heikod** [comment]
@greezybacon  what do I have to do? Sorry, I'm completely new to the system and settled it up ok so far, multilingual is the only thing missing :) appreciate ur help!

**Comment by greezybacon** [comment]
@heikod probably the easiest way to get going is to visit the main github page, change the branch by changing the dropdown from `develop` to `develop-next`, then download the zip file on the right side of the page.

**Comment by heikod** [comment]
ok worked, thanks. do i have to download the multilingual pack from the osticket page and install or is there one plugin from you with updated content? cheers

**Comment by greezybacon** [comment]
The language packs are not updated to work with the `develop-next` branch yet

**Comment by markus4000** [comment]
works in 1.10dev.
