### ISSUE TITLE
Tab "My tickets" for all assigned tickets to person AND team

### ISSUE THREAD

**Issue by AZimmerhofer** [osTicket/osTicket#1724]
Hello!

Today tickets assigned to a team (where the agent is member of) are NOT shown under "My tickets". This seems to be weird for me.

It would be better to adjust this behavior: All tickets (assigned to person or team) should be shown...

**Comment by protich** [comment]
We've discussed the possibly making such change --- but I think we shouldn't show tickets assigned to your team as well someone else (an individual agent) in "My Tickets".

**Comment by Chefkeks** [comment]
@protich 
Can understand your point, but also the point from AZimmerhofer.

So how about a tab like e.g. "My team tickets" appearing when a ticket is assigned to a team of which the agent is a member of?

Or will this become irrelevant with custom queues feature in the future, so that it's not necessary to change it?

**Comment by protich** [comment]
The primary motivation of doing the custom queues is so people can add whatever search criterion they want to the queues.

**Comment by AZimmerhofer** [comment]
@protich @Chefkeks 
It would be great to configure this by the admin. custom queries would be nice if the admin is able to arrange this query for the whole os ticket installation.

Our problem is: Every team member must have the opportunity to see closed tickets. So we cant use "Limit ticket access to ONLY assigned tickets". Therefore it would be very good to use the my ticket tab to seperate own tickets (assigned to me and assigned to my team) and tickets other teams. See also #1721.

**Comment by AZimmerhofer** [comment]
#1304

**Comment by Chefkeks** [comment]
Definitely like this suggestion (see below) from a admin point of view, but would limit it to a max of 3 queues or so, so that the agent can still easily see his/her own custom queues.

"custom queries would be nice if the admin is able to arrange this query for the whole os ticket installation"

**Comment by greezybacon** [comment]
The next major version of osTicket (currently `develop-next` supports saved searches, so that all agents can create and reuse searches like this

![screen shot 2015-02-13 at 1 15 07 pm](https://cloud.githubusercontent.com/assets/672074/6193583/5b129c2a-b382-11e4-8911-bd1a1af2c269.png)

**Comment by AZimmerhofer** [comment]
@greezybacon 

Thanks! Very good!
 
It would be great if the administrator can prearrange this settings. We would like to change the my tickets tab for every user. Would this be possible?
