### ISSUE TITLE
develop / develop-next schema signature

### ISSUE THREAD

**Issue by gmt-it** [osTicket/osTicket#1726]
No chance to install develop-next or develop. (clean install)

Develop-next:
core: Unbekannte oder ungültige Schema-Signatur (2d590ffab4a6a928f08cc97aace1399e .. d89d2bb9a52d1b9037f7815806cb7ba3)

Develop:
core: Unbekannte oder ungültige Schema-Signatur (b26f29a6bb5dbb3510b057632182d138 .. 493e6c902e76a8130d4a422f7880ddbc)

**Comment by ntozier** [comment]
I'm not sure what you're trying to tell us.

**Comment by gmt-it** [comment]
You can not make a clean install of develop because you got this signature error.

**Comment by ntozier** [comment]
So this is essentially the same as when you opened this:
https://github.com/osTicket/osTicket-1.8/issues/1659

but with a different schema number.

**Comment by gmt-it** [comment]
Yes, this is the same error after yesterdays update.

**Comment by greezybacon** [comment]
I cannot confirm the issue on the `develop` branch

**Comment by gmt-it** [comment]
This is my config:
![develop_001](https://cloud.githubusercontent.com/assets/10116166/6172469/4ab970c0-b2e1-11e4-8f19-28e5ecabf12e.jpg)
That is the error with the latest develop vrom GitHub:
![develop_002](https://cloud.githubusercontent.com/assets/10116166/6172492/79e53f6e-b2e1-11e4-8a68-68ba2d664aea.jpg)

**Comment by LucasBurg** [comment]
I also did the installing today, is show this error.

**Comment by greezybacon** [comment]
@LucasBurg @gmt-it where are you getting your files for installation? I did

```
git checkout develop
```

and the installation went without a hitch.

**Comment by gmt-it** [comment]
@greezybacon 
I use GitHub for windows and clone from here: 
![clone](https://cloud.githubusercontent.com/assets/10116166/6193786/e6ad426c-b3be-11e4-8b10-be5021f97346.jpg)

**Comment by gmt-it** [comment]
Git Shell: 
H:\Daten Privat\Projektdaten\osTicket\osTicket-1.8 [develop +1 ~656 -0 !]> git checkout develop
M       .gitignore
M       LICENSE.txt
M       README.md
........
M       setup/tips.php
M       setup/upgrade.php
M       view.php
M       web.config
Already on 'develop'
Your branch is up-to-date with 'origin/develop'.
H:\Daten Privat\Projektdaten\osTicket\osTicket-1.8 [develop +1 ~656 -0 !]>
So I think I use the latest from here.

**Comment by Chefkeks** [comment]
Can't confirm this either. Set up develop-next right now and everything went smooth.

I used the "Download ZIP" button which is under the "Clone in Desktop" and everything went fine. (https://github.com/osTicket/osTicket-1.8/archive/develop-next.zip)

**Comment by gmt-it** [comment]
@Chefkeks 
Seems like there are some files missing in the zip file:
This files are in /upgrader/streams/core when I update via GitHub but not in the zip file.
dad45ca2-61c9d5d7.task.php
b26f29a6-1ee831c8.task.php
d51f303a-dad45ca2.task.php
b26f29a6-1ee831c8.patch.sql
934954de-f1ccd3bb.task.php
b26f29a6-1ee831c8.cleanup.sql
8f99b8bf-03ff59bf.task.php
5cd0a25a-2d590ffa.patch.sql
5cd0a25a-2d590ffa.task.php
36f6b328-5cd0a25a.task.php
5cd0a25a-2d590ffa.cleanup.sql
36f6b328-5cd0a25a.cleanup.sql
36f6b328-5cd0a25a.patch.sql
1ee831c8-36f6b328.patch.sql
1ee831c8-36f6b328.task.php
15b30765-dd0022fb.task.php

Please check out helptopics in your installation. You will see no forms because the database is not updated.

**Comment by LucasBurg** [comment]
I did the dowload by sotfware of github, I will test "clone in desktop".

**Comment by LucasBurg** [comment]
List of archives this directory include/upgrader/streams/core.

dad45ca2-61c9d5d7.task.php    true
b26f29a6-1ee831c8.task.php    false
d51f303a-dad45ca2.task.php    true
b26f29a6-1ee831c8.patch.sql   false 
934954de-f1ccd3bb.task.php    false
b26f29a6-1ee831c8.cleanup.sql false
8f99b8bf-03ff59bf.task.php    true
5cd0a25a-2d590ffa.patch.sql   false
5cd0a25a-2d590ffa.task.php    false
36f6b328-5cd0a25a.task.php    false
5cd0a25a-2d590ffa.cleanup.sql false
36f6b328-5cd0a25a.cleanup.sql false
36f6b328-5cd0a25a.patch.sql   false
1ee831c8-36f6b328.patch.sql   false
1ee831c8-36f6b328.task.php    false
15b30765-dd0022fb.task.php    true

**Comment by gmt-it** [comment]
After todays updates I got this error when I install from tip file:

[CREATE TABLE `ost_lock` ( `lock_id` int(11) unsigned NOT NULL auto_increment, `staff_id` int(10) unsigned NOT NULL default '0', `expire` datetime default NULL, `code` varchar(20), `created` datetime NOT NULL, PRIMARY KEY (`lock_id`), UNIQUE KEY `ticket_id` (`ticket_id`), KEY `staff_id` (`staff_id`) ) DEFAULT CHARSET=utf8] Key column 'ticket_id' doesn't exist in table 
![unbenannt](https://cloud.githubusercontent.com/assets/10116166/6238872/d5a54936-b6fe-11e4-895d-2f5ae954e04c.JPG)

**Comment by greezybacon** [comment]
@gmt-it thanks for the heads up. I fixed this in 7449461

**Comment by gmt-it** [comment]
@greezybacon 
Thanks! Installation runs now but there is a problem with Help topics -> Forms. Standard forms are not shown and after selecting a helptopic in frontend there is no issue detail form.
![unbenannt1](https://cloud.githubusercontent.com/assets/10116166/6239753/29cfdcc6-b707-11e4-9da4-1d9dbda8e5d0.JPG)
![unbenannt](https://cloud.githubusercontent.com/assets/10116166/6239754/29d01d9e-b707-11e4-8692-650ea2f4ae09.JPG)

**Comment by Chefkeks** [comment]
@greezybacon 
Regarding the issue @gmt-it reported within the last comment, I'd like to know if such error shall be reported here (or anywhere else) for the a work-in-progress branch like develop-next and if yes, where such issues shall be reported - asking since I also noticed the issue above and also some issues with the new ticket filter settings.

**Comment by LucasBurg** [comment]
the error cotinue with my clone.

**Comment by gmt-it** [comment]
@LucasBurg: You have to download the zip file. With GitHub for Windows (GUI Version) you allways get this schema error if you try to install the Clone from your Windows folder. Don't know why...

**Comment by greezybacon** [comment]
@Chefkeks, yes, please continue to follow the `develop-next` branch experimentally. This is the place to log issues with all development branches. We'd like to get the software as stable as possible for the first developer preview release

**Comment by greezybacon** [comment]
@gmt-it I believe the forms are added correctly in #1989

**Comment by gmt-it** [comment]
@greezybacon I just installed the latest develop-next. Error is the same! Standard Form "Ticket Details" is not shown at front end. If you take a look to helptopic forms there is no relation to the Standard form.
![topic_003](https://cloud.githubusercontent.com/assets/10116166/7412586/915e6342-ef44-11e4-9e41-4ffe5568b7a4.png)
![topic_002](https://cloud.githubusercontent.com/assets/10116166/7412588/91609c34-ef44-11e4-9520-f27898c77071.png)
![topic_001](https://cloud.githubusercontent.com/assets/10116166/7412587/915fed5c-ef44-11e4-9a0c-8533c6a1b83e.png)

**Comment by mfelber** [comment]
@gmt-it I' not really an expert in this, but isn't it so that the changes greezybacon mentioned are not yet merged in the develop-next branch? I guess you must wait till this happened or you take a look at greezybacons own repository (branch greezybacon:issue/next-stabilize) where you find the adjusted files..

**Comment by greezybacon** [comment]
@mfelber you are right. Sorry for the confusion

**Comment by mfelber** [comment]
@greezybacon Thanks for clarifying. I'm still learning how this is all organized on github and it is good to hear that from someone who knows..
