### ISSUE TITLE
file upload via phone doesn't work

### ISSUE THREAD

**Issue by qikehu** [osTicket/osTicket#1729]
Hi I met three problems on 1.9.5.1,
1. file upload via phone doesn't work. I add a new field for upload files, it doesn't work on mobile devices.
2. Ticket search function doesn't work well on client side, barely find results.
3. Print function doesn't work well, it shows messy code.

For 2&3 issue, I think it might be the language issue, client side is using Chinese language, but I have no idea to fix those issues.

Thanks in advance.

**Comment by greezybacon** [comment]
@qikehu could you submit some screenshots or some of the text that does not render well in the PDF? I'd like to see how I could replicate it.

**Comment by qikehu** [comment]
update:

1. I tried file upload with other cell phones and file upload works on most of them.
2. Does the search function support custom field?
3. Screenshot here
![Uploading 20150213101212.png . . .]()

**Comment by greezybacon** [comment]
The PDF export assumes that you have fonts for these characters installed on your local system. Adobe has some of them. The problem for us is that the font packs are like 60MiB for the CJK fonts and it isn't worthwhile to make the osTicket download that large just to include extra PDF fonts. I also considered placing them in the CJK language pack phar files; however, there is a performance penalty of about 5ms per megabyte for requests using the language pack. Therefore, 60MiB language packs would significantly impact the sites which would use them.

I'm open to any other ideas.

**Comment by robintoy** [comment]
Stop spamming !!!!!!



Kind Regards


Robin Toy
Director
Strobe Technologies Ltd
[in]<https://www.linkedin.com/in/robin-toy-13714625>[sw]<http://community.spiceworks.com/people/robintoy>[Certification Badge - Small]
