### ISSUE TITLE
Feature Request: Fix the upper ticket-view (menubar)

### ISSUE THREAD

**Issue by TheSMa** [osTicket/osTicket#1731]
Is it possible to create an option, that agents/admins can fix the upper ticket-view? (see my screenshots)
In many cases (eg. long ticket conversations) it's nice to have a feature like that. You don't need to scroll up to get access to the menubar.

![ticket1](https://cloud.githubusercontent.com/assets/6357571/6188682/1ebe4992-b394-11e4-8dfb-7936bb02b1c2.jpg)
![ticket2](https://cloud.githubusercontent.com/assets/6357571/6188683/2018b5ca-b394-11e4-8ec1-8e78159210b6.jpg)

**Comment by ntozier** [comment]
I'm not sure what you mean.

**Comment by greezybacon** [comment]
@ntozier I think the suggestion is for a static navigation bar or sidebar, which stays put as the page is scrolled.

**Comment by TheSMa** [comment]
@greezybacon yes, that is what i mean.

**Comment by greezybacon** [comment]
This is somewhat addressed in #2043. The ticket options float with scroll, which I feel is better than the navigation options.

**Comment by tha023** [comment]
this is exactly what i would love to see as well! cant wait for the next update
