### ISSUE TITLE
Email topic mismatch

### ISSUE THREAD

**Issue by lvanjaarsveld** [osTicket/osTicket#1734]
Branche 1.9.5.1, email parsing issues. osTicket has a problem importing a few emails. I tought the bug was somehere in the subject, becouse it contained a number. But after running the subject trough the class.thread algorithme this doesn't seem to be the case.
1. Have osTicket fetch emails.
2. Send a message to this email with the following subject, "RE: Eerste aanmaning, klantnummer 3048".
3. Watch osTicket generate errors.

**Comment by greezybacon** [comment]
> Watch osTicket generate errors.

What errors do you receive?

**Comment by infectormp** [comment]
Well, i send email with following subject, "RE: Eerste aanmaning, klantnummer 3048" and osTicket fetch email without problem.

**Comment by infectormp** [comment]
@lvanjaarsveld you fetch email with POP or IMAP?

**Comment by lvanjaarsveld** [comment]
Gmail box, IMAP.
