### ISSUE TITLE
Different login for Ingoing and Outgoing email?

### ISSUE THREAD

**Issue by kwamtum2** [osTicket/osTicket#1745]
I notice it's not possible to have different "login" details for sending. We use mailjet or/and mandrill to send emails.

![image](https://cloud.githubusercontent.com/assets/1745506/6248305/a6766f2a-b77e-11e4-9083-0871e608501c.png)

Only it's not possible to use a third party SMTP server? I guess it's a small adjustment, but it would be a very nice feature!

**Comment by thaeli** [comment]
I'm doing this now. What I did was set up a separate "email address" for my third party SMTP server, enabling Header Spoofing for that address. Then set "Sending Email via SMTP / Status" to Disable for all my "real" email addresses. That seems to force everything to go through the third party server.

I currently have this in production with Amazon SES SMTP, but it should work the same with any SMTP email provider authorized to send for your domain.

**Comment by thaeli** [comment]
Updated my earlier comment, it was missing a step. Adding a quick note here so anyone on email thread gets it.

**Comment by des79** [comment]
Hi, 
sorry I reply to this one but I need help with SMTP configuration. If I set fake account (ex.: fake@mandrill.com) and use this account on settings->Default MTA, I can send email via mandrill but I receive email from this fake account (fake@mandrill.com) and if I reply to email I reply to this one.

How can I set smtp for every email but  sender id operator?

Thank you
+David

**Comment by ntozier** [comment]
I think that your going to have to provide screen shots... but cause I have no idea what your trying to ask.  If you reply to a fake email address then you would generate a bounce back.

**Comment by des79** [comment]
Hi ntozier,

I would like to send email via external smtp (mandrill). I created a user with mandrill auth info. But when I open a ticket, email sent by this user for a error on departments setting

**Comment by ntozier** [comment]
I still have no idea what you are trying to ask.  You have not provided us with any errors.
Each email has its own settings at Admin panel -> Emails -> each email.
If you don't want to collect email from an email, don't configure POP/IMAP.
Each Department can have its own outgoing email address.  That's in the department settings.

**Comment by TRBON** [comment]
To solve this you have to manipulate the os_email Table in your Database. 
1. Add the Email which you want to collect the messages. Example support@domain.com
2. Add a new which you want to send the messages. Here you cant use the same email so you type in fake@domain.com. Deactivate that this Email is used for collect messages. 
3. Now delete the Index for the row "email"
4. edit fake@domain.com to support@domain.com. Now you have two email account with the same address in OS. 
5. Set the sending Emailaddress at the sessings of the department.

**Comment by JediKev** [comment]
@TRBON 

That is not entirely true. With v1.14.1 this is a default option. There is a checkbox next to the Auth Required setting that when checked will show username and password box for SMTP. Reference the commit below:
- https://github.com/osTicket/osTicket/pull/5119

Also, I do not recommend deleting the index of any table. Will actually slow performance in some instances.

Cheers.
