### ISSUE TITLE
1.9.5 Feature Request: Custom View Ticket Filters and Persistent Filters

### ISSUE THREAD

**Issue by fictionedge** [osTicket/osTicket#1747]
1. When you create a filter, enter a ticket and leave the ticket the filter is reset. If you ,for instance, view a list of tickets with a certain status and have a few pages of those tickets, you loose track where you where. It would be nice the filter stays active until you reset it
2. Have custom ticket templates and choose a default one, would be a nice way to enter the ticket list and only see the tickets you're most interested (for instance of from a certain department, or with a certain status).

Good job

**Comment by greezybacon** [comment]
The search and sorting configuration is sticky in the `develop-next` branch. We hope to add customizable queues in the further releases

**Comment by fictionedge** [comment]
awesome!
