### ISSUE TITLE
Feature Request: Send KB to Client

### ISSUE THREAD

**Issue by steadhouse** [osTicket/osTicket#1750]
We would find great value in support agents being able to include links to public FAQ articles in their response. Right now, this can happen in one of two ways:

1 - the agent goes to the public osticket side, finds the FAQ, copies the link, pastes it in ticket response
2 - We make canned responses that include these links (but that seems like a large duplication of effort).

I'm not sure what the best way to implement this could be, but perhaps a second drop down near the canned response drop down with either all public FAQ, or the ones that are linked to the current ticket help topic. There would be some preview availability so the agent would know what they were linking.  Additionally - a pop up for the agent to search for a KB and then chose to attach could be useful.

Thanks!

**Comment by greezybacon** [comment]
I agree this would be really nice. I think the popup would make a great interface

**Comment by steadhouse** [comment]
Definitely! If someone comes along that is interested in writing the code, I'd be more than happy to help with testing and documentation!
