### ISSUE TITLE
Searching ticket based on partial keyword

### ISSUE THREAD

**Issue by amsut** [osTicket/osTicket#1751]
It looks like with osticket version 1.9.4 above, the partial keyword function has been removed? In osTicket v1.9.3, if I search for "cert", it will come back with both "cert" and "certificate". Right now I have to type "certificate" to get all result with certificate and if I just type "cert", it will only return result with "cert".

Would it possible to bring the partial keyword search feature back?

**Comment by greezybacon** [comment]
@amsut we've traded one feature for another. < v1.9.4 used MySQL LIKE scanning, >= v1.9.4 uses MySQL full text search. I agree the new search indexing system needs some improvement, however, I had hopes that the MySQL indexing engine would do a better job or word stemming.

**Comment by markus4000** [comment]
In 1.9.8 still not solved. is there a workaround?

**Comment by amsut** [comment]
@markus4000, try to search using * (star) sign.. For example: cert* it should come back with results contain both "cert" and "certificate".

**Comment by barrydegraaff** [comment]
My users also had problems finding stuff with the current search implementation, I created a patch for this. You may want to change/adapt it to suit your needs.

Regards, Barry


https://github.com/osTicket/osTicket-1.8/wiki/Search-Patch-for-osTicket-1.8

**Comment by comfine** [comment]
has anyone tested this mod with v1.10? 
is there a chance that the search after partial words will be implemented? this is really annyoing....

**Comment by barrydegraaff** [comment]
@comfine maybe you can try it, it is not that hard.

In case you have troubles I am happy to help.

**Comment by MaartenJB** [comment]
I've got version v1.10.1 and wanted to test the mod, but apparently the table fields changed from v1.9.x, so unfortunately I could not test it.

**Comment by comfine** [comment]
why are all these bugs simply closed? they are still persist and still annoying!
