### ISSUE TITLE
Attachment problem on Organization creation bug

### ISSUE THREAD

**Issue by agalloway83** [osTicket/osTicket#1758]
Hello!

We’ve noticed that there is a subtle bug when you perform a certain action. We customized the Organization form to include an attachment section at the end to attach documents pertaining to that org. In the normal agent view, when we create a new organization and attach a new file it won’t attach it properly. We have to go back to the already created organization and reattach the document. It works fine after that. Seems to not work on the initial creation of a new organization. Other than the modified form we are running base code with no plugins or code modification.

I would just like to report this as a bug.

Thank you,
Allen

**Comment by greezybacon** [comment]
I believe this is fixed in the tip of the develop branch, as of #1942
