### ISSUE TITLE
User log on

### ISSUE THREAD

**Issue by wfoster** [osTicket/osTicket#1766]
Hi Guys

Could I have the user link straight onto the ticket thread without having to put in any authentication details? i.e. email/ticket number, username/password, etc

We have tons of users connecting and I want them to click a link in the email that takes them straight to the thread.

Thanks

**Comment by greezybacon** [comment]
`%{recipient.ticket_link}` for clients and collaborators

**Comment by wfoster** [comment]
Works 100%. thanks bud. Please excuse taking so long to make resolved. Deepest apologies
