### ISSUE TITLE
Help Topic unavailable in ticket

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket#1768]
1. add Help Topic 1, 
2. add Help Topic 2 set Parent Topic to 1, 
3. add Help Topic 3 set Parent Topic to 2,
4. add Help Topic 4 set Parent Topic to 2,
5. add Help Topic 5 set Parent Topic to 2,
   and etc.

disable Help Topic 2. Help Topic 3,4,5 will unavailable in ticket edit form.

OT 1.9.5.1

**Comment by ntozier** [comment]
That is correct, and how it's intended to work.

**Comment by infectormp** [comment]
but if i do like taht 

add Help Topic 1,
add Help Topic 2 set Parent Topic to 1,
add Help Topic 3 set Parent Topic to 1,
add Help Topic 4 set Parent Topic to 1,

disable Help Topic 1. Help Topic 2,3,4 will **bold** available in ticket edit form.

**Comment by infectormp** [comment]
in my opinion help topic must be available even if parent topic is disabled

**Comment by greezybacon** [comment]
Currently, I see in the code where we cascade the `disabled` flag for help topics. However, I see we fetch the list from the database in the declared sort order, and also assume that parent topics are processed before the child topics. These combined may provide inconsistent handling based on which parent topic is disabled.
