### ISSUE TITLE
Search existing organizations

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket#1770]
Search existing organizations with russian name not work

**Comment by ntozier** [comment]
You may want to include more information such as version of osTicket and a screen shot showing what you are talking about, and any errors.  You should always include full step by step descriptions of how we can attempt to recreate the problem.

**Comment by infectormp** [comment]
you may know i use 1.9.5.1.

add oraganization with russian name go to csp/Users/Organizations - type oraganization name in search box - press search. Result: Search Results: No organizations found!

**Comment by infectormp** [comment]
a have same situation when i press New ticket button and try find user by name. If i search user by email osTicket find user immediately.

**Comment by infectormp** [comment]
Damn, trying reproduce this bug and now all work. Weird.

**Comment by infectormp** [comment]
I reslove this issue

search user and organasation in russian language don't work if i use Preferred Language: English 

if i set Preferred Language: Russian search work perfectly

**Comment by greezybacon** [comment]
That's really strange. But thanks for the additional info. I'll try to replicate it
