### ISSUE TITLE
develeop-next - Helptopic Forms 

### ISSUE THREAD

**Issue by gmt-it** [osTicket/osTicket#1780]
After todays commits its possible to add custom forms. Standard form are not shown in frontend. Deactivation of form fields (Custom form) gives an SQL Error and deleting custom form from the helptopic is not possible.

Deactivation error:
Warning: array_search() expects parameter 2 to be array, null given in /var/www/develop-next/include/class.topic.php on line 445

Warning: array_search() expects parameter 2 to be array, null given in /var/www/develop-next/include/class.topic.php on line 445

![error](https://cloud.githubusercontent.com/assets/10116166/6416733/a8079892-bea8-11e4-945c-dc301472fea3.jpg)

**Comment by greezybacon** [comment]
So this issue is just about the `array_search` warnings?

**Comment by gmt-it** [comment]
If you deactivate a formfield and you save it, it is still activated after reload. If you delete the hole custom form its still there after reload.

**Comment by greezybacon** [comment]
@gmt-it thanks for the clarification

**Comment by gmt-it** [comment]
If you don't add a custom form the standardform is not shown in frontend. I think the standardform should be active if no custom form is added. Or am I wrong?

**Comment by gmt-it** [comment]
For your info: I use a clean install from GitHub zip file.
My configuration:
![config](https://cloud.githubusercontent.com/assets/10116166/6417420/95a1b700-bead-11e4-9436-2fe9700a207b.jpg)
