### ISSUE TITLE
wrong placement of text format buttons

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket#1783]
chrome and firefox

scp/settings/access - edit any template and you get wrong placement of text format buttons
![clipboard01](https://cloud.githubusercontent.com/assets/9958813/6419131/b7b706b0-becb-11e4-807e-efc247b36890.jpg)

**Comment by greezybacon** [comment]
This should be fixed in the `develop-next` branch as the air mode toolbar was retired in Redactor version 10 (merged in the `develop-next` branch)
