### ISSUE TITLE
Future Request: Manage\Help Topics improvements

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket#1788]
- Would be nice implement filter in Manage\Help Topics. Very useful when you need filter Help Topics for specific Department.
- Add export ability to Manage\Help Topics

**Comment by greezybacon** [comment]
@infectormp are you describing a UI listing filter by department?

**Comment by infectormp** [comment]
@greezybacon yes. When you have more then one department it's very hard manage Help Topics.

**Comment by infectormp** [comment]
need filter like in Agents view
