### ISSUE TITLE
inherit departments from parent topic

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket#1797]
1.Add 2 department = testd1 (default) and testd2
2.Create topic topictest1, set department = testd2
3.Create topic topictest2, set parent topic topictest1

in Help Topics view 
topictest1 will have department = testd2 
topictest2 will have department = testd1 

in my opinion when you create subtopic Department must inherit from parent topic.

**Comment by ntozier** [comment]
I think that I see what your saying.
You think that if a parent topic has a department set, if a child department does not have a department set that it should default to the parent.

This is not how it's intended to work at this time.  Each help topic can have its own Department, and unless you explicitly set one, it will default to Admin panel -> Settings -> Default Department.

**Comment by infectormp** [comment]
@ntozier right. But it not very strange have parent and child topic assigned to different Department. Better add option to list *Use Parent Department* like it implemented in Custom Form *Use Parent Form*

**Comment by ntozier** [comment]
Sounds like a good suggestion to me.
