### ISSUE TITLE
Cannot delete organization

### ISSUE THREAD

**Issue by SpudR** [osTicket/osTicket#1810]
Trying to delete an organization the dialog pops up but then 'loading' appears and goes no further.

**Comment by ntozier** [comment]
https://github.com/osTicket/osTicket-1.8/issues/1485#issuecomment-62849687
?

**Comment by greezybacon** [comment]
Lemme guess: IIS. If so, you need to enable the DELETE verb for PHP for the website handling osTicket.

**Comment by SpudR** [comment]
Good guess but no - it's Apache/2.4.9 (Unix)
And the DELETE method is activated
I can delete users...
