### ISSUE TITLE
Dangerous self populaion of definitions with_loadDefaultForm

### ISSUE THREAD

**Issue by krokodylowy** [osTicket/osTicket#1812]
Please remove call to _loadDefaultForm from class.company.php and class.organizatin.php.
Users without privileges can't modify definitions. If admin remove all forms default forms shouldn't be created.
Also so form didn't contains 'lang' column yet an unique index can help 
ALTER TABLE `er_form` ADD UNIQUE (`type`) ;

BTW
In old hosting environment I saw thousands of inserts to form and form_entry_field on each click in osticket pages. Pages wasn't displayed correclty and I removed call to _loadDefaultForm

**Comment by protich** [comment]
Default/core forms are meant to exist -- and are not deletable. The only way _loadDefaultForm get triggered is during upgrade or if you accidentally deleted the forms from db.

**Comment by krokodylowy** [comment]
>or if you accidentally delete the forms from db.
...this is a problem. One more case is : rows exists but engine return nothing.

The point is - calls to _loadDefaultForm are not necessary and can be removed because allows unpriviliged users to create entries in definition.

**Comment by krokodylowy** [comment]
>    or if you accidentally delete the forms from db. 
...this is a problem. One more case is : rows exists but engine return nothing.

The point is - calls to _loadDefaultForm are not necessary and can be removed because allows unpriviliged users to create entries in definition.

**Comment by krokodylowy** [comment]
or if you accidentally delete the forms from db.
    

...this is a problem. One more case is : rows exists but engine return nothing.
The point is - calls to _loadDefaultForm are not necessary and can be removed because allows unpriviliged users to create entries in definition.
