### ISSUE TITLE
Error using osticket 1.9.5.1 behind a ssl-Proxy

### ISSUE THREAD

**Issue by ag-websolutions** [osTicket/osTicket#1817]
**My Serverinformationen**

osTicket-Version v1.9.5.1 (1faad22) 
Server-Software Apache 
MySQL-Version 5.5.40 
PHP-Version 5.4.38-nmm1 

PHP-Erweiterungen
gdlib  Wird für die Bildmanipulation und PDF-Druck verwendet
imap  Wird für den E-Mail-Abruf verwendet
xml  XML API
xml-dom  Wird für die HTML E-Mail-Verarbeitung verwendet
json  Verbessert die Leistung beim Erzeugen und Verarbeiten von JSON
mbstring  Dringend empfohlen für nicht-westeuropäische Sprachinhalte
phar  Dringend empfohlen für Plug-ins und Sprachpakete
fileinfo  Wird verwendet, um Dateitypen für Uploads zu erkennen

PHP-Einstellungen
cgi.fix_pathinfo  "1" wird empfohlen, wenn AJAX nicht funktioniert
date.timezone  Europe/Berlin

Datenbankinformationen und Nutzung
Schema d01baf8b (localhost)
Schema-Signatur b26f29a6bb5dbb3510b057632182d138
Belegter Speicher gesamt 75.25 MiB
Datenbankspeicher für Anhänge 29.42 MiB

I come from Version 1.7.x.
In this old version it was possible to use osticket behind a ssl-proxy.

But on 1.9.5.1 i have several problems:
- on client-side (home, new ticket, etc.) no css-Files and no js-Files loaded
- on scp-side it comes to timeouts or i can't login (after submit the correct name and password the side refresh without an error)

You can test it here:

without ssl-Proxy: http://helpdesk.ag-websolutions.de/
behind ssl-Proxy: https://ssl-account.com/helpdesk.ag-websolutions.de/

To fix the design-Problem on client-side, i edit the bootstrap.php and add this two lines near the end of the file:

**if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER 'HTTP_X_FORWARDED_PROTO']=="https")**
   **define("ROOT_PATH", "https://ssl-account.com/helpdesk.ag-websolutions.de/");**
_// Determine the path in the URI used as the base of the osTicket_

The design-Problem is fixed, but nobody can create a new account, Login or something like this.

It is possible, to use osticket 1.9x behind a ssl-proxy??

**Comment by greezybacon** [comment]
How are you setting this up? It looks like your proxy is not forwarding cookies and it looks like the HTTP server actually serving the HTTP requests needs to advertise itself as `https://ssl-account.com/...`. In Apache, this is the ServerName variable for a VirtualHost

**Comment by ag-websolutions** [comment]
Hi greezybacon,

thank you for your reply!

I only activate the ssl-proxy in the adminstration-panel from my webhoster (All-Inkl).
I can't configure it.

**Comment by greezybacon** [comment]
@ag-websolutions it looks like you should find a new hosting service

**Comment by ag-websolutions** [comment]
smile

all-inkl is here in Germany one of the greatest webhoster.

What surprises me is that the 1.7-version from osticket have no problems with this ssl-proxy. I use this version several years behind the proxy.

**Comment by greezybacon** [comment]
@ag-websolutions I could troubleshoot it with you as a commercial support case. We host the most recent version of osTicket behind a rather complex SSL proxy (although there is no special configuration for osTicket nor any modifications to the source code) without any troubles, so I'm not sure what is broken in the codebase or misconfigured with the SSL proxy.

**Comment by ag-websolutions** [comment]
Thank you for your offer, but i change the system away from ssl-proxy to a full ssl-cert
