### ISSUE TITLE
Crash importing users without an email address

### ISSUE THREAD

**Issue by greezybacon** [osTicket/osTicket#1826]
``` csv
name,email,address
"Jared Hancock",,"Alexandria, LA"
```

results in a backtrace

```
[12-Mar-2015 10:48:20] PHP Fatal error:  Uncaught exception 'Exception' with message 'Attempting to add invalid object to list' in (root)/include/class.orm.php:543
Stack trace:
#0 (root)/include/class.user.php(184): InstrumentedList->add(NULL)
#1 (root)/include/class.user.php(471): User::fromVars(Array)
#2 (root)/include/class.user.php(494): User::importCsv(Resource id #88, Array)
#3 (root)/include/ajax.users.php(295): User->importFromPost('name,email...')
#4 [internal function]: UsersAjaxAPI->importUsers()
#5 (root)/include/class.dispatcher.php(145): call_user_func_array(Array, Array)
#6 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/import', Array)
#7 (root)/include/class.dispatcher.php(120): Dispatcher->resolve('/import', Array)
#8 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/users/import', NUL in (root)/include/class.orm.php on line 543
```

**Comment by agalloway83** [comment]
Hi,

I had a though about this one, I've run into this before. I believe the email address is used as the unique identifier (user name) for the user, you need it to log in from the users side. If you're importing a user with no email address you're creating a user with no user name. I'm not sure how one would get around that, but I've found you can basically omit any field other than email address.

Just some thoughts!

**Comment by robintoy** [comment]
@JediKev has now been reported for abuse due to mass spamming via GitHub

**Comment by JediKev** [comment]
@robintoy 

You can't report someone for batch closing issues my man. If you don't want the emails then turn them off, simple as that :)

Cheers.

**Comment by robintoy** [comment]
batch close is a joke!
you never fixed a single issue and have spiked our filtering platform something nuts for no god damn reason as well as turn my wrist into a vibrator.

I would not mind if you fixed the issues and we had something to read by over 500 "Closed" is more than a joke and almost got our system to automatically report GitHub to the RBLs

**Comment by JediKev** [comment]
@robintoy 

The only way we can deal with that amount of old issues. We never had anyone solely working on managing the Github so issues would pile up and batch closing is the only way.

Cheers.
