### ISSUE TITLE
v1.9.6: staff.inc.php: passwd_text constant contains a misspelled word

### ISSUE THREAD

**Issue by C4RLOCO** [osTicket/osTicket#1835]
The file staff.inc.php has a misspelled word in line 20. 

The correct word is: authentication. Currently says: authenication.

![screen_shot_2015-03-14_at_9_07_32_pm](https://cloud.githubusercontent.com/assets/4073792/6658104/4135bb46-cb35-11e4-9d33-58672075addd.png)

**Comment by ebell451** [comment]
Sent pull request #1836 to fix typo in include/staff/staff.inc.php
