### ISSUE TITLE
v1.9.6: Advanced Ticket Search "Assigned To" and "Closed by" Dropdown Data

### ISSUE THREAD

**Issue by C4RLOCO** [osTicket/osTicket#1854]
System shows the same person twice. One under "Me" the other one under the user full name.

Shouldn't the implementation of "Me" substitute the full name of the user currently doing the search?

![screen_shot_2015-03-17_at_2_58_36_pm](https://cloud.githubusercontent.com/assets/4073792/6695342/f2d70436-ccb6-11e4-8bc7-99d695ff338f.png)

**Comment by infectormp** [comment]
5a07b1a hime "me" only from Assigned To. "me" still exist in Closed by.
