### ISSUE TITLE
New Feature: Backup MySQL Ticket Database within Admin Panel

### ISSUE THREAD

**Issue by C4RLOCO** [osTicket/osTicket#1855]
It would be very nice if Admins could backup the osTicket database directly from the Admin Panel. 

I would say a simple database backup instruction where we could do regular backups, or we could take one step further by enabling automatic backups (say daily, weekly, etc) to a given folder inside the ticket system folder structure. For example:

/db_backup/databasename-03172015.sql
/db_backup/databasename-03222015.sql
/db_backup/databasename-03172015.sql

Where these files are overwritten from time to time by keeping a maximum of 5 previous versions.

**Comment by infectormp** [comment]
Don't think the osTicket need this functionality.

You can use AutoMySQLBackup scripts http://sourceforge.net/projects/automysqlbackup/

AutoMySQLBackup support Daily, Weekly and Monthly backups with rotation.

**Comment by C4RLOCO** [comment]
thanks @infectormp for the link. 

I think a tool developed in house  that can be kept with ongoing maintenances would be preferred instead of relaying on third party tools.

I took a look to automysqlbackup and noticed the last update date is: 2013-05-29

**Comment by ntozier** [comment]
I do not feel that this should not be part of core.
If done at all it would be an ideal plugin.
Backups can be done by CLI MySQL, MySQL WorkBench, and a large variety of 3rd party DB solutions.

**Comment by C4RLOCO** [comment]
It just more convenient, that's all. Going to the the Admin Panel, one click and boom at least you get a manual backup as needed. No need to go with 3rd party apps.

I am talking about simple backups. Not branching the ticket system with a super complicated solution.

**Comment by greezybacon** [comment]
The PHP max execution is going to become a problem on this one. We are working on CLI apps for this since the CLI does not have the max execution time restriction. We've implemented a full import and export for file contents in the most recent release

**Comment by C4RLOCO** [comment]
@greezybacon sorry for my noob question and pardon my ignorance. Where/How can I check the import and export implementations?

**Comment by greezybacon** [comment]
I'm not sure what you mean by "check the ... implementations". You can play around with the file command line tool:

```
php setup/cli/manage.php file --help
```

**Comment by C4RLOCO** [comment]
got it! thank you!
