### ISSUE TITLE
Advanced search with custom field (Checkbox) 

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket#1858]
1.add custom field (Checkbox) to form Contact Information
2.go to ticket, check custom field, save ticket
3.go to Advanced search, check custom field, search

as result we get all tickets but we must get only 1 ticket where we set custom field (Checkbox)

may be related to #1769

**Comment by BobisOnlyBob** [comment]
This issue is also affecting me. A single checkbox-type custom field produces a checkbox in Advanced search that does not affect the search results at all.

**Comment by greezybacon** [comment]
Does this work in v1.10?
