### ISSUE TITLE
Wrong checkbox placement in advanced search 

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket#1859]
Wrong checkbox placement in advanced search for custom field (checkbox)
![adv_serach](https://cloud.githubusercontent.com/assets/9958813/6706832/34ecbf6c-cd72-11e4-8eda-01585fbebbd8.png)

**Comment by cervedgroup** [comment]
try using different browser

**Comment by infectormp** [comment]
@cervedgroup this first that i do.

FF+Chrome

**Comment by greezybacon** [comment]
I'm thinking that the checkbox should not be used here. Instead, a drop-down with options should be used instead:
  * don't care
  * set
  * not set
