### ISSUE TITLE
1.9.6 incorrect sender using %{ticket.staff}

### ISSUE THREAD

**Issue by cervedgroup** [osTicket/osTicket#1861]
If a ticket is assigned to OPERATOR1 and OPERATOR2 insert a reply, the user receive a message 

"OPERATOR1 has updated the ticket with the following response"

this because there is no variable that can be used in Response/Reply template to identify correct staff member that inserted the response and %{ticket.staff} variable refers to OPERATOR1 (that have the ticket assigned)

**Comment by greezybacon** [comment]
Use `%{response.poster}`

**Comment by C4RLOCO** [comment]
Is it possible to add %{response.poster} to the Supported Variables cheat sheet in the Email Template screen?

**Comment by greezybacon** [comment]
@C4RLOCO sure, all things are possible... This should also probably be the default in the template as well.

**Comment by Hannibal226** [comment]
@greezybacon 
Seems to work fine. Changed alls <code>%{ticket.staff}</code> to <code>%{response.poster}</code> now...
