### ISSUE TITLE
v1.9.6: Alerts and Notices, Email not sent to Team Lead on Ticket Re-Assignment

### ISSUE THREAD

**Issue by C4RLOCO** [osTicket/osTicket#1862]
System is not sending emails to Department Manager when a ticket is transferred. However, the assigned agent/team does get the email.

Current configuration is:
![screen shot 2015-03-18 at 9 53 39 am](https://cloud.githubusercontent.com/assets/4073792/6710096/b7847636-cd54-11e4-9a82-c57ed3984634.png)

**Comment by greezybacon** [comment]
This is from `Ticket::transfer`, where the alerts are sent
```php
            //recipients
            $recipients=array();
            //Assigned staff or team... if any
            if($this->isAssigned() && $cfg->alertAssignedONTransfer()) {
                if($this->getStaffId())
                    $recipients[]=$this->getStaff();
                elseif($this->getTeamId() && ($team=$this->getTeam()) && ($members=$team->getMembers↪()))
                    $recipients = array_merge($recipients, $members);
            } elseif($cfg->alertDeptMembersONTransfer() && !$this->isAssigned()) {
                //Only alerts dept members if the ticket is NOT assigned.
                if(($members=$dept->getMembersForAlerts()))
                    $recipients = array_merge($recipients, $members);
            }    

            //Always alert dept manager??
            if($cfg->alertDeptManagerONTransfer() && $dept && ($manager=$dept->getManager()))
                $recipients[]= $manager;
```
I don't spot any issues with this code. Are you sure your department has a manager?

**Comment by C4RLOCO** [comment]
Yes sir, I am actually the manager as well.

![screen_shot_2015-03-18_at_10_38_18_am](https://cloud.githubusercontent.com/assets/4073792/6711048/0ff2e626-cd5b-11e4-9d29-f37c3cd9c3d0.png)

**Comment by C4RLOCO** [comment]
Just did a new set of tests and the result is the same as described above.

**Comment by cervedgroup** [comment]
just tryed in my enviroment, email was sent to dep. manager when ticket was transfered between departments

**Comment by greezybacon** [comment]
@C4RLOCO if you only have one department, how are transferring it?

**Comment by C4RLOCO** [comment]
@cervedgroup thanks for testing it out.

@greezybacon, I am transferring tickets between staff within the same department. For example, when staff within is transferring tickets between themselves (same department), Manager would like to receive an email notification.

**Comment by greezybacon** [comment]
@C4RLOCO pardon my ignorance. Isn't that an assignment?

**Comment by C4RLOCO** [comment]
@greezybacon you are right. I guess I was not clear with the implementation of departments vs teams. In my scenario, there was no team implemented. I was mainly using departments due to the very small team we are.

I will close this for now while i tested again with teams. You have solve this by asking this question: Isn't that an assignment? thanks a lot! :)

**Comment by C4RLOCO** [comment]
I'm re-opening this issue.

After configuring a team, the team lead is not receiving an email alert when the same ticket is re-assigned to a different staff (in the same team).

Current configuration:
![screen shot 2015-03-20 at 7 11 22 pm](https://cloud.githubusercontent.com/assets/4073792/6762354/068b7cde-cf35-11e4-9a0d-493bbec9d896.png)

Scenario:
Staff-A decides to re-assign his ticket to Staff-B. According to the configuration above, Team Leader should receive an email notification about this ticket assignment, however, the system never triggers the email alert for the team lead (new assigned staff receives email alert though, which is OK)
