### ISSUE TITLE
Data protection: option to remove sensitive passwords and attachments from messages

### ISSUE THREAD

**Issue by jochenwezel** [osTicket/osTicket#1863]
From time to time, users submit sensitive data like passwords or confidential attachments into our osTicket system. 

Now we can blame the user, but we can't drop this sensistive information from the ticket any more. The only option is to delete the whole ticket. But then we loose all other information from the ticket, too.

It would be great if (at least) an osTicket admin
1. could drop attachements (with the requirement of an internal note and a list of the names of the deleted attachments as a templated text (or text variable) for that internal note)
2. could edit or drop messages from the customer user (with the requirement of a public note)
3. could edit or drop messages from the staff user (with the requirement of an internal note)

**Comment by C4RLOCO** [comment]
I wish there would be an option where attachments could be restricted completely.

**Comment by jochenwezel** [comment]
@C4RLOCO Your wish might be a separate issue. AFAIK I'd say this is already possible using Admin >> Settings >> Tickets:
![image](https://cloud.githubusercontent.com/assets/3033827/6710488/6a052130-cd81-11e4-888b-d9ae317710c7.png)
just remove the extensions which you don't want. (In case I'm wrong, please report this issue in a new thread. Thank you.)

But now let's go back to the origin intention: if the attachment is already there (and also some sensitive text parts in the message), there should be an option to delete this sensitive information from our server completely. It doesn't make sense to show collegues the passwords of their other collegues for years just because they can access the ticket.

**Comment by ntozier** [comment]
@C4RLOCO your commend appears to be off topic for this issue report.
You can disable attachments.  Admin panel -> Settings -> Tickets -> Attachment [Config] -> [ ] enable attachments.

**Comment by C4RLOCO** [comment]
Thank you both @greezybacon and @ntozier ! Both of your solutions works for me. I remember a few versions ago this was definitely not working as expected. Anyways, I agree my comment was a somewhat off topic. Sorry about that.

**Comment by greezybacon** [comment]
@jochenwezel I agree that editing the ticket thread would be very nice, and providing the ability to manage attachments on the thread and ticket as a whole would also be very nice.

**Comment by jochenwezel** [comment]
> would also be very nice.

in fact, it's a legal topic (at least for us)
