### ISSUE TITLE
v1.9.6: Alerts and Notices, Email not sent to Assigned Staff when another Staff posts a reply 

### ISSUE THREAD

**Issue by C4RLOCO** [osTicket/osTicket#1864]
Scenario:
A ticket is assigned to Staff-A. Then, another Staff (Say Staff-B) posts a reply (not an internal note) to contribute to the ticket.

Results:
The system sends an email only to the user but Staff-A does not get any email alert notification that someone from his team just made a reply.

This situation is leaving the assigned staff (which in this case is Staff-A) out of the loop in the communication.

This is my current configuration
![screen shot 2015-03-18 at 10 03 28 am](https://cloud.githubusercontent.com/assets/4073792/6710313/2070f39e-cd56-11e4-875c-0be2f8c73e53.png)

Now, I understand the New Message Alert is sent out to Agents when a new message from the User is appended to an existing ticket. However, this could be enhanced (or create a new alert) so it can be sent out to Agents when a new message is either from the user or any staff other than the one already assigned to the ticket in question.

**Comment by greezybacon** [comment]
Staff members post **Replies**, not *Messages*. Currently we are looking to expand the "Internal Note Alert" to "Internal Activity Alert", which would include notifications on replies by other agents

**Comment by C4RLOCO** [comment]
excellent!!! thank you @greezybacon

**Comment by greezybacon** [comment]
@C4RLOCO I've openend #1865 with a concept of this feature. I would definitely enjoy your feedback
