### ISSUE TITLE
[Feature request] Ability to make required comments optional

### ISSUE THREAD

**Issue by Chefkeks** [osTicket/osTicket#1872]
Hi guys,

thought a bit about all those people requesting the ability to disable the required comments, e.g. when transferring a ticket to another department or editing a ticket and so on and how this could (easily) be solved...

Instead of requiring the comment(s) there could be an option to "Disable required comments" with a help text like "Disables required comments, e.g. when editing a ticket. Therefore the system automatically adds an internal note to record the changes being made."

So instead of requiring a comment, just let the system analyze/compare the ticket details before and after it was edited and add an internal note to record / document the changes, for example:

```
 SYSTEM
 Agent John Doe edited the ticket. Applied changes:
 Help Topic changed from $OLD_HELPTOPIC to $NEW_HELPTOPIC
```

So, that's the feature request which may will make them happy (and hopefully also you) and maybe it could be expanded with a "Manage" button to allow enabling/disabling the required comments independently (e.g. enabled for editing a ticket, disabled for department transfer).

Cheers,
Michael

**Comment by rp-tech** [comment]
Yes please, this is my #1 annoyance with osTicket right now!

**Comment by mfelber** [comment]
This would be a very nice enhancement. I guess this would make many agents really happy..

**Comment by Chefkeks** [comment]
Just thought "Hey that is a really good idea" lets give a +1 and a thumb up :+1: ... Then ... A few seconds later I noticed it's from myself :D :D

Looks like I'm becoming old... :D

**Comment by ntozier** [comment]
+1 (old man)

**Comment by mfelber** [comment]
@Chefkeks Maybe your getting old but maybe only some parts of your brain have a funny sense of humor (like mine): sometimes I found my money bag (unexpected) in the freezer, sometimes I'm laughing about the funny looking guy on the other side till I notice that’s me in a mirror ;-) Those and many other "surprises" happen during my whole life and I think I’m not the only one. So see it like a undocumented inbuilt entertainment program of your body :-)

**Comment by Pablohn26** [comment]
+1 to this FR

**Comment by Chefkeks** [comment]
Since a lot of comments are optional since 1.10, I'm closing this issue / feature request.
