### ISSUE TITLE
Enhancement idea: Tell the user when browser isn't supported anymore

### ISSUE THREAD

**Issue by cmalbertschw** [osTicket/osTicket#1873]
Hello,

as far as I know, certain browsers are not officially supported by osticket anymore, like IE8. However, IE8 is (unfortunately) still used by some companies. 

I think a nice enhancment would be showing a message for unsupported browsers. It could simply state that the browser the user is using is not supported and ask the user to upgrade to a newer version.

What do you think?

**Comment by infectormp** [comment]
@albertschw just make page that will tell the user when browser isn't supported anymore and setup your web server to redirect users with "bad" browsers to this page

**Comment by albertschw** [comment]
If all people who have Osticket installed are required to create this page themselves then they constantly have to keep track of supported browsers after upgrading the installation. Ultimatively, only the Osticket team knows which browsers are supported or not. I therefore think it'd be better if this kind of page shipped with osticket.
