### ISSUE TITLE
Regex in 1.9.6

### ISSUE THREAD

**Issue by draconis244** [osTicket/osTicket#1874]
Any idea as to why the correct regex of 

^\s*$

is being saved as 

/^\s*$/iu

in the ticket filters ? I'm completely stumped as to why it mangles it

**Comment by greezybacon** [comment]
It's not mangling it. `/` denotes the start and stop of a regex. `iu` are called *modifiers*, and they instruct the system to apply case-**I**nsensitive matching and consider **U**nicode character encoding. Technically speaking, php uses the PCRE (Perl-compatible regular expressions), which in perl, your regex is not correct. It needs the `/` (slash) characters surrounding it.

**Comment by draconis244** [comment]
ahhhh so the form in which it saves it is the correct one for php, so it should work in the filters
