### ISSUE TITLE
v1.9.6: Email Template Sets - Last Updated Date does not update

### ISSUE THREAD

**Issue by C4RLOCO** [osTicket/osTicket#1876]
Just noticed after updating some templates that Last Update information does not update when templates gets modified.

![screen_shot_2015-03-19_at_10_05_29_am](https://cloud.githubusercontent.com/assets/4073792/6732162/3ece48d0-ce20-11e4-8fe0-fca5f8649b88.png)

**Comment by greezybacon** [comment]
We should probably drop that from the UI. Currently there is no way to update the "email template set" — only the individual email templates in the set.
