### ISSUE TITLE
v1.10 feature req: notification via xmpp chat

### ISSUE THREAD

**Issue by mckaygerhard** [osTicket/osTicket#1891]
connect to and users and send messages (firts 30-90 characters) of the current notification but also not only by mail, also by xmpp chat using a general user...

very simple in first phase: only take the title of the ticket/change/internal-note and send also by the xmpp protocol chat using a generic user

in a second phase, use the current usar that already made the ticket/change/note and send the notification using the same id in the xmpp server (if configured as) etc etc

i very interesting in a first phase that only send a notification of the title and fitrs 30 chars to the xmpp server users available as "chat notifications", all the xmpp chat have a "notiofication" service (a global message that all users receive)

**Comment by mckaygerhard** [comment]
why this still are not planning, many issue tracker now has this as a commonly feature, osticket maybe its the only popular issue tracker that not hav!

**Comment by Hamsteren** [comment]
I'm guessing it's not in due to you not making the function ;)
