### ISSUE TITLE
Updating attachments on Canned Responses causes crash (ka-boom!)

### ISSUE THREAD

**Issue by kmmoreau** [osTicket/osTicket#1893]
When editing a canned response and attempting to change the attachment- it will not save. Brings to you a white screen. Now, it will save the text edits but not change the attachment.

**Comment by ntozier** [comment]
White screen generally means that there is a php error.  You would want to consult your php error log and see what the error is.

**Comment by greezybacon** [comment]
I should add this is observed on the `develop-next` branch
