### ISSUE TITLE
API and custom fields issues fix after upgrading to 1.9.6

### ISSUE THREAD

**Issue by zaniwatts** [osTicket/osTicket#1894]
PLEASE NOTE FOR FUTURE VERSIONS:

ERRORS: Contact form did not submit to OSTICKET Unable to create new ticket: validation errors.
0: Serial Number is a required field.

This was fixed with patches in 1.9.2 and later worked in 1.9.3. Since 1.9.3 we have attempted upgrades at each new version with no results. 

I have a custom form: Product Details.
Form Fields:
1) Select Product, Type: Custom List: Products, Visibility: Required, Variable: productlist
2) Serial Number, Type: Short Answer, Visibility: Required, Variable: serialnum

Here is a code snippet of the data posted:
$data = array(
'name'      =>      $_POST['name'].' '.$_POST['surname'],  // from name aka User/Client Name
'email'     =>      $_POST['email'],  // from email aka User/Client Email
'phone'     =>      $_POST['telephone'],  // phone number aka User/Client Phone Number
'country'   =>      $countrylistname, // Country
'subject'   =>      $countrylistname.' - '.$_POST['subject'],  // test subject, aka Issue Summary
'topicId'   =>      $_POST['topic'],  // Topic
'message'   =>      $details,  // test ticket body, aka Issue Details.
'ip'        =>      $_SERVER['REMOTE_ADDR'], // Should be IP address of the machine thats trying to open the ticket.
'countrylist'   =>      $countrynum, // Country (must correspond to custom list entry on OSTICKET (Go to: Manage,Custom list, Items)
'productlist'   =>      $_POST['product'], // Product (must correspond to custom list entry on OSTICKET (Go to: Manage,Custom list, Items)
'serialnum' =>      $_POST['textfield7'], // Serial Number
'attachments' => array()
);

The only way I could fix this is to apply this patch from older version 1.8.
https://github.com/greezybacon/osTicket-1.8/commit/ea9f0c482ca062e5ff4bda0a4a32b5f89d1360e4
I however only applied the patch to include/class.dynamic_forms.php
It breaks if I apply the patch to  include/class.ticket.php

**Comment by ntozier** [comment]
It looks to me like you're getting the message " Serial Number is a required field." because you have set your "Serial Number" field to be required...

**Comment by zaniwatts** [comment]
A serial number does get posted and does have a value in. The problem is that it is not recognized by the API. My custom form fields are not recognized. This is only a problem since I upgraded to v 1.9.6. I had to apply a patch from previous versions that was never implemented in the latest version. To make it work.

**Comment by zaniwatts** [comment]
This patch still worked in 1.9.3, but not in 1.9.4,1.9.5 or 1.9.6

**Comment by greezybacon** [comment]
@zaniwatts there was a blunder with v1.9.6 we have patched in `df5ff0b0003429c633b32bed22e70c2982f1313c` and hope to release a hotfix for soon. Could you try with the tip of the develop branch or by applying that one patch?

**Comment by levillanova** [comment]
@zaniwatts I was having the same problem, then i've changed the requirement field as optional then  setted my custom field variable as number. After that in my form look like this.

            'message'   =>      $mensagem,  // test ticket body, aka Issue Details.
            'ip'        =>       $_SERVER['SERVER_ADDR'],   // Should be IP address of the machine thats trying to open the ticket.
            'topicId'   =>      $destinatario, // the help Topic that you want to use for the ticket 
            'ticketIdAPI'  =>   "0" //this is an example of a custom list entry. This should be the number of the entry.(custom field )

Works perfectly.
Thanks @zaniwatts

**Comment by greezybacon** [comment]
Thanks for the update. I'll add that there's another open issue about `0` not being supported on required fields
