### ISSUE TITLE
1.9.6 Display name format

### ISSUE THREAD

**Issue by cervedgroup** [osTicket/osTicket#1901]
Once again in this release, are present name formatting  issues

if the name format is set to Last, First , a username lilke " Mario Di Rossi " is shown as "Di, Mario" (only in the ticket detail, in the ticket list page is correctly shown)

The setting Last,First is the only one that allow us to have the list of agents (in the trasfer drop down menu), correctly sorted by last name
![ostnf](https://cloud.githubusercontent.com/assets/6535381/6825190/f1310882-d2f8-11e4-9d28-be53b07998aa.JPG)

Another issue, when a staff open a new ticket (following the "new Ticket" link in the scp interface, and wish to select the assignment , the list of the agents is shown in different way then on the ticket transfer dropdown 

![ostnticket](https://cloud.githubusercontent.com/assets/6535381/6825250/702a78ee-d2f9-11e4-937b-72a46e2820bd.JPG)

below is the correct way (we have the "last,first" setting) 

![ostnftransfer](https://cloud.githubusercontent.com/assets/6535381/6825303/ed3169c4-d2f9-11e4-8ef1-f01f9ee24d6f.JPG)

**Comment by lagrenge2** [comment]
This is a small but important issue 

Does any one know where in the code is the Orderby clause to make this?

**Comment by greezybacon** [comment]
@lagrenge2 I agree the sorting should be clear and consistent. In the mean time you might consider the option to restrict assignment by department members in the department configuration. That would help make the list shorter.

**Comment by greezybacon** [comment]
Can anyone verify if it this is properly addressed in #1972?
