### ISSUE TITLE
Regex/PCRE for blank line detection in subject for incoming emails ?

### ISSUE THREAD

**Issue by draconis244** [osTicket/osTicket#1902]
I've been bashing my brains out on the wall over this, I've tried every combination of regex and PCRE to get osticket 1.9.6 to detect a blank subject and reject the ticket, but every single emailed ticket I send at it, it lets it through, I've had a look at the emails with a hex editor and directly after the subject line is the ascii character 20 (decimal) or DC4, nothing after that DC4 

(see screenshot)

![screenshot from 2015-03-25 14 38 22](https://cloud.githubusercontent.com/assets/11556029/6826957/9d684518-d2fc-11e4-888f-007226d68bc2.png)

I've tried trapping that with 

/\x00-\x1f/iu and directly with /\x20/iu  but no it still comes through.....

I know the filtering works because I've got standard filters setup to look for things like sav@ for Sophos antivirus alerts they all seem to be working .....I'm at a loss how to do what should be a very simple filter but my head hurts now..... <grin>

**Comment by greezybacon** [comment]
`/^$/iu`
