### ISSUE TITLE
error: critical wrong rendering in firefox any version

### ISSUE THREAD

**Issue by mckaygerhard** [osTicket/osTicket#1903]
the recent fix of #1828 , and #1853 (oh thanks for that) the fixed commit causes now a new problem:

**taking in consideration that currently i see a commit that firefox v6 to 12 are supported..**
- so then i tested in newer browsers, chromium 28 and chrome 32, renders fine and OK!
- so i tested currently in firefox 7 (icecat gnu), iceweasel 17 and firefox 11, renders with problems
- so then i tested in more newer laste up to " paris a la moda" and works with problems (desing desorganization)

i paste pic about the problem

![error-reporte](https://cloud.githubusercontent.com/assets/1571724/6712261/d035f7f0-cd5d-11e4-8aa6-46716101974c.png)

**Comment by mckaygerhard** [comment]
hello @greezybacon how this issue progress.. 

i'll try to fix and make a pull but my knowlegde about javascript are very poor... i cant see errors in console javascrip

**Comment by novat0** [comment]
i have same behavior in firefox 26, so updated to lasted (37) under windows and same... rendering are strange when see the reports under firefox

**Comment by greezybacon** [comment]
@novat0 what version of osTicket are you using?

**Comment by mckaygerhard** [comment]
any progress here after a complete year waiting!?!?!?! puff
