### ISSUE TITLE
mixing two emails in a ticket

### ISSUE THREAD

**Issue by jardelgn** [osTicket/osTicket#1904]
My system receive a lot of emails at same time and create some tickets using of the title of one ticket and subject of other. I dont know 

Server informations
Version of osTicket v1.9.6 (9adad36)
Software de Servidor Web    Apache/2.2.29 (Amazon)
Versão do MySQL    5.5.41
Versão do PHP  5.3.29

Fetch email by IMAP and the account are in GMAIL

**Comment by ntozier** [comment]
Please post the raw output of the emails with full headers showing and a screen shot of the tickets showing the transposition.

**Comment by cervedgroup** [comment]
maybe someone attach emails as attachment to email and/or use the email of the reply to open a new ticket ?
