### ISSUE TITLE
Print a ticket with a table

### ISSUE THREAD

**Issue by federmoli** [osTicket/osTicket#1905]
Hi, I am new to this forum. I would like to report problems with the printing of tickets that contain tables into the internal notes.
When I create a note (internal or not) with a table of data, the print form result is a mismash.
Following some screenshots how it looks in the thread and printed:

Table insert correctly on ticket
![4d0cf9e726e1453d924f00cd6d42e4](https://cloud.githubusercontent.com/assets/11653029/6832863/4f8f6c54-d329-11e4-9415-8638f4e3623b.png)

Ticket Print result

![90364a7f90c3bcd0a155415ae7ecad](https://cloud.githubusercontent.com/assets/11653029/6832872/5fbbc1a4-d329-11e4-8701-ccf4a1913aef.png)

My version of osticket is 1.9.6  PHP version 5.5.11
Thanks a lot.

**Comment by greezybacon** [comment]
I've seen this before. Thanks for the post
