### ISSUE TITLE
duplicating mails and autoresponses

### ISSUE THREAD

**Issue by harrisyn** [osTicket/osTicket#1908]
After upgrading to the latest version. I get duplicated tickets for the same mail. This is happening very often as well.

Also noticed that reply made to a user who has an auto response set now creates a new ticket for only the auto response mail.

**Comment by harrisyn** [comment]
Any assistance here will be highly appreciated.

thanks.

**Comment by greezybacon** [comment]
@harrisyn I'm not aware of this bug. Can you submit headers and screenshots of an email that was duplicated?

**Comment by harrisyn** [comment]
I am still experiencing this challenge, The screenshot is taken from the db, the headers and all other fields are the same, I am guessing the mail is processed twice.
In trying to fix this, I opted to move mails out of the INBOX into a different mail folder, but the issue still continues.
![image](https://cloud.githubusercontent.com/assets/4963361/8595052/665438c4-2636-11e5-8adf-c29bda48a5b0.png)

**Comment by greezybacon** [comment]
What version is that database snapshot from? Which table?

**Comment by harrisyn** [comment]
this was based on the ticket_email_info table with a join on the ticket_thread table.
the db is MySQL 5.1.41.
what is also strange is it also creates a duplicate of the mail in the mail box. 
i.e. it picks up the mail from the INBOX (only one exists), creates two tickets with the same time and details, then also moves the mail from the INBOX to a different mail folder but creates a duplicate of the same mail in the new folder.

**Comment by ntozier** [comment]
That sounds to me like you have more then one cron running at the same time.

**Comment by greezybacon** [comment]
I would agree with @ntozier

**Comment by harrisyn** [comment]
I am using the internal task manager, and not an externally scheduled cron job.
this is my setting.
![image](https://cloud.githubusercontent.com/assets/4963361/8623029/6d38ce5a-271e-11e5-8de4-ad8024573df3.png)
