### ISSUE TITLE
ticket.recipients.email variable

### ISSUE THREAD

**Issue by JanKraljic** [osTicket/osTicket#1917]
Beside list of %{ticket.recipients} we would like also their email address something like %{ticket.recipients.email}. 

So that at can all Collaborators with email can be written in message.

Keep on the good work. We like osTicket very much, specially due to simple maintance.

**Comment by greezybacon** [comment]
I would vote for `%{ticket.recipients.full}` or something which would expand to `"Billy Jim" <bob@comany.tld>, "Joe Bob" <joe@company.tld>, ...`

**Comment by simonretter** [comment]
I support that!
/Simon

**Comment by Aka4** [comment]
We also are interested in variable `%{ticket.recipients.full}` variable.
We need to notify in emails who received message, our customers complain about lack of this, they don't know who beside them received e-mail.

We would like to add this, could you point us where in the code you create `%{ticket.recipients}` variable?

**Comment by Aka4** [comment]
@greezybacon Any news that`%{ticket.recipients.full}` variable could be added in some next version, or where in the code you create `%{ticket.recipients}` variable?

**Comment by greezybacon** [comment]
It's implemented in v1.10

**Comment by Aka4Code** [comment]
@greezybacon @JanKraljic @simonretter Do you know anything about this feature implementation?

I checked back in 1.10 and now with 1.11 and %{ticket.recipients.full} doesn't exists, it's not implemented as I can see.

When you use %{ticket.recipients.full} then it's the same result as using %{ticket.recipients}.

Maybe there is variable with different name that shows full names with their email addresses ?

**Comment by JediKev** [comment]
@Aka4Code 

The variable to use is `%{ticket.recipients.emails}`.

Cheers.
