### ISSUE TITLE
Feature Request: All Organisations Tickets for Primary Contatcs

### ISSUE THREAD

**Issue by markus4000** [osTicket/osTicket#1928]
It would be fantastic if:
Primary Contacts do have an additional link to the organisations tickets:

Menuline for eg.:

John Doe | profile | my tickets (13) | organisations tickets (89) - Logout

In the "organisations" setting the, admin can define with a checkbox if the Primary Contacts can see all the organisations tickets, or not.

That would be a great feature to manage tickets in teams (on client side).

**Comment by ntozier** [comment]
+1
I like this idea.

**Comment by markus4000** [comment]
It works in 1.10dev so I close it here.
In 1.10 it is possible to share all the tickets to all the members of the Organisation.
