### ISSUE TITLE
Autocomplete in Searchform does not work with custom Ticket Number format

### ISSUE THREAD

**Issue by markus4000** [osTicket/osTicket#1929]
If I choose:
T-###### as number Format

then it generates a ticket:
T-001023

But when start entering T-0... in the search form, it does not autocomplete to T-001023

But without custom number Format, it works.

(OsTicket 1.9.7)

**Comment by greezybacon** [comment]
@markus4000 we recommend adding special chars in the ticket format to the *end* of the format (`######-T` for instance)
