### ISSUE TITLE
Missing Venezuelan Time Zone

### ISSUE THREAD

**Issue by e1th0r** [osTicket/osTicket#1935]
Hi.
According to Venezuelan laws, reflected in http://www.iana.org/time-zonesVenezuela, the official time in Venezuela is -04:30 UTC but this time zone isn't in Osticket.

Best regards
![screenshot](https://cloud.githubusercontent.com/assets/368624/7027576/ea07589c-dd19-11e4-8fc6-f668140c5337.png)

**Comment by ntozier** [comment]
I believe that osTicket gets its timezones from PHP. ( I could be wrong)
http://php.net/manual/en/timezones.php
And the one you listed does not appear to be there.

**Comment by e1th0r** [comment]
If Osticket get the time zone from php, according http://php.net/manual/en/timezones.america.php, then php has the rigth zone from America/Caracas. 

My question is why osticket installer don't get the America/Caracas time zone?

Best regard

**Comment by JensEB** [comment]
osTicket gets its timezone from the DB
You can add your timzone in the table ost_timezone 
copy any record and change...
offset = -4.5
timezone = any Name of the timezone...

Best regard

**Comment by mckaygerhard** [comment]
i want this will added to next, i'm from Venezuelan too and the current timezone does not appears, thanks in advance..

**Comment by greezybacon** [comment]
Sure, @mckaygerhard I'll get right on it

**Comment by mckaygerhard** [comment]
Hello @greezybacon  this issue now can be close! our "great" president changes "again" and now timezone seems are correct! (back to -400)

so this issue about Venezuelan Timezone can be closed!

**Comment by greezybacon** [comment]
This should be fixed in v1.10 by the way
