### ISSUE TITLE
Staff logged out after Advanced Search with large number of tickets

### ISSUE THREAD

**Issue by artefactio** [osTicket/osTicket#1936]
I have identified a session issue affecting v1.9.5.1 version of osTicket and most likely v1.9.7 as well. I haven't seen it being fixed in develop branch.

The issue: staff member is logged out after using Advanced Ticket Search which returned large number of tickets.

How to reproduce: perform a search on a department with large number of tickets (I've done this on a department with more than 100.000 closed tickets). After the search is performed, try to open some tickets.

Reason for this issue is session data truncation, resulting from `session_data` column data type in the database being too small. Since session is used to store the results from advanced search, having too many tickets in it can lead to session becoming corrupted and staff member is logged out.

I have performed the following MySQL command on a live site and it fixed the issue:

`ALTER TABLE ost_session MODIFY session_data MEDIUMBLOB`

I'd like to propose a change in definition of %TABLE_PREFIX%session (file upload/setup/inc/streams/core/install-mysql.sql): `session_data blob` to `session_data mediumblob`

On a side note: I'm new to GitHub so it'll be some time before I start forking. Since I believe this issue is important, maybe someone else from the community can reproduce / verify and include proposed change in osTicket.

**Comment by infectormp** [comment]
Thank you. This fix work perfectly

**Comment by infectormp** [comment]
This solution also fix problem with exporting big list of tickets.

**Comment by markedagain** [comment]
+1 i can confirm this also solved my issue with big query DATA logging users out. It seems the query information is saved in session data :o

**Comment by Cristian-Caipa** [comment]
Excelente, de la que me salvo.
Esa es la solución. :)

**Comment by JediKev** [comment]
Please reopen if this is still an issue with `1.12.x` or `1.14.x`.
