### ISSUE TITLE
ost_user_account table doesnot create default administrator account

### ISSUE THREAD

**Issue by kvvaradha** [osTicket/osTicket#1939]
hi,  i am trying to use OSticket system for my freelancing. but i couldnt  install  it. 

I installed the system.  but it doesnot create the default  administrator account with it. 

Help me to create admin use account manually.

**Comment by Chefkeks** [comment]
Are you sure, you looked at the right table?

The admin/agent accounts are in the "ost_staff" table and not in the "ost_user_account" table ;)
