### ISSUE TITLE
Default language for client area before login

### ISSUE THREAD

**Issue by tahmasebi** [osTicket/osTicket#1940]
When a client see the welcome page, it's English (and I can't find any thing to change default language of this page elements such as menu items and direction), then, user choose language from top-right flags, and the page changes to client language, but after login when user goes logout, the page language changes to English again (default language)
Is there any solution for this problem?
thank you.

**Comment by greezybacon** [comment]
What version are you testing? The flags should appear on the client portal and allow changing the language. The browser requested default is served if possible otherwise.

**Comment by tahmasebi** [comment]
I use osTicket-1.9.7.
Flags appear on client area and they work well, but after logout, page language change to English.
I think browser default language is English and non-English users usually don't change their browser language (if i understood your mean correctly).

**Comment by greezybacon** [comment]
On logout we clear the session, which includes the flag preference. I'm missing what you're suggesting is broken. How should the system work?

**Comment by tahmasebi** [comment]
An example: User language is Persian and selected it from flags and changed the language from profile to Persian, why language should change to English again when user logout?! problem is here.
The system should has a default language, which administrator can change it. for example, if the system default language is Persian, user must see all the system in Persian(without regard to browser language), even after logout or before select a language from flags.    

Thank you

**Comment by ntozier** [comment]
But the system does have a default language... you choose it when you installed.  You apparently picked English.

**Comment by greezybacon** [comment]
@tahmasebi this is implemented in phase III of the multilingual project, implemented in the `develop-next` branch

**Comment by tahmasebi** [comment]
@ntozier, Yes, I choose it, but default language still English in client side. only dynamic contents changed to Persian, and menu items and direction are English.   
---------
@greezybacon, so I'll test it. 

thank you.
