### ISSUE TITLE
New Registration method that is Private but still services ClientCreateRequest's

### ISSUE THREAD

**Issue by Staja** [osTicket/osTicket#1944]
A registration mode that is like "private" but still services ClientCreateRequest's from AuthenticationBackend's with appropriate changes to client-includes to hide registration link.

I've included notes and code on a forum post below, the system I'm working from is not equipped for code-collab/Git
http://www.osticket.com/forum/discussion/85225/ldap-ad-automatic-registration-of-clients-users-on-login

**Comment by greezybacon** [comment]
@Staja you could mail your code to me, jared osticket.com, and I can try and create a pull request from it

**Comment by Staja** [comment]
It's just those 5 changes as described in forum post but I haven't tested it on 1.9.8.1

**Comment by chrismuench** [comment]
Please include this code in the next release.  I spent about 3 hours trying to figure out how to do AD self-registration until I found #2274

**Comment by Staja** [comment]
I wrote [a guide](http://osticket.com/forum/discussion/85969/iis-sso-and-normal-login-no-public-registration-with-automatic-user-creation-on-login) that goes into detail if you're interested.

**Comment by jdelhome3578** [comment]
:+1:

**Comment by greezybacon** [comment]
Shouldn't this just be a function of the plugin? Seems like we should add
an option to the plugin to auto register users, then in the main software,
if registration is requested by the plugin, then it is always allowed.

Am Freitag, 31. Juli 2015 schrieb jdelhome3578 :

**Comment by jdelhome3578** [comment]
:+1:  Sounds good to me
