### ISSUE TITLE
1.9.7 Search still doesn't work

### ISSUE THREAD

**Issue by johnhwyman** [osTicket/osTicket#1954]
I am unable to search for text in the title or body of the various tickets.

**Comment by Aka4** [comment]
Have the same problem, search works in random way - it's working to some keywords, and to some not working. I'm still testing, will give soon more data.

**Comment by Aka4** [comment]
When I tested with MyISAM db schema on MySQL 5.5.41 then search was working in random way.

Now I switched to InnoDB db schema on MySQL 5.6.23 and now when I try to search I have DB Error #1191 Can't find FULLTEXT index matching the column list

![os_ticket_info_page](https://cloud.githubusercontent.com/assets/11789024/7132863/6af64a08-e28d-11e4-8550-ff3d8148b0ee.png)

![error_osticket_search_logs](https://cloud.githubusercontent.com/assets/11789024/7132910/e42e9312-e28d-11e4-81b9-ac5a02324567.png)

![db_search_error](https://cloud.githubusercontent.com/assets/11789024/7132791/dc7b9314-e28c-11e4-86a5-f8fdf5293d5d.png)

Obviously there is something wrong with searching.

http://osticket.com/forum/discussion/85131/keyword-search-in-ticket-subject-or-content-not-working
http://www.osticket.com/forum/discussion/81043/keyword-search-not-working

**Comment by mckaygerhard** [comment]
this are prevously reported by me here: #1832#issuecomment-82494341 in the comment https://github.com/osTicket/osTicket-1.8/issues/1832#issuecomment-82494341 i posted that search always return same results.. either put a work or not ...

seems its a standar error due a bad query.. sure some standars are not follow... in line code of file class.search.php the search query are bad meging: ** COALESCE use in a distinct due return strange results.. ** so this its only a part of the problem, there more but for now this solve a part.. note that in poor os works this but not always due lack of posix, maybe a error of mysql engine under some guindos version, in my case there's no error.. but:

i suggests a subquery, currently i'm investigating a better way ... maybe its better use a count and max around non-null firts ocurrence, the count will use the non-null results

**Comment by Aka4** [comment]
greezybacon made patch for few bugs in search (for me it worked):
https://github.com/osTicket/osTicket-1.8/pull/2111

**Comment by mckaygerhard** [comment]
those patches does not are for the osticket-1.8 brand, are for the unstable and unworking develop brand (and uninstalable now)...

i try to backporting the patches to my instalation but i not got expected results..

**Comment by greezybacon** [comment]
@mckaygerhard I think you're mistaken

**Comment by mckaygerhard** [comment]
i see the "merged" pull and its merged to "develop" brand not "master"

in my instalation of stable 1.9.X the most similar code are under "master" brand, i'll try to backport that pull patches and there's already the commit (and a bit different)
