### ISSUE TITLE
Internal Activity Alerts on Closed/Resolved Tickets

### ISSUE THREAD

**Issue by blueyeguy** [osTicket/osTicket#1955]
When an internal note or message to the user is added to a closed/resolved ticket, and the ticket is left closed/resolved, the Agent/Team previously assigned to the ticket is getting an alert. 

The problem with this happens when the Agents no longer have access to the ticket because it belongs to another department, and they only had access to it through a team assignment. This happens when we have agents covering multiple departments, since they can only be assigned to one.

My understanding was that closed tickets are considered unassigned, and therefore no longer accessible to anyone outside the department to which they are assigned. If they are unassigned and therefore inaccessible, then the Agents should not be getting alerts on them. Or if they are going to get alerts on the tickets, then they should be able to access them even if they remain closed. 

Ideally, we would love for agents to be able to have access to closed tickets in their closed queue that they had access to while open. But we would also like them not to get internal activity alerts on closed tickets, unless that activity reopens the ticket.

**Comment by blueyeguy** [comment]
Should have included the following:

osTicket Version	v1.9.7 (4be5782)
Web Server Software	Microsoft-IIS/7.5
MySQL Version	5.5.39
PHP Version	5.5.23

Thanks,

**Comment by pintraj** [comment]
As an agent, i am not able to see the closed and resolved tickets. can you help me out

**Comment by ntozier** [comment]
@pintraj your comment appears to be completely off topic from this thread.
