### ISSUE TITLE
[New features] not very hard to do :-)

### ISSUE THREAD

**Issue by cervedgroup** [osTicket/osTicket#1957]
Hi, 2 things 
1) Is very important to manage the incident via osticket, the incident management could be done in that way 
 One incident could be linked to 1 or more tickets, when the incident is closed, should be the choice of closing all linked tickets. Also that should be the features of view closed incident and linked tickets. This feature is present in almost all ticketing (not free) systems.
2) It could be usefull to create a personal-customized queues in My tickets queue with the possibility to move the tickets into.This in order to organize the job (for example "Ticket waiting for user" or "Urgent tickets" or "whatever agent want to write...")

**Comment by mckaygerhard** [comment]
hi! its a very good feature request, but u must change the title, please change the title if not nobody will see or noted as seriously.. i recomended a more descriptive title..

about the queues,, this looks like a process flow.. this will raise the osticket functionallity to a more up level... or change all the osticket meaning

**Comment by ntozier** [comment]
I believe that this describes a forth coming feature called "Workflow".  Which should allow one to assign tasks to tickets that will need to be completed.

**Comment by mckaygerhard** [comment]
yes as i posted this described a few the workflow feature, but the issue title does not... i found this only by curiosity... its a great feature so i suggests the title must be changed.

**Comment by ntozier** [comment]
Must?  I think that the word you are looking for is "should".  I personally find it more fitting that the issue just be closed since the feature is already in the works.

**Comment by mckaygerhard** [comment]
I mean the title "is not very hard to do" its not very descriptive .. there are too many issues opened in the git repository and the organization is not a constant here.
If requests here were a little organized, external developers and collaborators would find better in that could collaborate or give tips to help accelerate the work I think is quite noticeable here are a lot of and there are very few manpowers directly working to so many issues opened!

**Comment by ntozier** [comment]
Yes, I'm very aware of what your point was.  However you seem to have ignored mine.

Language like "must" is really not acceptable as you are not an authority to dictate what people must do.  My points were that and this issue report isn't needed as its already being worked on.

**Comment by mckaygerhard** [comment]
well I think what happens is that not like the plain fact that i said, no one would even consider the issue (as many ticket here) until someone touch.. event in some cases event more than two requesters touch the issue reported nobody here take in care, but as I'm not manager here.. ok... as u said.

**Comment by ntozier** [comment]
I have no idea what your first paragraphs is trying to say.  I'm guessing that English is not your first language and there is some sort of language barrier here. Using the word must makes it a requirement, or a demand.  It makes you come across as an authority.  You are not.  Kindly refrain from demanding that others do anything. While I agree that the title is not informative, you do not have the right to tell others what to do.

There is a standard for reporting issues.  We ask that people ask things / report things on the forums.  If the report is substantiated, and replicable we usually ask that they post here (github) or do it for them.  We are not going to police people subjects.

If you want to provide constructive criticism and feedback without demands and without OS bias by all means please do so.

**Comment by novat0** [comment]
@ntozier i do not understant what author said until @mckaygerhard explain a lot.. so its clarelly that its a very disorder in the issues list due that king of behavior when users make a feature request.. **the tittle its too vage..** obvously..

**Comment by ntozier** [comment]
@novat0 that point is not in contention.

**Comment by mckaygerhard** [comment]
1.10 one year from this feature request and still 1.10 not come stable!  we will wait forever true features! **like workflow! that now in any ticket system are common feature**

please! please! (a note, 1200 issues opened where a 40% of them are duplicated and cross same !? are this not desorder!? there a something named tags and labels)

**Comment by ntozier** [comment]
There is no response in this thread indicating when 'workflow' would be added to the system.  So pointing out that it has been a year appears to be offtopic.  As are the rest of your comments.

**Comment by mckaygerhard** [comment]
i mean, there's still many time to comes 1.10 out stable..

when i need some thinks, "goes to 1.10" and 1.10 dont come out yet!

**Comment by ntozier** [comment]
Yes we acknowledge that it has been some time since the last release.
However prior to 1.8 it was usually about a year or more between releases.
And I certainly do not see you helping.

**Comment by mckaygerhard** [comment]
of course.. u dont see!, please can u commit the patch of the open in new window attachments, that was improved with my collaboration and others, and already hav a pull rquest opened?

**Comment by mckaygerhard** [comment]
of course.. u dont see!, please can u commit the patch of the open in new window attachments, that was improved with my collaboration and others, and already hav a pull rquest opened?

**Comment by ntozier** [comment]
Which one would that be?

**Comment by novat0** [comment]
the issue that refers here are #2164 and of course have right! its so easy to include into 1.9 release! just few changes

**Comment by mckaygerhard** [comment]
solved in https://github.com/clonemeagain/attachment_preview where i collaborated
