### ISSUE TITLE
Wrong attachment name in FAQ article

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket#1965]
Test case:
1.Add FAQ article, upload file 1.doc, save article.
2.Rename file to 2.doc
3.Open FAQ article, delete file 1.doc and upload file 2.doc, save article.

In saved FAQ article afttachment will shown as **1.doc**. 

Test case:
1.Add FAQ article, upload file 1.doc, save article.
2.Rename file to 2.doc, open 2.doc and change it, save.
3.Open FAQ article, delete file 1.doc and upload file 2.doc, save article.

In saved FAQ article afttachment will shown as **2.doc**. 

If file was not change OT take name from cache?

1.9.7 ff+chrome

**Comment by greezybacon** [comment]
osTicket de-duplicates the files by their contents. Therefore, the first file that is uploaded is the name that will be used for all future-uploaded files. We are aware of the limitation and are working toward de-duplicating the file contents while also allowing files with differing names to share contents.
