### ISSUE TITLE
Update statistics on ticket delete

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket#1966]
For test purposes i load to osTicket about 2500 ticket, then i delete all ticket but in DB tables ost_file, ost_file_chunk (485Mb), ost_ticket_email_info was not cleared

**Comment by infectormp** [comment]
and need clear Ticket Activity \ Statistics on ticket delete

**Comment by greezybacon** [comment]
The `ost_file` and `ost_file_chunk` tables should be cleaned up with the cron system after a few minutes. The `ost_ticket_email_info` table cannot be cleared because it is the only record of previously-processed emails. Its contents help ensure emails are not re-processed.

The statistics is a good find though. That's a bug

**Comment by infectormp** [comment]
hm, cron system? after several hours ost_file and ost_file_chunk still not cleared. Maybe i miss something?
ost_file have 3,858 rows 
ost_file_chunk have 4,166 rows

**Comment by ntozier** [comment]
Are you not running cron.php on a schedule?

**Comment by infectormp** [comment]
i run api/cron.php to fetch email

**Comment by infectormp** [comment]
@greezybacon ost_file and ost_file_chunk was cleaned up after some time.

**Comment by greezybacon** [comment]
Here's the query from `AttachmentFile::deleteOrhpans`:
```php
    $files = static::objects()
        ->filter(array(
            'attachments__object_id__isnull' => true,
            'ft' => 'T',
            'created__gt' => new DateTime('now -1 day'),
        )); 

    foreach ($files as $f) {
        if (!$f->delete())
            break;
    }   
```
Looks like the files are cleaned up after 24 hours. The delay was added to prevent a race between uploading files via drag and drop plugin (which aren't associated with something in the system until the [Save] button is pressed).
