### ISSUE TITLE
 PHP Warning on delete plugin

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket#1969]
get this when delete plugin 

PHP Warning:  Missing argument 1 for Plugin::uninstall(), called in /xxx/scp/plugins.php on line 40 and defined in /xxx/include/class.plugin.php on line 395, referer: https://xxx/scp/plugins.php?

**Comment by ntozier** [comment]
did you delete the plugin from the file system with out disabling and uninstalling it in osTicket?

reinstall the plugin.
disable the plugin (in osTicket)
tick the check box, click delete (in osTicket)

**Comment by infectormp** [comment]
in get this error in both cases

**Comment by ntozier** [comment]
interesting.  Which plugin?

**Comment by infectormp** [comment]
filesystem
