### ISSUE TITLE
Client UI bug

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket#1970]
Need space between attachment filename and size

![image](https://cloud.githubusercontent.com/assets/9958813/7182436/f6d06702-e459-11e4-97c7-ebaf85a5fb6b.png)

or better show it like this 
![image](https://cloud.githubusercontent.com/assets/9958813/7182489/66f6817e-e45a-11e4-944a-2dac96afb52d.png)

**Comment by greezybacon** [comment]
I think this was fixed in 08e0dc5d64313924d1722c6be9814baa5c361d0a. We need to backport part of that commit to the `develop` branch

**Comment by infectormp** [comment]
fixed

**Comment by greezybacon** [comment]
I want to keep it open to remember to back port it
