### ISSUE TITLE
Future request: Enchantment to Auto Add Members From

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket#1982]
Would be nice add ability set more then one mail domain for organization using delimiter. Very useful if one organization have more then one mail domain or migrate from one domain to another and can send mail from both mail doman some time.

**Comment by greezybacon** [comment]
Use commas

**Comment by infectormp** [comment]
ah ok. Then need add tooltip for this field.

**Comment by greezybacon** [comment]
That's a fair request
