### ISSUE TITLE
[develop-next] Installation fails when using language pack (German) as default language

### ISSUE THREAD

**Issue by Chefkeks** [osTicket/osTicket#1984]
Hey, just having some time to check again at the develop-next version, so I guess some more issue to come, starting with this one here.

My setup:
- Fresh installation (not an upgrade)
-  osTicket develop-next (--> https://github.com/osTicket/osTicket-1.8/commit/3278541f3cefccd2cc2c881da285c79954a043dc)
- ldap plugin
- passthru plugin
- german language pack

When I then tried to install it with German as the default language, the following error showed up:

PHP Fatal error: Uncaught exception 'OrmException' with message 'Group: id: Feld nicht definiert' in /srv/www/htdocs/oscaroo-next/include/class.orm.php:220 Stack trace: #0 /srv/www/htdocs/oscaroo-next/include/class.orm.php(224): VerySimpleModel->get('id', NULL) #1 /srv/www/htdocs/oscaroo-next/include/class.group.php(55): VerySimpleModel->__get('id') #2 /srv/www/htdocs/oscaroo-next/include/class.group.php(148): Group->getId() #3 /srv/www/htdocs/oscaroo-next/include/class.group.php(265): Group->updateDeptAccess(Array, Array) #4 [internal function]: Group::__create(Array, Array) #5 /srv/www/htdocs/oscaroo-next/include/class.i18n.php(78): call_user_func_array('Group::__create', Array) #6 /srv/www/htdocs/oscaroo-next/setup/inc/class.installer.php(158): Internationalization->loadDefaultData() #7 /srv/www/htdocs/oscaroo-next/setup/install.php(52): Installer->install(Array) #8 {main} thrown in /srv/www/htdocs/oscaroo-next/include/class.orm.php on line 220

When using English as the default language everything works fine.

**Comment by Chefkeks** [comment]
Okay, looks like I shall wait since I got a lot of the following issues all across my test installation:
![image](https://cloud.githubusercontent.com/assets/2871833/7247967/653e6a5a-e80f-11e4-8df6-85837109d01b.png)

Looks I need to wait until the develop-next is more stable and bugs are fixed, before I look further into develop-next branch. But overall the changes look good (e.g. new role-based access feature, new timezone settings, etc.) - only thing I do not like is the dropdown to sort the ticket - I personally prefer to hit the header of a table column to sort tickets, since for me it's faster and more intuitive.

**Comment by greezybacon** [comment]
Yes, the phrases on Crowdin will need to be updated to be compatible with `develop-next`

**Comment by Chefkeks** [comment]
Closing this old issue.
