### ISSUE TITLE
KB Error on file upload

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket#1985]
Test case:
1. Create FAQ with attachment
2. Edit FAQ
3. Try add file bigger than allowed size, you must get message File Upload Error - File is too large - Press OK
4. Again try add file but now press Cancel in file dialog, you get message File Upload Error - Your browser is not supported. File added at step 1 disappear from FAQ

1.9.7+chrome

**Comment by greezybacon** [comment]
@infectormp I tried this and can't seem to reproduce it.

**Comment by greezybacon** [comment]
Although I seems I'm having trouble with step one (create FAQ with attachment). Seems after saving and revisiting the page (via edit), the attachment is gone

**Comment by simonretter** [comment]
I have a similar problem. I use the "Ctrnl- V" to paste Pictures directly in the FAQ text.
If I have too many pictures, only some lines of the FAQ are stored and a text like "truncated" appears.
This is not nice, after spending  30min to create a nice FAQ with several screenshots.

**Comment by greezybacon** [comment]
@simonretter, what version of osTicket and what browser are you using? That sounds like a problem that was (attempted to be) corrected a while ago

**Comment by simonretter** [comment]
IE 11 and 1.9.7.

Brand new test 1 min ago.  I included 5 Pictures:

![t2](https://cloud.githubusercontent.com/assets/7000555/7254681/ee1a299c-e844-11e4-9953-2d942ed01e6c.jpg)

**Comment by infectormp** [comment]
look like this is chrome problem. i can reproduce this bug in chrome but not in firefox

**Comment by infectormp** [comment]
video bug report :) https://vid.me/TY0i

**Comment by novat0** [comment]
i have this problem too, with chorme 13 with windows xp and chrome 28 with macosx, i tried in firefox lasted and works very well.
