### ISSUE TITLE
Double text / answers, draft problem

### ISSUE THREAD

**Issue by simonretter** [osTicket/osTicket#1986]
Hi,

I have several people complaining about double text entries. This happens for Clients as well for Agents.
This is not new in 1.9.7. It happened before. Sometime we have hours between the entries.

We run:  osTicket (v1.9.7)
![t1](https://cloud.githubusercontent.com/assets/7000555/7253009/b747b728-e839-11e4-90fe-700587ab906d.jpg)

Our ost_draft table has 6800 entries. Why so much? Ticket drafts > 1 week should be cleaned.. or?

**Comment by greezybacon** [comment]
The draft table is purged for client drafts after a day or so and for agents when a ticket is closed. Do you have a lot of open tickets?

**Comment by greezybacon** [comment]
Are these messages (the blue ones) from email or from posts to the client portal (web)?

**Comment by simonretter** [comment]
Blue text is from the web Interface.

We have 150 open tickets and 6800 entries in ost_draft. But the "Body" is in 99% of the cases empty.
But I have entries with "Body text" closed in January.
