### ISSUE TITLE
open ticket export - last updated incorrect - 1.9.7

### ISSUE THREAD

**Issue by ntozier** [osTicket/osTicket#1998]
Hey all,

I got a report from one of my agents that the Open ticket queue export feature does not appear to record last updated properly.  Here's some images demonstrating the issue.  It appears that the "Last Message" is being used instead of the "Last Response".

look at ticket 593507 which was the ticket we discovered this.
![screen](https://cloud.githubusercontent.com/assets/1315768/7371086/894d2f08-ed8c-11e4-8528-bf41f5dec65a.png)

trimmed down export... look at ticket 593507 and down.
![export](https://cloud.githubusercontent.com/assets/1315768/7371090/8c69b9f4-ed8c-11e4-8481-4c53fbbed260.png)

Tickets Last Message/Last Response
![time](https://cloud.githubusercontent.com/assets/1315768/7371091/8f7f73fe-ed8c-11e4-88d0-2195269c661b.png)

Am I wrong on this?  Is it just status changes that count for Last Updated?  This seems like it might be a bug to me. :)

**Comment by davideakc** [comment]
How have you paginated the exported file in Excel?

I keep getting a .csv file with all the data in one line...

**Comment by ntozier** [comment]
Q: How have you paginated the exported file in Excel?
A: I haven't dont anything special.  I just hit export.

**Comment by davideakc** [comment]
What version of osTicket are you using?

If I hit "Export" it exports a file .csv with something like:

![image](https://cloud.githubusercontent.com/assets/15772383/11065968/746b65b2-87c6-11e5-89e8-a714d384b7c3.png)

It isn't in columns, but it's a single line...

**Comment by ntozier** [comment]
The issue report was opened against 1.9.7 like the title indicates.

**Comment by davideakc** [comment]
It seems that I need to replace the "," with the ";"

Excel automatically make all the informations in columns with the ; symbol

The file to edit is "class.export.php"?

**Comment by davideakc** [comment]
I've fixed it by taking the "class.export.php" of the new version of osTicket (v1.10-rc.2) and adapting the part of the code where there is specified the separator to use.
