### ISSUE TITLE
Organizations not saving changes and attachments.

### ISSUE THREAD

**Issue by agalloway83** [osTicket/osTicket#1999]
I'm not sure if this is a bug or something going on locally. When we go to an organization and edit fields and add attachments, it is not saving the modifications or the attachments. Works fine for users though.

**Comment by agalloway83** [comment]
I want to add, nothing is showing up in the osTicket system log.

**Comment by agalloway83** [comment]
V1.9.7

**Comment by mfelber** [comment]
If I'm not mistaken this fix here #1942 should solve all of this problem..
