### ISSUE TITLE
Feature Request: save/log recipients in each post reply thread

### ISSUE THREAD

**Issue by mfelber** [osTicket/osTicket#2006]
It would be very nice when you always could see in osticket who was adressed in a ticket reply. 

In some cases you can’t. For example you have a collaborators  in a reply and when you later remove him from the Ticket you can't see it in the Ticket that he also was adressed temporary. 

Also it is easier to see in the ticket which reply was send to which recipient for example when you changed the enduser in a ticket.

I guess one option to make it more transparent is to write the recipients into the corresponding reply thread.

What do you think?

Another option would be a similar feature like the raw email header feature in develop-next just for outgoing messages. But I don't know if it is realistic to implement that in osticket.

**Comment by greezybacon** [comment]
I agree, it would be nice to add a column to the `%thread_entry` table and record a list of user ID's of the collaborators enabled at the time the outbound mail was generated.

**Comment by mfelber** [comment]
Feature was implemented in osTicket 1.10 👍
