### ISSUE TITLE
spread ticket between stuff users

### ISSUE THREAD

**Issue by berezuev** [osTicket/osTicket#2015]
Hi.

Is there any way to spread tickets between some group of stuff "fifty-fifty"?
For example, I have 3 supporters and categories "foo" and "bar"...
First ticket in this categories is going to Staff1, second to Staff2, etc.

**Comment by infectormp** [comment]
@berezuev - you can set Staff in category properties. If ticket created with this category it will assigned to Staff automatically

**Comment by infectormp** [comment]
Round-robin algorithm not implemented in OsTicket as i know

**Comment by ntozier** [comment]
This is not currently a feature of osTicket.  I am also not aware of plans to implement it.

**Comment by berezuev** [comment]
I've writed simpliest plugin for this. 
Hope, this will be helpful for somebody: https://github.com/berezuev/osticket-spreader
