### ISSUE TITLE
Edit priority text or translate it correctly.

### ISSUE THREAD

**Issue by PeopleInside** [osTicket/osTicket#2017]
From the Admin panel i see is impossible to edit text of Priority status.

For example "Low" priority is the same in Italian and i want translate in "Bassa" but that is no possible

**Comment by ntozier** [comment]
I believe that this will also be covered in 1.10 when it is released.  The multilanguage feature is still being worked on and is currently in Phase III (Peter said that there would be 4 phases).

**Comment by greezybacon** [comment]
I agree additional priorities and translations would be nice

**Comment by MarcoArdito** [comment]
I'm setting up a demo install for other colleagues, trying to translate everything in Italian and also adapting some default text to our specific needs... it is difficult, atm. I started exporting it.phar to a regular folder (include/i18n/it_IT) so to be able to modify things easily there, and now I was looking for a way to translate priorities...

Until there's not a better alternative, I found that the ost_ticket_priority db table has a "priority_desc" field where each code-defined  (english) priority string can be translated to whatever (of course this allows for only one possible translation site-wide, I guess).

**Comment by greezybacon** [comment]
@MarcoArdito yeah, I agree, we really need a list manager for the priorities

**Comment by balojs** [comment]
@greezybacon  @rayfoss  pleasee check this request
