### ISSUE TITLE
1.9.4: DB Error #1062 

### ISSUE THREAD

**Issue by C439MK** [osTicket/osTicket#2019]
Hello,
After receiving the above error notifications intermittently for a number of months a quick search of the internet shows many fairly logical conclusions that someone is trying to update / insert a user with an email address that already exists.

My concern is that these actions should be being processed gracefully by something like a check of the database before the update / insert action. This way, the user can be warned of the problem and self correct and the error emails can be limited to actual errors that are cause for concern.

**Comment by ntozier** [comment]
I could be wrong, but I was of the opinion that this was already fixed in newer versions...
