### ISSUE TITLE
Email notification of new ticket is base64 as text as body of email.

### ISSUE THREAD

**Issue by dchurch24** [osTicket/osTicket#202]
So far, the notification by email of new tickets arrives as such:

 boundary="=_aaf0944733c21794124a87ce504ea129"
MIME-Version: 1.0
From: "Support" xxxxn@xxxx.com
Date: Thu, 21 Nov 2013 11:00:52 +0000
Message-ID: yy0EKPipQy81P6PZ-xxxx@xxxx.com
X-Mailer: osTicket Mailer
In-Reply-To: ULwval6NRRrih12I-iHErUEA@7b72e90c10
References: ULwval6NRRrih12I-iHErUEA@7b72e90c10
Return-Path: www-data@LBLASHSVN.ccleurope.xxxx.net
X-OriginalArrivalTime: 21 Nov 2013 11:01:30.0823 (UTC) FILETIME=[0895F570:01CEE6A9]

--=_aaf0944733c21794124a87ce504ea129

Content-Transfer-Encoding: base64

Content-Type: text/plain; charset=utf-8

LS0gZG8gbm90IGVkaXQgLS0KCltpbWFnZTpvc1RpY2tldCBMb2dvIChrYW5nYXJvbyldCgpXZSdy

ZSBIZXJlIEZvciBZb3UKLS0tLS0tLS0tLS0tLS0tLS0tCiAqRGVhciBEYXZlIFNtaXRoLCogCgog

Q29tcGxldGUuIAoKCllvdXIgQ0NMIElUIFJlcXVlc3QgVGVhbSwgCi0tLS0tLS0tLS0tLS0tLS0t

LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t

LS0tLS0tLS0tLS0tLS0tLQoKV2UgaG9wZSB0aGlzIHJlc3BvbnNlIGhhcyBzdWZmaWNpZW50bHkg

YW5zd2VyZWQgeW91ciBxdWVzdGlvbnMuIElmIG5vdCwgcGxlYXNlIGRvIG5vdCBzZW5kCmFub3Ro

ZXIgZW1haWwuIEluc3RlYWQsIHJlcGx5IHRvIHRoaXMgZW1haWwgb3IgW2xvZ2luIHRvIHlvdXIg

YWNjb3VudF0gZm9yIGEgY29tcGxldGUKYXJjaGl2ZSBvZiBhbGwgeW91ciBzdXBwb3J0IHJlcXVl

c3RzIGFuZCByZXNwb25zZXMuIApbW2ltYWdlOlBvd2VyZWQgYnkgb3NUaWNrZXRdIF0oaHR0cDov

L29zdGlja2V0LmNvbS8pCgotLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t

LS0tLS0KW2xvZ2luIHRvIHlvdXIgYWNjb3VudF0KaHR0cDovL2xibGFzaHN2bi90aWNrZXQvdXBs

b2FkL3ZpZXcucGhwP3Q9NzE4NTYyJmU9ZHNtaXRoM0BjY2xpbmQuY29tJmE9ZGIxZWM0M2E3ZDhh

Y2NlYWIyCjNjYjVkYzg1YTZmOWU3

--=_aaf0944733c21794124a87ce504ea129

Content-Type: multipart/related;

 boundary="=_8e483d3fc4dca752f555e6bc19f3e353"

--=_8e483d3fc4dca752f555e6bc19f3e353

Content-Transfer-Encoding: base64

Content-Type: text/html; charset=utf-8

PHAgc3R5bGU9ImRpc3BsYXk6bm9uZSI+LS0gZG8gbm90IGVkaXQgLS08L3A+PHA+PGltZyBzcmM9

ImNpZDo2ZmUxZWZkZWEzNTc1MzRkMjM4Yjg2ZTc4NjBhN2M1YUBiOTdiNzJlOTBjMTAiIGFsdD0i

b3NUaWNrZXQgTG9nbyAoa2FuZ2Fyb28pIiB3aWR0aD0iMTEzIiBoZWlnaHQ9IjY0IiBzdHlsZT0i

ZmxvYXQ6IHJpZ2h0OyB3aWR0aDogMTEzcHg7IG1hcmdpbjogMHB4IDBweCAxMHB4IDEwcHgiIC8+

IDwvcD48aDM+PHNwYW4gc3R5bGU9ImNvbG9yOiByZ2IoMTI3LCAxMjcsIDEyNyk7IGZvbnQtd2Vp

Z2h0OiBub3JtYWw7IGZvbnQtZmFtaWx5OiBHZW9yZ2lhOyBmb250LXNpemU6IDMwcHQiPldlJ3Jl

**Comment by PenziSu** [comment]
Hi All 

I got the same issue that "The blank message body" by Exchange SMTP Server.
but, when I am sending Email by Gmail SMTP Server , everything is fine.
my environment:
CentOS-6.6
PHP-5.3.3
osTicket-1.9.4

I am trying to two way resolved issue:
1. include/class.mailer.php line 140 to $mime = new Mail_mime("\n");
>> Good and Work!!
2. I had download and replace the class.mailer.php into include folder.
>> I got the error message below, But, still worked!!
"PHP Warning:  constant(): Couldn't find constant SUHOSIN_PATCH in /var/www/html/helpdesk/include/class.mailer.php on line 125"

**Comment by greezybacon** [comment]
@PenziSu you should be able to use the new MAIL_EOL setting in the config file to permanently set the end-of-line to "\n"

**Comment by PenziSu** [comment]
@greezybacon YES! It is Worked! Thank you :)

**Comment by heinztomato** [comment]
I installed osTickets a few days ago and had exactly the same issue. #442 was correct (sort of) but the line number does not fit to the current osTicket - version anymore.

So my suggestion (which does mainly the same as mentioned in #442)

search for $mime = new Mail_mime($eol); and insert $eol="\n" before it so it looks like this afterwards:

$eol = "\n";
$mime = new Mail_mime($eol);

**Comment by greezybacon** [comment]
@heinztomato please use the new MAIL_EOL setting definable in the `ost-config.php` file since v1.9.3 or so.

**Comment by shoan** [comment]
I am having a similar problem with 2 osticket installations that email each other. I have set `define(MAIL_EOL,"\n");` in ost-config.php in both the installations. But yet, the processed emails result in tickets with no body/thread content when the email originates from the other installation. 

One installation is v1.9.7 and the other is v1.9.12

**Comment by greezybacon** [comment]
> no body/thread content when the email originates from the other installation.

You will need to configure differing reply separator tags for each setup. Neither should contain the characters of the other.

**Comment by ordonezgs** [comment]
I have the same issue on v1.16.1 after I have upgraded from 1.14.
