### ISSUE TITLE
Karen's WISH LIST of Friday Features

### ISSUE THREAD

**Issue by kmmoreau** [osTicket/osTicket#2025]
- [ ] Add a Delete Button at the bottom of the Ticket Queue

**Comment by Chefkeks** [comment]
At the bottom?
Have to ask why the button above the ticket queue isn't enough? ;)

**Comment by Chefkeks** [comment]
Or do I miss something here? :D

**Comment by greezybacon** [comment]
Karen's use case is that her page size is set to like 50 or 100 or something. If she's reviewing a bunch of tickets which are possible junk from the queue, if she reaches the bottom, she would have to check a few boxes and then scroll all the way back up to click [Delete] or [Change Status] or something. It would be nice to have the buttons available lower on the page.

After discussing internally, we like the idea of floating the buttons bar when scrolling through the ticket queue, and repeating the feature when viewing an individual ticket. That way the buttons available at the top of the ticket-view page are accessible after scrolling to the bottom

**Comment by greezybacon** [comment]
This is addressed in #2043
