### ISSUE TITLE
Save draft in custom forms

### ISSUE THREAD

**Issue by S0lidARRAY** [osTicket/osTicket#2027]
In open a new ticket page for users. When you have too many fields in custom forms and you mistype just a single words, Then everything gets deleted is kinda annoying. Is there any way to save input data in custom forms like the one in Ticket Details section? Thanks.

**Comment by greezybacon** [comment]
How does everything get deleted?

**Comment by SolidK0RE** [comment]
For example, If I forgot to fill required fields like this one and hit submit.
![forget to fill](https://cloud.githubusercontent.com/assets/9249682/7536517/bcf5b63c-f5ba-11e4-8d3f-a156fc62a11a.JPG)

Then BOOM! everything in custom form will get deleted and I have to retype them again.
![deleted](https://cloud.githubusercontent.com/assets/9249682/7536522/c8e531fc-f5ba-11e4-87a0-7715b4a10f5d.JPG)
