### ISSUE TITLE
Missing or invalid data - check the errors and try again - No errors on page.

### ISSUE THREAD

**Issue by dchurch24** [osTicket/osTicket#203]
Hi,

I have a form with many custom fields - some of which are marked as required.

This was working fine up until around 30 minutes ago. I have not changed any config.

All mandatory fields have an entry in them, and are of the correct type and format (email addresses, etc...).

![screen](https://f.cloud.github.com/assets/368795/1591991/1f105784-52b3-11e3-9520-e23e5d5d7351.png)

**Comment by imasc** [comment]
Actually, there was an internal note that had to be filled - 
Internal Note: Reason for editing the ticket (required)
