### ISSUE TITLE
Feature Request: Status Colours?

### ISSUE THREAD

**Issue by simonnzg** [osTicket/osTicket#2034]
My people have asked if there's any way that a ticket can have a colour assigned to it depending on its status, i.e. red for new, amber for assigned, green for closed, or similar. 
Am I the only person who's asked about this, or is it because my lot can't read so have to look at the colours? ;-)

**Comment by greezybacon** [comment]
@simonnzg you're honestly the first to bring this up. Currently we have colors for priorities, but we haven't made those editable yet

**Comment by PeopleInside** [comment]
Nice! +1

**Comment by simonnzg** [comment]
I think they were partially looking for a way of identifying the status of a ticket at a glance from the default "Open Tickets" list. There's no column for Status, merely the priority and who it was assigned to, so rather than have another column, they wanted a coloured background, or maybe a coloured icon that they could use to visually sift what kind of state the open tickets list was in. Having used osTicket for a while, I can see what they mean: there's not enough information presented to work the way they do. 
We use osTicket to manage a queue of requests for coordination with our telecomms links from wind farm developers, giving the developers the opportunity to herd their requests and us the ability to keep tabs on the progress through our coordination process, so it's not exactly a classic helpdesk application, but close. So, the colours are also for use by the developers when they check their list of applications to see what's happening. A kind-of traffic light colour scheme (clear, not clear, in queue, in progress), so we're not talking of a rainbow of colours.
It's all way beyond my basic grasp of PHP, but I'm learning all the time!

**Comment by PeopleInside** [comment]
An example can be Hesk, in Hesk every status can have different color :) with mod for hesk you can also choose, customize the colour of each statuses :)

**Comment by rossum** [comment]
It would be wonderful to be able to have ticket status displayed on the ticket list, and to be able to sort based on that field.

**Comment by JediKev** [comment]
You can create Custom Statuses and with Custom Columns/Custom Queues you can set Conditions for a specific Column:
<img width="448" alt="Screen Shot 2019-12-03 at 12 50 46" src="https://user-images.githubusercontent.com/11823401/70080107-96287680-15cb-11ea-8c6f-4ec09f5e176f.png">

**Comment by AndyHorb** [comment]
@JediKev where I can setup what you show? Can't find the view that you posted.

**Comment by mlipok** [comment]
https://**MAINURL**/scp/queues.php?id=1#columns

![image](https://user-images.githubusercontent.com/11089482/115007884-c617a780-9eaa-11eb-87d8-5d30f7a74ccb.png)

**Comment by AndyHorb** [comment]
Thank you so much! You're my hero today :-)

**Comment by simonnzg** [comment]
Pity I left that employer a few years back. They still use OST, but have *never updated it* since I left!
