### ISSUE TITLE
Feature request: Upload max file

### ISSUE THREAD

**Issue by PeopleInside** [osTicket/osTicket#2037]
In the attachments insert a text who alert the user of max upload file allowed.

When client open a new ticket up to the drop file here a text who indicate to the user the maxximum file size allowed.

**Comment by ntozier** [comment]
When someone tried to upload a file that's too large they get a message saying "File is too large".

**Comment by PeopleInside** [comment]
Yes.

**Comment by JediKev** [comment]
Implemented in later versions. File picker restricts files that are too large so they cannot select an attachment that is too large.
