### ISSUE TITLE
Feature Request / Question : add authentication to API

### ISSUE THREAD

**Issue by yadimon** [osTicket/osTicket#2040]
Hello, i want to add authentictation to api calls.
i m not sure where to put it.
if i do it like API key, the login name and password should be in the header.
if the values are in the body, the access check will be process in TicketApiController::createTicket()?
as optional parameter? + add setting for it for the user? (like "api reqire authentication" checkbox)
Or what s the best way to implement it?

**Comment by JediKev** [comment]
API access is base on a Key that is tied to an IP address. The only way someone can utilize your API is if they are using the same IP that the Key is for and if they have your Key.
