### ISSUE TITLE
System Information: Add "alt" text for icons

### ISSUE THREAD

**Issue by Chefkeks** [osTicket/osTicket#2047]
A lot of users at the forum tend to copy their osTicket system information - unfortunately the icons (checkmark / warning sign) are not copied and since there is no "alt" text / attribute you can then only guess what php extensions ok and which are missing:

![image](https://cloud.githubusercontent.com/assets/2871833/7581202/4d09861e-f880-11e4-8588-1d0af5b5b112.png)

Would be great when you could add a alt text - would have done a PR, but couldn't find the right spot to add the alt text. I think something like "1" and "0" or "Yes" and "No" should be enough - so that there is not a need for new translations just because of the alt text.

Thanks,
Michael

**Comment by greezybacon** [comment]
That's a really good idea. Looks like the alt text [won't work in most browsers](http://stackoverflow.com/questions/4925463/how-different-browser-perform-when-copying-and-pasting-alt-text-in-the-img-tag). Perhaps we could just add the word `missing` somewhere if the extension isn't available.

**Comment by Chefkeks** [comment]
Haven't tested it with older browsers, but in current browsers (IE11, FF38, Chrome42) it works good (tested it with this one: http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_image_test), but anyway, I agree that the word missing is a good idea. (Btw. how do you do that a word appears with that special grey background here on github?!)

Maybe you should add a column for the icon / status and display the icon / status there, e.g.:
gdlib | Missing | Used for image manipulation
imap | OK | Used for email fetching
