### ISSUE TITLE
Issues with pasting Excel tables into Web Forms

### ISSUE THREAD

**Issue by J-Ocampo** [osTicket/osTicket#2051]
We are currently running into an issue with internal customers pasting Excel tables into Web Form requests. When attempting to paste an Excel table into the form, it will lose its format making it a jumbled mess.

Is there any fix for this?

**Comment by ntozier** [comment]
I'm not aware of this ever being a feature, so I don't believe that there would be a fix for it.

**Comment by greezybacon** [comment]
@J-Ocampo what version of osTicket are you using? Can you provide a link to such a spreadsheet so I could attempt to test?
