### ISSUE TITLE
[Internet Explorer] Unable to go back when "Printing ticket" in Agent Panel

### ISSUE THREAD

**Issue by yalg** [osTicket/osTicket#2053]
when we print , PDF replaces the page, but it is impossible to go back.

Adding a setting "open in new window " ?

**Comment by greezybacon** [comment]
> it is impossible to go back

What happens?

**Comment by yalg** [comment]
The history arrows are disabled when the PDF is open, so we don't be able to go back in the ticket.

It seems to be an IE bug.

However , even without this bug , users do not think to come back when they are in the PDF, they close the tab, and should reopen osTicket.

I think that adding an option " Open in new window " that would correct all the problems simply.

**Comment by greezybacon** [comment]
@yalg I agree. This has been addressed already in the `develop-next` branch
