### ISSUE TITLE
Custom field needs to be populated for closure

### ISSUE THREAD

**Issue by hawkhead99** [osTicket/osTicket#2061]
This is more of a request then an issue, but - 
On the 1.10 release notes - "Fields can be marked for required for closed. Therefore they can inhibit closure of a ticket without a valid value."

What if when you go to close the ticket - an in-line popup displays giving the user the opportunity to populate a required field (so they don't have to go into the edit screen).  I am wondering how practical it would be to use this new feature for setting a "resolution" before closure, but I don't want users to have to go to the edit screen every time before closing a ticket

If that is not really what the custom field is designed for, I can work on a pull request that includes setting a resolution capability if you feel that would be a good addition?  I have it as a mod for 1.9.7 already (http://osticket.com/forum/discussion/85479/add-resolution-to-ticket-upon-closing)

**Comment by infectormp** [comment]
@hawkhead99 - fully agree with you.

**Comment by infectormp** [comment]
Working with ticket fields very good implemented in spiceworks. you not need every time edit ticket to set topic and other required fields. very useful.

**Comment by greezybacon** [comment]
It seems like a link on the warning banner which triggers a pop-up edit would be a nice solution

**Comment by hawkhead99** [comment]
@greezybacon I agree, that could work well! :)  The only thing to consider is what would it do if you are doing a mass-close instead?  

So, with that solution still in mind, I assume there would be an array of ticket id's for links to a popup edit for each ticket that is being requested to be closed and is missing a required field?  That might still be a little more time consuming for the user, but would be faster then having to re-open each ticket with the problem.

**Comment by greezybacon** [comment]
@hawkhead99 I disagree with the option for mass actions. Selecting multiple tickets would likely include differing data required for closing.

**Comment by hawkhead99** [comment]
@greezybacon  wouldn't what I suggested factor that in though?  Of course I probably did not describe it well.  In the case of mass closure - it would list all the tickets that can not be closed due to data being required first (instead of just one like in the case of closing a single ticket through the view UI).  So a user would have to click on each ticket in the warning banner and edit the required data fields (through the popup edit).  That would take care of the fact that each one might have different required data.  Or are you suggesting that the edit screen would not give enough information for someone to populate those fields through a mass-close without looking at the ticket first?

Either way, it is not a bid deal for our company either way because one of the first things I always get requested to do on a new release is remove the change status buttons from the ticket list screen all together to make sure they do not accidently close someone elses ticket in the same department. I just wanted to bring up that scenario as well :)

**Comment by JediKev** [comment]
Implemented in later versions with Inline Edit feature.
