### ISSUE TITLE
dpr: Ticket Filter: Add Filter Actions

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket#2070]
Add Filter Actions: Set Help Topic

PHP Fatal error:  Class 'HelpTopic' not found in /xxx/include/class.filter_action.php on line 397, referer: https://xxx/scp/filters.php?a=add

**Comment by mfelber** [comment]
I can confirm that this issue occurs in 1.10 when you add the filter action "Set Help Topic". The Screen only shows "Loading" and when you save only a white page is shown:
![screenshot](https://cloud.githubusercontent.com/assets/5539456/7665266/f3a1619a-fbaf-11e4-8fb2-c46dc34d02ef.jpg)
The same error message is in the error log of the web server.
