### ISSUE TITLE
SQL schema utf8 -> utf8mb4

### ISSUE THREAD

**Issue by TinoDidriksen** [osTicket/osTicket#2074]
Any reference to MySQL's utf8 charset and collations should instead use the utf8mb4 versions. The old utf8 charset simply cannot store all Unicode code points, but the utf8mb4 versions can.

**Comment by greezybacon** [comment]
@TinoDidriksen I like the way you think; however, `utf8mb4` isn't available until MySql 5.5. Currently osTicket requires 5.0. We'll have to bump the requirements first
