### ISSUE TITLE
Registration confirmation link issue

### ISSUE THREAD

**Issue by eduardvilchuk** [osTicket/osTicket#2090]
I have installed osTicket v1.9.4 (c18eac4). Recently there appeared an issue, when someone is trying to register. User receives an email with link to confirm the registretion. When he opens the link, it show screen with password reset instead of confirmation screen. 

Here's what the email says
We've created an account for you at our help desk at http://marenno.com.

Please follow the link below to confirm your account and gain access to your tickets.

http://marenno.com/pwreset.php?token=lkbNeK0lhfPIa.DdcLEXzX4v.qdeBNCq9LwJusoqQMZVoMGs

Your friendly Customer Support System

**Comment by greezybacon** [comment]
@eduardvilchuk have you considered upgrading to v1.9.8.1 first?

**Comment by eduardvilchuk** [comment]
Not yet. Do you think it might help?

**Comment by greezybacon** [comment]
@eduardvilchuk even if it doesn't, you'll have trouble applying a fix I might suggest on an older code base

**Comment by eduardvilchuk** [comment]
@greezybacon ok, I will make upgrading right away. I will let you know, if it helps. Thanks

**Comment by eduardvilchuk** [comment]
@greezybacon I made an upgrade, and unfortunately this doesn't help. What should I try next? Thanks

**Comment by infectormp** [comment]
@eduardvilchuk i check my instalation and in confirmation email i get same link https://xxx/pwreset.php?token=atGcPylEFWiogNg9_uAxKr95Dafvo0whC0SeN0Wd00hm5_Qs but i not see any problem. When i go to this link my browser open page https://xxx/account.php?confirmed where i see message about my accout activation. 

@eduardvilchuk You see this screen?
![image](https://cloud.githubusercontent.com/assets/9958813/7734192/01ca2ffa-ff3d-11e4-8a6a-abe9763da975.png)

**Comment by eduardvilchuk** [comment]
@greezybacon yes, exactly. I see the screen with "forgot my password"

**Comment by infectormp** [comment]
@eduardvilchuk it's look like you have alredy activated account. What Registration Method set in Settings\Access and Registration Required is checked or not?

**Comment by eduardvilchuk** [comment]
@infectormp here is the screenshot with end user registration settings 
![screenshot_2](https://cloud.githubusercontent.com/assets/12512496/7810216/c9c32fb0-03a8-11e5-9ddc-2819e23c2d2b.png)

The problem is that each user that just registered opens this link. They can't see email confirmation page at all

**Comment by triagehhardy** [comment]
I am having the same issue on 1.9.11 im not sure why it is linking a password reset and not confirmation.. i cant get any of my users logged on this way.

**Comment by lfgoulart** [comment]
I have the same issue on v1.10. Someone know how to manually fix it?

**Comment by aalamgeer** [comment]
I have attached a screen shot below, I am getting a error message "Account confirmation required " during check my ticket status.

![image](https://user-images.githubusercontent.com/20042487/43717798-40de2ec4-99a6-11e8-8e7f-93b5fb9f8cac.png)

**Comment by ntozier** [comment]
@aalamgeer Your logging in as a user.  Did you click the registration link in the registration email sent to your user accounts email address?

**Comment by aalamgeer** [comment]
@ntozier Thanks for instant reply,
I am not getting any registration email on my user address.

**Comment by ntozier** [comment]
Then it sounds like you are having an email problem.  If you do not click the registration link in the email then your account is locked until you do.  You can resend it though.

**Comment by aalamgeer** [comment]
"Account confirmation required " error comes only for the one user, Rest users can view his own tickets status by email id and ticket number.

**Comment by omfgabcdefg** [comment]
@eduardvilchuk  did you found the solution for the broken link? I am having the same issue. After clicking the link it will not load or nothing will appear at all.
