### ISSUE TITLE
dpr: request predefined tasks in helptopic

### ISSUE THREAD

**Issue by markus4000** [osTicket/osTicket#2093]
It would be geat if it would be possible to define tasks in the helptopic. So everytime a ticket from helptopic x comes in, it adds the predefined tasks x1 x2 x3 to that ticket ...
so we could use it like a workflow. A ticket starts a row of tasks.
+1 :-)

**Comment by protich** [comment]
This is in our todo list -- we're calling the feature __Canned Task__.

**Comment by markus4000** [comment]
Thank you. Looking forward to that

**Comment by greezybacon** [comment]
Seems like we should keep this open and continue the discussion

**Comment by markus4000** [comment]
Hi, is it allready in RC1 ? Or still on the todo list? Looking forward to it.

**Comment by philbertphotos** [comment]
Has any development been done on this as yet?

**Comment by ntozier** [comment]
Doesn't look like it.

**Comment by kest874** [comment]
@greezybacon has done some work here: https://github.com/greezybacon/osTicket-1.8/tree/feature/canned-tasks I've not tested any of it.

**Comment by philbertphotos** [comment]
I will take a look thanks

**Comment by greezybacon** [comment]
I opened a pull request #2901 with some screenshots and some testable code

**Comment by ntozier** [comment]
@f3000 You can't find them in any version.  This feature is here on github.  You've posted to the threads about it.  The pull Request for inclusion is at: https://github.com/osTicket/osTicket/pull/2901

Side note: Please refrain from asking the same question on three different threads.

Q: Is this feature included in 1.10?
A: No.  It is also not included in 1.10.1.  This is an open feature that has not been merged with the main branch at this time.
