### ISSUE TITLE
User and Organization ticket filter options do not work when target channel is email

### ISSUE THREAD

**Issue by blueyeguy** [osTicket/osTicket#2094]
If the Target Channel is set to one of the system emails, it appears that the information used to match the criteria must be included somewhere in the actual email message (header, subject, body, etc.), and that it will not check outside of the email message for information to match on.

Even though the email at some point is then matched to a user, this does not appear to happen before the filtering therefore the ticket filters for user or organization related information are not working.

osTicket Version    v1.9.7 (4be5782)
Web Server Software Microsoft-IIS/7.5
MySQL Version   5.5.39
PHP Version 5.5.23

**Comment by ntozier** [comment]
This sounds like a chicken and egg situation to me.
Email does not have user or organization data as that's tied to the user account.
(ie there is no ticket yet, so no user, so no results.)
@greezybacon ?

**Comment by blueyeguy** [comment]
After upgrading to 1.10 this appears to work now. We can use a users organization in a ticket filter to assign tickets to the correct department and team.
