### ISSUE TITLE
dpr: Your lock is expiring soon

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket#2107]
I think this question has two answers: Yes and No. But why here is only OK?

![image](https://cloud.githubusercontent.com/assets/9958813/7760071/3c28772c-0020-11e5-90d7-34a6f207b35f.png)

**Comment by greezybacon** [comment]
I vote to remove the dialog altogether

**Comment by Chefkeks** [comment]
@greezybacon
Agree. Either renew the ticket lock automatically or release it in the background.

**Comment by infectormp** [comment]
+1

**Comment by greezybacon** [comment]
@Chefkeks it is renewed automatically in the background during agent activity (such as typing a response). This dialog happens during inactivity like when spacing out or answering a phone call

**Comment by ntozier** [comment]
How is the time til display of this dialog box determined?
Is it a based on a percentage of the value at Admin panel -> Settings -> Tickets -> Agent Collision Avoidance Duration?

I agree that this is an annoying pop up, but I'm not sure that getting rid of it is the right move.  However allowing admins to configure if it should be displayed might be ideal.  Or have a more interactive [similar to Banks] time out that triggers when there is say 20 seconds left and counts down unless the user intervenes.  [if they do not intervene then the system might even want to log the user out]

**Comment by greezybacon** [comment]
@ntozier its (expiration_time - 30 secs). I like the idea of the countdown, and when the countdown expires, change the popup to say that the lock has expired and change the buttons to indicate attempting to re-acquire the lock. I would also like to see the lock system change so that the lock is not acquired until the agent starts typing the response. That way the box will never be seen unless the agent has started *using* a lock

**Comment by Chefkeks** [comment]
@greezybacon
Sounds really good with <i> using </i> a lock and reminds me a little bit house it's handled with a lot of office applications for example. As long as you have not changed anything it opens normally, but once another user is editing it you'll see that little popup message telling you that user A is editing the file currently already. So really like to see such a mechanism in osTicket too.
