### ISSUE TITLE
Option to enable/disable "Verify Email Addresses" for form fields using email validator

### ISSUE THREAD

**Issue by Chefkeks** [osTicket/osTicket#2108]
Just stumbled across an "issue" with the new option:
<i>Verify Email Addresses: Verify email address domain<i>

Basically everything is OK with the new option, but for our use case I miss an option to disable email verification for specific form fields.

So let me explain why:
We have a custom form to be filled out when one of our users want us to register a domain, e.g. "oscar-the-kangaroo.com". In that form we also have a required field asking for the email address that should later then be used for the requested domain, e.g. "info@oscar-the-kangaroo.com". Since the domain is mostly not registered and available there is no MX record etc. so that the email validator of the form field will tell me that it's not a valid email address.

Makes totally sense, but for that use case when a custom form field has the email validator it would be nice to enable/disable email verification. I don't know how common our use case is and if it really makes sense for you to add such an option to enable / disable email verification for single form fields, but I thought that I am maybe not the only one that wants email verification in general, but not for all form field with an email validator. 

Anyway, I solved this now by switching to a custom regex validator, but wanted to report back too ;)

Cheers,
Michael

**Comment by infectormp** [comment]
@Chefkeks your decision switching to a custom regex validator was best solution :)
