### ISSUE TITLE
Future request: Close ticket by URL

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket#2114]
Would be nice add ability to close ticket by user when he open special URL.  

`Your problem was solved if you happy press here [URL to close ticket]`

When he go to this URL open page some page 

`Your problem was closed`

**Comment by greezybacon** [comment]
:+1:

**Comment by greezybacon** [comment]
I also think we should add ability to close to the client web user interface

**Comment by Chefkeks** [comment]
@greezybacon 
Agree and have a suggestion for that: In "Admin Panel > Tickets" there is currently the option "Allow Client Updates". Maybe add a "Config" button there and let the osTicket admins configure what they want to allow the end user at the portal (closing tickets, editing tickets, etc.).

**Comment by lehha** [comment]
+1 to have that link to Staff (Agent) e-mail templates.

**Comment by dmnc-net** [comment]
+1 for the idea but not just url in the email template. It would be nice if client/user may close own ticket from the ticket detail (web), at this moment just reply is possible.
