### ISSUE TITLE
Image Copy + Paste is not working in IE10

### ISSUE THREAD

**Issue by ramdaffodilsw** [osTicket/osTicket#2115]
Image copy paste is not working in IE10. Though there is option to insert image from insert image button but we need Copy + Paste image also like in other browsers.
Please suggest.

**Comment by greezybacon** [comment]
It was my understanding that copy+paste did work in IE. What version of Windows and osTicket are you using?

**Comment by ramdaffodilsw** [comment]
I am using windows 7 and ostickets 1.9 version. Though it's working in IE 11 and other browsers(crom, firefox) except IE10.

**Comment by rayfoss** [comment]
#3481 duplicate, this is being worked on...
