### ISSUE TITLE
FAQ <-> Canned Response sync / duplicate

### ISSUE THREAD

**Issue by greezybacon** [osTicket/osTicket#2130]
A thought on the FAQ/Canned response front. It would be very helpful to be able to check a checkbox in an FAQ to make it a canned response. The current method AFAIK is to replicate the FAQ in the Canned Responses. The checkbox method would allow us to have only a single document that served as both. If that is not possible then instead of a checkbox at least make a button in the FAQ to create a copy for you in the Canned Response.

**Comment by ntozier** [comment]
oh I like that it!

**Comment by infectormp** [comment]
:+1:

**Comment by Chefkeks** [comment]
+1 from my side too

**Comment by infectormp** [comment]
@greezybacon some time FAQ can be very big and send a lot of text to user not good idea, may be it's possible add variable that will return link to FAQ? Then will be possible add this variable to Canned response and send user only link to FAQ.

**Comment by infectormp** [comment]
If add variable field to FAQ, variable in canned response may look like #%{faq.variable}

**Comment by greezybacon** [comment]
What about adding a "summary" text area to the FAQ editor, which can be used as a teaser when the FAQ is shown in the listing on the category page. It would also allow the FAQ article to be used as a canned response. Furthermore, when used as a canned response, the summary text could be used followed by a link to the full article.

**Comment by Chefkeks** [comment]
> What about adding a "summary" text area to the FAQ editor, which can be used as a teaser when the FAQ is shown in the listing on the category page. It would also allow the FAQ article to be used as a canned response. Furthermore, when used as a canned response, the summary text could be used followed by a link to the full article.

My first thought was like "Hmmm and what if there is no summary created? - or is the summary then required?" followed by the second thought "But basically the idea is pretty cool, but the suggestion to use variables %{faq.some_faq_var} is also pretty cool". So I'm undecided here so far, but generally I welcome any improvements to the kb / canned responses :)

**Comment by ntozier** [comment]
We could auto populate the "summary" field using the first paragraph (or first X # of words) of the FAQ as the summary.  Once it's saved then if edited the summary field would appear and be editable (ie both, but save peoples time by auto-populating it)

**Comment by greezybacon** [comment]
> but the suggestion to use variables %{faq.some_faq_var} is also pretty cool"

I haven't seen that in this thread, but I'd really like to see custom data properties at the category level and then definable for each FAQ in each category

> We could auto populate the "summary" field using the first paragraph (or first X # of words) of the FAQ

I like the automated option
