### ISSUE TITLE
Save text reply on session problem

### ISSUE THREAD

**Issue by lehha** [osTicket/osTicket#2139]
When write a ticket reply, session may goes bad (change ip/vpn, cookies, etc), and situation on my previos version (1.7-rc3) was terrible - after submit I've got a login form with message "Authentication required" or broken CSRF Token.

Is it possible to insert a visible textarea field in auth form with writen text reply? So if there are auth problem, reply not to lose and is available for copying. May be it was fixed in next version?
I've see ajax verify before submit in old version, but in some situation it's not helping...

**Comment by greezybacon** [comment]
The current version, since v1.8.1 or so, has draft saving support if that would help

**Comment by ntozier** [comment]
Also 1.7-rc3 is ancient.  You should consider upgrading [at least to a non Release Candidate].
