### ISSUE TITLE
Change Request: team assignment alert 1.9.8

### ISSUE THREAD

**Issue by markus4000** [osTicket/osTicket#2140]
If you disable assignement alert "for this Team"
but a teamleader is defined. The teamleader doesn't receive an alert on team-assignment!

![05-06-_2015_10-50-40](https://cloud.githubusercontent.com/assets/4391014/8002711/650e234c-0b71-11e5-9736-77e498761a00.png)
![05-06-_2015_10-55-10](https://cloud.githubusercontent.com/assets/4391014/8002712/65119752-0b71-11e5-94ba-0ce68f65e2c0.png)

but the leader should receive a message on teamassignment, even if the team alert is desabled.

**Comment by ntozier** [comment]
My understanding is that specific always over rides general.
So Teams and Departments would override and suppress the alerts [if ticked] since they are specific.
Admin panel -> Settings -> Alerts & Notices is general.

**Comment by protich** [comment]
@markus4000 - Neil is correct in that, disabling assignment alert for the Team means alerts for all members -- including team lead. That said, I see the value of your desired outcome and will consider allowing disabling at team level to be specific.

**Comment by markus4000** [comment]
In older versions that point was diffrent.i made the update from 1.8.3 to 198... in 1.8.3 it was possible to send alerts dor some teams only to the teamleader and for some to all the team members.

It would be an enhancement, if it would be possible to define a deputy and as soon the leader is in holiday, the deputy gets the messages...

Next; it would be good when an agent can set a flag in his preferences; i'm on holiday, my deputy is: ...

And that stays active until the next login of the agent that is in holiday....

**Comment by markus4000** [comment]
Team alert works now in 1.10 it is possible to choos for every teammember, if he receives alerts or not.
:+1:
