### ISSUE TITLE
Cannot create dynamic changing  dropdown in Forms/ Custom form / Custom list

### ISSUE THREAD

**Issue by gokulaprasanna** [osTicket/osTicket#2146]
I am using osTicket-v1.9.7 . I cannot create multiple dynamic dependent dropdown in forms. i can get only one dynamic changing dropdown by creating a custom form and assign that form to helptopic. For EX: I need like when u select any helptopic in end user it should got to  category dropdown and if you select any option in category it should go to subcategory dropdown likewise.

**Comment by infectormp** [comment]
@gokulaprasanna i think you can do this because this not implemented in osticket.

**Comment by ntozier** [comment]
@gokulaprasanna This is not a feature of osTicket at this time.
