### ISSUE TITLE
BUG: Troubles with Canned Response and "ticket.VARIABLES"

### ISSUE THREAD

**Issue by markus4000** [osTicket/osTicket#2147]
the canned response with thicket.variables do not work proper.
Some variables work and some do not. it doesn't matter if they are from a custom form or from the ticket form.
V: 1.9.8 updatet from 1.8.3

**Comment by infectormp** [comment]
Can you post more details? What variables do not work?

**Comment by markus4000** [comment]
I have acustom form with variables. (around 20 fields)
![field automation](https://cloud.githubusercontent.com/assets/4391014/8053573/3dcce394-0e92-11e5-8e53-fbefe01a6cb1.gif)

then I use the %{ticket.VARIABLE} in the canned response.
eg. %{ticket.objektname} works
%{ticket.VerkEmail} does not work.
but both fields are filled out by the client.

**Comment by infectormp** [comment]
can you try rename VerkEmail to verkemail and test canned response again?

**Comment by infectormp** [comment]
What type of custom filed you use for VerkEmail and objektname?

**Comment by markus4000** [comment]
if I choose "small letters" , then it works!
So there is a BUG only with capital letters.

**Comment by mfelber** [comment]
@markus4000 Why do you think this is a bug? The help tips are showing only examples with lowercase variable names, also in the forum there are hints to use lowercase names for variables: http://osticket.com/forum/discussion/comment/94124/#Comment_94124 . So this seems to me by design..

**Comment by Chefkeks** [comment]
In my opinion it's not a bug, but it can annoy you a lot since uppercase characters are not automatically converted to lowercase what I would assume when hitting the save button. Btw is there any obvious hint that you cannot use uppercase chars?

**Comment by mfelber** [comment]
@Chefkeks I have not seen any obvious hint till now. But I think also it would be nice to prevent this situation. Maybe a direct hint in the help tip or a validation during saving the variable (with a corresponding error message why it could't been saved when uppercase letters are used).

**Comment by greezybacon** [comment]
I'm thinking this is a bug either in the UI, the help text, or the variable system. It seems that as it is it is misleading. I think it should work both as written in the "Variable" text box and lower case as well.
