### ISSUE TITLE
Custom user fields ignored when submitting ticket via API

### ISSUE THREAD

**Issue by snizzleorg** [osTicket/osTicket#2148]
when creating a ticket via the API customer user fields seem to be ignored. no error is produced but the corresponding field is not filled in.

custom fields for the ticket details are working.

v 1.9.8.1

**Comment by infectormp** [comment]
@snizzleorg you add custom filed to user? What field type you use? You set filed variable?

**Comment by snizzleorg** [comment]
yes:

```
$data = array(
    'name'      =>      'John Doe',  // from name aka User/Client Name
    'email'     =>      'john@picoquant.com',  // from email aka User/Client Email
    'phone'     =>      '1234567890',  // phone number aka User/Client Phone Number
    'position'  =>      1,
    'subject'   =>      'Test API message',  // test subject, aka Issue Summary
    'message'   =>      'This is a test of the osTicket API',  // test ticket body, aka Issue Details.
    'ip'        =>      $_SERVER['REMOTE_ADDR'], // Should be IP address of the machine thats trying to open the ticket.
        'topicId'   =>      '1', // the help Topic that you want to use for the ticket 
        //'Agency'  =>          '58', //this is an example of a custom list entry. This should be the number of the entry.
        //'Site'        =>              'Bermuda'; // this is an example of a custom text field.  You can push anything into here you want
    //'attachments' => array()
    'CustomerCountry' => 'Germany',
    'system_serial' => '1000000'
);
```

and of course the variables are set in the User-Form

while ```system_serial``` (a ticket custom field) is working neither phone (phone number) nor position (List), nor CustomerCountry (Short Answer) are filled in ...

**Comment by infectormp** [comment]
Filling field with List type via API not work for me when i try import ticket from other system.

**Comment by snizzleorg** [comment]
yeah but for me even the text type (short answer doesn't work) either when it's a Contact Information Field.

Ticket Detail Fields seem to work

**Comment by infectormp** [comment]
What version do you use?

**Comment by snizzleorg** [comment]
v 1.9.8.1

**Comment by infectormp** [comment]
can you post screenshot of your variable here?

**Comment by snizzleorg** [comment]
see above

**Comment by infectormp** [comment]
look like API respect only field in ticket and custom form

**Comment by greezybacon** [comment]
I believe there was a bug concerning custom data via the API addressed in v1.9.9. Is this still broken?

**Comment by snizzleorg** [comment]
Have to update first. once I get to it I'll let you know.

**Comment by opodecano** [comment]
Hi, i have the same problem. version of OsT is 1.9.8.1
if the custom var is in first position the value are not saved in ddbb..
![screenshot_3](https://cloud.githubusercontent.com/assets/11027530/8504044/e603df78-2197-11e5-93e6-cbed0fc64551.jpg)
![screenshot_4](https://cloud.githubusercontent.com/assets/11027530/8504045/e6050470-2197-11e5-89b8-8af8453d809d.jpg)
![screenshot_5](https://cloud.githubusercontent.com/assets/11027530/8504046/e6184e90-2197-11e5-9c4e-247c2a890989.jpg)
![screenshot_6](https://cloud.githubusercontent.com/assets/11027530/8504043/e5ffeeea-2197-11e5-850f-64e8bd505d48.jpg)

**Comment by greezybacon** [comment]
@opodecano I am confident *that* was fixed in the `develop` branch

**Comment by opodecano** [comment]
Tnx greezzy..!!
