### ISSUE TITLE
Untranslatable strings

### ISSUE THREAD

**Issue by avoidik** [osTicket/osTicket#2150]
http://jipt.i18n.osticket.com/scp/templates.php?tpl_id=1
**Agent Email Templates** and **End-User Email Templates** headers

http://jipt.i18n.osticket.com/scp/settings.php?t=pages
**Client**, **Staff** and **Logo** column headers

http://jipt.i18n.osticket.com/scp/profile.php
**Ext** (after phone number)

http://jipt.i18n.osticket.com/scp/dashboard.php
Inside Agent tab **No data for this timeframe found** and **Export**

http://jipt.i18n.osticket.com/scp/lists.php
**Custom Lists** header

**Comment by greezybacon** [comment]
Thanks for the report
