### ISSUE TITLE
Reply/internal note/status change resubmission with F5 page reload

### ISSUE THREAD

**Issue by Aka4Code** [osTicket/osTicket#2151]
When we send Reply/internal note/status change and then when we press page reload button or F5 button then the same data are resent.
Could you prevent this? http://stackoverflow.com/questions/3923904/preventing-form-resubmission

![image](https://cloud.githubusercontent.com/assets/11789024/8059279/5f0a50c8-0ebf-11e5-8f44-5711a4c01bbc.png)

![image](https://cloud.githubusercontent.com/assets/11789024/8059282/63f5ed2c-0ebf-11e5-87e2-03c941d6f6b7.png)

![image](https://cloud.githubusercontent.com/assets/11789024/8059285/68a2da60-0ebf-11e5-8659-468c4cebfa86.png)

![image](https://cloud.githubusercontent.com/assets/11789024/8059289/6cae5576-0ebf-11e5-8ad9-0c7712cca132.png)

![image](https://cloud.githubusercontent.com/assets/11789024/8059305/8a4ab78c-0ebf-11e5-9e59-bed6f27def34.png)

**Comment by Aka4** [comment]
@greezybacon Could you fix this with upcoming 1.10?

**Comment by greezybacon** [comment]
@Aka4, sorry, this will still be a problem for the first release of v1.10. Guess we'll still have more work to do
