### ISSUE TITLE
Feature request: Filter Actions

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket#2155]
Would be nice add ability to set field content in Filter Actions

Filter Actions:
Set Field => Some ticket field=> Some field content

**Comment by ntozier** [comment]
I think that would be a neat feature.  +1

**Comment by greezybacon** [comment]
I totally agree. I have thought this would be really nice to combine with the regex feature to allow matches in regex to be applied:

`Issue Summary` / `Matches Regex` / `Test Ticket, Field1=(?P<field1>\w+)`

Then,

`Set Field Value` / **Field**: Ticket Details / Field1, **Value**: %{field1}

**Comment by infectormp** [comment]
@greezybacon totally agree with you.

**Comment by balojs** [comment]
+1
