### ISSUE TITLE
/js/redactor.min.js blocked by firewall

### ISSUE THREAD

**Issue by insidenothing** [osTicket/osTicket#2156]
Just to let everyone know up-to-date Sonicwall IPSs will block /js/redactor.min.js causing the page to hang, F5 or ESC to make page usable. Just wanted to document in case anyone else has an issue.

Browser "net::ERR_CONNECTION_RESET" caused by Sonicwall IPS #2057 for "Obfuscated HTML Code -l 11"

Disabling Sonicwall IPS #2057 is a temporary fix. 

...but should they really obfuscate their code and call in 'min.js'?

**Comment by ntozier** [comment]
That sounds like a question for the folks who write redactor.
http://imperavi.com/redactor/

@greezybacon is this something that you can write an upstream ticket for?

**Comment by protich** [comment]
@ntozier -- Just for the record we have an OEM license on redactor. It's not free!! It's also the reason they have it obfuscated. Any issues related to it doesn't necessarily mean osTicket users should contact them -- they don't provide downstream support for our users.

**Comment by ntozier** [comment]
@protich I get that, but @greezybacon has opened tickets with them in the past for issues reported for users.  Which is why I asked if this was one of those things. :)

**Comment by protich** [comment]
I know.... I was specifically responding to the first part of your post. 
> That sounds like a question for the folks who write redactor.

Thanks and my apologies!

**Comment by greezybacon** [comment]
@insidenothing I think permanently disabling that rule would make sense for me. It's a sad day in the security world when we think that obfuscated javascript code is a threat to computing security. Perhaps if you return the SonicWall today you could still get a refund...
