### ISSUE TITLE
Team Assigment/Reassignment bug?

### ISSUE THREAD

**Issue by stf675** [osTicket/osTicket#2158]
version 1.9.8.1

When reassigning Team assigned ticket to an agent (same or different team)

resulted ticket "Assigned To:"  shows ticket assigned in the following format:

Agent Name / Original Team Name

(Team name is in Database record for that ticket).  Is it by design, or is it a bug?

**Comment by ntozier** [comment]
Tickets can be assigned to both an Agent and a Team. 
If its assigned to an Agent, and then assigned to a Team its now assigned to both.  It does not remove the assigned Agent.
If its assigned to a Team and then to an Agent its now assigned to both. 
This is by design.
