### ISSUE TITLE
Feature Request: FAQ Update History

### ISSUE THREAD

**Issue by markus4000** [osTicket/osTicket#2159]
I'd be nice to have an edit history for the knowledge base.

**Comment by greezybacon** [comment]
I agree. I'd like to see some sort of versioning with approval as well. It would be nice to be able to revert between versions and have states like some sort of quasi published which might work with the translation system to allow a new version to be "published" but translated before being visible to the public.

**Comment by Chefkeks** [comment]
@greezybacon Good to know, since I did a few another mockups of a possible slightly knowledge base revamp with such a history feature. Hope to finish them soon and send them over to y'all ;)

**Comment by markus4000** [comment]
@Chefkeks : do you have some results?

**Comment by Chefkeks** [comment]
@markus4000
Since that was 1 year ago,  think I had some results which I shared via email with the osTicket developers, but never released to anyone else. If you're still interested, I could share the mockups here on github.

**Comment by JediKev** [comment]
Implemented in later versions with Audit Log plugin.
