### ISSUE TITLE
Feature Request: Companies in new version

### ISSUE THREAD

**Issue by AlexYoung28** [osTicket/osTicket#2166]
Can we allow this to be more multiple company friendly, i.e. when you create a new ticket you can see which company the user is with, also in the dashboard can we see the company in that list? or at least make it easier for us to add extra fields in and populate them?

If you want any screenshots of what i mean i'll try but hopefully makes sense what i mean?

**Comment by greezybacon** [comment]
You can add a custom field, or use the Organization feature, right?

**Comment by AlexYoung28** [comment]
Well once you use the organisation feature it dont seem to appear unless you go into the user, ill double check tomorrow.

It would just be handy to either have a custom ticket list to display company or any of the custom fields.

**Comment by Chefkeks** [comment]
I guess it's either too late here already or I don't get it currently. Can you show me with a screenshot what exactly you're suggesting?
Thanks!

**Comment by infectormp** [comment]
If i understand right, @AlexYoung28 ask to show related to user fields in ticket form. 

Something like this: User A have organization B, now i put some variable to ticket form like ```%user.org.name``` where org = organization table in db and name = name filed from organization table. 

This can be used to add any custom filed to display in ticket form: ```%user.org.field``` where field = field\custom_field name form organization table or ```%user.field``` where  field= field\custom_filed name form user table and etc.

**Comment by AlexYoung28** [comment]
Ah ok that sounds a bit like what i want, ill do some screens of what i mean as might help me get pointed in right direction tomorrow when back in the office

**Comment by AlexYoung28** [comment]
![companynew](https://cloud.githubusercontent.com/assets/6728021/8543279/aac240cc-2493-11e5-89c9-b269c3878830.JPG)

This is roughly what i'm after from the ticket dashboard, is it in the pipeline to add the ability to add fields to the Ticket Dashboard?

**Comment by greezybacon** [comment]
So this is a request for custom columns in the ticket listing pages? (We call them queues)

**Comment by AlexYoung28** [comment]
Ah ok sorry yes basically that is what i would like dunnonif anyone else agrees

**Comment by greezybacon** [comment]
@AlexYoung28 I agree with you, this would be a nicety. I think we're going to try and tackle it for the custom queue feature in v1.11, but no promises.

**Comment by AlexYoung28** [comment]
Following on from this just been playing around with RC2, but when creating a new ticket and you add a new user how do you add them to an organisation?

**Comment by ntozier** [comment]
@AlexYoung28 you dont.  

You would want to go to User to add the user.   Then either click on the user and click Add Organization or go to Users -> Organizations, go to the Organization, and add the user.

**Comment by AlexYoung28** [comment]
Yeah i've seen that just wondering if it would just be quicker when creating a new user to just be able to select the users Organization

**Comment by rbukovansky** [comment]
@greezybacon What can we do to get this feature expedited, please? Thanks.

**Comment by rbukovansky** [comment]
Nevermind! It seems @greezybacon 's pull-request #2577 solves it! Now, we just need to allow it to develop-next branch...

**Comment by greezybacon** [comment]
So, is the root issue here adding a column to the ticket listing for the organization, or is it to specify the organization when creating a new user?

**Comment by rbukovansky** [comment]
I see two issues here:
1. Adding columns to ticket queues - that's going to be solved with your PR #2577 / osTicket 1.11
2. When creating new user, there is no possibility now to say immediately to which organization he belongs. You need to save him first and then add him to organization.

**Comment by greezybacon** [comment]
@rbukovansky I agree. That would be nice. It would also be nice to have an organization drop down in the advanced search, or ticket filter criteria as well

**Comment by rbukovansky** [comment]
@greezybacon Well, you are the developer, so make it happen! :)

**Comment by AlexYoung28** [comment]
Lol

**Comment by greezybacon** [comment]
> you are the developer

I love the singleton usage in your statement. Unfortunately, I only have so much time to dedicate to coding for this project, and everyone's issue is the most important...

**Comment by rbukovansky** [comment]
@greezybacon It was more suggestion than command... ;)

**Comment by ntozier** [comment]
I took it as being playful (and not rude or being a jerk).  Heck it made me smile. :)
