### ISSUE TITLE
[feat req] optional description input box

### ISSUE THREAD

**Issue by mckaygerhard** [osTicket/osTicket#2169]
currently the input box description of the requirements form are "Required", will be great if c¡only the title of resumen can be Required and the description of the ticket will be optional..

**Comment by ntozier** [comment]
I'm sorry but I have no idea what you are asking.
Please provide a mock up, or a better description.

**Comment by greezybacon** [comment]
I like this idea. v1.10 introduces the ability to "disable" the field, in which case it isn't rendered in the form at all. I like the idea of removing the forced requirement. @protich?

**Comment by mckaygerhard** [comment]
well somebody that already has "vision", thanks @greezybacon ; curently i have removed the code of the description field and put the same string of the resumen field... manuallly

in which part of code can i automate this, i mean wheantime, until v1.10 arrives, where i can set that the resumen field will copied to the description field¿?

**Comment by greezybacon** [comment]
Pardon my ignorance. What's the "resumen" field?

**Comment by ntozier** [comment]
That was a big part of why I asked for a mock up or better description of what he was talking about.

**Comment by mckaygerhard** [comment]
sorry, i mean "summary" I confused, at my work there we spoke in three types of speech, Russian, English and Spanish so its difficult coordinate that i write

**Comment by mckaygerhard** [comment]
what the progress of that?
