### ISSUE TITLE
core: Unknown or invalid schema signature (b26f29a6bb5dbb3510b057632182d138 .. 493e6c902e76a8130d4a422f7880ddbc)

### ISSUE THREAD

**Issue by ezekel** [osTicket/osTicket#2172]
php version -  5.4.16

mysql -  5.6.12

I get the copy using git clone  "osTicket v1.9.8.1-10"
, when I run the installation I get this message 

core: Unknown or invalid schema signature (b26f29a6bb5dbb3510b057632182d138 .. 493e6c902e76a8130d4a422f7880ddbc)

what should I do now ?
![support](https://cloud.githubusercontent.com/assets/6830057/8278218/466c5736-18fc-11e5-8215-5ab7d1fb1ee7.PNG)

Thank you in advance.

**Comment by greezybacon** [comment]
@ezekel did you use FTP in **binary** mode to upload the files?

**Comment by ezekel** [comment]
@greezybacon , 
Thank you for the quick reply.This is the first time I use osticket. I did not use the FTP because I did not upload it to my server I just want to work here in my local machine(localhost) ,I just followed your installation guide .

First:
cloning the osticket `git clone https://github.com/osTicket/osTicket-1.8`

Second:
since I was not able to perform this 
`cd osTicket-1.8
php setup/cli/manage.php deploy --setup /var/www/htdocs/osticket/`
because I get error message 

I just run it directly to my browser
`setup/cli/manage.php`

Is osticket will work in localhost ?

Thank you in advance.

**Comment by ezekel** [comment]
@greezybacon  I am using wampserver in my local mahcine can yo help me please

**Comment by greezybacon** [comment]
> since I was not able to perform this 
`cd osTicket-1.8 php setup/cli/manage.php deploy --setup /var/www/htdocs/osticket/`
because I get error message

Perhaps you meant semi-colon after the `cd` statement?
`cd osTicket-1.8; php setup/cli/manage.php deploy --setup /var/www/htdocs/osticket/`

I would recommend downloading the project from http://osticket.com/download. Unpack the ZIP file's `upload/` folder to `/var/www/htdocs/osticket/`. Visit http://localhost/osticket/ and proceed with the installation.

**Comment by ezekel** [comment]
@greezybacon ,

Okay I will try,your suggestion I will let you know.

**Comment by ezekel** [comment]
@greezybacon , I installed now, is this okay after extracted the folder, I get the upload and put it on my web document. and I renamed it to something "support" ..so the path like this http://localhost/supports/setup/install.php

Thank you in advance.

**Comment by ezekel** [comment]
@greezybacon , what's next thing to do if I run in the url like this http://localhost/supports/ after I pressed enter the url will be change to this http://localhost/supports/setup/install.php 

Thank you in advance.

**Comment by greezybacon** [comment]
Looks like you just need to complete the installation?

**Comment by ezekel** [comment]
@greezybacon , 

when osticket pop up the modal for installing the tables,after a few seconds it disappears then blank page,there is no message successfully installed.

That's why I run this in my url http://localhost/supports/ but it will redirect me to insatllation. did I successfully installed the osticket ?

Thank you in advance.

**Comment by ezekel** [comment]
@greezybacon , I get system error when renaming the install folder.

**Comment by greezybacon** [comment]
I am not familiar with the pop up to install the tables. Do you have anything interesting in the php error log?

**Comment by ezekel** [comment]
@greezybacon ,

This is the error log in php

```
[22-Jun-2015 08:07:33 UTC] PHP Strict standards:  Redefining already defined constructor for class Option in C:\wamp\www\osTicket-1.8\setup\cli\modules\class.module.php on line 11
[22-Jun-2015 08:07:33 UTC] PHP Stack trace:
[22-Jun-2015 08:07:33 UTC] PHP   1. {main}() C:\wamp\www\osTicket-1.8\setup\cli\manage.php:0
[22-Jun-2015 08:07:33 UTC] PHP Strict standards:  Redefining already defined constructor for class Module in C:\wamp\www\osTicket-1.8\setup\cli\modules\class.module.php on line 126
[22-Jun-2015 08:07:33 UTC] PHP Stack trace:
[22-Jun-2015 08:07:33 UTC] PHP   1. {main}() C:\wamp\www\osTicket-1.8\setup\cli\manage.php:0
[22-Jun-2015 08:07:48 UTC] PHP Strict standards:  Redefining already defined constructor for class Option in C:\wamp\www\osTicket-1.8\setup\cli\modules\class.module.php on line 11
[22-Jun-2015 08:07:48 UTC] PHP Stack trace:
[22-Jun-2015 08:07:48 UTC] PHP   1. {main}() C:\wamp\www\osTicket-1.8\setup\cli\manage.php:0
[22-Jun-2015 08:07:48 UTC] PHP Strict standards:  Redefining already defined constructor for class Module in C:\wamp\www\osTicket-1.8\setup\cli\modules\class.module.php on line 126
[22-Jun-2015 08:07:48 UTC] PHP Stack trace:
[22-Jun-2015 08:07:48 UTC] PHP   1. {main}() C:\wamp\www\osTicket-1.8\setup\cli\manage.php:0
```

**Comment by ntozier** [comment]
I do not see any errors in your error log.  All I see is strict notifications.

**Comment by ezekel** [comment]
@ntozier ,

can I ask is this will support to wampserver ?

**Comment by AlexYoung28** [comment]
Im using latest wamp and it works fine 1.9 and 1.10

**Comment by ntozier** [comment]
Q: can I ask is this will support to wampserver ? 

A: If you are asking 'Can osTicket be run under WAMP server?' then the answer is yes.

**Comment by LucasBurg** [comment]
I have the same problem, but I want to contribute to the project . What should I do ?

**Comment by vikas-DabKick** [comment]
I downloaded it as zip and installed as per procedure no problem has occured.. but when I tried to install using a cloned copy I faced this problem

download the code as a zip file and unzip and try to install.

**Comment by ntozier** [comment]
@vikas-DabKick I have a hard time believing that you downloaded 1.9.8.1 as a zip.  It hasn't been available as a zip file from osticket.com/download for well over a year.

What version are you running?
Please download from http://osticket.com/download and try again.
