### ISSUE TITLE
Ticket search problem

### ISSUE THREAD

**Issue by fictionedge** [osTicket/osTicket#2176]
The new feature to create our own status is great but it creates a new problem.
If I want to see all open tickets (no matter what their status name), I'm just can't, unless I search each status one by one.
Is there a work around? If not could you please add an option in the advanced search for open or closed tickets?

Thx

**Comment by greezybacon** [comment]
This is implemented in the `develop-next` branch with the new advanced search interface.

**Comment by fictionedge** [comment]
Awesome!

**Comment by harrisyn** [comment]
Can we safely test this?

**Comment by markus4000** [comment]
A MOD for current version: Issue #1662
Works fine for me.
https://github.com/osTicket/osTicket-1.8/issues/1662

**Comment by fictionedge** [comment]
thx markus4000
