### ISSUE TITLE
[Feature Request] Mass email to end users

### ISSUE THREAD

**Issue by kyle0440** [osTicket/osTicket#2183]
I would like the ability to send out a mass email to all registered users or a subset of selected ones (such as an organization) - This would be helpful for bulletins that might need to go out to all users quickly.

**Comment by ntozier** [comment]
You can use the export feature on the users tab, and import them into a mailing list on your mail server or into a mailing list web service (such Constant Contact).

I'm personally leery of adding a feature like this as I feel it would be prone to abuse should one of the staff accounts ever become compromised.

**Comment by kyle0440** [comment]
It's definitely a risk, but it could be a separate permission that's only default enabled on super admins. 

Although I wasn't aware of the export button. I must've been blind :P

I still think it would be quite useful to have this integrated though. Saves a couple steps that would have to be taken to ensure that an outside service is kept up to date.

**Comment by greezybacon** [comment]
There are entire products that do this, like MailChimp and Constant Contact. That said, I would also like to see this be a major feature of osTicket

**Comment by mckaygerhard** [comment]
i agree with @greezybacon , this feature acts aas a mail list .. and osticket its not a mail list. maybe this feature request its invalid
