### ISSUE TITLE
lookupByPhone function

### ISSUE THREAD

**Issue by itulga** [osTicket/osTicket#2184]
Hi,

How to find user by Phone number? I need function like lookupByPhone($phone).

Thanks

**Comment by gtulga** [comment]
I wrote it. I think it is not good way, please update it.

    static function lookupByPhone($phone) {
        $sql = "SELECT `id` FROM `".USER_TABLE."`";
        if (!($res = db_query_unbuffered($sql, $auto_create)))
            return false;

        while ($row = db_fetch_row($res)) {
            $user = User::lookup($row[0]);
            $cdata = $user->getDynamicData();
            foreach ($cdata as $e){
                if ($phone == $e->getAnswer('phone')){
                    return $user;
                }
            }
        }

        return self::lookup(0);
    }

**Comment by greezybacon** [comment]
In the v1.10 (develop-next) version, you could use

```php
class User ... {
    static function lookupByPhone($phone) {
        return User::objects()->filter(array(
            'cdata__phone' => $phone
        ))->one();
    }
}
```

It will throw `DoesNotExist` exception if such a user does not exist. Use a try / catch block, or change `one` to `first`, which will return NULL if no such user exists

**Comment by greezybacon** [comment]
This one seems much faster
```php
class User ... {
    static function lookupByPhone($phone) {
        return static::objects()->filter(array(
            'cdata_entry__form__type' => ObjectModel::OBJECT_TYPE_USER, 
            'cdata_entry__answers__field__name' => 'phone',
            'cdata_entry__answers__value' => $phone,
        ))->one();
    }
}
```
Especially if you add an index to the %form_entry_values table
```sql
ALTER TABLE `ost_form_entry_values`
ADD KEY `answers` (`value`(100));
```

**Comment by jmurn** [comment]
Do you have some fast solution for v1.11 ?
