### ISSUE TITLE
Fatal error: Call to a member function (develop-next)

### ISSUE THREAD

**Issue by balojs** [osTicket/osTicket#2186]
To try  see ticket, showed  this error
Fatal error: Call to a member function get() on null in /Applications/MAMP/htdocs/next/include/class.ticket.php
![screenshot](https://cloud.githubusercontent.com/assets/3303352/8360138/ea336ac6-1b27-11e5-8ff6-6440de32e133.png)

**Comment by greezybacon** [comment]
I have never seen that before. What version are you running?

**Comment by balojs** [comment]
closed

**Comment by balojs** [comment]
:closed

**Comment by balojs** [comment]
Currently fixed in version develop-next
