### ISSUE TITLE
Version 1.10

### ISSUE THREAD

**Issue by JamesPCS** [osTicket/osTicket#2188]
I'm not sure if this is the right place to post this issue but I was told to post here. I set up the Beta Version 1.10. It's not going into production yet I'm playing around with it and getting used to it. However, I can't get it to recognize the right settings. I have turned on php_intl.dll and set cgi.fix_pathinfo=1 but it is still showing that they are not detected. I have also added "c:\Websites\xampp\php" to the environment variables in windows. Can someone help me get OSTickets to recognize these? I have attached screenshots of my settings.
![osticketssettings](https://cloud.githubusercontent.com/assets/13053847/8377684/532fdef6-1be1-11e5-99fd-3f4a2a35063f.PNG)
![intl](https://cloud.githubusercontent.com/assets/13053847/8377687/5ab255e6-1be1-11e5-9b6d-6f9bb739fa88.PNG)
![cgi](https://cloud.githubusercontent.com/assets/13053847/8377689/5f2453f4-1be1-11e5-825f-9598b381dd1a.PNG)

**Comment by JamesPCS** [comment]
Also, it is still stating it is in GMT which is inaccurate. It should be Eastern Standard Time. I have set the time in the admin settings to America / New_York and I have set my individual agent account to the same. I have also set in php date.timezone=America/New_York. I have also tried setting all 3 to Detroit (which is in the same timezone) and it still displays incorrectly.

**Comment by ntozier** [comment]
Did you restart the web server?
Are you sure that you edited the proper php.ini?  (Windows installations have a tendency to have multiple)

**Comment by JamesPCS** [comment]
Yeah I just had to restart the entire computer. Xampp didn't seem to start and stop the services properly. The time now displays correctly in the dropdown, though it still has the wrong timezone. The cgi error is also still there.

**Comment by ntozier** [comment]
I would create a file (let's call it test.php) and put it in your osTicket web root.
In the file put:

[code]<?php phpinfo(); ?>[/code]

Open that userl/test.php and find the location of your php.ini.  Make sure that is the one that you edited.

**Comment by JamesPCS** [comment]
It is the same one. It’s in the xampp directory and I always use xampp to pull up the php file anyway as it’s quicker than navigating to the file. Once I restarted it the changes I made to the php_intl.dll file took effect and now the dropdown is displaying properly. However, that is the same file I modified the cgi.file_pathinfo line and it did not make any difference.
