### ISSUE TITLE
1.10 Update Custom List Ticket Status

### ISSUE THREAD

**Issue by kest874** [osTicket/osTicket#2191]
When attempting to update a ticket status in the custom list it produces:

![image](https://cloud.githubusercontent.com/assets/12860950/8381360/d60fabf8-1bf0-11e5-9a05-36a3f18c617b.png)

**Comment by kest874** [comment]
This is still an issue in RC1  Same DB Error.

**Comment by greezybacon** [comment]
I believe this is fixed in `develop-next`. Can anyone confirm?
