### ISSUE TITLE
1.10 Reassign Ticket

### ISSUE THREAD

**Issue by adegidio** [osTicket/osTicket#2193]
When I receive a ticket, by default I defined to not auto assign. I want to assign it to a member of the team. I do it but ticket is assigned to me instead of the selected member. If I try again to reassign it, the person who I try to reassign does not appear in list.

**Comment by greezybacon** [comment]
@adegidio could you provide some screen shots of your process?

**Comment by adegidio** [comment]
Hello Jared,

I will try to explain the situation:

   1. Someone create a ticket.
   2. I open the ticket as Agent (1 - Ticket  BCKB PRT_000005
   unassigned.png).
   3. I try to assign the ticket to pmoran (Pablo Moran), which a agent of
   my team (2 - Ticket  BCKB PRT_000005 trying to assign.png).
   4. I tried to assign but I receive "Unable to complete the ticket
   assignment", maybe because I didn't put a reason (3 - Ticket  BCKB
   PRT_000005 unable to assign.png).
   5. I tried again to assign ticket to pmoran completing reason and I
   received confirmation of assignment to ME (Ticket assigned successfully to
   Alejandro D'Egidio) instead of pmoran (4 - Ticket  BCKB PRT_000005 assigned
   to pmoran but appear adegidio as assigned.png).
   6. I try to reassing ticket to pmoran but he doesn't appear in box of
   "Assignee" (5 - Ticket  BCKB PRT_000005 wrong assigned to adegidio - trying
   to assign pmoran but he doesnt appear.png).
   7. If I try to assign ticket to any other person or team in list of
   Assignee, I receive a Blank Page (6 - Ticket  BCKB PRT_000005 blank
   page.png).


Please, let me know if you need something else to test.

Regards,
Alejandro



2015-06-27 23:57 GMT-03:00 Jared Hancock <notifications@github.com>:

**Comment by ntozier** [comment]
Your attachments didnt take.
Re: Blank Page
This usually indicates a PHP error.
Have you checked the PHP error log?

**Comment by adegidio** [comment]
Hello,
I'm sorry for the delay, I was absent. Could you please tell where is PHP error log? I know the apache error log. In apache error log I don't see any error.

**Comment by ntozier** [comment]
We cannot tell you where your PHP error log is located as it varies by OS and personal preference.
