### ISSUE TITLE
Will be present in the future a notification inside osticket for staff when there is a new verison of the software?

### ISSUE THREAD

**Issue by PeopleInside** [osTicket/osTicket#2205]
Will be good inform the staff inside admin panel there is a new version.

**Comment by markus4000** [comment]
You mean something like a changelog?
Nice idea. I made a internal FAQ post for that.

**Comment by PeopleInside** [comment]
I mean a message inside admin panel on top who alert there a new verison

**Comment by ntozier** [comment]
I believe that he is asking for osTicket to call home, and see if there is a newer version available.  If there is then he wants the admin panel to alert any admin staff that logs in.

**Comment by PeopleInside** [comment]
yes. For security reason and other think is good invite staff to update to the last version

**Comment by Boduje** [comment]
Yeah, this would be nice.  I had been using 1.9.1 and never had clue that 1.9.9 was out.

**Comment by PeopleInside** [comment]
@Boduje thank you for your feedback!
