### ISSUE TITLE
advanced ticket search problem osticket 1.10

### ISSUE THREAD

**Issue by zizackov** [osTicket/osTicket#2207]
Hi
when trying to do a search for ticket between 2 dates, i get no results although there are tickets in this date range. other advanced searches work fine.  
thank you, 
![osticket search](https://cloud.githubusercontent.com/assets/13097295/8470259/fbdeb30c-2090-11e5-8654-22606a03b8d2.jpg)

**Comment by greezybacon** [comment]
Thanks for the bulliten. I've drafted a fix for this, but haven't put a pull request together. I'll reference your issue when I post it

**Comment by SpudR** [comment]
Just to add to this - the searches for "in the last n days" and "in the next n days" don't work properly.
If I enter 365 days I just get 0 results though there are tickets in both ranges.
Also, what is the difference between these searches and the "After [date]" search?
