### ISSUE TITLE
1.9.9: Limit ticket access

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket#2209]
If i set `Limit ticket access to ONLY assigned tickets` to user, user not see closed tickets assigned to him

**Comment by infectormp** [comment]
User see only opened tickets

**Comment by Chefkeks** [comment]
That's normal since a closed ticket is no longer assigned to agent / team.

**Comment by infectormp** [comment]
It's not normal when you need see some information in closed ticket. If i set ```Limit``` i can't find closed this ticket and can't view this ticket. So if i need look inside closed ticket i need go to admin and aks him to reopen ticket or remove ```Limit``` from my user.

**Comment by ntozier** [comment]
First to clarify, Users are not assigned tickets.  They open them and are the owner.
Agents (staff) are assigned tickets, as are Departments and Teams.  And this is working as intended.

Your problem is that the ticket is assigned to a department that the Agent (staff) does not have access to.  Transfer the ticket to the department that the agent it in, and the agent will be able to see it.

**Comment by infectormp** [comment]
@ntozier saying user i mean staff.

**Comment by infectormp** [comment]
@ntozier i assign ticket to myself then i close ticket. After this a set limit access and ticket has disappeared from closed view. I can't search this ticket and can view it.

**Comment by ntozier** [comment]
And what department is the ticket assigned to?
And does your user account have access to it?

**Comment by infectormp** [comment]
ticket assigned to department = 1
staff have access  to department = 1,2,3 with full rights

i try set staff only department = 1 but have same result

**Comment by greezybacon** [comment]
I agree. We've discussed internally about adding a `closed_by` field to the ticket so that the person who last closed a ticket can see it after it closed if they have the restricted access setting checked.

**Comment by jyriup** [comment]
Hi greezybacon, 

Do you plan to add this closed_by field in near future?

**Comment by balojs** [comment]
@greezybacon and @protich, please, Consider this improvement
