### ISSUE TITLE
1.9.9: Exclude assigned tickets from open queue

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket#2210]
If i set `Exclude assigned tickets from open queue` in open queue i see count +1 from current opened tickets

![image](https://cloud.githubusercontent.com/assets/9958813/8473473/8c4f6c44-20b2-11e5-8264-b94161417eec.png)

![image](https://cloud.githubusercontent.com/assets/9958813/8473485/a2e57584-20b2-11e5-88aa-31245bcf1e7f.png)

**Comment by greezybacon** [comment]
So it looks like there is one ticket showing in the statistics query but not the ticket listing query
