### ISSUE TITLE
Ticket Filters problem in 1.10 

### ISSUE THREAD

**Issue by zizackov** [osTicket/osTicket#2211]
Hi
 when doing a ticket filter and trying to set the ticket priority, the ticket is not created at all. 
all other settings do work.
![capture](https://cloud.githubusercontent.com/assets/13097295/8476476/74c9ff0e-20ca-11e5-8484-a5e367b0925d.JPG)

**Comment by greezybacon** [comment]
Do you get a php error or anything suspicious when you attempt to create the ticket?

**Comment by zizackov** [comment]
yes i see errors.
 error 1054. how can i export them?

**Comment by ntozier** [comment]
Please consult your PHP error log on your server.

**Comment by greezybacon** [comment]
@zizackov just post whatever it is you've found
