### ISSUE TITLE
Blank white page after pop up modal is disappear

### ISSUE THREAD

**Issue by ezekel** [osTicket/osTicket#2215]
Hi, 

I just want to ask I am using wampserver( I am installing in localhost), during the installation process there is a modal showing ( I forgot the message) "Instaling os ticket....". after that the modal disappear and only white page. did I installed correctly ?...now how can I begin using the osticket if I successfully installed.

Thank you in advance.

**Comment by infectormp** [comment]
Look to web server log. Blank page usually  shown when you have php error

**Comment by ntozier** [comment]
Please consult your PHP error log.
Also what version are you trying to install?
