### ISSUE TITLE
Bug with attached files having same size and extension

### ISSUE THREAD

**Issue by Zholaman** [osTicket/osTicket#2218]
![tech_spec1](https://cloud.githubusercontent.com/assets/8802415/8502582/5c1dc20e-21cb-11e5-9841-7de9b1fc9c35.jpg)
When somebody sends to ServiceDesk email message with attached files, osTicket do not accepts the files having same size and extension. For example we have 3 attached files: 

1) test1.xls (size 10 KB), 
2) test2.xls (size 10 KB) 
3) test.pdf (size 5 KB)

osTicket skips only 2 files - test1.xls, test.pdf and discards test2.xls. This issue also rise when we try to attach file(s) through web interface to some ticket.

I have found this problem in osTicket v.1.9.5, 1.9.9, but I suspect it exist and in previous versions of osTicket.

**Comment by greezybacon** [comment]
I bet test1.xls and test2.xls have the same content. The system will de duplicate the files. Then there is another restriction that the same file cannot be attached twice to a thread poat

**Comment by Zholaman** [comment]
Sorry but what the 'a thread poat' ?

**Comment by Zholaman** [comment]
But files with same extensions and having slightly difference in size have the same problem. Fo example we have 2 files one of them has 9.7 KB (test1.xls) and other 10.3 KB (test2.xls), so osTicket skip one of them.

**Comment by Zholaman** [comment]
Sorry for my stupid question but could you tell me what the meaning of 'poat' ? 
I ask because I can't find translate of the word - poat.
Thanks!

**Comment by mfelber** [comment]
@Zholaman I think this is a typo. Thread "post" would make sense..

**Comment by Zholaman** [comment]
thanks!

**Comment by Zholaman** [comment]
Hi, let me express my opinion.

@greezybacon I think it not good to have such restriction. It would convenient to allow users send any files regardless of contents. Some of our users send to us files having different names but with same content (for example having single format of table).

**Comment by greezybacon** [comment]
This is partly addressed in develop-next (v1.10) in that duplicate files are allowed to have different names; however, there is still the limitation that the same file content cannot be attached to the same thread post more than once

**Comment by Zholaman** [comment]
@greezybacon Thanks!
