### ISSUE TITLE
%{ticket.subject} is not working in 1.10

### ISSUE THREAD

**Issue by zizackov** [osTicket/osTicket#2220]
osticket 1.10, when trying to send %{ticket.subject} in the email template, the user gets noting. 
all other var works ok. 
thank you

**Comment by robintoy** [comment]
F OFF!!!!



Kind Regards


Robin Toy
Director
Strobe Technologies Ltd
[in]<https://www.linkedin.com/in/robin-toy-13714625>[sw]<http://community.spiceworks.com/people/robintoy>[Certification Badge - Small]
