### ISSUE TITLE
1.9.9: Closed by

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket#2221]
`Closed by` field to set when staff create ticket with resolved state 
![image](https://cloud.githubusercontent.com/assets/9958813/8521498/c4913ae6-23ec-11e5-938a-13b6046b0f60.png)

**Comment by infectormp** [comment]
staff_id not set in db for this ticket

**Comment by ntozier** [comment]
I'm sorry but I do not see a question.
or an issue.
Can you please try explaining it a little differently.

**Comment by infectormp** [comment]
@ntozier ok, staff_id field in db = 0 when staff create ticket with resolved status from web intercafe

**Comment by infectormp** [comment]
if i close ticket that was alredy created (via mail) staff_id field in db = my staff_id.

**Comment by mckaygerhard** [comment]
i can see a clear isue on that, inclusivelly @infectormp provides also the solution ...
