### ISSUE TITLE
1.9.9: Wrong search result order

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket#2226]
In function **find** `class.search.php` used order by relevance `$sort = 'ORDER BY `search`.`relevance`';` but ORDER BY relevance return result from min to max and search result showed from min relevance to max. So result with best relevance always in end of list.

I use this select for test `SELECT object_type, object_id, MATCH (search.title, search.content) AGAINST ('220674-AIS' IN BOOLEAN MODE) AS `relevance` FROM ost__search search WHERE MATCH (search.title, search.content) AGAINST ('220674-AIS' IN BOOLEAN MODE) ORDER BY relevance`` and get result where 220674-AIS have good relevance but display at end of result list:

![image](https://cloud.githubusercontent.com/assets/9958813/8544751/bc98f364-24b0-11e5-8875-2503d28edcab.png)

After i add DESC to select i have right order from max relevance to min and now i see tickets in result with max relevance on firts page, not on last:
![image](https://cloud.githubusercontent.com/assets/9958813/8544863/989531a2-24b1-11e5-8163-ac4cff8bdc1b.png)

**Comment by infectormp** [comment]
i use mariadb 10.0.20

**Comment by mckaygerhard** [comment]
i also confirmed that, in mariadb 5.3.12, i added a note, all the linux disributions now have been swichet to mariadb as default mysql alternative sql manager
