### ISSUE TITLE
Attachments not working 1.10

### ISSUE THREAD

**Issue by Jo3ytjuh** [osTicket/osTicket#2227]
The attachments always give "Unknown or invalid file"
so no way to open attachments.

**Comment by ntozier** [comment]
Sounds more to me like you have a problem with your server config.
You may want to visit the forums with your setup information (include which way you utilize attachments) and description of problem.
You should also consult your webserver error log to see what the error log, and consult the PHP error log and see if anything is getting logged there.

**Comment by ARiber** [comment]
I am having the same issure. Before updatein to 1.10 RC2 attachments were never a problem.
Now when opening the attachments i get the following reply:

Cant find file.... /file.php?key=t2ahxwjp3k71u8nlmswql-cyqh033k1s&expires=1441152000&signature=2b48890055f3972652819d8e56a911641d31a565

Any idea what could be the reason?

OSTicket v1.10-rc.2 (231f11e)
MySQL 5.5.38
PHP 5.5.27-1~dotdeb+7.1

**Comment by ARiber** [comment]
check if you have given the correct access rights to the file file.php... in my case this was the reason that it didnt work because the file had no user rights on the server
