### ISSUE TITLE
Feature Request: Tags 

### ISSUE THREAD

**Issue by markus4000** [osTicket/osTicket#2230]
It would be very nice to have "tags" in osTickets. so the ticket-archive would be very nicely searchable. 
printer, network, userfail, hardware, supplier, opportunity, risk etc etc. etc. ...

**Comment by greezybacon** [comment]
This is sort of possible at the moment:

* Add a new list to the system, called "Tags"
* Add items to the list for all the tags you would like to track
* Add a new field to the "Ticket Details" form, maybe called tags. It can be internal and optional
* Edit tickets and define the tags you want
* Tags are now searchable by the advanced search box

**Comment by yegors** [comment]
I would donate money to whoever could build this feature.

**Comment by t-oster** [comment]
@yegors how much money are we talking about? Do you need tags per user or global tags? Can tags have sub-tags (like subfolders)?

**Comment by yegors** [comment]
@t-oster 

Global tags (with auto-complete from already existing tags, showing number of issues associated with each tag) that work in a similar fashion to Stackoverflow.com. No subtags. 

Each tag can be clicked to show tickets (opened/closed/all) that are tagged with it. 

That's pretty much it. $600 sound okay?

**Comment by t-oster** [comment]
Based on 1.10? Sounds good. Details per E-Mail? mail&thomas-oster.de

**Comment by JediKev** [comment]
Available via Lists as mentioned in the comment below:
https://github.com/osTicket/osTicket/issues/2230#issuecomment-120971506
