### ISSUE TITLE
Signature are not added to ticket message

### ISSUE THREAD

**Issue by PeopleInside** [osTicket/osTicket#2232]
When operator write a reply and ass Signature select Signature and send reply this is not included in the ticket.

**Comment by ntozier** [comment]
what version?

**Comment by PeopleInside** [comment]
1.9.9

**Comment by infectormp** [comment]
i can confirm this on my installation. i see Signature when write answer to user but in email message Signature absent

**Comment by infectormp** [comment]
need add  %{signature} variable to email template.

**Comment by PPCM** [comment]
I have the same problem with the v1.10-rc.2
I tried to add %{signature} in email template and directly in the email, and the text is not transformed

I have to precise that during the redaction of the response, the correct signature appear under the ticket

any idea?
Thanks

**Comment by greezybacon** [comment]
@PPCM, could you add some screenshots?

**Comment by PPCM** [comment]
Here are screenshots, but it will show nothing special
During the redaction of the response, the signature appears under the text
But when the response is received, the signature is not present

![redaction](https://cloud.githubusercontent.com/assets/1247223/10116146/cf77b31e-6428-11e5-88ff-f105bf389c80.jpg)
![mail](https://cloud.githubusercontent.com/assets/1247223/10116147/cf7974c4-6428-11e5-8d3d-ea58a3aec0fd.jpg)

**Comment by PPCM** [comment]
any idea?
