### ISSUE TITLE
osTicket v1.9.9 - Valid CSRF Token Required

### ISSUE THREAD

**Issue by rachelsupport** [osTicket/osTicket#2234]
I installed osTicket v1.9.9 on my Wordpress site successfully. However, when I try to login as an admin (using the correct username and password) - I receive the message: Valid CSRF Token Required.
I am unable to login.

**Comment by greezybacon** [comment]
This is usually a cookie issue. Are you using a proxy?

**Comment by rachelsupport** [comment]
No, not using a proxy. How can I get this working?

**Comment by rachelsupport** [comment]
I also asked my hosting company to take a look. They advised that the cookie is not being set at all and after checking the error logs, they didn't find anything either.

**Comment by greezybacon** [comment]
> They advised that the cookie is not being set at all 

Then something is terribly broken with your hosting environment. osTicket will send a Set-Cookie header when visiting the login.php page and requires the value be sent in the following request in the Cookie header

**Comment by rachelsupport** [comment]
I think I may have determined the issue. My website is on an optimized wordpress hosting plan - therefore, the server does not like any software that is not "wordpress". I will have to move my site to my other hosting account and test it out.
