### ISSUE TITLE
1.10 blank page on task

### ISSUE THREAD

**Issue by harrisyn** [osTicket/osTicket#2235]
Finally installed 1.10 after upgrading PHP, however after installation, when I click on tasks under a ticket
the popup appears blank.

![image](https://cloud.githubusercontent.com/assets/4963361/8576107/677f508c-258f-11e5-9db3-179c09d51c96.png)

**Comment by ntozier** [comment]
Check your PHP error log?
It should look like this:

![capture](https://cloud.githubusercontent.com/assets/1315768/8578313/186abf94-257c-11e5-97a5-b16410f3b1b1.PNG)

What happens when you click on the task tab at the top?

**Comment by harrisyn** [comment]
this happens when I click the "Add New Task" button in your screenshot.

**Comment by ntozier** [comment]
Do you have any other AJAX problems?  
Or is it just with this one screen?
Have you Checked your PHP error log?
What happens when you click on the task tab at the top?

**Comment by harrisyn** [comment]
Every other Ajax seems to work just fine. I don't have access to the logs

**Comment by greezybacon** [comment]
There's still a small amount of work outstanding on tasks. We hope to merge it in tomorrow

**Comment by greezybacon** [comment]
We merged in some patches for the task feature. Can you retest with the tip of the `develop-next` branch?

**Comment by kest874** [comment]
I can confirm that the merges fixed the issue.
