### ISSUE TITLE
Feature Request: Ticket Count in Ticket Assignment List

### ISSUE THREAD

**Issue by markus4000** [osTicket/osTicket#2238]
Idea: 
why don't you add a ticket-count in the agent-assignment-dropdown-list ?

eg:

Agent (5)
.  Markus4000 (5)
.  David (3)
.  Mario (8)
.  Jean (10)
.  Marie (0)
Teams (xx)
.  xxxxxx
.  yyyyyy
.  vvvvvv

so you always know the load of the staff.

**Comment by ntozier** [comment]
Oh neat idea! :+1:

**Comment by balojs** [comment]
+1

**Comment by JediKev** [comment]
Available via Custom Columns & Custom Queues feature.
