### ISSUE TITLE
Feature Request: deputy agent

### ISSUE THREAD

**Issue by markus4000** [osTicket/osTicket#2244]
Request;
+Agent should be able to set his flag "on holiday" by himself.
+Agent should be able to define a deputy that gets the mails in case that he is on holidays.

**Comment by mfelber** [comment]
@markus4000 I think the first one "+Agent should be able to set his flag "on holiday" by himself." is already adressed in 1.10:

![vacation mode](https://cloud.githubusercontent.com/assets/5539456/8650821/8f8d411c-2975-11e5-9da4-ce0ddf0a2b42.jpg)

Or do you mean something different?
