### ISSUE TITLE
Can't change Font/Back Color in comment box

### ISSUE THREAD

**Issue by Aka4Code** [osTicket/osTicket#2245]
This do not work within within tabs Reassign Ticket and Department Transfer.
But works fine with Post Reply and Post Internal Note tabs.

![image](https://cloud.githubusercontent.com/assets/11789024/8618320/5ed45e94-270d-11e5-8eac-3c2863e7d97c.png)
![image](https://cloud.githubusercontent.com/assets/11789024/8618322/631f8aaa-270d-11e5-9605-062c5b9e1d51.png)
![image](https://cloud.githubusercontent.com/assets/11789024/8618324/66dda06e-270d-11e5-847c-83a6fb534722.png)
![image](https://cloud.githubusercontent.com/assets/11789024/8618326/69b919da-270d-11e5-88c8-089658ed00f3.png)

![image](https://cloud.githubusercontent.com/assets/11789024/8618341/ac414a8e-270d-11e5-84e4-bec04fb60046.png)
Google Chrome version 43.0.2357.132

**Comment by greezybacon** [comment]
This seems to be fixed in v1.10
