### ISSUE TITLE
Redactor Plugins

### ISSUE THREAD

**Issue by Aka4Code** [osTicket/osTicket#2246]
Can we install some of Redactor Plugins such as Font Size change plugin?
http://imperavi.com/redactor/plugins/font-size/

I ask because I know you use some OEM license on redactor and it's not free.

P.S. With Redactor editor how to format table to edit border or background color?

**Comment by greezybacon** [comment]
If you can download the plugin, feel free to install and use it. And for table edits, feel free to write a plugin for that...
