### ISSUE TITLE
Filter Autoresponses 

### ISSUE THREAD

**Issue by harrisyn** [osTicket/osTicket#2249]
Is there a way to filter incoming mails for a particular message in the body of the mail?
I understand that autoresponses shouldnt be created as tickets, however in my setup all autoreponses create emails, I have managed to create a filter that blocks those that return a specific subject, however those that dont go on to create a ticket. 

Secondly, my company use a the Enterprise Vault for Microsoft Exchange, and whenever a mail is archived into the vault, Osticket reads it as a new mail and creates a ticket for it. I am not sure how to prevent or stop this from happening, any ideas would be helpful.

**Comment by infectormp** [comment]
> Is there a way to filter incoming mails for a particular message in the body of the mail?

Filter -> Ticket message -> Matches Regex -> some regexp

**Comment by infectormp** [comment]
@harrisyn you fetch mail from pop3 or imap?

**Comment by harrisyn** [comment]
IMAP

**Comment by harrisyn** [comment]
Hi @infectormp , in ticket filter, I have tried filter->ticket/issue details -> Contains -> Text to Catch
doesnt work.

Also it is odd that the responses come with the ticket id in the subject but do not get appended to the original ticket.
@greezybacon any idea why?

**Comment by infectormp** [comment]
@harrisyn ```ticket/issue details -> Contains``` dosn't work (for me) i use ```Matches Regex```

**Comment by greezybacon** [comment]
> Also it is odd that the responses come with the ticket id in the subject but do not get appended to the original ticket.

They must be from the owner or a collaborator on the ticket for the number to match.

**Comment by harrisyn** [comment]
Would that suggest it is correct to create a new ticket if a collaborator
forwards on a mail to another user and that user replies to the forwarded
mail?

**Comment by harrisyn** [comment]
By all thats good, can someone give me specifically how I can filter on the body of an email?

i am looking to filter on this sentence 
"Dear Colleague
Thanks for contacting xxxxxxxxxxx"

this is contained in the body of a mail that I need to block from creating tickets.
I have tried ticket-contains and also matches regex but not confident either works or maybe I have just doing it the wrong way.

Do assist if you can.

thanks.

**Comment by infectormp** [comment]
@harrisyn  Filter -> Ticket message -> Matches Regex -> Thanks for contacting xxxxxxxxxxx

**Comment by infectormp** [comment]
you can test your regexp here https://regex101.com/#PCRE before add to filters
