### ISSUE TITLE
Future request: Allow Primary Contacts view all ticket

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket#2258]
When Primary Contacts in organization changed he can view only new tickets when `Primary Contacts: Add to all tickets from this organization` enabled.

Would be nice allow Primary Contacts view all ticket from his organization not only new.

**Comment by markus4000** [comment]
+1
but isn't it the sam like #2259 and #1928 ?

**Comment by infectormp** [comment]
@markus4000 no, in https://github.com/osTicket/osTicket-1.8/issues/2259 i ask about  Account Manager, here about Primary Contacts.
