### ISSUE TITLE
Delete old tickets

### ISSUE THREAD

**Issue by gtulga** [osTicket/osTicket#2261]
How to delete very old tickets? I need if older than 6 months, delete them. Because my DB is huge now and it is very slow.

Thanks

**Comment by ntozier** [comment]
There really isn't a way to do this at current besides going to the closed ticket queue, selecting some tickets and clicking delete.  Your account of course needs access to delete tickets.

You could also do this at the database level but would want to make sure that you purge any attachments and the ticket threads associated with the ticket.  I was working on a plugin to do this sort of thing but got distracted.

**Comment by sarshhfox** [comment]
Hi @ntozier, any updates on the feature/plugin for archival and deletion of prehistoric tickets in OSticket?
