### ISSUE TITLE
Refuse guest tickets on email fetching

### ISSUE THREAD

**Issue by webscreations** [osTicket/osTicket#2265]
I would really appreciate it if someone could assist me.

I have a ticket system, which only agents can register users and the public cannot open tickets without an account. I have automatic email fetching turned on just in case anyone just replies to the email through there email client. 

The issue I have if anyone sends an email to that email address, it automatically opens them a ticket in OSTicket, but I only want to receive replies on tickets from registered users and just refuse all guest emails.

Could you do this with a filter, I have no idea how to achieve this!

**Comment by infectormp** [comment]
Email -> Accept All Emails:Accept email from unknown Users ?

**Comment by webscreations** [comment]
I must be an idiot not to see that in settings! Thanks so much. Is there anyway the system can email the user a message if there ticket gets rejected?

**Comment by ntozier** [comment]
@infectormp actually means:
current
Admin panel -> Settings -> Email -> Accept All Emails:Accept email from unknown Users

or on 1.10+
Admin panel -> Emails -> Settings -> Email -> Accept All Emails:Accept email from unknown Users

**Comment by webscreations** [comment]
Is there anyway the system can email the user a message if there ticket gets rejected?

**Comment by infectormp** [comment]
I am not sure, but you can test this.
