### ISSUE TITLE
Feature request: Alerts and Notices for each Department

### ISSUE THREAD

**Issue by Aka4Code** [osTicket/osTicket#2270]
If you could put configuration of Alerts and Notices inside Department options it will be more flexible (each Department could have different settings of alerts).

![image](https://cloud.githubusercontent.com/assets/11789024/8796620/55442d5a-2f96-11e5-94f3-7c0e76e8b782.png)

**Comment by ntozier** [comment]
Departments already have over ride settings for this. 
Note: this screen shot is from the forth coming 1.10 release, but older versions have this as well. 

![department](https://cloud.githubusercontent.com/assets/1315768/8805255/4459d4ec-2f9e-11e5-8d20-eb5d68f4d5ba.png)

**Comment by Aka4** [comment]
Departments have over ride settings for Recipients for all of the events in one.

But what when we want:
-Department A to receive Ticket Transfer Alert for Department Members
-Department B to NOT receive any Ticket Transfer Alert
-All Departments to receive New Message Alert for Assigned Agent/Team

We do not have settings for each Event for each Department of these:

![image](https://cloud.githubusercontent.com/assets/11789024/8828118/bedc844c-3090-11e5-84e0-910a51e42f4e.png)

**Comment by greezybacon** [comment]
V1.10 adds an option to disable alerts when you extend access to a
department for each member. That is, when an agent joins a department other
than their primary department, they can opt out of alerts sent to
department members. Perhaps that will be of some utility

Am Mittwoch, 22. Juli 2015 schrieb Aka4 :

**Comment by mckaygerhard** [comment]
hello all , i think that @Aka4Code means its that the alerts and reminders options if could be per department event globally.. 

v1.10 and v1.9 allow me to disable alerts of new mesage and new tickets, but i want only disables new alers for only transfers in a particular departament, and rest of messages let normal..

this feature must be great , but please FOR THE CURRENT VERSION not for the long away future!

**Comment by asmith3006** [comment]
I'd like to vote for this feature too. 
Use case:
Department A is a large department and is able to define that "All staff must check helpdesk regularly". As a result of this I want to disable notification as 100's of people would get notifications.
Department B is small and has a lot of work already. I want them all to receive an email alert there is a new ticket awaiting them so they don't have to check the desk unless they know work is available.

**Comment by InvisibleFrisbee** [comment]
This would be a welcome feature. 
If you want to leave the transfer alert enabled globally, then each department should have a setting to opt-out of the transfer alerts. Our primary (large) department has agents in it all the time and there is no need to have an alert for inbound transfers into that department. A secondary department is not checked regularly and the lone agent in that department needs to receive notification on transfers into it.
