### ISSUE TITLE
Create Config->isPublicClientRegistrationEnabled()

### ISSUE THREAD

**Issue by Staja** [osTicket/osTicket#2274]
This function would almost be the same as _Config->isClientRegistrationEnabled()_ but would exclude 'auto'.

``` PHP
function isPublicClientRegistrationEnabled() {
    return in_array($this->getClientRegistrationMode(),
    array('public'));
}
```

All public facing registration code (UI) could then use that function instead.
- include/client/accesslink.inc.php:43
- include/client/login.inc.php:51
- include/client/view.inc.php:15
- account.php:25

This would allow for SSO to be more practical as per [my forum guide](http://osticket.com/forum/discussion/85969/iis-sso-and-normal-login-no-public-registration-with-automatic-user-creation-on-login) or ticket  #1944

**Comment by chrismuench** [comment]
I second this please.
