### ISSUE TITLE
way of hardcoded domian in "view.php" so users doen not write the domain part of email

### ISSUE THREAD

**Issue by mckaygerhard** [osTicket/osTicket#2278]
a way of user does not have to write the domain part (including the "@") in the check ticket status (view.php and accesslink.inc.php files i suppost)

**Comment by ntozier** [comment]
How would you handle sites that provide support for many different domains?

**Comment by mckaygerhard** [comment]
yes @ntozier in that case osticket works wonderfully, but i refers for a corporation ... sometimes users are so busy and need only put theirs id and the ticket number..

the ostiket in my case are deployed for a multi-office corporation (significally modified and improved by me and other, using a mysql brand scalar DBMS) and users in every ticket chek must enter the complete email.. 

will be wonderfully for that case (and that cases exists) if users only enter the login name and the ticket number!

wheantime i only need the lines where, this can be a well good feature for next mayor release with a check configuration in the admin panel that enables multi domain or single domain.

**Comment by greezybacon** [comment]
I suppose that using the client authentication system is right out, eh? It allows for simple username, password, and access to all previous tickets.

**Comment by Rankgel** [comment]
In my case, we have deployed the system for internal use, I would like to  force verification against single domain when  users only put  email id username whitout @ and full domain.

**Comment by ntozier** [comment]
@mckaygerhard your post does not answer the question I asked.  Which was 'How would you handle sites that provide support for many different domains?'  You do go on to make your use case, but do not outline a way to handle this type of feature for individuals whom have a different use case from you.

Also is there some reason why you wouldn't just use the already built in user accounts?  Which do not require you to enter the full email address?

@Rankgel have you tried the Authentication :: LDAP and Active Directory plugin?  Or the built in client authentication (mentioned earlier in this post)?

**Comment by mckaygerhard** [comment]
i answered!

for next: an option that enable simple domina only
for me! (or those like me): where i do that?!
for multidomain: an option that disables single domain

so simple ... now tell me where i must touch the files and i write code! i need that right now!

**Comment by mckaygerhard** [comment]
ping?

how's the progress of that?

in ostiket without login enabled a token are generated qnd a link like 
http://supportosticket/tickets.php?t=A5SLDJGwOWERJWQYIFWQG ;
are sent to users.. so if login are disabled users enter directly to tickets (using the %{ticket.client_link} variable)

but if i enable the "login required", this are changed to 
http://supportosticket/tickets.php?id=2387 ;
and the email are used event the username of the user!

i hope that explain more close that i want (and other want, in the forun some closed post are similar)

**Comment by mckaygerhard** [comment]
AFTER SOME IRRITATING RESPONSE FROM SOME DEVELOPERS USER REPOND HERE https://github.com/osTicket/osTicket-1.8/issues/678#issuecomment-45722153 the same as i requested here, ticket number direct access using the username login and not email or ticket id

**Comment by arrayown** [comment]
@mckaygerhard If I were you, I wouldn't expect the developers to tell you exactly what to change because at that point they might as well start working on the feature. If you are good at programming, track down the relevant file/code and make the modification yourself.

For your use case, it wouldn't even have to implement the option "single/multi domain" in the Admin that you explained for other use-cases. Just do it for yourself and, if you'd like, you can initiate a pull request for someone to pick it up later, develop it further and include in the next release cycles.

Hope this helps and good luck!

**Comment by mckaygerhard** [comment]
its no related to good programing skills, i have a job and i not have enought time to analise the code! and more important i also have a family to pay attention!

i research something at the class but got a 550 error, also there's many more errors that i reported SOLUTION AND STILL NOT ARE IMPLEMENTED in the code like  1964, the problem about the translation  paths 1686 or the window popup attachtments https://github.com/osTicket/osTicket-1.8/issues/2164#issuecomment-119995132

I therefore if I can say that I REALLY contributed and I have solved what I could, but I have no time to dedicate or get focused so many in this because I have business to attend to, I am a user not a developer of this software

and to finally, i only ask to start point, and to complete, i made the job that will help many others

**Comment by Rankgel** [comment]
I have been trying to do this, but really as a normal user 
My 5c contribution: of course reviewing the "class.auth.php" file as mentioned in ticket issue, the cited ***function says that seeks the user by mail***; well, ***how dificult can be for you guys allow to search valid user by both: the name of session and email of user?***

Then, remove the email verification in frontend for tickets links!

Now what if I understand the partner is there much specific code in those files that only you know the system developers, and obviously we lose our  time looking for something that you guys can help us
