### ISSUE TITLE
Link to close ticket in New Ticket/Message Alert

### ISSUE THREAD

**Issue by lehha** [osTicket/osTicket#2281]
It will be perfetct to have a link, that allow close ticket right in New Ticket/Message Alert email template (for Agent).

When we receive spam-message or not important letter, a close or delete this ticket is a slowly operatoin (click on open ticket link, wait to load, scroll to top, click "close", and confirm form...)

**Comment by infectormp** [comment]
similar to https://github.com/osTicket/osTicket-1.8/issues/2114

**Comment by greezybacon** [comment]
GitHub should do that too!
