### ISSUE TITLE
Mail fetch issues with v1.9.9-1-gbe2f138 (be2f138)

### ISSUE THREAD

**Issue by guidokuehler** [osTicket/osTicket#2282]
Include the Subject or the content from the Email an - char then osTicket cut the rest at this char!!!

Our Config:

Serverinformationen
osTicket-Version    v1.9.9-1-gbe2f138 (be2f138)
Server-Software nginx/1.8.0
MySQL-Version   5.5.44
PHP-Version 5.6.4-4ubuntu6.2
PHP-Erweiterungen
gdlib    Wird für die Bildmanipulation und PDF-Druck verwendet
imap     Wird für den E-Mail-Abruf verwendet
xml  XML API
xml-dom  Wird für die HTML E-Mail-Verarbeitung verwendet
json     Verbessert die Leistung beim Erzeugen und Verarbeiten von JSON
mbstring     Dringend empfohlen für nicht-westeuropäische Sprachinhalte
phar     Dringend empfohlen für Plug-ins und Sprachpakete
fileinfo     Wird verwendet, um Dateitypen für Uploads zu erkennen

Examples below:

Example 1

HtmlThreadEnabled = True
Original = <div style="font-size: 11px">
osTicket = <div style="font
osTicket-Thread-Table-Body= &lt;div style="font
osTicket-Thread-Table-Format=html

Example 2

HtmlThreadEnabled = False
Original = Neue SAP Version SAPGUI 7.40 - Patch 2 und Java 8 Support
osTicket = Neue SAP Version SAPGUI 7.40
osTicket-Thread-Table-Body=Neue SAP Version SAPGUI 7.40
osTicket-Thread-Table-Format=text

Example 3

HtmlThreadEnabled = True
Original=<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns:m="http://schemas.microsoft.com/office/2004/12/omml" xmlns="http://www.w3.org/TR/REC-html40">
osTicket=&lt;html xmlns:v="urn:schemas
osTicket-Thread-Table-Body=&lt;html xmlns:v="urn:schemas
osTicket-Thread-Table-Format=html

Example 4

HtmlThreadEnabled = True
Original=<!--
osTicket=&lt;!
osTicket-Thread-Table-Body=&lt;!
osTicket-Thread-Table-Format=html

How we can resolve this, we cannot receive any Email from different Clients in the Ticket-System!!!

Best Regards
Guido

**Comment by infectormp** [comment]
pop3 or imap?

**Comment by guidokuehler** [comment]
imap 


Von: "infectormp" <notifications@github.com> 
An: "osTicket/osTicket-1.8" <osTicket-1.8@noreply.github.com> 
CC: "guidokuehler" <guido.kuehler@it-power.biz> 
Gesendet: Freitag, 24. Juli 2015 08:08:18 
Betreff: Re: [osTicket-1.8] Mail fetch issues with v1.9.9-1-gbe2f138 (be2f138) (#2282) 



pop3 or imap?

**Comment by guidokuehler** [comment]
We have the same Results with pop3 and imap.

**Comment by guidokuehler** [comment]
Resolved!

Another Admin has set in Answer-Separator for Emails only a single minus!!!
