### ISSUE TITLE
Draft error after upgrade to 1.10 RC 1

### ISSUE THREAD

**Issue by fictionedge** [osTicket/osTicket#2289]
Had to roll-back to 1.9. Users were always getting the message "Unable to save draft" making it impossible to create a ticket.

**Comment by gmt-it** [comment]
I have the same error, log shows (5000 entries): 
 Ungültiger CSRF-Token CSRFToken

Ungültiger CSRF-Token [8f6c258bd40d94df886ea19b8aa8edffc75f4d5e] bei http://www.service.192.168.1.35.xip.io/ajax.php/draft/2173
 Log-Datum: Freitag, 24. Juli 2015 11:05 IP-Adresse: 92.xxx.xxx.xxx

**Comment by jdelhome3578** [comment]
Have you tried #2295

**Comment by fictionedge** [comment]
Can't test anymore, sorry. I did a roll back.
