### ISSUE TITLE
Missing app.php in /scp when click on Applications menu

### ISSUE THREAD

**Issue by avtaniket** [osTicket/osTicket#2291]
After adding an menu from plugin using 

```
    Application::registerAdminApp('Multi Tenancy', 'multitenancy.php', array(
        iconclass => 'api'
    ));
```

a menu item is added with "Applications" and sub-menu "Multi Tenancy", which is correct.
But when clicking on "Applications", it redirect to apps.php which is missing in osticket script.

Please review here.

**Comment by ntozier** [comment]
version of osTicket?

**Comment by avtaniket** [comment]
osTicket 1.9.6, I review repository and found its also missing in latest releases.

**Comment by greezybacon** [comment]
The `/apps/.htaccess` file is supposed to direct traffic to `/apps/dispatcher.php`, are you using IIS?

**Comment by avtaniket** [comment]
No, I'm not using IIS.

Issue occurs because of link with *apps.php*, Considering the *htaccess* at apps folder then the menu link should be change from *apps.php* To folder */apps*

**Comment by wooknight** [comment]
I have the same issue . Running Apache on centos 7

**Comment by SoftwareMods** [comment]
I've had several customers (osTicket Reports) as well as my own installations all run into this as well. Clicking on apps.php results in a 404. My latest installation is on CentOS 7:

```
[scott@rowleys ~]$ hostnamectl
<snip>
       Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
       Kernel: Linux 3.10.0-693.5.2.el7.x86_64
       Architecture: x86-64
</snip>

[scott@rowleys ~]$ httpd -v
Server version: Apache/2.4.6 (CentOS)
```

**Comment by Hoimar** [comment]
This is still a problem, see: https://forum.osticket.com/d/96924-plugin-development-how-to-use-the-dispatcher-to-route-links-to-your-plugin/2
And also issue #1072.

**Comment by joeldeteves** [comment]
I don't know why this issue was closed; this is still a problem.

(using @SoftwareMods' Reports plugin).

**Comment by Temepest74** [comment]
I still have this issue. Any help?

**Comment by Hoimar** [comment]
As I explained in the [forum post](https://forum.osticket.com/d/96924-plugin-development-how-to-use-the-dispatcher-to-route-links-to-your-plugin/3) linked above, you have to comment out the erratic if statement in `scp/apps/dispatcher.php`, line 17.

**Comment by Temepest74** [comment]
I cannot do that. I have to make a plugin for multiple people to download, so I can not change the source code of everyone.

**Comment by Hoimar** [comment]
That's unfortunate. I found no workaround for this issue. Then you need to either open a new issue for the original problem, submit a pull request or distribute your own fork of OSTicket :/

**Comment by joeldeteves** [comment]
> That's unfortunate. I found no workaround for this issue. Then you need to either open a new issue for the original problem, submit a pull request or distribute your own fork of OSTicket :/

@JediKev @ntozier seems like this issue shouldn’t be closed?

Please let us know what we can do to assist the OST team with reproducing the issue / logs / etc.

**Comment by JediKev** [comment]
@joeldeteves 

Go to `scp/apps/dispatcher.php` and above `if (basename($_SERVER['SCRIPT_NAME'])==basename(__FILE__))` add `var_dump($_SERVER['SCRIPT_NAME'], __FILE__);die;` and post the output here for review.

Cheers.

**Comment by Temepest74** [comment]
Hey @JediKev , I did what you said, but I see nothing. When I click on the Application button, I am redirected to scp/apps.php and I get a 404 error
![image](https://user-images.githubusercontent.com/28103890/113003640-97e05b00-917b-11eb-961a-fa0740e90014.png)

**Comment by JediKev** [comment]
@Temepest74 

I'm sorry, I forgot to update this thread yesterday. The feedback I received from the Team is that Applications was just a concept that was never finished and never fully implemented. You can tell as none of our core Plugins make use of Applications.

I don't see this as something we will be finishing/rewriting as we have stopped all major development on the current series (`1.14.x`/`1.15.x`). We stopped major development on the current series as we are shifting our focus to v2.0 (full codebase rewrite with fully modern UI/UX). We will still be doing bug fixes, security patches, and potentially small additions but no major code changes and no major features. With this being said v2.0 will be _much_ more extendable making it easier to create plugins. You can follow the [v2.0 Roadmap here](https://github.com/osTicket/roadmap).

Cheers.

**Comment by Hoimar** [comment]
@JediKev

Oh, that's great to hear. The codebase seems a bit complicated at times, I'm really looking forward to the rewrite.

I'm starting to write a plugin for OSTicket `1.15.x` in a few weeks, do you think I'll need to completely rewrite that for `2.0`?

**Comment by Temepest74** [comment]
Thank you so much for your response @JediKev

**Comment by JediKev** [comment]
@Hoimar 

Oh yes lol We are switching to a framework (with a complete/robust ORM) and using ReactJS + Semantic UI for the front end. The entire codebase will be _completely_ different.

Cheers.

**Comment by joeldeteves** [comment]
> @Temepest74
> 
> I'm sorry, I forgot to update this thread yesterday. The feedback I received from the Team is that Applications was just a concept that was never finished and never fully implemented. You can tell as none of our core Plugins make use of Applications.
> 
> I don't see this as something we will be finishing/rewriting as we have stopped all major development on the current series (`1.14.x`/`1.15.x`). We stopped major development on the current series as we are shifting our focus to v2.0 (full codebase rewrite with fully modern UI/UX). We will still be doing bug fixes, security patches, and potentially small additions but no major code changes and no major features. With this being said v2.0 will be _much_ more extendable making it easier to create plugins. You can follow the [v2.0 Roadmap here](https://github.com/osTicket/roadmap).
> 
> Cheers.

Very exciting!

Especially new / modern UI 😍

Thank you @JediKev
