### ISSUE TITLE
Slow database

### ISSUE THREAD

**Issue by gtulga** [osTicket/osTicket#2299]
Hi,

I am running 1.9.8.1 and it has 170K tickets. 90% of them closed. but it is very slow and I installed very fast and big server for DB. I think problem is query issues. I dont see any indexing in ost_ticket, ost_ticket_event and ost_ticket_thread etc.

Have you plan to use indexing for DB and increase query speed?

Thanks,

**Comment by infectormp** [comment]
@gtulga can you try 1.9.9?
* fix slow query for ticket counts for large datasets (c4ace2d)

**Comment by gtulga** [comment]
yes, I made this changes.
