### ISSUE TITLE
move last month's tickets to new system

### ISSUE THREAD

**Issue by gtulga** [osTicket/osTicket#2300]
Hi,

I installed 1.9.11 on new server. But I cannot move my old server. because it has 400K tickets and too big to migrate. is there any way to only move last month's (~30K tickets) to new installed server?

Thanks

**Comment by greezybacon** [comment]
As of yet, there is still no archiving system. I would suggest migrating everything but the attachments (the `ost_file_chunk` table) and thereafter deleting all the tickets you don't want to keep. Thereafter, you could export and import the attachment contents with `php manage.php file import -h`
