### ISSUE TITLE
Unable to create users and department

### ISSUE THREAD

**Issue by dmarketer** [osTicket/osTicket#2306]
if trying to create users or organisation ( add new user/ organisation) nothing is happen

**Comment by ntozier** [comment]
Version of osTicket?

**Comment by dmarketer** [comment]
1.10 rc

**Comment by ntozier** [comment]
This works fine in my 1.10rc test.
What happens when you click on the "Add new" buttons?

**Comment by greezybacon** [comment]
Is there anything in your PHP logs? Could you submit some screenshots of how you're triggering the error?
