### ISSUE TITLE
upgrade Error

### ISSUE THREAD

**Issue by ParmaU** [osTicket/osTicket#2308]
I upgraded the system osTicket version v1.9.11 to version 1.10 RC1
at the end gives me this error 

 [core]: Errore Upgrader

[INSERT INTO `ost_staff_dept_access` (`staff_id`,  `dept_id`,  `role_id`) SELECT A1.`staff_id`,  A2.`dept_id`,  CASE WHEN A2.`role_id` = 0 THEN A3.`role_id` ELSE A2.`role_id` END FROM `ost_staff` A1 JOIN `ost_group_dept_access` A2 ON (A1.`group_id` = A2.`group_id`) JOIN `ost_group` A3 ON (A3.`id` = A1.`group_id`) WHERE A2.`dept_id` != A1.`dept_id`] Table 'ostiket110.ost_group' doesn't exist

**Comment by infectormp** [comment]
this fixed in last branch
