### ISSUE TITLE
error : unable to save draft ... v 1.9.11

### ISSUE THREAD

**Issue by oneilak** [osTicket/osTicket#2309]
Hello everybody,

I have the problem, obtain the individual users following error message for some time.

some only once in other directly repeatedly.

why is that? you can disable the save? or you can adjust the latency?

I suspect that it is because that is our data center at another site and get the message when the WAN connection is busy

![11111](https://cloud.githubusercontent.com/assets/13413719/8902208/6cf669e6-344f-11e5-9886-e70fd698989f.png)

**Comment by oneilak** [comment]
hey
I have just the message when creating a Ticket.
I have the customer selected and at the moment where he wanted to take it came the message.
I have to run it just get through aktualliesierung the page

![1](https://cloud.githubusercontent.com/assets/13413719/8929427/9cb37e2c-3525-11e5-8842-6a7309c43d89.png)

**Comment by greezybacon** [comment]
Do you guys happen also to be receiving CSRF errors in your admin dashboard logs?

**Comment by oneilak** [comment]
no to this problem i dont have a csrf error

**Comment by Hannibal226** [comment]
@greezybacon

Did u say this should be fixed by changed in develop-next? 
But is this already in 1.9.11? Thought it will be coming with 1.10? 

So anyway the flag "annoyance" is more than correct here, heh :P

CHEERS

**Comment by barrydegraaff** [comment]
I totally HATE this alert message, with all the AJAX code running around in osTicket, one wonders why devel choose to use javascript alerts.

Why did osTicket not use an unobstructed message (like a toast message) that can be ignored by the user without clicking any buttons.

I find the draft pop-up happens a lot when staff is very fast in writing a ticket response, the reply response is send before the draft-save is completed.

Anyway this is VERY annoying.

**Comment by protich** [comment]
@barrydegraaff - Perhaps YOU should make a pull request to fix the issue?

**Comment by barrydegraaff** [comment]
Yeah you are right. In my install I removed 3 lines of code to suppress the message...

Maybe I will look into it tomorrow
________________________________

**Comment by barrydegraaff** [comment]
So Peter,

  
  



On a more constructive tone, can you tell me why the dialog was implemented like this?
What would be the harm in just removing it?
Thanks Barry

**Comment by barrydegraaff** [comment]
@protich I have created a PR for this issue, regards, Barry

**Comment by greezybacon** [comment]
Perhaps we should just remove it. Perhaps users would be less confused if their drafts just seemed to randomly be dropped

**Comment by barrydegraaff** [comment]
I would prefer to drop it, but not sure if the devs here would have liked that PR
________________________________

**Comment by Hannibal226** [comment]
@greezybacon
As I moved our ticket system from my local PC to a server we now have a lot more of those annoying alerts.  (maybe request times?) 

I'm reading this correctly and even with 'develop-next' no guarantee for getting rid of it? 
Or how is the state of this now? 

An personally I would like that even going back and forward keeping texts (working drafts), but anyway if there is no real solution, I prefer to delete it than having a couple of times multiple tickets opened or calls because of this alert. 

CHEERS 😉

**Comment by R1chardTM** [comment]
I am experiencing this issue very often and it is getting pretty annoying. Hoping for a fix soon.

**Comment by barrydegraaff** [comment]
Please note, that I already proposed a fix for this some 6 months ago....
https://github.com/osTicket/osTicket-1.8/pull/2480

**Comment by Hannibal226** [comment]
@barrydegraaff 
Don't get me wrong, but this isn't a fix, this is a workaround.
So even it's better, the problem itself is still there.

CHEERS!

**Comment by gbernabe** [comment]
I have this problem. is there fix now?????

**Comment by barrydegraaff** [comment]
Dunno, seems no body is taking pull requests here... https://github.com/osTicket/osTicket/pull/2480

**Comment by ntozier** [comment]
might have something to do with the conflicts with the PR?

**Comment by Hannibal226** [comment]
@barrydegraaff 
We personally using ur workaround and I'm happy to use it, but this still isn't a solution for the problem itself.
So like I said it's a workaournd, not a fix.

Thanks and CHEERS

**Comment by barrydegraaff** [comment]
yeah, there is a conflict cause no one merges the PR, so it is no longer up-to-date with the current code.

Depending on how you look at it, the problem the current error overlay creates, is worse then the problem of not saving a draft, anyway, it would be polite to close or deal with PR's in a timely manner.

**Comment by gbernabe** [comment]
I've been researching a lot. 

With this solution: 

https://github.com/osTicket/osTicket/pull/2480/commits/b06259a71b71c612349ad0047ccb34dc68e29a83

The problem doesn't occur in Internet Explorer, but occur in Chrome. 

Analyzing the file "redactor-osticket.js" i can see that the program save in cache every 10 seconds. If you close the windows before, then, you can see the error. I've thought that we can put less time. Five seconds for example. Surely, you don't complete any screen in less than 5 seconds. 

I don't know if I explained well with my english, sorry. 

I'm pleased to share all this with you.
