### ISSUE TITLE
OS 1.9.11 - CSRF-Token __CSRFToken__ error messages

### ISSUE THREAD

**Issue by oneilak** [osTicket/osTicket#2320]
can any one tell me what this exactly means this message?

is it normal that so often appears in the log?

![2](https://cloud.githubusercontent.com/assets/13413719/8930415/04f6ba6e-352e-11e5-8089-5f2945a4d569.png)
![3](https://cloud.githubusercontent.com/assets/13413719/8930416/05175f08-352e-11e5-9f13-e4ee24cbfac4.png)

**Comment by bwl21** [comment]
I observe such messages if the session is corrupt.
