### ISSUE TITLE
Responses to be sent from the Agent configured email ids

### ISSUE THREAD

**Issue by supportreq** [osTicket/osTicket#2326]
Hi @protich,

I guess we had this feature in older versions where the email responses sent was using the agent's email id and his smtp. Can we have it back as it is really useful considering the amount of blocks due to spam filter having one email id just kills the use of the backend system..

Please advice..

Thank You

**Comment by ntozier** [comment]
I'm not aware of that ever being a feature.
Departments can each have their own email address though.

**Comment by greezybacon** [comment]
I agree. We've planned adding this feature, but to my knowledge it's never existed in the mainline product
