### ISSUE TITLE
Installation PHP Error

### ISSUE THREAD

**Issue by sockzahh** [osTicket/osTicket#2327]
Hi There,

Receiving the following error just after submitting mysql db information:

> Fatal error: Uncaught exception 'Exception' with message 'Duplicate entry '21' for key 'PRIMARY'' in D:\home\site\wwwroot\include\class.orm.php:224 Stack trace: #0 D:\home\site\wwwroot\include\class.dynamic_forms.php(644): VerySimpleModel->save() #1 D:\home\site\wwwroot\include\class.dynamic_forms.php(195): DynamicFormField->save() #2 [internal function]: DynamicForm::create(Array, Array) #3 D:\home\site\wwwroot\include\class.i18n.php(76): call_user_func_array('DynamicForm::cr...', Array) #4 D:\home\site\wwwroot\setup\inc\class.installer.php(158): Internationalization->loadDefaultData() #5 D:\home\site\wwwroot\setup\install.php(52): Installer->install(Array) #6 {main} thrown in D:\home\site\wwwroot\include\class.orm.php on line 224

Running from latest git pull

The database is written but it doesn't look like the config file is being written.

Being installed on Azure Web App with MySQL DB running PHP 5.4

Any pointers would be great, thanks.

**Comment by greezybacon** [comment]
Were you installing with a primary language other than US-English?

**Comment by sockzahh** [comment]
Just plain US english, nothing fancy.

**Comment by greezybacon** [comment]
What branch did you install from?

**Comment by sockzahh** [comment]
Currently running from develop but error was still persisting on first try with stable release.

**Comment by alaingmail** [comment]
Hi,

I'm experiencing the same error with version 1.9.11:

Fatal error: Uncaught exception 'Exception' with message 'Duplicate entry '21' for key 'PRIMARY'' in D:\home\site\wwwroot\Member\Support\include\class.orm.php:224 
Stack trace: 
#0 D:\home\site\wwwroot\Member\Support\include\class.dynamic_forms.php(644): VerySimpleModel->save() 
#1 D:\home\site\wwwroot\Member\Support\include\class.dynamic_forms.php(195): DynamicFormField->save() 
#2 [internal function]: DynamicForm::create(Array, Array) 
#3 D:\home\site\wwwroot\Member\Support\include\class.i18n.php(76): call_user_func_array('DynamicForm::cr...', Array) 
#4 D:\home\site\wwwroot\Member\Support\setup\inc\class.installer.php(158): Internationalization->loadDefaultData() 
#5 D:\home\site\wwwroot\Member\Support\setup\install.php(52): Installer->install(Array) 
#6 {main} thrown in D:\home\site\wwwroot\Member\Support\include\class.orm.php on line 224

50 tables have been created. I too am installing this on the Windows Azure Web App platform running PHP 5.4 and using a ClearDb MySql database.

Is there a fix for this issue?

**Comment by greezybacon** [comment]
Are you guys installing with a language pack or using US-English as the primary language at install time?

**Comment by alaingmail** [comment]
I believe I was installing with default values and did not explicitly doing anything related to choosing a language pack.

For the record I was able to get v1.10-rc.2 successfully installed, although I need more testing before I can be 100% sure all is OK with it. I also tried installing v1.9.12, the other latest release, but encountered the same error.
