### ISSUE TITLE
Adding New client from LDAP Lookup from Pop-up

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket#2336]
When I type in a name the drop down populates with users with `(remote)` after the name, I click on the new user but it does not populate the add user form.  What is the intended process for adding new users from LDAP?

**Comment by greezybacon** [comment]
Why does this issue keep coming up? Is the search on GitHub broken?!

**Comment by greezybacon** [comment]
Try the patch in #2335

**Comment by jdelhome3578** [comment]
I believe this is a different issue. This issue is with the ajax window.

**Comment by greezybacon** [comment]
Did you try the patch?

Am Donnerstag, 30. Juli 2015 schrieb jdelhome3578 :

**Comment by jdelhome3578** [comment]
Will try tomorrow

**Comment by jdelhome3578** [comment]
#2335 Does not fix this issue. When I start to type the user pops up in the type head but when I click on it nothing happens. The type head closes and just has what I typed.

![image](https://cloud.githubusercontent.com/assets/5774055/9006963/d9a9c0ac-375a-11e5-89b8-55f42a416e22.png)

**Comment by greezybacon** [comment]
Do you have an OU with a comma in its name?

**Comment by jdelhome3578** [comment]
No but the users name is Last, First

**Comment by kest874** [comment]
This functionality is workign fine for me, even with usernames having the comma.  At times it can be a little slow however to do the lookup.

**Comment by jdelhome3578** [comment]
@greezybacon  more info in image `0` will work and `1` will not. 

![image](https://cloud.githubusercontent.com/assets/5774055/9356605/f0395bee-464f-11e5-949f-7b5f720d1865.png)

**Comment by greezybacon** [comment]
Would anyone be able to test the patch in osTicket/core-plugins#85?

**Comment by oneilak** [comment]
@greezybacon 

i would try it but how can I edit the phar file? or you can "new" provide for a test?

**Comment by jdelhome3578** [comment]
@greezybacon Please create a phar and I will test.
