### ISSUE TITLE
INFO: Resende an history as the customer does not work ... 1.10 RC1

### ISSUE THREAD

**Issue by oneilak** [osTicket/osTicket#2338]
for the customer dont work the button resend an view history, nothing happens.
I'll just (if multiple entries are there) to the top of this page thrown

as agent it works

**Comment by ntozier** [comment]
Sorry but I am not sure what you are trying to say, since Users don't have an "edit and resend" button in my test installation.

**Comment by oneilak** [comment]
as customer

![2015_07_31_16_10_17_audius_gmbh](https://cloud.githubusercontent.com/assets/13413719/9009079/0948c1d4-379f-11e5-8dab-0279494e961f.png)

**Comment by ntozier** [comment]
IE11, Chrome, and Firefox... I don't see that.
![capture](https://cloud.githubusercontent.com/assets/1315768/9010192/8446dadc-3773-11e5-9669-80724a322620.PNG)

**Comment by oneilak** [comment]
crazy :P 

work you with ad auth or local?
has your user admin rights?

**Comment by oneilak** [comment]
ok normal customer (without admin rights, only customer account) with ad account also have the option

**Comment by greezybacon** [comment]
I think the drop-down has since been removed from the client interface
