### ISSUE TITLE
1.10 Issue - System message for Transfer on Task

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket#2340]
`Bob transferred this to None`

![image](https://cloud.githubusercontent.com/assets/5774055/9007461/7adaaa82-375f-11e5-83e5-e9e04c34c6bd.png)

**Comment by ntozier** [comment]
I cannot reproduce this one.
Please provide steps on how you did this.

**Comment by jdelhome3578** [comment]
This was produced on a task when transferring from one dept to another

**Comment by ntozier** [comment]
Still unable to reproduce, but my tasks page doesn't look anything like your screen shot.
Was there a fix released for the css formating issue on task pages (that I obv missed)?

**Comment by jdelhome3578** [comment]
I don't believe I added an mods from pull request. What does your screen look like?

**Comment by ntozier** [comment]
It looks like there is no css formatting.

**Comment by greezybacon** [comment]
Is the name of your department "None"?

**Comment by jdelhome3578** [comment]
I have the three default Maintenance, Sales, Support

**Comment by jdelhome3578** [comment]
Tested again from the tip of develop-next, still seeing the issue.

**Comment by greezybacon** [comment]
Did you maybe delete the department it was transferred to?

Am Mittwoch, 12. August 2015 schrieb jdelhome3578 :

**Comment by jdelhome3578** [comment]
With a clean install, I create a task under maintenance and transfer it to support I receive the message `transferred this to None`.

**Comment by jdelhome3578** [comment]
@greezybacon database entry for transfer has all `0`

![image](https://cloud.githubusercontent.com/assets/5774055/9356847/97f63dce-4651-11e5-8535-9988bf322e52.png)

**Comment by jdelhome3578** [comment]
@greezybacon @protich this is still an issue from tip develop-next

**Comment by jdelhome3578** [comment]
@greezybacon @protich this is still an issue from tip develop-next

**Comment by jdelhome3578** [comment]
@greezybacon @protich
Image from `_thread_event` table. Please note that the ticket transfer is fine but the task transfer has a `0` for `staff_id`, `dept_id`, `topic_id`.

![image](https://cloud.githubusercontent.com/assets/5774055/12923793/0be487f2-cf25-11e5-98ff-5b14dfa0debb.png)
