### ISSUE TITLE
1.10 RC1 Issues - Delete Draft

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket#2341]
Delete Draft does not clear the text in the response text box.

**Comment by greezybacon** [comment]
Yes it does ...

**Comment by jdelhome3578** [comment]
I double checked and I can't get it to delete/clear the text box

**Comment by jdelhome3578** [comment]
When I click the trash can to delete a draft Chrome says `Request URL:http://supportdpr/scp/ajax.php/draft/1
Request Method:DELETE
Status Code:404 Not Found`

**Comment by greezybacon** [comment]
Hmm. Can you send the content of your %draft table for `id` = 1?

**Comment by jdelhome3578** [comment]
![image](https://cloud.githubusercontent.com/assets/5774055/9212093/69652874-4054-11e5-8c5c-55bc7d15146a.png)

**Comment by jdelhome3578** [comment]
I have tried Chrome and IE 11 with no luck.

**Comment by jdelhome3578** [comment]
Still having the issue after testing from the tip of `develop-next`.

![image](https://cloud.githubusercontent.com/assets/5774055/9355971/965a648c-464b-11e5-8db5-aa36f90bea4d.png)

**Comment by jdelhome3578** [comment]
@greezybacon Still having the issue after testing from the tip of `develop-next`.

**Save**
![image](https://cloud.githubusercontent.com/assets/5774055/9356020/ea969412-464b-11e5-8f50-521d39d328d1.png)

**Delete**
![image](https://cloud.githubusercontent.com/assets/5774055/9355971/965a648c-464b-11e5-8db5-aa36f90bea4d.png)

**Comment by jdelhome3578** [comment]
@greezybacon still have issue in 1.10 rc2

**Comment by greezybacon** [comment]
You have to edit the web site in IIS and allow the DELETE verb

**Comment by jdelhome3578** [comment]
@greezybacon All verbs are allowed

**Comment by jdelhome3578** [comment]
@greezybacon  I am still having this issue

**Comment by greezybacon** [comment]
I still have no idea why you're having this issue

**Comment by jdelhome3578** [comment]
Found that verbs were restricted in the PHP Handler Mapping.
