### ISSUE TITLE
v 1.10 RC1 ... I see no other agents in statistics

### ISSUE THREAD

**Issue by oneilak** [osTicket/osTicket#2348]
I see no other agents in statistics,
i am logged on as admin

![unbenannt](https://cloud.githubusercontent.com/assets/13413719/9016903/f97077b2-37d4-11e5-94e3-000608a3ab93.PNG)

**Comment by greezybacon** [comment]
There's a privilege for that in the agent management page

**Comment by oneilak** [comment]
i have admin rights ... 

before the updatet I could see everything,
what for permissions I need, to see it?

**Comment by greezybacon** [comment]
<img width="790" alt="screen shot 2015-08-02 at 8 58 23 pm" src="https://cloud.githubusercontent.com/assets/672074/9029450/42a92228-3959-11e5-8ed3-e71ae3ce114c.png">

That one. The "Stats" one. However, it looks like it was accidentally dropped with Access Control 2.0 merge

**Comment by greezybacon** [comment]
Can you try the patch in #2358 for the permission to appear on the agent management page?

**Comment by oneilak** [comment]
perfectly that now goes :-)
