### ISSUE TITLE
Develop Next - PHP Fatal Error with Cronjob

### ISSUE THREAD

**Issue by gmt-it** [osTicket/osTicket#2353]
root@mail:~# /usr/bin/php5 /var/www/vhosts/test.me/service.test.me/api/cron.php

PHP Fatal error:  Call to a member function getQuestion() on a non-object in /var/www/vhosts/test.me/service.test.me/include/class.search.php on line 537

Fatal error: Call to a member function getQuestion() on a non-object in /var/www/vhosts/test.me/service.test.me/include/class.search.php on line 537

**Comment by gmt-it** [comment]
New Ticket via e-mail fetch shows:  Micha added invalid_address via Email (to) as collaborators 5 minutes ago

Mail system send this error:

This is the mail system at host mail.test.me.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<invalid_address@.SYNTAX-ERROR> (expanded from
    <invalid_address@.SYNTAX-ERROR.>): bad address syntax

Attached is Autoreply:
ForwardedMessage.eml
Betreff: 
Re: Test 99*1*0 [#100370]
Von: 
"[ Test Support ]" <ticketsupport@test.me>
Datum: 
02.08.2015 10:40
An: 
"invalid_address" <invalid_address@.SYNTAX-ERROR>

Guten Tag, invalid_address,
A collaborator hat soeben eine neue Antwort auf ein von Ihnen eröffnetes Ticket verfasst.

Was neues 99901

Am 02.08.2015 um 10:18 schrieb G.:

    Noch mal ein Test


    Am 02.08.2015 um 09:50 schrieb [ Test Support ]:

        Hallo Michaael,
        ein Support-Ticket mit der Nr. 100370 wurde erstellt. Ein Mitarbeiter wird sich sobald als möglich um Ihr Anliegen kümmern. Sie können dieses Ticket hier einsehen

**Comment by gmt-it** [comment]
![new_mail_ticket](https://cloud.githubusercontent.com/assets/10116166/9025535/41b160ca-3908-11e5-8409-122cd50b8226.png)

**Comment by greezybacon** [comment]
> New Ticket via e-mail fetch shows: Micha added invalid_address via Email (to) as collaborators 5 minutes ago

How is that a problem?

**Comment by gmt-it** [comment]
@greezybacon The Problem here is: A client send an e-mail and will not get the autoreply because the system send it to invalid_address@.SYNTAX-ERROR. The incoming mail has a valid address and no one added the collaborator manual. I think that is a problem, or?

**Comment by ntozier** [comment]
So wouldn't the fix to be to not add an invalid email as a collaborator?

**Comment by gmt-it** [comment]
A User send a e-mail to ticketsupport@test.me. The System read the mail and create a new ticket. You can see at screenshot, that ticket is created with the e-mail address of user "Micha". At the same time the System write to the ticket that the user,who send the mail, added an invalid mail address. No one added an invalid address, so no one can not add it to fix....
