### ISSUE TITLE
Email Loop

### ISSUE THREAD

**Issue by wfoster** [osTicket/osTicket#2354]
Hi Guys

I have an issue with an email loop. Basically we have the system popping from a postfix mailbox with this particular email account. The email account has an alias with the same name though. The reason for this is that the boss who does not want to use the ticket system still gets the emails coming in from the clients. So lets call the email software@domain.co.za. The alias is called software and forwards to software@domain.co.za and boss@domain.co.za.
No for some reason the ticket system does not like this setup. I need it to work though. I have now added myself to the alias to check how long the tickets take to reflect on the ticket system. Some take up to 6 hours. This is very strange. We also have a hardware@domain.co.za which has no alias or forwards, etc and the tickets come through within 2 minutes.

Is there a way that I can resolve this?

Thanking you in advance. Below is the error message
![untitled](https://cloud.githubusercontent.com/assets/7644638/9025963/0f3a6a6a-391c-11e5-8169-05709c8fe28c.jpg)

**Comment by greezybacon** [comment]
Usually the email loop is invoked with a recpient of an email, like a staff alert or the administrator address is also fetched as a system email. That's the part of the loop you need to fix: separate agent and inbound email addresses.

**Comment by wfoster** [comment]
Removed the aliases from the postfix box so no forwarders exits anymore on there. Seems to have resolved the issue. Please excuse this not getting closed sooner. tnx
