### ISSUE TITLE
Request for function: Modifying ticket view for agents

### ISSUE THREAD

**Issue by oneilak** [osTicket/osTicket#2363]
what be really would  great, if i would adjust at the agent panel the view in over the ticketlist.

that means for example, 
i want to see the departments, as a column in the ticketlist is.

**Comment by mfelber** [comment]
If I'm not wrong the feature you are suggesting is already planned for osticket 1.11 and it's called "custom queue".

**Comment by oneilak** [comment]
oh if that's true then that is super :-)

can it confirm maybe someone? * nice look *

**Comment by mfelber** [comment]
When you use the github search you will see that the developers have talked about this feature. Here is an example: https://github.com/osTicket/osTicket-1.8/issues/2166 I think the feature that you suggested is the same feature that alexyoung28 suggested or do mean something different?

**Comment by oneilak** [comment]
ok its perfect :-)
