### ISSUE TITLE
1.10 RC1 Issues - Knowledgebase Article Listing Type

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket#2365]
Listing Type does not come up as Featured when it was saved as Featured and appears in the Featured section. This happens for both Article and Category.

![image](https://cloud.githubusercontent.com/assets/5774055/9045168/69b2f77c-39ef-11e5-9423-5739f752d7a9.png)
![image](https://cloud.githubusercontent.com/assets/5774055/9045067/cbe24926-39ee-11e5-96d2-15f56d8a8382.png)
![image](https://cloud.githubusercontent.com/assets/5774055/9045082/e044d3f2-39ee-11e5-9988-88d18fc94c51.png)

**Comment by greezybacon** [comment]
Is this still relevant? I can't reproduce it with the tip of `develop-next`

**Comment by jdelhome3578** [comment]
Articles are working right but Category is still coming up the same

**Comment by jdelhome3578** [comment]
@greezybacon  1.10 rc2 still has this issue with category

**Comment by jdelhome3578** [comment]
Fixed with PR #3200
