### ISSUE TITLE
 process Adjustment: department transfer - no agent assign

### ISSUE THREAD

**Issue by oneilak** [osTicket/osTicket#2366]
Hello there,

I would find it great if the following change would be possible.
when I transfer a ticket to another department, it should assigned no agent more.

currently it is a problem for us, if I give a ticket in a different department, i must make a transfer to a another agent

**Comment by ntozier** [comment]
This appears to be a duplicate request of https://github.com/osTicket/osTicket-1.8/issues/1100

**Comment by oneilak** [comment]
@greezybacon 

comes to the checkbox now? :-)

**Comment by greezybacon** [comment]
@protich is working on that part of the system at the moment. He claims the checkbox will be added for the stable release
