### ISSUE TITLE
'Translation' Table prefix missing 

### ISSUE THREAD

**Issue by avtaniket** [osTicket/osTicket#2370]
For osTicket-v1.10-rc.1, there has hard coded use of translation table as "ost_translation"...which need to be change with table prefix.

Issue occurs during installation and process, throws sql fatal error as 

Fatal error: Uncaught exception 'InconsistentModelException' with message 'Unable to prepare query: Table 'db_anikettlara.ost_translation' doesn't exist SELECT A1.\* FROM `ost_translation` A1 WHERE (A1.`lang` = ? AND A1.`type` = ?)' in /var/www/testproject/anikett/osticket_v110/include/class.orm.php:2660 Stack trace: #0 /var/www/testproject/anikett/osticket_v110/include/class.orm.php(2653): MySqlExecutor->execute() #1 /var/www/testproject/anikett/osticket_v110/include/class.orm.php(2729): MySqlExecutor->_prepare() #2 /var/www/testproject/anikett/osticket_v110/include/class.orm.php(1499): MySqlExecutor->getArray() #3 /var/www/testproject/anikett/osticket_v110/include/class.orm.php(1322): ModelInstanceManager->fillTo(0) #4 /var/www/testproject/anikett/osticket_v110/include/class.translation.php(899): ResultSet->valid() #5 /var/www/testproject/anikett/osticket_v110/include/class.translation.php(920): CustomDataTranslation::getTranslation('en_US') #6 /var/www/testproject/anikett/osticket_v110/include/class.list.php(328): Custo in /var/www/testproject/anikett/osticket_v110/include/class.orm.php on line 2660

**Comment by mfelber** [comment]
@avtaniket This seems to be same issue that was reported here https://github.com/osTicket/osTicket-1.8/issues/2302 and was fixed with https://github.com/osTicket/osTicket-1.8/pull/2324. The actual develop-next branch has already this fix (and others too).
