### ISSUE TITLE
V 1.9.11/ RC 1.10 r1 ... no login with number as username

### ISSUE THREAD

**Issue by oneilak** [osTicket/osTicket#2378]
hey

i make a test with a number as username, he say access denied.

is it normal?

**Comment by ntozier** [comment]
Yes.

**Comment by oneilak** [comment]
Ehe?:-p

**Comment by oneilak** [comment]
Why?:-p

**Comment by greezybacon** [comment]
Maybe y'all could try #2393

**Comment by rayfoss** [comment]
Closing duplicate issue, please continue the conversation on the ne
