### ISSUE TITLE
1.10rc1 - Users tab Export issues

### ISSUE THREAD

**Issue by nfebuary** [osTicket/osTicket#2383]
The Export at the bottom of the User Directory list produces this error: "Query Token Required". 

The Export at the bottom of the Organizations list redirects to ../scp/orgs.php?a=export&qh=0688838aa7dbfa350501a2e0bd2cae9e a blank page.

**Comment by ntozier** [comment]
I presume that this bug report is for version 1.10rc1.

**Comment by nfebuary** [comment]
Yes and I changed the title to be more specific.

**Comment by jdelhome3578** [comment]
I see the same issue

**Comment by Fmkjr** [comment]
This issue is still present in RC2 you can not export users list

**Comment by richardtuttle** [comment]
This issue is still happening on version 1.10(901e5ea)

**Comment by balojs** [comment]
@rayfoss  please check this bug

**Comment by ntozier** [comment]
ticket export had an issue to.  it's here:
https://github.com/osTicket/osTicket/issues/3264

Maybe the same or a similar fix will work

**Comment by balojs** [comment]
thanks @ntozier

**Comment by balojs** [comment]
ticket export had an issue to. it's here: #2197

**Comment by balojs** [comment]
ticket export had an issue to. it's here: #3705
