### ISSUE TITLE
Help topics in multiple combos

### ISSUE THREAD

**Issue by S0lidARRAY** [osTicket/osTicket#2388]
A quick look from this [forum thread.](http://osticket.com/forum/discussion/78585/help-topics-in-multiple-combos) Right now, I have about 36 help topics (with a whole lot more coming in the near future) and managing them is so confusing not only for agents but for users as well. My question is, Will this feature get implemented in the next version of osTicket?

**Comment by ntozier** [comment]
![addhelptopic](https://cloud.githubusercontent.com/assets/1315768/9198603/2651def4-400b-11e5-8f51-a97fe7e1a2f3.PNG)

Sort of... but not exactly like the mod that you linked too.
