### ISSUE TITLE
Upgrade from 1.9.2 to 1.9.11 fails with Call to undefined function __() 

### ISSUE THREAD

**Issue by AlexeyDemidov** [osTicket/osTicket#2389]
While upgrading from 1.9.2 to 1.9.11 it fails with following error message:

PHP Fatal error:  Call to undefined function __() in SOMEPATH/osticket_1.8/upload/scp/upgrade.php on line 80

Removing _() wrapper around word 'Upgrader' allows it to continue. After that it fails again with 
CSRF token complain but going through login page helps. 

I have PHP gettext extension available.

**Comment by ntozier** [comment]
Can you please provide some more information about your setup?  (Admin panel -> Dashboard -> Information)

**Comment by AlexeyDemidov** [comment]
Server Information
osTicket Version	v1.9.11 (c1b5a33) —  Up to date
Web Server Software	Apache/2.2.22 (Debian)
MySQL Version	5.5.44
PHP Version	5.5.27-1~dotdeb+7.1
PHP Extensions
gdlib	 Used for image manipulation and PDF printing
imap	 Used for email fetching
xml	 XML API
xml-dom	 Used for HTML email processing
json	 Improves performance creating and processing JSON
mbstring	 Highly recommended for non western european language content
phar	 Highly recommended for plugins and language packs
fileinfo	 Used to detect file types for uploads
PHP Settings
cgi.fix_pathinfo	 "1" is recommended if AJAX is not working
date.timezone	 UTC
Database Information and Usage
Schema	ost_rebsoc (localhost)
Schema Signature	b26f29a6bb5dbb3510b057632182d138
Space Used	364.58 MiB
Space for Attachments	121.79 MiB
