### ISSUE TITLE
 boostrap-typeahead.js / typeahead.css should NOT be loaded from scp/css and scp/js

### ISSUE THREAD

**Issue by ghost** [osTicket/osTicket#2402]
Since many people (like me) would like to have http auth enabled on the /scp/ directory, I see no point in including css and js files from the scp/css and scp/js directory on the client frontend.

I have created the two new files js/boostrap-typeahead.js and css/typeahead.css and changed the include/client/header.inc accordingly.

Pull Request: #2401 

Thanks

**Comment by JediKev** [comment]
Here is the fix for anyone interested:
- https://github.com/osTicket/osTicket/pull/6541
