### ISSUE TITLE
v1.10 RC1 Ticket Status bug

### ISSUE THREAD

**Issue by rpbaquing** [osTicket/osTicket#2403]
I cannot add new ticket status nor delete from existing.

**Comment by jdelhome3578** [comment]
Are you testing from the tip of develop-next? I believe this was fixed in #2314.

**Comment by rpbaquing** [comment]
I am testing the latest beta. I will try that fix.

Thanks

**Comment by balojs** [comment]
fix available  #3236

**Comment by balojs** [comment]
@rayfoss  fix available #3236
