### ISSUE TITLE
Auto select Priority level based on Help topic setup

### ISSUE THREAD

**Issue by mmmartinez011** [osTicket/osTicket#2409]
Hi,

How to make the assigned Priority level based on Help topic from admin panel be selected upon opening a new ticket?

Thanks in advance.

**Comment by ntozier** [comment]
Admin panel -> Manage -> Help Topic -> your help topic -> Priority

**Comment by mmmartinez011** [comment]
I already do it. But nothing happen. I'm using osTicket (v1.8.1.2). The default priority of the system is always selected upon opening or creating a new ticket.

**Comment by ntozier** [comment]
I'd recommend that you upgrade.  1.8.1.2 is old. 
The current version in the 1.8 tree is 1.8.12.  
1.9.11 is current, and 1.10 is just around the corner.

**Comment by greezybacon** [comment]
I think this doesn't work in v1.10 either. The problem is that the help topic can be changed on the new ticket page and we don't fetch the list of default priorities for every possible help topic so we can reflect changes in help topic in the priority drop down
