### ISSUE TITLE
Allowed Memory Size Exhausted in class.filter.php v.1.9.11

### ISSUE THREAD

**Issue by abssoft** [osTicket/osTicket#2414]
I have Ticket Filter that should prevent reply for ticket, come from no-reply@tld.com
![2015-08-14 08-58-33](https://cloud.githubusercontent.com/assets/946560/9265816/b02f880c-4262-11e5-9cab-41b465d4a084.png)

And after upgrading to 1.9.11 cron started to raise an Exeption "Allowed Memory Size Exhausted in class.filter.php:325"

Exeprion is raised at /include/class.filter.php:325

```
throw new FilterDataChanged($ticket);
```

catched by /include/class.ticket.php:2481 (function filterTicketData)

```
catch (FilterDataChanged $ex) {
        // Don't pass user recursively, assume the user has changed
        return self::filterTicketData($origin, $ex->getData(), $forms);
}
```

and started over again

seems that there is infinite recursion

**Comment by justpusher** [comment]
I faced the same problem and found one of the reasons. 
In my case there was a saved user with lowercase email (abc@domain.com), and the received email has some of the letters uppercase (ABc@domain.com). So ticket email was first overwritten in    
 ```
Ticket::filterTicketData 
$vars['email'] = $user->getEmail(), 
```

then again overwritten in 

```
Filter::apply 
$ticket['email'] = $info['reply-to']
```

, and ticket considered changed, and filter applied again, and so on without the end. 
I suggest using case-insensitive comparison (strcasecmp) in Filter::apply

`$changed = 0 != strcasecmp($info['reply-to'], $ticket['email'])
                || ($info['reply-to-name'] && 0 != strcasecmp($ticket['name'], $info['reply-to-name']))`

**Comment by JensEB** [comment]
Hello,

It isn´t a bug in PHP.
If a reply-to adress exists, the function Ticket::filterTicketData() produces a endless loop, because it´s a recursive funktion.
The function Filter::apply() checks only if $info['reply-to'] exists and it exist in every loop...

so I changed the checkup from: (osTicket 1.9.14 - ./include/class.filter.php line 318 function apply)
if ($this->useReplyToEmail()  && $info['reply-to']) {
to:
if ($this->useReplyToEmail()  && (strcasecmp($info['reply-to'], $ticket['email']) != 0)) {

Now it checks if reply-to is not to-adress. This fails in second loop, because to-adress is changed in reply-to-adress....

It seems to work. I hope, this helps you...

**Comment by tmp2000** [comment]
I use JensEB's patch ,it is ok now.

**Comment by ntozier** [comment]
Official fix looks to be here: https://github.com/osTicket/osTicket/pull/3437

**Comment by JensEB** [comment]
The official Fix can´t work. There is no file include/class.filter_action.php in V1.9.14....
Witch Version is there supported?

**Comment by tmp2000** [comment]
I use 1.8-git,as for the official fix ,I changed the class.filter.php from 
        if ($this->useReplyToEmail() && $info['reply-to']) {
            $changed = $info['reply-to'] != $ticket['email']
                || ($info['reply-to-name'] && $ticket['name'] != $info['reply-to-name']);
            $ticket['email'] = $info['reply-to'];
            if ($info['reply-to-name'])
                $ticket['name'] = $info['reply-to-name'];
            if ($changed)
                throw new FilterDataChanged($ticket);

        }

to 


        if ($this->useReplyToEmail() && $info['reply-to']) {
            //$changed = $info['reply-to'] != $ticket['email']
            //    || ($info['reply-to-name'] && $ticket['name'] != $info['reply-to-name']);
            if(!$info['reply-to'] && !$ticket['email'] && !strcasecmp($info['reply-to'], $ticket['email'])){
                // Change email and  throw data changed exception
                $ticket['email'] = $info['reply-to'];
                if ($info['reply-to-name'])
                    $ticket['name'] = $info['reply-to-name'];
                throw new FilterDataChanged($ticket);                  
            }
        }

**Comment by protich** [comment]
@JensEB - You should upgrade to 1.9.15 which includes the fix as per this commit 9e1cf3bf. 

@tmp2000  - We don't have version called `1.8-git`. My guess is your installation is running directly from your git repo - which you haven't updated in a while (git fetch & merge).

**Comment by tmp2000** [comment]
@protich yes,I get from osticket's one repo.Not Stable version.Might be 1.9.* version.Not upgrade for  a long time.While for the 9e1cf3b commit,I think it should be 

!strcasecmp($info['reply-to'], $ticket['email']) add "!" .Only the value between $info['reply-to'] and $ticket['email'] not equal the value  $ticket['email'] should be changed and throw FilterDataChanged.

**Comment by tmp2000** [comment]
@protich yes,I got one repo here,but not stable version.As for the 9e1cf3b,I found my error submit before.Should remove "!" before strcasecmp.
