### ISSUE TITLE
Certain fields in "Organization Information" form not being saved

### ISSUE THREAD

**Issue by mtibbits140** [osTicket/osTicket#2415]
When I enter a new organization I fill out all of my required fields from the organization information form. After it saved, I go back to view the data and it hasn't saved. There are a large number of fields that are once again empty. Most of these are required fields, but not all. 

I know there was an issue with this in the past that was fixed, I believe, in #1942. 

In the first screenshot you can see that my data has been entered. When I click on "Add Organization" I get the error that you see in the second image. 

I click "ok" and then when I click on the org name to view the data, a large portion of it is missing as you can see from the 3rd screenshot. 

If I retype the missing data a second time and click "update organization" then it will save.

This seems to have started since upgrading to version 1.9.11. 
![ost_01](https://cloud.githubusercontent.com/assets/13353202/9280504/311108ec-4295-11e5-9d5a-485e8346dcb3.jpg)
![ost_02](https://cloud.githubusercontent.com/assets/13353202/9280518/426ffeae-4295-11e5-9441-5482c48ee23b.jpg)
![ost_04](https://cloud.githubusercontent.com/assets/13353202/9280522/45c27eba-4295-11e5-9138-5e133f4685fd.jpg)

**Comment by mtibbits140** [comment]
Can anybody help with this?

**Comment by greezybacon** [comment]
> some reason that update actually broke things...

What was broken?

**Comment by mtibbits140** [comment]
Ok, I am still having this issue, but can now add more info: 

When creating an organization or a user, any information selected in a drop down field is not being saved. I have to re-open the org or the user, re-select the information in those drop down fields and ONLY THEN is it actually saved to the database.

These drop down fields are custom form fields using custom lists. 

This started happening for me when I updated to 1.9.11. I have since updated to 1.9.12 and still having the same issue.  

I have attached screen shots. Any thoughts or ideas on how to fix this? 
![2015-09-21_13-45-56](https://cloud.githubusercontent.com/assets/13353202/9998740/108de8fa-6069-11e5-89fa-7e34dac61963.png)
![2015-09-21_13-46-50](https://cloud.githubusercontent.com/assets/13353202/9998738/108b4bc2-6069-11e5-9b0e-be3bc8fdbabb.png)
![2015-09-21_13-47-17](https://cloud.githubusercontent.com/assets/13353202/9998739/108da048-6069-11e5-97d7-59f1302a59d6.png)
![2015-09-21_13-49-55](https://cloud.githubusercontent.com/assets/13353202/9998737/108ad340-6069-11e5-99d8-6a95d4a46bca.png)

**Comment by mfelber** [comment]
I have reported the same here (at this time I didn't notice that you are describing the same): https://github.com/osTicket/osTicket-1.8/issues/2489

I guess this is a design limitation in 1.9.x.

In 1.10 (still beta) this issue doesn't occurs.
