### ISSUE TITLE
1.10 RC1 Error creating a new installation with languages different from english

### ISSUE THREAD

**Issue by ManuDoni** [osTicket/osTicket#2419]
When I select a primary language, different from english, during the installation process it runs for a few second and then returns a blank page.
I've tried with it.phar, fr.phar and de.phar.
The date of these .phar is June, 23rd, 2015 (the last available for now)
The php log is:

```
( ! ) Fatal error: Uncaught exception 'InvalidArgumentException' with message 'List indices should be integers' in C:\Apache24\htdocs\osticket_last\include\class.util.php on line 147
( ! ) InvalidArgumentException: List indices should be integers in C:\Apache24\htdocs\osticket_last\include\class.util.php on line 147
Call Stack
#   Time    Memory  Function    Location
1   0.0028  155576  {main}( )   ...\install.php:0
2   0.0621  2383328 Installer->install( )   ...\install.php:52
3   14.1185 12603944    Ticket::create( )   ...\class.installer.php:291
4   14.2317 12743520    Ticket::filterTicketData( ) ...\class.ticket.php:2917
5   14.2637 12783744    Form->getField( )   ...\class.ticket.php:2741
6   14.2643 12783800    ListObject->offsetExists( ) ...\class.ticket.php:81
```

**Comment by greezybacon** [comment]
The file formats for v1.10 are a bit different. We haven't upgraded the language packs to work with v1.10. That said, it shouldn't crash

**Comment by BastianBalthasarBux** [comment]
Can confirm:
Same error occurs with official packages from osticket page, at least with de.phar and Core v1.10.1!

**Comment by JediKev** [comment]
@BastianBalthasarBux please follow #3865 for updates. This is an oldddd thread. Thanks.

**Comment by BastianBalthasarBux** [comment]
Oldie but goldie ... ;)

Any chance for using 'duplicates' and 'the like' states for the issues? If set 'duplicate', it would make sense to close this one afterwards. And it makes it easier for people to find a solution, if duplicate-threads are connected.
I found at least a third ticket with that issue, and with 1146 open issues I am pretty sure, there are more tickets as duplicates!
