### ISSUE TITLE
Futurure request: FAQ on File Link / Share

### ISSUE THREAD

**Issue by oneilak** [osTicket/osTicket#2420]
hey everyone

it was be nice when i can link a file or shares in the FAQs.
have we in the future a chance for such a feature

**Comment by jdelhome3578** [comment]
Are you talking about some how inserting a link to a FAQ in a ticket response?

**Comment by oneilak** [comment]
as exampel

i write a new faq for junk mails, and i will link a dokument from a share with informations.
i don´t will attached it, because of changes in the document or duplicate data storage.

![unbenannt](https://cloud.githubusercontent.com/assets/13413719/9312664/734738ae-451e-11e5-9758-434eae3d5f08.PNG)

**Comment by ntozier** [comment]
Maybe you would fine this helpful?
http://stackoverflow.com/questions/5796215/an-url-to-a-windows-shared-folder

**Comment by oneilak** [comment]
![2015-08-19 14_03_23-osticket __ agenten-bereich](https://cloud.githubusercontent.com/assets/13413719/9355634/2074101c-467b-11e5-8bb4-60f5fe2696a8.png)

**Comment by ntozier** [comment]
http://file//ff does not appear to be a valid URL for a HREF.  
File URLS are formatted file://host/path where host is the FQDN of the system which the path is accessible, and path is the directory path to the target file.  Also last I checked some web browsers refuse to follow file links on pages.  You should really be using a valid HTTP: URL.

**Comment by oneilak** [comment]
the problem is 

i write
![unbenannt](https://cloud.githubusercontent.com/assets/13413719/9366424/9099b356-46b7-11e5-9d16-6fb065edf326.PNG)


an osticket save it thus
![unbenannt2](https://cloud.githubusercontent.com/assets/13413719/9366425/94600b34-46b7-11e5-93c7-082d86798650.PNG)

**Comment by greezybacon** [comment]
So it seems like this is a redactor related issue

**Comment by abstractmodel** [comment]
i got exactly the same problem. version 1.9.11.

saying it's redactor related is not a solution for us...

**Comment by mfelber** [comment]
@abstractmodel I don't think that the comment should reflect a solution. 
It should only say this behavior is redactor related. With this information people could try for example to use the redactor documentation to see if this behavior is adjustable or if it is a design limitation.

It seems to me that the redactor expects URLs via http and not the file protocol and therefore the saved URLs will be "cleaned".

One possible workaround could be the hint from ntozier: 
configure your webserver to make those files available via a http URL.

**Comment by JediKev** [comment]
Implemented in later versions.
