### ISSUE TITLE
v 1.9.11 wrong data export - v 1.10-RC2 is it worse

### ISSUE THREAD

**Issue by oneilak** [osTicket/osTicket#2430]
hey to all

I know that the statistics not 100% worked ...

I noticed when I set the filter for example, on 01/06/2015 sit and say all tickets for 1 month, he shows so far also everything.
But when I say exports, it takes the data from 01.06.2015 until today.

Is there a workaround?

**Comment by oneilak** [comment]
in 1.10 rc2 it works even worse :-(

**Comment by greezybacon** [comment]
> in 1.10 rc2 it works even worse :-(

Care to elaborate?

**Comment by oneilak** [comment]
please?

**Comment by ntozier** [comment]
@greezybacon is asking to elaborate on what 'works even worse'.

**Comment by oneilak** [comment]
Tickets from 1 May for the period of 1 month
![stat1](https://cloud.githubusercontent.com/assets/13413719/9394132/f8fc1b8a-4786-11e5-9cc0-a19aaad0c4e4.PNG)

![stat2](https://cloud.githubusercontent.com/assets/13413719/9394139/fe1fdf5c-4786-11e5-868d-80548247dd01.PNG)


and here the export to Excel
![export](https://cloud.githubusercontent.com/assets/13413719/9394141/00272e7c-4787-11e5-8a67-eb2d460e691e.PNG)

**Comment by greezybacon** [comment]
Could you maybe post the raw CSV text?
