### ISSUE TITLE
Blank modal window when closing ticket

### ISSUE THREAD

**Issue by jjarvela** [osTicket/osTicket#2434]
Blank modal Window appears in osTicket 1.9.12 (19292ad) when trying to close or resolve ticket.
This also happens when trying to add new ticket or collaborator address to ticket. This bug might be reported with earlier versions but it seems to keep coming back. Happens in all browsers. 
![modal_bug](https://cloud.githubusercontent.com/assets/9404675/9376898/b5bf6a5e-471b-11e5-880e-10ea7e949e98.png)

Environment:
OsTicket v1.9.12 (19292ad)
nginx/1.6.2
mysql 5.6.25
PHP 5.6.4-4ubuntu6.2
Schema signature b26f29a6bb5dbb3510b057632182d138

**Comment by mfelber** [comment]
I can't reproduce it with 1.9.12. Do you use some special plugins? The similar issues that were reported in the past that I have seen so far were related to a "wrong" nginx config or a "bad merge from an i18n change" ..

**Comment by ntozier** [comment]
Sounds to me like an AJAX issue... 
Please see: https://github.com/osTicket/osTicket-1.8/issues/382
As a reminder nginx is not a web server software that we support.
