### ISSUE TITLE
question 1.10-RC2: what is the claim funktion?

### ISSUE THREAD

**Issue by oneilak** [osTicket/osTicket#2435]
hey

what exactly does the assignment "claim".
does it have any special effects?

![2015-08-20 08_41_14-ticket 992025](https://cloud.githubusercontent.com/assets/13413719/9377247/41eb73ba-4717-11e5-8bc1-6b117640e31b.png)

**Comment by clarkies** [comment]
Hi,

This will assign the ticket to the person who is currently logged in.

Thanks

**Comment by mfelber** [comment]
By the way: this isn't a new feature. It also exist in former versions of osticket. Only the placing of this has changed..

**Comment by oneilak** [comment]
hey i cant find "claim" in the older version ... it has the same function as when i click on assign->agent

![2015_08_20_10_56_12_ticket_700226](https://cloud.githubusercontent.com/assets/13413719/9379542/5ac09a1a-472a-11e5-8078-ea2c68474ab0.png)

**Comment by mfelber** [comment]
claim in the older versions:

![claim](https://cloud.githubusercontent.com/assets/5539456/9379814/34384b8e-472c-11e5-9f2b-be708434411d.jpg)

claim = self assign

**Comment by oneilak** [comment]
I did not in the v 1.9.11 :-(

![2015_08_20_11_16_51_ticket_518091](https://cloud.githubusercontent.com/assets/13413719/9379936/14ad9606-472d-11e5-94d9-6c925c4f9d9b.png)

So if I understand it correctly (simply put), I click on it since and is then assigned to ticket me?

**Comment by mfelber** [comment]
Yes, this is how it works. You have this button but you only see this button when the ticket is unassigned and when you are allowed to assign tickets..

**Comment by oneilak** [comment]
ah ok, in the old version i see it.

should I then only see it in the new version, it does not have nobody assigned?

is this correct behavior:
when I click on it to, open the list with all agents.
I can then select one and the ticket assignment on a agent.

**Comment by AVenzorSO** [comment]
I know this is an old thread, but it seems to be the same issue. On a fresh install of RC2 when I click "Claim" it brings up the assign dialog. It's no different than me clicking "Agent" instead and I'm guessing it's not the intended function.
