### ISSUE TITLE
question 1.10-RC2: image for agents

### ISSUE THREAD

**Issue by oneilak** [osTicket/osTicket#2436]
hey

How can I store an image in my account?

![2015_08_20_08_43_21_osticket_staff_control_panel](https://cloud.githubusercontent.com/assets/13413719/9377284/9d300a6a-4717-11e5-8970-7efb25da34d0.png)

**Comment by mfelber** [comment]
Do you are talking about the avatar system? If so, you can for example create an gravatar.com-Account and "store" an image there. Then osticket will "recognize" you (if you use the same email address for example as agent) and load the gravatar image automatically in osticket for your agent account.

**Comment by oneilak** [comment]
ok an lokal upload for the futur?

**Comment by mfelber** [comment]
This feature isn't complete. Other sources are planned. It looks like ldap and ad are already possible: https://github.com/osTicket/osTicket-1.8/pull/2334

**Comment by greezybacon** [comment]
osTicket has all the equipment necessary to do this, I just punted on implementing it in the user interface. Perhaps someone could suggest some UI mockups on the process of

* Uploading images
* Cropping them
* Selecting an avatar out of those previously uploaded and cropped

**Comment by Chefkeks** [comment]
@greezybacon 
Working on some mockups. Don't know exactly how you're thinking the window should look like, but just have a look at my mockups ;) Will upload them later when I'm finished :)

**Comment by Chefkeks** [comment]
@greezybacon
[4 hours later....] 
Finished my mockups :)

The wizard starts here:
![avatar wizard](https://cloud.githubusercontent.com/assets/2871833/9405752/d0840838-47fa-11e5-9043-749fc4d36db1.png)

You can then either select to generate a new random avatar or upload, crop&edit your own avatar. Going the route first with the random avatar:
![avatar random 1](https://cloud.githubusercontent.com/assets/2871833/9405779/0c49411c-47fb-11e5-9b1a-6de0ba961302.png)

Generate a second avatar:
![avatar random 2](https://cloud.githubusercontent.com/assets/2871833/9405788/20077b1a-47fb-11e5-84e9-004c967c7eae.png)

Maybe select the previous avatar - it looked better:
![avatar random 2 linux](https://cloud.githubusercontent.com/assets/2871833/9405794/2b865dd0-47fb-11e5-8d17-9bc45e8b7c3a.png)

Or maybe try to go with a third one:
![avatar random 3](https://cloud.githubusercontent.com/assets/2871833/9405810/387693ca-47fb-11e5-8995-c0ac29aa4405.png)

Can't decide, going to generate another avatar:
![avatar random 4](https://cloud.githubusercontent.com/assets/2871833/9405823/4c919490-47fb-11e5-826c-92825be31006.png)

And so on with random avatars. Now we go back to the upload tab:
![avatar wizard](https://cloud.githubusercontent.com/assets/2871833/9405752/d0840838-47fa-11e5-9043-749fc4d36db1.png)

We uploaded some images and can now select an avatar to start editing:
![avatar wizard after upload](https://cloud.githubusercontent.com/assets/2871833/9405840/7e745614-47fb-11e5-9f4d-e49a242c1190.png)

We maybe crop the image.
![avatar upload crop](https://cloud.githubusercontent.com/assets/2871833/9405850/987a203e-47fb-11e5-83b5-811b6bea52af.png)
(The link from the mockup: http://deepliquid.com/projects/Jcrop/demos.php?demo=thumbnail )

And we apply some effect on the image - turn it into red:
![avatar upload crop and effect](https://cloud.githubusercontent.com/assets/2871833/9405891/07cd8520-47fc-11e5-9b72-0c04bb06a9dd.png)

Maybe we remove the cropping and just take all red effect:
![avatar upload effect red](https://cloud.githubusercontent.com/assets/2871833/9405906/233216dc-47fc-11e5-8647-1391199b9b52.png)

OK that's all. Hope you like it or gives you some inspiration.
Let me know when I shall mail you / the team the balsamiq file, so you don't need to start from a scratch when you like my mockups. I also linked the mockups so you can click thru in balsamiq ;)

**Comment by mfelber** [comment]
@Chefkeks I really like this mockups! The used elements and the arrangement of them (popup-window, button positions, naming, etc.) are fitting well to the existing gui design. The usage seems to me really self-explaining like is intended by osticket. I'm only a little bit concerned how much effort will be needed to implement this..

**Comment by ntozier** [comment]
@Chefkeks amazing! +1

**Comment by protich** [comment]
@Chefkeks :+1: I now know who to reach out to when I need mockups. 

__PS__: Can you please start a new issue with email mockups you did awhile back?

**Comment by greezybacon** [comment]
I really like the idea of keeping the cropped avatar separate from the upload files. I think that's what I was missing

**Comment by Abraka** [comment]
Hm request from 2015 and still nothing...cmon

**Comment by JediKev** [comment]
@Abraka 

You do know that the code is completely open source right?

Cheers.

**Comment by Abraka** [comment]
yea, thats great of course!..but, but...does this mean that you need more than 3 years for implementing such a semi basic feature?
