### ISSUE TITLE
1.10-RC2 Enhacement request: Attach task(s) to ticket

### ISSUE THREAD

**Issue by Chefkeks** [osTicket/osTicket#2438]
Hi!

Maybe we missed it or couldn't find it, but it would be very nice if task(s) could be attached to a ticket. 

Currently it seems that "standalone" created tasks cannot be attached to a ticket. Would be great if this was possible ;)

Cheers!
Michael

**Comment by ColeMan1990** [comment]
+1

**Comment by yod527** [comment]
Yep, would be awesome somehow create a task from a ticket.

**Comment by jhollingsworth** [comment]
To link the two together also, as a ticket may require several tasks to be completed in order before the overall ticket can be closed.

+1

**Comment by balojs** [comment]
@rayfoss  the same petition
 "Enhacement request: Attach task(s) to ticket"

**Comment by Faye1234Baker** [comment]
Yes, I would like to see this feature too.  Quite often tasks are created to fix a bug that could also fix problems on other tickets.  It would be ideal to be able to link the same task to each ticket that would be affected by that task.  For example a task to fix a Add Member button could solve several tickets raised against customers complaining they can't add members.
At the moment all I can do is create an identical duplicate task that is attached to the ticket using the Add Task button.  Perhaps this could be updated to provide a list of existing tasks that can be assigned to a ticket.

**Comment by ntozier** [comment]
"Perhaps this could be updated to provide a list of existing tasks that can be assigned to a ticket."
^ I feel that would be a separate feature request.

**Comment by Faye1234Baker** [comment]
I feel that would be a separate feature request.
 ^ It's more of an implementation detail of the original request.

**Comment by akash65** [comment]
can anyone tell me what are the positive and negatives of **creating task in side ticket** and **creating a task alone**?
