### ISSUE TITLE
1.10-RC2: Feedback about Tasks & Tickets relationship / visibility

### ISSUE THREAD

**Issue by Chefkeks** [osTicket/osTicket#2439]
Hi again :D 

just got some feedback from my colleagues (they never used any 1.10 version before today) mostly regarding tasks and tickets and the relationship between them, the visibility of tasks on a ticket thread.

Overall they really like tasks, but one of my colleagues took some time (10 minutes I guess) until he recognized the tasks inside the ticket thread and he claimed that the visibility is not good (since you get automatically scrolled down - which he really liked :D), but you may can get used to it. He thought mentioning tasks in the ticket thread would help here (as already suggest in https://github.com/osTicket/osTicket-1.8/issues/2316) as well as including a link to the task(s) on the bottom where the little hint is displayed:
![image](https://cloud.githubusercontent.com/assets/2871833/9378955/ea46b99e-4725-11e5-907c-d0ef95ccc97a.png)

Next he claimed was that he created a task (standalone) and couldn't then attach that task to a ticket (see issue https://github.com/osTicket/osTicket-1.8/issues/2438)

After playing around with tasks creation, assignment, transferring, etc. a bit, he suggested that he would like to have the department and assignee pre-selected with his primary department and him as the assigned agent since he selects these values in 90% of all tasks / tickets (or at least pre-select the department / agent from the ticket when creating a "ticket task")
![image](https://cloud.githubusercontent.com/assets/2871833/9379155/914b43a8-4727-11e5-835d-58373b9724c9.png)

Sure sometimes he'll create (standalone/ticket) tasks for other departments and may assign another agent too, but mostly he'll assign to him self / the agent&dept already working on a ticket. Btw. I second his opinion (since I assign over 90% of tickets / tasks to myself or the agent/dept working on a ticket too) and think it would be nice have some logic to do so or individual default values for tasks and also ticket creation (like department, assignee) which can be configured in the Agent Profile.

Lastly another colleague created a ton of tasks and then claimed that he's missing some kind of "relationship" information. So without opening/viewing every single task / ticket he wasn't able to find out which task is "standalone" and which tasks is attached to a ticket. He suggested to show some information which task is attached to which ticket in the tables on the ticket/task queues or combine the queue to have one mixed queue. I do not agree with the last suggestion from him to combine the task and the ticket queue, but I think too that there is definitely some relationship information missing to differ "ticket tasks" vs. "standalone tasks".

So much feedback from my colleagues who overall really like the direction of 1.10 with the new/improved features like tasks, the new advanced search and so on.

Cheers,
Michael

**Comment by OBenned** [comment]
+1 on that we really like the new taks feature, but the visibility on how the relationship between task and tickets is not that good

**Comment by ColeMan1990** [comment]
+1 I ran into the same problems.

**Comment by ipAnything** [comment]
When I tried this feature the Description i typed is not visible in the task. No thread was created. I am using 1.10 RC3

**Comment by drtomasso** [comment]
+1 on visible relation between task and ticket

**Comment by markus4000** [comment]
It would be nice to have the link to the task in the top overlay menu. so it is always available, where ever you are in the ticket.

**Comment by ntozier** [comment]
I agree.  Which is why I opened a feature request to do so.
https://github.com/osTicket/osTicket/issues/3445

**Comment by markus4000** [comment]
so it is the right way ;-)

**Comment by balojs** [comment]
@rayfoss  please check this request #2439

**Comment by akash65** [comment]
can anyone tell me relationship between ticket and task?

**Comment by ntozier** [comment]
@akash65 There really is no relationship. (Okay thats not entirely true)

Ideally Tasks were envisioned as taking a ticket and breaking it down into pieces.  Some pieces may be the responsibility of the network department, some the responsibility of the Operations, and others Maintenance, and some the Finance Department.  Identifying these pieces and making tasks for them and assigning them to the parties needed to resolve them gives the person assigned the ticket a step by step list of who needs to do what.

However Tasks can be created with out being associated with a ticket.  So there doesn't have be any relationship between the two.

**Comment by akash65** [comment]
can anyone tell me how due date is assigned once we create user through web portal?but here we didnot enter due date in any fields right then how it comes?

**Comment by akash65** [comment]
can anyone say ticket has different due date and sub-ticket has another date greater than due date?

**Comment by ntozier** [comment]
@akash65 this appears to be off topic for this issue report.  I would invite you to try the support forums for general questions at http://osticket.com/forums

**Comment by akash65** [comment]
Can anyone tell what is the major difference between under "ticket" tasks are created and "task" individually created and assigned to particular department?

please help me

**Comment by ntozier** [comment]
A ticket is a ticket...  A task is a task.
Tickets can be comprised of many tasks.
Tasks are only one task.

That's sort of like asking Whats the difference between betweena "To do list" and an item on the "to do list"

**Comment by akash65** [comment]
thanks man @ntozier

**Comment by ntozier** [comment]
@akash65 very welcome.  I hope I explained it in an easy to understand way. :)

**Comment by akash65** [comment]
i have a question on ticket and task?
if "**task is created under ticket**" then how will the "ticket owner know if the task has got completed".can anyone explain me please
