### ISSUE TITLE
develop-next - ticket sort error

### ISSUE THREAD

**Issue by gmt-it** [osTicket/osTicket#2442]
After updating with latest develop next ticket sort works not as it shoud. If I choose most recently closed the system shows the wrong order. I think there should be an option for ascending / descending

Take a look:

Page one:
![sort_001](https://cloud.githubusercontent.com/assets/10116166/9385989/b842c436-4759-11e5-9c3e-8080b9e256f0.png)

**Comment by greezybacon** [comment]
I think they're sorted according to "Most Recently Closed" (i.e. oldest first). Perhaps the wording is bad. Click on "Most Recently Closed" again to reverse the sort order.

**Comment by gmt-it** [comment]
@greezybacon 
Sorry, but most recently closed shows wrong order, doesn't matter if I choose newest first:
![unbenannt](https://cloud.githubusercontent.com/assets/10116166/9386574/64dda04c-475c-11e5-89f7-5622d8901562.PNG)

**Comment by greezybacon** [comment]
I'm confused. Now you're posting the picture with the items in reverse order? What's the real issue?

**Comment by gmt-it** [comment]
@greezybacon The issue is that the latest cloesed tickets are from 01.08 up to 20.08.2015. That are more than 200.

**Comment by greezybacon** [comment]
The sort option include the priority too. Is that the confusion?

**Comment by gmt-it** [comment]
No, I have no chance to see most recently closed tickets. It is not the Problem with priority. Until latest update you choose most recently closed and you see all tickets that are closed i.e. today. Now you get a table with tickets closed month ago without a logical sort order. It was functional until latest update.

**Comment by greezybacon** [comment]
I encountered the same issue. Sorry for the confusion. I think this is fixed in the commits in #2056 as of e17a9124e7c59d6de7ae21a8e736740b837badec

**Comment by gmt-it** [comment]
Error is back again in latest develop-next!

**Comment by greezybacon** [comment]
It doesn't look like e17a912 is merged into `develop-next` yet. You might have to manually apply it after upgrading
