### ISSUE TITLE
1.10rc2 : task generating: Assignee field bug

### ISSUE THREAD

**Issue by markus4000** [osTicket/osTicket#2445]
if I create a task, it does not save the assignee at the first time.
After creating, assing is possible, but not with the create form.

**Comment by Chefkeks** [comment]
I can confirm this issue.

**Comment by greezybacon** [comment]
Can you guys confirm the fix in #2452

**Comment by Chefkeks** [comment]
@greezybacon 
Patch #2452 works :+1:

**Comment by markus4000** [comment]
fixed in 1.10dev
