### ISSUE TITLE
1.10-rc2: New Filter / Status line freezes / Add Rule doesn't work

### ISSUE THREAD

**Issue by ti2media** [osTicket/osTicket#2447]
1. When I go to the admin area - click Ticket Filter -> add Filter -> the status line freezes
2. When I then refresh the page, all fields are available -> I fill out everything
3. When I click "add Rule" -> nothing happens
4. When I click "add Filter" -> I receive an error - I have to add a rule ( see 3. )
   ![freeze](https://cloud.githubusercontent.com/assets/13893235/9394952/8b0e8fb8-478b-11e5-8498-8b04dd443c1f.jpg)

**Comment by greezybacon** [comment]
This is fixed in #2056 with 98fa8df6315349b4013f08fe8808a0f2f1af7223
