### ISSUE TITLE
1.10 Feature idea: Diff for history of ticket thread entries

### ISSUE THREAD

**Issue by Chefkeks** [osTicket/osTicket#2448]
It's already late here and while reading thru some of the issues here the following idea came in my mind and I like to share it here, before I forget it ;)

It's regarding the history feature when you edit a ticket thread entry. It would be really useful to have a diff view (like here on github). Then you could easily see the changes made between the edited and original entry. Especially when an agent just corrects some typos and you have a long text which you'd need to compare then.

Cheers and good night :P
Michael

**Comment by ntozier** [comment]
+1
