### ISSUE TITLE
1.10rc2: Delete Custom Logo

### ISSUE THREAD

**Issue by bradfish** [osTicket/osTicket#2449]
This was a bug I found in 1.10rc1; however, I did not report it. I see it has not been corrected for 1.10rc2 so I wanted to get the devs the heads up on probably an easy bug to fix. Currently, if an administrator uploads a logo they are unable to delete it using the checkbox of the delete form. A user can check the box and click Save Changes; however, the logo is not removed and remains visible on the page. I have tried going to another page and returning and it is still there as well as clearing cache. Unfortunately, no physical error is displayed on the page or in the logs.

**Comment by ntozier** [comment]
already reported here: https://github.com/osTicket/osTicket-1.8/issues/2433

**Comment by greezybacon** [comment]
This is fixed in `develop-next` as of b528df56c3750561ddb72a18a44a8b84fcb1bcd1
