### ISSUE TITLE
1.10rc2: Import Users

### ISSUE THREAD

**Issue by bradfish** [osTicket/osTicket#2450]
Within the import section (Both Copy & Paste AND Upload), mass users are not able to be imported. The error for both sections will always be: "Unable to map header to a user field". 

I have tried this with just importing one user and multiple users and received the same error.

**Comment by mfelber** [comment]
I can't reproduce what you describe (both works in my case). Maybe you should post an example that does not work. I only get this error when (also in earlier versions than 1.10) when the used import data is not correct prepared (separator is missing or so).

**Comment by bradfish** [comment]
![capture](https://cloud.githubusercontent.com/assets/13727540/9431492/21fbed34-4a30-11e5-9648-546dbafbe107.PNG)

No problem, please see attached.

**Comment by mfelber** [comment]
Aha, now I can reproduce this issue. In osticket 1.9.x this data would be accepted in 1.10 it doesn't work.  Only using two items seems to making problems.

I had used this data for testing with a single user:

email1@no-reply.de, Tom Reagan, 0123456789, Testnote1

And this for multiple users:

email1@no-reply.de, Tom Reagan, 0123456789, Testnote1
email2@no-reply1.de , Johnny Caspar, 0123456790, Testnote2

Both work.

But I also see another problem.

If I would use this lines:

email1@no-reply.de, Tom Reagan, 0123456789, Testnote1
email2@no-reply.de , Johnny Caspar, 0123456790, Testnote2

It doesn't work. Same email domain (no-reply.de) seems to make problems. 

The import hangs in this case, the loading message is shown permanently:

![import loading](https://cloud.githubusercontent.com/assets/5539456/9434546/63b34884-4a40-11e5-97a0-e129e32de710.jpg)

In 1.9.x this worked.

By the way: In the upload tab there is shown the order of the expected data (email, name, phone, note). When you use the name as the first item it will be imported as the email address.
