### ISSUE TITLE
1.10rc2 - Upgrade error (Core)

### ISSUE THREAD

**Issue by simonbradbury** [osTicket/osTicket#2451]
Hi

I get this error when I try to update from 1.9.12

[CREATE TABLE `ost_translation` ( `id` int(11) unsigned NOT NULL AUTO_INCREMENT, `object_hash` char(16) CHARACTER SET ascii DEFAULT NULL, `type` enum('phrase', 'article', 'override') DEFAULT NULL, `flags` int(10) unsigned NOT NULL DEFAULT '0', `revision` int(11) unsigned DEFAULT NULL, `agent_id` int(10) unsigned NOT NULL DEFAULT '0', `lang` varchar(16) NOT NULL DEFAULT '', `text` mediumtext NOT NULL, `source_text` text, `updated` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (`id`), KEY `type` (`type`, `lang`), KEY `object_hash` (`object_hash`) ) DEFAULT CHARSET=utf8] Table 'ost_translation' already exists

**Comment by mfelber** [comment]
This seems to me a duplicate (open) issue: https://github.com/osTicket/osTicket-1.8/issues/2078

**Comment by greezybacon** [comment]
That's weird. It's only created once in the upgrade files... Did it exist in your v1.9.12 database?

**Comment by hofzor** [comment]
Having the same "ost_translation already exists" issue.  We tried to upgrade last night and ran in to issues (no one was able to log in via LDAP or local) and had to revert back to 1.9.51.

Here's the process I did:
Did a mysql dump
Created a back up of the production osticket folder
Downloaded, extracted, and overwrote the production osticket folder's contents
Performed the upgrade via the web interface

Upgrade was a success, but at this point nobody was able to log in.  My cached login allowed me to be in, but if I signed out, I was unable to get back in.  I tried resetting the local osticket admin account's password, but got a loop where it just kept prompting me to enter the username.  After trying to look up fixes, I decided to try the upgrade process again.

I went to my backup folder and overwrote everything in the production folder
Did a MySQL -u -p database < databasebackup.sql
The 19.51 version was working fine, so tried to go through with the update again.  At this point I am now receiving  the "ost_translation already exists" error.

**Comment by ntozier** [comment]
@hofzor 
re: "(no one was able to log in via LDAP or local"
Did you also upgrade your LDAP plugin?

**Comment by hofzor** [comment]
@ntozier 

I did not update the LDAP plugin.  I'm going to drop the ost_translation table, and try again tonight.  I will follow up with results.

**Comment by ntozier** [comment]
Please let us know your results. :)

**Comment by hofzor** [comment]
Sorry, was finally able to get to it tonight. 

I dropped the ost_translation table, but am now getting an error that the table doesn't exist.  I'm not really sure where to go from here.  I performed all the same steps as I had above, with the exception that I dropped the table right before doing all of that.

DB Error #1146
[SELECT A1.* FROM `ost_translation` A1 WHERE (A1.`lang` = ? AND A1.`type` = ?)] Table 'osticket.ost_translation' doesn't exist

 ---- Backtrace ----
 #0 (root)/include/mysqli.php(318): osTicket->logDBError('DB Error #1146', '[SELECT A1.* FR...')
 #1 (root)/include/class.orm.php(2741): db_prepare('SELECT A1.* FRO...')
 #2 (root)/include/class.orm.php(2735): MySqlExecutor->execute()
 #3 (root)/include/class.orm.php(2811): MySqlExecutor->_prepare()
 #4 (root)/include/class.orm.php(1540): MySqlExecutor->getArray()
 #5 (root)/include/class.orm.php(1363): ModelInstanceManager->fillTo(0)
 #6 (root)/include/class.translation.php(899): ResultSet->valid()
 #7 (root)/include/class.translation.php(920): CustomDataTranslation::getTranslation('en_US')
 #8 (root)/include/class.list.php(392): CustomDataTranslation::translate('37eec2fe8f75003...')
 #9 (root)/include/class.list.php(205): DynamicList->getLocal('name_plural')
 #10 (root)/include/class.list.php(520): DynamicList->getPluralName()
 #11 [internal function]: DynamicList::getSelections()
 #12 (root)/include/class.forms.php(563): call_user_func(Array)
 #13 (root)/include/class.forms.php(571): FormField::allTypes()
 #14 (root)/include/class.forms.php(1002): FormField::getFieldType('text')
 #15 [internal function]: FormField->getImpl(Object(DynamicFormField))
 #16 (root)/include/class.dynamic_forms.php(638): call_user_func_array(Array, Array)
 #17 (root)/include/class.dynamic_forms.php(1385): DynamicFormField->__call('getImpl', Array)
 #18 (root)/include/class.dynamic_forms.php(1385): DynamicFormField->getImpl(Object(DynamicFormField))
 #19 (root)/include/class.dynamic_forms.php(990): DynamicFormEntryAnswer->getField()
 #20 (root)/include/class.company.php(71): DynamicFormEntry->getAnswer('name')
 #21 (root)/include/staff/footer.inc.php(5): Company->__toString()
 #22 (root)/scp/upgrade.php(88): require('/var/www/html/h...')
 #23 (root)/scp/staff.inc.php(116): require('/var/www/html/h...')
 #24 (root)/scp/admin.inc.php(16): require('/var/www/html/h...')
 #25 (root)/scp/upgrade.php(16): require_once('/var/www/html/h...')
 #26 (root)/scp/staff.inc.php(116): require('/var/www/html/h...')
 #27 (root)/scp/autocron.php(18): require('/var/www/html/h...')
 #28 {main}

**Comment by ntozier** [comment]
after you deleted the table, you are going to have to recreate it.

**Comment by sbattar** [comment]
Here is what I did to successfully upgrade from osTicket1.9.12 to osTicket1.10RC2
Backed up the 1.9.12 db and folders.
Installed osTicket1.10.rc2 with the db name same as my production with empty data.
went into the mysql command line
Ran..
DROP TABLE `ost_translation`;
ALTER TABLE `ost_attachment` DROP `lang` ;
ALTER TABLE `ost_staff` DROP `lang` ;
ALTER TABLE `ost_staff` DROP `extra` ;
ALTER TABLE `ost_staff` DROP `locale` ;
ALTER TABLE `ost_staff` DROP `timezone` ;

And then populated data using database restore from my backed up database
mysql -uroot -p PROD_DB_NAME < BACKEDUPFILE.sql

Logged into the portal checked upgrade option to run it successfully.
Hope this helps.

Cheers

**Comment by Hannibal226** [comment]
I already opened a new issue some time ago, but just want to leave the info, that ur way above didn't help me out.
Maybe @greezybacon has an idea what to do upgrade without loosing data?

#3221

**Comment by SeppPenner** [comment]
I'm having exactly the same problem as @simonbradbury. After deleting and adding the table again using the code:
```
CREATE TABLE ost_translation (
id int(11) unsigned NOT NULL AUTO_INCREMENT,
object_hash char(16) CHARACTER SET ascii DEFAULT NULL,
type enum('phrase', 'article', 'override') DEFAULT NULL,
flags int(10) unsigned NOT NULL DEFAULT '0',
revision int(11) unsigned DEFAULT NULL,
agent_id int(10) unsigned NOT NULL DEFAULT '0',
lang varchar(16) NOT NULL DEFAULT '',
text mediumtext NOT NULL, source_text text,
updated timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (id),
KEY type (type, lang),
KEY object_hash (object_hash) ) DEFAULT CHARSET=utf8
```
and deleting the old log messages, the error is gone but osTicket is still throwing an upgarde error:
![grafik](https://user-images.githubusercontent.com/9639361/28180015-0b6e5a86-6804-11e7-8a40-8391b6cd4392.png)
