### ISSUE TITLE
Can't create filter 1.10-RC.2

### ISSUE THREAD

**Issue by TravelingTartar** [osTicket/osTicket#2462]
When trying to create an email filter, two things happen:
First attempt, the screen is grayed out.
Refresh.
Screen is editable but the Add Rule button does not trigger an action - no ability to enter new rule.
{fresh install}

**Comment by rowlandan25** [comment]
This is fixed in #2056 with 98fa8df

**Comment by TravelingTartar** [comment]
Thanks. Applied but didn't work, but thanks so much to all for your help and hard work! Great release.

**Comment by TravelingTartar** [comment]
Downloaded and updated to v1.10-rc.2 (231f11e). Still nothing. Just FYI.

**Comment by greezybacon** [comment]
> Thanks. Applied but didn't work, but thanks so much to all for your help and hard work! Great release.

I disagree. The patch fixes the issue.

**Comment by TravelingTartar** [comment]
Respectfully, then there might be another problem. In my case, it's not working. But no worries, I'll wait for the next RC or final and see what happens. Thanks though.

**Comment by TravelingTartar** [comment]
This fixed it: https://github.com/osTicket/osTicket-1.8/issues/2472
