### ISSUE TITLE
v1.9.12 - Email fetching not reading correctly

### ISSUE THREAD

**Issue by robintoy** [osTicket/osTicket#2465]
In version 1.9.12 we now get a lot of emails not being read correctly and the ticket message / reply we get instead is: -

```
xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns:m="http://schemas.microsoft.com/office/2004/12/omml" xmlns="http://www.w3.org/TR/REC-html40">
```

This mainly seems to be from Microsoft Office 365 and some Exchange mailbox based emails.

**Comment by robintoy** [comment]
This is the same issue as #2272 to which the fix suggested here solves the problem.

We have been running the fix on our system for ages with no issues or side effects

**Comment by robintoy** [comment]
Here is the exact code we are using in V1.10-rc2

`<?php //add to make it look right
function safe_html($html, $spec=false, $balance=1) {
        // Remove HEAD and STYLE sections
        $html = preg_replace(
            array(':<(head|style|script).+?</\1>:is', # <head> and <style> sections
                  ':<!\[[^]<]+\]>:',            # <![if !mso]> and friends
                  ':<!DOCTYPE[^>]+>:',          # <!DOCTYPE ... >
                  ':<\?[^>]+>:',                # <?xml version="1.0" ... >
				  ':<html[^>]*:i',				# Clean html tag (Issue 2272 fix)
            ),
            array('', '', '', '', '<html'),
            $html);								# added '<html' (Issue 2272 fix)
?>`

**Comment by greezybacon** [comment]
Could anyone try the patch in #3215?
