### ISSUE TITLE
v1.10-rc2 - Help!!! "ticket is missing data"

### ISSUE THREAD

**Issue by bradfish** [osTicket/osTicket#2466]
Starting with yesterday (upgraded to rc2 on friday) I've begun to notice more and more of the tickets being posted will not let me close them. This includes existing tickets as well as new tickets that have been posted. At the bottom of the page I am receiving "This ticket is missing data on one or more required fields and cannot be closed". Can someone please come up with a work around fix to let me close these tickets?

![capture](https://cloud.githubusercontent.com/assets/13727540/9456906/1cb91de4-4afb-11e5-99b4-174b756721a8.PNG)

**Comment by bradfish** [comment]
To follow up on this thread, I ended up commenting out the error and forcing the error check to be false in class.ticket.php

		/*
        if ($this->getMissingRequiredFields()) {
            $warning = sprintf(
                    __( '%1$s is missing data on %2$s one or more required fields %3$s and cannot be closed'),
                    __('This ticket'),
                    '', '');
        } elseif (($num=$this->getNumOpenTasks())) {
            $warning = sprintf(__('%1$s has %2$d open tasks and cannot be closed'),
                    __('This ticket'), $num);
        }
		*/

This has allowed me to close tickets. The only thing I can think of that caused this is originally yesterday I was playing with the standard form for ticket status (open, close, resolved, etc.) and i remember trying to disable/delete the closed ticket form since my techs were confused between Closed and Resolved. I know the ticket would not let me disable or delete it and shortly after problems began. Outside of that I am at a lost on what is causing this?

**Comment by ntozier** [comment]
Admin panel -> manage -> forms... 
check your all your fields, and make sure that you didn't enforce data integrity on them... which is what causes this error since you need to edit the ticket to add the data before the ticket can be closed.

**Comment by balojs** [comment]
It is possible to display the required fields inline? @greezybacon

**Comment by balojs** [comment]
@rayfoss It is possible to display the required fields inline?
