### ISSUE TITLE
Canned responses don't appear to work in 1.9.12

### ISSUE THREAD

**Issue by sstillwell** [osTicket/osTicket#2467]
Updated my install to 19292ad (v1.9.12) - now it appears that when I select a canned response when editing a ticket, nothing happens...the canned text does NOT get put into the response edit box.

php 5.4.41-1
nginx 1.8.0

The update was done via the method listed in README.md:

cd <src directory>
git pull
php setup/cli/manage.php deploy -v <target directory>

Not sure what's up...this has been working well for quite a while through several updates.  As errors go, it's more of an annoyance than anything else, but obviously would like it to work and will help as I can.

**Comment by infectormp** [comment]
for me canned responses do not work with nginx in any version of osticket

**Comment by infectormp** [comment]
i get error - open() "/xxx/scp/ajax.php/tickets/7871/canned-resp/6.json" failed (20: Not a directory)

**Comment by Chefkeks** [comment]
Just as a side note: Nginx is NOT supported officially.

**Comment by infectormp** [comment]
>  Nginx is NOT supported officially.

and this is VERY bad.

i run nginx for all my sites except osticket

**Comment by sstillwell** [comment]
> i get error - open() "/xxx/scp/ajax.php/tickets/7871/canned-resp/6.json" failed (20: Not a directory)

I get similar errors in my logs as well (varying ticket number and response number, of course)

**Comment by guidokuehler** [comment]
We works not with 1.9.12 but with 1.9.9 successfull under nginx and also with canned responses.

Below our System-Details

osTicket-Version	v1.9.9-1-gbe2f138 (be2f138)
Server-Software	nginx/1.8.0
MySQL-Version	5.5.44
PHP-Version	5.6.4-4ubuntu6.2

**Comment by infectormp** [comment]
@guidokuehler i try your config form https://github.com/osTicket/osTicket-1.8/issues/844#issuecomment-131213369 and have no luck.

**Comment by guidokuehler** [comment]
We have no idea what is the problem on your System.
Ours and your sytem ist very different (PHP and osTicket-Version)!
We have also needed change fastcgi-php.conf and others.

**Comment by greezybacon** [comment]
I would be happy to support nginx. Can anyone suggest how osTicket can be distributed so that nginx will work without external modifications? Similar to `.htaccess` files for Apache

**Comment by infectormp** [comment]
nginx support rewrite rules as apache http://nginx.org/ru/docs/http/ngx_http_rewrite_module.html

**Comment by ree4** [comment]
> I would be happy to support nginx. Can anyone suggest how osTicket can be distributed so that nginx will work without external modifications? Similar to .htaccess files for Apache
> - greezybacon

Officially supporting nginx would be nice

**Comment by ree4** [comment]
@sstillwell did you get it sorted?

**Comment by crypticmind** [comment]
+1 for  officially supporting nginx. I'm seeing too many issues with nginx. Most are already solved, but an official support would provide better documentation for running under nginx that would cut a lot of forum traffic.
