### ISSUE TITLE
Ticket Filters - Page doesn't load & Filter Rules broken in 1.10RC2

### ISSUE THREAD

**Issue by bhiscox** [osTicket/osTicket#2472]
Hello,

Like the design change so far from 1.10RC1 to RC2 but two problems happen.

First the first time I go into ticket filters the orange 'status' line that flashes along the top after any click sort of stops mid way and the rest of the page stays greyed while the browser shows that it is complete and not waiting for more data.

If I click refresh the whole page will come up but when I try to click the add filter rules button absolutely nothing happens. The behavior is predictable. Since upgrading to 1.10RC2 it has never worked and when I downgrade back to 1.10RC1 it does instantly and everytime.

It is a non production environment (on the OSTicket side) and I can give you access if you would like to check it out. Below is my server information.

Server Information
osTicket Version	v1.10-rc.1 (07c1d79)  Upgrade — v1.10-rc.2 is available
Web Server Software	Apache/2.4.16 (Unix) PHP/5.6.12 mod_perl/2.0.9 Perl/v5.14.2
MySQL Version	5.6.26
PHP Version	5.6.12
PHP Extensions
gdlib	 Used for image manipulation and PDF printing
imap	 Used for email fetching
xml	 XML API
xml-dom	 Used for HTML email processing
json	 Improves performance creating and processing JSON
mbstring	 Highly recommended for non western european language content
phar	 Highly recommended for plugins and language packs
intl	 Highly recommended for non western european language content
fileinfo	 Used to detect file types for uploads
PHP Settings
cgi.fix_pathinfo	 "1" is recommended if AJAX is not working
date.timezone	 Asia/Hong_Kong
Database Information and Usage
Schema	osticket (localhost)
Schema Signature	98ad7d550c26ac44340350912296e673
Space Used	2.61 MiB
Space for Attachments	0.09 MiB
Timezone	HKT

**Comment by bhiscox** [comment]
Just a slight update, I upgraded back to 1.10RC2 and modified a pre-existing rule it loads fine and fast but still if I add new rules the aforementioned happens. 

I took a screenshot this time. 
![osticket-filterfail](https://cloud.githubusercontent.com/assets/13976211/9487323/156bbffc-4c03-11e5-91ea-210e57fc0d68.jpg)

**Comment by jdelhome3578** [comment]
I see the same behavior when trying to add a new filter.

**Comment by jdelhome3578** [comment]
Is this fixed with 98fa8df?

**Comment by philbertphotos** [comment]
Here is the fix ...
Fixed a bug that created a javascript error "SyntaxError: expected expression, got ';'"
On line 345
/include/staff/filter.inc.php
var next = <?php echo $maxi; ?>;
Added qoutes so there is a proper null-string if not the "Add Filter" button fails.
var next = "<?php echo $maxi; ?>";

**Comment by bhiscox** [comment]
@philbertphotos, that has worked flawlessly for me. Good job.

**Comment by TravelingTartar** [comment]
Agreed. Worked for me, thanks.

**Comment by greezybacon** [comment]
Sorry guys. `next` is an int type which is incremented later in the javascript code. It should default to zero (0) if unset in PHP

**Comment by eayonm** [comment]
@philbertphotos thanks!!

**Comment by greezybacon** [comment]
This was fixed in d2af0eb630200dd2144a77e38906063c6ec57c20
