### ISSUE TITLE
v1.9.5.1 - possible duplicate email address 

### ISSUE THREAD

**Issue by simonebracaloni** [osTicket/osTicket#2473]
I found this issue on v1.9.5.1

It is possible to enter the same email address in different format. E.g.

```
name.surname@domain.com
<name.surname@domain.com>
```

Both are accepted and stored to the database in this way, because email address uniqueness is done at DB level and the two strings are different, this makes possible to have two user with the same email address.

The format with bracket is also not shown on the user detail page.

**Comment by greezybacon** [comment]
Interesting find. Thanks

**Comment by mckaygerhard** [comment]
ping? what about this bug! i currently confirm that in my setup! please remenber its a bug not a new feature request! i used 1.9.11 in production!

**Comment by robintoy** [comment]
Just a thought, if this is still an issue can we just remove the < and > characters from the email address field before it is processed meaning the DB will error as required?

**Comment by mckaygerhard** [comment]
obviously its easy to resolve, but still not resolved!

**Comment by greezybacon** [comment]
If fixing things is so easy, why are there so few people doing it?

**Comment by greezybacon** [comment]
@simonebracaloni @mckaygerhard could you try the patch in #3239 to see if it addresses this issue?
