### ISSUE TITLE
[CSS] Redoing the CSS

### ISSUE THREAD

**Issue by charlestruluck** [osTicket/osTicket#2486]
I wanted to ask before I performed.

Would it be helpful or not if I loaded the page with Bootstrap (getbootstrap.com) in replacement of the current looks by default. I feel like the current default design for the page is clumpy and not very modern/flat looking.
Just a question. I'd be happy to do it.

**Comment by NMonst4** [comment]
Have you made some css changes? I made some changes for scp but no bootstarp changes only clear and modern look.

**Comment by greezybacon** [comment]
You guys go ahead and slash away. We're holding off to transform the backend to make it themeable and to completely redesign the staff, client, and admin portals.

**Comment by philbertphotos** [comment]
I cant wait till this happens but I would have too ...smh I would like to contribute to this if at all possible.

**Comment by charlestruluck** [comment]
I definitely feel one of the factors repelling people from osTicket is design/UI. Customizability is tough, and people don't like design that doesn't flow with everything else they use.

**Comment by philbertphotos** [comment]
I agree..
