### ISSUE TITLE
1.10-RC2, custom list. Select all and deselect all missing

### ISSUE THREAD

**Issue by gshtapani** [osTicket/osTicket#2487]
Hi,

I have upgraded my company's OsTicket system from 1.9.12 to 1.10-RC2.
We have couple custom lists with multi selection allowed.
Now Select all and deselect all are missing from drop downs.

Regards,
Tapani

**Comment by ntozier** [comment]
I'm not aware of multiselection (or select all / deselect) being an option in osTicket?  
I would recommend that you restore from back up.
1.10rc2 is not ready to be used in a production environment.
