### ISSUE TITLE
10-RC2 SLA enhancement

### ISSUE THREAD

**Issue by philbertphotos** [osTicket/osTicket#2494]
Ability to create a SLA with information that a user read detailing the SLA rules and conditions

**Comment by ntozier** [comment]
So you are asking for an enhancement to the SLA system so that you can define custom pages, which the end user must accept in order to use the site?  That sounds more like an EULA.

**Comment by philbertphotos** [comment]
No the end user does not need to accept its so they can read the contents of the SLA.

Example why does this ticket take 72 hours to complete.
"Services will be provided between the hours of 8:00 a.m. and 5:00 p.m., Monday through Friday, except holidays. During this time the Help Desk will be staffed with a minimum of X people."
