### ISSUE TITLE
Enhancement: Agent new ticket

### ISSUE THREAD

**Issue by markus4000** [osTicket/osTicket#2497]
when a agents enters a Interna ticket, it would be good if the fields, Department, sla, duedate, assigne would be autofilled depending tue helptopic.

**Comment by infectormp** [comment]
are you try set all this in Admin panel-Manage-Help topics?

**Comment by markus4000** [comment]
I want to help the other agents to choose the right setting... they do not know always the default assignee and SLA for the help topic.

**Comment by ntozier** [comment]
Go to Admin panel -> Manage -> Help Topics.
Edit the help topic.
Change the fields you want to change: "Department, sla, duedate, assigne"

**Comment by markus4000** [comment]
It works but not for the SLA and it is not really userfriendly for those agents that dont know that they have to choose "default".
I m looking for a userfriendly way to make internal tickets from agent to agent.

**Comment by ntozier** [comment]
There is no such thing as an "internal tickets from agent to agent."
Tickets are Owned by Users.  They are opened by or for Users.

**Comment by markus4000** [comment]
Then I mean agent acting as a user in an internal ticket.

**Comment by markus4000** [comment]
It would be nice to have a "frontend look" for the backendusers, if they open a internal ticket. Because i dont want every agent to be able to overrule the presets of a heltopic.

**Comment by greezybacon** [comment]
Shouldn't those agents just interface with the client interface? We have collaboration, and very recently in v1.10, organization ticket sharing, so it might be possible for a group of agents not to have access to the "agent" panel at all.

**Comment by markus4000** [comment]
I have 6 departments. We use the tickets for request from the sales people to the operations or develpment or productmanagement.
But there are some internal topics as well. And i dont want the sales people to be able to open one of those internal tickets. Eg.: only the agents are able to open a ticket with the helptopic for the ectronic engeneers a ticket. Bit not all thr agents know how the settings have to be (SLA, Assignee, department.... etc.etc)
