### ISSUE TITLE
v1.10-rc2 Claiming Ticket requires ticket Assignment

### ISSUE THREAD

**Issue by rowlandan25** [osTicket/osTicket#2503]
When I click on Claim Ticket, it brings up the Assign panel, the same panel you get when you click Assign->Agent.
![capture](https://cloud.githubusercontent.com/assets/1084662/9577817/67c98f90-4faa-11e5-854b-1d92cbb3b38b.PNG)

It does not just auto-assign it to the agent that is logged in.

Expected Result:
Assign directly to the current user

**Comment by C4RLOCO** [comment]
I agree..

**Comment by slimatic** [comment]
Looks to me that the functionality, when clicked should come up with the pop-up with the Assignee set to the user by default. 

It should differ slightly from Assign to agent option however it looks like they are functioning the same.

Let the dropdown fill the user by default.

**Comment by goobersmooch** [comment]
I agree that if the current agent clicks on the claim button that it should be assigned to the agent that clicked the claim button.
