### ISSUE TITLE
v1.10-RC.2: Printing Tickets

### ISSUE THREAD

**Issue by C4RLOCO** [osTicket/osTicket#2505]
When printing a ticket, the layout is not properly set. The Ticket number overlaps with the Date and Time

**Comment by rowlandan25** [comment]
I am not seeing this issue when I printed tickets out today (also running v1.10-RC.2).  I am curious to see what you see, could you print one to PDF and post it?

**Comment by C4RLOCO** [comment]
Thanks @rowlandan25 for chiming in.

See screenshot below:

<img width="954" alt="textoverlapping" src="https://cloud.githubusercontent.com/assets/4073792/9611451/b1d53126-50ad-11e5-95b3-c95177455b44.png">

**Comment by pkgdemon** [comment]
I also see this with RC2.

**Comment by C4RLOCO** [comment]
Thanks @pkgdemon for chiming in. @greezybacon any thoughts?

**Comment by shiko2009** [comment]
is there any fix for this problem ?

**Comment by pkgdemon** [comment]
I've noticed commits have seemed to stop from @greezybacon, and work on develop-next has slowed down with no commits in 18 days.  Is 1.10 still coming?

**Comment by greezybacon** [comment]
@pkgdemon sometimes life happens... Yes, v1.10 will still come

**Comment by pkgdemon** [comment]
@greezybacon wish your project the best.  I will be patient, and wait for the next RC.  Thanks.

**Comment by luiizfenix** [comment]
So far no fix?
or is there any other fix than revert to stock logo?

**Comment by JediKev** [comment]
@luiizfenix I'm using v1.10.1 and I do not see this issue with a custom Logo.

**Proof:**
![screen shot 2017-11-29 at 11 41 49](https://user-images.githubusercontent.com/11823401/33390172-c21515be-d4fa-11e7-8b6d-faa5f73524e3.png)
<img width="957" alt="screen shot 2017-11-29 at 11 42 07" src="https://user-images.githubusercontent.com/11823401/33390174-c4e2a90a-d4fa-11e7-9c72-542788e1126e.png">

So my suggestion is to upgrade to the latest version and re-test this issue. Cheers.

**Comment by luiizfenix** [comment]
Hi @JediKev i'm also using v1.10.1 but my issue is persistent: 

proof: 
![image](https://user-images.githubusercontent.com/32772585/33390420-daeda0d4-d503-11e7-98af-27a75a413575.png)

![image](https://user-images.githubusercontent.com/32772585/33390470-f8cf86b2-d503-11e7-8254-d0df0aa88151.png)

**Comment by JediKev** [comment]
What is the size of your logo?

**Comment by luiizfenix** [comment]
301*127 px

**Comment by JediKev** [comment]
Bingo. Your issue is due to incorrect logo sizing. You need to make it as close to `817px x 170px` as possible.

This is mentioned in the Logo Help Tip:
![screen shot 2017-11-29 at 12 07 47](https://user-images.githubusercontent.com/11823401/33391297-236fa128-d4fe-11e7-9150-e05d4ffe8928.png)

**Comment by perryk** [comment]
If the resize doesn't sort this out, you could try applying this PR: https://github.com/osTicket/osTicket/pull/3889

**Comment by luiizfenix** [comment]
The resize did work but now i feel my logo is a little bit more small. 
But its ok after all. 

Thanks
