### ISSUE TITLE
v1.9.12 bug: collaborators not email notification on firts entry of ticket threat

### ISSUE THREAD

**Issue by mckaygerhard** [osTicket/osTicket#2509]
I activated all alerts in alerts (excepted by members team or group), testing working email and setup a topic that notify to all ...
(edited)

then acept users request of ticket via web portal or email ..

so then make a email and send to the configured. with cc emails so then we have: a dest email1@domain, a cc colab1@domain

when ticket are opened by osticket, the cheff and all involucrates configured in alerts get email notification about a new ticket **but the collaborators not** 

**collaborator only gets notification when a second threath/note/event on the opened ticket happened (by example, change status, make a note or let a response) by any of the involucrates**

to collaborators get notification i must activate "all menbers" and that are nonsense, i only want that the involucrates get messages **since firts entry of the ticket threat**.

thanks in advance

**Comment by mckaygerhard** [comment]
i found (using the #771 issue) that this problem was previusly reported as #1130 but at this date still are not implemented

where i must edit to make this ?

**Comment by mckaygerhard** [comment]
still, in any way, if present in 1.10 brand, still 1.10 are not stable and i cannot proposed in organization to use in production...

almost one year still **waiting this NEED FEAURED of added colaborators when agent open tickets for users** atleast whow csn i made for 1.9 brand for love of god and aliens!

**Comment by greezybacon** [comment]
@mckaygerhard we do not send the initial email because the collaborators were already included on the email which was used to create the ticket. Why should they receive a second email with the same information?

**Comment by mckaygerhard** [comment]
becose those dest received an normal email event and ostiket notification

if i can make a ticket from the interface and here in firts step added that colaboratos, the mail that will be send will be for all the related (the author, the client and the collaborator)

**Comment by mckaygerhard** [comment]
as i said @greezybacon due the people involved does received/send as normal emails from fitrs step, those then answered with normal emails, and all the threath happen outside the thiket threath! a real pain for support technician

**Comment by inphower** [comment]
Still no solution??

**Comment by mckaygerhard** [comment]
of course no solution.. until something like happened with owncloud raise to this project... raise a fork and  development will slow...migrating to the new fork

**Comment by ntozier** [comment]
@inphower See:
greezybacon commented on Jun 25, 2016
"mckaygerhard we do not send the initial email because the collaborators were already included on the email which was used to create the ticket. Why should they receive a second email with the same information?"

There is:
A: no way to open a ticket in the UI with collaborators.
B: the only way to open a ticket with collaborators is to email the ticket system and CC the people.  And the DEVs decided not to send all recipients two emails instead of one.

**Comment by mckaygerhard** [comment]
i repeat: the people involved does received/send as normal emails from fitrs step, those then answered with normal emails, and all the threath happen outside the thiket threath! a real pain for support technician

**Comment by ntozier** [comment]
So your argument is:
If I send an email to: tickets@foo.bar.
and CC it to Jon@foo.ba, Mary@foo.ba, and Jane@foo.ba.
That Jon, Mary, and Jane will not get the original email?

**Comment by inphower** [comment]
But when We sent the first response from osTicket this only goes to one email because CC's on first entry are not included,,,

**Comment by mckaygerhard** [comment]
u know @ntozier u only take care when more than one user are making noise..

@inphower that u said its not happened, all in the mail, CC and author, will be included in the ticket as collaboratos... 

the problem here you all, its that those that mailed in CC, will receive a mail outside of the threat of the ticket... 

so if one of these, responds, the tiket obviously not received the threat history due its not in the response mail..

i mean: Jon, Mary and Jane get the original mail, but due "I send"  not only to the ticket, these guys are not "notified" that the final and true recipiend are "a ticket"

if after that mail that Jon, Mary and Jane, there's other with the ticket, then they will think "ah, ok was a ticket, not a private conversation"

of course, we are lidiating with "dummy" people, that the reason of the ticket survey, ticket support or whatever u name it!

so the the threating goes in a pain due the history will lose when that happened

**Comment by mckaygerhard** [comment]
@inphower i think that u refers when a supporter open a ticket as author, and of course in this case and in 1.9 series of osticket this are not possible, but are not dificulty to make it.. the response from osticket guys was "use 1.10" that was almot 1,5 years ago.. in this moment 1.10 was unstalbe, so the suggestion was to use unstable in production.. great!

**Comment by mckaygerhard** [comment]
this problem still happened in 1.10 ... collaboratos are not showed and  not notified!

**Comment by JediKev** [comment]
@mckaygerhard 

The train of thought here is that since the Collaborators receive the original email from the User, there is no need for them to receive the New Ticket Alert. You are more than welcome to mod the codebase to your liking if this is not something you desire.

Cheers.

**Comment by mckaygerhard** [comment]
solutions seems are in #3353 but developers again not take any on that issue.. puff that's why there's so many fork and "deleted" comments

**Comment by JediKev** [comment]
@mckaygerhard 

There is no "fix" as there is no actual issue, this is how it’s intended to work. As I mentioned before you are more than welcome to modify the codebase/apply the pull request you mentioned and be done with it.

Cheers.

**Comment by mckaygerhard** [comment]
so then the pull #3353 so merge it!

**Comment by vegnuli** [comment]
hey pull are in #3353 about 10 years.. and now @protich  sais: "we want to get with community"!???? umm ...

**Comment by ntozier** [comment]
Hey all. I'm glad that you are having a conversation, however I would point out that it is completely off topic to this issue report. Please keep issue reports on topic. Thank you.

**Comment by diazvictor** [comment]
What's the problem... he's cooperating and they're still complaining
