### ISSUE TITLE
7 Errors while upgrading

### ISSUE THREAD

**Issue by crypt0jan** [osTicket/osTicket#2511]
Hi there, 

I've been trying to upgrade our OSticket version 1.7.2 to 1.9.12 and when that did not work, upgrade it to 1.8.12 which also did not work. I got the same errors and noticed that I miss the tables the errors are talking about, but our system runs fine for over a year now!

ERRORS:
[SELECT `ost_form_entry`.\* FROM `ost_form_entry` WHERE `ost_form_entry`.`object_type` = ? ORDER BY `ost_form_entry`.`sort` ASC LIMIT 1]
Table ‘fakecompanyname.com_support.ost_form_entry’ doesn't exist<br /> <br /> ---- Backtrace ----<br /> #0 (root)/include/mysqli.php(285): osTicket->logDBError('DB Error #1146', '[SELECT `ost_fo…')<br /> #1 (root)/include/class.orm.php(893): db_prepare('SELECT`ost_for…')<br /> #2 (root)/include/class.orm.php(888): MysqlExecutor->execute()<br /> #3 (root)/include/class.orm.php(954): MysqlExecutor->_prepare()<br /> #4 (root)/include/class.orm.php(388): MysqlExecutor->getArray()<br /> #5 (root)/include/class.orm.php(428): ModelInstanceIterator->fillTo(0)<br /> #6 (root)/include/class.orm.php(337): ModelInstanceIterator->offsetGet(0)<br /> #7 (root)/include/class.orm.php(151): QuerySet->offsetGet(0)<br /> #8 (root)/include/class.company.php(27): VerySimpleModel::lookup(Array)<br /> #9 (root)/include/class.company.php(64): Company->getForm()<br /> #10 (root)/include/staff/footer.inc.php(3): Company->__toString()<br /> #11 (root)/scp/upgrade.php(88): require('/var/www/html/d…')<br /> #12 {main}

---

[SELECT `ost_form_entry`.\* FROM `ost_form_entry` WHERE `ost_form_entry`.`object_type` = ? ORDER BY `ost_form_entry`.`sort` ASC LIMIT 1]
Table ‘fakecompanyname.com_support.ost_form_entry’ doesn't exist<br /> <br /> ---- Backtrace ----<br /> #0 (root)/include/mysqli.php(285): osTicket->logDBError('DB Error #1146', '[SELECT `ost_fo…')<br /> #1 (root)/include/class.orm.php(893): db_prepare('SELECT`ost_for…')<br /> #2 (root)/include/class.orm.php(888): MysqlExecutor->execute()<br /> #3 (root)/include/class.orm.php(954): MysqlExecutor->_prepare()<br /> #4 (root)/include/class.orm.php(388): MysqlExecutor->getArray()<br /> #5 (root)/include/class.orm.php(428): ModelInstanceIterator->fillTo(0)<br /> #6 (root)/include/class.orm.php(337): ModelInstanceIterator->offsetGet(0)<br /> #7 (root)/include/class.orm.php(151): QuerySet->offsetGet(0)<br /> #8 (root)/include/class.company.php(27): VerySimpleModel::lookup(Array)<br /> #9 (root)/include/class.company.php(64): Company->getForm()<br /> #10 (root)/include/staff/footer.inc.php(3): Company->__toString()<br /> #11 (root)/scp/upgrade.php(88): require('/var/www/html/d…')<br /> #12 (root)/scp/staff.inc.php(118): require('/var/www/html/d…')<br /> #13 (root)/scp/admin.inc.php(16): require('/var/www/html/d…')<br /> #14 (root)/scp/upgrade.php(16): require_once('/var/www/html/d…')<br /> #15 (root)/scp/staff.inc.php(118): require('/var/www/html/d…')<br /> #16 (root)/scp/tickets.php(17): require('/var/www/html/d…')<br /> #17 (root)/scp/index.php(17): require('/var/www/html/d…')<br /> #18 {main}

---

[INSERT INTO ost_attachment SET object_id=0, `type`='D', inline=1, file_id='']
Duplicate entry ‘0-0-D’ for key ‘PRIMARY'<br /> <br /> ---- Backtrace ----<br /> #0 (root)/include/mysqli.php(163): osTicket->logDBError('DB Error #1062’, ‘[INSERT INTO os…')<br /> #1 (root)/include/upgrader/streams/core/d51f303a-dad45ca2.task.php(27): db_query('INSERT INTO ost…')<br /> #2 (root)/include/class.upgrader.php(371): NewHtmlTemplate->run(30)<br /> #3 (root)/include/class.upgrader.php(122): StreamUpgrader->doTask()<br /> #4 (root)/include/ajax.upgrader.php(35): Upgrader->doTask()<br /> #5 [internal function]: UpgraderAjaxAPI->upgrade()<br /> #6 (root)/include/class.dispatcher.php(145): call_user_func_array(Array, Array)<br /> #7 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/upgrader’, NULL)<br /> #8 (root)/scp/ajax.php(115): Dispatcher->resolve('/upgrader')<br /> #9 {main}

---

[INSERT INTO ost_file SET created=NOW() ,type='image/png',name='powered-by-osticket.png',`key`='b56944cb4722cc5cda9d1e23a3ea7fbc',ft='T',signature='h6zc6UtnLiOrQZq9HwTtUacr_1w3kYqn']
Unknown column ‘key’ in ‘field list'<br /> <br /> ---- Backtrace ----<br /> #0 (root)/include/mysqli.php(163): osTicket->logDBError('DB Error #1054’, ‘[INSERT INTO os…')<br /> #1 (root)/include/class.file.php(353): db_query('INSERT INTO ost…')<br /> #2 (root)/include/class.file.php(528): AttachmentFile::save(Array)<br /> #3 (root)/include/upgrader/streams/core/d51f303a-dad45ca2.task.php(21): AttachmentFile::create(Array, Array)<br /> #4 (root)/include/class.upgrader.php(371): NewHtmlTemplate->run(30)<br /> #5 (root)/include/class.upgrader.php(122): StreamUpgrader->doTask()<br /> #6 (root)/include/ajax.upgrader.php(35): Upgrader->doTask()<br /> #7 [internal function]: UpgraderAjaxAPI->upgrade()<br /> #8 (root)/include/class.dispatcher.php(145): call_user_func_array(Array, Array)<br /> #9 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/upgrader’, NULL)<br /> #10 (root)/scp/ajax.php(115): Dispatcher->resolve('/upgrader')<br /> #11 {main}

---

[SELECT `ost_form_entry`.\* FROM `ost_form_entry` WHERE `ost_form_entry`.`object_type` = ? ORDER BY `ost_form_entry`.`sort` ASC LIMIT 1]
Table ‘fakecompanyname.com_support.ost_form_entry’ doesn't exist<br /> <br /> ---- Backtrace ----<br /> #0 (root)/include/mysqli.php(285): osTicket->logDBError('DB Error #1146', '[SELECT `ost_fo…')<br /> #1 (root)/include/class.orm.php(893): db_prepare('SELECT`ost_for…')<br /> #2 (root)/include/class.orm.php(888): MysqlExecutor->execute()<br /> #3 (root)/include/class.orm.php(954): MysqlExecutor->_prepare()<br /> #4 (root)/include/class.orm.php(388): MysqlExecutor->getArray()<br /> #5 (root)/include/class.orm.php(428): ModelInstanceIterator->fillTo(0)<br /> #6 (root)/include/class.orm.php(337): ModelInstanceIterator->offsetGet(0)<br /> #7 (root)/include/class.orm.php(151): QuerySet->offsetGet(0)<br /> #8 (root)/include/class.company.php(27): VerySimpleModel::lookup(Array)<br /> #9 (root)/include/class.company.php(64): Company->getForm()<br /> #10 (root)/include/staff/footer.inc.php(3): Company->__toString()<br /> #11 (root)/scp/upgrade.php(88): require('/var/www/html/d…')<br /> #12 (root)/scp/staff.inc.php(118): require('/var/www/html/d…')<br /> #13 (root)/scp/admin.inc.php(16): require('/var/www/html/d…')<br /> #14 (root)/scp/upgrade.php(16): require_once('/var/www/html/d…')<br /> #15 (root)/scp/staff.inc.php(118): require('/var/www/html/d…')<br /> #16 (root)/scp/autocron.php(18): require('/var/www/html/d…')<br /> #17 {main}

---

[SELECT `ost_form_entry`.\* FROM `ost_form_entry` WHERE `ost_form_entry`.`object_type` = ? ORDER BY `ost_form_entry`.`sort` ASC LIMIT 1]
Table ‘fakecompanyname.com_support.ost_form_entry’ doesn't exist<br /> <br /> ---- Backtrace ----<br /> #0 (root)/include/mysqli.php(285): osTicket->logDBError('DB Error #1146', '[SELECT `ost_fo…')<br /> #1 (root)/include/class.orm.php(893): db_prepare('SELECT`ost_for…')<br /> #2 (root)/include/class.orm.php(888): MysqlExecutor->execute()<br /> #3 (root)/include/class.orm.php(954): MysqlExecutor->_prepare()<br /> #4 (root)/include/class.orm.php(388): MysqlExecutor->getArray()<br /> #5 (root)/include/class.orm.php(428): ModelInstanceIterator->fillTo(0)<br /> #6 (root)/include/class.orm.php(337): ModelInstanceIterator->offsetGet(0)<br /> #7 (root)/include/class.orm.php(151): QuerySet->offsetGet(0)<br /> #8 (root)/include/class.company.php(27): VerySimpleModel::lookup(Array)<br /> #9 (root)/include/class.company.php(64): Company->getForm()<br /> #10 (root)/include/staff/footer.inc.php(3): Company->__toString()<br /> #11 (root)/scp/upgrade.php(88): require('/var/www/html/d…')<br /> #12 (root)/scp/staff.inc.php(118): require('/var/www/html/d…')<br /> #13 (root)/scp/admin.inc.php(16): require('/var/www/html/d…')<br /> #14 (root)/scp/upgrade.php(16): require_once('/var/www/html/d…')<br /> #15 (root)/scp/staff.inc.php(118): require('/var/www/html/d…')<br /> #16 (root)/scp/autocron.php(18): require('/var/www/html/d…')<br /> #17 {main}

---

[INSERT INTO ost_file SET created=NOW() ,type='image/png',name='kangaroo.png',`key`='6fe1efdea357534d238b86e7860a7c5a',ft='T',signature='fiak1C25LaMYZhVXc2weGfgAaiVKnzAJ']
Unknown column ‘key’ in ‘field list'<br /> <br /> ---- Backtrace ----<br /> #0 (root)/include/mysqli.php(163): osTicket->logDBError('DB Error #1054’, ‘[INSERT INTO os…')<br /> #1 (root)/include/class.file.php(353): db_query('INSERT INTO ost…')<br /> #2 (root)/include/class.file.php(528): AttachmentFile::save(Array)<br /> #3 (root)/include/upgrader/streams/core/d51f303a-dad45ca2.task.php(21): AttachmentFile::create(Array, Array)<br /> #4 (root)/include/class.upgrader.php(371): NewHtmlTemplate->run(30)<br /> #5 (root)/include/class.upgrader.php(122): StreamUpgrader->doTask()<br /> #6 (root)/include/ajax.upgrader.php(35): Upgrader->doTask()<br /> #7 [internal function]: UpgraderAjaxAPI->upgrade()<br /> #8 (root)/include/class.dispatcher.php(145): call_user_func_array(Array, Array)<br /> #9 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/upgrader’, NULL)<br /> #10 (root)/scp/ajax.php(115): Dispatcher->resolve('/upgrader')<br /> #11 {main}

**Comment by ehk20** [comment]
Something similar happen to us going from 1.8 to 1.10-RC2:


Error 1) [SELECT page.*, count(topic.page_id) as topics  FROM ost_page page  LEFT JOIN ost_help_topic topic ON(topic.page_id=page.id)  WHERE page.id=1 GROUP By page.id]

Table 'osticket.ost_page' doesn't exist<br />

Error 2) [SELECT id, f.type, size, name, `key`, signature, ft, bk, f.created,  count(DISTINCT a.object_id) as canned, count(DISTINCT t.ticket_id) as tickets  FROM ost_file f  LEFT JOIN ost_attachment a ON(a.file_id=f.id)  LEFT JOIN ost_ticket_attachment t ON(t.file_id=f.id)  WHERE f.id=2 GROUP BY f.id]

Table 'osticket.ost_ticket_attachment' doesn't exist<br />

Error 3) [SELECT staff.created as added, grp.*, staff.*  FROM ost_staff staff  LEFT JOIN ost_groups grp ON(grp.group_id=staff.group_id)              WHERE username='ehk20']

Table 'osticket.ost_groups' doesn't exist<br />

**Comment by ntozier** [comment]
As a reminder RC releases are not suitable for production environments.,  They are release candidates.  I would recommend that you restore your site and db from back up.

**Comment by ehk20** [comment]
I'm reporting this so that the bug can be fixed in final release.
