### ISSUE TITLE
deleted tickets still show in dashboard.

### ISSUE THREAD

**Issue by kt1024** [osTicket/osTicket#2512]
as showed below, there is only 1 ticket left, but deleted tickets still show in dashboard.
osticket 1.9.12, database: maria 10.0.21

![image](https://cloud.githubusercontent.com/assets/12657496/9621573/b07d04a4-515a-11e5-9a5b-f16d9bd1c855.png)

![image](https://cloud.githubusercontent.com/assets/12657496/9621570/ac113d36-515a-11e5-9e86-497affb086d9.png)

thanks.

**Comment by mckaygerhard** [comment]
the dashboard statics are historical so alwayswill show "what happened in time" not "what are happened right now", so i think its not a bug or problem..
