### ISSUE TITLE
new agent password/login error

### ISSUE THREAD

**Issue by kt1024** [osTicket/osTicket#2514]
1. no password input (or auto generate) for local auth agent.
   ![image](https://cloud.githubusercontent.com/assets/12657496/9627039/2d21d94c-5194-11e5-9215-5e0779c7a07b.png)
2. login/password reset link (from email) broken, unable to login
3.  LDAP auth agents will also got similar initial login link. and can't find places to modify new user email template.  
   ![image](https://cloud.githubusercontent.com/assets/12657496/9627062/4af60718-5194-11e5-9600-4be97295075d.png)

both issue tested with chrome 45/IE 11, both failed. and clean installation twice (with clean DB).
osTicket 1.9.12, maria db 10.0.21

thanks.

**Comment by mfelber** [comment]
This remembers me to my issue report: https://github.com/osTicket/osTicket-1.8/issues/2141

**Comment by kt1024** [comment]
uncheck "welcom email" will allow password input. but 2&3 still no work.

**Comment by greezybacon** [comment]
I agree this is a problem with the LDAP plugin
