### ISSUE TITLE
SMTP mail sender error Authentication required

### ISSUE THREAD

**Issue by frankii91** [osTicket/osTicket#2519]
Unable to email via SMTP:********_:587 [**_******_] Failed to set sender: ***_****\* [SMTP: Invalid response code received from server (code: 530, response: 5.7.1 Authentication required)]

Despite the error messages are sent and delivered.

In the settings Authentication off 
Sending Email via SMTP   -> Authentication Required NO

and if I give smtp authentication ON, it does not work ....
missing field in the login and password may not always be the same as for pop / imap

Sorry for my english but google translator

**Comment by ntozier** [comment]
It appears that your mail server says: code: 530, response: 5.7.1 Authentication required.  Which means it requires SMTP Auth.  If you turn on authentication, do you get an error?

**Comment by frankii91** [comment]
In osTicket you can not turn on Authentication.

Progress is spinning circle and so you can wait forever.

Despite the error mails are delivered to the recipient.
However, not always. Some programs represent them as SPAM

**Comment by ntozier** [comment]
Re: "In osTicket you can not turn on Authentication."

Yes you can... Change Authentication Required to Yes.

**Comment by frankii91** [comment]
When so doing it does not work ... I do not manage to save the settings.

http://pub.vexon.pl/video.avi
http://pub.vexon.pl/video1.avi
http://pub.vexon.pl/video2.avi

**Comment by frankii91** [comment]
My server smtp / imap i OK

**Comment by frankii91** [comment]
This solution provide ssl://domain.com
Too bad that does not have this information quick help   "?"

**Comment by ntozier** [comment]
You cannot use SMTP Auth with out using SSL/TLS with out sending your userid and password over the internet in clear text.  So its generally accepted that SMTP Auth only is used on SSL/TLS connections.

**Comment by ajiprasetyo** [comment]
I have same issue and solved with check "yes" Authentication Required..
