### ISSUE TITLE
IMAP transfer emails to a folder bug

### ISSUE THREAD

**Issue by frankii91** [osTicket/osTicket#2520]
I do not know why but some e-mails are not transferred correctly from your inbox repeatedly copied to the specified folder and there are marked as deleted, are duplicated in the target folder, and received a box marked as deleted.
Sometimes emails are duplicated 10 times.

After stronei person ticket in the logs do not see any errors.

**Comment by mfelber** [comment]
I guess this is a problem that is related to intense load situations or with high latency network connections on this server. I never had this problem with osticket. 

But I have a different system that is suffering from this...

**Comment by infectormp** [comment]
i use osticket with smtp auth and not have any problem

**Comment by frankii91** [comment]
version 1.10RC2 ?

**Comment by frankii91** [comment]
This solution provide ssl://domain.com
Too bad that does not have this information quick help   "?"

**Comment by frankii91** [comment]
OK I know why this is happening.
It does not work deleting e-mails.
in osTicket setting delete the email. It does not remove only means as deleted.

**Comment by frankii91** [comment]
Solution..
in
class.mailfetch.php
function fetchEmails() 

......

original
..
     for($i=$nummsgs; $i>0; $i--) { //process messages in reverse.
            if($this->createTicket($i)) {
                imap_setflag_full($this->mbox, imap_uid($this->mbox, $i), "\\Seen", ST_UID); //IMAP only??          
			if((!$archiveFolder || !imap_mail_move($this->mbox, $i, $archiveFolder)) && $delete)
			imap_delete($this->mbox, $i);
                $msgs++;
......

change to
     for($i=$nummsgs; $i>0; $i--) { //process messages in reverse.
            if($this->createTicket($i)) {

                imap_setflag_full($this->mbox, imap_uid($this->mbox, $i), "\\Seen", ST_UID); //IMAP only??
//this
			$wiadomosc = imap_headerinfo($this->mbox, $i);
			if($wiadomosc->Deleted!='D'){              
//this 
			if((!$archiveFolder || !imap_mail_move($this->mbox, $i, $archiveFolder)) && $delete)
			imap_delete($this->mbox, $i);
//this		
	}
//this
                $msgs++;
......

ceases to copy messages that have already been transferred

If you want to permanently delete messages marked as deleted added:
......
			imap_delete($this->mbox, $i);
			}
// this                        
imap_expunge ($this->mbox);
//this
                       $msgs++;			
....

**Comment by greezybacon** [comment]
@frankii91 if I'm interpreting your suggestions correctly, osTicket should check `imap_headerinfo($this->mbox, $i)->Deleted != 'D'` before archiving. Is that correct?

I see osTicket already has the lines for `imap_delete` and `imap_expunge`

**Comment by greezybacon** [comment]
What mail server software are you using?

**Comment by frankii91** [comment]
function fetchEmails() {

        if(!$this->connect())
            return false;

        $archiveFolder = $this->getArchiveFolder();
        $delete = $this->canDeleteEmails();
        $max = $this->getMaxFetch();

        $nummsgs=imap_num_msg($this->mbox);
        //echo "New Emails:  $nummsgs\n";
        $msgs=$errors=0;
        for($i=$nummsgs; $i>0; $i--) { //process messages in reverse.
            if($this->createTicket($i)) {

                imap_setflag_full($this->mbox, imap_uid($this->mbox, $i), "\\Seen", ST_UID); //IMAP only??
				$wiadomosc = imap_headerinfo($this->mbox, $i);
				if($wiadomosc->Deleted!='D'){              
			if((!$archiveFolder || !imap_mail_move($this->mbox, $i, $archiveFolder)) && $delete)
			imap_delete($this->mbox, $i);
				}
				
imap_expunge ($this->mbox);

                $msgs++;
                $errors=0; //We are only interested in consecutive errors.
            } else {
                $errors++;
            }

            if($max && ($msgs>=$max || $errors>($max*0.8)))
                break;
        }

        //Warn on excessive errors
        if($errors>$msgs) {
            $warn=sprintf(_S('Excessive errors processing emails for %1$s/%2$s. Please manually check the inbox.'),
                    $this->getHost(), $this->getUsername());
            $this->log($warn);
        }

        @imap_expunge($this->mbox);

        return $msgs;
    }

**Comment by greezybacon** [comment]
@frankii91 again, you're suggesting the addition of
```php
$wiadomosc = imap_headerinfo($this->mbox, $i);
            if($wiadomosc->Deleted!='D'){       
```
`imap_expunge` seems already used in the current version

**Comment by frankii91** [comment]
So it is used but in a different place, it seems to me that in my place works better.

eg. to transfer 10 emails at 6 encounters an error. then imap_expunge not perform properly.

and conveying the message loop is executed again

**Comment by frankii91** [comment]
I have a server ... I do not know :) not my :)
