### ISSUE TITLE
v1.10 rc2 Sort not working properly.

### ISSUE THREAD

**Issue by geiserc** [osTicket/osTicket#2522]
v1.10 rc2

When I change the sort direction only the tickets that are shown in that page (I have 2 pages of open tickets) are sorted. Page 1 sorts as a single set of tickets and page 2 sorts as a second set of tickets. Both sort properly within the page, but they do not sort as one single whole set of tickets.

This same 'sort' issue exists when I try to sort tickets found using the search feature.
![image](https://cloud.githubusercontent.com/assets/7979394/9658630/b62cfbc0-51ff-11e5-98d7-73d5703d5beb.jpg)
![image](https://cloud.githubusercontent.com/assets/7979394/9658640/c7fee43a-51ff-11e5-86e2-96549ad1cdca.jpg)

Any thoughts on how to correct this?

Thanks,
Che

**Comment by C4RLOCO** [comment]
This also relates to https://github.com/osTicket/osTicket-1.8/issues/2499

**Comment by greezybacon** [comment]
Can anyone try the patch in e17a9124e7c59d6de7ae21a8e736740b837badec. It's in #2056 to be merged toward rc3

**Comment by geiserc** [comment]
This has fixed it for me! 

Thank you!

**Comment by geiserc** [comment]
Actually, under further testing it is partially working now. It at first seemed to work flawlessly - but what I've found is that it works using the advanced search but the same problem is still in place when typing a search in the search box from the main ticket window.

**Comment by C4RLOCO** [comment]
I agree. I was able to confirm this.

**Comment by ehk20** [comment]
Something similar happens when trying to on "most recently closed" on the closed tab
