### ISSUE TITLE
1.10-RC2: Ticket thread data missing

### ISSUE THREAD

**Issue by geiserc** [osTicket/osTicket#2524]
Tickets showing multiple thread entries show no entries. This is only on some tickets. There does not seem to be any way for me to get the ticket thread to show up. I tried print Thread and print Thread + Internal Notes and the thread entries are missing there as well.

![thread data missing](https://cloud.githubusercontent.com/assets/7979394/9672537/7708449e-5250-11e5-9652-2c301dc9bc08.jpg)

**Comment by ntozier** [comment]
Have you consulted you php error log or tried enabling displaying of errors? Because it looks like you are throwing an error that is being suppressed.

This article describes how to turn on error display. 
http://www.tmib.net/osticket-v19x-frequently-asked-questions-faq#2

**Comment by geiserc** [comment]
I followed the link above and that has now activated the errors showing up directly in osTicket. Here's what I got:
![err](https://cloud.githubusercontent.com/assets/7979394/9688355/8b856b48-52e3-11e5-90fb-d45c29695b78.jpg)

**Comment by greezybacon** [comment]
@geiserc what timezone do you have set in Admin Panel -> Settings -> System, and in your Profile?

**Comment by geiserc** [comment]
Jared,

Timeline is set to auto and thus results on Loss Angeles being set. This is correct (I'm on northern California). Same in my profile.





On Sep 7, 2015, at 8:12 PM, Jared Hancock <notifications@github.com<mailto:notifications@github.com>> wrote:


@geiserc<http://cp.mcafee.com/d/k-Kr6xAe410SyMMyUYyqen6jtPrX5TT4TbCTSbLKcTsdLInvsjsjdKnLtcsUqejtyvwEwuTZta_3UAiTbCO1XvRQHYfyhbsKr89FL_XX_nVZ5YsqehP7nKnjhd7bf8Tv7fFCzAQsYJt6OaaJS4ul3PWApmU6CQjqpJ7HFdMESgFqcy7CXCOsVHkiP2cFASO7bUh-lfzoSgGT2TQ02YMYMyOngJswnIjYUwuTZta_3UAiTbwGx4jUzapdIxOVJxxAsr1vF6y0QJRE2pma_cKzPNFtd42f8TbwIijid409BoHYPh1cD7Zgd426PQQgaOFik29Ewd5069LFI6yASUOrJ89N> what timezone do you have set in Admin Panel -> Settings -> System, and in your Profile?

**Comment by greezybacon** [comment]
@geiserc sorry, you're pictures didn't come through

**Comment by geiserc** [comment]
Very strange. There were no pictures, just the response.

**Comment by geiserc** [comment]
Here's the error message I get now:
![error](https://cloud.githubusercontent.com/assets/7979394/9768255/5835fbc0-56d7-11e5-98af-ffb4b0b47745.jpg)

**Comment by t-oster** [comment]
I have the same problem as soon as I assign a due-date to a new task:
``` 
DateTimeZone::getOffset() expects parameter 1 to be DateTime, boolean given in include/class.format.php on line 522

**Comment by t-oster** [comment]
Seems as if $task->duedate is set to true instead of the dateTime Object. Thus in
include/staff/templates/task-view.tmpl.php(200)
the expression
```
echo $task->duedate ?
                        Format::datetime($task->duedate) : '<span
                        class="faded">&mdash; '.__('None').' &mdash;</span>';
```
evaluates $task->duedate to true but Format::datetime crashes.

I quickfixed it to
```
echo $task->duedate instanceof DateTime ?
                        Format::datetime($task->duedate) : '<span
                        class="faded">&mdash; '.__('None').' &mdash;</span>';
```
but that does not fix the cause. I am currently searching the code, which loads the task from the DB. I guess there is some problem.

**Comment by t-oster** [comment]
...in the database, it is also was set to 0000-00-00 00:00:00. So setting of due-date in the task-creation dialog is also broken. But even changing it in the db to a correct date does not solve it.

**Comment by t-oster** [comment]
(i moved my comments to #2547 since this seems to be a separate issue)
