### ISSUE TITLE
v1.10-rc.2 - Can't edit ticket status value

### ISSUE THREAD

**Issue by jlenfers** [osTicket/osTicket#2527]
Can't edit a new ticket status that I've created before, it doesn't save the change.

**Comment by greezybacon** [comment]
Thanks for the report

**Comment by jlenfers** [comment]
I've received this message after trying to edit a ticket status:

[UPDATE `ost_ticket_status` SET `extra` = ?, `properties` = ? WHERE `ost_ticket_status`.`id` = ? LIMIT 1]

Unknown column 'extra' in 'field list'

---- Backtrace ----
#0 (raiz)/include/mysqli.php(318): osTicket->logDBError('DB Error #1054', '[UPDATE `ost_ti...')
#1 (raiz)/include/class.orm.php(2741): db_prepare('UPDATE `ost_tic...')
#2 (raiz)/include/class.orm.php(526): MySqlExecutor->execute()
#3 (raiz)/include/class.list.php(1423): VerySimpleModel->save(true)
#4 (raiz)/include/ajax.forms.php(161): TicketStatus->setConfiguration(Array)
#5 [internal function]: DynamicFormsAjaxAPI->saveListItem('1', '7')
#6 (raiz)/include/class.dispatcher.php(145): call_user_func_array(Array, Array)
#7 (raiz)/include/class.dispatcher.php(38): UrlMatcher->dispatch('1/item/7/update', Array)
#8 (raiz)/include/class.dispatcher.php(120): Dispatcher->resolve('1/item/7/update', Array)
#9 (raiz)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/list/1/item/7/...', NULL)
#10 (raiz)/scp/ajax.php(260): Dispatcher->resolve('/list/1/item/7/...')
#11 {main}

**Comment by balojs** [comment]
@rayfoss fix available #3236
