### ISSUE TITLE
Redactor Font Size Plugin for osTicket

### ISSUE THREAD

**Issue by Biergarten-Eden** [osTicket/osTicket#2530]
Hi All,

after Installing and customizing osTicket, I've stumbled across a problem which I cant seem to solve.
My Company generally likes to use the Font size 10 in all its E-Mails, and my Boss wants our Ticketsystem to do the same.
Now, the inbuilt Template editor (Redactor) doesnt support choosing Font Sizes.
I've stumbled upon this plugin ( http://imperavi.com/redactor/plugins/font-size/)  from the Redactor makers, and I've looked everywhere for a Tutorial on how to install it, but I havent found any answers yet which have helped me much.
Could you Guys help me out?

**Comment by greezybacon** [comment]
Download it (the javascript file) to the `js/` folder of your osticket installation. Add an include for the JS file in your `include/staff/header.inc.php` and `include/client/header.inc.php` files. Edit `js/redactor-osticket.js` and include `font-size` in the plugins list.

**Comment by jeclink** [comment]
This worked for me in version 1.10
Add the following code to redactor-plugins.js in /js folder
RedactorPlugins.fontsize =  function()
{
   return  {
	init: function()
	{
		var fonts = [10, 11, 12, 14, 16, 18, 20, 24, 28, 30];
		var that = this;
		var dropdown = {};

		$.each(fonts, function(i, s)
				{
					dropdown['s' + i] = { title: '<span style="font-size:' + s + 'px;">' +
                    s + '</span>', func: function() { that.fontsize.set(s); } };
				});
		dropdown.remove = { title: __('Remove Font Size'), func: that.fontsize.reset };
		var button = this.button.addBefore('deleted', 'fontsize', __('Change Font Size'));
		this.button.addDropdown(button, dropdown);
	},
	set: function(value)
	{
		this.inline.format('span', 'style', 'font-size:' + value + 'px;');
		
		
	},
	reset: function()
	{
		this.inline.removeStyleRule('font-size');
	}
  };
};

Next open redactor-osticket.js  and add the fontsize plugin
if (!$.clientPortal) {
            options['plugins'] = options['plugins'].concat(
                    'fontcolor', 'fontfamily', 'signature', 'fontsize');
        }
