### ISSUE TITLE
1.102RC2 Issue Task is not assigned on create

### ISSUE THREAD

**Issue by OBenned** [osTicket/osTicket#2534]
When i have a ticket i wanted to create a task on, i create the task and the try and assign it to a agent.
But when the task is created it is still unassigned

**Comment by Chefkeks** [comment]
As far as I know this issues was already reported and a fix will be included in RC3.
Just can't find the related issue right now...

**Comment by OBenned** [comment]
Is it this issue? https://github.com/osTicket/osTicket-1.8/issues/2445

**Comment by t-oster** [comment]
Yep. I confirm it's fixed with the patch in #2445
