### ISSUE TITLE
1.8 to update 1.10-RC2 bug

### ISSUE THREAD

**Issue by ehk20** [osTicket/osTicket#2535]
We had a few DB Errors post our 1.8 to 1.10-RC2 update but this seems to be the main remaining one. At first I thought it was a problem with the missing *_page table but on a clean install it seems this doesn't exist there either?:

[SELECT page.*, count(topic.page_id) as topics  FROM ost_page page  LEFT JOIN ost_help_topic topic ON(topic.page_id=page.id)  WHERE page.id=1 GROUP By page.id]

Table 'osticket.ost_page' doesn't exist<br />
<br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(163): osTicket->logDBError('DB Error #1146', '[SELECT page.*,...')<br />
#1 (root)/include/class.page.php(39): db_query('SELECT page.*, ...')<br />
#2 (root)/include/class.page.php(25): Page->load('1')<br />
#3 (root)/include/class.page.php(211): Page->Page('1')<br />
#4 (root)/include/class.config.php(441): Page->lookup('1')<br />
#5 (root)/offline.php(27): OsticketConfig->getOfflinePage()<br />
#6 (root)/client.inc.php(34): include('/var/www/ostick...')<br />
#7 (root)/login.php(19): require_once('/var/www/ostick...')<br />
#8 {main}

**Comment by C4RLOCO** [comment]
Hi @ehk20 ,
I would restore the 1.8 backup and try to upgrade via: 1.8 > 1.9 > 1.10RC2
