### ISSUE TITLE
Enhacement request: create tasks automatically

### ISSUE THREAD

**Issue by pkgdemon** [osTicket/osTicket#2539]
It would be useful to be able to create a handful of task types automatically when a new ticket is made.

**Comment by mfelber** [comment]
Do you mean something like a ticket template that inhibits some pre defined tasks? Or a list of pre defined tasks that is available to add in each ticket?

**Comment by pkgdemon** [comment]
Exactly.  I'm trying to create a topic for example that will be for "new hires".  I was going to use notify certain groups independently to create credentials.  This way when tasks are overdue it only nags the right group.  Rather than the entire group the ticket is assigned to.

**Comment by rowlandan25** [comment]
+1

**Comment by philbertphotos** [comment]
That would be very nice.

**Comment by markus4000** [comment]
I like it.
Same #2093

**Comment by Invidia1990** [comment]
+1
