### ISSUE TITLE
v.1.10-RC.2: Internal Note not added when creating new ticket

### ISSUE THREAD

**Issue by C4RLOCO** [osTicket/osTicket#2541]
When agent creates a new ticket, an internal note is also written. However, when clicking "Open" the system creates the ticket accordingly but it does not include the internal note.

**Comment by febrile42** [comment]
Also experiencing this issue in 1.10-RC2.

On submission, ticket information is saved and creates a new ticket as expected, but any internal note appears to be discarded.

**Comment by ipso** [comment]
We are running into this problem too.

**Comment by ipso** [comment]
Checked out latest 'develop' branch and this issue seems to be fixed.
