### ISSUE TITLE
Call to a member function stripQuotedReply() on a non-object ininclude/class.mailer.php on line 160

### ISSUE THREAD

**Issue by jyotirekha** [osTicket/osTicket#2544]
Hi,
We are using osticket 1.8.After frequent interval the server gives the error "Call to a member function stripQuotedReply() on a non-object ininclude/class.mailer.php on line 160".After restarting the server it works fine.
Please can anyone help me.. to resolve this issue parmanently.

**Comment by ntozier** [comment]
1.8 is really old please upgrade to at least 1.8.12

**Comment by jyotirekha** [comment]
Sorry, I am using osticket version  1.8.1.

**Comment by ntozier** [comment]
Please upgrade.
