### ISSUE TITLE
v1.10-rc2: delete managed sequence hangs?

### ISSUE THREAD

**Issue by ntozier** [osTicket/osTicket#2545]
**Server Details:**
osTicket: v1.10-rc.2 (231f11e) 
server:IIS 8.5
php: 5.6.12
MySQL: 5.5.42

**How to replicate:**
Navigate to Admin panel -> Settings -> Tickets -> Manage (button)
delete a managed sequence. (I have created one called YYYY).
Click Save Changes

resulted in the following:
eternal loading screen (see image below)

![capture](https://cloud.githubusercontent.com/assets/1315768/9793422/563beda2-57b3-11e5-8988-5c80c9ac934c.PNG)

esc bypasses the screen.  The delete does process.

**Chrome is showing me this error:**
POST http://ost110.domain.tld/scp/ajax.php/sequence/manage 500 (Internal Server Error)
m.ajaxTransport.a.send @ jquery-1.11.2.min.js?231f11e:4
m.extend.ajax @ jquery-1.11.2.min.js?231f11e:4
(anonymous function) @ scp.js?231f11e:637
m.event.dispatch @ jquery-1.11.2.min.js?231f11e:3
m.event.add.r.handle @ jquery-1.11.2.min.js?231f11e:3

**Comment by greezybacon** [comment]
Do you have any logs from the 500 error?

**Comment by gluck59** [comment]
have same problem, but error 404
(v1.10.4)
