### ISSUE TITLE
1.10 RC2 Due date on new task is broken

### ISSUE THREAD

**Issue by t-oster** [osTicket/osTicket#2547]
If I create a new task and set a due date, in the database only 

```
0000-00-00 00:00:00
```

is written, which leads to the task not being displayed because of the succeeding parse-error when trying to parse the date in include/staff/templates/task-view.tmpl.php(200).

The error the users will see is:

```
DateTimeZone::getOffset() expects parameter 1 to be DateTime, boolean given in include/class.format.php on line 522
```

My timezone in Admin and Profile is Europe/Berlin

**Comment by t-oster** [comment]
It tries to save a unix-timestamp in SQL, but I think this does not work as expected. This line seems to be to blame:
https://github.com/osTicket/osTicket-1.8/blob/develop/include/class.forms.php#L1048

In my database, the column is of type DATETIME. If I change it to BIGINT, it seems to work, but the date is off by 3 hours. So there seems to be an additional timezone error.

So the questions are:
- Are the DateTime Form fields supposed to be saved in an SQL DATETIME or BIGINT column?
- If it should be the DATETIME, the timestamp probably needs to be converted before inserting into the DB
- If it is BIGINT, the SQL code for creating the table seems to be wrong.
- How can the time be off by 3 hours if I am in Europe/Berlin?

**Comment by greezybacon** [comment]
Then it really looks like we should consider #2477

**Comment by akashkumardce** [comment]
To fix the issue-

In file - include/class.tasks.php
Line -
```
            $task->duedate = $vars['internal_formdata']['duedate'];
```
Should be replaced by-
```
            $task->duedate = date('Y-m-d G:i:s',Misc::dbtime($vars['internal_formdata']['duedate'])); 
```     
It creates duedate to be in insertable format for database, and hence fixes the issue.

**Comment by pierrecoetzer** [comment]
The fix in class.tasks.php is working - it now converts the duedate into the correct format, but it doesn't seem to keep the current timezone in mind - My timezone is Africa/Johannesburg - if I add a duedate the time part is out by -4 hours.
Example Due date: 2016-04-16 17:00:01 (Selected on the dropdown), but 2016-04-16 13:00:00 get written to database.

**Comment by edukondalugorla** [comment]
same problem i am facing.
