### ISSUE TITLE
Feature Request: Time and Date Format

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket#2548]
Allow Client and Agent to select a preferred Time and Date format.  i.e. - 12-hour or 24-hour mm-dd-yyyy or yyyy-mm-dd etc.

**Comment by greezybacon** [comment]
What version are you requesting this change to? It has been supported globally (one config for both clients and agents) since at least v1.7. In v1.10, we allow a custom global setting and also a locale override (English, US; German; etc) for agents

**Comment by jdelhome3578** [comment]
I have my system setup with locale defaults but I myself like 24 hour time format and yyyy-mm-dd date format but I don't want the whole system that way. Could you add the system like settings (see image) to the agent and client to override the global setting?
![image](https://cloud.githubusercontent.com/assets/5774055/10020160/5c7d75e0-610f-11e5-80e9-f64058d89618.png)

**Comment by arendtb** [comment]
Thank you that fixed mine.

**Comment by joel0** [comment]
I see there are localization settings in the profile preferences, but the options for time format are system default and relative time.  It would be nice to have the full controls seen on the system settings.
