### ISSUE TITLE
Update Problems from 1.9 to 1.10-RC1

### ISSUE THREAD

**Issue by fgn-git-hub** [osTicket/osTicket#2556]
Are there any known issues while upgrading from 1.9.x to 1.10-RC1. Every time I try to, I get an error while executing the db upgrade script. It always complains about already existing tables and / or rows in tables. Is there a recommended way to do an upgrade? I would really want to test the 1.10 branch, but with my existing ticket data. 

Thank you so far. 
Best regards
Sebastian

**Comment by ntozier** [comment]
The short version is you shouldn't.  RC means release candidate, and it still has a lot of issues.  Also RC2 is out.  Neither should be used in a production environment at this time,

**Comment by fgn-git-hub** [comment]
I know it's a RC, still I can try to update, it for testing isn't it?
Therefor I want to test the update process, I want to see what it's capable of. And I never said, that I want to use it for productive use. 
That's my intention, and I guess, therefor my questions are still reasonable ;-)

**Comment by greezybacon** [comment]
I would recommend attempting the upgrade to RC2. There were several improvements made to the upgrade system between the two releases.
