### ISSUE TITLE
Mobile App for osTicket

### ISSUE THREAD

**Issue by supportreq** [osTicket/osTicket#256]
A mobile app for osTicket with Push Notifications would be an awesome feature

**Comment by 19kestier** [comment]
bump

**Comment by zyrex786** [comment]
Hey guys any update on how to configure the app that's on play store?

**Comment by ntozier** [comment]
You would have to talk to the author of that app.  It is was not released by the osTicket team and is not supported by us.

**Comment by walhallaRV** [comment]
Hi, still no app or responive design availlable?

**Comment by JediKev** [comment]
@walhallaRV

Responsive design should be coming in/after `2.0` (no set development or release date). Mobile app possibly coming after that.

Cheers.
