### ISSUE TITLE
 dashboard reports displays 1s instead of 0s 

### ISSUE THREAD

**Issue by mdmpofu** [osTicket/osTicket#2568]
l happened to delete all tickets that l was using in my test environment and wanted a clean slate. After having successfully reset the dashboard as well, l find that when l have two tickets in my database, the dashboard statistics are incorrect they show 1s instead of 0s in other help topics that have not been assigned a ticket. l am using osticket 1.9. Is there a fix for this problem on this version because the solution given http://osticket.com/forum/discussion/9543/fix-statistics-page for version 1.7 doesnt seem to work with 1.9, all it does is to blank out the statistics.
![statistics](https://cloud.githubusercontent.com/assets/14290995/9954895/f37d09b8-5dec-11e5-92cd-031eeeb6a4b5.PNG)

**Comment by ntozier** [comment]
The Dashboard has pretty much always had the problem of showing 1s instead of 0s.  It's been slated to be revamped for some time but that hasn't happened yet.  I'm not aware of any fix besides the one that you linked.

**Comment by ChristWolves** [comment]
If anyone stumbled upon this page with this problem, I have a solution for those who are not familiar with PHP..

Here is the code you should replace for oSTicket v1.9.14 in include/ajax.reportsphp about line 85 (after  # XXX: Die if $group not in $groups)
From: 
`$queries=array(
            array(5, 'SELECT '.$info['fields'].',
                COUNT(*)-COUNT(NULLIF(A1.state, "created")) AS Opened,
                COUNT(*)-COUNT(NULLIF(A1.state, "assigned")) AS Assigned,
                COUNT(*)-COUNT(NULLIF(A1.state, "overdue")) AS Overdue,
                COUNT(*)-COUNT(NULLIF(A1.state, "closed")) AS Closed,
                COUNT(*)-COUNT(NULLIF(A1.state, "reopened")) AS Reopened
            FROM '.$info['table'].' T1
                LEFT JOIN '.TICKET_EVENT_TABLE.' A1
                    ON (A1.'.$info['pk'].'=T1.'.$info['pk'].'
                         AND NOT annulled
                         AND (A1.timestamp BETWEEN '.$start.' AND '.$stop.'))
                LEFT JOIN '.STAFF_TABLE.' S1 ON (S1.staff_id=A1.staff_id)
            WHERE '.$info['filter'].'
            GROUP BY T1.'.$info['pk'].'
            ORDER BY '.$info['sort']),`

To:
` $queries=array(
            array(5, 'SELECT '.$info['fields'].',
  SUM(CASE WHEN A1.state = "created" THEN 1 ELSE 0 END) AS Opened,
  SUM(CASE WHEN A1.state = "assigned" THEN 1 ELSE 0 END) AS Assigned,
  SUM(CASE WHEN A1.state = "overdue" THEN 1 ELSE 0 END) AS Overdue,
  SUM(CASE WHEN A1.state = "closed" THEN 1 ELSE 0 END) AS Closed,
  SUM(CASE WHEN A1.state = "reopened" THEN 1 ELSE 0 END) AS Reopened
            FROM '.$info['table'].' T1
                LEFT JOIN '.TICKET_EVENT_TABLE.' A1 ON (A1.'.$info['pk'].'=T1.'.$info['pk'].' AND NOT annulled AND (A1.timestamp BETWEEN '.$start.' AND '.$stop.'))
                LEFT JOIN '.STAFF_TABLE.' S1 ON (S1.staff_id=A1.staff_id)
            WHERE '.$info['filter'].'
            GROUP BY T1.'.$info['pk'].'
            ORDER BY '.$info['sort']),`

That's all folks! Enjoy osTicketing.. :)

**Comment by rockman73** [comment]
@protich and @greezybacon - this fix been is missing from the latest repo. It appears include/ajax.reports.php is no longer present in the repo. Reporting is a critical feature and this is a P1 bug, thanks for your attention! :)

**Comment by rockman73** [comment]
Here is an alternate solution by tweaking the LEFT JOIN logic:
```
$queries=array(
            array(5, 'SELECT '.$info['fields'].',
                COUNT(*)-COUNT(NULLIF(A1.state, "created")) AS Opened,
                COUNT(*)-COUNT(NULLIF(A1.state, "assigned")) AS Assigned,
                COUNT(*)-COUNT(NULLIF(A1.state, "overdue")) AS Overdue,
                COUNT(*)-COUNT(NULLIF(A1.state, "closed")) AS Closed,
                COUNT(*)-COUNT(NULLIF(A1.state, "reopened")) AS Reopened
            FROM '.$info['table'].' T1
                LEFT JOIN '.TICKET_EVENT_TABLE.' A1
                    ON (A1.'.$info['pk'].'=T1.'.$info['pk'].'
                         AND (A1.timestamp BETWEEN '.$start.' AND '.$stop.'))
                LEFT JOIN '.STAFF_TABLE.' S1 ON (S1.staff_id=A1.staff_id)
            WHERE '.$info['filter'].' AND A1.'.$info['pk'].' is not null
            GROUP BY T1.'.$info['pk'].'
            ORDER BY '.$info['sort']),
```

**Comment by ntozier** [comment]
@rockman73 a P1 bug...  while I agree that reporting is important I cannot agree with your opinion.

I would recommend that you check out the ReportsMod by forum user scottro.
http://www.sudobash.net/osticket-reports-6-0-osticket-release-1-7/

The Dashboard has been on the to do list to revamp for quite some time now, and it not even close to a priority last I heard.

**Comment by rockman73** [comment]
First, I'd like to say THANK YOU for a pretty cool ticketing system. We will have to agree to disagree about reporting. :) You guys should remove the "Dashboard Reports" from the feature page http://osticket.com//features. Based on your responses here and on the forums, plus the removal of include/ajax.reports.php from the repo it is clear reporting is not a feature of this product anymore. But, thank you for the redirect to a third-party solution. We will likely roll our own reporting. Cheers
