### ISSUE TITLE
1.10-RC2 Display issue on creating custom forms

### ISSUE THREAD

**Issue by ewhptiv** [osTicket/osTicket#2569]
When creating custom forms, the fields are too large to fit in the main column. Probably an issue depending of the language (french in this case).

![image](https://cloud.githubusercontent.com/assets/395636/9956707/568d8f3a-5dea-11e5-8226-db7fa24c1483.png)

**Comment by greezybacon** [comment]
Yeah, looks like we need `max-width` on the drop-down lists

**Comment by nfebuary** [comment]
@greezybacon After you save the form the config button appears inline with the type select list. We would have to drop the config to the next line as well. We could also squeeze some additional space out of the label and variable fields. Not much, just a few px/em's.

![screen shot 2015-10-02 at 9 23 01 am](https://cloud.githubusercontent.com/assets/8247872/10248814/90a19862-68e7-11e5-9db9-1d263bd9ccf2.png)
