### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by philbertphotos** [osTicket/osTicket#2574]
I edited and updated the STAFFINC_DIR - staff.inc.php
Most of the fields were missing 
_example:_
`<input type="email" size="40" maxlength="64" style="width: 300px" name="email"              value="<?php echo Format::htmlchars($staff->email); ?>`

```
<input type="email" size="40" maxlength="64" style="width: 300px" name="email"  class="auto email"  value="<?php echo Format::htmlchars($staff->email); ?>"
```

I added class="auto email", class="auto first" class="auto last", etc to the receptive fields that way when creating a user with LDAP it automatically inserts the data in the inputs.

**Comment by greezybacon** [comment]
> Most of the fields were missing 
Like not there at all, or missing something?

**Comment by philbertphotos** [comment]
like the "class" was missing 90 percent of it ... luckily you had the class="auto phone" so I was able to deduce the rest.

**Comment by goobersmooch** [comment]
I was able to get the email to populate by adding class="auto email" after name="email", but I can't seem to get the first or last names to populate. Any suggestions?

**Comment by philbertphotos** [comment]
yea do the same to the others class="auto first", class="auto last",

**Comment by goobersmooch** [comment]
Awesome! Works like a champ! Thanks @philbertphotos.
