### ISSUE TITLE
OST 1.10 - Add original ticket # to a new Task sequence automatically

### ISSUE THREAD

**Issue by pfurches** [osTicket/osTicket#2578]
OST 1.10 RC2
It would be a nice feature if the task sequence number format or at least somewhere in the task itself, could reference the original ticket.

If you create a task from within a ticket, is it possible to reference the original ticket # automatically?  Maybe using a automatic variable like %{ticket.number}.

We use a "gracious hospitality" approach to tickets. When a ticket is assigned, you own it until it is closed. If you need additional help, you create a task for another agent to perform. This allows us to track tickets and all the agents who worked on the issue.

For example:
A ticket is opened. We need part. Agent creates a task in the ticket for the supply department to order the needed part.  When the part comes in the task is closed but if the agent forgets to reference the original ticket when they created the task (and they do that a lot in our testing) the second agent has to search the system for the original ticket so they can route the part where it needs to go.

As far as I call tell, you can setup the sequence numbering to use prefix, etc.  But if it is created within a ticket, it will not reference a ticket # unless the agent creating the task remembers to put it in there.

I know a task can be created independently from tickets. But if it is opened from within a ticket can the system detect this and append the ticket # in the task header or at least the internal notes section?

**Comment by ntozier** [comment]
I like this idea.

**Comment by philbertphotos** [comment]
me too

**Comment by markus4000** [comment]
I like it. Its a must have. Same as #2446
