### ISSUE TITLE
v1.10 - ablity to have filters removed Trigger words from email

### ISSUE THREAD

**Issue by philbertphotos** [osTicket/osTicket#2583]
Example a Agent reply to an email with the word #WHATEVER somewhere in the body it will remove the trigger word and do what ever task is needed by the filter.

**Comment by ntozier** [comment]
1. I cannot confirm the blank page pdf.  This works in my installation just fine.
2. Changing this to a different title / error description appears to be completely unrelated to the original topic.  In the future instead of editing your issue report, please simply create a new one.

**Comment by philbertphotos** [comment]
I made a mistake with the first bug report and had a feature request so i decided to edit instead of close it ... Sorry about that

**Comment by ntozier** [comment]
No worries.  Like I said... in the future. :)

**Comment by sumann** [comment]
Can I use filters to select auto response. My requirement is to read a tickets and on the basis of some keywords give auto response for that ticket.

**Comment by ntozier** [comment]
@sumann this doesn't appear to be related to the original thread.  Please ask your question on the forums, or start your own issue report.  Thanks.
