### ISSUE TITLE
Feature request 1.10: Display List Properties

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket#2587]
We are already able to add properties to list items but I find them not useful as they are not able to be shown. I think it would help if a client selected a list item that on the agent side there was an option to view those item properties in the ticket view. My example would be I ask clients to select a system id for a printer, with that id I have the printer model and brand selected as item properties. Agent at the ticket details can't see that information currently so I have to ask the client to fill in an extra field for model type. Can you make something like a help tip on the ticket details so when you hover over the item that has properties that they display in something like a help tip?

**Comment by greezybacon** [comment]
I agree, this would be a great advancement of the list feature

**Comment by jdelhome3578** [comment]
Added with #3153
