### ISSUE TITLE
Query token not found errow in osTicket v1.9.12 (stable)

### ISSUE THREAD

**Issue by admister** [osTicket/osTicket#2592]
getting the error "Query token not found" while exporting the list of tickets in .csv format. this happens only while we filter tickets from advance search. much like the issue mentioned on the link below
http://osticket.com/forum/discussion/76379/resolved-export-list-error-query-token-not-found
![eror](https://cloud.githubusercontent.com/assets/5221608/10157822/2863b3e0-66ab-11e5-9f94-0330c90179e8.png)

**Comment by infectormp** [comment]
clear browser chache

**Comment by jagmohangupta** [comment]
thank you, i did that and tried from different systems. still the same

**Comment by greezybacon** [comment]
The search system in v1.9 has trouble with searches over 500 records

**Comment by infectormp** [comment]
This solution https://github.com/osTicket/osTicket-1.8/issues/1936  fix this problem
