### ISSUE TITLE
Feature Request: Internal Notice as Filter Action

### ISSUE THREAD

**Issue by t-oster** [osTicket/osTicket#2595]
It would be a great feature, if one could add a Filter-Action, which adds an internal notice to a ticket if it matches the filter criteria.
I know there are some other requests for automatic task-creation in ticket filters, but I think internal notices are more easy to implement and would suit many needs.

I.E. we get some mails which may be Phishing, but I cannot be sure. I just want to add a notice for our agents, that they should take caution when responding to this ticket.

**Comment by greezybacon** [comment]
:+1:
