### ISSUE TITLE
 future improvement - Fileuploade System

### ISSUE THREAD

**Issue by oneilak** [osTicket/osTicket#2598]
Hello everybody,

I have always the problem that the permissions do not quite fit the file uploade. if I then the whole new bequeath it goes again.

Is there perhaps in the future a better alternative?

![2015_09_30_13_53_21_geloschte_elemente_andreas kuhnt_extern_ffg_werke com_outlook](https://cloud.githubusercontent.com/assets/13413719/10192178/b660656a-677a-11e5-9bfd-b018b71f232a.png)

**Comment by ntozier** [comment]
Don't use the storage: filesystem plugin and store things in the database instead?

**Comment by oneilak** [comment]
I do not want unnecessary DB is large by Annexes

**Comment by infectormp** [comment]
i get same error from time to time and solve it by ```chown -R apache:apache /sd/files```

**Comment by oneilak** [comment]
i worked with iis ;-)

**Comment by infectormp** [comment]
@oneilak so you need move to linux :)

**Comment by greezybacon** [comment]
This sort of issue is the reason we retired file based attachments in favor of database-backed ones. Folks just seem to have a hard time with filesystem permissions. However, the idea is really simple. The web process (whatever user it happens to be running as--your guess is as good as mine on Windows), will write files to the upload folder you configured in the plugin. Then, when the file is needed, it will read and serve the file again. That's it. Anyone could read the code [here](https://github.com/osTicket/core-plugins/blob/develop/storage-fs/storage.php).

Have you tried turning it off and back on again? Perhaps you should check the plugin settings and make sure the path configured is correct. Perhaps you should just grant "Everyone" read access to the "Uploade" folder.

**Comment by ntozier** [comment]
I may be totally off base here... but doesn't PHP /temp folder permissions also do something weird ... like uploaded files go to PHPs temp folder.  It gets permissions based on that locale.  Then it gets moved to where it belongs, and still has the permissions of the original folder?

**Comment by oneilak** [comment]
Help ....

he saves, despite the conversion is no longer in the db ... which value in the DB are the front where he should save (fileshare / DB) ??

**Comment by oneilak** [comment]
php log

#1 C:\inetpub\wwwroot\osticket\include\class.file.php(247): AttachmentFile->open()
#2 C:\inetpub\wwwroot\osticket\file.php(36): AttachmentFile->download('inline', '1443744000')
#3 {main}
  thrown in C:\inetpub\wwwroot\osticket\include\class.file.php on line 693
[01-Oct-2015 14:09:04 Europe/Berlin] PHP Fatal error:  Uncaught exception 'Exception' with message 'No such backend registered' in C:\inetpub\wwwroot\osticket\include\class.file.php:693
Stack trace:
#0 C:\inetpub\wwwroot\osticket\include\class.file.php(111): FileStorageBackend::getInstance(Object(AttachmentFile))
#1 C:\inetpub\wwwroot\osticket\include\class.file.php(247): AttachmentFile->open()
#2 C:\inetpub\wwwroot\osticket\file.php(36): AttachmentFile->download(false, '1443744000')
#3 {main}
  thrown in C:\inetpub\wwwroot\osticket\include\class.file.php on line 693
[01-Oct-2015 14:10:29 Europe/Berlin] PHP Fatal error:  Uncaught exception 'Exception' with message 'No such backend registered' in C:\inetpub\wwwroot\osticket\include\class.file.php:693
Stack trace:
#0 C:\inetpub\wwwroot\osticket\include\class.file.php(111): FileStorageBackend::getInstance(Object(AttachmentFile))
#1 C:\inetpub\wwwroot\osticket\include\class.file.php(247): AttachmentFile->open()
#2 C:\inetpub\wwwroot\osticket\file.php(36): AttachmentFile->download(false, '1443744000')
#3 {main}
  thrown in C:\inetpub\wwwroot\osticket\include\class.file.php on line 693
[01-Oct-2015 14:12:15 Europe/Berlin] PHP Fatal error:  Uncaught exception 'Exception' with message 'No such backend registered' in C:\inetpub\wwwroot\osticket\include\class.file.php:693
Stack trace:
#0 C:\inetpub\wwwroot\osticket\include\class.file.php(111): FileStorageBackend::getInstance(Object(AttachmentFile))
#1 C:\inetpub\wwwroot\osticket\include\class.file.php(247): AttachmentFile->open()
#2 C:\inetpub\wwwroot\osticket\file.php(36): AttachmentFile->download(false, '1443744000')
#3 {main}
  thrown in C:\inetpub\wwwroot\osticket\include\class.file.php on line 693
[01-Oct-2015 14:12:45 Europe/Berlin] PHP Fatal error:  Uncaught exception 'Exception' with message 'No such backend registered' in C:\inetpub\wwwroot\osticket\include\class.file.php:693
Stack trace:
#0 C:\inetpub\wwwroot\osticket\include\class.file.php(111): FileStorageBackend::getInstance(Object(AttachmentFile))
#1 C:\inetpub\wwwroot\osticket\include\class.file.php(247): AttachmentFile->open()
#2 C:\inetpub\wwwroot\osticket\file.php(36): AttachmentFile->download(false, '1443744000')
#3 {main}
  thrown in C:\inetpub\wwwroot\osticket\include\class.file.php on line 693
[01-Oct-2015 14:13:55 Europe/Berlin] PHP Fatal error:  Uncaught exception 'Exception' with message 'No such backend registered' in C:\inetpub\wwwroot\osticket\include\class.file.php:693
Stack trace:
#0 C:\inetpub\wwwroot\osticket\include\class.file.php(111): FileStorageBackend::getInstance(Object(AttachmentFile))
#1 C:\inetpub\wwwroot\osticket\include\class.file.php(247): AttachmentFile->open()
#2 C:\inetpub\wwwroot\osticket\file.php(36): AttachmentFile->download(false, '1443744000')
#3 {main}
  thrown in C:\inetpub\wwwroot\osticket\include\class.file.php on line 693

**Comment by greezybacon** [comment]
Did you uninstall the file system storage plugin? Visit the system settings page, select a backend and click save

**Comment by oneilak** [comment]
have the plugin uninstalled and all ost files again rerecorded ...
it works now conditioned again ...
sometimes it can open files sometimes not ...

strange and incomprehensible: P (technically)

**Comment by oneilak** [comment]
Addendum: in IE it seems to go smoothly
in Firefox and Chrome but there are access problems and the different.
means: what goes in Firefox does not have unbending tim chrome can be opened.
we've got a latency problem?

**Comment by greezybacon** [comment]
@oneilak I have no idea what you're talking about
