### ISSUE TITLE
1.10.rc2 - Signauture is not added to sent mails

### ISSUE THREAD

**Issue by PPCM** [osTicket/osTicket#2599]
Hi there,

During the redaction of the message, the signature is present, but when it is received by the user, the signature is not missing.

Here are 2 screenshots to illustrate my words
![cf77b31e-6428-11e5-88ff-f105bf389c80](https://cloud.githubusercontent.com/assets/1247223/10193094/3a2d1c34-6781-11e5-8845-8425332925fa.jpg)
![cf7974c4-6428-11e5-8d3d-ea58a3aec0fd](https://cloud.githubusercontent.com/assets/1247223/10193098/411b3b84-6781-11e5-9b04-5d2c693fccc3.jpg)

Any idea about this issue?

Thanks a lot

**Comment by ntozier** [comment]
This appears to be a duplicate report of https://github.com/osTicket/osTicket-1.8/issues/2232

**Comment by greezybacon** [comment]
Looks like you changed your response template to `%{response}`, you need to add `%{signature}`

**Comment by PPCM** [comment]
Great, that's it

Thanks a lot

**Comment by rayfoss** [comment]
Closing duplicate issue, please continue the conversation on the ne

**Comment by Dsaamorim** [comment]
How can i add and show applicant's signature when i print out?

I need some help, please, i did not undertand these posts.
