### ISSUE TITLE
Adding an ajax page

### ISSUE THREAD

**Issue by JamesPCS** [osTicket/osTicket#2601]
I am using version 1.10 playing around with it and trying to get it functional but I tried adding an ajax page in the staff directory called getLocations.php. What this does is simply when you select a customer (which is a feature I added) from a dropdown list, another dropdown is populated with a list of locations for that customer. The problem is that if I navigate directly to that page via setting the url to OSTickets/upload/include/staff/getLocations.php, I get a forbidden error. It seems the coders have created an ajax page that all ajax must go through and I'm trying to figure out where the problem is. However, if I navigate to that page I get a 400 Bad Request Http response. They use regular expressions to create a string and even create their own Http responses which means that I might not even be getting the right Http response! Here's where I think the problem is:

[code]
url('^/tickets/', patterns('ajax.tickets.php:TicketsAjaxAPI',
        url_get('^(?P<tid>\d+)/change-user$', 'changeUserForm'),
        url_post('^(?P<tid>\d+)/change-user$', 'changeUser'),
        url_get('^(?P<tid>\d+)/user$', 'viewUser'),
        url_post('^(?P<tid>\d+)/user$', 'updateUser'),
        url_get('^(?P<tid>\d+)/preview', 'updateUser'),
        url_get('^(?P<cust_id>\d+)/preview', 'findLocations'),
        url_post('^(?P<tid>\d+)/lock$', 'acquireLock'),
        url_post('^(?P<tid>\d+)/lock/(?P<id>\d+)/renew', 'renewLock'),
        url_post('^(?P<tid>\d+)/lock/(?P<id>\d+)/release', 'releaseLock'),
        url_get('^(?P<tid>\d+)/forms/manage$', 'manageForms'),
        url_post('^(?P<tid>\d+)/forms/manage$', 'updateForms'),
        url_get('^(?P<tid>\d+)/canned-resp/(?P<cid>\w+).(?P<format>json|txt)', 'cannedResponse'),
        url_get('^(?P<tid>\d+)/status/(?P<status>\w+)(?:/(?P<sid>\d+))?$', 'changeTicketStatus'),
        url_post('^(?P<tid>\d+)/status$', 'setTicketStatus'),
        url('^(?P<tid>\d+)/thread/(?P<thread_id>\d+)/(?P<action>\w+)$', 'triggerThreadAction'),
        url_get('^status/(?P<status>\w+)(?:/(?P<sid>\d+))?$', 'changeSelectedTicketsStatus'),
        url_post('^status/(?P<state>\w+)$', 'setSelectedTicketsStatus'),
        url_get('^(?P<tid>\d+)/tasks$', 'tasks'),
        url('^(?P<tid>\d+)/add-task$', 'addTask'),
        url_get('^(?P<tid>\d+)/tasks/(?P<id>\d+)/view$', 'task'),
        url_post('^(?P<tid>\d+)/tasks/(?P<id>\d+)$', 'task'),
        url_get('^lookup', 'lookup'),
[/code]

The findLocations url_get is the code I added. I'm sure it's wrong but I can't figure out exactly what these regular expressions are doing. They are sent to some dispatcher class that pulls apart the url string passed in and matches it to something. 

Anyone have a clue as to how to get my ajax to work?

**Comment by greezybacon** [comment]
The `include/` folder is restricted. Move your code to the `scp/` folder

**Comment by JamesPCS** [comment]
Does that mean the regex I added is correct? Even when I directly call that page it changes it to ajax.php so it does have to go through this page? Here's the code I have so far:

On page ticket-open.inc.php
[code]
<td>
                <span style="display:inline-block;">
	    			<select name="customer" onChange="findLocations(this.value)">
			        	<option value="0" selected >Select Customer</option>
			            <?php
			             $services = db_query('SELECT cust_id,cust_name FROM '.CUST_TABLE.' ORDER BY cust_name');
			             while (list($cust_id,$name) = db_fetch_row($services)){
			                $selected =($info['customer']==$cust_id)?'SELECTED':'';?>
			                <option value="<?=$cust_id?>"<?=$selected?>><?=$name?></option>
			            <?php
			             }?>
			        </select>
			        &nbsp;<font class="error"><b>*</b>&nbsp;<?=$errors['customer']?></font>
		   		</span>
            </td> <tr>
            <td width="160"> <?php echo __('Location'); ?>: </td>
            <td>
                <span id="loc_div" style="display:inline-block;">
	                <select id="sLocation" name="location" onChange="autoComplete()">
		                <option value="0" selected>Select Location</option>
		                <?php
		                 if(isset($_POST['customer'])){
		                	$services=db_query('SELECT location_id, site_name FROM '.CUST_LOCATION_TABLE.' WHERE cust_id='.db_input($_POST['customer']),false);
		                 	while (list($location_id,$name)=db_fetch_row($services)){
		                    	$selected=($info['location']==$location_id)?'SELECTED':'';?>
		                    	<option value="<?=$location_id?>" <?=$selected?> ><?=$name?></option>
		                	<?php }
		                 }?>
		            </select>
		            &nbsp;<font class="error"><b>*</b>&nbsp;<?=$errors['location']?></font>
	            </span>
            </td>
[/code]

In scp.js I have
[code]
function findLocations(cust_id, auto_complete){
	url = '/OSTickets/upload/scp/ajax.php/getLocations.php?cust_id='+cust_id;
	$.get(url,
		function(data){
			$('#loc_div').html("<select name='location' onChange='autoComplete()' >"+
				"<option value=''>Select Location</option>"+data+"</select>");
			try{$('#loc_div').trigger('create')}catch(e){}
			autoComplete();		
		},
		"html"
	);
}
[/code]

In getLocations.php (which I have now put in the scp directory) I have
[code]
 <?php 

 include_once(INCLUDE_DIR.'class.error.php');
 include_once(INCLUDE_DIR.'class.role.php');
 include_once(INCLUDE_DIR.'class.passwd.php');
 include_once(INCLUDE_DIR.'class.user.php');
 include_once(INCLUDE_DIR.'class.auth.php');
 include_once(INCLUDE_DIR.'class.location.php');
 

 	$custID = 116; 

 	if (isset($_POST['custID'])) {
 		$custID = $_POST['custID'];
 	}
 	
	$sql = 'SELECT l.location_id, l.site_name FROM ' . CUST_LOCATION_TABLE
    	. ' AS l JOIN ' . CUST_TABLE . ' AS c ON c.cust_id=l.cust_id'
    	. ' WHERE c.cust_id='.$custID;
    	
  	$locations = array();

 	if (($res=db_query($sql)) && db_num_rows($res)) {
        $str = "";
        $str .= "<option value='0'>Select Location</option>";

        while(list($id,$name)=db_fetch_row($res)) { 
              $str .= "<option value=".$id.">".$name."</option>";
        }
    }
	echo $str;
	
?>
[/code]

The problem is that I can't seem to navigate to that page. When I go use the url "'/OSTickets/upload/scp/getLocations.php?cust_id='+cust_id;"
I get this error:
jquery-1.11.2.min.js?3e4b685:4 GET http://172.16.13.19/OSTickets/upload/scp/ajax.php?api=tickets&f=autoComplete&id= 400 (Bad Request)

so it's still adding the ajax.php into the url. So then in ajax.php I added:
[code]
url('^/tickets/', patterns('ajax.tickets.php:TicketsAjaxAPI',
    	url_get('^(?P<cust_id>\d+)/preview', 'findLocations'),
[/code]

and just for good measure I added in ajax.tickets.php
[code]
function findLocations($cust_id = 116){
//set to 116 by default just to try to get data. Will set to 0 eventually.    
    	$src="";
    	if($res=db_query("SELECT location_id, site_name FROM ".CUST_LOCATION_TABLE." WHERE cust_id=".$cust_id))
    		if(db_num_rows($res)==1)
    		{
    			$row=db_fetch_array($res);
    			$src.= '<option value="'.$row['location_id'].'" selected="SELECTED">'.$row['site_name'].'</option>:1';
    			return $src;
    		}
    	while($row=db_fetch_array($res)){
    		$src.= '<option value="'.$row['location_id'].'">'.$row['site_name'].'</option>';
    	}
    	return $src==""?'<option>-No Locations Found-</option>':$src;
    }
[/code]

I tried renaming those files to txt and attaching them here but it wouldn't let me.
