### ISSUE TITLE
timeline to support PHP7

### ISSUE THREAD

**Issue by jjjj12212** [osTicket/osTicket#2602]
PHP 7 is around the corner and I tried the application with PHP7 and getting alot of deprecated issues with the Class methods having the same name as the class (the constructor) then nothing happens (a blank screen).

Is there a timeline when osTicket will be supporting PHP 7?

**Comment by greezybacon** [comment]
> Is there a timeline when osTicket will be supporting PHP 7?

Wanna do the work and open a pull request? I have run osTicket v1.10 (`develop-next`) on PHP 7 with just a few changes, so I don't think the codebase is *too* far off

**Comment by infectormp** [comment]
Here is some deprecated warnings for PHP 7:
```Method name "Services_JSON" in class "Services_JSON" is deprecated (@php4_constructors) in file /xxx/include/JSON.php[132].
Method name "Services_JSON_Error" in class "Services_JSON_Error" is deprecated (@php4_constructors) in file /xxx/include/JSON.php[782].
Method name "Services_JSON_Error" in class "Services_JSON_Error" is deprecated (@php4_constructors) in file /xxx/include/JSON.php[796].
Method name "PasswordHash" in class "PasswordHash" is deprecated (@php4_constructors) in file /xxx/include/PasswordHash.php[33].
Method name "AjaxController" in class "AjaxController" is deprecated (@php4_constructors) in file /xxx/include/class.ajax.php[28].
Method name "API" in class "API" is deprecated (@php4_constructors) in file /xxx/include/class.api.php[22].
Method name "Captcha" in class "Captcha" is deprecated (@php4_constructors) in file /xxx/include/class.captcha.php[21].
Method name "Config" in class "Config" is deprecated (@php4_constructors) in file /xxx/include/class.config.php[32].
Method name "OsticketConfig" in class "OsticketConfig" is deprecated (@php4_constructors) in file /xxx/include/class.config.php[182].
Method name "CryptoAlgo" in class "CryptoAlgo" is deprecated (@php4_constructors) in file /xxx/include/class.crypto.php[234].
Method name "CSRF" in class "CSRF" is deprecated (@php4_constructors) in file /xxx/include/class.csrf.php[37].
Method name "Dispatcher" in class "Dispatcher" is deprecated (@php4_constructors) in file /xxx/include/class.dispatcher.php[24].
Method name "UrlMatcher" in class "UrlMatcher" is deprecated (@php4_constructors) in file /xxx/include/class.dispatcher.php[84].
Method name "Filter" in class "Filter" is deprecated (@php4_constructors) in file /xxx/include/class.filter.php[40].
Method name "FilterRule" in class "FilterRule" is deprecated (@php4_constructors) in file /xxx/include/class.filter.php[564].
Method name "TicketFilter" in class "TicketFilter" is deprecated (@php4_constructors) in file /xxx/include/class.filter.php[700].
Method name "Internationalization" in class "Internationalization" is deprecated (@php4_constructors) in file /xxx/include/class.i18n.php[26].
Method name "DataTemplate" in class "DataTemplate" is deprecated (@php4_constructors) in file /xxx/include/class.i18n.php[542].
Method name "Knowledgebase" in class "Knowledgebase" is deprecated (@php4_constructors) in file /xxx/include/class.knowledgebase.php[20].
Method name "Log" in class "Log" is deprecated (@php4_constructors) in file /xxx/include/class.log.php[22].
Method name "Mailer" in class "Mailer" is deprecated (@php4_constructors) in file /xxx/include/class.mailer.php[33].
Method name "MailFetcher" in class "MailFetcher" is deprecated (@php4_constructors) in file /xxx/include/class.mailfetch.php[36].
Method name "Mail_parse" in class "Mail_Parse" is deprecated (@php4_constructors) in file /xxx/include/class.mailparse.php[35].
Method name "EmailDataParser" in class "EmailDataParser" is deprecated (@php4_constructors) in file /xxx/include/class.mailparse.php[584].
Method name "DatabaseMigrater" in class "DatabaseMigrater" is deprecated (@php4_constructors) in file /xxx/include/class.migrater.php[36].
Method name "StaffNav" in class "StaffNav" is deprecated (@php4_constructors) in file /xxx/include/class.nav.php[26].
Method name "AdminNav" in class "AdminNav" is deprecated (@php4_constructors) in file /xxx/include/class.nav.php[209].
Method name "osTicket" in class "osTicket" is deprecated (@php4_constructors) in file /xxx/include/class.osticket.php[54].
Method name "osTicketSession" in class "osTicketSession" is deprecated (@php4_constructors) in file /xxx/include/class.ostsession.php[30].
Method name "PageNate" in class "PageNate" is deprecated (@php4_constructors) in file /xxx/include/class.pagenate.php[27].
Method name "SetupWizard" in class "SetupWizard" is deprecated (@php4_constructors) in file /xxx/include/class.setup.php[31].
Method name "EmailTemplateGroup" in class "EmailTemplateGroup" is deprecated (@php4_constructors) in file /xxx/include/class.template.php[185].
Method name "EmailTemplate" in class "EmailTemplate" is deprecated (@php4_constructors) in file /xxx/include/class.template.php[511].
Method name "gettext_reader" in class "gettext_reader" is deprecated (@php4_constructors) in file /xxx/include/class.translation.php[122].
Method name "FileReader" in class "FileReader" is deprecated (@php4_constructors) in file /xxx/include/class.translation.php[465].
Method name "Upgrader" in class "Upgrader" is deprecated (@php4_constructors) in file /xxx/include/class.upgrader.php[21].
Method name "StreamUpgrader" in class "StreamUpgrader" is deprecated (@php4_constructors) in file /xxx/include/class.upgrader.php[188].
Method name "UserSession" in class "UserSession" is deprecated (@php4_constructors) in file /xxx/include/class.usersession.php[28].
Method name "Validator" in class "Validator" is deprecated (@php4_constructors) in file /xxx/include/class.validator.php[23].
Method name "VariableReplacer" in class "VariableReplacer" is deprecated (@php4_constructors) in file /xxx/include/class.variable.php[30].
Method name "XmlDataParser" in class "XmlDataParser" is deprecated (@php4_constructors) in file /xxx/include/class.xml.php[21].
Method name "Installer" in class "Installer" is deprecated (@php4_constructors) in file /xxx/setup/inc/class.installer.php[24].```

**Comment by infectormp** [comment]
PHP 7 will emit E_DEPRECATED whenever a PHP 4 constructor is defined. When the method name matches the class name, the class is not in a namespace, and a PHP 5 constructor (__construct) is not present then an E_DEPRECATED will be emitted.

**Comment by oneilak** [comment]
hey

I have always problems with other versions of PHP. I am running osTicket only 5.3 and 5.4 ... as soon as I get to a more recent servicekit Change (also 7) I only error 500 (see screens) ...

you have adjusted anything?


ps I use IIS8.5

![unbenannt](https://cloud.githubusercontent.com/assets/13413719/10216349/aa0bf596-6828-11e5-97b1-ae8db9e1d5bf.png)
![unbenannt2](https://cloud.githubusercontent.com/assets/13413719/10216348/aa084a7c-6828-11e5-98da-ed8a242336cb.png)

**Comment by oneilak** [comment]
The Solution for php 5.6

You need to install the: Visual C++ Redistributable for Visual Studio 2012 Update 4  32-bit version.  and it should be noted that even if your operating system is a 64-bit operating system, you must install the 32-bit version  as PHP does not run in 64 bit.

 A download link is here: http://www.microsoft.com/en-us/download/details.aspx?id=30679

**Comment by ntozier** [comment]
@oneilak sadly it took me about a week to figure that little gem out.  :)

**Comment by oneilak** [comment]
my testserver displayed a withe page with php 7 ...

@greezybacon 

what changes you have made

**Comment by greezybacon** [comment]
> @oneilak sadly it took me about a week to figure that little gem out. :)

One could definitely get a Linux VM up and running in less than a week! Does anyone use the Windows Platform Installer? That's what I've used and recommended for Windows and it usually works very well.

**Comment by oneilak** [comment]
my WPI has not a phpv7 install

**Comment by ntozier** [comment]
WPI doesn't have 7 yet.

@greezybacon "Does anyone use the Windows Platform Installer?"
Yes, and it did not install the vc++ redist for vs 2012.  I had to install that separately.

**Comment by oneilak** [comment]
i have manual install the vc++2012 für php 5.6 ... for (the test page) php7 have i install the vc++2015

**Comment by infectormp** [comment]
offtop: PEAR-1.10.0 Add support for PHP 7 and drop support for PHP 4 and 5.0 - 5.3

**Comment by greezybacon** [comment]
I think the current thinking is to require PHP 5.4 for v1.10 and fully upgrade the PEAR internals

**Comment by ntozier** [comment]
As a side note PHP 7.0.0 RC 7 was released 12 Nov 2015 and includes the following statement:
"If no major issues appear within the usual two-week test period, the 7.0.0 general availability (GA) release will be brought out."

**Comment by infectormp** [comment]
i will switch to PHP 7 after release.

**Comment by jjjj12212** [comment]
PHP 7.0 has been fully released today.

**Comment by infectormp** [comment]
PEAR-1.10.0:
* Add support for PHP 7
* Drop support for PHP 4 and 5.0 - 5.3

**Comment by danielc1234** [comment]
Is there anyone out there that has gotten this working yet with PHP 7?

**Comment by danielc1234** [comment]
We got osticket working with PHP 7. Even the API and Fetch, but was a real pain. Still depreciations all over the place, but overall it is working. Also has some issues with the MTA.

Any idea when there maybe an official release that will be for PHP 7? This is too good of a software to not update it so it can stay current. :)

**Comment by war59312** [comment]
Mind detailing how you got it working with PHP 7?

**Comment by danielc1234** [comment]
@war59312 Really it was my buddy that was able to sort through all the errors and make the modifications. If the developers are interested, I can zip up my installation and send them the files as a starting point. It took about 4 hours of troubleshooting.

**Comment by ntozier** [comment]
You'd probably want to submit it as a pull request.

**Comment by LordMike** [comment]
I'll chime in. 
My host has informed me that they will pull php 5.x support in favor of 7.0+ by the end of 2016.

**Comment by ntozier** [comment]
So... you mean this?
https://github.com/osTicket/osTicket-1.8/pull/2828

**Comment by LordMike** [comment]
@ntozier, well - yes and no. From a users point of view (mine), it needs to be released too - in due time. I'm just chiming in saying that webhosts will actually pull support for older PHP versions - and therefore, over time, Osticket needs to support 7.0+ to keep staying a preferred choice :)

Althought I'm sure it'll all work out in the end. :)

**Comment by ArthurBorsboom** [comment]
Arch Linux has updated their PHP version from v5 to v7.
osTicket is the only webapp currently blocking the upgrade.

+1 for making the 1.9.x version PHP7 compatible.
+1 for all the great work on osTicket

**Comment by Exordian** [comment]
+1 PHP 5.4 is EOL, PHP 5.5 will be EOL this year

**Comment by greezybacon** [comment]
This is now fixed in the `develop` branch. Thanks for the posting

**Comment by ArthurBorsboom** [comment]
That is good news.
Thanks for your work.

Will the PHP 7 support also land in 1.9.x or only in 1.10.x ?

**Comment by ntozier** [comment]
I believe that it will land in a 1.9.13 maintenance patch.

**Comment by ArthurBorsboom** [comment]
If that happens, that would be great.
Thanks again.

**Comment by greezybacon** [comment]
PHP7 is only supported for the `develop` branch, v1.10

**Comment by ArthurBorsboom** [comment]
That is a shame, but thanks for the clarity.

**Comment by danielc1234** [comment]
@greezybacon So you are saying that the develop version is working fine with php7? I have modified our 1.8 to work with PHP7, but would like to get up to speed on the latest version. How long do you feel it will take to get the 1.10 branch stable?

**Comment by ntozier** [comment]
@danielc1234 
Q: How long do you feel it will take to get the 1.10 branch stable?
A: The devs will not and do not answer this type of question.

**Comment by danielc1234** [comment]
@ntozier Okay, didn't know that. 

Can I ask if you are working with the develop branch with PHP7? And if so, have you had any issues?

**Comment by ntozier** [comment]
Sorry but I am not running php7 on either of my production sites or testing sites.

**Comment by skliarie** [comment]
Installed version 1.10 and it is working properly under php7.0 (ubuntu 16.04).
