### ISSUE TITLE
1.9.12 - Office 365 Login fails php 5.6.x

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket#2604]
I am having trouble getting osticket to log in to an office 365 account running on php 5.6+. I am able to get it to work when running php 5.5.x. I believe it has something to do with the SSL/TLS improvements in 5.6.x.

With php 5.5.28 it works fine.
with php 5.6.14 I get `SMTP: STARTTLS failed (code: 220, response: 2.0.0 SMTP server ready)`

**Comment by bobbeims** [comment]
same issue here ... is this slated to be fixed in 1.10?

**Comment by ntozier** [comment]
Other threads similar to this indicate that the 'fix' is to use a different version of PHP.  There are a number of threads here indicating PHP7 compatibility for 1.10.x.  So my guess would be the easy fix  choice would be to run PHP 5.4, 5.5, or 7.

**Comment by jdelhome3578** [comment]
Fixed with commit 4f68aeb
