### ISSUE TITLE
Future request: accept email only from registered organization

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket#2605]
Currently osTicket have option to allow email from registered or all users `Accept email from unknown Users`. I think will be better add ability to `Аccept email only from registered organization`. I think this will be very useful.
In this situation we not need register all user from organization, need only register organization.

How this will be work:
- If `Main Domain` set in `Organization form\Setting` osTicket will accept email from any address in this domain. 
- If both option `Accept email from unknown Users` and `Аccept mail only from registered organization`  enabled, osTicket will be accept email only from registered users from registered organization

**Comment by greezybacon** [comment]
It already works that way. Or is supposed to at least.

**Comment by infectormp** [comment]
Not work that way. We use ```Accept email from unknown Users``` and have set domain names for organization in directory but osTicket accept email from any domain.
