### ISSUE TITLE
v. 1.9.12 - Knowledgebase attach file on create FAQ get lost

### ISSUE THREAD

**Issue by Hannibal226** [osTicket/osTicket#2606]
Hey,

like written above attachments get lost, when opening a new FAQ and u save it.
Afterwards u can edit and add it fine again.

Problem was recognized on 1.9.7 (maybe already earlier) and still exists on 1.9.12.

CHEERS!

**Comment by ntozier** [comment]
Isn't there already an issue report for this?
/goes searching

**Comment by infectormp** [comment]
https://github.com/osTicket/osTicket-1.8/issues/1985#issuecomment-94814731

**Comment by Hannibal226** [comment]
Haha ok, so seems like @greezybacon himself missed this or thought it's done. xD
Sorry then ;)

**Comment by PacCharles** [comment]
I seem to be having the same issue as Hannibal226.
Upon first creating a new Knowledgebase FAQ, whatever I type is saved. If I have added an attachment as part of creating the new article however, the attachment is not saved to the newly created KB article.  I can then open my just-created article, add my attachment, and the attachment will still be there after I save the article a second time.

This issue manifests in Firefox 42, Chrome 46, and IE 11

**Comment by coffeverton** [comment]
I had this problem too.
Solved it by editing the file include/class.faq.php, in the method "add".

Just add the code below after the line 239:
$faq->attachments->upload($vars['files']);

By the way, i don't think that the $_FILES array is populated at all, so the lines 237 and 238 may be useless.

**Comment by nobe-vsv** [comment]
Hello togehter,

i´ve excatly the same issue with the stable version v1.10. After edit the faq and save the attachment is missing. I have to reedit the faq and upload the attachment again + save again. My Server settings are:
osTicket-Version 	v1.10 (901e5ea) — Aktuell
Server-Software 	Apache
MySQL-Version 	5.5.52
PHP-Version 	5.6.30

What i have to do to fix the issue?

**Comment by liutongofchina** [comment]
@nobe-vsv , I added `$_SESSION[':uploadedFiles'][$a->file_id] = 1;`
in include/class.forms.php.
And it resolved this issue.
I used the same osTicket version.

```
function render($options) {
        $config = $this->field->getConfiguration();
        $name = $this->field->getFormName();
        $id = substr(md5(spl_object_hash($this)), 10);
        $attachments = $this->field->getFiles();
        $mimetypes = array_filter($config['__mimetypes'],
            function($t) { return strpos($t, '/') !== false; }
        );
        $maxfilesize = ($config['size'] ?: 1048576) / 1048576;
        $files = $F = array();
        $new = array_fill_keys($this->field->getClean(), 1);
        foreach ($attachments as $a) {
            $F[] = $a->file;
            $_SESSION[':uploadedFiles'][$a->file_id] = 1;
            unset($new[$a->file_id]);
        }
```
