### ISSUE TITLE
1.10 PHP Error on user lookup

### ISSUE THREAD

**Issue by kest874** [osTicket/osTicket#2610]
I'm getting:  PHP Fatal error:  Call to undefined method QuerySet::chain() in /var/www/ost/include/ajax.users.php on line 49, referer: http://ost/scp/tickets.php?a=open

when I try to use the userlookup:

![image](https://cloud.githubusercontent.com/assets/12860950/10230035/bc5dce82-6840-11e5-91ae-2353dc334ad1.png)

This is from the tip.  Any idea why?

**Comment by ntozier** [comment]
version of osTicket?  Because 1.10 hasn't been released yet so...

**Comment by kest874** [comment]
Sorry, develop-next with all commits through 934cde3:

![image](https://cloud.githubusercontent.com/assets/12860950/10230971/cc9067d8-6845-11e5-9558-5ef3f581eb8d.png)

This is a green install
