### ISSUE TITLE
osTicket 1.10 RC2 - DB Error #1054 deleting departments

### ISSUE THREAD

**Issue by yatbio** [osTicket/osTicket#2611]
Hello,

Setup a demo area for a fresh installation of 1.10 RC2.  Doing some "cleanup"  of default settings I went into Agents > Departments and deleted 2/3 of the default listed departments.  Once i selected the two departments I didn't need and selected "Delete" I received a DB error alert via email.

DB Error # 1054

[UPDATE ost_filter SET dept_id=0 WHERE dept_id=3] Unknown column 'dept_id' in 'where clause'

 ---- Backtrace ----
 #0 (root)/include/mysqli.php(183): osTicket->logDBError('DB Error #1054',  '[UPDATE ost_fil...')
 #1 (root)/include/class.dept.php(370): db_query('UPDATE ost_filt...')
 #2 (root)/scp/departments.php(101): Dept->delete()
 #3 {main}

**Comment by PartieHonteuse** [comment]
Update:

I created a new department and deleted it.  Same error.  Seems like this happens for all departments.  Thought maybe it would just be the default loaded departments.

 DB Error #1054

[UPDATE ost_filter SET dept_id=0 WHERE dept_id=4] Unknown column 'dept_id' in 'where clause'

 ---- Backtrace ----
 #0 (root)/include/mysqli.php(183): osTicket->logDBError('DB Error #1054',  '[UPDATE ost_fil...')
 #1 (root)/include/class.dept.php(370): db_query('UPDATE ost_filt...')
 #2 (root)/scp/departments.php(101): Dept->delete()
 #3 {main}

**Comment by greezybacon** [comment]
@PartieHonteuse are you sure about the version? It looks like that code is from rc1 and was fixed in rc2.

**Comment by PartieHonteuse** [comment]
Hi Jared,

I'm pretty sure - at least according to the Dashboard - Information tab I
am (See first screen cap).
[image: Inline image 1]

I'm also seeing some errors related to "DEPT_ID" from the SQL query when
trying to delete some of the default emails:

[SELECT count(dept_id) FROM ost_department dept WHERE email_id IN (2) OR
autoresp_email_id IN (2)] Unknown column 'dept_id' in 'field list'

---- Backtrace ----
#0 (root)/include/mysqli.php(183): osTicket->logDBError('DB Error #1054',
'[SELECT count(d...')
#1 (root)/scp/emails.php(57): db_query('SELECT count(de...')
#2 {main}
