### ISSUE TITLE
osTicket 1.10 RC2 Custom form field duplication

### ISSUE THREAD

**Issue by nfebuary** [osTicket/osTicket#2613]
Location: Admin Panel>Manage>Forms>Add New Custom Form OR edit any existing form.

When adding a form field: If there is an error when saving, the field clones it's self. The top form field of the two is a fake form field thus adding any information in that field to correct the error will not solve the issue. However, if the bottom form field error is corrected and then saved, the clone is removed and the field works fine.

Screenshot of the cloned field. (it is not really a copy it appears to not have any functionality.) I purposely did not add the variable so it would trip the error. 
![screen shot 2015-10-02 at 9 21 25 am](https://cloud.githubusercontent.com/assets/8247872/10249528/720fec7e-68eb-11e5-87cf-29edbbce01e2.png)

**Comment by ntozier** [comment]
So maybe I'm off base here... but what about this?

![mockup](https://cloud.githubusercontent.com/assets/1315768/10250168/49cfd790-68f7-11e5-83be-e48f7e8e6760.png)

**Comment by nfebuary** [comment]
Visually that is much better for the error message and the highlighted fields. BUT the functional issue I'm having is if you save 1 field and say for example: You forget to add a variable that is required the form field clones itself so instead of 1 form field line you now have 2 form field lines of the same. 

Before saving:
![screen shot 2015-10-02 at 10 32 41 am](https://cloud.githubusercontent.com/assets/8247872/10250545/0528dd22-68f1-11e5-979d-bf5981df94fb.png)

After saving:
![screen shot 2015-10-02 at 10 32 59 am](https://cloud.githubusercontent.com/assets/8247872/10250549/0ee5c1f4-68f1-11e5-9ae3-d9249abe47a2.png)

I should have added the before and after in my original post.

**Comment by ntozier** [comment]
Oh wow!  I completely missed that!

**Comment by nfebuary** [comment]
I still liked the idea of reducing the size of the error message and highlighting the box in red.

**Comment by ntozier** [comment]
Right on! :)
