### ISSUE TITLE
Customer has multiple email addresses

### ISSUE THREAD

**Issue by itulga** [osTicket/osTicket#2621]
Hi,

Our customers has multiple email addresses. How to add second email address?

Thanks

**Comment by jamesangi** [comment]
Admin panel -> manage -> forms -> contact information

Add whatever extra contact fields you would like.

**Comment by gtulga** [comment]
I can add extra contact fields. But system can use it? for example:

I receive ticket from bob@company.com and bob@gmail.com, so these tickets will be Bob's tickets. how to configure it?

Thanks

**Comment by jamesangi** [comment]
Oh, I see what you mean.  No, I don't believe there is any way to do that short of modifying the code.  It probably wouldn't be that involved if you have some coding experience.

**Comment by dnamkaa** [comment]
i have installed osTcket 1.9 . I need to chip in source code  so that  will be able to receive ticket from different mails

**Comment by ntozier** [comment]
Simply add an entry in the ost_user_emails table.

id | user_id | address
0,24,faux@fake.com
0,24, fake@faux.com

where 0 represents the next free id#.
24 represents the user_id#.
and address is the user's additional email address.

osTicket will not accept email from that person's address that you accept.  However when they open a ticket it will always default to the original email (the first one that osTicket finds when opening the ticket).  This also may result in some warnings in the log.  We do this here for our users and haven't had any problems.

**Comment by f1mishutka** [comment]
+

We need an ability to bind several email addresses to one person too.
Thank you!

**Comment by bwl21** [comment]
Amazing, that this is request ist still open ...
