### ISSUE TITLE
Version 1.10 Redactor.deleteDraft is not a function

### ISSUE THREAD

**Issue by JamesPCS** [osTicket/osTicket#2624]
When I create a new ticket and hit cancel it just sits there. When I look at the output in the cosole with google dev tools I see that it's looking for redactor.deleteDraft and it can't find it.

**Comment by JamesPCS** [comment]
Okay so I changed redactor.deleteDraft to redactor.draft.deleteDraft and that seems to work, at least it doesn't give me an error and now it redirects me back to tickets. However, now I'm trying to fix the reset button . When I click on it I get the error:

Uncaught Error: No such method "deleteDraft" for Redactor

**Comment by mauvalente** [comment]
I have the same error here

**Comment by JediKev** [comment]
I know this is old but the cancel button issue should be fixed with pull request #2924 and the reset button issue should be fixed with pull request #3898.

**Comment by abdoevs** [comment]
change `redactor.deleteDraft();` to `redactor.draft.deleteDraft();`
