### ISSUE TITLE
Advanced search with custom choices field not working (1.10rc2)

### ISSUE THREAD

**Issue by jamesangi** [osTicket/osTicket#2625]
I have a custom form with a field of type "Choices."  I cannot use Advanced Search on this field.  For example, I have two closed tickets with "Bill" selected in this field but my search returns no results.

Here are some screenshots:
![billing 1](https://cloud.githubusercontent.com/assets/14003656/10310995/c893fde0-6c12-11e5-9b41-2b8b4136ad85.PNG)
![billing 2](https://cloud.githubusercontent.com/assets/14003656/10310998/cc8d9e56-6c12-11e5-91a1-8d1f0259d97b.PNG)
![billing 3](https://cloud.githubusercontent.com/assets/14003656/10311000/cd91e0d2-6c12-11e5-999d-d0c2abf66119.PNG)

**Comment by jamesangi** [comment]
No one else seeing this?  I tried a clean install and it still happens, nothing interesting in the logs.  I've noticed a couple more advanced search oddities as well:
1) When loading a saved search it "shakes" the window back and forth like there is an error, except there is none.
2) Sometimes after clicking "search" you then have to click on the "search" tab to get the results to display.

**Comment by Animeonmymind** [comment]
Same situation here, custom field searches yield no results.

**Comment by greezybacon** [comment]
I was able to duplicate this yesterday. I think the problem is that the search system builds a query with
```sql
<field> IN ('BILL')
```

however, the storage model for the Choices field looks like `{"Bill": "Bill"}`, because it stores the key and the value. In the event the field is changed to reflect different keys/values, the previously set value can be retained. Therefore, the SQL query needs to be built like
```
<field> LIKE '%"Bill"%'
```

**Comment by mbaghert** [comment]
custom field search not result

**Comment by ntozier** [comment]
@mbaghert Huh?

**Comment by bpalme** [comment]
I would appreciate any hints on how to patch this until a real fix is developed.  If you can point me in the right direction, I might be able to come up with something.

**Comment by ntozier** [comment]
@bpalme on Oct 22nd Jared posted what he thinks the problem is.  I would think that would be the answer to your question as to where to start.

**Comment by bpalme** [comment]
Thanks.  I guess I was hoping he would throw me a little more meaty bone.  I didn't see any good way for a quick fix from class.search.  So I'm assuming I have to get into class.orm?  There is a lot there to dive into...

**Comment by bpalme** [comment]
Well this is as far as I've gotten.  In class.dynamic_forms, I've changed getSearchQ() to return a different Q:
`return new Q(array("{$name}__contains" => array_keys($value)));
            
//return new Q(array("{$name}__intersect" => array_keys($value)));`
(around line 1822)
This does change the query operator to LIKE  for the choice field as greazybacon suggests.  However, when the SQL is executed the parameter for that value is missing in the params array.  All the other values are there, but that one is missing.  I haven't been able to track down why that is the case.  I thought I'd add that in case someone wants to pick it up from here.  I have to get back to my real work. ; )

**Comment by jakester2** [comment]
I am seeing the same problem.

I am able to fix this by adding a key to the value under the choices menu. For example, if one of my choices in the menu is "Choice 01", I change that to "choice_01:Choice 01".

Then I go into the database and change all the references to the key instead of the value.

Once the ticket_cdata table recompiled I was able to search with the respective changes ive made.

Its kind of a hack, but its all I have...

**Comment by GoodbyeWorld** [comment]
I represent a small not-for-profit that uses osTicket, and we're affected by this considerably.   Would anyone be interested in taking this bug on?  I wish I had money to offer as a bounty, but maybe someone would be willing to tackle this bug knowing it would really help us to help local families in need.

**Comment by esamo** [comment]
I've got an issue that choice field is not saved properly in ticket__cdate table, it saves always as value '0', not depending on actual user's choice. When table ticket__cdata gets dropped, the column is recreated with the correct value, but any new ticket has the same problem again.

**Comment by mfelber** [comment]
@esamo The values from the __cdata tables are coming from other tables. They are materialized views, not normal tables. They are collecting data from multiple other osticket tables. And therefore they are dropped an recreated.

I guess you are changing values directly via the database or with a modification. Then you have to find the origin table for this value and manipulate the data there.

**Comment by esamo** [comment]
I'm not modifying data. All the custom fields are saved corretly to the cdata but not the choice field.

**Comment by mfelber** [comment]
@esamo What PHP version do you use?

**Comment by esamo** [comment]
I've pasted the whole config above

**Comment by mfelber** [comment]
Opps, did not see that ;-) Hmm, I guess this should not happen and could be a bug. 
Have you checked the error log of your webserver or the osticket system log?

**Comment by mfelber** [comment]
Nevertheless I would upgrade to PHP 5.6 and see if this makes a difference. 

PHP 5.5. has reached last year its end of life. If this does not help and you have no error in the logs I would suggest that you create a new issue report for that because this seems not to be the same issue..

**Comment by JediKev** [comment]
I have created this pull request that should solve this issue: #4124

**Note:** If you're using a Choices field, every choice HAS to have a key associated with them (mentioned in the helptext).
<img width="320" alt="screen shot 2017-12-14 at 13 38 51" src="https://user-images.githubusercontent.com/11823401/34010987-25d9ce98-e0d4-11e7-8e8b-2bb8dd9bb8d9.png">
