### ISSUE TITLE
v1.10-rc.2 Adding new task to ticket

### ISSUE THREAD

**Issue by 1024jon** [osTicket/osTicket#2627]
Fresh install just for testing.  After creating a ticket, when I go to add a task to that ticket, the page loads a box and wont load any further.  I have tried on both Chrome and Safari.  Normal task creation works correctly.

![screenshot 2015-10-06 11 15 40](https://cloud.githubusercontent.com/assets/8061767/10316247/932d3c26-6c1b-11e5-929a-445b64e6c9f0.png)

**Comment by ntozier** [comment]
server details?
This looks like an AJAX issue to me.

**Comment by 1024jon** [comment]
OSX 10.10 running AMPPS 4.6.3 with PHP 5.6.9

**Comment by 1024jon** [comment]
Just found this in logs.  Call to undefined function _() in /Applications/AMPPS/www/testticket/include/ajax.tickets.php on line 1062, referer: http://****/testticket/scp/tickets.php?id=3

**Comment by goobersmooch** [comment]
I had the same exact problem as described above except I am running osticket version v1.10-rc.2-135-g1aaa313. I was able to fix it by changing line 1052 of /include/ajax.tickets.php from _('Add New Task') to __('Add New Task'). The code is just missing an extra underscore.

So @1024jon if you change line 1062 from _('Add New Task') to __('Add New Task') your problem should be resolved.

**Comment by groovybluedog** [comment]
In my version, the fix you proposed has already been implemented, however, the *exact* same issue is occurring for me even tough the file already has that extra underscore. Exactly the same thing as the screenshot above.

**Comment by ntozier** [comment]
@groovybluedog and what version would that be?

**Comment by groovybluedog** [comment]
v1.10-rc.2

**Comment by dali-dbr** [comment]
I needed to do the opposite. I removed the underscore and now it works :)

**Comment by webgeri** [comment]
hi,
i have also this issue in the v1.10 stable. the solutions above don't solve my problem. the button "Add New Task" won't apper!

german language is installed
in admin-panel information i get one warning:
cgi.fix_pathinfo should be 1...
but in modern php that is not necessary

i use for testing xampp with
php 7.0.13 and 5.5.5-10.1.19-MariaDB 

thx
geri
