### ISSUE TITLE
Future request: quick jump to ticket 

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket#2629]
Would be nice add field where you can put ticket number and jump directly to ticket. This field must be accessible from any place of osTicket so you can jump directly to ticket from any place.

**Comment by ntozier** [comment]
Can't the search field already be utilized like that?

**Comment by infectormp** [comment]
in my opinion no

**Comment by infectormp** [comment]
when you view ticket you can't jump to other ticket with search field.

**Comment by nfebuary** [comment]
Your suggesting leaving the search field at the top of the Ticket view to search other tickets and a way to toggle between the two or more open tickets? I was toying with the idea of a split screen when searching for any information while in ticket view, but with a 960 width it would not be feasible without a UI overhaul. I can see where there would be a need to keep the search even on the ticket page though.

**Comment by infectormp** [comment]
Yes need leaving the search field at the top of the Ticket view and do not display search result is found only 1 ticket, immediate open ticket without user action. I call this - jump directly to ticket.

btw in my installation i change with to 1180 because work with 960 not comfortable :)
