### ISSUE TITLE
Future request: expand them width

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket#2636]
Current them width (960px) not very comfortable for work. I want suggest change them width to 1366px. This will more comfortable and add some extra space to UI that can be used for future improvements.

**Comment by infectormp** [comment]
Currently i modify osTicket UI to 1180px because use 960px at 24 inch display not comfortable.

**Comment by NMonst4** [comment]
i have made some scp style changes. https://github.com/NMonst4/osTicket-1.8/blob/develop/scp/css/scp.css
