### ISSUE TITLE
No Custom Form when ticket created via email

### ISSUE THREAD

**Issue by bcowman** [osTicket/osTicket#2637]
1.10 RC1 - I have a Custom Form associated with a Help Topic.  If I create a ticket using the New Ticket link then the Custom Form fields are displayed.  However if I create a ticket by fetching an email, the Help Topic is correct but the Custom Form is never attached to the ticket.  I have to manually add the Custom Form to email created tickets.

**Comment by ntozier** [comment]
You should always upgrade to the latest version [ie in this case rc2] and re-test.

**Comment by bcowman** [comment]
Typo.  I'm already using rc2.

**Comment by BassemN** [comment]
The same issue with 1.9.12
