### ISSUE TITLE
OST 1.10 - Task as a ticket

### ISSUE THREAD

**Issue by PPCM** [osTicket/osTicket#2640]
Task object is a great idea in OST 1.10 RC2
But an agent must go throw "tickets" and "tasks" pages to see what he has to do.
It will be really useful if a task can be considered has a ticket flagged as a task

In that way, an agent needs only to focus on one page "tickets" and answers to requests (tickets and tasks)
The "tasks" page can still exists, but it will be a filter that shows only tickets flagged as tasks

What do you think?

**Comment by PPCM** [comment]
Something else: when an agent create a task for another service, it can only watch progress on that task only if he can access to the destination service...

**Comment by ntozier** [comment]
I haven't the foggiest idea what you mean by "when an agent create a task for another service, it can only watch progress on that task only if he can access to the destination service..."

another service?  destination service?

**Comment by PPCM** [comment]
Exact the destination service.
For example:
The service A (customers relation service for example) receive a ticket with some problems.
He can create tasks for a service B (developpers for example) and other tasks for service C ().
The agent of service A can't see any evolution of tasks of its tickets, it can only see that the tasks are closed...

**Comment by ntozier** [comment]
service is not a osTicket term.  You appear to mean Department.  So...
service A = Department A
service B = Department B
service C = Department C

What you are describing is the designed behavior.  Agents only have access to the departments that they have access to.  I believe that you would want utilize Teams to change this.

**Comment by PPCM** [comment]
Sorry for the bad term, but in french translation, department is called service

I don't want that an agent access to all tickets of another departement, but only to tasks associated with the ticket he can access...
