### ISSUE TITLE
devnext: fatal @ getDbTimezone

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket#2642]
Get `Fatal error: Call to a member function getDbTimezone() on null in /xxx/include/class.misc.php on line 99` @ install step with last devnext branch

mariadb 10.1.7

**Comment by infectormp** [comment]
SELECT @@global.system_time_zone;
+---------------------------+
| @@global.system_time_zone |
+---------------------------+
| MSK                       |
+---------------------------+

**Comment by AlexYoung28** [comment]
if this helps

CentOS 7
PHP 5.4.16 (cli) (built: Jun 23 2015 21:17:27)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies

I'm getting same issue with a mariadb as well.

**Comment by infectormp** [comment]
i comment this lines in  function dbtime($var=null) in class.misc.php
```if (!isset($dbtz)) {
            $dbtz = new DateTimeZone($cfg->getDbTimezone());
        }```
```
// UTC to db time
        $D = DateTime::createFromFormat('U', $time);
        return $time + $dbtz->getOffset($D); ```

and then finish install step

**Comment by AlexYoung28** [comment]
Yep that worked for me as well.

**Comment by greezybacon** [comment]
Yeah, I've also noticed that the installer crashes in the current `develop-next` branch

**Comment by c0nfused** [comment]
Lines 16-18 of `setup/install.php` are

    require('setup.inc.php');
    
    require_once INC_DIR.'class.installer.php';

`class.installer.php` is what defines the `$cfg` variable, but `setup.inc.php` is requiring (including) files that assume `$cfg` is already defined. Thus the error indicating `$cfg` is null, and not the expected variable.

Simply reversing the lines doesn't work because `setup.inc.php` is what defines `INC_DIR` which is used in the second line..

**Comment by codekmarv** [comment]
Same here, @c0nfused that fix you have it on your fork right? 
Regards,

Marvin M

**Comment by kensel** [comment]
c0nfused's change works and my installation completed successfully.

**Comment by goobersmooch** [comment]
c0nfused's fix worked for me as well.

**Comment by LucasBurg** [comment]
Same here
