### ISSUE TITLE
Export tickets Fatal

### ISSUE THREAD

**Issue by basteroid** [osTicket/osTicket#2645]
Hi!
osTicket (v1.10-rc.2), ubuntu 14.04.
When you on the page .../scp/index.php click Export when will fatal error.
Ubuntu log:
[:error] [pid 28940] [client xxxx:51513] PHP Fatal error:  Export::dumpTickets(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition &quot;QuerySet&quot; of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide a __autoload() function to load the class definition  in /var/www/html/upload/include/class.export.php on line 60

[:error] [pid 30667] [client xxxx:51479] PHP Warning:  Class __PHP_Incomplete_Class has no unserializer in Unknown on line 0, referer: .../scp/tickets.php?status=closed

**Comment by rayfoss** [comment]
We're unable to reproduce this, If this is still occurring please submit a new ticket. The issue template will give us information that may help us fix this if it's still occurring.
