### ISSUE TITLE
1.9.12 many error logging

### ISSUE THREAD

**Issue by cervedgroup** [osTicket/osTicket#2648]
Hi, we have many errors in system log 
DB Error #1050
[CREATE TABLE `ost_ticket__cdata` (PRIMARY KEY (ticket_id)) AS SELECT entry.`object_id` as `ticket_id`, MAX(IF(field.id='5', coalesce(ans.value_id, ans.value), NULL)) as `subject`, MAX(CASE WHEN field.id='7' THEN REPLACE(REPLACE(REPLACE(REPLACE(coalesce(ans.value_id, ans.value), '{', ''), '}', ''), '"', ''), ':', ', ') ELSE NULL END) as `priority` FROM ost_form_entry entry JOIN ost_form_entry_values ans ON ans.entry_id = entry.id JOIN ost_form_field field ON field.id=ans.field_id WHERE entry.object_type='T' GROUP BY entry.object_id] Table 'ost_ticket__cdata' already exists

 ---- Backtrace ----
 #0 C:\Osticket\upload\include\mysqli.php(177): osTicket->logDBError('DB Error #1050', '[CREATE TABLE `...')
 #1 C:\Osticket\upload\include\class.dynamic_forms.php(330): db_query('CREATE TABLE`o...')
 #2 C:\Osticket\upload\include\class.dynamic_forms.php(315): TicketForm::buildDynamicDataView()
 #3 C:\Osticket\upload\include\staff\tickets.inc.php(270): TicketForm::ensureDynamicDataView()
 #4 C:\Osticket\upload\scp\tickets.php(506): require_once('C:\Osticket\upl...')
 #5 C:\Osticket\upload\scp\index.php(17): require('C:\Osticket\upl...')
 #6 {main}

DB Error #1146
[SELECT ticket.ticket_id, tlock.lock_id, ticket.`number`, ticket.dept_id, ticket.staff_id, ticket.team_id , user.name , email.address as email, dept.dept_name, status.state , status.name as status, ticket.source, ticket.isoverdue, ticket.isanswered, ticket.created , IF(ticket.duedate IS NULL, IF(sla.id IS NULL, NULL, DATE_ADD(ticket.created, INTERVAL sla.grace_period HOUR)), ticket.duedate) as duedate , CAST(GREATEST(IFNULL(ticket.lastmessage, 0), IFNULL(ticket.closed, 0), IFNULL(ticket.reopened, 0), ticket.created) as datetime) as effective_date , ticket.created as ticket_created, CONCAT_WS(" ", staff.firstname, staff.lastname) as staff, team.name as team , IF(staff.staff_id IS NULL, team.name, CONCAT_WS(" ", staff.lastname, staff.firstname)) as assigned , IF(ptopic.topic_pid IS NULL, topic.topic, CONCAT_WS(" / ", ptopic.topic, topic.topic)) as helptopic , cdata.priority as priority_id, cdata.subject, pri.priority_desc, pri.priority_color FROM ost_ticket ticket LEFT JOIN ost_ticket_status status ON (status.id = ticket.status_id) LEFT JOIN ost_user user ON user.id = ticket.user_id LEFT JOIN ost_user_email email ON user.id = email.user_id LEFT JOIN ost_department dept ON ticket.dept_id=dept.dept_id LEFT JOIN ost_ticket_lock tlock ON (ticket.ticket_id=tlock.ticket_id AND tlock.expire>NOW() AND tlock.staff_id!=61) LEFT JOIN ost_staff staff ON (ticket.staff_id=staff.staff_id) LEFT JOIN ost_team team ON (ticket.team_id=team.team_id) LEFT JOIN ost_sla sla ON (ticket.sla_id=sla.id AND sla.isactive=1) LEFT JOIN ost_help_topic topic ON (ticket.topic_id=topic.topic_id) LEFT JOIN ost_help_topic ptopic ON (ptopic.topic_id=topic.topic_pid) LEFT JOIN ost_ticket__cdata cdata ON (cdata.ticket_id = ticket.ticket_id) LEFT JOIN ost_ticket_priority pri ON (pri.priority_id = cdata.priority) WHERE ( ( ticket.staff_id=61 AND status.state="open") OR ticket.dept_id IN (1, 2, 3, 4, 6, 7, 8) ) AND status.state IN ( 'open' ) AND ticket.staff_id=61 ORDER BY pri.priority_urgency ASC, effective_date DESC, ticket.created DESC LIMIT 0, 50] Table 'osticket.ost_ticket__cdata' doesn't exist

 ---- Backtrace ----
 #0 C:\Osticket\upload\include\mysqli.php(177): osTicket->logDBError('DB Error #1146', '[SELECT ticket....')
 #1 C:\Osticket\upload\include\staff\tickets.inc.php(276): db_query('SELECT ticket.t...')
 #2 C:\Osticket\upload\scp\tickets.php(506): require_once('C:\Osticket\upl...')
 #3 {main}

and also many of this ;
Token CSRF not valid [89126cfedb0c4d10b0f3ce19add6479814d2e37d] on https://xxxxx.com:443/Osticket/scp/login.php

**Comment by mfelber** [comment]
I think at least the db error 1146 has something to do with the rebuilding of the materialized view, see this issue https://github.com/osTicket/osTicket-1.8/issues/1545. Maybe the db error 1050 has also to do with it 1050. Seems not be really a serious problem.

The CSRF errrors are related to a security feature of osticket. You will find multiple issues related to this on github (for example this https://github.com/osTicket/osTicket-1.8/issues/2234) or in the forum (like this http://osticket.com/forum/discussion/77289/invalid-csrf-token-osticket-1-8-1-2). Sometimes it is the hosting environment, sometimes it is the browser cache..

**Comment by cervedgroup** [comment]
thank you

**Comment by mfelber** [comment]
Maybe this forum entry is interesting for you (related to the error 1050): http://osticket.com/forum/discussion/86696/db-error-1050#latest

**Comment by scroom** [comment]
@mfelber In my case the DB-user already have all right on the DB (fresh osTicket v1.10 stable). But I'm constantly getting this error.
