### ISSUE TITLE
add collaborators from bekend

### ISSUE THREAD

**Issue by ParmaU** [osTicket/osTicket#2649]
Hello
I'm trying the system osTicket ver 1.10 rc2 I think it is interesting to add the possibility when creating the ticket from the form of adding the ability to insert one or more persons / email to be kept informed of the case

**Comment by ntozier** [comment]
This appears to be a duplicate thread.
Please close this and refer to existing enhancement request: https://github.com/osTicket/osTicket-1.8/issues/771
