### ISSUE TITLE
Enhancement Request: Direct user Links to Help Topics forms

### ISSUE THREAD

**Issue by ehk20** [osTicket/osTicket#2652]
It would be great if we could create links directly to help topics like:

/open.php?ht=2

This has been discussed previously in the forums:
http://osticket.com/forum/discussion/79163/direct-link-to-help-topics-when-opening-the-tickets

For us this would be extremely useful as we are migrating a number of existing forms from other systems into osTicket Help Topics and this way we could swap the existing links to these forms with functional equivalents (rather than expect the user to find the corresponding HT from the lists).

**Comment by jdelhome3578** [comment]
A pull request has already been opened #2633
