### ISSUE TITLE
Add User to Organisation On New Ticket

### ISSUE THREAD

**Issue by AlexYoung28** [osTicket/osTicket#2659]
You got the ability to create a new user when you make a new ticket but can we make it so you either make a new organization or add to an existing one.

**Comment by infectormp** [comment]
If you set domain name (xxx.com) in organization option, new users with this domain will be added to organization automatically

**Comment by jdelhome3578** [comment]
His option would be nice I use the organizations as departments in my organization, so the email setting is not an option.

**Comment by AlexYoung28** [comment]
Have to say didnt know that but it just makes sense for those with enviroments with lot of clients to be honest to add it when a new user is created.

Then when you get the custom fields in the dashboard you can view orgs in that

**Comment by infectormp** [comment]
@AlexYoung28 Next version (1.10) will show organization in ticket view.

**Comment by AlexYoung28** [comment]
Yup i know :)

**Comment by AlexYoung28** [comment]
Any news of this coming in 1.10?

**Comment by ntozier** [comment]
There has never been any official dev comment on this being added to the project... so no.  There is no news about it being added to 1.10 or any other version for that matter.
