### ISSUE TITLE
organization form: Last Updated value not updated if notes added

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket#2660]
Last Updated value not updated if notes added
![lastu](https://cloud.githubusercontent.com/assets/9958813/10577097/de4085ec-7670-11e5-89a7-b7e380e03fc5.png)

![lastu22](https://cloud.githubusercontent.com/assets/9958813/10577142/461f7772-7671-11e5-8203-98c0a39b114a.png)

**Comment by infectormp** [comment]
osTicket 1.9.12

**Comment by greezybacon** [comment]
@protich does adding, editing, or deleting a note constitute "updating" the organization or user?

**Comment by ntozier** [comment]
I personally wouldn't think so... since it's not really changing anything [important].
