### ISSUE TITLE
v1.10-rc.2 (231f11e) Cannot delete Saved Search

### ISSUE THREAD

**Issue by pratikvav** [osTicket/osTicket#2662]
Once we create a Saved Search and say we want to delete one it just do not allow it. It gives a popup saying do you want to Delete and on pressing OK it just does nothing.
![screenshot1](https://cloud.githubusercontent.com/assets/15137365/10598091/56ce3962-7713-11e5-9630-fc721e4bc1ee.jpg)

**Comment by greezybacon** [comment]
If you're using IIS, you need to [enable the DELETE verb](http://stackoverflow.com/a/10616736)

**Comment by pratikvav** [comment]
No we are using CentOS with nginx here

**Comment by greezybacon** [comment]
Sorry, I can't really help you with nginx

**Comment by ntozier** [comment]
CentOS... have you tried disabling SELinux?

**Comment by pratikvav** [comment]
I manged to get it working had to enable the DELETE Verb in nginx. I had it disabled for security reasons. But to get this working had to enable it.
