### ISSUE TITLE
v1.10 version to production use

### ISSUE THREAD

**Issue by Aka4Code** [osTicket/osTicket#2664]
We would like to use 1.10 in production (now we have 1.9.8.1) 
and we do not want to wait for official stable 1.10 release.

What do you recommend:
1. 1.10-rc.2 beta release from https://github.com/osTicket/osTicket-1.8/releases/tag/v1.10-rc.2
2. tip of develop branch https://github.com/osTicket/osTicket-1.8/tree/develop
3. tip of develop-next branch https://github.com/osTicket/osTicket-1.8/tree/develop-next
4. tip of custom-queues branch https://github.com/greezybacon/osTicket-1.8/tree/feature/custom-queues
   ?

Which one of them is more stable with more bugs removed?

**Comment by mfelber** [comment]
My understanding is that the develop branch (2) is for the next 1.9.x. release.

Custom-queues (4) has also nothing to do with 1.10, it's for the next major release after 1.10 (maybe called 1.11). 

1.10-rc2 (1) is behind the tip of the develop-next branch.

 So I guess now option (3) the tip of develop-next will be the best choice for you. 

I also think 1.10-rc3 will come soon, so if you would wait a little bit..

**Comment by Chefkeks** [comment]
> We would like to use 1.10 in production

As far as things haven't changed, it's definitely not recommended to use 1.10 in production yet!

**Comment by Aka4** [comment]
@Chefkeks Good you mention this, because I was suggested by email from osTicket Team dated at 2015-08-20:

![image](https://cloud.githubusercontent.com/assets/11789024/10602846/14e54aa6-771b-11e5-909c-b0ee5650764e.png)

I understand things change since that time :/

**Comment by Chefkeks** [comment]
Oh, must have missed that little sentence in the mail (which is 2 months old) and so maybe I'm not up-to-date and you can use it production or things changed and it's still not recommended to use in production.

Would be great if @protich @greezybacon could shed some light into this discussion here ;)

**Comment by greezybacon** [comment]
SupportSystem.com is running it in production. There are a few edits there which haven't been merged into the osTicket codebase, but I agree, there are too many issues left

**Comment by Aka4** [comment]
@greezybacon So at the moment you do not recommended to use it in production, yes?

**Comment by greezybacon** [comment]
@Aka4 let's not get in a legal debate. When osTicket v1.10 is marked stable, it will be labeled as stable, not as a release candidate. Your opinions of the stability may vary, as your usage of the software may encompass only some features which are currently completely stable in the release candidate. To mark the software stable, to the best of our ability, it should implement every feature, every configuration, and every use case without error, which makes it extremely difficult to call it "stable".

**Comment by philbertphotos** [comment]
I currently using 1.10rc2 in production it works just fine for my needs. I regularly test the develop-next in sandbox they have too many unknowns.

**Comment by Aka4** [comment]
@greezybacon I know I should not ask but.... any chances v1.10 will be released in 2015 year?

**Comment by philbertphotos** [comment]
We can only hope

**Comment by ntozier** [comment]
I expect 1.10 to be released before the end of the year.
[which of course is not an official answer.]

**Comment by Aka4** [comment]
@ntozier But you think that before the end of the year will be released stable final version of 1.10 or rather only RC3?

**Comment by ntozier** [comment]
It's speculation, but I believe that 1.10 will be released between now and early Jan.  I am not a dev so this is not an official answer and purely my opinion.

**Comment by Aka4Code** [comment]
Anything new in this topic? What do you think about actual state of tip of develop-next branch - can we use it in production?

**Comment by ntozier** [comment]
Q: What do you think about actual state of tip of develop-next branch - can we use it in production?
A: That wouldn't be a good idea.

**Comment by philbertphotos** [comment]
Nope not ready they are still pull and testing

**Comment by Exordian** [comment]
updates on a 1.10 release date?

**Comment by GoodbyeWorld** [comment]
@greezybacon Any chance you can comment on when 1.10 will be stable?  Are we close?

**Comment by Ali-Se** [comment]
@greezybacon (Me too) still waiting for stable release, it has been a long time since the rc2 (more than six months)

**Comment by Hannibal226** [comment]
+1

**Comment by balojs** [comment]
+1

**Comment by Aka4Code** [comment]
Is osTicket dead? 
@greezybacon @protich can you confirm or deny?

I don't know what to think - from the last about six months there was not many activity on this project.
Is it related to @greezybacon work on this 'Phlite' project or do you have some financial problems and need paid support?

**Comment by ntozier** [comment]
Off topic much?
Q: Is osTicket dead? 
A: No.

Q: @greezybacon @protich can you confirm or deny?
A: No.

Q: Is it related to @greezybacon work on this 'Phlite' project or do you have some financial problems and need paid support?
A: I do not begin to know how to answer this.

**Comment by Aka4Code** [comment]
I hope this is not true - I was checking osTicket company website http://www.enhancesoft.com/#about and within ABOUT US section there is no more mention about Jared Hancock... do @greezybacon still works at Enhancesoft company and osTicket project? @protich @kmmoreau can you confirm or deny?

I remember that before in that ABOUT US section were three persons - Jared, Peter and Karen, and now there is only Peter and Karen and I can see that you are running software engineer recruitment process - http://enhancesoft.pages.ontraport.net/senior-software

**Comment by philbertphotos** [comment]
All i can say is Wooooow how off the rails some can get ...

**Comment by jackdaih** [comment]
Yes, Some people can be way off the rails. 

Some are simply frustrated with the lack of an official release. After all, the current release candidate is > 6 months old. Understanding this fact, in my humble opinion, their lack of proper articulation does not call for the usual canned response. Perhaps an official post with details behind the current development / testing challenges would help quell those whom are looking for answers.

**Comment by protich** [comment]
I think my public activity  as well as project's can speak on "undeadness". Admittedly, development pace has slowed down considerably due to various factors. A new release is forthcoming.

Any volunteers to work full-time _for free_ to help us push a new releases every week?

Here is an idea for a reality show (while you consider my generous offer above) -- a behind the scene all-access look at what it takes to manage an open source project, all for free and for the good of humanity.  The scene on freecoders vs. freeloaders will be awesome to see.

Now back to the offer... any takers or nah? 

On a serious note, I do get the concerns expressed and perhaps lack of communication on my part is to blame. More on that later... 

And yes,  __we're [hiring] (http://enhancesoft.com/careers)__?

**Comment by simonnzg** [comment]
Looks like I'm a little to old to work for you, based on the staff photos on the "Hiring" pages. ;-)
Wrong continent, too. However, I'm running RC2 in a slightly quirky production environment and have plenty of testing and documentation experience I can lend you in my spare time if you need it. I'm sure there are plenty of others who appreciate what you're doing, too.

**Comment by balojs** [comment]
Thanks! @protich and @greezybacon  your work it's awesome

**Comment by Aka4Code** [comment]
@protich well, then it would be fine if you only could say approximate time when you plan to release new version (would be enough to say something like next 3 months, next year, anything).

Lack of communication from your side is really killing, don't know what to think :/

When I look at public activity of @greezybacon there is no much comparing to March 2015:

![image](https://cloud.githubusercontent.com/assets/11789024/13699857/73a26b8c-e77d-11e5-9e61-2463a13bf90d.png)

Beside volunteers, do you need any donations to speed up project?

**Comment by kest874** [comment]
I believe pushing them for a release is the wrong thing to do especially when your not paying for the product. I've been using 1.10 in production for the last several months.  Sure there a few issues here and there but it is very workable.  I commend the osTicket team for their efforts this far.

**Comment by simonnzg** [comment]
+1
However, please do offer them money!

**Comment by protich** [comment]
@Aka4Code - No one works for you or owes you anything (sorry to be rude) and no we don't need your donation.

**Comment by philbertphotos** [comment]
Perfectly said...

**Comment by philbertphotos** [comment]
Had to be said...

**Comment by ntozier** [comment]
@Aka4Code it will be released when the devs think that it is ready to be released.

**Comment by derekjohnsonzethcon** [comment]
Im not going to beg for a release date because i know what it takes to release software. I love the work that has been put forth by all parties involved and i want to offer assistance in any way that i can be help. I run a datacenter that we use to host our own software for our customers. We have some extra computing power

**Comment by derekjohnsonzethcon** [comment]
Where i could fire up a couple of instances and put forth my time to help with testing.

**Comment by jurajhudak** [comment]
Hello. RC3 is available and i NEED

**Comment by kest874** [comment]
You basically download the zip file and over write your existing files, or you can do a git pull.

**Comment by jurajhudak** [comment]
When we overwrite the existing file, system stopped working.

**Comment by robintoy** [comment]
Download like @kest874 states and the installer takes you through it all, but this is still a beta release client hence the RC added to the title.

**Comment by jurajhudak** [comment]
OK, we must download zip file and than run installer? 
And data will be remain in the system?

**Comment by robintoy** [comment]
If you ok v1.9.x the DB will be upgraded and you will have no way back so make sure you happy to take this route.

All data will remain or did when we did it

**Comment by jurajhudak** [comment]
We use osTicket (v1.10-rc.2)

**Comment by mfelber** [comment]
It seems that there is a fix needed after the upgrade from rc2 to rc3: https://github.com/osTicket/osTicket/issues/3225

**Comment by ntozier** [comment]
@jurajhudak 
Its like upgrading any other piece of web based software.
back up your site.  back up your database.
install the new files.  Run the upgrader (not needed from RC2 to RC3).

**Comment by GoodbyeWorld** [comment]
@jurajhudak I've recently gone through an upgrade of RC2 to RC3 and might be able to help.  If you're interested, how can I contact you off github?  (I don't think this is the right forum for further discussion)

**Comment by jurajhudak** [comment]
Thank you so much, everyone. We will continue as you write and when we will be have problems, I write.

**Comment by sachinbhosale86** [comment]
Thank You Os ticket for making such wonderful tool for making life easy.
