### ISSUE TITLE
1.9.12 Where is the claim button ?

### ISSUE THREAD

**Issue by cervedgroup** [osTicket/osTicket#2665]
Hi, the claim button is not yet present in unissegned tickets...

**Comment by greezybacon** [comment]
I believe you have to have the ticket assignment permission to do that. Do you have it set for your group?

**Comment by cervedgroup** [comment]
yes, the user group as all the permissions in all departments....

**Comment by greezybacon** [comment]
> is in the admins group

That means nothing. There is no "superuser" group. All permissions and department memberships must be manually granted.

**Comment by cervedgroup** [comment]
the user can assign/transfer the ticket , but the claim button is not present.
the user have all the permission in all departments, but the claim button is not present.

**Comment by protich** [comment]
We collapsed claim button in v1.10 into assign dropdown. We've had negative feedback and  will be added back before stable version.

**Comment by cervedgroup** [comment]
Ok, so in the next 1.9.x version the button will be back also ?
thank you

**Comment by greezybacon** [comment]
I'm confused, I thought the change in v1.10 did not affect v1.9

**Comment by cervedgroup** [comment]
i confirm that in 1.9.12 the "Claim" button has gone away ...

**Comment by mfelber** [comment]
I also use 1.9.12 and I can see and use the claim button in it..

**Comment by infectormp** [comment]
i use 1.9.12 and have "Claim" button

**Comment by calebpaine** [comment]
Also on 1.9.12.
I have the claim button as a superuser, but none of my other users do. Some kind of permission issue that I've not been able to narrow down.

**Comment by ntozier** [comment]
@calebpaine what are your group permissions on the accounts that do not have claim buttons?
