### ISSUE TITLE
Develop-Next: Cannot search by ticket number in scp

### ISSUE THREAD

**Issue by slimatic** [osTicket/osTicket#2667]
When I try to search by ticket number I get this error:

![image](https://cloud.githubusercontent.com/assets/318846/10607847/48bcee58-770a-11e5-94bf-365d28468ace.png)

I am on the latest develop-next commit 1aaa3139d1dfd7236c576b1278261bc820690a1d.

Message reads:
`Warning: Cannot modify header information - headers already sent by (output started at osTicket-1.8\include\staff\templates\sub-navigation.tmpl.php:27) in osTicket-1.8\include\class.http.php on line 62`

**Comment by jdelhome3578** [comment]
@greezybacon Could this be related to bare header redirect #2641

**Comment by greezybacon** [comment]
No that was only for SSO logins

**Comment by t-oster** [comment]
I also get this when searching for a ticket number. The autocomplete shows the right email, but the ajax response contains this warning directly after the header and I get a javascript exception in jquery.pjax.js:629Uncaught TypeError: Cannot read property '0' of nullextractContainer @ VM545 jquery.pjax.js:629options.success @ VM545 jquery.pjax.js:238m.Callbacks.j @ jquery-1.11.2.min.js:2m.Callbacks.k.fireWith @ jquery-1.11.2.min.js:2x @ jquery-1.11.2.min.js:4m.ajaxTransport.send.b @ jquery-1.11.2.min.js:4
 ````
  if (/<html/i.test(data)) {
    var $head = $(parseHTML(data.match(/<head[^>]*>([\s\S.]*)<\/head>/i)[0]))
````
I can debug this more after my hollyday....

**Comment by t-oster** [comment]
But my warning starts at
````
Cannot modify header information - headers already sent by (output started at /kunden/296328_51674/webseiten/osticket/include/staff/header.inc.php:81) in /kunden/296328_51674/webseiten/osticket/include/class.http.php on line 62
````
I am on develop-next @ 1aaa3139d1dfd72

**Comment by t-oster** [comment]
OK. I tracked down what happens:

include/staff/tickets.inc.php(111) calls Http::redirect('tickets.php?id=...') because there is only one result and it wants to redirect to this ticket.

The problem is, that the tickets.inc.php is included in scp/tickets.php(494) after the header.inc.php was already included and thus the headers are already sent (header.inc.php contains html code).

**Comment by t-oster** [comment]
seems as if it would require some structural changes in order to work, because changing the order of includes is not simple.

BTW are there any plans to update the structure of OsTicket to a more Model-View-Controller based approach where the controller is called first fills the view variables before the view is rendered? Maybe with a template-engine like smarty?

**Comment by greezybacon** [comment]
Seems like the typeahead based search system should negotiate the target page better. That is, when clicking on the ticket number in the typeahead drop-down, the system should go to the ticket view page for that ticket directly, rather then coming through the ticket queue listing page first.

**Comment by t-oster** [comment]
That would be nice but if you type faster than the typeahead Ajax call finishes (I.e you paste the ticket number and press return) you still end up with the ticket number as query string and get the error described above. By the way the hack seems to work quite well.

**Comment by greezybacon** [comment]
> That would be nice but if you type faster than the typeahead Ajax call finishes (I.e you paste the ticket number and press return) you still end up with the ticket number as query string and get the error described above. By the way the hack seems to work quite well.

Perhaps; however, if going directly to the ticket view required a [click], then pasting a pressing enter could be changed to go back to a queue listing of one item

**Comment by t-oster** [comment]
I could live with that.
But this leads me to another point: #2817
