### ISSUE TITLE
1.10 tip of devevlop-next 1aaa313  Client search and count is broken

### ISSUE THREAD

**Issue by kest874** [osTicket/osTicket#2669]
When searching as an enduser the search returns all of their tickets:

![image](https://cloud.githubusercontent.com/assets/12860950/10648349/7eef9620-7803-11e5-9a2d-0dd0d5357376.png)

I searched "findme" and  both tickets for user were shown.  Note that the ticket count is incorrect, showing 3 when only 2 tickets are for the logged in user.  This is a green install from the tip commit 1aaa313.

Search last worked at commit f6ccc3f

**Comment by c0nfused** [comment]
Fresh install here too... I search for "findme" and I get an error!

Fatal error: Uncaught exception 'InconsistentModelException' with message 'Unable to prepare query: SELECT COUNT(*) FROM (SELECT A1.`ticket_id`, Z1.`relevance` AS `__relevance__` FROM `ost_ticket` A1 JOIN (SELECT COALESCE(Z3.`object_id`, Z5.`ticket_id`, Z8.`ticket_id`) as `ticket_id`, SUM(MATCH (Z1.title, Z1.content) AGAINST ('findme' IN NATURAL LANGUAGE MODE)) AS `relevance` FROM `ost__search` Z1 LEFT JOIN `ost_thread_entry` Z2 ON (Z1.`object_type` = 'H' AND Z1.`object_id` = Z2.`id`) LEFT JOIN `ost_thread` Z3 ON (Z2.`thread_id` = Z3.`id` AND Z3.`object_type` = 'T') LEFT JOIN `ost_ticket` Z5 ON (Z1.`object_type` = 'T' AND Z1.`object_id` = Z5.`ticket_id`) LEFT JOIN `ost_user` Z6 ON (Z6.`id` = Z1.`object_id` and Z1.`object_type` = 'U') LEFT JOIN `ost_organization` Z7 ON (Z7.`id` = Z1.`object_id` AND Z7.`id` = Z6.`org_id` AND Z1.`object_type` = 'O') LEFT JOIN ost_ticket Z8 ON (Z8.`user_id` = Z6.`id`) WHERE MATCH (Z1.title, Z1.content) AGAINST ('findme' IN NATURAL LANGUAGE MODE) GROUP BY `ticket_id`) Z1 WHERE A1.`ticket_id` in /home/osticket-devnext/public_html/osTicket-1.8/include/class.orm.php on line 2767
