### ISSUE TITLE
v1.10-rc.2-135-g1aaa313 - Department Parent/Child Role Permission Inheritance/propagation

### ISSUE THREAD

**Issue by goobersmooch** [osTicket/osTicket#2674]
If you have nested departments and an agent is assigned to the parent department then they should have access to tickets in the child departments as well with the chosen role permissions.

If this is by design It would be very nice to be able to have an option somewhere (maybe in the extended access section) to propagate that agents role permissions to child departments instead of having to add every single child department as an extended department. 

See screenshots below for an example.

![osticket2](https://cloud.githubusercontent.com/assets/15216195/10704897/a7b663d4-799f-11e5-8357-4cbb0b2533da.jpeg)
![osticket3](https://cloud.githubusercontent.com/assets/15216195/10704984/3c1017f0-79a0-11e5-95e5-6fc5f76a7456.jpeg)

**Comment by philbertphotos** [comment]
+1

**Comment by baozdemir** [comment]
+1

**Comment by MosquitoCoding** [comment]
I am still experiencing the same problem, and I noticed that it has been marked as completed. However, I have not been able to find this feature. Could you please provide an update on the status of this issue?

**Comment by JediKev** [comment]
@FlorianPanten 

We did a mass archive of old issues back in 2020. This was part of that archive.

When nesting Departments any Agent with access to the Parent Department will see Tickets in the Child Department(s) however Access does not extend to the Child Department(s). This is further explained in [our Documentation](https://docs.osticket.com/en/latest/Admin/Agents/Departments.html) under "Department Information > Parent".

With this being said I will discuss this with the rest of the development team to see if we should reopen and mark as Feature Request or keep it closed (rejected).

Cheers.
