### ISSUE TITLE
Reverse email fetch order (IMAP)

### ISSUE THREAD

**Issue by bunkobugsy** [osTicket/osTicket#2685]
Any ideeas on why tickets are created from emails in reverse order (newest first / LIFO) ?

Fetching 2 emails every minute on cron job running on Centos 5 + Dovecot IMAPS (993).

osTicket Version    v1.9.12 (19292ad) —  Up to date
Web Server Software Apache
MySQL Version   5.5.46
PHP Version 5.5.30

**Comment by kest874** [comment]
Change line 834 in include/class.mailfetch.php from:

for($i=$nummsgs; $i>0; $i--) { //process messages in reverse.

to

for($i=1; $i<=$nummsgs; $i++) { //process messages in forward order.

This will process the emails oldest to newest.

**Comment by bunkobugsy** [comment]
Thanks, will try your patch, any chance this will be included in the next release as a permanent fix (assuming this would be the normal behavior)?
