### ISSUE TITLE
Mail allert when there are more than x ticket open?

### ISSUE THREAD

**Issue by gitfve** [osTicket/osTicket#2687]
Hi

I looking for a function there can post a mail to "supporters" if there are more then x cases open?

**Comment by ntozier** [comment]
I don't have the foggiest idea what you are asking for.  Please try asking a different way, or provide a mock up of the feature that you are requesting.

**Comment by gitfve** [comment]
Ok, I try again.

Customers make the support ticket. Our "supporters" don't know when, therefore they logon to the system to check if there are any tickets. It will be nice if there was a function there can alert the support "Agent" if there are more than x open ticket. (I know we can get alert when there are tickets, but I want about 3 ticket before the alert)

**Comment by ntozier** [comment]
There is no function like that currently.  It's every ticket gets announced, or none.
