### ISSUE TITLE
Tickets with image Attatchments

### ISSUE THREAD

**Issue by philbertphotos** [osTicket/osTicket#2688]
It would be nice to have tickets with attachment images popup instead of going to that link and taking the agent away from osticket.

**Comment by nfebuary** [comment]
Agreed, an attachment preview has been discussed and is on a To-Do list.

**Comment by perryk** [comment]
There is a fantastic attachment preview plugin here: https://github.com/clonemeagain/attachment_preview

It is working well for me, and I think makes viewing tickets much easier.
