### ISSUE TITLE
10-RC2 Deparment permission bug

### ISSUE THREAD

**Issue by philbertphotos** [osTicket/osTicket#2690]
I've noticed that when setting up an agent with permission to departments I notice I have to go into the agent account and set the same permission ... it seems kind of redundant. Should not setting a agents permission in either section should give the user all rights to the tickets of that department I should have to do it in both places.

**Comment by colonelpopcorn** [comment]
You seem to be confusing membership with access. An agent can have multiple different access roles, but can only belong to one department. Are you moving an agent from one department to another and expecting them to inherit all of their previous access?
