### ISSUE TITLE
Email Filters for emails related to existing Ticket - not only for new Tickets

### ISSUE THREAD

**Issue by mlipok** [osTicket/osTicket#2693]
Please add feature to Email Filters for emails related to existing Ticket.
Currently Email Filters works only for email which create new Ticket

Was discussed here:
http://osticket.com/forum/discussion/comment/100217

**Comment by ntozier** [comment]
"Currently Email Filters works only for email which create new Ticket"

This should read "Currently Email Filters works only for ~~email which create~~ new Ticket(s)"

**Comment by mlipok** [comment]
Yes indeed.
Thanks for correcting my vocabulary.

mLipok

**Comment by ntozier** [comment]
Very welcome. :)
