### ISSUE TITLE
'Print -> Ticket Thread' generates unreadable thread's titles (on russian)

### ISSUE THREAD

**Issue by Zholaman** [osTicket/osTicket#2707]
Hi,
'**Print -> Ticket Thread**' and '**Print -> Thread + Internal Notes**' generates unreadable titles of thread (**which on russian**). 

I think this type of error relates to functions that working with utf-8 encoding or something like that.

[Screenshoot is accessable by the link](http://osticket.com/forum/discussion/86747/print-ticket-thread-and-print-thread-internal-notes-generates-unreadable-thread-s-title#latest)

**Comment by Zholaman** [comment]
Hi @greezybacon , could you tell me, what type and version of pdf library used in osTicket v1.9.12. I ask because we have problem with titles of threads (which on russian) that appear in pdf. To converting to pdf we use 'Print -> Ticket Thread'? Titles (on russian) of threads appear in pdf in unreadable format. Screenshot is attached in http://osticket.com/forum/discussion/86747/print-ticket-thread-and-print-thread-internal-notes-generates-unreadable-thread-s-title#latest

**Comment by Zholaman** [comment]
I have found that you use **Ticket2PDF** class that extends the **mPDF** library (v.5.7.3).

May be the following code will help to resolve our issue

1.  When I am writing code on PHP I usually use the following code to provide support of UTF-8:
```PHP
$conn = new mysqli($db_servername, $db_username, $db_password, $db_name);
$conn->set_charset("utf8");
```
2. Concerning mPDF:
```PHP
$mpdf = new mPDF('utf-8', 'A4', '10', 'Arial', 0, 0, 5, 5, 5, 5);
$mpdf->charset_in = 'utf-8';
```

**Comment by Zholaman** [comment]
Let me add some details, all text on russian in pdf we can see without problems except threads' titles.

**Comment by Zholaman** [comment]
Hi, I have checked, this error appeared after upgrading from v1.9.5.1 to v1.9.9 !

**Comment by ntozier** [comment]
Try upgrading to 1.9.12 and see if it fixes itself?

**Comment by Zholaman** [comment]
Hi @ntozier, sorry, I had upgraded to v1.9.12 in August yet.

The previous message from me was my little investigation result, I found that the above bug appeared after upgrading from v1.9.5.1 up to v1.9.9.

I have found, that in v1.9.9 new class is appeared, it is Charset (class.charset.php), I also compared difference in important (from my point of view) files between v1.9.5.1 and v1.9.9:

1. include/class.pdf.php (difference is not found);
2. upload/scp/tickets.php (difference is found but as I understood it does not impact on export to pdf functions).

I've been doing my investigation in my free time from work and education.

**Comment by infectormp** [comment]
I not have any issue with Ticket Thread with Russian with 1.9.12.

**Comment by Zholaman** [comment]
@infectormp I do not know why this problem had appeared after upgrading from v1.9.5.1 up to 1.9.12. I have no changed the configuration files of Apache, PHP, MySQL , I just copied new files on the server by FTP connection.

**Comment by infectormp** [comment]
what PHP version and Mysql version you use, what osticket db encoding\collate used?

**Comment by Zholaman** [comment]
@infectormp,
software's version and MySQL database's charset/collate:

1. MySQL v5.1.73
    - default character set is - **utf8**
    - default collation name is - **utf8_general_ci**
2. PHP v.5.3.3
3. Apache v.2.2.15

**Comment by mfelber** [comment]
I have seen some people having problems with PHP 5.3.3 and osticket. But normally they have some php errors in the web server error log..

**Comment by Zholaman** [comment]
Hi @mfelber, could you tell me, what PHP versions is perfect for osTicket ? But in mean time we had not problems with osTicket before upgrading, when we used osTicket **v1.9.5.1**. This problem(see above) appeared after upgrading from v1.9.5.1. up to 1.9.9. So with my point of view this bug/problem is not depend with PHP version. In any way thanks for your assumption.

**Comment by Zholaman** [comment]
@infectormp , I have installed fresh osTicket v1.9.12 (without upgrades and so one) on the test site (which I have created special for this test), and bug still exists.

**Comment by mfelber** [comment]
@Zholaman I think for example PHP 5.5.30 would be a good choice. PHP 5.3.x had reached the end of life in august 2014, PHP 5.4 in September 2015. So both are getting no longer security updates or bug fixes. PHP 5.6.x could make some trouble with email sending due to problems with the peer verification. You could use a xampp test environment to see if this would help before you do anything with your production system..

**Comment by infectormp** [comment]
@Zholaman i use php 5.6.15. Can you try bump PHP version?

**Comment by Zholaman** [comment]
@infectormp At the current moment I have not the possibilities to install new version of PHP on the current server and I do not want compiling PHP from the source. Instead I plan to deploy osTicket v1.9.12 on new server with PHP v.5.6.x, and if it does work, then I move current osTicket to new server.

Thanks for excelent proposal.

**Comment by Zholaman** [comment]
Hi @infectormp, I have deployed new VM (**Ubuntu v15.10**) with last version of **PHP v5.6.11**, **MariaDB v10.0.22**, but it is did not help. The bug still exists.

**Comment by Zholaman** [comment]
Hi @ntozier, I have found that ticket's threads titles incorrectly encoded before being posted to the database. I changed text of some ticket's thread titles directly in database and thread's title (on russian) appeared in pdf correctly.
