### ISSUE TITLE
Execution order in ticket filters ignore priority on osTicket v1.9.12

### ISSUE THREAD

**Issue by alirezastack** [osTicket/osTicket#2713]
I have 2 filters for tickets.
One with execution order of 1 that closes the ticket that contains `sample-text` in issue summary and another all settings are the same as the first filter, but the second one has execution order of 10 and keeps ticket open with emergency status.

Why the first filter is not applied to the tickets as it has higher priority? Is this a bug? Am missing something?

**Comment by protich** [comment]
Execution order doesn't necessarily mean priority -- it just needs the order the filters are applied. In your case, filter #2 will be applied last. If you want filter #1 to be applied then you'll need to check "stop processing" or change execution order to be higher than that of filter #2.

**Comment by alirezastack** [comment]
Execution order is higher than filter #2,

**Comment by protich** [comment]
It's the order of execution --- meaning starts from 1, 2, 3.....999. In your case filter 2 get applied after filter 1.
