### ISSUE TITLE
1.10-RC.2 Stuck At Please Wait Screen For 60-90 Seconds When Creating Ticket With New Ticket Alerts Enabled

### ISSUE THREAD

**Issue by goobersmooch** [osTicket/osTicket#2727]
When i create a new ticket as a user and hit the create ticket button the page stays on the “Please Wait!" screen for 30-90 seconds.

![screen shot 2015-11-12 at 3 09 04 pm](https://cloud.githubusercontent.com/assets/15216195/11131559/dee1033a-8950-11e5-9056-e169adb8e722.png)

This only happens when i have new ticket alerts enabled.

![screen shot 2015-11-12 at 3 13 08 pm](https://cloud.githubusercontent.com/assets/15216195/11131622/2180545c-8951-11e5-962c-2c620984eae3.png)

**Comment by ntozier** [comment]
"as a user"
As a user (client)?  or as an Agent (staff)?

How do you have email configured? (phpmail?  SMTP?)

**Comment by goobersmooch** [comment]
A user as in a client. I've tried both SMTP and phpmail with the same results.
