### ISSUE TITLE
When creating a task in v1.10-rc.2 (231f11e) the assignee does not stick

### ISSUE THREAD

**Issue by bhiscox** [osTicket/osTicket#2728]
When creating a task in version v1.10-rc.2 (231f11e) it seems as though the assignee does not stick and when you go back to the task after it is created the task always says 'unassigned'.

**Comment by johnweidauer** [comment]
same on my end.

**Comment by akashkumardce** [comment]
In file - include/class.task.php (v1.10-rc.2)
Line - 1199 ( referenced [File](https://github.com/osTicket/osTicket-1.8/blob/231f11e85765a888b2b8c90d16df11cb0af30e67/include/class.task.php))
Add the code-
```
if ($vars['internal_formdata']['assignee']->staff_id)
            $task->staff_id = $vars['internal_formdata']['assignee']->staff_id;
```

It will save assignee information in database, and hence assigns the task to a staff.
This will Fix #2728

**Comment by akashkumardce** [comment]
https://github.com/osTicket/osTicket/pull/3100/commits/e68ec9c01076b4e2e5ee58088627e70946d5b192

Fixes the issue of task assignment

**Comment by jaskaransingh156** [comment]
That was genuinely very helpful. I was probing for it for a long time.
