### ISSUE TITLE
1.10RC - When printing a ticket the time is displayed incorrectly

### ISSUE THREAD

**Issue by kaptk2** [osTicket/osTicket#2731]
When a ticket is printed out the timezone doesn't seem to be respected. It displays correctly on the site itself but when it is printed the wrong time is shown. I have made sure that the time is set correctly on the server and double checked the users profile to ensure they had the correct timezone set in their profile. The fact that it shows fine when viewing the ticket on screen leads me to believe that this is a bug when the ticket is printed.

**Comment by jfisic** [comment]
I am also running 1.10 and All time settings are correct, I all times that appear on osticket are correct, the only thing that is incorrect is the footer printed time when printing out a ticket.  It says that it is 6 hours ahead of the actual time.  php.ini is correct, time on the server is correct, and all of the other times in osticket are correct. 

Anyone have any thoughts?

**Comment by ntozier** [comment]
You haven't mentioned you MySQL database timezone...

**Comment by jfisic** [comment]
Yes I did forget that one, I did just double checked that as well and it is correct. I have submitted a copy of a printed ticket.
 
[Ticket-HG000001 (8).pdf](https://github.com/osTicket/osTicket/files/667180/Ticket-HG000001.8.pdf)
