### ISSUE TITLE
10-RC2 Filter "send an Email" (bug)

### ISSUE THREAD

**Issue by philbertphotos** [osTicket/osTicket#2740]
You are unable to type in the textarea when you enable the "Send to Email" the only way to type anything is to TAB into the control. 

![11182015-091121](https://cloud.githubusercontent.com/assets/2892474/11242661/8a9bd45c-8dd9-11e5-9746-618c6d442f4b.png)

**Comment by thejordanaustin** [comment]
I had this same issue. It was weird. I ended up using the "tab" key on the keyboard and it worked. What I'm trying to track down now is the bug report about the arrays not working, if you can't list the ticket number in there seems kind of useless to me.
