### ISSUE TITLE
1.9.12 - Changing order to tickets if internal note posted

### ISSUE THREAD

**Issue by davideakc** [osTicket/osTicket#2743]
Hi,

it is possible (by editing the source code) move the ticket above to the list of all tickets when a new internal note is posted? (like if you set the priority to "High" or "Emergency"...
So I can always know if there's a new internal posted if the tickets go to the top position...

Thanks

**Comment by davideakc** [comment]
Any idea?

**Comment by ntozier** [comment]
I haven't the foggiest idea of what you mean.
mock up?

**Comment by colonelpopcorn** [comment]
I think what he's getting at is a way to sort by latest response. That-a-way you can keep a finger on the pulse of what's going on at your help-desk.

**Comment by protich** [comment]
"Most Recently Updated" sort is supported in the upcoming version (V1.10).
