### ISSUE TITLE
1.10 rc2 Task not showed

### ISSUE THREAD

**Issue by ilvikingo** [osTicket/osTicket#2747]
Hi everyone,
 when I try to see task I cannot, any idea how to fix this? 
![schermata 2015-11-23 alle 13 41 33](https://cloud.githubusercontent.com/assets/6615283/11336735/078fbc5a-91e8-11e5-9a18-0593e526e16e.png)

**Comment by ntozier** [comment]
Admin panel -> Agents -> Roles -> Tasks
You have permissions?
Was the task assigned to someone else?

**Comment by ilvikingo** [comment]
Hi ntozier , thanks for the reply!

Yes permissions are correctly set and assigned to me , the only agent atm
