### ISSUE TITLE
1.10 rc2 Task in Filter

### ISSUE THREAD

**Issue by ilvikingo** [osTicket/osTicket#2748]
Hi Everyone,

is there a chance to create a filter that create automatically a task when a help topic is used?

**Comment by ntozier** [comment]
Not at this time, but I imagine that will be coming in a forth coming version.

**Comment by colonelpopcorn** [comment]
+1 for this feature.

**Comment by protich** [comment]
Canned Tasks a planned feature but it won't make 1.10 cut.
