### ISSUE TITLE
develop-next: Task cannot be assigned anymore

### ISSUE THREAD

**Issue by t-oster** [osTicket/osTicket#2750]
After upgrading to 77309f4e939af489e4aac73beb9b7c4ad87c6c7d, I the box to assign a task to an agent is empty. Assigning tickets works as usual, but assigning tasks does not work. Neither on new, nor on existing tasks.

![no-assign](https://cloud.githubusercontent.com/assets/1052720/11368640/34dfb0e2-92bb-11e5-8d8d-c8424121a7bc.jpg)

**Comment by t-oster** [comment]
Thanks to git-bisect (nice tool ;), the commit to blame is 06e425145df51a88ab10d118d6d3075265e4f184

**Comment by t-oster** [comment]
It still does not work If I set the department to have only members assignable.

**Comment by t-oster** [comment]
@protich could you review your commit 06e4251 and make sure the assignment still works on tasks afterwards? I reverted that commit and the assignment works again, so I am almost certain that your changes introduced this error.

**Comment by protich** [comment]
@t-oster - Yes, I'm guilty of breaking the assignment. PR #2760 address the issue + other tasks related bugs.
