### ISSUE TITLE
Option to queue mail sending to avoid long page loads

### ISSUE THREAD

**Issue by Ketrel** [osTicket/osTicket#2752]
Currently when an action causes an email to be sent, it's sent on the page load that generates it, and with slow SMTP servers (such as Office 365), this can cause long page loads.  (In my case, I'm getting page loads as long as 10 seconds when replying to a ticket, but instantaneous if I were to choose not to send an email)

An option that would avoid this would be to be able to add them to a queue which would be handled by the same cron (or faux cron) job that retrieves mail.  That would offload the slowness of the SMTP servers to the cron job's execution of the code and the page loads that generate the mail would go back to having no additional load time since it would only be making local changes.

**Comment by goobersmooch** [comment]
I'm having the exact same issue using SMTP with Office 365, but our page loads are much longer than 10 seconds. See #2727.
An option like @Ketrel suggests above would be great.
