### ISSUE TITLE
Completely Separate Groups of Agents / Organizations / End users

### ISSUE THREAD

**Issue by kingIZZZY** [osTicket/osTicket#2754]
A more "generic" development company who might have several unrelated projects/products would want to service support for those various products separately: Each should ideally not be able to see/access any of the other Agents / Organizations' / End users / Tickets.

I.O.W. Instead of cloning an entire new installation of osTicket in order to service Agents & end users of Project A, Project B and Project C separately, there should be a feature of segregating the agent/user base into separate "domains" in the same osTicket installation.

Related discussion: http://osticket.com/forum/discussion/86791/how-to-handle-segregation-of-departments

**Comment by nfebuary** [comment]
Multi branding is on the table and is being discussed. However, I cannot produce a development timeline for you since we are currently in the discussion/concept stage of this feature.

**Comment by AlexYoung28** [comment]
+1
