### ISSUE TITLE
Ablity to assign TASKS to users in 1.10RC2 

### ISSUE THREAD

**Issue by philbertphotos** [osTicket/osTicket#2764]
I find that there is a need to assign a task to the user and not just a team member. Is there anyway to do this ?
(feature)

**Comment by ntozier** [comment]
There is no way to do that at this time... but I think that I like the idea!

**Comment by protich** [comment]
@philbertphotos - By user do you mean Agents? If so, then perhaps you don't have any available/eligible agents.  

@ntozier - That's what tickets are for! Attaching a task to a user's ticket is the closest thing you can do to associate a task to an end user.

Tasks are meant to be internal to do list with external collaborators.

**Comment by ntozier** [comment]
@protich Yes I know that's the way the system is designed... I was just thinking that I can see why assigning a task to a User (client) might be a great idea.  It could be something that is as simple as "Please reboot the computer and try again and let us know if it fixes it".  Currently we (my agency) does this with a simple reply to the client but having a mechanism that the user has to do something [or at least say that they did, and click that they did it] seems like a really neat idea to me.

**Comment by philbertphotos** [comment]
That the idea also it stops the SLA until the user completes the task and closes the task.
