### ISSUE TITLE
Timezone not correct in custom form fields

### ISSUE THREAD

**Issue by superjunky** [osTicket/osTicket#2769]
Hi,

In OST 1.10RC2 I am having an issue with timezone settings.

Problem: Time from a custom form field is of by 1 hour.

I am running the same OST installation on 2 different machines, both with the same OST settings.
Server 1 is correct. Also on the system settings page, a Default Locale settings can be set.
Server 2, ticket times seem to be correct, custom form fields are not. On this system settings page, no Default Locale setting is displayed.

Any ideas on what might be wrong?

**Comment by oneilak** [comment]
please check the timezone settings at php.ini

**Comment by kingapricot** [comment]
@oneilak Where is the php.ini located?

**Comment by oneilak** [comment]
@kingapricot  #2779

**Comment by superjunky** [comment]
Installing the intl php module solved my issue
