### ISSUE TITLE
Blank Date Column with UK Date format

### ISSUE THREAD

**Issue by bcowman** [osTicket/osTicket#2771]
Version 1.10-rc.2

I have a default installation and my open tickets are listed with US date format MM/dd/y
![image](https://cloud.githubusercontent.com/assets/6651942/11567851/0f9889bc-99e1-11e5-8341-4cf66d2cdac5.png)

If I change the system settings to UK date format dd/MM/y
![image](https://cloud.githubusercontent.com/assets/6651942/11567887/36f7ec8c-99e1-11e5-828e-cc1d803cb667.png)

then go back to my open tickets
![image](https://cloud.githubusercontent.com/assets/6651942/11567908/61cb0782-99e1-11e5-8841-4553c41731a5.png)

Date column is blank.

**Comment by andrew-za** [comment]
Same issue - formats clear the date
