### ISSUE TITLE
Access link not being populated

### ISSUE THREAD

**Issue by studiorepublic** [osTicket/osTicket#2774]
We're having issues with the access link sent out from osTicket 1.9.12

All other email links are populated correctly, but these are not - we end up with this:

Follow the link below to check the status of the ticket #999999.

[xxxxx.org.uk/view.php][1]

**Comment by ntozier** [comment]
This seems more like a question for the forums...
Version of osTicket?
What's the HTML view of the template that you are using?

**Comment by studiorepublic** [comment]
This is what we have:

`Hi %{recipient.name.first},
An access link request for ticket #%{ticket.number} has been submitted on your behalf for the helpdesk at %{url}.

Follow the link below to check the status of the ticket #%{ticket.number}.

%{recipient.ticket_link}

If you did not make the request, please delete and disregard this email. Your account is still secure and no one has been given access to the ticket. Someone could have mistakenly entered your email address.

--
%{company.name}`

**Comment by ntozier** [comment]
Appears that this has already been reported here: https://github.com/osTicket/osTicket-1.8/issues/2201

**Comment by studiorepublic** [comment]
I think it's something else in our case as it looks fine in the DB

<h3><strong>Hi %{recipient.name.first},</strong></h3> <div> An access link request for ticket #%{ticket.number} has been submitted on your behalf for the helpdesk at %{url}.<br /> <br /> Follow the link below to check the status of the ticket #%{ticket.number}.<br /> <br /> <a href="%{recipient.ticket_link}">%{recipient.ticket_link}</a><br /> <br /> If you <strong>did not</strong> make the request, please delete and disregard this email. Your account is still secure and no one has been given access to the ticket. Someone could have mistakenly entered your email address.<br /> <br /> --<br /> %{company.name} </div>

**Comment by studiorepublic** [comment]
Don't think so - the code looks fine in the db to me:  

`<h3><strong>Hi %{recipient.name.first},</strong></h3> <div> An access link request for ticket #%{ticket.number} has been submitted on your behalf for the helpdesk at %{url}.<br /> <br /> Follow the link below to check the status of the ticket #%{ticket.number}.<br /> <br /> <a href="%{recipient.ticket_link}">%{recipient.ticket_link}</a><br /> <br /> If you <strong>did not</strong> make the request, please delete and disregard this email. Your account is still secure and no one has been given access to the ticket. Someone could have mistakenly entered your email address.<br /> <br /> --<br /> %{company.name} </div>

**Comment by studiorepublic** [comment]
Don't think so - it looks fine in the db:

```html
<h3><strong>Hi %{recipient.name.first},</strong></h3> <div> An access link request for ticket #%{ticket.number} has been submitted on your behalf for the helpdesk at %{url}.<br /> <br /> Follow the link below to check the status of the ticket #%{ticket.number}.<br /> <br /> <a href="%{recipient.ticket_link}">%{recipient.ticket_link}</a><br /> <br /> If you <strong>did not</strong> make the request, please delete and disregard this email. Your account is still secure and no one has been given access to the ticket. Someone could have mistakenly entered your email address.<br /> <br /> --<br /> %{company.name} </div>
```
