### ISSUE TITLE
osTicket an MS SQL

### ISSUE THREAD

**Issue by oneilak** [osTicket/osTicket#2778]
Hello everybody,

it is actually planned times to support Microsoft SQL Server?
I would find it great and think that it would be good for the performance.

**Comment by infectormp** [comment]
Microsoft SQL Server and performance incompatible :) Would be better add Oracle support

**Comment by colonelpopcorn** [comment]
I thought the purpose of the ORM was to *reduce* the number of queries to the back-end database. If osTicket only queries the database when absolutely necessary, then it shouldn't have much of an effect on performance to change the back-end database to a different architecture.

**Comment by ntozier** [comment]
@colonelpopcorn  IMO the purpose of ORM is to divorce the queries from a specific flavor of DB (MySQL/MariaDB) to be able to support multiple DB softwares.  I think that @infectormp was stating that his opinion is that MS SQL is a performance hog compared to other SQL flavors, and that he would rather see Oracle support added before MS SQL.

**Comment by colonelpopcorn** [comment]
@ntozier Gotcha, my mistake. This request makes some more sense now.

**Comment by greezybacon** [comment]
I think it's already been expressed, but I'll reiterate. The timeline is slightly complex. I think this is what's left on the roadmap:

* Remove the rest of the SQL statements and convert to ORM for the business logic code
* Add backends for other databases. SQLite will be first
* Add install capabilities (CREATE TABLE) to the ORM and port installer away from the current SQL-based script
* Add migration capabilities (ALTER TABLE) to the ORM and port the upgrader away from the current SQL-based scripts
