### ISSUE TITLE
PHP.ini location

### ISSUE THREAD

**Issue by kingapricot** [osTicket/osTicket#2779]
Where is my PHP.ini? I have osTicket installed on a Windows machine

**Comment by oneilak** [comment]
with iis or xampp or other?

**Comment by kingapricot** [comment]
@oneilak wampserver 2.5

**Comment by oneilak** [comment]
The simple solution is to left click the WAMP Server system icon and go to PHP then click the php.ini menu option.  The correct file is opened in notepad. 
 
\wamp\bin\apache\apache2.x.x\bin﻿\php.ini.

**Comment by kingapricot** [comment]
Thank you very much!
