### ISSUE TITLE
Quote formatting (blockquote) the same in web form and at email messages

### ISSUE THREAD

**Issue by Aka4Code** [osTicket/osTicket#2783]
When we use Quote formatting, then we get in osTicekt web form, some nice text style:

![image](https://cloud.githubusercontent.com/assets/11789024/11686653/5b7672cc-9e82-11e5-96c4-6ac432263cbd.png)

![image](https://cloud.githubusercontent.com/assets/11789024/11686673/840733ac-9e82-11e5-9a44-e307f66e1b05.png)

But this effect is only at website.
With emails this gray line do not exist.

I would like to insert into code that send email this line - it will copy formatting to emails:
`$mail_content = str_replace('<blockquote>', '<blockquote style="font-style: italic !important; border-left: 5px solid #eeeeee; color: #777; padding: 10px 20px;" >', $mail_content);`

Can anyone help me where to search for place where I can insert this code? @greezybacon  @protich @nfebuary ?

We use osTicket Version v1.9.8.1

**Comment by Aka4** [comment]
This is related to #176

**Comment by Aka4** [comment]
Ok., I have found:

`/include/class.mailer.php`
at the begining of `function send($to, $subject, $message, $options=null) {`
after line `global $ost, $cfg;`
if we add:
`$message = str_replace('<blockquote>', '<blockquote style="font-style: italic !important; border-left: 5px solid #eeeeee; color: #777; padding: 10px 20px;" >', $message);`

then email Quote formatting will work in email messages
