### ISSUE TITLE
Ticket not created sometimes on creating ticket from Agent panel

### ISSUE THREAD

**Issue by zeeshankhurshid** [osTicket/osTicket#2786]
I have seen few time when creating a fresh ticket from Agent panel, Tickets were not generated. How ever from API I had never faced any such case.

Event I had watched issue for each bucket but was not able to find ticket few time.

Hope to get resolution and reason behind it. 

Thanks
Zeeshan

**Comment by ntozier** [comment]
Version of osTicket?
I have never once had this problem in over 3 years.
Are you getting any PHP errors?
What webserver are you hosting under?

**Comment by zeeshankhurshid** [comment]
I am having version 1.8 on live however on dev env I am having 1.10 but I
had noticed this prob on both the environment. I never get any error. New
ticket page gets posted which takes me to ticket listing page which does
not my last ticket with no logs at admin too.

Thanks
Zeeshan

On Thu, Dec 10, 2015 at 7:14 PM, ntozier <notifications@github.com> wrote:

> Version of osTicket?
> I have never once had this problem in over 3 years.
> Are you getting any PHP errors?
> What webserver are you hosting under?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/osTicket/osTicket-1.8/issues/2786#issuecomment-163622342>
> .
>



-- 
Thanks & Regards
Zeeshan Khurshid
