### ISSUE TITLE
Ticket filters not getting created by applying rule on ticket status

### ISSUE THREAD

**Issue by zeeshankhurshid** [osTicket/osTicket#2792]
I was trying to create a ticket filter but I was not able to find ticket status under ticket rule section. Is it any problem adding ticket status in ticket rules ?

**Comment by ntozier** [comment]
version of osTicket?

in 1.9.x and 1.10+  it would be Ticket / Issue Summary.

**Comment by zeeshankhurshid** [comment]
I have seen Issue Summary but it seems to be issue title, I was talking for
applying a filter on ticket status as for example

"If ticket is resolved and assignee is Payment team then shorten the SLA
plan to 12 hours"

Hope you got my question.


On Mon, Dec 14, 2015 at 7:34 PM, ntozier <notifications@github.com> wrote:

> version of osTicket?
>
> in 1.9.x and 1.10+ it would be Ticket / Issue Summary.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/osTicket/osTicket-1.8/issues/2792#issuecomment-164445756>
> .
>



-- 
Thanks & Regards
Zeeshan Khurshid
