### ISSUE TITLE
Expose email headers to issue filter

### ISSUE THREAD

**Issue by bkonetzny** [osTicket/osTicket#2793]
Currently it's possible to create issue filters which are based on email subject or body. It would be a great addition to filter issues based on email headers, for example deny issue creation if an auto-responder header is present in the email. This is far more reliable than checking for the subject line, which differs for auto-responders such as away or vacation messages.

With this change, one could create filters that react on given headers like this:

```
auto-submitted: auto-generated
Auto-Submitted: auto-replied (vacation)
```

**Comment by ntozier** [comment]
Note to devs: auto-submitted is discussed in RFC 3834.
https://tools.ietf.org/html/rfc3834

**Comment by greezybacon** [comment]
> for example deny issue creation if an auto-responder header is present in the email

We've worked pretty hard at detecting bounces and auto replies automatically. The auto-reply should be threaded with the ticket generating the original email which was automatically replied to. Is there a problem with the threading that needs to be fixed?
