### ISSUE TITLE
Catchable fatal error when receiving mail in 1.10RC2

### ISSUE THREAD

**Issue by superjunky** [osTicket/osTicket#2795]
When I receive replies from a certain email address, ost creates a new ticked instead of attaching the reply to the existing ticket, and displays the following error.

Catchable fatal error: Method EmailAddress::__toString() must return a string value in /include/mysqli.php on line 300

**Comment by greezybacon** [comment]
Would it be possible to get a full stack trace from the crash?

**Comment by superjunky** [comment]
Can you give me a hint on what a "full stack trace" might be?

**Comment by greezybacon** [comment]
maybe [this](http://stackoverflow.com/a/7039409) would help

**Comment by superjunky** [comment]
I asume a backtrace can only be made at the time of crash?! The system wasn't set to Debug, and unfortunately I cannot reproduce the error since I don't own the particular (valid) email address.
I understand you can't really investigate without the trace. i'm sorry..

**Comment by greezybacon** [comment]
@superjunky I'll try and investigate by guessing why EmailAddress::__toString() might not return a string

**Comment by superjunky** [comment]
Perhaps the address format comes in handy:

***.***-***@***.***.com

**Comment by greezybacon** [comment]
So the left-hand-size of the `@` was literally `.-` (dot dash)?

**Comment by superjunky** [comment]
Try a page refresh, I made an edit :)
