### ISSUE TITLE
1.10 RC2 Email reply with attachment, alerts do not contain attachment

### ISSUE THREAD

**Issue by kest874** [osTicket/osTicket#2798]
I've noticed that even while having %{message.files}, %{response.files} in the email templates that if the correspondence is via email the attachments are not included in the alert email.

The attachment is put into the thread message, just not emailed out.

If you respond via the GUI (client or staff) and add an attachment the attachment is included in the alert emails.

**Comment by mmichalski** [comment]
what needs to change in order for this to work:
class.ticket.php file located in the include directory
attachment variable would replace the null variable in 4 or 5 statements within the file
