### ISSUE TITLE
Tasks: Due Date does not assign and can not close tasks.

### ISSUE THREAD

**Issue by bhiscox** [osTicket/osTicket#2799]
In addition to the bug I reported with Tasks not saving who they are assigned to (https://github.com/osTicket/osTicket-1.8/issues/2728)  I have found two more bugs.

If you assign a due date to a task when creating it then when the task is created/saved it DOES NOT save the due date and there is no way to add it.

Additionally when entering the task whether you are the person who it's been assigned to (you have to go back in and assign it after) you can NOT CLOSE it, the only thing you can do from inside the task is delete it. If you are on the list of tasks page outside the individual task you can change the status properly.

**Comment by t-oster** [comment]
may be a dulicate of #2547 ?

**Comment by akashkumardce** [comment]
To fix the issue of saving duedate-

In file - include/class.tasks.php
Line -
            `$task->duedate = $vars['internal_formdata']['duedate'];`
Should be replaced by-
            `$task->duedate = date('Y-m-d G:i:s',Misc::dbtime($vars['internal_formdata']['duedate'])); `
It creates duedate to be in insertable format for database, and hence fixes the issue

**Comment by bhiscox** [comment]
What line is it supposed to go under? You left that out of the email.

**Comment by bhiscox** [comment]
@akashkumardce your two fixes worked well now it seems the only thing I see now is a problem where alerts aren't going out on tasks or due dates (I turned on all the notifications I could).

**Comment by zeeshankhurshid** [comment]
@akashkumardce :+1: Thanks for the solution, this work like a charm.

**Comment by akashkumardce** [comment]
https://github.com/osTicket/osTicket/pull/3100/commits/e68ec9c01076b4e2e5ee58088627e70946d5b192

Fixes the issue

**Comment by jjjeroenski** [comment]
Thanks for the solution, it works!
