### ISSUE TITLE
Problem in email authentication [IMAP] 

### ISSUE THREAD

**Issue by zeeshankhurshid** [osTicket/osTicket#2801]
Hi,
   I was able to authenticate one of my email id for one help topic but when I was trying to add a new email id for another help topic each time its giving me "Can not authenticate to IMAP server: [ALERT] Please log in via your web browser: https://support.google.com/mail/acco ".
                                          Both the email ids are of gmail, both having their IMAP enabled in settings, I double checked password and config settings but still the result is same. 

Please suggest any solution.

**Comment by GoodbyeWorld** [comment]
I had issues with gmail logins, and in addition to needing to enable imap/smtp/etc. in gmail, I needed to configure the account (in google account settings) to allow "less secure" authentication methods.  Maybe you've done this for one, but not the other.

https://support.google.com/accounts/answer/6010255?hl=en

**Comment by zeeshankhurshid** [comment]
My first check was on this only. Both are having "less secure" authentication method allowed.
