### ISSUE TITLE
1.9.12 Default Status Empty - Cannot View Ticket Details - Cannot Open New Tickets

### ISSUE THREAD

**Issue by hossvw** [osTicket/osTicket#2802]
Also commented in another thread, but just in case, I am creating a new one.

Randomly yesterday while running 1.9.11 on a setup that's been running for over 2 years, I noticed I could not get into any of my tickets.  I could see the list just fine, but when I select one to see the details I just get a blank screen.

I upgraded to 1.9.12 this morning to see if that would fix it with no luck.

I noticed that the Default Status is empty and could be causing the issue.. but I have no clue why this started or how to fix it.  I added a new custom status and linked it to open to see if I could set the default to that but it didn't help.

Users can also not open new tickets.

Any tips here?

![screen shot 2015-12-17 at 8 17 48 am](https://cloud.githubusercontent.com/assets/16339198/11875067/a05fed08-a497-11e5-89e1-a9e635104961.png)
![screen shot 2015-12-17 at 8 20 08 am](https://cloud.githubusercontent.com/assets/16339198/11875068/a0708654-a497-11e5-8fd6-27b78f572598.png)

**Comment by ntozier** [comment]
" I just get a blank screen"
This indicates a PHP error.  Please consult your PHP error log or enable error displaying to see what the error is.

Some more details [versions/softwares] about your setup might be helpful also. (PHP, webserver, etc)
