### ISSUE TITLE
user can't received email

### ISSUE THREAD

**Issue by herdi89** [osTicket/osTicket#2809]
hi... i'm using office365 as my email.
but when i try to diagnostic the email, i got the notification that the email was sent successfully.
But when i checked in my email, i didn't receive that email?

here is my setting below. can you help me? thank you.
image
![image](https://cloud.githubusercontent.com/assets/16377998/11925460/1da567e4-a7ee-11e5-9abd-e5492cb435df.png)

**Comment by greezybacon** [comment]
Is it going to spam? That is usually the case. The "green bar" should mean that Office 365 accepted the mail for delivery. It should either then arrive at the inbox or the spam box.

**Comment by herdi89** [comment]
hi greezy,

Thank  you for your reply. I already check in the spam box, but there is no email from OS Ticket, I already checked it from web mail and also from outlook.

**Comment by greezybacon** [comment]
What version of PHP and osTicket are you using?

**Comment by herdi89** [comment]
Hi Greezy,

this is the version that I using 
![image](https://cloud.githubusercontent.com/assets/16377998/11947926/295e3f36-a8a0-11e5-8d19-11829477237a.png)

**Comment by ntozier** [comment]
You should upgrade.

**Comment by herdi89** [comment]
hi ntozier, 

which one i should upgrade it?

**Comment by ntozier** [comment]
osTicket.

**Comment by herdi89** [comment]
hi Ntozier,

I think i already using the latest OS ticket version which is 1.9

**Comment by mfelber** [comment]
1.9.12 is the actual stable release. In older versions are more bugs. 

You can see the fixed bugs in the release notes: https://github.com/osTicket/osTicket-1.8/releases 

It is better for both sides to use the latest stable release. You have less bugs in your environment and it is easier to support you..

**Comment by herdi89** [comment]
hi mfelber,

right now i already install os ticket version 1.9.7 on my old place.
![image](https://cloud.githubusercontent.com/assets/16377998/11951589/ba4a6c76-a8c4-11e5-9954-318bdb51ae5e.png)

and when i try to instal in a new place, the sql server and PHP version is little bit different.
![image](https://cloud.githubusercontent.com/assets/16377998/11951603/d2abb0cc-a8c4-11e5-8eb8-832951f9d569.png)

So is it cause due to the sql server which i installed in a new one is too high? Because if i see in the OSTicket version both of them are same. So my conclusion, i think the problem with osTicket version is not the main problem.

**Comment by mfelber** [comment]
I have noticed that an environment with php 5.6.x could have mail problems with osticket: https://github.com/osTicket/osTicket-1.8/issues/2628

I'm not aware of sql issues..

**Comment by herdi89** [comment]
hi mfelber, 

I will try to downgrade my php with 5.5 version.

If there is any more progress, I will inform you guys.

**Comment by ntozier** [comment]
1.9.7 is still old and you should upgrade to 1.9.12.

**Comment by herdi89** [comment]
Dear All,

Merry christmas for all of you.

Today I already reinstall my XAMPP with PHP version 5.5.
and also i already used the latest osticket which is 1.9.12

but when i try to setting the smtp again, I still got a problem.

my osticket version 
![image](https://cloud.githubusercontent.com/assets/16377998/12013857/808f2b74-ad52-11e5-9dd0-604f291affb4.png)

the screenshot error when setting SMTP server
![image](https://cloud.githubusercontent.com/assets/16377998/12013887/fb71c202-ad52-11e5-937f-5914815a0be4.png)

using port : 587
![image](https://cloud.githubusercontent.com/assets/16377998/12013880/e963f4ea-ad52-11e5-87e3-b56d31ef5292.png)

using port : 465
![image](https://cloud.githubusercontent.com/assets/16377998/12013897/1814f5a0-ad53-11e5-8f20-a1c8cb4be46e.png)

**Comment by herdi89** [comment]
Dear All,

I want to update,

For the SMTP i should using port 25 instead 587 or 465. But it still for gmail.

![image](https://cloud.githubusercontent.com/assets/16377998/12014063/46d12ff4-ad57-11e5-8e41-024c04fafda4.png)

I will try using for office365 now.

**Comment by herdi89** [comment]
Dear All,,

Any information which you can give me to resolve this problem? Everything that related with OS Ticket and Office365 can be very usefull. Because I already tried everything, but still can't find any solution. Thank you..

**Comment by herdi89** [comment]
Dear All, 

Do you have another idea for my problem?

Kindly need your suggestion and your idea.. Thank you.

**Comment by ntozier** [comment]
My only other suggestion is ditch XAMPP.  
Install and configure your Apache, MySQL, and PHP yourself.

**Comment by herdi89** [comment]
Hi ntozier,

If I do the configure myself, are you sure it can works with office365? still got no problem?

**Comment by ntozier** [comment]
Other people have posted on the forums that they are using osticket with Exchange 365.

**Comment by sumimura** [comment]
hi all... i also have some issue with my osTicket and also Office365... it still can't receive notification email  from Osticket when I tried to test diagnostic and create new ticket. Anyone can help me?
