### ISSUE TITLE
PHP 7 Compatibility

### ISSUE THREAD

**Issue by danielc1234** [osTicket/osTicket#2815]
Hi,

When will osticket be compatible with PHP 7?

Or better question, is there a way to make the 1.10.rc.1 version work with PHP 7?

We upgraded our servers and osticket crashed. So bummed and really need to get it working again.

Thanks
Dan

**Comment by ntozier** [comment]
This appears to be a duplicate issue report to: https://github.com/osTicket/osTicket-1.8/issues/2602

**Comment by danielc1234** [comment]
Yeah, just noticed that. I'll follow over there and hopefully greezybacon can help me out.

**Comment by war59312** [comment]
Dan, you should close this 1 then.

**Comment by greezybacon** [comment]
This is now fixed in the `develop` branch. Thanks for the posting
