### ISSUE TITLE
Feature Request: Recurring Preventative Maintenance Tickets/Tasks

### ISSUE THREAD

**Issue by phantomofrussia** [osTicket/osTicket#2816]
Hello,

I would like to request a feature where you can setup recurring tickets that the system will create every week/month/days so we can maintenance tasks or tickets. This way we do not have to remember to create these tasks/tickets ourselves but have it setup in the system to be done automatically. 

This is one of the features that I would really like to see. This would help me sell this to management instead of the ticketing system we pay yearly for. 

Thanks,
Simon

**Comment by ntozier** [comment]
Setup a calender app that sends email reminders.
Set the email to send to your ticket system.

**Comment by phantomofrussia** [comment]
That is an option that I have found people doing but wouldn't it be better to have it built into the software? This way you do not have to go to a completely different website to have this completed.

**Comment by jdelhome3578** [comment]
:+1:

**Comment by bwhatley87** [comment]
I accomplished this using a cron-job and an API/PHP. It works very well... We even change ticket details through variables from the cron job.

**Comment by phantomofrussia** [comment]
Hi bwhatley87, could you give some more details on how you setup the API/PHP and cron-job?

greezybacon - any idea when this might be implemented into osticket?

Thanks

**Comment by ntozier** [comment]
@phantomofrussia 
**Re: "greezybacon - any idea when this might be implemented into osticket?"**
Neither He nor any other dev has ever said that it would be implemented.  So you are not likely to get an answer to this question.

**Comment by phantomofrussia** [comment]
@ntozier 

On Dec. 29th greezybacon labeled this as an enhancement. Because of that I assumed this is something the devs will add to osticket in the future.

**Comment by ntozier** [comment]
@phantomofrussia your assumption is an assumption.  
It means that it is not a bug report, and is an enhancement request.

**Comment by samogon13** [comment]
[clik](http://smart-itc.com.au/osticket-automatic-scheduled-tickets/)

**Comment by robintoy** [comment]
Good post @samogon13 
This is excellent and just what the doctor ordered!!!

But looking at the road map for osTicket, what would be good is to have this converted to "Tasks" which is introduced in V1.10.x.

I think the dev's will agree this is a great bit of code and perfect place for it (Maybe something better than FAQ's but easy to edit)

**Comment by robintoy** [comment]
For us using this or a modded version of this just for backup log checking / recording would be great!
