### ISSUE TITLE
Typeahead confuses users

### ISSUE THREAD

**Issue by t-oster** [osTicket/osTicket#2817]
Right now, if you type and press enter, you get the query string you typed. But if you type and wait a second for the typeahead ajax call to finish and then press enter, you get the first typeahead match as query string, which may lead to totally different results.

So the behavior of the system depends on the speed you type.

In our organization I had to change typeahead to NOT select the first result automatically, so if you hit enter you always search for exactly the string you typed. If you want one of the typeahead matches, you can just click on them.

One quick-fix is here:

```
# This patch file was generated by NetBeans IDE
# It uses platform neutral UTF-8 encoding and \n newlines.
--- a/scp/js/bootstrap-typeahead.js
+++ b/scp/js/bootstrap-typeahead.js
@@ -177,8 +177,8 @@
         i.find('a').html(that.highlighter(item, orig))
         return i[0]
       })
-
-      items.first().addClass('active')
+      //suggested fix from https://bibwild.wordpress.com/2013/04/04/overriding-bootstrap-typeahead-to-not-initially-select/
+      //items.first().addClass('active')
       this.$menu.html(items)
       return this
     }
```

**Comment by ntozier** [comment]
Where do Users have type ahead?  I think that you mean Agents.

**Comment by t-oster** [comment]
sorry, of cause I mean agents.

**Comment by greezybacon** [comment]
@t-oster, I agree with you. The inconsistent handling of the [Enter] key is confusing. Perhaps we just need an option to the typeahead widget which should be used here to disable usage of the [Enter] key

**Comment by chrisscotweb** [comment]
So this is still a problem in 1.10..
@t-oster 's solution needs additional upgrade:

```
diff --git a/scp/js/bootstrap-typeahead.js b/scp/js/bootstrap-typeahead.js
index fffa189..6efc537 100644
--- a/scp/js/bootstrap-typeahead.js
+++ b/scp/js/bootstrap-typeahead.js
@@ -43,18 +43,19 @@
     constructor: Typeahead
 
   , select: function (e) {
-      var val = JSON.parse(this.$menu.find('.active').attr('data-value'))
-        , text
-
-      if (!this.strings) text = val[this.options.property]
-      else text = val
-
-      this.$element.val(text)
-
-      if (typeof this.onselect == "function")
-          if (false === this.onselect(val, e))
-              return;
-
+      if (this.$menu.find('.active').length) {
+        var val = JSON.parse(this.$menu.find('.active').attr('data-value'))
+          , text
+  
+        if (!this.strings) text = val[this.options.property]
+        else text = val
+  
+        this.$element.val(text)
+  
+        if (typeof this.onselect == "function")
+            if (false === this.onselect(val, e))
+                return;
+      }
       return this.hide()
     }
```

I completely agree about the confusion.  Also, I find it confusing in general that the search does different things depending on if it's "lookahead" mode - it seems unnecessarily limiting.  It could instead quite easily use the logic "if an email is present in the query, remove it and filter by it", or "if request query is numeric, filter by ticket number".  Some of my users want to be able to search via email AND other text (perfectly normal request).
