### ISSUE TITLE
v1.10-rc.2 install error with php7.0

### ISSUE THREAD

**Issue by raykai** [osTicket/osTicket#2819]
cant install v1.10-rc.2 1st setup page giving a error 500 
php7 error log :
PHP Fatal error:  Cannot declare class Error, because the name is already in use in /***/include/class.error.php on line 0

install runs ok with PHP 5.6 but not with PHP 7.0

**Comment by ntozier** [comment]
osTicket is not supported with PHP7 at this time.

See
https://github.com/osTicket/osTicket-1.8/issues/2815
and
https://github.com/osTicket/osTicket-1.8/issues/2602

**Comment by greezybacon** [comment]
This is now fixed in the `develop` branch. Thanks for the posting

**Comment by 4nanook** [comment]
I am getting this same error with osTicket Core, v1.10-rc.3 using PHP7.

**Comment by HermesTrismegistus** [comment]
The error class, that's located in the includes folder class.error.php. The class inside this file which is named error, needs to be renamed to something else, if you want to run the install. But after the install multiple php errors are displayed inside the apache logs. So there still a lot of issue's to fix. Especially regarding smtp and imap settings etc. Which is of course the most essential part....
