### ISSUE TITLE
v1.10-rc.2 (231f11e) order issue

### ISSUE THREAD

**Issue by centoasa** [osTicket/osTicket#2825]
the sort order don't work; maybe I've setup a different numbering ticket?

**Comment by greezybacon** [comment]
@centoasa could you provide a screenshot to describe what you're talking about?

**Comment by k9buddy** [comment]
is it same problem? . please see my screenshot it only sort ticket ID in same page. i can't sort the latest ID to page 1 

![untitled](https://cloud.githubusercontent.com/assets/16252605/12046419/3b9d654a-aeeb-11e5-8ab7-2463e5e06131.png)

**Comment by centoasa** [comment]
https://www.evernote.com/shard/s272/sh/a2534c57-5615-49fb-af01-09cfc9e746c6/4fb7e79392e6752323bdedb3253e07c4
Ordered by most recently closed, it's not true because as you can see is 7/17 and it is the first ticket, the last recently closed is the first on the last page

**Comment by greezybacon** [comment]
@centoasa perhaps the wording is a bit confusing. 7/17 occurs AFTER 6/24. Therefore the 7/17 ticket was closed MORE recently and floats higher. You can click the sort option again (I think) to reverse it.

**Comment by greezybacon** [comment]
And concerning the numbering feature, we recommend static additions be added to the *end* of the ticket number because sorting is attempted numerically. Therefore 15-12345 is considered for sorting up to the first non-digit character, or just `15`. So therefore, if all your ticket numbers start with `15-` then they will sort randomly

**Comment by centoasa** [comment]
Happy new year!
Sorting on most recently closed, the first you can see is true, but second ticket was closed 6 month ago, but on the last page there are ticket closed really most recently.
Click again on sorting most recently the first ticket is always 17/07/15 17.41

**Comment by greezybacon** [comment]
I wanna say that particular issue has beed addressed at some point in the v1.10 branch. Could you try with the tip of the `develop-next` branch?

**Comment by centoasa** [comment]
I must update with all files in develop-next?

**Comment by greezybacon** [comment]
@centoasa yeah, I would recommend a `git pull` on the `develop-next` branch. To download again, visit the code page above, then select the `develop-next` branch from the tag/branch dropdown. Then download the zip archive and extract.

**Comment by centoasa** [comment]
Just installed develop-next
Ordering now works great! But disappear the reply ticket button on header

**Comment by ntozier** [comment]
That sounds like a separate issue.

**Comment by centoasa** [comment]
the button was "answered" (sorry for mistake)
