### ISSUE TITLE
[1.10RC2] Full text search with piped emails

### ISSUE THREAD

**Issue by antarex-be** [osTicket/osTicket#2829]
Currently evaluating 1.10RC2, i'm facing a problem with the full text search : the search does not work with ticket created via API (emails piped with automail.php)

When i create a ticket through the web interface, no problem, i can search any word included in the ticket, but when i create the ticket through the API (with automail.php), the search does not work, when i search any word included in the ticket, the result is no ticket found.

**Comment by greezybacon** [comment]
Do you notice any difference in the `ost__search` table for such tickets? The `object_type` for ticket info is `T`, and for thread entries is `H`

**Comment by antarex-be** [comment]
For tickets created through automail.php, i have a record object_type T with the mail subject, but i do not have any record object_type H with the mail body.  For tickets created through the web interface, i have the two records, T & H

**Comment by greezybacon** [comment]
I think this is caused because there are images in the emails which cause the body to have to be rewritten before it is saved and indexed. Could you test with an email without any images. Also, I thought this bug was fixed in v1.9.12 and also in v1.10 with the ORM overhaul.

**Comment by antarex-be** [comment]
No, there is no image, no html, the email are text/plain, not even multi-part

**Comment by greezybacon** [comment]
@antarex-be I'm not sure what would cause that
