### ISSUE TITLE
New agent password

### ISSUE THREAD

**Issue by A-Lawrence** [osTicket/osTicket#2834]
When creating a new agent, it attempts to set a password on an agent that doesn't yet exist.  Thus, when the user attempts to login they are unable to.

**Comment by ntozier** [comment]
Version of osTicket?
What leads you to this conclusion?

**Comment by A-Lawrence** [comment]
Latest dev version.

When creating an agent, and clicking "set password" and entering my own choice of password, the password field is still NULL after clicking "save".  The password can't be saved prior to the account being created.

**Comment by Chefkeks** [comment]
I also experienced this issue last year while testing 1.10-rc2 - haven't tested since, but if it's still an issue it shall definitely be fixed.
Btw I think I forgot to report that issue actually, so kudos to @A-Lawrence

**Comment by greezybacon** [comment]
I've confirmed this too
