### ISSUE TITLE
Fatal error on ticket creation via SCP

### ISSUE THREAD

**Issue by A-Lawrence** [osTicket/osTicket#2835]
Fatal error: Call to a member function getBaseUrl() on null in /helpdesk/include/class.client.php on line 64.

**Comment by simonnzg** [comment]
That's interesting as I got this: "Fatal error: Call to a member function getBaseUrl() on a non-object in /var/www/html/tickets/include/class.client.php on line 64" only a few minutes ago on a fresh pull from develop-next whilst trying to reply to a ticket.

Simon

**Comment by A-Lawrence** [comment]
This hasn't yet been merged with the development branch. It'll only appear once Jared approves the PR (he's already given it the thumbs-up: https://github.com/osTicket/osTicket-1.8/pull/2837)

**Comment by simonnzg** [comment]
Thanks for the heads-up!

**Comment by simonnzg** [comment]
I know that there's a fix, but is this ever going to be merged with develop-next?
