### ISSUE TITLE
Issue after config moved to ORM

### ISSUE THREAD

**Issue by kest874** [osTicket/osTicket#2840]
Getting the following error:

Fatal error: Cannot use object of type ConfigItem as array in /var/www/ostsupport.nasg.net/include/class.plugin.php on line 14

After merging to TIP of develop-next. 

Something is amiss with plugins and commit https://github.com/osTicket/osTicket-1.8/pull/2827

**Comment by kest874** [comment]
Worked around it by removing the plugins then re-added.

**Comment by greezybacon** [comment]
Thanks. I fixed this in 364044e

**Comment by protich** [comment]
@greezybacon  -- Below is another fix for cases where the plugin doesn't have any configuration e.g OutLook Export Plugin.

```diff

diff --git a/include/staff/plugin.inc.php b/include/staff/plugin.inc.php
index 58d4a03..6ab5b3c 100644
--- a/include/staff/plugin.inc.php
+++ b/include/staff/plugin.inc.php
@@ -1,9 +1,9 @@
 <?php
-
-$info=array();
+$info = array();
+$page = null;
 if($plugin && $_REQUEST['a']!='add') {
     $config = $plugin->getConfig();
-    if (!($page = $config->hasCustomConfig())) {
+    if ($config && !($page = $config->hasCustomConfig())) {
         if ($config)
             $form = $config->getForm();
         if ($form && $_POST)
```

**Comment by greezybacon** [comment]
@protich would you like me to commit that directly?

**Comment by protich** [comment]
I can commit it --- if you approve the changes :)

**Comment by kest874** [comment]
@protich What is the Outlook Export Plugin?  It peeked my interest.
