### ISSUE TITLE
taken ticket

### ISSUE THREAD

**Issue by centoasa** [osTicket/osTicket#2843]
The button "take ticket" open always the dropdown to assign ticket to operator (include himself) and other colleague.
But take should not open dropdown, but only the OK to confirm assignement to himself.

**Comment by ntozier** [comment]
I  haven't the foggiest idea what you are talking about.
Also what version of osTicket?

**Comment by protich** [comment]
@ntozier -- it's about "claim" button. It's coming back in V1.10 ST.

**Comment by centoasa** [comment]
Sorry, but I talked about claim button.
