### ISSUE TITLE
orm / database connectivity use

### ISSUE THREAD

**Issue by andresmoya** [osTicket/osTicket#2847]
Is it possible to use orm / built in queries / connections to connect to osticket when building a plugin, or would we have to write our own connection and queries?

**Comment by ntozier** [comment]
You can use ORM queries for your plugin.
You can also use the older db_query functions (until they are removed.. @greezybacon @protich are they going to be removed?)

**Comment by andresmoya** [comment]
Thanks for the response, is there any documentation on them on how to use them?
