### ISSUE TITLE
OSticket Cannot fetch emails. Can't connect to <domain>143: Permission denied

### ISSUE THREAD

**Issue by antopj** [osTicket/osTicket#2850]
Hello All,

Installed OSticket
issue in fetching email

Invalid login. Check IMAP settings
 Can't connect to <domain>143: Permission denied

telnet to 143 success.
working email no issues in webmail
SElinux disabled

Still not working

-Pls help..

Thanks

**Comment by mfelber** [comment]
I guess this type of question would fit better to the forum of osticket. 

Here are the guidelines: http://www.osticket.com/forum/discussion/77765/please-read-before-requesting-assistance
The version of osticket, the php version, the mail server type and a screenshot of your configured email settings in osticket for this mailbox could help to assist you better..
