### ISSUE TITLE
develop-next: Email Autocompletion (SCP) broken

### ISSUE THREAD

**Issue by t-oster** [osTicket/osTicket#2855]
If I create a new ticket, the email search does not contain the right address anymore.

Before (somwhere commit 3e47a230e6a0ffeca85a7f9896a0fa5f3e5465bf)
![vorher](https://cloud.githubusercontent.com/assets/1052720/12260225/e6c18990-b91a-11e5-93bb-93d4cb5f5e09.png)

After (at commit 364044e8552c8ba64dd25026dc39c873538face3):
![after](https://cloud.githubusercontent.com/assets/1052720/12260232/eca4a00e-b91a-11e5-8b35-1b38044b3b46.png)

I don't have time to bisect further right now, but maybe someone else can...

**Comment by greezybacon** [comment]
I noticed this at the tip of `develop-next` too

**Comment by t-oster** [comment]
I bisected and this e02ab7baa473ae319cefed520d67737d88ed56d6 seems to be the bad commit.

**Comment by philbertphotos** [comment]
Any working FIX for this issue hard to tell what has changed or needed.
