### ISSUE TITLE
incoming emails from outlook <!</style> appears in the ticket thread

### ISSUE THREAD

**Issue by DanYNWA** [osTicket/osTicket#2856]
![screen](https://cloud.githubusercontent.com/assets/11150436/12264221/20cf9a8e-b92d-11e5-90f0-5c95f824cae6.png)

when a client post a response using outlook <!<//style> appears in the ticket thread instead of the original message.

**Comment by greezybacon** [comment]
I've seen this one before. What version of osTicket are you using?

**Comment by ntozier** [comment]
And what version of Outlook?
And what format are you sending email in?

**Comment by DanYNWA** [comment]
im using 1.9.12 version

**Comment by DanYNWA** [comment]
not sure on the version of outlook whatever version is the latest using
outlook.com (i don't use it that was just checking to see if it worked
using outlook in case clients use it)

**Comment by DanYNWA** [comment]
I am still having issues with this. can anyone help me?

 thank you.

**Comment by manrobal** [comment]
We have the same issue since we upgraded osTicket to 1.9.12 version. Some client responses only contains the "<!<//style>" string. We had no idea the reason until I find this thread. 

Any help?

Thanks!
