### ISSUE TITLE
following a path recommendation on install for Ajax made osticket not work

### ISSUE THREAD

**Issue by dhpennell** [osTicket/osTicket#2859]
PHP Version => 5.4.16 on a CentOS 7.

The two things our vanilla php.ini didn't have (warnings) according to the install were a time zone and, I think, path translation. The latter, suggested to make AJAX work better,  wrecked the whole install, and even reverting to our old php.ini, restarting the server, didn't help. 

We deleted the contents of our mysql database and reinstalled osticket from scratch with just the time zone set and everything was fine.

**Comment by dhpennell** [comment]
By wrecked i mean blank page. Also going directly to pages by name caused blank pages or errors.

**Comment by ntozier** [comment]
Version of osTicket?
A blank page indicates a PHP error, please consult your PHP error log.
