### ISSUE TITLE
LDAP Login slow

### ISSUE THREAD

**Issue by cornelldevelopments** [osTicket/osTicket#2860]
Hello,

I've installed osticket 1.9 and successfully installed and configured the LDAP plugin.

When users login however, it takes about 30 seconds to log them in. Even if they've logged in before and their account has already been created.

I've tried this on other versions of osticket but it's the same with all. LDAP is installed properly but users take ages to be logged in.

Any help would be much appreciated.

Cheers

**Comment by ntozier** [comment]
osTicket 1.9? There are 20 different versions of osTicket 1.9. Which version are you running?
Which version of the LDAP plugin are you running?  It is a .phar or extracted?
What LDAP server are you running?
Which version of PHP are you running?
How many hops is it from your webserver to your LDAP server?

**Comment by cornelldevelopments** [comment]
Currently, I'm running 1.10-rc2. But I've also tried and same issue on 1.10-rc1, 1.9.9, 1.9.11 and 1.9.12. My point was any version I tried same issue.
The plugin version is 0.6.2. and is a phar file.
The server is MS server 2008 R2.
PHP version 5.4.
Not sure how to calculate the hops. The webserver is hosted externally on a standard cpanel webhost.

The other thing is, using LDAP for agents to log in is almost instant. But it's just the users that are slow. Almost like it's trying to authenticate locally first for ages before trying LDAP authentication...

**Comment by ntozier** [comment]
Do a traceroute from the webserver to the AD server (or vice versa).  
You could also do a continuous ping to see what the latency is.

Since before the ldap plugin was released I've been running my own in house AD and IIS server, and I have never had login time like you describe.

**Comment by cornelldevelopments** [comment]
It shows 30 hops and an average ping time of 30ms between our internal AD and the external host. Also, as mentioned, agents are authenticated instantly but users take long. However with agents, you have the option in the osticket back-end to choose "LDAP" authentication only. Whereas users don't have this. This is what makes me suspect it's taking long attempting something else before trying ldap authentication for users...

**Comment by cornelldevelopments** [comment]
I just copied osTicket to an internal web server. Now authentication takes like 2 seconds. So I guess the 30 seconds it takes when it's hosted externally is used up on latency and communication perhaps...
