### ISSUE TITLE
Advice regarding plugin, new ticket creates two events

### ISSUE THREAD

**Issue by tuudik** [osTicket/osTicket#2863]
Hi,
I've modified @thammanna plugin to work with Rocket.Chat https://github.com/tuudik/osticket-rocketchat/
Added some features from @laufhannes fork.

But there is one thing that bugs me. Currently when new ticket is created, plugin will make double notifications:

```
osticketbot @osticketbot BOT 10:29 
Message by ...
Ticket CTS-341797: Again test
drtomasso commented on Aug 25, 2014 Hi We're using Slack (https://slack.com) as our internal chat solution, and I'm trying to integrate osTicket into Slack. I need osTicket to send a POST request to Slack with relevant data as client name and subject, when a new ticket is created (either by ...

osticketbot @osticketbot BOT 10:29 
New Ticket <https://.......?id=15> by .... (....@...)
Ticket CTS-341797: Again test
drtomasso commented on Aug 25, 2014 Hi We're using Slack (https://slack.com) as our internal chat solution, and I'm trying to integrate osTicket into Slack. I need osTicket to send a POST request to Slack with relevant data as client name and subject, when a new ticket is created (either by ...
```

How could I modify the plugin, so it would send only the "New Ticket" alert and not "Message by"?
What would be best way considering osTicket features?

**Comment by philbertphotos** [comment]
I was working on a plugin that used "Signal::connect('model.created" the best thing to do is a json_encode the array and look for what you need so it only triggers in its a new ticket.

Short example : 
 function bootstrap() {
        self::$config = self::getConfig();
 
        $object = Signal::connect('model.updated', array('ClosedAlertPlugin', 'closedTicket'));
    }
    
    function closedTicket($object){
        global $ost;
        $email=true;
        //$ost->send($object->getEmail(), 'Alert Test', 'This is the body',null,null);
        //errorlog('info','ClosedAlertConfig', self::$config->get("alert_dept"));

        //Only fire if this is a ticket and it is closed.
     if (get_class($object) == "Ticket" && $object->getState() == 'closed') {
---------------------------------------------

I think you can figure out the rest

**Comment by tuudik** [comment]
Thank you for the hint @philbertphotos 

Searched through source, found this:
```
                COUNT(*)-COUNT(NULLIF(A1.state, "created")) AS Opened,
                COUNT(*)-COUNT(NULLIF(A1.state, "assigned")) AS Assigned,
                COUNT(*)-COUNT(NULLIF(A1.state, "overdue")) AS Overdue,
                COUNT(*)-COUNT(NULLIF(A1.state, "closed")) AS Closed,
                COUNT(*)-COUNT(NULLIF(A1.state, "reopened")) AS Reopened
```

So, my logic says, I can use something like this:
```
if (get_class($object) == "Ticket" && $object->getState() == 'created') {
```

**Comment by tuudik** [comment]
I must say, didn't work as expected:(

**Comment by philbertphotos** [comment]
Sorry that did not work let me see what i can dig up for you.

**Comment by philbertphotos** [comment]
Take a look at this it may help you.
https://github.com/poctob/OSTEquipmentPlugin/wiki/Plugin-Development-Part-5-Signals

**Comment by philbertphotos** [comment]
I found a workaround for the double posting if you still interested.

**Comment by philbertphotos** [comment]
Finally found a fixed. Let me know if you are interested.

**Comment by RogueTiger** [comment]
@philbertphotos - I'm interested! I just set up this integration and streamlining it would be awesome. Thanks!

**Comment by philbertphotos** [comment]
This is kinda Hacky but works last time I tested it last year till now while working on the plugin

    function onTicketUpdated($object)
    {        global $ost;
        // Only fire if this is a ticket and it is closed.
	        if (get_class($object) == "Ticket" && $object->getState() == 'closed') {
            $selecteddept = self::$config->get("alert_dept");
            $memb = array();
            $manb = array();
            $userinfo = array();
            $staffinfo = array();
			
		foreach(($object->getMessages()->constraints) as $evn) //Avoids double closing messages.
				$chk++; //Lets check if it ran already
			if ($chk > 3) //If greater than 2 then return
				return;
            $clsmsg = self::$config->get("closedmsg");
            self::logger('info', 'ClosedAlertObject', $object);
            self::logger('info', 'ClosedAlertCheck', $chk); //I think this was debugging.
			self::logger('info', 'ClosedAlerttime', microtime(true));
            foreach($selecteddept as $id => $deptname) {
                if ($id == $object->getDeptId()) {
                    // check agent that are dept members and have alerts turned on
                    $memb = self::getDeptMembers($id, $object->getStaffId());
                    // $manb = self::getManagers($id,$object->getStaffId());
                    foreach($memb as $id) {
                        $tempinfo = self::getUserInfo($id['staff_id']);
                        $staffinfo = array_merge($staffinfo, $tempinfo);
                    }
                }
            }
            self::logger('info', 'StaffInfo', $staffinfo);
        }
    }

**Comment by philbertphotos** [comment]
Let me know if you get it.
