### ISSUE TITLE
Ablity to select canned responses for multiple Departments

### ISSUE THREAD

**Issue by philbertphotos** [osTicket/osTicket#2867]
Right now you can set canned responses to one department but in my shop we have a need for that same response to be available in multiple departments would be a nice feature.

Since its getting hard to since we have no choice but keep the default of "All Departments" is becoming an organization problem.

![01162016-110126](https://cloud.githubusercontent.com/assets/2892474/12373169/ffd0059a-bc46-11e5-895e-f5dca2a2fad7.png)

**Comment by dscanal** [comment]
**it could be a multiple choice checkbox
and also to a group or specific technical**

> podría ser con un checkbox de selección multiple
> y también a un grupo o técnico especifico
