### ISSUE TITLE
1.10 (364044e8) error saving pages

### ISSUE THREAD

**Issue by JohnDelisle** [osTicket/osTicket#2868]
When I edit a page (via Admin -> Manage -> Pages, select a page, and make a change) I get the following error on-screen and in my ssl error log:

Warning: Invalid argument supplied for foreach() in /opt/osTicket-git/osTicket-1.8/include/class.page.php on line 322

**Comment by GoodbyeWorld** [comment]
Update:  Just to be sure it wasn't specific to my install, I did a clean fresh install of 1.10 (364044e8), and the issue is there.

**Comment by webunraveling** [comment]
I've just discovered the same issue, using v1.10-rc.3. Not using SSL. Language is English/default.
