### ISSUE TITLE
XSS Vulnerability - open.php

### ISSUE THREAD

**Issue by mattkoch614** [osTicket/osTicket#2871]
The open.php (New Ticket) page is vulnerable to XSS attacks. I was able to change my profile "Full Name" field to the following:

```
"<script>alert("vulnerable")</script>
```

This resulted in the script being executed when I loaded the open.php page (see attachment).

![xss_vulnerability](https://cloud.githubusercontent.com/assets/8203609/12430382/528a5754-bebd-11e5-892f-04e2ed3ff0d5.PNG)

**Comment by Chefkeks** [comment]
What version of osTicket are you running?

**Comment by ntozier** [comment]
I can confirm that this can be done on 1.10rc2.

Side note: the name field appears to be limited to 128 characters.

**Comment by noleafclover614** [comment]
@chefkeks
1.9.12

**Comment by Chefkeks** [comment]
Thanks!

I sure @protich @greezybacon will take care of that.
