### ISSUE TITLE
File attachment extension validation

### ISSUE THREAD

**Issue by noleafclover614** [osTicket/osTicket#2872]
File extension validation for attachments is not enforced server side - only locally via JavaScript.  Is this something that is being considered for a future release?

**Comment by noleafclover614** [comment]
Moving this to https://github.com/osTicket/core-plugins/issues

**Comment by protich** [comment]
The issue addressed in commit fdad9239 - to be merged into the upcoming release.

Thanks,

**Comment by noleafclover614** [comment]
We've noticed inconsistent behavior on the staff administration page (```/scp/tickets.php```) vs. the "end user" facing page (```/tickets.php```) for tickets.  The ```ajaxUpload``` function is called when uploading files from both interfaces.

The ```isValidFileType()``` function inside of ```ajaxUpload()``` is supposed to check for allowed **mimetypes** and file **extensions** before allowing a file to be uploaded.  For the end user facing page, this function appears to load the configured allowable mime types and extensions just fine.  On the ticket page for staff, however, this data does not appear to be pulled in at all, resulting in empty arrays when performing the validation check.

Essentially this means that there are no file upload restrictions being enforced for files uploaded by staff members.

ajaxUpload function for reference:

https://github.com/osTicket/osTicket-1.8/blob/fdad9239600b92bdf53144ee0ec4a29969bf2570/include/class.forms.php#L2647-L2663

**Comment by Chefkeks** [comment]
Aren't the settings regarding file mimetypes and extensions only for end-users?

Currently cannot look it up (on the move) but I'm pretty sure it is like that. Would need to verify under Admin Panel > Settings > Tickets (or System?) > Attachment Settings tomorrow/next week unless you're faster @noleafclover614 :D

**Comment by protich** [comment]
@noleafclover614 - osTicket doesn't restrict agents uploads. The rationale being, an agent should be able to send any file type to end users.  

In the future, we're planning on making response and internal note forms configurable just like Ticket Details form -- allowing for ability to restrict or even disable attachments.

**Comment by noleafclover614** [comment]
@protich Thanks, I didn't know that this was by design.
