### ISSUE TITLE
Search Timing Out and Eating CPU

### ISSUE THREAD

**Issue by dotcade** [osTicket/osTicket#2875]
When a search query is entered into OsTicket, the CPU usage spikes up 85% and the mysql57.exe process begins to eat up the CPU. In the browser when you perform the search it takes about 15-16 seconds and then it just times out.

We did not originally have this issue when we were running it on XAMPP. 

The VM has 6gb of ram and 4 cores.

OSTicket: 1.9.7
MySQL: 5.7.10
PHP: 5.6.12

**Comment by ntozier** [comment]
1.9.7 is old, you should upgrade to current.

**Comment by palemouse** [comment]
This issue is occurring for me on 1.9.12
MySQL: 5.7.10
PHP: 5.6.17

An example of the offending query (searching for a keyword of "monitor"):

SELECT DISTINCT COALESCE(B1.ticket_id, B2.ticket_id, B3.ticket_id, B4.ticket_id) FROM (
                SELECT object_type, object_id, MATCH (search.title, search.content) AGAINST ('monitor' IN BOOLEAN MODE) AS `relevance`
                FROM `ost__search` `search`
                WHERE MATCH (search.title, search.content) AGAINST ('monitor' IN BOOLEAN MODE)
            ) `search` LEFT JOIN (select ticket_id as ticket_id from ost_ticket
            ) B1 ON (B1.ticket_id = search.object_id and search.object_type = 'T') LEFT JOIN (select A2.id as thread_id, A1.ticket_id from ost_ticket A1
                join ost_ticket_thread A2 on (A1.ticket_id = A2.ticket_id)
            ) B2 ON (B2.thread_id = search.object_id and search.object_type = 'H') LEFT JOIN (select A3.id as user_id, A1.ticket_id from ost_user A3
                join ost_ticket A1 on (A1.user_id = A3.id)
            ) B3 ON (B3.user_id = search.object_id and search.object_type = 'U') LEFT JOIN (select A4.id as org_id, A1.ticket_id from ost_organization A4
                join ost_user A3 on (A3.org_id = A4.id) join ost_ticket A1 on (A1.user_id = A3.id)
            ) B4 ON (B4.org_id = search.object_id and search.object_type = 'O') LEFT JOIN ost_ticket A1 ON (A1.ticket_id = COALESCE(B1.ticket_id, B2.ticket_id, B3.ticket_id, B4.ticket_id)) LEFT JOIN ost_ticket_status A2 ON (A1.status_id = A2.id) WHERE ((A1.staff_id=1 AND A2.state="open") OR A1.dept_id IN (1,3,2,4,5) OR A1.team_id IN (14,16) AND A2.state="open")ORDER BY `search`.`relevance` LIMIT 500

This query completely locks up the mysqld.exe process. The entire instance must be restarted for they query to clear and the CPU usage to go back down.

**Comment by jotbe** [comment]
Same here, fresh install on a FreeBSD 10 vServer, a handful of sample tickets. Everything is fine and fast beside searching for tickets.

osTicket: 1.9.12
nginx: 1.8.1
MySQL: 5.7.10
PHP: 5.6.18

**Comment by jotbe** [comment]
I found out that the query doesn't seem to work with optimizations for derived tables introduced with MySQL v5.7. I disabled the `derived_merge` temporarily and the query execution plan for the query was obtained instantly:

```
mysql> SET optimizer_switch = 'derived_merge=off'; 
Query OK, 0 rows affected (0.00 sec)

mysql> EXPLAIN SELECT DISTINCT COALESCE(B1.ticket_id, B2.ticket_id, B3.ticket_id, B4.ticket_id) FROM ( SELECT object_type, object_id, MATCH (search.title, search.content) AGAINST ('test3' IN BOOLEAN MODE) AS `relevance` FROM `ost__search` `search` WHERE MATCH (search.title, search.content) AGAINST ('test3' IN BOOLEAN MODE) ) `search` LEFT JOIN (select ticket_id as ticket_id from ost_ticket ) B1 ON (B1.ticket_id = search.object_id and search.object_type = 'T') LEFT JOIN (select A2.id as thread_id, A1.ticket_id from ost_ticket A1 join ost_ticket_thread A2 on (A1.ticket_id = A2.ticket_id) ) B2 ON (B2.thread_id = search.object_id and search.object_type = 'H') LEFT JOIN (select A3.id as user_id, A1.ticket_id from ost_user A3 join ost_ticket A1 on (A1.user_id = A3.id) ) B3 ON (B3.user_id = search.object_id and search.object_type = 'U') LEFT JOIN (select A4.id as org_id, A1.ticket_id from ost_organization A4 join ost_user A3 on (A3.org_id = A4.id) join ost_ticket A1 on (A1.user_id = A3.id) ) B4 ON (B4.org_id = search.object_id and search.object_type = 'O') LEFT JOIN ost_ticket A1 ON (A1.ticket_id = COALESCE(B1.ticket_id, B2.ticket_id, B3.ticket_id, B4.ticket_id)) LEFT JOIN ost_ticket_status A2 ON (A1.status_id = A2.id) WHERE ((A1.staff_id=1 AND A2.state="open") OR A1.dept_id IN (1,2,3,4))ORDER BY `search`.`relevance` LIMIT 500;
+----+-------------+------------+------------+----------+--------------------------+-------------+---------+--------------------------+------+----------+----------------------------------------------------------+
| id | select_type | table      | partitions | type     | possible_keys            | key         | key_len | ref                      | rows | filtered | Extra                                                    |
+----+-------------+------------+------------+----------+--------------------------+-------------+---------+--------------------------+------+----------+----------------------------------------------------------+
|  1 | PRIMARY     | <derived2> | NULL       | ALL      | NULL                     | NULL        | NULL    | NULL                     |    2 |   100.00 | Using temporary; Using filesort                          |
|  1 | PRIMARY     | <derived3> | NULL       | ref      | <auto_key0>              | <auto_key0> | 4       | search.object_id         |    2 |   100.00 | Using where; Using index                                 |
|  1 | PRIMARY     | <derived4> | NULL       | ref      | <auto_key0>              | <auto_key0> | 4       | search.object_id         |    2 |   100.00 | Using where                                              |
|  1 | PRIMARY     | <derived5> | NULL       | ALL      | NULL                     | NULL        | NULL    | NULL                     |    3 |   100.00 | Using where; Using join buffer (Block Nested Loop)       |
|  1 | PRIMARY     | <derived6> | NULL       | ALL      | NULL                     | NULL        | NULL    | NULL                     |    3 |   100.00 | Using where; Using join buffer (Block Nested Loop)       |
|  1 | PRIMARY     | A1         | NULL       | ALL      | PRIMARY,dept_id,staff_id | NULL        | NULL    | NULL                     |    3 |    33.33 | Range checked for each record (index map: 0xD); Distinct |
|  1 | PRIMARY     | A2         | NULL       | eq_ref   | PRIMARY                  | PRIMARY     | 4       | ffhh_ticket.A1.status_id |    1 |   100.00 | Using where; Distinct                                    |
|  6 | DERIVED     | A4         | NULL       | index    | PRIMARY                  | PRIMARY     | 4       | NULL                     |    2 |   100.00 | Using index                                              |
|  6 | DERIVED     | A3         | NULL       | ref      | PRIMARY,org_id           | org_id      | 4       | ffhh_ticket.A4.id        |    1 |   100.00 | Using index                                              |
|  6 | DERIVED     | A1         | NULL       | ref      | user_id                  | user_id     | 4       | ffhh_ticket.A3.id        |    1 |   100.00 | Using index                                              |
|  5 | DERIVED     | A3         | NULL       | index    | PRIMARY                  | org_id      | 4       | NULL                     |    3 |   100.00 | Using index                                              |
|  5 | DERIVED     | A1         | NULL       | ref      | user_id                  | user_id     | 4       | ffhh_ticket.A3.id        |    1 |   100.00 | Using index                                              |
|  4 | DERIVED     | A1         | NULL       | index    | PRIMARY                  | user_id     | 4       | NULL                     |    3 |   100.00 | Using index                                              |
|  4 | DERIVED     | A2         | NULL       | ref      | ticket_id                | ticket_id   | 4       | ffhh_ticket.A1.ticket_id |    1 |   100.00 | Using index                                              |
|  3 | DERIVED     | ost_ticket | NULL       | index    | NULL                     | user_id     | 4       | NULL                     |    3 |   100.00 | Using index                                              |
|  2 | DERIVED     | search     | NULL       | fulltext | search                   | search      | 0       | const                    |    1 |   100.00 | Using where                                              |
+----+-------------+------------+------------+----------+--------------------------+-------------+---------+--------------------------+------+----------+----------------------------------------------------------+
16 rows in set, 1 warning (0.00 sec)
```

To make this flag permanent I added it to `my.cnf`:

```
[mysqld]
optimizer_switch = derived_merge=off
```

The search function is working like a charm now. I didn't find time yet to take a more thorough look at the query itself, but I'm pretty confident that after some optimization one should be able to activate `derived_merge` again.

More information:
- https://dev.mysql.com/doc/refman/5.7/en/upgrading-from-previous-series.html
- https://dev.mysql.com/doc/refman/5.7/en/subquery-optimization.html#derived-table-optimization

**Comment by greezybacon** [comment]
@jotbe thanks for the info. Could you maybe do some testing with the `develop-next` branch and v1.10? We rewrote the searching system in hopes of better results from both MariaDB and MySQL, which have significantly different optimization engines and settings.
