### ISSUE TITLE
Fatal error: Call to a member function getBaseUrl()  [v1.10-rc.2]

### ISSUE THREAD

**Issue by balojs** [osTicket/osTicket#2876]
When i make a post
Fatal error: Call to a member function getBaseUrl() on a non-object in /Applications/MAMP/htdocs/finanzas/include/class.client.php on line 69
![screenshot](https://cloud.githubusercontent.com/assets/3303352/12456664/7d0ab1f0-bf66-11e5-95aa-b61740991a98.png)

**Comment by mfelber** [comment]
Seems to be a duplicate issue: https://github.com/osTicket/osTicket-1.8/issues/2835

**Comment by balojs** [comment]
Thanks my friend @mfelber the fix worked
![screenshot](https://cloud.githubusercontent.com/assets/3303352/12457266/383ebd7a-bf69-11e5-929b-64b4b0e37571.png)

**Comment by mfelber** [comment]
@balojs I'm glad I could help...

**Comment by balojs** [comment]
#2876 Fix Call to a member function getBaseUrl() [v1.10-rc.2]

**Comment by balojs** [comment]
Thaks

**Comment by greezybacon** [comment]
This was fixed in efe3a3e668f10f9a5f64654ab8ea42c02e732405
