### ISSUE TITLE
the validations show no entry that has Error [v1.10-rc.2]

### ISSUE THREAD

**Issue by balojs** [osTicket/osTicket#2877]
http://localhost:8888/osticket/scp/settings.php?t=tickets

![screenshot](https://cloud.githubusercontent.com/assets/3303352/12461000/44fa4a08-bf7c-11e5-82a5-ce4145e16298.png)

**Comment by balojs** [comment]
Maximum Open Tickets: no have value

**Comment by balojs** [comment]
Unable to update settings - correct errors below and try again

**Comment by jdelhome3578** [comment]
I don't have this issue. Is this a clean install or update?

**Comment by balojs** [comment]
is clean install

**Comment by jdelhome3578** [comment]
try #2880

**Comment by jdelhome3578** [comment]
Fixed in #2914

**Comment by balojs** [comment]
Thanks
