### ISSUE TITLE
Some characters problem

### ISSUE THREAD

**Issue by 666reyes666** [osTicket/osTicket#2883]
Message is partially lost when some characters are in the email

Eg:  😊
Ticket is trunked and only content before the 😊 is displayed

**Comment by ntozier** [comment]
What version of osTicket are you running?

This has been reported numerous times for older versions, and has since been fixed.  Please use search in the future.  Here are just a few I found with search:

https://github.com/osTicket/osTicket-1.8/issues/2144
https://github.com/osTicket/osTicket-1.8/issues/1259
https://github.com/osTicket/osTicket-1.8/issues/674
https://github.com/osTicket/osTicket-1.8/issues/633
https://github.com/osTicket/osTicket-1.8/pull/551
https://github.com/osTicket/osTicket-1.8/issues/1177

**Comment by 666reyes666** [comment]
My apologies if it is a duplicate.. I  didnt find it
I upgraded to v1.9.12 a few weeks ago.. This happened yesterday, fetching from gmail

About this osTicket Installation

Server Information
osTicket Version	v1.9.12 (19292ad) —  Up to date
Web Server Software	Apache/2.4.10 (Unix) OpenSSL/1.0.1e-fips mod_bwlimited/1.4
MySQL Version	5.6.28
PHP Version	5.5.18

**Comment by 666reyes666** [comment]
Message is cut at =F0=9F=98=8A

Content-Type: text/plain;
	charset=utf-8
Content-Transfer-Encoding: quoted-printable
Mime-Version: 1.0 (1.0)
X-Mailer: iPad Mail (13C75)

Bonjour, je ne sais pas si je suis vraiment incomp=C3=A9tente, mais je suis i=
ncapable de modifier mon adresse courriel dans mon compte.=F0=9F=98=8A  J'ai=
 un compte  avec mon ancienne adresse soit:  ...................

**Comment by greezybacon** [comment]
The MySQL character set we're using is utf8, which only allows up to three byte characters. The Emoji characters use four. You can manually change your database default schema and table schema (especially on %thread_entry) to `utf8mb4`, which allows four-byte characters

**Comment by greezybacon** [comment]
@protich, I personally would like to like to see the minimum requirements for MySQL move to v5.5 and the default character set change to `utf8mb4`. I'm sure this issue is going to keep coming up.

**Comment by Chefkeks** [comment]
@greezybacon
Since we already changed to utf8mb4 here, I totally agree with you, as well as MySQL 5.5

**Comment by davideakc** [comment]
I've the same problem with the 1.9.12 version of osTicket: when the system see a letter like ì è ò à (italian letters) etc... it cuts the text (not always, sometime)

For example:

![1](https://cloud.githubusercontent.com/assets/15772383/13571490/a0c55bd4-e475-11e5-9bff-170b57d0d927.png)

This is the the original mail:

[header.txt](https://github.com/osTicket/osTicket-1.8/files/161413/header.txt)

How can I fix this problem?
