### ISSUE TITLE
Hover/Popup over Filter in 1.10r2

### ISSUE THREAD

**Issue by philbertphotos** [osTicket/osTicket#2884]
Would be nice to be able to hover over a filter and see what the filter is ... as it stands you have to click on each filter to see what it does. If you have 40+ filters it gets harder.

**Comment by ntozier** [comment]
To me this mostly sounds like a case of you need to name your filters better. :)

**Comment by philbertphotos** [comment]
I do name them ... pretty well but the problem I forget what it specifically does at times and other admins dont always know so yes a mini summary would be freaking awesome.
