### ISSUE TITLE
1.10rc2 - css issue on manage form page(s) 

### ISSUE THREAD

**Issue by ntozier** [osTicket/osTicket#2886]
Tested in current versions of Chrome, Firefox, IE11, Opera.

In all but IE the Form Fields section of the page are too wide for the container they are in which results in the Delete column being shifted to the right looking messy. (see image below)

![css-issue-1-chrome](https://cloud.githubusercontent.com/assets/1315768/12623920/50a49c90-c4fa-11e5-8f8f-ae454251c41a.png)

**Comment by ntozier** [comment]
@nfebuary I think that your the one that deal with this type of thing. right?

**Comment by nfebuary** [comment]
Agreed on the label field needing to be reduced. The fields look fine until the config shows up and pushes everything over.
