### ISSUE TITLE
Double quotes in the search query returns no results

### ISSUE THREAD

**Issue by SCHOLAR-Graeme** [osTicket/osTicket#2889]
The search fails to find anything when encapsulating your search string with double quotes. This happens because double quote escaping is done twice. First here
https://github.com/osTicket/osTicket-1.8/blob/develop/include/staff/tickets.inc.php#L130
Then again here:
https://github.com/osTicket/osTicket-1.8/blob/develop/include/class.search.php#L307

Resulting in the following search string:
"Search Me"
Being converted to:
\\"Search Me\\"

Looks like you will need to remove the call to `db_real_escape` on line 130 in the tickets.inc.php file.

**Comment by ntozier** [comment]
Version of osTicket?

**Comment by SCHOLAR-Graeme** [comment]
I am using version 1.9.12 but the lines of code still exist in the develop branch.

**Comment by philbertphotos** [comment]
This happens in 1.10rc2 also.

**Comment by greezybacon** [comment]
@SCHOLAR-Graeme I think you have a good point. It looks like it is double escaped.

@philbertphotos I think you're mistaken. In v1.10, `db_real_escape` was removed from the searching code path and replaced with ORM code, which does no escaping anywhere. Values are tracked as parameters and sent separately to the database via `mysqli_stmt::bind_param` (https://github.com/osTicket/osTicket-1.8/blob/develop-next/include/class.orm.php#L2803 (from https://github.com/osTicket/osTicket-1.8/blob/develop-next/include/class.orm.php#L2770))
