### ISSUE TITLE
Please add "Last First " option to "Default Name Formatting"

### ISSUE THREAD

**Issue by kajla** [osTicket/osTicket#2896]
Without: ,
Hungarian name format is: "Last name First name", not "Last name, First name".

Thank you!

**Comment by JediKev** [comment]
What version are you running? I have the fix for you if you want it.

**Comment by kajla** [comment]
Hello,

Oh, this is good news! Thank you! :)
osTicket version: v1.9.12 (19292ad)

**Comment by JediKev** [comment]
Luckily for you its super easy, go to your osTicket files and go to include > class.user.php 
Here you will add two things:
1.) Go to line 610 (static $formats = array) and replace the whole array with this:
```
static $formats = array(
        'first' => array(     /*@trans*/ "First", 'getFirst'),
        'last' => array(      /*@trans*/ "Last", 'getLast'),
        'full' => array(      /*@trans*/ "First Last", 'getFull'),
        'legal' => array(     /*@trans*/ "First M. Last", 'getLegal'),
        'lastfirst' => array( /*@trans*/ "Last, First", 'getLastFirst'),
        'formal' => array(    /*@trans*/ "Mr. Last", 'getFormal'),
        'short' => array(     /*@trans*/ "First L.", 'getShort'),
        'shortformal' => array(/*@trans*/ "F. Last", 'getShortFormal'),
        'complete' => array(  /*@trans*/ "Mr. First M. Last Sr.", 'getComplete'),
        'original' => array(  /*@trans*/ '-- As Entered --', 'getOriginal'),
		'hungarian' => array( /*@trans*/ "Last First Hungarian", 'getLastFirstHungarian'),
    );
```
2.) Go to line 695 where you will see the getLastFirst() function and add this function after that:
```
function getLastFirstHungarian() {
        $name = $this->parts['last'].' '.$this->parts['first'];
        if ($this->parts['suffix'])
            $name .= ' '.$this->parts['suffix'];
        return $name;
    }
```

Just a warning (I'm sure you've found out by now) that on some things the name format just doesn't work, I even tried the 'Last, First' option and just on some things it wouldn't work, but most places it will most definitely work. :)

**Comment by protich** [comment]
@JediKev  - I think making a pull request would be a better answer as opposed to suggesting manual code edit. I'll have specific feedback on how to best implement it.

**Comment by kajla** [comment]
Thank you, I added this lines to include/class.user.php file. 
It works, but next update will broke this solution.
Could you add this solution to next release, please?

**Comment by kajla** [comment]
On the agent site works fine, but on the client side still not working.
On the agent site Users page:
![scp_users_active_en](https://cloud.githubusercontent.com/assets/5457824/17285903/15f8f938-57c6-11e6-90aa-93c24ee66313.png)
/red is bad, green is good/

On the client site:
![client_name_new_ticket](https://cloud.githubusercontent.com/assets/5457824/17285927/4814a0c0-57c6-11e6-9b15-60354557dc45.png)

... and:
![client_name](https://cloud.githubusercontent.com/assets/5457824/17285935/522ef524-57c6-11e6-9060-abc18a938dcc.png)

On the profile page the name is correct:
![client_name_profile](https://cloud.githubusercontent.com/assets/5457824/17285934/4e757002-57c6-11e6-8413-4aaf40e6674b.png)

If I change this:

```
 function getLastFirstHungarian() {
         $name = $this->parts['last'].' '.$this->parts['first'];
         if ($this->parts['suffix'])
             $name .= ' '.$this->parts['suffix'];
         return $name;
     }
```

... to this:
```
function getLastFirstHungarian() {
        $name = $this->parts['first'].' '.$this->parts['last'];
        if ($this->parts['suffix'])
            $name .= ' '.$this->parts['suffix'];
        return $name;
    }
```
the client name is good, but on the profile page, tickets page and the agents names are bad.

osTicket Version: v1.9.14 (8b927a0)
