### ISSUE TITLE
LDAP: FF username and password save problem

### ISSUE THREAD

**Issue by kajla** [osTicket/osTicket#2903]
Dear Developers,

I saved my username and password to Firefox, but I have got a problem with this feature on "Agent Account" panel (Admin panel --> Agents --> Agents --> My name).

FF insert username to the "Mobile Number" field:
![osticket_username](https://cloud.githubusercontent.com/assets/5457824/12776026/e5b7a28e-ca52-11e5-8e30-0f0827c80283.png)

I clear this field, but it's not enough, the error message:
![osticket_error_msg](https://cloud.githubusercontent.com/assets/5457824/12775972/6bd3482e-ca52-11e5-82cb-5df9e4b5eac4.png)

I changed LDAP to local and I see the FF insert the password to the "Password" field:
![osticket_username_w_pass](https://cloud.githubusercontent.com/assets/5457824/12776197/49be9a66-ca54-11e5-8fc4-ddb8ba2079ef.png)

osTicket version: v1.9.12 (19292ad)
Firefox version: 44.0

Could you help me, please?

**Comment by kajla** [comment]
Same as "My Preferences" page:
![osticket_my_pref](https://cloud.githubusercontent.com/assets/5457824/12778118/4d3e5bd8-ca61-11e5-9ade-b3f37ae12fd4.png)

/We can't change here the LDAP password/

**Comment by UkaLee** [comment]
password error within Firefox, try to update / change your password with chrome or IE

**Comment by ntozier** [comment]
1. This appears to be a browser issue.  What version of Firefox are you running?
2. It's simply never safe to save usernames and password in web browsers.
3. You are correct that you cannot change your LDAP password from osTicket.  This is intentional.

**Comment by kajla** [comment]
1. My Firefox version is: 44.0
Oh yes, it's a browser issue, with Opera Developer (36.0.2079.0) works fine with stored username and password:
![osticket_opera](https://cloud.githubusercontent.com/assets/5457824/12787276/07997944-ca95-11e5-8e86-25a727912171.png)

2. This is true, but my computer is password protected.

3. Can I hide it?

Thank you very much! :)

**Comment by UkaLee** [comment]
Agent Panel -> User -> Select User -> Manage Account -> Manage Access -> Check : User Cannot Change Password

**Comment by kajla** [comment]
Thank you, it's working with one user! :+1: 
But could I set it globally to work with all users? :)

**Comment by UkaLee** [comment]
No clue sorry, i will have the same problem in some days. need to import all the user and will do it one by one.

**Comment by ntozier** [comment]
I think that the easiest way to update ALL users so that they cannot change their password is to do it at the SQL level.

UPDATE ost_user_account SET status='9';

Note: I'm of the opinion that this will also affect staff accounts.
