### ISSUE TITLE
Post Installation Issues

### ISSUE THREAD

**Issue by eljagg** [osTicket/osTicket#2905]
Hi,
Can you please assist me in resolving these issues:

**Version of osTicket?**
osTicket (v1.9.12)

**Autoresponder settings?**

![auto-responder-issue](https://cloud.githubusercontent.com/assets/3020078/12793527/09e632c0-ca7f-11e5-8062-c4f5e42ccf04.png)

Q: Email confirmation no being sent out automatically.
A: Which email confirmation are you referring to? 
Client side?                         *\* => Yes**
Staff side?                          *\* =>  Yes**
New ticket alerts?               *\* =>  Yes**
New message alerts?         *\* =>  Yes**
Account setup alerts? etc  .*\* =>  Yes**

I am running OsTicket on Xammp V3.2.2 running Windows Server 2012R2

Thank you for the response and your help. What we are trying to do is get this(OsTicket) working properly then switch to the paid version. My boss wants to be convinced before this move (to paid version) is authorized.

**Comment by ntozier** [comment]
Version of osTicket?
Autoresponder settings?
Mail configuration?


Q: No Ticket number provided in auto response email.
A: Whats your email template look like for that?

Q: when I click submitting ticket ... saving to draft pops up.Same after editing ticket (saving to draft). Where does the draft gets saved to?
A: it gets saved to database. (the information in the text box.)  Specifically the ost_drafts table.

Q: Email confirmation no being sent out automatically.
A: Which email confirmation are you referring to?  Client side?  Staff side?  New ticket alerts?  New message alerts?  Account setup alerts? etc.
