### ISSUE TITLE
Cant save reopen status in UI 1.10r2

### ISSUE THREAD

**Issue by philbertphotos** [osTicket/osTicket#2908]
Every time I uncheck "Allow tickets on this status to be reopened by end users " when I press save it does not update I have to edit the database directly.

![02032016-180241](https://cloud.githubusercontent.com/assets/2892474/12799733/e1a8bf80-caa6-11e5-9dcb-0bf626031a43.png)

**Comment by protich** [comment]
PR #2767 addressed the issue -- it's already merged to the tip of develop-next.
