### ISSUE TITLE
Closed "alloworeopen" Ticket behaviour in 1.10RC2

### ISSUE THREAD

**Issue by philbertphotos** [osTicket/osTicket#2909]
Tickets cannot be updated when its closed with "allowreopen" false ... to me the behavior should be that the ticket is updated but the status is un-changed. What happens now and its pretty dam annoying a new ticket is created example "RE: Change password of extensions [#000905]" most times the user is just saying thank you ... and every time they respond it goes into that new ticket.

In my mind a few things should happen 
#1 the closed ticket gets updated but the user nor agent is alerted.
#2 The user gets a response the ticket is closed and cant be updated and its rejected.
#3 The ticket is annotated and the Agent is notified or not (could be an option)

**Comment by ntozier** [comment]
I agree with #2.  But I do not want the ticket updated, or alerts.  An internal note to the ticket would be okay.

**Comment by philbertphotos** [comment]
An internal note being created sounds good.
