### ISSUE TITLE
[SOLVED] Emails with charset iso-8859-1 are cut (v1.9.8)

### ISSUE THREAD

**Issue by molul** [osTicket/osTicket#2910]
It's been a few months since I upgraded to 1.9.8, and while I had this issue in the beginning, it wasn't so important as it only happened when the staff sent emails with iso-8859-1 charset, so I told my partners to configure their email clients to send always in utf-8. 

However, recently this problem has come back with a few new customers, and I'd rather not tell them to do the same. Is there anything I cand do to fix it in the code? I'm attaching an email source example in case it helps. 

[emailSource_ISO_charset_problem.txt](https://github.com/osTicket/osTicket-1.8/files/117111/emailSource_ISO_charset_problem.txt)

I'm also attaching a screenshot of our system information:
![osticket_system_info](https://cloud.githubusercontent.com/assets/2084933/12810533/15fca730-cb27-11e5-8bbc-90c2f67d1354.png)

Please let me know if you need more info.

**Comment by ntozier** [comment]
1.9.8 is old.  You should probably upgrade.

Also please see: https://github.com/osTicket/osTicket-1.8/issues/2883

**Comment by molul** [comment]
Thank you! Yes, I was considerating upgrading to latest version, but for me upgrading is a bit more difficult than usual, as I have to copy some pieces of code for my mod that allows staff to reply to tickets through email (as customers), so I thought I'd try finding an easier solution first, if available.

Alright then, I'll prepare the upgrade :)

**Comment by molul** [comment]
After upgrading to 1.9.12, the problem persists. Anything else I could try?

**Comment by ntozier** [comment]
Did you make the change in the thread that I linked you?

**Comment by molul** [comment]
Hi! If you mean changing the database encoding to utf8mb4, it seems I'm not able as my MySQL is 5.1. Is there anything else I could do before asking our sysadmin team to upgrade to MySQL 5.5?

**Comment by molul** [comment]
We made a test in a different server and the utf8mb4 worked alright. The problem is that upgrading our main web server to MySQL 5.5 might give some problems in some other web apps, so we're studying how to do it properly and it will take 1 or 2 months. If there's any quick fix we could do in the meantime not to loose tickets, I'd really appreciate any hint :)

**Comment by molul** [comment]
With my partners we finally found a solution. The problem was apparently in php's configuration, not properly parsing emails with ISO charset.

After many tests, we tried adding the line "setlocale(LC_ALL, 'en_US.UTF-8');" at the beginning of api/pipe.php (just after the big comment header and before "ini_set('memory_limit', '256M'); //The concern here is having enough mem for emails with attachments.").

Now everything's fine. You can close this thread  if you want :)

**Comment by protich** [comment]
@molul - Thank you very much for the feedback, we'll look into forcing locale on init.

**Comment by greezybacon** [comment]
I wonder if this should be added in `class.translation.php`, line 769, where the locale is set for translations
```php
        // Define locale for C-libraries
        putenv('LC_ALL=' . $info['code'].'.UTF-8');
        self::setLocale(LC_ALL, $info['code'].'UTF-8');
```

And, in `Bootstrap::i18n_prep`, add
```php
Translation::setLocale(LC_ALL, 'en_US.UTF-8');
```
The `en_US` part would be overridden later in a web request when loading the strings translation

**Comment by greezybacon** [comment]
@molul it's been a while, but would you be able to verify if the patch in #3168 addresses the issue?
