### ISSUE TITLE
Open a New Ticket always returns "500 Internal Server Error" (Invalid CSRF token on ticket.response)

### ISSUE THREAD

**Issue by tedg-dev** [osTicket/osTicket#2911]
Setup a new installation of v1.9.12 (19292ad), made some changes to Forms > Ticket Details.

Now on EVERY "Open a New Ticket", irregardless of the user, I get the generic "500 Internal Server Error"

Looking at the php "ost_syslog", I see many instances of this entry (not sure if it is a clue):

Invalid CSRF token [7bb804a344ab6005a30b1b8802eebcacf99b4ed2] on http://blah/blah/scp/ajax.php/draft/ticket.response.1

Have cleared cache, tried Safari and Chrome, same exact issue.

How can I see more details regarding this "Warning"?  Do I need to look in a different place to get more log details?

Here is my setup info:

About this osTicket Installation

Server Information
osTicket Version    v1.9.12 (19292ad) —  Up to date
Web Server Software Apache/2.2.29 (Unix)
MySQL Version   5.5.44
PHP Version 5.3.29
PHP Extensions
gdlib    Used for image manipulation and PDF printing
imap     Used for email fetching
xml  XML API
xml-dom  Used for HTML email processing
json     Improves performance creating and processing JSON
mbstring     Highly recommended for non western european language content
phar     Highly recommended for plugins and language packs
fileinfo     Used to detect file types for uploads
PHP Settings
cgi.fix_pathinfo     "1" is recommended if AJAX is not working
date.timezone    UTC
Database Information and Usage
Schema  support_osti956 (127.0.0.1)
Schema Signature    b26f29a6bb5dbb3510b057632182d138
Space Used  2.38 MiB
Space for Attachments   0.01 MiB
Installed Language Packs
Copyright © 2006-2016 IPCentral :: Support Ticket System All Rights Reserved.

**Comment by ntozier** [comment]
Please see your forum post at:
http://www.osticket.com/forum/discussion/87292/open-a-new-ticket-always-returns-500-internal-server-error-invalid-csrf-token-on-ticket-response

Thanks

**Comment by tedg-dev** [comment]
Thank you, was not sure the proper place to create this issue
