### ISSUE TITLE
Blank screen after adding fa.phar

### ISSUE THREAD

**Issue by shot4u** [osTicket/osTicket#2918]
I have installed osTicket with English language. Then I have added fa.phar (Persian language) to i18n folder.
Now when I try to change language it shows a blank page. 
I have enabled errors in my host but still cannot see any php error message.
I have used this file: http://rmalekghasemi.ir/own/fa.phar
Please advise.

**Comment by ntozier** [comment]
Official langiage files are housed at osticket.com/download.  We cannot provide support for third party language packs, you should contact the author for support.

As a side note, a blank page indicates a PHP error so you should consult your PHP error logs.

**Comment by shot4u** [comment]
Thank you for update
I used http://osticket.com/sites/default/files/download/lang/fa.phar now and there is no difference and it displays white screen.
P.S. I have enabled display_errors in my server still it shows nothing

**Comment by ntozier** [comment]
Version of osTicket?
Version of PHP?

**Comment by PooyaE** [comment]
@ntozier Im using os-ticket support script v1.9 and have trouble in this case too. also find the exact line of code in class.translation.php file.

$this->cache_translations = include $this->STREAM;
this line will include a .phar file.
[file](https://github.com/osTicket/osTicket/blob/develop/include/class.translation.php#L565)

something like this: phar:///dir/to/fa.phar/x.mo

php is not throwing any error even if display errors is enabled. I test this code in a single php file and still get nothing.

btw this script is working in PHP Version 5.4.45 and my current version is 5.5.37.

thanks in advance

**Comment by PooyaE** [comment]
@ntozier My current version is v1.9.12 and also I tried last released from osticket website.
and there is no any error related to this issue.

**Comment by ntozier** [comment]
If you are getting a white screen there is a PHP error.  I suggest that you find your php error log, because no one can help you with out the error.  The location of the PHP error log is set in your php.ini.
