### ISSUE TITLE
After transfer Ticket to new Department - Department Members getting no alert (OST 1.9.12)

### ISSUE THREAD

**Issue by ElKid** [osTicket/osTicket#2920]
I have the issue on OST 1.9.12

osTicket Version    v1.9.12 (19292ad)
Web Server Software    Apache
MySQL Version    5.5.44
PHP Version    5.3.3-7+squeeze28

After transfer Ticket to new Department only Department manager got alert, Department Members not.

I tried solutions #2356
https://github.com/greezybacon/osTicket-1.8/commit/c880377cb16e396d043a00e375d8f0e33e9b3532
but not works for me.

I tried solve the problem in code but I didn't have success.
Any help pleas?

**Comment by kitnox** [comment]
Same probleme v1.10-rc.2 (231f11e) 

2 step to transfert
1- I must assign a team before transfer for send a alert. (alert)
2- I transfert to same team for apply transfert département (no alert)
