### ISSUE TITLE
All agents can still create tickets in default department even with no access to it

### ISSUE THREAD

**Issue by awilkins** [osTicket/osTicket#2922]
Tested osTicket 1.10-rc2
# Reproduce problem
1. Added new department "Berties"
2. Created a new agent Bertie Thompson
   - With primary dep. Berties
   - username : bt ; password : btbtbt
3. Logged bt into another browser
   - Created ticket : confirm that bt can only create
     - Tickets in "Berties" department
     - Tickets with no department
   - Confirmed that new ticket appears on bt's Open Tickets list
4. Created a ticket with admin user
   - Admin user by default is in Support dept and no other
   - Created support ticket
   - Ticket shows up in Admin user list
   - Ticket does not show up in bt list
   - Viewed ticket as admin
   - Copied ticket URL to bt window - "Access denied"
5. Created a ticket with no department selected using bt
   - Can create ticket
   - bt Cannot see ticket in list
   - bt Cannot view ticket via URL
   - All tickets with no dept set just drop into the default (Support)
# Expected behaviour
- All tickets created by Agent with no access to default department are created in their primary department

**Comment by ntozier** [comment]
I don't see a problem?
bt as an agent can create tickets in other departments (that bt does not have access to)... in fact by not picking a department there is a high probability bt wouldn't have access to the ticket since the default department setting would rule the day and assign the ticket to the systems default department.

**Comment by awilkins** [comment]
bt can't pick other departments, just the one he's a member of, or leave it blank.

![one-department](https://cloud.githubusercontent.com/assets/368399/12949447/c576d834-cfff-11e5-8ddf-972960536d7c.png)

> by not picking a department there is a high probability bt wouldn't have access to the ticket since the default department setting would rule the day and assign the ticket to the systems default department.

And that's the problem - this means Agents can create tickets by accident that are not in their department, and they can't access them. In 1.9 this isn't a problem because Agents can see tickets from every department. In 1.10 this means that an agent can create a ticket in the default department when he isn't a member of that department and not be able to change that.

**Comment by ntozier** [comment]
Ah I see.  You are assuming that the agent who opens a ticket should have access to said ticket.  That is not the case.  Your sample ticket is owned by user Dave.  Dave can log in and see the ticket, the agent has no special privs to see said ticket because it's not theirs.
