### ISSUE TITLE
Custom form with Access to Registered User or LDAP?!

### ISSUE THREAD

**Issue by UkaLee** [osTicket/osTicket#2926]
Hi,
first thanks for Osticket great tool!

I am using it for a while now and I really hoping for some kind of Custom Forms.
I need to provide a Possibility to Select the user which are Registered in Osticket.
Is for Approve Stuff and Requests. 

I can import all User in a Custom Choose form, but then I have to update them every-time someone new joins the Company. 

If there a way to solve that? Like the Filed is a agent wants to open a new ticket and can search withing the LDAP Directory?

regards

**Comment by ntozier** [comment]
Chefkeks has written about this on the forums, and here:
https://github.com/Chefkeks/osTicket-Addons/

**Comment by UkaLee** [comment]
Thanks I will give it a Try!
