### ISSUE TITLE
error "DB Error #1054" in osticket 1.10rc2

### ISSUE THREAD

**Issue by philbertphotos** [osTicket/osTicket#2929]
I cant find what is causing this ...any help would be great

[SELECT A1.`id`, A1.`pid`, A1.`thread_id`, A1.`staff_id`,
A1.`user_id`, A1.`type`, A1.`flags`, A1.`poster`, A1.`editor`,
A1.`editor_type`, A1.`source`, A1.`title`, A1.`body`, A1.`format`,
A1.`ip_address`, A1.`created`, A1.`updated`, A3.`staff_id`, A3.`dept_id`,
A3.`role_id`, A3.`username`, A3.`firstname`, A3.`lastname`, A3.`passwd`,
A3.`backend`, A3.`email`, A3.`phone`, A3.`phone_ext`, A3.`mobile`,
A3.`signature`, A3.`lang`, A3.`timezone`, A3.`locale`, A3.`notes`,
A3.`isactive`, A3.`isadmin`, A3.`isvisible`, A3.`onvacation`,
A3.`assigned_only`, A3.`show_assigned_tickets`, A3.`change_passwd`,
A3.`max_page_size`, A3.`auto_refresh_rate`, A3.`default_signature_type`,
A3.`default_paper_size`, A3.`extra`, A3.`permissions`, A3.`created`,
A3.`lastlogin`, A3.`passwdreset`, A3.`updated`, A4.`id`, A4.`org_id`,
A4.`default_email_id`, A4.`status`, A4.`name`, A4.`created`, A4.`updated`,
A2.`id`, A2.`thread_entry_id`, A2.`mid`, A2.`headers` FROM `ost_thread_entry`
A1 LEFT JOIN `ost_thread_entry_email` A2 ON (A1.`id` = A2.`thread_entry_id`)
LEFT JOIN `ost_staff` A3 ON (A1.`staff_id` = A3.`staff_id`) LEFT JOIN
`ost_user` A4 ON (A1.`user_id` = A4.`id`) WHERE A2.`mid` = ? ORDER BY A1.`` ASC
LIMIT 1

Unknown column 'A1.' in 'order clause'

---- Backtrace ----<br />
#0 (root)/include/mysqli.php(318):

osTicket->logDBError('DB Error #1054', '[SELECT A1.`id`...')<br />
#1 (root)/include/class.orm.php(2743): db_prepare('SELECT

A1.`id`,...')<br />
#2 (root)/include/class.orm.php(2737):

MySqlExecutor->execute()<br />
#3 (root)/include/class.orm.php(2831):

MySqlExecutor->_prepare()<br />
#4 (root)/include/class.orm.php(1540):

MySqlExecutor->getRow()<br />
#5 (root)/include/class.orm.php(1344):

ModelInstanceManager->fillTo(9223372036854775807)<br />
#6 (root)/include/class.orm.php(1073):

ResultSet->asArray()<br />
#7 (root)/include/class.orm.php(1077):

QuerySet->all()<br />
#8 (root)/include/class.thread.php(1139):

QuerySet->first()<br />
#9 (root)/include/class.mailfetch.php(750):

ThreadEntry->lookupByEmailHeaders(Array, false)<br />
#10 (root)/include/class.mailfetch.php(820):

MailFetcher->createTicket(1)<br />
#11 (root)/include/class.mailfetch.php(900):

MailFetcher->fetchEmails()<br />
#12 (root)/include/class.cron.php(25):

MailFetcher->run()<br />
#13 (root)/include/class.cron.php(100):

Cron->MailFetcher()<br />
#14 (root)/include/api.cron.php(19): Cron->run()<br

/>
#15 (root)/include/api.cron.php(40):

CronApiController->run()<br />
#16 (root)/api/cron.php(23):

LocalCronApiController::call()<br />
#17 {main}

**Comment by philbertphotos** [comment]
I turned off the cronjoab and this problem stopped ... I have no idea why its happening and I need the cronjob running.

**Comment by kest874** [comment]
Any php errors in the log (error.log)?  Might be a bounced mail in the inbox? Also I've seen where someone forwards messages as attachments cause an issue.
