### ISSUE TITLE
Custom Logo does not show up 

### ISSUE THREAD

**Issue by theorganiser** [osTicket/osTicket#2930]
when i upload a custom logo in to the dashboard it wont show the logo.
i used a JPEG image at first and then changed it to PNG  even resized the image to the right pixels.
but still it wont show it.
in the dashboard it just says Custom Logo as a text  i can delete it.
in the ticket system portal it only shows a X.
anybody any idea ?

**Comment by JediKev** [comment]
Just to be sure, you have to go to the Admin Panel and then Company > Logos and uploaded them there.  Once uploaded you have to tick one of or both of the bubbles to the left stating that you want it to show up on the client side and or agent side.  The help tip suggests that the logo should be in either .gif, .png, or .jpg format and around 817px x 170px.  If you have done those steps and it still hasn't worked what version of osTicket are you running?

**Comment by theorganiser** [comment]
Yes i did al those steps,  it worked in 1.9  before,  nut i now use 1.10  clean install  on a synology disk station

**Comment by ntozier** [comment]
1.10rc2 is a release candidate and really should not be run in a production environment. I would recommend that you revert to the previous version until 1.10 is actually released.

**Comment by theorganiser** [comment]
i am running testdrives to see if os ticket is something for my company  and thought i would install 1.10 
but opened this threat to let you guys know it
