### ISSUE TITLE
Email Formatting Received

### ISSUE THREAD

**Issue by dmaxted** [osTicket/osTicket#2933]
We seem to have a formatting problem on html emails that are received by the system osTicket-v1.9.12. When a customer logged a ticket thru Microsoft Outlook as:

Hi Support,
Having a problem printing to the network.
Regards, Guest

Formatting comes through as:

Hi Support,

Having a problem printing to the network.

Regards, Guest

How can we modify the code to show on one line. 'Enable HTML Ticket Thread' has been disabled.

**Comment by ntozier** [comment]
Version of Outlook?
Which of the three formats that Outlook can send are you using?

**Comment by dmaxted** [comment]
Using Microsoft Office 2010 formatted in HTML. 
From my understanding, the ticketing system should be converting it to plan text upon receipt.

**Comment by ntozier** [comment]
Can you provide an example of what you are seeing?

**Comment by Invidia1990** [comment]
Got the same problem.
HTML E-Mail text copied
![2016-02-22 15_22_54-unbenannt - nachricht html](https://cloud.githubusercontent.com/assets/13020958/13220785/6505b43e-d978-11e5-9ee8-a511463c948b.jpg)
and pasted
![2016-02-22 15_23_44-osticket __ agenten-bereich](https://cloud.githubusercontent.com/assets/13020958/13220790/6af9b35e-d978-11e5-9b27-2d71eeeacf19.jpg)

**Comment by dmaxted** [comment]
Exactly the same issue as post above.

**Comment by ntozier** [comment]
Copying and pasting text from an HTML email into the WYSIWYG editor does not actually demonstrate the problem...

**Comment by Invidia1990** [comment]
Hmm, I dont know where you can't see the problem.
How about now?
![2016-02-22 17_39_58-clipboard](https://cloud.githubusercontent.com/assets/13020958/13225011/5a4c7600-d98b-11e5-8ae1-765fbe65594a.jpg)

I have the exact same issue as dmaxted. Using Office 2010 x64. It would be really nice to have a solution for this. Because if you paste a longer E-Mail it just looks broken.

**Comment by ntozier** [comment]
Then let me clarify... This issue report is about "html emails that are received by the system".
Not you cutting and pasting from an Outlook compse window into the WYSIWYG editor.

**Comment by kest874** [comment]
It's putting <br><br> after each part of text.  So when outlook sends it the html layout has <br><br> at the end of each line.

**Comment by Invidia1990** [comment]
@ntozier should I open an extra issue for it then? For me it looks similiar because it doesn't matter if I send the outlook html e-mail or copy the text to post a internal note. The result is at both ways the same.

**Comment by dmaxted** [comment]
Have we found a solution for this problem. 
Emails accepted into the ticket system look broken and unprofessional.

**Comment by philbertphotos** [comment]
This happens in 1.10RC2 also... its an annoying bug since 99% of our users use outlook.

**Comment by kest874** [comment]
Ok did some testing and came up with the following change to class.mailfetch.php

Change the function getbody to look like below:

    function getBody($mid) {
        global $cfg;

        if ($cfg->isRichTextEnabled()) {
            if ($html=$this->getPart($mid, 'text/html', $this->charset))
                $body = new HtmlThreadEntryBody($html);
            elseif ($text=$this->getPart($mid, 'text/plain', $this->charset))
                $body = new TextThreadEntryBody($text);
        }
        elseif ($text=$this->getPart($mid, 'text/plain', $this->charset))
            $body = new TextThreadEntryBody($text);
        elseif ($html=$this->getPart($mid, 'text/html', $this->charset))
            $body = new TextThreadEntryBody(
                    Format::html2text(Format::safe_html($html),
                        100, false));

        if (!isset($body))
            $body = new TextThreadEntryBody('');

        if ($cfg->stripQuotedReply())
            $body->stripQuotedReply($cfg->getReplySeparator());
		
		// Strip Outlook client markup
		$body = str_replace('<o:p></o:p></p>', '<br>', $body); 
		$body = str_replace('<p class="MsoNormal">', '', $body);
		$body = str_replace('<o:p>&nbsp;</o:p></p>', '<br>', $body);
		$body = str_replace('<o:p></o:p></span></p>', '<br>', $body);

        return $body;
    }

The extra markup is caused by Outlook using "Word" to render the html the above strips most of it out.

**Comment by philbertphotos** [comment]
Gonna try this patch now .... Thanks for the work.

**Comment by dmaxted** [comment]
Thanks for this. Will apply patch and let you know.

**Comment by dmaxted** [comment]
No change on my side.

**Comment by kest874** [comment]
Working ok here this won't affect the "paste into note" as demonstrated above.
