### ISSUE TITLE
Read only option to slave

### ISSUE THREAD

**Issue by cyberformed** [osTicket/osTicket#2937]
[REPLACE INTO ost_session SET session_updated=NOW() ,session_id='vaa3dne6uo5ftpdq5nqbi2p0d5',session_data='csrf|N;TZ_OFFSET|s:3:\"5.5\";TZ_DST|s:1:\"0\";',session_expire=(NOW() + INTERVAL 86400 SECOND),user_id='0',user_ip='',user_agent=''] The MariaDB server is running with the --read-only option so it cannot execute this statement http://example.com/api/cron.php

**Comment by ntozier** [comment]
Version of osTicket?
Description of the actual issue?
Did you shut off readonly mode as described in the error?  [The MariaDB server is running with the --read-only option so it cannot execute this statement ]

**Comment by cyberformed** [comment]
Version 1.7

When running a cron job. display error.

**Comment by ntozier** [comment]
This is the 1.8 repo.  You would want to report the issue at:
https://github.com/osTicket/osTicket-1.7/

You also didn't answer the third question.

**Comment by cyberformed** [comment]
I have shut off the read-only option in database.
