### ISSUE TITLE
Nested forms

### ISSUE THREAD

**Issue by UkaLee** [osTicket/osTicket#2938]
Hello,
I’m preparing a ticket system for our Internal IT.
I am almost done but what I really miss is that there are no nested form.

I was able to work around in some topics but it’s getting more complex and now my boss and colleagues want it different.

Example:

Help Topic System 1
New Account Creation: (Choice YES / NO) *mandatory
    Attribute 1
    Attribute 2
    Attribute 3
    Attribute 4
    Attribute 5
Change Role: (Choice YES / NO) *mandatory
    Attribute 1
    Attribute 2
    Attribute 3
    Attribute 4
    Attribute 5
Change something else: (Choice YES / NO) *mandatory
    Attribute 1
    Attribute 2
    Attribute 3
    Attribute 4
    Attribute 5

This is how it looks now, but you if you want to “Change the role” for example you have to select NO / yes (provide all information) and NO again.

This is just one example and it doesn’t look nice and it’s complicated for the end-user (yes we did a test run)

It would be great if there would be some nested forms.
Select the Help topic.
First Choose (“New Account Creation”/ “Change Role” / “Change something else”)
And if one is selected you get the Attributes to fill 

Maybe there is a way to do it but I was not able to find it.

Regards

**Comment by bishu05** [comment]
Did any one implemented this option??
