### ISSUE TITLE
How to stop email loop

### ISSUE THREAD

**Issue by jedjann** [osTicket/osTicket#2946]
hi guys i need you help. i got an email loop notification on my dashboard. i already deleted the email that causing the  loop . how to stop the email loop? is there a sending queue to delete the massage that causing the email loop? thanks! 

osTicket Version - v1.9.12 (19292ad)
Web Server Software - Apache/2.4.6 (CentOS) PHP/5.4.16
MySQL Version - 5.5.44
PHP Version - 5.4.16

**Comment by infectormp** [comment]
ban email or make Ticket Filter

**Comment by jedjann** [comment]
i tried email banning but it keeps notifying me Ticket Denied. 
Ticket Filter doesn't work doesn't do anything i keep receiving email loop notification.

**Comment by ntozier** [comment]
Where is the email that is causing the loop coming from?

If its osTicket sending the email to your mailserver, which is then silently CCing or copying the email to a folder, which causes the email to be picked up by osTicket... then change it at the mailserver level.

**Comment by ntozier** [comment]
@ali4837 your post makes no sense.  Details please?
