### ISSUE TITLE
Url denied when ticket created by API

### ISSUE THREAD

**Issue by norcis** [osTicket/osTicket#2950]
I create tickets using API. In the body URLs such as `<a href='SIP:+44123123123'>Call</a>` gets replaced with `<a href='denied:SIP:+44123123123'>Call</a>`

**Comment by ntozier** [comment]
Version of osTicket?

**Comment by norcis** [comment]
v1.9.12

**Comment by norcis** [comment]
Any ideas?

**Comment by greezybacon** [comment]
htmLawed does not consider that a valid href attribute. You can check in `include/class.format.php` in the `safe_html` method where htmLawed is configured

**Comment by norcis** [comment]
I added sip and tel schemes for href in safe_html method and rebooted, but still I get denied in urls.

**Comment by norcis** [comment]
greezybacon, how can I fix it? Maybe htmLawed is used somewhere else when creating tickets using API?

**Comment by norcis** [comment]
Up

**Comment by ntozier** [comment]
So you went to include/class.format.php and added sip in the safe_html method like @greezybacon suggested... you restarted your website and it still doesn't work?

**Comment by norcis** [comment]
Yes, rebooted, checked again, still no luck.

**Comment by a-schild** [comment]
It's important to not add it at the end of the line, but before the first ; character, since these are the allowed links for href: type links.
The types at the end of the list are for src: type references
