### ISSUE TITLE
OsTicket 1.9.12

### ISSUE THREAD

**Issue by spray63** [osTicket/osTicket#2952]
Good day! Could you tell me how you can remove on the registration page are two links, Register and login?
![2016-03-07 12-54-10 - - google chrome](https://cloud.githubusercontent.com/assets/17699307/13564542/eb176216-e463-11e5-85e9-ad3eaf15bc30.png)

**Comment by infectormp** [comment]
@spray63 you can try this commit https://github.com/datatecuk/osTicket-1.8/commit/6bfb905b3ee1c9ee412f60e28a129311fe0b1f56

**Comment by spray63** [comment]
Thank you very much! Now try

**Comment by spray63** [comment]
Removed the link as suggested, but I use Russian language.now there was here this error
![2016-03-07 23-02-03 - - google chrome](https://cloud.githubusercontent.com/assets/17699307/13580130/4c3ce8e4-e4ba-11e5-9cc4-47964021a761.png)

**Comment by spray63** [comment]
Figured out the first problem! Managed to remove all the links. And how can you fix these links? I want to remove them too. Do not tell me what file .php edit need
![2016-03-08 11-45-39 - - google chrome](https://cloud.githubusercontent.com/assets/17699307/13595313/b1790b5c-e523-11e5-89e9-38c8032c7b41.png)
