### ISSUE TITLE
Invalid reset token

### ISSUE THREAD

**Issue by gfilas** [osTicket/osTicket#2954]
Hi, I've downloaded trunk version and staff password reset is not working at all, we always get an "invalid reset token" message. I found that the problem is related with class.config.php. Many changes were included there since the release candidate. I found that in function Items() in that class the variable $items was declared as static, and the problem was that it only gathers the "core" namespace config once, but it never loaded "pwreset" namespace and so it never found the reset token saved.

Changing the line "static $items" to $items=null in the function items() solved the issue.

Regards,
Gabriel.

**Comment by ntozier** [comment]
"I've downloaded trunk version"
which version would what be?

**Comment by gfilas** [comment]
The last code available on github (develop-next branch)

Regards

De: ntozier [mailto:notifications@github.com]
Enviado el: lunes, 07 de marzo de 2016 12:53
Para: osTicket/osTicket-1.8
CC: Filas Gabriel
Asunto: Re: [osTicket-1.8] Invalid reset token (#2954)


"I've downloaded trunk version"
which version would what be?

—
Reply to this email directly or view it on GitHub<https://github.com/osTicket/osTicket-1.8/issues/2954#issuecomment-193311699>.

Internet Email Confidentiality Footer ******************************************************************************************************************************************** La presente comunicazione, con le informazioni in essa contenute e ogni documento o file allegato, e' rivolta unicamente alla/e persona/e cui e' indirizzata ed alle altre da questa autorizzata/e a riceverla. Se non siete i destinatari/autorizzati siete avvisati che qualsiasi azione, copia, comunicazione, divulgazione o simili basate sul contenuto di tali informazioni e' vietata e potrebbe essere contro la legge (art. 616 C.P., D.Lgs n. 196/2003 Codice in materia di protezione dei dati personali). Se avete ricevuto questa comunicazione per errore, vi preghiamo di darne immediata notizia al mittente e di distruggere il messaggio originale e ogni file allegato senza farne copia alcuna o riprodurne in alcun modo il contenuto. ***************** This e-mail and its attachments are intended for the addressee(s) only and are confidential and/or may contain legally privileged information. If you have received this message by mistake or are not one of the addressees above, you may take no action based on it, and you may not copy or show it to anyone; please reply to this e-mail and point out the error which has occurred. ********************************************************************************************************************************************

**Comment by quazardous** [comment]
v1.10-rc.2 always buggy

function static variable in php are shared by all the instance of all the class hierarchy (weird)...

Using an array of items by namespace does the trick.

here is a patch.

```patch
diff --git a/include/class.config.php b/include/class.config.php
index 165ad08..6f5c42a 100644
--- a/include/class.config.php
+++ b/include/class.config.php
@@ -133,13 +133,14 @@
     }
 
     function items() {
-        static $items;
+        static $items = [];
 
-        if (!isset($items))
-            $items = ConfigItem::items($this->section, $this->section_column);
+        if (!isset($items[$this->section]))
+            $items[$this->section] = ConfigItem::items($this->section, $this->section_column);
 
-        return $items;
+        return $items[$this->section];
     }
+    
 }
 
 class ConfigItem
```
