### ISSUE TITLE
ISSUE: Receiving consistent warnings when saving a new ticket from the agent panel

### ISSUE THREAD

**Issue by ArmgaSys** [osTicket/osTicket#2956]
Receiving: Warning: Missing argument 1 for VerySimpleModel::get() in [PATH]\include\class.orm.php on line 239
This is in V1.10 current tip

To Duplicate:

1) Logon
2) From the Agent Panel dashboard, click "New Ticket"
3) Fill out the ticket details
4) Save
5) Note the warning

**Comment by greezybacon** [comment]
Can you produce a backtrace for this? By itself, that doesn't explain what's going on. Have you made any edits to the software?

**Comment by ArmgaSys** [comment]
Greezy,
We do not have a backtrace for this.
I was, however, able to quickly reproduce using our test install by setting PHP logging to Development (which enables warnings).  This is using pristine code
