### ISSUE TITLE
Ticket Filters addtion 1.10Rc2

### ISSUE THREAD

**Issue by philbertphotos** [osTicket/osTicket#2957]
I notice it has "Topic ID" in the matching rule criteria would be nice is "Topic Name" was added ... kinda annoying to keep looking in SQL since there is no way to see the Topic ID in the UI. Plus its easier by name since most of us can remember the name of the Helptopic.

**Comment by txzsfj** [comment]
Just setting up my system now, as a quick comment to this: Names would be great. In the interim, in most browsers, just hover over the link in Help Topics' main page, and the URL pop-up will show the topic ID.

-r
