### ISSUE TITLE
ISSUE: Updating ticket "issue summary" does not change subject in grids (but does change in emails)

### ISSUE THREAD

**Issue by ArmgaSys** [osTicket/osTicket#2958]
When a customer emails a new ticket into OSTicket, the ticket automatically receives a subject (appears to be stored in ticket__cdata).

If the agent updates the "Issue Summary", all future outbound emails from OSTicket show the updated "Issue Summary" in the subject line (as expected).  The grids (open, My Tickets, etc) continue to show the original subject, not the updated "Issue Summary".

**Comment by ntozier** [comment]
Version of osTicket?

How exactly does an agent update the "Issue Summary"?  It's not an editable field.

**Comment by ArmgaSys** [comment]
Ntozier,
My apologies.  I should have included those details initially.

Version: TIP from develop-next (29a9487)

To Duplicate:

1) Send an email to OSTicket with a test subject.
    Note that the new ticket shows in the Open queue with the email's original subject
2) Open the ticket via SCP
3) Click the edit icon on the ticket (upper right)
4) Under "Ticket Details", change the "Issue Summary" field and click "Save"
5) Note that the "Open" queue still shows the original subject.

Root Issue:
The "Subject" is stored in ticket__cdata whereas the "Issue Summary" is stored in the form data.  Most code seems to use the "Issue Summary" field via the accessor on ticket.class.php getSubject() which probes the form data.  The queues / grids, however, pull the subject from ticket__cdata resulting in inconsistent display of the ticket data.

Potential corrective actions (as we see it... there could be many more ways to solve the issue):
Update the ticket__cdata subject when updating the ticket based on the Issue Summary form data.
-OR-
Modify the tickets handler to extract the subject from the form data.  This may have a performance penalty as it looks like this data is not currently being loaded when the grid / queue data is being processed.

**Comment by ntozier** [comment]
Perfect!  Thanks for clarifying.

**Comment by jakester2** [comment]
I am seeing this same issue when adding a custom drop-down menu to Ticket Details. I then try and remove the selection and it does not update with the changes.
