### ISSUE TITLE
On StaffAlert send Ticket attachment via email.

### ISSUE THREAD

**Issue by exfranshis** [osTicket/osTicket#2965]
Hi!
I've problem with osTicket 1.9.12. It's possible in this version send "Ticket Attachment" to staff via Alert Email (when the user create a new ticket or add new reply)?

I've tried osTicket 1.10 beta (but i prefer 1.9.12 because i've customize it) and in that version is possible send attachment to staff (it's very simple with the new variable in "ticket template")

**Comment by ntozier** [comment]
I believe that feature is introduced in the forth coming 1.10.x version.
So no there would not be a way to do it in 1.9.12 unless you alter the source and add that feature yourself.  You can probably look at 1.10.x and reverse engineer to add it to 1.9.x.
