### ISSUE TITLE
Status Update for 1.10?

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket#2966]

**Comment by ntozier** [comment]
When it is ready.
You will not likely get any other answer.

**Comment by jdelhome3578** [comment]
I figured but it has been some time and activity on here has come to a crawl.

**Comment by greezybacon** [comment]
@jdelhome3578 sorry, I hope we can do a better job of meeting your activity expectations in the future. We merged `develop-next` in to `develop` today and are hoping for a rc3 release soon. Also, the `develop-next` branch is now ready for the up-and-coming features of the next major version.
