### ISSUE TITLE
DB Error #1062 - osTicket 1.9.5v

### ISSUE THREAD

**Issue by mohankarunasiri** [osTicket/osTicket#2967]
DB Error #1062

[INSERT INTO `ost__search` (`object_type`,  `object_id`,  `title`,  `content`) VALUES ('H', 7547, '0 13 14 19 20 22 23 26 27 31', '0 4 5 9 10 18 19 22 23 28 29 30 32 33'), ('H', 7545, '0 13 14 19 20 22 23 26 27 31', '0 4 5 9 10 18 19 22 23 28 29 30 32 33'), ('H', 7543, '0 13 14 19 20 22 23 26 27 31', '0 7 8 14 15 18 19 24 25 26 28 29 30 36 37 38 39 42 43 48 49 50 52 53 54 60 61 66 67 70 71 76 77 78 80 81 82 85 86 96 97 100 101 106 107 108 110 111 112 119 120 130 131 134 135 140 141 142 144 145'), ('H', 7541, '0 13 14 19 20 22 23 26 27 31', '0 6 7 13 14 17 18 23 24 25 27 28'), ('H', 7537, '0 13 14 19 20 22 23 26 27 31', '0 8 9 15 16 19 20 25 26 27 29 30')] Duplicate entry 'H-7547' for key 'PRIMARY'
 
 ---- Backtrace ----
 #0 (root)/include/mysqli.php(177): osTicket->logDBError('DB Error #1062',  '[INSERT INTO `o...')
 #1 (root)/include/class.search.php(611): db_query('INSERT INTO `os...')
 #2 (root)/include/class.search.php(591): MysqlSearchBackend->__index(NULL,  true)
 #3 [internal function]: MysqlSearchBackend->IndexOldStuff(Array,  NULL)
 #4 (root)/include/class.signal.php(98): call_user_func_array(Array,  Array)
 #5 (root)/scp/autocron.php(58): Signal::send('cron',  Array)
 #6 {main}

**Comment by mohankarunasiri** [comment]
I've got PHP error log from my web server.

[21-Mar-2016 02:17:31 Europe/Berlin] PHP Fatal error:  Uncaught exception 'Exception' with message 'Unable to index content' in /opt/lampp/htdocs/support/include/class.search.php:612
Stack trace:
#0 /opt/lampp/htdocs/support/include/class.search.php(591): MysqlSearchBackend->__index(NULL, true)
#1 [internal function]: MysqlSearchBackend->IndexOldStuff(Array, NULL)
#2 /opt/lampp/htdocs/support/include/class.signal.php(98): call_user_func_array(Array, Array)
#3 /opt/lampp/htdocs/support/scp/autocron.php(58): Signal::send('cron', Array)
#4 {main}
  thrown in /opt/lampp/htdocs/support/include/class.search.php on line 612

**Comment by ntozier** [comment]
1.9.5
upgrade.

**Comment by mohankarunasiri** [comment]
Thanks for your replying, I really wanted to upgrade my current version but 1200 end users connecting every day (24x7) to help desk and I did lot of customization to existing application therefore Is it possible to handle above error through application's cording modification?

Due to above error, may be cause to duplicating tickets?

Thanks,
Mohan.

**Comment by ntozier** [comment]
Generally speaking the devs are most likely not going to assist you to modify your modified source code.  If you want a feature or bug fix that was released after you modified your code you will have to go through the pull requests, find the ones that you want to add and modify your source with the fixes, etc. Or you will have to upgrade and then re-apply your code changes to the source.  There have been 8 releases of the 1.9.x tree since 1.9.5 and soon there will be another one that is a lot of bug fixes, security fixes that you are missing.

**Comment by greezybacon** [comment]
@mohankarunasiri you can upgrade your source code (with some work) with GIT. The easiest way would be to fetch a patch. You can do with with github:

https://github.com/osTicket/osTicket/compare/v1.9.5...v1.9.12.patch

Then you can attempt to apply the patch on your customized codebase. Resolve the merge conflicts, and you should be underway.

Another way is to let GIT do the heavy lifting. Clone this git repo, checkout v1.9.5, copy your current source code over the repo, checkout a new branch to contain your customization, then merge in v1.9.12: (on Unix)

```
git clone https://github.com/osTicket/osTicket
cd osTicket
git checkout v1.9.5
cp -vr /path/to/deployment .
git checkout -b customz
git merge v1.9.12
```
Resolve the merge conflicts (should be fewer this way), and then deploy again:
```sh
php manage.php deploy -v /path/to/deployment
```
You can use the `-t` flag to deploy a dry-run first

**Comment by mohankarunasiri** [comment]
Ok, Is it possible to clean upgrade from 1.9.5v to 1.9.12v without database changes? Or gradually upgrade from 1.9.6, 1.9.7, 1.9.8, to 1.9.12? because I need our existing tickets, users, agents and settings as it is.

**Comment by greezybacon** [comment]
There are no more database changes in v1.9 after v1.9.4

**Comment by ntozier** [comment]
Q: Ok, Is it possible to clean upgrade from 1.9.5v to 1.9.12v without database changes?
A: Yes, as @greezybacon said there are no database structure changes upgrading from where you are to current.

**Comment by mohankarunasiri** [comment]
Thanks, I will start from clean installation.
