### ISSUE TITLE
Organization staff seeing dublucate ticket 

### ISSUE THREAD

**Issue by Srdrulu** [osTicket/osTicket#2968]
Hi I have problem about organization when one staff of organization create ticket all origination's staff seeing  this ticket total count of staff
you can see attach file  
And also I want to see old ticket of this organization's   new member of this organization how can do ?
![ss](https://cloud.githubusercontent.com/assets/7911584/13986189/7fc6317c-f11a-11e5-8574-b4fb06377c03.png)

**Comment by ntozier** [comment]
You're image is from the client side... 
And I have no idea what you are trying to ask.
I'm also not real sure how you managed to make 7 tickets with the same ticket #.

**Comment by Srdrulu** [comment]
yes client side it is very strange problem if other member(member of same organization ) create ticket on client side other member see on their screen once time this ticket but if member create himself ticket it is showing total count of organization's member 
exam. organization name is 'ss'  , 
ss have  3 members  
1-member1
2-member2
3-member3
when member1 create one ticket ticket number #3333
member1 seeing  his screen 
3 time ticket #3333
others member just one 
when member2 or member3 create ticket 
Member1 seeing this ticket once time

**Comment by Srdrulu** [comment]
on staff side I mean in  /scp I have once time   this ticket

**Comment by Srdrulu** [comment]
I did mark   Organization Members:   Add to all tickets from this organization

**Comment by ntozier** [comment]
By member you mean User?
Version of osTicket?

**Comment by Srdrulu** [comment]
v1.10-rc.2 (231f11e)
yes User

**Comment by Srdrulu** [comment]
DO you have any idea ? for this problem ?

**Comment by ntozier** [comment]
I have no idea what the issue is, but I can confirm that it is happening in 1.10rc2 (Yet another reason not to run 1.10rc2 in a production environment)

Here's what I did to try:  
- created a new organization.
- added 4 users to it.  
- went into settings and ticked Organization Members: Add to all tickets from this organization.
- logged in as a user and created a ticket.
It creates the ticket.  It adds my three collaborators (ie the other 3 people in the Org).  Then when I click on Tickets (at the top in the menu bar) I see three identical tickets.

**Comment by Srdrulu** [comment]
Ok in staff panel ->Users->Organization-> click organization name -> setting tab ->Automated Collaboration-> mark Organization Members Add to all tickets from this organization

**Comment by Srdrulu** [comment]
Can you look like this also ? and Thank you very much you are trying to help

**Comment by Srdrulu** [comment]
i found solution about this problem #2405 but now i have other 2 problem 1. ticket sort 2. how can users see owned ticket
