### ISSUE TITLE
No Auto fill new ticket details - osTicket v1.9.12

### ISSUE THREAD

**Issue by WhispersfromIO** [osTicket/osTicket#2969]
When I create a new ticket, it comes up with a "Lookup or create a user box", which I can search for existing users. The search autocomplete function works here. But when I click "Continue" after selecting a existing user, it does not fill out any fields in the "New Ticket" fields. The user database is local and not AD or LDAP.

osTicket Version    v1.9.12 (19292ad) — Up to date
Web Server Software     Apache
MySQL Version   5.5.47
PHP Version     5.5.9-1ubuntu4.14

**Comment by greezybacon** [comment]
Is there a javascript error happening?

**Comment by WhispersfromIO** [comment]
Yes. From FireFox "Inspect Element"

`SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 19 of the JSON data`
`.parseJSON()`
`$.Redactor.prototype.autosave/this.autosaveInterval</<.success<()`
`.proxy/s()`
`v.Callbacks/l()`
`v.Callbacks/c.fireWith()`
`T()`
`.send/r()`

**Comment by WhispersfromIO** [comment]
The column 19 error keeps repeating, but when I click the continue button it comes up with the following error, so I think this is what you are looking for.

`SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 106 of the JSON data`
`.parseJSON()`
`$.userLookup/<()`
`$.dialog/</</<.success()`
`v.Callbacks/l()`
`v.Callbacks/c.fireWith()`
`T()`
`.send/r()`

**Comment by WhispersfromIO** [comment]
More details. In Chrome, the select user screen won't load at all when opening a new ticket. My previous issue was with using Firefox.

    jquery.pjax.js?19292ad:629 Uncaught TypeError: Cannot read property '0' of nullextractContainer     @ jquery.pjax.js?19292ad:629options.success @     jquery.pjax.js?19292ad:238l @ jquery-1.8.3.min.js?19292ad:2c.fireWith @ jquery-    1.8.3.min.js?19292ad:2T @ jquery-1.8.3.min.js?19292ad:2r @ jquery-1.8.3.min.js?19292ad:2
