### ISSUE TITLE
CJK font issue for ticket pdf export

### ISSUE THREAD

**Issue by matlinuxer2** [osTicket/osTicket#2978]
I got the same problem as the forum discussed.

http://osticket.com/forum/discussion/86053/there-is-scrambing-code-if-having-chinese-character-when-using-print

the screenshot is like the attachment below. ( screenshot of adobe reader on linux )

![2016-03-26_001751_908x586_scrot](https://cloud.githubusercontent.com/assets/53925/14048322/7b2f5aba-f2e8-11e5-9ba9-fb19bafc7fdb.png)

Is there any information/hint to fix this?

I think I can help to fix this, if there were some hint for this issue. 
( like which files are better entry points, ...etc. )

**Comment by ntozier** [comment]
If memory serves me correctly osTicket switched to mpdf (https://github.com/mpdf/mpdf) from fpdf (http://www.fpdf.org/)

I would start there.

**Comment by matlinuxer2** [comment]
Thank you!

I found "/include/class.pdf.php" wrap the mPDF's class. 

code block is below:
```
require_once(INCLUDE_DIR.'mpdf/mpdf.php');

class Ticket2PDF extends mPDF
{

	var $includenotes = false;

	var $pageOffset = 0;
```

Is "Ticket2PDF" the right class to patch?

I found "Ticket2PDF" has hard-code implementation to "Arial" font.  Any idea?

**Comment by greezybacon** [comment]
We upgraded the PDF printing system for version v1.10, but I think printing CJK is still an issue. The main problem is that I can't find a font pack in the neighborhood of one megabyte
