### ISSUE TITLE
v1.10-rc.2: Alerts on Tasks don't work

### ISSUE THREAD

**Issue by Distans** [osTicket/osTicket#2979]
Hello,

When creating a new task or assigning an existing one to a department email alerts won't go although they should according to the settings.

osTicket Version: v1.10-rc.2

Other alerts work fine (besides transferring a ticket from one department to another but this is another story).

**Comment by blastoma** [comment]
@greezybacon can you help?

**Comment by haraldhh** [comment]
I noticed the same problem. It would at least be nice if the ticket asignee would be notified when a task under a ticket is closed.

**Comment by ntozier** [comment]
@haraldhh your comment does not appear to be on topic.  Please start your own feature request.

**Comment by haraldhh** [comment]
If I understood You correctly I would have to start a feature request to get notified when a task is closed? I will do that.

**Comment by greezybacon** [comment]
@Distans if I had a dollar for every time someone submitted an issue about email notifications not working...

**Comment by ipAnything** [comment]
Is there a fix for this?
