### ISSUE TITLE
1.10 rc2 Develop Next is currently broken

### ISSUE THREAD

**Issue by philbertphotos** [osTicket/osTicket#2982]
remote-tracking branch 'upstream/develop-next' into develop-next its broken in several areas...
Manually correcting it is a pain so far :)

**Comment by philbertphotos** [comment]
scp/tickets.php has some invalid PHP text "<<<<<<< HEAD"  and "================" 
In includes/class.file.php I comment out the ARRAY in line 848 works now and testing other fixes :)

**Comment by ariesbeck** [comment]
This has already been fixed in the develop branch. See commit 72b4fa0.

**Comment by ariesbeck** [comment]
As for the array issue I believe this is a php compatibility issue. const arrays were added in 5.6. Readme indicates 5.3 and above so this is a problem...either the min php version needs to change or the array needs to be defined another way.

**Comment by philbertphotos** [comment]
Thanks.!

**Comment by ipso** [comment]
Would be nice to get develop-next branch fixed as well, its causing headaches with our development work to fix other bugs and get them submitted.

**Comment by greezybacon** [comment]
We merged the `develop-next` in to `develop`. You should change to that branch. `develop-next` will become largely unstable again when we start merging in features for the next major version of osTicket.

**Comment by greezybacon** [comment]
@ariesbeck good catch on the 5.3 requirement. We bumped to 5.4 in v1.10, but I missed that spot. Thanks

**Comment by philbertphotos** [comment]
Ok I usually test develop-next I will download a copy of develop and give it a whirl.

**Comment by balojs** [comment]
+1

**Comment by robintoy** [comment]
develop-next is now v1.10-rc3 and rc2 moved to develop as already stated.
We been using rc2 for a long time now and it is very stable [v1.10-rc.2 (231f11e)].

I'm just wondering as your issues might now be solved should we close this issue?
