### ISSUE TITLE
Can't create new task while viewing existing

### ISSUE THREAD

**Issue by catbadger** [osTicket/osTicket#2986]
To reproduce:
-Create a task by completing the new task form
-while on the page that displays the newly created task
-try clicking new task. it **_does not _** show the dialog

**Comment by ntozier** [comment]
You neglected to include version of osTicket in the report.

**Comment by catbadger** [comment]
oops! version is 1.10

**Comment by ntozier** [comment]
There is no such thing as 1.10 yet as it hasn't been released yet.
Do you mean 1.10dpr, 1.10rc1 or 1.10rc2?

**Comment by catbadger** [comment]
1.10rc2 apologies for the delay.

**Comment by catbadger** [comment]
more specifically develop branch

**Comment by m4gn3to** [comment]
Hi.

I'm in version v1.10 (901e5ea) and I get the same issue.
