### ISSUE TITLE
Syntax error when moving from develop-next to develop - no new tickets created

### ISSUE THREAD

**Issue by simonnzg** [osTicket/osTicket#2990]
Just moved from develop-next to develop.
This is where I've been so far today:
29a9487 HEAD@{0}: checkout: moving from develop to develop-next
b67c445 HEAD@{1}: pull: Fast-forward
e3c9e0f HEAD@{2}: checkout: moving from develop-next to develop
29a9487 HEAD@{3}: reset: moving to ORIG_HEAD
6217b75 HEAD@{4}: pull: Fast-forward
29a9487 HEAD@{5}: pull: Fast-forward
364044e HEAD@{6}: checkout: moving from develop to develop-next
e3c9e0f HEAD@{7}: pull: Fast-forward
b0e6e37 HEAD@{8}: checkout: moving from develop-next to develop
364044e HEAD@{9}: checkout: moving from develop to develop-next
b0e6e37 HEAD@{10}: pull: Fast-forward

Currently sitting on develop b67c445 and seeing the following error as the system tries to pick up an incoming ticket. 

[SELECT A1.`id`, A1.`org_id`, A1.`default_email_id`, A1.`status`, A1.`name`, A1.`created`, A1.`updated`, A3.`id`, A3.`user_id`, A3.`flags`, A3.`address`, A4.`id`, A4.`name`, A4.`manager`, A4.`status`, A4.`domain`, A4.`extra`, A4.`created`, A4.`updated`, A5.`id`, A5.`user_id`, A5.`status`, A5.`timezone`, A5.`lang`, A5.`username`, A5.`passwd`, A5.`backend`, A5.`extra`, A5.`registered` FROM `ost_user` A1 LEFT JOIN `ost_user_email` A2 ON (A1.`id` = A2.`user_id`) LEFT JOIN `ost_user_email` A3 ON (A1.`default_email_id` = A3.`id`) LEFT JOIN `ost_organization` A4 ON (A1.`org_id` = A4.`id`) LEFT JOIN `ost_user_account` A5 ON (A1.`id` = A5.`user_id`) WHERE A2.`address` = pike@westpower.co.uk] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '@westpower.co.uk' at line 1

---- Backtrace ----
#0 (root)/include/mysqli.php(204): osTicket->logDBError('DB Error #1064', '[SELECT A1.`id`...')
#1 (root)/include/class.orm.php(3090): db_query('SELECT A1.`id`, ...', true, true)
#2 (root)/include/class.orm.php(3146): MySqlExecutor->execute()
#3 (root)/include/class.orm.php(1746): MySqlExecutor->getRow()
#4 (root)/include/class.orm.php(1790): ModelInstanceManager->{closure}()
#5 (root)/include/class.orm.php(1769): CallbackSimpleIterator->next()
#6 (root)/include/class.orm.php(1778): CallbackSimpleIterator->rewind()
#7 (root)/include/class.orm.php(1445): CallbackSimpleIterator->valid()
#8 (root)/include/class.orm.php(1455): CachedResultSet->fillTo(9223372036854775807)
#9 (root)/include/class.orm.php(1484): CachedResultSet->asArray()
#10 [internal function]: CachedResultSet->count()
#11 (root)/include/class.orm.php(1165): count(Object(ModelResultSet))
#12 (root)/include/class.orm.php(537): QuerySet->one()
#13 (root)/include/class.user.php(595): VerySimpleModel::lookup(Array)
#14 (root)/include/class.ticket.php(3203): User::lookupByEmail(Object(EmailAddress))
#15 (root)/include/class.mailfetch.php(795): Ticket::create(Array, Array, 'Email')
#16 (root)/include/class.mailfetch.php(844): MailFetcher->createTicket(1)
#17 (root)/include/class.mailfetch.php(924): MailFetcher->fetchEmails()
#18 (root)/include/class.cron.php(25): MailFetcher->run()
#19 (root)/include/class.cron.php(100): Cron->MailFetcher()
#20 (root)/include/api.cron.php(19): Cron->run()
#21 (root)/include/api.cron.php(40): CronApiController->run()
#22 (root)/api/cron.php(23): LocalCronApiController::call()
#23 {main}

**Comment by simonnzg** [comment]
Reverted to 29a9487 and that is working properly (in this respect!), although what has changed between that and b67c445, I don't yet know.

**Comment by simonnzg** [comment]
Output of cron.php run:
PHP Fatal error:  Uncaught exception 'InconsistentModelException' with message 'Unable to prepare query:  SELECT A1.`id`, A1.`org_id`, A1.`default_email_id`, A1.`status`, A1.`name`, A1.`created`, A1.`updated`, A3.`id`, A3.`user_id`, A3.`flags`, A3.`address`, A4.`id`, A4.`name`, A4.`manager`, A4.`status`, A4.`domain`, A4.`extra`, A4.`created`, A4.`updated`, A5.`id`, A5.`user_id`, A5.`status`, A5.`timezone`, A5.`lang`, A5.`username`, A5.`passwd`, A5.`backend`, A5.`extra`, A5.`registered` FROM `ost_user` A1 LEFT JOIN `ost_user_email` A2 ON (A1.`id` = A2.`user_id`) LEFT JOIN `ost_user_email` A3 ON (A1.`default_email_id` = A3.`id`) LEFT JOIN `ost_organization` A4 ON (A1.`org_id` = A4.`id`) LEFT JOIN `ost_user_account` A5 ON (A1.`id` = A5.`user_id`) WHERE A2.`address` = pike@westpower.co.uk' in /var/www/html/tickets/include/class.orm.php:3091
Stack trace:
#0 /var/www/html/tickets/include/class.orm.php(3146): MySqlExecutor->execute()
#1 /var/www/html/tickets/include/class.orm.php(1746): MySqlExecutor->getRow()
#2 /var/www/html/ti in /var/www/html/tickets/include/class.orm.php on line 3091

**Comment by protich** [comment]
I just merged PR #2984, addressing the issue, to the tip of develop.

**Comment by simonnzg** [comment]
That's great! I'll give it a go and report back. :)

**Comment by simonnzg** [comment]
Yes, it works fine.  I did notice a DB Error #1062 caused by me lazily sending the same attachment twice. It didn't like that!
