### ISSUE TITLE
Active Directory or LDAP Authentication Backend and Force password change on next login

### ISSUE THREAD

**Issue by barrydegraaff** [osTicket/osTicket#2991]
When I create a new user, and select Active Directory or LDAP Authentication Backend
the user is asked to change his/her password. But this does not work.

To work-around:
I have to select Local Authentication backend, then click save, then uncheck `Force password change no next login.` and then select  Active Directory or LDAP Authentication Backend and save again to create a working new user. (I have unchecked `Send sign in information`)

It seems the osTicket login ALWAYS respects the setting of `Force password change on next login.` that is weird as that particular setting is hidden from the UI the moment I choose Active Directory or LDAP Authentication Backend.

So either the `Force password change no next login.` should be ignored by the login process when AD is used OR the setting should be shown in the admin UI.

**Comment by ghost** [comment]
'Thanks' for closing without comment.

**Comment by ntozier** [comment]
Are you still experiencing this in 1.14.1?
