### ISSUE TITLE
cómo obtener los datos ingresados mediante un campo personalizado? #1

### ISSUE THREAD

**Issue by ccontreras93** [osTicket/osTicket#2993]
Hola buen día, alguien me podría ayudar!, quiero saber como obtener los datos (valores) que se encuentran almacenados dentro de los campos personalizados. es decir, agregue un nuevo campo llamado "númerocuenta" en el formulario "organización" y quiero obtener el valor almacenado de ese dato.

**Comment by ntozier** [comment]
Google Translate:
Hello good day, someone could help me !, I want to know how to get the data (values) that are stored in custom fields. ie add a new field called "númerocuenta" in the form "organization" and want to get the stored value of that data. 

You want to get the data into an email to a client, or do you want to use SQL to get the data out of the DB for a custom script or something?

**Comment by ccontreras93** [comment]
Yes, I want to use SQL to obtain the values ​​of the database custom forms
