### ISSUE TITLE
error "DB Error #1054" in osticket 1.9.12

### ISSUE THREAD

**Issue by hmarthe** [osTicket/osTicket#2999]
I have a DB issue on OSTICKET 1.9.2 after a upgrade To 1.9.12 : 

DB Error #1054
[SELECT ticket_id FROM ost_ticket T1 LEFT JOIN ost_sla T2 ON (T1.sla_id=T2.id AND T2.isactive=1) WHERE status='open' AND isoverdue=0 AND ((reopened is NULL AND duedate is NULL AND TIME_TO_SEC(TIMEDIFF(NOW(), T1.created))>=T2.grace_period*3600) OR (reopened is NOT NULL AND duedate is NULL AND TIME_TO_SEC(TIMEDIFF(NOW(), reopened))>=T2.grace_period*3600) OR (duedate is NOT NULL AND duedate
---- Backtrace ----
#0 (root)/include/mysqli.php(177): osTicket->logDBError('DB Error #1054', '[SELECT ticket_...')
#1 (root)/include/class.ticket.php(2723): db_query('SELECT ticket_i...')
#2 (root)/include/class.cron.php(31): Ticket::checkOverdue()
#3 (root)/scp/autocron.php(57): Cron::TicketMonitor()
#4 {main}

someone can help me please ?

**Comment by hmarthe** [comment]
PHP :

PHP 5.4.16 (cli) (built: Jun 23 2015 21:17:27)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies

Linux :

CentOS Linux release 7.2.1511 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"

**Comment by greezybacon** [comment]
@hmarthe did you resolve the issue?

**Comment by hmarthe** [comment]
yes ticket is closed tks
