### ISSUE TITLE
DB error #1062 on incoming tickets

### ISSUE THREAD

**Issue by simonnzg** [osTicket/osTicket#3001]
I've noticed that I get a DB Error #1062 when, I THINK(!), a duplicate file is received in a ticket to a file already stored on the database.  I'm not, at the moment, sure what has happened to the tickets involved as they are no-longer in the mail queue and I can't find anything with the same time-stamp in the folder all incoming mail is copied to.

Is this a known problem? 

Here's the output of one of the errors:

[INSERT INTO `ost_attachment` SET `type` = 'H', `file_id` = 766, `inline` = 1]

Duplicate entry '0-766-H' for key 'file-type'<br />
<br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(204): osTicket->logDBError('DB Error #1062', '[INSERT INTO `o...')<br />
#1 (root)/include/class.orm.php(3095): db_query('INSERT INTO `os...', true, true)<br />
#2 (root)/include/class.orm.php(589): MySqlExecutor->execute()<br />
#3 (root)/include/class.thread.php(993): VerySimpleModel->save()<br />
#4 (root)/include/class.thread.php(1001): ThreadEntry->saveAttachment(Array, 0)<br />
#5 (root)/include/class.thread.php(1440): ThreadEntry->saveAttachments(Array)<br />
#6 (root)/include/class.thread.php(1448): ThreadEntry::create(Array)<br />
#7 (root)/include/class.thread.php(2299): ThreadEntry::add(Array)<br />
#8 (root)/include/class.thread.php(2516): MessageThreadEntry::add(Array, Array)<br />
#9 (root)/include/class.ticket.php(2297): ObjectThread->addMessage(Array, Array)<br />
#10 (root)/include/class.ticket.php(3417): Ticket->postMessage(Array, 'Email', false)<br />
#11 (root)/include/class.mailfetch.php(795): Ticket::create(Array, Array, 'Email')<br />
#12 (root)/include/class.mailfetch.php(844): MailFetcher->createTicket(1)<br />
#13 (root)/include/class.mailfetch.php(924): MailFetcher->fetchEmails()<br />
#14 (root)/include/class.cron.php(25): MailFetcher->run()<br />
#15 (root)/include/class.cron.php(100): Cron->MailFetcher()<br />
#16 (root)/include/api.cron.php(19): Cron->run()<br />
#17 (root)/include/api.cron.php(40): CronApiController->run()<br />
#18 (root)/api/cron.php(23): LocalCronApiController::call()<br />
#19 {main}

**Comment by simonnzg** [comment]
Forgot to add: Using c2e81b8

**Comment by simonnzg** [comment]
...and now everything works fine. (facepalm)
Copying all incoming mail to a test mailbox to see if I can catch what triggers this.

**Comment by simonnzg** [comment]
OK, it happened four times on four attachments (three e-mails). Three attachments errored twice, but I have found the tickets responsible, and the attachments seem fine. Nothing since.
As I can't replicate the problem, I'm going to give up and wait to see if it happens again.

**Comment by greezybacon** [comment]
This is definitely a problem. Could you try this patch:
```patch

**Comment by simonnzg** [comment]
Dare I say: What Patch? (considering all the fun we're having with attachments)

**Comment by greezybacon** [comment]
Sorry, check GitHub. I edited my post after I accidentally posted it empty.

**Comment by simonnzg** [comment]
ok

**Comment by simonnzg** [comment]
Well. 
1. I'm going to have to learn how to apply patches via Git.
2. Made the changes using vim. Didn't break anything, but also not at the moment getting the problem anyway.
All I can offer is that I'll keep that patch in place for a while and see what happens. While I read up on patching. Me end-user. Write PHP in vim. Badly.

**Comment by greezybacon** [comment]
Using *vim*...?! That's a long way from a measly "end user"

**Comment by simonnzg** [comment]
I talk to my servers via a shell, so use vim a lot. It's not so bad. In recent years it's gained syntax highlighting. ;-)
No errors so far this morning (7am in the UK)

**Comment by simonnzg** [comment]
Oh. It happened again:
[INSERT INTO `ost_attachment` SET `type` = 'H', `object_id` = 36495, `file_id` = 4295, `inline` = 1]

Duplicate entry '36495-4295-H' for key 'file-type'<br />
<br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(204): osTicket->logDBError('DB Error #1062', '[INSERT INTO `o...')<br />
#1 (root)/include/class.orm.php(3091): db_query('INSERT INTO `os...', true, true)<br />
#2 (root)/include/class.orm.php(585): MySqlExecutor->execute()<br />
#3 (root)/include/class.thread.php(993): VerySimpleModel->save()<br />
#4 (root)/include/class.thread.php(1001): ThreadEntry->saveAttachment(Array, 0)<br />
#5 (root)/include/class.thread.php(1440): ThreadEntry->saveAttachments(Array)<br />
#6 (root)/include/class.thread.php(1448): ThreadEntry::create(Array)<br />
#7 (root)/include/class.thread.php(2299): ThreadEntry::add(Array)<br />
#8 (root)/include/class.thread.php(2516): MessageThreadEntry::add(Array, Array)<br />
#9 (root)/include/class.ticket.php(2297): ObjectThread->addMessage(Array, Array)<br />
#10 (root)/include/class.ticket.php(3417): Ticket->postMessage(Array, 'Email', false)<br />
#11 (root)/include/class.mailfetch.php(795): Ticket::create(Array, Array, 'Email')<br />
#12 (root)/include/class.mailfetch.php(844): MailFetcher->createTicket(1)<br />
#13 (root)/include/class.mailfetch.php(924): MailFetcher->fetchEmails()<br />
#14 (root)/include/class.cron.php(25): MailFetcher->run()<br />
#15 (root)/include/class.cron.php(100): Cron->MailFetcher()<br />
#16 (root)/include/api.cron.php(19): Cron->run()<br />
#17 (root)/include/api.cron.php(40): CronApiController->run()<br />
#18 (root)/api/cron.php(23): LocalCronApiController::call()<br />
#19 {main}

**Comment by simonnzg** [comment]
And again. This time I think I can see the e-mail that caused it. It's an HTML one with two attachments, from a particularly active user. The body of the e-mail contains their company logo, plus a Twitter and Facebook icon and I suspect that it's these three images as I have three error messages for that e-mail. 
Is there some sort of checksum+name (no salt) process taking place to categorise each file, which gets affected by the same thing coming in more than once?
Duplicate entry '36497-25-H' for key 'file-type'
Duplicate entry '36497-26-H' for key 'file-type'
Duplicate entry '36497-1339-H' for key 'file-type'

**Comment by simonnzg** [comment]
Multipart HTML Base64 encoded e-mail from Microsoft SMTP Server. Three PNG files in the body, two document attachments that have no effect.
Can send the source or the whole e-mail if you want to drop it into a test system to see what goes bang.

**Comment by greezybacon** [comment]
@simonnzg thanks, I'll read deeper into this. It looks like the patch fixed the original issue, though. The `object_id` field was not sent to the database in the original SQL error. That represents a different and more serious issue.

**Comment by simonnzg** [comment]
Thank you. At least the tickets are still flowing. :)

**Comment by greezybacon** [comment]
@simonnzg might you be able to test the fix in #3035?

**Comment by simonnzg** [comment]
OK. Will give it a try (in a few hours - it's a bit late here) :)

**Comment by simonnzg** [comment]
Just had a bunch of DB #1062 errors caused by the Googlebot. Not seen that before. Extract:
`user_ip` = '66.249.69.228', `user_agent` = 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)'] Duplicate entry 'ed5bp6vmk8bj1030lhe3ql2gi2' for key 'PRIMARY'

**Comment by ebonweaver** [comment]
3 years later still an issue??  Brand new setup, replied to a ticket email, got this immediate reply:

[INSERT INTO `ost_attachment` SET `type` = 'H', `object_id` = 11, `file_id` = 1, `inline` = 1]

Duplicate entry '1-11' for key 'file_object'<br />
<br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(199): osTicket->logDBError('DB Error #1062', '[INSERT INTO `o...')<br />
#1 (root)/include/class.orm.php(3455): db_query('INSERT INTO `os...', true, true)<br />
#2 (root)/include/class.orm.php(658): MySqlExecutor->execute()<br />
#3 (root)/include/class.thread.php(1189): VerySimpleModel->save()<br />
#4 (root)/include/class.thread.php(1197): ThreadEntry->createAttachment(Array, 'powered-by-osti...')<br />
#5 (root)/include/class.thread.php(1665): ThreadEntry->createAttachments(Array)<br />
#6 (root)/include/class.thread.php(1677): ThreadEntry::create(Array)<br />
#7 (root)/include/class.thread.php(2748): ThreadEntry::add(Array)<br />
#8 (root)/include/class.thread.php(2963): MessageThreadEntry::add(Array, Array)<br />
#9 (root)/include/class.ticket.php(2692): ObjectThread->addMessage(Array, Array)<br />
#10 (root)/include/class.ticket.php(3099): Ticket->postMessage(Array, 'Email')<br />
#11 (root)/include/class.thread.php(571): Ticket->postThreadEntry('M', Array)<br />
#12 (root)/include/class.thread.php(839): Thread->postEmail(Array, Object(ThreadEntry))<br />
#13 (root)/include/class.mailfetch.php(845): ThreadEntry->postEmail(Array)<br />
#14 (root)/include/class.mailfetch.php(917): MailFetcher->createTicket(1)<br />
#15 (root)/include/class.mailfetch.php(997): MailFetcher->fetchEmails()<br />
#16 (root)/include/class.cron.php(25): MailFetcher::run()<br />
#17 (root)/include/class.cron.php(110): Cron::MailFetcher()<br />
#18 (root)/include/api.cron.php(19): Cron::run()<br />
#19 (root)/include/api.cron.php(40): CronApiController->run()<br />
#20 (root)/api/cron.php(23): LocalCronApiController::call()<br />
#21 {main}

**Comment by cjrw42** [comment]
7 years on and still an issue

Fresh install of v1.17.2 today, first test ticket

[INSERT INTO `ost_attachment` SET `type` = 'H', `object_id` = 5, `file_id` = 5, `inline` = 1]

Duplicate entry '5-5' for key 'ost_attachment.file_object'<br />
<br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(207): osTicket->logDBError()<br />
#1 (root)/include/class.orm.php(3482): db_query()<br />
#2 (root)/include/class.orm.php(658): MySqlExecutor->execute()<br />
#3 (root)/include/class.thread.php(1260): VerySimpleModel->save()<br />
#4 (root)/include/class.thread.php(1268): ThreadEntry->createAttachment()<br />
#5 (root)/include/class.thread.php(1807): ThreadEntry->createAttachments()<br />
#6 (root)/include/class.thread.php(1819): ThreadEntry::create()<br />
#7 (root)/include/class.thread.php(2957): ThreadEntry::add()<br />
#8 (root)/include/class.thread.php(3172): MessageThreadEntry::add()<br />
#9 (root)/include/class.ticket.php(3138): ObjectThread->addMessage()<br />
#10 (root)/include/class.ticket.php(4438): Ticket->postMessage()<br />
#11 (root)/include/class.ticket.php(4641): Ticket::create()<br />
#12 (root)/scp/tickets.php(426): Ticket::open()<br />
#13 {main}


enviro here is:

debian 11  (running as a vm in vmware for test)
apache2
php 8.2, 
mysql  Ver 8.0.32,  

full set of green ticks on the pre-setup screen for additional php modules etc.

sendmail as MTA working correctly.

ticket contained a pasted photo, with a textbox and arrow object as annotation

**Comment by JediKev** [comment]
@cjrw42 

PHP 8.2 is not yet supported. Downgrade to PHP 8.1 and retest.

Cheers.
