### ISSUE TITLE
Auth Ticket generation & check mismatch

### ISSUE THREAD

**Issue by glydetech** [osTicket/osTicket#3005]
There is a mismatch between the email link auth token generation and check. I came across this in version v1.8.1.2-4-g3047226 but the issue appears to be still there. I noted that both sections mention in comments that they are old code, but it appears to be still used.

The token is generated here https://github.com/osTicket/osTicket/blob/develop/include/class.ticket.php#L447

``` php
return md5($this->getId() . strtolower($this->getEmail()) . SECRET_SALT);
```

Where this token is checked https://github.com/osTicket/osTicket/blob/develop/include/class.auth.php#L1064:

``` php
&& !strcasecmp($_GET['a'], md5($ticket->getId() .  $_GET['e'] . SECRET_SALT))
```

The email address is not lower-cased before the comparison operation.

This should be changed to:

``` php
&& !strcasecmp($_GET['a'], md5($ticket->getId() .  strtolower($_GET['e']) . SECRET_SALT))
```

**Comment by ntozier** [comment]
You might want to submit a pull request with the change.
