### ISSUE TITLE
osTicket-v1.9.13.zip Package

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket#3007]
I am seeing a lot of errors trying to extract the files out of the zip on Windows 7

**Comment by GMo888** [comment]
Hello, do you have the link for this package ?

De : jdelhome3578 [mailto:notifications@github.com]
Envoyé : jeudi 31 mars 2016 19:16
À : osTicket/osTicket <osTicket@noreply.github.com>
Objet : [Disarmed] [osTicket/osTicket] osTicket-v1.9.13.zip Package (#3007)


I am seeing a lot of errors trying to extract the files out of the zip on Windows 7

**Comment by jdelhome3578** [comment]
https://github.com/osTicket/osTicket/releases/download/v1.9.13/osTicket-v1.9.13.zip

**Comment by ntozier** [comment]
This (1.9.13) has not been released yet.  Once it is released there will be an announcement on the forums, and you will be able to download it from osticket.com/download

**Comment by jdelhome3578** [comment]
Exhibit A: https://github.com/osTicket/osTicket/releases

**Comment by ntozier** [comment]
creating a new tag for the release... is not in fact releasing the release.

Exhibit A: osTicket always makes an announcement on the forum when there is a release.
Exhibit B: osTicket releases are available for download at osticket.com/download
Exhibit C: The devs have expressed that they wish the download feature at github was capable of being disabled.

**Comment by jdelhome3578** [comment]
Consider it a beta test then
