### ISSUE TITLE
Call to a member function addMissingFields() on a non-object

### ISSUE THREAD

**Issue by ccontreras93** [osTicket/osTicket#3009]
Hello!, good afternoon , someone could help me fix this error.

![error](https://cloud.githubusercontent.com/assets/18148309/14193696/462412a4-f764-11e5-9f09-eacc4836643c.png)

**Comment by ntozier** [comment]
Version of osTicket?
What are you doing when the error occurs?

Please help us to help you by providing more information.

**Comment by ccontreras93** [comment]
It is the osTicket - v1.9.12.

It occurs in selling edition of the ticket when the ticket save button is pressed.

**Comment by ccontreras93** [comment]
For error correction mentioned above is only necessary to perform this modification.

![correccion de error de validacion](https://cloud.githubusercontent.com/assets/18148309/14252555/8be775ec-fa4d-11e5-815f-a2c032034db0.png)
