### ISSUE TITLE
merge went south on https://github.com/osTicket/osTicket/blob/develop-next/scp/tickets.php#L89

### ISSUE THREAD

**Issue by quazardous** [osTicket/osTicket#3011]
https://github.com/osTicket/osTicket/blob/develop-next/scp/tickets.php#L89

**Comment by ntozier** [comment]
?

**Comment by quazardous** [comment]
@ntozier look Line 89 there is unresolved merge artifacts :p

**Comment by greezybacon** [comment]
@quazardous my bad. It was fixed in 72b4fa03051bd82403eb19da3643a8913babc0b4
