### ISSUE TITLE
1.10 RC2 / display user custom field in the main user detail view

### ISSUE THREAD

**Issue by quazardous** [osTicket/osTicket#3013]
custom fields are supported for users and you can edit them in the edit form but you cannot see them in the main user view like custom fields for tickets.

Plz add custom field to the user view.

**Comment by ntozier** [comment]
Ummm... They display in my user view.  HAve you populated the custom fields?  Because if there is nothing to display then it does not display the empty field.

**Comment by mfelber** [comment]
I guess he means the ticket view. In the "header" (don't know how to call it) of the ticket view some fields of the user form are shown but you can't decide which. That's recalls me to my feature request: https://github.com/osTicket/osTicket/issues/2607

**Comment by quazardous** [comment]
sorry I should hav put an URL or a screenshot

it 's not in the user part of the ticket view, in the user management view
![capture d ecran 2016-04-03 a 20 05 58](https://cloud.githubusercontent.com/assets/1506211/14233982/b974cf80-f9d7-11e5-9834-8950ac9bc7f9.png)
![capture d ecran 2016-04-03 a 20 05 35](https://cloud.githubusercontent.com/assets/1506211/14233983/b99bd30a-f9d7-11e5-925b-3a459073f844.png)

**Comment by ntozier** [comment]
That information is displayed when you click on the user.  You added it to the User Details form not the Ticket Details.

**Comment by quazardous** [comment]
yes it is a **user** custom form. but it's not displayed on the user view. On the second screenshot I would love to see my custom field: Test: Custom Value.

@ntozier I'm not speaking about Ticket custom field, they are working fine.

**Comment by ccontreras93** [comment]
Hello! good day , could you tell me how to set up the api in view of the organization added the new field to appear ?
