### ISSUE TITLE
Ticket Detail not visible

### ISSUE THREAD

**Issue by DerKiLLa** [osTicket/osTicket#3017]
When opening a new ticket, the important details are not visible. So i can't change the subject und the text. Same issue, when editing a ticket. 

Same with "Create new user". 

develop-branch with PHP7.

![editticket](https://cloud.githubusercontent.com/assets/4670462/14350196/2999a1da-fcc8-11e5-9199-08c07cb94299.jpg)
![openticket](https://cloud.githubusercontent.com/assets/4670462/14350199/29ac4862-fcc8-11e5-8c99-d9c8f97a252b.jpg)
![createuser](https://cloud.githubusercontent.com/assets/4670462/14350200/29b7cf3e-fcc8-11e5-84e4-7113c1f25690.jpg)

**Comment by ntozier** [comment]
1.10rc2?

**Comment by DerKiLLa** [comment]
**Server Information**

osTicket Version	v1.10-rc.2-328-g5acdf56 (5acdf56) —  Up to date
Web Server Software	Apache/2.2.15 (CentOS)
MySQL Version	5.1.73
PHP Version	7.0.5

**Comment by WhispersfromIO** [comment]
I have the same issue here with the current v1.9.12 [](https://github.com/osTicket/osTicket/issues/2969)
In Firefox, the lookup or create a user comes up and I can search by user, but the details are not populated in the ticket. In Chrome, neither the Lookup user or new ticket populates with anything.

**Comment by greezybacon** [comment]
I had some sort of database hiccup on my system, and all the fields were marked disabled. You can check by navigating to the form (Admin Panel -> Forms -> Ticket Details), then click the [Config] button, click the Settings tab, verify if the fields are enabled

**Comment by DerKiLLa** [comment]
Thanks! That worked ... but still have the bug with "Lookup or create a user".

**Comment by mfelber** [comment]
It seems that there is a relation between this issue and using osticket 1.10 and php 7.
Multiple users have reported problems with suddenly disabled fields in their forms.

All of them are using php 7:

https://github.com/osTicket/osTicket/issues/3513

http://osticket.com/forum/discussion/89118/v1-10-can-t-enable-help-topic-form#latest
