### ISSUE TITLE
Attachments being removed with edit FAQ

### ISSUE THREAD

**Issue by CJohnson5136** [osTicket/osTicket#3019]
Attachments are being removed from FAQ pages when using the edit FAQ option at the bottom of the page. The edit FAQ option at the top right of the page does not remove them, but the one from the dropdown menu at the bottom does. We are running version 1.9.12.

**Comment by infectormp** [comment]
duplicate https://github.com/osTicket/osTicket/issues/2888

**Comment by balojs** [comment]
same #3139

**Comment by rayfoss** [comment]
fixed in 907ec36
