### ISSUE TITLE
Textarea for ticket response bug(s)

### ISSUE THREAD

**Issue by Curium** [osTicket/osTicket#3023]
I have noticed some strange behavior in the text area when answering a ticket as an agent. There are really two different problems related to this text area. Please let me know if I should separate them into two different bug reports.
1. When writing an answer, any random text really, and occasionally press the backspace because you wrote something wrong. A lot of times (more than 50% of the time) the cursor jumps all the way to the start of the text area instead of just deleting the text. This behavior usually takes some time to initiate but when it start it's really common. Thats why I suspect it having something to do with the save function of the text area (it doesn't start right away). In earlier versions where the auto save feature wasn't implemented I didn't see this. I found this behavior in both FireFox and Chrome.
2. When inserting a link into some text, e.g. https://github.com/, and then pressing enter right after to insert a new line, the linebreakes are insertet insside the `<a href>`-tag. And the text before the link is pushed down by the line break. Please see example in the screen shot below.

![href error](https://cloud.githubusercontent.com/assets/4319060/14426656/bc1a80d0-fff0-11e5-8478-d0c4cdcbd61d.png)

I'm currently on osTicket (v1.9.12).

Cheers!

**Comment by ntozier** [comment]
1. appears to be a dupe.
https://github.com/osTicket/osTicket/issues/2322
https://github.com/osTicket/osTicket/issues/2373
https://github.com/osTicket/osTicket/issues/2744

2. Enter your text.
Click on the <> button in the menu just above the text window.
Still seeing that?

**Comment by Curium** [comment]
OK, I really did look for the first problem without any luck. So lets drop it here as discussions are ongoing in other treads. 

Regarding number 2. 
I see the same result in code viewer. However I noticed that this does not always aper right away. But if you finish the link and press enter you get a normal line break and the link-text becomes a link. If you then go back to the end of the link and press enter again you will see the abnormal behavior. Also if by chance removed the line break after the link and then try to make a new one you're out of luck. Then you need to remove the link first, make a new line and then add the link back. 
![error1](https://cloud.githubusercontent.com/assets/4319060/14451466/a4b92ba2-0087-11e6-852a-1184a7537bcc.png)
![error2](https://cloud.githubusercontent.com/assets/4319060/14451467/a860d5d4-0087-11e6-817f-07d142897d36.png)

**Comment by ntozier** [comment]
What version of osTicket are you running?
I cannot reproduce this on my installation(s).

**Comment by Curium** [comment]
> I'm currently on osTicket (v1.9.12).
