### ISSUE TITLE
Other type Pages not displayed - OSTicket v1.10-rc.2 (231f11e)

### ISSUE THREAD

**Issue by Taps7734** [osTicket/osTicket#3024]
If I got to ADMIN > MANAGE > PAGES and ADD NEW PAGE, I get the option to create a page of the OTHER type.  Once created, and some content added (doesn't matter if it is the full blown content, or just some test text to use as a place holder) and the page is set to ACTIVE, I see the entry in the client page with the title as a link.  But when I click on the link ( http://domain.com/pages/linkname ) I get a 404 error.

There are no errors in my apache error log besides the 404.  

I would be happy to add any other information, but I dont know what might be considered important.

**Comment by ntozier** [comment]
If you are getting a 404 then that is the error in the log. 
What does the rest of the error say (in the log)?
What webserver software (and ver) are you using?

**Comment by Taps7734** [comment]
192.168.xx.xx - - [11/Apr/2016:13:06:40 -0400] "GET /pages/test HTTP/1.1" 404 208

Server version: Apache/2.4.6 (CentOS)
Server built:   Nov 19 2015 21:43:13

**Comment by simonnzg** [comment]
Warning: Invalid argument supplied for foreach() in /var/www/html/tickets/include/class.page.php on line 322  is the error I get, as well as the 404 error for no page found.

**Comment by Taps7734** [comment]
I found that if I add 

`Options +FollowSymLinks`

to the top of pages/.htaccess then my pages show up as expected, without errors..

**Comment by greezybacon** [comment]
@protich, should the `Options` be specified in the standard release of osTicket?

**Comment by lafaurie** [comment]
I use nginx how to configure this because I have the same problem in 1.10-rc3

**Comment by balojs** [comment]
+1

**Comment by ntozier** [comment]
@lafaurie There are a number of issue reports regarding nginx (which is not a supported software for osTicket) here on github and a lot other people talking about configuration changes needed to make osTicket work with this webserver software. Please search the issues and read them.
