### ISSUE TITLE
deploy --clean removes the ost-config.php file

### ISSUE THREAD

**Issue by jk3us** [osTicket/osTicket#3025]
It looks like this was fixed a long time ago in #60, but I guess it's back.  I just upgraded 1.9.12 to 1.9.13 on my test server, and then did

    php setup/cli/manage.php deploy -Cv /var/www/helpdesk/

And it deleted `include/ost-config.php` and `include/.MANIFEST`

**Comment by greezybacon** [comment]
@jk3us would you mind trying the patches in #3082 to see if they address the issue?

**Comment by jk3us** [comment]
That seems to have fixed this problem!
