### ISSUE TITLE
Saving data without using custom forms

### ISSUE THREAD

**Issue by ccontreras93** [osTicket/osTicket#3026]
Hi good afternoon , I need help with the system , what happens is that you add a column in the database to not use the option form . And I want to know how I can do to save the data.

OSTickets version I use is : osTicket - v1.9.12

![imagen1](https://cloud.githubusercontent.com/assets/18148309/14443671/4db06892-0006-11e6-8c99-63846f9df5c5.png)

**Comment by ntozier** [comment]
Try adding your own Org, and see it saves.  And then see if it can be updated.  

Although I think that something in that section is borked.  (Org info doesn't appear to be getting deleted when one deletes an Org... I have three (3) Test organizations even though the screen only shows two Orgs (osTicket and Test)

**Comment by ccontreras93** [comment]
Yes , what happens is that and add that part (ie , modified form) but when I update the values ​​really are not saved and not like him .

That is, how to modify the code for registering and saving the new data.
