### ISSUE TITLE
.msg attachment behavior wonky (1.9.7 and 1.9.12)

### ISSUE THREAD

**Issue by ntozier** [osTicket/osTicket#3029]
Forum user fgunsili reported:

> We are using 0s-ticket ver.1.9.12 and it works fine. Most
> of the attachment of tickets works fine but only in one case it does not work.
> When we receive  attachment  as (*.msg ) it doesnt appears. We
> couldn’t solve it. What should we do ? Do you have any suggestions ?

source: http://www.osticket.com/forum/discussion/87672/can-not-receive-msg-attachments-in-osticket

I just tried this on my system and it doesn't work right for me either.

**Test 1**
add .msg to the extensions allowed.
Went to Outlook and Save As an email (with out an attachment)
Email ticket system (drag and dropped .msg into my email)
Ticket opens, with the .msg content added after my email text (and signature).
[note: maybe the system should add a separator before the content?]
**Result: Works.**

**Test 2**
add .msg to the extensions allowed.
Went to Outlook and Save As an email (with an attachment [.pdf])
Email ticket system (drag and dropped .msg into my email)
Ticket opens, with **NO** .msg content added.
I get a system message that reads: 

DATE time am          File Import Error
FILENAME:Unable to save file
**Result: Fails.**

Note 1: I was also under the impression that .msg was being phased out in favor of the .eml format.
Note 2: I tested on version 1.9.7 since that's the version my live sites run currently.

**Comment by kest874** [comment]
This is still an issue in 1.10rc2 and rc3 with a .msg that has an attachment inside however it's throwing an error: 

>  Call to a member function logNote() on null line 917

![image](https://cloud.githubusercontent.com/assets/12860950/16819198/f79b3366-4910-11e6-9257-a868fcce0f0e.png)

then stops processing email, so every time cron runs it fetches the same mail throwing the error again.  

I've work around it for now with:

![image](https://cloud.githubusercontent.com/assets/12860950/16819284/52d54f00-4911-11e6-899e-d88501405d53.png)

the actual error is `string(33) "image001.png: Unable to save file"`

**Comment by greezybacon** [comment]
If the `.msg` attachment MIME type is `application/tnef`, then the system will assume that Outlook has included it as a better format for the self-same email. This is because Outlook will send a text message body and a TNEF attachment which will include an HTML or rich text body, along with all the other attachments.

If, when attaching a .msg attachment, it will become a `application/tnef` attachment, then the system will not process it as a "regular" attachment, it will process it as **the entire email**, in a better format.

**Comment by greezybacon** [comment]
@kest874 I opened #3272 to attempt to fix the bug you demonstrated

**Comment by kest874** [comment]
I'll test it later this morning and provide some feedback.

**Comment by kest874** [comment]
This works, it now logs that it couldn't save the file, and continues to process.

**Comment by FG-Lars** [comment]
Anyone working on a fix to this? 

Would be nice for our users to be able to attach .msg files when replying to a ticket.
