### ISSUE TITLE
Translation on Crowdin: osTicket 1.10 - organization strings

### ISSUE THREAD

**Issue by mlipok** [osTicket/osTicket#3036]
http://jipt.i18n.osticket.com/scp/orgs.php
I click in "Add Organization"

There is no string to translate for: 

"Details on user organization"
"Name:"
"Address:"
"Phone:"
"Website:"
"Internal Notes:"

Also in organization settings, there is no string to translate for:
"Organization ticket sharing allows members access to tickets owned by other members of the organization."

"Collaborators always have access to tickets."

"Ticket Sharing"

**Comment by Chefkeks** [comment]
At least the last one "Ticket Sharing" is there - just proofread and approved it some days ago. Don't know currently about the other strings you listed here.

But I found other issues that e.g. some strings are split so many times that it's not possible to translate them in a way that the result sounds correct in German.

I opened several issues over at Crowdin and also a pull request here at GitHub, but still waiting for a response from @greezybacon.

**Comment by Chefkeks** [comment]
https://github.com/osTicket/osTicket/pull/3027

**Comment by greezybacon** [comment]
@Chefkeks, I gave you a thumbs-up reaction. I hope to make another round through the Crowdin phrases early next week.

**Comment by Chefkeks** [comment]
@greezybacon Thanks for telling me - wouldn't have noticed it otherwise since it looks like Github does not make any notification for reactions (yet) :(
I'll make several more commits to that pull request with the issues already found over at Crowdin, so you can cherrypick that they get fixed ;)

**Comment by greezybacon** [comment]
@Chefkeks sounds good. Please don't let me impede your progress.

**Comment by balojs** [comment]
👍
