### ISSUE TITLE
Fatal Error when user must change password

### ISSUE THREAD

**Issue by jk3us** [osTicket/osTicket#3039]
When a user clicks a password reset link and gets to the profile page where they have to change their password, an ajax request to autocron.php is fired.  autocron.php requires staff.inc.php, which then requires profile.php (because `$thisstaff->forcePasswdChange()` is true).  profile.php then fails at line 45 because `$nav` isn't defined (because staff.inc.php doesn't define it when AJAX_REQUEST is set).

This happens in 1.9.12 and the 1.9.13 tag in the git repo.

**Comment by rayfoss** [comment]
Is this still happening with 1.10? to be clear, this only happens when using autocron?

**Comment by stonecan** [comment]
It's still happening in 1.10, clean install. Here's the log:
```
[error] 2035#2035: *415 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function setTabActive() on null in /var/www/html/osticket/scp/profile.php:50
Stack trace:
#0 /var/www/html/osticket/scp/staff.inc.php(133): require()
#1 /var/www/html/osticket/scp/autocron.php(18): require('/var/www/html/o...')
#2 {main} thrown in /var/www/html/osticket/scp/profile.php on line 50" while reading response header from upstream```
