### ISSUE TITLE
Duplicate subjects

### ISSUE THREAD

**Issue by mohankarunasiri** [osTicket/osTicket#3040]
The attached document shows you duplicate tickets but the serial number is unique all other contents are duplicate. Please let me know a method to solve this problem.
Thanks,
Mohan.

osTicket Version - 1.9.5

![duplicate tickets](https://cloud.githubusercontent.com/assets/18019138/14557046/e4e4a2e0-0318-11e6-8f42-5ab4a0c19c72.png)

**Comment by ntozier** [comment]
"osTicket Version - 1.9.5"
^
I'd start with "Upgrade".

**Comment by ntozier** [comment]
You cross posted to the forums. with this info:
osTicket Version 	v1.9.5.1 (1faad22)
Web Server Software 	Apache/2.4.10 (Unix) OpenSSL/1.0.1j PHP/5.5.19 mod_perl/2.0.8-dev Perl/v5.16.3
MySQL Version 	5.6.21
PHP Version 	5.5.19

**Comment by mohankarunasiri** [comment]
Email fetching frequency is set for every 10min.
![fetching email via imap or pop](https://cloud.githubusercontent.com/assets/18019138/14732129/1887c7ce-0875-11e6-8368-b2854b195737.png)

**Comment by ntozier** [comment]
Have you upgraded yet?
How often are you running cron?  (showing me a screen shot of your fetch frequency does not answer this question)
