### ISSUE TITLE
FeatureRequest: Organization name on "Users List"

### ISSUE THREAD

**Issue by mlipok** [osTicket/osTicket#3042]
Please add new collumn "Organization" on "Users list" 
In this way there be posibility to validate which user have not assigned their organization.

**Comment by AlexYoung28** [comment]
+1

**Comment by mlipok** [comment]
There is a small icon with funny faces to add HandsUp

**Comment by infectormp** [comment]
duplicate of https://github.com/osTicket/osTicket/issues/1981

**Comment by rbukovansky** [comment]
My PR #3191 should resolve this issue.

**Comment by mlipok** [comment]
I agree. So I close my request and waiting for one of other will be done.
