### ISSUE TITLE
FeatureRequest: Organization  on Dashboard

### ISSUE THREAD

**Issue by mlipok** [osTicket/osTicket#3043]
on Dashboard there are statistics for 
Departments
Topics
Agents

Please add also statistics for Organizations

I think this is very important to have information which organization post most tickets, and which organization have to many not solved/closed tickets.

**Comment by mlipok** [comment]
@JediKev  Any comment as to the reasons for closing this ticket/FeatureRequest/BugReport?

**Comment by JediKev** [comment]
@mlipok 

This was closed due to how old it is and the lack of activity. If this is still an issue please re-open.

Cheers.

**Comment by mlipok** [comment]
Please re-open.
This is still valid Feature Request.
To other user please confirm if you agree with me.

**Comment by mlipok** [comment]
And some suplemental request:
Add Organization and Teams
