### ISSUE TITLE
Default date in new ticket

### ISSUE THREAD

**Issue by catbadger** [osTicket/osTicket#3044]
When the date of a new ticket is left blank, it defaults to 1970-01-01 it should probably not allow a blank date or default to something relevant to the ticket like a blank value or the current date.

**Comment by ntozier** [comment]
Version of osTicket?
I have NEVER had this happen and I never enter dates for new tickets.

**Comment by catbadger** [comment]
rc2

**Comment by ntozier** [comment]
I have two test 1.10rc2 installations.  I cannot replicate this report on either of them.

**Comment by catbadger** [comment]
what does it default to?

**Comment by ntozier** [comment]
The current date.

**Comment by catbadger** [comment]
this was caused by my fix in this PR  https://github.com/osTicket/osTicket/pull/2975
repaired and updated in PR.
