### ISSUE TITLE
"Installing osTicket 1.8-git" while the checked out tag is v1.9.13

### ISSUE THREAD

**Issue by itwy** [osTicket/osTicket#3045]
The installer and control panel say "Installing osTicket 1.8-git" but I want to install the latest stable release: https://github.com/osTicket/osTicket/releases

What is wrong?

Thanks.

**Comment by mfelber** [comment]
As far as I know official releases of osticket are announced at the forum http://osticket.com/forum/categories/announcements and it is recommended to download them here: http://osticket.com/download . So I think 1.9.13 is not officially released..

**Comment by infectormp** [comment]
1.9.13 is official https://github.com/osTicket/osTicket/releases

**Comment by Chefkeks** [comment]
Just because there is an version tag on github, it does NOT mean its official.

As @mfelber stated correctly
> official releases of osticket are announced at the forum http://osticket.com/forum/categories/announcements and it is recommended to download them here: http://osticket.com/download

So even though there might be a 1.9.13 tag, it's not released officially!

Cheers,
Michael

**Comment by infectormp** [comment]
osticket check for new version at github. So i don't agree with you guys.

**Comment by Chefkeks** [comment]
Maybe @protich or @greezybacon can shed some light into this discussion and decide if it's necessary to adjust the update checking process, so only officially released versions are shown under the system dashboard and not any head rev / tagged version from git (as far as I understood the code correctly :D)

**Comment by ntozier** [comment]
@infectormp You are welcome to your opinion, but in this case it is not correct.  osTicket releases **ALWAYS** have a forum announcement and are made available at osticket.com/download.  If it is not at osticket.com/download then it simply is not an "official release" until such time that it is added there.  

The problem this time is that someone made the tag in preparation for the release and then there was a delay.  They [tags] usually get made shortly before the release so this exact situation doesn't happen.

**Comment by greezybacon** [comment]
There's a DNS update that is necessary to fix the admin dashboard for the "out of date" check. Sorry, we're still unwinding some behind-the-scenes projects to the development back on track.

**Comment by itwy** [comment]
Got it. Thanks guys.
