### ISSUE TITLE
Agents are not sorted by name, but by username (1.10-RC2)

### ISSUE THREAD

**Issue by rbukovansky** [osTicket/osTicket#3046]
I tried to sort my Agents list by name, but I'm getting the list sorted by username instead. See attached picture.
![agent_sorting_by_name](https://cloud.githubusercontent.com/assets/1004491/14600339/4ce465d4-055c-11e6-8f0d-26b64c1e4ec2.png)

**Comment by rbukovansky** [comment]
Jméno = Name
Uživatelské jméno = Username

**Comment by ntozier** [comment]
Your screen shot tells me that your Agents are sorted by their last name.

**Comment by greezybacon** [comment]
It seems like the records *should* be sorted by lastname, firstname. Correct?

**Comment by rbukovansky** [comment]
Exactly, greezebacon.
