### ISSUE TITLE
No attachments in emails for new tickets.

### ISSUE THREAD

**Issue by catbadger** [osTicket/osTicket#3047]
Attachments aren't attached to emails on new tickets. Oddly enough, they are working on responses.

**Comment by catbadger** [comment]
possible fix in include/class.ticket.php

```diff
@@ -3591,8 +3591,13 @@ static function open($vars, &$errors) {
             else
                 $signature='';
 
-            $attachments = ($cfg->emailAttachments() && $response)
-                ? $response->getAttachments() : array();
+            $attachments = array();
+            //this is the attachment bug
+            if($tform->getField('message')->getWidget()->getAttachments($cfg)) {
+                $attachments = $ticket->getThread($vars)->getLastMessage()->getAttachments();
+            }elseif($cfg->emailAttachments() && $response) {
+                $attachments = $response->getAttachments();
+            }

```

**Comment by greezybacon** [comment]
@catbadger I'm confused. Ticket creation via email does not go through `Ticket::open`, which you modified here. It goes through `Ticket::create`. I don't see how your fix would address the problem you describe.

**Comment by catbadger** [comment]
Ticket::open calls Ticket::create. This fix worked for me. How would you fix it with the offending code being in ticket::open?

**Comment by protich** [comment]
@catbadger - Why would you be attaching attachments to a message  when you're opening a ticket on behalf of the user? Issue detail is meant to describe the issue. If you want attachments sent to user then you need to attached them to the response.

**Comment by catbadger** [comment]
@protich why would you build it into the interface and not allow it? secondly our support team needs to attach to the ticket, like the UI appears to allow.

**Comment by protich** [comment]
@catbadger -- You're missing the point -- you can attach documents, if you wish, but it won't get sent as part of the response. And for your information you can disable (hide) issue summary and details via help topic setting.

Your proposed change tries to propagate files attached to message as part of response -- that's what I have issues with.

**Comment by catbadger** [comment]
So whats the right way? Care to illustrate with code?

**Comment by greezybacon** [comment]
You can add the files in the templates with these tokens
```
%{message.files}
%{response.files}
```

**Comment by catbadger** [comment]
but then there's no code to actually attach the files?

**Comment by greezybacon** [comment]
`%{message.files}` is resolved for email template processing and throws an `OOBContent` exception to interrupt the template processing and add attachments
https://github.com/osTicket/osTicket/blob/develop/include/class.thread.php#L1099-L1100

and the template variable replacement engine handles the `OOBContent` by adding the files into the `extras` array
https://github.com/osTicket/osTicket/blob/develop/include/class.variable.php#L136-L140

at the end of the variable replacement system, `TextWithExtras` is returned to reflect the HTML content of the template along with the attachments
https://github.com/osTicket/osTicket/blob/develop/include/class.variable.php#L119-L121

and the mailer handles the `TextWithExtras` object by extracting the HTML text and adding the attachments
https://github.com/osTicket/osTicket/blob/develop/include/class.mailer.php#L424-L432
