### ISSUE TITLE
List of TEAMS not showing up - [v1.10-rc.2-328-g5acdf56]

### ISSUE THREAD

**Issue by Taps7734** [osTicket/osTicket#3048]
Server Information
osTicket Version    v1.10-rc.2-328-g5acdf56 (5acdf56) —  Up to date
Web Server Software Apache/2.4.6 (CentOS) PHP/5.4.16
MySQL Version   5.5.47
PHP Version 5.4.16

When I go to look at the list of created teams (/scp/teams.php) the list is always empty.  Even if I just created one.  If I look at the list of teams I can auto-assign a ticket to, I see the teams I have created,

in /include/staff/teams.inc.php on line 98 I see the following:

`'members_count'=>SqlAggregate::COUNT('members__staff', true),`

if I remove the `__staff` part, then I can see the list, and edit them.

**Comment by greezybacon** [comment]
@Taps7734 good find. Looks like all your teams have no members. Could you try the fix in #3052?

**Comment by Taps7734** [comment]
That is exactly the issue.  I had created a team as a placeholder.  And then later when I went to add the agents, the teams didn't show up in the list.  Your suggested fix #3052 worked.
