### ISSUE TITLE
Help Topics Manual Sort Not Working [v1.10-rc.2-328-g5acdf56]

### ISSUE THREAD

**Issue by Taps7734** [osTicket/osTicket#3049]
Server Information
osTicket Version	v1.10-rc.2-328-g5acdf56 (5acdf56) —  Up to date
Web Server Software	Apache/2.4.6 (CentOS) PHP/5.4.16
MySQL Version	5.5.47
PHP Version	5.4.16

/scp/helptopics.php does allow me to select that sorting mode be "Manually", and allows me to drag the topics upand down in the order I prefer.  But when I hit save, they all go back to Alphabetical sorting.

**Comment by greezybacon** [comment]
@Taps7734 good find. Could you try the patch in #3053 and see if it addresses the issue?

**Comment by Taps7734** [comment]
#3053 fixed the issue
