### ISSUE TITLE
Team Reassignment 

### ISSUE THREAD

**Issue by UkaLee** [osTicket/osTicket#3055]
Hi,

I am currently working with 1 Department and 2 Teams.

2 teams with several Agents.
1st Level Support
2nd Level Support
Problem : 

I am working on a ticket and i am not able to solve it, so i want to re queue it, but this is not possible. I am able to Transfer it to the 2nd Level Support but not to the 1st Level Support.
I can only Select a Specific Agent on the 1st Level Support but not the Queue.

Thx

osTicket Version
v1.9.12 (19292ad)
— Up to date

Web Server Software
Apache/2.4.10 (Debian)
MySQL Version
5.5.46
PHP Version
5.6.17-0+deb8u1

**Comment by ntozier** [comment]
Sounds to me like its already assigned to you and the 1st Level Support team.

**Comment by UkaLee** [comment]
Correct but I need to re queue it and It needs to be flagged as Open and without Agent Assigned.
So the colleagues can see it and work on the ticket.

**Comment by ntozier** [comment]
I'm of the opinion that If its assigned to the you and the team, then your colleagues can see and work on the ticket. Tickets can have two assignee's: Person (individual) AND Team / Department.

**Comment by greezybacon** [comment]
A department manager can unassign it. Perhaps you should promote yourself?

**Comment by UkaLee** [comment]
Took the easy way and removed the auto assignment from the tickets, and everyone is able to claim it.
