### ISSUE TITLE
Cant CANCEL or RESET new ticket. (v1.10-rc.2-328-g5acdf56)

### ISSUE THREAD

**Issue by Taps7734** [osTicket/osTicket#3056]
Server Information
osTicket Version v1.10-rc.2-328-g5acdf56 (5acdf56) —  Up to date  
Web Server Software Apache/2.4.6 (CentOS) PHP/5.4.16 
MySQL Version 5.5.47 
PHP Version 5.4.16 

When creating a new ticket, clicking RESET or CANCEL has no effect.

No errors logged on server, nor in browsers.

**Comment by ntozier** [comment]
Report Confirmed.

v1.10rc2 (231f11e)
IIS/8.5
Mysql 5.542
PHP 5.6.12

**Comment by rbukovansky** [comment]
Not working for me either.

CentOS 7/Apache 2.4.6-40.el7.centos
MariaDB 5.5.47-1.el7_2
PHP 5.4.16-36.el7_1

**Comment by rbukovansky** [comment]
osTicket 1.10-RC + #3075
