### ISSUE TITLE
Errors in apache log when opening new ticket (v1.10-rc.2-328-g5acdf56)

### ISSUE THREAD

**Issue by Taps7734** [osTicket/osTicket#3057]
Server Information
osTicket Version v1.10-rc.2-328-g5acdf56 (5acdf56) —  Up to date  
Web Server Software Apache/2.4.6 (CentOS) PHP/5.4.16 
MySQL Version 5.5.47 
PHP Version 5.4.16 

When I go to the new ticket page, I receive the following error 3 times.

`PHP Warning:  Missing argument 1 for DynamicFormEntryAnswer::save(), called in /var/www/html/include/class.dynamic_forms.php on line 1272 and defined in /var/www/html/include/class.dynamic_forms.php on line 1417, referer: http://support.domainname.com:82/scp/tickets.php?a=open&uid=23`

**Comment by fragtion** [comment]
I'm seeing a similar error with php7 using the latest develop release - "Warning: Declaration of DynamicFormEntryAnswer::save($refetch) should be compatible with VerySimpleModel::save($refetch = false) in /home/www/rapalasa/htdocs/support_ost/include/class.dynamic_forms.php on line 0" -- maybe it's related?

**Comment by fragtion** [comment]
I was able to fix the error I just mentioned by changing the following line in '/include/class.dynamic_forms.php':

`    function save($refetch) {`
to
`    function save($refetch=true) {`

Maybe this will solve your error too?

**Comment by greezybacon** [comment]
Thanks for the heads up. I fixed this in e44a331
