### ISSUE TITLE
cgi.fix_pathinfo  (v1.10-rc.2-328-g5acdf56)

### ISSUE THREAD

**Issue by Taps7734** [osTicket/osTicket#3058]
Server Information
osTicket Version v1.10-rc.2-328-g5acdf56 (5acdf56) —  Up to date  
Web Server Software Apache/2.4.6 (CentOS) PHP/5.4.16 
MySQL Version 5.5.47 
PHP Version 5.4.16 

PHP Settings
cgi.fix_pathinfo  "1" is recommended if AJAX is not working  

I get the exclamation mark no matter what the setting in the php.ini is:  Default, 0, or 1.

To be honest, since I haven't ben able to change this, I cant verify what AJAX was supposed to do to determine if it was working or not.

**Comment by ntozier** [comment]
"I get the exclamation mark no matter what the setting in the php.ini is: Default, 0, or 1."

Then you haven't changed it in the right php.ini 
-OR-
you did not restart Apache after making the change.

**Comment by Chefkeks** [comment]
-OR-
You're running PHP as an apache module (like I do), then the exclamation mark will stay (unless you switch to FastCGI for PHP)

**Comment by Taps7734** [comment]
@ntozier I only have the one php.ini.  This virtual machine is only doing this one service.  So that narrows down which one to edit.  And I restart apache each time.

@Chefkeks That makes sense.  But I hadn't seen any documentation about it.

**Comment by greezybacon** [comment]
>  if AJAX is not working

Have you observed, besides the exclamation mark, whether anything is *not* working?

**Comment by Taps7734** [comment]
@greezybacon As I stated before, I don't have anything to compare it to, so I cant confirm or deny that AJAX is functioning.

**Comment by ntozier** [comment]
mouse over any ? in the settings menus.
Do you get a pop up?

Click new ticket.  Does a Create New user window open?

**Comment by Taps7734** [comment]
If that is the function of AJAX, then yes, it appears to be working correctly even though the exclamation mark is there.

Is there a way to check to see if PHP is running as a module as suggested by @Chefkeks and changing the red ! so that it doesn't appear to be an issue when it isn't one?

**Comment by ntozier** [comment]
This might help you understand:
https://docs.joomla.org/Should_PHP_run_as_a_CGI_script_or_as_an_Apache_module%3F

**Comment by Taps7734** [comment]
@ntozier That was informative.

I do wonder how many are running php as an apache module and see this even though it appears to be working.
