### ISSUE TITLE
Suggestion - Toggle email delivery in log

### ISSUE THREAD

**Issue by Taps7734** [osTicket/osTicket#3059]
Is there any way to add a quick toggle in the system alerts to log an email being delivered?  Maybe just FROM, TO, Subject, and Mail Server response?

I am always looking to ensure notifications were sent out, and hopping back and forth to our mail server remotely can be awkward.  Having the ability to add it directly to the system log would be helpful.

**Comment by infectormp** [comment]
Not sure is this possible. I use DavMail as mail gateway for Exchange, so i always see sent mail in mailbox.
