### ISSUE TITLE
osTicket PHP dependency should actually be 5.4+

### ISSUE THREAD

**Issue by ntozier** [osTicket/osTicket#3060]
According to:
https://pear.php.net/package/Net_LDAP2

![ldap2](https://cloud.githubusercontent.com/assets/1315768/14743292/deec25c4-086e-11e6-80dc-ce7c06dde24c.png)

This to me would mean that osTicket's PHP dependency should at least match.
Right?

**Comment by greezybacon** [comment]
#2828
