### ISSUE TITLE
[1.10rc2] You cannot select SLA - None - at Department, Help Topic, or Filter

### ISSUE THREAD

**Issue by ntozier** [osTicket/osTicket#3061]
I'm opening this for 1.10rc2 but this is also true on older versions as well. (1.9.x)

You **can** set the Default SLA to - None - at 
![set-tick-sla](https://cloud.githubusercontent.com/assets/1315768/14743753/2f7432c8-0871-11e6-964b-502cfaa5b819.png)

However you **cannot** select - None - at any other level. Such as:
Department level
![dept-sla](https://cloud.githubusercontent.com/assets/1315768/14743767/42e3e948-0871-11e6-9c54-9f41cd334ef7.png)

Help Topic level
![htopic-sla](https://cloud.githubusercontent.com/assets/1315768/14743780/514d53b6-0871-11e6-9089-0eab427bbc6b.png)

Ticket Filter level
![filter-sla](https://cloud.githubusercontent.com/assets/1315768/14743786/5b782686-0871-11e6-834e-5e23c97a9435.png)

While I understand that you can simply look at the problem backwards and start off Applying - None - and then increase the SLA (by adding one) at those levels it seems to me that it should be able to be done in either direction.

note: You can also select -None- when you edit a ticket, but that didn't really seem terribly pertinent to the thread.

**Comment by jdelhome3578** [comment]
I asked about this in #2804

**Comment by ntozier** [comment]
I knew I had seen it before... but couldn't find it when I searched. :)
