### ISSUE TITLE
PHP 7.0.5 on Windows IIS8 Errors

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket#3063]
Warning: Declaration of TicketModel::delete() should be compatible with VerySimpleModel::delete($pk = false) in C:\inetpub\osTicket\RC\include\class.user.php on line 36

Warning: Declaration of User::delete() should be compatible with VerySimpleModel::delete($pk = false) in C:\inetpub\osTicket\RC\include\class.user.php on line 161

Warning: Declaration of Organization::delete() should be compatible with VerySimpleModel::delete($pk = false) in C:\inetpub\osTicket\RC\include\class.organization.php on line 406

Warning: Declaration of DynamicForm::delete() should be compatible with VerySimpleModel::delete($pk = false) in C:\inetpub\osTicket\RC\include\class.dynamic_forms.php on line 246

Warning: Declaration of DynamicFormField::delete() should be compatible with VerySimpleModel::delete($pk = false) in C:\inetpub\osTicket\RC\include\class.dynamic_forms.php on line 654

Warning: Declaration of DynamicFormField::save() should be compatible with VerySimpleModel::save($refetch = false) in C:\inetpub\osTicket\RC\include\class.dynamic_forms.php on line 654

Warning: Declaration of DynamicFormEntry::delete() should be compatible with VerySimpleModel::delete($pk = false) in C:\inetpub\osTicket\RC\include\class.dynamic_forms.php on line 1049

Warning: Declaration of DynamicFormEntryAnswer::delete() should be compatible with VerySimpleModel::delete($pk = false) in C:\inetpub\osTicket\RC\include\class.dynamic_forms.php on line 1166

Warning: Declaration of SelectionField::getWidget() should be compatible with FormField::getWidget($widgetClass = false) in C:\inetpub\osTicket\RC\include\class.dynamic_forms.php on line 1381

Warning: Declaration of TypeaheadSelectionWidget::render($how) should be compatible with ChoicesWidget::render($mode = false) in C:\inetpub\osTicket\RC\include\class.dynamic_forms.php on line 1457

Warning: Declaration of DynamicList::delete() should be compatible with VerySimpleModel::delete($pk = false) in C:\inetpub\osTicket\RC\include\class.list.php on line 132

Warning: Declaration of DynamicListItem::delete() should be compatible with VerySimpleModel::delete($pk = false) in C:\inetpub\osTicket\RC\include\class.list.php on line 456

Warning: Declaration of TicketStatus::delete() should be compatible with VerySimpleModel::delete($pk = false) in C:\inetpub\osTicket\RC\include\class.list.php on line 779

Warning: Declaration of TicketStatus::create($ht) should be compatible with VerySimpleModel::create($ht = false) in C:\inetpub\osTicket\RC\include\class.list.php on line 779

Warning: Declaration of Message::create($vars, &$errors) should be compatible with ThreadEntry::create($vars) in C:\inetpub\osTicket\RC\include\class.thread.php on line 1261

Warning: Declaration of Message::add($vars, &$errors) should be compatible with ThreadEntry::add($vars) in C:\inetpub\osTicket\RC\include\class.thread.php on line 1261

Warning: Declaration of Response::create($vars, &$errors) should be compatible with ThreadEntry::create($vars) in C:\inetpub\osTicket\RC\include\class.thread.php on line 1313

Warning: Declaration of Response::add($vars, &$errors) should be compatible with ThreadEntry::add($vars) in C:\inetpub\osTicket\RC\include\class.thread.php on line 1313

Warning: Declaration of Note::create($vars, &$errors) should be compatible with ThreadEntry::create($vars) in C:\inetpub\osTicket\RC\include\class.thread.php on line 1352

Warning: Declaration of Note::add($vars, &$errors) should be compatible with ThreadEntry::add($vars) in C:\inetpub\osTicket\RC\include\class.thread.php on line 1352

Warning: Declaration of RandomSequence::save() should be compatible with VerySimpleModel::save($refetch = false) in C:\inetpub\osTicket\RC\include\class.sequence.php on line 234

Fatal error: Cannot declare class Error, because the name is already in use in C:\inetpub\osTicket\RC\include\class.error.php on line 43

**Comment by ntozier** [comment]
version of osTicket?

and this: https://github.com/osTicket/osTicket/pull/2828

**Comment by jdelhome3578** [comment]
Latest develop tip from today
