### ISSUE TITLE
Suggestion - Add a custom.css file

### ISSUE THREAD

**Issue by Taps7734** [osTicket/osTicket#3064]
In my header.inc.php file I add a line each time for a custom.css file.

```
<link type="text/css" rel="stylesheet" href="<?php echo ROOT_PATH ?>scp/css/translatable.css?956ad7b"/>

<link type="text/css" rel="stylesheet" href="<?php echo ROOT_PATH ?>scp/css/custom.css?956ad7b"/>
```

Then I keep all of my customized CSS in this file so that I only have to update this one inc file each time I update.

Is it possible to add this line in the repo?  And possible a toggle somewhere under system for using it?  So that you can turn it on and off at will for testing?

**Comment by Taps7734** [comment]
In addition to this, I would like to add that all hard-coded table width be removed from the HTML and allow it to be customized via CSS.

**Comment by ntozier** [comment]
> In addition to this, I would like to add that all hard-coded table width be removed from the HTML and allow it to be customized via CSS.

The plan is to make the UI themeable.

**Comment by Taps7734** [comment]
Even better.  I am getting ahead of myself then.

**Comment by ntozier** [comment]
@Taps7734 I just made a PR (pull request) for a possible solution that I have just implemented on my test box (see above).  It doesn't add a toggle, but it allows you to add a custom css file.

**Comment by netbrothers-tr** [comment]
I'm up for it. What's the status on this one?
