### ISSUE TITLE
 Ticket Assignment

### ISSUE THREAD

**Issue by ccontreras93** [osTicket/osTicket#3074]
Hello, good afternoon I need help on how to assign automatic tickets to agents. Following this process:

You get the ticket == > the available agent is assigned (ie , do not have tickets assigned )

OSTickets version I use is : osTicket - v1.9.12

I hope you can help me.

**Comment by ntozier** [comment]
Your desired process seems to contradict itself.  Please clarify.

**Comment by ccontreras93** [comment]
Sorry, what happens is , you get the ticket and if default is assigned to a team , the team member can automatically assign it when accessed

The following image shows the process should continue .

![proceso](https://cloud.githubusercontent.com/assets/18148309/14830276/8a615b1a-0bb5-11e6-8d80-6b7c7ae4053c.png)

get the message === > If the staff is available (no tickets) is assigned the ticket === > if it is not available the staff goes the next staff.

**Comment by ntozier** [comment]
This is not a feature of osTicket at this time.
I do recall that someone on the forums (or here) wrote a mod to assign tickets in a round robin style.

**Comment by ccontreras93** [comment]
Anyway thank you very much.
