### ISSUE TITLE
ADD Organization

### ISSUE THREAD

**Issue by ccontreras93** [osTicket/osTicket#3076]
Hi good afternoon , I would be very grateful if you could help me with a problem, what happens is that you add one more column in the table organization for a data store .

Also, add a field called Account Number using custom forms of organization. Similarly , add the text field in the temporary files in this way the text box for data entry appears.

But , when saving the info of the new organization , saves the data in the custom form and the database,

But it is not reflected in the custom text field , only in the text box inserted manually.

As seen in the imgen , I do so that the new data is part of the render () ? or that part I work?
![columna agregada](https://cloud.githubusercontent.com/assets/18148309/14836647/42883206-0bd7-11e6-9a27-474efe700fb1.png)

![cuadro de texto](https://cloud.githubusercontent.com/assets/18148309/14836685/93df21d2-0bd7-11e6-8ee5-c2b512c003ca.png)

![insert y update](https://cloud.githubusercontent.com/assets/18148309/14836870/09e2437c-0bd9-11e6-9462-1d394df9cf00.png)

How I can do to remove the excess box ? or to reflect the data in that picture?
OSTickets version I use is: osTicket - v1.9.12

**Comment by greezybacon** [comment]
This can be done without editing the code or the database. Navigate to Admin Panel -> Manage -> Forms -> Organization Information, add a field there with a the label "Numero de cuenta" and variable field "numcuenta". (Sorry for the missing accents). Use a field type of "Short Answer", and configure the field to require a number.

You should be on your way. The field will show up in the popup dialogs, and is available for email templates via `%{user.org.numcuenta}`

**Comment by ccontreras93** [comment]
Thank you very much , but that way as I could visualize that data in this window?

![addnumcuenta](https://cloud.githubusercontent.com/assets/18148309/14855656/7c0fae2c-0c5a-11e6-9f9a-b14320296e68.png)

**Comment by greezybacon** [comment]
Good question. Sorry there's no simpler way to do this. Something like this might work
```php
<?php
$numero = null;
foreach ($org->getDynamicData() as $entry) {
    if ($F = $entry->getField('numero')) {
        $numero = $F->display($F->getClean());
    }
}
echo $numero;
?>
```

**Comment by ccontreras93** [comment]
Many many thank you very much

**Comment by balojs** [comment]
👍

**Comment by ccontreras93** [comment]
Sorry, and add the column to be displayed in the main window , but not displayed , I'm doing something wrong?
![addnumcuenta](https://cloud.githubusercontent.com/assets/18148309/14865848/5e660002-0c86-11e6-9789-d4902eb4c60b.png)

**Comment by greezybacon** [comment]
@ccontreras93 you'll have to do something a bit more creative to get it to work in the listing. Use the `subject` field as an example in the `include/staff/tickets.inc.php` file. I'll give it a shot in line here:

* Add `cdata__numero` to the values selected from the database (`cdata` for *custom data*)
* Fetch the `numero` custom data field (the field object) to display the data
* Add a header column for the field (looks like you did this)
* Display the value in the column
* Add sorting option to sort by the new column

Or try a patch?...

```patch
diff --git a/include/staff/orgs.inc.php b/include/staff/orgs.inc.php
index feb53ac..3738933 100644
--- a/include/staff/orgs.inc.php
+++ b/include/staff/orgs.inc.php
@@ -18,6 +18,7 @@ if ($_REQUEST['query']) {

 $sortOptions = array(
         'name' => 'name',
+        'numero' => 'cdata__numero',
         'users' => 'users',
         'create' => 'created',
         'update' => 'updated'
@@ -54,7 +55,7 @@ $qstr.='&amp;order='.($order=='-' ? 'ASC' : 'DESC');
 //echo $query;
 $_SESSION[':Q:orgs'] = $orgs;

-$orgs->values('id', 'name', 'created', 'updated');
+$orgs->values('id', 'name', 'created', 'updated', 'cdata__numero');
 $orgs->order_by($order . $order_column);
 ?>
 <div id="basic_search">
@@ -122,6 +123,7 @@ else
         <tr>
             <th nowrap width="4%">&nbsp;</th>
             <th width="45%"><a <?php echo $name_sort; ?> href="orgs.php?<?php echo $qstr; ?>&sort=name"><?php echo __('Name'); ?></a></th>
+            <th width="11%"><a <?php echo $numero_sort; ?> href="orgs.php?<?php echo $qstr; ?>&sort=numero"><?php echo __('Numero'); ?></a></th>
             <th width="11%"><a <?php echo $users_sort; ?> href="orgs.php?<?php echo $qstr; ?>&sort=users"><?php echo __('Users'); ?></a></th>
             <th width="20%"><a <?php echo $create_sort; ?> href="orgs.php?<?php echo $qstr; ?>&sort=create"><?php echo __('Created'); ?></a></th>
             <th width="20%"><a <?php echo $update_sort; ?> href="orgs.php?<?php echo $qstr; ?>&sort=update"><?php echo __('Last Updated'); ?></a></th>
@@ -130,6 +132,7 @@ else
     <tbody>
     <?php
         $ids=($errors && is_array($_POST['ids']))?$_POST['ids']:null;
+        $numero_field = OrganizationForm::getInstance()->getField('numero');
         foreach ($orgs as $org) {

             $sel=false;
@@ -142,6 +145,7 @@ else
             </td>
             <td>&nbsp; <a href="orgs.php?id=<?php echo $org['id']; ?>"><?php
             echo $org['name']; ?></a> </td>
+            <td><?php echo $numero_field->display($org['cdata__numero']); ?></td>
             <td>&nbsp;<?php echo $org['user_count']; ?></td>
             <td><?php echo Format::date($org['created']); ?></td>
             <td><?php echo Format::datetime($org['updated']); ?>&nbsp;</td>
```

**Comment by ccontreras93** [comment]
Thank you, the option to add a new column seems more convenient, and is what I did from the beginning.

The question I have is ..
Where to find the file where the default values ​​are added labels ?, since the modifications I have done , if I do not use the custom form does not allow me to add the data.

Another question , if I use the patch, in case you want to display the data in this window 
![numcuentaticket](https://cloud.githubusercontent.com/assets/18148309/14894195/1b3202a6-0d38-11e6-8a10-363841107824.png)

, you should perform another patch ?

**Comment by ccontreras93** [comment]
Hi good afternoon , sorry but the patch is that I recommended earlier
versions and not as incorporating it , I could help ? Since osTicket
version I use is the 9.12.



2016-04-28 11:29 GMT-05:00 Jared Hancock <notifications@github.com>:

**Comment by greezybacon** [comment]
@ccontreras93 I'm not sure what you mean

**Comment by ccontreras93** [comment]
Hi good afternoon , thank you very much , and solve the problem with one more column in the database . regards
