### ISSUE TITLE
1.10rc-2 Not upload file 

### ISSUE THREAD

**Issue by nntu** [osTicket/osTicket#3077]
hi.
Sorry my English ^^
i use 1.8-git (e2315506)
so when i upload file it not work 
![error](https://cloud.githubusercontent.com/assets/316238/14838977/21a2885a-0c51-11e6-90b7-1b41ad9e59cf.png)
![upload](https://cloud.githubusercontent.com/assets/316238/14838978/21a4ebf4-0c51-11e6-99d1-453def223030.png)

**Comment by greezybacon** [comment]
Try updating again. We've had some trouble with the attachments sticking and merged some commits this week. Your codebase is about 50 commits behind now. Try downloading and deploying again

**Comment by nntu** [comment]
hix 
i'm not attach file .
 DB Error #1062

[INSERT INTO `ost_file_chunk` SET `file_id` = 99,  `filedata` = '%PDF-1.5\r\n%

**Comment by greezybacon** [comment]
@nntu that error doesn't make any sense. You have a record in the database for file_id 99. And it's not a whole block (512000 bytes), so there would be no need to add another chunk. Do you have an entire backtrace for the error?
