### ISSUE TITLE
Suggestion - Message of the day

### ISSUE THREAD

**Issue by Atriusftw** [osTicket/osTicket#3079]
Just a quick suggestion that hit my mind.

A pretty neat feature would be to have a simple message of the day when agents log in, to give instructions or information.

Maybe make it float either to the left or right with an appearance of a sticky note with a small x in the top corner to close it.

With the new ACL rewamp in 1.10, access to creating these MOTDs could be granted pretty simple aswell.
A function to define timespan of that specific "note" would also be a nice touch.

Thoughts?

**Comment by greezybacon** [comment]
My personal opinion is that this would make a really nice plugin. The missing component is a way for plugins to add content to the main screens of osTicket
