### ISSUE TITLE
Translation: 1.10

### ISSUE THREAD

**Issue by mlipok** [osTicket/osTicket#3080]
I go here:
http://jipt.i18n.osticket.com/

**Question:**
Why this strings:

> Welcome to the Support Center
> In order to streamline support requests and better serve you, we utilize a support ticket system. Every support request is assigned a unique ticket number which you can use to track the progress and responses online. For your reference we provide complete archives and history of all your support requests. A valid email address is required to submit a ticket.

Are not showing as translated to Polish ?

I see they are translated here:
https://crowdin.com/translate/osticket-official/all/enus-pl#2123
https://crowdin.com/translate/osticket-official/all/enus-pl#507

EDIT:
the same here:
https://crowdin.com/translate/osticket-official/all/enus-pl#7337

**Comment by ntozier** [comment]
Well because that text isn't static.  
It's in the ui at: Admin panel -> Manage -> Pages -> Landing

**Comment by mlipok** [comment]
When I go to the landing page via
http://jipt.i18n.osticket.com/

Then I get:
Warning: Invalid argument supplied for foreach() in /var/www/osticket.com/jipt.i18n/include/class.page.php on line 322
![crowdin_landingpages_saveissue](https://cloud.githubusercontent.com/assets/11089482/14867893/14d7ebc2-0ccb-11e6-8b88-a333000b1fd7.png)

**Comment by ntozier** [comment]
I'm not sure why you are reporting this here.

**Comment by mlipok** [comment]
As I understand this issue with Saving Landing Page I should report to Crowdin (as I does) here I only notice this (I mention about in my EDIT:.....).

**Comment by ntozier** [comment]
the landing page translation is not in Crowdin... its in the osticket ui stored in the DB.

**Comment by greezybacon** [comment]
@ntozier @mlipok the landing page is translatable, but only via Crowdin.

**Comment by mlipok** [comment]
Finally 
Wthether the issue:
Warning: Invalid argument supplied for foreach() .....

should be fixed by Crowdin ?
