### ISSUE TITLE
Status name, "Open to Abierto", Don't Save :: Develop-Next

### ISSUE THREAD

**Issue by balojs** [osTicket/osTicket#3084]
Step 1
Manage>>Lists>>Ticket Status

Step 2
Edit Open Value.
![screenshot](https://cloud.githubusercontent.com/assets/3303352/14895513/51482e44-0d36-11e6-9d5e-d97208f536e4.png)

Step 3
Save

Results
![screenshot](https://cloud.githubusercontent.com/assets/3303352/14895534/64655d12-0d36-11e6-811d-cd2374181b06.png)

**Comment by rbukovansky** [comment]
Same for me (1.10-RC2+latest git/develop)

**Comment by rbukovansky** [comment]
BTW I have this translated in ticket_status.yaml as well and it's not translated system wide.

**Comment by mfelber** [comment]
BTW I think the ticket_status.yaml will only be used when osticket is installed with this language (which is not possible yet for 1.10). Due to this bug which prevents editing the name you could only change the name in the table ticket_status table directly.

**Comment by greezybacon** [comment]
Can anyone try the patch in #3236 to see if it addresses the issue?

**Comment by mfelber** [comment]
I have tested the patch and it works fine :-)

**Comment by balojs** [comment]
thanks @greezybacon 👍

**Comment by balojs** [comment]
it works fine!
