### ISSUE TITLE
On image annontation in the broserw the save faild with a DB error

### ISSUE THREAD

**Issue by tomlaf** [osTicket/osTicket#3086]
Osticket, Deleop Branch (hash 784184b6dd5846ad9a73c632592dfaaad4b69030)
Serveur : IIS on Windows 2012 R2
PHP 5.6.16
MySQL 5.7.11

Step create a ticket, copy past a picture, do anotate, try to save then this error will be generated : 

[INSERT INTO `ost_attachment` SET `file_id` = 4, `type` = 'D', `object_id` = 23]

Duplicate entry '23-4-D' for key 'file-type'<br /> <br />
---- Trace ----<br />
#0 C:\inetpub\osticketroot\include\mysqli.php(204): osTicket->logDBError('DB Error #1062', '[INSERT INTO `o...')<br />
#1 C:\inetpub\osticketroot\include\class.orm.php(3121): db_query('INSERT INTO `os...', true, true)<br />
#2 C:\inetpub\osticketroot\include\class.orm.php(596): MySqlExecutor->execute()<br />
#3 C:\inetpub\osticketroot\include\class.attachment.php(161): VerySimpleModel->save()<br />
#4 C:\inetpub\osticketroot\include\ajax.draft.php(101): GenericAttachments->upload(Array)<br />
#5 C:\inetpub\osticketroot\include\ajax.draft.php(300): DraftAjaxAPI->_uploadInlineImage(Object(Draft))<br />
#6 [internal function]: DraftAjaxAPI->uploadInlineImage('23')<br />
#7 C:\inetpub\osticketroot\include\class.dispatcher.php(145): call_user_func_array(Array, Array)<br />
#8 C:\inetpub\osticketroot\include\class.dispatcher.php(38): UrlMatcher->dispatch('23/attach', Array)<br />
#9 C:\inetpub\osticketroot\include\class.dispatcher.php(120): Dispatcher->resolve('23/attach', Array)<br />
#10 C:\inetpub\osticketroot\include\class.dispatcher.php(38): UrlMatcher->dispatch('/draft/23/attac...', NULL)<br />
#11 C:\inetpub\osticketroot\scp\ajax.php(261): Dispatcher->resolve('/draft/23/attac...')<br />
#12 {main}

**Comment by jjjeroenski** [comment]
Same problem here with version v1.10-rc.3 (907ec36)
Any solution found already?
