### ISSUE TITLE
Gmail POP settings not working for incoming mails 

### ISSUE THREAD

**Issue by cyberformed** [osTicket/osTicket#3087]
I have a ticketing system. I am using gmail pop setting for osticket. But any kind of incoming emails are not coming to my admin panel dashboard.

**Comment by ntozier** [comment]
Version of osTicket?
Have to enabled the account to collect email via pop at gmail?
Have you configured a cron job or windows task scheduler to run cron on your server?

**Comment by cyberformed** [comment]
yes I have enabled the pop settings in Gmail as well as cron.

**Comment by robintoy** [comment]
Hi @cyberformed 
do you get any error messages at all when you try and setup the POP3??

Also, as asked by @ntozier what version of osTicket you running?
(PS this might be better in the forums http://osticket.com/forum/categories)
