### ISSUE TITLE
Suggestion: Default Tab when in Ticket View

### ISSUE THREAD

**Issue by halliballi123** [osTicket/osTicket#3091]
Hi everyone, 

I am not sure if this is the right place to post a suggestion. But I'll give it a try.

Most time when we open tickets, we don't reply to the user, we take internal notes.
![osticket_defaulttab](https://cloud.githubusercontent.com/assets/18659349/14949784/f6b978a6-104c-11e6-8896-b9ab5487b64d.PNG)

I suggest that in **options of osTicket** there should be placed an option for **default tab in ticket view**.

At the moment I did a dirty hack and changed the source of _/scp/js/tickets.js _
And I know that the changes are gone, when updating the system.
Thanks in advance

**Comment by ntozier** [comment]
I think that this should be done not at the system level, but at the: system, department, team, and Agent account levels for the most flexibility.

**Comment by clonemeagain** [comment]
This plugin: https://github.com/clonemeagain/osticket-plugin-notefirst was actually built for this, relies on the dev version of https://github.com/clonemeagain/attachment_preview/tree/develop?files=1 my first plugin.

Basically, it injects JavaScript that checks if it's sane to switch tabs, then does so, preserving the warning messages which normally fade onClick.

Haven't figured out how to stop it scrolling down without editing tickets.js yet. If anyone knows, please!
