### ISSUE TITLE
QUESTION : 1.9.13 upgrade

### ISSUE THREAD

**Issue by cervedgroup** [osTicket/osTicket#3092]
Hi, i'm on 1.9.12 , can i use the zip in the github to upgrade at 1.9.13 ?

the downloadable zip in osticket.com is still on 1.9.12

thank you

**Comment by ntozier** [comment]
Can you?  Yes.
Should you?  No.

**Comment by cervedgroup** [comment]
why not ?

**Comment by ntozier** [comment]
It hasn't been officially released.
