### ISSUE TITLE
Adding new user programmatically

### ISSUE THREAD

**Issue by mansha99** [osTicket/osTicket#3095]
Hi
I am trying to integrate OS Ticket with my existing App.
I want users  created at my app to be able to raise ticket without 
registering again on OsTicket support App.
In other words i want ability to add users programmatically to OSTicket App.
It should go like this
    1. User creates a new account on my Web App
    2. This should also add a new user to OsTicket App
    3. Now once user is authenticated (at My App),
    he should be able to raise a ticket on OsTicket App.
    He should also be able to track pending ticket status
    via My App.

Kindly help.

**Comment by ntozier** [comment]
There is no mechanism in the project to do this at this time. You will have to write code so that when your existing App makes the user it also talks to the database and creates the user at the same time.

**Comment by mansha99** [comment]
<?php
echo "Thank you";
?>

**Comment by clonemeagain** [comment]
I recommend writing a plugin utilizing app/despatcher so you can simply send a user to the plugin from your normal app. Then your plugin can make the user easy enough. Maybe the REST API can create users? Dunno, haven't tried.

Then your app can use the REST API to pull tickets for that user as well. Allowing them to track them.
