### ISSUE TITLE
[i18n] Agents expire password combobox translation not read from messages.po (1.10-RC2+git/develop)

### ISSUE THREAD

**Issue by rbukovansky** [osTicket/osTicket#3101]
![settings_agents_settings](https://cloud.githubusercontent.com/assets/1004491/15039413/470f9846-12ad-11e6-8186-c3e9e1ad521e.png)

This is translated in messages.po, but it stays in English...

**Comment by mfelber** [comment]
Why messages.po? Osticket uses messages.mo.php. 

I don't have this problem:
![i18 combo box password reset](https://cloud.githubusercontent.com/assets/5539456/15041403/f5e8c92e-12bb-11e6-87b8-1e8eb80791ba.jpg)

**Comment by rbukovansky** [comment]
I know, but messages.po is on Crowdin...

BTW Which version are you running, please? Thanks.

**Comment by mfelber** [comment]
I'm running (only for testing purposes) 1.10 from github. I have downloaded it april 21st via the download button (develop branch).

I think you have to convert it to a mo-file (for example with poedit) and then convert it to messages.mo.php like it is described here (building language packs):

https://github.com/osTicket/osTicket/blob/develop/setup/doc/i18n.md

**Comment by rbukovansky** [comment]
I have my own .phar file with translation created. The file name is not a issue...

**Comment by mfelber** [comment]
Why should the file name be a issue?

**Comment by rbukovansky** [comment]
You are saying it... I know I need to convert messages.po to message.mo.php and then phar it with the rest of files... I'm just saying that messages file has the translation but it doesn't show up.

The .phar file you are using is official one downloaded from osticket.com? Thanks.

**Comment by mfelber** [comment]
Yes I'm using the content of the latest official phar-file from osticket.com. But I'm using not the phar-file directly.
 
I unphar it and replace the files with the new translated files from crowding. This extracted and modified language pack I'm using for my testing..

**Comment by rbukovansky** [comment]
Interesting... As I understand, osTicket is not able to work with not .phared translation... How did you managed to get it working (wasn't working for me)?

**Comment by mfelber** [comment]
I do nothing special: I just name the folder with the language pack content like the language pack, in my case "de" and then I upload it to the 18-folder. Osticket detects it automatically..

**Comment by rbukovansky** [comment]
Interesting... I have downloaded German translation and it works, but not for Czech translation. Any idea why?

**Comment by mfelber** [comment]
When I try the czech translation it works normal:

![i18 cs](https://cloud.githubusercontent.com/assets/5539456/15068154/8ee7f21c-1375-11e6-85e5-7940914f008f.jpg)

Do you really see the translated content in the messages.mo.php?

Here is mine: 
[messages.mo.php.zip](https://github.com/osTicket/osTicket/files/251781/messages.mo.php.zip)

**Comment by rbukovansky** [comment]
Well, it was in messages.po, but after converting to messages.mo.php it wasn't. Same issue for my other submitted issue about combobox... Damn it.

Was it official Czech .phar file?

BTW How do you convert messages.po to messages.mo.php if you do so?

**Comment by rbukovansky** [comment]
Never mind this issue. Problem with it solved. Wrong conversion from messages.po -> messages.mo.php.

Sorry!

**Comment by mfelber** [comment]
Yes I have used the latest czech-phar from osticket.com (march 28th).

I had the same problems when I tried to convert it the first times.
So don't worry about that.

This are the steps I made:

1) Download the messages.po(t) as single download (click on the three little dots), otherwise some content is missing, because the packages are not build so often:
![crowdin download](https://cloud.githubusercontent.com/assets/5539456/15070864/94e43f56-1387-11e6-9261-c7dabd04a778.jpg)

2) Converting the po-file to a mo-file via poedit (free version, poedit.net):
![mo erstellen](https://cloud.githubusercontent.com/assets/5539456/15071038/fdbcc4b6-1388-11e6-97f6-c08e00b2e4a0.jpg)

3) Using the class.translation.php to create the messages.mo.php:

I run this command (in the include folder of osticket) _php class.translation.php messages.mo > messages.mo.php_
where I uploaded the messages.mo-file before. To avoid the error with the include.dir I remove it temporarily in the class.translation.php (line 857 from require_once INCLUDE_DIR . 'class.orm.php'; torequire_once . 'class.orm.php';)

I know this isn't very "elegant" but my knowledge about php isn't good enough ;-)

**Comment by rbukovansky** [comment]
Yup, same for me now.

**Comment by rbukovansky** [comment]
Now I need to get Ticket statuses and Priorities translation work... And here I'm not able to find what's wrong for real...

**Comment by mfelber** [comment]
My understanding is that this type of content is translatable in the gui of osticket directly:

http://osticket.com/blog/120 (Internationalization, Phase III)
Maybe you found out how it works when you translate some things via the gui and look where the changes are stored..

**Comment by rbukovansky** [comment]
Those are unfortunately things that can't be done that way. AFAIK ticket statuses are using ticket_status.yaml file and priorities are using priorities.yaml file for translation, not the UI.

**Comment by mfelber** [comment]
Oh, yes you are right. Priority.yaml and ticket_status.yaml are used for this.
The translation of these files are only used when the installation process was done with the corresponding language pack! This are not the only parts with this limitation, the email templates for example are affected too or the built in canned responses. 

Osticket 1.10 crashes during the installation with a language pack, so it seems that it is not prepared for that at the moment (I have tested it with 1.9.12 to see the different behavior for priority.yaml and ticket_status.yaml).

I guess this parts of osticket are a little behind the progress of the Internationalization Phase (which is not finished yet).
