### ISSUE TITLE
[i18n] Description of agents templates are not in messages.po (1.10-RC2+git/develop)

### ISSUE THREAD

**Issue by rbukovansky** [osTicket/osTicket#3102]
![settings_agents_templates](https://cloud.githubusercontent.com/assets/1004491/15039447/85463fde-12ad-11e6-98d7-27335c6545da.PNG)

Text marked with yellow can't be translated, I didn't find them in messages.po.

**Comment by mfelber** [comment]
I also see that this part isn't displayed translated. The same content is already translated in the email template section (registration-staff.yaml). I guess only the linking to the content is missing..
