### ISSUE TITLE
[i18n] Description of users templates are not in messages.po (1.10-RC2+git/develop)

### ISSUE THREAD

**Issue by rbukovansky** [osTicket/osTicket#3103]
![settings_users_templates](https://cloud.githubusercontent.com/assets/1004491/15039472/bdc2ca30-12ad-11e6-826e-69f909b76d00.PNG)

Text marked with yellow can't be translated, I didn't find it in messages.po.

**Comment by mfelber** [comment]
I also see that this part isn't displayed translated. The same content is already translated in the email template section (access-link.yaml,banner-client.yaml, etc.). I guess only the linking to the content is missing..
