### ISSUE TITLE
[i18n] Require e-mail verification translation not read from messages.po (1.10-RC2+git/develop)

### ISSUE THREAD

**Issue by rbukovansky** [osTicket/osTicket#3104]
![settings_users_settings](https://cloud.githubusercontent.com/assets/1004491/15039515/0354cb3e-12ae-11e6-843c-269906dc1cd7.PNG)

I have this text translated in messages.po.

**Comment by mfelber** [comment]
I don't have this problem:

![i18 uberprufung schnellzugriff](https://cloud.githubusercontent.com/assets/5539456/15042040/e523021c-12c0-11e6-8aa3-b56ff470c7b7.jpg)

**Comment by rbukovansky** [comment]
Yup. Corrected message.mo.php and it's OK now.

Sorry!
