### ISSUE TITLE
[i18n] Autorefresh combobox translation not read from messages.po (1.10-RC2+git/develop)

### ISSUE THREAD

**Issue by rbukovansky** [osTicket/osTicket#3105]
![staff_panel_my_profile_autorefresh](https://cloud.githubusercontent.com/assets/1004491/15040464/5a99c726-12b5-11e6-9078-f668608c3dfc.png)

This is translated in messages.po.

**Comment by rbukovansky** [comment]
Staff panel -> My profile -> Preferences

**Comment by mfelber** [comment]
I don't have this problem:

![i18 auto refresh rate](https://cloud.githubusercontent.com/assets/5539456/15041778/ebc0f36a-12be-11e6-9886-9952f811147b.jpg)

**Comment by rbukovansky** [comment]
Closing. Wrong conversion of messages.po to messages.mo.php.

Sorry!
