### ISSUE TITLE
[Suggestion] Better icon for new user registration (1.10-RC2+git/develop)

### ISSUE THREAD

**Issue by rbukovansky** [osTicket/osTicket#3106]
There is "smiling face" emoticon used for registration. I would suggest using some kind of "user with plus sign" (see attached) icon...
![new_user_plus_sign](https://cloud.githubusercontent.com/assets/1004491/15041104/bf0648d4-12b9-11e6-9b08-b87a1dee7e3a.png)

**Comment by ntozier** [comment]
I can't decide if that looks more like Cobra Commander (G.I. Joe) or Kylo Ren (Star Wars 7).  But I'm leaning towards Cobra Commander.

**Comment by rbukovansky** [comment]
This is just example how that icon could look like, not the actual icon replacement. That's up to devs to choose the proper icon from their icon set...
