### ISSUE TITLE
How do I display my plugin page between the header and footer?

### ISSUE THREAD

**Issue by meatballcoder** [osTicket/osTicket#3113]
I have this,

```
namespace controller;

require_once(STAFFINC_DIR.'header.inc.php');
require_once(STAFFINC_DIR.'staff.inc.php');
class MyController {
    public function searchAction(){
        require('myplugin.html');
    }
}
require_once(STAFFINC_DIR.'footer.inc.php');
```

But I get,

`Fatal error: Call to a member function getError() on a non-object in C:\osticket\include\staff\header.inc.php on line 58`

How do I make a page in my plugin show up between `header.inc.php` and `footer.inc.php`?  The plugin works and is enabled and works, but the page is not totally integrated without these includes.  Thanks for any help.

I am using `dispatcher.php` in scp if that matters.

The examples I've looked at use twig, so I can't use it.

**Comment by clonemeagain** [comment]
Chuck your code in your repo mate, hard to see without testing it. (Your readme says code coming).

**Comment by meatballcoder** [comment]
I was waiting because of a Pull Request I made.  If it is not approved, I have to figure something else out.  I got this to work, but the repo is empty until I find out about the PR.

**Comment by clonemeagain** [comment]
I had to move dispatcher to get that working as well. I could swear they promised us a plugin manual.

Maybe I should edit the /scp/apps/.htaccess and pull that change. hmm, yeah, that could actually work.
