### ISSUE TITLE
[Suggestion] Custom form title on ticket details

### ISSUE THREAD

**Issue by uziel200** [osTicket/osTicket#3117]
When a Ticket is created and contains a custom form, in the details it just appears the name of field with it respective value. It will be nice that show a division with the title of the custom form, and then the name and value of the field

**Comment by ntozier** [comment]
You may want to provide a mock up image of what you mean,

**Comment by rbukovansky** [comment]
I believe this is already done for 1.10. At least mine shows name of form, additional instructions between main ticket form and custom form.

**Comment by uziel200** [comment]
@rbukovansky you're right, I installed a test environment with the versión 1.10-rc.2 and in the details of the Ticket, the name of the custom form is visible above the fields list.
