### ISSUE TITLE
Validation at new Ticket [1.9.12]

### ISSUE THREAD

**Issue by uziel200** [osTicket/osTicket#3119]
When a new ticket is created is posible to post a response at the same time, but if a file is attachment to the response but nothing is captured in the filed of response the attachment lose it, because the ticket is saved without a response.

This is a user error, but the system should send an alert that are file attachment to a response that is empty and the ticket should not being saved.

**Comment by clonemeagain** [comment]
So you want failed file uploads to prevent a new ticket being made? Or do you mean that an empty response should be acceptable if an upload was submitted?

**Comment by uziel200** [comment]
This is when a member of the staff is opening a new ticket. If there is 1 or more attachment to an empty response the ticket should not being saved. Because the file lost it.

In the image, the ticket is saved, with no response because is empty, but the file is upload successfully. And lost it.

![example](https://cloud.githubusercontent.com/assets/5307189/15232258/acf1a984-1865-11e6-8038-7d28cc7af7fc.png)

**Comment by clonemeagain** [comment]
Oh, the response should be the attachment.  Especially with two upload fields, yes I see.

Even if it's something simple like "See attached" added automatically. That would be useful. Would bypass the error without changing too much else.
