### ISSUE TITLE
Is it safe to truncate the ost__search table?

### ISSUE THREAD

**Issue by tmp2000** [osTicket/osTicket#3121]
My database's ost__search is corrupted ,and can not repaired with "repair table ost__search;" which showed 
+--------------------------+--------+----------+------------------+
| Table                    | Op     | Msg_type | Msg_text         |
+--------------------------+--------+----------+------------------+
| dbname.ost__search | repair | Warning  | Can't open table |
| dbname.ost__search | repair | error    | Corrupt          |
So the another solution would be " drop it/recreat it" or try truncate it.
But I am not sure whether it would impact the tickets system (such as replied tickets,already fetched tickets from emailbox...) . Is "ost__search" just for search function?
Hope to your reply.
Frank

**Comment by ntozier** [comment]
My understanding is that it is for speeding up search. @greezybacon @protich ?
At this point though it doesn't sound like you have much of a choice.  Restore from backup or truncate.

**Comment by greezybacon** [comment]
You can drop it or truncate it. Set the `reindex` value to `1` in your config file afterwards to rebuild the index.
