### ISSUE TITLE
1.9.12 Memory leak in Mail Fetcher

### ISSUE THREAD

**Issue by varuzam** [osTicket/osTicket#3127]
Hi.
Ubuntu 14.04
php 5.5.9-1ubuntu4.16
affected versions v1.10-rc.2 (231f11e) and  v1.9.12
Mail is fetched from GoogleMail  via IMAP or POP

i start `php -f /var/www/osticket/www/api/cron.php` and it use more and more memory (more 8GB) until it is terminated by me.
Email example in attachment

[example_email.txt](https://github.com/osTicket/osTicket/files/262298/example_email.txt)

**Comment by greezybacon** [comment]
I think this will be an upstream bug in PHP's imap extension. We hope to change to use the Zend_Mail library, which we would have more control over fixing.

**Comment by varuzam** [comment]
I found that this problem occurs when i use the action "Use Reply-To Email" in filter

**Comment by varuzam** [comment]
I doubt that this is a bug in the php-imap

**Comment by greezybacon** [comment]
I see. So my guess is that you also mean that there is only a single email which is processed, but no response is ever sent out?

**Comment by mfelber** [comment]
There was a similar case some time ago, maybe it helps: https://github.com/osTicket/osTicket/issues/2414

**Comment by mjakubicek** [comment]
We are facing the same issue -- any hints on a quick fix?

**Comment by varuzam** [comment]
http://osticket.com/forum/discussion/88019/memory-leak-in-mail-fetcher

**Comment by JensEB** [comment]
Please look at https://github.com/osTicket/osTicket/issues/2414
for a solution it´s a bug in Filter::apply()...
