### ISSUE TITLE
DB error when open/close ticket

### ISSUE THREAD

**Issue by wochebs** [osTicket/osTicket#3128]
I got this mail notifications when open or close a ticket: 
osTicket (v1.9.12)

[ INSERT INTO ost_ticket_thread SET created=NOW()  ,thread_type='M' ,ticket_id=3132 ,title='failure notice' ,format='text' ,staff_id='0' ,user_id=39 ,poster='mailer-daemon' ,source='' ,body='Hi. This is the qmail-send program at ......

....

Got a packet bigger than 'max_allowed_packet' bytes<br />
<br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(177): osTicket->logDBError('DB Error #1153', '[ INSERT INTO o...')<br />
#1 (root)/include/class.thread.php(1140): db_query(' INSERT INTO os...')<br />
#2 (root)/include/class.thread.php(1194): ThreadEntry->create(Array)<br />
#3 (root)/include/class.thread.php(1230): ThreadEntry->add(Array)<br />
#4 (root)/include/class.thread.php(1210): Message->add(Array, Array)<br />
#5 (root)/include/class.thread.php(164): Message->create(Array, Array)<br />
#6 (root)/include/class.ticket.php(1773): Thread->addMessage(Array, Array)<br />
#7 (root)/include/class.ticket.php(2821): Ticket->postMessage(Array, 'Email', false)<br />
#8 (root)/include/class.mailfetch.php(763): Ticket::create(Array, Array, 'Email')<br />
#9 (root)/include/class.mailfetch.php(811): MailFetcher->createTicket(1051)<br />
#10 (root)/include/class.mailfetch.php(891): MailFetcher->fetchEmails()<br />
#11 (root)/include/class.cron.php(25): MailFetcher::run()<br />
#12 (root)/scp/autocron.php(64): Cron::MailFetcher()<br />
#13 {main}

**Comment by meatballcoder** [comment]
What is your setting in MySQL for this?

**Comment by ntozier** [comment]
check your my.cnf [mysql] and look at your max_allowed_packet= directive.

**Comment by wochebs** [comment]
Hello, I can't change or view the settings of MySQL.

This problem started last week before everything worked well, I do not think it's an error in the configuration of MySQL.

Is there any way to close / delete those alerts that keep coming to me.

**Comment by ntozier** [comment]
So then that would lead me to ask what happened last week?
What changed that all of a sudden it doesn't work?
Was mysql upgraded? Was the config changed?
To be clear this appears to be a MySQL error, not a PHP or osTicket error.

**Comment by wochebs** [comment]
Last week we received many requests (much more than normal) and began receiving this alert. I try to correct the error by updating to the latest version and everything stayed the same.

The message I get is always the same, but I get it every time I close or open a ticket. Basically it is a lot of characters numbers and letters.

**Comment by ntozier** [comment]
Well you should talk to the admin for your mysql server and tell him that you are getting: 
Got a packet bigger than 'max_allowed_packet' bytes
And that the fix is to increase the "max_allowed_packet" directive in your my.cnf.
Or at least that's the only fix I know for it.

**Comment by meatballcoder** [comment]
Can you connect to the db and do Show Variables?  It will show the MySQL setting you are looking for.  You probably can't set it, but you can view it.  Maybe it's worth a try anyway?

$res = mysql_query("SHOW VARIABLES LIKE 'max%'");
while ($row = mysql_fetch_assoc($res)) {
  echo $row['Variable_name'].':'.$row['Value']."<br>\n";
}

http://stackoverflow.com/questions/2228165/possible-to-show-mysql-variables-with-php-code-onto-the-browser

**Comment by wochebs** [comment]
I contact the server provider and increase "max_allowed_packet" and the problem was resolved for now.

Thank you very much!! .

**Comment by greezybacon** [comment]
Interesting. We automatically truncate the thread entry to be less than `max_allowed_packet`, but only when the thread entry is over 250000 (250k) bytes. Curious @wochebs what was the `max_allowed_packet` set to? We assume it's at least 512k
