### ISSUE TITLE
API of Consult

### ISSUE THREAD

**Issue by evandrosk** [osTicket/osTicket#3130]
Hello,

  I wanted to know if he thought something about external consultation, but no success, I wonder if there and just have not found it, or whether it will be something developed.

  To meet my needs just having to generate a generic to make consultation ticket listing, view a specific ticket and creation attaching file (do not know exactly why the default api could not climb attachments).

Thanks.

**Comment by greezybacon** [comment]
@evandrosk are you asking about accessing external databases from osTicket?
