### ISSUE TITLE
Capture Advanced Search Query

### ISSUE THREAD

**Issue by tjob29** [osTicket/osTicket#3135]
Is there a way to capture the SQL query that is ran during an advanced search in v1.9.9? Trying to create a monthly CSV report by help topic, but results don't provide enough info when I chose to export to csv.

**Comment by greezybacon** [comment]
@tjob29 you could edit `include/staff/tickets.inc.php` and around line 271, do 
```php
print "<code>$query</code><br/>\n";
```
Or just uncomment the `echo $query` line
