### ISSUE TITLE
Sub-ticketing - RFC

### ISSUE THREAD

**Issue by semoand1** [osTicket/osTicket#3136]
Hi Friends,

There is a need for sub-ticketing mechanism in osTicket in order to give fair weight of a ticket based on its load.

Example, there is a product for tracking IT tasks either incident, standard change, RFC, etc.

From my work experience, when you open a ticket to replace hard disk of a PC or Laptop then it will result in sub-tickets such as purchase order, reformatting, re-licensing some software.

Thus, the ticketing system here is not merging tickets but it will create sub-ticket of original ticket and it will add more value to KPI of IT staff giving fair report of the load of work they handle.

I would suggest sub-ticketing instead of merge ticket as it will add more values and weight measurement to those heavy loaded tickets and this of course will comply with international standards such as ITIL V3.

I wish there will be such new feature in osTicket to allow create sub-tickets in a way of reporting original ticket dashboard, sub-dashboards of a single ticket, and total tickets dashboard.

This will add more value.

Best Regards.

**Comment by ntozier** [comment]
So you want the devs to add Tasks?
(which is already in 1.10)

**Comment by semoand1** [comment]
Actually, I haven't yet tried to use v 1.10 because I am afraid to lose some modifications I made to change (Ticket) to be (Work Order) in our osTicket.
