### ISSUE TITLE
Add custom form to Advanced Search

### ISSUE THREAD

**Issue by Eryens** [osTicket/osTicket#3137]
Hello !

I must use osTicket with 2 completly different tickets types, I have 1 form of each ticket which is great.
One is the "ticket details" form and the other one is a handmade custom form.

I know I can add parameters in "Advanced Search" by adding them in the "Ticket Detail" form, but I want to be able to search for some parameters that aren't in the base "Ticket Detail".

Is it possible ? Thanks by advance.

**Comment by greezybacon** [comment]
This is possible with #2577. Might you have an opportunity to evaluate and comment on that feature?
