### ISSUE TITLE
Keep attachments when editing thread

### ISSUE THREAD

**Issue by balojs** [osTicket/osTicket#3139]
1- Created Ticket : Add attachments
2- Edit Ticket : add more info and updated
3- Result : remove all attachment from custom form.
![screenshot](https://cloud.githubusercontent.com/assets/3303352/15375028/4e71b9ea-1d0a-11e6-8ce7-e1335801fa2a.png)

Help me!!! 
thanks 

solved 907ec36  #2888

**Comment by UkaLee** [comment]
https://github.com/osTicket/osTicket/issues/2888 

known bug

**Comment by balojs** [comment]
the error could be, that the flag is initialized required field to load the custom form
![screenshot](https://cloud.githubusercontent.com/assets/3303352/15434010/318a2ad8-1e72-11e6-81b7-2e571239d866.png)

**Comment by balojs** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/3303352/15438756/ea419d50-1e8a-11e6-824a-cceb5fc18b66.png)

**Comment by balojs** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/3303352/15438760/f28214c2-1e8a-11e6-9ee1-be0c272931b7.png)

**Comment by balojs** [comment]
Please @greezybacon  👍

**Comment by balojs** [comment]
Please @greezybacon 👍

**Comment by balojs** [comment]
thread: Keep attachments when editing thread entry (907ec36)

**Comment by juraganerka** [comment]
did this issue have been fixed @balojs ?
i got this problem to?

**Comment by ntozier** [comment]
The issue opener closed the thread because it was a duplicate thread. I would recommend that you refer to the open issue thread for this topic.
