### ISSUE TITLE
 Ticket Created by email

### ISSUE THREAD

**Issue by ccontreras93** [osTicket/osTicket#3140]
Hi good afternoon , I need help to know which file is the code that performs the survey and creation of a ticket sent from an email.

Please.

OSTickets version I use is the v1.9.12

**Comment by greezybacon** [comment]
If you're piping, then `api/pipe.php`, which will start in `include/api.tickets.php`, PipeApiController. If you're fetching then it would be controlled by `include/class.cron.php`, the MailFetcher method.

**Comment by ccontreras93** [comment]
Hi good afternoon , thank you very much.
