### ISSUE TITLE
Rewrite setup/install.php to twig

### ISSUE THREAD

**Issue by verschoof** [osTicket/osTicket#3142]
Hi guys,

Would you be interested if I implement twig for the install.php?
Why? I go use osTicket, since its open source I want to do something back.

This is my first step to write osTicket to Twig Templating Engine.
I will start in `/setup/`, why? becasuse is isolated so I thought I go start there, so we can do this step by step.

What do you guys think? And I would like to know from the repo maintainers if they would appreciate it.

**Comment by verschoof** [comment]
@protich @greezybacon What do you guys think?

**Comment by greezybacon** [comment]
@verschoof I would like to see the entire project move to Twig personally. If you're up for the work, I think starting in `/setup/` is a fairly good idea. Suggest your initial pull requests against the `develop-next` branch. That's where the new crazy features go in

**Comment by philbertphotos** [comment]
How far you want to go with this ... and do you want help implementing it further in osticket...

**Comment by verschoof** [comment]
I do wanna help implement this further in osTicket. I noticed that osTicket its pretty complex code while it don't has to be.

Personally, My idea for my self was to improve the setup dir, add twig, add controllers, maybe some services. and see how it ended up. Also to see how you guys would react on it, because those are pretty big changes.

My goal is to make the code more simple so it would be more "attractive" for people to help with OsTicket.

I don't have much time, but I wanna help with the project.

I'm fan of Symfony, and I love there components. There are many components we can use, HttpFoundation, Routing, ConsoleCommands etc =)
