### ISSUE TITLE
php manage.php deploy script

### ISSUE THREAD

**Issue by verschoof** [osTicket/osTicket#3145]
Hi guys,

I see a script that copies the installation to another dir. I see a bunch (complicated) of code that copies on dir to another. But what is the idea behind this?

Because `system('cp -rf ' . $rootPattern . '/* ' . $this->destination);` works fine too :)

**Comment by greezybacon** [comment]
@verschoof yeah, that would work on *nix, but what about Windows? And what's more, the code rewrites the deployment to embed the version number so that javascript reloading can be forced after a deployment and such.
