### ISSUE TITLE
How can i call jquery ajax in osticket

### ISSUE THREAD

**Issue by euphon** [osTicket/osTicket#3148]
Hi,

I want to load person list according to the city selected. I have two  select box first one is city names. and second one is person name when select one city from city select the second select box will load person name according to the city i have selected 
filename

 ticket.open.inc.php

```
$(document).ready(function(){
$("#townCity").change(function () { 
var query   =   $("#townCity").val();
$.ajax({
    type: "GET",
    url: "ajax.php/users?q="+query,
    dataType: 'json',
    success: function (data) {

    }
});
});

```

How can i call this ajax url in  ajax.php page  `url_get('^/(?P<id>\d+)$', 'getCity'),`  i didt understand how to call this ajax i am new to osticket 
**Please let me know the flow of ajax functionality in osticket 
how to specify url in ajax function
Which files is performing action
ajax.php files**
please help me

**Comment by greezybacon** [comment]
@euphon I think your URL would look something like `ajax.php/path/to/34`, where `34` is the ID number matched in your ajax.php page.
