### ISSUE TITLE
'OrmException' with message 'Model `TicketCData` does not have a relation called `priority`'

### ISSUE THREAD

**Issue by jakester2** [osTicket/osTicket#3149]
My current version is "1.8-git (4456677e)", however I was able to reproduce the error on the latest develop-next snapshot as of 5/25/2016.

### The problem:
When I press the Priority button in the ticket queue to try and sort by priority, I get the following error.

Today I downloaded the most recent snapshot of develop-next and I had the same problem.

Does anyone have a fix for this? Is anyone else having this issue?

![capture](https://cloud.githubusercontent.com/assets/195975/15543861/6576a0ce-224b-11e6-907e-56f8f17898ab.PNG)

### The error:
`Fatal error: Uncaught exception 'OrmException' with message 'Model TicketCData does not have a relation called priority' in /var/www/html/osticket/include/class.orm.php:2121 Stack trace: #0 /var/www/html/osticket/include/class.orm.php(2133): SqlCompiler->{closure}('priority', 'TicketCData') #1 /var/www/html/osticket/include/class.orm.php(2641): SqlCompiler->getField('cdata__priority...', 'TicketModel') #2 /var/www/html/osticket/include/class.orm.php(1375): MySqlCompiler->compileSelect(Object(QuerySet)) #3 /var/www/html/osticket/include/class.orm.php(1191): QuerySet->getQuery(Array) #4 /var/www/html/osticket/include/class.orm.php(1407) : eval()'d code(12): QuerySet->toSql(Object(MySqlCompiler), 'TicketModel') #5 /var/www/html/osticket/include/class.orm.php(2520): QueryView000000004e84818100007f980e838be0::getSqlAddParams(Object(MySqlCompiler)) #6 /var/www/html/osticket/include/class.orm.php(2209): MySqlCompiler->compileJoin('QueryView000000...', 'QueryView000000...', 'A2', Array, false) #7 /var/www/html/osticket/includ in /var/www/html/osticket/include/class.orm.php on line 2121`

**Comment by greezybacon** [comment]
@jakester2 could you try the patch in #3242 to see if it addresses the issue?
