### ISSUE TITLE
osTicket Core, v1.9.12 ticket deleting problem

### ISSUE THREAD

**Issue by sheshman** [osTicket/osTicket#3150]
Hi All,

When i want to delete a ticket from dashboard or edit mode pop-up windows appears as blank;
![osticket_error](https://cloud.githubusercontent.com/assets/11405304/15571798/965687d6-2345-11e6-94e6-5ac01eea628b.png)

No error messages no warning, is there any solution for it ? Thanks in advance.

**Comment by ntozier** [comment]
Ah the dreaded white bar.
This is usually an AJAX issue.  Check your webserver error/access logs to see if an error is being logged.  Also what webserver software are you running?

**Comment by sheshman** [comment]
it's working on hosting company's server directly, it's a linux server most probably apache. I created a ticket to get their support, i've checked logs folder for any error log but it's empty.

**Comment by greezybacon** [comment]
This is generally associated with nginx. Or Apache is not configured to pass the path_info to PHP scripts.
