### ISSUE TITLE
PHP global question

### ISSUE THREAD

**Issue by meatballcoder** [osTicket/osTicket#3151]
I'm interested in the design of osTicket.  Is there a reason why global is used instead of the superglobal $GLOBALS?

//current usage
global $ost, $cfg, $nav;

instead of using this,

$GLOBALS['ost]

Not questioning if its good or bad.  I'm really interested why one is chosen over the other for learning.

Thanks.

**Comment by voku** [comment]
I prefer $GLOBALS, because you see what you get. ;)

**Comment by meatballcoder** [comment]
Until it breaks or you want to add things.
