### ISSUE TITLE
Staff Dashboard Statistics

### ISSUE THREAD

**Issue by reymund27** [osTicket/osTicket#3154]
Hi,

I am trying to create a user for a senior member of staff who manages all the departments

However, although this user has access to all departments, the user cannot see stats. I have tried giving full admin permissions but no luck. It works fine for my user and another admin.

There is no text showing in statistics under the tabs for Department / topics / Agents but the graph above works fine.

**Comment by ntozier** [comment]
This seems like a question for the forums.
Go to: Admin panel -> Agents -> Groups -> the users group. 
Ensure that "Can View Agent Stats" is checked.

The staff should not be an admin as that is an osTicket admin to change things in osTicket.

**Comment by MelArlo** [comment]
I am seeing this same issue. I have an agent that is not an admin. Their group has the "Can View Agent Stats" box checked. They can see the graph but no individual statistics. Is this a bug or is there a workaround?

**Comment by ntozier** [comment]
This still seems like a question for the forums.
What version of osTicket are you two running?
Environment details?

**Comment by MelArlo** [comment]
Hello, I actually found this issue on the forums which lead me here (http://osticket.com/forum/discussion/87811/staff-dashboard-statistics). As far as version we are running v1.9.12 in a CentOS environment using PHP 5.4.16. Attached is an image of our group settings where we are running in to the issue.
![group](https://cloud.githubusercontent.com/assets/3092652/17182157/31e2d754-53e8-11e6-9e33-07edf211f2a9.png)

**Comment by arkhan** [comment]
I have the same issue with 1.10 version
