### ISSUE TITLE
LDAP Plugin Fatal Error with Develop-tip

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket#3158]
Fatal error: Access level to Net_LDAP2_RootDSE::__construct() must be public (as in class PEAR) in phar://C:/inetpub/osTicket/DPR/include/plugins/auth-ldap.phar/include/Net/LDAP2/RootDSE.php on line 238

**Comment by jjjeroenski** [comment]
see this topic: https://github.com/osTicket/osTicket-plugins/issues/105
