### ISSUE TITLE
Integrate the buttons , log in using Google and Facebook OsTicket 1.10 RC2 (Integrar os botões, fazer login usando Google e Facebook OsTicket 1.10 RC2)

### ISSUE THREAD

**Issue by suportgc** [osTicket/osTicket#3160]
Hello everyone.
I would like to know how to integrate the buttons , log in using Google and Facebook in my system.
If possible , I would like a step by step because I am a layman and not know this type of configuration .
Grateful and I look back .

Below , data My osTicket .

![ost](https://cloud.githubusercontent.com/assets/19677143/15694976/04b8428c-2779-11e6-998e-787c9c242c28.png)

Olá a todos.
Gostaria de saber como faço para integrar os botões, fazer login usando Google e Facebook em meu sistema.
Se possivel, gostaria de um passo a passo, pois sou leigo e não conheço este tipo de configuração.
Grato e aguardo retorno.

Segue abaixo, dados de meu OsTicket.

**Comment by novat0** [comment]
i like this feature.. due ist suppost to provide easy to report issues to clients.. and no so hard to report interfaces.. 

just a "point and click" button and here there are all the sended tickets of user!

**Comment by greezybacon** [comment]
This is available in the https://github.com/osTicket/core-plugins repo. It's in the `auth-oauth` plugin folder
