### ISSUE TITLE
E- mail automatic reply when closing a ticket OsTicket 1.10 RC2 (E- mail automatic reply when closing a ticket OsTicket 1.10 RC2)

### ISSUE THREAD

**Issue by suportgc** [osTicket/osTicket#3161]
Hello everyone.
I would like to know how to send an email automatically when solving a ticket ?
Grateful and I look back .

Below , data My osTicket .

![ost](https://cloud.githubusercontent.com/assets/19677143/15695034/8228c3f4-2779-11e6-97db-cbf6102109b3.png)

Olá a todos.
Gostaria de saber como faço para enviar um e-mail automaticamente quando solucionar um ticket ?
Segue abaixo, dados de meu OsTicket.

**Comment by rbukovansky** [comment]
Normally, when you're adding reply to ticket, you can select the status of ticket below your answer. When you try to just close the ticket using that combobox, it will ask you for answer, which is mandatory. And as all replies are usually sent to customer, just add something like "I'm closing this ticket" to your answer.

**Comment by suportgc** [comment]
Hello "rbukovansky", Thanks for the answer.

I was thinking of an automatic process as when a ticket is opened, however, I believe that this so informed , already help a lot.
Thank you very much.
