### ISSUE TITLE
 Chat online at OsTicket 1.10 RC2 (Chat Online no OsTicket 1.10 RC2)

### ISSUE THREAD

**Issue by suportgc** [osTicket/osTicket#3162]
Hello everyone.
Sorry about my English.

I wonder if there is any online chat system that can integrate into osTicket ?

If so , how can I join ?
I am a layman and if possible , could drill me step by step ?

Would I like a system similar to that currently used in Freshdesk , with an option to open a new ticket with the chat or attach to an existing ticket .
Grateful and I look back .

The following information from my osTicket .

![ost](https://cloud.githubusercontent.com/assets/19677143/15695389/fcf7a3ea-277c-11e6-869b-b31979765db1.png)

Olá a todos.
Gostaria de saber se existe algum sistema de chat online que posso integrar ao OsTicket ?

Se sim, como posso integrar ?
Sou leigo e se possivel, poderiam me detalhar passo a passo ?

Gostaria de um sistema semelhante ao usado atualmente no Freshdesk, com opção de abrir um novo ticket com o chat ou anexar a um ticket existente.
Grato e aguardo retorno.

Segue informações do meu OsTicket.

**Comment by greezybacon** [comment]
@suportgc I think your many questions would be better served in the [osticket forum](http://osticket.com/forums).

Currently, there is no support for integrated chat inside osTicket.

**Comment by suportgc** [comment]
Hello .
Thanks for the tip
