### ISSUE TITLE
System will not email user notifications of new ticket, or of Agent replies in tickets

### ISSUE THREAD

**Issue by JasonLabs** [osTicket/osTicket#3163]
I apologize if this is not the place for this... 
I have been working through the support forum on this issue here, and we haven't been able to get to the bottom of this: 
http://osticket.com/forum/discussion/88037/system-will-not-email-user-notifications-of-new-ticket-or-of-agent-replies-in-tickets

I am hosting with HostGator
osTicket Version	v1.9.12 (19292ad) 
Web Server Software	Apache
MySQL Version	5.5.42
PHP Version	5.5.30

My Issues:
1. When a new ticket is created, the user is not notified by email that a ticket is created if the email is an external email address.. for example a gmail account.  
2. When an Agent replies to a ticket, the user is not notified by email that a response has been given to the ticket

NOTE: 
-All other notifications to the Agent (ticket creation, etc) are emailed, so internal emails on the domain are working. 
-Through email diagnostics, the system is sending email perfectly to any email address, so it seems emailing to external addresses work via Admin Panel -> Emails -> Diagnostic

**Comment by ntozier** [comment]
Are you using SMTP or PHPMail to send?
What server are you using if SMTP?
Did you check your email server logs to find out why the emails are not being sent like I asked?

**Comment by JasonLabs** [comment]
I am using SMTP to send mail.

I am using the same server that osTicket is installed on. (Please let me know if I misunderstood) 

The server logs do not indicate any errors or bounces when sending mail. The server logs would seem to indicate that Agent replies on tickets and ticket creations are not attempting to send. (but this could be because I don't know how to read the server log properly)

**Comment by JasonLabs** [comment]
At this point I don't know what else to try. Is there another angle I can take with my testing? 
Do you know which script is supposed to trigger the emails when a new ticket is made, or when an agent replies to a ticket?

**Comment by greezybacon** [comment]
Can you try using the php mail function, perhaps? It would seem if the diagnostic tool works, then the other emails must be dropped for some other reason by the mail transfer agent (ie. not osTicket).

**Comment by JasonLabs** [comment]
Thank you so much for your response! 

On osTicket I have tried setting the outgoing to be through the php mail, and I still do not get any response from an agent reply to a ticket to an external email. 

On the same server I tried this simple php mail script, and it worked just fine: 
(Please let me know if I should be testing some other way to see if the php mail function is working on the server.)

`<?php
//if "email" variable is filled out, send email
  if (isset($_REQUEST['email']))  {
  
  //Email information
  $admin_email = "myemail@myemaildomain.com";
  $email = $_REQUEST['email'];
  $subject = $_REQUEST['subject'];
  $comment = $_REQUEST['comment'];
  
  //send email
  mail($admin_email, "$subject", $comment, "From:" . $email);
  
  //Email response
  echo "Thank you for contacting us!";
  }
  
  //if "email" variable is not filled out, display the form
  else  {
?>

 <form method="post">
  Email: <input name="email" type="text" /><br />
  Subject: <input name="subject" type="text" /><br />
  Message:<br />
  <textarea name="comment" rows="15" cols="40"></textarea><br />
  <input type="submit" value="Submit" />
  </form>
  
<?php
  }
?>`

**Comment by greezybacon** [comment]
@JasonLabs yes, you mentioned that the diagnostic in osTicket worked. That would mean that the SMTP system is working properly. My guess is that it is a routing issue. There's some rule or setup somewhere which is dropping or refusing the mails. I've seen before where some anti-spam systems classify our mails as spam based on the subject lines. Perhaps you could change the subject lines, or add the ticket number, or add some content to the template bodies to make them look less like spam?

**Comment by JasonLabs** [comment]
@greezybacon I have changed the templates to have my own subject line as well as an internal message that is my own creation, and I still have the same result:

The ticket will reply to an internal email address (an email on the same domain as osTicket) 
The ticket will not reply to external email address (such as gmail, etc...)

I am on HostGator, and I have verified the Apache SpamAssasin is deactivated, so it should let all mails through (outgoing and incoming). 

Again, thank you so much for your time!

**Comment by ntozier** [comment]
Sounds to me like you should be talking to HostGator and asking them to look at the mail logs to see why the email is not leaving the server to the intended destination.

**Comment by JasonLabs** [comment]
I did receive the logs from them, and there is no indication of blocked emails or errors for sent emails.

The following is just a portion of the mail log: 

```
Mail Log Parsed from May 25, 2016 14:18:50 to May 27, 2016 14:18:50

User sent approximately 1,763 messages to 14 unique recipients.
There were 0 bounces on 0 unique addresses, 0 percent of the emails sent.

Hourly mail volume for the entire account:

2016-05-25
------------------------------
Hour    Volume   Bounces     %
------------------------------
  15         9         0     0
  16         1         0     0
  18         1         0     0
  19         2         0     0
  20         5         0     0

2016-05-26
------------------------------
Hour    Volume   Bounces     %
------------------------------
  10        37         0     0
  11        71         0     0
  12        65         0     0
  13        73         0     0
  14        62         0     0
  15        74         0     0
  16        61         0     0
  17        60         0     0
  18        60         0     0
  19        60         0     0
  20        60         0     0
  21        60         0     0
  22        60         0     0
  23        60         0     0

2016-05-27
------------------------------
Hour    Volume   Bounces     %
------------------------------
   0        60         0     0
   1        60         0     0
   2        60         0     0
   3        60         0     0
   4        60         0     0
   5        60         0     0
   6        60         0     0
   7        61         0     0
   8        61         0     0
   9        60         0     0
  10        76         0     0
  11        60         0     0
  12        60         0     0
  13        65         0     0
  14        19         0     0
```

**Comment by JasonLabs** [comment]
Hey guys, just wanted to ask if there are any other ideas for me to test or try. I would still love to get this to work. 
Thanks!
