### ISSUE TITLE
Wider SCP

### ISSUE THREAD

**Issue by rbukovansky** [osTicket/osTicket#3166]
If anyone interested I have created ugly hack (pull request #3165) to current develop branch, that makes SCP take 90% of screen estate (it's not Bootstrap UI, just plain edit of files to make them work this way).

Enjoy.

**Comment by marcinkorzycki** [comment]
It would be wonderful if osTicket will be wider. Maybe merge it to 1.11?

**Comment by JediKev** [comment]
@marcinkorzycki

A full UI/UX overhaul is due for the `2.0.x` series. Please stay tuned.

Cheers.

**Comment by rbukovansky** [comment]
@JediKev Can we see it?

**Comment by JediKev** [comment]
@rbukovansky 

`2.0.x` development has not started yet. Development of this series will start after `1.11.x` or `1.12.x` (no promises).

Cheers.

**Comment by rbukovansky** [comment]
@JediKev I see... OK. Thanks.
