### ISSUE TITLE
1.9.7 - unregistered client emails rejected silently [Feature Request?]

### ISSUE THREAD

**Issue by ntozier** [osTicket/osTicket#3171]
I noticed this in 1.9.7 and haven't tested in newer versions if someone can test this on 1.9.12 and 1.10rc2 that would be awesome. [ Note: I am running the Authentication::LDAP and AD plugin.]

If you have Admin panel -> Settings -> Access:
Registration Requires: checked
Registration Method: Public

And you attempt to open a ticket by sending an email that is not associated with an account, it fails [silently] and does not generate any kind of message to the person trying to open the ticket saying "Hey you need to register for an account before you can open a ticket!"

There are two ways to catch these failed attempts.  1. by changing Admin panel -> Settings -> System -> Default Log Level to DEBUG and check System Log, or by running a SQL query to check for it.

SELECT created,log FROM ost_syslog WHERE title ='Ticket Denied';

Proposed solution(s): 
**1**: Add a template for rejection notices, and a corresponding Autoresponder setting for enabling/disabling the sending said template. 
**2**: If the Authentication:: LDAP and AD plugin is installed utilize the search user to see if the email is valid and allow the ticket to be opened, and a corresponding plugin setting for enabling/disabling the option.

**Comment by intrixius** [comment]
+1 !  I just found out on our system that we missed a lot of emails due to this problem/shortcoming. It should indeed send an email to the sender to let him/her know they first have to register...

**Comment by greezybacon** [comment]
I agree that it would be nice to send an email back. However, osTicket currently does not correspond via email except when the ticket thread is continued. So we currently don't have a way to respond to the email unless we create a ticket, which we aren't since it's being denied.

I like the idea of the LDAP integration, though.

**Comment by sriddick** [comment]
Has there been any update or progress on this feature request? Or is is possibly now a feature in the newer versions?

**Comment by ntozier** [comment]
Didn't I just tell you in another issue report that this is not a feature at this time?
Yup I did.  In the one linked above your response.

**Comment by sriddick** [comment]
Thanks @ntozier 
Your last comment was not really very productive. Whilst I took note of your reply that "this was not currently a feature" My question was different. The case was opened on the 3rd of June as per your comment, so I was merely enquiring if there has been any progress on adding the feature considering that we are almost at the end of August. No need to be sarcastic.

**Comment by ntozier** [comment]
Written text does not convey tone.  If it had then you would know that I was not being sarcastic I was being annoyed that you would ask the same question that I has just answered in another thread.  IT should be obvious there is no update as it would have been here.

**Comment by ntozier** [comment]
@JediKev @protich 
Can this get an updated dev response please?

**Comment by sriddick** [comment]
Agreed

**Comment by starhound** [comment]
Love when communities just close issues without any solution or information on if the feature is going to exist or not! 

We're trying to get this exact functionality in v1.15.2.

**Comment by ntozier** [comment]
@starhound 
There is a free 3rd party plugin called osTiceket notifyReject that you can get from 
http://software-mods.com/notifyReject.html
I have not used it with 1.15.2 personally, but it might help you.

UPDATE
Note: the plugin mentioned above is not an Official osTicket plugin, it is a Community plugin.  Community plugins are made by the community not the Developers.  They are not supported or recommended by the Developers and are not affiliated with the Development Team.

**Comment by starhound** [comment]
Thanks pal!
