### ISSUE TITLE
Agent is Logged off in 1.10 RC2 when ticket are Modifed

### ISSUE THREAD

**Issue by philbertphotos** [osTicket/osTicket#3173]
Agent gets logged of after closing any ticket. I am using the multiLDAP plugin but this was working fine before.

**Comment by philbertphotos** [comment]
Ok updated the issue .,... if the ticket is modified meaning "Closed, Open, Resolved" it logs the agent off. I also turned off all plugins and logged in locally an the same issue persists.

**Comment by ntozier** [comment]
By MultiLDAP do you mean Authentication::LDAP and AD?  Or do you have a custom plugin that you are using?

If custom can you disable it and see if the problem persists?  If so then you know if it is your plugin or not.

**Comment by philbertphotos** [comment]
I turned off all plugins it still does it ... .both 1.10 and develop.

**Comment by philbertphotos** [comment]
Fixed ... once upgraded from PHP 5.5 to 5.6

**Comment by greezybacon** [comment]
@philbertphotos I think this is a timezone issue for PHP 5.5. Could you post your configuration from the system information page?

**Comment by philbertphotos** [comment]
Too late i already upgraded to 5.6 and no longer have the issue ... You still want the info?

**Comment by greezybacon** [comment]
@philbertphotos v1.10 only requires PHP 5.4, so the info might help to solve the issues for PHP versions previous to 5.4

**Comment by philbertphotos** [comment]
Server Information
osTicket Version 	v1.10-rc.3 (907ec36) — Up to date
Web Server Software 	Apache
MySQL Version 	5.5.49
PHP Version 	5.6.22-1+donate.sury.org~trusty+1
