### ISSUE TITLE
Error:  Can not authenticate to IMAP server

### ISSUE THREAD

**Issue by jasonvega** [osTicket/osTicket#3174]
Receiving this error from the system.  User/pass and settings are all verified and correct.

I'm guessing this has to do with Google's updated authentication process.

**Comment by rbukovansky** [comment]
I can probably help. What kind of error are you getting from Google?

**Comment by ntozier** [comment]
Have you granted the account permission to connect via IMAP/POP in the account settings for the gmail account?
