### ISSUE TITLE
error: error get info from ticket when delete custom forms "getDynamicFields() on a non-object "

### ISSUE THREAD

**Issue by mckaygerhard** [osTicket/osTicket#3178]
1) made custom forms or fiels (can be in dinamic forms or in users organizations)
2) made some tickets using web or angent interface with those custom forms enabled
3) delete all custom forms
4) try to edit the issue created recently that used the custom forms

got that error:

`Fatal error: Call to a member function getDynamicFields() on a non-object in /var/www/osticket/include/class.dynamic_forms.php on line 877`

this due the custom fields in the fomrs deleted in the issues triying to edit are not existing, obviously due are now deleted in step 3, so cannot edit the ticket

happened in 1.9.11 and 1.10rc, in 1.10 only some times.

in any time, i not using in production 1.10 ! so due theres is not 1.10 oficial firts production release

**Comment by mckaygerhard** [comment]
also seems was same: #1485 of course that was solved due now reference organization field are fixed, but in case of custom form, reference of that custom fileds in dinamic custom forms are delted by user

**Comment by greezybacon** [comment]
@mckaygerhard could you provide a full backtrace? Line 877, plus or minus 20 lines, does not contail a call to 'getDynamicFields'. I see where the issue _could_ be triggered on line 927 (v1.9.11, 925 in v1.9.14).

I think this issue should be taken care of for the v1.10 branch. I don't where the call to `getDynamicFields` could crash on the `develop` branch.

Could you try this patch?
```patch
diff --git a/include/class.dynamic_forms.php b/include/class.dynamic_forms.php
index 8408017..dac8b1e 100644
--- a/include/class.dynamic_forms.php
+++ b/include/class.dynamic_forms.php
@@ -918,11 +918,16 @@ class DynamicFormEntry extends VerySimpleModel {
      * entry.
      */
     function addMissingFields() {
+        if (!($form = $this->getForm())
+            // The form for this entry was removed. No missing fields to
+            // consider
+            return;
+
         // Track deletions
         foreach ($this->getAnswers() as $answer)
             $answer->deleted = true;

-        foreach ($this->getForm()->getDynamicFields() as $field) {
+        foreach ($form->getDynamicFields() as $field) {
             $found = false;
             foreach ($this->getAnswers() as $answer) {
                 if ($answer->get('field_id') == $field->get('id')) {
```

**Comment by mckaygerhard** [comment]
the 1.9.14 get solved this issue or i must pached by myselft! (i will graduate in php-pached-master at this way)

take in consideration that this only happened in tickets that have some fields or users not already present in sistem, by ej. delete a custom filed or whole form associated

**Comment by mckaygerhard** [comment]
u in second line got dinamic fields from so this must solved, so i'll closed after tested today! thanks for the patch

**Comment by mckaygerhard** [comment]
working! thanks oh men relly relly thanks, please commit that change to the TODAY STABLE VERSION ABLE TO USE IN PRODUCTION due v1.10 still are not stable!

i'll closed when commit are confirmed!

**Comment by mckaygerhard** [comment]
working! thanks oh men relly relly thanks, please commit that change to the TODAY STABLE VERSION ABLE TO USE IN PRODUCTION due v1.10 still are not stable!

i'll closed when commit are confirmed!

**Comment by greezybacon** [comment]
#3222. Cheers
