### ISSUE TITLE
Error when deploying new version - a1a5b02

### ISSUE THREAD

**Issue by Taps7734** [osTicket/osTicket#3182]
When attempting to run 
`php manage.php deploy -v /var/www/stage/2016-06-07`

from /var/www/git/2016-06-07,  I receive the following error

```
PHP Fatal error:  Class 'Translation' not found in /var/www/git/2016-06-07/bootstrap.php on line 296

Fatal error: Class 'Translation' not found in /var/www/git/2016-06-07/bootstrap.php on line 296
```

**Comment by greezybacon** [comment]
This seems to have been fixed in the official v1.10-rc.3 release. Can you run a pull and give it another go?
