### ISSUE TITLE
Request: include a backlink to the ticket if a task is created under a ticket

### ISSUE THREAD

**Issue by haraldhh** [osTicket/osTicket#3190]
If an agent gets assigned a task that is part of a ticket, it would be nice if the link would be to the ticket (and the task-tab) and not the task. The ticket usually contains more background information about the issue to be resolved, and can be crucial for the agent to be able to complete the task.

There is no information in a task that it belongs to a ticket.

**Comment by ntozier** [comment]
I believe that this is on purpose.
The onus is on the task opener to provide the necessary details to complete the task, because there is no guarantee that the person completing the task even has access to the ticket system, let alone the ticket in question.

**Comment by haraldhh** [comment]
I see. There are many use-scenarios that's for shure. If a task is assigned to an existing agent, the task could have a link to the ticket instead.

**Comment by greezybacon** [comment]
@haraldhh I gave it a shot in #3241. I can get a link to the tasks tab in the ticket page. Because of the ajax usage to pull up the individual task, I can't get a link to the actual task in the tasks tab inside the ticket view.
