### ISSUE TITLE
TicketFilter + AutoResponse not working

### ISSUE THREAD

**Issue by sharmay** [osTicket/osTicket#3192]
osTicket (v1.10-rc.2-307-gbf2395b)

Two Departments DepA, DepB
Default system wide department is DepA
I created Ticket Filter if ticket sender email matches depb assign this ticket to DepB
I am member of DepA and Extended member of DepB.
When someone from DepB creates a ticket there is no AutoResponse coming to me that new ticket is created, how can I achieve this ?

**Comment by greezybacon** [comment]
@sharmay could you send some screenshots of your configurations? Specifically the ticket filter(s) being used?

**Comment by sharmay** [comment]
![image](https://cloud.githubusercontent.com/assets/6456966/16815532/0355a852-48ef-11e6-8b2d-71a9144e17e1.png)

I had to add Agent assignment to get notification, what I want it all members of Infrastructure department get notification.

**Comment by sharmay** [comment]
Any suggestion ?
