### ISSUE TITLE
External task Cron (OsTicket 1.10 RC2)

### ISSUE THREAD

**Issue by suportgc** [osTicket/osTicket#3198]
Hello good afternoon.
I wonder if it is possible to configure an external cron job to search emails.

eg have an external server and want to configure it to run cron on
meudominio.com/support/api/cron.php

**Comment by robintoy** [comment]
since version 1.7 there is a cron job for collecting emails you can start which is done via the rcron.php file from the scripts folder of your release.

just set a cron job to use wget to the URL like "meudominio.com/support/scripts/rcron.php"

Hopefully this helps?

**Comment by suportgc** [comment]
Hello robintoy .
Thanks for the answer .

Sorry about my English.

I don't know this type of configuration .

It would be possible to explain to me how can I do this ?

I saw that in rcron.php file is requested my URL and API.
That's easy.

It is that my hosting SRV does not allow me to use cron with less than 15 minutes .

This rcron.php task is executed in how long?

I can set for a minute?

How do I set this wget ?

Thank you and again forgive me for the little knowledge and English .

**Comment by suportgc** [comment]
Hello robintoy .
Just to inform .
I made the setting in EasyCron and it worked perfectly.

However , in my Debiam server does not work.

I used this command.

* * * * * wget -q -O /dev/null http://meusite/rcron.php

Where is wrong?

Must perform this task every 1 minute

Thank you

**Comment by robintoy** [comment]
Hi @suportgc 
Glad I could help.
If you do need a little more information please just ask.

**Comment by robintoy** [comment]
The command on our cron job used is: -
wget -q http://osTicketPath/scripts/rcron.php

**Comment by suportgc** [comment]
Hello @robintoy 
Thank you for your help.
Everything working perfectly.
