### ISSUE TITLE
Departament email settings 

### ISSUE THREAD

**Issue by rafor1982** [osTicket/osTicket#3199]
Hi,
I've got one question about email settings.
version: v1.10-rc.2
I want to disable assignment email alerts but in only at one department.
My configuration is:
admin panel --> Tickets --> alerts and notices --> Ticket Assignment Alert: mark Assigned Agent / Team
If I create new ticket and assign it to agent (agent will receive email) - that's good.
I want that agents who are in department "EXAMPLE" do not receive that assignment alert.
So I go to:
admin panel --> agents --> departments --> "EXAMPLE" --> Alerts and Notices--> Recipients--> and set No one (dosable Alerts and Notices)

but it does not work. If I create ticket and assign it to "EXAMPLE" department and assign to agent001,
agent001 still get email information about assigment.

**Comment by greezybacon** [comment]
> admin panel --> agents --> departments --> "EXAMPLE" --> Alerts and Notices--> Recipients

Where is that again? I can't find that page
