### ISSUE TITLE
1.9.x enachement in operator view

### ISSUE THREAD

**Issue by cervedgroup** [osTicket/osTicket#3201]
Is possibile to limit the staff list view at only operators that belong to departement of the ticket ?

Example : 100 operators in 15 department, if a operator of department 1 need to trasfer the ticket to another operator of the same department, all the operators are shown in the operator selection, and this is annoying.
thank you

**Comment by ntozier** [comment]
I agree that the interface needs to scale better for larger implementations.
Maybe a type ahead box with a display of the first few (3) alpha names, and if someone types in something the matches change the display.

**Comment by cervedgroup** [comment]
good idea, or a simple flag "show only my group/department" in preferences or from trasfer ticket interface

**Comment by ntozier** [comment]
My only concerns with that is if someone wants to transfer outside of their department/team, or if one department has 100  agents and another has only 5.  The department with the 100 agents would still have a scaling issue.  I think that the type ahead would alleviate that congestion.

Perhaps there could also be a toggle on the Agents account for what to display.

**Comment by cervedgroup** [comment]
any news about that ? in latest release (1.10.1) only the staff of the department is shown, no way to chosse to view all the operators ?

**Comment by ntozier** [comment]
Q: any news about that ?
A: There has been no update to this thread.  So I would say no.

Q: in latest release (1.10.1) only the staff of the department is shown, no way to chosse to view all the operators ?
A: This is not accurate according to my installation and I have no idea why you would think that...

**Comment by ntozier** [comment]
To be clear this is a setting that you or another admin set.

Admin panel -> Agents -> Departments -> DEPARTMENT A
uncheck Ticket Assignment: [ ] Restrict ticket assignment to department members

**Comment by cervedgroup** [comment]
is already unchecked in all our departments ...

**Comment by ntozier** [comment]
Then I simply cannot replicate the behavior that you are reporting.
