### ISSUE TITLE
osTicket 1.10-rc2, multiple issues (sorting, dropdown boxes, target=_blank

### ISSUE THREAD

**Issue by jjjj12212** [osTicket/osTicket#3202]
Hi Developers,

We have encountered a few issues with 1.10-rc2 that we would like suggestions on how to fix (if it's simple) and let you be aware of the issues.
1. ticket sorting - the sorting is messed up, we have 3 pages of ticket # and on each page its sorted assended into different segments instead of as a whole.

for example page 1:
     sort: Ticket Number DESC

72779
72747
72732
...
...

on Page 2:
73559
73552
73546
...
...

on Page 3:
73712
73709
73708

On each page, it's sorted but I expected the top most number on page 1 instead of page 3.
1. On firefox, the dropdown boxes are cutting off the texts in the box. We mostly use firefox.
2. When we open attachments, we wanted it to open a separate tab instead of replacing the current screen. I noticed in the code it's already set target="_blank" however it doesn't work and I find my small customization which opens a different website also set with target="_blank" no longer works (worked with version 1.9)

Please note that we made this version in production since we find this version much faster to load compared to 1.9 and we love the edit thread feature.

Please help,

jjjj12212

**Comment by ntozier** [comment]
You are running a release candidate with numerous issues.  Since 1.10rc3 was released a few days ago, please update and re-test to see if you are still having issues.

**Comment by jjjj12212** [comment]
I fixed the problem today, had to move all the sorting options (line 214 - 307) above the pagination code (pasted it on line 188) all on the tickets.inc.php file. I'm shocked that no one was able to assist me with this and surprised that I was able to pull this off.

Thanks everyone for your help :D

**Comment by greezybacon** [comment]
I ran this on rc3 and do not see the issue. Does anyone know if it is specific to rc2?

**Comment by SudNdarK** [comment]
Has anyone found a solution to the target="_blank" not working?
