### ISSUE TITLE
No new message notifications when not signed in

### ISSUE THREAD

**Issue by dcmcand** [osTicket/osTicket#3204]
I get new ticket notifications, but no notification if someone responds to an open ticket or reopens a closed ticket.  When I sign in, I get all the notifications at once.  Is there a way to set it to send notifications when no one is signed in?

**Comment by ntozier** [comment]
Are you running cron?

**Comment by dcmcand** [comment]
Yes, I have */5 * * * * nobody /usr/bin/php/ /path/to/osticket/api/cron.php in my crontab

**Comment by dcmcand** [comment]
Solved the issue by creating a crontab for user nobody directly.  it works now.  Not sure why it wasn't working under root crontab.
