### ISSUE TITLE
1.9.14 Form Field Visibility

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket#3205]
Option `For EndUser Only` is making it required. Should there be an option like the rest for Optional or required. As an Agent this is nice for something the Enduser needs to provide but the agent does not need to even see when creating a ticket.

**Comment by greezybacon** [comment]
We added more granular control to the visibility options in v1.10 to address this issue. The thought for "For EndUser Only" was to implement something a like a field for CAPTCHA, which should not be shown to the agents and is required for end users.
