### ISSUE TITLE
tz_offset variable missing on some places

### ISSUE THREAD

**Issue by dmnc-net** [osTicket/osTicket#3206]
Hi, I found a issue with wrong time on some places:
- User Profile (/osticket/profile.php) [WRONG]
- System Settings (/osticket/scp/settings.php) [WRONG]
- Staff Profile (/osticket/scp/profile.php) all staff profiles [OK]
- ticket time [OK]

Problem is in variables which are not set (so returning null):
/osticket/include/staff/settings-system.inc.php - `$config['tz_offset']`
/osticket/include/client/profile.inc.php - `$info['tz_offset']`

But `default_timezone_id` and `timezone_id` in second case has been loaded from the DB correctly, so I may not be a problem to set the `tz_offset`.

I'm using CET/CEST, Central European (Summer) Time, GMT+1
`$gmtime = Misc::gmtime()` ... function returns `time()-date('Z')`  ... which converts my local time into the GMT (because od 'Z') so I need to add back the TZ offset and that offset has to be stored in the `tz_offset` within `$config` or `$info`.

osTicket version: found on v1.8.2-dpr-11-gc754f04, remains on v1.9.14 (8b927a0)
additional info: http://osticket.com/forum/discussion/77001/problem-with-local-time

**Comment by ntozier** [comment]
Side note: Admin panel -> System does not, has never, and is not intended to show the correct time.  It is for date time formatting purposes only.

**Comment by dmnc-net** [comment]
But it's confusing. Even more with label "Actual time". When the code is actually expecting and then working with `$config['tz_offset']` why not to set this variable? Why not to act in same style in all 3 places where the time is shown (admin X, staff ✓, client X)? And how to handle all customer's questions about wrong time? In case if they will enter their profile page.

**Comment by dmnc-net** [comment]
Closed with the reference to the younger duplicate of this issue? With no summary? Please will be this issue fixed or not?

**Comment by ntozier** [comment]
This issue report is not closed.  The one (3214) that referenced this issue is.

**Comment by dmnc-net** [comment]
@ntozier I see, sorry. Anyway version 1.10 solved this ussue by a new design, I think we can close it.
