### ISSUE TITLE
osTicket v1.10-rc3 -- Posting reply or internal note logs user out

### ISSUE THREAD

**Issue by robintoy** [osTicket/osTicket#3209]
if you reply to a ticket it saves the reply and logs the user out, but creating new tickets works with no issues.

**Comment by philbertphotos** [comment]
I get this to ... I have not been able to find out why and makes RC3 unusable to me.

**Comment by trueserve** [comment]
I, on the other hand, do not experience this issue.

Does your webserver error log have any note?

**Comment by robintoy** [comment]
Being honest it killed us so badly we had to roll back to RC2 as we actually use this as a live system.

I know we should not but it is so much better than v1.9.x

**Comment by ntozier** [comment]
I also do not experience this.  Can the folks who do maybe post some information regarding their server environment?  (webserver and ver, os and ver, php ver)

**Comment by philbertphotos** [comment]
Server Information
osTicket Version 	v1.10-rc.3 (907ec36) — Up to date
Web Server Software 	Apache
MySQL Version 	5.5.47
PHP Version 	5.5.9-1ubuntu4.14

**Comment by philbertphotos** [comment]
hmmm wonder if its a PHP thing and ... There is no log or anything I can find that causes it.

**Comment by philbertphotos** [comment]
This was fixed as soon as I upgraded to PHP 5.6 so its a bug a confirmed bug in Osticket and php 5.5 and maybe lower

**Comment by robintoy** [comment]
Hi @philbertphotos 
we use 5.6 and still have the issue.

**Comment by MichaelCowe** [comment]
I had this problem on Centos 7 PHP 5.4, upgraded using below instructions and its working a treat

1: yum install epel*
2: yum update / yum upgrade
3: `CentOS and Red Hat Enterprise Linux 6.x
wget http://rpms.famillecollet.com/enterprise/remi-release-6.rpm 
sudo rpm -Uvh remi-release-6*.rpm

CentOS and Red Hat Enterprise Linux 7.x
wget http://rpms.famillecollet.com/enterprise/remi-release-7.rpm 
sudo rpm -Uvh remi-release-7*.rpm`
4: yum update / yum upgrade
5: yum --enablerepo=remi,remi-php56 update
6: yum --enablerepo=remi,remi-php56 upgrade
7: reboot
8: php -v Big Grin
