### ISSUE TITLE
OSTicket-v1.10-rc.3 Error 

### ISSUE THREAD

**Issue by suportgc** [osTicket/osTicket#3212]
![ost](https://cloud.githubusercontent.com/assets/19677143/16194389/b84e1aa0-36ca-11e6-8205-31dea804dd3b.png)
When updating the version of my system.
I am getting the warnings .

Can you help me ?

To perform the update , simply replace the files with new ones.
Is correct ?

**Comment by suportgc** [comment]
Just to detail.
When I replaced the files and entered the system, it was not requested update.
Just reported that has been updated .

**Comment by greezybacon** [comment]
These warnings suggest you should install / enable the "Zend Opcache" extension and the "ACPu" extension. As suggested, such would improve the overall performance

**Comment by suportgc** [comment]
Thanks for the answer .
