### ISSUE TITLE
Time Zone Wrong Setting

### ISSUE THREAD

**Issue by firepro20** [osTicket/osTicket#3214]
As can be observed the timing is off. PHP.ini is set and defined to UTC. These are set for Admin Panel and Preferences. What is wrong? 

![image](https://cloud.githubusercontent.com/assets/17837413/16201105/6a9bfc32-3710-11e6-8c93-ad6ac9951f21.png)

![image](https://cloud.githubusercontent.com/assets/17837413/16201214/d158fae2-3710-11e6-9182-2ba2496f2328.png)

**Comment by ntozier** [comment]
The first screen shot appears to be the system settings page in admin panel. Those times are not there to be correct they are there to demonstrate the result of the formatting string to the left.

**Comment by firepro20** [comment]
Fixing the time offset on phpmyadmin did the trick

**Comment by C4RLOCO** [comment]
Hi @firepro20 how did you fix the time offset on phpmyadmin ?

**Comment by C4RLOCO** [comment]
I noticed the database (phpmyadmin) time zone is set to MST (Interpreted as America/Denver) and my osTicket setting is America/New_York. I could not find a way to change the phpmyadmin timezone (hosted in GoDaddy)

Admin Panel - Dashboard - Information -> TimeZone America/Denver
Admin Panel - Settings - Default Time Zone -> America/New York

**Comment by firepro20** [comment]
@C4RLOCO You go into phpmyadmin and then there are some variables that reference the times table. I changed one or two of them which where the global time setting for the server.

**Comment by elambro** [comment]
For Googlers, if your database time is set to GMT, OSTicket reads this as 'Europe/London' instead of UTC. Your times will then be 1 hour off during DST. To fix this, change `includes/class.config.php`.  Change the method `OsticketConfig::getDbTimezone` to this: 

```
function getDbTimezone() {
        if (!$this->exists('db_timezone')) {
            require_once INCLUDE_DIR . 'class.timezone.php';
            $this->persist('db_timezone', DbTimezone::determine());
        }
        $db = $this->get('db_timezone');
        if ( $db === 'Europe/London') {
            $db = 'UTC';
        }
        return $db;
    }
```
