### ISSUE TITLE
OsTicket 1.9.14 Multiple Attachments Issue

### ISSUE THREAD

**Issue by ATalker** [osTicket/osTicket#3218]
After upgrading OsTicket from 1.9.12 to 1.9.14 I found Multiple Attachments issue: if you pick more than one file for attach  in ticket  then after post reply one or few attachments will not upload.
Examples in attachments.
![test1](https://cloud.githubusercontent.com/assets/13776659/16219940/a878b47a-379a-11e6-86c6-9a73137c78d6.gif)
![test2](https://cloud.githubusercontent.com/assets/13776659/16219941/a87ca8f0-379a-11e6-8f1b-f8388055b5d3.gif)

**Comment by ntozier** [comment]
This appears to be a duplicate report.
https://github.com/osTicket/osTicket/issues/877
https://github.com/osTicket/osTicket/issues/1125

**Comment by greezybacon** [comment]
@ATalker could you try the patch in cd6eae6c93e23483566b73559af92378088b1e64? I think it should be backported to 1.9.x until we can shore up the parallel request + session thrashing issue.

**Comment by ATalker** [comment]
@greezybacon i tried your patch and it works. Thank you!

**Comment by greezybacon** [comment]
@ATalker thanks for the feedback. I pushed the commit into the `1.9.x` branch.

**Comment by Dorian-Grim** [comment]
@greezybacon cd6eae6 only fixes the 2nd gif, the 1st still remains unsolved for the 1.9.x branch.
Can you point to a patch please?
