### ISSUE TITLE
Upgrade Error: 1.9.12 -> 1.10 RC3 

### ISSUE THREAD

**Issue by Hannibal226** [osTicket/osTicket#3221]
I was testing the upgrade from our production version (1.9.12) to the new RC3 release.

I think I tried and changed things feeled like about hundred times, but always seeing:
`[core]: Upgrader Error now`.

All problems starting with the Error:
`DB Error #1054`
After that issue I only see the Upgrader Errors.

Problem always the same `Table 'XYZ' already exists` or `Duplicate column name 'XYZ'`
I tried to deselect all the SLX statement from SQL which causing the specific error, but it's always continuing and I just deselecting the next ones...

INFO: 
I copied the new version to testserver, created the DB, imported the backup of production DB and then just copied/changed the ost-config.

What is going on and how can I solve this problem without setting up new or loosing all existing ticket/data?

CHEERS

**Comment by greezybacon** [comment]
Seriously?! Are you seriously redacting the names of the tables and columns? How in the world can I help you fix the problem? Is there a back trace from the `DB Error #1054`?

**Comment by Hannibal226** [comment]
@greezybacon 
Ehm sorry, but as it's so various I didn't think this would help, but here u go:
#1054 error:
`Unknown column 'extra' in 'field list'`
[core]: Upgrader Error now:
`Table 'ost_translation' already exists`
`Duplicate column name 'lang'`

Here I started to uncomment "ADD 'lang' AFTER 'inline'

Then it continues with (uncommented after each of these):
`Duplicate column name 'timezone'`
`Table 'ticketsystem.ost__timezones' doesn't exist`
`Table 'ost_queue' already exists`
`Duplicate column name 'est_duedate'`
`Table 'ost_role' already exists`
[...]

So I stopped here, because it will just continuing and I don't think this is the correct way, heh :P 

CHEERS
