### ISSUE TITLE
1.10 RC3 knowledgebase broken

### ISSUE THREAD

**Issue by GoodbyeWorld** [osTicket/osTicket#3223]
Upgraded from 1.10 RC2 to 1.10 RC3, release afd63e1198c5c7d7f6dd6c9057f176d9b007242f

When logged in as staff, I go to Knowledgebase tab and I get this:

`Fatal error: Call to a member function sort() on a non-object in /opt/osTicket-git/osTicket-1.10-rc3/include/staff/faq-categories.inc.php on line 147`

I had a small handful of articles in my knowledgebase, and they appear to be unavailable due to this.

**Comment by infectormp** [comment]
https://github.com/osTicket/osTicket/issues/3147

**Comment by GoodbyeWorld** [comment]
@infectormp Thank you - that did indeed fix this issue.
