### ISSUE TITLE
1.10 RC3 ticket subject empty

### ISSUE THREAD

**Issue by GoodbyeWorld** [osTicket/osTicket#3224]
Upgraded from 1.10 RC2 to 1.10 RC3, release afd63e1198c5c7d7f6dd6c9057f176d9b007242f

I've got a ticket type where I've unchecked many of the default form questions like "Issue Summary" which gets stored as the variable "subject".  Prior to RC3, the Subject of new tickets was set to the name of the ticket type, and now (since I do not ask the user to provide an Issue Summary) the Subject of all new tickets is empty.  I've confirmed that by re-enabling that form field, and entering a value, the Subject of the ticket is set to the user-entered value.

Would it be possible to have the Subject behave like it did in RC2, where if the user did not provide a value for Subject, it would default to the ticket type?

**Comment by ntozier** [comment]
Did you modify your RC2 installation?  Because this: "Would it be possible to have the Subject behave like it did in RC2, where if the user did not provide a value for Subject, it would default to the ticket type?"  is not a thing that osTicket does.

**Comment by GoodbyeWorld** [comment]
Other than adding a custom language to "translate" some terms needed for our use-case, no other changes including code changes were made. We're a small not-for-profit organization, and we deliver a full years worth of gently-used baby clothing and supplies to families in need.   The language needed to be adjusted away from "tickets", "agents", and "users" to "requests", "volunteers", and "applicants", for example.  I provided a write-up on the procedure here: https://crowdin.com/project/osticket-official/discussions/465/0/en-GB


Anyhow, back to the issue at hand - here are the steps to reproduce this (I need to run through this again myself, but I think it's "this easy".. famous last words):

1. Create a custom form with whatever fields you like.
2. Create a Help Topic, and associate your custom form with the Help Topic
3. In the Help Topic Forms tab, un-check all fields in the Ticket Details section

Now create a new ticket, and go to the agent panel and look at the list of tickets.  Your new ticket is created with a Subject (aka Issue Summary) set to the name of the Help Topic.  

For my use-case, this was terrific.  I didn't want users entering a subject because we're using the tickets for tracking request-fulfillment, where the request-type is one of several Help Topics, like "Need a Gift", "Have Items for Donation", etc.

**Comment by GoodbyeWorld** [comment]
@ntozier - I've just installed a fresh v. 1.10 RC2 install with a fresh database, followed the three steps above, and it worked as I described (the ticket Subject (aka Issue Summary) was set to the Help Topic name).

I then upgraded to RC3, and the behavior changed.  RC3 leaves the ticket Subject empty when new tickets are created.

**Comment by greezybacon** [comment]
@GoodbyeWorld could you try the patch in #3237 to see if it addresses the issue

**Comment by GoodbyeWorld** [comment]
@greezybacon You rock Jared, that did it!

I feel like I come across and report some pretty odd bugs, so I'll share some background that might explain why.  We're a small not-for-profit project where we collect clothing and baby-item donations, clean and prepare them, then deliver a full year's worth of clothing and supplies to families in need.  As we grew, we started to realize that tracking requests by-hand in email just wouldn't scale.  I'm an IT guy, and I saw this problem as a great fit for a ticketing system and selected osTicket to track donations and gift fulfillment.  Now we have a team of 30 volunteers using osTicket, and fulfill requests from several hundred families a year.   This project has enabled us to scale and provide substantially more help our community with way less effort by volunteers.  

In addition to a ton of custom forms, the biggest customization I made was creating a language translation to use terms that are appropriate for this context.  Luckily it was easy enough to do with the i18n support.

Thanks again for your help with this!

**Comment by ntozier** [comment]
If this solved your issue can you please close the issue report.

**Comment by GoodbyeWorld** [comment]
@ntozier Will do, thanks!

**Comment by greezybacon** [comment]
@GoodbyeWorld thanks for your feedback on how you use the system. It's encouraging to find how everyone makes use of all the various features.
