### ISSUE TITLE
1.10 RC3 datetime form data broken

### ISSUE THREAD

**Issue by JohnDelisle** [osTicket/osTicket#3225]
Upgraded from 1.10 RC2 to 1.10 RC3, release afd63e1198c5c7d7f6dd6c9057f176d9b007242f

It appears that there's been a change around how datetime form values are stored, and as a result, after upgrading all the datetime values in my tickets are no longer being displayed.  

Here's how my form fields are defined in the ost_form_field table:

```
MariaDB [support]> select * from ost_form_field where form_id = 8 \G
*************************** 1. row ***************************
           id: 40
      form_id: 8
        flags: 30465
         type: datetime
        label: Baby Due-Date
         name: babyDue
configuration: {"time":false,"gmt":false,"min":"","max":"","future":true}
         sort: 1
         hint: Please tell us your approximate due-date. We need to know the due-date to prepare the gift. We try to provide clothes that are appropriate for each season, and the due-date helps us to understand what sizes your baby will need when.
      created: 2015-12-26 16:05:31
      updated: 2016-06-23 06:32:40
*************************** 2. row ***************************
           id: 41
      form_id: 8
        flags: 30465
         type: choices
        label: Sex
         name: babyGender
configuration: {"choices":"Boy\r\nGirl\r\nMultiple Babies (Twins etc.)\r\nIt will be a surprise\r\nI hope to find out before delivery date","default":"","prompt":"","multiselect":false}
         sort: 2
         hint: We need to know the sex of your baby before we can begin preparing your gift. If you're unsure now, you can always update this later once you know.
      created: 2015-12-26 16:05:31
      updated: 2016-01-01 16:15:28
2 rows in set (0.00 sec)

```

Notice that id 40 is a datetime type field.

Now look at how the data is stored (output truncated to save space here):

```
*************************** 219. row ***************************
entry_id: 2507
field_id: 40
   value: 1470528000
value_id: NULL
*************************** 220. row ***************************
entry_id: 2514
field_id: 40
   value: 1462147200
value_id: NULL
*************************** 221. row ***************************
entry_id: 2521
field_id: 40
   value: 2016-10-07 00:00:00
value_id: NULL
*************************** 222. row ***************************
entry_id: 2528
field_id: 40
   value: 2016-06-23 00:00:00
value_id: NULL
*************************** 223. row ***************************
entry_id: 2535
field_id: 40
   value: 2016-07-28 00:00:00
value_id: NULL
*************************** 224. row ***************************
entry_id: 2542
field_id: 40
   value: 2016-06-22 00:00:00
value_id: NULL
224 rows in set (0.00 sec)
```

Notice how the `value` changes from Unix epoch time stamps to date-time strings at row 221 - this is the first ticket received since upgrading to RC3.  Rows prior to 221 were with RC2.

As a result of this change, dates are no longer visible to agents when working with tickets opened back on RC2.  When viewing the ticket, the entire field (Baby Due-Date) is missing entirely.  If they choose to edit, the value is "0", and they can set a new datetime value by using the popup calendar widget.

I can manually correct this by editing the data (converting from epoch to date time string), but I thought I should report this since I'm sure others will be affected.  

Can this be worked around in the code, so it detects and accommodates either the epoch or date time string values correctly?

Thanks

**Comment by infectormp** [comment]
can you try this https://github.com/osTicket/osTicket/pull/3219?

**Comment by GoodbyeWorld** [comment]
@infectormp Thanks for the suggestion - I've tried that, and it didn't appear to make any difference when viewing tickets. 

I may not understand the nuance of the change you suggested, but I don't see how it would affect datetime fields being stored in the DB as epoch timestamps (RC2) vs. being stored as MySQL datetime strings (RC3).  I think something must have changed around the format of how datetime values are stored.

**Comment by greezybacon** [comment]
I think 5ebebbbcde10b3475b8efbb86becfb9a37352791 is the culprit. Perhaps you could run the associated database update query:
```sql
-- Change storage type for `DatetimeField` values to Y-m-d format
UPDATE `ost_form_entry_values` A1
  JOIN `ost_form_field` A2 ON (A2.`id` = A1.`field_id`)
  SET A1.`value` = DATE_FORMAT(FROM_UNIXTIME(A1.`value`), '%Y-%m-%d %H:%i:%s')
  WHERE A2.`type` = 'datetime' AND A1.`value` > 1000000;

-- Updates should happen in the %cdata tables too; however, those are more
-- complex and the tables are being dropped anyway
```

**Comment by GoodbyeWorld** [comment]
@greezybacon Thanks for the fix, very appreciated!  Your SQL update corrected all the date data, and now it's showing up correctly when using RC3 to look at tickets created in RC2. 

I see you've tagged this db-migration, and probably want to follow up with something to accommodate other users moving from RC2 to RC3 so I'll leave this issue open, unless you advise me to close it.  Thanks.

**Comment by greezybacon** [comment]
@protich you have several users for whom you should run that patch...
