### ISSUE TITLE
1.10 RC3 advanced search not matching "includes" on "choices" form fields

### ISSUE THREAD

**Issue by GoodbyeWorld** [osTicket/osTicket#3226]
Upgraded from 1.10 RC2 to 1.10 RC3, release afd63e1198c5c7d7f6dd6c9057f176d9b007242f

I have a form field that is a "Choices" type, with several options for the users to select from.  For example, the choices might be Red, Yellow, and Blue.  Users select from one of those.

When I perform an advanced search, I find my form field, choose "Includes", and then select "Red" from the options that are presented.  When I search, I get no results.  This happens regardless of what I use in the "contains" directive, even though I have hundreds of tickets that should have been found.

I enabled SQL logging, and discovered this query.  Notice the `value IN ('Red')` part.  I should mention I did several advanced searches trying "includes" and "does not include", and I don't know which search this particular query belonged to, but it serves its purpose in helping to see the issue, I think.

```
SELECT COUNT(*) FROM (SELECT A1.`ticket_id` FROM `ost_ticket` A1 JOIN `ost_form_entry` A2 ON (A2.`object_type` = 'T' AND A1.`ticket_id` = A2.`object_id`) LEFT JOIN `ost_form_entry_values` A3 ON (A2.`id` = A3.`entry_id`) JOIN `ost_ticket_status` A4 ON (A1.`status_id` = A4.`id`) WHERE (A3.`field_id` = '41' AND NOT A3.`value` IN ('Red')) AND ((A4.`state` = 'open' AND (A1.`staff_id` = 4 OR A1.`team_id` IN (3))) OR A1.`dept_id` IN ('1', '4', '7')))
```

Next, I looked at the data this query was searching in with the `in` clause, and found the following:

```
select * from ost_form_entry_values where field_id = 41;
+----------+----------+---------------------------------------------------------------------------------------+----------+
| entry_id | field_id | value                                                                                 | value_id |
+----------+----------+---------------------------------------------------------------------------------------+----------+
<truncated>
|     2206 |       41 | {"Red":"Red"}                                                                         |     NULL |
|     2213 |       41 | {"Red":"Red"}                                                                         |     NULL |
|     2219 |       41 | {"Red":"Red"}                                                                         |     NULL |
|     2226 |       41 | {"Green":"Green"}                                                                     |     NULL |
|     2240 |       41 | {"Green":"Green"}                                                                     |     NULL |
|     2247 |       41 | {"Green":"Green"}                                                                     |     NULL |
<truncated>

```

Notice that the `value` is NOT simply `'Red'`, as seen in the long `select` statement above.  I don't know why it's stored as it is, but in order to find this value, you'd need a `select` where your `in` clause looks for `'{"Red":"Red"}'`.

Hope this helps, it'd be great if advanced search worked!

**Comment by greezybacon** [comment]
> Hope this helps, it'd be great if advanced search worked!

I know I've seen this elsewhere. Sorry we have gotten around to addressing it yet.

**Comment by GoodbyeWorld** [comment]
@greezybacon Looks like someone else has reported this - https://github.com/osTicket/osTicket/issues/2625 Maybe that's what you were thinking  of?

**Comment by edukondalugorla** [comment]
I am facing same issue in advanced search.

**Comment by GoodbyeWorld** [comment]
Just upgraded to stable release 1.10.  901e5ea  

Same issue with advanced searches.

**Comment by rayfoss** [comment]
Closing duplicate issue, please continue the conversation on the ne
