### ISSUE TITLE
OsTicket 1.9.14: There is  no email address near collaborator name

### ISSUE THREAD

**Issue by ATalker** [osTicket/osTicket#3227]
Hello
   In **OsTicket 1.9.12**,  If you add collaborator manual or automatically, then system will print Internal message with name + email of user(s)
   In **OsTicket 1.9.14**,  If you add collaborator manual or automatically, then system will print Internal message with only name 
   Is it Bug or Feature?

Examples: 

**Screenshot for 1.9.12**
![ot 1 9 12 test](https://cloud.githubusercontent.com/assets/13776659/16299438/57108f38-394b-11e6-8fbb-5106a4f7156d.png)

**Screenshot for 1.9.14**
![ot 1 9 14 test](https://cloud.githubusercontent.com/assets/13776659/16299437/570ece46-394b-11e6-8537-8be59a1bd3ac.png)

**Comment by greezybacon** [comment]
Looks like a XSS bug

**Comment by greezybacon** [comment]
@ATalker could you try the patch in #3238 to see if it addresses the issue?

**Comment by ATalker** [comment]
I tried https://github.com/osTicket/osTicket/pull/3238 and it works in case when you add collaborator manually  but patch doesn't solve bug when system adds collaborator in automatic mode.

**Comment by ATalker** [comment]
Problem with auto adding collaborators for organization is still present in osTicket
1.9.15. There are no emails near collaborators name after creating ticket.
![5ceda1bdaf](https://cloud.githubusercontent.com/assets/13776659/20254930/160bdac4-aa52-11e6-8829-8519b73fb90b.jpeg)

**Comment by ATalker** [comment]
Problem with auto adding collaborators for organization is still present in osTicket
1.9.16. There are no emails near collaborators name after creating ticket.
![ot 1 9 16](https://user-images.githubusercontent.com/13776659/32219606-263f3fd4-be48-11e7-97f2-5675b4fe8ee9.jpeg)

**Comment by ATalker** [comment]
#3238 doesnt solve fully this issue
