### ISSUE TITLE
1.10 RC3 - issue report - i18 - ticket state name will not be saved

### ISSUE THREAD

**Issue by mfelber** [osTicket/osTicket#3230]
When I enter a new ticket state name for the german language and click on save (Speichern):

![ticket state name offen](https://cloud.githubusercontent.com/assets/5539456/16306343/a1f8730a-395d-11e6-8ab5-99bb61b24a83.jpg)

.. it won't be saved:

![ticket stae name open](https://cloud.githubusercontent.com/assets/5539456/16306310/86c67c58-395d-11e6-94c1-ca2eac0a1dcd.jpg)

No error is displayed. No error in the osticket or in the webserver log.
The other parts of osticket don't have this problem (for example the properties of the list elements):

![custom list elements properties](https://cloud.githubusercontent.com/assets/5539456/16306587/7ac22b36-395e-11e6-80ad-83377fee3ce4.jpg)

**Comment by mfelber** [comment]
I don't think that has something to do with the language pack. That also happen with a fresh install without  a language pack.

In osticket 1.9.x I can change the name:

![offen](https://cloud.githubusercontent.com/assets/5539456/16313921/bddf2afa-397b-11e6-9a20-9e1dc6bb38d4.jpg)

That seems the place in the database where it should be stored:

![ticket status](https://cloud.githubusercontent.com/assets/5539456/16313936/d151e988-397b-11e6-8227-e5c392a2c63e.jpg)

**Comment by balojs** [comment]
Same issue #3084

**Comment by mfelber** [comment]
Ok, I see it. I will close this issue report because it's obviously a duplicate issue ;-)
