### ISSUE TITLE
1.10 RC3 auth-ldap fails with error 500

### ISSUE THREAD

**Issue by mohataj** [osTicket/osTicket#3232]
still working in 1.10 RC2, auth-ldap fails with error 500 in 1.10 rc3

http://FQHN/helpdesk/scp/ajax.php/users?q=<username> cannot be loaded

**Comment by ntozier** [comment]
wrong repo to report this at.
Also this is a dupe.  Please close it.
https://github.com/osTicket/osTicket-plugins/issues/105
https://github.com/osTicket/osTicket-plugins/issues/100
