### ISSUE TITLE
1.10 RC3 email added to ticket wrong sender and recipient

### ISSUE THREAD

**Issue by mohataj** [osTicket/osTicket#3233]
Email-Info shows up in the ticket as:

Von: Helpdesk  [mailto:helpdesk@] 
Gesendet: Freitag, 24. Juni 2016 13:10
An: Vorname Nachname
Betreff: Aw: Tickettitel [#140464]

should be

Von: Vorname Nachname
Gesendet: Freitag, 24. Juni 2016 13:10
An: Helpdesk  [mailto:helpdesk@] 
Betreff: Aw: Tickettitel [#140464]

**Comment by ntozier** [comment]
Please provide actual email headers.

**Comment by mohataj** [comment]
Hans Langemann posted 2 days ago 

das verstehe ich nicht
 

Von: Helpdesk Münchner Tafel [mailto:helpdesk@muenchner-tafel.de] 
Gesendet: Freitag, 24. Juni 2016 14:17
An: Matthias Hataj <Hataj@muenchner-tafel.de>
Betreff: Neue Nachricht
 


Helpdesk Münchner Tafel [mailto:helpdesk@muenchner-tafel.de] <br><b>Gesendet:</b> Freitag, 24. Juni 2016 18:37<br><b>An:</b> Matthias Hataj &lt;Hataj@muenchner-tafel.de&gt;<br><b>Betreff:</b> Neue Nachricht<o:p></o:p></span></p><p class=MsoNormal><o:p>&nbsp;</o:p></p><div><p class=MsoNormal style='margin-bottom:12.0pt'>-- Bitte oberhalb dieser Zeile antworten --<o:p></o:p></p></div><h3><strong>Hallo Matthias Hataj,</strong><o:p></o:p></h3><p class=MsoNormal style='margin-bottom:12.0pt'>es wurde eine neue Nachricht zum Ticket <a href="http://mtfms.mtf.local/helpdesk/scp/tickets.php?id=117">#140464</a> hinzugefügt. <o:p></o:p></p><table class=MsoNormalTable border=0 cellpadding=0><tr><td style='padding:.75pt .75pt .75pt .75pt'><p class=MsoNormal><strong>Von</strong>: <o:p></o:p></p></td><td style='padding:.75pt .75pt .75pt .75pt'><p class=MsoNormal><em>Hans Langemann &lt;Hans Langemann&gt;</em> <o:p></o:p></p></td></tr><tr><td style='padding:.75pt .75pt .75pt .75pt'><p class=MsoNormal><strong>Abteilung</strong>: <o:p></o:p></p></td><td style='padding:.75pt .75pt .75pt .75pt'><p class=MsoNormal>Disposition <o:p></o:p></p></td></tr></table><p class=MsoNormal><o:p>&nbsp;</o:p></p><div><p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;color:#1F497D'>Weder colleborator, noch – doch - &nbsp;Beteiligte Person: Hans Langemann</span><o:p></o:p></p><p><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;color:#1F497D'>&nbsp;<o:p></o:p></span></p><p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;color:#1F497D'>Für mich ist entscheidend, eine gute Bestückung des Kellers zu erreichen, hier sei Dank Urs, ebenso sind die Verteilerstellen zu sehen.</span><o:p></o:p></p><p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;color:#1F497D'>Die Disposition ist gleich dabei zu gewichten!</span><o:p></o:p></p><p><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;color:#1F497D'>&nbsp;<o:p></o:p></span></p><p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;color:#1F497D'>Begleitend dabei sei Helpdesk, das Augenmerk aber mehr auf die Tagesprobleme, dem operativen Geschäft gerichtet.</span><o:p></o:p></p><p><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;color:#1F497D'>&nbsp;<o:p></o:p></span></p><p><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;color:#1F497D'>&nbsp;<o:p></o:p></span></p><p><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;color:#1F497D'>&nbsp;<o:p></o:p></span></p><p><span style='font-size:11.0pt;font-family:"Calibri",sans-serif;color:#1F497D'>&nbsp;<o:p></o:p></span></p><p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto'><b><span style='font-size:10.0pt;font-family:"Tahoma",sans-serif'>Von:</span></b><span style='font-size:10.0pt;font-family:"Tahoma",sans-serif'> Helpdesk Münchner Tafel [<a href="mailto:helpdesk@muenchner-tafel.de">mailto:helpdesk@muenchner-tafel.de</a>] <br><b>Gesendet:</b> Freitag, 24. Juni 2016 14:27<br><b>An:</b> Hans Langemann<br><b>Betreff:</b> Aw: Änderungen Tourenpläne [#140464]</span><o:p></o:p></p><p>&nbsp;<o:p></o:p></p></div><p class=MsoNormal style='margin-bottom:12.0pt'><o:p>&nbsp;</o:p></p><div class=MsoNormal align=center style='text-align:center'><hr size=2 width="100%" align=center></div><p class=MsoNormal>Um das Ticket zu betrachten/beantworten, bitte am Support-Ticket-System <a href="http://mtfms.mtf.local/helpdesk/scp/tickets.php?id=117"><span style='color:#548DD4'>anmelden</span></a> <br><em>Ihr freundliches Support-Ticket-System</em> <br><img border=0 width=126 height=23 id="_x0000_i1026" src="cid:image001.png@01D1CE47.853AFB10" alt="Powered by osTicket"><o:p></o:p></p></div></body></html>

**Comment by greezybacon** [comment]
@mohataj those are not the headers. That is the body of the email
