### ISSUE TITLE
Error when attempting to assign to different user - v1.10-rc.3-1-gafd63e1

### ISSUE THREAD

**Issue by Taps7734** [osTicket/osTicket#3234]
When I attempt to assign a ticket to another user, I see that the AJAX window just spins after I hit the ASSIGN button.  

Looking in the error log, I see this

`PHP Fatal error:  Call to undefined method QuerySet::findFirst() in /var/www/html/include
/class.dept.php on line 341, referer: http://support.company.com/scp/tickets.php?id=7322`

Originally saw the issue in 907ec36, so I updated to afd63e1 and the problem persists,

**Comment by Taps7734** [comment]
Sorry.  Didn't have the full version in the title.  Just what I pulled from the bootstrap.php.

Full version is v1.10-rc.3-1-gafd63e1

**Comment by balojs** [comment]
I have the same versión but not show this error

![screenshot](https://cloud.githubusercontent.com/assets/3303352/16340923/cce478f4-39e7-11e6-9209-790f022475ba.png)

**Comment by greezybacon** [comment]
I think #3090 might be the best fix for this

**Comment by greezybacon** [comment]
@balojs could you try this patch?
```patch
diff --git a/include/class.dept.php b/include/class.dept.php
index 93f92d7..31be31a 100644
--- a/include/class.dept.php
+++ b/include/class.dept.php
@@ -336,7 +336,7 @@ implements TemplateVariable {
         if (is_object($staff))
             $staff = $staff->getId();
 
-        $members = $this->getMembers() ?: $this->members;
+        $members = $this->getMembers()->getIterator() ?: $this->members;
 
         return ($members->findFirst(array(
                         'staff_id' => $staff)));
```

**Comment by balojs** [comment]
@greezybacon yeah, it's worth this patch 👍

**Comment by de4niih** [comment]
Worked for me too ;)
