### ISSUE TITLE
1.10/1.11 DB Error #1054

### ISSUE THREAD

**Issue by kest874** [osTicket/osTicket#3235]
@greezybacon Could you give me some incite on where to trace this error, it's somewhat random:

`DB Error #1054
[SELECT A1.`id`, A1.`org_id`, A1.`default_email_id`, A1.`status`, A1.`name`, A1.`created`, A1.`updated`, A2.`id`, A2.`user_id`, A2.`flags`, A2.`address`, A3.`id`, A3.`name`, A3.`manager`, A3.`department`, A3.`status`, A3.`domain`, A3.`extra`, A3.`created`, A3.`updated`, A4.`id`, A4.`user_id`, A4.`status`, A4.`timezone`, A4.`lang`, A4.`username`, A4.`passwd`, A4.`backend`, A4.`extra`, A4.`registered` FROM `ost_user` A1 LEFT JOIN `ost_user_email` A2 ON (A1.`default_email_id` = A2.`id`) LEFT JOIN `ost_organization` A3 ON (A1.`org_id` = A3.`id`) LEFT JOIN `ost_user_account` A4 ON (A1.`id` = A4.`user_id`) WHERE A1.`id` = 486] Unknown column 'A3.department' in 'field list'

 ---- Backtrace ----
 #0 (root)/include/mysqli.php(199): osTicket->logDBError('DB Error #1054', '[SELECT A1.`id`...')
 #1 (root)/include/class.orm.php(3371): db_query('SELECT A1.`id`, ...', true, true)
 #2 (root)/include/class.orm.php(3427): MySqlExecutor->execute()
 #3 (root)/include/class.orm.php(1938): MySqlExecutor->getRow()
 #4 (root)/include/class.orm.php(1982): ModelInstanceManager->{closure}()
 #5 (root)/include/class.orm.php(1961): CallbackSimpleIterator->next()
 #6 (root)/include/class.orm.php(1970): CallbackSimpleIterator->rewind()
 #7 (root)/include/class.orm.php(1646): CallbackSimpleIterator->valid()
 #8 (root)/include/class.orm.php(1656): CachedResultSet->fillTo(9223372036854775807)
 #9 (root)/include/class.orm.php(1302): CachedResultSet->asArray()
 #10 (root)/include/class.orm.php(1325): QuerySet->all()
 #11 (root)/include/class.orm.php(600): QuerySet->one()
 #12 (root)/include/class.orm.php(376): VerySimpleModel::lookup(Array)
 #13 (root)/include/class.orm.php(412): VerySimpleModel->get('user', NULL)
 #14 (root)/include/class.thread.php(1718): VerySimpleModel->__get('user')
 #15 (root)/include/class.thread.php(1766): ThreadEvent->getUserName()
 #16 [internal function]: ThreadEvent->{closure}(Array)
 #17 (root)/include/class.thread.php(1812): preg_replace_callback('/\\{((...', Object(Closure), 'Created by {...')
 #18 (root)/include/class.thread.php(2059): ThreadEvent->template('Created by {...')
 #19 (root)/include/staff/templates/thread-event.tmpl.php(6): CreationEvent->getDescription(1)
 #20 (root)/include/class.thread.php(1828): include('/var/www/suppor...')
 #21 (root)/include/staff/templates/thread-entries.tmpl.php(60): ThreadEvent->render(1)
 #22 (root)/include/class.thread.php(271): include('/var/www/suppor...')
 #23 (root)/include/staff/ticket-view.inc.php(563): Thread->render(Array, Array)
 #24 (root)/scp/tickets.php(534): require_once('/var/www/suppor...')
 #25 {main}
`

The org table doesn't have a department column, so I'm not sure where this is happening.  The error seems to pop up at random when viewing a ticket.

**Comment by greezybacon** [comment]
Did you add it to your database? I'm not sure where that would come from. Maybe you should restart apache or php-fpm?

**Comment by kest874** [comment]
I didn't add but might to get the error to go away. The issue is that it's not repeatable and I'm not clear where or how the field is getting added to the query.

**Comment by greezybacon** [comment]
@kest874 it doesn't make any sense. If you get a lead on when the error occurs, let me know and I'll check it out further.

**Comment by kest874** [comment]
Narrowed this down, I have a  second site configured that uses a department field in the organization table.  The code in that site surrounding the department doesn't exist in the troubled site, it's as if the department column is cached and apache is confused about which site is loading throwing the error.

Any thoughts?  For now I added the department column so the error should not reoccur.

**Comment by greezybacon** [comment]
@kest874 Apache caching is indeed the issue. The cache key is based on the `SECRET_SALT` defined in the `ost-config.php` file. Ensure that the two sites have differing salts. You can also edit the `GIT_VERSION` defined in `bootstrap.php`; however, this will be overwritten when you deploy or unpack updated code.

**Comment by greezybacon** [comment]
If you wanna read more, [here's the code](https://github.com/osTicket/osTicket/blob/develop/include/class.orm.php#L267) where the caching happens

**Comment by kest874** [comment]
@greezybacon Than you for your assistance, I changed the key on one site and then restarted apache problem solved.  Most likely no one will ever run into this.
