### ISSUE TITLE
OSTicket v1.10 RC3 Task Bug

### ISSUE THREAD

**Issue by blhf** [osTicket/osTicket#3245]
When I open a new Task after update the title becomes blank. Please help fix. Regards,

**Comment by blhf** [comment]
Experienced this when using Choices and Custom List. Thanks

**Comment by blhf** [comment]
@greezybacon

**Comment by ntozier** [comment]
Can you please be a little more coherent and descriptive of what your actual issue is.  Please include step by step instructions to re-create your issue, and you might want to include an image or two (before/after) so that we can see what you mean.

**Comment by blhf** [comment]
![image](https://cloud.githubusercontent.com/assets/10716429/16479201/5d62d1a8-3ed1-11e6-8be4-de94d363906a.png)
![image](https://cloud.githubusercontent.com/assets/10716429/16479202/5f5ccbe4-3ed1-11e6-916b-c816c263f7fa.png)
![image](https://cloud.githubusercontent.com/assets/10716429/16479209/6382cd86-3ed1-11e6-9c08-0f30f9091225.png)
![image](https://cloud.githubusercontent.com/assets/10716429/16479210/6634e910-3ed1-11e6-87f5-8a638353700d.png)

**Comment by blhf** [comment]
@ntozier  I actually reverted RC2 @ the moment thats why I edited the last picture to erased the title. That is the scenario in RC3 title is not showing after creation of task, same as using the custom list.

Best Regards,

**Comment by markus4000** [comment]
When I open a new task, it doesn't save my desctription and my attachments. It just takes the Title.
RC3 and actual develop version. both the same issue. known?

**Comment by ipAnything** [comment]
Fix can be found here [](https://github.com/t-oster/osTicket-1.8/commit/develop)

Use replace **create** with **add**

**Comment by blhf** [comment]
ipAnything I haven't tried it yet. I rollback to the previous version. can
you share some screenshots?

**Comment by ipAnything** [comment]
If you click on my link you would have seen the code that needs changing. All you have to do is replace the word **create** with **add**. Screenshot below.

![add instead of created](https://cloud.githubusercontent.com/assets/12978304/18803251/aff3ef8c-81ee-11e6-92e5-85456d478c07.PNG)
