### ISSUE TITLE
1.10-rc3 "Custom forms" title problem in client ticket view

### ISSUE THREAD

**Issue by chucks26** [osTicket/osTicket#3247]
Hi,

first of all sorry for my poor english.
Osticket 1.10-rc3 in testing ambient:
![version](https://cloud.githubusercontent.com/assets/20221464/16481732/15ef6120-3ead-11e6-81cd-057a95fb1581.jpg)

We have a few help topics with several custom forms. Theese forms show up correctly when an user open a new ticket (open.php):
![1](https://cloud.githubusercontent.com/assets/20221464/16481809/63e49814-3ead-11e6-8d44-241aa9e32eb6.jpg)

When user try to view the ticket just created (from email autoresponse link), the title of all the custom forms il set up as the last custom form:
![2](https://cloud.githubusercontent.com/assets/20221464/16481863/97de8a08-3ead-11e6-9b17-e11501a3b9cc.jpg)

If user try to print the ticket, instead, pdf will be created as expected:
![3](https://cloud.githubusercontent.com/assets/20221464/16482015/554a548c-3eae-11e6-9a21-5a555511111f.jpg)

I think that problem is in row 118 of /include/client/view.inc.php:
        <tr><td colspan="2" class="headline flush-left"><?php echo $form->GetTitle(); ?></th></tr>

Any suggestion?

Thank you and sorry again for language mistakes...

Chuck26

**Comment by balojs** [comment]
the same problem 1.10-rc3

**Comment by chucks26** [comment]
Did some tries...

Tried 1.10-RC2 and it works correctly....

Replaced "bad" code:

                  RC3 -> "/include/client/view.inc.php", rows from 102 to 136
with
                  RC2 -> "/include/client/view.inc.php", rows from 98 to 128

in RC3 and works flawlessy. I know that could be not a good approach, but, in your opinion, could be a solution?

Cheers,
Chuck26

**Comment by ntozier** [comment]
your "bad" code appears to match the replacement code you provided...

**Comment by chucks26** [comment]
Let me be more accurate (I try..)

In 1.10-RC3 (without any code modification) there is the problem mentioned above.
In 1.10-RC2 (without any modification) not.

So I take code from 1.10-RC2, "/include/client/view.inc.php", rows from 98 to 128:

`foreach (DynamicFormEntry::forTicket($ticket->getId()) as $form) {
    // Skip core fields shown earlier in the ticket view
    $answers = $form->getAnswers()->exclude(Q::any(array(
        'field__flags__hasbit' => DynamicFormField::FLAG_EXT_STORED,
        'field__name__in' => array('subject', 'priority'),
        Q::not(array('field__flags__hasbit' => DynamicFormField::FLAG_CLIENT_VIEW)),
    )));
    if (count($answers) == 0)
        continue;
    ?>
        <table class="custom-data" cellspacing="0" cellpadding="4" width="100%" border="0">
        <tr><td colspan="2" class="headline flush-left"><?php echo $form->getTitle(); ?></th></tr>
        <?php foreach($answers as $a) {
            if (!($v = $a->display())) continue; ?>
            <tr>
                <th><?php
    echo $a->getField()->get('label');
                ?>:</th>
                <td><?php
    echo $v;
                ?></td>
            </tr>
            <?php } ?>
        </table>
    <?php
    $idx++;
} ?>
    </td>
</tr>
</table>
<br>`

And pasted in 1.10-RC3, to replace code in  "/include/client/view.inc.php", rows from 102 to 136:

`foreach (DynamicFormEntry::forTicket($ticket->getId()) as $i=>$form) {
    // Skip core fields shown earlier in the ticket view
    $answers = $form->getAnswers()->exclude(Q::any(array(
        'field__flags__hasbit' => DynamicFormField::FLAG_EXT_STORED,
        'field__name__in' => array('subject', 'priority'),
        Q::not(array('field__flags__hasbit' => DynamicFormField::FLAG_CLIENT_VIEW)),
    )));
    // Skip display of forms without any answers
    foreach ($answers as $j=>$a) {
        if ($v = $a->display())
            $sections[$i][$j] = array($v, $a);
    }
}
foreach ($sections as $i=>$answers) {
    ?>
        <table class="custom-data" cellspacing="0" cellpadding="4" width="100%" border="0">
        <tr><td colspan="2" class="headline flush-left"><?php echo $form->getTitle(); ?></th></tr>
<?php foreach ($answers as $A) {
    list($v, $a) = $A; ?>
        <tr>
            <th><?php
echo $a->getField()->get('label');
            ?>:</th>
            <td><?php
echo $v;
            ?></td>
        </tr>
<?php } ?>
        </table>
    <?php
} ?>
    </td>
</tr>
</table>
<br>`

Then I try to run 1.10-RC3 and works great...

Cheers,
Chuck26

**Comment by violarisgeorge** [comment]
In order for this bug to be fixed I suggest that the following
`<tr><td colspan="2" class="headline flush-left"><?php echo $form->getTitle(); ?></th></tr>`

in include/client/view.inc.php

should become:

`<tr><td colspan="2" class="headline flush-left"><?php echo $formArray[$i]->getTitle(); ?></th></tr>`

Additionally, 

`$formArray = array();` 

should be declared before the 

`foreach (DynamicFormEntry::forTicket($ticket->getId()) as $i=>$form)` 

loop, and right after where the loop begins we should declare:

`$formArray[$i] = $form;`

There's probably a more elegant way to do this but as a quick hack it helped me overcome the issue until it is probably fixed in the next rollup.
