### ISSUE TITLE
"Array, Missing or invalid data - check the errors and try again"

### ISSUE THREAD

**Issue by solankesanket** [osTicket/osTicket#3248]
I have configured osTicket version number 1.9.12 on my local machine using WAMP server. A ticket is created successfully with valid fields. I have configured the same version on Windows based server, which is my production server and passing the same data as on my local machine, but I'm getting this error.
I want to know what are the possible cases due to which this issue can arise. 
I have found the error message in 'class.ticket.php', so can you tell me which data is missing or invalid. 
Request you let me know which are the mandatory fields while creating a ticket. 

Thanks,
Sanket.

**Comment by ntozier** [comment]
I'm sorry but you have not really provided us with enough information to assist you.  Perhaps a screen shot of what you are seeing, and your ticket details form where you added fields would clarify things.

**Comment by ntozier** [comment]
I'm presuming that since you close this that you found a solution.  Can you please post here what your solution was in case someone else needs this information later?
