### ISSUE TITLE
Enhancement: Status List by department

### ISSUE THREAD

**Issue by balojs** [osTicket/osTicket#3252]
@greezybacon 
is possible ability, status list visibility by department?

Thanks very much

**Comment by greezybacon** [comment]
@balojs are you requesting certain ticket statuses to be available for only certain departments?

**Comment by balojs** [comment]
@greezybacon  is correct.

Thanks

**Comment by yisrael1981** [comment]
+1 
In my system, we have various departments that utilize the same system and reach one needs different status listings, so we need up having one huge list which makes it very messy

**Comment by kest874** [comment]
Take a look at https://github.com/osTicket/osTicket/pull/3250 for a non messy drop down list.

**Comment by yisrael1981** [comment]
@kest874 That has nothing to do with this issue.
This is about ticket statuses not help topics

**Comment by kest874** [comment]
@yisrael1981 Sorry failed to see "statuses"

**Comment by balojs** [comment]
@protich please evaluate this enhacement certain ticket statuses to be available for only certain departments

**Comment by balojs** [comment]
@rayfoss and @JediKev  please check my request
