### ISSUE TITLE
osTicket 1.10-rc3 - tasks not sending email on creation

### ISSUE THREAD

**Issue by eproudfit** [osTicket/osTicket#3257]
While working with tasks, I have set up the alerting / notifications to be the same as tickets.

If I create the task and assign it to the department only, it does not send out an email to the department members.
If I create the task and assign to the department and an agent, it does send out the email.

I am still evaluating emails about tasks (comments/replies, assignments, etc..)

Also, as a side note: Replying to an assignment task email, it generates a new ticket.  I would think it should go as a comment/reply to the task being responded to.

**Comment by ipAnything** [comment]
Anyone has an update on this? or a fix?

**Comment by jdelhome3578** [comment]
I think I may have found the issue #3407
