### ISSUE TITLE
Assigning ticket doesn't change the dept., too if necessary

### ISSUE THREAD

**Issue by eboehnisch** [osTicket/osTicket#326]
If one assigns a ticket to a person in another department, the department the ticket is assigned to should be changed as well. Otherwise the assignee can only see the ticket as long as there are still _other_ tickets in her/his department. As soon as the assignee closes the last ticket in her own department all tickets assigned to her but a different department are no longer listed.

Example: I am assigned three tickets. One in my own department, two from Sales. osTicket shows "My Tickets (1)".

The "Closed Tickets" number is also incorrect here (should be e.g. 31,000 in our case).

![screen shot 2013-12-17 at 12 13 27](https://f.cloud.github.com/assets/1845871/1763392/956ff55c-670c-11e3-91ec-3d7886f0baed.png)

**Comment by fofosanchezhn** [comment]
hi :) sorry about my silly question but i'm kinda new in this area, can you tell me please in what archive have to apply the patch? already i try it in the class.tickets.php but didn't work :(

**Comment by fofosanchezhn** [comment]
ps. i'm using the version 1.9.12

**Comment by clonemeagain** [comment]
I haven't upgraded to 1.9 yet, essentially it was just a few extra lines in the onAssign method, utilizing the transfer method with a log message.
I should probably upgrade, been slack. Msg me on Monday and I'll write a new patch for you if you want.

**Comment by pcbarbassa** [comment]
Any news about this subject?

**Comment by ntozier** [comment]
Well the lead dev said "I wholeheartedly disagree that a ticket assignment should result in a transfer by default." So I imagine that no other devs have even looks at this more than in passing.

**Comment by clonemeagain** [comment]
@pcbarbassa @jonub 
I figured out how to hack it to do that on mine, patch in comment here: 
https://github.com/osTicket/osTicket/compare/develop...clonemeagain:patch-1#commitcomment-22407711
Initial patch was for 1.7.

**Comment by clonemeagain** [comment]
@pcbarbassa @jonub 
I figured out how to hack it to do that on mine, patch in comment here: 
https://github.com/osTicket/osTicket/compare/develop...clonemeagain:patch-1#commitcomment-22407711
Initial patch was for 1.7.

**Comment by akash65** [comment]
can anyone tell me how to transfer a ticket?

**Comment by ntozier** [comment]
@akash65 why are you cross posting? Also your response does not appear to be on topic for this issue report. I expect that it is because your account does not have "transfer" privileges. I would invite you to seek your support experience at the support forums. http://osticket.com/forums

**Comment by andrelindner** [comment]
> If one assigns a ticket to a person in another department, the department the ticket is assigned to should be changed as well. Otherwise the assignee can only see the ticket as long as there are still _other_ tickets in her/his department. As soon as the assignee closes the last ticket in her own department all tickets assigned to her but a different department are no longer listed.
> 
> Example: I am assigned three tickets. One in my own department, two from Sales. osTicket shows "My Tickets (1)".
> 
> The "Closed Tickets" number is also incorrect here (should be e.g. 31,000 in our case).
> 
> ![screen shot 2013-12-17 at 12 13 27](https://camo.githubusercontent.com/bd1365e611573e21ce17ba6d2a9419ec62eeac7c/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f313834353837312f313736333339322f39353666663535632d363730632d313165332d393165632d3364373838366630626165642e706e67)

still an issue? if not, please close this issue.
