### ISSUE TITLE
Thread count ballon in ticket list

### ISSUE THREAD

**Issue by chucks26** [osTicket/osTicket#3260]
Hi all,

first of all sorry for my English...

I've got a problem in ticket view...in subject column appears ballon with number of thread entries only if >= 2 (see image). Is it possible to show it up also when only 1 note or reply is present?

In the example below, ticket n° 50157344 has 1 reply from user but there is no notification about that...

![image](https://cloud.githubusercontent.com/assets/20221464/16656725/12466132-4460-11e6-8e1a-8b6e817a3e85.png)

Hoping to have been clear enough...thank you!

Chuck26

**Comment by ntozier** [comment]
1 is the original message. If there is a ticket... you can assume that it is 1 unless stated otherwise.

**Comment by chucks26** [comment]
Nope...In the example in the image, ticket n° 50157344 (the second one in the list) has 1 reply from user but there is no notification about that...so there is the original ticket and a reply from user sent via mail. Ticket n. 68422712 (the third) instead has no replies, so there is only original ticket, but no layout differences between this and n. 50157344. Ticket 778120835 (the first) has 1 reply from user and 1 internal note and ballon shows "2"...

Is it correct?

Thank you,
Chuck26

**Comment by ntozier** [comment]
Yes.  There is no response, so its still 1.

**Comment by chucks26** [comment]
Uhm..I cannot understand the logic about that...

A)Ticket n. 68422712 (the third) -> only ticket, no response -> no ballon
B)Ticket n. 50157344 (the second one) -> original ticket + 1 response from user - > no ballon
C)Ticket n. 778120835 (the first) -> original ticket + 2 responses -> ballon shows "2"
D)Ticket n. 56545191 (the fourth) -> original ticket + 3 responses -> ballon shows "3"

Why there is no difference in layout in cases "A" & "B"?

Thank you,
Chuck26

**Comment by chucks26** [comment]
Ok, but why case C shows "2"? There are 2 responses from user....

Thank you,
Chuck26

**Comment by chucks26** [comment]
Did some investigation and found what I think could be my problem...

Every help topic in our system has got custom forms and "Issue Details" field is always disabled, so users never fill it up.
So new ticket thred count when ticket is created is 0...when user reply via mail, system add the response, so the thread count becomes 1 (and shows no ballon).
We need the ability to notice user response in ticket list..
Is it possible to hide "Issue Details" field but fill it up with a fixed value?
Or better, is it possible to show up ballon also with thread count =1?

Thank you as always,
Chuck26

**Comment by greezybacon** [comment]
@chucks26 that's an interesting case. I never considered such a case. It's not clear when the issue details is disabled, since it can be disabled per each help topic. Perhaps we should show the balloon for 1 or more thread items rather than 2 or more

**Comment by chucks26** [comment]
That would be great for us!
In our case, all users are guests, but for some help topics we use the corporate mail to "authenticate" user...in other words, for a few kind of help topics, a simple user fill the ticket with email field of his chief, and this one reply at the osticket mail of confirmation, adding an entry to the thread of the ticket. Agents take care only of tickets with this "tag", so is important for us to make it easy to view in ticket list.

Any hint to where to take a look for changing thread count at 1 to show ballon in code?

Thank you very much,
Chuck26

**Comment by chucks26** [comment]
@greezybacon sorry for insistence...

Any hint to where to take a look to change thread count at 1 to show balloon?

Thank you in advance,
Chuck26

**Comment by kest874** [comment]
It's in include/staff/tickets.inc.php around line 566:

![image](https://cloud.githubusercontent.com/assets/12860950/16813517/78766f1a-48f7-11e6-991b-c9219681dea0.png)

**Comment by chucks26** [comment]
Great!!

That's what I was looking for...thank you @kest874 !
Works like a charm...

Chuck26
