### ISSUE TITLE
Provision to disable authentication for viewing tickets

### ISSUE THREAD

**Issue by pslnarayan** [osTicket/osTicket#3263]
Hi
As per my understanding ticket description and its updates can be viewed only by submitter and agent. If any other user need to view the ticket content, the user should know who was the submitter and ticket number to view the contents. It will be good if there is provision to disable authentication checks for viewing the ticket contents at ticket level or installation (for all tickets) level.  

Support for URL like below for viewing the ticket, that can be viewed by anybody in the organisation without logging into osticket

View URL    : https://www.xyz.domain.com/helpdesk/tickets.php?id=3438 

The below links are available 
Edit URL    : https://www.xyz.domain.com/helpdesk/scp/tickets.php?id=3438

Ticket URL     : https://www.xyz.domain.com/helpdesk/view.php?auth=c1x2efqaahkbqaaao3X4ZxatHUSvlA%3D%3D

**Comment by kest874** [comment]
Not sure this is a good idea, I could then pick any id at random and add a reply...

**Comment by ntozier** [comment]
Goodbye security.  No thanks.

Use Organizations if you want people to be able to see other peoples tickets.
And/Or add a custom open ticket list with minimal details (no ticket number) on the index or a separate page.  Like this: http://tmib.net/add-client-side-open-ticket-list-osticket-19-or-110
