### ISSUE TITLE
osTicket 1.10-rc3 - Users export fails with error

### ISSUE THREAD

**Issue by sistemasad** [osTicket/osTicket#3265]
When you click the export link, you get a blank 500 http error.
On apache logs it shows:

`PHP Fatal error:  Call to undefined method ModelResultSet::rewind() in /site_1.10.rc3/include/class.export.php on line 281, referer: http://------------------/scp/users.php`
- osTicket 1.10.rc3
- Centos 6.8 64b
- mysql 5.1
- php 5.6

**Comment by mfelber** [comment]
You could try this fix https://github.com/osTicket/osTicket/pull/3262
