### ISSUE TITLE
osTicket 1.10-rc3 - Collaborator search autocompletion raises  'OrmException'

### ISSUE THREAD

**Issue by sistemasad** [osTicket/osTicket#3267]
When trying to add a collaborator to a ticket, the third character you enter raises this on apache logs:

`PHP Fatal error:  Uncaught exception 'OrmException' with message 'Union queries must have matching values counts' in /site_1.10.rc3/include/class.orm.php:1282
Stack trace:
#0 /site_1.10.rc3/include/ajax.users.php(90): QuerySet->union(Object(QuerySet))
#1 [internal function]: UsersAjaxAPI->search()
#2 /site_1.10.rc3/include/class.dispatcher.php(145): call_user_func_array(Array, Array)
#3 /site_1.10.rc3/include/class.dispatcher.php(38): UrlMatcher->dispatch(false, Array)
#4 /site_1.10.rc3/include/class.dispatcher.php(120): Dispatcher->resolve(false, Array)
#5 /site_1.10.rc3/include/class.dispatcher.php(38): UrlMatcher->dispatch('/users', NULL)
#6 /site_1.10.rc3/scp/ajax.php(262): Dispatcher->resolve('/users')
#7 {main}

thrown in /site_1.10.rc3/include/class.orm.php on line 1282, referer: http://-----------/scp/tickets.php?id=4527`

No error is shown on browser. If you continue typing, each new char, raises that, BUT the autocompletion shows you correct options to select when match, and the collaborator is added correctly.

osTicket 1.10.rc3
 Centos 6.8 64b
 mysql 5.1
 php 5.6

**Comment by lafaurie** [comment]
I have the same error but I noticed that is for users that are in invited state because I tested with users that are in active and works
