### ISSUE TITLE
osTicket 1.10-rc3 - Client side ticket list problems

### ISSUE THREAD

**Issue by sistemasad** [osTicket/osTicket#3268]
Hello,

The client side has several bugs related to the ticket list.
The column sorting doesn't work (also the column headers don't have the sort triangle).
The "showing 1 of pagesize of total open tickets" is showing wrong values (see image attached). The total amount of tickets on the platform is used.
![image](https://cloud.githubusercontent.com/assets/7767510/16737845/76fae946-4793-11e6-807b-2297ad334a7c.png)
Also, the search seems to do nothing. No errors on log and no change on the list.

Thank you.

**Comment by kest874** [comment]
Version your using?

**Comment by ntozier** [comment]
Version of osTicket?
PHP?
Did you dump/delete tickets from the database?

**Comment by sistemasad** [comment]
Sorry, didn't paste the info:
osTicket 1.10.rc3
 Centos 6.8 64b
 mysql 5.1
 php 5.6

No, no dump or delete, just updated from rc2

**Comment by jdelhome3578** [comment]
There is still an issue with the search functionality. It does not appear that the search is getting applied.

**Comment by markus4000** [comment]
I have the same problem. 1.10
Client ticket search is not working.
Search by ticketnumber works, but not by keywords.

**Comment by markus4000** [comment]
please reopen
