### ISSUE TITLE
Open Ticket List Shows Closed Tickets Sometimes

### ISSUE THREAD

**Issue by loginid** [osTicket/osTicket#3270]
I've got this strange issue that I've searched for on the issues list but can't find a solution for or raised issue.

Hopefully someone can help me identify a solution.

Sometimes when I close tickets or delete tickets.
The tickets will still appear in the open ticket list when I go back to the ticket list.
Or sometimes when I've closed a load of tickets and I go back to the ticket list, those closed tickets will still appear in the open tickets list. 
Usually I have to close the browser and log in again to get the proper view.

I'm not sure how or why it happens, but it just happens at least once or twice a day.

Maybe something to do with sessions?  

I really have no clue.  Any help would be great!  Thank you!

**Comment by loginid** [comment]
Also I get this error a lot ; 

Unable to save draft. Refresh the current page to restore and continue your draft.

**Comment by kest874** [comment]
What version are you using?  IT sounds like your browser isn't refreshing.

**Comment by loginid** [comment]
Hi - I'm using version osTicket (v1.9.12)

Even when I refresh manually, it will not show the correct number of open tickets.
When this problem happens, sometimes I will refresh and it will show 9 tickets open.
Then I will go to "Create a new ticket" and it will show the correct open tickets.
Then I'll go back to the open tickets list and it will again show 9 tickets.
When I refresh manually it will then still show the incorrect tickets.
So I'll just have to log out, close the browser.
Log back in and it will show the correct tickets.

I really don't know what the problem is?


Thank you!

**Comment by ntozier** [comment]
Can you provide a screen shot?
