### ISSUE TITLE
osTicket 1.10-rc3 - ajax forms don't load completely

### ISSUE THREAD

**Issue by C0rn3j** [osTicket/osTicket#3277]
First off, I know this is not the support forum(I don't seem to be able to post even after confirming email on the osticket forum) and that nginx is not officially supported.

I'm not sure if this is related to PHP, the RC version, nginx or my config.

Here's my setup + the bug http://imgur.com/a/UMOJM 

This seems to happen on all tabs like this one.

Here's my nginx config(chaotic as I was trying different configs from different github issues) http://pastebin.com/KQtTDLvL

If it turns out to be my nginx config, could someone post a working one as I've only been able to find configs for version 1.9 and down?

**Comment by ntozier** [comment]
There is a NGINX thread here on github that addresses the config changes necessary for getting osTicket to run under nginx. It's long and has spanned a couple years.  Here's the link: https://github.com/osTicket/osTicket-1.7/issues/538
I think that Andrew908's comment on Nov 6, 2015 might be what you are looking for.

As far as the support forums please email me at neil at osticket dot com with the email address you used to sign up for an account and I will take a look at your account and see if I can figure out why you cannot post.

**Comment by c0rn3j** [comment]
I didn't realize that the issue spanned so far and tried working with one of the top configs, whoops.

Anyway, trying out the nginx.com recipe config or trying out @jonvargas's working config which seems to be the newest in that thread didn't work even when trying to use Andrew908's additions. 

Not sure if I should keep the conversation in this issue, the 1.7 branch #538 issue or move to the forums.

one of the issues, it's not just pop ups. 
 http://i.imgur.com/prauWEw.png

my current config
http://pastebin.com/mAB0qH72

**Comment by ntozier** [comment]
I'd recommend keeping it here.  While it can't hurt to post to the forums also, I answer most of the questions on the forums and I don't know the answer (I don't run nginx).

**Comment by c0rn3j** [comment]
http://pastebin.com/Bx45XsNJ
I almost forgot error logs. This is when I try to load domain.com/open.php to open a new ticket as a guest.
