### ISSUE TITLE
For the ticket filtering | is there a way I can only allowed existing users only to send email support?

### ISSUE THREAD

**Issue by adrianabrahamsun** [osTicket/osTicket#3279]
I want to filter emails that is not from list of customers, so only existing customer can use the email to send an issue ticket to the system.

**Comment by infectormp** [comment]
Admin Panel - Settings - Emails - Accept All Emails

**Comment by ntozier** [comment]
Coincidentally if you turn on "registration required" only existing customers can use email to send an issue to the ticket system.

see: https://github.com/osTicket/osTicket/issues/3171
