### ISSUE TITLE
Can't add new help topic. 

### ISSUE THREAD

**Issue by N-Upchurch** [osTicket/osTicket#3281]
Hi there, 

When I go to add a new help topic, I get "This request has been denied for security reasons. If you believe this was in error, please contact support." back. I'm on version 1.9.14

Any ideas?

**Comment by ntozier** [comment]
Please provide a screen shot.

**Comment by N-Upchurch** [comment]
Thanks for your response. Details to follow: 

![screenshot 2016-07-20 09 01 39](https://cloud.githubusercontent.com/assets/8893713/16989200/e4e091ba-4e58-11e6-98a6-ee5b7c4ae8fc.png)

Apache Version: 2.2.31
PHP Version: 5.5.34
GNU/Linux

**Comment by ntozier** [comment]
That does not appear to be an osTicket error.
You should consult your Apache error logs you appear to have a permissions issue.

**Comment by N-Upchurch** [comment]
Hmm, nothing in the error logs. I'll check permissions.

**Comment by N-Upchurch** [comment]
Looks like it was down to my mod_sec rules. Thanks so much for your help ntozier, it's very appreciated!

**Comment by ntozier** [comment]
Very welcome, glad to be of assistance.  :)
