### ISSUE TITLE
Long Answer custom form + print not displaying line breaks correctly (1.9.14)

### ISSUE THREAD

**Issue by mattyribbo** [osTicket/osTicket#3283]
Hi. I've discovered an issue with trying to print a ticket with a Long Answer custom form. The PDF generator doesn't seem to be recognising <br /> tags and turning them into new lines.

I'm exhibiting this issue on 1.9.12. I've upgraded to 1.9.14 and no change in the issue.

![issuewithcustomform](https://cloud.githubusercontent.com/assets/936104/17021592/e7c856e0-4f40-11e6-936a-e3c7cd2f2c1b.png)

**Comment by mfelber** [comment]
The issue you are describing was already reported: https://github.com/osTicket/osTicket/issues/2644

It is a known limitation of 1.9.x. 
1.10 will address this issue..

**Comment by mattyribbo** [comment]
A-ha. Didn't spot that issue when looking through. Thanks for the update.
