### ISSUE TITLE
Support Staff can't reply to the ticket issue email

### ISSUE THREAD

**Issue by adrianabrahamsun** [osTicket/osTicket#3284]
Hi Guys, 

Previously while i was working on this issue - https://github.com/osTicket/osTicket/issues/3279, someone advice me to disable the all email can create ticket issue and after I did that, the issue was resolved.

Now Only my registered Customers can use our web support email to create ticket to the system which is what i wanted. however new issue occured ! 

Now is my support staffs - they are unable to reply to the email ticket created by the system to support our customer directly via email and still able to record a log in the system on the customer end. 

Is there a function I need to set to get it working? please advice. Thank you.

**Comment by kest874** [comment]
Add the staff members as regular users with their email address, this issue will go away.

**Comment by adrianabrahamsun** [comment]
the issue still stays, and the ticket wasn't assigned to the staff that response... previously it was working fine.

**Comment by ntozier** [comment]
Huh?
Do you have Claim on Response checked?
Version of osTicket?

**Comment by adrianabrahamsun** [comment]
Do you have Claim on Response checked?  -- I dont understand... where to check?
Version of osTicket? -- v1.9.14 (8b927a0)
