### ISSUE TITLE
1.10-RC3 Customs forms can't disallow editing

### ISSUE THREAD

**Issue by InflamedSebi** [osTicket/osTicket#3285]
Disallow "editable" in forms don't take affect.

How to reproduce:
1. Go to forms -> users informations
2. Create a field and make it immutable (not editable) for users and agents
3. Login as user and open the profile
4. Change the field just as you like. It will be saved.

Also Agents can edit those fields without permission.

osTicket Version    v1.10-rc.3 (907ec36)
Web Server Software     Apache/2.4.7 (Ubuntu 14.04)
MySQL Version   5.5.49
PHP Version     5.5.9-1ubuntu4.17

**Comment by Exordian** [comment]
imo this is a huge vulnerability since we can not trust those fields anymore

**Comment by InflamedSebi** [comment]
more than 2 years now ...
