### ISSUE TITLE
1.10-RC3 imho Important enhancements for tasks

### ISSUE THREAD

**Issue by InflamedSebi** [osTicket/osTicket#3287]
Tasks are great, but they miss some features to make them actually usefull for us.
I know this is much stuff, but i don't want to create lots of maybe unneccessary issues.
Just tell me to move certain numbers to a new Issue and i will do so.
1. Due to tickets link their tasks, but tasks don't link to their ticket back, you should add this.
   Sometimes you need to know stuff from the original ticket or the state of the other tasks and searching for the ticket is hard if you don't have informations about it.
2. You may add an option to display all tickets under "My Tickets" you are actively involved. Not only tickets you are assigned to. So for example:
   Ticket 1 is assigned to Bob and it has 2 Tasks. One for Bob and one for John.
   As long as John has not closed his task, the original ticket will be visible under his tickets.
   But as soon as he closes his task, the ticket doesn't show up for him anymore, because he is done with this.
3. If you create a task, there should be an option to set default text. Maybe a small button next to the title, to insert the text from the original ticket title. And same for the description field. This would save a lot of time so you don't have to retype everything and just need to click the description or title or both in.
4. Predefined Task Templates is a must have.
   Lets say we have lots of user creations in the system.
   Each user needs an email account (Agent Bobs job), eDirectory/Ldap object (Johns job), phone directory entry (Bob again), workplace (Caretaker Ben), and office stuff (also Ben).
   Now I have to create 5 Tasks for each new user. Those 5 Tasks always stay the same.
   It would be nice to create a template "New User" which will automatically add those 5 predefined tasks with text and auto assign them to the Agents.
   If an Agent is in vacation mode maybe assign noone or the person creating the tasks.
5. On creation of tasks there are those 2 assignee fields "Department" and "Assignee". And imho the Department should act as a filter for the Assignee field.
   We have 2 Departements (Caretaker Service (about 100 Agents) and IT Service (about 30 Agents)) and various teams. Finding the right Agent/Team is kinda pain if Departement is not a filter.
6. This leads me to the Question: Shouldn't teams be part of an departement instead of gobal?
   Would make things much cleaner especially for bigger companies.
7. An option to auto close tickets as soon as all tasks are closed, would be awesome. Because Bob sometimes gets annoyed: he already closed his task, but John takes forever to do his task. And the Ticket stays open and open and Bob has to check continously if he can close the ticket now.
8. Users can see the ticket status and it would be nice to have a task progress for them.
   A simple "2 of 3 Tasks done." would do it. Or a list of the tasks (just the title) with their state.
9. For Tickets exists an option:
   Assigned Tickets:   Exclude assigned tickets from open queue.
   Maybe add this for tasks too.
10. Reopening tasks of closed tickets doesn't reopen the ticket. Maybe you want to know about that.

Tanks for reading.
Maybe one of the devs can do a short response on each point, because we are actively looking for a new helpdesk and osTicket 1.10 will be it if the important points are at least on the todo list.
Maybe some if this is already work in progress or already done, then tell me and i will sort that out.

**Comment by markus4000** [comment]
1.  +3
2.  +2
3.  +2
4.  +2
5.  +1
6. -
7.  as an Email "all task done" +1
8. - 
9. ? 
10.  -

**Comment by jjjeroenski** [comment]
I also want to suggest the progress of tasks.
For example bigger tasks are 50% done or 80% done.
Or Not started 0% .

Like you have for example in MS Outlook: "Task is ...% done"

**Comment by InflamedSebi** [comment]
i guess this is not changing anyway
