### ISSUE TITLE
New organization option presents empty form

### ISSUE THREAD

**Issue by crypticmind** [osTicket/osTicket#3288]
### Setup: Ubuntu xenial, nginx, PHP7-fpm

![image](https://cloud.githubusercontent.com/assets/6013514/17075725/530fb0a0-5073-11e6-9463-de451c63a46a.png)

The Company Profile -- Basic Settings panel also shows the same behaviour.

![image](https://cloud.githubusercontent.com/assets/6013514/17075729/82eb3b1e-5073-11e6-8d9e-a357306952cb.png)

I'd like to know if this is supposed to happen (I'm running straight from the develop branch). If this is not supposed to happen, how can I debug the issue? 

I also see missing fields in the "Open New Ticket" page.

![image](https://cloud.githubusercontent.com/assets/6013514/17075876/795bee86-5078-11e6-81a0-384160974945.png)

I can see I'm getting a 404 (I'm using **nginx** btw). I've already gone through the issue of $pathinfo and I can see tooltips, meaning AJAX is operational. I don't know why this URL is failing here. 

I have the best intentions of providing a PR if this is an issue I can fix.

**Comment by crypticmind** [comment]
Further investigation, I've solved the 404 in the welcome page an others (was missing a few nginx `location` directives), but the response from such AJAX calls returns this value: 

```
{"media":null,"html":null}
```

I'm assuming the main goal of this call is to retrieve the form to be presented to the user, but such form always comes null.

This takes me to this interesting NOTICE I'm seeing in PHP-FPM logs:

```
[23-Jul-2016 15:24:38] WARNING: [pool www] child 31 said into stderr: "NOTICE: PHP message: PHP Warning:  Declaration of TransferForm::render($options) should be compatible with Form::render($staff = true, $title = false, $options = Array) in /var/www/html/include/class.forms.php on line 4266"
```

**Comment by crypticmind** [comment]
I do get a form if I add a custom field, like so:

![image](https://cloud.githubusercontent.com/assets/6013514/17078820/08f507de-50d4-11e6-8310-d4f824d11534.png)

Seems to me I have an issue where osTicket is not retrieving those fields that are system-mandatory like summary and priority for a ticket, name for an organization, etc.

Any tips regarding how to troubleshoot this would be very helpful. My PHP skills are kinda rusty.

**Comment by crypticmind** [comment]
## USER ERROR

The fields I was after were disabled 😠

**Comment by Bran-Ko** [comment]
Hi, I have the same situation. But I don't have any 404 code in browser sniff. Do you have some cure for this ?

**Comment by ntozier** [comment]
@Bran-Ko 
If you do not have the 404 code in browser... then quite obviously you do not have the same problem.
This is also a closed issue.  For anyone else reading this @Bran-Ko opened this report: https://github.com/osTicket/osTicket/issues/3513
