### ISSUE TITLE
Add collaborators with API

### ISSUE THREAD

**Issue by michaeldg** [osTicket/osTicket#3291]
Hi,

According to the documentation (https://github.com/osTicket/osTicket/blob/develop/setup/doc/api/tickets.md) it is not supported to add collaborators with the API. 

Does the feature not exist yet or is the documentation not updated?

Thanks,
Michaël

**Comment by ntozier** [comment]
This seems like a question better suited for the support forums at: http://osticket.com/forum

That being said, no the API does not support adding collaborators at this time.
