### ISSUE TITLE
/support/include/class.plugin.php on line 555

### ISSUE THREAD

**Issue by gtmiller** [osTicket/osTicket#3292]
I uploaded the rc.3 to a new website no location (no upgrade going on) and when I point the browser to the site, where normally the setup script starts I get this error:
Fatal error: Only variables can be passed by reference in /hermes/bosnaweb07a/b2740/ipg.preventionitcom/prev-ticket/support/include/class.plugin.php on line 555
right at the top line of the browser with nothing else displayed (all white background).

Any Ideas as to what is causing this? Am I doing something wrong (is there a different installation procedure for the RC.3)?

Just prior to this, and on the same server (different directories of course) I installed osTicket Core, v1.9.14 and it worked fine.

Sincerely,

George Miller

**Comment by ntozier** [comment]
Web server software and version?
PHP version?

**Comment by gtmiller** [comment]
Server Information 
Configuration for www.ipage.com
CGI Active 
Document Root /home/users/web/b2740/ipg.preventionitcom 
FrontPage Extensions No 
Logs https://www.ipage.com/controlpanel/LogFiles.bml 
Platform Type Debian 
MySQL Version 5.5.44 
Perl Version 5.8.8 
PHP Version 5.3 
Sendmail Path /usr/sbin/sendmail 
Perl Path /usr/bin/perl 
PHP Path /usr/local/bin/php

**Comment by ntozier** [comment]
You need to upgrade your version of PHP.  I'd recommend either 5.5 or 5.6.  Please let us know if you still have a problem after the upgrade.

**Comment by gtmiller** [comment]
thank you :-)

------ Original Message ------

**Comment by thebravoman** [comment]
This is still occurring with 
osTicket Version	v1.10 (901e5ea) —  Up to date
Web Server Software	Apache
MySQL Version	5.5.52
PHP Version	5.6.24

**Comment by thebravoman** [comment]
This error occurs every 5 minutes and because of it I think that cron is not working and the mails are not read and tickets created from them. The line in questions is 555:

554: if ($r = dns_get_record($sig['hash'].'.'.self::$verify_domain.'.',
555:            DNS_TXT, $ignored, $ignored, true)
556:        ) {

**Comment by thebravoman** [comment]
These are the only two files with DNS_TXT

include/class.osticket.php:        $records = dns_get_record($product.'.updates.osticket.com', DNS_TXT);
include/class.plugin.php:            DNS_TXT, $ignored, $ignored, true)

Where is this DNS_TXT defined. What is it purpose?

**Comment by thebravoman** [comment]
I tracked it down to here - https://github.com/osTicket/osTicket/issues/3500

**Comment by hoover67** [comment]
The requirements page still lists php5.3 as sufficient for the latest version. I guess this is no longer true then? I'm in the process of trying to upgrade from v1.6 (don't ask) and the exact same error bit me, too. 

All the best, Uwe

**Comment by ntozier** [comment]
Q: I guess this is no longer true then? 
A: Correct.  I've asked that the page be updated some time ago.  I recommend PHP 5.6.
