### ISSUE TITLE
V1.10-RC3: Wrong Subject Title Variable when creating tickets

### ISSUE THREAD

**Issue by C4RLOCO** [osTicket/osTicket#3295]
When creating a ticket on behalf of a customer/client, the system overwrites the given Ticket Subject   with the text contained in the variable for "Help Topic".

**Comment by C4RLOCO** [comment]
@greezybacon I need your help on this one as this is creating a havoc in our system with the new tickets created.. Thanks!

I also noticed that the issue happens when a customer creates a ticket, the system is basically giving the wrong subject title by overwriting it with that on of the help topic selection

**Comment by C4RLOCO** [comment]
Anyone?

**Comment by C4RLOCO** [comment]
@greezybacon @protich any thoughts?

**Comment by ntozier** [comment]
I am not able to replicate this report on my 1.10rc3 test systems.  
You're running the version that is downloadable from osticket.com/download?

**Comment by C4RLOCO** [comment]
Hey @ntozier thanks for the help. I did download the version from osticket.com/download but after that I remember updating the directory with the latest commits on https://github.com/osTicket/osTicket/commits/develop


I'm going to give it another try on a new directory in my server starting with the baseline version I guess.

**Comment by C4RLOCO** [comment]
@ntozier thank you for your comment as I reloaded the files without adding the commits and that solve my issue. I guess I will try to load the commits individually to see which one is affecting the ticket title.

Closing this issue... :)
