### ISSUE TITLE
V1.10-RC3: Set agent password without function

### ISSUE THREAD

**Issue by realtarget** [osTicket/osTicket#3296]
It's not possible to reset the password of an agent except the users own password.

v1.10-rc.3-12-g55dc25a (55dc25a)

![resetpw](https://cloud.githubusercontent.com/assets/4380964/17247246/35190c58-5592-11e6-92f0-56b17d488a0c.JPG)

**Comment by ntozier** [comment]
I see the same thing in the download version from osticket.com [Version: v1.10-rc.3 (907ec36)].

Clicking the Update button however does generate an email to the person, so perhaps the devs removed the way to set the password manually.

**Comment by C4RLOCO** [comment]
Also confirming the issue above in our environment v1.10-rc.3 (907ec36)

**Comment by FaserF** [comment]
Same problem still persists.

**Comment by JediKev** [comment]
@FaserF @C4RLOCO @realtarget Uncheck the box and you'll get a section to fill out your own password for them. 👍

**Comment by husseinsheikh** [comment]
I am using  v1.11.0-rc1 and when i reset the password, it shows the blank white page and doesn't get any emails?

**Comment by ntozier** [comment]
@husseinsheikh this thread does not appear to be the same issue that you are reporting.  You should probably start your own thread and include your system environment details.

Side note a "blank white page" usually means a PHP error.  Please consult your error logs and post the error that you are getting in your issue report.
