### ISSUE TITLE
[v1.10-rc.3] Warning in include/class.forms.php

### ISSUE THREAD

**Issue by Sorok-Dva** [osTicket/osTicket#3300]
Hi all,

I met two warnings today after moving my inetpub folder in another hard drive disk.

`PHP Warning:  Declaration of AssignmentForm::render($options) should be compatible with Form::render($staff = true, $title = false, $options = Array) in D:\inetpub\wwwroot\support\include\class.forms.php on line 4146`

`PHP Warning:  Declaration of TransferForm::render($options) should be compatible with Form::render($staff = true, $title = false, $options = Array) in D:\inetpub\wwwroot\support\include\class.forms.php on line 4266`

I tried to install from beginning ostickets but still have the same warnings... And my end users can't access to the support due by those warnings

I'm running on a Windows Server 2012 R2, with PHP 7

Regards,

**Comment by kest874** [comment]
PHP 7 is the issue, use 5.6

**Comment by Liightman** [comment]
This problem came with the modification of the osticket folder. Yesterday I was running with PHP 7.0 and i didn't have this problem...
And since I move inetpub from C hard drive disk to D hard drive disk, i've this problem.

I've obviously configurate my php.ini for this modification

**Comment by ntozier** [comment]
1.10RC3 is a Release Candidate and should not be used in a production environment.  If it worked where it was before you can move it back until you can figure out what is different between the two locations.  It would be as simple as something like your webserver doesn't have permission to access the files or said location the a same way.

**Comment by ntozier** [comment]
update 1.10 final
Forum user is still reporting this as a problem
http://www.osticket.com/forum/discussion/89095/v1-10-php-7-warning
