### ISSUE TITLE
I want to automatically login my clients from my user interface (HTML form) into osticket system

### ISSUE THREAD

**Issue by jOthman** [osTicket/osTicket#3301]
I want to automatically login my clients from my user interface (HTML form) into osticket system. 
In the attachment you can find my UI (login.html), I make a form with method post, and I copy the same names for the variables from login.php, and the names are (Username: luser) and (Password: lpasswd).

I have done the same thing for Agents login, and it worked just fine. I think the problem is that Client login is front-end, while Agent login is back-end login.

I would be thankful if anyone helps me ASAP.

Best Regards,
Othman
[login.zip](https://github.com/osTicket/osTicket/files/397685/login.zip)

**Comment by jOthman** [comment]
I have my user interface as a separate HTML file.

**Comment by C4RLOCO** [comment]
Hi @jOthman 
I believe your post is more appropriate for a forum. Github is for reporting issues related to osTicket releases. Your post above does not sounds like a bug to me.
