### ISSUE TITLE
Cant send alert and messages to external mail

### ISSUE THREAD

**Issue by brajerry** [osTicket/osTicket#3303]
I can only send emails with @mydomain.com

**Comment by ntozier** [comment]
While I appreciate that you took the time to file a bug report, I feel like perhaps this sort of thing may be better suited for the support forums.  http://osticket.com/support

Also please help us to help you by reading and following the posting guidelines located in this thread: [Please read before requesting assistance](http://www.osticket.com/forum/discussion/77765/please-read-before-requesting-assistance#latest).  The more information you give us the better we will be able to assist you. Thank you.

Version of osTicket?
Are you using PHP Mail or SMTP?
Email settings?

**Comment by brajerry** [comment]
osTicket (v1.10-rc.3)
Am using smtp with my mail server's ip and port number 25.
I can send email and alerts to users with mail@mydomain.com but cant send mail to users with other domains like gmail, yahoo, outlook etc

**Comment by ntozier** [comment]
**blink blink**
So you are saying that when osTicket sends and email to *@google.com (etc) that those users are not getting the email and it is not in their spam box?  Does your mail server allow relaying?

**Comment by brajerry** [comment]
Yes and my server allows relaying

**Comment by brajerry** [comment]
When I even try the diagnosis in the osticket mail setting i get an error message. "Mail error" in my log files but it always successfull with *@mydomain.com

**Comment by ntozier** [comment]
This does not sound like it is osTicket related to me. Whats the error in your mail logs?

**Comment by brajerry** [comment]
Error sending messege no additional information

**Comment by C4RLOCO** [comment]
@brajerry check with your hosting company. I had a similar issue in the past and the hosting company had to "reset" they email setting.. after they did that all emails and alerts were successfully sent.

Hope it helps!
