### ISSUE TITLE
1.10-rc3 Duplicate user - same email, different name

### ISSUE THREAD

**Issue by chucks26** [osTicket/osTicket#3304]
Hi to all,

as always, sorry for my English...
I noticed a strange issue...my system is configurated with no registration and with the ability to open tickets for guests. As axpected, when a user submit a ticket for the first time, enters name, mail and other required fields, system create a new user. Second time, if he enter the same email, no matter what he specifies in the "name" field, system recognizes user and associate the ticket with data of the "first" user...OK, I think this is the way Osticket is intended to work...

Strange things now....If I insert a new user manually (agent panel) before that user create a ticket, when the user will create one, system will pick up user data insereted by agent.
Instead, if I IMPORT user from copy/paste or CSV files, when a user will fill up a new ticket (using a mail alredy imported), system will create another new user with the same email...I'm really sure that email is the same!

Any hint?

Thank you,
Chuck26

**Comment by ntozier** [comment]
osTicket displays the first name that it finds.  You ought not have added a second user with the same email address.  The system is supposed to prevent two users with the same email address.

**Comment by chucks26** [comment]
Ok, right!

But...In a clean user list, if I add (via import) a new user with name "Abc" and email "abc@abc.it" and than an user (via web form) create a new ticket using "Cde" as name and "abc@abc.it" as email, system will add another user (with 2 different names, but same email). I supposed system will use the previous insered user, but it doesn't!
Should be working this way?

Thank you,
Chuck26

**Comment by chucks26** [comment]
Ok, solved!

There were some problems in spaces after the commas in the import window.

I've tried to insert data in format:

> name, email
> Name1, abc@abc.it

the space after the comma made the trouble.

Without it everything worked great!

Thank you as always for the patience and support.

Chuck26
