### ISSUE TITLE
Deny Changing of Email and Name

### ISSUE THREAD

**Issue by orkun1675** [osTicket/osTicket#3305]
Because I am creating user accounts for every customer that signs up on our main site using SQL (there is no API for user creation as far as i know), I don't want the customers to change their name and email address on the osTicket system and have a mismatch with the main site.

How can I prevent users from accessing the Account Information section in the profile page? (changing their password is completely fine)

I tried hiding or disabling the input fields here but a capable user can find a workaround this way.

Thanks for the help.

**Comment by wfoster** [comment]
What version OST are you on?

**Comment by ntozier** [comment]
Q: How can I prevent users from accessing the Account Information section in the profile page?
A: You cannot prevent them from accessing their account information.... it is THEIR account information.

Also you can create users by importing them.. by going to Agent panel -> Users.
