### ISSUE TITLE
Terms&condition at ticket printing

### ISSUE THREAD

**Issue by shiko2009** [osTicket/osTicket#3311]
Hello 
i want to make some terms and conditions to be printed at any ticket 
i have tried to make custom forms and fields with long answer or information with no luck 
it can't be rendered while printing tickets 
how to do that 
if you like to help me via team viewer i am ready for that 
thanks for all

**Comment by shiko2009** [comment]
Any help please

**Comment by robintoy** [comment]
Dont think the system has the ability for this at the moment.....

But thinking outside the box you could edit your html response templates to include a link to your T&C listed on your website?

**Comment by shiko2009** [comment]
When i recieve a device from any customer i give him copy of ticket which includes status of device..serial num...model...etc 
I just need these T&C to be printed at the same ticket.. These T&C cosists of 15 lines that should be visible to the client before signing on the ticket
Here's a photo to detail my problem

**Comment by shiko2009** [comment]
![4f982bc2-aa7a-11e5-891d-67885ce8ab3c](https://cloud.githubusercontent.com/assets/16225171/17630291/51ac4c3c-60c7-11e6-8412-799276181ee4.jpg)

**Comment by ntozier** [comment]
Couldn't you just use a canned response?
Then print the ticket.

**Comment by shiko2009** [comment]
i did that but it just print it at a new page .. please consider that i print 2 copies from ticket so every ticket will be printed at 4 pages which is not suitable for me 
i just want to advantage free spaces at the paper and print all what i need at 1 paper is that possible to do ?

**Comment by ntozier** [comment]
Tickets can vary from 2 pages, to 20+ (My highest is only 19 pages) so I have no idea why this solution wouldn't work for you...

**Comment by shiko2009** [comment]
i just don't like ticket style i need my ticket in one page and there's alot of wasting space on the paper why we could't use it ? 
i used to create tickets with isolsoft support center which allowed me to customize my ticket and put alot of options on the same page and print it in one page but now i can't get this script again

**Comment by ntozier** [comment]
Then it sounds to me you will need to write your own PHP print script to pull the data that you want, and format it the way you want, and to add the verbiage you want.

**Comment by shiko2009** [comment]
is that possible ? 
and how to do that ?  how much does it cost ?

**Comment by wfoster** [comment]
It is a system capable of accomplishing tasks by using the features built into it.
Anything more than those features you will need to develop and implement yourself.
Your other option is going through the MODS to see if somebody has already found a solution that you can implement http://osticket.com/forum/categories/osticket-1-9-mods
You could possibly find a freelance PHP/SQL developer and pay them to do it. At your own risk obviously.

**Comment by shiko2009** [comment]
Great
Thank you wfoster 👍
