### ISSUE TITLE
RFC v1.10-rc.3-12: SMTP Credentials for transactional email providers (Mandrill)

### ISSUE THREAD

**Issue by realtarget** [osTicket/osTicket#3312]
Unfortunately it's not possible to configure a separate provider for inbound and outbound email.

Due to the fact that the amount of companies which use transactional email services (eg. Mandrill, Mailjet, Mailgun) is rising this should be implemented asap.

![smtp-credentials](https://cloud.githubusercontent.com/assets/4380964/17616317/3690642c-6074-11e6-880f-0bf800ca15d9.JPG)

**Comment by poxin13** [comment]
Would like to see this, transaction email service are great (mailgun / sparkpost)

**Comment by loginid** [comment]
Yes I agree this should be implemented, especially as transactional email services are how the big companies process email now (25% of non spam email goes through sparkpost now!).

**Comment by pengc99** [comment]
also looking for API support for transactional mail services - I am a Mailgun user.
