### ISSUE TITLE
osticket 1.9.14: loading ticket hangs on opening

### ISSUE THREAD

**Issue by nitroflow** [osTicket/osTicket#3316]
After upgrading from a previous version to 1.9.14 the loading bar gets stuck(as depicted below) and I have to reload the page for the ticket to open. This behaviour happens on the hosted server. However, this does not happen on a local xampp installation with an imported database or on the hosted server with a fresh installation.

![Image of the issue](https://lh3.googleusercontent.com/gT5shirVXBwHz9DUBOMHJcSctn7SxFdtZisHrsKaw4_aY77_dlfKDtLuvuON14DIZje8c3ITvAey_IzbE1IOadV2druAusmyO1J7dAn2aVKa1Wv_7oNWJvx8_4D-dN2_sZDeQPCdtRF0ThKCWds5GIlhVitifredIH8aBqvjby3QNkzyWiGOj19pmbUO4SLM80-y0KYg8SwgEEiDLVx2QdUuJkEVj4LGX2IrYzrAeV8iomDastuORwfO6F8ayt_b3-DaTKfVD5xvHdMbkptaNjG75ciH1Nh-1pGeG-89Gu5QGZ0Qtk0X-7Uu16E-iVvrkv7jCRicMF2rH4FiSm5L683PQubk7nS_mrkemWEo-aeZls4r_yHlziT_xMsJGgJ91LoclNigJOwbPtLXet8dD77P5xfjQ7SsBR-rxWBzTy6MzEsfkGZa40W_CT5_CkOI5RCVe5IuZNOo5QsZ1cx8o1vv3jhXxlYMUtA25KTFFDi8VJQCVeLvtD_1R2u-uI7YUfNi4nleathZ2RbQkV8g1jCG4b8E-8OKROyTUw2Pbyl1N7grG9uYCieuh4YpsazEhPymqTfU2fMB_vIXlexQTQQ_J5nttA=w1280-h138-no)

**Comment by ntozier** [comment]
Previous version?
Have you checked to see what the actual error is?  It's usually a javacsript or AJAX issue.

see also: 
https://github.com/osTicket/osTicket/issues/1362

**Comment by nitroflow** [comment]
I'm not sure on the previous version as the person that performed the upgrade is on vacation, but there's no anchor, the url only changes to "/scp/tickets.php?id=XXXX" from "/scp/tickets.php". This also doesn't explain why it works on a local server but not on the hosted server, or why it works on the hosted server with a clean install.

There are some javascript errors caught on firefox console but I'm no javascript developer so I don't have a clue how to fix them or even if they are relevant.

`SyntaxError: missing : after property idtickets.php:410:38
SyntaxError: missing : after property idtickets.php:485:38
A opção getPreventDefault() foi descontinuada. Em alternativa, utilize defaultPrevented.jquery-1.8.3.min.js:2:40351
Este site aparenta utilizar um efeito de posicionamento scroll-linked. Isto pode não funcionar bem com panning assíncrono; veja https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects para mais detalhes e para se juntar à discussão de ferramentas e funcionalidades relacionadas!tickets.php
SyntaxError: missing : after property id
.globalEval/<()
jquery-1.8.3.min.js:2
.globalEval()
jquery-1.8.3.min.js:2
.domManip/<()
jquery-1.8.3.min.js:2
.each()
jquery-1.8.3.min.js:2
.domManip()
jquery-1.8.3.min.js:2
.append()
jquery-1.8.3.min.js:2
.html/<()
jquery-1.8.3.min.js:2
.access()
jquery-1.8.3.min.js:2
.html()
jquery-1.8.3.min.js:2
pjax/options.success()
jquery.pjax.js:271
v.Callbacks/l()
jquery-1.8.3.min.js:2
v.Callbacks/c.fireWith()
jquery-1.8.3.min.js:2
T()
jquery-1.8.3.min.js:2
.send/r()
jquery-1.8.3.min.js:2
jquery-1.8.3.min.js:10:38
`

**Comment by nitroflow** [comment]
Turns out the problem is caused by the use of pt_PT language pack. This is the same as http://osticket.com/forum/discussion/80195/ticket-view-freeze-during-open-a-ticket

**Comment by nitroflow** [comment]
Turns out the problem is caused by the use of pt_PT language pack. This is the same as http://osticket.com/forum/discussion/80195/ticket-view-freeze-during-open-a-ticket

I've applied the same fix and now it works.
