### ISSUE TITLE
Osticket RC3 Ticket with 100+ Tasks is crashing.

### ISSUE THREAD

**Issue by philbertphotos** [osTicket/osTicket#3317]
We have a few tickets some hitting 100+ tasks and it crashes. I included a flash video to illustrate the problem.
[Ticket issue_sm.zip](https://github.com/osTicket/osTicket/files/431699/Ticket.issue_sm.zip)

**Comment by wfoster** [comment]
Is the task created if you log out log in?
Do all your browsers respond this way?
What happens if you ctrl+F5 to refresh the browser?

Are you using RC for live production?

**Comment by philbertphotos** [comment]
Refreshing does not work it happens exactly the same on every browser.. 
I have been using the 10 RC2 and now 3 in a product environment

**Comment by wfoster** [comment]
Is it right for me to assume that you are new to OSTicket?
RC (Release Candidate) should be used in testing environments unless you can put up with bugs, manual fixes and waiting for the upgrades
Have RC3 configured in 5 different setups and all are giving problems with the 'Tasks' module.
Best advice i can give you is to be patient while RC is in development.

**Comment by philbertphotos** [comment]
No i am a veteran and created my own plugins for it and a PHP developer.
I am fully aware about the RC status and decided it was stable enough to run in production. The task module only became a problem with tasks assigned to one ticket hits about 100.

**Comment by wfoster** [comment]
If I can recreated your issue then i will  see if I can help resolve. Like I said I have yet to experience tasks successfully working in RC3

**Comment by wfoster** [comment]
In your personal opinion, which is more stable for production environments between RC 2 / RC 3?

**Comment by philbertphotos** [comment]
RC 3 by far...

**Comment by philbertphotos** [comment]
I would appreciate the help

**Comment by philbertphotos** [comment]
This has been fixed in v1.12.2
