### ISSUE TITLE
1.10 RC3 + PHP 7: Ticket and Task Settings: No "Config"-button for attachments, tabs not working and no "Save"-button

### ISSUE THREAD

**Issue by Af0x** [osTicket/osTicket#3319]
Hello,

reffering to 1.10 rc3 there is no "save"-button under Admin Control Panel -> Settings -> Tickets

Also the tabs "Autoresponder" and "Alerts and Notices" don´t seem to be functional.

Edit: Additionally "Ticket Attachment Settings" (bottom of the settings-tab) don´t seem to work/give any options.

Regards,

Af0x

**Comment by ntozier** [comment]
I have to disagree with all your statements.

![tickets](https://cloud.githubusercontent.com/assets/1315768/17933590/af4ca5d4-69e2-11e6-9a50-2bd1547323e1.png)

autoresponder tab
![autoresp](https://cloud.githubusercontent.com/assets/1315768/17933599/b89e9f5c-69e2-11e6-82e9-616a2644e6b6.png)

Alerts Tab
![alerts](https://cloud.githubusercontent.com/assets/1315768/17933605/c1bac1ec-69e2-11e6-895d-5d9c5fba2b36.png)

Attachment settings
![attach](https://cloud.githubusercontent.com/assets/1315768/17933615/c7ee5862-69e2-11e6-99e8-e5159d3ef006.png)

It sounds like you have a lot of issues.  You may want to re-download osticket.com/download and then re-upload the core files to make sure that they all stock.  You may also want to post more information about your system (such as webserver and ver, PHP ver, etc.).  See Admin panel -> Dashboard -> Information.

**Comment by Af0x** [comment]
hi, I´m using PHP 7.0.10 with PHP-FPM on Debian Jessie. Webserver is Apache 2.4.10.

**Comment by Af0x** [comment]
I added PHP 7 to the title, maybe someone can confirm this?
again the question to @ntozier : what PHP-Version is used on the screens?

**Comment by ntozier** [comment]
I run PHP 5.6.12 currently

**Comment by Af0x** [comment]
thanks, how long does it usually take to fix an issue like this? currently I´m stuck and can´t go on testing/setting up.

**Comment by Af0x** [comment]
After more researching I think that this Issue is related to the "Config"-button for attachments as this problem also exists within the Tasks-Settings (No Save-Button, tab not working, no "Config"-button for attachments). Plus loading this specific pages seems to be "stuck", as the red "loading bar" (I don´t know how to call it) on the top does not finish and gets stuck at circa 80%.

**Comment by jjjeroenski** [comment]
Ubuntu 16.4 with PHP7 running osticket v1.10-rc.3 (907ec36) 

Apache/2.4.18 (Ubuntu)
Mysql 5.7.13
PHP version 7.0.8-0ubuntu0.16.04.2

and I have the save button:

![image](https://cloud.githubusercontent.com/assets/671920/18129671/05fe0c70-6f8c-11e6-8704-bd15e7f00992.png)

also settings page works:

![image](https://cloud.githubusercontent.com/assets/671920/18129700/2e97ebce-6f8c-11e6-8ca5-842bcb6acd75.png)

![image](https://cloud.githubusercontent.com/assets/671920/18129713/3d863ba4-6f8c-11e6-9193-41ea1dcc5d19.png)

![image](https://cloud.githubusercontent.com/assets/671920/18129722/4bd7e432-6f8c-11e6-9e80-92d76b5e2e04.png)

**Comment by Af0x** [comment]
thanks for checking. I checked a different browser and it still appears.
Maybe [this DB Error](https://github.com/osTicket/osTicket/issues/3326) is the cause of all that. I started with a fresh 1.10rc3.

**Comment by Af0x** [comment]
ok guys, I worked around this issue by first installing Version 1.9.14 and then upgrading from there to 1.10rc3. now things look quite good. I went back to PHP 5.6 and after upgrading I put php 7 back in place.
btw: I also tried a fresh install of 1.10rc2 which was not successful either.

**Comment by m-terlinde** [comment]
Hey guys,

I've got the same problem with the actual stable version:
osTicket-Version 	v1.10 (901e5ea) — Up to date
Server-Software 	Apache/2.4.18 (Ubuntu)
MySQL-Version 	5.7.12
PHP-Version 	7.0.8-0ubuntu0.16.04.3

I've installed all PHP extensions. I get the DB Error # 1146 and DB Error # 1064 aswell. (like ref #3326)

Kind regards,
Matthias

**Comment by MatthieuBarbu** [comment]
Hello,

I've got the same problem with the actual stable version:
osTicket-Version v1.10 - stable
Server-Software Apache/2.4.25 (Debian)
MySQL-Version 10.1.26-MariaDB (Debian)
PHP-Version PHP 7.0.19-1

I've installed all PHP extensions. I get the DB Error # 1146

Anyway, thanks for your concern

**Comment by ntozier** [comment]
If you are installing with a language pack under PHP 7.0 try downgrading to 5.6, or install with out the language pack and add it later.

see: https://github.com/osTicket/osTicket/issues/3326
