### ISSUE TITLE
Email not sent to Team on task Creation (1.10RC3)

### ISSUE THREAD

**Issue by ipAnything** [osTicket/osTicket#3320]
If I create a Task and assign it to a Team, The Team members do not receive the email that a Task has been assigned to them. The Team has the members marked to get notices.

If I go to Settings > Tasks > Alerts & Notices
1) **New Task Alert** does not have the option to select **Assigned Agent / Team**
2) **Task Assignment Alert** has **Assigned Agent / Team** as a choice, so I would expect that once I am assigning a Team or an Agent on Task Creation, then they should get a notification that a Task was assigned to them, but this is not happening.

Is this not the desired intention?

Is there a fix for this?

**Comment by wfoster** [comment]
So I have RC3 setup on 5 different OS.
Seems like the task module does not work correctly on any of them and all give very similar issues.
Notification issues, display issues and calling from the DB sometimes errors out.

Are you using the RC in a live production environment?

**Comment by ipAnything** [comment]
Yes I am, Tasks was one of the reasons why I moved to 1.10 RC3.

Several people claimed that the system is stable enough to use in a Production Environment and being gang we are implementing osTicket it made more sense to use the latest version with the newest features.

We have not encountered much issues. More things that we would expect to work differently.

The Tasks is what does not seem to be working as it should.

**Comment by wfoster** [comment]
I think they use RC3 on the hosted solution by the looks of it.
Maybe create a free account there and test. If it is working there then surely should be working by us.
I just don't have the time right now to trouble shoot though

**Comment by ntozier** [comment]
I dont think its stable enough to use in production personally.  I also don't use the hosted solution though.  I personally think of RC's as beta software.

**Comment by wfoster** [comment]
Could not agree with you more @ntozier Youthink of it as beta and osTicket specifically call it a beta release. Not very wise going live with it. Wonder if online has any issues with their release? Do you know if the community source code is behind on development to the live code? just out of interest

![image](https://cloud.githubusercontent.com/assets/7644638/18256375/ec9d0704-73b4-11e6-8a81-6e7295d13477.png)
