### ISSUE TITLE
Field of visibility not changeable after created 1.10 RC3

### ISSUE THREAD

**Issue by suportgc** [osTicket/osTicket#3321]
Hello good afternoon.

I need your help.

I still can not understand why my fine field caught .

Not being possible to edit after creation.

Follow gif exeplo .

![field of visibility](https://cloud.githubusercontent.com/assets/19677143/17938354/faacd1d4-69fb-11e6-84fd-616ed0c65fc2.gif)

**Comment by ntozier** [comment]
Well its not in English, but I would say that those fields are required by osTicket and cannot be edited.  There aren't very many of those so I would guess that it is Task Details, the Title (Email Subject) and Description (Email body) fields.

**Comment by suportgc** [comment]
Hi ntozier.
I am Brazilian and I use the Portuguese .
However , the error occurs in any field.
If you create a new field, after creating it gets blocked.

![field of visibility 2](https://cloud.githubusercontent.com/assets/19677143/17939632/ea081cde-6a01-11e6-80a4-0fcc25536cfb.gif)

**Comment by ntozier** [comment]
I see the same behavior.

**Comment by suportgc** [comment]
This error is being presented only 1.10 RC3

In 1.10 RC2 not exist.

**Comment by wfoster** [comment]
The functions are still available but using it is a bit different i believe
Press the config button next to your variable type field.
Then go to the permission TAB

![image](https://cloud.githubusercontent.com/assets/7644638/18217821/46dd3340-715f-11e6-89f4-d19767487abb.png)

**Comment by suportgc** [comment]
Hello .. Good evening.

Thank you for help.

It was of great help.

Sorted out.
