### ISSUE TITLE
Intermittent Invalid CSRF Token __CSRFToken__ warnings and internal server error 500 when user and agent login

### ISSUE THREAD

**Issue by ruminate428** [osTicket/osTicket#3323]
Hello Everyone,

I have just implemented v1.9.14 with the only plugin being LDAP authentication on apache 2 running ubuntu 12.04 server.

When agents or end users login they sometimes get a long wait and it will not allow them to login, this gives them an error 500 page.

Sometimes when refreshing and quickly clicking on login it lets them through or gives them an Invalid CSRF Token **CSRFToken**  error.

I do not know what is causing this but it is a major issue for end users and agents alike.

Thank you.

**Comment by jjjeroenski** [comment]
We had almost the same problem with last installation, also that "500 pages" and sometimes the "CSRFToken error".
Please check this post: https://github.com/osTicket/osTicket-plugins/issues/105

**Comment by ruminate428** [comment]
After trying the above fix I am no longer receiving "CSRFToken error" but the login still hangs from time to time and give an error 500.

**Comment by ruminate428** [comment]
Is anyone else having an issue similar to this?
