### ISSUE TITLE
v1.10-rc.3 (907ec36) upload/insert screenshots in ticketes: DB error

### ISSUE THREAD

**Issue by jjjeroenski** [osTicket/osTicket#3325]
See error below after upgrading to v1.10-rc.3 (907ec36) - latest version.
Running on Ubunut 16.4 - Apache PHP7

If you paste a screenshot directly in the ticket form, sometimes it works sometimes not. (strange...)
For example if you try 4/5/9/... times --> error and the 5th (6/7/...) time (the same picture in the same ticket) it works.
![image](https://cloud.githubusercontent.com/assets/671920/18000397/23bd1d94-6b7e-11e6-904c-2f0732de07f4.png)

Everytime it doesn't work for pasting, you get this error in the logs:

`[INSERT INTO`ost_attachment`SET`file_id`= 123,`type`= 'D',`object_id`= 297,`name` = 'screenshot-pIjk'] Duplicate entry '297-123-D' for key 'file-type'

 ---- Backtrace ----
 #0 (root)/include/mysqli.php(204): osTicket->logDBError('DB Error #1062', '[INSERT INTO `o...')
 #1 (root)/include/class.orm.php(3121): db_query('INSERT INTO`os...', true, true)
 #2 (root)/include/class.orm.php(596): MySqlExecutor->execute()
 #3 (root)/include/class.attachment.php(161): VerySimpleModel->save()
 #4 (root)/include/ajax.draft.php(101): GenericAttachments->upload(Array)
 #5 (root)/include/ajax.draft.php(300): DraftAjaxAPI->_uploadInlineImage(Object(Draft))
 #6 (root)/include/class.dispatcher.php(145): DraftAjaxAPI->uploadInlineImage('297')
 #7 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('297/attach', Array)
 #8 (root)/include/class.dispatcher.php(120): Dispatcher->resolve('297/attach', Array)
 #9 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/draft/297/atta...', NULL)
 #10 (root)/scp/ajax.php(262): Dispatcher->resolve('/draft/297/atta...')
 #11 {main}
`

If you add normal attachments to the ticket form without copy/paste, it works normal.
So this is ok:
![image](https://cloud.githubusercontent.com/assets/671920/18000366/e5b7bcb6-6b7d-11e6-8aa7-d5c7868aca5a.png)

There are already people posting this problem, but it was with older versions and combination ticket with other problems, this is an isolated problem, no other errors.
Upgrade also without any problems or errors.

I have backup and restore point, so that's not the problem.

**Comment by ntozier** [comment]
Thanks for reporting this.  While I do not have a solution for you what I do to work around this is only use the "insert image" (box with mountains) at the top of the WYSIWYG editor.  I've never had an issue using that, but drag and drop the image seems kinda horrible.

**Comment by jjjeroenski** [comment]
Same issue when inserting screenshots (copy/paste) in the task window.

**Comment by vieckzand** [comment]
I have same issue when copy paste image (screenshots) in tickets details, sometimes it work but sometimes not

**Comment by xeir83** [comment]
The image can be pasted if nothing else has been written in the response window. (If the picture is pasted before you write something, it will be pasted). If you paste after writing something the Italic symbol will be marked. Unmark it and you  will be able to paste it.

**Comment by ntozier** [comment]
interesting.  I'll have to test that,

**Comment by SotoDucani** [comment]
Just adding my +1 to this, encountered while attempting to paste in a screenshot from my clipboard in the ticket response. My DB Error and Backtrace matches jjjeroenski's near exactly.

![image](https://cloud.githubusercontent.com/assets/8963875/21732821/6ea6b248-d429-11e6-95f8-a2036d002ee3.png)

**Comment by jjjeroenski** [comment]
also solved when upgraded to the last version.

![image](https://cloud.githubusercontent.com/assets/671920/25665889/35506dac-301f-11e7-8d77-561c1868bbd9.png)

**Comment by xeir83** [comment]
@jjjeroenski What did you upgrade to last version? Im running the same version of osTicket as you but still having this problem. I have noticed that if i have written something in the box i will be able to paste the image if i do not use linebreak/return. If i paste the image directly on same row, it will work.

![image](https://cloud.githubusercontent.com/assets/20067631/25697040/c25a3166-30b9-11e7-9f57-84164ca1864b.png)

**Comment by xeir83** [comment]
Just a note regarding response window. When pressing return/enter. A linebreak isn't always inserted. Im not sure if this has something to do with the image pasting. But i have noticed that if you don't press Enter/linebreak the image will be pasted without any error.
