### ISSUE TITLE
Question: Response to client of ticket and notify to another departament

### ISSUE THREAD

**Issue by lsfiege** [osTicket/osTicket#3327]
Hello!
It's possible to respond to a client in ticket and report that response to another department/team? (besides having notified the responsible department)

Greetings!

**Comment by ntozier** [comment]
I do not believe that this is a feature of osTicket at this time.  
Well unless you add someone in said department (or a mailing list) as a collaborator.

**Comment by lsfiege** [comment]
Thanks!
