### ISSUE TITLE
Showing FAQ results in fatal error

### ISSUE THREAD

**Issue by martin-rueegg** [osTicket/osTicket#3328]
When navigating to `/scp/kb.php` a fatal error is caused (probably depending on the data):

`Fatal error: Call to a member function sort() on array in /include/staff/faq-categories.inc.php on line 147`

**Comment by ntozier** [comment]
Version of osTicket?

**Comment by robintoy** [comment]
I would guess he means v1.10-rc.3 as we experience this and have jumped back to rc.2

**Comment by martin-rueegg** [comment]
Sorry @ntozier, I forgot to post that information. Actually, I was running off the development branch (which might be a bad idea, of course). ;-)

patch will follow.

**Comment by martin-rueegg** [comment]
btw: https://github.com/protich/osTicket/commit/0a06ab7810e76accd4745dda03680bd351b45c70 is a similar fix like mine #3331

**Comment by martin-rueegg** [comment]
any comments on the fix? #3331 
ping @protich, @greezybacon

**Comment by jdelhome3578** [comment]
Fixed #3216
