### ISSUE TITLE
Print to PDF output can't find any pictures

### ISSUE THREAD

**Issue by jjjeroenski** [osTicket/osTicket#3330]
Problem about version: v1.10-rc.3 (907ec36) - latest version.
Running on Ubuntu 16.4 - Apache PHP7

If you have tickets with inline pictures (screenshots) and you want to print out (PDF - "print ticket tread") --> header and inline pictures are gone, only a read square.

It looks like he can't find the images.

![screenshot pdf](https://cloud.githubusercontent.com/assets/671920/18088312/4cb2cd72-6eba-11e6-929e-b51cdc75e8b7.JPG)
![ticket printout header](https://cloud.githubusercontent.com/assets/671920/18088329/65484808-6eba-11e6-91e8-7e782b6aa2f2.JPG)

Somebody with the same problem on version v1.10 RC3 ?

I moved from one server to another, not only with old moved tickets, also with new ones.

**Comment by Af0x** [comment]
hi, unfortunately I can´t check because my system is blocked by bugs.
As you are using PHP7, can you please check out [this Issue](https://github.com/osTicket/osTicket/issues/3319) and maybe confirm it?

**Comment by wfoster** [comment]
Are you still experiencing all those DB errors from your earlier posts?
I think you may want to fresh install. I am running latest and no problem.
Multiple OS and multiple browsers. All work fine. I do have an issue inserting the imagine inline but for the most part the pdf output does print as expected.

The red 'X' is normally picture does not exist. In your 'admin panel' have you selected to save attachments to DB? Could be the culprit. It is checked off by default

**Comment by jjjeroenski** [comment]
The "save attachments" is configured like this: 
![saveattachments](https://cloud.githubusercontent.com/assets/671920/18241095/a50823b6-734f-11e6-93df-e3120a5adb44.JPG)
Or do you mean another setting?

DB errors only sometimes when using inline copy paste screenshots in posts. No other DB errors left.
What issue do you have @wfoster when you are inserting inline pictures, same like in my other post https://github.com/osTicket/osTicket/issues/3325?

**Comment by wfoster** [comment]
I am have the issue that you experience with having to insert multiple times before it responds to the action. Could you post the database errors for inline copy and paste that you are getting?

**Comment by jjjeroenski** [comment]
@wfoster , even it is another topic, i will answer your question here:

> INSERT INTO `ost_attachment` SET `file_id` = 131, `type` = 'D', `object_id` = 298, `name` = 'screenshot-Abe5'] Duplicate entry '298-131-D' for key 'file-type'
>
> ---- Backtrace ----
> #0 (root)/include/mysqli.php(204): osTicket->logDBError('DB Error #1062', '[INSERT INTO `o...')
> #1 (root)/include/class.orm.php(3121): db_query('INSERT INTO `os...', true, true)
 >#2 (root)/include/class.orm.php(596): MySqlExecutor->execute()
 >#3 (root)/include/class.attachment.php(161): VerySimpleModel->save()
 >#4 (root)/include/ajax.draft.php(101): GenericAttachments->upload(Array)
 >#5 (root)/include/ajax.draft.php(300): DraftAjaxAPI->_uploadInlineImage(Object(Draft))
 >#6 (root)/include/class.dispatcher.php(145): DraftAjaxAPI->uploadInlineImage('298')
 >#7 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('298/attach', Array)
 >#8 (root)/include/class.dispatcher.php(120): Dispatcher->resolve('298/attach', Array)
 >#9 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/draft/298/atta...', NULL)
 >#10 (root)/scp/ajax.php(262): Dispatcher->resolve('/draft/298/atta...')
> #11 {main}
