### ISSUE TITLE
Agent logon landing page

### ISSUE THREAD

**Issue by wfoster** [osTicket/osTicket#3335]
Hi Guys

Is there any way that i can edit what fields are displayed on the landing page when an agent logs in?
Our IT department is split on the ticket system into 4 departments: Hardware, Software, Mobile, Accounts.
The IT manager is the manager of all the departments on the ticket system. The problem is that he cannot sort between what ticket belongs to what department. If there is a way then please let me know.
My suggestion is that i replace the "Assigned to" column with department. Then he can just sort on the heading field with the drop down sort. please let me know if this is possible if there is no other way. As you can see he has 50 to 150 tickets open at any given time and wants to keep a hand on it.
![image](https://cloud.githubusercontent.com/assets/7644638/18163942/b83da8ee-703d-11e6-9b48-21d8e810f3ab.png)

I resolved it by making him an agent of each department. This means logging out and in consistently throughout the day. A big pain as you can imagine.

Thanks for the help

Let me know if I can assist with issues. I can help on most of the functional things like the settings, etc. not so much on the coding things though. Been using the system for about 3 years now and fixed and customized tons of things.

**Comment by ntozier** [comment]
This is not a feature of osTicket at this time.  You should be able to achieve this once the Custom Queues feature is released but that is a ways off as I understand it is planned to be in the version after 1.10 is released.

However if you are familiar with PHP/HTML you can modify the core source files to do this yourself.  This Forum thread will point you in the right direction.
http://osticket.com/forum/discussion/75457/a-better-ticket-list
Good luck.

**Comment by wfoster** [comment]
Thanks man
