### ISSUE TITLE
osTicket Guest Ticket Filing on osTicket 1.10.3 beta -> PHP 7

### ISSUE THREAD

**Issue by MiSAKACHi** [osTicket/osTicket#3337]
Hi all,

I have successfully installed osTicket 1.10.3 on our server running on Apache 2.4.23 with PHP 7.

After the system was deployed, I tried to test the available functionalities provided
by the system. Upon filing a support ticket as a guest user, I was stumped to see this one

![noinfo](https://cloud.githubusercontent.com/assets/9588282/18235488/0cedcac8-734e-11e6-8468-ab2325ede420.PNG)

I can file a ticket without providing any information.

As for this

![noinfo2](https://cloud.githubusercontent.com/assets/9588282/18235593/9a51b1da-734f-11e6-92a7-eaaa421c4b11.PNG)

![noinfo3](https://cloud.githubusercontent.com/assets/9588282/18235642/ef18d996-734f-11e6-86be-4bea64ebb3a5.PNG)

I can register an account without providing details

Please advise.

**Comment by ntozier** [comment]
1.10 rc3 is beta software and should not be run in a production environment. 
If you want to do more then play with or beta test the software, please run the current stable,

You have not really provided us with any of your setup information so I doubt that anyone can assist you.
I also cannot replicate your report.  I cannot open a ticket without providing information.

**Comment by MiSAKACHi** [comment]
What are the needed information aside from the PHP and Apache version? I'd gladly provide them.

Current Setup with the Server:
- Windows Server 2012 R2 x64
- PHP 7.0.10
- Apache 2.4.23

With regards to the problem mentioned above, check the image with a YELLOW HIGHLIGHT, 
there's no text fields to put the information needed.

**Comment by MiSAKACHi** [comment]
Bumping this thread, @ntozier can you help? I allowed external access to the problematic osTicket Installation. I'd give the link to someone who can look onto this issue. Thanks in Advance.

**Comment by ntozier** [comment]
I would try down grading to PHP 5.6.x.

Since I cannot replicate your issue I would presume that it is because of the version of PHP you are using or the fact that you are running beta software.  If you need commercial support you would want to contact them at: http://osticket.com/commercial-support

**Comment by MiSAKACHi** [comment]
Ok, thanks for the response. It looks like downgrading the PHP version and going to the stable version of the osTicket is the way to go.
