### ISSUE TITLE
No way to add or FAQ

### ISSUE THREAD

**Issue by craigmcewen** [osTicket/osTicket#3338]
Hey guys, can't seem to be able to view the add FAQ section. Added some data in the backend and it was able to show the doc on the front panel and you can get to it using the drop downs but cannot add anything from main screens. 

![no additions can be made to knowledge base](https://cloud.githubusercontent.com/assets/21174078/18247502/454b9284-73b6-11e6-994f-cf43cc4e8747.png)

**Comment by cluck** [comment]
Also observed here on 1.10 RC3.

Depending on some navigation before I also ended up seeing **Fatal error: Call to a member function sort() on a non-object in /var/www/lib/osticket/include/staff/faq-categories.inc.php on line 147**

**Comment by Af0x** [comment]
fix is here https://github.com/osTicket/osTicket/pull/3216/commits/12325c6d393d466542bcbb4dbe4555b18b28405c

**Comment by ntozier** [comment]
@craigmcewen you did not mention the version of osTicket you are running.

**Comment by craigmcewen** [comment]
Sorry guys!! V1.10-rc3

**Comment by craigmcewen** [comment]
@Af0x  I added your code to the faq-category page as suggested, well actually I copied the entire code and replaced mine as i had 73 lines total and you were pushing 140 odd.... The same prob still exists, still cannot add a faq into the system?? Am I missing something more? (Likely I would admit haha)
![nofix](https://cloud.githubusercontent.com/assets/21174078/18260113/2b8a9b06-742e-11e6-9fbe-aa1abaef2718.png)

**Comment by craigmcewen** [comment]
@Af0x After some playing about thinking I must have done something wrong, I realised I had! I updated the wrong file, but I seen no error from the update either so as you assume lol.. All resolved with your fix. 
Will say thought that adding just those pieces of code alone, they did not resolve, it was a full paste over old code.
