### ISSUE TITLE
Memcached extension is missing in class.ostsession.php on line 69

### ISSUE THREAD

**Issue by Pablohn26** [osTicket/osTicket#3342]
I have a lot of warnings like: 

> 2016/09/05 15:47:23 [error] 11470#11470: *2809648 FastCGI sent in stderr: "PHP message: PHP Warning:  Memcached extension is missing in /var/www/support/htdocs/include/class.ostsession.php on line 69" while reading response header from upstream, client: 10.0.1.46, server: support.webpage.com, request: "GET /scp/settings.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm-support.sock:", host: "support.webpage.com", referrer: "https://support.webpage.com/scp/index.php"

I have checked with php info and memcached is enabled. 

scp/system.php does not inform about memcached support, should be appear there? 

Osticket version    v1.9.12 (19292ad) 
PHP version 5.6.23

Not sure if it is related with #3115

**Comment by ntozier** [comment]
Please always upgrade to current prior to reporting a bug, (1.9.14 is current as of this writing)

webserver and ver?
If linux did yo install the php-memcache package?

**Comment by Pablohn26** [comment]
webserver: nginx/1.10.1
php: PHP 5.6.23-0+deb8u1 (fpm-fcgi) (built: Jul 12 2016 07:33:23)

```
dpkg -l | grep memcached
ii  libmemcachedutil2:amd64            1.0.18-4                     amd64        library implementing connection pooling for libmemcached
ii  memcached                          1.4.21-1.1                   amd64        high-performance memory object caching system
ii  php5-memcached                     2.2.0-2                      amd64        memcached extension module for PHP5, uses libmemcached

```

```
service memcached status
● memcached.service - memcached daemon
   Loaded: loaded (/lib/systemd/system/memcached.service; enabled)
   Active: active (running) since Mon 2016-09-05 16:00:35 UTC; 19h ago
```

And php module is enabled (also checked with php info)
```
php --info | grep "memcached support"
memcached support => enabled
```

**Comment by Pablohn26** [comment]
Thanks to your comment I have fixed the problem.

To fix this problem, you have to install php5-memcached AND php5-memcache (on debian). 

I guess warning text should be a little bit more exact and mention memcache php extension (instead of memcache**d** )
