### ISSUE TITLE
1.10.rc3 Editor: Cursor position wrong

### ISSUE THREAD

**Issue by Af0x** [osTicket/osTicket#3343]
Hello,

when you answer to a new ticket the cursor position looks like this:
![cursor](https://cloud.githubusercontent.com/assets/7013929/18253192/061efbb4-7393-11e6-8d8d-2c040d359665.png)

I use Firefox 48.0.1 
osticket 1.10.rc3

Regards,

Af0x

**Comment by ntozier** [comment]
And as soon as you start typing it's correct.
I would guess that this is a problem with the WYSIWYG editor (Redactor) not osTicket. 
It's not as pronounced in Chrome and not noticeable in IE.

**Comment by gitfve** [comment]
Is it possible you correct all the "Redactor" problem with firefox? I use 1.9.14 and there are big problem, when using firefox.

**Comment by ntozier** [comment]
Redactor is a 3rd party WYSIWYG editor.

**Comment by gitfve** [comment]
OK. Are you considering to switch the editor to a more stable one (on firefox at least)?

**Comment by ntozier** [comment]
I'm not considering anything... I'm not a dev.

**Comment by gitfve** [comment]
ok then:-) So maybe a developer look here too...

**Comment by Af0x** [comment]
no fix on this ugly one? that´s very sad

**Comment by wacki4** [comment]
We still have problem with redactor plugin o 1.10 - on pasting text, pasting image, cursor position etc.

Are you going to update this plugin ? I've checked that it has never version avaiable.
