### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by Padmahas** [osTicket/osTicket#3345]
Hello osTicket team,
Where can I find the documentation for osTicket API?

Thank you.

**Comment by ntozier** [comment]
https://github.com/osTicket/osTicket/blob/develop/setup/doc/api/tickets.md

**Comment by Padmahas** [comment]
Hello @ntozier, Thank you for the link.
Is it possible to test whether this API can be integrated to mobile app without installing osTicket into the server? Or do you know anything about using osTicket through mobile App?

Thank you again.

**Comment by ntozier** [comment]
You would need a server install to test against.

**Comment by devtar** [comment]
can i hit the osTicket url with postman? If yes then how?
