### ISSUE TITLE
Language file not working

### ISSUE THREAD

**Issue by Isfirs** [osTicket/osTicket#3346]
### Environment
- osTicekt 1.9.14 current lastest)
- `de.phar` from the current latest repo
### Actual behavior
- The landing page won't show the correct translation at multiple places.
### Expected behavior
- Read german texts at the now missing parts.
### Steps to reproduce
- Install osTicket
- drop in de.phar
- Load page with german language
### Notes

If there is anything missing, please tell me.

**Comment by Chefkeks** [comment]
Multilanguage support of osTicket is not fully implemented yet. So to have a full German osTicket, you need to install osTicket with German as the primary language. Dropping in the de.phar after the installation won't work with all the translation, since some texts are still pulled from the database currently and not the language packs which means you'll need to re-install with German as primary language.

**Comment by Isfirs** [comment]
And how to do so?

Please provide a link with instructions to a "clean" installation.

**Comment by ntozier** [comment]
- delete your database.
- delete your source.
- create your database (and give your DB user access to it)
- put the source in your preferred location. (where your webserver will serve it, or configure the webserver to serve the new location.)
- put the language file into place.
- Run the installer.
- While running the installer make sure that you Choose your language.
- complete running the installer.

**Comment by Isfirs** [comment]
Thank you.

Why aren't languages resovled from the uploaded files yet?

Compiling them into the database is `bad practice` and isn't maintable.

is there a milestone to fix that?

**Comment by ntozier** [comment]
The multi language feature in osTicket has not been announced as completed.

**Comment by dinaras** [comment]
Hello,

I have installed greek language in os1cket 1.10 rc3. It did not work using the .phar file. I had to uncompress the file using online tool, and then uploaded the uncompressed files to corresponding directory i created. Then everything started working ok.

I am having a similar problem with translations added to db from agent panel in user templates. All other translations worked fine apart from translating user templates forms. Emails translated fine as well

Thank you

**Comment by rayfoss** [comment]
new language packs are up as of Jan 13.

**Comment by nilschrishahn** [comment]
Where??

**Comment by rayfoss** [comment]
yeah, ignore the dates on the website... the files are actually new, doing `phar extract -f ` and taking a look at the MANIFEST.php will tell you the real date they were updated.

**Comment by atilimtosun** [comment]
> yeah, ignore the dates on the website... the files are actually new, doing `phar extract -f ` and taking a look at the MANIFEST.php will tell you the real date they were updated.

i had trying to fix this problem for a day thanks  for help
