### ISSUE TITLE
1.10rc3 opening ticket -> white page + not visible for Agents

### ISSUE THREAD

**Issue by Af0x** [osTicket/osTicket#3350]
Hello,

when I open a ticket I don´t get to the "thank you"-page. Instead only a white page is shown and no confirmation is sent to user. When I reload the page I get the "thank you"-page and mail is sent.

The "white-page-opening" is also visible as "closed" in statistics of the agent-panel but there is no way to access this ticket. Also the user is there but no ticket is visible.

If I try to delete this user it says that there is one ticket from this user and if I tick the checkbox for deletion it says "no permission" (I am logged in as admin-user).

PHP 7.0.10, Apache 2.4.10
osticket 1.10rc3 (upgraded from 1.9.14)

I see no error in apache-log, syslog, mysql-log or php-fpm-log. Maybe someone has another idea how to debug.

Regards,

Afox

**Comment by ntozier** [comment]
IF you are getting a white page then you are throwing a PHP error.  You should check the PHP error log.  You can look at your phpini to see where that is, or turn on error reporting in osTicket and display the error to the screen.

**Comment by Af0x** [comment]
This issue comes from deleting a form-variable and after going back to original state this error is gone.

**Comment by Af0x** [comment]
to be honest: I have no idea what I did to trigger this error but here is the PHP-Error. That´s all I can do for now...
Actually there are two errors, the first one is when calling the form from customer-perspective (I think) and the second is the white page-error after submitting the form.

`[Thu Sep 08 23:17:50.196019 2016] [proxy_fcgi:error] [pid 862] [client IP:Number] AH01071: Got error 'PHP message: PHP Warning:  Declaration of AssignmentForm::render($options) should be compatible with Form::render($staff = true, $title = false, $options = Array) in /dir/to/osticket/include/class.forms.php on line 4146\nPHP message: PHP Warning:  Declaration of TransferForm::render($options) should be compatible with Form::render($staff = true, $title = false, $options = Array) in /dir/to/osticket/include/class.forms.php on line 4266\n'

[Thu Sep 08 23:18:15.931425 2016] [proxy_fcgi:error] [pid 1411] [client IP:Number] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught ObjectNotUnique: One object was expected; however multiple objects in the database matched the query. In fact, there are 3 matching objects. in /dir/to/osticket/include/class.orm.php:1175\nStack trace:\n#0 /dir/to/osticket/include/class.orm.php(544): QuerySet->one()\n#1 /dir/to/osticket/include/class.orm.php(350): VerySimpleModel::lookup(Array)\n#2 /dir/to/osticket/include/class.orm.php(386): VerySimpleModel->get('email_info', NULL)\n#3 /dir/to/osticket/include/class.thread.php(722): VerySimpleModel->__get('email_info')\n#4 /dir/to/osticket/include/class.thread.php(849): ThreadEntry->getEmailHeaderArray()\n#5 /dir/to/osticket/include/class.thread.php(865): ThreadEntry->isAutoReply()\n#6 /dir/to/osticket/include/class.ticket.php(2337): ThreadEntry->isBounceOrAutoReply()\n#7 /dir/to/osticket/include/class.ticket.php(3419): Ticket->postMessage(Array, 'Web', false)\n#8 /dir/to/os...\n', referer: https://myurl.com/open.php`

**Comment by jackd90** [comment]
Looks like I'm having the same issue after upgrading.

![image](https://cloud.githubusercontent.com/assets/13241118/21434995/d8fee2b2-c83c-11e6-889d-36ca639f8228.png)
