### ISSUE TITLE
Require login page for open a new tricket 

### ISSUE THREAD

**Issue by nanthakumarr** [osTicket/osTicket#3351]
Hi guys i need to know which php file is belongs to the database check of my username and password for user login page while open a new ticket, kindly any one help me please,

**Comment by ntozier** [comment]
PHP files do not belong to the database.  
version of osTicket?
What are you trying to achieve?

**Comment by nanthakumarr** [comment]
My os ticket version is : osTicket (v1.9.4-rc2)
![myticket](https://cloud.githubusercontent.com/assets/16773989/18385576/1f685754-76af-11e6-8c4d-74fbb4b58e0c.png)

**Comment by ntozier** [comment]
1.9.4-rc2 is ancient... and a release candidate.  You need to upgrade to something more current, and something that isn't a release candidate.

**Comment by nanthakumarr** [comment]
ok I have an another doubt, is this possible to login without username and password (ie) unregistered username and password, why i am asking is in Osticket there is a enduser validation, so the registered user only loggedin to create a ticket, i dont want to register a user, but i login using our company service url, is this possible, kindly help me....

**Comment by ntozier** [comment]
That really depends on what you mean by can they login without username/password.  They can click a quick access link in any of the emails send to them [by the system] and see their **ticket, but only that ticket**.  So in that way they can 'login', otherwise no they cannot "login" with out a username/password.

**Comment by nanthakumarr** [comment]
I dont want to register a user to open a ticket, my employees have a username and password, so that service, i need to call in class.auth.php, i need only login to open a ticket with their master username and password, is this possible,

**Comment by ntozier** [comment]
Admin panel -> Settings -> Access
require registration: checked.
registration method: private.

**Comment by gitsweety** [comment]
> I dont want to register any new user to open a ticket, my employees have a username and password, so that service, i need to call in class.auth.php, i need only login to open a ticket with their master username and password, login should be based on the response from the service, is this possible, please help me,
> ![untitled](https://cloud.githubusercontent.com/assets/16773989/18462734/95eef252-79a2-11e6-91f8-0cbadf7cf1d9.png)
Can you please explain that isuue in details

**Comment by Nawrass31** [comment]
Kindly can you answer this question: Can client register and sign in only by username without password
