### ISSUE TITLE
add unread count in tab title

### ISSUE THREAD

**Issue by iweindesmedt** [osTicket/osTicket#3354]
It would be nice if the tab title has an unread count, a bit like Gmail's tab title.
Maybe make it configurable with variables like `%{number_open}`, `%{number_open_my}`, `%{number_closed}`,...

**Comment by ntozier** [comment]
I have no idea what you are talking about.
You may want to include more information, such as a mock up image of what you are talking about, and/or how to reproduce the issue that you are having.  You should probably also include version of osTicket that you are running.

**Comment by iweindesmedt** [comment]
Sorry, maybe i was unclear indeed. Just think of it as a notification system through the tab title, like an app on your phone would indicate how many new messages you have by placing a number on the app icon.

As an agent in the osTicket system, you then could see how many new/open/closed/... tickets there are just by looking at the tab title. This means that you can spot this without having to activate the tab of osTicket.

So instead of the title being `osTicket :: Staff Control Panel`, it would be `(5) osTicket :: Staff Control Panel` when there are 5 open tickets.

As a plus, it would be great if this was configurable in the Admin panel. So you can choose to show only "my open" tickets, "all" open tickets, "overdue" tickets, etc...

(for the Gmail reference, take a look here: http://lifehacker.com/5743173/gmail-adds-unread-count-in-favicon-to-gmail-labs, this is done with favicon, but it's the same concept)

**Comment by ntozier** [comment]
So to be clear you are asking us to alter the web pages title to indicate when there are new messages.  
Thanks for a the clarification.

**Comment by iweindesmedt** [comment]
Exactly, just suggesting this as an enhancement.
