### ISSUE TITLE
Sending alerts is not working anymore: [SMTP: Invalid response code received from server (code: -1, response: )] 

### ISSUE THREAD

**Issue by bblaha** [osTicket/osTicket#3358]
After resolving what appears to me to be a bug, I have run into another problem. The first problem can be seen here: http://osticket.com/forum/discussion/88796/ticket-responses-not-getting-sent-diagnostic-mail-working#latest
Now sending to clients is working, but our agents are not receiving notifications when a new ticket is created. At least now I am getting an error message:
Failed to set sender: mail@example.com [SMTP: Invalid response code received from server (code: -1, response: )] 
This looks to me like an error message that was not really handled (-1). Since the SMTP server setup works: What could this be?

**Comment by bblaha** [comment]
When I comment on a ticket the assigned agent receives a notification. He does not receive anything when the ticket is created or assigned

**Comment by ntozier** [comment]
This appears to be a question that should be handled on the support forums.  Additionally uou have not provided any information about your setup.  Software versions, etc.  Please help us to help you by reading and following the posting guidelines located in this thread: [Please read before requesting assistance](http://www.osticket.com/forum/discussion/77765/please-read-before-requesting-assistance#latest).  The more information you give us the better we will be able to assist you. Thank you.

**Comment by bblaha** [comment]
Thought this was handled with the thread I added to my question. I can post it to the support forums, but I have - as can be seen in above linked thread - not received any helpful responses besides yours, which is pretty much the same as this one ;)
