### ISSUE TITLE
new ticket cancel button #2881 

### ISSUE THREAD

**Issue by meinsteren** [osTicket/osTicket#3360]
I have the same Problem (Osticket v1.10-rc.3 / Latest commit  55dc25a  on Jul 10 ).

any solution ???

mfg
 Giano

**Comment by ntozier** [comment]
You have not actually provided a description of what your problem actually is.

Please help us to help you by reading and following the posting guidelines located in this thread: [Please read before requesting assistance](http://www.osticket.com/forum/discussion/77765/please-read-before-requesting-assistance#latest).  The more information you give us the better we will be able to assist you. Thank you.

**Comment by meinsteren** [comment]
Sorry.
Reference  Issue: #2881

**Comment by meinsteren** [comment]
![error](https://cloud.githubusercontent.com/assets/22029754/18476569/e25fc1b6-79ca-11e6-9d6a-2550d99d53b9.jpg)

**Comment by ntozier** [comment]
Then this is a duplicate issue report, please close it.
