### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by hrace009** [osTicket/osTicket#3365]
Hello, This is my first time isong osTicket.
as usual, like other system, it only need to upload the file to server, and pointing to URL.
when i try to open URL at my browser, it only show "No input file specified. "
I have try to follow installation guide from WIKI http://osticket.com/wiki/Installation
It still show "No input file specified. "

**Comment by ntozier** [comment]
This appears to be a setup / configuration / installation question and not an code issue.  Please open a thread at the support forums: http://osticket.com/forum

Please help us to help you by reading and following the posting guidelines located in this thread: [Please read before requesting assistance](http://www.osticket.com/forum/discussion/77765/please-read-before-requesting-assistance#latest).  The more information you give us the better we will be able to assist you. Thank you.
