### ISSUE TITLE
Canned response not showing up array variable value

### ISSUE THREAD

**Issue by monttana** [osTicket/osTicket#3369]
Hi all,

We are working with the osTicket v1.10-rc.3 on production and it is moving smoothly, the only thing  that we have discovered that is not working right is the fact that the data stored in a form that has a variable of choices type (array) and that variable is used in a canned response the content of that variable is not been displayed correctly. We only get a "array" value instead of the correct value.

**Comment by Eddie595** [comment]
Don't have time to look at the code right now, but if this utilizes the same function as the basic 'export' feature at the bottom of the ticket listing, then this is the same issue so to speak. It probably isn't, but when you utilize the export link it also displays the array/row number. Although sometimes it shows "n" and sometimes it shows "n,variable": where 'n' is the number, and 'variable' is the correct result.
