### ISSUE TITLE
PHP Fatal error:  Call to a member function getLastMessage() on null

### ISSUE THREAD

**Issue by jaketyo** [osTicket/osTicket#3371]
Version: 1.10-RC.3

I am trying to call `$ticket_lastMessage = $ticket->getLastMessage();` from a plugin but I get the following error in the error log:

`PHP Fatal error:  Call to a member function getLastMessage() on null in /var/www/html/osticket-dev/include/class.ticket.php on line 801, referer: https://########/osticket-dev/scp/tickets.php?a=open&uid=6`

It looks like `getThread()` from tickets.php inside the getLastMessage() function is returning NULL, but I don't know why.

Anyone know why that is happening?

(UPDATE): Today, without changing any code I am seeing the same error on a separate function. The function `$ticket_name = $ticket->getName()`.

When inspecting the function getName() itself, it seems that the only reason it would return null is if either `$o=>getName()` returns NULL, or if `getOwner()` returns NULL. The latter of which is unlikely.

**Comment by Ara4Sh** [comment]
I got this when enabling rocket.chat plugin 

`PHP Fatal error:  Call to a member function getLastMessage() on null in /var/www/ost/include/class.ticket.php on line 801, referer: https://ticket.karina.cloud/open.php`

system information : 

```
iosticket v1.10 (901e5ea) — Up to date
Web Server Software 	Apache/2.4.10 (Debian)
MySQL Version 	5.6.34
PHP Version 	5.6.29-0+deb8u1
```

**Comment by ntozier** [comment]
rocket.chat plugin?
There is no official Rocket.chat plugin...  and I have never heard of it.
We do not provide support for third party plugins, so please contact the author/vendor of your 3rd party plugin for support.

**Comment by jaketyo** [comment]
Just a head's up, my original issue is still prevalent and has nothing to do with any plugins.
It is running on a bare-bones installation with no plugins.

**Comment by rayfoss** [comment]
The original specifies that this happens when interacting with the code through a custom plugin...

@jaketyo Is there any way to reproduce the error through the front end?
