### ISSUE TITLE
Clear Staff on Transfer to Team

### ISSUE THREAD

**Issue by ipAnything** [osTicket/osTicket#3372]
Currently if a Ticket is assigned to an Agent and you Assign the Ticket to a Team, the ticket remains assigned to the Agent and now also the Team. eg: **Assigned To: Agent/Team** even if the agent is not a member of the assigned Team.

If the agent has the need to assign the ticket to a Team or a New Team, it is clear that he needs somebody else to handle the ticket. So it makes no sense that he remains the assigned Agent. Also no notification is sent to the assigned team that a new ticket has been assigned to the Team as the ticket is already assigned to an Agent.

To fix this I added `$this->staff_id = 0;` on line 2211 after line `$this->team_id = $assignee->getId();` in the `function assign` in the **class.ticket.php**

This successfully removes the Agent on assignment to a Team/New Team and the notification to team members is sent.

I am using 1.10rc3. I suggest that this is implemented as part of 1.10.

**Comment by ntozier** [comment]
I agree that un-assign is a needed feature!  (I do it manually right now in the DB, but luckily I don't need to do it very often) That being said 1.10 is currently under a feature freeze so it definitely will not be included in the 1.10 release.

Also this thread is very similar to this issue report: https://github.com/osTicket/osTicket/issues/3308

**Comment by ipAnything** [comment]
Hi @ntozier,

Thank you for your feedback. Issue report #3308 is not the same as what I am indicating here. #3308 is a new option for being able to un-assign a ticket at will. What I am suggesting here is a change in the logic of an existing operation.

As per my post, it makes no sense that the ticket remains assigned to the Agent, if the agent is transferring the ticket to another Team. So it should by default un-assign the agent without user intervention.

The change to the code is minimal but the effect is of great importance. I would not categorize this as a new feature. More of a fix to what is a logical bug.

**Comment by ntozier** [comment]
On the contrary, both of you are asking for a way to unassign tickets (on transfer or not). I said that the requests are similar not identical. I also agree that this is a needed feature.

Tickets can be assigned to: (1) an Agent (or not) and (2) a Department or (2) a Team or not.

Whether or not it makes sense that the Agent who is assigning it to another Department/Team still has access to the ticket depends entirely on your work flow/use case. Your fix should take into account multiple use cases and offer the option at the administrator (and/or Agentl) level to decide.

**Comment by ipAnything** [comment]
In that case, the option should be given on the actual Transfer. So IF the Tciket is already assigned to an Agent, then the option would appear to over write such a default by un-ticking an option like "Un-assign the existing Agent" Is this what you mean?

![unassign on transfer](https://cloud.githubusercontent.com/assets/12978304/18801637/46e203bc-81e4-11e6-9ade-3bf24bbc1d95.PNG)

**Comment by chucks26** [comment]
> To fix this I added $this->staff_id = 0; on line 2211 after line $this->team_id = $assignee->getId(); in the function assign in the class.ticket.php

v1.10 (901e5ea) here.
Did the same on my own, and put in production a month ago. Any problem so far...

Cheers,
Chuck26

**Comment by ipAnything** [comment]
@chucks26 I did not quite understand you.

I have not experience any issue so far with this adjustment. I am using v1.10 (901e5ea) also.

**Comment by chucks26** [comment]
It was only to say that I did the same edit (before reading this post) and worked great in production for me!

Cheers,
Chuck26

**Comment by stf675** [comment]
Confirming that @ipAnything solution works perfectly
