### ISSUE TITLE
smime support

### ISSUE THREAD

**Issue by sharmay** [osTicket/osTicket#3374]
osTicket : v1.10-rc.2-307-gbf2395b
osTicket not able to decode email and shows them as an attachment smime.7pm

For decoding I used following commands:
openssl smime -inform DER -verify -noverify -in smime.p7m -out /tmp/out.txt

Now out.txt is real email.

Looks like ticket was opened via sending email from outlook.

**Comment by ntozier** [comment]
Please upgrade to the latest Beta 1.10rc3 and re-test.

**Comment by sharmay** [comment]
I will update and retest, but I do not recall  this fix in rc3 change log, do you have reference to this change ?

**Comment by ntozier** [comment]
Nope. We are not in the habit of supporting old RC's.
