### ISSUE TITLE
Rich Text mode truncate angular brackets

### ISSUE THREAD

**Issue by sharmay** [osTicket/osTicket#3375]
osTicket:` v1.10-rc.2-307-gbf2395b

when angular brackets are using they are treated as html and gets truncated:

./test.sh &lt;id&gt;  will result in ./test.sh

./test.sh -U &lt;id&gt;  will result in ./test.sh -U

./test -U &lt;id&gt; &lt; some filename
Pass input filename

will truncate everything after < and shows ./test -U

**Comment by ntozier** [comment]
You are using an outdated Beta version.  You should update to the current beta and retest.
Also you should provide step by step instructions to recreate your issue, and should also probably provide a screen shot.

**Comment by sharmay** [comment]
Upgraded to latest 1.10
Still angular brackets in message are truncated.

Create new ticket or response to an existing ticket, have some message with angular brackets. Message will truncate angular brackets.

**Comment by ntozier** [comment]
By angular you mean < and >?  It's probably being parsed as HTML and being stripped out.

**Comment by ntozier** [comment]
Then the editor is assuming its invalid HTML and stripping it.  Try using &lt; and &gt;
