### ISSUE TITLE
[1.10r3] Long FAQ titles wrap incorrectly

### ISSUE THREAD

**Issue by ntozier** [osTicket/osTicket#3380]
FAQs with titles greater then (approx) 64 characters wrap the title to the next line.  However it appears to push the display of the entire title down one line before displaying it.  Which results in an orphans FAQ icon on a blank line and then the next two lines having the title.  See image:

![long-faq](https://cloud.githubusercontent.com/assets/1315768/18955750/aa892b98-8626-11e6-91fc-afdc87874bb0.png)

I have tested this in in Chrome 52.0.2743, Firefox 49.0, Firefox 49.0.1, Microsoft Edge 25.10586.0.0., Internet Explorer 10.0.9200.17609, Internet Explorer 11.0.9600.18449 update 11.0.35.

**Comment by rbukovansky** [comment]
Temporary solution:
I have commented out line `display: inline-block;` for `a, .link` in `assets/default/css/theme.css` and it makes links jump back...

But some webdeveloper needs to better look at that...

Or you can rewrite those articles' with shorter titles... ;)

**Comment by gitfve** [comment]
Sorry to say, but GUI look wrong or bad in v1.10x compared v1.9.x I don't know why there are so many CSS change. When using v1.10x for testing it look totally screwed up compared to my v1.9.x Nothing fit nice on the page. If i going to create a new ticket the page on my 1.9.x is about to fit the screen, but in 1.10.x there are more like two pages to scroll, too much space and most off the field is placed on new lines... look real bad.

Same problem in the QA section.

I am not ready to skip my 1.9.x over the 1.10x.

The ticket editing (back-end) in 1.9.x in FF have a lot of problem, but 1.10x have a lot of the same problem!

Hope for a 1.12 where all this is solved.

**Comment by ntozier** [comment]
update: This is still present in 1,10 final

**Comment by JediKev** [comment]
I made a pull request #3522 that should fix this. 😁

**Comment by ntozier** [comment]
@JediKev  your pull fixes the issue.
Closing issue.
