### ISSUE TITLE
Subject of new tickets - HelpTopics - V1.10rc2 / V1.10rc3

### ISSUE THREAD

**Issue by alexdel35** [osTicket/osTicket#3381]
Hello,

I created a sandbox system with the latest release candidate 1.10rc3 and I am currently testing it.

Behavior of the following has been modified from the previous RC (RC2).

RC2: If you create a dedicated help topic with specific forms and if you disable the default form named "Ticket Details", in the agent panel tickets view, the subject of the tickets are the name of the Help Topic.

RC3: If you do the same thing, the subject is empty. I can imagine in previous version, if there is no subject it took the HelpTopic name but now it is not.

Do you know why this behavior has been modified and if we can roll back to the previous one?

For your information, I consider that the requester does not have to systematically fill in a subject for the request. If he is asking for the installation of a software, for instance, the subject is always "Software installation" and in the details of the specific form, he can ask for a list of software. I created a lot of dedicated helptopics and generally disabled the default form to put the ones I generated.

I quoted the answers I received on this topic. [http://osticket.com/forum/discussion/88898/subject-of-new-tickets-helptopics-v1-10rc2-v1-10rc3#latest]

> ntozier
> September 29 Flag
> Q: Do you know why this behavior has been modified and if we can roll back to the previous one?
> A: I am not aware of that behavior EVER being a thing in osTicket.  Perhaps you modded your installation using a thread on github or here.  I do remember a thread or two about this sort of thing and someone posting a way to do it, but it was not an official thing.
> 
> alex_del
> September 29 Flag
> Nope I did not mod it.:)
> I have on one side the RC2 and on the other side the RC3.
> And the behavior I mentionned for the RC2 is the default one.
> But it changed in the RC3.
> 
> MichaelM
> September 29 Flag
> I can attest to this as I tested RC2 for a very short time before setting up RC3 and I noticed the help topic carried over in RC2 as the subject when the Ticket Details form was disabled, but this does not happen in RC3. Both were clean installs prior to any mods (RC2 was not modded at all, RC3 I have since modded).

**Comment by jdelhome3578** [comment]
See #3237
