### ISSUE TITLE
search not working

### ISSUE THREAD

**Issue by gamba47** [osTicket/osTicket#3383]
Hi guys, i recently upgrade again to the latest git version.
I'm using osticket on this instalation since 1.7 and upgrading to any new version when i have time.

The problem i have at this time is the search function not fully working. When i search for a word who is in the subject or inside the ticket the search response is mostly empty.

This issue is only on this instalation and the only thing i found diferent on this is the 3 upgrades i have on this ( 1.7 => 1.8 => 1.9 => 1.8git )

Is there any way to test this? i'm not a gurú but maybe i can make some test with a little help.

Best regards.

**Comment by gamba47** [comment]
Sorry for the bad Subject i forgot to mention this is not an issue related directly to 1.8git version i make a clean install and the search is working like a charm!

The problem is there yet but not in a clean install.

Thanks!

**Comment by ntozier** [comment]
"1.8git" does not really convey the version that you installed. This is the version displayed when you download from github.  There should also be a github version in () after it.  Like this: v1.10-rc.3 (907ec36)

I would highly recommend that you only download and install versions from osticket.com/download. These versions are specifically prepared for end users to run.

**Comment by gamba47** [comment]
Thanks @ntozier !

This is the versión i saw in the web (it's in spanish sorry):
![osticket](https://cloud.githubusercontent.com/assets/11230767/19208126/e9b0fa38-8ccc-11e6-9fd3-f35951ba3908.png)

The git versión is unstable? i use it for a 2 sites and it's working really great! do you think i need to downgrade ?

Thanks for your time!
Best regards.

Emiliano.

**Comment by ntozier** [comment]
I would recommend that you download and install the latest stable version from osticket.com/download.
