### ISSUE TITLE
how to make Email Address Optional in Create New Ticket?

### ISSUE THREAD

**Issue by tanejakaran** [osTicket/osTicket#3388]
I have make required = 0 and removed validation error. 
Remove Unique from database as well. 

Email validation and required is removed but still Email uniqueness is there.
If I do not add any email address, system go to indefinite Loading mode and It needs at least one character to save a full name or create a user. 

How to make email address optional without any character. 
Only name needed.  Using latest version

**Comment by ntozier** [comment]
unique emails are required at this time.

**Comment by tanejakaran** [comment]
Thanks for your answer. But, Today I had Fixed with some database customization :)

**Comment by mailenh** [comment]
Hey Karan, would you tell me how you did it?

**Comment by tanejakaran** [comment]
unique emails are required at this timE.

For whom, I donot need email, I used dummy email address which is not going
anywhere or I have integrated sms api. So
phonenumber@theirserviceprovoder.com is email address for those users. They
received sms instead of email. :)
