### ISSUE TITLE
Mapping Incoming mailbox to a specific helptopic

### ISSUE THREAD

**Issue by ramkinavy** [osTicket/osTicket#3390]
Is there a way , if i can map multiple incoming mail address (for creation of support tickets) to a specific help topic?? 

unable to figure out

**Comment by ntozier** [comment]
Version of osTicket?

Admin panel -> Manage -> Ticket Filters
Add a new filter
Addressee your email
Action, Set Department.

**Comment by rbukovansky** [comment]
Not sure, if you can do that in osTicket <1.10 (1.9?), but in >=1.10 you can set default help topic in settings of e-mail box. 
![default_help_topic](https://cloud.githubusercontent.com/assets/1004491/19302768/ea9b4394-9065-11e6-9a46-822e67535cc7.png)
