### ISSUE TITLE
Disable "Post Reply" button after clicking to prevent duplicate messages

### ISSUE THREAD

**Issue by meirg** [osTicket/osTicket#3391]
When posting a reply to a ticket, the submit button should be disabled after submitting to prevent duplicate replies being sent due to agents clicking the button again before the page loads.

I have experienced this in Google Chrome, but have not tried in other browsers.

This may be relevant to other submit buttons as well, this is just where I notice the issue the most

**Comment by JediKev** [comment]
I have a Pull Request pending (#3426) that should fix this issue. Instead of disabling the button on click we put a 'Loading' overlay on the page until the reply is posted to prevent such duplicate replies.

**Comment by rayfoss** [comment]
fixed. Thanks jedi!
