### ISSUE TITLE
Grap Ticket Activity of dashboard in osticket 1.10RC3 has issue

### ISSUE THREAD

**Issue by thuc960** [osTicket/osTicket#3395]
Date and count ticket maybe loop
Is there way to resolve it?
Thanks
![10-12-2016 10-17-11 am](https://cloud.githubusercontent.com/assets/10082797/19296426/91826e04-9065-11e6-8a55-1e5fcc0dee93.png)

**Comment by ntozier** [comment]
I'm sorry but I am not sure what you are trying to ask.

**Comment by rodrigopaivadasilva** [comment]
Hi
Well... I think that he said the same I see after to install osTicket v1.10
After I installed the last version I closed the default ticket created by system and when I was access Dashboard and below Satistic table. There don't show information of closed ticket. I still see a open ticket information:

Support 	1 	0 	0 	0 	0 	2.0 	0.0

**Comment by ntozier** [comment]
@rodrigopaivadasilva No idea what your saying.  Screen shot?  Are you talking about multiple versions?  And what is the "Support 1 0 0 0 0 2.0 0.0"
