### ISSUE TITLE
osTicket v. 1.9.14 Attachments not opening/displaying

### ISSUE THREAD

**Issue by firepro20** [osTicket/osTicket#3396]
Text files and images are not being opened when clicked from the admin/agent side. They are neither being downloaded. Just an empty white box is being displayed when links are clicked

**Comment by ntozier** [comment]
Please help us to help you by reading and following the posting guidelines located in this thread: [Please read before requesting assistance](http://www.osticket.com/forum/discussion/77765/please-read-before-requesting-assistance#latest).  The more information you give us the better we will be able to assist you. Thank you.

How do you have attachments configured?
Webserver and ver?
Webserver or PHP errors from logs?

**Comment by rayfoss** [comment]
no response

**Comment by firepro20** [comment]
Upgraded to latest version. Everything is working now
