### ISSUE TITLE
1.10-rc.3 error when create ticket 

### ISSUE THREAD

**Issue by nntu** [osTicket/osTicket#3397]
server

osTicket    v1.10-rc.3 (907ec36) — Up to date
Web Server  Apache/2.4.10 (Debian)
 My SQL     5.6.34
 PHP    5.6.26-0+deb8u1

![wawerwer](https://cloud.githubusercontent.com/assets/316238/19338529/cd502754-9147-11e6-900a-489cef11d670.png)

![v2](https://cloud.githubusercontent.com/assets/316238/19338535/dd911e16-9147-11e6-8526-4748d77293bf.png)

PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'List indices should be integers' in /var/www/html/hotro/include/class.util.php:149\nStack trace:\n#0 /var/www/html/hotro/include/class.forms.php(81): ListObject->offsetExists('message')\n#1 /var/www/html/hotro/tickets.php(39): Form->getField('message')\n#2 {main}\n  thrown in /var/www/html/hotro/include/class.util.php on line 149, referer: http://10.141.2.83/hotro/login.php

**Comment by tchwpkgorg** [comment]
I'm seeing the exact same issue with osticket 1.10 right after installation:

- Ubuntu 16.04.1 LTS
- PHP 7
- Apache 2.4

**Comment by Nagsein** [comment]
I'm seeing the same issue:
Versión osTicket	v1.10 (901e5ea) 
Servidor del Software Web	Apache/2.4.18 (Ubuntu)
Versión MySQL	5.7.17
Versión PHP	7.0.13-0ubuntu0.16.04.1

**Comment by Finn10111** [comment]
I am having the same error since about one hour. osTicket was installed a few weeks ago, after changing some settings (renaming a department, deleting some form-entries from "Ticket Details") I can't create new tickets also. It seems like I am getting the same error message:

`PHP Fatal error:  Uncaught InvalidArgumentException: List indices should be integers in /var/www/html/include/class.util.php:149\nStack trace:\n#0 /var/www/html/include/class.forms.php(81): ListObject->offsetExists('message')\n#1 /var/www/html/include/class.ticket.php(3564): Form->getField('message')\n#2 /var/www/html/scp/tickets.php(328): Ticket::open(Array, Array)\n#3 {main}\n  thrown in /var/www/html/include/class.util.php on line 149, referer: http://osticket.example.org/scp/tickets.php?a=open&uid=38`

**Comment by TCBSnowsun** [comment]
Has someone workarounded the issue?

**Comment by rayfoss** [comment]
https://github.com/osTicket/osTicket/issues/3620 1.10 can't install properly on php 7.0, it can upgrade to it however. The issue is some fields are missing or disabled. The problem has been fixed and should be out on 1.11, but your best bet is to do an install on php 5.6

**Comment by TCBSnowsun** [comment]
Can i implement the bugfix on the 1.10 version on my own and update the files on the current installation?
Or do i need to install it fresh after that?

**Comment by rayfoss** [comment]
You should be able to fix it on php 7 by setting the proper mask on all the broken values... 

```
$ grep -Irin --include="*.yaml" 0x
include/i18n/en_US/list.yaml:41:        flags: 0x770F1
include/i18n/en_US/list.yaml:48:        flags: 0x73021
include/i18n/en_US/sequence.yaml:11:#               INTERNAL:=0x0001 (restrict delete)
include/i18n/en_US/file.yaml:24:    P5Dn5uTh5mbnbO/0xaL+a/BvIj4h8d/+vIwCBAAQTs/v2l/l5dYDcMcBsHW/a6lbANpWAGjf+V0z
include/i18n/en_US/file.yaml:82:    bG1Z887KEZILhJ4n9MdCr2j0t6NC80xauN5NP5sSpLAAXXMBmRRH1j6+1+ISWig0V6hdaA0i0r4m
include/i18n/en_US/file.yaml:87:    fi00P+2ZnRbVfuOgSYt91Ca3eeVlWerY/OUEoW8K7XWEz3sucru9QmsBuNZpHHY/ipf6H0xHG7cd
include/i18n/en_US/file.yaml:95:    jN7c3Yv6t9gk3HzGfvAsipfdlZQBeN8gtmwQ2uIoNFcu0xpBatWICMJyneLjc3LJFFedtclNCwXQ
include/i18n/en_US/file.yaml:104:    6f293ejk4A7qJZRC/lRgywOFU/JP0DtdTk55sVgZ3no34rYecxy00X3zAvTkh35qL6jfrA1uqg4b
include/i18n/en_US/file.yaml:131:    /laItso5rCmMZnTRvH47vJ5XnzlYdMh0xoojKQo2RXj9OXKi8+E4uLwf619LgMwfpWcXBOgOkZcV
include/i18n/en_US/file.yaml:174:    1n54LwPG78HGRiHVUG7pf3AvB9i95QLYJQxoW3Ddi1hlcyzavsSRogppZZBM0xGYH8lEDveBSktL
include/i18n/en_US/team.yaml:6:#   - isenabled - (0x01) true or false if the team should be initially
include/i18n/en_US/team.yaml:8:#   - noalerts - (0x02)
include/i18n/en_US/team.yaml:13:- flags: 0x01
include/i18n/en_US/form.yaml:11:#   0x0001  If the form can be removed from the system
include/i18n/en_US/form.yaml:21:#     const FLAG_MASK_CHANGE      = 0x0010;     # Type cannot change
include/i18n/en_US/form.yaml:22:#     const FLAG_MASK_DELETE      = 0x0020;     # Cannot be deleted
include/i18n/en_US/form.yaml:23:#     const FLAG_MASK_EDIT        = 0x0040;     # Data cannot be edited
include/i18n/en_US/form.yaml:24:#     const FLAG_MASK_DISABLE     = 0x0080;     # Field cannot be disabled
include/i18n/en_US/form.yaml:25:#     const FLAG_MASK_REQUIRE     = 0x10000;    # Requirement cannot be changed
include/i18n/en_US/form.yaml:26:#     const FLAG_MASK_VIEW        = 0x20000;    # View settings cannot be changed
include/i18n/en_US/form.yaml:27:#     const FLAG_MASK_NAME        = 0x40000;    # Name cannot be changed
include/i18n/en_US/form.yaml:45:      flags: 0x777A3
include/i18n/en_US/form.yaml:54:      flags: 0x777A3
include/i18n/en_US/form.yaml:62:      flags: 0x3301
include/i18n/en_US/form.yaml:67:      flags: 0x3001
include/i18n/en_US/form.yaml:86:      flags: 0x77721
include/i18n/en_US/form.yaml:96:      flags: 0x75523
include/i18n/en_US/form.yaml:101:      flags: 0x430B1
include/i18n/en_US/form.yaml:112:      flags: 0x471A1
include/i18n/en_US/form.yaml:120:      flags: 0x3101
include/i18n/en_US/form.yaml:128:      flags: 0x3101
include/i18n/en_US/form.yaml:135:      flags: 0x3101
include/i18n/en_US/form.yaml:150:      flags: 0x777A3
include/i18n/en_US/form.yaml:158:      flags: 0x3301
include/i18n/en_US/form.yaml:168:      flags: 0x3301
include/i18n/en_US/form.yaml:173:      flags: 0x3301
include/i18n/en_US/form.yaml:181:      flags: 0x3001
include/i18n/en_US/form.yaml:194:      flags: 0x470A1
include/i18n/en_US/form.yaml:202:      flags: 0x450F3
```

all of those are broken... except the commented out ones. so really, reinstalling on 5.6 is probably easier.
https://github.com/osTicket/osTicket/pull/3621

**Comment by TCBSnowsun** [comment]
Okay thanks
