### ISSUE TITLE
Requests Cancelling

### ISSUE THREAD

**Issue by mike-bailey** [osTicket/osTicket#3400]
Not sure if it's an osTicket issue (I think it is an osTicket issue since it's now happening on load) or a hosting issue, but on upgrade to the latest version and trying to view a ticket or related actions: the following request tries to run, cancels, then other requests run successfully loading it. Seems to be basically doubling load time for us. 

`Request URL:https://[redacted].net/[redacted]/scp/tickets.php?_pjax=%23pjax-container
Request Headers
Provisional headers are shown
Accept:text/html, */*; q=0.01
Content-Type:application/x-www-form-urlencoded; charset=UTF-8
Referer:https://[redacted].net/[redacted]/scp/tickets.php?id=1225
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36
X-PJAX:true
X-PJAX-Container:#pjax-container
X-Requested-With:XMLHttpRequest
Query String Parameters
_pjax:#pjax-container`

**Comment by mike-bailey** [comment]
Still no update on this?

**Comment by mike-bailey** [comment]
Hello, is osTicket now unmaintained?

**Comment by JediKev** [comment]
@mike-bailey 

No, this issue is old an has not been updated in a year. If this is still an issue please re-open.

Cheers.
