### ISSUE TITLE
installing osticket alongside Wordpress Website problem

### ISSUE THREAD

**Issue by shiko2009** [osTicket/osTicket#3401]
Hi Dears 
i am having big problem so any help will be appreciated and sorry for my bad english 
i have an wordpress website 
what i need to do is to create link that points to my osticket 
let's say that my website is www.abc .com 
so to install osticket i need to create new folder and name it (support for ex ) 
when i create support folder and extract upload content to it and then go to www.abc .com/support/setup 
it gives me no pages found 
please i need to figure out how to install osticket alongside wordpress ... i don't need to integrate my website with osticket i just need to setup osticket and i will create a new custom link that refers to my osticket location 
please help me to do that .. what's wrong ? 

Note :- i tired to give support folder all permissions with no success

**Comment by ntozier** [comment]
If you put the contents of the upload folder into your created support folder, then you would go to http://abc.com/support

The installer will run for you.  If it doesn't then you have some sort of redirection going on and your webserver isn't serving the directory you created /support.

**Comment by shiko2009** [comment]
![untitled](https://cloud.githubusercontent.com/assets/16225171/19417636/2309b2c0-93b2-11e6-9041-903d52bb7b6a.jpg)
Here's some info that would help ..
so is there any solutions for my problem ? how to do redirections to my osticket directory ?

**Comment by shiko2009** [comment]
okay very thanks @ntozier 
i resolved my problem it was because old version of php
