### ISSUE TITLE
DB Error 1142__cdata table being dropped

### ISSUE THREAD

**Issue by chowell16** [osTicket/osTicket#3403]
Initially the service account was allowed to drop tables, however when it dropped it would cause data inconsistencies in the system, therefore I took away the permission and now get the following error.

[DROP TABLE IF EXISTS `ost_ticket__cdata`]

DROP command denied to user 'pnpservice'@'localhost' for table 'ost_ticket__cdata'<br /> <br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(177): osTicket->logDBError('DB Error #1142', '[DROP TABLE IF ...')<br />
#1 (root)/include/class.dynamic_forms.php(332): db_query('DROP TABLE IF E...')<br />
#2 (root)/include/class.dynamic_forms.php(360): TicketForm::dropDynamicDataView()<br />
#3 [internal function]: TicketForm::updateDynamicDataView(Object(DynamicFormEntryAnswer), Array)<br />
#4 (root)/include/class.signal.php(98): call_user_func_array(Array, Array)<br />
#5 (root)/include/class.orm.php(235): Signal::send('model.updated', Object(DynamicFormEntryAnswer), Array)<br />
#6 (root)/include/class.dynamic_forms.php(1017): VerySimpleModel->save()<br />
#7 (root)/include/class.ticket.php(2294): DynamicFormEntry->save()<br />
#8 (root)/scp/tickets.php(230): Ticket->update(Array, Array)<br />
#9 {main}

**Comment by tanejakaran** [comment]
Same issue, I am facing on (v1.9.14) 

Any solutions please help me out?

**Comment by mfelber** [comment]
The cdata tables are materialized views. In this tables osticket collects data from other tables in order to avoid complex queries. So osTicket needs to drop and rebuild this tables constantly! You should not touch this tables and you should allow to drop it..

**Comment by tanejakaran** [comment]
how to avoid db error coming due to this?

**Comment by mfelber** [comment]
I think you cannot avoid it yet. The developers have considered to mute this error: https://github.com/osTicket/osTicket/issues/1545#issuecomment-129032871

**Comment by ntozier** [comment]
"DROP command denied to user 'pnpservice'@'localhost' for table 'ost_ticket__cdata'"
^
Give your DB user access to the DROP command.
