### ISSUE TITLE
File Attachments Error

### ISSUE THREAD

**Issue by skeeph** [osTicket/osTicket#3406]
Hello. I am using Osticket-develop branch and I want to create tickets via API. I send 

`{'email': 'api@osticket.com', 'source': 'API', 'attachments': [{'1.txt': 'data:text/plain;base64,base64Encoded'}], 'alert': True, 'subject': 'Testing API', 'name': 'Angry User', 'ip': '127.0.0.1', 'phone': '3185558634X123', 'auto
respond': True, 'message': 'MESSAGE HERE'}`

to **/api/http.php/tickets.json**. But I got error

`b'<br />\n<b>Catchable fatal error</b>:  Object of class AttachmentFile could not be converted to string in <b>\\include\\class.orm.php</b> on line <b>1638</b><br />\n'` 

and 200 http code.

Ticket is created, but here is comment **: Unable to save file** rather than attached files. What am i doing wrong? Thanks

**Comment by bandwidth543** [comment]
I have this same problem.

I sent the following JSON to the osticket's API:
```
{"email":"test@email.com","name":"test name","subject":"test subject","message":"data:text\/plain,test message","attachments":{"testfile.txt":"data:text\/plain;charset=utf-8,content of attachment"}}
```

osticket's API created this ticket and returned an ID to me. `Ticket ID: 490139`

After logging into the system, the ticket attachment was not added. `SYSTEM; File Import Error; Unable to save file`

![1](https://user-images.githubusercontent.com/73256190/97112940-6c96a300-16e7-11eb-888e-25352ebbcd53.png)
![2](https://user-images.githubusercontent.com/73256190/97112941-6ef8fd00-16e7-11eb-967a-77aa3a4ac7cb.png)

What am I doing wrong? What causes this error?
