### ISSUE TITLE
onNewTask routine missing

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket#3407]
onNewTask routine missing from class.task.php

No way to send out alerts on new task???

**Comment by jdelhome3578** [comment]
Also, on new task an email is sent but an error occurs.  
Template Fetch Error
Unable to fetch "" template - id #0

**Comment by mfelber** [comment]
This seems to be not solved. Even in the latest osTicket 1.10. No "New Task Alert" or "Overdue Task Alert" will be send..

**Comment by DonCep** [comment]
Hi mixrat, 

You was change something ? Because v1.10.1 isn't working. Only sending Task Assigment Alert, Task Transffer Alert and New Activity Alert. But missing New Task Alert and Overdue. 

And didn't any solution on this error

**Comment by mixrat** [comment]
I received this from the server after creating a test task...
![image](https://user-images.githubusercontent.com/20234985/37511543-12d16828-2964-11e8-9f99-169ff77afd1e.png)

**Comment by DonCep** [comment]
Yes this is  Assigment Alert, but Agent who create Task didn't get email that he create task.

**Comment by mixrat** [comment]
OK. Sorry for the confusion.

**Comment by DonCep** [comment]
I just want to ask, You getting all the 5 alerts ?

**Comment by mixrat** [comment]
I do not get the new ticket notice, nor do I get the overdue notice. Other notices seem to work.

**Comment by jdelhome3578** [comment]
Fixed with #5381

**Comment by JediKev** [comment]
@jdelhome3578 

Sorry, I was going to post the pull here after it has been approved. I’m sure things will change a bit with the pull’s code so I didn’t want to link it just yet. With this being said, thank you for posting an update.

Everyone looking for a fix please follow the thread linked by @jdelhome3578 above.

Cheers.
