### ISSUE TITLE
Error Viwe Ticke V1.10

### ISSUE THREAD

**Issue by vollesmetal** [osTicket/osTicket#3413]
Hello everyone I am using version 1.10 and when I click to view an open ticket it me appears as shown in the image below.

![ticket](https://cloud.githubusercontent.com/assets/20096321/19604175/ef527770-9792-11e6-9a62-34ea5fdf6540.png)

![ticket02](https://cloud.githubusercontent.com/assets/20096321/19604178/f3c5a91c-9792-11e6-8d4a-461cd148e6f7.png)

Has anyone ever seen something like that?

**Comment by ntozier** [comment]
You cannot be running 1.10 it not only hasn't been released yet but there is no tag for downloading it here on guthub.  You must be running 1.10dpr, 1.10rc1, 1.10rc2, or 1.10rc3.  So.... which one is it?  (ADmin panel -> Dashboard -> Information.

My guess is that you have an error being thrown.  With out any version information and the error (PHP or webserver error logs) it would he really hard to diagnose your issue.

My 1.10rc* test servers have not had this issue, so it likely has something to do with your setup or software versions.

**Comment by vollesmetal** [comment]
v1.10-rc.3 (907ec36)
Only displays those messages:


![timezone](https://cloud.githubusercontent.com/assets/20096321/19604596/bef45362-9794-11e6-9be1-4247f80a2dc8.png)

**Comment by ntozier** [comment]
Great!  We have a version.  So now we're just waiting for your error messages.

**Comment by vollesmetal** [comment]
my last log

[Fri Oct 21 13:42:03 2016] [error] [client 179.183.42.218] PHP Fatal error:  Call to undefined method QuerySet::findFirst() in /home/storage/3/b8/f3/fdta/public_html/suporte/include/class.dept.php on line 341, referer: http://www.fdta.com.br/suporte/scp/index.php
[Fri Oct 21 13:42:09 2016] [error] [client 179.183.42.218] PHP Fatal error:  Call to undefined method QuerySet::findFirst() in /home/storage/3/b8/f3/fdta/public_html/suporte/include/class.dept.php on line 341, referer: http://www.fdta.com.br/suporte/scp/tickets.php?status=assigned
[Fri Oct 21 13:42:42 2016] [error] [client 179.183.42.218] PHP Fatal error:  Call to undefined method QuerySet::findFirst() in /home/storage/3/b8/f3/fdta/public_html/suporte/include/class.dept.php on line 341, referer: http://www.fdta.com.br/suporte/scp/tickets.php?status=assigned
[Fri Oct 21 13:51:26 2016] [error] [client 179.183.42.218] PHP Fatal error:  Call to undefined method QuerySet::findFirst() in /home/storage/3/b8/f3/fdta/public_html/suporte/include/class.dept.php on line 341, referer: http://www.fdta.com.br/suporte/scp/index.php
[Fri Oct 21 13:53:52 2016] [error] [client 179.183.42.218] mod_mime_magic: invalid type 0 in mconvert()., referer: http://www.fdta.com.br/suporte/css/font-awesome.min.css?907ec36
[Fri Oct 21 13:54:48 2016] [error] [client 179.183.42.218] PHP Fatal error:  Call to undefined method QuerySet::findFirst() in /home/storage/3/b8/f3/fdta/public_html/suporte/include/class.dept.php on line 341, referer: http://www.fdta.com.br/suporte/scp/tickets.php?status=open

**Comment by vollesmetal** [comment]
[Sat Oct 22 11:38:06 2016] [error] [client 179.183.42.218] mod_mime_magic: invalid type 0 in mconvert()., referer: http://www.fdta.com.br/suporte/css/font-awesome.min.css?907ec36
[Sat Oct 22 11:38:22 2016] [error] [client 179.183.42.218] PHP Fatal error:  Call to undefined method QuerySet::findFirst() in /home/storage/3/b8/f3/fdta/public_html/suporte/include/class.dept.php on line 341, referer: http://www.fdta.com.br/suporte/scp/
[Sat Oct 22 12:04:16 2016] [error] [client 179.183.42.218] mod_mime_magic: invalid type 0 in mconvert()., referer: http://fdta.com.br/suporte/css/font-awesome.min.css?907ec36
[Sat Oct 22 12:04:57 2016] [error] [client 179.183.42.218] PHP Fatal error:  Call to undefined method QuerySet::findFirst() in /home/storage/3/b8/f3/fdta/public_html/suporte/include/class.dept.php on line 341, referer: http://www.fdta.com.br/suporte/scp/tickets.php

**Comment by vollesmetal** [comment]
Line 341-342

 return ($members->findFirst(array(
                        'staff_id' => $staff)));

**Comment by vollesmetal** [comment]
I found looking in the database that ost_ticket table -> column staff_id this by assigning the number zero when you open the ticket, so that I can not see the ticket, then I assign the ticket to my agent, then I can see if I assign to the team for example Support I can not view the ticket even when assigned to support staff

**Comment by vollesmetal** [comment]
Another mistake is also when I create the ticket by admin panel to the customer, when I click "create" the page error and when I go on the ticket the ticket is created but it is not assigned to anyone.
![abrindo ticket](https://cloud.githubusercontent.com/assets/20096321/19620177/e63b015c-9855-11e6-8dbe-d535766e848f.png)

![ticker blan](https://cloud.githubusercontent.com/assets/20096321/19620179/08287f92-9856-11e6-83f5-e65de117d292.png)

**Comment by vollesmetal** [comment]
How to solve this problem?

**Comment by vollesmetal** [comment]
My problem is not the same as its @jakobii
