### ISSUE TITLE
1.10 RC3 :: Item Abbreviation Update

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket#3416]
Unable to edit the item Abbreviation field for lists.

**Comment by ntozier** [comment]
Version of osTicket?
How to replicate your report?
a screen shot showing what you are talking about?

**Comment by jdelhome3578** [comment]
Version number in subject!!!!

Open a custom list, click on an item, change Abbreviation value, click save. Does not save!

**Comment by ntozier** [comment]
So Admin panel -> Manage -> lists.
I click on my list.
I click on my item.
I type something in Abbreviation.
I click Save.

It saves as expected.
I have tried this twice now.  Once changing the abbrev on something and again to change it back..  I am unable to replicate your report.

**Comment by jdelhome3578** [comment]
Looks like I applied 52cb1d8

**Comment by jdelhome3578** [comment]
Fixed with PR #3446
