### ISSUE TITLE
Client email reply to ticket opens as new ticket number

### ISSUE THREAD

**Issue by jonub** [osTicket/osTicket#342]
In some random instances when a client replies by email to an open or closed ticket it creates a new ticket despite being the same email address and the ticket number is in the subject. The latest instance was an out of office reply but I would have thought that should make no difference (Subject: "Out of Office: Ticket #XXXXXX Reply Re: Ac.....") . The ticket was open, it had already been replied to previously by email and inserted into the correct ticket, but in this instance it created a new ticket.

incoming email piping used
ost v1.8.0.1

**Comment by ulfkreutzberg** [comment]
Hi greezybacon,
hi all,

I am using osTicket v1.9.12 (19292ad) and a reply to a custom id 
Re: Test34 [#FFGM15-00019]
does not re-open a closed Ticket, instead a new Ticket with a new id is generated. 
Do you support alphanumerical ids or do you only support numbers?

Many thanks and best regards,
Ulf

**Comment by ntozier** [comment]
If I remember correctly the allow reopen tick box logic is reverse in Admin panel -> Manage -> Lists -> Statuses -> Items -> Closed -> Properties.

**Comment by ulfkreutzberg** [comment]
Thanks for this hint. I had to change the default value of "Allow user to reopen..." from "system standard" to "open" - now it works. Thank you!

**Comment by mariusdinca** [comment]
Hello all,
Wonder if you could help.
I have os Ticket v.1.9.12 and for a while now it started gliching.
Up until now when we replied to an email that had already created an issue that reply was noted as an update/note in the ticket, now it simply creates a new ticket and its frustrating.

**Comment by ntozier** [comment]
@mariusdinca this is a **closed** bug report for version 1.8.0.1 from December 2013.
I would suggest that you try what is commented above, and if it doesn't work for you upgrade to current.
Then if it still doesn't work for you then post on the forums.  https://osticket.com/forums
