### ISSUE TITLE
Open ticket status broken?

### ISSUE THREAD

**Issue by jakobii** [osTicket/osTicket#3423]
Just freshly installed v1.10-rc.3 twice on clean installs of Ubuntu 16.04. As far as I can tell the open ticket status is broken in the agent home/landing page. I must be missing something because I'm pretty sure you would have noticed this by now if that was the case.

Example
I created 3 tickets, all are assigned to a single agent(the only agent) and assigned the a same department, and they all have the status of open. I can find all three tickets when doing an advanced search for all open tickets but only two tickets show up in the "open" ticket page.
![ost_fail1](https://cloud.githubusercontent.com/assets/19825478/19713275/89de9238-9af9-11e6-86a3-feea4aec1884.png)

In my earlier tests of v1.10-rc.3, before you made resent commits to it, I could not get _anything_ to show up in the "open" page at all. now after you made recent commits things are showing up, but its hit and miss. not sure if I'm just missing something obvious.

**Comment by jakobii** [comment]
Also not sure if this is a duplicate issue of #3413. I could not understand the issue.

**Comment by 4nanook** [comment]
On Tue, 25 Oct 2016, jakobii wrote:
> 
> Just freshly installed v1.10-rc.3 twice on clean installs of Ubuntu 16.04. As 
> far as I can tell the open ticket status is broken in the agent home/landing 
> page. I must be missing something because I'm pretty sure you would have 
> noticed this by now if that was the case.

      I am getting the same thing which is why I asked if there were a way to
pull the current working pre-release from a repository as there was with v1.8
and earlier.

      Have not received a response.

**Comment by jakobii** [comment]
It appears that as soon as I enabled the form 'ticket details' and filling out ticket detail information in new tickets, the tickets started to appear in the 'open' page. sorry for the confusion.

**Comment by balojs** [comment]
Please check

settings > tickets > settings
![screenshot](https://cloud.githubusercontent.com/assets/3303352/19734666/a915fb84-9b65-11e6-9fa8-b52e85862b26.png)

**Comment by jakobii** [comment]
@bailey86 thats a good tip thank you! that may have been contributing to my misunderstanding the open tickets queue. If the default setting is to exclude tickets from the open queue once an agent comments on it, then by default the open ticket queue should be called something like "unanswered tickets". and then have a different page that truly allows to view all open tickets(according to the view permissions of the user) . but whatever, its just a little confusing at first is all. 

![image](https://cloud.githubusercontent.com/assets/19825478/19737337/e2c00c7e-9b67-11e6-9e1c-e6497e3fae7d.png)

**Comment by jakobii** [comment]
@4nanook sorry i don't quite understand what you mean. Are you looking for a "current working pre-release" of 1.10? i think that is the intent of v1.10-rc.3 .
