### ISSUE TITLE
Error when creating & opening a task. rc3 QuerySet::findFirst()

### ISSUE THREAD

**Issue by edukondalugorla** [osTicket/osTicket#3427]
Hi,
When I attempt to create a task and opening a task, errors are getting.

when creating a task, i see these errors:
 PHP Fatal error:  Call to undefined method QuerySet::findFirst() in /var/www/html/osticket/include/class.dept.php on line 341, referer: http://company.com/scp/tasks.php
 PHP Fatal error:  Call to undefined method QuerySet::findFirst() in /var/www/html/osticket/include/class.dept.php on line 341, referer: http://company.com/scp/tasks.php?id=26

when opening a task, i see these errors:
PHP Fatal error:  Call to undefined method QuerySet::findFirst() in /var/www/html/osticket/include/class.dept.php on line 341, referer: http://company.com/scp/tasks.php?status=open
 PHP Fatal error:  Call to undefined method QuerySet::findFirst() in /var/www/html/osticket/include/class.dept.php on line 341, referer: http://company.com/scp/tasks.php?status=open
PHP Fatal error:  Call to undefined method QuerySet::findFirst() in /var/www/html/osticket/include/class.dept.php on line 341, referer: http://company.com/scp/tasks.php?id=26

 Osticket version, congfiguration info:
    osTicket Version    v1.10-rc.3 (907ec36) —  Up to date
    Web Server Software Apache/2.4.7 (Ubuntu)
    MySQL Version   5.6.27
    PHP Version 5.5.9-1ubuntu4.20

**Comment by JediKev** [comment]
This was addressed in commit 393a7d22.
