### ISSUE TITLE
osTicket (v1.10-rc.3) - Unable to add FAQs. No option

### ISSUE THREAD

**Issue by ramkinavy** [osTicket/osTicket#3428]
I have added a new category in the knowledge base as Admin

im not seeing any option to add FAQ under the category. please check

**Comment by jakobii** [comment]
you need to add a category first.

**Comment by jakobii** [comment]
![selection_003](https://cloud.githubusercontent.com/assets/19825478/19773671/55535590-9c1f-11e6-8de8-f2461017cf9b.png)

**Comment by ramkinavy** [comment]
I have already added the category but still not showing 

Get Outlook for iOS




On Thu, Oct 27, 2016 at 8:56 PM +0530, "jakobii" <notifications@github.com> wrote:












you need to add a category first.

**Comment by ramkinavy** [comment]
<img width="1015" alt="screen shot 2016-10-27 at 9 18 10 pm" src="https://cloud.githubusercontent.com/assets/8140237/19774512/f87c9806-9c8a-11e6-9e05-5861cd0d88e5.png">
<img width="991" alt="screen shot 2016-10-27 at 9 18 00 pm" src="https://cloud.githubusercontent.com/assets/8140237/19774513/f8d63f50-9c8a-11e6-9552-7b2512e719d3.png">

**Comment by ramkinavy** [comment]
Also these categories dont get listed in the list as below
<img width="1013" alt="screen shot 2016-10-27 at 9 19 59 pm" src="https://cloud.githubusercontent.com/assets/8140237/19774575/328ade9a-9c8b-11e6-9713-ba4086f9425a.png">

**Comment by ntozier** [comment]
Is this 907ec36? (Admin Panel -> Dashboard -> Information)
Did you search issues? https://github.com/osTicket/osTicket/issues/3338

**Comment by ramkinavy** [comment]
yes 907ec36

**Comment by ipAnything** [comment]
Fix can be found at [**faq: Fix crash rendering list of categories  #3216**](https://github.com/osTicket/osTicket/pull/3216/files)

Just change **Line 144** of `include/staff/faq-categories.inc.php `

**FROM**
     `->all();  `
 **TO** 
     `->getIterator(); `

**Comment by ramkinavy** [comment]
thanks hope this should work for listing the categories and also solve the FAQ creation problem

**Comment by jakobii** [comment]
![selection_004](https://cloud.githubusercontent.com/assets/19825478/19776596/91161644-9c29-11e6-9a41-3753e98df850.png)
![selection_005](https://cloud.githubusercontent.com/assets/19825478/19776631/b42a21de-9c29-11e6-8c50-8da01c280f5c.png)
once you create a category, go back to the FAQ's page click on the category you just created, then you should see the button "Add New FAQ"

**Comment by JediKev** [comment]
@ramkinavy This issue has been fixed on the tip of develop branch.
