### ISSUE TITLE
After upgrading to V1.10 RC3 

### ISSUE THREAD

**Issue by paul-developerconnections** [osTicket/osTicket#3434]
This blank message appears when I click on the Transfer Button

![image](https://cloud.githubusercontent.com/assets/12858602/19865921/22529b22-9f96-11e6-98f3-c74cd8375243.png)

Error Log...

PHP Fatal error:  Uncaught Exception: TransferForm: Unknown template style  in /var/www/www.developerconnections.net/public_html/support/include/class.forms.php:4248\nStack trace:\n#0 /var/www/www.developerconnections.net/public_html/support/include/staff/templates/transfer.tmpl.php(43): TransferForm->render(Array)\n#1 /var/www/www.developerconnections.net/public_html/support/include/ajax.tasks.php(510): include('/var/www/www.de...')\n#2 /var/www/www.developerconnections.net/public_html/support/include/class.dispatcher.php(145): TasksAjaxAPI->transfer('11')\n#3 /var/www/www.developerconnections.net/public_html/support/include/class.dispatcher.php(38): UrlMatcher->dispatch('11/transfer', Array)\n#4 /var/www/www.developerconnections.net/public_html/support/include/class.dispatcher.php(120): Dispatcher->resolve('11/transfer', Array)\n#5 /var/www/www.developerconnections.net/public_html/support/include/class.dispatcher.php(38): UrlMatcher->dispatch('/tasks/11/trans...', NULL)\n#6 /var/www/www.developerconnections.net/public_html/support/s in /var/www/www.developerconnections.net/public_html/support/include/class.forms.php on line 4248, referer: https://www.developerconnections.net/support/scp/tasks.php?id=11

**Comment by markus4000** [comment]
i have 1.10development running, and I don't have this issue.

**Comment by ntozier** [comment]
Do you get this behavior when opening a new ticket (on the search for user dialogue)?
or anywhere else?

Also you have not provided any web server information [Webserver software, php versions etc].

**Comment by 4nanook** [comment]
I just pulled the most recent from github (git clone) and I am seeing
the following two error messages on the admin panel after logging in:

Warning: Declaration of AssignmentForm::render($options) should be compatible 
with Form::render($staff = true, $title = false, $options = Array) in 
/misc/www/home/support/osticket/include/class.forms.php on line 4150

Warning: Declaration of TransferForm::render($options) should be compatible 
with Form::render($staff = true, $title = false, $options = Array) in 
/misc/www/home/support/osticket/include/class.forms.php on line 4270

      This is with PHP7.

      I also get this when I go to the main page not logged in:

Warning: Declaration of AssignmentForm::render($options) should be compatible 
with Form::render($staff = true, $title = false, $options = Array) in 
/misc/www/home/support/osTicket/include/class.forms.php on line 4150

Warning: Declaration of TransferForm::render($options) should be compatible 
with Form::render($staff = true, $title = false, $options = Array) in 
/misc/www/home/support/osTicket/include/class.forms.php on line 4270

      When I say open a new ticket and then select a topic, it tells me:


Support ticket request created
,

Thank you for contacting us.

A support ticket request has been created and a representative will be getting 
back to you shortly if necessary.



Support Team

      But it never gave me a chance to type any text it for the ticket.  I also
get those same two errors on the top of this form.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by jdelhome3578** [comment]
Have you tried #3266?

**Comment by 4nanook** [comment]
What version of PHP?  I only have problems since upgrading to PHP7.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by paul-developerconnections** [comment]
I have updated to the latest version from yesterday all issues have now been resolved

Thanks to everyone for their help
