### ISSUE TITLE
Edit mode of the task, Due Date is not being displayed for modification.

### ISSUE THREAD

**Issue by edukondalugorla** [osTicket/osTicket#3435]
Hi,

When I open edit mod of a task. duedate edit option is not displaying. how to update duedate of a task?

 Osticket version, congfiguration info:
	osTicket Version	v1.10-rc.3 (907ec36) —  Up to date
	Web Server Software	Apache/2.4.7 (Ubuntu)
	MySQL Version	5.6.27
	PHP Version	5.5.9-1ubuntu4.20

**Comment by ntozier** [comment]
Do you mean this?
https://github.com/osTicket/osTicket/pull/3430

**Comment by edukondalugorla** [comment]
how to edit  due date of a task.

**Comment by ntozier** [comment]
Did you read the link?
