### ISSUE TITLE
Email messages do not merge in osTicket v1.10

### ISSUE THREAD

**Issue by Danteba** [osTicket/osTicket#3440]
In osTicket v1.10-rc.2 when a user sent a email message with the same subject of an already created ticket, the email message was inserted as a new post on the  initial ticket.

For example:

1. The user-a@test.com send a email message to support@test.com with subject: "Need your assistance" with CC to user-b@test.com
1.  A new ticket is created with the title "Need your assistance"
1. The user-b@test.com reply to all senders (with the same subject)
1. The message from user-b@test.com is **appended (merged) to the original ticket.**
1. So, there is just one ticket called "Need your assistance" with the messages from user-a@test.com and user-b@test.com

After the installation of the osTicket v1.10 this behaviour was broken:

1. The user-a@test.com send a email message to support@test.com with subject: "Need your assistance" with CC to user-b@test.com
1. A new ticket is created with the title "Need your assistance"
1. The user-b@test.com reply to all senders (with the same subject)
1. The message from user-b@test.com **CREATES a NEW ticket** (with the same subject).
1. So, there are two tickets called "Need your assistance", one with the messages from user-a@test.com and the other with the message of user-b@test.com

Is this an expected behaviour? Or is it a bug?

Thank you for your work, and sorry for my english! :)

**Comment by Danteba** [comment]
I found a workaround to this problem.

Just add the following lines at /includes/class.mailfetch.php after line 687 :

```
        $vars['references'] = $mailinfo['references'] ?: null; // Issue #3440 workaround
        $vars['in-reply-to'] = $mailinfo['in-reply-to'] ?: null; // Issue #3440 workaround
```

**Comment by ericLemanissier** [comment]
thanks for the fix. Could you make a pull request ?

**Comment by cbiere** [comment]
@Danteba: Thanks a bunch! This fixed the problem in our installation of osTicket 1.10. Despite having [#%Ticketid] in the subject, responses by e-mail (from agents) created a new ticket.
