### ISSUE TITLE
[Feature Request] Manage -> Plugins should display plugin version (1.10)

### ISSUE THREAD

**Issue by ntozier** [osTicket/osTicket#3443]
When you install a new plugin in osTicket it displays the version of the plugin that you are trying to install.
(aka when you go do Admin panel -> Manage -> Plugins -> Add New Plugin)

However after its installed when you go to Admin panel -> Manage -> Plugins there is no column for nor a display of the version of the plugin installed.   Preferably this should be displayed here (but I would settle for when you click on the installed plugin)

Rational: this will allow people to quickly and easily see what version of the plugin they have installed so that when they upgrade they can check and see if a new version of the plugin is available.

**Comment by Chefkeks** [comment]
I second that idea :+1:
