### ISSUE TITLE
[Feature Request] add Tasks to scroll menu -OR- add second tab on Reply area. [1.10]

### ISSUE THREAD

**Issue by ntozier** [osTicket/osTicket#3445]
To view tasks associated with a ticket you have to click on the Tasks tab.  This is good and fine, but with the autoscroll and long tickets you have to scroll all the way back up (or click the scroll up button on the scroll menu).  It would be nice if you could access tasks with out having to scroll back up to the top of the ticket either by adding the tasks tab also to the reply area i.e. Post Reply (tab) | Post Internal Note (tab) | Tasks (tab) -or- by adding a Tasks button on the scrolling menu bar.

If you need a mock up let me know and I can make one.

**Comment by markus4000** [comment]
:+1:
