### ISSUE TITLE
Include full thred in mail replies

### ISSUE THREAD

**Issue by max36010** [osTicket/osTicket#3447]
Email body only contains last reply text. It'sdifficult for the recipient to recapitulate the  full thread.

**Comment by ntozier** [comment]
Correct.  But they can log into the ui and see the complete ticket.  Every response has links in it to do so.

**Comment by ntozier** [comment]
You can also utilize other variables like some of these:
%{ticket.thread.original} for the first message
%{ticket.thread.lastmessage}

**Comment by 4nanook** [comment]
What is the best way to report a problem with v1.10?

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by rayfoss** [comment]
unintelligible. You should report bugs here. For guidelines on doing so  https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines

**Comment by marcinkorzycki** [comment]
Can we refresh this topic?
