### ISSUE TITLE
v1.10 Upgrade - Error 422/500 & DB Error #1146

### ISSUE THREAD

**Issue by shausman** [osTicket/osTicket#3448]
Upgraded from v1.9.14 to v1.10
![server information](https://cloud.githubusercontent.com/assets/8027043/19946271/04be4e50-a11a-11e6-89a5-e2a76f5cea49.jpg)

- Downloaded the latest release from https://github.com/osTicket/osTicket/releases/tag/v1.10
- Took offline
- Copied (& replaced) unpacked v1.10 files
  - was not prompted to upgrade until after I copied the files over, Server Information page said 1.9.14 was up to date
- Opened admin panel, upgrader opened & completed
- Brought back online, Landing page looks good, attempted to login & submit ticket
  - Getting 422 after clicking "Sign In", 500 error after logging in with LDAP credentials (the same ones that work in /scp/)
![422 500 error](https://cloud.githubusercontent.com/assets/8027043/19946178/a8b85d58-a119-11e6-9826-e66086193337.jpg)
- Checked system logs, DB Error #1146
![default](https://cloud.githubusercontent.com/assets/8027043/19945598/439bd884-a117-11e6-8c09-7c284ea18a6d.jpg)

Aside from attempting to revert to 1.9.14 I'm at a bit of a loss. Please let me know if I can provide any additional logs &/or screenshots.

**Comment by protich** [comment]
What errors are you seeing in your web server logs?

**Comment by shausman** [comment]
@protich Sounds like I need more coffee to have forgotten about that...

`[Wed Nov 02 17:07:38.539136 2016] [:error] [pid 5816:tid 836] [client 10.1.165.163:57740] PHP Fatal error:  Access level to Net_LDAP2_RootDSE::__construct() must be public (as in class PEAR) in phar://C:/Apache24/htdocs/ticket/include/plugins/auth-ldap.phar/include/Net/LDAP2/RootDSE.php on line 238, referer: http://10.22.48.7/ticket/login.php
`

**Comment by ntozier** [comment]
re: your edits: I was just going to point that out. :)

**Comment by protich** [comment]
@shausman - I'm working on packaging a new version of the plugin.
