### ISSUE TITLE
onTicketCreated: getSubject not working in v1.10

### ISSUE THREAD

**Issue by drtomasso** [osTicket/osTicket#3449]
Hi

After upgrading to v1.10, my plugin for sending notification to Telegram isn't getting the subject anymore. Rest of the information is working, just not `$ticket->getSubject()`.

Has the method on how to get ticket subject changed?

https://github.com/drtomasso/osticket-telegram/blob/master/telegrambot/telegrambot.php#L20

**Comment by JediKev** [comment]
It has not changed a bit. This is [class.ticket.php](https://github.com/osTicket/osTicket/blob/develop/include/class.ticket.php#L457-L459). You might want to contact the developers of the plugin.

**Comment by drtomasso** [comment]
Well, something has changed. I had to change the plugin to use signal `ticket.created` instead of `model.created` to make it work again.

Looking forward to a documented API. That would really boost development of plugins, integrations and maybe even apps.

Anyway, closing this as this is now solved.
