### ISSUE TITLE
Sort error for banlist.inc.php

### ISSUE THREAD

**Issue by tmp2000** [osTicket/osTicket#3452]
Under develop branch and 1.9.8.1 version(might other version also have the same error), line 113-116 in banlist.inc.php , the string "staff.php" should be changed to "banlist.php" .Otherwise ,the sort would not work which mentioned in issue #1725 .

                <th width="56%"><a <?php echo $email_sort; ?> href="staff.php?<?php echo $qstr; ?>&sort=email"><?php echo __('Email Address');?></a></th>
                <th width="10%"><a  <?php echo $status_sort; ?> href="staff.php?<?php echo $qstr; ?>&sort=status"><?php echo __('Ban Status');?></a></th>
                <th width="10%"><a <?php echo $created_sort; ?> href="staff.php?<?php echo $qstr; ?>&sort=created"><?php echo __('Date Added');?></a></th>
                <th width="20%"><a <?php echo $updated_sort; ?> href="staff.php?<?php echo $qstr; ?>&sort=updated"><?php echo __('Last Updated');?></a></th>

to 

            <th width="56%"><a <?php echo $email_sort; ?> href="banlist.php?<?php echo $qstr; ?>&sort=email"><?php echo __('Email Address');?></a></th>
            <th width="10%"><a  <?php echo $status_sort; ?> href="banlist.php?<?php echo $qstr; ?>&sort=status"><?php echo __('Ban Status');?></a></th>
            <th width="10%"><a <?php echo $created_sort; ?> href="banlist.php?<?php echo $qstr; ?>&sort=created"><?php echo __('Date Added');?></a></th>
            <th width="20%"><a <?php echo $updated_sort; ?> href="banlist.php?<?php echo $qstr; ?>&sort=updated"><?php echo __('Last Updated');?></a></th>

**Comment by ntozier** [comment]
So 1.9.8.1 is really old at this point.  You should really update your version.

**Comment by JediKev** [comment]
I have a [Pull Request](https://github.com/osTicket/osTicket/pull/3455) that is pending on this issue. Thank you.
