### ISSUE TITLE
v. 1.10 - Replies log me out [SOLVED]

### ISSUE THREAD

**Issue by GreenDragonTech** [osTicket/osTicket#3454]
Since the upgrade to 1.10, every time I reply to a ticket, it logs me out.  I've tested and the recipients are receiving their emails and everything posts correctly, but it's annoying to have to log back in every time.

Is nobody else having this problem?

**Comment by robintoy** [comment]
I used to get this on 1.10-rc.3 and raised it as a issue but not sure if solved

**Comment by ntozier** [comment]
@GreenDragonTech  I'm not having this problem.   You should probably include system information (software and versions) and check webserver error logs and php error logs.

Side thought... did you clear your browser cache after upgrading?

**Comment by GreenDragonTech** [comment]
I'll see if I can find the logs, but clearing my browser cache did not help.

**Comment by GreenDragonTech** [comment]
I found the logs on my server. See attached. I don't know what to do with them Any ideas would be appreciated.
[mysite.txt](https://github.com/osTicket/osTicket/files/569547/mysite.txt)

**Comment by mmurshid** [comment]
@ntozier  it works fine on the localhost,but when hosted to another live server it logg out,could you test on your end?
@GreenDragonTech  did you manage to solve the issue? if yes kindly share with me,i am facing same issue.

**Comment by mmurshid** [comment]
@robintoy  do u have same problem? kindly assist

**Comment by ntozier** [comment]
@mmurshid there is no way that I can replicate what you are saying as I do not use the same host as you.  However if it works locally and does not work when you move it remotely then its a pretty fair presumption that something about the remote hosts config is borking it.  I would recommend that you compare the software versions, and configurations between the local and remote hosts.  Most of the time when someone see's something like this they are running afoul their ISPs mod_security rules (or other "security" configuration).

**Comment by GreenDragonTech** [comment]
@mmurshid  No, not yet. I still face this problem and was surprised nobody else has reported it. I wish I had a solid answer. I've tried adjusting many things, but nothing has solidly affirmed a conclusion.

**Comment by GreenDragonTech** [comment]
**SOLVED!!!!** @mmurshid , @ntozier gave me an idea. I switched PHP version from 5.5 to **7.0** and it resolved the problem! Solution: If you run cPanel, go to PHP Selector and choose 7.0 in the drop down. Otherwise, contact your host and ask them.

**Comment by mmurshid** [comment]
thanks to you guys.. @GreenDragonTech  and @ntozier , i have upgraded to ver 5.7 and it works fine.Be Blessed guys.

**Comment by ntozier** [comment]
@protich @JediKev 
I'm not sure that this is solved since I have a few people on the forums posting saying similar things.

Here are a few of them:
http://osticket.com/forum/discussion/89270/when-i-submit-a-comment-on-a-ticket-i-have-to-login-again
http://osticket.com/forum/discussion/89277/reply-ticket-logout-always

**Comment by GreenDragonTech** [comment]
@ntozier I marked it solved because I opened this forum, and I found a solution that worked for me.

**Comment by bhenie** [comment]
there is another way to fix without upgrade php version ?

**Comment by Nuviware** [comment]
Marking a bug "Solved" by changing the php version isn't the solution to the problem.
The problem is in the code and it can be solved ;-)

**Comment by gazzaluty** [comment]
This problem doesn't occur in Firefox?

**Comment by CelticWebSolutions** [comment]
I have exactly the same issue, though I am running Php 7.  Has any investigation been done on the code side of this issue?

**Comment by dgismondi** [comment]
Hola, al editar un ticket el sistema cierra sesión y vuelve al inicio para login. Es incomodo y no se si es bug o configuración. Gracias !
Estoy utilizando la v1.10 y mi hosting solo tiene disponible hasta la versión de php 5.6.

Alguna sugerencia?

**Comment by eKKiM1** [comment]
I was experiencing the same issue with PHP 5.4
Since no descent fix was ever supplied afaik i started digging in the code.

i noticed (or cant find where) that the constructor of the osTicketSession is not called anywhere?
This function starts the PHP session.

I made a quick work around (no idea if it influences other things..) by adding the following lines add the end of ./include/class.ostsession.php (before ?> ofcourse)

`session_name("OSTSESSID");
session_start();`

it's a dirty work around and probably breaks other functionality. However, i hope that a dev now has an idea where to look to fix this issue.

**Comment by juniorpires** [comment]
In my case, this always happen if the option "Avoid Collision" is enable. If it is set to 0 (zero) the error don't occur.

**Comment by dgismondi** [comment]
where change this value ?? thanks

**Comment by JediKev** [comment]
**Admin Panel > Settings > System > Collision Avoidance Duration**

**Comment by dgismondi** [comment]
El parámetro mas parecido es "Duración del filtro de colisión" estaba en 3 minutos y lo lleve a 0 y sigue sin funcionar, al editar un ticket de cierra la sessión. gracias !

**Comment by fthomas137** [comment]
Well, I'm glad it's just not me but I'm sad that there is no clear fix. I'm currently running osTicket version 1.9.14 and php version 5.6.16.

**Comment by ntozier** [comment]
@fthomas137  The subject for this issue report states "Solved". Perhaps your issue is that you are running an outdated version.

**Comment by thetwopct** [comment]
Changing the Collision Avoidance Duration to 0 has not solved the problem for me. I am running PHP 5.6

**Comment by ntozier** [comment]
@thetwopct 
version of osticket?
Have you tried upgrading PHP to 7 like the original posted recommended?

**Comment by ntozier** [comment]
@lucasmontec We do not supper PHP 7.1+ at this time.

**Comment by CosmaP** [comment]
I am still getting this issue.  I am on 1.10 of osTicket.

I have tried all the available PHP versions 5.4, 5.5, 5.6, 7.0, 7.1  and it makes no difference.

What now?

Thanks

**Comment by ntozier** [comment]
@CosmaP 
System environment?
Error logs?
Did you try the three things mentioned in this post or just 1 (change php ver)?
maybe upgrade to current (1.10.4) as of this response?

**Comment by CosmaP** [comment]
* System environment?*  I believe it is a Linux server.  It is hosted with
TSOHost
*Error logs?* How do I extract them?
*Did you try the three things mentioned in this post or just 1 (change php
ver)?* Yes
*maybe upgrade to current (1.10.4) as of this response? *It already was at
1.10.4

[image: image.png]


*________________________________*

*Cosma *

.

*P* *Please consider the environment*
*Save paper - do you really need to print this email?*

*Save electricity - do you really need to send this email? Save your own
energy - do you really need to read this email?*

**Comment by ntozier** [comment]
> * System environment?*  I believe it is a Linux server.  It is hosted with
> TSOHost

apache?  php ver?

> *Error logs?* How do I extract them?

Depends on your environment.  You would talk to TSOHost about how to see your php and <unknown webserver> logs.

**Comment by CosmaP** [comment]
Apache - Waiting for the host to let me know
Php - 5.5

Log attached


*________________________________*

*Cosma *

Mobile: 07956 323938
Skype: Cosma.Papouis

*P* *Please consider the environment*
*Save paper - do you really need to print this email?*

*Save electricity - do you really need to send this email? Save your own
energy - do you really need to read this email?*
