### ISSUE TITLE
Hide empty forms

### ISSUE THREAD

**Issue by greezybacon** [osTicket/osTicket#346]
If a form is empty or has no visible fields (perhaps they're all internal), then the form header should not be shown

**Comment by greezybacon** [comment]
This is fixed in the `develop-next` branch finally with `DynamicForm::hasAnyVisibleFields()`

**Comment by andrelindner** [comment]
> If a form is empty or has no visible fields (perhaps they're all internal), then the form header should not be shown

still an issue? if not, please close this issue.
