### ISSUE TITLE
osTicket v1.10 IIS LDAP not working 

### ISSUE THREAD

**Issue by iArjan** [osTicket/osTicket#3460]
Hello,

On IIS PHP v.5.6 you get a error when you save the LDAP settings. I made my own fix, i edited the phar file with the new php LDAP files, then it worked, you can save settings and the connection works. But when you try to login to the scp (Yes i have admin right) i get this error: "Access denied"

What is going wrong?

It synchronizes with the LDAP database because i get the list with all users and i add them to the agents.

**Comment by jdelhome3578** [comment]
Have you tried the new version v0.6.3 from http://osticket.com/download

**Comment by iArjan** [comment]
Yes, same error @jdelhome3578

**Comment by jdelhome3578** [comment]
Do you have any error messages?

**Comment by iArjan** [comment]
No, also no errors in the php error log. When i use the original ldap plugin i get a blank page and this shows in the php error logs: [04-Nov-2016 12:31:46 UTC] PHP Fatal error:  Access level to Net_LDAP2_RootDSE::__construct() must be public (as in class PEAR) in phar://D:/osticket10/include/plugins/auth-ldap.phar/include/Net/LDAP2/RootDSE.php on line 238

With my edited ldap plugin it works fine, he also find the users but when i try to login in the scp i get: "Access denied"

**Comment by jdelhome3578** [comment]
Can you edit the settings for the LDAP Plugin? What version of AD?

**Comment by iArjan** [comment]
Yes with my edited plugin for LDAP i can edit, with the original one i cannot.

The version AD we are using is: 2003

**Comment by iArjan** [comment]
Edit: With osTicket 9.11 everything worked fine.

**Comment by ntozier** [comment]
I'm running IIS 8.5, php 5.6.12 and I do not have this problem anymore.  Fixing it required a couple changes to the plugin all of which have been pushed to the new v0.6.3. 

I would suggest that you: 
1. disbale the ldap plugin in osTicket.
2. delete the ldap plugin in osTicket
3. delete the plugin from the file system /include/plugins [do not rename it, delete it or move it from the folder to your desktop]
4. download the plugin from osticket.com/download
5. put the new plugin in the /include/plugins folder
6. Add the plugin in osTicket.
7. Configure the plugin in osTicket.

Please let us know if you can now save.

**Comment by iArjan** [comment]
It didn't work. When i enter my LDAP data and press submit i get a white  page.

PHP error log:

[04-Nov-2016 14:34:40 UTC] PHP Fatal error:  Access level to Net_LDAP2_RootDSE::__construct() must be public (as in class PEAR) in phar://D:/osticket10/include/plugins/auth-ldap.phar/include/Net/LDAP2/RootDSE.php on line 238

**Comment by protich** [comment]
Everyone -- We did release a new version, v0.6.3, of the plugin yesterday. Simply replace your phar file.

**Comment by iArjan** [comment]
Still not working.. When i save my LDAP settings i get a blank page.
Php error log:
[07-Nov-2016 09:17:21 UTC] PHP Fatal error:  Access level to Net_LDAP2_RootDSE::__construct() must be public (as in class PEAR) in phar://D:/osticket10/include/plugins/auth-ldap.phar/include/Net/LDAP2/RootDSE.php on line 238

**Comment by iArjan** [comment]
already a solution? i tried everything but still nothing is working

**Comment by ntozier** [comment]
@iArjan did you download the new version of the LDAP plguin (0.6.3)?

**Comment by iArjan** [comment]
@ntozier Yes i did. And still not working. When i edit the phar and change it with the new Ldap PEAR files from php and compile it to a phar again it is working, I can edit the settings, i can save it etc without that blank screen. But the only thing that doesnt work is login with an ldap user i get this message: "Access denied"

**Comment by ntozier** [comment]
Did you then apply this patch to osTicket?
https://github.com/osTicket/osTicket/pull/3456

**Comment by iArjan** [comment]
Yes, i applied login for users.
And i try to apply that patch but where can i find this code:  87: ->annotate(array('relevance' => new SqlCode(1))) ?

**Comment by ntozier** [comment]
Click on this https://github.com/osTicket/osTicket/pull/3456
Click on Files Changed.

**Comment by iArjan** [comment]
Still not working...

**Comment by ntozier** [comment]
If you have downloaded the new version for osticket.com/download and performed the patch... then i am not sure what the problem would be. Have you consulted the IIS error logs and PHP error logs?

**Comment by iArjan** [comment]
Still not working. I will wait until the new release of osTicket is ready. Maybe it's fixed then. Thanks for the help.

**Comment by ntozier** [comment]
If you're not going to work on this issue report with us then please close your issue report.

**Comment by iArjan** [comment]
close

**Comment by iArjan** [comment]
close #1
