### ISSUE TITLE
Name is cropped when creating new client during new ticket dialog

### ISSUE THREAD

**Issue by sergstetsuk** [osTicket/osTicket#3461]
Name field is cropped to 20 characters when you add new client during new ticktet creation. One must edit this field later.

**Comment by JediKev** [comment]
What version of osTicket? I'm using v1.10(tip of develop) and I'm able to create a user with a really long name when creating a new ticket.

**Comment by ntozier** [comment]
I have never seen what you are describing dating all the way back to osTicket 1.6.  Please provide us with more information about your setup by providing the information at: Admin panel -> Dashboard -> Information, and a screen shot of the screen that you are experiencing the issue.  Thanks.

**Comment by sergstetsuk** [comment]
Some screenshots. Reproduction:
1. Click on "New Ticket"
2. Enter name "Тестовик_Іванович Тестовенко", email and choose from custom list one of items.
3. Click "Create client"
4. I see cropped name and selected item from list is not saved too (this can be another issue).
5. Click on it. Edit once more and save
6. All now ok.
Maybe this is because I use Ukrainian letters in name?
![osticket1](https://cloud.githubusercontent.com/assets/4447821/20020696/44c38d04-a2db-11e6-9528-be017ea03185.png)
![osticket2](https://cloud.githubusercontent.com/assets/4447821/20020697/44ca018e-a2db-11e6-9de6-fec331bf3e7e.png)
![osticket3](https://cloud.githubusercontent.com/assets/4447821/20020698/44d3bea4-a2db-11e6-8e69-034acc960a0c.png)
![osticket4](https://cloud.githubusercontent.com/assets/4447821/20020699/451017b4-a2db-11e6-89db-c69ac1c2d7a4.png)
![osticket5](https://cloud.githubusercontent.com/assets/4447821/20020700/451b316c-a2db-11e6-8b3f-1e4c84a25976.png)

**Comment by ntozier** [comment]
What do you have Admin panel -> Settings -> Default Name Formatting set to?

**Comment by sergstetsuk** [comment]
Actually it doesn't matter. Was "Last, First". Here is with "First Last". I can create long names in English but not Ukrainian. Here you have 2 examples (English long names and Ukrainian Long Names):
![osticket1](https://cloud.githubusercontent.com/assets/4447821/20050034/99f5826e-a4cf-11e6-8aec-282ec716e015.png)
![osticket2](https://cloud.githubusercontent.com/assets/4447821/20050033/99f4a98e-a4cf-11e6-835a-264adc97b2c2.png)
![osticket3](https://cloud.githubusercontent.com/assets/4447821/20050035/99f87eec-a4cf-11e6-8d9a-d0afb5f6d644.png)
![osticket4](https://cloud.githubusercontent.com/assets/4447821/20050036/9a00fc02-a4cf-11e6-86ce-247a5d847b20.png)
![osticket5](https://cloud.githubusercontent.com/assets/4447821/20050037/9a04a3ca-a4cf-11e6-963e-43652be556f0.png)
![osticket6](https://cloud.githubusercontent.com/assets/4447821/20050038/9a07a8c2-a4cf-11e6-8c96-626e9533da5d.png)
![osticket7](https://cloud.githubusercontent.com/assets/4447821/20050039/9a15ff62-a4cf-11e6-99d7-9221459b13c5.png)
![osticket8](https://cloud.githubusercontent.com/assets/4447821/20050040/9a17f86c-a4cf-11e6-99c3-3b36899f5a64.png)

**Comment by ntozier** [comment]
Select "-- As Entered --".

**Comment by sergstetsuk** [comment]
As Entered is the same.
![osticket1](https://cloud.githubusercontent.com/assets/4447821/20091993/6c29e224-a59e-11e6-8249-d791d63c4bbe.png)
![osticket2](https://cloud.githubusercontent.com/assets/4447821/20091995/6c66009c-a59e-11e6-87ee-bc3f8f371ed6.png)
![osticket3](https://cloud.githubusercontent.com/assets/4447821/20091994/6c643e6a-a59e-11e6-875f-d382de19a60c.png)
Name field cannot be abnormally low because second edit of the same name works well. This problem is only during user creation.
