### ISSUE TITLE
Only the help tips are working in translation

### ISSUE THREAD

**Issue by sjaakverhoog** [osTicket/osTicket#3462]
I've installed the Dutch translation files in the include/i18n/nl-NL folder and i can select the dutch language in the admin panel. But everything is still in english exept for the help tips, these are nicely translated to Dutch.
What am i doing wrong?
![trans](https://cloud.githubusercontent.com/assets/9580505/20003598/aca5758a-a287-11e6-8414-3dfe1ccec3a0.png)

**Comment by sjaakverhoog** [comment]
I'm working with version : osTicket (v1.10-rc.3)

**Comment by JediKev** [comment]
Press 'Save Changes' twice. I don't know why but it hangs up sometimes and will only do certain things.

**Comment by sjaakverhoog** [comment]
JediKev, i tried your solution but in my case it is still not working :-(
Is it possible that my hosting is the issue. It looks like the translation of the help tips is stored in a .po file (this one works) but this is the only .po file i can find in the language pack. Maybe my hosting can not handle .yaml files.. Is this possible?

**Comment by sjaakverhoog** [comment]
I have now upgraded my OSTicket to version v1.10 (901e5ea). But stil only the help tips are translated. All the other text and templates are not translated.
I removed all the files and folders and i've put the new files and folders back by FTP.
After that i configured the old database to it. Still nothing more translated.. Could it be the old database?

**Comment by ntozier** [comment]
Did you change your language in your account profile?

**Comment by sjaakverhoog** [comment]
Yes i did..
![image](https://cloud.githubusercontent.com/assets/9580505/20142302/713a2b24-a694-11e6-8c0a-eab0cc94a181.png)
