### ISSUE TITLE
Custom Lists

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket#3463]
@protich @JediKev When importing a list: If you click on import list, the list is imported but the page is not refreshed with the new list items. I then have to refresh the page to see the new list items. I think it is supposed to refresh after import.

**Comment by JediKev** [comment]
This seems to be working just fine for me...are you using an osTicket that has been upgraded or just plain 1.10 install?

**Comment by jdelhome3578** [comment]
Upgraded install from 1.9.14 -> 1.10 rc3 -> 1.10
