### ISSUE TITLE
Bugged Knowledge base osTicket Core, v1.10 - Images not showed to the user and impossibility to delete files.

### ISSUE THREAD

**Issue by PeopleInside** [osTicket/osTicket#3464]
Hi,
after upgraded my OsTicket images uploaded and inserted in the Knowledge base page was invisible for visitor and is visible only in the admin side.

Tested on a new install and issue is the same.

Also I see in the Image you cannot delete files, also is difficult to download images or understand from the admin side where the file is located in the server.

This BUG topic is for alert my knowledge base are now broken. Image are no more showed to users.

**Comment by PeopleInside** [comment]
Also will be not bad add the possibility to add an image from a URL

**Comment by PeopleInside** [comment]
In effect after the update I see some error in OsTicket logs (Database Errors) and now I know what is.
For solve this issue now I have to create a folder in the OsTicket and upload all necessary image than edit all knowledge base and put normal link in HTML code as OsTicket editor don't have option to insert a imagine from a link.

And until this BUG will be not fixed I cannot anymore upload image and use for knowledge base because will be showed only to Staff and not to the visitors.

In the time you fix this you may see an option to delete media (uploaded image) because it not exist any delete button for delete an uploaded existing image.
Also consider to add Insert image from URL.

This is error logged 

[INSERT INTO `LVti_attachment` SET `file_id` = 11, `type` = 'D', `object_id` = 830] Duplicate entry '830-11-D' for key 'file-type'

---- Backtrace ----
#0 (##)/include/mysqli.php(204): osTicket->logDBError('DB Error #1062', '[INSERT INTO `L...')
#1 (##)/include/class.orm.php(3133): db_query('INSERT INTO `LV...', true, true)
#2 (##)/include/class.orm.php(597): MySqlExecutor->execute()
#3 (##)/include/class.attachment.php(161): VerySimpleModel->save()
#4 (##)/include/ajax.draft.php(101): GenericAttachments->upload(Array)
#5 (##)/include/ajax.draft.php(300): DraftAjaxAPI->_uploadInlineImage(Object(Draft))
#6 [internal function]: DraftAjaxAPI->uploadInlineImage('830')
#7 (##)/include/class.dispatcher.php(145): call_user_func_array(Array, Array)
#8 (##)/include/class.dispatcher.php(38): UrlMatcher->dispatch('830/attach', Array)
#9 (##)/include/class.dispatcher.php(120): Dispatcher->resolve('830/attach', Array)
#10 (##)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/draft/830/atta...', NULL)
#11 (##)/scp/ajax.php(262): Dispatcher->resolve('/draft/830/atta...')
#12 {main}

**Comment by protich** [comment]
This is a bug that was introduced by an option to show attachments only to logged in users -- images in knowledgeable articles should be excepted. 

For now you can disable the restriction in `Admin Panel > Settings > System > Require login to view any attachments`. Simply uncheck the option and save.

**Comment by PeopleInside** [comment]
Thank you @protich thank you so much :) nice to read you and happy this has been identified as bug. Thanks also for the solution.

**Comment by PeopleInside** [comment]
@protich there is no any button for delete uploaded images https://github.com/osTicket/osTicket/issues/3466 so I habe deleted all row in the image attachments in the database and now if I upload an image I Am no more able to see in existing file. OsTicket is no more listing uploaded files also I AM unable to understand where is uploaded in the server.

BIG issue on image attachments.
From this bug I have started to want try to delete existing image and re-upload but 

- no delete button for uploaded exist.
- is not possible understand where image are uploaded. Folder in OsTicket folder?
- now if I upload an image is no more listed by the existing media page... so missed totally the possibility to manage uploaded images

**Comment by protich** [comment]
PR #3469 addresses this issue.

**Comment by rayfoss** [comment]
please continue the thread on #3469
