### ISSUE TITLE
V1.10 Translation issues

### ISSUE THREAD

**Issue by fabioandreteles** [osTicket/osTicket#3465]
Hello. I'm trying v1.10 and found some issues with the translation. Don't know if are the files that are not updated. I extracted the .phar file and put it in the folder. I have noe EN and PT language. When I'm in Portuguese the following issues occur, on client site:

![image](https://cloud.githubusercontent.com/assets/16255063/20006913/c16bcd8e-a291-11e6-8b8b-e16f4ad47016.png)

The marked parts are not translated (think it might be the message.po.php). I have a newer one but is in .po format, no PHP. I tried add soem line to message.po.php but killed the site :)

On the FAQ page some other parts:
![image](https://cloud.githubusercontent.com/assets/16255063/20007153/e5f527da-a292-11e6-830d-6e5d3fefc51e.png)

Entering a category also some parts not translated:
![image](https://cloud.githubusercontent.com/assets/16255063/20007172/f89df98e-a292-11e6-8f24-e5e3a5ecd579.png)

As the important part is the client side these are the issues I saw and post here, waiting that someone could help. If there is any way to upload the latestes crowdin files to my instalation that would be great as I'm contributing to it.

Thank you!

**Comment by ntozier** [comment]
Thanks for the report! :)

**Comment by mlipok** [comment]
Q1: Is here good place to, notice any further issues ?
Q2: Whether crowdin newer translation was used in V1.10 ? I'm asking as latest Build on crowdin is 5 months ago. And for example latest Polish activity was at 27 July so I do not know if V1.10 conain latest translation files from translation located on crowdin .

**Comment by ntozier** [comment]
Q1: Is here good place to, notice any further issues ?
A: Yes.

Q2: Whether crowdin newer translation was used in V1.10 ?
A: 1.10 does not contain language files.  The new language files have not been compiled for 1.10 yet.

**Comment by rbukovansky** [comment]
This should be resolved by #3175 which was merged to develop branch and it was released with 1.10, but I'm not sure if Crowdin has latest strings for translations, those strings are translated in your language and new language package for your language was released. My guess it wasn't...

**Comment by fabioandreteles** [comment]
Thank you for the comment. I think Crowdin doesn't have the latest strings. At least I finished the Portuguese translation until 100% on December, it didn't translate after that and now the Crowdin stays on 100%. I'll wait and see some new developments on this.

**Comment by rbukovansky** [comment]
@protich @greezybacon Any updates of strings for translation on Crowdin, please? Thanks.

**Comment by rayfoss** [comment]
new language packs are up as of Jan 13.
