### ISSUE TITLE
[Feature Request] reformat Admin panel -> Dashboard -> Information

### ISSUE THREAD

**Issue by ntozier** [osTicket/osTicket#3467]
I love tables.  No really ever since I learned how to use HTML tables circa 1996 I've loved them for formatting information on a screen. However tables really suck when users are copying the information and pasting it into the forums. Pasting as plain text makes the information look horrible, and pasting with the tables intact make for a horrible formatting in the forum post. (So bad in fact that I usually edit peoples posts to remove the tables.)  So to that end I cordially request that either:

1. Replace the old HTML tables to make the copying and pasting of this information better.
-OR-
2. Add a "Copy for issue report" button to the page that allows the user to add the information in a different format to their clipboard.

note: although written just after the release of 1.10 applies to all versions.

**Comment by Chefkeks** [comment]
Great idea Neil :+1:
