### ISSUE TITLE
stuck on "loading...." when closing a TASK within a ticket. 

### ISSUE THREAD

**Issue by jakobii** [osTicket/osTicket#3468]
![selection_006](https://cloud.githubusercontent.com/assets/19825478/20024789/f2201318-a2a5-11e6-964a-33263049ef42.png)

This is what it gets stuck on when I close a task within a ticket. If I refresh the page the ticket reloads with the task closed correctly. I can also close the task just fine when not within the ticket page. 

love being able to manage tasks within a ticket, awesome! thanks!

v1.10 11de92f
ubuntu 16.04.1
Apache/2.4.18
PHP 7.0.8-0ubuntu0.16.04.3

![selection_008](https://cloud.githubusercontent.com/assets/19825478/20024892/acee12e4-a2a6-11e6-8e04-212f7200f3c8.png)

#3058 - not sure if this could be related to my problem...  I doubt it though.
cgi.fix_pathinfo	 "1" is recommended if AJAX is not working
date.timezone	 Setting default timezone is highly recommended

**Comment by jakobii** [comment]
I have rebuilt a new osticket server with php5.6. I am still having the same problem.

**Comment by ntozier** [comment]
Your version of osTicket does not appear to be the one from osticket.com/download.
Which is: v1.10 (901e5ea).  I would recommend that you download the version from the official site and install that... not whatever this version you have installed now.

**Comment by jakobii** [comment]
thank you for the suggestion. I download the osticket from osticket.com v1.10 (901e5ea). the problem still exists.

**Comment by krishbang88** [comment]
@jakobii : I am experiencing similar issue. did you solve it? 
can somebody post a resolution for this issue plz.

**Comment by Chefkeks** [comment]
+1
Same issue here - osTicket 1.10 (901e5ea) is stuck on "loading...." when ~~closing~~ creating a TASK within a ticket.
Apache 2.4.16 with PHP 5.6.9

**Comment by warpedreality** [comment]
Also experiencing this issue.  Happens when posting updates and/or closing tasks.  Page has to be refreshed in order to resume normal functionality.  

Server is Ubuntu 16.04

osTicket Version 	v1.10 (901e5ea) — Up to date
Web Server Software 	Apache/2.4.18 (Ubuntu)
MySQL Version 	5.7.16
PHP Version 	5.6.29-1

Firefox 50.1.0

**Comment by tykisson** [comment]
I am getting stuck on the loading screen when replying to a task with in a ticket. If I go to the task from the Task Tab and post a reply it works just fine.

It appears to only hang when replying to the Task from the Ticket Tab.

osTicket Version	v1.10 (901e5ea) —  Up to date
Web Server Software	Apache/2.4.18 (Ubuntu)
MySQL Version	5.7.17
PHP Version	7.0.8-0ubuntu0.16.04.3

Chrome Version 55.0.2883.87 (64-bit)

**Comment by pespi123** [comment]
Got the same issue with Google Chrome version 56 and 57.
There are no errors in the eventlog or php-log on the client / osticket server.
All other browsers worked in this setup...

osTicket Version v1.10
IIS 8.5.9600.16384
PHP 5.6.0
Mysql 5.6.24

**Comment by rjcotton** [comment]
I also have this issue on ubuntu 14 server running php 5.6 and ubuntu 16 with PHP 7.0. is there any updates

Server Information
--
osTicket Version | v1.10 (901e5ea) —  Up to date
Web Server Software | Apache/2.4.18 (Ubuntu)
MySQL Version | 5.7.19
PHP Version | 7.0.18-0ubuntu0.16.04.1


Server Information
--
osTicket Version | v1.10 (901e5ea) —  Up to date
Web Server Software | Apache/2.4.7 (Ubuntu)
MySQL Version | 5.5.57
PHP Version | 5.6.31-2+ubuntu14.04.1+deb.sury.org+1

**Comment by rjcotton** [comment]
so just to test I installed 1.10-RC3 from https://github.com/osTicket/osTicket/releases/tag/v1.10-rc.3 and the issue does not exist. 

Server Information
--
osTicket Version | v1.10-rc.3 (907ec36)  Upgrade— v1.10 is available
Web Server Software | Apache/2.4.7 (Ubuntu)
MySQL Version | 5.5.57
PHP Version | 5.6.31-2+ubuntu14.04.1+deb.sury.org+1

**Comment by DimaHaar** [comment]
I am getting stuck on the loading screen when i reply to a task with in a ticket. what can I do ?
![loading_screen](https://user-images.githubusercontent.com/22370244/29273498-c4fe17d4-8104-11e7-99a7-17a2825b1084.jpg)

**Comment by leafeven** [comment]
I can confirm that reply and close methods result in stuck at loading when replying from with in a ticket. replying or closing from tasks tab works as expected with no issue.

![image](https://user-images.githubusercontent.com/18286441/29621679-106e3d6e-87e7-11e7-8507-c6a756f5e1c6.png)

**Comment by nicoletta-maia** [comment]
I've created a pull request that should fix this issue: #4200 
Cheers
