### ISSUE TITLE
Bad FAQ title showed if there are a special character like -> ? question mark

### ISSUE THREAD

**Issue by PeopleInside** [osTicket/osTicket#3471]
**Bad FAQ title showed if there are a special character like -> ? question mark**

As the title say there are a bad title showed on my FAQ
https://www.peopleinside.it/liveticket/kb/index.php
Screenshot:
![immagine senza nome](https://cloud.githubusercontent.com/assets/5006150/20042172/945158b0-a475-11e6-86fc-e940539edac5.png)

Question mark removed, issue solved but maybe there are a bug

**Comment by ntozier** [comment]
This appears to be a duplicated of this issue report.
https://github.com/osTicket/osTicket/issues/3380

**Comment by PeopleInside** [comment]
Sorry. Thanks.
