### ISSUE TITLE
V1.10 The "Auto-Response Disable" function doesn't work.

### ISSUE THREAD

**Issue by chris-b123** [osTicket/osTicket#3472]
On a new Ticket it generates a E-Mail "A new ticket was opened".

![2016-11-07 08_47_46-osticket](https://cloud.githubusercontent.com/assets/23306749/20049999/068b8990-a4c7-11e6-81f5-a6215ada0df0.png)

**Comment by ntozier** [comment]
devs to get to the screen shot screen you go to: Manage -> Help Topics -> Click on a Help Topic -> Click on the New ticket options tab.

I can also confirm that both the Agent and User: New Ticket Alert is sent when this is checked in my v1.10 (901e5ea) when I open a ticket and assign it to my test Help Topic.

**Comment by alexkuc** [comment]
It appears the bug is still present.

**Comment by alexkuc** [comment]
I think I have found the culprit of the issue (I could be wrong though)...

https://github.com/osTicket/osTicket/blob/43bf186db9e85c8ec218158ea4c0bc3e90bbe3eb/include/class.ticket.php#L1316-L1317

Under my circumstances, ```$alertstaff``` variable has a false (0) value, hence the if-statement is never executed...

I will try to come up with a quick N dirty patch to provide a workaround. Hopefully devs (or someone who is more skilled at osTicket would be able to comment on this).

**Comment by JediKev** [comment]
@alexkuc

Is it `FALSE` or `0`?

**Comment by alexkuc** [comment]
@JediKev from what I recall, it was `FALSE`
