### ISSUE TITLE
Upgrade issue (1.9.14 -> 1.10)

### ISSUE THREAD

**Issue by kajla** [osTicket/osTicket#3473]
Hi,

I have an issue with osTicket upgrade from v1.9.14 (8b927a0) to v1.10 (901e5ea).
The upgrader ran `successfully`, but i saw this in the error log file:

> Got error 'PHP message: PHP Fatal error:  Uncaught exception 'ObjectNotUnique' with message 'One object was expected; however multiple objects in the database matched the query. In fact, there are 2 matching objects.' in /var/www/osticket/include/class.orm.php:1176\nStack trace:\n#0 /var/www/osticket/include/class.orm.php(545): QuerySet->one()\n#1 /var/www/osticket/include/class.list.php(297): VerySimpleModel::lookup(Array)\n#2 /var/www/osticket/include/class.list.php(384): DynamicList->getConfigurationForm(true)\n#3 /var/www/osticket/include/class.dynamic_forms.php(1592): DynamicList->getForm()\n#4 /var/www/osticket/include/class.dynamic_forms.php(534): SelectionField->hasSubFields()\n#5 /var/www/osticket/include/class.filter.php(308): Bootstrap::{closure}()\n#6 /var/www/osticket/include/class.filter.php(321): Filter::getSupportedMatches()\n#7 /var/www/osticket/include/class.filter.php(711): Filter::getSupportedMatchFields()\n#8 /var/www/osticket/include/c...\n', referer: http://MYDOMAIN/scp/upgrade.php

Before I run the upgrade script, I saw this on System Logs page:

> DB Error #1146
> 
> [SELECT A1.* FROM `ost_translation` A1 WHERE (A1.`lang` = 'en_US' AND A1.`type` = 'phrase')] Table 'osticket.ost_translation' doesn't exist
> 
>  ---- Backtrace ----
>  #0 (root)/include/mysqli.php(204): osTicket->logDBError('DB Error #1146',  '[SELECT A1.* FR...')
>  #1 (root)/include/class.orm.php(3133): db_query('SELECT A1.* FRO...',  true,  true)
>  #2 (root)/include/class.orm.php(3180): MySqlExecutor->execute()
>  #3 (root)/include/class.orm.php(1771): MySqlExecutor->getArray()
>  #4 (root)/include/class.orm.php(1815): ModelInstanceManager->{closure}()
>  #5 (root)/include/class.orm.php(1794): CallbackSimpleIterator->next()
>  #6 (root)/include/class.orm.php(1803): CallbackSimpleIterator->rewind()
>  #7 (root)/include/class.orm.php(1463): CallbackSimpleIterator->valid()
>  #8 (root)/include/class.orm.php(1480): CachedResultSet->fillTo(9223372036854775807)
>  #9 (root)/include/class.orm.php(1489): CachedResultSet->asArray()
>  #10 (root)/include/class.translation.php(899): CachedResultSet->getIterator()
>  #11 (root)/include/class.translation.php(920): CustomDataTranslation::getTranslation('en_US')
>  #12 (root)/include/class.list.php(396): CustomDataTranslation::translate('b312b2410ff22c3...')
>  #13 (root)/include/class.list.php(209): DynamicList->getLocal('name_plural')
>  #14 (root)/include/class.list.php(524): DynamicList->getPluralName()
>  #15 [internal function]: DynamicList::getSelections()
>  #16 (root)/include/class.forms.php(567): call_user_func(Array)
>  #17 (root)/include/class.forms.php(575): FormField::allTypes()
>  #18 (root)/include/class.forms.php(1016): FormField::getFieldType('text')
>  #19 [internal function]: FormField->getImpl(Object(DynamicFormField))
>  #20 (root)/include/class.dynamic_forms.php(596): call_user_func_array(Array,  Array)
>  #21 (root)/include/class.dynamic_forms.php(1339): DynamicFormField->__call('getImpl',  Array)
>  #22 (root)/include/class.dynamic_forms.php(1339): DynamicFormField->getImpl(Object(DynamicFormField))
>  #23 (root)/include/class.dynamic_forms.php(948): DynamicFormEntryAnswer->getField()
>  #24 (root)/include/class.company.php(71): DynamicFormEntry->getAnswer('name')
>  #25 (root)/include/staff/footer.inc.php(5): Company->__toString()
>  #26 (root)/scp/upgrade.php(88): require('/var/www...')
>  #27 {main}

After upgrade, the ticket page is empty:
![scp_ticket empty](https://cloud.githubusercontent.com/assets/5457824/20055248/7eb55090-a4e0-11e6-829d-763efa23abbf.png)

... and in the log file:
> Got error 'PHP message: PHP Fatal error:  Uncaught exception 'ObjectNotUnique' with message 'One object was expected; however multiple objects in the database matched the query. In fact, there are 2 matching objects.' in /var/www/osticket/include/class.orm.php:1176\nStack trace:\n#0 /var/www/osticket/include/class.orm.php(545): QuerySet->one()\n#1 /var/www/osticket/include/class.list.php(297): VerySimpleModel::lookup(Array)\n#2 /var/www/osticket/include/class.list.php(384): DynamicList->getConfigurationForm(true)\n#3 /var/www/osticket/include/class.list.php(728): DynamicList->getForm()\n#4 /var/www/osticket/include/class.list.php(745): DynamicListItem->getConfigurationForm()\n#5 /var/www/osticket/include/class.list.php(672): DynamicListItem->getForm()\n#6 /var/www/osticket/include/class.dynamic_forms.php(1467): DynamicListItem->hasProperties()\n#7 /var/www/osticket/include/class.dynamic_forms.php(1383): SelectionField->display(Array)\n#8 /var/www/osticket/i...\n'

What can I do?
Could you help me, please?
![please](https://m.popkey.co/338088/mpjp5.gif)

Thanks in advance.

**Comment by kajla** [comment]
Upgrade crash when smile #6:

> Upgraded to v1.10.0 ... post-upgrade checks!
> Please wait... while we upgrade your osTicket installation!
> Still busy... smile #6

then...
> Error occurred. Aborting...
Please wait... while we upgrade your osTicket installation!
Something went wrong

System logs:
![kep](https://cloud.githubusercontent.com/assets/5457824/22150951/2e50b948-df1c-11e6-95d5-e69ee1328268.png)

Thank you in advance for your help.

**Comment by ntozier** [comment]
Ummm.  I'm confused.  You upgraded and it upgraded fine and in your first post said "The upgrader ran successfully", that you were getting a PHP error and tickets were not displaying properly.

But then in a second post you say "Upgrade crash when smile" and indicate a that the upgrader had an error.  So, which is it? Because obviously it cannot be both. :)

**Comment by kajla** [comment]
Oh, okay, let me show you. 

![osticket_upgrade_error](https://cloud.githubusercontent.com/assets/5457824/22167196/1ea11512-df65-11e6-8676-e2860b6c38b2.gif)

**Comment by kroganjin** [comment]
I have the same problem...

**Comment by EJonason** [comment]
I'm experiencing a very similar issue.  Had all the same errors as above, but the only thing so far that isn't working is all users can't view any closed tickets.  We can view and edit open tickets normally and all other functions work.

**Comment by kajla** [comment]
I turned on display errors:
![kep](https://user-images.githubusercontent.com/5457824/27391238-b9ce7448-56a3-11e7-85a8-6dee0ed361ed.png)
... on **scp/tickets.php?id=XXX** page.

> Fatal error: Uncaught exception 'ObjectNotUnique' with message 'One object was expected; however multiple objects in the database matched the query. In fact, there are 2 matching objects.' in /srv/www/htdocs/osticket/include/class.orm.php:1176 Stack trace: #0 /srv/www/htdocs/osticket/include/class.orm.php(545): QuerySet->one() #1 /srv/www/htdocs/osticket/include/class.list.php(297): VerySimpleModel::lookup(Array) #2 /srv/www/htdocs/osticket/include/class.list.php(384): DynamicList->getConfigurationForm(true) #3 /srv/www/htdocs/osticket/include/class.list.php(728): DynamicList->getForm() #4 /srv/www/htdocs/osticket/include/class.list.php(745): DynamicListItem->getConfigurationForm() #5 /srv/www/htdocs/osticket/include/class.list.php(672): DynamicListItem->getForm() #6 /srv/www/htdocs/osticket/include/class.dynamic_forms.php(1472): DynamicListItem->hasProperties() #7 /srv/www/htdocs/osticket/include/class.dynamic_forms.php(1388): SelectionField->display(Array) #8 /srv/www/htdocs/osticket/include/staff/ticket-view.inc.php(45 in /srv/www/htdocs/osticket/include/class.orm.php on line 1176

Any news?
Thanks in advance.

**Comment by Cronus89** [comment]
I am having this same error when I try to view a closed ticket.  The page is blank, with the normal osTicket header, but no contents such as ticket lists.

`[15-Aug-2017 20:32:32 UTC] PHP Fatal error:  Uncaught exception 'ObjectNotUnique' with message 'One object was expected; however multiple objects in the database matched the query. In fact, there are 2 matching objects.' in C:\inetpub\wwwroot\tobaccosuper.com\help\include\class.orm.php:1176
Stack trace:
#0 C:\inetpub\wwwroot\tobaccosuper.com\help\include\class.orm.php(545): QuerySet->one()
#1 C:\inetpub\wwwroot\tobaccosuper.com\help\include\class.list.php(297): VerySimpleModel::lookup(Array)
#2 C:\inetpub\wwwroot\tobaccosuper.com\help\include\class.list.php(384): DynamicList->getConfigurationForm(true)
#3 [internal function]: DynamicList->getForm()
#4 C:\inetpub\wwwroot\tobaccosuper.com\help\include\class.list.php(112): call_user_func(Array)
#5 C:\inetpub\wwwroot\tobaccosuper.com\help\include\class.list.php(1327): CustomListHandler->__call('getForm', Array)
#6 C:\inetpub\wwwroot\tobaccosuper.com\help\include\class.list.php(1327): TicketStatusList->getForm()
#7 C:\inetpub\wwwroot\tobaccosuper.com\help\include\class.list.php(1143): TicketStatus->getConfig in C:\inetpub\wwwroot\tobaccosuper.com\help\include\class.orm.php on line 1176
`
