### ISSUE TITLE
Faq last update time completly wrong. OsTicket 1.10

### ISSUE THREAD

**Issue by PeopleInside** [osTicket/osTicket#3475]
Hi,
I created a FAQ today and I can see last update was done 6 month ago.
Has no sense.

In visitor side seems the last update time is wrong but in operator side is correct.

Operator side:
![1](https://cloud.githubusercontent.com/assets/5006150/20062328/a09b1316-a503-11e6-967e-39bb7bb3058f.png)

Visitor side:
![2](https://cloud.githubusercontent.com/assets/5006150/20062337/a6bc98be-a503-11e6-86b2-0f05a896690c.png)

FAQ URL: https://www.peopleinside.it/liveticket/kb/faq.php?id=10

**Comment by JediKev** [comment]
I just made a [pull request](#3476) that should fix this for you.

**Comment by PeopleInside** [comment]
Thank you @JediKev :)
