### ISSUE TITLE
Some vars are not working on OsTicket 1.10

### ISSUE THREAD

**Issue by MendesMartini** [osTicket/osTicket#3482]
Hello,

Some vars that I was using on OsTicket 1.9 are not working on OsTicket 1.10 like:

%{ticket.message}
%{ticket.lastmessage}
%{ticket.lastmessage.create_date}

When I try to use %{ticket.lastmessage} (for example), I got the error 500:

> GET http://atendimento.santosmadeiras.com.br/scp/ajax.php/tickets/460/canned-resp/35.json?_=1478601375881 500 (Internal Server Error)
send @ jquery-1.11.2.min.js?901e5ea:4
ajax @ jquery-1.11.2.min.js?901e5ea:4
(anonymous function) @ scp.js?901e5ea:207
dispatch @ jquery-1.11.2.min.js?901e5ea:3
r.handle @ jquery-1.11.2.min.js?901e5ea:3
ListPicker._handleMouseUp @ about:blank:668

I apologize for my bad English.

**Comment by ntozier** [comment]
They were likely changed then.  osTicket 1.10 has a nifty type ahead feature for variables.  You might want to investigate that to see if you can find replacements.

**Comment by MendesMartini** [comment]
Bingo:

%{ticket.thread.lastmessage}

Thank you very much.
