### ISSUE TITLE
Feature Request: Task Alert for Ticket-Assignee

### ISSUE THREAD

**Issue by markus4000** [osTicket/osTicket#3487]
It would be great if the TICKET assignee gets a notice on TASK activity, too.
For that it would be good to add the option in the "task setting and options".

![image](https://cloud.githubusercontent.com/assets/4391014/20116736/bf2a24b6-a5fd-11e6-8df0-b5f86ca4cd6f.png)

**Comment by ntozier** [comment]
There really isn't a concept of a ticket assignee in osTicket at this time.  So to do this that would have to be added first.  I would think that most people who assign tickets to others would be covered by the Department Manager though.  Can you expand on your use case to rationalize why this would be a good feature to have?

**Comment by markus4000** [comment]
The ticket assignee is the one who is responsible for the result of the ticket. The "ticket" is like a project. And the owner of the project (the assignee) wants to know when there was activity in one of the tasks of his ticket

eg: 
Ticket; _"new employee starts 1st. Dec. 2016"_
Task1 : set up email-account
Task2 : order computer
Task3: install his Smartphone 
Task4: install Computer
...
Every task has its own assignee. but the assignee of the TICKET wants to be noticed when something happend in one of the TASKS of his ticket.

But the department manager is not interested to be noticed on every activity… else he’d be spammed. the department manager only wants to know if a task is overdue.
And anyways, if the ticket and the department is not the same, and if the agents only have access to their own department, the ticket owner cant see the tasks if he assigns it to another department. That is a weak point.

what do you think?

**Comment by ntozier** [comment]
Other than this "the ticket owner cant see the tasks if he assigns it to another department. " it sounds good.
The ticket owner can always see his own ticket.  He just needs to log in as a User to see his tickets.

**Comment by markus4000** [comment]
I mean the ticket assignee can’t see the tasks of his tickets if he assigns the task to another department. That’s not good. at least he shout be able to see the "owner view" of the task (Without the internal notes), or the ticket assignee should receive notices if something changed.

From my Point of view: A task should have “owner” and a “assignee” too. Like the ticket. The owner and the assignee can view the task, and everyone of the owners department and everyone of the assignees department too.

**Comment by JediKev** [comment]
@markus4000 

An Agent assigned to a ticket is not necessarily responsible for the Tasks of a Ticket. A ticket can be assigned to an Agent and/or Team and can be referred to many departments. There can be a task or multiple tasks specific to each department, team, or agent. If you want the Assigned Agent to get the Task notifications you must assign the Task to the Agent as well.

Cheers.
