### ISSUE TITLE
Adding user details

### ISSUE THREAD

**Issue by simonnzg** [osTicket/osTicket#3490]
Is it me or is it currently not possible to add new users manually?  I've tried two separate barefoot git installs of Develop and in both there's no option to add a new user's details.

**Comment by simonnzg** [comment]
..or should I say, you can add a user or company, but you can't name it!

**Comment by ntozier** [comment]
Sorry but I have no idea what you mean.
Log into osTicket. 
Click on Users
Click on Add Users.

**Comment by simonnzg** [comment]
Been using osTicket for a few years, but this is the first couple of test installs I've done since the latest release and it's almost as if something isn't being loaded.  See the pic. That's what I get. No way of actually adding anything to the user before creating, and when I create it it has a blank name and there's no way of updating it.  It's so fundamental that I can't imagine it's something that everyone has got, but someone may know what I'm doing wrong.  This is a fully vanilla install, from Git, PHP7 (it's the only thing that may mess it up).
![new user no way to config](https://cloud.githubusercontent.com/assets/524239/20182524/f2bf6b12-a759-11e6-8cb3-16ba5e75b736.PNG)

**Comment by simonnzg** [comment]
This is Develop from Github.

**Comment by tuxstorm** [comment]
Directed here from my forum post where I'm experiencing the same thing.

I'm using the current release (v1.10)

Per ntozier's request I downgraded to php 5.6 (PHP Version 5.6.27-1+deb.sury.org~xenial+1), and get the same behavior. 

I'm going to try an installation on Debian and see what happens.

**Comment by simonnzg** [comment]
I've tried on Ubuntu Server 16.04LTS and Mint 18.  Both have PHP7 and both exhibit the same behaviour.
I've downloaded the tarball version of 1.10 and will install that to see if it's the same, and then I'll install Develop on an older Ubuntu 14.04LTS/PHP5 box to see what happens. 
It may not be PHP7, as such, but something that Debian put into PHP.INI that breaks osTicket, and it's got into Ubuntu and Mint that way.  I have a Mageia 5 VM that I haven't tried installing osTicket on. May as well go the whole hog and put it on there, too.  :)

**Comment by simonnzg** [comment]
Ubuntu Server 14.04 LTS with PHP5: Vanilla install of Develop via git works fine.
All pointing at a php.ini "Enhancement" in Debian-esque OSs running PHP7 at the moment?

**Comment by simonnzg** [comment]
Vanilla Ubuntu Server 16.04LTS with PHP7: Problem is there!
Next job is to remove extensions and prod the installation to see if anything squeaks.

**Comment by simonnzg** [comment]
Interesting. I moved the database off the old system onto a new one with PHP5 that was tested and working.  Once I installed the database off the PHP7 machine the new system broke too, so the problem breaks the database or is caused by a broken database, so downgrading to PHP5 won't fix the problem.

**Comment by denysvitali** [comment]
I have 1.10 and all work as intended.
Can you provide some logs?

**Comment by simonnzg** [comment]
Logs? osTicket? No chance.
Having 1.10 isn't enough, you have to have 1.10 AND Ubuntu AND PHP7.

**Comment by ntozier** [comment]
@simonnzg  osTicket does have logging:
Admin panel -> Dashboard -> System Logs.

But most stuff will still end up in your PHP and webserver software logs.

**Comment by denysvitali** [comment]
I'm gonna try to use a Docker Image to see if I can reproduce your issue,
https://hub.docker.com/r/osticket/osticket/

The image I linked is based on [PaaS](https://github.com/pi0/paas) which is a Nginx Server with PHP7, running in Ubuntu.
I'm trying to reproduce your error as we speak

**Comment by simonnzg** [comment]
Yes, I know about osTicket's logs, and they don't help with this one, and I have it set to display PHP problems on screen as well and I don't get any.
My suspicion is that the problem is not a PHP problem, as such, in as much as it's not an error, but an expected behaviour, so it won't log anything untoward.  It's something to do with the way that Ubuntu has set up PHP7, but I can't see anything obvious.

**Comment by simonnzg** [comment]
I got this when logging on, but I don't think it's too relevant, but might be:
Warning: Declaration of AssignmentForm::render($options) should be compatible with Form::render($staff = true, $title = false, $options = Array) in /var/www/html/osTicket/include/class.forms.php on line 4150

Warning: Declaration of TransferForm::render($options) should be compatible with Form::render($staff = true, $title = false, $options = Array) in /var/www/html/osTicket/include/class.forms.php on line 4270

**Comment by denysvitali** [comment]
I have the same warning when I run the [osTicket installation](https://raw.githubusercontent.com/pi0/osticket-docker/master/bin/osticket-install.php) from the shell:
```
OSTicket cron job is set to run every 5 minutes
Using linked MySQL container
Waiting for database TCP connection to become available...
Connecting to database mysql://osticket@mysql/osticket
Loading installation secret
Updating configuration file
Installing database. Please wait...
PHP Warning:  Declaration of AssignmentForm::render($options) should be compatible with Form::render($staff = true, $title = false, $options = Array) in /var/www/src/include/class.forms.php on line 4150

Warning: Declaration of AssignmentForm::render($options) should be compatible with Form::render($staff = true, $title = false, $options = Array) in /var/www/src/include/class.forms.php on line 4150
PHP Warning:  Declaration of TransferForm::render($options) should be compatible with Form::render($staff = true, $title = false, $options = Array) in /var/www/src/include/class.forms.php on line 4270

Warning: Declaration of TransferForm::render($options) should be compatible with Form::render($staff = true, $title = false, $options = Array) in /var/www/src/include/class.forms.php on line 4270
Database installation failed. Errors:
  core: Internal Error - please make sure your download is the latest (#1)
```

But since they're warnings, I don't think they are the source of the problem.
Can you post your console log? It may be a javascript problem (CTRL + SHIFT + J in Firefox)

**Comment by simonnzg** [comment]
The javascript log remains stubbornly uninformative, which is what you'd expect as the text editor is obviously not being invoked at that stage. It remains entirely blank in Chrome.
In fact, no logs get written to at all. Nothing in /var/log

**Comment by alexisskeates** [comment]
Just downgraded 16.04 install to php5.6 problem still exsists

**Comment by simonnzg** [comment]
I think whatever it is breaks the database as that happened to me too. I didn't downgrade, but moved the database to a new system on a new machine running PHP5 and the problem followed me.

**Comment by alexisskeates** [comment]
I just did a fresh install using my webhost's (tsohost.com) platform to test. All worked fine, so I decided to move the database across. As soon as I moved the database across the issue reappeared. So appears to be something database related. Not sure how to fix this or even where to start looking.

**Comment by denysvitali** [comment]
Which was the first version you used?
How many times have you upgraded?
On Nov 24, 2016 1:53 PM, alexisskeates <notifications@github.com> wrote:I just did a fresh install using my webhost's (tsohost.com) platform to test. All worked fine, so I decided to move the database across. As soon as I moved the database across the issue reappeared. So appears to be something database related. Not sure how to fix this or even where to start looking.

**Comment by alexisskeates** [comment]
I initially installed the last RC version 3 I think it was? Then about two weeks after the version 10 stable was released and I upgraded to that. Both versions have had the issue from when I first installed.

**Comment by DarthSlider** [comment]
Same Issue.
Windows 2012 R2, OsTicket 1.10, PHP 7.1, Apache 2.4.23, MariaDB 10.1.19
So it`s not unique to Ubuntu.

**Comment by simonnzg** [comment]
That's a bit of a pain.  It means it's a general PHP7 problem, doesn't it? :(

**Comment by DarthSlider** [comment]
Any solution yet? Should i downgrade to PHP 6 or 5?

**Comment by simonnzg** [comment]
Downgrade and try the existing database, but it's probably broken. I don't know what happens, there, but even downgrading with the same database won't fix it.  As it's a fresh install, use PHP5 and a new database. :(

**Comment by simonnzg** [comment]
I assume that @protich will post some updates eventually. It's been a month since the last bunch, but I don't know if this one is on the radar yet, or not.

**Comment by ntozier** [comment]
@DarthSlider there is no such things as PHP 6.x.  So 5.6

**Comment by DarthSlider** [comment]
Thanks! I`ll try to reinstall it tomorrow.
All this php stuff is new to me, so i just downloaded up to date version of everything. I think there should be some kind of notification what php 7+ is not officially supported yet.

**Comment by ntozier** [comment]
1.10rc3 was the initial release that supported PHP7 (and bumped the minimum PHP to 5.4)... for the most part it is supported.  But it appears that not enough testing happened and some code that PHP7 doesn't like still exists.  Hence why I was saying try downgrading to 5.6.

**Comment by tluquet3** [comment]
Hi @simonnzg , I actually got the same problem at first but I found a quick solution.
In v1.10 you apparently need to manually add the fields you want in your user's information, they are disabled by default.
Solution:
 

- Go to admin panel, "Manage"->"Forms" 
-  Choose the contact information form
-  For each field, click on config and enable.

This should work.
If you experience the same problem in the ticket creation ( you don't see the ticket details ), do the same with the ticket details form.

**Comment by DarthSlider** [comment]
Thank you @tluquet3 !
Offtopic, is there any way to get end users from Active Directory?

**Comment by ntozier** [comment]
@DarthSlider You would have to export them from AD and import them into osTicket.

**Comment by ehsansafi2005** [comment]
I had the same issue and it was solved by enabling the visibility of then in Manage --> Forms ...
