### ISSUE TITLE
Changing overdue date in Tasks in 1.10

### ISSUE THREAD

**Issue by joseaguardia** [osTicket/osTicket#3492]
Hello!

Is possible to edit the date of a task after creation?

Thanks!

**Comment by ntozier** [comment]
Tasks (like tickets) have multiple dates.  Which one are you referring to?

**Comment by protich** [comment]
This is a legit issue -- the plan is to add in-place edit instead of mass edit of all fields. Hope to sneak in the feature on the next minor release (v1.10.1)

**Comment by joseaguardia** [comment]
@ntozier I want to change the due date of the task.

@protich That's a good idea, although actually I can't change the due date in any way. If I edit the task (like I do with tickets) I can only change the title:

![image](https://cloud.githubusercontent.com/assets/16305835/20258242/fce6479e-aa4e-11e6-9703-508d814c6749.png)

Thanks!

**Comment by akash65** [comment]
is there possible to set different dates for ticket and different for task for the same group?
