### ISSUE TITLE
Advenced search not  working

### ISSUE THREAD

**Issue by edukondalugorla** [osTicket/osTicket#3493]
1.10 RC3 advanced search not matching "includes" on "choices" form fields

**Comment by jdelhome3578** [comment]
Does PR #3495 fix your issue?

**Comment by GoodbyeWorld** [comment]
Same issue, upgraded from 1.10 RC1, to RC2, to RC3, to stable release.  Still having this problem.

**Comment by GoodbyeWorld** [comment]
This is a duplicate for #2625

**Comment by sieveni91** [comment]
I would like to use advanced search, but the problem is still existing. Is there a chance for a fix?

**Comment by JediKev** [comment]
I have created this pull request that should solve this issue: #4124

**Note:** If you're using a Choices field, every choice HAS to have a key associated with them (mentioned in the helptext).
<img width="320" alt="screen shot 2017-12-14 at 13 38 51" src="https://user-images.githubusercontent.com/11823401/34011117-91f4e75c-e0d4-11e7-9a81-0b2601e359c6.png">
