### ISSUE TITLE
Possible incorrect use of ROOT_PATH

### ISSUE THREAD

**Issue by silverskysoft** [osTicket/osTicket#3497]
In [class.forms.php](https://github.com/osTicket/osTicket/blob/f5385cf37cc97db1235dcf068615471bec0ed29c/include/class.forms.php#L248), the ROOT_PATH is sent back into HTML that is generated for client side Javascript delivered over JSON. This breaks proxies as they don't intercept JSON.

This same issue is noted in: [include/ajax.tips.php](https://github.com/osTicket/osTicket/blob/develop/include/ajax.tips.php#L42)

Possible way to fix is to use the help desk URL by calling getURL()
 `$url = rtrim($ost->getConfig()->getUrl(), '/') . '/' . substr($url, 1); `

Is this a right way to fix?

**Comment by silverskysoft** [comment]
Any comments?

**Comment by rayfoss** [comment]
Which sort of proxy are you using? It doesn't sound like an issue that would arise with HTTP or Socks proxies.

**Comment by silverskysoft** [comment]
@rayfoss, this is Apache 2.4 mod_proxy and it does not intercept JSON. ROOT_PATH is a locally derived URLs is sent back via a messaging mechanism like JSON which aren't generally intercepted by proxies (it actually is very hard parse JSON for URLs as it can contain URLs in any format they choose).
