### ISSUE TITLE
OsTicket 1.9.15:  Problem with auto adding collaborators for organization

### ISSUE THREAD

**Issue by ATalker** [osTicket/osTicket#3498]
Hello
Not so far I have reported  about  adding collaborators issue here -> #3227 . 
This bug exists in 1.9.13 and 1.9.14 version.
Issue was partially fixed - #3238 
But problem with auto adding collaborators for organization is still present in osTicket 
1.9.13, 1.9.14  and 1.9.15 is not exception.
There are no emails near collaborators name after creating ticket.
Example: https://i.imgsafe.org/5ceda1bdaf.jpeg

**Comment by ntozier** [comment]
So if you already reported it in 3227... why are you reporting it again?
Does the bug exist in 1.10?

**Comment by ATalker** [comment]
Because this issue reported in the context of new version 1.9.15.
I pointed  #3227 as additional information to understand current situation with bug .

Gui in  OT 1.10 and OT 1.9 are different. 
So this issue cant relate to OT 1.10

**Comment by ntozier** [comment]
You do not need to report the issue on each version.
Simply update your original report that you are still experiencing this issue on version X.
Please close this duplicate report.

**Comment by ATalker** [comment]
close as duplicated. all info is in #3227
