### ISSUE TITLE
How to prevent a ticket to be reopened by (v1.9.14)

### ISSUE THREAD

**Issue by gitfve** [osTicket/osTicket#3499]
v1.9.14
How to prevent a ticket to be reopened by the user when they reply on a ticket link there are closed be the administrator.

**Comment by ntozier** [comment]
I followed your question up until the last three words.

Go to: Admin panel -> Manage -> Lists -> Ticket Statuses.
I created a ticket status called Close-noReopen.
Click on Properties.
Notice the "Allow Reopen" option.

You can also set this flag on Closed status if you do not want to use a specific status like I do.

**Comment by gitfve** [comment]
The user can reopen my closed ticket because i have not set "Notice the "Allow Reopen" option."
All working now, Thanks, Nice:-)

**Comment by ntozier** [comment]
Very welcome.  Please close this issue report if it's solved.

**Comment by gitfve** [comment]
Closed
