### ISSUE TITLE
CRON task no longer works after upgrade from 1.9.14 to 1.10

### ISSUE THREAD

**Issue by blueyeguy** [osTicket/osTicket#3500]
I get the following error generated in my php logs every time my schedules task cron job runs:

[12-Nov-2016 14:00:00 America/Chicago] PHP Fatal error:  Only variables can be passed by reference in C:\inetpub\wwwroot\[sitename]\include\class.plugin.php on line 555

The cron job worked normally in 1.9.14

Server Information
osTicket Version	v1.10 (901e5ea) —  Up to date
Web Server Software	Microsoft-IIS/7.5
MySQL Version	5.5.39
PHP Version	5.5.27

**Comment by blueyeguy** [comment]
Upgrading my PHP to 5.6.24 seems to have resolved this for me.

**Comment by greezybacon** [comment]
@blueyeguy interesting. Do you still have access to a machine running PHP 5.4 or 5.5? If so, could you try this patch?:
```patch
diff --git a/include/class.plugin.php b/include/class.plugin.php
index d565b90..5ae9f03 100644
--- a/include/class.plugin.php
+++ b/include/class.plugin.php
@@ -552,7 +552,7 @@ abstract class Plugin {
         $info = array();
         $ignored = null;
         if ($r = dns_get_record($sig['hash'].'.'.self::$verify_domain.'.',
-            DNS_TXT, $ignored, $ignored, true)
+            DNS_TXT, $ignored, $ignored, $raw=true)
         ) {
             foreach ($r as $rec) {
                 foreach (explode(';', $rec['txt']) as $kv) {
```

**Comment by blueyeguy** [comment]
I do not have 5.4 or 5.5 running in my sandbox any more but I did make this suggestion to someone else in the forums that was experiencing the same error on line 555 that I was. They have not responded whether or not it solved the problem.

I would try and roll back my PHP to a previous version, but right now I am actually running Lime Survey there that is being actively used and I don't want to risk messing that up to test this. I can try this after 11/28. That's when the surveys will be closed.

**Comment by MischaLundberg** [comment]
@greezybacon after editing this line i'll get the following error.
PHP Parse error:  syntax error, unexpected '[', expecting ')' in [path]/include/class.config.php on line 105

I'm using PHP 5.3.10-1ubuntu3.25 with Suhosin-Patch 

Thanks for your help!

**Comment by thebravoman** [comment]
Same here. I have finally tracked it to here.

**Comment by ntozier** [comment]
Just received another report of this issue on the forums at: 
http://osticket.com/forum/discussion/89586/cron-issues-since-upgrade-to-v1-1

person is running 5.6.29.  Referred them to the patch in comments above.

**Comment by thebravoman** [comment]
@ntozier  - which patch?

Because I have tried the one mentioned by @greezybacon, but it does not work for me.

**Comment by ntozier** [comment]
There is only one patch in this thread.

**Comment by thebravoman** [comment]
@ntozier my hope was that I was missing something and there was another patch :(. That my eyes were laying to me.

**Comment by ntozier** [comment]
I seem to recall that someone else said that they reverted to the 1.9.x cron.php and had some luck.  So you could try that. :)  I haven't looked at the diff between the two or tested it myself though.

**Comment by moose999** [comment]
I have the same problem. I have PHP 5.6, and I have tried with PHP 5.5.

If I use the default class.plugin.php included with 1.10 I get:
"Only variables can be passed by reference in /include/class.plugin.php on line 555"

If I change line 555 of class.plugin.ph from 
DNS_TXT, $ignored, $ignored, true)
to
DNS_TXT, $ignored, $ignored, $raw=true)
I get:
syntax error, unexpected '[', expecting ')' 

If I use cron.php from 1.9.x I still get:
"Only variables can be passed by reference in /include/class.plugin.php on line 555"

Any ideas?

**Comment by MischaLundberg** [comment]
Meanwhile my installation is running again. 
After Installing PHP 5.6 i've reinstalled osTicket and created a new cronjob.

@moose999:
How's your cronjob look like? 
In my case it would be something like this:
*/2 * * * * /usr/bin/php56/php5 -nc /etc/php56/cgi/php.ini -f /osTicket/api/cron.php

Hope this helps..

**Comment by moose999** [comment]
Hi,

I'm only checking every 15 minutes, I am piping the output of both stderr and stdout to email, and I am not loading a php.ini file in that way, so my command is very different:

/usr/local/bin/php /home/ACCOUNTNAME/public_html/osticket/api/cron.php 2>&1 | mail -s "osTicket-CRON" USERNAME@DOMAINNAME

I have tried both the newest git version and the newest release at http://osticket.com/download with the same results.

Many thanks!

**Comment by ntozier** [comment]
How many versions of PHP do you have installed?  Because using this: /usr/local/bin/php means that it defaults to one version... and maybe if you have multiple versions installed you should specify it differently.  At a command prompt run: php -v and see what version is being used for CLI.  Also PHP often uses a different php.ini for command line so you would need to make sure that the extensions required are enabled in the CLI version.

**Comment by moose999** [comment]
Hi there,

My host has 5.2, 5.3, 5.4, 5.5, 5.6, and 7 installed, and I choose which version I am using with the .htaccess file. I have tried with 5.5 and 5.6. I do not have shell access, so cannot run php -v.

Is there a list of the extensions required, so that I can have the host make sure they are enabled for me?

https://clients.evohosting.co.uk/knowledgebase.php?action=displayarticle&id=107

**Comment by ntozier** [comment]
Choosing the version you run via .htaccess does not in fact choose the version of php being used at CLI.

Required extensions really depend on your setup and how you want to use osTicket.  Bare minimum is mysql (or mysqli), gdlib, imap (if you use pop/imap), xml, xml-dom, json, fileinfo all look "required" to me. There are others that are recommended.  Look at Admin panel -> Dashboard -> Information.

**Comment by moose999** [comment]
Aha! It turns out I can use /opt/php56/bin/php in my cron job to choose the PHP version being used at CLI. Many thanks!

**Comment by ntozier** [comment]
You're very welcome.
Glad to be of service. :)
