### ISSUE TITLE
Customer self-registration error, HTTP 500 - V1.10

### ISSUE THREAD

**Issue by adalbertusgabriel** [osTicket/osTicket#3501]
My config:
WWW Server: 	Apache/2
MySQL 	5.5.41
PHP 	5.6.12 (but tested also on 7.0)

Every attempt of user self-registration is always finished by internal server error - user can fill up the form, but after he hits the Register button he gets blank page.

Log is showing:
PHP Fatal error:  Call to a member function getAccount() on null in /home/myaccount/domains/somedomain.com/public_html/support/account.php on line 49, referer: http://somedomain.com/support/account.php?do=create

My account.php file is default and line mentioned in this log is coming from condition (line 48 to 54) as below:

```
if ($user && $_POST) {
    if ($acct = $thisclient->getAccount()) {
       $acct->update($_POST, $errors);
    }
    if (!$errors && $user->updateInfo($_POST, $errors))
        Http::redirect('tickets.php');
}
```

I can create customer account from my admin panel.
Customer without account can create a ticket and next he is getting confirmation in e-mail with working link to preview of this ticket.
But every scenario of self-registartion by customer from available links (main support page, link on ticket preview page linked in e-mail with ticket confirmation etc.) always leads to fail.

**Comment by greezybacon** [comment]
What version of osTicket are you using?

**Comment by adalbertusgabriel** [comment]
V1.10. The same was on 1.9.14 and 1.9.15.

Now it's just testing environment, but we want to use osticket as our main support system.

**Comment by ntozier** [comment]
by v1.10 do you mean 901e5ea?

**Comment by adalbertusgabriel** [comment]
It's downloaded from http://osticket.com/download.

Sha256sum 68ff411693802e154426d9ec9b2365ff524aad5f6e52ad9422f073ae48e3a46d checked and confirmed after zip download.

**Comment by greezybacon** [comment]
Do you use any authentication plugins like pass-thru or LDAP?

**Comment by adalbertusgabriel** [comment]
No plugins yet, just default installation.

**Comment by luckshot** [comment]
I am having a similar problem.  There is no client-side error, but I do get a server-side error in apache2/error.log, and the symptom is similar:  Limited "new user" form display and the system ultimately creates a blank user.  Ntozer suggested this was the best place to post this information.

User information is not editable / system creates blank users on "new user". 

Base installation, no modifications, just a direct download from the osticket main download page.

Server error from log:
[Wed Nov 23 09:59:53.941758 2016] [:error] [pid 32093] [client 192.168.3.165:50312] PHP Warning:  Declaration of TransferForm::render($options) should be compatible with Form::render($staff = true, $title = false, $options = Array) in /var/www/support/include/class.forms.php on line 4270

Server details:
mysql:
mysql  Ver 14.14 Distrib 5.7.16, for Linux (x86_64) using  EditLine wrapper
php:
PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.8-0ubuntu0.16.04.3, Copyright (c) 1999-2016, by Zend Technologies
apache2:
Server version: Apache/2.4.18 (Ubuntu)
Server built:   2016-07-14T12:32:26

Client details:
Chrome Version 54.0.2840.99 m
Firefox 38.0.5
Microsoft Edge 38.14393.0.0
  Microsoft EdgeHTML 14.14393

**Comment by rishikumarsonar** [comment]
Get the same issue, I don't get any content on "Contact Information" section on various forms.

Account Registration
Open a New Ticket

**Comment by panreyes** [comment]
Hi! I'm having the same error with a default LAMP install in Ubuntu 16.04.1 with PHP 7.

This is in /var/log/apache2/error.log:
PHP Warning: sprintf(): Too few arguments in /var/www/html/include/staff/profile.inc.php on line 192, referer: http://xxxx.xx/scp/users.php?id=4
PHP Warning: Creating default object from empty value in /var/www/html/include/class.user.php on line 515, referer: http://xxxx.xx/scp/tickets.php?a=open&uid=5
PHP Fatal error:  Uncaught Error: Call to a member function save() on null in /var/www/html/include/class.user.php:516\nStack trace:\n#0 /var/www/html/include/ajax.users.php(166): User->updateInfo(Array, Array, true)\n#1 /var/www/html/include/class.dispatcher.php(145): UsersAjaxAPI->updateUser('5')\n#2 /var/www/html/include/class.dispatcher.php(38): UrlMatcher->dispatch('/5', Array)\n#3 /var/www/html/include/class.dispatcher.php(120): Dispatcher->resolve('/5', Array)\n#4 /var/www/html/include/class.dispatcher.php(38): UrlMatcher->dispatch('/users/5', NULL)\n#5 /var/www/html/scp/ajax.php(262): Dispatcher->resolve('/users/5')\n#6 {main}\n  thrown in /var/www/html/include/class.user.php on line 516, referer: http://xxxx.xx/scp/tickets.php?a=open&uid=5

**Comment by andysmithfal** [comment]
I had the same issue as luckshot and rishikumarsonar with a completely fresh install of Ubuntu 16.04, Apache 2.4, PHP 7 and osTicket 1.10 - adding a new user would not show the form under the 'Create new user' heading. I switched to PHP 5.6 with the same install and the problem persisted. 
One observation I made (sorry didn't have time to dig too deeply) and not sure if it's relevant, was that hitting the 'Add User' button made three separate AJAX requests to ajax.php?/users/add. My working install of 1.10 (see below) only makes one request. 
Apache's error.log contained the following: 
```
[Mon Feb 13 14:30:49.676997 2017] [:error] [pid 7328] [client xxx] PHP Warning:  Creating default object from empty value in /var/www/html/include/class.user.php on line 515, referer: http://xxx/scp/tickets.php?a=open&uid=4
[Mon Feb 13 14:30:49.677157 2017] [:error] [pid 7328] [client xxx] PHP Fatal error:  Uncaught Error: Call to a member function save() on null in /var/www/html/include/class.user.php:516\nStack trace:\n#0 /var/www/html/include/ajax.users.php(166): User->updateInfo(Array, Array, true)\n#1 /var/www/html/include/class.dispatcher.php(145): UsersAjaxAPI->updateUser('4')\n#2 /var/www/html/include/class.dispatcher.php(38):
```
osTicket version: 
```
# sha256sum osTicket-v1.10.zip 
 68ff411693802e154426d9ec9b2365ff524aad5f6e52ad9422f073ae48e3a46d  osTicket-v1.10.zip
``` 

What I ended up doing was installing a fresh copy of osTicket 1.9.15 (new set of database tables), running the installer script, and then upgrading to 1.10. This seems to have fixed the issue - could the problem lie in the 1.10 installer script?

**Comment by ntozier** [comment]
I've seen this mentioned in a couple threads.  Under PHP7 you have to install 1.9.x and then upgrade for things to work right.  This is not a problem with PHP 5.5 or 5.6 you can install 1.10.  I think its a installer compatibility with PHP7 thing.

**Comment by rayfoss** [comment]
this is clearly a php 7... the fixed was merged into develop, but it is not retroactive. Simply downgrading php will also not fix it... reinstall or manually fix all the hex flags.
