### ISSUE TITLE
 Page does not work. 1.10 Final

### ISSUE THREAD

**Issue by suportgc** [osTicket/osTicket#3502]
Hello good afternoon.

Gostarua the help of you.

My osTicket this date in the newest version, however I am in error on ticket display page.

By accessing the ticket, nothing appears.

The following photo and link

https://suportgc.com.br/suporte

User: lourdes
Password: 123456789
![error](https://cloud.githubusercontent.com/assets/19677143/20274770/fad1714e-aa7c-11e6-98fb-e95ee1f65b99.png)

**Comment by ntozier** [comment]
You do not appear to be running a version of osTicket that we distribute.  Please re-download and install the core source files on your site and see if that fixes your issue.

**Comment by suportgc** [comment]
Hello good afternoon.

This is just a theme for the customer.

The following print administrative area
![ost](https://cloud.githubusercontent.com/assets/19677143/20275229/e36441e2-aa7e-11e6-885b-57ad28cce75c.png)

**Comment by ntozier** [comment]
We do not support 3rd party modifications.   You will need to install the stock code and see if it works.  If it does, then the problem is wit the modifications that you have made.

**Comment by suportgc** [comment]
I understand.

Thanks for the support
