### ISSUE TITLE
1.10 RC3 Export ticket data including ticket message

### ISSUE THREAD

**Issue by edukondalugorla** [osTicket/osTicket#3503]
I want to get tickets "message"  also in csv file when i export tickets. how to solve it.

**Comment by ntozier** [comment]
Huh?

**Comment by edukondalugorla** [comment]
How to export ticket message.

**Comment by Eddie595** [comment]
This is a feature request. @edukondalugorla is looking to have an option (or a default) for the export function(s) to provide the ticket's initial detail\explanation text field in the export file. This would be nice but I feel having an options window for what to export probably has already been requested somewhere down the line.
