### ISSUE TITLE
Problems in a Fresh osTicket install (Ubuntu 16.04)

### ISSUE THREAD

**Issue by gusarg81** [osTicket/osTicket#3507]
Hi, I have problems after a fresh install of osTickets. The installation process went just fine. Now, when I want to login it says:

> Unprocessable Entity

> The server understands the media type of the request entity, but was unable to process the contained instructions.

Apache error log:

> [Tue Nov 15 13:47:37.257144 2016] [proxy_fcgi:error] [pid 31339:tid 140252985440000] [client 10.0.1.1:49482] AH01071: Got error 'PHP message: PHP Warning:  Declaration of AssignmentForm::render($options) should be compatible with Form::render($staff = true, $title = false, $options = Array) in /var/www/virtual/gdnet.com.ar/tickets/htdocs/include/class.forms.php on line 4150\nPHP message: PHP Warning:  Declaration of TransferForm::render($options) should be compatible with Form::render($staff = true, $title = false, $options = Array) in /var/www/virtual/gdnet.com.ar/tickets/htdocs/include/class.forms.php on line 4270\n', referer: http://tickets.gdnet.com.ar/

Apache access log: 

> "GET /scp/login.php HTTP/1.1" 422 285 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.100 Safari/537.36"

This error does not happen on main page of the site (http://tickets.gdnet.com.ar/) but since I can't login, I can't tell if is happening somewhere else.

Any idea?

Thanks in advance.

**Comment by ntozier** [comment]
Version of osTicket?
Version of PHP?
Can you log in as an Agent (URL/scp)?

**Comment by gusarg81** [comment]
Hi, fixed by commenting the line Http::response(422); in login.php to test the error. Seems the user/password stored in my Chrome was causing the problems.

**Comment by greezybacon** [comment]
It seems like this should be reopened. If the 422 is causing errors, perhaps it should be removed.

**Comment by gusarg81** [comment]
@ntozier latest stable version of osTicket, PHP 7.0.8 and now, when that line was there, I can't even log as Agent.

Like I said, fixed by commenting those line of code.

Thanks.
