### ISSUE TITLE
feature request: deactivate task module for selected departments

### ISSUE THREAD

**Issue by markus4000** [osTicket/osTicket#3508]
one of the strength of osticket is, that it is fully selfexplaining.
But it seems that the task module is not full self explaining. So I'd like to turn the task feature off for some departments. I want only use the task for the "Advanced" users.
what do you think?

**Comment by JediKev** [comment]
@markus4000 

You can accomplish this via the Role Permissions. You'd create a Role without any of the Task options enabled. You'd then give the new Role to any Agent you don't want to utilize Tasks.
<img width="420" alt="Screen Shot 2019-12-04 at 12 40 23" src="https://user-images.githubusercontent.com/11823401/70170965-6644a600-1693-11ea-80ab-a4a848480a18.png">

Cheers.
