### ISSUE TITLE
Task no title when created

### ISSUE THREAD

**Issue by blhf** [osTicket/osTicket#3509]
Hi, would like to ask how to fix this issue. 
No Title is displayed when creating task.
 
![image](https://cloud.githubusercontent.com/assets/10716429/20335227/c4050a10-abfb-11e6-9afd-f9360077ed66.png)

**Comment by blhf** [comment]
Currently running updated version osticket v1.10 stable.

**Comment by blhf** [comment]
This is not working for me: https://github.com/osTicket/osTicket/issues/3245#issuecomment-229361902

**Comment by markus4000** [comment]
PHP Version?

**Comment by blhf** [comment]
Hi @markus4000 I'm using PHP v5.6.

**Comment by ntozier** [comment]
Can you define what you mean by "updated version osticket v1.10 stable"?
Have you consulted your PHP error logs?
Did the task infact have a title when it was created?

**Comment by blhf** [comment]
before updating I'm running v1.10rc2 no errors on the task title display. I
can confirm it because I have a back up of v1.10 RC2 version. When I
updated to v1.10 stable the title not displaying anymore when saving.

**Comment by rayfoss** [comment]
May be related to #3531

**Comment by JediKev** [comment]
Are there any PHP, MySQL/MariaDB, or Apache errors? I'm able to create a task with a title on v1.10(latest).
