### ISSUE TITLE
Installation of osTicket 1.10 with german translation fails

### ISSUE THREAD

**Issue by kiwi-x** [osTicket/osTicket#3511]
Hello,

if decompressed the zip archiv of osTicket 1.10, added the german translation from the i18n.osticket.com/download/project/osticket-official.zip file and additionally placed the de.phar file to include i18n folder.

I started the installation with german as default language.

The install.php ends up with a plain white browser window and nothing inside. Logon to admin panel is possible but now there is an issue with configuring tasks and tickets, 'cause the attachement configure button won't appear and there is no save button.

Installation in english runs fine, but switching from english to german as default language I have to translate any mail template by hand :-(

Regards
Kiwi-X

**Comment by ntozier** [comment]
I wasn't aware that the 1.10 language packs had been released yet.

**Comment by kiwi-x** [comment]
Oh.

I'm new on osTicket and I did the installation by downloading the latest stable version and the offered language packages and plugins.

There wasn't any hint, that the language files aren't usable for the 1.10. 

Should I delete the 1.10 installation and go install the 1.9.15 instead?

I don't care, I just wanted to use the newest release for a new installation.

Cheers
Kiwi-X

**Comment by rayfoss** [comment]
You could unpack the language pack manually... See #3451
