### ISSUE TITLE
Add organization or user popup without form

### ISSUE THREAD

**Issue by Bran-Ko** [osTicket/osTicket#3513]
I have Xenial + PHP7.0 + MariaDB10
This is fresh installation of osTicket 1.10

Add organization popup look like 
![image](https://cloud.githubusercontent.com/assets/10847283/20352672/6489bca8-ac18-11e6-8cba-e81cbe3d976c.png)

Add user looks like
![image](https://cloud.githubusercontent.com/assets/10847283/20352692/76fc2aec-ac18-11e6-933e-b12652c520e7.png)

**Comment by Bran-Ko** [comment]
But I don't have any 404 code ...

**Comment by Bran-Ko** [comment]
I forget to write .. I'm using HAproxy before osTicket.
in ost_config is
define('TRUSTED_PROXIES', 'ip.of.haproxy.server');

I don't know if it is important

**Comment by alexisskeates** [comment]
I'm having the same issue both those forms load as show in the screenshots, but there is not fields to enter any information. System information below if that helps.

![screen shot 2016-11-18 at 11 44 07](https://cloud.githubusercontent.com/assets/10001929/20429081/624ceede-ad84-11e6-8ca1-0823078e1c3b.png)

**Comment by Bran-Ko** [comment]
I have almost same info, but I have PHP version 7.0.8-0ubuntu0.16.04.3 (from repository)

**Comment by simonnzg** [comment]
I have this, too. It's a problem that happens with Ubuntu/PHP7. No idea why. Yet.
See #3490

**Comment by williamhodges** [comment]
Same issue.

**Comment by DarthSlider** [comment]
Same Issue.
Windows 2012 R2, OsTicket 1.10, PHP 7.1, Apache 2.4.23, MariaDB 10.1.19

**Comment by tluquet3** [comment]
In v1.10 you apparently need to manually add the fields you want in your user or organization information, they are disabled by default.
Solution:

-     Go to admin panel, "Manage"->"Forms"
-     Choose the contact information form or the organization form
-     For each field, click on config and enable.

This should work.

**Comment by simonnzg** [comment]
Hi Thomas,  I was sure that it was a configuration problem, but assumed it was somewhere in the PHP7 settings, so didn't think about looking in there!
