### ISSUE TITLE
1.9.15 manage.php file migrate fails when files where size = 0

### ISSUE THREAD

**Issue by kainjow** [osTicket/osTicket#3517]
If you run:

    php setup/cli/manage.php file migrate --backend D --to F

And there is a file that has size = 0, it will fail with:

    PHP Fatal error: Call to a member function logError() on a non-object in /path/to/osticket/include/class.error.php on line 33

In class.file.php migrate(), when it tries to read the $source file, it won't read anything so the target file never gets written. Then it tries to read the target file to generate the hash, and this is where the error comes from. Somehow class.error.php is not setup correctly and global $ost is invalid. I had to find out the error by echoing it in the Error class constructor.

**Comment by v60fan** [comment]
Is there any workaround to this?

**Comment by scalatore** [comment]
Dear all,

I still observe this on v1.12.

Best regards

Andrea

**Comment by JediKev** [comment]
@scalatore 

Please see:
https://github.com/osTicket/osTicket/pull/4024

Cheers.
