### ISSUE TITLE
v1.10: Creating a task inside a ticket has no style sheet and no links work

### ISSUE THREAD

**Issue by blueyeguy** [osTicket/osTicket#3518]
When we create a task within a ticket in 1.10 it breaks and shows a page with information but no links work and there is no formatting or style sheet (first image).  After getting back into the system the task shows up on the tasks tab and is viewable from there, but when going back into the task through the ticket, it again breaks and again none of the links are clickable (second image).

osTicket Version	v1.10 (901e5ea) —  Up to date
Web Server Software	Microsoft-IIS/7.5
MySQL Version	5.5.39
PHP Version	5.6.24

![tickettask](https://cloud.githubusercontent.com/assets/11031985/20486889/084adfe6-afc7-11e6-87c9-961fe2f4141d.jpg)
![tickettask2](https://cloud.githubusercontent.com/assets/11031985/20486888/084ad7a8-afc7-11e6-88ac-6135ee9dbd64.jpg)

**Comment by ntozier** [comment]
This was already reported here: https://github.com/osTicket/osTicket/issues/3197

**Comment by blueyeguy** [comment]
Ah, Thanks I did a search but didn't come up with anything. I must have missed it. I can get rid of mine.
