### ISSUE TITLE
Feature Request: Allow Tips on Tips

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket#3521]
![image](https://cloud.githubusercontent.com/assets/5774055/20492335/54d14d80-afe2-11e6-84d3-3ddb3787239f.png)

I think some type of parent to child relationship would help it that only one tip is shown for each parent. I have commented out [this line](https://github.com/osTicket/osTicket/blob/develop/scp/js/tips.js#L45) to allow Tips on Tips to function but the tips keep on stacking up. If you click off the tips they all go away.

**Comment by JediKev** [comment]
This would start to get super messy and to put it frank annoying for most end users/agents...that's why we don't do popups on popups...any argument as to why we should create this feature?

**Comment by jdelhome3578** [comment]
@JediKev I am trying to keep this organized. I have a lot of printers and I don't want to have to duplicate the information on every printer but instead connect the information.
Here is a better screenshot:

![image](https://cloud.githubusercontent.com/assets/5774055/20497091/db96dc46-aff5-11e6-9bb4-8cca22952232.png)

My other idea would be to pull the information all in the same popup. Maybe tabbed over underneath the item with properties.

**Comment by JediKev** [comment]
@jdelhome3578 

I don't think we'll ever implement popups on popups as it's just too messy and not good practice overall. You could possibly implement a scenario where if you click the inline item you'll get a popup box to review the properties?

Cheers.
