### ISSUE TITLE
More field in overview?

### ISSUE THREAD

**Issue by gitfve** [osTicket/osTicket#3523]
Is it possible to add more field? (version 1.9.14)

![p1 jpg](https://cloud.githubusercontent.com/assets/6228825/20518206/94389da4-b09e-11e6-9a38-3521dd8ac507.png)

**Comment by ntozier** [comment]
There is currently no way to do what you are asking in the UI.  That being said the forums has a thread that spans nearly all recent versions. 

http://osticket.com/forum/discussion/75457/a-better-ticket-list

There is a forth coming feature called Custom Queues that should be released in 1.11 (or whatever the next release is numbered) which should allow you to do this with out modifying the core source files.
