### ISSUE TITLE
[BUG] Agent Identity Masking no longer works [1.10]

### ISSUE THREAD

**Issue by ntozier** [osTicket/osTicket#3524]
I have a report that Admin panel -> Settings -> Agents -> Agent Identity Masking no longer works in 1.10.

I have confirmed this in my 1.10 installation.

Original report:
http://osticket.com/forum/discussion/89247/hide-agent-s-name-on-responses-not-working#latest

**Comment by dogatemycomputer** [comment]
+1

**Comment by ntozier** [comment]
ping

**Comment by orangesunny** [comment]
I also have this annoying issue in my installation. :(

**Comment by maurosanjo** [comment]
I also have this problem on my installation. The agent name is hidden on e-mail message, but on web view of ticket history the agent's name is always visible.

**Comment by shimsim** [comment]
Has this been fixed in v1.10.1 or is it only going to be fixed in 1.11.0 ?

If not, is there any alternative fix other than the one posted on the forum discussion above ? I did try that fix but now the user ticket view looks kind of incomplete.

**Comment by JediKev** [comment]
@shimsim I am actually working on this now. Will push the pull request soon, once I do I'll post back here.

**Comment by shimsim** [comment]
@JediKev thats great news, we didnt realize the bug until customers started replying to agents using their names, which was a bit of a shock. its kind of a big bug for us, we like to keep agents personal details off the internet, anyway, using the code edit in the mean time, thanks for the update.

**Comment by shimsim** [comment]
Great, thanks for the interim fix 👍

**Comment by JediKev** [comment]
@shimsim I have pushed the fix for this here - #4008. Please make the changes, test, and report back to me. Cheers.
