### ISSUE TITLE
Email Subject Issue

### ISSUE THREAD

**Issue by Siriuo** [osTicket/osTicket#3528]
In Version 1.9.15 there seems to be an issue where if the person replying adds some text to the end of the subject after the ticket number the system seems to become confused and create a new ticket. 

For example if subject is "Email Subject[#123456]" and the person replying via email changes this to "Email Subject[#123456]Extra"

**Comment by ntozier** [comment]
Try moving the ticket number variable (aka [#123456]) to the front of the subject in the template.
Or... add a space after the ] and see if that helps.
