### ISSUE TITLE
Auto responder too short. If there are a url you can't write nothing.

### ISSUE THREAD

**Issue by PeopleInside** [osTicket/osTicket#3529]
Hi,
please increase the number of character in auto responder.
If you have also needs to put an URL there are no enough character allowed, I see my message truncated.

Also you are allowed to write a long message but when is saved will be truncated. You should be unable to continue to write in the field when max character is reach.
Please increase.

In the screenshot I have short sentence but if there are a URL I cannot add more text because the limit of character is reach.
![immagine senza nome](https://cloud.githubusercontent.com/assets/5006150/20644015/e4d43f16-b427-11e6-88f3-b72dc3d68f42.png)

**Comment by ntozier** [comment]
Version of osTicket?
Steps to reproduce this? (I have no idea what screen you are on.)

**Comment by PeopleInside** [comment]
Oh sorry this is in the wrong place
