### ISSUE TITLE
Ticket Search Issue osTicket (v1.10)

### ISSUE THREAD

**Issue by wsaintclair** [osTicket/osTicket#3530]
Recently install OsTicket.

When I perform an advanced search, I do not list the tickets, only the amount is shown in the search criteria. in the sample Search(3), but don't show de list.

Practically when a ticket is closed or solved we can not see it again.

![image](https://cloud.githubusercontent.com/assets/24207422/20648798/fbe7a332-b486-11e6-91a9-c2d907e0a998.png)

Info:

![image](https://cloud.githubusercontent.com/assets/24207422/20648818/6ce46c6e-b487-11e6-91e5-63c0625d0b37.png)

**Comment by daro1337** [comment]
iI have same problem. Moreover there is another bug, in advanced search => add other field => closed date => between => click on calendar icon and change month to left and it switch to November 1899
![zrzut ekranu 2016-11-28 o 13 34 09](https://cloud.githubusercontent.com/assets/17786393/20668478/62dd05a8-b56f-11e6-8337-9c8678821293.png)

**Comment by wsaintclair** [comment]
It does not work...

**Comment by wsaintclair** [comment]
Issue resolved with this parameter in agent permisions/misselaneous:

Check "Search — See all tickets in search results, regardless of access"

![image](https://cloud.githubusercontent.com/assets/24207422/20813631/b66e91d0-b7ec-11e6-94a5-faf12f6da66f.png)

![image](https://cloud.githubusercontent.com/assets/24207422/20813695/fa115fbc-b7ec-11e6-8d2b-e9b26dfcfa3c.png)
