### ISSUE TITLE
v1.10: Adding A Title in Edit Thread Entry does not work 

### ISSUE THREAD

**Issue by C4RLOCO** [osTicket/osTicket#3531]
When editing an existing message (internal note in my case) from an existing ticket. When trying to add a Title to the Thread Entry, the system does not add the value to the thread. There are no errors displayed as it appears to have accepted the value without issues.

<img width="748" alt="screen_shot_2016-11-27_at_11_18_01_am" src="https://cloud.githubusercontent.com/assets/4073792/20649699/4b814a40-b493-11e6-8115-604de824636e.png">

Server Information
osTicket Version	v1.10 (901e5ea) —  Up to date
Web Server Software	Apache/2.4.23
MySQL Version	5.5.49
PHP Version	5.6.25

**Comment by JediKev** [comment]
Do you edit the thread and then add the title or just save the title without editing thread?

**Comment by C4RLOCO** [comment]
Hi @JediKev,
thanks for the reply.

I did it both ways and the result is the same.
