### ISSUE TITLE
Canned responses and an embedded link to the survey site Osticket 1.10

### ISSUE THREAD

**Issue by suportgc** [osTicket/osTicket#3532]
Hello good day.

I would like an aid with a setup.

I would like that when you end a customer's call, you can submit a satisfaction link.

I already use the Lime Survey system for this work, but I would like to know how to link the ticket number to the form so that we can better identify the customer's response.

**Comment by ntozier** [comment]
You can already do this with canned responses.

**Comment by suportgc** [comment]
Hello ntozier

Got it.

Would it be possible for Lime Survey to automatically import the ticket number?

**Comment by ntozier** [comment]
That sounds like an excellent question for Lime Survey support to answer.

When you built the link you can embed the link to them with the ticket number so its a matter of if they can accept the custom url parameter.

**Comment by suportgc** [comment]
Thanks
