### ISSUE TITLE
Unable to work the search functionality of client UI (v1.10)

### ISSUE THREAD

**Issue by Takuji-S** [osTicket/osTicket#3534]
Now I am just evaluating osTicket. I have created some ticket from the client UI using test users.
Then I tried to search the created ticket using the search function in client UI.
However it seems to be unable to get the result.  it looks like no change in the ticket list.  Hence it seems to be not working fine.

Someone knows the search functionality spec?

osTicket installation Info:
![image](https://cloud.githubusercontent.com/assets/17108836/20678481/3983dafe-b5da-11e6-923f-5f310fb4d291.png)

After clicking the search button (specified a word):
![image](https://cloud.githubusercontent.com/assets/17108836/20678209/347c4fba-b5d9-11e6-93db-f96cc046a747.png)

After clicking the search button (specified a number):
![image](https://cloud.githubusercontent.com/assets/17108836/20678573/932d88de-b5da-11e6-82b8-1d2e006e635c.png)

Regards,
Takuji Suzuki

**Comment by elambro** [comment]
Did you find a fix for this?

**Comment by Takuji-S** [comment]
Yes, I have fixed by applying Fulltext engine (mroonga (fulltext search engine) plus MeCab (bi-gram Markov model engine)) to MySQL/MariiaDB.
After install mroonga and mecab, perform the following:
ALTER TABLE  ost__search ENGINE = Mroonga COMMENT = 'engine "InnoDB"' DEFAULT CHARSET utf8 COLLATE=utf8_unicode_ci;
ALTER TABLE ost__search drop KEY `search`;
ALTER TABLE ost__search ADD FULLTEXT INDEX `search` (`title`,`content`);
