### ISSUE TITLE
*/scp redirects to */ after login

### ISSUE THREAD

**Issue by cogitsa** [osTicket/osTicket#3535]
Hi guys,

I recently did a cpanel to cpanel transfer, server to new server. Everything seems to work fine except for one small thing - one can't access scp. As soon as it's entered in the url bar, it redirects the user back to the front client section. I thought it could have been the .htaccess but that didn't seem to do anything, neither did deleting my browser cookies or trying a different browser all together. No errors in error_log in both the public and scp directories. Using php 7, (was php 7 on previous server), Maria DB 10.1 (was mysql 5.5 on old server) and the latest OS Ticket of 1.10.

Any ideas?

**Comment by ntozier** [comment]
My guess would be your .htaccess file, or webserver config.  I'd recommend doing a fresh install of osTicket, and then migrating your database to test.

**Comment by cogitsa** [comment]
Makes little sense but I disabled PHP FPM and this did the trick I think. Then incoming emails would show as (empty) although attachments still came in. Changing from PHP 7 to PHP 5.6 fixed this, also put PHP FPM back on to see for any effect and no effect. Perfect settings were PHP 5.6 with FPM. OS Ticket is still not fully ready for PHP 7.
