### ISSUE TITLE
Does not match regex issue v1.9.14

### ISSUE THREAD

**Issue by Dorian-Grim** [osTicket/osTicket#3536]
Hi,

I am successfully using https://regex101.com/r/Ij0IQW/1 for a Matches Regex in a filter. However I need a Does Not Match Regex for the given string, so when I select Does Not Match Regex, the filter stops working. I took a look at https://github.com/osTicket/osTicket/pull/481/commits/584465c9a6080a5bddca5face3b5df11018ffcf7#diff-2e0d1c372c827113bd6fc155c8bea6a7R407 but did not see anything wrong with the pregMatchB function.

I am basically lost. Can some one please help me out? Is the filter matching criteria for the "regex does not match" broken somehow?

Dorian

**Comment by Dorian-Grim** [comment]
I am using v1.9.14 (8b927a0), I forgot to mention

**Comment by ntozier** [comment]
Please upgrade to 1.9.15 (current in the 1.9 branch) or current version 1.10 (as of this writing) and re-test.

**Comment by Dorian-Grim** [comment]
But I don't want to upgrade :( ...

**Comment by ntozier** [comment]
Then I dont know what to tell you.  The devs generally do not go back to older versions to try to fix problems in older versions unless they are present in the current versions.
