### ISSUE TITLE
Custom form cannot be deleted from user or organisation

### ISSUE THREAD

**Issue by bernardflach** [osTicket/osTicket#3542]
Version 1.10
After adding a custom form to an organization or user, the form cannot be removed by using more -> Manage Forms.
I now have to dive into the database and remove it.
tried on Chrome, IE and Firefox. Same result. Does not mather if the form has been filled in or not.
tried on a fresh install of OST.. same problem

**Comment by ntozier** [comment]
I can confirm this behavior (at least on Orgs, I didn't attempt on user)

**Comment by ntozier** [comment]
No.
Nor does it work if you click 3 times or speed click it a lot. :)

**Comment by JediKev** [comment]
Sorry as soon as you add the form you are able to delete it but not after the page has been refreshed or you 'Saved Changes'...weird...I'll look into this some more!

**Comment by bernardflach** [comment]
@jediKev : nope.  also not working

**Comment by JediKev** [comment]
#3543 (my pending PR) should fix the issue for ya'll!

**Comment by bernardflach** [comment]
awesome :)
