### ISSUE TITLE
v1.10 'Contact Information' > 'Field Configuration' > 'Setting' : Not taking account of the parameters

### ISSUE THREAD

**Issue by larzabal** [osTicket/osTicket#3547]
We have updated osticket v1.9.15 to v1.10 with success. 

In the 'Contact Information' form, we have parameted a Type 'Short Answer' field.
Now, in v1.10, I modified field's config. In 'Field Configuration' page, 'Setting', I unchecked Visible 'For EndUSers' and 'For Agents' and save parameters. OsTicket save the configuration with success.
But the field is always visible in the form for agents and users. 

If I modified an other parameter (Required, Editable), OsTicket v1.10 no take account of the parameter updated to. And, the problem is in all forms: 'Contact Information', 'Organization Information', etc

I installed on my machine a new installation osticket v1.10 for a localhost test with a database empty. I produce the same problem.

#bug #forms #1.10

**Comment by ntozier** [comment]
Another report here:
http://osticket.com/forum/discussion/89431/agent-can-edit-check-boxes-even-if-not-have-permited

**Comment by mwells1702** [comment]
Any fix on this?

**Comment by Stinkykiller** [comment]
Fresh (new) installtion of v1.10 and the bug is still present. Could we at least get some temporary fix until the next patch?

**Comment by kennethwellin** [comment]
Same problem here: User can still edit even if edit after submission is disabled. Any solution yet?

**Comment by JediKev** [comment]
Has anyone tried #3888 ??

**Comment by geo782** [comment]
1.10.1 i have tried editing the 3 files in #3888 but It stills allows an agent to edit the email field. Btw, Editable is unchecked for email. 
Steps : open ticket, click user name, click at pencil button, change email of user.
