### ISSUE TITLE
Cannot change owner of ticket

### ISSUE THREAD

**Issue by compuvin** [osTicket/osTicket#3549]
Searching for existing users seems to be broken in the release v1.10 (901e5ea)
It appears that I can add a new user but not search for an existing one. This is an issue when changing the owner of a ticket as well as trying to add a user to an organization.

![image](https://cloud.githubusercontent.com/assets/619451/20928432/d018d6ea-bb93-11e6-90ec-c6a4812c6d16.png)

osTicket Version v1.10 (901e5ea)
Web Server Software Microsoft-IIS/7.5 
MySQL Version 5.6.33 
PHP Version 5.6.0

**Comment by ntozier** [comment]
Are you using the LDAP plugin?

**Comment by compuvin** [comment]
I am but I am trying to change the owner to an existing user of the system.

**Comment by ntozier** [comment]
Yes, you made it clear what you are trying to do.  But it works on my system so what I am trying to do is diagnose what else might be affected, and what might be causing it since you did not include any errors.

When you open a new ticket as an Agent does search work?
Have you applied this Pull Request? https://github.com/osTicket/osTicket/pull/3456

**Comment by compuvin** [comment]
I wish it was giving me an error message that I could give you but it doesn't seem to be complaining about anything. If I type in a name in the search box, it just doesn't seem to execute the search. If I open a brand new ticket as an agent I cannot search for an existing user there either. For a new ticket, I can cancel out of the search and can type in the email address and it applies to the correct user.

I have not applied the pull request you mentioned. LDAP seems to work fine for agent login authentication.

**Comment by ntozier** [comment]
The LDAP search function is broken without that PR.  Please try applying it and see if it fixes your problem.

**Comment by compuvin** [comment]
I edited ajax.users.php and commented out that line of code in the Pull Request. I am still having the issue though.

I see this error message in the IIS log:
2016-12-06 21:54:14 10.10.10.97 GET /scp/ajax.php/users q=**testuser** 80 DOMAIN\\User 10.10.10.97 Mozilla/4.0+(compatible;+MSIE+7.0;+Windows+NT+10.0;+WOW64;+Trident/7.0;+.NET4.0C;+.NET4.0E;+.NET+CLR+2.0.50727;+.NET+CLR+3.0.30729;+.NET+CLR+3.5.30729;+InfoPath.3;+Zoom+3.6.0) 500 0 0 181

I see a 500 error. Sorry I'm not much help. I don't have much experience with PHP.

**Comment by compuvin** [comment]
I changed my LDAP plugin settings to use LDAP rather than AD and this seems to have fixed my issue. Weird as this has been working all along without an issue through previous updates.

This may be more of an issue with the LDAP/AD plugin rather than the search.

**Comment by compuvin** [comment]
This has been fixed in a newer release. Not sure what fixed it.
