### ISSUE TITLE
 Unable to open config file for writing. Permission denied! (#3) 

### ISSUE THREAD

**Issue by tdkmatt** [osTicket/osTicket#3552]
Files are correctly promissioned, but keep getting this error

**Comment by rayfoss** [comment]
What OS are you using? `ls -laht` output? What version/branch of osticket?

There are several levels to Linux file permissions:
http://unix.stackexchange.com/questions/16828/what-roles-do-dac-file-permissions-acl-and-mac-selinux-play-in-linux-file-s

https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines

**Comment by tdkmatt** [comment]
Centos 6.8, using cpanel, os-config.php is set to 7777, still does not work, host l3 support looked and saw no issues

**Comment by tdkmatt** [comment]
fork is 1.10

**Comment by rayfoss** [comment]
try creating a file next to it as the apache user, then try modifying it `sudo su -s /bin/sh apache`

**Comment by tdkmatt** [comment]
am i able to pay for support to have this installed at all?

**Comment by ntozier** [comment]
Yes.  Professional installation is available according to: http://osticket.com/support
