### ISSUE TITLE
Github Integration

### ISSUE THREAD

**Issue by tiagoboldt** [osTicket/osTicket#3554]
Hi, 

Has anyone considered integrating osTicket with Github? 

Use case: receiving a support email that creates a ticket within osTicket would also open an issue against a github repository. 

A second iteration would read comments and status from the issue from github and bring them to the ticket, enabling the team to answer or close issues directly from github. 

What do you guys think?

**Comment by rayfoss** [comment]
This is definitely something that could/should go on a plugin. Unfortunately we have no plans to build this out. Have you looked at https://issue-zero.firebaseapp.com/login it tries to make Github issue management simpler. And it's open source https://github.com/angular/issue-zero
