### ISSUE TITLE
dashboard - NaN on y axis

### ISSUE THREAD

**Issue by Dorian-Grim** [osTicket/osTicket#3555]
I get NaN on the y axis all of a sudden...
![image](https://cloud.githubusercontent.com/assets/24250692/21112398/4e8beb38-c0ae-11e6-9e5e-053586aa4454.png)

I don't know what I  did wrong, but I am sure it was showing fine. I also found this, http://osticket.com/forum/discussion/85570/y-axis-on-dashboard-chart-shows-nan-and-the-dates-are-8-days-old , but can't seem to understand what mcseforsale stumbled upon. What I can note is that I don't have 8 days old x axis, but yesterdays, 11/12/2016 (dd/mm/yyyy), date.

![image](https://cloud.githubusercontent.com/assets/24250692/21112535/c3acbd7a-c0ae-11e6-8b96-ab716035bc30.png)

**Comment by ntozier** [comment]
1.9.14 is old.  You should upgrade to the current version in your tree at least (1.9..15), if not the actual current version 1.10 as of this writing.  Did you perform any changes on the server that may have affected this? Are you running cron.php regularly? Do you have any errors in the PHP error log?

**Comment by Dorian-Grim** [comment]
I see these two in the console, only in the dashboard
![image](https://cloud.githubusercontent.com/assets/24250692/21114721/b83c9c96-c0b6-11e6-9d5a-82511648a561.png)
No php error
Didn't touch the source files, only configuration from the web-interface.
I am running cron.php with my task scheduler on the server.

**Comment by Dorian-Grim** [comment]
So after I created a ticket this morning, 13/12/2016, the problem dissapeared. But I have no explication in why.
