### ISSUE TITLE
Can't delete SAVED Searches under Advanced Ticket Search v1.10

### ISSUE THREAD

**Issue by jcmachadouga** [osTicket/osTicket#3558]
Can't delete SAVED Searches under Advanced Ticket Search v1.10

If you save any search, you won't be able to delete them.

Click on delete:
![image](https://cloud.githubusercontent.com/assets/12191381/21196731/b95539d4-c206-11e6-8fbf-b6cb5a58de09.png)

Click OK to confirm:

![image](https://cloud.githubusercontent.com/assets/12191381/21196772/e3fd4c4e-c206-11e6-80a1-6392814c26b4.png)

Saved SEARCH is still there:

![image](https://cloud.githubusercontent.com/assets/12191381/21196790/f9b5752a-c206-11e6-92cd-34c22684cdf3.png)

### Versions
Server Information
osTicket Version v1.10 (901e5ea) —  Up to date  
Web Server Software Microsoft-IIS/8.5 
MySQL Version 5.6.17 
PHP Version 5.6.22 

Happens on any browser.

**Comment by ntozier** [comment]
So like: https://github.com/osTicket/osTicket/issues/2662 ?

**Comment by jcmachadouga** [comment]
Wow... I am blind... searched for it and didn't find it... Thanks !

**Comment by ntozier** [comment]
Very welcome. :)

Please close this one.

**Comment by rayfoss** [comment]
We should probably make DELETE enabled a check on the dashboard... or switch to a post/method approach like symfony and ror.
