### ISSUE TITLE
[Feature Request] Ticket Status in action bar [1.10+]

### ISSUE THREAD

**Issue by ntozier** [osTicket/osTicket#3560]
### Description

When scroll down a tick the action bar opens at the top of the screen to grant easy access to the commands that you can use on the ticket.  Forum user: mLipok is requesting that the tickets current status be added to this bar.

For screen shots on what this would look like please consult the forum post that he authored which is here: 
http://osticket.com/forum/discussion/89424/ticket-status-in-sticky-bar

### Versions
1.10+

**Comment by JediKev** [comment]
I have a pull request (#3562) pending on this. 🙂

**Comment by mlipok** [comment]
This one thread could be closed.
Continuation should be in #3562

**Comment by rayfoss** [comment]
Continuation in #3562
