### ISSUE TITLE
Agent / Staff Terminology

### ISSUE THREAD

**Issue by dbinoj** [osTicket/osTicket#3563]
Is it possible to use the term "Staff" in newer osTicket installations? A configurable option might be nice, even though they are called as agents in the code. Can we override the single term in any language files? Tried searching for the reason for change from Staff to Agent in release history and issues, but I could not find them.

**Comment by dbinoj** [comment]
Found the Forums. I have a feeling that GitHub issues are being used only for bugs these days. Will close this issue and create a post in the Forums.

**Comment by ntozier** [comment]
We've actually moved away from calling them staff, to calling them Agents.
So I do not think that you are going to get much traction on changing it back.

**Comment by dbinoj** [comment]
I'm having trouble in registering and posting a question in the forum. My profile page gives a Page Not Found message and I'm not able to create posts. I've verified my email. Is there any other steps involved?

**Comment by ntozier** [comment]
Yes.  Someone has to authorize your account.  Which I have done.

**Comment by dbinoj** [comment]
@ntozier, Ah.. Okay. Thanks! :+1:  BTW, I think I'll ask my question here just for this issue. Hope it will be fine. 

But our employees are used to be called as Staffs (and they are, even officially) and the change from Staff to Agent is not warmly welcomed. It gives an inferior feel to them? :confused: We are a University and our staff are mostly seasoned staff and are kind of hard to persuade. What do you suggest we do? As of now, I have reverted back to a 1.8 version which we were running for a long time.

**Comment by rayfoss** [comment]
```
include/class.report.php:212:            $headers = array(__('Agent'));
include/staff/tickets.inc.php:69:            'heading' => __('Agent'),
include/staff/tasks.inc.php:54:            'heading' => __('Agent'),
```
You're welcome.

**Comment by dbinoj** [comment]
Thanks! Though to help in future updates, I'm thinking of making a config option which we could switch between the two terms. Shall I try to make it into an option in Admin Panel and submit my changes? If so, what will be the best way to implement this? Or am I better off replacing the string whenever we update? I'm replacing the stings for now. Thanks for the help though :+1: :smile:

**Comment by ntozier** [comment]
I'd recommend that as a plugin.

**Comment by dbinoj** [comment]
Thanks for the feedback!
