### ISSUE TITLE
FAQ Hide Content

### ISSUE THREAD

**Issue by firepro20** [osTicket/osTicket#3565]
Running version 1.10

Hi is it possible for the FAQ content to be hidden on the front support page, and only the link "General Fix" visible. I am asking so that front page won't be cluttered by content that is contained in the FAQ itself. I want to have a presentable support landing page with just links to the individual FAQs. Is this possible?

![image](https://cloud.githubusercontent.com/assets/17837413/21344242/0904a8aa-c69b-11e6-915a-06344db6f7d6.png)

**Comment by ntozier** [comment]
FAQ categories aren't displayed on the front support page.  So... I'm not sure what your talking about.

They are displayed when a User clicks Knowledgebase.  Also that folder is not the stock one, so I'm going to assume that you are using some third party theme.  If you would like support you will need to uninstall it first as we do not support 3rd party themes, mods, or plugins.

**Comment by firepro20** [comment]
Fixed by commenting out the Treat php code
