### ISSUE TITLE
Permissions spelled wrong

### ISSUE THREAD

**Issue by craig-tx** [osTicket/osTicket#3567]
* [ X] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

Canonical URL is [staff.inc.php L53](https://github.com/osTicket/osTicket/blob/c0ab96790b114ed5638c6c344b8252f7f959562a/include/staff/staff.inc.php#L53)  

**Permisions** should be **permissions** https://en.oxforddictionaries.com/definition/permission

![sp](https://cloud.githubusercontent.com/assets/16706018/21369591/3c769fa4-c6cd-11e6-89c7-1b35d029418f.png)

**Comment by JediKev** [comment]
Thank you! I made pull request #3568 to fix it!

**Comment by rayfoss** [comment]
Fixed by #3568
