### ISSUE TITLE
ost_ticket__cdata custom field not updated

### ISSUE THREAD

**Issue by fdellwing** [osTicket/osTicket#3569]
I installed a fresh v1.10 from http://osticket.com/download today to try some things for the future.

I than added a `form_field`:

```sql
'40', '2', '12289', 'choices', 'Status', 'netfutura_status', '{\"choices\":\"1:nicht bearbeitet\\r\\n2:OK\\r\\n3:in Arbeit\\r\\n4:n\\u00e4chstes Update\",\"default\":\"1\",\"prompt\":\"\",\"multiselect\":false}', '4', NULL, '2016-12-21 14:10:53', '2016-12-21 14:49:22'
```

The field also got correctly added to `ost_ticket__cdata`.

But if I change the field `_cdata` is not showing the value (sometimes it does, but most times it shows simple 0)

`ost_form_entry_values` shows the correct data and thats where the ticket details is it getting from.

```sql
'10', '40', '{\"3\":\"in Arbeit\"}', NULL
'11', '40', '{\"2\":\"OK\"}', NULL
'12', '40', '{\"2\":\"OK\"}', NULL
```

But I want to access this data from the ticket overview. I edited the code and it works fine. But only if the `_cdata` table is correct.

![ost](https://cloud.githubusercontent.com/assets/22813377/21393443/bc41fcf2-c794-11e6-9e97-a6f25d478da1.png)

```php
<td><?php echo explode(",",$T['cdata__netfutura_status'])[1]; ?></td>
```

```sql
'4', 'Test', '2', '3,in Arbeit'
'5', 'Test 1', '3', '0'
'6', 'Test 2', '2', '0'
```
Is there something I just dont get? When is the _cdata table being updated? Why is is not showing the correct information? Would be nice if someone have an idea for me...

**Comment by fdellwing** [comment]
I testet some more..

If I drop the table and reload the site the table gets rewritten and all data are available.

So if I edit a ticket the value gets not correctly written in the table instead it writes 0. Can you fix that?

I think an ugly workaround may be to automaticly drop the cdata table every time a ticket is edited?

**Comment by mlemens-como** [comment]
I am having this issue too in v1.10

**Comment by mlemens-como** [comment]
To add to it, it is the "Choices" custom field that does it. I have a "Long Answer" custom field and it saves to the _cdata table just fine. I can confirm dropping the table and letting oSticket recreate it works also.
