### ISSUE TITLE
Monthly News

### ISSUE THREAD

**Issue by markus4000** [osTicket/osTicket#3577]
Dear @protich, dear Devs,
it would be nice to have something like "monthly news" where you report about the state of development. even if there is not a new release.
You have a huge community and we love the product but we don't know what's going on with the product/project. Tell us, what you are doing, what is planned, what is done and so on.
A project that does not communicate does not exist.
thank you and best regards
Markus

**Comment by rayfoss** [comment]
We are communicating, in the forums, on irc and through bugs and pull requests here. Do expect news by the end of the week.

**Comment by Chefkeks** [comment]
@rayfoss 
> Do expect news by the end of the week.

Nah... I expect awesome gifts 🎉 🎈 and some great cake 🍰 when celebrating my birthday at the end of the (work-)week 😄 😁

**Comment by markus4000** [comment]
So I'm looking forwad to that
