### ISSUE TITLE
I cannot set smtp to email

### ISSUE THREAD

**Issue by ezekel** [osTicket/osTicket#3581]
I have this version installed in go daddy 
`System Settings and Preferences - osTicket (v1.9.9-1-gbe2f138)`

this is the set up in `Sending Email via SMTP `

hostname: smtp.gmail.com
port :  587
Authentication Required: yes 
Header Spoofing:  allow

when I tried to save changes it will show error `Unable to log in. Check SMTP settings.`

is there something I missed ?

Thank you in advance.

**Comment by ntozier** [comment]
Are you actually using gmail... o are you using gsuite?
Also your version is a little old.

**Comment by ezekel** [comment]
@ntozier yes im using my gmail account...i dont know why it is not working

**Comment by ezekel** [comment]
@ntozier...gsuite ?

**Comment by ntozier** [comment]
gsuite is the new name for Google Domain Services with email, docs, etc.

**Comment by ezekel** [comment]
@ntozier, 

why is that I cannot set smtp even I use the smtp of our domain but still no luck...maybe there is other configuration that I missed ?

**Comment by ezekel** [comment]
@ntozier ,

I also tried to diagnose in sending email, it successfully sent but I did not receive the email.

Thank you in advance.

**Comment by ntozier** [comment]
You haven't provided us enough information about your set up [the webserver, and mail server] or settings to be able to help you.  You might want to read this:  [Please read before requesting assistance](http://www.osticket.com/forum/discussion/89130/please-read-before-requesting-assistance). and you may want to pursue this on the forums instead.  You also might want to search there for people having the same issue and see if they found solutions.
