### ISSUE TITLE
Timezone IST (and others) Ambiguity

### ISSUE THREAD

**Issue by dbinoj** [osTicket/osTicket#3583]
The timezone returned by `timezone_name_from_abbr` can not be trusted as it just selects the first result sorting the tz name alphabetically. This messes up times displayed in the site even though timezone in OSTicket System Settings, OSTicket User Prefs, php.ini, MySQL, Server OS are all set to the same value.

Eg. IST refers to Israel/Indian/Irish Standard Times (Ref: [List_of_time_zone_abbreviations](https://en.wikipedia.org/wiki/List_of_time_zone_abbreviations)) 
One may intend to use Indian/Irish timezone but "Asia/Jerusalem" comes first alphabetically.
Few other TZs which I found to have duplicates are ACT, AMT, BST, etc.,

Either function `get_from_database` in `class.timezone.php:165` should be modified to translate ambiguous timezones with some other reference value or a better method must be implemented.

Related StackOverflow answer: http://stackoverflow.com/a/30958892

**Comment by ntozier** [comment]
Thanks for the report (and informational list)

**Comment by scslogin** [comment]
This happens with "AST" being interpreted as "Asia/Riyadh" while we are actually on "America/Santo_Domingo". Note that PHP has no problem outputting the correct time with "echo date(DATE_RFC2822)".
