### ISSUE TITLE
Unregistred users can't see images in FAQ

### ISSUE THREAD

**Issue by yod527** [osTicket/osTicket#3588]
### Description

Unregistred users can't see images in FAQ. (FAQ allowed for all), To make images visible I need to login in any role (client, staff, admin). Images stored on FS.

### Steps to Reproduce

1. Log out anywhere in the system.
2. Create FAQ conating image added via text editor pane.
3. Open FAQ that contains images.
4. Get JS console erros:

faq.php:109 GET http://example.com/tickets/kb/ajax.php/i18n/ru/js 
faq.php:76 GET http://example.com/tickets/file.php?key=o2jl2widjbvdmxjpvmtwf83gfvhacs…4400&signature=8f8c780f7923a9b5bffa66a3caf6a9032391a4b4&disposition=inline 422 (Unprocessable Entity)
faq.php:76 GET http://example.com/tickets/file.php?key=snp1fqdbikot6zlmcnloruprk2pcfu…4400&signature=48623c1ae76b221f735fd6f6183564c60c34c7ed&disposition=inline 422 (Unprocessable Entity)
faq.php:76 GET http://example.com/tickets/file.php?key=oiut7sy1hzzwalysv3fvdehurne9fz…4400&signature=03cf428a516c2ebb05077dc520696398893b5d6d&disposition=inline 422 (Unprocessable Entity)
faq.php:109 GET http://example.com/tickets/kb/ajax.php/i18n/ru/js 404 (Not Found)

![test](https://cloud.githubusercontent.com/assets/2010171/21607950/216a8b8a-d1c2-11e6-8486-b5c14fe0f3fd.png)

Bug is not stable. Sometimes after several logins images starting to show correctly, sometimes not. (browser cache?)

**Expected behavior:** 

Images showed correctly for guiests.

**Actual behavior:** 

Images is showing for registered users only.

### Versions

osTicket: v1.10 (901e5ea)
Server: Apache/2.4.18 (Ubuntu) //16.04
MySQL: 5.7.16
php: 7.0.8-0ubuntu0.16.04.3

Langpack:
ru — include/i18n/ru.phar 
145919, for version v1.9 
Mon, 28 Mar 16 20:26:01 +0000

**Comment by yod527** [comment]
Just deplyed current version from development branch: same issue.

**Comment by rayfoss** [comment]
Hey, it seems like you're requiring login to view attachments...

![screenshot from 2017-01-03 09-06-34](https://cloud.githubusercontent.com/assets/876076/21611836/33fd4338-d194-11e6-875b-21e202f64c6a.png)

Reply if this is not the case!
