### ISSUE TITLE
Generating POT files is not working anymore (might be bigger issue)

### ISSUE THREAD

**Issue by rbukovansky** [osTicket/osTicket#3589]
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

I have updated to latest osTicket 1.10 and command `php manage.php i18n make-pot` is not working anymore.

### Steps to Reproduce

1. Install fresh osTicket 1.10
2. From terminal/commandline and from folder with that installation run:
`php manage.php i18n make-pot > messages.pot`

**Expected behavior:** [What you expected to happen]
Full messages.pot is generated

**Actual behavior:** [What actually happened]
messages.pot contains only: `<html></html>`

### Versions

osTicket 1.10
CentOS 7

**Comment by rbukovansky** [comment]
@greezybacon Could you please take a look if you have any spare time? Thanks.

**Comment by rbukovansky** [comment]
Well, it seems that whole manage.php is broken. All commands are returning `<html></html>` for me.

**Comment by greezybacon** [comment]
```
➜  osTicket git:(develop) git checkout v1.10
...
HEAD is now at 901e5ea... Add release notes for v1.10
➜  osTicket git:(901e5ea) $ php manage.php i18n make-pot > messages.pot
account.php
ajax.php
avatar.php
bootstrap.php
captcha.php
...
scp/js/ticket.js
scp/js/tips.js
scp/js/upgrader.js
➜  osTicket git:(901e5ea) $ ls -l messages.pot
-rw-r--r--. 1 greezybacon greezybacon 331658 Jan  3 09:11 messages.pot
➜  osTicket git:(901e5ea) $ 
```
So it looks like it's working for me ...

```
➜  osTicket git:(901e5ea) $ rm include/ost-config.php 
➜  osTicket git:(901e5ea) $ php manage.php i18n make-pot               
<html></html>
```

Maybe you need to perform the installation first?

**Comment by rbukovansky** [comment]
Well, it has been long time since I did it... Oh boy! 😱

Thanks, @greezybacon!
