### ISSUE TITLE
IE Login Issue

### ISSUE THREAD

**Issue by gauravjhs** [osTicket/osTicket#3590]
We are using v 1.10

User/Admin is unable to login on IE. Every time user is redirected to login screen.

Tried it with the latest checkout from Git as well.

**Comment by rayfoss** [comment]
Which version of ie ? do you get javascript errors?

**Comment by gauravjhs** [comment]
We tried it with all versions of IE and there is no javascript or any other error.

**Comment by rayfoss** [comment]
You're in luck, this happened to me too... the solution for me was to re-enable the Contact Information form fields. Here are their defaults
![screenshot from 2017-01-04 11-01-56](https://cloud.githubusercontent.com/assets/876076/21651248/87c35316-d26d-11e6-9ada-fc1bed7debf4.png)
![screenshot from 2017-01-04 11-01-48](https://cloud.githubusercontent.com/assets/876076/21651251/87cccebe-d26d-11e6-9a8e-a8af7725f363.png)
![screenshot from 2017-01-04 11-01-37](https://cloud.githubusercontent.com/assets/876076/21651250/87c892cc-d26d-11e6-9dc7-6763c86d488e.png)
![screenshot from 2017-01-04 11-01-28](https://cloud.githubusercontent.com/assets/876076/21651249/87c7953e-d26d-11e6-80fe-9452edb3e375.png)

**Comment by gauravjhs** [comment]
Hi Ray,

Unfortunately this didn't work for me. Any clue what is happening?

I tried a fresh installation with same database but that didn't work either.

**Comment by rayfoss** [comment]
@gauravjhs are you on php 7.0? fixes this issue https://github.com/osTicket/osTicket/pull/3621

**Comment by gauravjhs** [comment]
@rayfoss I am using PHP 5.4.16
