### ISSUE TITLE
Orgainsation User List redirected to Full User list on page change

### ISSUE THREAD

**Issue by gauravjhs** [osTicket/osTicket#3591]
Steps to reproduce
1. Goto Users -> Organizations 
2. Click on Organization
3. Goto any other page on user list
4. Link Changes from "orgs.php?id=4" to "users.php?sort=&order=&p=2"
5. It starts showing all users on the platform.

**Comment by ntozier** [comment]
1. Version of osTicket?
2. Screen shot?
3. Why do you think that this a problem?
