### ISSUE TITLE
1.10 : Lazy Lock Issue

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket#3592]
### Prerequisites

* [y] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [y] Do you have any errors in the PHP error log, or javascript console?
* [n] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [y] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

An agent that is not an Administrator on the computer is unable to get a good response back on the lock. The lock does appear to be generated in the database but a 500 error is generated on the browser side.

![image](https://cloud.githubusercontent.com/assets/5774055/21643456/55df9524-d256-11e6-9548-d0edd19b3e05.png)

![image](https://cloud.githubusercontent.com/assets/5774055/21643467/69541d8c-d256-11e6-909e-a75fb1f5dc02.png)

![image](https://cloud.githubusercontent.com/assets/5774055/21643474/7b151878-d256-11e6-8122-360ddb69778f.png)

I have noticed that the drafts are working fine even after the 500 error on the lock:
![image](https://cloud.githubusercontent.com/assets/5774055/21643554/eb92e86e-d256-11e6-86a5-e4f17efd8cd4.png)

### Steps to Reproduce

1. Log in using HTTP passthrough and LDAP plugin latest versions
2. Open existing ticket
3. start typing in the reply box

**Expected behavior:** I expect the ticket to be locked and not give a message

**Actual behavior:** I am given a message and the Chrome log shows a 500 error on the lock request [shown in the above images]

### Versions

osTicket Version	v1.10 (901e5ea) 
Web Server Software	Microsoft-IIS/8.5
MySQL Version	5.7.16
PHP Version	5.6.28
Windows Server 2012 R2
Chrome 55.0.2883.87 m (64-bit)

**Comment by greezybacon** [comment]
Generally HTTP 500 errors generate errors that show up in some log file. Are you able to find an PHP errors and could you attach them?

**Comment by jdelhome3578** [comment]
@greezybacon that's what I thought but I'm not getting any errors in the PHP log.
