### ISSUE TITLE
Task connection with Ticket number issue

### ISSUE THREAD

**Issue by jighem** [osTicket/osTicket#3593]
Running Osticket ver. 1.10

Task in the task list does not show ticket for which it is created for .
Is there any way by which all tasks would not be visible to all
Currently all tasks visible to all
Ideally only tasks assigned to me should only be visible.

When ticket opened, it shows task created for it in task tab but when we open task from task menu it doesn't show any clue about ticket

**Comment by ntozier** [comment]
Tasks are independent of tickets such that the person [Read: Agent] who was given the task may have no rights to view the original ticket, so I'm not sure you want the task to display that information to the Agent since it shouldn't matter.

**Comment by markus4000** [comment]
Usecase: a agent who is assigned to a task wants to have the big picture. so he has to know to which ticket the task is related. I don't see any reason why a task should not have a link to the ticket. it doesn't matter if the agent has the right to see it or not. even if the agent doesn't have the right to see it, he should know that there is a related ticket to the task. I do not really see your point @ntozier why you don't like the idea.
there are many related requests open. i think it is a valid point.
#2446
#2578
#2673
#2068

**Comment by ntozier** [comment]
Tasks are primarily designed as generic internal 'to do' list that can be created independently or can be attached to other models such as tickets, organizations, users...etc.  So not all tasks are going to have an ticket # to display / link.  

Also since you pointed out that this is essentially the same request as: https://github.com/osTicket/osTicket/issues/257 
you should close this duplicate Feature Request.

**Comment by moedit** [comment]
Another use case is an agent needs to configure part of a system which is related to a ticket that establishes which client that relates to, so there may be a number of same tasks but each will need customizing based on the client, for us it would be essential to display the link to the original ticket.
Is this something that can be done?
