### ISSUE TITLE
Task Related

### ISSUE THREAD

**Issue by jighem** [osTicket/osTicket#3594]
Current Version v1.10 (901e5ea)
Currently when we allow users to view all tickets then it also allows all tasks in the departments to be seen by the agent which should not be the case.
If you say they will be able to see their department tasks then how I can assign individual tasks as selecting department is compulsory in task creation
![taskdept](https://cloud.githubusercontent.com/assets/24699194/21674126/65f1075c-d352-11e6-8ecf-f77892487725.png)
then we need to make assign as compulsory instead of department.

**Comment by JediKev** [comment]
You simply choose an 'Assignee' right next to the box. If you have the Task Alerts & Notices set up the Agent assigned should get an alert saying they have a new task.

**Comment by jighem** [comment]
You didn't got me @JediKev
I don't want to show personal task to other members but in current scenario once we select department the task is visible to others also.
What I want is instead of department agent should be mandatory

**Comment by Chefkeks** [comment]
So you want some kind of "private" / "personal" tasks which can only be accessed by the owner / the agent who created the task?
Or do I misunderstand that too?

**Comment by jighem** [comment]
Yes true

**Comment by mlipok** [comment]
I would to add my 2 cents.
@Chefkeks  says:
"So you want some kind of "private" / "personal" tasks which can only be accessed by the owner / the agent who created the task?"

I think this should works like this:
Agent/staff member assignee should be mandatory. 
Staff member (moderator/admin....) should be able to create task for other staff member.
The creator and assignee + colaborators should be able to view independently from lack of Team/Group/Department selection.

For example I'm a boss of small company I want to add new task to one of my employer (staff member).
I want to select this staff and only he should be able to see this task content.

**Comment by jighem** [comment]
True at certain extent @mlipok
Agent should view tasks assigned to them or by them
Admin should be able to see all tasks

**Comment by ntozier** [comment]
@jighem Re: "Admin should be able to see all tasks"
Admin **SHOULD NOT** be able to see all tickets/tasks.  The Admin's job is to configure, administrate, and maintain the ticket system not service tickets. They shouldn't have access to any tickets.  Being an admin means osTicket administrator, which is how this works now.

**Comment by mlipok** [comment]
I was using "admin" in not proper way.
Usually this is website administrator.

But I was think about SiteOwner or CompanyManager which is giving task to employers.
But the best description would be TaskCreator+TaskAssignedAgent/Staff
