### ISSUE TITLE
Feature Request: Agent Ticket View

### ISSUE THREAD

**Issue by jighem** [osTicket/osTicket#3595]
Is it possible to allow agents to search and view tickets but not be able to see all their department tickets in open tickets?

The following are the things that should happen when "limit access to assigned tickets" is checked for the agent

-  Agent should be able to see tickets assigned to them only.
-  Agent should be able to search ticket by number, organisation or email id or other parameter for search. 
    - Reason: When a client calls, they may ask to talk to  another agent, but to buy time we may ask for their ticket id or other details to search their ticket. Then, reply if required, after claiming the ticket.
- Agent should not be able to reply on the ticket unless they claim the ticket.
- Locked tickets must not be transferred to claiming agent

**Comment by rayfoss** [comment]
![screenshot from 2017-01-05 09-59-13](https://cloud.githubusercontent.com/assets/876076/21687132/b316f94e-d32d-11e6-9d1d-6bbaded75da5.png)
this is a setting controllable by the agent

Other relevant settings:
![screenshot from 2017-01-05 10-07-30](https://cloud.githubusercontent.com/assets/876076/21687438/e5ef71d8-d32e-11e6-9dc7-242127737fdd.png)
![screenshot from 2017-01-05 10-04-04](https://cloud.githubusercontent.com/assets/876076/21687439/e5f1cb40-d32e-11e6-9b37-00b442d2a84e.png)
