### ISSUE TITLE
Feature Request: Default DateTime Format for Polish

### ISSUE THREAD

**Issue by mlipok** [osTicket/osTicket#3599]
for : "Day, Date and Time Format"
Please preset it for Polish to this settings:

EEEE, d MMMM y HH:mm

Results:
czwartek, 5 stycznia 2017 22:22

**Comment by JediKev** [comment]
@mlipok 

Any Admin can configure the day, date, and time formats for the system. `EEEE, d MMMM y HH:mm` is valid and will work just fine:
<img width="430" alt="Screen Shot 2019-12-04 at 13 23 48" src="https://user-images.githubusercontent.com/11823401/70173844-54fe9800-1699-11ea-8551-eb383d7c5455.png">

Please reopen if you think I missed something.

Cheers.
