### ISSUE TITLE
Title not changed in customized version.

### ISSUE THREAD

**Issue by cyberformed** [osTicket/osTicket#3601]
Title bar is still showing osTicket after customization. It shows perfectly with page reload. but showing the title bar osticket after clicking tickets link which causes an ajax call.

**Comment by ntozier** [comment]
Huh?

**Comment by fdellwing** [comment]
Can't confirm this. Titlebar is perfectly fine in user login.

**Comment by rayfoss** [comment]
can't reproduce. please follow the issue template
