### ISSUE TITLE
Advanced Search results have incorrect Date Created values

### ISSUE THREAD

**Issue by JohnDelisle** [osTicket/osTicket#3602]
### Prerequisites

* [Yes] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [No] Do you have any errors in the PHP error log, or javascript console?
* [Yes ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [Yes] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

When using Advanced Search, and sorting by Date Created, the tickets are sorted by their created date, BUT, the values of the dates in the "Date Created" column are NOT their created dates, they're the "Last Updated" date values.

### Steps to Reproduce

1. Log in as staff
2. Go to "Tickets"
3. If you see "Advanced Search" with a little "clear" button beside it, click "clear" to clear any existing advanced searches.
4. Click "Advanced" to begin an Advanced Search.
5. Check "Status", select "is", and enter "Open".  This should do an advanced search for any Open tickets.
6. Click "Search"
7. Look at the Date column.  It should be "Date Created".  If not, change your sort order to "Priority + Date Created".
8. This is an IMPORTANT STEP - Click the "Date Created" column header, and change the sort order.  This seems to affect the results of this issue.
9. Look at the dates, and hover over a ticket number.  Notice that the dates in the "Date Created" column are NOT the actual ticket creation date (as seen when hovering the ticket number).  The dates are the last-update dates (or date of last correspondence, not 100% sure). 
10. Note that the date is sorted by the actual Date Created, even though the last-update date is displayed in the column.

**Expected behavior:** 

For the dates in the "Date Created" to be the actual creation date of the ticket, and for the sort order to be based on actual Date Created values. 

**Actual behavior:** 

Dates in the "Date Created" column are NOT ticket creation dates, they're last-update or last-message dates.

Note the "Date Created" value here:
![image](https://cloud.githubusercontent.com/assets/2569504/21745002/ff055732-d4e6-11e6-9b67-e82da1086bd9.png)

This is the ACTUAL "Date Created":
![image](https://cloud.githubusercontent.com/assets/2569504/21745003/08f4298a-d4e7-11e6-8ff6-53947e57752a.png)

This is the "Last Message" date, which seems to be shown in the Advanced Search results as "Date Created":
![image](https://cloud.githubusercontent.com/assets/2569504/21745006/122efd72-d4e7-11e6-8f48-db23a2b6caa8.png)

### Versions

v1.10 (901e5ea)
Chrome current version.  Same behaviour in MSIE.
CentOS 7.2 current.

**Comment by fdellwing** [comment]
Can confirm this issue.
