### ISSUE TITLE
Open or closed ticket assigned only

### ISSUE THREAD

**Issue by Balazs1985** [osTicket/osTicket#3605]
Helo,

So I need options and settings, which the employees can only see their own trouble tickets from their ticket, the other is not. When I use this option (Limited Access: /assigned_only/), you do not see in the open you do not have tickets, but will disappear and not see a single ticket is not closed. So they can not open them again if necessary, either.

It is necessary that the open and the closed units are handled separately.

Version: osTicket (v1.9.14)

**Comment by fdellwing** [comment]
Can confirm this, but asking the question, why an agent should ever need to reopen a ticket?

**Comment by Balazs1985** [comment]
Helo, thank you for answer, but....
...Based on SOS telephone notification to the opening of additional administration and a ticket is needed.
Furthermore fundamentally useful if an employee sees the mistakes of the past and tickets.

**Comment by fdellwing** [comment]
I'm with you, that he should see his old tickets. Will take a closer look into this later. Didn't found the problem on my first look.

**Comment by fdellwing** [comment]
Can not find the error here, the db query seems to be correct but the foreach does not gets a single element. Someone with more insight in the code have to look at this.
