### ISSUE TITLE
Different client mails with same subject goes into same ticket thread

### ISSUE THREAD

**Issue by SoporteMesi** [osTicket/osTicket#3607]
Hi,
We have recently updated from 1.9.15 to 1.10 and we have notice some odd behavior. When many clients send us an email with the same subject in a very short amount of time, the osticket join all of them in one thread.

I mean, last case we see 5 clients send us an email with word "help" in subject. Instead of having 5 tickets created, osticket created only one ticket with all of them inside.

How can we prevent this from happening, to have every new email to open a new ticket and only those with the ticket ID to be considered part of an existing one?

**Comment by rayfoss** [comment]
Do they all come from the same email address? How is your email setup (piping or imap/pop)? Is there any forwarding happening in between?

**Comment by SoporteMesi** [comment]
Hi,
Hi we fetch emails from imap account. It's configured in the osticket panel with a cron every 5 minuts.

Every one of them came from a different emails address. The only thing in common is the subject (and, of course, our address as "to" in the emails).

You can see the headers from one of those 5 emails here:  http://pastebin.com/My9fTBEK

**Comment by rayfoss** [comment]
Two ideas:
1. The spam filter is mangling the email-id to be the same between the emails.... or
2. There is a bug that treats [PAGOS-MESI] as a ticket id.

**Comment by ntozier** [comment]
Please provide the headers from all 5 emails.

**Comment by SoporteMesi** [comment]
Hi,

I don't thing the [PAGOS-MESI] makes conflict, becouse all our mails has that. But i'm sending you here many headers from those mails: http://pastebin.com/n0ThdbVf

While we were talking here, we got new emails wich got added to the same ticket.

**Comment by rayfoss** [comment]
"In-Reply-To: <4821EE07.3030701@mesi.com.ar>"... They are all in reply to the same message, hence why it's placing them in the same ticket. It seems like you sent a mass CC message with the same message id, their responses will end up tracking through the same ticket.
