### ISSUE TITLE
Custom Form Does not appear for Email ticket even after saving with the Help Topic

### ISSUE THREAD

**Issue by jighem** [osTicket/osTicket#3611]
Using v1.10 (901e5ea)
1) When create new ticket Custom form shows in the Ticket Creation
![cf1](https://cloud.githubusercontent.com/assets/24699194/21884301/be450be8-d8d8-11e6-8613-e54a4821ba73.png)
![cf2](https://cloud.githubusercontent.com/assets/24699194/21884312/c66e53c4-d8d8-11e6-8478-cf6db142942f.png)
2) When Editing the Ticket Custom Form Does not appear in the screen even after saving the Ticket with the required Help Topic
![cf3](https://cloud.githubusercontent.com/assets/24699194/21884353/ee461d64-d8d8-11e6-8bab-1daca2b1a06e.png)

Please Have a look on the Custom Form Created!
![cf4](https://cloud.githubusercontent.com/assets/24699194/21884365/fe95ea96-d8d8-11e6-97b1-e10e000dac77.png)

Please suggest Remedy for the same!

**Comment by fdellwing** [comment]
Can not reproduce that.

Create
![ost9](https://cloud.githubusercontent.com/assets/22813377/21887220/56f0d940-d8bf-11e6-83c1-be554ee26062.png)

Edit
![ost10](https://cloud.githubusercontent.com/assets/22813377/21887222/56f42ffa-d8bf-11e6-9160-ead464c31016.png)

Form
![ost11](https://cloud.githubusercontent.com/assets/22813377/21887219/56f09066-d8bf-11e6-930c-6819031cd372.png)

Help Topic
![ost12](https://cloud.githubusercontent.com/assets/22813377/21887221/56f306a2-d8bf-11e6-8155-b29081757117.png)

**Comment by jighem** [comment]
Check with the ticket which are already generated newly created Email Tickets you wont be able to see the Custom Form fields in the edit

**Comment by fdellwing** [comment]
So..what is the problem exactly?

Is the form not visible on NEWLY created tickets? Or on tickets that are created before the form existed.

**Comment by jighem** [comment]
If you will see point no 2 screenshot, 
![cf3](https://cloud.githubusercontent.com/assets/24699194/21888468/68e4b358-d8ea-11e6-955a-9a75ae3d7ad6.png)

The above screenshot is of the ticket created via Email,
HelpTopic of the same is "Query" for which the Custom form is created. Field "Query" is not visible.

Whereas in the point No 1 check screen no 2 "Module" field is visible where in the point No 2 screen its not visible.
![cf2](https://cloud.githubusercontent.com/assets/24699194/21888430/45aede18-d8ea-11e6-8de6-c4226d1d3b48.png)

**Comment by fdellwing** [comment]
I can't help you like this..

What I did:
I created a new custom form and appended it to a help topic.
I created a ticket and the form was visible on this help topic.
I edited the same ticket and the form was visible.

The form is NOT visible:
If you edit a ticket that did not have the form since creation (e.g. a ticket created before the form existed, a ticket created with another help topic).

**Comment by jighem** [comment]
I agree to your point!
First of all thanks for the promt replies and concerns.
When Ticket is created from SCP by Agent, Custom forms are visible
When New tickets generated after creation of form via email (Email Fetch cron) custom forms are not visible even if the same help topic is assigned while creation of ticket
My Question is 
1) Custom form can be attached even after generation of Ticket? If yes then How?
2) If Ticket's Help Topic is changed after creation then Custom Form will work?

**Comment by ntozier** [comment]
Q: Custom form can be attached even after generation of Ticket? If yes then How?
A: Yes.  Go to the open ticket.  Click the Gear in the menu bar (manage), select "Manage Forms".  Add the form that you want to add.  Click save.  The form is now associated with the ticket.  Edit the ticket and populate the fields.

Q: If Ticket's Help Topic is changed after creation then Custom Form will work?
A: No.  Forms are added at ticket creation of manually.

**Comment by jighem** [comment]
Thanks @ntozier It worked, 
I also want the custom form details in export is it possible?
As when I Export the customform details are not getting displayed in the exported files.

**Comment by ntozier** [comment]
This is not currently a feature of osTicket.
There is another thread around here some where for people having export issues.  I would say that you probably want to close this since it is resolved, and add your support on the other thread saying that you would like it.  The more people give feedback for a given feature the more likely it is that it will get implemented.

Alternatively I see that form fields added to the Ticket Details form seem to export just fine.

**Comment by jighem** [comment]
No issues thanks @ntozier
