### ISSUE TITLE
Help！！What is the relationship between the orm and dynamic_forms？

### ISSUE THREAD

**Issue by KomaBeyond** [osTicket/osTicket#3613]
Well，i am trying to change the api code of create tickets, and at first i dont't know how it works, so i am follow ur step to catch ur idea.  But when i am run to the class.orm.php and class.dynamic_forms.php file, i know that is ur idea about this system, and i want to know, so i review the code again and again, but....i really can't. So i am asking now, could u show ur design map for me about this system and especially about the relationship between the ORM and Dynamic_forms ?

**Comment by ntozier** [comment]
ORM is Object-relational mapping.  It's an abstraction layer for talking to the database.

Dynamic forms is a feature that allows people to make their own forms, and have them change as things are done when opening a ticket.  

As far as your question regrading a design map, the answer would be no, I'm pretty sure that there isn't one.

**Comment by KomaBeyond** [comment]
OK, i know the ORM how it works but i don't know how the Dynamic forms works, could u explain it for me?
