### ISSUE TITLE
Account Registration & Account Confirmed page's doesn't use template in our language

### ISSUE THREAD

**Issue by ridd84** [osTicket/osTicket#3614]
### Prerequisites

I use fresh installation with 6 languages configured, I configured diferent email templates/pages

[Description of the bug or feature]

After user register submit, appears this page with this message

`Account Registration
Thanks for registering for an account.
We've just sent you an email to the address you entered. Please follow the link in the email to confirm your account and gain access to your tickets.`

Also, after check email and follow link appears new one

`Account Confirmed!
Thanks for registering for an account.
 You've confirmed your email address and successfully activated your account. You may proceed to open a new ticket or manage existing tickets.
Sincerely,
`

**Expected behavior:** [What you expected to happen]

Message page in current language, based on template language defined in (/scp/settings.php?t=users#templates)

**Actual behavior:** [What actually happened]

Message page allways in english

### Versions

 	v1.10 (901e5ea)

**Comment by ntozier** [comment]
My guess would be: Since the email is sent prior to the user logging in and selecting their language in their profile that it defaults to English.  Also as a side note: Language Packs for 1.10 haven't been released yet last I checked.

**Comment by gcasas84** [comment]
Hi, also I have the same problem with (Sign-In Page), I define template language in (scp / Settings / Users / Templates / Sign-InPage) but allways get english content.
