### ISSUE TITLE
поле "от" не отображается полное имя а только точки, подскажите как исправить (And column "from" doesn't display a full name)

### ISSUE THREAD

**Issue by dim09** [osTicket/osTicket#3618]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [ ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

**Comment by dim09** [comment]
версия 1.9.12

**Comment by ntozier** [comment]
It appears that you did not answer a single question or provide more than a single piece of information regarding your problem... You should probably try that again and answer the questions and fill out the description like the template above dictates or no one will ever look at this again except maybe to close it.

**Comment by dim09** [comment]
And column "from" doesn't display a full name

**Comment by rayfoss** [comment]
We still have no idea what you mean... could you try filling out the issue template to help us out

**Comment by dim09** [comment]
the problem was solved
