### ISSUE TITLE
Restrict ticket assignment to current user when Creating New Ticket

### ISSUE THREAD

**Issue by maibarra** [osTicket/osTicket#3619]
### Description

I can't limit ticket assignment to current user.

### Steps to Reproduce

1. Log into Agent-level user
2. Click on "New ticket" or "Create New Ticket"
3. See "Assign to" field.

![optionsassign](https://cloud.githubusercontent.com/assets/755379/22002212/3ca93654-dc07-11e6-9ead-8ea3316e74bb.png)

**Expected behavior:** I would like to populate the "Assign to:" dropdown field with **the current user as the ONLY option**.

**Actual behavior:** I can either give users permission to assign tickets or remove said permission.

### Versions

v1.9.12
OS: All OSes affected

**Comment by maibarra** [comment]
I would appreciate getting help on how to replace the following lines of code from the `ticket-open.inc.php` file:

```
<select id="assignId" name="assignId">
                    <option value="0" selected="selected">&mdash; <?php echo __('Select an Agent OR a Team');?> &mdash;</option>
                    <?php
                    if(($users=Staff::getAvailableStaffMembers())) {
                        echo '<OPTGROUP label="'.sprintf(__('Agents (%d)'), count($users)).'">';
                        foreach($users as $id => $name) {
                            $k="s$id";
                            echo sprintf('<option value="%s" %s>%s</option>',
                                        $k,(($info['assignId']==$k)?'selected="selected"':''),$name);
                        }
                        echo '</OPTGROUP>';
                    }
                    ?>
</select>&nbsp;<span class='error'>&nbsp;<?php echo $errors['assignId']; ?></span>
```

To limit or **hardcode** ticket assignment to the current user.

A help request was already posted on [S.O.](m/questions/41616639/osticket-limit-ticket-assignment-to-myself-only): 

Thank you

**Comment by fdellwing** [comment]
But this is not that the "assign to" function is for? The permission to assign tickets is there to transfer it to another agent. To assign yourself to a ticket you can just claim it.

**Comment by ntozier** [comment]
fdellwing is correct.  Tickets cannot and are not assigned to Users.

**Comment by maibarra** [comment]
I believe I misused the term "User", when I was referring to an agent. My apollogies. Issue is closed now.
