### ISSUE TITLE
Initial form field flags saved to database incorrectly when installing under PHP 7.

### ISSUE THREAD

**Issue by dellsala** [osTicket/osTicket#3620]
### Description

After a fresh installation, the client open ticket form appears to be missing fields. Under the admin panel, under Manage -> Forms, the visibility of all fields is listed as "Disabled". In the database, all `ost_form_field`.`flags` values are set to 0.

### Steps to Reproduce

1. Run a fresh install of OSTicket 1.10 under PHP 7.
2. Browse to client "Open Ticket" form.

**Expected behavior:** Expect to see a working open ticket form with contact fields.

**Actual behavior:** No contact fields appear in the form. The ticket fields do not appear after selecting a help topic. Form field visibilities are listed as "Disabled" in the form manager under the admin panel.

![screen shot 2017-01-17 at 8 48 25 am](https://cloud.githubusercontent.com/assets/977797/22023367/db73f436-dc93-11e6-9a57-1da8671ffc80.png)

### Versions

osTicket: v1.10 (901e5ea)
PHP: 7.0.8
OS: Ubuntu 16.04
MySQL: 5.7.16

**Comment by dellsala** [comment]
I'm pretty sure this is related to a change in string handling in PHP 7.

[Hexadecimal strings are no longer considered numeric](http://php.net/manual/en/migration70.incompatible.php#migration70.incompatible.strings.hex)

The initial field flags are entered as hex values in `form.yaml`. Under earlier PHP versions, I'm guessing those values got converted to INTs by the yaml parsing library. Under PHP 7, it appears they come in as strings. When MySQL tries to write a string of a hex number (ex: "0x777A3") to an INT column, it saves it as 0.

**Comment by rayfoss** [comment]
I can reproduce this... it also caused problems loging in with internet exploder 11. We should really catch this is testing.

See pull request https://github.com/osTicket/osTicket/pull/3621

-- Sent from my iPhone
