### ISSUE TITLE
Missed italian translation FAQ last update time

### ISSUE THREAD

**Issue by PeopleInside** [osTicket/osTicket#3622]
OsTicket 1.10 Last FAQ Update time is in English and is not translated to Italian language file.

**Comment by ntozier** [comment]
You're using the new language pack released on Jan 13?

**Comment by PeopleInside** [comment]
Don't know. I have to manually download? I will look if there are any update.

**Comment by ntozier** [comment]
The dates on the web page are not correct.  They were updated on Jan 13.

**Comment by yod527** [comment]
i'm using latest "ru.phar" from 13'th jan, but "Tasks" and some other new strings are not translated. Crowdin translation in 100% translated & approved by 3 Jan. What am I doing wrong?

**Comment by JediKev** [comment]
@SpySDD 

We try to re-build the language packs and plugins every time we release a new major version. The next build should be when `1.11.0` stable is released. Stay tuned!

Cheers.
