### ISSUE TITLE
Cannot disable Email Address 

### ISSUE THREAD

**Issue by blhf** [osTicket/osTicket#3627]
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch?
Yes
* [ ] Do you have any errors in the PHP error log, or javascript console?
No
* [x] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
Yes
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?
Yes

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

[Description of the bug or feature]

### Steps to Reproduce

Manage -> Forms -> Contact Information -> Email Address -> Config -> settings -> uncheck Enabled.

**Expected behavior:** able to uncheck 'Enabled' checkbox

**Actual behavior:** not able to uncheck 'Enabled' checkbox

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.
![image](https://cloud.githubusercontent.com/assets/10716429/22137932/059f7852-df19-11e6-937b-a5496e23ab92.png)

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.
![image](https://cloud.githubusercontent.com/assets/10716429/22137946/133e8de0-df19-11e6-8f22-e69072ff2125.png)

Using Chrome.

![image](https://cloud.githubusercontent.com/assets/10716429/22137955/1d3bf814-df19-11e6-92f9-50218cc480b8.png)

**Comment by fdellwing** [comment]
Why should this be disable-able? The email is important for osTicket and cannot be dismissed without rewriting whole lot of code.

**Comment by blhf** [comment]
We will deploy this as localhost users don't have a internet connection. --please view this link. http://osticket.com/forum/discussion/89581/do-not-require-email-address#latest

**Comment by fdellwing** [comment]
Good to know, but my answer is still true. I dont know all the code, but as I saw there is no way everything will work without an email. But maybe they provided a solution for that and just forget to let you disable that..

**Comment by ntozier** [comment]
Are you not using an admin account?
Because I have no issues disabling the field.  I think its a bad idea, but it's your install.

**Comment by blhf** [comment]
@notizier I'm using an admin account. Did you tweak or somehow change
something in the system?

**Comment by fdellwing** [comment]
I cannot disable it with admin account, too.

**Comment by projektion1** [comment]
is it possible to disable email or not under "Contact Information" form? In my version v1.14.3 (f4f5bc6) it is not possible for me! Or do I have to do a special setting?

**Comment by JediKev** [comment]
@projektion1 

Email addresses are the unique identifier for both Users and Agents, so it is required. You will have to modify the codebase in multiple places and make some changes in the database to accomplish this.

Cheers.
