### ISSUE TITLE
richTextEditor insert image error

### ISSUE THREAD

**Issue by alienflyer** [osTicket/osTicket#3629]
I'm running version of 1.8. When the richTextEditor is visible on the client side and you click the insert image button the popup displays, but I don't see the upload tab or the browse button as I do with the staff side. Everything on the staff side is working and I have it set to allow for uploads. 

I have also put the cgi_path fix into the php.ini file. Hoping someone can point me into a direction to debug as I'm running out of ideas from the poking around I've been doing. I've also noticed that the bullet points don't appear when selected (everything indents just no bullet)

**Comment by ntozier** [comment]
1.8 is ancient and no longer supported.  You should upgrade.

**Comment by alienflyer** [comment]
unfortunately we have already done a fair bit of customization to our build (some things that 1.9 did eventually end up adding) and currently dont have the time to migrate up. 

I get that its old my big hope is that someone can at least point me in a direction to debug.
