### ISSUE TITLE
Print / PDF Error

### ISSUE THREAD

**Issue by stephansdh** [osTicket/osTicket#3630]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch? - Not tried with the develop branch
* [ ] Do you have any errors in the PHP error log, or javascript console? No
* [ ] Did you check the [osTicket forums](http://osticket.com/forum/categories)? Yes
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported? Seen similar but not the same

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

I upgraded to V1.10 and the print ticket button on the client and staff side produced a error code 500.
(http://osticket.com/forum/discussion/89676/issue-encountered-after-upgrade-to-v1-10)

I then created a brand new install in a different folder and them same happened. 

### Steps to Reproduce

1.view ticket
2. hit print button top right

**Expected behavior:** produces a printable pdf page

**Actual behavior:** displays error code 500
### Versions

osTicket Version	v1.10 (901e5ea) —  Up to date
Web Server Software	Apache
MySQL Version	5.5.51
PHP Version	5.4.45
PHP Extensions
gdlib	 Used for image manipulation and PDF printing
imap	 Used for email fetching
xml	 XML API
xml-dom	 Used for HTML email processing
json	 Improves performance creating and processing JSON
mbstring	 Highly recommended for non western european language content
phar	 Highly recommended for plugins and language packs
intl	 Highly recommended for non western european language content
fileinfo	 Used to detect file types for uploads
APCu	 Improves overall performance
Zend Opcache	 Improves overall performance
PHP Settings
cgi.fix_pathinfo	 "1" is recommended if AJAX is not working
date.timezone	 America/Chicago
Database Information and Usage
Schema	ab8234_Tickets (localhost)
Schema Signature	98ad7d550c26ac44340350912296e673
Space Used	2.72 MiB
Space for Attachments	2.44 MiB
Timezone	CST (Interpreted as America/Chicago)

Installed Language Packs

English (United States) —
en_US — include/i18n/en_US

I have tried in chrome, safari and IE.
![screenshot 2017-01-22 16 50 11](https://cloud.githubusercontent.com/assets/25283062/22184071/e1d8a618-e0c2-11e6-94f5-2d6b0d70d772.png)
![screenshot 2017-01-22 16 52 33](https://cloud.githubusercontent.com/assets/25283062/22184095/45ec297c-e0c3-11e6-8638-a458897f107a.png)

**Comment by stephansdh** [comment]
Hold The Line,
Solved the problem, It wasn't necessarily a bug, it was my logo breaking it,
Reverting back to the stock images solved it.

**Comment by rockmanxp** [comment]
@stephansdh I'm experiencing the same issue and reverting to stock logos was not enough. I possibly missed something. Any advise? Thanks!

**Comment by stephansdh** [comment]
@rockmanxp Hmm, its been a while so i cant clearly remember!
However,
I seem to recall creating a fresh install and just leaving it as defaults and created a ticket and trying to print and slowly tried changing things till the image broke it.
Have you tried running from a fresh install?
