### ISSUE TITLE
Bug in class.thread.php!!!

### ISSUE THREAD

**Issue by KomaBeyond** [osTicket/osTicket#3631]
```
function getEntry($id) {
        return ThreadEntry::lookup($id, $this->getId());
}
```

this function should change like this:

```
function getEntry($id) {
        return ThreadEntry::lookup($id);
 }
```

otherwise when i call this function like this "$thread->getEntry($entry_id)"，there was an error occured.

**Comment by ntozier** [comment]
So you didn't make this a Pull Request because?

**Comment by KomaBeyond** [comment]
Should i?  I think it's too simple, there is no need to make a PR, if they saw this issue they can fixed it fast.

**Comment by fdellwing** [comment]
So you think it is faster for them to look at the file, find the function, fix it themselves as triggering the merge?

**Comment by KomaBeyond** [comment]
It should be change like this:
```
function getEntry($id) {
        $pk = static::getMeta('pk');
        $criteria = array($pk[0] => $id, 'thread_id' => $this->getId());

        return ThreadEntry::lookup($criteria);
}
```

or we can change the class "ThreadEntry" it's $meta "pk" config, like this:
```
'pk' => array('id', 'thread_id'),
```

So, which is the best ? I will make a PR!

**Comment by rayfoss** [comment]
@KomaBeyond When does this bug manifest? for instance when creating a task, editing a ticket, etc...

Having steps to reproduce the problem would really help... I'm not getting any errors with it under normal use.

**Comment by KomaBeyond** [comment]
@rayfoss Please see the first comment of mine in this issue.
