### ISSUE TITLE
Editor same problem as always.

### ISSUE THREAD

**Issue by gitfve** [osTicket/osTicket#3632]
Any change it will be fixed, as the back end is so bad. I use Firefox.

Maybe change the bad editor another modern one there are smooth and work.
https://www.froala.com/wysiwyg-editor

**Comment by ntozier** [comment]
This appears to be a duplicate issue report.
see https://github.com/osTicket/osTicket/issues/2373
Close this one.

**Comment by gitfve** [comment]
OK
