### ISSUE TITLE
Migration of OS ticket stopped both side fetching emails in osticket

### ISSUE THREAD

**Issue by jighem** [osTicket/osTicket#3633]
### Prerequisites

* [yes in my environment various deploys ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [No ] Do you have any errors in the PHP error log, or javascript console?
* [Yes ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [ yes] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

1. Install OSticket or restore old deploy backup on new server
2. Either Restore the backup of old OS ticket which was working or update old database details in ost-config

**Expected behavior:** It should work normally and fetch the emails from auto fetch cron as per old working

**Actual behavior:** It stopped fetching the emails and also dont show any errors in log

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.
![osticket](https://cloud.githubusercontent.com/assets/24699194/22322783/5eeba6ba-e3c4-11e6-942c-67f190e40bb6.png)
![osticket2](https://cloud.githubusercontent.com/assets/24699194/22322784/5ef03bc6-e3c4-11e6-9a38-c478d1d5aca5.png)

Shared Hosting Cpanel
Also have same deployment on windows other server same issues.

Please tell me what I should do atleast I want to start it again with the current tickets available in the database and user details alongwith agents
other setups will be done by myself

**Comment by ntozier** [comment]
Can you upgrade your PHP to 5.6 and see if that helps?

I seem to recall someone else having this same problem and they posted saying that they reverted to the pre 1.10 cron.php and it fixed their issue (this was during the RC releases though).  Either way that I don't see where you say that you setup cron to run cron.php after your migration.

**Comment by jighem** [comment]
did that but didn't turned out working for me

Please help this is my production environment, if this dont work then please tell me which all tables I would require to copy for all old threads attachments to be part of new deployment along with users, agents and organisation details

**Comment by pjdarch** [comment]
If you have the ability to create a Scheduled Task on your Windows server, you can do what I do to force the execution of cron.php.

1) Create a task in Task Scheduler to repeat every 5 minutes indefinitely, 

2) Start a Program with the following settings.:

> Note: Be sure to change the PHP and osTicket paths to your own as mine are just examples

**Program/script:** "C:\PHP\php-7.0.12-nts-Win32-VC14-x86\php.exe"
**Argument:** -f C:\inetpub\wwwroot\osTicket\api\cron.php
**Security Account:** LOCAL SERVICE

There's  additional information at http://osticket.com/wiki/POP3/IMAP_Setting_Guide
