### ISSUE TITLE
Fetch on auto-cron should work only if admin logged in

### ISSUE THREAD

**Issue by jighem** [osTicket/osTicket#3634]
Request to @protich please check possibility to "Fetch on auto-cron" should work only for Administrator users only
as if "Fetch on auto-cron" runs for each logged in user then the database stops responding and whole deployment go on toss for few mins till all or few of members logs off.

Please suggest which page needs to be changed to achieve this.

No doubt, Fetch on auto cron is the best option for people like me who dont know much about how to put cron jobs for fetching emails.

Thanks in advance.

**Comment by ntozier** [comment]
I seriously doubt that you are going to get any traction on this.  fetch on auto-cron is included as an absolute last resort.  You should be using cron or windows task scheduler and running cron.php. You can learn out how to setup a cronjob or windows task scheduler job in under 5 minutes via google.

**Comment by fdellwing** [comment]
You can very easily get the right syntax, even if you dont have a clue about cron, with services like http://crontab-generator.org/
