### ISSUE TITLE
Populate Company Name and Assigned To Columns

### ISSUE THREAD

**Issue by alfie013** [osTicket/osTicket#3636]
Hi Everyone,

Can you please help me on how to populate the two columns?

![q11](https://cloud.githubusercontent.com/assets/25225267/22393821/cdf21bca-e4c3-11e6-8df1-0a139ff72f16.png)

osTicket Version: v1.10 (901e5ea) 

Kindly take a look on my attached file. I added a coded on line 76-80 and edited the coded on line 477. 

[tickets.inc.php.txt](https://github.com/osTicket/osTicket/files/736668/tickets.inc.php.txt)

Thank you,
Alfie

**Comment by ntozier** [comment]
This is going to sound harsh.  

This is your code and you are responsible for your code.  GitHub is where we (the community) and the devs post upgrades for the product, fix bugs, file issue reports, etc.  Your code question really doesn't belong here.  It belongs on the forums if it belongs anywhere.

I would also point out that if you want to do this you could have simply grabbed the PR (Pull Request) for the Custom Queues feature which already exists here on github.

**Comment by fdellwing** [comment]
Department Name is easy, it gets already pulled with every query. Just echo $T[dept__name] for this. But what do you mean with Company Name?

**Comment by fdellwing** [comment]
Got it!

Its quite simple if you know what to do...but I never worked with classes in php in the past.

You can `User::lookupByEmail($T['user__default_email__address'])->getOrganization()->getName()` to get the organization name!

Via `User::lookupByEmail($T['user__default_email__address'])` you can also get all other infos of this user. This might come in handy..
