### ISSUE TITLE
Bug in emails.php IMAP Code

### ISSUE THREAD

**Issue by TomAshley303** [osTicket/osTicket#3637]
### Description

Attempting to add any email account credentials for IMAP or POP3 produces "IMAP doesn't exist. PHP must be compiled with IMAP enabled" even though IMAP is enabled in PHP and the web server has been restarted. IMAP support was compiled into PHP after OSTicket was installed.

phpinfo() reports the imap module loaded and under protocols reports: imap, imaps

### Steps to Reproduce

Attempt to add an email account with IMAP or POP3 login in OSTicket.

**Expected behavior:** [What you expected to happen]
For an account to be added.

**Actual behavior:** [What actually happened]

IMAP doesn't exist. PHP must be compiled with IMAP enabled

### Versions
v1.10 (901e5ea)

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.

imap	 Used for email fetching <--- shows hazard icon

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

Server is CentOS/CloudLinux 7, Litespeed Web Server (Drop in Apache replacement), and PHP5.6.22
Browser is Chromium 55.0.2883.87 Built on Ubuntu.

**Comment by fdellwing** [comment]
Well..its hard to say anything about that..

osTicket checks the php extensions each time you enter the information site. So, your imap extension has to be disabled in this context. Is your osTicket using the same version of php as you phpinfo()?

Please add a new php file to your osTicket with following code:
```php
<?php print extension_loaded('imap'); ?>
```
Open the site and look at the output. If it is not 1 (or true), the extension is not loaded. Than you have to take a look at your php settings.

**Comment by TomAshley303** [comment]
I'm on Litespeed Web Server. This ticket can be closed. When compiling PHP for Litespeed I was using the flags _'--with-imap=shared' '--with-imap-ssl' '--with-kerberos'_ and the first IMAP flag should be _''--with-imap'_
