### ISSUE TITLE
I upgraded and downgraded os ticket from v 1.9.14 to 1.10 , But I want to upgrade it again. I am getting errors.

### ISSUE THREAD

**Issue by shemeery4j** [osTicket/osTicket#3640]
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [x] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### I upgraded OS ticket from version 1.9.14 to 1.10 - Then I downgraded to previous version because of some reasons. Now I want to upgrade it to the latest version .

[Description of the bug or feature]

### Steps to Reproduce

1. Restore the database
2. Copy the folder upload and scripts
3. copy the upload folder from new versions
4. Run the upgrade

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.
![2a](https://cloud.githubusercontent.com/assets/25450988/22456424/c69cc164-e7ab-11e6-98d1-27983826fa05.JPG)

**Comment by fdellwing** [comment]
Literally no infos at all. Please close this.

**Comment by shemeery4j** [comment]
Please review it now. When I upgraded for first time , Some tables were added to mysql database. And I copied the old upload folder to my osticket folder. After it was working fine. But when I try to upgrade I am getting this error. Some times it shows 1054 DB error.

**Comment by fdellwing** [comment]
Please provide us with the system log.

**Comment by shemeery4j** [comment]
![a1](https://cloud.githubusercontent.com/assets/25450988/22457819/1d668a0a-e7b3-11e6-8d98-60f8b5c54665.png)
![a2](https://cloud.githubusercontent.com/assets/25450988/22457820/1d9dbe62-e7b3-11e6-829f-2058c2360b7d.png)


Sorry. We are not even getting a log report. I will downgrade it and I will try to get log report.

**Comment by fdellwing** [comment]
The errors should be on your server in the apache (php) errorlog ;)

**Comment by shemeery4j** [comment]
![a1](https://cloud.githubusercontent.com/assets/25450988/22457954/b681247a-e7b3-11e6-9057-00c48f2727ae.png)
![a2](https://cloud.githubusercontent.com/assets/25450988/22457955/b6a7b266-e7b3-11e6-8d99-08bbdfb8a965.png)

This is after downgrading.

**Comment by fdellwing** [comment]
Is that your production system or a dev system? Do you need the data what is in this ticket system?

I dont know, if there is any way to fix your problem without manually altering the database in a way that the upgrader will run.

**Comment by shemeery4j** [comment]
Its on a production environment. But we are testing it on a ubuntu virtual machine. How you can help us?

**Comment by fdellwing** [comment]
Well..you need to look at the conflicts that are happening during upgrade and solve them. This conflicts should be noted in you apache errorlog.

**Comment by shemeery4j** [comment]
[phperrorlog.txt](https://github.com/osTicket/osTicket/files/741667/phperrorlog.txt)

Here you have phperrorlog.

**Comment by fdellwing** [comment]
Can you trigger an upgrade and than give me only the errorlog from after you triggered the upgrade?

**Comment by shemeery4j** [comment]
sure

**Comment by shemeery4j** [comment]
[error.txt](https://github.com/osTicket/osTicket/files/741745/error.txt)

Please check.

**Comment by fdellwing** [comment]
Mh..

Dont seems like a DB problem, but this function is causing the problem.

```php
     /**
      * getDateFormat
      *
      * Retrieve the current date format for the system, as a string, and in
      * the intl (icu) format.
      *
      * Parameters:
      * $propogate - (boolean:default=false), if set and the configuration
       *      indicates default date and time formats (ie. not custom), then
      *      the intl date formatter will be queried to find the pattern used
      *      internally for the current locale settings.
      */
     function getDateFormat($propogate=false) {
          if ($this->get('date_formats') == 'custom')
              return $this->get('date_format');
          if ($propogate) {
              if (class_exists('IntlDateFormatter')) {
                  $formatter = new IntlDateFormatter(
                      Internationalization::getCurrentLocale(),
                      IntlDateFormatter::SHORT,
                      IntlDateFormatter::NONE,
                      $this->getTimezone(),
                      IntlDateFormatter::GREGORIAN
                  );
                  return $formatter->getPattern();
              }
              else {
                  // Use a standard
                  return 'y-M-d';
              }
          }
          return '';
      }
```

But this is the point there I cant help you, I'm not deep enough in the code for this. Maybe @rayfoss has an idea..

**Comment by shemeery4j** [comment]
waiting for @rayfoss

**Comment by shemeery4j** [comment]
There is a change in the format of time in previous and new version

**Comment by rayfoss** [comment]
Try running it with the `class_exists('IntlDateFormatter')` if block removed on `include/class.format.php`. There is a fallback that may work better... upgrading from your clean back up is probably the easiest option... you'll probably run into more issues.

**Comment by shemeery4j** [comment]
Can You make it clear. Unfortunately I font have a clean backup. I have the database which is already corrupted in this manner.

**Comment by shemeery4j** [comment]
[class.format.txt](https://github.com/osTicket/osTicket/files/743925/class.format.txt)

Is this the file you are talking about. I think the formats given are correct.

**Comment by shemeery4j** [comment]
Any help on this?

**Comment by shemeery4j** [comment]
![1](https://cloud.githubusercontent.com/assets/25450988/22539292/891846e6-e932-11e6-9724-15183004ed70.JPG)
![2](https://cloud.githubusercontent.com/assets/25450988/22539293/8943ccb2-e932-11e6-99ca-bf31165f9ffd.JPG)

**Comment by ntozier** [comment]
"I upgraded OS ticket from version 1.9.14 to 1.10 - Then I downgraded to previous version because of some reasons."

How did you downgrade?  Because if it wasn't "restore the DB and Files from a pre-upgrade backup.  Then you didn't downgrade.  I would suggest that you restore from before you upgraded initially.  If that is not an option the you have a hell of a mess.  http://osticket.com/commercial-support might be able to help.

**Comment by rayfoss** [comment]
We just wen't through something similar... what worked for us was to delete any table that created errors, restore from backup and then try again. ost_task, ost_help_form, ost_thread_*, ost_thread, ost_lock and a couple others were among the troublemakers.
