### ISSUE TITLE
Allow Agents to delete tickets

### ISSUE THREAD

**Issue by Mohsnb** [osTicket/osTicket#3642]
1.Please add to admin panel which can **delete some post** in tread and some **attached** in posts.
because users send duplicate post or large attachments .

2.Please add to users panel to can **close your threads**.
when limited users for example with 1 opened thread then user can close last thread and open new thread for new issue.

thank you

**Comment by fdellwing** [comment]
You can add 2. really easy yourself.

After `if(!defined('OSTCLIENTINC') || !$thisclient || !$ticket || !$ticket->checkUserAccess($thisclient)) die('Access Denied!'); ` add
```php
// if set, close the ticket
if(isset($_GET['action'])) {
        if(($_GET['action'] == 'close')) {
                if($thisclient->getId() == $ticket->getUserId() && $ticket->getStatus() != "Resolved" && $ticket->getStatus() != "Closed") { // only ticket owners can close the ticket (and only if not already closed)
                        $ticket->setStatus(3); // equivalent to status = closed
                        $ticket->setStaffId(8); // new user "SYSTEM"
                }
        }
        else {  
        echo "Not possible";
        }
}
```
You may need to add or edit the "if" to work with your statuses and language.

`$ticket->setStaffId(8);` this is optional but I use it, because otherwise the ticket will be shown "closed by the agent who was assigned". If you use it, be sure to set the correct ID of you "SYSTEM" user.

After this `<a class="action-button" href="tickets.php?a=edit&id=<?php
                     echo $ticket->getId(); ?>"><i class="icon-edit"></i> <?php echo __('Edit'); ?></a>` add
```php
<a class="action-button pull-right" href="tickets.php?id=<?php
echo $ticket->getId(); ?>&action=close">  <i class="icon-remove"></i> <?php echo __('Close'); ?></a>
```

Have fun!

**Comment by rayfoss** [comment]
Could you clarify #1? You can already give agents delete permission...

**Comment by MohsenBahraminejad** [comment]
![delattached](https://cloud.githubusercontent.com/assets/25475989/22565642/14c97c9e-e99e-11e6-90b2-dc4c341d635a.png)

**Comment by kgpanteon** [comment]
How to allow agent to change ticket status to delete mode in V1.10?

**Comment by ntozier** [comment]
There is no such thing as a "Delete" ticket status (unless you made one).  And then you would change ticket status just like you would for any other status (open, closed, etc).

From the open ticket list, tick the check box at the left of the ticket and click the Change Status (Flag upper right).  Or view the ticket and click the Change Status (Flag on the menu).  Or view the ticket and scroll all the way down to the bottom type a reply, select the delete status that you made, and click Post Reply.
