### ISSUE TITLE
Reply email is creating new tickets. Solutions?

### ISSUE THREAD

**Issue by tanejakaran** [osTicket/osTicket#3643]
I have (v1.9.14). When we do reply from email sometimes, it is coming in same ticket number. But sometimes, it is creating new tickets. 

Not sure what is the issue? But, what i did investigate, at that time cdata table was not available. either query are stopped in between or not sure why email is not replying in same tickets. No Error logs generated for this. But, I have lots of cdata issue which is not related to particular issue. 

### Steps to Reproduce

1. Sent email to customer 
2. When they respond then sometime new ticket or someticket get reply in same ticket. 

Every time, it should come in same ticket.  But, sometimes it does not come in same tickets. 

Any solutions please help me out?

**Comment by fdellwing** [comment]
I'm quite sure, I read about this problem in the past. But can't remember where and if solved.

**Comment by tanejakaran** [comment]
Can you provide me link? I have seen solution for 1.7.1 but i am using 1.9.4 and code pattern is not same.

**Comment by fdellwing** [comment]
As I said: Can't remember where..

**Comment by ntozier** [comment]
Have you added the ticket number to your (outgoing ticket email) subjects?

osTicket checks message-id first and tries to compare it to existing message-ids.  Then it checks the reference-id and in-reply-to. Lastly if all else fails it checks the message subject for the ticket [#number] to see if it matches an existing ticket.  If the email client that your customer is using doesn't preserve message-id's correctly etc then it is like that you will run into an issue like this.

**Comment by tanejakaran** [comment]
Have you added the ticket number to your (outgoing ticket email) subjects? - No. 

What is difference between message id and Ticket number?

**Comment by ntozier** [comment]
message-id is a email header from the RFC.
see: https://tools.ietf.org/html/rfc2822

ticket number is the ticket number in osTicket.

They have nothing to do with each other.

**Comment by JohnDelisle** [comment]
Same problem here - and it's not the mail client stripping message-id in my case, it's using Amazon SES that causes it.  

My local MTA relays to SES, and SES replaces message-id with whatever they like.   Email replies create new tickets.   I have [#123123] ticket numbers in the subjects, but that's not helping.

**Comment by mbaraq** [comment]
> Same problem here - and it's not the mail client stripping message-id in my case, it's using Amazon SES that causes it.
> 
> My local MTA relays to SES, and SES replaces message-id with whatever they like. Email replies create new tickets. I have [#123123] ticket numbers in the subjects, but that's not helping.

Am having the same issue. Were you able to figure out why osticket isn't looking at the subject for the ticket ID ?

**Comment by JohnDelisle** [comment]
I gave up and moved to MailGun.
