### ISSUE TITLE
Understanding the Table Structures and relationship

### ISSUE THREAD

**Issue by swenger7** [osTicket/osTicket#3644]
We are using this this system in our support department for tickets. We have a separate system for tickets that are converted to RMA which is built in Access. I am using the ODBC to link the tables from OS Tickets so that I can pull in information that is already documented on the tickets. However I keep running into issues with how the Relational Database was built with the Tables in OS Tickets. For example, I find that the table which lists the form field values rather than just having an identifying field which links to another table that would have the related records, the information is repeated on each line in brackets and quotes. For example it will display {"50":"Windows 7"} or {"49":"Windows 10"} each time instead of simply displaying 50 or 48 which would link to a master table that identifies what they are. I tried creating Queries to parse the info but this makes the results take much longer to populate and also for some odd reason in the Cdata table which is the temporary resident info on some records it will display both "50":"Windows 7" but on other records it will only display the number 50. So what I am really wondering is if there is some documentation which lists all the Tables and the Key fields and their relationships. Also if there is a way to get the data without the brackets and quotes.

Thanks
Sam

**Comment by Chefkeks** [comment]
Hey Sam, played around pretty much already with the database table structures and relationship while creating the osTicket ldap user info addon and recently a (yet unpublished) custom list entries updating MySQL procedure and even though this won't help you, I'd really appreciate some kind of visualization of the table structures and especially relationship too.

I'm pretty sure if I'd have enough time, I could visualize this on my own, but I'm definitely don't have enough time in the near as well as the far future, so I would really appreciate it too having a visualization!

Cheers,
Michael

**Comment by Chefkeks** [comment]
So read my comment as an extra long version of +1

**Comment by swenger7** [comment]
Thanks

**Comment by ntozier** [comment]
As a side note: "For example it will display {"50":"Windows 7"} or {"49":"Windows 10"} each time instead of simply displaying 50 or 48 which would link to a master table that identifies what they are."

If it didn't do this and Agent Smith deleted or changed 50 or 49 from the list. All the data on all your tickets with those entries would be wrong... ;)

**Comment by swenger7** [comment]
IMHO, when designing a database, I would have made that master field not allowed to be deleted so that this relationship will always be there. If you look at most accounting systems for example, once there is an entry on any master table item, that item can no longer be deleted for the exact reason that you mention.

**Comment by ntozier** [comment]
Thanks for the input.
