### ISSUE TITLE
SYSTEM user  not translated some case

### ISSUE THREAD

**Issue by Weibel73** [osTicket/osTicket#3645]
Hi

The 'SYSTEM' translated to hungarian 'RENDSZER'

When I claim ticket in Ticket thread shows: SYSTEM posted xxxxxxx Ticket unassigned.
"posted" and "ticket unassigned" words translated but SYSTEM is not.
When ticket owerdue the tread correctly tarnslated 'SYSTEM posted ....' >> 'RENDSZER írta .....' 

Its just a minor error but very annoying me :)
I hope it't clear

Best regards:
György Weibel

![sc](https://cloud.githubusercontent.com/assets/16578375/22527092/229e4ff0-e8ce-11e6-9a9f-c5e2de59641d.jpg)

**Comment by Weibel73** [comment]
Dear @rayfoss!
 Is possible correct way  to change in ticket.php 

example :

 -- $msg=sprintf(__('Ticket flagged as answered by %s'),$thisstaff->getName());  **change to**
++ $msg=sprintf(__('Ticket flagged as answered by %s'),__($thisstaff->getName()));

when user flagged nothing change but when the SYSTEM is translated to.....

**Comment by Chefkeks** [comment]
I guess I noticed "SYSTEM" somewhere in the file a few lines above or below today and thought "this looks like they forgot to make it translate-able", so it didn't look like "__('SYSTEM')", but then I received a phone call and must have forgotten it. So maybe you're right, but maybe there is just a SYSTEM somewhere missing __(' ') so it gets translated.

**Comment by Weibel73** [comment]
I Search 'SYSTEM' all the code  maybe class.task.php @884 ?

**Comment by Chefkeks** [comment]
I don't know anymore and can't look it up currently (answering from my phone and it's 10pm already here). So I'll have a look next week again, but basically your suggestion looks good too - if it's working and SYSTEM gets translated correctly, you should make another PR for it or add it as commit to your already existing PR.

**Comment by Weibel73** [comment]
Hi 

$msg=sprintf(('Ticket flagged as answered by %s'),__($thisstaff->getName())); 

With this method too many code rows affected.
I'm think  find a base problem we've also suggested missing __'' in class.task.php row `884



883     `$vars['staffId']` = 0;
884      $vars['poster'] = 'SYSTEM';                   >>             __('SYSTEM')
885        if ($poster && is_object($poster)) {
886            $vars['staffId'] = $poster->getId();
887            $vars['poster'] = $poster->getName();
888        } elseif ($poster) { //string
889            $vars['poster'] = $poster;
890        }`

I try it and it looks like working :)))

George

**Comment by Weibel73** [comment]
@Chefkeks 
So is not easy :) latest post is wrong way. I think its a deeper problem in code if you online disccuss it.
I thikn basicly wrong some part of code what relatod to translating.

George
