### ISSUE TITLE
SLA not set on staff ticket creation

### ISSUE THREAD

**Issue by jamesangi** [osTicket/osTicket#3648]
If an agent creates a new ticket on the staff page the SLA is not set based on the help topic or department.  If an end-user creates a new ticket the SLA setting is correct.

Is this the expected behavior?

**Comment by ntozier** [comment]
Yes.  Agents have higher control and can over ride things.

**Comment by jamesangi** [comment]
I like that they can override things, but it would be nice if the "default" followed the help topic/department instead of always choosing the default SLA plan.

**Comment by amatosg** [comment]
Although it's ok for agents to override the SLA, it should follow the designated one for the topic/department so metrics won't be affected. Just a thought.

**Comment by balojs** [comment]
@rayfoss same problema

**Comment by JediKev** [comment]
I have submitted a pull request (#3915) that should resolve this issue. Please make the changes, test, and get back to me.
