### ISSUE TITLE
Email Addresses With Subdomains - Authorized Users Only Error

### ISSUE THREAD

**Issue by jakobii** [osTicket/osTicket#3649]
### Prerequisites

1. * [x] Can you reproduce the problem in a fresh installation of the "develop" branch?
2. * [ ] Do you have any errors in the PHP error log, or javascript console?
3. * [x] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
4. * [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. Disable the contact info email validation in admin\manage\form\contact info\email (this is because the email validation does not like the extra period after the '@' symbol.)
2. attempt to create a ticket (logged in as an agent or just as a standard user)
3. In the email address field, use a email address with a subdomain. 
4. _you can use mine if you want_ example: 99999@students.mhusd.org <this email address is valid and I'm using it for testing>

**Expected behavior:** [What you expected to happen]
creates the ticket

**Actual behavior:** [What actually happened]
does not create ticket. 
error: This help desk is for use by authorized users only

![selection_003](https://cloud.githubusercontent.com/assets/19825478/22568101/5a1cdaae-e947-11e6-99d0-71756ea97f35.png)

### Versions

osTicket Version	v1.10 (901e5ea) —  Up to date
Web Server Software	Apache/2.4.18 (Ubuntu)
MySQL Version	5.7.17
PHP Version	7.0.8-0ubuntu0.16.04.3

and 

osTicket Version	v1.10-8-g4e49086 (4e49086) —  Up to date
Web Server Software	Apache/2.4.18 (Ubuntu)
MySQL Version	5.7.17
PHP Version	7.0.13-0ubuntu0.16.04.1

**Comment by fdellwing** [comment]
That's a problem we had with a software we distribute aswell. That is probaly because the mail gets checked for validaty via regex.

**Comment by ntozier** [comment]
Which you should be able to shut off at:
Admin panel -> Manage -> Forms -> Contact Information ->  Email Address -> Config -> Validator: None

**Comment by jakobii** [comment]
@ntozier  I only get the error below after I turn on the validator, found at: Admin panel -> Manage -> Forms -> Contact Information -> Email Address -> Config -> Validator: None

![](https://cloud.githubusercontent.com/assets/19825478/22568101/5a1cdaae-e947-11e6-99d0-71756ea97f35.png)

if i try to create a ticket with the validator on, it just tells me the email is invalid, and does not let me create the ticket.

**Comment by ntozier** [comment]
Which would be why I told you to shut it off?

**Comment by jakobii** [comment]
@ntozier sorry if im explaining this badly. it is off. 

If its not off, i just get a standard email invalid error. but since **it is off**, i get the error mentioned previously.
![selection_003](https://cloud.githubusercontent.com/assets/19825478/22599629/6d292148-e9ec-11e6-9d12-d750a52d5077.png)

**Comment by jakobii** [comment]
It appears we we had a conflicting ticket filter, the filter was denying the subdomain. its good to know that those deny rules stop ticket creation so quickly, and now I know what that error message means. Sorry about this confusion! after disabling the filter and disabling the email validator it all working.
