### ISSUE TITLE
ticket time is showing wrong

### ISSUE THREAD

**Issue by lijothelegend** [osTicket/osTicket#3654]
Ticket time is showing wrong . I have checked in my server time and my sql server time is correct there.

![os info](https://cloud.githubusercontent.com/assets/22472451/22619818/eae33d12-eb22-11e6-811b-a77fccd75172.JPG)
![os ticket my sql time](https://cloud.githubusercontent.com/assets/22472451/22619819/eae41f7a-eb22-11e6-8eef-7a941972a68d.JPG)
![os ticket](https://cloud.githubusercontent.com/assets/22472451/22619821/eae54a9e-eb22-11e6-9939-7f9337524f64.JPG)
![os timezone](https://cloud.githubusercontent.com/assets/22472451/22619820/eae4e770-eb22-11e6-9dfa-c5bb404a9b56.JPG)
![osdate](https://cloud.githubusercontent.com/assets/22472451/22619822/eae7f5a0-eb22-11e6-8c92-bbf8b2bba111.JPG)

Ticket time is showing wrong . I have checked in my server time and my sql server time is correct there.

**Comment by iHunt101** [comment]
Try to check your php.ini conf and set your time zone..

**Comment by lijothelegend** [comment]
time zone in my php.ini is correct 



Thanks&Regards
Lijo Joseph George
Technical Team|| ManoramaOnline
Mobile: +91 9895336448 | Office : +91 0481 2563646 | Ext :670
Visit us:www.manoramaonline.com | LinkedIn | Facebook | Twitter

**Comment by fdellwing** [comment]
If the time is wrong as you state, what should the time be? By how much is it off?

**Comment by lijothelegend** [comment]
Seem that its showing time of  Timezone IST (Interpreted as 
Asia/Jerusalem) not of Asia/Kolkata  I need the time of Asia/Kolkata for 
the tickets.

Thanks&Regards
Lijo Joseph George
Technical Team|| ManoramaOnline
Mobile: +91 9895336448 | Office : +91 0481 2563646 | Ext :670
Visit us:www.manoramaonline.com | LinkedIn | Facebook | Twitter

**Comment by fdellwing** [comment]
Well, this is already know: #3583

**Comment by fdellwing** [comment]
Looked into it and are completely confused...

So in the ost_config is correct 'Asia/Kolkata' (+530), in `class.format.php` `function datetime` $cfg->getTimezone() is 'Asia/Kolkata' (+530) but 2 seconds later after passing it to `IntlDateFormatter` we are in 'Asia/Jerusalem' (+430). How??

**Comment by rayfoss** [comment]
@fdellwing We've ran into this issue on multiple occasions do you have any more details to put in a fix?

**Comment by fdellwing** [comment]
Not yet, have to take a closer look at the `IntlDateFormatter`, if there are any workarounds.

**Comment by rayfoss** [comment]
From #3583 
```
dbinoj commented on Dec 31, 2016
The timezone returned by timezone_name_from_abbr can not be trusted as it just selects the first result sorting the tz name alphabetically. This messes up times displayed in the site even though timezone in OSTicket System Settings, OSTicket User Prefs, php.ini, MySQL, Server OS are all set to the same value.

Eg. IST refers to Israel/Indian/Irish Standard Times (Ref: List_of_time_zone_abbreviations)
One may intend to use Indian/Irish timezone but "Asia/Jerusalem" comes first alphabetically.
Few other TZs which I found to have duplicates are ACT, AMT, BST, etc.,

Either function get_from_database in class.timezone.php:165 should be modified to translate ambiguous timezones with some other reference value or a better method must be implemented.

Related StackOverflow answer: http://stackoverflow.com/a/30958892
```

It seems like the interpretation can change for strange reasons. CST db_timezone was being interpreted as UTC in a test install... I restarted the server twice and had the same issue. To debug it I started installing php-devel, php-xdebug and restarting the webserver... but then the problem disappeared and CST correctly resolved to America/Chicago. 0_0

**Comment by fdellwing** [comment]
CST will never be interpreted as UTC by `timezone_name_from_abbr`. You must have run in another problem. Did you manually queried your DB for `@@system_time_zone`? The old version (without my PR) just queries the DB for this.

**Comment by deependhulla** [comment]
To remove timezone issue with osticket  DB timezone as : IST (Interpreted as Asia/Jerusalem) 
http://osticket.com/forum/discussion/89257/v1-10-timezone-misinterpreted
https://github.com/osTicket/osTicket/issues/3654
https://github.com/osTicket/osTicket/issues/3583

we have done quick fix ain include/class.config.php

Search for  line having 
`function getDbTimezone() `

in this function you would  last line as   
 `  return $this->get('db_timezone');`
Comment this line , and add below two line
`$dvd_db_timezone='Asia/Kolkata';
return $dvd_db_timezone;
`

The function would like below.
 ` function getDbTimezone() {
        if (!$this->exists('db_timezone')) {
            require_once INCLUDE_DIR . 'class.timezone.php';
            $this->persist('db_timezone', DbTimezone::determine());
        }
$dvd_db_timezone='Asia/Kolkata';
return $dvd_db_timezone;
//        return $this->get('db_timezone');

    }

`

This will help a lot till proper code fix is there.

**Comment by lijothelegend** [comment]
Thanks all,
It has been fixed

**Comment by fdellwing** [comment]
@deependhulla I hope you don't want to promote that as a valid solution. If you want a proper solution, take a look at my PR #3663

**Comment by deependhulla** [comment]
@fdellwing my suggestion is for quick fix, so that work get started specially who are looking forward to implement osticket and have got all correct but basic timezone feature is creating problem to start off using and exploring octicket's features and power..

Actually   would prefer original core osticket fix this timezone issue asap.
and/or give option for also selecting time-zone for database too.

overall I love osticket.
thanks to octicket team too for such a wonderful product.

**Comment by elambro** [comment]
For Googlers, if your database time is set to GMT, OSTicket reads this as 'Europe/London' instead of UTC. Your times will then be 1 hour off during DST. To fix this, change `includes/class.config.php`.  Change the method `OsticketConfig::getDbTimezone` to this: 

```
function getDbTimezone() {
        if (!$this->exists('db_timezone')) {
            require_once INCLUDE_DIR . 'class.timezone.php';
            $this->persist('db_timezone', DbTimezone::determine());
        }
        $db = $this->get('db_timezone');
        if ( $db === 'Europe/London') {
            $db = 'UTC';
        }
        return $db;
    }
```

**Comment by thiru506** [comment]
@deependhulla ...Thank you very much....your given a proper solution..!!!

**Comment by mxyq** [comment]
耐你们

**Comment by antiuser** [comment]
Yes, this patch good, but this is hardcoded function. Im using Asia/Yekaterinburg (GMT +5.00) but in osticket i see in tickets date as GMT +4.00.
@deependhulla thank you

**Comment by kanthans** [comment]
> To remove timezone issue with osticket DB timezone as : IST (Interpreted as Asia/Jerusalem)
> http://osticket.com/forum/discussion/89257/v1-10-timezone-misinterpreted
> #3654
> #3583
> 
> we have done quick fix ain include/class.config.php
> 
> Search for line having
> `function getDbTimezone() `
> 
> in this function you would last line as
> ` return $this->get('db_timezone');`
> Comment this line , and add below two line
> `$dvd_db_timezone='Asia/Kolkata'; return $dvd_db_timezone;`
> 
> The function would like below.
> ` function getDbTimezone() { if (!$this->exists('db_timezone')) { require_once INCLUDE_DIR . 'class.timezone.php'; $this->persist('db_timezone', DbTimezone::determine()); } $dvd_db_timezone='Asia/Kolkata'; return $dvd_db_timezone; // return $this->get('db_timezone'); }`
> 
> This will help a lot till proper code fix is there.

Hi
We were facing the same issue and had applied the above patch in 1.10.5. This has been working well. 

However we recently upgraded to 1.12.2 and all our ticket times were weird again, this time it was advancing by 2 hours 30 mins (as if the timezone is +8 instead of +5.30). We just applied the same patch and seems to be working well. 

Is the bug still getting carried from 1.10. to 1.12?

**Comment by deependhulla** [comment]
> > To remove timezone issue with osticket DB timezone as : IST (Interpreted as Asia/Jerusalem)
> > http://osticket.com/forum/discussion/89257/v1-10-timezone-misinterpreted
> > #3654
> > #3583
> > we have done quick fix ain include/class.config.php
> > Search for line having
> > `function getDbTimezone() `
> > in this function you would last line as
> > ` return $this->get('db_timezone');`
> > Comment this line , and add below two line
> > `$dvd_db_timezone='Asia/Kolkata'; return $dvd_db_timezone;`
> > The function would like below.
> > ` function getDbTimezone() { if (!$this->exists('db_timezone')) { require_once INCLUDE_DIR . 'class.timezone.php'; $this->persist('db_timezone', DbTimezone::determine()); } $dvd_db_timezone='Asia/Kolkata'; return $dvd_db_timezone; // return $this->get('db_timezone'); }`
> > This will help a lot till proper code fix is there.
> 
> Hi
> We were facing the same issue and had applied the above patch in 1.10.5. This has been working well.
> 
> However we recently upgraded to 1.12.2 and all our ticket times were weird again, this time it was advancing by 2 hours 30 mins (as if the timezone is +8 instead of +5.30). We just applied the same patch and seems to be working well.
> 
> Is the bug still getting carried from 1.10. to 1.12?

not aware of 1.12 .. but this fix worked for us on  osTicket (v1.14.2) again.

**Comment by perezalvarezhi** [comment]
I tried both solutions and I might be wrong but I think none worked for me. Also I just updated to 1.14.2 but I dont think there was a fix for this on this version.

Before this fix I saw MST (Interpreted as America/Denver) with 1 hour less than my time.

After doing the solution user @deependhulla proposed above I at least can see my real timezone selected in the Timezone section which is America / Mexico_City but now my time is off by 2 hrs. 

Even if I try other time zones more advanced in time for example "America/New_York" which is 2 hours ahead and could compensate my 2 hrs it ends up 4 hrs before not ahead.

Also I checked my server time and it is in MST with the correct time. I checked this by doing the command "date" on the terminal.

Anyone still having this problem? I understend the problem is closed but I cant fix it.

**Comment by JediKev** [comment]
@perezalvarezhi 

What is your System Timezone set to (**Admin Panel > Settings > System > Date and Time Options > Default Timezone**)? Is it `America / Mexico_City`?

Also, what is your Profile Timezone set to (**Profile > Preferences > Localization > Timezone**)?

Cheers.

**Comment by perezalvarezhi** [comment]
> 
> 
> @perezalvarezhi
> 
> What is your System Timezone set to (**Admin Panel > Settings > System > Date and Time Options > Default Timezone**)? Is it `America / Mexico_City`?
> 
> Also, what is your Profile Timezone set to (**Profile > Preferences > Localization > Timezone**)?
> 
> Cheers.

Hey there @JediKev  I think while reading your questions you helped me figure it out. 
I had to enter the default time zone as the same as my server which is in Pacific (Before I stated it is on MST but it is not, it is on Pacific) and then my agent profile in the time zone it is located.

I selected in Admin Panel > Settings > System > Date and Time Options > Default Timezone "America/Los_Angeles" and then in my profiles I had America/Mexico_City.

This way it worked fine.

Thanks!

**Comment by JediKev** [comment]
@perezalvarezhi 

Awesome! I'm glad you got this resolved!

Cheers.

**Comment by feiticeir0** [comment]
Hi all ! 
I know this is 2020, but this issue still remains... Had to edit the file `class.config.php`  and return my timezone for this to work... Thank you
EDIT: Sorry, Latest threads are already 2020 . I'm using the latest version 1.14.3

**Comment by antiuser** [comment]
@JediKev another one with this bug

**Comment by JediKev** [comment]
@antiuser 

Cool.. you never responded to my message in your issue thread. #5522 

Cheers.

**Comment by antiuser** [comment]
@JediKev this bug found on 1.12.2 version, and i told about this in issue information (up to 1.12.6), this issue comes from old time, and no reaction. Im assume that ticket should be reopened

**Comment by Stufo76** [comment]
> > To remove timezone issue with osticket DB timezone as : IST (Interpreted as Asia/Jerusalem)
> > http://osticket.com/forum/discussion/89257/v1-10-timezone-misinterpreted
> > #3654
> > #3583
> > we have done quick fix ain include/class.config.php
> > Search for line having
> > `function getDbTimezone() `
> > in this function you would last line as
> > ` return $this->get('db_timezone');`
> > Comment this line , and add below two line
> > `$dvd_db_timezone='Asia/Kolkata'; return $dvd_db_timezone;`
> > The function would like below.
> > ` function getDbTimezone() { if (!$this->exists('db_timezone')) { require_once INCLUDE_DIR . 'class.timezone.php'; $this->persist('db_timezone', DbTimezone::determine()); } $dvd_db_timezone='Asia/Kolkata'; return $dvd_db_timezone; // return $this->get('db_timezone'); }`
> > This will help a lot till proper code fix is there.
> 
> Hi We were facing the same issue and had applied the above patch in 1.10.5. This has been working well.
> 
> However we recently upgraded to 1.12.2 and all our ticket times were weird again, this time it was advancing by 2 hours 30 mins (as if the timezone is +8 instead of +5.30). We just applied the same patch and seems to be working well.
> 
> Is the bug still getting carried from 1.10. to 1.12?

found again v1.15.7 (26ab7e9) and quick fixed as above, but i think it should be permanently fixed

**Comment by mixneko** [comment]
Dear All
Asia/Taipei also can't be right timezone
it will show "America/Chicago"
for now I follow this code
`we have done quick fix ain include/class.config.php
Search for line having
function getDbTimezone()
in this function you would last line as
return $this->get('db_timezone');
Comment this line , and add below two line
$dvd_db_timezone='Asia/Taipei'; return $dvd_db_timezone;
The function would like below.
function getDbTimezone() { if (!$this->exists('db_timezone')) { require_once INCLUDE_DIR . 'class.timezone.php'; $this->persist('db_timezone', DbTimezone::determine()); } $dvd_db_timezone='Asia/Taipei'; return $dvd_db_timezone; // return $this->get('db_timezone'); }
`
please help to fix it
thank you
