### ISSUE TITLE
Tickets disappeared from Agent dashboard 

### ISSUE THREAD

**Issue by eatallah** [osTicket/osTicket#3655]
I have single Admin and Multi Agents for multi sites, each agent have team members related to his\her site, 
Agents can’t see or trace tickets if they assign it to other Agents or team member? It will be disappeared from their tickets dashboard totally,
Can anyone help me please, I’m using v1.10-rc.3 (907ec36)

Thanks you in advance,

**Comment by iHunt101** [comment]
Did you try to use the v1.10 stable?

**Comment by eatallah** [comment]
Thanks, I'll check but before that, do you think that my problem is due to bug or problem on the current release or from our configuration side? 
Thanks again

**Comment by iHunt101** [comment]
Last time i check, even the v1.9.14 it works fine. Have a look of the vew version, it fix some bugs..

**Comment by eatallah** [comment]
Thanks a lot iHunt101,
problem was solved by removing (limit ticket access to only assigned tickets),
Thanks again

![image](https://cloud.githubusercontent.com/assets/16880472/22695351/8ed2e410-ed5b-11e6-808f-a471a29d4925.png)
