### ISSUE TITLE
Subject Summary Input in Form

### ISSUE THREAD

**Issue by iHunt101** [osTicket/osTicket#3656]
I recently use v1.9.14 stable and now i try to adopt the new version. But when i try to add additional input fields in ticket details, the input field in not set as class="form-control". The new version is set the form like this
v1.9.14
`<input type="text" id="_6a4f38aa4c035d5a" size="40" maxlength="40" placeholder="" name="6a4f38aa4c035d5a" value="" class="form-control"/>`

![1 9 14](https://cloud.githubusercontent.com/assets/16589622/22634036/30ade66e-ec61-11e6-98be-9e47f05db6ff.JPG)

v1.10
`<input type="text" id="_81af557b258a325a" size="40" maxlength="50" placeholder="" name="81af557b258a325a" value=""/>`

![1 10](https://cloud.githubusercontent.com/assets/16589622/22634037/30e2cf8c-ec61-11e6-89ea-c74dae4fd5cf.JPG)

I am using Google Chrome Version 53.0.2785.101 (64-bit), Firebug 1.4.0 Lite and Windows 64 OS.

**Comment by fdellwing** [comment]
And this is a problem, because?

**Comment by rayfoss** [comment]
I don't see any harm in putting it back if you need it for styling... pull req it?

**Comment by iHunt101** [comment]
Yes please.. @rayfoss

**Comment by iHunt101** [comment]
How can i manulally do this while waiting for new fix?
