### ISSUE TITLE
Cannot confirm email address on forum

### ISSUE THREAD

**Issue by terrytibbles** [osTicket/osTicket#3657]
Hello,

It's not possible for me to post on the osTicket forum, as I click the button to re-send the confirmation email, and never get the confirmation email. Is it possible to rectify this?

Thanks.

Terry

**Comment by iHunt101** [comment]
Hi,
Have you login your account using this email?

**Comment by terrytibbles** [comment]
Hello,

Yes, I have used the same email address on GitHub and the forum.

Terry

**Comment by Chefkeks** [comment]
I'm sure forum moderator @ntozier can help ;)

**Comment by rayfoss** [comment]
give it 24 hours... unless he's sick. Confirmation is a manual process.

**Comment by ntozier** [comment]
Please email me with your email account that you used to sign up and I will take a look.
neil at osticket dot com.

**Comment by terrytibbles** [comment]
Hello,


This is the email address I signed up with.


Regards,


Tom

________________________________

**Comment by ntozier** [comment]
I cannot see your email address on github.

**Comment by terrytibbles** [comment]
The email address is: tom_jay@hotmail.com.


________________________________

**Comment by ntozier** [comment]
I have added the registered users role to your forum account.
If you have further issues please email me at neil at osticket dot com.
