### ISSUE TITLE
	This action requires a lock. Please try again 

### ISSUE THREAD

**Issue by iHunt101** [osTicket/osTicket#3658]
![lock](https://cloud.githubusercontent.com/assets/16589622/22636771/87f987a4-ec78-11e6-8bdc-ffa06a039f0b.JPG)

I was trying the new version, v1.10 but i get this old issue? i checked the code and compare to your soulution from issue #2371 and the updated version apply this fix. How could this happen?

**Comment by rayfoss** [comment]
#2371 is very specific to internal notes... maybe you meant to refer to another issue? otherwise... we'll need more info...

**Comment by iHunt101** [comment]
Sorry for that. It not about internal note. I wwas trying to post a comment but i got this error.

**Comment by rayfoss** [comment]
is your computer time different from your installation time? when you create a new ticket does it display the time correctly?

**Comment by iHunt101** [comment]
Yes the time was exactly the same..

**Comment by zalbador20** [comment]
Hi. 
I had the same issue, I read this out and worked for me.

http://osticket.com/forum/discussion/91557/resolved-unable-to-answer-to-tickets-this-action-requires-a-lock-please-try-again
