### ISSUE TITLE
just installed osTicket (v1.10-45-g11663e3)... and while I can see my tickets, there is nothing on the page

### ISSUE THREAD

**Issue by mrabino1** [osTicket/osTicket#3659]
Having updated 30+ times prior (via git pull.. and then  php setup/cli/manage.php deploy -v /var/www/tickets/   ) without any issues (on an ubuntu server)..  I just installed (v1.10-45-g11663e3)... and when I went to login to my console.. everything looked normal... when I selected a ticket, the header body footer rendered (so not an PHP error issue.eg whitescreen of death).. but the actual ticket content itself was blank... 

![2017-02-06_20-48-36](https://cloud.githubusercontent.com/assets/4902221/22663659/b7b90bba-ecad-11e6-9974-866a870355b5.png)

**Comment by mrabino1** [comment]
About this osTicket Installation

Server Information
osTicket Version	v1.10-45-g11663e3 (11663e3) —  Up to date
Web Server Software	Apache/2.4.7 (Ubuntu)
MySQL Version	5.5.54
PHP Version	5.5.9-1ubuntu4.20

**Comment by ntozier** [comment]
This also looks like you have a PHP error please check your logs.

**Comment by mrabino1** [comment]
[Mon Feb 06 23:34:34.652119 2017] [:error] [pid 1419] PHP Parse error:  syntax error, unexpected ';' in /var/www/tickets/include/staff/ticket-view.inc.php on line 871

**Comment by mrabino1** [comment]
here is line 871 of that file 
        <?php echo sprintf(__('Are you sure you want to <b>claim</b> (self assign) %s?'), __('this ticket');?>

(no modification from me)

**Comment by mrabino1** [comment]
When replaced with its predecessor code
` <?php echo __('Are you sure you want to <b>claim</b> (self assign) this ticket?');?>`

page renders fine... so.....syntax on
`<?php echo sprintf(__('Are you sure you want to <b>claim</b> (self assign) %s?'), __('this ticket');?>
 `  
must be off

**Comment by tomlaf** [comment]
The error is a parenteses missing at the end of line 871

The line should be  :
<?php echo sprintf(__('Are you sure you want to <b>claim</b> (self assign) %s?'), __('this ticket'));?>

I will try to submit a commit and a merge request, but these will be my 1st here so it may take time ;-)

**Comment by tomlaf** [comment]
Ok I did a pull request to develop for this under #3660.

**Comment by rayfoss** [comment]
The fix is in the latest. You may want to update your php to 5.6, 5.5 is end of life and won't get security updates... not sure if Ubuntu has any commitment to keep it patched beyond that.
