### ISSUE TITLE
Advanced search box return ajax problem

### ISSUE THREAD

**Issue by internet-conception** [osTicket/osTicket#3664]
When I try to make an advanced search the popup open properly.
I can adjust my setting (simply display tickets from one agent)
Then the ajax return dont work...

It work on my test server but not on the production server :(

I've made a small video of the behavior : https://youtu.be/pLPUhF9mT6w

And some screenshot about my config and the firefox console result.
![capture d ecran 2017-02-07 a 12 17 28](https://cloud.githubusercontent.com/assets/2952654/22690142/91b38864-ed34-11e6-9543-82f9a0a579fc.png)
![capture d ecran 2017-02-07 a 12 28 07](https://cloud.githubusercontent.com/assets/2952654/22690143/91c64a62-ed34-11e6-9461-a9ae9d2e8a26.jpg)

**Comment by internet-conception** [comment]
Finally I found that the php version was not good :( 5.6.21
I change php to phpcgi and now it work... But there is definitly a bug in the code...

**Comment by rayfoss** [comment]
Most of us are using the PHP module, and I can't reproduce the issue... seems like a configuration issue in the php.ini being used for the php module perhaps? we need more info...
