### ISSUE TITLE
Duedates did not sync

### ISSUE THREAD

**Issue by iHunt101** [osTicket/osTicket#3666]
### Description

Ticket information and ticket details due date did not sync. I mage a due date input for my client to monitor our services. But i was confuse about another dua date in Ticket information. It never sync to Ticket information due date.

**Expected behavior:** Both due dates will sync if you edit one of them.

**Actual behavior:** If i set a due date in ticket information, the duedate of ticket details never change.

### Versions
v1.10 (901e5ea)
Windows 64 OS
php 5.6
Chrome Version 53.0.2785.101 (64-bit)

![duedate](https://cloud.githubusercontent.com/assets/16589622/22725642/a79a2162-ee09-11e6-9eff-07653e1dd384.JPG)

![duedate2](https://cloud.githubusercontent.com/assets/16589622/22725713/16c80e82-ee0a-11e6-8476-00d51f7c1962.JPG)
![duedate3](https://cloud.githubusercontent.com/assets/16589622/22725712/169a22ba-ee0a-11e6-8f7e-0b2f271af0ea.JPG)

**Comment by ntozier** [comment]
It appears that you added a custom Due Date field...
Why would Variable1 update and change VariableA?
One is built in and part of the system, the other is something that someone added to a custom form.
