### ISSUE TITLE
Ticket CSV export is broken on 1.10

### ISSUE THREAD

**Issue by yod527** [osTicket/osTicket#3667]
### Description

While producing csv export of tickets, no matter where only 2 first are exported.

### Steps to Reproduce

1. Agent panel -> tickets -> open
2. Select All
3. Only 2 first tickets are exported!

**Expected behavior:**All tickets exported to csv.

**Actual behavior:** Only 2 tickets exported.

### Versions

osTicket Version	v1.10 (901e5ea) —  Up to date
Web Server Software	Apache/2.4.18 (Ubuntu)
MySQL Version	5.7.16
PHP Version	7.0.8-0ubuntu0.16.04.3

**Comment by fdellwing** [comment]
Can not confirm this. Please check for PHP Errors in your errorlog.

**Comment by yod527** [comment]
No errors, but warnings:
[Wed Feb 08 12:34:33.371643 2017] [:error] [pid 5861] [client 192.168.100.14:59569] PHP Warning:  mysqli_result::fetch_row(): Couldn't fetch mysqli_result in /var/www/html/tickets/include/class.orm.php on line 3191, referer: http://portal.dom.local/tickets/scp/index.php
[Wed Feb 08 12:34:33.371705 2017] [:error] [pid 5861] [client 192.168.100.14:59569] PHP Warning:  mysqli_result::close(): Couldn't fetch mysqli_result in /var/www/html/tickets/include/class.orm.php on line 3089, referer: http://portal.dom.local/tickets/scp/index.php

**Comment by yod527** [comment]
Well, the thing is, no matter what tickets I will choose - in csv i'll get only 2 first...

**Comment by yod527** [comment]
Same problem on another server..

Версия osTicket	v1.10 (901e5ea) —  Up to date
ПО Веб Сервера	Apache/2.4.23 (Win32) OpenSSL/1.0.2h PHP/5.6.28
Версия MySQL	10.1.19
Версия PHP	5.6.28

**Comment by fdellwing** [comment]
I get the PHP warnings aswell, but the export works. Can someone look into this, with a newer mysql/php version please? @rayfoss?

**Comment by yod527** [comment]
"Users" and "Tasks" exports works fine. Problem is with tickets only. I had about 2500 tickets, and tryed to drop them. So, I left only 50, and problem is still there...

**Comment by yod527** [comment]
Updated my production server, so now versions are:
osTicket v1.10 (901e5ea) 
WebServer Apache/2.4.18 (Ubuntu)
MySQL 5.7.17
PHP 7.0.13-0ubuntu0.16.04.1
Tryed to switch to English language and English locale. Separators in CSV changed from ';' to ',' but problem is still there, (2 first tickets on the page only) even on updated server.

**Comment by ntozier** [comment]
There is already an issue report for this (with a fix).
https://github.com/osTicket/osTicket/issues/3264
please close duplicate thread.

**Comment by demenna** [comment]
@ntozier there is no fix in that thread... guy just commented out 8 lines of code. Export works but custom fields are reported as id. It is still an unresolved issue...

**Comment by ntozier** [comment]
I'm not sure what that has to do with this being a duplicate thread.  Please post updates and information to the active lone.  Linked above.

**Comment by demenna** [comment]
I was not referring to the duplicate but rather the fact that you stated that there is a fix. There is no fix. It’s an open bug. That’s all.

rdm

**Comment by ntozier** [comment]
There is a fix in that thread.  Two of them actually.  
You commented that the first one does not work.
But you have not commented on the second one.
#3813

This is a closed issue report.

**Comment by demenna** [comment]
The second one? You are referring to commenting out the free() line in mysqli.php? I did try it even though It doesn’t seem to make sense. When you comment that line everything simply crashes and the log complains of an attempt to execute an sql query in an invalid state. I’m a obj-c/java programme and I’m not familiar with php, and in particular with the object oriented styles of it. I did poke around the class.export.php file, but with very little success. Is there some documentation on the sourcecode that 
I can look through? I might be able to help if I knew a little more about what’s going on there.

rdm

**Comment by julie007** [comment]
@demenna  is right commenting those line is not proper solution. just commented out 8 lines of code all tickets exported but when I try to select tickets filtered for any of 1 or 2 tickets  it will still export all tickets.
please help me for this. it would be great if this will resolve.
Thanks in advance.
