### ISSUE TITLE
Issue when I go to /setup/index.php

### ISSUE THREAD

**Issue by pirmax** [osTicket/osTicket#3668]
> Fatal error: Uncaught Error: Call to a member function getPrimaryLanguage() on null in /var/www/vhosts/domain.com/ticket.domain.com/include/class.i18n.php:367 Stack trace: #0 /var/www/vhosts/domain.com/ticket.domain.com/include/class.i18n.php(382): Internationalization::getDefaultLanguage() #1 /var/www/vhosts/domain.com/ticket.domain.com/include/class.translation.php(761): Internationalization::getCurrentLanguage(NULL) #2 /var/www/vhosts/domain.com/ticket.domain.com/setup/setup.inc.php(73): TextDomain::configureForUser() #3 /var/www/vhosts/domain.com/ticket.domain.com/setup/install.php(16): require('/var/www/vhosts...') #4 {main} thrown in /var/www/vhosts/domain.com/ticket.domain.com/include/class.i18n.php on line 367

**Comment by fdellwing** [comment]
In what language are you trying to install? And do you have the newest language pack for that language?

**Comment by pirmax** [comment]
I haven't installed any language pack. I'm on version PHP 7.0.1+

**Comment by fdellwing** [comment]
Well..the problem is, that instead of a valid language, your language seems to be null. But without more infos (installation step, system infos), no one can help you.

**Comment by ntozier** [comment]
I would recommend that you downgrade to php 5.6.  A lot of people have reported wonky issues with PHP 7+

**Comment by pirmax** [comment]
I use the default installation...

**Comment by scroom** [comment]
Same issue here. Don't want to to downgrade to PHP 5.6 because there are other services which are running very well with PHP 7. Is there maybe a workaround?

**Comment by scroom** [comment]
In my case it helped to download the german language file to the folder include/i18n 

wget http://osticket.com/sites/default/files/download/lang/de.phar

Blank page is gone and I can start the installation process.
