### ISSUE TITLE
Uncaught exception 'ObjectNotUnique'

### ISSUE THREAD

**Issue by pespi123** [osTicket/osTicket#3671]
Hi!

We're using Mysql 5.6 and IIS 8.5 on a Windows Server 2012 R2.
After multiple tries of updating our testsystem (identical like the produtive one) I'm slowly giving up.
I'm updating from 1.9.14 to 1.10 and everytime I want to create a new ticket in the agent interface and finish the process with the "Open"-Button the site turns blank... with the debug mode enabled the following error shows up (it's also the only error I can find):

Website / PHP Error:

> Fatal error: Uncaught exception 'ObjectNotUnique' with message 'One object was expected; however multiple objects in the database matched the query. In fact, there are 3 matching objects.' in \include\class.orm.php:1176 Stack trace: #0 \include\class.orm.php(545): QuerySet->one() #1 \include\class.list.php(297): VerySimpleModel::lookup(Array) #2 \include\class.list.php(384): DynamicList->getConfigurationForm(true) #3 \include\class.list.php(728): DynamicList->getForm() #4 \include\class.list.php(763): DynamicListItem->getConfigurationForm() #5 \include\class.dynamic_forms.php(1770): DynamicListItem->getFilterData() #6 \include\class.dynamic_forms.php(1117): SelectionField->getFilterData() #7 \in in \include\class.orm.php on line 1176

I've tried searching the matching objects but I have no idea where to look and how to troubleshoot this problem, I really hope someone can help me here...

Thanks!

**Comment by fdellwing** [comment]
Please check the following tables for duplicates: ost_list, ost_filter, ost_filter_action, ost_filter_rule.

**Comment by pespi123** [comment]
Fixed... self made list with product categories like this:
         C10 - CRM Vertrieb
	 N10 - NAV Verkauf und Marketing
	 N11 - NAV Einkauf
	 N12 - NAV Artikel & Lager & Logistik
	 N20 - NAV Projektverwaltung
	 N21 - NAV Service
	 N22 - NAV Fertigung
	 N30 - NAV Buchhaltung
	 N31 - NAV MWSt-BuHa
	 N32 - NAV Anlagen-BuHa
	 N33 - NAV Kostenrechnung
	 N40 - NAV Alpha Auftrags Plus
	 N41 - NAV Alpha CRM
	 N42 - NAV Alpha Dienstleister
	 N43 - NAV Alpha Swiss Payroll
	 N50 - NAV Rechte
	 N60 - NAV Auswertungen
	 N70 - NAV Interfaces
	 N71 - NAV Office-Integration
	 N80 - NAV NAV-Server
	 N81 - NAV NAS
	 N99 - NAV Übriges

After deleting the list, the ticket creation worked again but I cant really associate it with the duplicate problem...
What ever, fixed is fixed :)
