### ISSUE TITLE
Question: New canned response

### ISSUE THREAD

**Issue by fdellwing** [osTicket/osTicket#3672]
Maybe I am just blind or stupid...but I cannot find the option to define new canned responses!? Please help me :worried:

**Comment by rayfoss** [comment]
![screenshot from 2017-02-09 08-47-51](https://cloud.githubusercontent.com/assets/876076/22788182/7c16577c-eea4-11e6-9bb3-edadd584a27d.png)

**Comment by fdellwing** [comment]
Well..what is not a place I would ever consider them. Thanks.
