### ISSUE TITLE
Cannot delete saved search

### ISSUE THREAD

**Issue by SpudR** [osTicket/osTicket#3673]
Same as v1.10-rc.2 (231f11e) Cannot delete Saved Search #2662
Issue still exists.
I have no control over the server so the proposed fix cannot be implemented.

**Comment by fdellwing** [comment]
I don't think that anyone can help you with that. This is not an error in the code, but in the config of the server.

**Comment by rayfoss** [comment]
use pull request #3665, ill make them load/deletable.
