### ISSUE TITLE
Error in pagination: Users->Organizations

### ISSUE THREAD

**Issue by adi76** [osTicket/osTicket#3674]
### Prerequisites

* [yes ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [no ] Do you have any errors in the PHP error log, or javascript console?
* [yes] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [no] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

When you go to User->Organizations (for example: url: ..../scp/orgs.php?id=1) and try to go to next page (for example: 2) the destination url should looks like: ..../scp/orgs.php?id=1&p=2 but I got .../scp/users.php?sort=&order=&p=2

The problem is in file: include/staff/templates/users.tmpl.php line 39:

Is:
$pageNav->setURL('users.php', $qs);

Should be:
$pageNav->setURL('orgs.php?id=',$org->getId(), $qs);

### Steps to Reproduce

1. Login to SCP
2. Go to Users
3. Go to Organizations of (for example: id=1)
4. Try to go to page number (for example: 2)

**Expected behavior:** [What you expected to happen]
..../scp/orgs.php?id=1&p=2

**Actual behavior:** [What actually happened]
.../scp/users.php?sort=&order=&p=2

### Versions
1.9.14
1.10
Admin panel -> Dashboard -> Information which also additionally gives you information about you server.

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

**Comment by fdellwing** [comment]
I dont have enough users to test that, but I am quite sure you can not change the $pageNav to the URL you want.

The userlist in orgs.php is the same  as in users.php. So you would end up with a really messy URL there...

See incluce/staff/org-view.inc.php:
```html
<div class="tab_content" id="users">
<?php
include STAFFINC_DIR . 'templates/users.tmpl.php';
?>
</div>
```

**Comment by adi76** [comment]
I do that change in my $pageNav (as I described earlier), and it works fine for me. I wrote this issue, to let you know that the error exists in osTicket 1.9.14 and 1.10. Maybe you should make this change to osTicket, to have this working just fine for other users in the future.

ps. sorry for my english :-)

**Comment by fdellwing** [comment]
Ok, I will be more precise: Do you have checked the functionality of the scp/users.php? Because I am 100% sure if we change what, you will have the exact same problem with "wrong URL" there.

**Comment by fdellwing** [comment]
Did a PR for this Issue, thanks for the report.
