### ISSUE TITLE
IMAP "No Such Host" error when saving and intermittently

### ISSUE THREAD

**Issue by rayfoss** [osTicket/osTicket#3675]
### Description
The problem can start in one of two ways. The mail fetcher may start sending emails with "Error: No such host as imap.gmail.com" messages, or you won't be able to configure a new imap fetch because it will error out on save with the error message "no such host".

- running ` php -r "echo gethostbyname('imap.gmail.com.');"` will return the ip as intended
- running `gethostname(google.com);` on line 336 of include/class.email.php will return `google.com`
- I tried disabling IPv6 while it was occurring, that did not help stop it.

- at least one of the machines where this was occurring took 11 seconds to run `php -a` when imap is enabled. it is quick otherwise.

The work around is to restart apache... that will fix gethostname in the apache php module. I am able to reproduce this about once a month by accident. May be related to https://github.com/osTicket/osTicket/issues/3363 but is seen most often in PHP 7 only.

May be related to http://serverfault.com/a/136550/59123 of note, which points to an apache bug in 2.4.6 through 2.4.25. perhaps only the RHEL version. May be a module such as Zend Optimizer. It's been seen happening in PHP version v4.4.9 with Zend Optimizer v2.5.10. Apache is v1.3.31.

As such the best approach would be to develop better error messages on screen and on email for this issue.

**We've only seen this happen 3 verified times in osTicket, if you are experiencing this, let us know**

### Steps to Reproduce

1. use apache
2. run osticket
3. *unknown*
4. try to save valid imap settings

**Expected behavior:**

Imap settings will save successfully.

**Actual behavior:**
An error will occur on the page with the message "no such host."

### Versions
1.10

PHP version: 
7.0.15 
Server: 
Apache/2.4.25 (Fedora) OpenSSL/1.0.2j-fips PHP/7.0.15

**Comment by gawonmi** [comment]
Was running into exactly the same error. Restarting apache resolved this issue.

**Comment by ecldcalder** [comment]
Same issue - trying to change IMAP server to outlook.office365.com and kept getting "no such host" error. Restarting apache resolved it and I was able to change the IMAP settings.

osTicket Version	v1.9.12 (19292ad)  
Web Server Software	Apache/2.2.15 (CentOS)
MySQL Version	5.1.73
PHP Version	5.3.3

**Comment by ecldcalder** [comment]
Upgraded PHP and osTicket - ran into same "no such host" problem again. Restarting apache resolved it.

osTicket Version	v1.10 (901e5ea) —  Up to date
Web Server Software	Apache/2.2.15 (CentOS)
MySQL Version	5.5.54
PHP Version	5.6.30
