### ISSUE TITLE
Dashboard Response Time

### ISSUE THREAD

**Issue by fdellwing** [osTicket/osTicket#3679]
So, we have this query for the dashboard:
```sql
SELECT A2.id AS dept__id, AVG(DATEDIFF(A1.closed, A1.created)) AS ServiceTime, AVG(DATEDIFF(A4.created, A5.created)) AS ResponseTime FROM ost_ticket A1 JOIN ost_department A2 ON (A1.dept_id = A2.id) LEFT JOIN ost_thread A3 ON (A3.object_type = 'T' AND A1.ticket_id = A3.object_id) LEFT JOIN ost_thread_entry A4 ON (A3.id = A4.thread_id AND A4.type = 'R') LEFT JOIN ost_thread_entry A5 ON (A4.pid = A5.id) WHERE A1.dept_id IN ('1', '3', '4', '5', '6') GROUP BY A2.id;
```
The ResponseTime gets calulated by this `AVG(DATEDIFF(A4.created, A5.created)) AS ResponseTime` where A4 is `ost_thread_entry A4 ON (A3.id = A4.thread_id AND A4.type = 'R')` and `A5 is ost_thread_entry A5 ON (A4.pid = A5.id)`

But as you can see here, only responses posted by filters even have a `pid`, agent ones not:
```
id, pid, thread_id, staff_id, user_id, type, flags, poster, editor, editor_type, source, title, body, format, ip_address, created, updated
24, 0, 7, 1, 0, R, 64, Fabian Dellwing, , , , , aa, html, 172.16.3.104, 2017-02-06 13:28:02, 0000-00-00 00:00:00
25, 0, 7, 1, 0, R, 64, Fabian Dellwing, , , , , test, html, 172.16.3.104, 2017-02-06 13:36:28, 0000-00-00 00:00:00
26, 0, 7, 1, 0, R, 64, Fabian Dellwing, , , , , test, html, 172.16.3.104, 2017-02-07 10:36:41, 0000-00-00 00:00:00
27, 0, 7, 1, 0, R, 64, Fabian Dellwing, , , , , test, html, 172.16.3.104, 2017-02-07 10:46:17, 0000-00-00 00:00:00
28, 0, 7, 1, 0, R, 64, Fabian Dellwing, , , , , test, html, 172.16.3.104, 2017-02-07 11:00:49, 0000-00-00 00:00:00
36, 35, 22, 0, 0, R, 192, SYSTEM (Vordefinierte Antwort), , , , , Hi Test, Your ticket #000017 created on 09.02.17 10:39 is in department., html, 172.16.3.104, 2017-02-09 10:39:05, 0000-00-00 00:00:00
```
Secondly:

`DATEDIFF` considers only days for the diff. We should think about using `ROUND(AVG(TIMESTAMPDIFF(SECOND,A5.created, A4.created))/3600/24,4)` (yes, A4 and A5 need to be switched for that!) for the response time to get precise values.

Maybe even change ResponseTime and ServiceTime to hours format for preciser values. (Just cut the /24).

**Comment by fdellwing** [comment]
Does no one have an idea how to fix that `pid` problem. It worked fine in 1.9.5 but I dont want to downgrade, because 1.9.5 is ugly as hell. I need this for pulling the correct row out of the database for an intern project.

**Comment by fdellwing** [comment]
Does no one have an idea how to fix that pid problem. It worked fine in 1.9.5 but I dont want to downgrade, because 1.9.5 is ugly as hell. I need this for pulling the correct row out of the database for an intern project.

@rayfoss @ntozier

**Comment by ntozier** [comment]
I generally advise people not to trust or rely on the Dashboard. I do not feel that it has been accurate or useful since it was first added to the product.  I heard about a tear ago that even the devs wanted to revamp it at some point.

I use the Report Mod by Scott Rowley at sudobash dot net.

**Comment by fdellwing** [comment]
I dont want to use any information in the dashboard. I just want to check which answer belongs to which answer-1 and that is currently impossible, because `pid` doesnt get set while posting a thread_entry.

**Comment by chetan-prime** [comment]
Hi @fdellwing , does #738 fix the pid column being unset for requests replied via webui ?
I can see the issue you reported with responses by agents. If I query the DB using the same query as the php then I can see most of the records pid columns has a NULL value.
Is there any way to use the thread_id to achieve what we want here instead..
