### ISSUE TITLE
Adding new custom form deletes data from old form

### ISSUE THREAD

**Issue by salloo** [osTicket/osTicket#3680]
I have created some custom forms which I attach to the tickets. But whenever a new form is added the old data from previous form disappears.

1. Create 2 custom forms with any fields.
2. Open a ticket and click manage forms.
3. Attach form, save changes
4. Edit ticket and enter form values for attached form.
5. Add second form.
6. Edit ticket, values of old form are gone.

Previous form should retain the values.

osTicket Version	1.8-git (?)  Upgrade — 901e5ea is available
Web Server Software	Apache/2.4.18 (Ubuntu)
MySQL Version	5.7.17
PHP Version	5.6.30-1+deb.sury.org~xenial+1
running on macOS Sierra version 10.12.3 (16D32)

**Comment by fdellwing** [comment]
Please update you osTicket. Your version reached EOL in May 2016.

**Comment by salloo** [comment]
This is also happening in develop branch and also in tag v1.10.

**Comment by fdellwing** [comment]
Can not reproduce that with  v1.10 (901e5ea)
