### ISSUE TITLE
editor does not accept tel: links

### ISSUE THREAD

**Issue by a-schild** [osTicket/osTicket#3681]
### Description
When entering tel: links in the wysiwyg editor, after saving they are all converted to denied:tel: links.
Also when manuelly entering them in the html source view of the editor, on save they are all marked invalid

### Steps to Reproduce
1. Open a page editor in the admin part of osticket
2. Enter a link with target tel:+41323329714
3. Hit save

![0b01c8b4f108a80104008040e757c1](https://cloud.githubusercontent.com/assets/1441009/22874676/b7e05322-f1c7-11e6-8316-2cde4a0aab96.png)

**Expected behavior:**
A clickable link with target tel:+41323329714 should be displayed on the edited page

**Actual behavior:** 
A clickable link with target denied:tel:+41323329714 is displayed and it is of course not working
![e18d8ca0ec54c835c51f8819009e73](https://cloud.githubusercontent.com/assets/1441009/22874679/ba01b358-f1c7-11e6-8b0a-7c0a9b45af36.png)

### Versions

osTicket-Version 	v1.10 (901e5ea) — Aktuell
Server-Software 	Apache/2.2.22 (Debian)
MySQL-Version 	5.6.35
PHP-Version 	5.6.30-1~dotdeb+zts+7.1
Webbrowser Firefox 51 and Google Chrome 56

**Comment by fdellwing** [comment]
Well, another redactor problem. Looked at the redactor.min.js, could not find the problem. Surrendered..

**Comment by a-schild** [comment]
It's a server side issue, the <a href"tel:..."> is correctly posted to the server, but in the received answer it's modified.
I think it's the include/htmLawed.php where the cleanup is done.

Just adding tel to line 47 does not solve the problem, perhaps someone with more knowledge about that part of the code can help out?

**Comment by mfelber** [comment]
htmLawed is configured via class.format.php. When I add "tel" to line 320 it will no longer be denied. No reboot necessary: https://github.com/osTicket/osTicket/issues/2950

**Comment by a-schild** [comment]
Yep, that solves the problem.
It's important to not add it at the end of the line, but before the first ; character, since these are the allowed links for href: type links
