### ISSUE TITLE
File Not found when using "Attachments on the filesystem"

### ISSUE THREAD

**Issue by jighem** [osTicket/osTicket#3682]
### Prerequisites

* [Yes ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ No] Do you have any errors in the PHP error log, or javascript console?
* [ Yes] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [ Yes] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

When Post Reply  
1) "IOException: Unable to read resource content" in error log 
2) to the agent it shows "File not found" 
3) User dont get notification of email 

Note: File System for Attachment is implemented.
1) Attachments can be donwloaded from SCP as well as client panel
2) While Resend from SCP it shows "Loading...." on event of Resend click by Agent on ticket where attachment is there and "File not found" message displayed.

### Steps to Reproduce

1. Implement Plugin "Attachments on the filesystem"
2.  Email Cron on the server. (May be the reason or not sure) not checked creating ticket from web.
3. (a) From Agent panel post reply where already there are some attachments while creating attachment this shows "File not found"
![systemlog](https://cloud.githubusercontent.com/assets/24699194/22877835/457a0d7e-f1fd-11e6-9b18-02ec94e51acc.png)

 (b) Resend to user using "Edit and Resend" It shows "Loading....." continuously and dont send intimation to user.
![resendattached](https://cloud.githubusercontent.com/assets/24699194/22877783/013b73aa-f1fd-11e6-96e8-905a22868fae.png)

**Expected behavior:** [It should atleast send intimation to client/users that your ticket is replied no matter attachment doesnt go.]

**Actual behavior:** [No intimation to client/user]

1.10 Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.
Currently working on production server (windows 2008r2) running on Xampp server 3.2.2
![systeminfo](https://cloud.githubusercontent.com/assets/24699194/22877903/8d66fa5c-f1fd-11e6-88e6-aa7e08964cb7.png)

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

**Comment by ntozier** [comment]
I would think that this should be in the forums or at the plugin repo issues not the main repo.  You should close this and open it in the right place.

Forums:
http://osticket.com/forum/

Plugin Repo
https://github.com/osTicket/osTicket-plugins

In the meantime here are some questions to point you in different directions for a resolution
Did you migrate your attachments from the DB to the filesystem after you enabled the Filesystem storage plugin?
Did you check file permissions (at the OS level)?
