### ISSUE TITLE
Dashboard doesn't show my tickets in the option "up to today" just selecting option one quarter

### ISSUE THREAD

**Issue by thekiree** [osTicket/osTicket#3685]
Hello everyone! , I hope you can help me with my issue , it is my university project.

I tell you my issue details:

My Dashboard doesn't show my tickets report in the option "up to today" just appear my tickets report selecting option "one quarter", or I need to wait for the next day so they can appear in my dashboard, I tried changing the zone time of php and mysql but both are rigth, and these have the correct date and format (America/Tijuana), the date and time format on my server and the date create of tickets are also correct.

I´ll show you Screenshots to describe with more details my issue, I think to know the problem maybe is the query requests, but I don´t know where I can edit it.

My other question or issue is where I find the html files because i want to quit the branding of osticket and customize to my liking.

Thank you so much!! I wait for your answers. 

### Description

[Dashboard doesn't show my tickets when I create one unless I select "one quarter"]

### Steps to Reproduce

Explaning the Issue:

1. [Right now we are on February 13, 2017, but if I select the "up to  today" option, it only shows me tickets I created a few days before, but I already created 6 tickets today and they do not appear to me]

![image](https://cloud.githubusercontent.com/assets/25756460/22909633/11f4f074-f20a-11e6-8791-a7c4a60d4614.png)

2. [When I change my search to "one quarter" it show me all my tickets]

![image](https://cloud.githubusercontent.com/assets/25756460/22909627/06ae5174-f20a-11e6-8b65-1e42e7175785.png)

3. [Lastly I show you more information images of the creation of my tickets and my system]

![image](https://cloud.githubusercontent.com/assets/25756460/22909679/5dac9a8a-f20a-11e6-8e1e-155d7253dfab.png)

![image](https://cloud.githubusercontent.com/assets/25756460/22909752/bd236278-f20a-11e6-9e26-182b281f2462.png)

Finally I show you what i want to change for my logo, and how i do it?

![image](https://cloud.githubusercontent.com/assets/25756460/22909836/39056242-f20b-11e6-93e3-0b2ba51937b8.png)

My server is debian 8 and I use chrome and firefox browsers for my tests.

Thank you so much!!!!

**Comment by fdellwing** [comment]
Can not reproduce that with my setup, works fine for me. So I'm quite sure it has something to do with timezone problems. Will look into this later.

Your other question: No one likes someone who takes a work and deletes all sign of the original author. So you have to find the right files yourself.

**Comment by ntozier** [comment]
Dashboard is old and tired and needs a revamp.  Until it becomes a priority and such a revamp happens I don't think that your going to get any traction on issues for it.  Make sure that you are running cron.php on schedule.

Change your company information at: Admin panel -> Systems -> Company.

**Comment by thekiree** [comment]
fdellwing, thanks for your answers, I tried change all my timezone mysql, my server, and php but it still not working, or if you have a solution that I can try? I will be grateful to you.

about the brand,  you're right!

**Comment by thekiree** [comment]
ntozier Thanks for answer, if the dashboard is old, how can I update it? and if you have a solution to updatate cron.php I would appreciate you to help me because I'm not very knowledgeable

**Comment by ntozier** [comment]
Q:  if the dashboard is old, how can I update it?
A: you can't.  I'm saying that it hasn't been updated by the devs in a long time and needs to redone by them.

Q: and if you have a solution to updatate cron.php I would appreciate you to help me because I'm not very knowledgeable
A: run cron.php using a task scheduler or cron..    described here:
http://osticket.com/wiki/POP3/IMAP_Setting_Guide

**Comment by thekiree** [comment]
I already understood what you wanted to tell me. about the dashboard, I´ll need to wait, but about cron.php it works okay! with all my mails, I do not think that´s the problem, because I get emails correctly, the problem is  creating tickets of all forms, my problem is actually that it does not let me see the tickets I created recently, unless I search with The "one quarter" option.

It's my college project, I think I'll disapprove haha!

Although I tried with Osticket 1.9, and this works well, but there are problems in the Spanish translation with some words, they mark me as undefinided.

**Comment by chazman113** [comment]
I can replicate this on 1.10. I've been looking in the classes and it seems like the conversion from regular date time to UNIX timestamp is setting things back or forward. I'm in windows... Windows is EST, MySQL TZ is system, OS ticket is EST, PHP is EST. For example, the stats don't populate until 4 hours after the action happens. I can hack class.reports a bit and get the statistics on the bottom right but the dashboard graph won't ever seem to display the "current date".
![capture](https://cloud.githubusercontent.com/assets/26551638/24112801/0d435f70-0d71-11e7-8507-83683d7f101f.PNG)

**Comment by chazman113** [comment]
FYI I've been troubleshooting and did the following:

Just got the latest files in the include directory for staff/classes off git in the hopes it had been incidentally fixed but no dice.

I also uploaded the MySQL timezone script and manually changed the global setting to eastern from SYSTEM.
