### ISSUE TITLE
In all ticket thread duedate changed is shown when is it fix date.

### ISSUE THREAD

**Issue by Weibel73** [osTicket/osTicket#3686]
### Prerequisites

* [X ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [X ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [X ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

[Description of the bug or feature]

After set due date to fix date, every ticket details edit append 'due date changed ' action to thread view

1. Create a new ticket and  save it
2. Open ticket, set due date to fix date in future, and update ticket
3. Open ticket again edit source for example don't edit duedate and save it
4. See in last ticket thread entry: Source changed and also duedate is changed but old and new data is same

Database data:

{"sla_id":[null,"0"],"source":["Web","Phone"],"duedate":["2017-02-24 00:45:00","2017-02-24 0:45"]}

osTicket Version	v1.10 (901e5ea) —  Up to date
Web Server Software	Microsoft-IIS/7.5
MySQL Version	5.5.31
PHP Version	5.6.9

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

**Comment by fdellwing** [comment]
Can confirm this, but point 2 is misleading: You can not set a duedate in the past.

**Comment by Weibel73** [comment]
sorry, I want to wwrite future not past :) corrected....

**Comment by fdellwing** [comment]
I am quite sure this is the reason:

`{"sla_id":[null,"0"],"source":["Web","Phone"],"duedate":["2017-02-24 00:45:00","2017-02-24 0:45"]}`

But I do not have time at the moment to look into this. The two dates are the same but not the same format. The method that compares them must be lazy programmed. It should compare them as unixtimestamps to be sure. If someone knows there it is compared, I will fix this.

**Comment by Weibel73** [comment]
I think this is a result!
because duedate not changed even so databse writer function what compare new and old data write changes to database.

I think that happens:

when edit a ticket details and post form one function read original duedate and campare form posted value, this comparing run false for 2 different date format. The function "you think" duetate changed (because 2 date format is different) and write data change to database.
