### ISSUE TITLE
Dates not showing on tickets

### ISSUE THREAD

**Issue by Cronus89** [osTicket/osTicket#3687]
I upgraded from 1.9.15 to 1.10 after doing so, The Updated Date on the Open Tickets Page is not shown. Also when going into an individual ticket, the create date is also not there.

Furthermore, I just look at logs and the logdate is also missing.

I have not found any errors anywhere and checked the database and the dates are in the tables.

Information Page > http://i.imgur.com/9VZ29v4.png

Server is Windows Server 2008 R2
Client Machine is Windows 10 Pro, using Chrome 56 64bit.
I tested on a secondary machine running the same Client versions and it also does this.

**Comment by ntozier** [comment]
CAn you provide a screen shot and mark where you are missing your dates?

**Comment by Cronus89** [comment]
The Entire column is blank on here http://i.imgur.com/ul3ZyLq.png

This is a sample of one of the tickets, all the date fields are blank here as well. http://imgur.com/l9QclRL

**Comment by fdellwing** [comment]
And you are sure, there are no php errors? This looks a lot like an error with the date class.

**Comment by ntozier** [comment]
My installation has the same issue (and has for some time) @rayfoss  and I thought that it was something that I broke making alterations to the code. (all of which were submitted as PRs) 

Server 2012 R2
IIS 8.5
MySQL 5.5.42
PHP 5.6.12

I have no PHP errors being logged.  As another side note my PHP, MySQL, ServerOS, osTicket and profile timezones all match.

**Comment by Cronus89** [comment]
I believe me and @ntozier are running the same setup pretty much.  I am on IIS 7 iirc (server 2008 r2) but its the same. Below are the only errors I have in my php log.

`[14-Feb-2017 17:15:23 UTC] PHP Fatal error:  Uncaught exception 'ObjectNotUnique' with message 'One object was expected; however multiple objects in the database matched the query. In fact, there are 2 matching objects.' in C:\inetpub\wwwroot\help\include\class.orm.php:1176
Stack trace:
#0 C:\inetpub\wwwroot\help\include\class.orm.php(545): QuerySet->one()
#1 C:\inetpub\wwwroot\help\include\class.list.php(297): VerySimpleModel::lookup(Array)
#2 C:\inetpub\wwwroot\help\include\class.list.php(384): DynamicList->getConfigurationForm(true)
#3 [internal function]: DynamicList->getForm()
#4 C:\inetpub\wwwroot\help\include\class.list.php(112): call_user_func(Array)
#5 C:\inetpub\wwwroot\help\include\class.list.php(1327): CustomListHandler->__call('getForm', Array)
#6 C:\inetpub\wwwroot\help\include\class.list.php(1327): TicketStatusList->getForm()
#7 C:\inetpub\wwwroot\help\include\class.list.php(1143): TicketStatus->getConfiguration()
#8 C:\inetpub\wwwroot\help\include\class.ticket.php(300): TicketStatus->isReopenable()
#9 C:\inetpub\wwwroot\help\include\clie in C:\inetpub\wwwroot\help\include\class.orm.php on line 1176
[14-Feb-2017 17:15:54 UTC] PHP Fatal error:  Uncaught exception 'ObjectNotUnique' with message 'One object was expected; however multiple objects in the database matched the query. In fact, there are 2 matching objects.' in C:\inetpub\wwwroot\help\include\class.orm.php:1176
Stack trace:
#0 C:\inetpub\wwwroot\help\include\class.orm.php(545): QuerySet->one()
#1 C:\inetpub\wwwroot\help\include\class.list.php(297): VerySimpleModel::lookup(Array)
#2 C:\inetpub\wwwroot\help\include\class.list.php(384): DynamicList->getConfigurationForm(true)
#3 [internal function]: DynamicList->getForm()
#4 C:\inetpub\wwwroot\help\include\class.list.php(112): call_user_func(Array)
#5 C:\inetpub\wwwroot\help\include\class.list.php(1327): CustomListHandler->__call('getForm', Array)
#6 C:\inetpub\wwwroot\help\include\class.list.php(1327): TicketStatusList->getForm()
#7 C:\inetpub\wwwroot\help\include\class.list.php(1143): TicketStatus->getConfiguration()
#8 C:\inetpub\wwwroot\help\include\class.ticket.php(300): TicketStatus->isReopenable()
#9 C:\inetpub\wwwroot\help\include\clie in C:\inetpub\wwwroot\help\include\class.orm.php on line 1176
[14-Feb-2017 17:16:28 UTC] PHP Fatal error:  Uncaught exception 'ObjectNotUnique' with message 'One object was expected; however multiple objects in the database matched the query. In fact, there are 2 matching objects.' in C:\inetpub\wwwroot\help\include\class.orm.php:1176
Stack trace:
#0 C:\inetpub\wwwroot\help\include\class.orm.php(545): QuerySet->one()
#1 C:\inetpub\wwwroot\help\include\class.list.php(297): VerySimpleModel::lookup(Array)
#2 C:\inetpub\wwwroot\help\include\class.list.php(384): DynamicList->getConfigurationForm(true)
#3 [internal function]: DynamicList->getForm()
#4 C:\inetpub\wwwroot\help\include\class.list.php(112): call_user_func(Array)
#5 C:\inetpub\wwwroot\help\include\class.list.php(1327): CustomListHandler->__call('getForm', Array)
#6 C:\inetpub\wwwroot\help\include\class.list.php(1327): TicketStatusList->getForm()
#7 C:\inetpub\wwwroot\help\include\class.list.php(1143): TicketStatus->getConfiguration()
#8 C:\inetpub\wwwroot\help\include\class.ticket.php(300): TicketStatus->isReopenable()
#9 C:\inetpub\wwwroot\help\include\clie in C:\inetpub\wwwroot\help\include\class.orm.php on line 1176
[14-Feb-2017 15:54:32 America/Chicago] PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0
[15-Feb-2017 02:56:07 UTC] PHP Fatal error:  Maximum execution time of 300 seconds exceeded in C:\inetpub\wwwroot\main\wp-content\plugins\ag-custom-admin\plugin.php on line 120`

**Comment by ntozier** [comment]
This error isn't about osTicket:
[15-Feb-2017 02:56:07 UTC] PHP Fatal error: Maximum execution time of 300 seconds exceeded in C:\inetpub\wwwroot\main\wp-content\plugins\ag-custom-admin\plugin.php on line 120

but can be fixed by increasing your max_execution_time directive in your php.ini

**Comment by Cronus89** [comment]
Yea that error is new, wasnt showing up yesterday while I was debugging this. So its unrelated to osticket.

**Comment by blueyeguy** [comment]
I had the same issue and  just changed the date and time options under system settings and preferences from -Advanced- to Locale Defaults and the times came back. 

http://osticket.com/forum/discussion/89105/no-last-updated-date-and-no-closed-ticket-count-after-1-10-stable-update#latest

**Comment by ntozier** [comment]
Confirmed.  This works...

**Comment by Cronus89** [comment]
That fixed it for me aswell!  Hopefully The Dev team can fix this bug now. It sucks cause now its stuck in 24 hour time, whether i choose it or not. Oh well, at least I have times back for now.

**Comment by blueyeguy** [comment]
I did get back my 12hr time by going back in and setting my advanced settings as shown.

![image](https://cloud.githubusercontent.com/assets/11031985/22998183/3967aa56-f39b-11e6-8f68-bdb6951714ff.png)

**Comment by SCHOLAR-Graeme** [comment]
To get the dates to appear when the "Date and Time Format" is set to "Advanced" I had to first enable PHP's Internationalization extension in the `php.ini` file:
`extension=php_intl.dll`
