### ISSUE TITLE
This is a query, Can I combine the tickets?

### ISSUE THREAD

**Issue by thekiree** [osTicket/osTicket#3690]
## Can I combine the tickets?

I want users not to be generated 2 tickets when sending two emails individually, how can I combine them, or will there be a way that when sending an email, the system recognizes that the ticket is open and continues to be added to the thread ?.

I noticed that the answers are added to the thread if you respond to the same email, but this does not always know the users, they simply send emails, and we have to be ready for these events.

**Comment by arrayown** [comment]
It's been [requested](https://github.com/osTicket/osTicket/issues/1225) since 2014, still no word on progress. There was something going on last year that kinda threw off development for a while. I hope they get to this feature eventually.
