### ISSUE TITLE
v1.9.14 Email Piping email parse failed 400

### ISSUE THREAD

**Issue by Pooleyy** [osTicket/osTicket#3692]
Hey guys,

Can anybody help me please?
I'm running v1.9.14

I'm trying to set up Email Piping (office365)
I just want future emails sent to sales@company.com to be piped into osTickets.

I've set up the following cronjob on my cPanel:
/usr/local/bin/php -q /home/company/public_html/support/api/pipe.php

I've also set up email forwarding to:
|/support/api/pipe.php

When the Cron executes, i get the following error:

`(400) Email parse failed []
(400) Unable to create new ticket: validation errors:
0: Issue Summary is a required field
1: Issue Details is a required field
message: Message content is required
err: Missing or invalid data - check the errors and try again
(416) Request failed - retry again!`

Any ideas? p.s - I'm not too much of an expert in this type of things

Thanks

**Comment by ntozier** [comment]
Last I checked Exchange did not support piping.

**Comment by Pooleyy** [comment]
Ah sorry I made a mistake. It's not office365. Just a simple email account set up in cpanel. Any ideas?

**Comment by routeprint** [comment]
Waiting for reply of subject, since i'm also facing same challenge
