### ISSUE TITLE
Uploaded image not visible in landing page for anonymous users

### ISSUE THREAD

**Issue by meddario** [osTicket/osTicket#3697]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
Didn't try
* [x] Do you have any errors in the PHP error log, or javascript console?
JS: `422 Unprocessable Entity`
PHP: Apparently nothing related to this error:
```
[Fri Feb 17 11:04:18.618365 2017] [:error] [pid 25899] [client our.ip:49335] PHP Warning:  Declaration of AssignmentForm::render($options) should be compatible with Form::render($staff = true, $title = false, $options = Array) in /var/www/html/osticket/include/class.forms.php on line 4150
[Fri Feb 17 11:04:18.618549 2017] [:error] [pid 25899] [client our.ip:49335] PHP Warning:  Declaration of TransferForm::render($options) should be compatible with Form::render($staff = true, $title = false, $options = Array) in /var/www/html/osticket/include/class.forms.php on line 4270
[Fri Feb 17 11:28:42.934122 2017] [:error] [pid 26714] [client our.ip:27867] PHP Warning:  session_destroy(): Session callback expects true/false return value in /var/www/html/osticket/scp/logout.php on line 30, referer: http://our.domain.com/scp/pages.php?id=1
[Fri Feb 17 11:28:42.934197 2017] [:error] [pid 26714] [client our.ip:27867] PHP Warning:  session_destroy(): Session object destruction failed in /var/www/html/osticket/scp/logout.php on line 30, referer: http://our.domain.com/scp/pages.php?id=1
```
* [x] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
Yes, didn't find anything similar
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?
Maybe issue #334 is similar, but it's marked as closed

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

[Description of the bug or feature]

If an image is uploaded in the landing page (using the "image button" in the editor), the image is visible in the landing page only if the user is logged in.

### Steps to Reproduce

1. [First Step] Upload the image in the landing page using the editor and save
2. [Second Step] Check the landing page without logging out, the image is visible
3. [Third Step] Check the landing page using anonymous browsing, the image isn't visible, error "422 Unprocessable Entity" in the browser network console.

**Expected behavior:** [What you expected to happen]
The image in the landing page should be visible both for logged and anonymous users.
**Actual behavior:** [What actually happened]

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.

v1.10 (901e5ea)

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

```
Web Server Software	Apache/2.4.18 (Ubuntu)
MySQL	5.7.17
PHP	7.0.13-0ubuntu0.16.04.1

```
```
Client OS: Windows 10
Browsers: Chrome 56.0.2924.87 (64-bit), Firefox 51.0.1 (64-bit)
```

Thanks in advance!

**Comment by fdellwing** [comment]
Well...this behaviour is wanted..?

```php
// Enforce security settings
if ($cfg->isAuthRequiredForFiles() && !$thisclient) {
    if (!($U = StaffAuthenticationBackend::getUser())) {
        // Try and determine if a staff is viewing this page
        if (strpos($_SERVER['HTTP_REFERRER'], ROOT_PATH .  'scp/') !== false) {
            $_SESSION['_staff']['auth']['dest'] =
                '/' . ltrim($_SERVER['REQUEST_URI'], '/');
            Http::redirect(ROOT_PATH.'scp/login.php');
        }
        else {
            require 'secure.inc.php';
        }
    }
}
```
To see images without login you need to uncheck we option `Login required` in the main settings.

**Comment by meddario** [comment]
Ok, my fault, i didn't realize that also the images in the landing pages are normal attachments after all, thanks for the clarification!
