### ISSUE TITLE
White spaces accepted in Issue Summary field

### ISSUE THREAD

**Issue by firepro20** [osTicket/osTicket#3698]
### Prerequisites

* [ Yes] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ No] Do you have any errors in the PHP error log, or javascript console?
* [ Yes] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [ No] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

When creating a new ticket, **Issue Summary** field is accepting white spaces only as a valid title, thus on the open ticket panel, tickets with no Subject are created.

Is there a way using the Regular Expression on the field to do this? i.e. the attached image?

![image](https://cloud.githubusercontent.com/assets/17837413/23063203/8e72ebae-f509-11e6-9ce0-23ee18a40900.png)

### Steps to Reproduce

1. Open a new ticket
2. Make a couple of spaces in _Issue Summary_ field
3. Fill in all other details and submit... the ticket will then be listed on the dashboard with no subject, since white spaces are excepted as a subject.

**Expected behavior:** Error message informing that an empty issue summary is not allowed.

**Actual behavior:** Ticket is created with a blank issue summary, as white spaces are taken as valid input

### Versions

Server Information
osTicket Version 	v1.10 (901e5ea) — Up to date
Web Server Software 	Apache/2.4.10 (Debian)
MySQL Version 	5.5.53
PHP Version 	7.0.14-1~dotdeb+8.1

**Comment by fdellwing** [comment]
Yes you can prevent that with the regex validator. Just use `\S` (any non-whitespace character) as regex :)

**Comment by firepro20** [comment]
Thankyou! :)

**Comment by firepro20** [comment]
Reopening this issue to make this clear. The Regex validator on osTicket works by comparing the inputted regex validator with the text inputted in the field. 

So with **\s**, which symbolises white space, if you give it whitespace it will match and proceeds to create ticket. This is not what we want.

The solution that I found is to use the **\w** regex, which represents any word/character, as long as there is something and not nothing, it will match and create ticket as needed.

**Comment by fdellwing** [comment]
Please read exactly!

I told you to use uppercase S which stands for any non-whitespace character. The levelcase s is, as you mentioned any whitespace character.

To give even more information:

`\w` == `\S`
`\W` == `\s`

**Comment by fdellwing** [comment]
Please read exactly!

I told you to use uppercase S which stands for any non-whitespace character. The lowercase s is, as you mentioned any whitespace character.

`\S` Matches anything other than a space, tab or newline.
`\s` Matches any space, tab or newline character.
`\w` Matches any letter, digit or underscore. Equivalent to [a-zA-Z0-9_].
`\W` Matches anything other than a letter, digit or underscore

**Comment by firepro20** [comment]
Yeah sorry about that misread my bad
