### ISSUE TITLE
Print ticket to PDF header text misaligned

### ISSUE THREAD

**Issue by ChristWolves** [osTicket/osTicket#3699]
Hi there,

Many thanks for producing this piece of great software! Kudos to you and your team for the awesome work, keep it up!

I have installed the latest v1.10 osTicket and noticed that once I wanted to print to PDF, the text at the header gets misaligned as shown in the attachment. 

FYI the logo is measuring 181x66 px on my Desktop screen. Just wondering what might have caused this problem? It was fine previously in v1.9.14.

Your kind help is much appreciated.
![printproblem](https://cloud.githubusercontent.com/assets/18367224/23075773/ac5b0d30-f578-11e6-9cda-4a53580536f5.jpg)

**Comment by ntozier** [comment]
This has been reported in the past, and reverting back to the stock image has always fixed the issue.

**Comment by ChristWolves** [comment]
Hi @ntozier,

Thanks for your quick response.

Are there any specific requirement for the logo in terms of dimension to prevent this from happening?

**Comment by ntozier** [comment]
Not that I know of, but I presume if you match the stock one it should be fine..

**Comment by clonemeagain** [comment]
I fixed it in mine by moving the ticket h1 to the right, see referenced plugin thread.
