### ISSUE TITLE
[1.10] Dashboard - Hundreds of "fake" ticket "created" per day

### ISSUE THREAD

**Issue by Yotouille** [osTicket/osTicket#3701]
Hi there,

We've been using osTicket on v1.10 for a few weeks without any issue, but the Dashboard had just gone wild this weekend, and it does not seems to chill out.

The Dashboard is viewing about 200 new tickets per day (shown as "created" in the Dashboard page), note that there was no new "real" ticket created since the issue. We can see this behavior from any agent account.

There's nothing in the logs, all is doing all right beside this.

**Screenshot of glitched Dashboard:**
![ost_dashboard_glitch](https://cloud.githubusercontent.com/assets/17159346/23120458/b36181aa-f75c-11e6-86fc-a30bad5fdc6f.png)

**Real ticket values:**
![ost_ticket_values](https://cloud.githubusercontent.com/assets/17159346/23120474/c532cd8a-f75c-11e6-8f13-d176e6229246.png)

Thanks !

**Comment by sperows** [comment]
I would suggest opening a thread at the official osTicket forum and you might want to check the database for these tickets (**select count(*) from ost_ticket where ost_ticket.status_id=1**), as all that dashboard does is - checks the database for this information.

You might have no permissions to view tickets, which are not assigned to the correct department.

**Comment by Yotouille** [comment]
Don't know why but the value shown in my osTicket Dashboard correspond to this query:
`select count(*) from ost_ticket` (without the `where` condition).

Next, I found an email in osTicket's inbox that wasn't deleted, and osTicket created a new (ghost) ticket every 5 minutes on the same email, all weekend long... I cannot view any of these ghost ticket in osTicket, they are only counted in the Dashboard and have really populated the DB...

**note**: the email stuck inside the inbox was an agent replying from an automatic response ("overdue notification"), subject beginning with `RE :`

It brings a lot of questions to me:
- why the email was not deleted properly ?
- why osTicket didn't recognize the same email on the second fetch ?
- how can I mass delete ~700 tickets I can't see in the UI ? (with a nice sql query maybe)
- we are only using 1 Department and 1 Team, I don't know where all these tickets have been assigned.

Thanks !! ^^

**Comment by Yotouille** [comment]
Ok ! I think I've just found the root of this problem, it was missing the `ctype` PHP module, used in some php file called from `cron.php`... My bad.

I didn't understood why the few first email where fetched all right (maybe it reached a cap in some id numbers and must use `ctype_digit()` at some point).

For the +700 junk tickets present in DB I think we will rollback past the issue.

BTW, I don't remember being warned about `ctype` for PHP during first setup (but I remember the page with green check marks all over). Maybe it would be nice to add this specificity in documentation ?

Bye !

**Comment by fdellwing** [comment]
Well, there is a simple reason, why there is no check for `ctype` module. It is in the default build since version 4.2.0. So you are using FreeBSD or a highly customized homebrew php?

**Comment by Yotouille** [comment]
We are using Alpine Linux (and Docker), I'm starting to get used about missing PHP modules when switching our Docker images from Ubuntu, but I must confess I did not see this one coming.

**Comment by fdellwing** [comment]
On the other hand, it should be absolutely no problem to add a check for `extension_loaded('ctype')` in the setup. @rayfoss please put this on your list for 1.11.0.

**Comment by Yotouille** [comment]
Thanks !

**Comment by ChristWolves** [comment]
Any tutorial on putting osT system on Docker? PLanning to try it..

**Comment by ntozier** [comment]
I'm not aware of any tutorial for this...

**Comment by Yotouille** [comment]
You can find tutos on Docker and tutos on osTicket installation, that's all you'll need.
