### ISSUE TITLE
Advanced Search Broken for Custom Form Fields of Type Choice and Custom List

### ISSUE THREAD

**Issue by jesse-thomas** [osTicket/osTicket#3703]
When using advanced search in the Agent console to search tickets with info from custom forms of the type Choice or Custom List no results are returned. 

### Steps to Reproduce all done in the Agent Console

1. Create a custom form, add a field of type choice, add some choices (Yes, No)
2. Add the form to a help topic
3. Create a ticket with that topic
4. Edit the ticket and select a value for the field (Yes or No), save.
5. Perform an advanced search for the Custom Form / Field  / includes value (yes or no)

Same thing when you use a custom list instead of the Choice field

I would expect to get back all tickets that had the matching value for the field

Instead I get back no results

osTicket Version	v1.10 (901e5ea) —  Up to date
Web Server Software	Apache
MySQL Version	5.6.33
PHP Version	5.5.9-1ubuntu4.21

Sever: Ubuntu 14.04
Browser: Google Chrome.

Additionally if I search for does not include i get tickets back that acutall have the value set.

**Comment by parijathakumar** [comment]
I am also facing the same issue. My system details are ...

Debian -8 Jessie
PHP-5.6.30
MySQL-5.5.55
Apache-2.4.10

**Comment by JediKev** [comment]
I have created this pull request that should solve this issue: #4124

**Note:** If you're using a Choices field, every choice HAS to have a key associated with them (mentioned in the helptext).
<img width="320" alt="screen shot 2017-12-14 at 13 38 51" src="https://user-images.githubusercontent.com/11823401/34011133-9c9485be-e0d4-11e7-8b2e-c2ac35c88e4e.png">

**Comment by jesse-thomas** [comment]
@JediKev Thanks for letting me know. I just added the "fix" I used several months ago, please let me know if you think its any good. Also I am not using keys with my options. #4127

**Comment by JediKev** [comment]
@jesse-thomas So I just tested your pull request and it gave me about 11 records that had nothing to do with the search. When I searched with my method it gave me 13 (correct) results and when I tested yours it gave me 24 (13 - correct || 11 - incorrect) results. I'm not sure what yours is doing but it's including results that shouldn't be there. Cheers.
