### ISSUE TITLE
Ticket and tasks have no save button

### ISSUE THREAD

**Issue by webgeri** [osTicket/osTicket#3704]
hi,
i have installed the latest version 1.10 of osticket from the official download with german translation.
my problem ist that in admin panel in Tickets and Task is no save button to make changes possible.
further i get a white site when i want to create a new ticket as a user.

i have installed osticket in xampp to try it
php 7.0.13
MySQL 5.5.5-10.1.19-MariaDB 

under information in the admin panel i have three warnings:
php extensions:
APCu - only a perfomance thing and under php7 not recommended
Zend Opcache - only a perfomance thing

php settings:
cgi.fix.pathinfo - "1" is recommended if AJAX is not working

is there any known issue and solution with php7?

thx
geri

**Comment by fdellwing** [comment]
There are many issues yet with PHP7+ as osTicket is not optimized for it. The 3 Warnings are most likely not the reason for your problem.

The white page while creating a ticket is the good know "white screen of death". Please provide us with the errors from your php errorlog.

**Comment by webgeri** [comment]
hi fdellwing,
thx for your answer.
there are some errors in the logfile, but the most are because of some mail setting issues.
here are some i dont know what to do with them:
\\include\\class.forms.php on line 4270, referer:mydomain.com/open.php
\\include\\class.forms.php on line 4150, referer:mydomain.com/account.php?do=create
\\include\\class.forms.php on line 4270, referer:mydomain.com/account.php?do=create

thx
geri

**Comment by fdellwing** [comment]
Can you post a bigger part around `\include\class.forms.php on line 4270, referer:mydomain.com/open.php`? He seems to have a problem there in line 4270, but it would be nice to know about what he is complaining.

Best would be, to give us just a whole part of your errorlog and just mask external ips/domains.

**Comment by ntozier** [comment]
For now you would want to downgrade to PHP 5.6

**Comment by webgeri** [comment]
hi,
i have found a workaround as solution for me.
i have installed osticket v1.9.15 width php 5.6 on a webserver where i can switch between php 5.6 and 7.
after that i upgraded osticket to v1.10 and tested it, everithing ok.
changed the php version from 5.6 to 7 and tested it, everthing ok.
at last i downloaded all files and the sql-dump and put all on the server where it should be and it works.

thx
geri
