### ISSUE TITLE
Can Form fields be included on the export csv file?

### ISSUE THREAD

**Issue by boschnathan** [osTicket/osTicket#3705]
this is my first time with osticket.
Issue: custom fields does not show in export.

here is what i did.

   1. create custom form with fields then link it to the help topics.
   2. create a ticket and fill out the custom fields.
   3. ticket created and closed.
    4. export the closed ticket but the fields are not included on the report (csv file)

Kindly help me with my issue.
osticket version 1.10

**Comment by fdellwing** [comment]
You can export a ticket to .csv?? I know you can export a ticket list, but a ticket?

**Comment by ntozier** [comment]
I'm not aware of such a feature in osTicket...

**Comment by boschnathan** [comment]
i mean export all the details and fields in a ticket? or if this will be done using SQL command does anybody tried it?

**Comment by fdellwing** [comment]
You can use the print option to get a PDF of a ticket. Custom fields are included in that PDF.

**Comment by boschnathan** [comment]
but within the search result, for example the closed tickets.
when you have a 100 tickets then you want to export it to csv will it include the custom fields?

**Comment by fdellwing** [comment]
No it will not.

**Comment by boschnathan** [comment]
thank you for the info.

**Comment by zuberost** [comment]
@boschnathan : Hi Could you able to resolve the Issue ??? Are you able to generate Custom Form Fields in Report ? If Yes. could you please help on the same. Even if it is through data base query.

**Comment by julie007** [comment]
Hello, I am getting the same issue custom fields does not show in the export report.can anybody tell me how and where I have to change to resolve this issue?

**Comment by maddymathan** [comment]
Hi yes me too required helptopic export in OS TICKET. Version 1.14.3 Kindly help the same
