### ISSUE TITLE
How to add sql function for filed in where statement?

### ISSUE THREAD

**Issue by KomaBeyond** [osTicket/osTicket#3708]
This is my code, but it doesn't work.
```
$ticket = Ticket::objects();
$ticket->extra['where'][] = "unix_timestamp(`created`) > 1487647093";
foreach ( $ticket->all() as $row ) {

}
```

**Comment by fdellwing** [comment]
What are you trying to do?

**Comment by KomaBeyond** [comment]
@fdellwing I want to select all of the records from tickets table  where its created time greater than the timestamp what i am given.

**Comment by fdellwing** [comment]
Are you trying to create some custom sites in osTicket?

**Comment by KomaBeyond** [comment]
@fdellwing yes, my own system base on it.
