### ISSUE TITLE
No "Add New Task" Button

### ISSUE THREAD

**Issue by webgeri** [osTicket/osTicket#3710]
hi,
i have the issue that in "Tasks" the button "Add New Task" won't apper!
also in tickets the Tasks has no Button.

i have found this issue in 1.10rc [#2627](https://github.com/osTicket/osTicket/issues/2627)

german language is installed
in admin-panel information i get one warning:
cgi.fix_pathinfo should be 1...
but in modern php that is not necessary

i use for testing xampp with
php 7.0.13 and 5.5.5-10.1.19-MariaDB

i have testet it in all modern browser:
firefox, opera, chrome, edge, safari

thx
geri

**Comment by ntozier** [comment]
If you switch to English does the button appear?

**Comment by webgeri** [comment]
hi,
no, sorry but also in englisch there a no buttons.
another issue i just found is that the timestamp in tickets is wrong, it's exactly 6 hours behind my time in austria.

thx
geri

**Comment by ntozier** [comment]
@webgeri please see the other topics here for date related things.  There are a number of them usually are resolved by correcting the date/timzeone in one of like 5 different places.

**Comment by webgeri** [comment]
hi ntozier,
ok, my bigger problem is the issue with the missing buttons in Tasks

thx
geri

**Comment by ntozier** [comment]
GitHub is for reporting replicatable bugs.  If you are experiencing multiple issue and looking for support then I would invite you to participate in the Official Support Forums at http://osticket.com/forum

I would also recommend that you start here: [Please read before requesting assistance](http://www.osticket.com/forum/discussion/77765/please-read-before-requesting-assistance#latest)

**Comment by webgeri** [comment]
hi,
i had to install osticket 1.9.15 on a server with php 5.6, than a upgraded osticket to v 1.10, switched the php version to 7.0.13, copied all files and the database to the server where osticket should run.

The Buttons are there and i can use tasks.

thx for helping!
