### ISSUE TITLE
Agent login side not working

### ISSUE THREAD

**Issue by JHLIM-DCSG** [osTicket/osTicket#3711]
Hi,

I just have a trouble after enable a new reports plugins in to the OsTicket.
Normal user login is fine but now all admin user cannot login.
It only appear white blank screen after insert the username and password.

Not too sure what happening now, database is all seem like still working fine but admin can't go into closed case anymore.
Should I reinstall the OsTicket again or how can I remove newly installed plugins?

OS : UBUNTU 14.04.
Browser : Firefox

**Comment by iHunt101** [comment]
Just delete the plugin on the directory folder and try again to load the page.

**Comment by ntozier** [comment]
"I just have a trouble after enable a new reports plugins in to the OsTicket."
There is no official reports plugin for osTicket so you would want to contact the 3rd party that you got the plugin from.  We do not support other peoples code.

"It only appear white blank screen after insert the username and password."
This means that you have a PHP error being logged..  You would want to look at your PHP error log and provide the error to the 3rd party vendor.

Please close this issue report it doesn't belong here.

**Comment by JHLIM-DCSG** [comment]
Hi ntozier,

Thanks. resolved with PHP error.

Thanks again.
