### ISSUE TITLE
No tickets visible

### ISSUE THREAD

**Issue by svdab** [osTicket/osTicket#3716]
Hello,

Recently installed the latest version of osTicket v1.10 (901e5ea).
Have no idea what I did wrong, but no single ticket is visible anymore.
It's not a rightsissue, since the tickets aren't visible from new a adminuser neither.

Any thoughts?

**Comment by fdellwing** [comment]
Just to be sure, you use the same database as before?

**Comment by svdab** [comment]
Yes, same db. One moment they were visible, the other they were not. It still says how much tickets I have, but there's no list. When I search via Users, I do see the tickets.

**Comment by fdellwing** [comment]
Do you have any php errors?

**Comment by svdab** [comment]
No.

**Comment by ntozier** [comment]
There is no such thing as a "adminuser" in osTicket.
There are Admin Agents... but that does not grant permissions to view tickets. Check the Agent 
Admin panel -> Agents -> Agent -> click on the Agent -> Click on the Access tab and then the Teams tab and ensure that the they have the proper access and teams that you want them to.

**Comment by svdab** [comment]
That is correct. It's not a rightsissue.

**Comment by ntozier** [comment]
Please provide: 
- Environment Details (OS, Webserver and ver, PHP ver, DB and ver, osTicket version)
- a screen shot demonstrating what you are talking about.  
- error logs from webserver and PHP and DB.

As I cannot replicate your report.
