### ISSUE TITLE
OS Ticket - Theme not displaying data

### ISSUE THREAD

**Issue by jhollingsworth** [osTicket/osTicket#3718]
http://osticketthemes.com/

We have applied the theme from the above site to our OS Ticket setup.  All appears to be working okay, except we have had a report that when a customer logs on to the customer portal to check the ticket data, they are unable to view.  Unless the ticket is created automatically by email.  Any tickets created on the portal or by an agent do not display any of the data.

I have two test environments that pull from the same mySQL db, one with the theme and one without.  The one without the theme displays all data perfectly and allows the customer to respond, the one with the theme only shows the header information and no data, and no option for the customer to respond.

I have done a bit of digging around and found that if I use a form which contains no custom fields, then the data shows perfectly, once I add a custom field then the data isn't viewable.

I have provided a couple of screen shots to show what I mean.  

If anyone can point me in the right direction I would very much appreciate it.

![ticket-email](https://cloud.githubusercontent.com/assets/25886546/23457343/689ac612-fe6f-11e6-9922-7efba1d7cd9e.PNG)
![ticket-portal](https://cloud.githubusercontent.com/assets/25886546/23457342/6899b02e-fe6f-11e6-95a5-9a162d2be451.PNG)

**Comment by fdellwing** [comment]
White site most likely is a php error. Did you check those?

Oh and why are you asking for help with a unofficial "theme"? I mean you paid for it, so the designer should get it to work?

**Comment by jhollingsworth** [comment]
I haven't checked the php errors yet.   The designer of the theme is not available to contact.   It's a free theme.

**Comment by fdellwing** [comment]
The should be in your php errorlog. As you dont provided any information about your system at all, I cannot give you a hint.

**Comment by ntozier** [comment]
I'm sorry but we do not provide support for 3rd part modifications (which is what 3rd party themes are now).  You will have to contact the author of the theme for support.
