### ISSUE TITLE
Errors are displayed in browser

### ISSUE THREAD

**Issue by justpusher** [osTicket/osTicket#3719]
from [bootstrap.php](https://github.com/osTicket/osTicket/blob/v1.10/bootstrap.php):  

```
        #Don't display errors
        ini_set('display_errors', 1);
        ini_set('display_startup_errors', 1);
```

There's definitely a mistake or typo.

**Comment by fdellwing** [comment]
Errors do not get shown in browser if you set up your php so. Dont know, why this 2 lines are there?

**Comment by justpusher** [comment]
display_errors option allows overriding in PHP scripts, so the errors are displayed regardless of PHP settings. This is a security breach.

**Comment by fdellwing** [comment]
No they are not, so don't panic. But I don't know why this is here, so I wait for someone who knows it.

**Comment by ntozier** [comment]
These entries are to allow the site admin to over ride settings with out having to alter the php.ini on the server so that they can troubleshoot easier.  They have been a part of osTicket for as along as I can remember.

Please close this thread.

**Comment by justpusher** [comment]
I think these lines need a proper comment in bootstrap.php

**Comment by ntozier** [comment]
If you would like to change the comment you are more then free to issue a Pull Request to change the comment.
