### ISSUE TITLE
Triple Ticket Created

### ISSUE THREAD

**Issue by DaVibez** [osTicket/osTicket#3720]
Hello,

we started now with osTicket before 3 days. Since today morning osTicket creates sometimes for an new incoming fetched e-mail 3 new Tickes for same email. I can not find the problem.

**Comment by ntozier** [comment]
This question appears to be better suited for the Official Support forums at:
https://osticket.com/forums

To get you started please read this thread: [Please read before requesting assistance](http://www.osticket.com/forum/discussion/77765/please-read-before-requesting-assistance).
