### ISSUE TITLE
Plugins unarchived on every page load

### ISSUE THREAD

**Issue by SoftwareMods** [osTicket/osTicket#3721]
With every page load every plugin has it's phar file unarchived. This not only slows performance of page loads but will also greatly restrict the size of plugins developers can create.  Having multiple plugins will only compound the issue and ultimately the plugin(s) will be blamed for greatly increasing page load times (even on pages where the plugin is never utilized).

This behavior also applies to disabled plugins.

**How I tested**
To the top of my plugins config.php file I added 

`error_log('Called');`

Built the phar file and moved it into the plugins directory
Installed the plugin
Browse to pages such as "Users > Organizations", "Manage > API Keys" and others that have nothing to do with my plugin.
With each new page the error_log has a new 'Called' line added. (tail -f error_log)
Disabled the plugin
Further browsing with further 'Called' lines generated. (I'm of the opinion that if the plugin is disabled there is no point in unarchiving and reading through it's files)
Deleted plugin
Further browsing (phar file is still present in directory but plugin isn't installed)
No further entries generated (as expected).

**Possible solution/workaround**
My current thought to work around this is to create the plugin to unarchive itself upon installation and then update it's own phar file to reference the unarchived files instead - thus the unarchive only needs to do a couple of lines of text even if your plugin is several MB. I think either the developer will have to program this way or osTicket will need modified to do something similar. As it stands now, I don't see that plugins could be larger than a MB or two depending on the host.

**Comment by ntozier** [comment]
@protich @JediKev 
Any word on this?
