### ISSUE TITLE
[Bug]contact information: Editable Settings 

### ISSUE THREAD

**Issue by mwells1702** [osTicket/osTicket#3724]
[ No] Do you have any errors in the PHP error log, or javascript console?
[ Yes] Did you check the osTicket forums?
[ Yes] Did you perform a cursory search to see if your bug or enhancement is already reported?

How to reproduce:

Go to forms -> users informations
Create a field and make it immutable (not editable) for users and agents
Login as user and open the profile
Change the field just as you like. It will be saved.

osTicket Version: v1.10 (901e5ea) —  Up to date
Web Server Software: Microsoft-IIS/8.5
MySQL Version:5.6.33
PHP Version:7.0.16
OS: Windows Server 2012 R2 DC
-Getting no errors. Just does not seem to work.
![upload](https://cloud.githubusercontent.com/assets/26208878/23593198/7af4d6bc-0203-11e7-98d7-293f358796d5.png)

Ok so the field (tick box) that allows you to set "read-only" in the "contact information" section is not working for me. I want users to be able to sign up with name then not be able to change it once logged-in. However when i uptick the box my test user account is still able to edit the full name box?

"Fields marked editable allow agents and endusers to update the content of this field after the form entry has been created."

full information here (http://osticket.com/forum/discussion/89994/field-config-full-name#latest

**Comment by blueyeguy** [comment]
The thread you linked suggested trying PHP 5.6, did you do that? Your information still shows PHP 7

**Comment by mwells1702** [comment]
I have PHP 5.6.30 and have tried that.?

**Comment by mwells1702** [comment]
[06-Mar-2017 19:08:57 UTC] PHP Warning:  array_reduce() expects parameter 1 to be array, null given in C:\Inetpub\vhosts\<domain>\<sub-domain>\include\ajax.forms.php on line 76

Dont know if this helps

**Comment by dogatemycomputer** [comment]
+1 

Marking a field READ ONLY allows the customer to edit it by accessing the customer portal and clicking EDIT.   I dug around in the PHP code and could not find anyplace where the CSS marks the field READ ONLY when generated.  

Server Information
osTicket Version	v1.10 (901e5ea) —  Up to date
Web Server Software	Apache/2.2.15 (CentOS)
MySQL Version	5.5.54
PHP Version	5.6.30

![editable](https://cloud.githubusercontent.com/assets/7565020/24068404/06ee14d0-0b4b-11e7-9113-4e9a0972993e.jpg)

**Comment by JediKev** [comment]
I have submitted a pull request that should fix your issue. Please pull the changes, test, and let me know if it resolves your issue. 👍

**Comment by mwells1702** [comment]
Does not seem to work for me ?

**Comment by JediKev** [comment]
So you made all the changes in my pull request and it doesn't fix the field editablity issue? Are you getting any errors?

**Comment by mwells1702** [comment]
Tested & Works

**Comment by akash65** [comment]
> Tested & Works

Hello dude, but that thing is not working for me. can you help me?

**Comment by akash65** [comment]
> I have submitted a pull request (#3888) that should fix your issue. Please pull the changes, test, and let me know if it resolves your issue.

Is that pull request works beacuse i didn't find any solution to my problem...please help me to figure out
