### ISSUE TITLE
Translation file doesn't work.

### ISSUE THREAD

**Issue by Rockhount** [osTicket/osTicket#3725]
### Prerequisites

* osTicket-Version: 	v1.10 (Stable - 901e5ea)
* Server-Software: 	Microsoft-IIS/10.0
* MySQL-Version:		5.7.17
* PHP-Version: 	 	7.0.16 (+ APCu v7.0.10 & Zend Opcache v7.0.16)

### Description

Translation doesn't apply. The " de.phar" file is the new one from January 2017.

### Steps to Reproduce

1. Setup the stable release with the versions above.
2. Download and install the german language file.
3. Set German as the primary language under the general settings.

**Expected behavior:** Display most of the text as German.

**Actual behavior:** German texts are rarely displayed. Most of the time it is still in english.

#### PHP

PHP Warning:  array_key_exists() expects parameter 2 to be array, boolean given in C:\...\include\class.translation.php on line 419

PHP Warning:  include(): Failed opening 'phar://C:/.../include/i18n/de.phar/LC_MESSAGES/messages.mo.php' for inclusion (include_path='./;C:/.../include/;C:/.../include/pear/') in C:\...\include\class.translation.php on line 565

### Question

So whats the real problem and how do I have to chage "class.translation.php", so that it works again?

**Comment by fdellwing** [comment]
Can you test it with PHP 5.6?
