### ISSUE TITLE
SMTP Office 365

### ISSUE THREAD

**Issue by julianlampert** [osTicket/osTicket#3726]
I cannot setup my mail account from Office 365:
`Failed to connect to ssl://smtp.office365.com:587 [SMTP: Failed to connect socket: fsockopen(): unable to connect to ssl://smtp.office365.com:587 (Unknown error) (code: -1, response: )]`

I think this issue has something to do with the SMTP-Class from PEAR.

**Comment by julianlampert** [comment]
Changed the following line in `/include/pear/Net/SMTP.php`:
from
`$this->socket_options =$socket_options;`
to
`$this->socket_options = array('ssl' => array('verify_peer_name' => false));`

In the settings I used the hostname: `smtp.office365.com` and the port `587`, without the `ssl://`

**Comment by ntozier** [comment]
Version of osTicket?
Version of PHP?

**Comment by julianlampert** [comment]
osTicket Version: v1.9.15 (70898b3)
PHP Version: 5.6.30

But the issue is already resolved, with the solution above.

**Comment by lewishackfath** [comment]
Hello,

What was the line number of the code changed.
I'm working in version 1.10.1 but am having the same issue.

**Comment by JediKev** [comment]
@lewishackfath the line he changed, changes nothing. `$this->socket_options` is already set to `array('ssl' => array('verify_peer_name' => false))` so I don't know why he did that or maybe a fix has already been merged. Anyways you should try out the part beneath the code change and see how that goes. Cheers.

**Comment by lewishackfath** [comment]
@JediKev what do you mean the part beneath the code change?

**Comment by mfelber** [comment]
@lewishackfath I think he meant 
> In the osTicket settings I used the hostname: smtp.office365.com and the port 587, without the ssl://

**Comment by lewishackfath** [comment]
@mfelber  I have already tried both with and without the ssl:// and with/without tls:// all of these fail.
I am getting incorrect authentication errors when I know the details are correct as I am using them as smtp details for a wordpress site that I run on the same server. I am very much at a loss as to why I cannot get this to work. I also have a ticket on the OS Ticket forums but am not getting anywhere their either: http://osticket.com/forum/discussion/comment/118862

This is extremely frustrating as we cannot send authenticated mail which means some of our end users are having the emails flagged as spam and its getting dropped from their inbox.

**Comment by ntozier** [comment]
Side thought... Are you using a "MS Exchange Shared Account" instead of a dedicated Exchange User account?

**Comment by lewishackfath** [comment]
@ntozier I'm not sure how will I determine if this is the case?

All I know is to authenticate with smtp on my wordpress site I use the following credentials:

Username: emailaddress@domain.com.au
Password: EmailPassword
server: smtp.office365.com
Port: 587
TLS enabled

**Comment by ntozier** [comment]
You would look in Exchange Online.  You would have to ask MS how to tell the difference [we do not use them where I work as they violate HIPAA]

I think that Kevin is saying by "try the part beneath the code" is this: 
"In the osTicket settings I used the hostname: smtp.office365.com and the port 587, without the ssl://"

Julian's fix was:
open this file: /include/pear/Net/SMTP.php
go to line 176.
change the line from: $this->socket_options = $socket_options;
to: $this->socket_options = array('ssl' => array('verify_peer_name' => false));
Have you done that?

**Comment by JediKev** [comment]
@ntozier it doesn't seem he needs to because it does that by default. Unless somehow `$socket_options` is getting set beforehand?
```php
        // Turn off peer name verification by default
        if (!$socket_options)
            $socket_options = array(
                    'ssl' => array('verify_peer_name' => false)
                    );

        $this->socket_options = $socket_options;
```

So maybe @lewishackfath should try the suggested fix just in case!

Also, @lewishackfath, can you confirm that in your php.ini file `php_openssl.dll` is indeed uncommented?

**Comment by lewishackfath** [comment]
@ntozier 

I have tried both with and without the fix and get the same issue no matter what I do.
if I forego putting the ssl:// or tls:// on the front i get the folllowing error:
`authentication failure [SMTP: Invalid response code received from server (code: 535, response: Incorrect authentication data)]`

and if I include either tls:// or ssl:// i get this error:
`Failed to connect to tls://smtp.office365.com:587 [SMTP: Failed to connect socket: fsockopen(): unable to connect to tls://smtp.office365.com:587 (Unknown error) (code: -1, response: )]`

**Comment by lewishackfath** [comment]
@JediKev I will have to wait for the server providers to open to confirm this as I do not have access to view our php.ini file.

**Comment by ntozier** [comment]
You have not answered this:

Julian's fix was:
open this file: /include/pear/Net/SMTP.php
go to line 176.
change the line from: $this->socket_options = $socket_options;
to: $this->socket_options = array('ssl' => array('verify_peer_name' => false));
Have you done that?

**Comment by lewishackfath** [comment]
@ntozier yes i have.

I have then tried the server as smtp.office365.com and I still get an authentication error.

**Comment by mfelber** [comment]
One thing came to my mind which you easily can try.

Download newer versions of the pear package and replace temporarily the two files of osticket with the newer ones: 
http://download.pear.php.net/package/Net_SMTP-1.8.0.tgz
http://download.pear.php.net/package/Net_Socket-1.2.2.tgz

Replace SMTP.php and Socket.php from "include/pear/Net/" with the ones from the downloaded archives. Maybe for Office 365 is some special treatment necessary which is better handled with the newer versions of the files.

**Comment by lewishackfath** [comment]
@mfelber this time it worked! Thanks you.

I used the server as: smpt.office365.com:587

**Comment by mfelber** [comment]
I'm glad that I could help you. This was not easy..

**Comment by lewishackfath** [comment]
@mfelber no it was not. But at least now there is an answer! And that means it may help many others.

**Comment by mfelber** [comment]
@lewishackfath Yes, that was worth it. For the next office 365 user it will be a lot easier.

**Comment by edgar2627** [comment]
I just installed osTicket 2020-02-23 and having the similar issues: 

Sending Email via SMTP     Failed to connect to smtp.office365.com:587 [SMTP: Failed to connect socket: Connection refused (code: -1, response: )]
Authentication Required | Yes

osTicket Version | v1.14.1 (f1e9e88)
Web Server Software | Apache
MySQL Version | 5.6.44
PHP Version | 5.6.40

Can somebody help?

**Comment by ntozier** [comment]
@edgar2627 This is a closed issue report.  The cause was an old version PEAR packages which upgrading fixed.

The error messages the user reported are not the same as you are reporting.

I would recommend that you post on the support forums.  Please read and follow the posting guidelines before you post: [Please read before requesting assistance](https://forum.osticket.com/d/89131-please-read-before-requesting-assistance).
