### ISSUE TITLE
Buggy dropdown for due date

### ISSUE THREAD

**Issue by pespi123** [osTicket/osTicket#3727]
System:
Osticket 1.9.14, IIS 8 with PHP 5.6.24 (already tried different PHP Versions) on a Windows Server 2012 R2

PHP / OsTicket Timezone: 
Europe/Zurich

A partner company of mine has the issue, that the shown values in the duedate dropdown-list are completly wrong but the actual value of the list element is right (when inspecting the element).
It looks like this:
![image](https://cloud.githubusercontent.com/assets/12261308/23617834/aaaa69fe-028e-11e7-80df-fa328ad66344.png)

The duedate value works in the background, it's just the shown value that is wrong... any tips on what to check? 

We already went through some parts of the code and database and compared it to a "working" system, so far nothing special :(

**Comment by blueyeguy** [comment]
Try adjusting your Date and Time format settings in Admin Panel>Settings>System>Date and Time Options
Mine are set as shown in the attached:
![datetime](https://cloud.githubusercontent.com/assets/11031985/23620147/8a8468f6-025b-11e7-9883-9a6beaab6cf9.JPG)

**Comment by pespi123** [comment]
Mhh it's pretty much the same like in your configuration (beside the timezone: Europe/Zurich)...
I also compared the settings with our OsTicket but I couldn't find a difference...

**Comment by pespi123** [comment]
Okay nevermind, your tip helped 👍 
The timeformat for europe is H:i:s or G:i:s, I was just blindly checkling the formats without even caring for the input in the fields...
