### ISSUE TITLE
php warnings following deployment instructions in README

### ISSUE THREAD

**Issue by bradbulger** [osTicket/osTicket#3728]
This is running php 5.6.11 on Ubuntu 15.10. Following the Deployment steps in the README file to deploy into a nonexistent directory, it seems to be trying to include bootstrap.php before copying it? I'm not sure. A subsequent repeat of the "deploy" command has no error. The new directory is populated in any case.

$ git clone https://github.com/osTicket/osTicket
Cloning into 'osTicket'...
remote: Counting objects: 36683, done.
remote: Total 36683 (delta 0), reused 0 (delta 0), pack-reused 36682
Receiving objects: 100% (36683/36683), 21.85 MiB | 1.88 MiB/s, done.
Resolving deltas: 100% (27719/27719), done.
Checking connectivity... done.
$ ls -ld /var/www/osticket
ls: cannot access /var/www/osticket: No such file or directory
$ cd osTicket/
$ php manage.php deploy --setup /var/www/osticket
PHP Warning:  include(/var/www/osticket//bootstrap.php): failed to open stream: No such file or directory in - on line 2
PHP Warning:  include(): Failed opening '/var/www/osticket//bootstrap.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in - on line 2
PHP Notice:  Use of undefined constant INCLUDE_DIR - assumed 'INCLUDE_DIR' in - on line 3
$ php manage.php deploy --setup /var/www/osticket
$

**Comment by jwogrady** [comment]
Having the same issue...  Here are my steps to reproduce and workaround...

Per the install instructions

```shell
root@myserver:~# mkdir /var/www/MY-WEBSITE/osticket
root@myserver:~# chown -Rf www-data:www-data /var/www/MY-WEBSITE/osticket/
root@myserver:~# git clone https://github.com/osTicket/osTicket
Cloning into 'osTicket'...
remote: Counting objects: 36683, done.
remote: Total 36683 (delta 0), reused 0 (delta 0), pack-reused 36682
Receiving objects: 100% (36683/36683), 21.85 MiB | 17.61 MiB/s, done.
Resolving deltas: 100% (27719/27719), done.
Checking connectivity... done.
root@myserver:~# cd osTicket/
root@myserver:~/osTicket# php manage.php deploy --setup /var/www/MY-WEBSITE/osticket/
PHP Warning:  include(/var/www/MY-WEBSITE/osticket//bootstrap.php): failed to open stream: No such file or directory in - on line 2
PHP Warning:  include(): Failed opening '/var/www/MY-WEBSITE/osticket//bootstrap.php' for inclusion (include_path='.:/usr/share/php') in - on line 2
PHP Notice:  Use of undefined constant INCLUDE_DIR - assumed 'INCLUDE_DIR' in - on line 3
root@myserver:~/osTicket# php manage.php deploy --setup /var/www/MY-WEBSITE/osticket/
root@myserver:~/osTicket# 
```
looks like it can't find //botstrap.php....  Let's try same procedure leaving off the trailing slash.

```shell
root@myserver:~# mkdir /var/www/MY-WEBSITE/osticket
root@myserver:~# chown -Rf www-data:www-data /var/www/MY-WEBSITE/osticket
root@myserver:~# git clone https://github.com/osTicket/osTicket
Cloning into 'osTicket'...
remote: Counting objects: 36683, done.
remote: Total 36683 (delta 0), reused 0 (delta 0), pack-reused 36682
Receiving objects: 100% (36683/36683), 21.85 MiB | 18.29 MiB/s, done.
Resolving deltas: 100% (27719/27719), done.
Checking connectivity... done.
root@myserver:~# cd osTicket/
root@myserver:~/osTicket# php manage.php deploy --setup /var/www/MY-WEBSITE/osticket
PHP Warning:  include(/var/www/MY-WEBSITE/osticket//bootstrap.php): failed to open stream: No such file or directory in - on line 2
PHP Warning:  include(): Failed opening '/var/www/MY-WEBSITE/osticket//bootstrap.php' for inclusion (include_path='.:/usr/share/php') in - on line 2
PHP Notice:  Use of undefined constant INCLUDE_DIR - assumed 'INCLUDE_DIR' in - on line 3
root@myserver:~/osTicket# php manage.php deploy --setup /var/www/MY-WEBSITE/osticket
root@myserver:~/osTicket# 
```
That didn't help.

In both case, no error the second time I run the command since the file exists on the second try.

This leads me to think this is related to the processor order on the setup script.
