### ISSUE TITLE
Multiselect problems

### ISSUE THREAD

**Issue by Micke1101** [osTicket/osTicket#3735]
### Prerequisites

* [Y ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [N ] Do you have any errors in the PHP error log, or javascript console?
* [Y ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [Y ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

Unable to move focus away from multiselect field in a custom form when in internet explorer.
I found this https://github.com/select2/select2/issues/3300 which suggests that it's the placeholder that does it and after making the placeholder empty in class.forms.php it seems to work
`                echo ' data-'.$D.'="'.Format::htmlchars($V).'"';
            ?>
            data-placeholder="<?php /*echo $prompt;*/ ?>"
            <?php if ($config['multiselect'])
                echo ' multiple="multiple"'; ?>>`

### Steps to Reproduce

1. Add a choise field to the contactform with some entries of your choise.
2. Go to create a new user.
3. Click on the field.
4. Now try and go to another field.

**Expected behavior:** The focus should be moved to the field i want that i click on.

**Actual behavior:** The multiselect regains focus.

### Versions
Production
osTicket Version v1.10 (901e5ea)
Web Server Software Microsoft-IIS/7.5
MySQL Version 5.7.14
PHP Version 5.6.30

Testing
osTicket Version 1.10
Web Server Software Apache/2.4.23 (Win64) PHP/5.6.25 
MySQL Version 5.7.14 
PHP Version 5.6.25 

OS Windows 7
Affected browser Internet Explorer 11.0.9600.18537

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

**Comment by ntozier** [comment]
While I don't have an answer for you I did want to let you know that I appreciate this issue report. :)

**Comment by jacquibo** [comment]
I'm getting this same issue with 4.0.3 :(
From what I've read in issues now closed on here it's been know about since 2015.

**Comment by ntozier** [comment]
@jacquibo  4.0.3?

**Comment by Micke1101** [comment]
@ntozier he's reffering to the version of select2 which was what was the suggested fix for this issue.
