### ISSUE TITLE
i18n: Redactor not completely translated (e.g. German translation)

### ISSUE THREAD

**Issue by Af0x** [osTicket/osTicket#3736]
Hello,

concerning version 1.10 with German translation, there are many translations missing in Redactor:

- Sourcecode-icon

- font-style-icon, including h1 to h5

- video-icon, also no text is visible in the corresponding popup

- table-icon, including the complete dropdown

- link-dropdown

- align-icon, including the dropdown
 
System: Apache 2.4.10 | MySQL 5.5.54 | PHP 7.0.16-1

@Chefkeks maybe you can say something about this?

Regards,

Af0x

**Comment by Chefkeks** [comment]
Yes, sure I can say something about this.

Just looked it up and there are 36 strings which are translated when it comes to Redactor - did a search on the translation platform 😉. So it seems like that Redactor is definitely not completely translated. My guess is that inside the source code of osTicket / Redactor only a part of all the strings got converted so they are translatable and others are still missing. Maybe @rayfoss or @JediKev can chime in here and add them to the translation system? I'd do it myself, but lacking time - would need a day with 72 hours these days to get all the outstanding things at work / home done, so not really have time to do it.

Cheers,
Michael

**Comment by Af0x** [comment]
thanks for your explanation.
It seems they aren´t interested.

**Comment by ntozier** [comment]
"It seems they aren´t interested."

I don't know about them... but comments like this make me not want to help the individual posting it.

**Comment by Af0x** [comment]
and what is wrong on that? Chefkeks mentioned them 4 days ago, since then there is no feedback at all. So it seems they are not interested in helping on this particular topic.

**Comment by ntozier** [comment]
You are assuming.

**Comment by DMTGMBH** [comment]
@chefkeks @notzier [Here you will find a solution](http://osticket.com/forum/discussion/90628/bugfix-redactor-translation-of-missing-strings-or-languages) to add missing languages or language strings to redactor without touching the core files. It uses the inbuild function of redactor to load languages from external files. Best regards, Jürgen

**Comment by Af0x** [comment]
hello Jürgen, thank you for the Fix. Could you please attach the Blueprintfile to the post. I will test it then. Regards, Af0x

**Comment by Af0x** [comment]
is this issue still present in the current Version 1.10.1?
If yes could someone please fix this?

**Comment by JediKev** [comment]
@Af0x 

>is this issue still present in the current Version 1.10.1?

Yes. There is no pull request referenced so you can assume so.

>If yes could someone please fix this?

Unfortunately, no one here has time right now (as we are all working on other things) so you'll have to wait until a pull request is made to add the rest of the translation strings. If you cannot wait, the code is Open Source and you're allowed to modify it how you want it. 👍

Cheers.

**Comment by Af0x** [comment]
I really hope someone finds time to fix this soon because this issue makes the system look very unprofessional to any customer wanting to create a new ticket in a translated edition.

Also it takes some time to translate and release new language-packages.

Please don´t wait too long.

**Comment by ntozier** [comment]
This is open source.  You or anyone else can make a PR with the fix.  If this is that important to you then why not do it yourself?

**Comment by Af0x** [comment]
because this is out of my skill range.

**Comment by Af0x** [comment]
will this issue be fixed in the upcoming 1.11?

**Comment by JediKev** [comment]
@Af0x 

As far as I know, no.

Cheers.

**Comment by JediKev** [comment]
@Af0x

Our i18n process has never been stated as completed. We are still working on the i18n process as we develop along. Feel free to contribute and update these files yourself if you can.

Cheers.

**Comment by Af0x** [comment]
it is an issue that makes translated osticket-versions look very unprofessional because the missing redactor-strings will not be shown.

On the first post I made a list what is missing.

**Comment by JediKev** [comment]
@Af0x

Honestly, @DMTGMBH has already linked you to a post on our forum explaining how to do it manually. You can implement his directions or wait for an official pull request.

Cheers.

**Comment by Af0x** [comment]
honestly it can´t be that big deal to fix this issue for someone who already added some i18n string. why should every user himself fix it on his system when, with some efford. it can be fixed and made better for everyone. And no, I can´t make a commit when nobody is able or willing to explain what has to be done.

**Comment by ntozier** [comment]
@Af0x It looks to me like the fix was posted to you on Jun 18 2017.
https://github.com/osTicket/osTicket/issues/3736#issuecomment-309265105

**Comment by Af0x** [comment]
see my last comment. this is only a temporary, local fix and doesn´t help the rest. but ok, we can do this through the next versions when I ask again if there has been a fix and you say no and that there is already a fix and then I explain why this is no real solution for all the users and you say then you just have to be patient or have to commit a fix until someone finally someone takes heart and commits a real solution.

the developers add so much nice features to this software but somehow can´t manage to fix problems (or "incompletion") that affect users the most because it is in the front end.

**Comment by ntozier** [comment]
There is a fix right there and I feel like if it was really that important to you or anyone else then perhaps someone would have used the last year and 13 days and made it into a pull request for inclusion in the project.  Since you haven't it must really not be that important to you.

**Comment by Af0x** [comment]
since you don´t read precisely and don´t seem to understand the content of the fix there is no sense to discuss any further with you.

**Comment by ntozier** [comment]
My point stands.  Good day.

**Comment by Af0x** [comment]
I tried the fix with 1.11.0-rc1 and get a 403 when trying to access the newly created file in /include/i18n/redactor.
Any idea what could be wrong?

**Comment by Af0x** [comment]
so I disabled the .htaccess file in /include and the error is gone. But even then redactor doesn´t get filled with the alternate strings. So - at least for version 1.11.0-rc1 - the fix is not working.

**Comment by Af0x** [comment]
still need help
