### ISSUE TITLE
disable a department ...

### ISSUE THREAD

**Issue by cervedgroup** [osTicket/osTicket#3737]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [ ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [X ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

Can i do something to disable a Department, without deleting it ?
i need , for example, that a department will be not visible in department list while transferring a ticket
Thank you

Version 1.9.14

**Comment by ntozier** [comment]
I do not beleive that this is a feature at this time.  Have you tried making it private?

**Comment by cervedgroup** [comment]
yes, but is still there ...

**Comment by cervedgroup** [comment]
if i delete the department, what happen to all the closed tickets assigned to the department ?
