### ISSUE TITLE
v1.10 Task DueDate - unable to change

### ISSUE THREAD

**Issue by mlipok** [osTicket/osTicket#3740]
### Prerequisites

* [**Y** ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [**N** ] Do you have any errors in the PHP error log, or javascript console?
* [**Y** ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [**Y** ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description
**I'm unable to change Task DueDate.**

### Steps to Reproduce

1. [First Step]
**Create new task**

2. [Second Step]
**Try to change DueDate for this saved task**

**Expected behavior:** [What you expected to happen]
**osTicket should give ability to change DueDate for tasks.**

**Actual behavior:** [What actually happened]
**Can not change DueDate for tasks.**

### Versions
**v1.10**

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.
**NOT RELATED / NEEDED**

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.
**NOT RELATED / NEEDED**

http://osticket.com/forum/discussion/90036/how-to-change-end-due-time-in-task#latest

**Comment by rayfoss** [comment]
Confirmed.
![screenshot from 2017-03-17 12-42-48](https://cloud.githubusercontent.com/assets/876076/24055746/4bcfd660-0b0f-11e7-8dad-e550070deb8b.png)

**Comment by ntozier** [comment]
This appears to be a duplicate issue of https://github.com/osTicket/osTicket/issues/2994
Please close dupe (which is sad since I think that this one is better written).

**Comment by tkozubek** [comment]
Affirmative.
Workaround is to close task and reopen a duplicate... please enhance the "tasks" area.

**Comment by WilliamAnthony** [comment]
when will this enhancement be done?

**Comment by mlipok** [comment]
@JediKev  Any comment as to the reasons for closing this ticket/FeatureRequest/BugReport?
