### ISSUE TITLE
manage.php deploy path problems

### ISSUE THREAD

**Issue by dmnc-net** [osTicket/osTicket#3741]
### Description

Errors during CLI deployment.

### Steps to Reproduce
Follow README.md Deployment section:

> And deploy the code into somewhere in your server's www root folder, for instance
> ```
> cd OsTicket
> php manage.php deploy --setup /var/www/htdocs/osticket/
> ```

**Expected behavior:**
No error

**Actual behavior:**
```
# php manage.php deploy --setup /var/www/osticket-latest/
PHP Warning:  include(/var/www/osticket-latest//bootstrap.php): failed to open stream: No such file or directory in - on line 2
PHP Stack trace:
PHP   1. {main}() -:0
PHP Warning:  include(): Failed opening '/var/www/osticket-latest//bootstrap.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in - on line 2
PHP Stack trace:
PHP   1. {main}() -:0
PHP Notice:  Use of undefined constant INCLUDE_DIR - assumed 'INCLUDE_DIR' in - on line 3
PHP Stack trace:
PHP   1. {main}() -:0
```

Second run of the command didn't produce an error message at all.

**Running on:**

PHP 5.6.30-0+deb8u1 (cli) (built: Feb  8 2017 08:50:21) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans

**Comment by webunraveling** [comment]
Here is, what appears to be, the same issue but on a server running PHP7.

Output of install script:

    $ php setup/cli/manage.php deploy --setup /home/userName/public_html/my/install/dir/osTicket/
    #!/usr/bin/env php

Resulting `error_log` file

    [14-Aug-2017 16:16:46 UTC] PHP Warning:  include(/home/userName/public_html/my/install/dir/osTicket//bootstrap.php): failed to open stream: No such file or directory in - on line 2
    [14-Aug-2017 16:16:46 UTC] PHP Warning:  include(): Failed opening '/home/userName/public_html/my/install/dir/osTicket//bootstrap.php' for inclusion (include_path='.:/opt/alt/php70/usr/share/pear') in - on line 2
    [14-Aug-2017 16:16:46 UTC] PHP Notice:  Use of undefined constant INCLUDE_DIR - assumed 'INCLUDE_DIR' in - on line 3

**Comment by JediKev** [comment]
Try removing the end slash on the command and retry 👍

**Comment by JediKev** [comment]
If you read the error you can see that it has two slashes in front of `bootstrap.php`, which that path does not exist, which will cause bootstrap to not be included, which stops deployment 😁
```
[14-Aug-2017 16:16:46 UTC] PHP Warning:  include(/home/userName/public_html/my/install/dir/osTicket//bootstrap.php): failed to open stream: No such file or directory in - on line 2
```

**Comment by webunraveling** [comment]
Wow... thanks for the ~~bug fix~~ patient explanation about what I was doing wrong. I probably shouldn't have been on the internet that day.

**Comment by JediKev** [comment]
@webunraveling lol no problem dude! It happens to me all the time! Take this for example:
https://github.com/osTicket/osTicket/issues/3865#issuecomment-310687046

I was completely embarrassed that I didn't know you can install under a different language 😂

**Comment by webunraveling** [comment]
haha thanks for sharing... glad you got it figured out after all of that work.

**Comment by dmnc-net** [comment]
nope, error remains even if I removed the ending slash in the command and second run produces no errors.

**Comment by JediKev** [comment]
@dmnc-net Is the file actually there? Is the file readable/writable to php?

**Comment by JediKev** [comment]
@dmnc-net Also, please post a screenshot of you running the command and the error it returns.

**Comment by dmnc-net** [comment]
![image](https://user-images.githubusercontent.com/2069874/32703462-9075e1ca-c7f6-11e7-87e8-3c12f2613231.png)
... sure but it is nothing else than I've posted here in the `code` block. Maybe I should attach some additional debug from php but dunno how. It is trying to do `include(/var/www/osticket-latest//bootstrap.php)` on the 2nd line of file '' (no file) ... At the 2nd run file exists (double slash is probably not a problem) and output is blank.

**Comment by JediKev** [comment]
@dmnc-net somewhere you have a second slash being appended to the string as you see here:
```
include(): Failed opening '/var/www/osticket-test//bootstrap.php' for inclusion ...
```

You need to figure out where that second slash is coming from, remove it, and you'll be all good. I cannot, under any circumstance, reproduce this _unless_ I manually add the second slash myself.

**Comment by dmnc-net** [comment]
As I wrote, 2nd slash has been produced [here](https://github.com/osTicket/osTicket/blob/develop/include/cli/modules/unpack.php#L213) and even if I modify the code on that line (remove the slash) to: `include '{$this->destination}bootstrap.php';`, error still remains. 

As a proof, I've included `file_exist` check just before that fread which executes include...
```
echo (file_exists($this->destination."bootstrap.php")? "YEP": " NOPE");
 $INCLUDE_DIR = fread($pipes[1], 8192);
```
And guess what? NOPE. So please let those double slashes live, we have to focus on that part where code is trying to include non-existent file ... probably it has to be just for evaluation of the `$INCLUDE_DIR` but in my case it is executed.... so how can I help?

**Comment by JediKev** [comment]
Create the directory beforehand, run the command as `sudo`, and let me know what happens. Cheers.

**Comment by dmnc-net** [comment]
@JediKev I've tried that as `root` and error still remains. But I've expected this from my previous findings. As I mentioned and linked the code, this method is simply trying to include non-existent file:
```
    function get_include_dir() {
        static $location;
        if (isset($location))
            return $location;
        $pipes = array();
        $php = proc_open('php', array(
            0 => array('pipe', 'r'),
            1 => array('pipe', 'w'),
        ), $pipes);
        fwrite($pipes[0], "<?php
        include '{$this->destination}/bootstrap.php';
        print INCLUDE_DIR;
        ");
        fclose($pipes[0]);
        $INCLUDE_DIR = fread($pipes[1], 8192);
        proc_close($php);
        return $location = rtrim($INCLUDE_DIR, '/').'/';
    }
```

**Comment by JediKev** [comment]
@dmnc-net I have fixed this issue with this pull request: https://github.com/osTicket/osTicket/pull/4101

Please make the changes, test, and get back to me. Cheers.

**Comment by dmnc-net** [comment]
No issues with fresh pull (e4cb4e9), thanks.
