### ISSUE TITLE
PHP 7.x

### ISSUE THREAD

**Issue by omexXx** [osTicket/osTicket#3743]
Hello,

Does the lastest release support php 7.x ?

**Comment by ntozier** [comment]
The latest release (1.10) supports 7.0.x.  7.1 is right out.
And I've heard people saying that you should install 1.9.15 first and then uppgrade to 1..10 if you plan on running PHP7.

**Comment by rayfoss** [comment]
Install on PHP 5.6 then upgrade to PHP 7 if you must, the installer of 1.10 has issues with 7.0 that have been addressed for the next release.
