### ISSUE TITLE
Only allow ticket creation from users which are in the database/directory

### ISSUE THREAD

**Issue by firepro20** [osTicket/osTicket#3746]
Is there a way to do this please?

**Comment by ntozier** [comment]
Require login to create tickets?

**Comment by firepro20** [comment]
I need to allow creation of  tickets from web interface only by users who
are already listed in user database.

**Comment by ntozier** [comment]
Precisely.  If they are in the DB then they are Users.  Requiring them to login means that they exist in the DB, and cannot create tickets with out logging in..

**Comment by firepro20** [comment]
Logging in is disabled. If I enable it, will they all need to set a
password?

**Comment by ntozier** [comment]
Yes. 

Or you could set a password for them ahead of time.  You should be able to achieve this with a pretty simply SQL query to set it to something like 'L3tmein!' and make them change it.  Or it you run LDAP you could install the Authentication::LDAP/AD plugin and have them auth against that.
