### ISSUE TITLE
Search ticket module problem.

### ISSUE THREAD

**Issue by Supakarn** [osTicket/osTicket#3747]
Hello,
I  have the problem with search module on iOS.
**Steps -**  type the word in search column and enter the search icon on ticket page, 
it seems like the system doesn't show the result. it still the same page and the URL doesn't change the value.

This problem occurs on Safari (iOS version 10.2.1) , Google Chrome - version 57.0.2987.100 on iOS
For android, it's working normally on Google Chrome and default web browser. 
#osTicket versions 1.10-rc.2  Any thoughts on this? Is it not supported on iOS or bug code.

**Comment by ntozier** [comment]
"osTicket versions 1.10-rc.2"
Please:
Upgrade to stable.  
Test again.

No one should still be running rc2.  Especially not in a production environment.

**Comment by ashembel** [comment]
I'm on 1.10 latest release and have the same issue, on Client side search, only complete ticket string is searchable. 

Subject line or any custom form fields are not searchable.
