### ISSUE TITLE
Time is based on your time zone (GMT )

### ISSUE THREAD

**Issue by rayfoss** [osTicket/osTicket#3751]
![screenshot from 2017-03-16 09-48-06](https://cloud.githubusercontent.com/assets/876076/24005603/76ad60b0-0a37-11e7-9165-c383a8c2803c.png)

My timezone is not GMT... seems hard coded or broken.

**Comment by elambro** [comment]
I have the same problem. It shows GMT and all of the dates are 1 hour off in domain.com/scp/settings.php?t=system. php.ini and server time are correct.

**Comment by BitKFu** [comment]
same for me. seems to be broken. I guess it's maybe because of the PHP 7 ...
