### ISSUE TITLE
Advanced Search (between) date range issue in version 1.10

### ISSUE THREAD

**Issue by kekaru** [osTicket/osTicket#3752]
Hi,
There's an issue with regards on date range selection. Whenever I select dates under 'Last Response' with 'between' method, the date range values always shows up on 'Created Date' range fields. Same with 'Last message' with 'between' method. 

Thanks.

**Comment by ntozier** [comment]
Maybe a screen shot of where and what you are talking about?
Maybe some system environment details?

**Comment by kekaru** [comment]
Screenshots below:
![image](https://cloud.githubusercontent.com/assets/26477153/24069125/598b0690-0bdb-11e7-8df4-eca888b06d64.png)
In 'Last Response', I chose 2017-3-25 but the value shows up under 'Created Date'
![image](https://cloud.githubusercontent.com/assets/26477153/24069157/0e3d6b1e-0bdc-11e7-977f-bd4510676d1c.png)

As for the system details:
![image](https://cloud.githubusercontent.com/assets/26477153/24069191/e3e38866-0bdc-11e7-8271-468f01c74009.png)

Thank you,
