### ISSUE TITLE
Errors When Adding New Task

### ISSUE THREAD

**Issue by jwogrady** [osTicket/osTicket#3753]
### Prerequisites

* [ y] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ y] Do you have any errors in the PHP error log, or javascript console?
* [ y] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [ y] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

`create new task` button in task view renders a blank box.  Browser console throws an error.

```https://MY-SITE.com/scp/ajax.php/tasks/add?_uid=1489734456068 Failed to load resource: the server responded with a status of 500 (Internal Server Error)```

### Steps to Reproduce

1. login is agent
2. nav to task view
3. click new task button

**Expected behavior:** [What you expected to happen]

Expected an input form.

**Actual behavior:** [What actually happened]

Got a empty white box.

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.

```
osTicket Version	v1.10-47-gb9f0937 (b9f0937) —  Up to date
Web Server Software	Apache/2.4.10 (Debian)
MySQL Version	10.1.22
PHP Version	5.6.30-0+deb8u1
```

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

OSX with Chrome Version 56.0.2924.87 (64-bit)

**Comment by JediKev** [comment]
I've tried to reproduce this on my environment (Apache 2.4, CentOS 7, PHP 5.4, MariaDB 15.1, osT 1.10) and the form shows like it's supposed to. I have a hunch it's ajax being crazy. Can you take a screenshot of **Admin Panel > Dashboard > Information** for me? Specifically the **PHP Settings** section.

**Comment by jwogrady** [comment]
Thanks for taking a look.

For what it is worth, had the same issue on an earlier NGINX build.  Figured it was related to the a bad location setting... so I moved to Apache since that is what is officially support.  Got the same exact same result.   Tried to rule out browser issues too, but got same error in Chrome, Firefox and  Safari.

![screen shot 2017-03-17 at 9 22 11 am](https://cloud.githubusercontent.com/assets/2075310/24047435/b127ff0e-0af3-11e7-96b2-fe448716e7d4.png)

**Comment by JediKev** [comment]
Can you confirm that the form exists under **Admin Panel > Manage > Forms > Task Details**?

**Comment by jwogrady** [comment]
Here is what I got.

![screen shot 2017-03-17 at 9 47 16 am](https://cloud.githubusercontent.com/assets/2075310/24048427/de3a30c2-0af6-11e7-8584-0bff66d9d356.png)
![screen shot 2017-03-17 at 9 47 36 am](https://cloud.githubusercontent.com/assets/2075310/24048432/dfb7c9d2-0af6-11e7-9bdc-ce1d73696c35.png)

**Comment by JediKev** [comment]
Ok, strange...Can you look into your osTicket Error Log, PHP Error Log or Apache Error Log and see if there is any more info on this error?

**Comment by jwogrady** [comment]
Here is the Apache2 access log.

```
[17/Mar/2017:09:54:03 -0500] "GET /scp/autocron.php HTTP/1.1" 200 352 "https://MY-SITE.com/scp/index.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36"
[17/Mar/2017:09:54:29 -0500] "GET /scp/tasks.php?_pjax=%23pjax-container HTTP/1.1" 200 3329 "https://MY-SITE.com/scp/index.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36"
[17/Mar/2017:09:55:04 -0500] "GET /scp/ajax.php/tasks/add?_uid=1489762502495 HTTP/1.1" 500 676 "https://MY-SITE.com/scp/tasks.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36"
```
error log
```[Fri Mar 17 09:55:04.351071 2017] [:error] [pid 14624] [client MY-IP:MY-PORT] FastCGI: server "/usr/lib/cgi-bin/php5-fcgi" stderr: PHP message: PHP Parse error:  syntax error, unexpected ';' in /PATH-TO-MY-INSTALL/osticket/include/ajax.tasks.php on line 692, referer: https://MY-SITE/scp/tasks.php```

**Comment by jwogrady** [comment]
This appears to have resolved the issue.
https://github.com/osTicket/osTicket/pull/3755

**Comment by JediKev** [comment]
So you pulled those changes and it's now working for you?

**Comment by jwogrady** [comment]
Yep, solution was merged early this morning. What are the odds? Thanks for your help.
![screen shot 2017-03-17 at 12 21 54 pm](https://cloud.githubusercontent.com/assets/2075310/24055062/a263480c-0b0c-11e7-8a92-760159b391e6.png)
