### ISSUE TITLE
How to display only private topics in open.php?

### ISSUE THREAD

**Issue by lhpmonkey** [osTicket/osTicket#3758]
Hi, I have two directories, one for external users and one for internal users. In the directory of the internal users I want to modify class.topic.php to display only private topics, because in the directory of the external users I'll use the public topics, btw the two directories use the same database, the difference is that in the internal, the open.php should display the private topics and in the external should display the public topics. (http://mysupport.com/open.php and http://mysupport.com/internal/open.php)

Now, how I can make this change or wich code to insert in class.topic.php to do this?

I'm using osTicket 1.10

Thank you

**Comment by ntozier** [comment]
This does not appear to be an issue report.
