### ISSUE TITLE
Pull Request Activity

### ISSUE THREAD

**Issue by roman-1983** [osTicket/osTicket#3759]
Please take a look at the PRs - there are a lot of very old PRs, some are from 2013 and 2014. :-(

Merge or close them, please.

**Comment by ntozier** [comment]
This is not a valid issue report.  Please close it.

**Comment by roman-1983** [comment]
Okay - where can we discuss about the PR activity?
I thinks this is an issue - because it makes the impression, that OsTicket is not well maintained and so it does not make sense to send more PRs.

**Comment by rayfoss** [comment]
@roman-1983 We're open to suggestions...

**Comment by roman-1983** [comment]
How about a "merge month" to merge and close all the open pull requests.
I started to review some changes and approve or decline them. Maybe this is a help?

**Comment by Chefkeks** [comment]
I also think that either once a month or once every quarter or at any other time range you guys prefer there should be a review of the open PRs and then there shall be a decision whether they will be merged, declined or added into a review queue by adding some label or assigning a milestone to them. It'd help the community and you too (at least I hope so).

Besides, I guess a lot folks doing PRs have not yet understand how to make PRs right and so there are several PRs with thousands of added, removed or changed lines, but actually it's only e.g. 12 lines that got added/removed/changed.

> "Upstream, Upstream, Upstream!"
