### ISSUE TITLE
osticket install problems - Blank Install Page

### ISSUE THREAD

**Issue by groundhog59** [osTicket/osTicket#3760]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [ ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description
ok so I uploaded all the files to my directory osticket, then I type the address in my web browser and instead of the Install page I get this blank page !  http://www.fgmworld.com/osticket/setup/
Any ideas how to fix this ?
[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

**Comment by ntozier** [comment]
This does not appear to be a bug report.  I would invite you to visit the forums and post your question there.  A white page indicates a PHP error, you should consult your PHP error log.   Please help us to help you by reading and following the posting guidelines located in this thread: [Please read before requesting assistance.](http://www.osticket.com/forum/discussion/77765/please-read-before-requesting-assistance)  The more information you give us the better we will be able to assist you. Thank you.
