### ISSUE TITLE
Stored Cross-Site Scripting using Inline Attachment

### ISSUE THREAD

**Issue by ajdumanhug** [osTicket/osTicket#3764]
### Prerequisites

* [Y] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [N] Do you have any errors in the PHP error log, or javascript console?
* [Y] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [Y] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

I found a stored XSS vulnerability using inline attachment.

### Steps to Reproduce

1. Create a Ticket
2. Under Issue Summary, upload a malicious SVG File ([File](https://drive.google.com/file/d/0B9reBRXrbKwAeHpKQ2RfQnF3TXM/view?usp=sharing))
3. Submit the Ticket
4. View the Ticket and Find the Attached SVG File
5. Right click and click "Open image in new tab".
6. The Payload will now pop up and it will redirect you to my website.

**Screenshot**
![xssstored](https://cloud.githubusercontent.com/assets/9420289/24340775/4526c1a4-12e7-11e7-8718-4cb70e789fa7.png)

**Expected behavior:**
OSTicket should not allow SVG file to execute under the domain who uses OSTicket or files like SVG should be downloaded and not executed in the browser.

**Actual behavior:**
OSTicket allows execution of SVG Files under the website of the target who uses OSTicket.

### Versions
v1.10

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.
NOT RELATED / NEEDED

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.
Windows 10 / Chrome Latest Version

**Comment by VanBreuk** [comment]
We're reproducing this on our v1.10 setup after a security researcher contacted us about the problem. Currently the only solution to prevent redirects and other problems for users/agents logged in to the system seems to be disabling attachments.

Is there a fix available?
