### ISSUE TITLE
CSV Injection 

### ISSUE THREAD

**Issue by ajdumanhug** [osTicket/osTicket#3767]
### Prerequisites

* [Y] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [N] Do you have any errors in the PHP error log, or javascript console?
* [Y] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [Y] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

OSTicket allows users to export tickets but I created a ticket with malicious payload that once exported and executed in Desktop, it will run a command to open Calculator.

### Steps to Reproduce

1. Create a ticket with this title: ```=cmd|' /C calc'!A0```
2. Go to Tickets and Click Export
3. Open the CSV File and it will ask you to enable something and it will run CMD to open Calculator.

**ScreenShot**
![csv](https://cloud.githubusercontent.com/assets/9420289/24342564/3b5a6150-12f4-11e7-8dfa-68deac3db9b9.png)

**Expected behavior:**
Nothing will execute

**Actual behavior:**
Command is Executed to run CMD and Open Calculator.

### Versions
v1.10

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.
Windows 10 / Latest Version of Chrome

**Comment by ntozier** [comment]
CSV means Comma Separated Values. This is a **plain text file format** that does not support formulas or macros.  If you want to use those things you will either have to change to the .xls or .xlsx formats.

This appears to have nothing to so with osTicket.  Please close this.

**Comment by ajdumanhug** [comment]
Hi @ntozier,

Agree but with this vulnerability, If someone created a ticket with that kind of Subject and the admin exported the ticket to his/her desktop, it could execute malicious scripts or do something bad with the admin's desktop.

Also, you don't have to change the file extension of the exported file. Once you have a Microsoft Excel, just open the file and it will execute the script or command.

I'll close this issue as you requested.
