### ISSUE TITLE
Unable to create tasks

### ISSUE THREAD

**Issue by wooknight** [osTicket/osTicket#3769]
### Prerequisites

no errors in php or jsconsole log

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

I am unable to create tasks . Priority is mandatory for tasks and I cannot select priority from the dropdown because it is empty . This is very consistent . I installed OsTicket very recently so no updates ,I am running osTicket (v1.10) on Centos 7 . Using Firefox 52.0 (64-bit) on a MAC OS  Sierra

![screen shot 2017-03-27 at 5 20 57 pm](https://cloud.githubusercontent.com/assets/973745/24383462/dd2042ee-1311-11e7-8087-dc7617e0cb83.png)

**Comment by ntozier** [comment]
Tasks do not have a Priority field... So you added this yourself?

**Comment by wooknight** [comment]
No , I don't believe so . This is what my tasks setup screen looks like 

![screen shot 2017-03-28 at 9 38 59 am](https://cloud.githubusercontent.com/assets/973745/24416679/794c5878-139a-11e7-88aa-08094e06a3a4.png)

**Comment by wooknight** [comment]
ok , one of our designers set that up . My apologies!!!!
