### ISSUE TITLE
OS Ticket 1.10 Custom Logo and Print issues

### ISSUE THREAD

**Issue by whacky98** [osTicket/osTicket#3770]
The issue I am seeing is 2 things the customer logo when we go to print will just display a red x yet I can switch to the default logo it will display and print fine.  I have tried to save the default logo and set it as the custom logo to ensure it is not my logo and same results.  Also since version 1.10 when I try to print it used to in old version just open and print now it brings up a open or save window in any browser.  I can click open and it does open the only issue I have with this is it saves a copy of the pdf everytime I print a ticket which later I will have to go clear out over time.

**Comment by clonemeagain** [comment]
It's actually a PHP issue with mPDF.. likely the oldness of the version means they won't want to fix it.  But there is a patch in the referenced plugin if you're keen.
