### ISSUE TITLE
Add/EDIT User/Company - failed 

### ISSUE THREAD

**Issue by svenerbeck** [osTicket/osTicket#3771]
/upload/login.php
Agent login works like charme.  Thank you.  

The client login is not working. It is not possible to add a company / user / username. 
The fields to name are not there or not clickable.  If user is added it is not editable and the name in the system is [1]   -  (take a look at my screenshots).

Asking myself it it is a installation bug on my side or a missconfiguration?   
(EDIT: Translated my system with offical de lang. packet)

Thanks for the help  

Greetz  
Sven  

![bildschirmfoto 2017-03-30 um 08 07 23](https://cloud.githubusercontent.com/assets/12124066/24489879/22582b78-1520-11e7-8fed-0d125bd97804.png)
![bildschirmfoto 2017-03-30 um 08 07 14](https://cloud.githubusercontent.com/assets/12124066/24489881/225993c8-1520-11e7-8cd7-93f11b961375.png)
![bildschirmfoto 2017-03-30 um 08 07 06](https://cloud.githubusercontent.com/assets/12124066/24489880/2258f4d6-1520-11e7-8bad-6af6c84062dc.png)
![bildschirmfoto 2017-03-30 um 08 06 53](https://cloud.githubusercontent.com/assets/12124066/24489882/225dd9e2-1520-11e7-8719-149bc7c0ddb8.png)

**Comment by svenerbeck** [comment]
got it - has to be activated. 
thank you for this great tool 
(CLOSED)

**Comment by tejastank** [comment]
Hi...

I did not got, Face same issue. how to fix ?

Steps ?
