### ISSUE TITLE
How to re-assign ticket?

### ISSUE THREAD

**Issue by jdvillaluz** [osTicket/osTicket#3778]
The scenario is I accidentally assigned the ticket with the wrong people and I wanted to re assign the ticket? Im newbie here. Thanks guys! 

### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [ ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

**Comment by ntozier** [comment]
This does not appear to be an issue report.   This appears to be a how to configure and use the product type of question.  Please visit the forums for support issues that are not related to reproducible bugs.

That being said if you cannot see the ticket anymore you cannot re-assign it. You need to be able to have access to a ticket to assign it to someone/department.

**Comment by iHunt101** [comment]
Hi @jdvillaluz , you must go to ticket and click on it. Find the edit icon at the upper right. Click and select if you want to assign to and agent or to another team.
![ass](https://user-images.githubusercontent.com/16589622/27938369-3e4562ec-62f0-11e7-8b34-33286519fb6a.jpg)
