### ISSUE TITLE
An empty line after closing tag in ost-config.php causes all image to be corrupt

### ISSUE THREAD

**Issue by AlexeyDemidov** [osTicket/osTicket#3779]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [N] Do you have any errors in the PHP error log, or javascript console?
* [Y] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [Y] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

Having an empty line after closing php ?> tag in include/ost-config.php causes all images to be corrupt as '0x0A' byte is added at the beginning of every image.

### Steps to Reproduce

Fresh install of v1.10, modify ost-ticket.php manually to add an empty line at the end.

### Versions

OS Debian 8.7 jessie.

Server Information
osTicket Version	v1.10 (901e5ea) —  Up to date
Web Server Software	Apache
MySQL Version	5.5.54
PHP Version	5.6.30-0+deb8u1
PHP Extensions
gdlib	 Used for image manipulation and PDF printing
imap	 Used for email fetching
xml	 XML API
xml-dom	 Used for HTML email processing
json	 Improves performance creating and processing JSON
mbstring	 Highly recommended for non western european language content
phar	 Highly recommended for plugins and language packs
intl	 Highly recommended for non western european language content
fileinfo	 Used to detect file types for uploads
APCu	 Improves overall performance
Zend Opcache	 Improves overall performance
PHP Settings
cgi.fix_pathinfo	 "1" is recommended if AJAX is not working
date.timezone	 GMT
Database Information and Usage
Schema	ost_rebsoc (mysql)
Schema Signature	98ad7d550c26ac44340350912296e673
Space Used	2.34 MiB
Space for Attachments	0.02 MiB
Timezone	MSK (Interpreted as Europe/Moscow)

**Comment by ntozier** [comment]
So let me see if I get this right... you modified the code and it is causing you issues.  Why are you reporting this?

**Comment by AlexeyDemidov** [comment]
This installation was moved to the different server and configuration file was updated by hand. So, let me see if I get this right... Your configuration files aren't supposed to be modified?

**Comment by ntozier** [comment]
Q: So, let me see if I get this right... Your configuration files aren't supposed to be modified?
A: No. You can modify ost-config.php all you want as long as you remember that they are PHP files.

So what you left out is that this is a server migration.  It seems to me that perhaps you should be starting a thread on the forums.  I editted my files and now have two blank lines after my closing ?> in my ost-config.php and I cannot replicate your issue report.
