### ISSUE TITLE
[REQ] Canned response ability to change ticket status

### ISSUE THREAD

**Issue by 2ge** [osTicket/osTicket#3780]
Hi

thanks for this great software, really helps. I am using a lot of canned responses, and it would be nice, if it could change the ticket status, so for example within canned response template I could insert

`%{ticket.action.status.close}`

so it ticket will change to close. Next addition would be immediately simulating "Post Reply" button, for example 

`%{ticket.action.submit.ok}`

also I dont want to add any notes, so it could be disabled by

`%{ticket.action.notedialog.false}`

Maybe one day....thanks!

**Comment by ntozier** [comment]
Thank you for the request.

**Comment by mlipok** [comment]
https://github.com/osTicket/osTicket/issues/1749
