### ISSUE TITLE
OSTicket is still using wintertime

### ISSUE THREAD

**Issue by scroom** [osTicket/osTicket#3781]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [x] Do you have any errors in the PHP error log, or javascript console? -> No
* [x] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

As described above. I'm in the CEST-timezone (Europe/Berlin) which I've configured in OSticket as well. But the ticket-time is an hour late. (07:40 instead of 08:40 for example). timedatectl shows me that the OS is configured correct as well:

`Local time: Do 2017-04-06 08:36:50 CEST
  Universal time: Do 2017-04-06 06:36:50 UTC
        RTC time: n/a
       Time zone: Europe/Berlin (CEST, +0200)
 Network time on: yes
NTP synchronized: yes
 RTC in local TZ: no
`

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

OSTicket 1.10
PHP 7.0.15-0ubuntu0.16.04.4 (cli)
Ubuntu 16.04 LTS
Apache2

**Comment by ntozier** [comment]
This appears to be a duplicate issue report.
Please see the like 6 other timezone issues here on git hub or the numerous ones on the forums.
