### ISSUE TITLE
Empty overlay on printing tasks

### ISSUE THREAD

**Issue by AbraCadabra007** [osTicket/osTicket#3782]
I can't print task. Clicking in Print icon on single Task page an empty overlay appears and lock status. Pushing ESC overlay disappears but I can't print.

osTicket 1.10 develop version also tested, same problem.
Apache & nginx
PHP 5.6.30

**Comment by randman1** [comment]
I am seeing the same issue but found a temporary workaround by right clicking the Print icon and selecting Open Link in New Tab (Firefox) or Open in new tab (IE).

osTicket Version 	v1.10 (901e5ea) — Up to date
Web Server Software 	Apache/2.4.18 (Ubuntu)
MySQL Version 	5.7.18
PHP Version 	7.0.18-0ubuntu0.16.04.1

After clicking on the Print icon, the overlay appears and "Loading" briefly flashes before displaying a small white dialog. This behavior is seen using Firefox 49.0.2 and IE 11. Logs show no errors.

**Comment by JediKev** [comment]
I have submitted a pull request (#3909) that should fix this issue. Please pull the changes, test, and let me know if it solves your issue! Thanks.
