### ISSUE TITLE
system dont show all image

### ISSUE THREAD

**Issue by dmartinezve** [osTicket/osTicket#3784]
The osticket was very slow when opening the tickets, some did not load completely and did not show the form to respond, a task was performed to optimize the tables of mysql with the command optimize and now no image is displayed even the logo principal

![image](https://cloud.githubusercontent.com/assets/27121398/24834926/7b9292a8-1cc0-11e7-9488-5945f969324e.png)

![image](https://cloud.githubusercontent.com/assets/27121398/24834938/e3ad0026-1cc0-11e7-9ea7-f6a485142483.png)

But if we read the direct file from the ost_file_chunk table the image can be displayed, 
![image](https://cloud.githubusercontent.com/assets/27121398/24835015/79ff0054-1cc3-11e7-932e-ef30bee32c34.png)

this table has more than 3million records

![image](https://cloud.githubusercontent.com/assets/27121398/24834947/5b20bc56-1cc1-11e7-886b-7a490405da7b.png)

If an email is sent the system receives it and processes and loads the attachment but they are not visualized inside the text of the message, and when trying to open the attachment is not visualized either

![image](https://cloud.githubusercontent.com/assets/27121398/24834961/c67a57f0-1cc1-11e7-811b-1dfc4d3fca8b.png)

system configurations 
![image](https://cloud.githubusercontent.com/assets/27121398/24834972/101e99f2-1cc2-11e7-82de-b6fee4090dcd.png)

![image](https://cloud.githubusercontent.com/assets/27121398/24835052/16954694-1cc4-11e7-867b-e27be75ce921.png)

**Comment by blueyeguy** [comment]
You should update your installation. 1.9.6 is very old, and it's likely you won't get much traction on this until you are at least using the most current in the 1.9 branch, which is 1.9.15

**Comment by 4nanook** [comment]
1.10 does not work properly for me with PHP7 either.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by blueyeguy** [comment]
Your installation doesn't say you have PHP 7, and I didn't say anything about upgrading all the way to 1.10, but if you go to 1.10, I would recommend staying with PHP 5.6

**Comment by ntozier** [comment]
So 1.9.6 does not support PHP 7. But then you are not using PHP7 according to your own screen shot.  You are running 5.5.  So I guess I dont understand why you say that it doesn't run under PHP7 when you aren't even running it.

So my primary site has about 10k tickets and does not even come close to 1% of your 3 million records in that table.  According to your screen shots you have an average of 466 images per ticket in your ticket system.  I'd say that is probably the issue.

**Comment by dmartinezve** [comment]
hi my table ticket has 36k tickets average 83 images file per ticket and my threads table 755k average per ticket 21 message per ticket, but 15 days before was normal

![image](https://cloud.githubusercontent.com/assets/27121398/24867222/863a633c-1dda-11e7-829f-aa2aa665ddd8.png)

why its crash now? what warranty i have that migrate to new version is solution? dont exist any test check that i can doit before for know problem?

one simple message have one sign mail of user with image logo factory more 3 social networks logo more image attachment, and threads average 21 * 5 = 105 image per ticket, now query into database is very fast dont is problem

but dont views nothing images?

exist any hashcode or key i need for view images, that for any rason is lost?

**Comment by mlipok** [comment]
For warranty You should try to migrate on separate server using them just for test.

**Comment by iHunt101** [comment]
Hi @dmartinezve you should work on a dev environment server to dev & test. @mlipok was right. Do it from separate server. Install latest & statble version of osTicket. Then put all the custom fields or something like that of what you have on your current server. Export your tickets db and import to dev and observe. But i may suggest you shuold work it from the start to make sure it works fine. Also are dont forget to update atleast v5.6 of PHP.
