### ISSUE TITLE
Add Filter without Rules, Generates DB Error

### ISSUE THREAD

**Issue by sjlevy** [osTicket/osTicket#3790]
**Version**

osTicket Version - v1.10 (901e5ea)
Web Server Software - Microsoft-IIS/8.5
MySQL Version - 5.6.15
PHP Version - 5.6.30

**Steps to Reproduce**

1. Go to Manage / Ticket Filters / Add New Filter

2. Enter a Filter Name / Filter Order / Select Any for Target Channel

3. Click 'Add Filter'

4. Refer to Dashboard / System Error Logs

Results in this DB Error:

```
DB Error #1062

[INSERT INTO ost_filter_rule SET created=NOW(),  filter_id=5,  updated=NOW() , what='', how='', val='', isactive=1] Duplicate entry '5---' for key 'filter'

 ---- Backtrace ----
 #0 C:\inetpub\wwwroot\osticket\include\mysqli.php(204): osTicket->logDBError('DB Error #1062',  '[INSERT INTO os...')
 #1 C:\inetpub\wwwroot\osticket\include\class.filter.php(668): db_query('INSERT INTO ost...')
 #2 C:\inetpub\wwwroot\osticket\include\class.filter.php(641): FilterRule::save(0,  Array,  Array)
 #3 C:\inetpub\wwwroot\osticket\include\class.filter.php(452): FilterRule::create(Array,  Array)
 #4 C:\inetpub\wwwroot\osticket\include\class.filter.php(515): Filter::save_rules(5,  Array,  Array)
 #5 C:\inetpub\wwwroot\osticket\include\class.filter.php(373): Filter::save(0,  Array,  Array)
 #6 C:\inetpub\wwwroot\osticket\scp\filters.php(42): Filter::create(Array,  Array)
 #7 {main}
```

**Comment by blueyeguy** [comment]
What would be the point of adding a filter that has no rules and doesn't do anything?

**Comment by ntozier** [comment]
I was wondering the same thing... but opted to ignore the madness. :)

**Comment by sjlevy** [comment]
Shouldn't it return a friendly validation error message and fail gracefully instead?

Also for example you may simply need to filter based on a Target Channel and not need Rules (only Actions)

**Comment by ntozier** [comment]
I would say it should.
