### ISSUE TITLE
Custom Form > Choices

### ISSUE THREAD

**Issue by deathtoall** [osTicket/osTicket#3792]
Hi,

i am using OSTicket v1.10 (901e5ea), Apache/2.4.25.

i created a custom form with type>choices. how do i make a specific word not clickable? and change the font to BOLD? 

![image](https://cloud.githubusercontent.com/assets/27323760/24938630/f693c6fa-1f6a-11e7-8f27-19d0a3564664.png)

i dont have option in admin panel to change.

![image](https://cloud.githubusercontent.com/assets/27323760/24939050/5be16a24-1f6d-11e7-88a9-4d1c35d1c406.png)

please help.

**Comment by blueyeguy** [comment]
This doesn't look like a bug report, I would suggest asking this question in the forums
http://osticket.com/forum/

Before doing so, please help us to help you by reading and following the posting guidelines located in this thread:  http://www.osticket.com/forum/discussion/77765/please-read-before-requesting-assistance#latest

The more information you give us the better we will be able to assist you. Thank you.

**Comment by ntozier** [comment]
Also you cannot make one item on a choices list bold. This is not a feature in osTicket.
