### ISSUE TITLE
Not receiving email notifications

### ISSUE THREAD

**Issue by alfie013** [osTicket/osTicket#3793]
Hello Guys,

When the ticket is assigned to Agent and Team, only the assigned Agent received the updates from the requester. Can you guys help me to make the assigned Team receive also the updates?

Here is a sample scenario:

Ticket #12345 is assigned to Me and to my Team

Update from OsTicket to Client: I'm not getting any notification from OsTicket when an update is sent to the client. The rest of my Team got the update.
Update from Client to OsTicket: When the client replies to the ticket, only me (as assigned agent) receives the update notification. Team members never get notified. 

**osTicket Info:**

**Server Information**
osTicket Version --------------> v1.10 (901e5ea) —  Up to date
Web Server Software ---------> Microsoft-IIS/8.5
MySQL Version ---------------> 5.7.17
PHP Version ------------------> 7.0.15

**Ticket Alerts Settings:** 
	New Message Alert
		Assigned Agent/Team = Active
	New Internal Activity Aler
		Assigned Agent/Team = Active

Thank you,

**Comment by alfie013** [comment]
Hi,

Can you help me on this??

Thank you,
Alfie

**Comment by ntozier** [comment]
Try downgrading to PHP 5.6?

Do you have them enabled? (please provide a screen shot of Admin panel -> Settings -> Tickets -> Autoresponder.)  Please make sure that you do not have these notices suppressed at the department or email level.

How are you sending email?  PHPMailer?  SMTP?

**Comment by alfie013** [comment]
Hello @ntozier,

Here is the screen shot of Autoresponder. 

![test 12](https://cloud.githubusercontent.com/assets/25225267/25158604/a61e101a-245e-11e7-94c9-7687e8418e7c.png)

Yes, we are using SMTP. 

Thank you,

**Comment by alfie013** [comment]
@ntozier,

Any updates on this? Can you help me fix this?

Looking forward to your response.

Thank you,

**Comment by ntozier** [comment]
Did you downgrade to PHP 5.6?
Have you consulted your Mailserver logs?

**Comment by alfie013** [comment]
Hello @ntozier,

I have successfully fixed my problem by editing the codes on class.ticket.php file. 

Thank you,

**Comment by ntozier** [comment]
Can you post what you edited?

**Comment by kajla** [comment]
It doesn't work for me either.
Can you post what you edited?

Thank you.
