### ISSUE TITLE
Issue with number of queries pending in MYSQL

### ISSUE THREAD

**Issue by jighem** [osTicket/osTicket#3797]
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

[Description of the bug or feature]

### Steps to Reproduce
Our team responded slow ticket on some event when observed processlist, at that time we observed many queries from ticket users are in the queue once that is cleared it starts functioning properly 
can anyone help me with the same?
### Versions

| 21748 | suppticket   | Milward.securehostdns.com:55038 | spinetech_supptick |
Query   |   43 | Waiting for table level lock | REPLACE INTO ost__search SET obj
ect_type='H', object_id=76016, content='Dear Team, Is it possible to |
| 21783 | suppticket   | Milward.securehostdns.com:55074 | spinetech_supptick |
Query   |   58 | Copying to tmp table         | SELECT COUNT(*) FROM (SELECT A1.
`ticket_id`, null AS number, COUNT(DISTINCT A1.`ticket_id`) AS `tick |
| 21784 | suppticket   | Milward.securehostdns.com:55075 | spinetech_supptick |
Query   |   58 | Copying to tmp table         | SELECT COUNT(*) FROM (SELECT A1.
`ticket_id`, null AS number, COUNT(DISTINCT A1.`ticket_id`) AS `tick |
| 21785 | suppticket   | Milward.securehostdns.com:55076 | spinetech_supptick |
Query   |   56 | Copying to tmp table         | SELECT COUNT(*) FROM (SELECT A1.
`ticket_id`, null AS number, COUNT(DISTINCT A1.`ticket_id`) AS `tick |
| 21788 | suppticket   | Milward.securehostdns.com:55080 | spinetech_supptick |
Query   |   53 | Copying to tmp table         | SELECT COUNT(*) FROM (SELECT A1.
`ticket_id`, null AS number, COUNT(DISTINCT A1.`ticket_id`) AS `tick |
| 21790 | suppticket   | Milward.securehostdns.com:55082 | spinetech_supptick |
Query   |   50 | Waiting for table level lock | REPLACE INTO ost__search SET obj
ect_type='T', object_id=24584, content='SpineHR\nNo_Module_Selected\ |
| 21800 | suppticket   | Milward.securehostdns.com:55092 | spinetech_supptick |
Query   |   46 | Waiting for table level lock | SELECT COUNT(*) FROM (SELECT A1.
`ticket_id`, null AS number, COUNT(DISTINCT A1.`ticket_id`) AS `tick |
| 21801 | suppticket   | Milward.securehostdns.com:55093 | spinetech_supptick |
Query   |   45 | Waiting for table level lock | SELECT COUNT(*) FROM (SELECT A1.
`ticket_id`, null AS number, COUNT(DISTINCT A1.`ticket_id`) AS `tick |
| 21802 | suppticket   | Milward.securehostdns.com:55094 | spinetech_supptick |
Query   |   45 | Waiting for table level lock | SELECT COUNT(*) FROM (SELECT A1.
`ticket_id`, null AS number, COUNT(DISTINCT A1.`ticket_id`) AS `tick |
| 21804 | suppticket   | Milward.securehostdns.com:55096 | spinetech_supptick |
Query   |   43 | Waiting for table level lock | SELECT COUNT(*) FROM (SELECT A1.
`ticket_id`, null AS number, COUNT(DISTINCT A1.`ticket_id`) AS `tick |
| 21805 | suppticket   | Milward.securehostdns.com:55097 | spinetech_supptick |
Query   |   43 | Waiting for table level lock | SELECT COUNT(*) FROM (SELECT A1.
`ticket_id`, null AS number, COUNT(DISTINCT A1.`ticket_id`) AS `tick |
| 21807 | suppticket   | Milward.securehostdns.com:55099 | spinetech_supptick |
Query   |   41 | Waiting for table level lock | SELECT COUNT(*) FROM (SELECT A1.
`ticket_id`, null AS number, COUNT(DISTINCT A1.`ticket_id`) AS `tick |
| 21808 | suppticket   | Milward.securehostdns.com:55100 | spinetech_supptick |
Query   |   41 | Waiting for table level lock | SELECT COUNT(*) FROM (SELECT A1.
`ticket_id`, null AS number, COUNT(DISTINCT A1.`ticket_id`) AS `tick |
| 21809 | suppticket   | Milward.securehostdns.com:55101 | spinetech_supptick |
Query   |   40 | Waiting for table level lock | SELECT COUNT(*) FROM (SELECT A1.
`ticket_id`, null AS number, COUNT(DISTINCT A1.`ticket_id`) AS `tick |
| 21810 | suppticket   | Milward.securehostdns.com:55102 | spinetech_supptick |
Query   |   40 | Waiting for table level lock | SELECT COUNT(*) FROM (SELECT A1.
`ticket_id`, null AS number, COUNT(DISTINCT A1.`ticket_id`) AS `tick |
| 21811 | suppticket   | Milward.securehostdns.com:55103 | spinetech_supptick |
Query   |   39 | Waiting for table level lock | SELECT COUNT(*) FROM (SELECT A1.
`ticket_id`, null AS number, COUNT(DISTINCT A1.`ticket_id`) AS `tick |
| 21813 | suppticket   | Milward.securehostdns.com:55105 | spinetech_supptick |
Query   |   38 | Waiting for table level lock | SELECT COUNT(*) FROM (SELECT A1.
`ticket_id`, null AS number, COUNT(DISTINCT A1.`ticket_id`) AS `tick |
| 21814 | suppticket   | Milward.securehostdns.com:55106 | spinetech_supptick |
Query   |   38 | Waiting for table level lock | SELECT COUNT(*) FROM (SELECT A1.
`ticket_id`, null AS number, COUNT(DISTINCT A1.`ticket_id`) AS `tick |
| 21815 | suppticket   | Milward.securehostdns.com:55107 | spinetech_supptick |
Query   |   38 | Waiting for table level lock | SELECT COUNT(*) FROM (SELECT A1.
`ticket_id`, null AS number, COUNT(DISTINCT A1.`ticket_id`) AS `tick |
| 21817 | suppticket   | Milward.securehostdns.com:55109 | spinetech_supptick |
Query   |   37 | Waiting for table level lock | SELECT COUNT(*) FROM (SELECT A1.
`ticket_id`, null AS number, COUNT(DISTINCT A1.`ticket_id`) AS `tick |
| 21819 | suppticket   | Milward.securehostdns.com:55111 | spinetech_supptick |
Query   |   32 | Waiting for table level lock | SELECT COUNT(*) FROM (SELECT A1.
`ticket_id`, Z1.`relevance` AS `__relevance__` FROM `ost_ticket` A1  |
| 21821 | suppticket   | Milward.securehostdns.com:55113 | spinetech_supptick |
Query   |   30 | Waiting for table level lock | SELECT COUNT(*) FROM (SELECT A1.
`ticket_id`, Z1.`relevance` AS `__relevance__` FROM `ost_ticket` A1  |
| 21822 | suppticket   | Milward.securehostdns.com:55114 | spinetech_supptick |
Query   |   29 | Waiting for table level lock | REPLACE INTO ost__search SET obj
ect_type='H', object_id=76017, content='Mr. Peter, As per our teleco |
| 21823 | suppticket   | Milward.securehostdns.com:55115 | spinetech_supptick |
Query   |   25 | Waiting for table level lock | SELECT COUNT(*) FROM (SELECT A1.
`ticket_id`, null AS number, COUNT(DISTINCT A1.`ticket_id`) AS `tick |
| 21824 | suppticket   | Milward.securehostdns.com:55116 | spinetech_supptick |
Query   |   10 | Waiting for table level lock | SELECT COUNT(*) FROM (SELECT A1.
`ticket_id`, Z1.`relevance` AS `__relevance__` FROM `ost_ticket` A1  |
| 21826 | suppticket   | Milward.securehostdns.com:55118 | spinetech_supptick |
Query   |    8 | Waiting for table level lock | SELECT COUNT(*) FROM (SELECT A1.
`ticket_id`, Z1.`relevance` AS `__relevance__` FROM `ost_ticket` A1  |

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.
![image](https://cloud.githubusercontent.com/assets/24699194/25086246/263f3f84-2384-11e7-9c15-5fb74779bdba.png)

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.
Server os Windows server2008 r2 running apache with XAMPP and MYSQL version 5.5.38

**Comment by ntozier** [comment]
How busy is the server?
Whats the hardware specs of the server?
What else are you serving from the server and how busy are those sites?

If it were me I would ditch XAMPP and install the components myself and see if I still had the issue.

**Comment by jighem** [comment]
Server is only having OS Ticket nothing else 
4GB RAM quad Core server with windows 2008 R2
What else to be installed on server to replace XAMPP please guide me on that too so that it can be procured.
IIS dont give proper performance with PHP tried with that too.

**Comment by ntozier** [comment]
XAMPP is a 3rd party distribution of: Apache, MySQL, and PHP.  Simply install them separately with out using the third party installer and configuration(s).

**Comment by jighem** [comment]
I have observed that most of the queries are pending or waiting for obtaining table level lock 
can anyone help me how to avoid table level lock in the mysql so that I can overcome this situation.

**Comment by jighem** [comment]
Also have observed that ost__search table is the table where all queries are waiting for lock and have approx 1.2 lac of records 
What does it contain?
Can I empty the table?
Any Impact of the same if I Empty the table?

one more observation!
MySQL database is 5.5 and ost__search table is MyISAM(Engine) whereas all other tables are INNODB(Engine)
![image](https://cloud.githubusercontent.com/assets/24699194/25180702/99ef033e-252c-11e7-891d-0750ab17023f.png)
