### ISSUE TITLE
[REQ] Letsencrypt Support

### ISSUE THREAD

**Issue by webdawg** [osTicket/osTicket#3802]
Thanks for the great software.  I actually have an instance of this on supportsystem.com

Anyway we can get some by default LetsEncrypt support/acme support?

**Comment by ntozier** [comment]
What is it?

**Comment by webdawg** [comment]
https://letsencrypt.org/

Let’s Encrypt is a free, automated, and open Certificate Authority.

**Comment by ntozier** [comment]
I have added this to the list of feature requests that I keep for the devs to reference.

**Comment by webdawg** [comment]
Sounds great!

**Comment by leifnel** [comment]
There are several ways to set up lets-encrypt certificates on webservers already. 
There is no need to handle that inside each application on the webserver.
It is better managed by the hosting control panel or by the sysadmin; it doesn't matter what is in the website, just encrypt it ;-)

**Comment by realgt** [comment]
almost 3 years later theres still no Lets Encrypt support directly on supportsystem.com?

**Comment by protich** [comment]
We're planning on scheduling an upgrade in the coming weeks to finally bring LE support to SupportSystem, albeit it's a little late. 

<img width="967" alt="Screen Shot 2020-02-03 at 11 03 10 AM" src="https://user-images.githubusercontent.com/31067/73673853-fcd21b00-4674-11ea-9377-c13788db4fb4.png">

It will be rolled out to all plans, retiring custom certs systemwide.
