### ISSUE TITLE
Unable to use forum

### ISSUE THREAD

**Issue by Xymanek** [osTicket/osTicket#3803]
I know this is a bit out of place for github, but I couldn't find any other way to contact.

Some time ago (which is quite a bit now) I resisted on [osTicket forums](http://osticket.com/forum/) seeking to ask a question. Upon registration the system told me that I needed to be approved by a moderator. Fair enough. Fast forward 2 weeks, nothing changed. I'm still not able to post on forum or do anything. So I went to [contact us](http://osticket.com/contact-us) page and filled the form there. Fast forward 1-2 weeks nothing happened. I'm still unable to do anything on forums and I didn't receive any reply.

Can someone look into this? I used same username on forum (Xymanek)

**Comment by ntozier** [comment]
I show your account as awaiting email confirmation.

![xymanek](https://cloud.githubusercontent.com/assets/1315768/25236832/e4d35adc-25b6-11e7-97da-45b8b03b9560.png)

What did you put as your reason to join?  I may have rejected the application if it seems spam bot like.

I've bypassed the email verification for you but had to set your date of birth to dec 31 2016 (you might want to fix that).  

Once you verify that you can get in please close this issue report.

**Comment by Xymanek** [comment]
> What did you put as your reason to join?

I don't remember, I think something along the lines of `To ask a question about osTicket's functionality` or something similar. In any case it looks like I'm able to use the forum now. Thanks!

**Comment by ntozier** [comment]
Very welcome.  

If you get stuck feel free to PM me on the forums or email me directly at neil at osticket dot com

**Comment by Tayor-Goose** [comment]
Hello, ntozier. thats my case too. My user in forum is can_john. Please can you resend the activation email, please? It would be preferable this option for not to disturb to you. Thanks
