### ISSUE TITLE
V1.10 Date and time field and multiple choice option in ticket center is not populating correctly and transfering to email alert after upgrade from 1.19 to 1.10v 

### ISSUE THREAD

**Issue by MRSBPO** [osTicket/osTicket#3804]
### Prerequisites

* [ Not sure] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [Not sure ] Do you have any errors in the PHP error log, or javascript console?
* [Yes ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [ Yes] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

So the problem is that I set up a new ticket center. It is an upgrade from 1.19 to 1.10. I downloaded 1.10 yesterday from website. Once I upgraded everything worked fine. However in the template I have built a custom page. On the page where users are selecting a date and time to request a meeting, with a reason (multiple choice field) date comes populated as month/day/year and day is not populating correctly. It is 4 digits for the day instead two. So for example April/29/17 is displaying as April/2929/17
Also they select multiple choices and when they put the ticket in email alert comes as date always as 12/31/1969 time 7:33pm. And multiple choices come back in email alert as "Array" (instead of listing multiple choices that user have selected).
Now in the ticket itself in ticket center everything looks fine, the date and multiple choices, It is email alert only that is not transferring correctly via email. 
Now email alert worked fine before the upgrade to 1.10.
Here is how email alert looks now:

New ticket #000018 created 
From: Joe Doe 
Date requested: 12/31/1969 7:33 pm
Reason: Array
Details:
Do not close the ticket. Test. 

Again all this looks good in the ticket after the ticket is put in. But while you are populating date it doubles on day digits in the ticket center. And email alert is not transferring date and time correctly and reason. 

This is how email alert looked before the upgrade:

New ticket #000009 created 
From: Joe Doe 
Date Meeting is Requested on: 05/15/2017 3:45 am
Reason: Payroll, Transportation/Parking, Incident or Employee related Issue
Details:
I am concerned about those 3 reasons. Please help.  

### Versions
Server Information
osTicket Version	v1.10 (901e5ea) —  Up to date
Web Server Software	Apache/2.4.6 (CentOS) PHP/5.4.45
MySQL Version	5.5.52
PHP Version	5.4.45

CentOS 7 and browser version is Chrome Version 58.0.3029.81

**Comment by ntozier** [comment]
So your post leaves me with a bunch of questions, and one suggestion.

"It is an upgrade from 1.19 to 1.10. I downloaded 1.10 yesterday from website."
There is no such version as 1.19.
What website?

"However in the template I have built a custom page."
It is not possible to create a custom page in a template. So maybe some step by step instructions as to how you achieved this so we can try to replicate it would be good.

"On the page where users are selecting a date and time to request a meeting, with a reason (multiple choice field) date comes populated as month/day/year and day is not populating correctly. It is 4 digits for the day instead two. So for example April/29/17 is displaying as April/2929/17"
go to:
Admin panel -> Settings -> System.
What do you have set for Date and Time Format?

"PHP Version	5.4.45"
You should probably upgrade to 5.5 or 5.6.

**Comment by MRSBPO** [comment]
Ok so my understanding is that you want precise steps of what have I done to get to this point. I was thinking to get you a "shorter" version of the events thinking that people who are dealing with this will understand what am I talking about. However I was wrong so here is the precise (and much longer) version:
I have installed CentOS version 7 and use that as base operating system to install OSTicket center. By doing so I went to: http://osticket.com/ and click on Downloads link. There I had two choices Self Hosted or Cloud version. I picked self hosted version and click on download. There I was presented with v1.10 and v1.9.15. I picked 1.10 as I was thinking that 1.10 will be latest stable version. Well after I installed 1.10 and installed all pre-requisites before that (PHP, MadriaDB etc.) and configure everything I went thru setting ticket center up and modifying things for my needs. In that process i tried installing LDAP plug  in and had some problems that is not compatible with PHP version that i had at the time (PHP 5.6w). I couldn't install ldap for php in CentOS. It gave me conflict error of php5.6 and 5.4ldap for php or something amongst those lines. My choice was to downgrade php version and ticket center version to make sure everything was working correctly. I did both and was running php5.4 with ticket center 1.9.15. So now i went to customize my ticket center and go to:
Admin panel>Manage>Forms> where i created custom form. In that form i added those fields:
Label:Select one or more choices Type:Choices Visability:Requre Variable: reson
Label: Select Date Prefered  Type:Date and TIme Visability:Require Variable: date
When user logs into the ticket center they have this form to fill in. I get alert in email that i set up with those variables. When i get email everything works fine and format is nice.
So now the we got request that all the users have access to ticket center that are in Active Directory. We are company that have a huge turnaround with users, so managing that would be a problem with current setup because i as admin had to register and create every user. So i called OSTicket center and ask for solution. They said i should upgrade to 1.10 and that ldap in this particular version allows users to log in with automatic registration as long as they are in Active Directory. Perfect solution.
That is exactly what i did. Upgrade to 1.10 (by following instructions on website -by website i mean wiki site on osticket main page) . And boom. My problem is over. Everything works. That is until i tested the ticket center by putting the ticket in and came back with example in email alert i already posted in my original post. So i hope you understand a little better my problem now. If you don't, i can draw a diagram also and attach it here. 
To answer your questions:
Website: http://osticket.com/download
Steps: Admin panel>Manage>Forms> where i created custom form. In that form i added those fields:
Label:Select one or more choices Type:Choices Visability:Requre Variable: reson
Label: Select Date Prefered  Type:Date and TIme Visability:Require Variable: date
Date and Time format: Is default i did not change anything. It is:
Time format: hh:mm: a
Date format: MM/dd/y
Date and Time Format: MM/dd/y h:mm a
Day, Date and Time Format: EEE, MMM, d y h:mma
Upgrade PHP: I am i doubt that upgrading php will resolve the problem i have. However if you prefer to see latest and greatest i will upgrade to 5.6. I just don't understand the logic of why would php version matter of date and time format or multiple choice format not transferring correctly in email if everything worked in version 1.9.15. 
Also i am not sure why in email alert dated chosen always comes back as: 12/31/1969 7:33 pm no matter what i choose. 

Thank you.

**Comment by MRSBPO** [comment]
Update:
So now after removing one "d" from date format, to show: Date Format: MM/d/y
now when you go to create a ticket, it displays fine (not double on day anymore). So one thing is fixed. However in email alert i still get date of 12/31/1969 7:33 pm no matter what date i choose. 
Also in email alert multiple chose is still a problem it comes back with "Array" word rather than choices that user selected in the ticket.

**Comment by MRSBPO** [comment]
Update II 
If I remove multiple choice and give them to select only one, it works fine. Only if i let user be bale to select multiple issues it feeds in email as "Array" rather than choices they selected.

**Comment by MRSBPO** [comment]
Update III
I upgraded PHP version to 5.5 no difference. Same problem. 
Than I upgraded PHP version to 5.6 and no difference. Same problem.

**Comment by MRSBPO** [comment]
Server Information
osTicket Version	v1.10 (901e5ea) —  Up to date
Web Server Software	Apache/2.4.6 (CentOS) PHP/5.6.30
MySQL Version	5.5.52
PHP Version	5.6.30

**Comment by MRSBPO** [comment]
Anyone? Is this a bug or? I am not sure why is this happening but it is preventing system from working normally. Everything is up to date at this point but problem is still there. Does anyone have any idea of what is going on?
Can anyone repeat what I am experiencing?

**Comment by maxcrookston666** [comment]
I can confirm issues with version 1.10.  I updated and now custom date fields are changing upon submission. 
Looks like a masking issue, my date widget assigns via this format, April/033/17 even though my settings mask is MM/dd/y

**Comment by maxcrookston666** [comment]
found solution.
https://github.com/osTicket/osTicket/pull/3623
look for the changes in the osticket.js file in js folder.   replace data  with changes.

**Comment by cslone** [comment]
Any luck on the email/array issue? I am experiencing the same issue; the word 'Array' gets spit out in the email rather than the list of values that make it up. It does this as long as you allow multiple selections, even if you only select one.

Server Information
osTicket Version v1.10 (901e5ea) (plus some tweaks)
Web Server Software | Apache/2.4.18 (Ubuntu)
MySQL Version | 5.7.20
PHP Version | 5.6.31-1~ubuntu16.04.1+deb.sury.org+1

**Comment by cslone** [comment]
If this is still helpful to, @MRSBPO,  or anyone else, the solution/workaround to the array issue you described above (which I was also having) is to create the list first in the List tab of the admin panel. Then add that list as one of the form fields and save. You can then configure it much the way you would a Choices field to allow multiple selections and the emails created from this will properly output the list instead of printing 'Array.'
