### ISSUE TITLE
i have to create and update custom fields info from php code for "Contact Information", so is their any way?

### ISSUE THREAD

**Issue by harshad-concetto** [osTicket/osTicket#3806]
hello guys,

i just need to know that is their any way to update and create "Contact Information" form details from other side

in details

we needs to update that custom info through the database tables, so could you please help me with that?

**Comment by ntozier** [comment]
Q: is their any way to update and create "Contact Information" form details from other side
Huh?  Other side?  What do you mean by the Other side?  I see osTicket as having three sides.  The User UI, the Admin UI, and the back end (OS and DB).

Q: we needs to update that custom info through the database tables, so could you please help me with that?
A: You would have to look at the DB and figure out how all the moving parts work together and write a script that updates it how you want to update it.
