### ISSUE TITLE
Attachments are corrupted after restoring the database

### ISSUE THREAD

**Issue by pramod-s** [osTicket/osTicket#3808]
### Prerequisites

* [ No] Can you reproduce the problem in a fresh installation of the "develop" branch? No
* [No ] Do you have any errors in the PHP error log, or javascript console? No
* [Yes ] Did you check the [osTicket forums](http://osticket.com/forum/categories)? yes
* [Yes ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description
The osTicket was setup on one server, we had to migrate to a new high end server. So we took the backup of the mysql database and restored it in the new server. But after restoring all the ticket details including the attachments are coming, but when we try to download the attachment it is getting corrupted.

### Steps to Reproduce

1. Backup existing mysql database.
2. setup same instance of osTicket v1.10-rc.2 (231f11e)
3. restore the database from step 1.
4. After login try to download an attachment from the existing ticket.
5. Attachments gets downloaded but are corrupted and not able to open.

**Expected behavior:** [Attachments should open]

**Actual behavior:** [Attachments are corrupted and not able to open]

### Versions - osTicket v1.10-rc.2 (231f11e)

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

**Comment by AlexeyDemidov** [comment]
If you edited your configuration file see #3779

**Comment by pramod-s** [comment]
Hi,

I have not edited my configuration file. But after the installation I got the message that the ost-config.php is writable, I changed it to read only.

Saw the details from #3779, there was an empty line. I removed the empty line and restarted the apache server. Still the attachments are corrupted (I have noticed this error only for word and excel, text files are loading fine).

Regards,
Pramod S

**Comment by ntozier** [comment]
You are running an outdated [read:not supported] RC (Release Candidate) version that was full of bugs.   You should upgrade to stable to test to see if you still have issues.

**Comment by pramod-s** [comment]
Hi,

I tried to install the v1.10, but in the installation page when I try to point to the existing database it is showing an error "We have a problem - another installation with same table prefix exists".

Can you please let me know how to upgrade the osticket with the existing database from v1.10-rc.2

**Comment by ntozier** [comment]
What are you doing?  It sounds to me like you are trying to do a new install.

You should:
back up your site.  
back up your database.
download archive file from http://osticket.com/download
install the contents of the archive in the root osTicket folder.
Log into osTicket.

**Comment by pramod-s** [comment]
Hi,

Let me tell you in detail :
Earlier we had installed v1.10-rc.2 on one of our servers,
and later we were required to move the osticket to new server.
we took the mysql database backup and restored it in new server.
installed v1.10-rc.2 and pointed this to the restored database.
we are able to see everything, including the attachment.
but when we download the attachment, it is getting corrupted.
Now, we want to know is there something we are doing wrong here ?

Regards,
Pramod S

**Comment by Synt4xError** [comment]
You still shouldn't be using RC2, you should be using latest edition from OSTickets website under the download section. 

It's possible your issue can be resolved once updated, you don't know until you try. You can test on a lab environment by backing up database and site and restoring it to a location and test there. 

Your version of OSTicket is not supported by anyone because it was a "beta" edition of OSTicket.

**Comment by ntozier** [comment]
I would invite you to seek your support experience at the support forums.  This does not appear to be a bug report for the devs to look at. 

You should:
- back up your old site. (make sure you note any plugins installed) 
- back up your old database.
- download 1.10 archive file from http://osticket.com/download
- install the contents of the archive in the root osTicket folder on the new server.
- copy your old /include/ost-config.php to the new server. (alternatively you can edit it if you want)
- download any plugins you had installed from from http://osticket.com/download
- put the plugins in the /include/plugins folder 
- create the DB on the new server.
- create the same user DB credentials and grant it privs on the DB on the new server.
- restore the DB on the new server.
- Open a web broswer and browse to the site (and Log into osTicket).

"but when we download the attachment, it is getting corrupted."
You haven't told us how you have osTicket configured to handle attachments.

If you still have problems I would compare the php.ini on the old server to the one on the new server, then do the same with the webserver config.

**Comment by pramod-s** [comment]
Hi,

In the old osTicket attachments were stored in the database only. After restoring only the text files we are able to download, other office files(word, excel) and images are corrupted.

Tried it with new version(v1.10)  and compared the php.ini files, but still the same issue persists.

**Comment by shenol** [comment]
I have the same problem. I do not mind if I do it again
