### ISSUE TITLE
Assign tickets to user by API

### ISSUE THREAD

**Issue by bohregard** [osTicket/osTicket#381]
Using the API, the ability to assign the ticket to a user by either their username or ID.

**Comment by Dynatrace-Adam-Gardner** [comment]
Looking at the <code>assign</code> function of the class.ticket.php

//Assign ticket to staff or team - overloaded ID.
    function assign($assignId, $note, $alert=true) {
        global $thisstaff;

        $rv=0;
        $id=preg_replace("/[^0-9]/", "", $assignId);
        if($assignId[0]=='t') {
            $rv=$this->assignToTeam($id, $note, $alert);
        } elseif($assignId[0]=='s' || is_numeric($assignId)) {
            $alert=($alert && $thisstaff && $thisstaff->getId()==$id)?false:$alert; //No alerts on self assigned tickets!!!
            //We don't care if a team is already assigned to the ticket - staff assignment takes precedence
            $rv=$this->assignToStaff($id, $note, $alert);
        }

        return $rv;
    }

Therefore, to assign to a team with team_id of 2 ... use

assignId:t2 (JSON) or <assignId>t2</assignId> in XML

To assign to a user, just user their user ID ... Eg. to assign to a user with UID of 3765 use
assignId:3765 (JSON) or <assignId>3765</assignId> in XML

**Comment by andrelindner** [comment]
> Using the API, the ability to assign the ticket to a user by either their username or ID.

still an issue? if not, please close this issue.
