### ISSUE TITLE
Unable to sort by department on the "open tickets" queue v1.10

### ISSUE THREAD

**Issue by aaacharlie** [osTicket/osTicket#3812]
I spent hours trying to find someone with instructions on how to add the "departments" column to the open tickets queue. It's a fairly popular request. Unfortunately no directions exist. I went at the code on my own with very little coding experience, and I got a working and sortable department column on the open queue.

In /include/staff/tickets.inc.php I modified two sets of code. WARNING this worked great for me so far, but I'm not sure of any future erorrs or implications it might cause down the road. Backup up your db and your tickets.inc.php file. The column is still titled "assigned to" but shows the departments and I'm ok with that and not going to attempt to make it perfect.

Line 327>332 These are responsible for making the column sortable when you click it.

case 'assignee':
    $tickets->order_by('dept__name', $orm_dir);
    $tickets->order_by('dept_id', $orm_dir);
    $tickets->order_by('dept__name', $orm_dir);
    $queue_columns['dept_id']['sort_dir'] = $sort_dir;
    break;

Line 517>523 This set of lines made the "assigned to" column populate departments instead.

$lc='';
                if ($showassigned) {
                    if ($T['dept_id'])
                        $lc = Dept::getLocalById($T['dept_id'], 'name', $T['dept__name']);
                    elseif ($T['dept_id'])
                        $lc = Dept::getLocalById($T['dept_id'], 'name', $T['dept__name']);
                }
                else {
                    $lc = Dept::getLocalById($T['dept_id'], 'name', $T['dept__name']);

Good luck, and please post improvements.

**Comment by ntozier** [comment]
Not sure why you are opening an issue report for this.
You should post this to: 
http://osticket.com/forum/discussion/75457/a-better-ticket-list

Or you should install the Custom Queues forth coming feature PR and use that.

**Comment by aaacharlie** [comment]
Ntozier,

Thanks for being on top of organizing.  I see your posts a lot.
Unfortunately I was unable to post to the forum, maybe because I just
signed up today and need to be given that privilege first? So I posted to
github instead.  I'll try the forum  again later. I literally spent about 4
hours today working on this and really wanted to share it.  Thank you.

Charlie

**Comment by ntozier** [comment]
I appreciate your sharing it, I  just think that it isn't an 'issue report' :)
You should be able to post to the forums.  Feel free to email me at neil at osticket dot com if you find this to be untrue. :)

Oh and please close this issue report. :)
