### ISSUE TITLE
Recommended PHP.ini Settings for OST v1.10 on IIS8.5 Php version  7.0.17 

### ISSUE THREAD

**Issue by harpalpatiala** [osTicket/osTicket#3814]
Hi Folks,
I am new to community so please bear with me.

I am looking for a recommended PHP.ini settings to get osTicket work better for us and produce less issues.
Issues that we are facing right now:-

1. Drag drop of Attachment in Reply box makes a Never uploading situation. However Choose File works.
2. Some browsers behave different, like on Safari we cannot Sort tickets, On IE cannot upload Excel files.
3. Sometime Reply goes without attachment
4. On Lookup or Create user page (While Creating new ticket from Agent console), we cannot select user with mouse click however pressing Tab or Enter works.

PHP.ini is attached herewith. [php.txt](https://github.com/osTicket/osTicket/files/959527/php.txt)

Our Setup have following:-
osTicket Version v1.10 (901e5ea) —  Up to date  
Web Server Software Microsoft-IIS/8.5 
MySQL Version 10.1.22 
PHP Version 7.0.17 

Any help would be greatly appreciated.

**Comment by ntozier** [comment]
This does not appear to be a issue bug report.  I invite you to join the Forums and get support there http://osticket.com/forum

Please include how you have attachment configured, sizes, etc.  And if you use any of the storage plugins.
