### ISSUE TITLE
Search feature pagination issue v1.10

### ISSUE THREAD

**Issue by mlemens-como** [osTicket/osTicket#3816]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
-- YES
* [ ] Do you have any errors in the PHP error log, or javascript console?
-- NO
* [ ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
-- YES
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?
-- YES

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

[Description of the bug or feature]

### Steps to Reproduce

-- Install v1.10, create enough tickets with a common search term to make it paginate across 2 pages on a search for that search term.

**Expected behavior:** [What you expected to happen]

-- To be able to click through the pagination numbers. For the counts found to be right on the search tab.

**Actual behavior:** [What actually happened]

-- When you first search for the search term, everything looks right. 
-- When you try to go to the next page, it just says: There are no tickets matching your criteria.

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.

osTicket Version	v1.10 (901e5ea) —  Up to date
Web Server Software	Apache/2.4.7 (Ubuntu)
MySQL Version	5.5.55
PHP Version	5.5.9-1ubuntu4.21

-- I also tried it on another Ubuntu server with NGINX.

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

-- Does it in latest version of chrome and ie on Windows 10.

**Comment by JediKev** [comment]
I have tested this on both Ubuntu (PHP 7) and CentOS (PHP 5.4) and had no issues whatsoever...are you getting any errors in your error logs? Also are you searching by a 'word' or doing an 'Advanced Search'?

**Ubuntu (PHP 7):**
<img width="483" alt="screen shot 2017-06-30 at 09 40 26" src="https://user-images.githubusercontent.com/11823401/27740822-c61c78f4-5d78-11e7-98a1-094d154935de.png">
<img width="961" alt="screen shot 2017-06-30 at 09 40 17" src="https://user-images.githubusercontent.com/11823401/27740828-c9f7f228-5d78-11e7-8256-8fd893d4174d.png">

**CentOS (PHP 5.4):**
<img width="493" alt="screen shot 2017-06-30 at 09 42 52" src="https://user-images.githubusercontent.com/11823401/27740831-cfcdbf7a-5d78-11e7-9223-e7a48fb05b6f.png">
<img width="961" alt="screen shot 2017-06-30 at 09 23 34" src="https://user-images.githubusercontent.com/11823401/27740840-d8780f18-5d78-11e7-966b-87f35690c5e9.png">

**Comment by mlemens-como** [comment]
I was trying the basic search and advanced search.

I did have some luck exporting the ost__search table before doing an upgrade, then truncating the ost__search table after the upgrade and importing it in.
I came to the conclusion it may be something with us running MySQL 5.5*…I think I read like “full index search” or something may be the culprit…they were saying it came out in MySQL 5.6

If we need to be running 5.6 or later, it would be nice if the Upgrader would notify us that. Or at least tell us what issues we may have if we don’t upgrade to 5.6.
Liking the new features in v1.10 so far!

Thanks!

**Comment by JediKev** [comment]
>I did have some luck exporting the ost__search table before doing an upgrade, then truncating the ost__search table after the upgrade and importing it in.

So you got it working -or- are you just mentioning how you set it up?

>If we need to be running 5.6 or later, it would be nice if the Upgrader would notify us that. Or at least tell us what issues we may have if we don’t upgrade to 5.6.

I agree, but you don't need to be running 5.6 or later. It works with MySQL 5.5.x or above.

>Liking the new features in v1.10 so far!

That's really great to hear! 1.11 will be even better! 😉

**Comment by mlemens-como** [comment]
I got it working for us by reimporting the ost__search table.
I could not find anyone else having this particular problem from hours of searching.

I am going to say it is something on our end it sounds like, or more people would be complaining by now.
I think this ticket can be closed.

Thanks for looking into it.

**Comment by JediKev** [comment]
>I got it working for us by reimporting the ost__search table.

Thank you for posting the resolution. If anyone ever has the same issue, they will know what to do 👍 

>I think this ticket can be closed.

You will have to close this issue 😁

>Thanks for looking into it.

Not a problem!

**Comment by mlemens-como** [comment]
Thanks for the help, closing ticket.

**Comment by ntozier** [comment]
As a side not (for anyone reading this later) regarding: 
"I came to the conclusion it may be something with us running MySQL 5.5*"

We are running MySQL 5.5.42 and I cannot reproduce this issue. (my system was upgraded, and not a new 1.10 install)
