### ISSUE TITLE
Wrong date format in registration form 

### ISSUE THREAD

**Issue by danielraknes** [osTicket/osTicket#3817]
### Description

Date formats in registration form is wrong format.

### Steps to Reproduce

You can try it yourself by this link: 
http://networkstatement.jbv.no/btp/open.php

Sorry that it is in norwegian, but try the field "Disponeringdato start". 

**Expected behavior:** [What you expected to happen]

As the dates in the rest of the dates is in the correct format, i believe that this date also should be correct.

**Actual behavior:** [What actually happened]

Example: todys date (3th of may) formats to 033/mai/17 in the datefield.

### Versions

Running on a RHEL7.

Serverinformasjon
osTicket versjon	v1.10 (901e5ea) —  Up to date
Web Server programvare	Apache/2.4.6 (Red Hat Enterprise Linux) PHP/5.6.29
MySQL versjon	5.5.52
PHP-versjon	5.6.29
PHP Extensions
gdlib	 Bildemanipulering og PDF-utskrift
imap	 Brukes for henting av e-post
xml	 XML-API
xml-dom	 Brukes til HTML epost behandling
json	 Forbedrer ytelsen oppretting og behandling av JSON
mbstring	 Anbefales for ikke vestlige europeiske språk innhold
phar	 Anbefales for plugins og språkpakker
intl	 Anbefales for ikke vestlige europeiske språk innhold
fileinfo	 Used to detect file types for uploads
APCu	 Improves overall performance
Zend Opcache	 Improves overall performance
PHP-innstillinger
cgi.fix_pathinfo	 "1" anbefales hvis AJAX ikke fungerer
date.timezone	 Å sette standard tidssone er meget viktig
Database informasjon og bruk
Skjema	bane_pf (localhost)
Skjema sinatur	98ad7d550c26ac44340350912296e673
Rom brukt	6.05 MiB
Rom for vedlegg	0.00 MiB
Timezone	CET (Interpreted as Europe/Berlin)

**Comment by truezjz** [comment]
get same issue when use English version 1.10,  but in 1.9 works fine.

**Comment by JediKev** [comment]
Could you post a screenshot of your Date and Time Options? **(Admin Panel > Settings > System > Date and Time Options)**

**Comment by truezjz** [comment]
![osticketissue1](https://cloud.githubusercontent.com/assets/16107662/26467683/b45c8a92-4161-11e7-957a-d2e942f9641f.jpg)

**Comment by truezjz** [comment]
@JediKev thx for your attention, ticket #3824 seems also related to this issue. I noticed if I changed  in Settings -> System -> Date and Time Format, to "Locale Defaults, 24 hours", it will give me a correct format like this: "17-May-25"

**Comment by Chefkeks** [comment]
@JediKev and @truezjz
Look at Pull Requests from me:
https://github.com/osTicket/osTicket/pulls/Chefkeks

**Comment by danielraknes** [comment]
Thanks guys!! #3623 fixed my issue and we are all happy again :)
