### ISSUE TITLE
Textarea in popup windows is a bit small

### ISSUE THREAD

**Issue by danielraknes** [osTicket/osTicket#3818]
### Description

If you have "a lot" to say in a popup window, the text area is too small to get an overview of what you have written. 

Can you please make this windows a bit bigger or expandable for the user?

Like the textarea i'm writing this issue :)

Best regards
Danny

**Comment by ntozier** [comment]
screen shot of where and what you are talking about would be nice.
Also what version of osTicket are you running?

**Comment by JediKev** [comment]
Thanks for the suggestion! I doubt this will be changed though as you can scroll within the box.

**Comment by danielraknes** [comment]
Thanks for your reply anyway :)
