### ISSUE TITLE
PEAR Mail_mimeDecode should be upgraded to 1.5.6

### ISSUE THREAD

**Issue by kaorukobo** [osTicket/osTicket#3819]
### Description

In my osTicket instance, few emails from certain MTAs aren't parsed well. For these emails, a new ticket is created but the message body turned to `(empty)` . 

Digging into code, I found this problem is caused not by osticket but by bundled Mail_mimeDecode. `Mail_mimeDecode->decode`'s result was strange, any `body` of MIME-parts were null.

### Solution

I just upgraded bundled Mail_mimeDecode 1.5.5 to [1.5.6 (2016-08-28)](https://pear.php.net/package/Mail_mimeDecode) by replacing [mimeDecode.php](https://github.com/osTicket/osTicket/blob/develop/include/pear/Mail/mimeDecode.php) to newer version. The problem has gone.

### Steps to Reproduce

I cannot provide the data (incoming email) to reproduce the above problem.

### Versions

v1.10

**Comment by iradave** [comment]
The fix suggested by @kaorukobo has resolved this issue for us on v1.10.

**Comment by dhiru1602** [comment]
Same issue with my osticket install. Mails from Live, Outlook and Hotmail have an empty body. This is quite a big issue since the actual body content is lost incase of Email piping.

![image](https://user-images.githubusercontent.com/1326273/32179201-3cef279e-bda8-11e7-97b7-1a4883b0c4f2.png)

**Comment by kaorukobo** [comment]
Refs related issues:

#3278
#3361
#3362
