### ISSUE TITLE
Error when accessing some internal ajax uri

### ISSUE THREAD

**Issue by soulraven** [osTicket/osTicket#382]
i get 400(Bad Request) when app call:
- scp/ajax.php/config/scp
- scp/ajax.php/users/lookup/form (when "New Ticket" button is clicked)

any ideea why? and how i manage to resolve this?

i am using: osTicket (1.8-git)

**Comment by hmert** [comment]
This works for me now.

https://github.com/osTicket/osTicket-1.8/issues/844#issuecomment-42192709

**Comment by java2dev** [comment]
@soulraven How did you resolve the first issue regarding ajax.php/config/scp and user/form 404 bad request? I have the same issue and the ajax.php/config/scp is generated in loop.
Thanks in advance.

**Comment by java2dev** [comment]
This is my conf

`server {
	listen       127.0.0.1:86
;
	server_name  localhost;

	root   var/osticket/upload;
	index  index.php index.html index.htm;

	log_not_found off;
	charset utf-8;

	location ~ /\. {deny all;}
	
	   set $path_info "";
# Requests to /api/* need their PATH_INFO set, this does that
if ($request_uri ~ "^/upload/api(/[^\?]+)") {
	set $path_info $1;
}

# /api/*.* should be handled by /api/http.php if the requested file does not exist
#location ~ ^/upload/api/(tickets|tasks)(.*)$ {
#	try_files $uri $uri/ /upload/api/http.php;
#}

if ($request_uri ~ "^/api(/[^\?]+)") {
        set $path_info $1;
    }

    location ~ ^/api/(?:tickets|tasks).*$ {
        try_files $uri $uri/ /api/http.php?$query_string;
    }

# /scp/ajax.php needs PATH_INFO too, possibly more files need it hence the .*\.php
#if ($request_uri ~ "^/upload/scp/.*\.php(/[^\?]+)") {
#	set $path_info $1;
#}

#location ~ ^/ajax.php/(.)$ {
#try_files $uri $uri/ /ajax.php;
#}
#location ~ ^/scp/ajax.php/(.)$ {
#try_files $uri $uri/ /scp/ajax.php;
#}

 location ~ ^/scp/ajax.php/.*$ {
            try_files $uri $uri/ /scp/ajax.php?$query_string;
        }
        location ~ ^/ajax.php/.*$ {
                try_files $uri $uri/ /ajax.php?$query_string;
        }

# Make sure requests to /scp/ajax.php/some/path get handled by ajax.php
#location ~ ^/scp/ajax.php/(.*)$ {
#	try_files $uri $uri/ /scp/ajax.php;
#}

	location ~ \.php$ {
	fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
	include fastcgi_params;
	fastcgi_param  PATH_INFO   $path_info;
	fastcgi_pass 127.0.0.1:8686;
#           fastcgi_split_path_info ^(.+\.php)(/.+)$;
           #try_files $uri =404;
           #fastcgi_index index.php;
           #fastcgi_param  SCRIPT_NAME    $fastcgi_script_name;
           
           
	}
}
`
