### ISSUE TITLE
client search is not working with keywords 1.10

### ISSUE THREAD

**Issue by markus4000** [osTicket/osTicket#3822]
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch?

### Description

Client search is not working.
Searching for Ticketnumber works
Seraching for keywords does not work.

### Steps to Reproduce

1. install new 1.10 Version (or dev, same result)
2. create som tickets
3. Login as a Client
4. Search for keyword: nothing happens
![search110](https://cloud.githubusercontent.com/assets/4391014/25840527/6f9f463c-349c-11e7-98d9-51dac0579433.PNG)

### Versions
![version110](https://cloud.githubusercontent.com/assets/4391014/25840441/1a8128be-349c-11e7-843c-ff87321a837f.PNG)

**Comment by markus4000** [comment]
does someone else have the same problem?

**Comment by djmrsmith** [comment]
I also have the same problem....

![capture](https://cloud.githubusercontent.com/assets/16204559/26347980/89686eb2-3fab-11e7-9591-701ef3347e2f.PNG)

Please help...

**Comment by alexandremota** [comment]
Hello!

We also have this problem, it has bothered us a lot. If anyone can help, thanks!

![2017-06-10 09_37_36-osticket __ painel de controle do administrador](https://user-images.githubusercontent.com/1570758/27002804-95245dce-4dc0-11e7-985d-08971b5e1576.png)
