### ISSUE TITLE
ostickets broken in using Google Chrome

### ISSUE THREAD

**Issue by orlyinomcoke** [osTicket/osTicket#3823]
### Prerequisites

* [x ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [x ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [x ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

My ticket support system for how many years is suddenly having multiple errors/bugs. 

1. When not logged in and tried to open a ticket, it will then AUTOMATICALLY login using another account. 

2. Can still login, but when i open a  ticket, the logged in user will be changed to another account name.

3. Agent login having a valid csfr token error.

### Steps to Reproduce

1. Go to my supprot ticket portal 
2. Click open a new ticket

**Expected behavior:**

SHould be able to open ticket using the logged in account not another another account

**Actual behavior:** 

Opening tickets are all submitted using one account.

### Versions

![image](https://cloud.githubusercontent.com/assets/28568495/25856841/cb8e937c-3509-11e7-8755-96fa3a6673de.png)

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

Using latest google chrome version & windows 10

NOTE: all agents across the world are using google chrome, and all are having the same issue. 

Thank you in advance. Cheers! 

Orly

**Comment by JediKev** [comment]
You're using 1.9.12 you should try upgrading to the latest stable release of the 1.9.x series (1.9.15) to see if these issues go away. _Always backup your database and files before you upgrade._
