### ISSUE TITLE
Due Time is invisible when create new ticket in Agent portal 

### ISSUE THREAD

**Issue by truezjz** [osTicket/osTicket#3824]
### Prerequisites

* [ Y] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [N ] Do you have any errors in the PHP error log, or javascript console?
* [ Y] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [ Y] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

[Description of the bug or feature]

### Steps to Reproduce

Log into Agent portal,  create new ticket, All due time are invisible in the drop down list.

**Expected behavior:** [What you expected to happen]
In v1.9, all All due time are visible in the drop down list

**Actual behavior:** [What actually happened]

### Versions
V1.10

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

**Comment by JediKev** [comment]
I have v1.10 installed and I am able to see all of the Due Date times. Could you provide more information on your installation details and server configuration?

<img width="961" alt="screen shot 2017-05-25 at 14 09 30" src="https://cloud.githubusercontent.com/assets/11823401/26466302/e0e9673c-4153-11e7-95b8-37d6bdd90c4a.png">

**Comment by truezjz** [comment]
Server Information
osTicket Version	v1.10 (901e5ea) —  Up to date
Web Server Software	Apache/2.4.4 (Win64) PHP/5.4.12
MySQL Version	5.6.12
PHP Version	5.4.12
OS: windows 10

One thing I noticed, in Settings -> System -> Date and Time Format,   if I choose "-Advanced-", the due time are invisible, but if I choose "Locale Defaults", the due time are visible.

**Comment by ntozier** [comment]
Please upgrade PHP to 5.6 and retest.
