### ISSUE TITLE
add Help topic to Ticket Filter

### ISSUE THREAD

**Issue by etessam** [osTicket/osTicket#3825]
### Prerequisites
N/A

### Description

Can we add the Help Topic to the list of Filter Rules Section in the Ticket Filters screen ?

### Steps to Reproduce

1. Admin Panel
2. Manage
3. Ticket Filters > Filter Rules section
![untitled](https://cloud.githubusercontent.com/assets/17230552/25913194/85833040-35c2-11e7-8dd0-8925a2a62d20.png)

### Versions

osTicket : 1.8.1
Windows OS

**Comment by ntozier** [comment]
I find it incredibly unlikely that the Devs will back port a current feature to the no longer supported or released 1.8.  This is in the 1.9 and 1.10 versions.

**Comment by etessam** [comment]
@ntozier can you please show me a screenshot ?

**Comment by JediKev** [comment]
This is version 1.10 and it has the option of Help Topic ID.

<img width="960" alt="screen shot 2017-05-25 at 14 04 31" src="https://cloud.githubusercontent.com/assets/11823401/26466105/2534d3e6-4153-11e7-95cd-b9bfca1e5efe.png">

**Comment by mlipok** [comment]
Could this application be considered closed?

**Comment by etessam** [comment]
@JediKev  I have Upgraded to the 1.10, it solved my problems, thank you.

@mlipok the source code is Free Open, but once you install it on your server it's considered closed. The version will be available to you only.
