### ISSUE TITLE
Roadmap for a shiny v1.9.? With a working backend editor. [Question]

### ISSUE THREAD

**Issue by gitfve** [osTicket/osTicket#3833]
-Main problem in v1.9.x is the back-end editor, it is so unstable and have so many problem. Most if using Firefox. Can't understand it is still the same after years.

Is there a upcoming solution for the editor problem in the back-end on v1.9.?

**Comment by ntozier** [comment]
This does not appear to be an issue/bug report.   Please close.

If you would like to have a discussion about the product with other people please feel free to join and participate in the forums at: http://osticket.com/forum
