### ISSUE TITLE
Trying to update a ticket with custom field

### ISSUE THREAD

**Issue by jhonniedj** [osTicket/osTicket#3835]
Dear All,

I'm rather new, but hope I can get some help here.
With OSticket 1.10

I'm trying to edit a custom field, just from the view-mode,
since all my agents need to edit, is this RMA number field.
With some script-kiddie-skills I managed to do this.
Only thing is, because of the name and ID of the form input field is changing,
I can not make it permanent.
Is there somewhere a static name for my custom field,
so I can use this, in stead of the changing [03da7e1a78cc6c3e] name/id?

In "include\staff\ticket-view.inc.php" at line 209
I added some code:

```
<div style="display:inline-block"> 
	<form method="POST" action="tickets.php?id=<?php echo $ticket->getId(); ?>" name="update"> 
		<?php csrf_token(); ?> 
		<input type="hidden" name="a" value="edit"> 
		<input type="hidden" name="source" value="<?php echo Format::htmlchars($ticket->getSource()); ?>">  
		<input type="hidden" name="topicId" value="12">   
		<input type="hidden" name="slaId" value="1">   
		<input type="text" id="_03da7e1a78cc6c3e" size="16" maxlength="30" placeholder="COMPANY.NAME.DATE" name="03da7e1a78cc6c3e" value="" style="text-align:center;font-size:11px;line-height:16px;">
		<input type="submit" value="RMA" class="button" style="height:19px;width:25px;padding: 1px 9px 3px 5px;">  
	</form> 
</div>
```

Thanks in advance,

**Comment by clonemeagain** [comment]
I tried to figure that out as well.. ended up giving it up as a joke. There is no documentation, no examples, no way to do it. The "dynamic forms" are not dynamic at all, they are "database forms".. Who thought eval'ing class definitions was a good idea? 

The worst part is, I felt like I was close.. if I could only figure out how to inject a custom form into a ticket, then I could have rendered it wherever I wanted, but that first part, never worked. I knew the ID of the form I wanted, and that it wasn't currently attached, but building the form object and associating it with the ticket never worked, it would always add as id zero, which broke the edit page completely.. frustrating. I miss 1.7.. sure it was verbose in HTML, but it worked.
