### ISSUE TITLE
Loss attachments when editing thread

### ISSUE THREAD

**Issue by devi1903** [osTicket/osTicket#3836]
OSTicket v1.10

When editing a ticket the attachments are lost/removed. I have noted that also the SLA is removed. My code already contains the changes in commit [https://github.com/osTicket/osTicket/commit/907ec36bd9f8c37c38c34b510b5af4e3ae26fd2a](url) as per below code, however this has not resolved the issue.

I have noted that when the same agent that added the attachments to the ticket originally and created the ticket edits the ticket then the attachments remain there, however when a different agent edits the ticket the attachments are removed.

`// Replace previous edit --------------------------
$original = $old->getParent();
// Link the new entry to the old id
$entry->pid = $old->pid;
// Drop the previous edit, and base this edit off the original
$old->delete();
$old = $original;
}

// Move the attachments to the new entry
$old->attachments->update(array(
'object_id' => $entry->id
));

// Mark the new entry as edited (but not hidden nor guarded)
$entry->flags = ($old->flags & ~(ThreadEntry::FLAG_HIDDEN | ThreadEntry::FLAG_GUARDED))
| ThreadEntry::FLAG_EDITED;

// Guard against deletes on future edit if requested. This is done
// if an email was triggered by the last edit. In such a case, it
// should not be replaced by a subsequent edit.
if ($guard)
$entry->flags |= ThreadEntry::FLAG_GUARDED;`

**Comment by ntozier** [comment]
duplicate report.  Please close dupe.
See: https://github.com/osTicket/osTicket/issues/2888

**Comment by devi1903** [comment]
Is #2888 being reopened as fault is not resolved?

**Comment by cbiere** [comment]
This bug is NOT fixed. I'm using the Knowledge Base as central point for all documentation. If the attached documents are not safe there, this feature is complete and utter useless. This should be disabled until it is fixed.

**Comment by ntozier** [comment]
@cbiere this thread is about attachments being lost on TICKETS when they are edited.  
It does not have anything to do with the Knowledge Base,

**Comment by cbiere** [comment]
How can you tell? You verified that this two operations do not share code? You seriously think these two issues (assuming these are really separate), have no common cause? I don't know what of the possibilities to consider more worrying. The problem is: This software loses attachments and I don't give a hell of a damn what kind of sub function this applies to. Or would you prefer a separate ticket for each buggy line of code?

**Comment by JediKev** [comment]
@cbiere 

Whoah man...slow your roll. No one yelled at you are started cursing. Please be as polite as possible so that people will feel happy to help you.

>How can you tell? You verified that this two operations do not share code?

He's been helping to fix issues/bugs since basically the beginning of osTicket....I think he would have a pretty good idea.

**Comment by devi1903** [comment]
@ntozier i can confirm this bug is not fixed. Unfortunately at this stage this bug is making OSTicket unusable for setups that require file attachments as data is not secure. When reproducing this fault it must be noted that if you edit tickets as the same user this fault does not exist. This only exists when a user creates and ticket and then a different user edits the ticket. When the different user edits the ticket the attachment gets removed. Also note that the SLA gets unset and all date fields go back by a number of days. Only if the user selects these fields themselves or deletes and re-uploads an attachment does it remain in place after the ticket is saved. I would not be surprised if the knowledge base issue is linked to exactly the same bug.

**Comment by ntozier** [comment]
@devi1903 I never said it was fixed.  I said 

"duplicate report. Please close dupe.
See: #2888"

**Comment by devi1903** [comment]
@ntozier. Noted, i will close this issue. Should #2888 not be open? Its closed noting that the issue is resolved.
