### ISSUE TITLE
Help Topic: Topic ID Display

### ISSUE THREAD

**Issue by serunati** [osTicket/osTicket#3837]
v1.10 (901e5ea)

Help Topic IDs are not accessible/displayed in the Admin Panel.  Please add this information as the Ticket Filter - Rules Matching Criteria only utilizes the 'id' and not the 'topic' fields from the records.

Currently the data is only accessible though direct access to the DBTable 'ost_help_topic'.  Our security model would prefer that OSTicket Admins not require access to the DB when creating conditions/filters.

**Comment by ntozier** [comment]
This does not appear to be a bug report.
Also you're statement actually isn't true.

You can go to Admin panel -> Manage -> Help Topics.
Mouse over the Help Topics and look at the mouse over url in the bottom left. (most bottom modern browsers).

You can also on that same page click on ANY Help Topic.  And look at the URL.. the Help Topic ID# is clearly displayed in the URL.
