### ISSUE TITLE
How to trans the SqlFuntion::NOW()  into string?

### ISSUE THREAD

**Issue by KomaBeyond** [osTicket/osTicket#3838]
There is my code:
```php
$created = $entry->getCreateDate();
```
And it return me an object of SqlFuntion?? But i want the datetime string. How ?

**Comment by clonemeagain** [comment]
You might need to share more info mate.. imagine we have no idea what you are on about. 

Are you talking about class SqlFunction ? Or are you trying to fetch the created datetime of a ThreadEntry object? Because it looks like there is another function further down "getVar" which should work like: 

```php 
$formatted_created = $entry->getVar('create_date');
```
