### ISSUE TITLE
LDAP Plugin, not saving changes HTTP Error 500

### ISSUE THREAD

**Issue by firepro20** [osTicket/osTicket#3847]
### Prerequisites

* [No ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [Yes] Do you have any errors in the PHP error log, or javascript console?
* [Yes ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [Yes] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

These are the errors I found in my log file

```
[Fri Jun 09 11:24:22.528795 2017] [:error] [pid 776] [client 192.168.0.201:57187] PHP Warning:  Declaration of AssignmentForm::render($options) should be compatible with Form::render($staff = true, $title = false, $options = Array) in /var/www/osticket/include/class.forms.php on line 4150

[Fri Jun 09 11:24:22.552107 2017] [:error] [pid 776] [client 192.168.0.201:57187] PHP Warning:  Declaration of TransferForm::render($options) should be compatible with Form::render($staff = true, $title = false, $options = Array) in /var/www/osticket/include/class.forms.php on line 4270

[Fri Jun 09 11:25:16.248229 2017] [:error] [pid 1023] [client 192.168.0.201:57199] PHP Warning:  require_once(include/Net/LDAP2.php): failed to open stream: No such file or directory in /var/www/osticket/include/plugins/auth-ldap/config.php on line 132, referer: http://tickets.axinternal.local/scp/plugins.php?id=1

[Fri Jun 09 11:25:16.248331 2017] [:error] [pid 1023] [client 192.168.0.201:57199] PHP Fatal error:  require_once(): Failed opening required 'include/Net/LDAP2.php' (include_path='./:/var/www/osticket/include/:/var/www/osticket/include/pear/:/var/www/osticket/include/plugins/auth-ldap/include') in /var/www/osticket/include/plugins/auth-ldap/config.php on line 132, referer: http://tickets.axinternal.local/scp/plugins.php?id=1

[Fri Jun 09 11:25:24.947825 2017] [:error] [pid 1024] [client 192.168.0.201:57200] PHP Warning:  require_once(include/Net/LDAP2.php): failed to open stream: No such file or directory in /var/www/osticket/include/plugins/auth-ldap/config.php on line 132, referer: http://tickets.axinternal.local/scp/plugins.php?id=1

[Fri Jun 09 11:25:24.947970 2017] [:error] [pid 1024] [client 192.168.0.201:57200] PHP Fatal error:  require_once(): Failed opening required 'include/Net/LDAP2.php' (include_path='./:/var/www/osticket/include/:/var/www/osticket/include/pear/:/var/www/osticket/include/plugins/auth-ldap/include') in /var/www/osticket/include/plugins/auth-ldap/config.php on line 132, referer: http://tickets.axinternal.local/scp/plugins.php?id=1

[Fri Jun 09 11:25:42.067986 2017] [:error] [pid 772] [client 192.168.0.201:57223] PHP Warning:  require_once(include/Net/LDAP2.php): failed to open stream: No such file or directory in /var/www/osticket/include/plugins/auth-ldap/config.php on line 132, referer: http://tickets.axinternal.local/scp/plugins.php?id=1

[Fri Jun 09 11:25:42.068110 2017] [:error] [pid 772] [client 192.168.0.201:57223] PHP Fatal error:  require_once(): Failed opening required 'include/Net/LDAP2.php' (include_path='./:/var/www/osticket/include/:/var/www/osticket/include/pear/:/var/www/osticket/include/plugins/auth-ldap/include') in /var/www/osticket/include/plugins/auth-ldap/config.php on line 132, referer: http://tickets.axinternal.local/scp/plugins.php?id=1
```

### Description

When entering information for LDAP, after I enable the plugin from Mange -> Plugins, the websites gives and Internal 500 error and crashes. This happens when I enter any valid information in the LDAP setup form and press save changes.

### Steps to Reproduce

1. Enter info on LDAP setup form
2. Save
3. Error pops up

**Expected behavior:** [What you expected to happen]

the form to save my changes

**Actual behavior:** [What actually happened]

Crashing with an internal 500 web error.

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.

v1.10 (901e5ea)

Apache/2.4.10 (Debian)

Latest Chrome
Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

**Comment by compuvin** [comment]
Do you have the latest version of the LDAP plugin (v0.6.3)? Also, do you have the LDAP and LDAP2 packages installed on the system running osTicket? See https://github.com/osTicket/osTicket-plugins/issues/105

**Comment by RonniePitts** [comment]
[ldap.zip](https://github.com/osTicket/osTicket/files/1193492/ldap.zip)

Hi Guys,

Had a bit of a bad experience upgrading from 1.9 to 1.10.1 (php upgrade,etc.), after it finally upgraded noticed that the LDAP plugin wasn't working anymore however local user worked fine. 

The logs indicated this error 

Fatal error:  Uncaught Error: Call to a member function bind() on null in phar
.....thrown in phar://C:/osTicket/upload/include/plugins/auth-ldap.phar/authentication.php on line 220

Basically updated PEAR, Net_LDAP2 & Net_LDAP, etc. still not working so unpacked the phar. 

Main issues with current live LDAP plugin:

1. The current plug will not save any LDAP configuration unless its successful (you may be lucky if you've upgraded as the settings will still exist),  basically the error is unable to bind to server yadda yadda. 
2. The getConnection method is currently throwing a NULL, I'm assuming there is an issue with Net_LDAP2 somewhere. 

Temporary Hack Fix

The current authenticated method has been stripped to use the ldap methods in PHP now, however this is VERY BASIC.  Also the validation checking in the config has been commented out so it now saves. 

Its now possible to authenticate using ldap in my environment (Windows & 1.10.1) with the minor changes to the code but this breaks the search obtain and possible new users until the remaining code is updated to support the ldap functions in php. 

I've attached the raw unpack files which need to exist in the plugin directory.

**Comment by ntozier** [comment]
As a side note there is no version 1.10.1, I trust that you mean 1.10.

I would think that this should probably be posted on the plugin repo.

**Comment by jdwfly** [comment]
I just ran into similar issue as @firepro20 today. My environment is cPanel/WHM with a multiPHP install. If you install the PEAR extensions through cPanel they are installed to /home/username/php and that directory needs to be included in the include_path. Even after doing that I also had to remove the "include/" from the config.php and the authentication.php since that directory structure inside the /home/username/php did not have an include folder. Once those changes were made the plugin was functional for me.

**Comment by ericmuga** [comment]
same issue on osticket1.10

**Comment by ntozier** [comment]
I still think that this should not be in this repo,and should be in the plugin repo.

@ericmuga environment details?  version of PHP?  error message?

I've run the LDAP plugin since it was released across many versions of both osTicket and PHP as well as multiple OSes and never had a problem.

**Comment by ericmuga** [comment]
This is fine noe

**Comment by towerplease** [comment]
I got it working because i missconfigured something, just in case you did this too, here is my solution:

To have user-LDAP/AD login to work, you registermethod needs to be "public", otherwise you get access denied because its not allowed to create a new user. When you login with AD-Credentials there is automatically created a osTicket-User.

Hope this helps some of you.

I would recommend to osTicket-devs to still make it possible to login, even when the registermethod is set to private.
