### ISSUE TITLE
Advanced Search in backend returning all Tickets in the system. 

### ISSUE THREAD

**Issue by darklord1807** [osTicket/osTicket#3848]
### Prerequisites

* [X] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [X] Do you have any errors in the PHP error log, or javascript console?
* [ X] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [ ]X Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description
AdvancedSearch returning all Tickets in the system. 

### Steps to Reproduce

1. Log in the backend (/scp) as a Staff 
2) In the Open Tabs, do an Advanced Search with Due Date ticked
3) The search result will output all the tickets in the system(Even those I should not be able to get access to)

**Expected behavior:** 
Only Tickets belonging to me should appear in the search result. 

**Actual behavior:** [What actually happened]

 The search result actually output all the tickets in the system(Even those I should not be able to get access to)

### Versions
1.10

**Comment by Shnoulle** [comment]
I confirm the issue , some request seems OK, for exemple the 'is not' for status.

**Comment by clonemeagain** [comment]
Check your user account's permissions, there is a checkbox under Miscellaneous:

"  Search — See all tickets in search results, regardless of access"

**Comment by darklord1807** [comment]
Hello @clonemeagain. Thanks for the help, but even though it is unticked, it still show up all the tickets in the system. 

Kindly help. 

Thanks,

**Comment by JediKev** [comment]
Hello @darklord1807. When you open any of the tickets is there a Due Date set?
<img width="315" alt="screen shot 2017-07-20 at 11 19 28" src="https://user-images.githubusercontent.com/11823401/28427931-528d5532-6d3d-11e7-82d9-afe9e6f84de5.png">
