### ISSUE TITLE
Advanced search showing no result for custom form field

### ISSUE THREAD

**Issue by julie007** [osTicket/osTicket#3851]
please help me for this issue I m new to Osticket and unable to search tickets for custom form include field.every time it is showing no result but except include like has a value, does not have a value and does not include, it is working fine and tickets are showing.

**Comment by mlemens-como** [comment]
Your probably not going to get any help on this until you supply more detailed information, and a message that makes sense after you are done reading it.

**Comment by ntozier** [comment]
You may want to try posting on the forums.  Please help us to help you by reading and following the posting guidelines located in this thread: [Please read before requesting assistance](http://www.osticket.com/forum/discussion/77765/please-read-before-requesting-assistance#latest).  The more information you give us the better we will be able to assist you. Thank you.

**Comment by julie007** [comment]
Thanks for reply.
 I have an issue while searching tickets from advance tab for custom form include field,
Let me describe you the process
1.Login as agent
2.clicked “[advanced]” button next to the search field, then click “Add Other Field”.
3.Select any value from the custom form list.
4.Select  “includes” and enter any value to search.
5.No results returned.
Even I have tickets from that particular help topic.
Except "include " all(has a value, does not have a value and does not include) working fine for me.
It would be great help for me if someone gives me the solution.
