### ISSUE TITLE
Due date timeset is displayed wrong

### ISSUE THREAD

**Issue by Zuescho** [osTicket/osTicket#3852]
Hi, i have some really weird problem.
![snip-time](https://user-images.githubusercontent.com/13680959/27081990-54791c58-5043-11e7-84b3-d1f0261e5c1d.PNG)

I'm running v1.10(901e5ea)
Everything is vanilla, besides the german de.phar package.

All times around the System are the same and match up, only when creating a ticket the 12h format is still shown. i tried the fix but it only made times double appear.

For reference the fix that i tried. [#1103](https://github.com/osTicket/osTicket/issues/1103)
Problem once "fixed" here [#1060](https://github.com/osTicket/osTicket/issues/1060)

here is a part of my _class.misc.php_ without making any changes.

```
$time = Misc::user2gmtime(mktime(0,0,0));
        ob_start();
        echo sprintf('<select name="%s" id="%s" style="display:inline-block;width:auto">',$name,$name);
        echo '<option value="" selected>'.__('Time').'</option>';
        for($i=23; $i>=0; $i--) {
            for ($minute=45; $minute>=0; $minute-=15) {
                $sel=($hr==$i && $min==$minute)?'selected="selected"':'';
                $_minute=str_pad($minute, 2, '0',STR_PAD_LEFT);
                $_hour=str_pad($i, 2, '0',STR_PAD_LEFT);
                $disp = Format::time($time + ($i*3600 + $minute*60 + 1), false);
                echo sprintf('<option value="%s:%s" %s>%s</option>',$_hour,$_minute,$sel,$disp);
            }
        }
```
![time-2](https://user-images.githubusercontent.com/13680959/27082413-e35c310c-5044-11e7-8f2c-8e37db9c3e0f.PNG)

**Comment by JediKev** [comment]
Hello @Zuescho 
Change 'Zeitformat' from 'hh:mm' to 'HH:mm' then save your changes. Now retest and tell us what happens.

**Comment by Zuescho** [comment]
I'm so dumb.
Its working now, the error really was that hh:mm.
Thank you so much.
