### ISSUE TITLE
Valid CSRF Token Required

### ISSUE THREAD

**Issue by manellen3** [osTicket/osTicket#3853]
Dear osTicket,

I've found a weird thing when I tried to login as agent in `scp/login.php`. The error is

> Valid CSRF Token Required

Does anyone know what I've missed?

Thank in advance.

**Comment by manellen3** [comment]
Dear Team,

The system information as follow:
- 64bit Amazon Linux 2017.03 v2.4.0
- Apache
- PHP 7.0.16
- osTicket version 1.10

I've read some other similar issues but it can't solve my issue. For example, the suggest to clear cache and it doesn't work and osTicket version 1.10 should work on previous PHP 7.1.

Thank in advance.

**Comment by JediKev** [comment]
Hello @manellen3 
Wherever you read "the suggest to clear cache" they are correct, however they left out one detail. You need to delete all cache AND COOKIES then force refresh your login page (yourosticketdomain.com/scp).

**Comment by manellen3** [comment]
Hello @JediKev,

Thanks for your suggestion.

Yes it is work, but my domain looks weird when I tried to force access to agent login at
`http://www.myosticketdomain.com/ticketing/scp`, 
it will redirect to e.g. 
`http://myosticketdomain.ap-southeast-1.elasticbeanstalk.com/ticketing/scp/login.php`
How it come?

And how I need to force login agent to `http://www.myosticketdomain.com/ticketing/scp` instead of the regular one at `http://www.myosticketdomain.com/ticketing/scp/login.php`?

Please assist me where i've missed.
Thank in advance.

**Comment by JediKev** [comment]
> Yes it is work, but my domain looks weird when I tried to force access to agent login at
http://www.myosticketdomain.com/ticketing/scp,
it will redirect to e.g.
http://myosticketdomain.ap-southeast-1.elasticbeanstalk.com/ticketing/scp/login.php
How it come?

This sounds like you haven't registered your own domain name with your server. Take a look at [this link](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/customdomains.html).

As for your **Valid CSRF Token Required** error: https://github.com/osTicket/osTicket/issues/3546

**Comment by manellen3** [comment]
> This sounds like you haven't registered your own domain name with your server. Take a look at this link.

I'll try it

> As for your Valid CSRF Token Required error: #3546

I've follow the steps and it doesn't work for me. I'm trying this one:

`$this->data->session_data = "";`

Any ideas?

**Comment by JediKev** [comment]
>I've follow the steps and it doesn't work for me. I'm trying this one:
>
>$this->data->session_data = "";
>
>Any ideas?

The suggested fix was approved and seemed to fix everyone's issue with CSRF Tokens. Try adding the fix again and run the `REPAIR TABLE` command suggested in the comments here: https://github.com/osTicket/osTicket/commit/424bfc99d93b920f6162b602eeea41125086425d#comments

**Comment by manellen3** [comment]
> $this->data->session_data = "";

It is actually work, it was cache.

Thanks @JediKev
