### ISSUE TITLE
Is it possible for users to comment on knowledgebase articles in osticket

### ISSUE THREAD

**Issue by julie007** [osTicket/osTicket#3854]
hello, 
I want to know that is it possible for end user to comment on knowledgebase  articles....if it is possible than please let me know how to do and where i have to add my coding.

**Comment by julie007** [comment]
okay thanks@JediKev for reply.
but i want to add comment box in user side on Knowledgebase section for their convenience so please can anyone help me for this.
i have added comment box in faq.inc.php and added some code there but while submitting my comment it is redirect me to client/index.php. i am not sure which table i have to use for submitting my comments.
so it would be great if anyone can help me for this.
Thanks in advance

**Comment by JediKev** [comment]
This is a completely custom feature so unfortunately you are on your own.
