### ISSUE TITLE
osTicket issue, ticket form not appearing in front end

### ISSUE THREAD

**Issue by pagedesigner** [osTicket/osTicket#3858]
osTicket issue, ticket form not appearing in front end
im using later version
i have checked forum and goled but not found any answere
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

**Comment by JediKev** [comment]
Please post a screenshot of **Admin Panel > Manage > Forms > Ticket Details Form** and also a screenshot of **Admin Panel > Dashboard > Information**.

**Comment by clonemeagain** [comment]
Also, go back and fill in all those [bits] that are missing from your report.
