### ISSUE TITLE
Nothing can add. Always getting a blank pop up

### ISSUE THREAD

**Issue by alansebastian** [osTicket/osTicket#3859]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch? -- Yes
* [ ] Do you have any errors in the PHP error log, or javascript console? -- No
* [ ] Did you check the [osTicket forums](http://osticket.com/forum/categories)? -- Yes
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported? no

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

In many places button clicks opens blank pop up. For eg: In Users -- Add User, Delete User, New Ticket etc..

### Steps to Reproduce

1. Go to Users
2. Clicks on Add User button

**Expected behavior:** [What you expected to happen] -- User Registration form need to be list

**Actual behavior:** [What actually happened] -- Now we are getting a blank pop up

### Versions
osTicket Version          v1.10 (901e5ea) —  Up to date 
Web Server Software   nginx/1.10.0
MySQL Version           5.7.18
PHP Version                7.0.18-0ubuntu0.16.04.1

![os ticket issue](https://user-images.githubusercontent.com/18212081/27285599-d21f6c26-551a-11e7-93fe-88bb21adda35.png)

**Comment by JediKev** [comment]
You need to check if you are getting any AJAX errors (Chrome Developer Tools is easiest) and post them if you do, also post screenshot of **Admin Panel > Dashboard > Information**.

**Comment by alansebastian** [comment]
The above-mentioned issue fixed by following the link,  https://github.com/osTicket/osTicket/issues/844#issuecomment-42192709

**Comment by JediKev** [comment]
Thank you so much for reporting your fix, it will help a lot of people. 👍
Please close this issue.
