### ISSUE TITLE
User (Sign-In Page) template not being displayed in front end in other language then English.

### ISSUE THREAD

**Issue by raykai** [osTicket/osTicket#3860]
### Prerequisites
* [YES] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [NO] Do you have any errors in the PHP error log, or javascript console?
* [YES] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [YES] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description
 I use fresh installation of osTicket Version v1.10 (901e5ea) with 2 languages English and French configured, I configured Sign-In Page Templates under: **Admin panel >Settings > Users > Templates & Pages > Sign-In Page.** 

<a href="https://ibb.co/c5EJJQ"><img src="https://image.ibb.co/j2uJJQ/b3.jpg" alt="b3" border="0"></a>

Then i click on French flag button and enter my French text I want to see on the French Sign-In Page. Press Save button. 

<a href="https://ibb.co/fi2usk"><img src="https://image.ibb.co/ep19Q5/b4.jpg" alt="b4" border="0"></a>

(Note the Last Updated date and time shown on the Users Settings Templates page will not change if you save when being in the other language but will show the new date and time if you change and save the English language page  BUG?)

<a href="https://ibb.co/hGeqXk"><img src="https://image.ibb.co/cFiHCk/b2.jpg" alt="b2" border="0"></a>

ones you save the French translation text. go to the front-end login page (domain.com/login.php) click on the French flag (or another language) the text will still show the English text. 

<a href="https://ibb.co/eT0ayQ"><img src="https://image.ibb.co/e5rhdQ/b5.jpg" alt="b5" border="0"></a>

**Note:** i did not test the other Users Settings Templates page to see if they all have the same bug.

### Steps to Reproduce

1. [install fresh osTicket Version v1.10 (901e5ea) with 2 languages English and French]
2. [configer French to be the Secondary Languages.]
3. [Go to Admin panel >Settings > Users > Templates & Pages > Sign-In Page.]
4. [configer the French language by clicking on the flag. ]
5. [enter a Title and enter some text in the big text box. for the French language.]
6. [Click on Save button ]
7. [Note that the Last Updated (date and time) for the page you just save did not change.]
8. [go to the user front end]
9. [click on the Sign In button at top right of the screen. (domain.com/login.php)]
10. [click on French flag at the top right of the page (domain.com/login.php?lang=fr) ]
11. [the blue title and first text on the page stays in English even tho you just set up the French text. ]

**Expected behavior:** [What you expected to happen]
when saving a translation for other languages in the user Templates & Pages it should show this text when the user is on that language instead of the main English text.

**Actual behavior:** [What actually happened]
Even if you saved a translation for the Templates & Pages Sign-In Page (i did not test the other Templates & Pages but i guess they would have the same bug.) it will still show on the user front end the English text when the user selects on another language and not show the translated text that has been  set and saved.

### Versions
<a href="https://ibb.co/dpam55"><img src="https://image.ibb.co/nKZ2dQ/os_Ticket_INFO.jpg" alt="os_Ticket_INFO" border="0"></a>

### System:
Running on VPS from OVH:
OS: ‪Ubuntu 16.04.2 LTS‬
Product: 	Plesk Onyx v17.5.3_build1705170317.16 os_Ubuntu 16.04
CPU:  Intel Core Processor (Haswell, no TSX) (1 core(s)) (usage is about 2-3%)
Ram: 2GB

**Comment by JediKev** [comment]
Thanks for the find! I have addressed this issue with pull request: #3878.
