### ISSUE TITLE
Time Formatting - AM / PM Don't Work

### ISSUE THREAD

**Issue by dotcade** [osTicket/osTicket#3861]
### Description

When trying to change the time in Settings>System the 'a' format does not display am or pm in the agent panel. Screenshots replicating the issue are below.

### Steps to Reproduce

1. Settings>System> Date and Time Format
2. Add 'a' to any of the fields ending in Time Format.

**Expected behavior:** Time in agent panel shows with an am/pm at the end.

**Actual behavior:** It displays nothing.

### Server Information
osTicket Version: v1.10 (901e5ea) —  Up to date
Web Server Software: Microsoft-IIS/8.5
MySQL Version: 5.7.13
PHP Version: 7.1.6 (We've had this issue while on PHP5 too)

### Relevant PHP Settings
date.timezone: America/Chicago

### Relevant Database Information and Usage
Timezone: Central Standard Time (Interpreted as America/Chicago)

### Screenshots
**System Settings without 'a':**
![system settings 1](https://user-images.githubusercontent.com/1711492/27358894-642ee5ce-55de-11e7-9139-7ccbd7c1e854.PNG)
**Agent Panel without 'a':**
![agent 1](https://user-images.githubusercontent.com/1711492/27358931-8ba2e90c-55de-11e7-8ffa-f50ee93b11c7.PNG)

**System Settings with 'a':**
![system settings 2](https://user-images.githubusercontent.com/1711492/27358916-74ff0a32-55de-11e7-9b1b-13a52e57fd46.PNG)
**Agent Panel with 'a':**
![agent 2](https://user-images.githubusercontent.com/1711492/27358956-ac2269fa-55de-11e7-84de-092cdc28ef54.PNG)

**PHP INI**
![php ini](https://user-images.githubusercontent.com/1711492/27358973-b8ebd3e2-55de-11e7-8ea5-3e34f90862f0.PNG)

Note: When I set 'Date and Time Format' to 'Locale Defaults' it still displays without am/pm at the end.

**Comment by JediKev** [comment]
Do you get any errors in your error logs? My date/time is working just fine on a CentOS server, so I'm thinking it has something to do with your PHP configuration or IIS configuration.

**Date/Time Settings:**
<img width="940" alt="screen shot 2017-06-22 at 16 42 27" src="https://user-images.githubusercontent.com/11823401/27457304-d7c354ac-5769-11e7-91a7-0b8f09dce2f9.png">

**Date/Time displayed:**
<img width="157" alt="screen shot 2017-06-22 at 16 42 41" src="https://user-images.githubusercontent.com/11823401/27457309-db1e5034-5769-11e7-810f-6a88312d3b1a.png">

**Comment by dotcade** [comment]
@JediKev Here are my error logs, no mention of time from what I can see: 
[error logs.txt](https://github.com/osTicket/osTicket/files/1098577/error.logs.txt)

and here is proof that regular php time works fine:
![time](https://user-images.githubusercontent.com/1711492/27493775-b48bf618-5810-11e7-8269-f10eab9478ef.PNG)
![timesource](https://user-images.githubusercontent.com/1711492/27493776-b49afe1a-5810-11e7-9998-be0334da9a7b.PNG)

**Comment by JediKev** [comment]
I have tested this on:
- CentOS 7 (PHP: 5.4, MariaDB: 5.5.0, Apache: 2.4.6, osT: 1.10)
- Ubuntu 16.04 (PHP: 7.0.18, MySQL: 5.7.18, Apache: 2.4.18, osT: 1.10)

Both of them displayed the `AM/PM` just fine. I'm guessing this issue is IIS specific or maybe the way your PHP is configured..? When you add the `a` to the **Date and Time Format** and save changes, what is the value of the key `datetime_format` under the table `ost_config`?

**Comment by dotcade** [comment]
@JediKev It seems like they aren't being updated in the table.

![test](https://user-images.githubusercontent.com/1711492/27600150-9ed3e178-5b30-11e7-9e15-0e8fa22df0cf.PNG)

**Comment by JediKev** [comment]
Let's try adding the 'a' to the formats in your `php.ini`. Once you add them, save your changes, restart IIS, and retest!

**Comment by JediKev** [comment]
Ok, can you try two things for me?
1.) Install and enable PHP's Internationalization extension. (php_intl)
2.) Change the Time Format Settings in osTicket to the following:
```shell
Date and Time Format: Advanced
Time Format: h:mma
Date Format: MM/dd/yy
Date and Time Format: MM/dd/yy h:mma
Day, Date and Time Format: EEE, MMM d yy h:mma
```

**Comment by dotcade** [comment]
@JediKev That worked, thank you!
