### ISSUE TITLE
Archiving and deletion of old tickets 

### ISSUE THREAD

**Issue by sarshhfox** [osTicket/osTicket#3862]
Hi guys, any updates on the feature/plugin for archival and deletion of old tickets?

### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

v1.9.12 (19292ad)

Apache/2.4.7 (Ubuntu)

**Comment by clonemeagain** [comment]
I wrote a mod for this back in the day (1.7), and have been working on upgrading it to 1.10, I'll post here when it's done if you like. 

http://osticket.com/forum/discussion/75386/mod-archive-delete-old-tickets

It's being implemented as a plugin.

**Comment by sarshhfox** [comment]
Many thanks @clonemeagain. 
Yes, would really appreciate if you can please post in here as soon its done in the latest 1.10.

**Comment by clonemeagain** [comment]
Almost there.. https://github.com/clonemeagain/osticket-plugin-archiver/milestone/1

**Comment by sarshhfox** [comment]
Thanks mate. Really appreciate it.
