### ISSUE TITLE
Call to undefined method Task::getEstDueDate()

### ISSUE THREAD

**Issue by Staja** [osTicket/osTicket#3864]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [x] Do you have any errors in the PHP error log, or javascript console?
* [ ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

PHP Fatal error:  Call to undefined method `Task::getEstDueDate()` in .\include\class.task.php on line 1017

### Steps to Reproduce

1. Create New Task Alert template in active Email Template Set which includes the variable `%{task.due_date}`
2. Create New Task

**Expected behavior:** [What you expected to happen]
No PHP Fatal Error

**Actual behavior:** [What actually happened]
PHP Fatal Error

### Versions
osTicket v1.10

**Comment by Staja** [comment]
I'm guessing the calling should be:
Line 1017 `if ($due = $this->getDueDate())`

**Comment by JediKev** [comment]
You are correct, thanks for the find!

**Comment by Staja** [comment]
This still hasn't been fixed.
