### ISSUE TITLE
osTicket not working correctly with Dutch Language Pack.

### ISSUE THREAD

**Issue by Bram0194** [osTicket/osTicket#3865]
### Description

When using the Dutch Language pack, I am unable to open sub-tabs under admin panel > settings >any category. Also, the categorys of which i cant open the tabs, are missing the save settings/reset button.

### Steps to Reproduce

1. Start a fresh install of osTicket v1.10, place nl.phar inside i18n folder
2. Go to install.php, choose Dutch from the language dropdown menu
3. Install
4. Go to admin panel
5. Cant open tabs and some save settings/reset buttons are missing.

**Expected behavior:** [What you expected to happen]
Able to open the tab and configure settings.

**Actual behavior:** [What actually happened]
Nothing happens when you click the tab.

### Versions
osTicket v1.10 (901e5ea)
PHP 7.0.18-0ubuntu0.16.04.1
MySQL 5.7.18
Webserver Apache/2.4.18 (Ubuntu)

Using Windows 10, tried Chrome, and Internet Explorer on multiple machines. Also tried the installations on ubuntu 16.04 using apache and php7.0, and on XAMPP which both have the same results.

### logs

this DB error log is in my osticket but im not sure if it has anything to do with my problem.
` DB Error #1146
[SELECT A4.`staff_id` AS `lock__staff_id`, A1.`staff_id` AS `staff_id`, A1.`isoverdue` AS `isoverdue`, A1.`team_id` AS `team_id`, A1.`ticket_id` AS `ticket_id`, A1.`number` AS `number`, A2.`subject` AS `cdata__subject`, A6.`address` AS `user__default_email__address`, A1.`source` AS `source`, A3.`priority_color` AS `cdata__:priority__priority_color`, A3.`priority_desc` AS `cdata__:priority__priority_desc`, A1.`status_id` AS `status_id`, A7.`name` AS `status__name`, A7.`state` AS `status__state`, A1.`dept_id` AS `dept_id`, A8.`name` AS `dept__name`, A5.`name` AS `user__name`, A1.`lastupdate` AS `lastupdate`, A1.`isanswered` AS `isanswered`, B0.`firstname` AS `staff__firstname`, B0.`lastname` AS `staff__lastname`, B1.`name` AS `team__name`, (SELECT COUNT(R0.`id`) AS `count` FROM `ost_thread` Q7 JOIN `ost_ticket` Q8 ON (Q7.`object_type` = 'T' AND Q7.`object_id` = Q8.`ticket_id`) LEFT JOIN `ost_thread_collaborator` R0 ON (Q7.`id` = R0.`thread_id`) WHERE Q8.`ticket_id` = A1.`ticket_id`) AS collab_count, (SELECT COUNT(R1.`id`) AS `count` FROM `ost_thread` Q7 JOIN `ost_ticket` Q8 ON (Q7.`object_type` = 'T' AND Q7.`object_id` = Q8.`ticket_id`) LEFT JOIN `ost_thread_entry` R0 ON (Q7.`id` = R0.`thread_id`) LEFT JOIN `ost_attachment` R1 ON (R1.`type` = 'H' AND R0.`id` = R1.`object_id`) WHERE Q8.`ticket_id` = A1.`ticket_id` AND R1.`inline` = 0) AS attachment_count, (SELECT COUNT(R0.`id`) AS `count` FROM `ost_thread` Q7 JOIN `ost_ticket` Q8 ON (Q7.`object_type` = 'T' AND Q7.`object_id` = Q8.`ticket_id`) LEFT JOIN `ost_thread_entry` R0 ON (Q7.`id` = R0.`thread_id`) WHERE Q8.`ticket_id` = A1.`ticket_id` AND NOT R0.`flags` & 4 != 0) AS thread_count FROM `ost_ticket` A1 LEFT JOIN `ost_ticket__cdata` A2 ON (A1.`ticket_id` = A2.`ticket_id`) LEFT JOIN `ost_ticket_priority` A3 ON (A2.`priority` = A3.`priority_id`) LEFT JOIN `ost_lock` A4 ON (A1.`lock_id` = A4.`lock_id` AND A4.`expire` > NOW()) JOIN `ost_user` A5 ON (A1.`user_id` = A5.`id`) LEFT JOIN `ost_user_email` A6 ON (A5.`default_email_id` = A6.`id`) JOIN `ost_ticket_status` A7 ON (A1.`status_id` = A7.`id`) JOIN `ost_department` A8 ON (A1.`dept_id` = A8.`id`) LEFT JOIN `ost_staff` B0 ON (A1.`staff_id` = B0.`staff_id`) LEFT JOIN `ost_team` B1 ON (A1.`team_id` = B1.`team_id`) WHERE A1.`ticket_id` IN (SELECT A1.`ticket_id` FROM `ost_ticket` A1 JOIN `ost_ticket_status` A2 ON (A1.`status_id` = A2.`id`) WHERE A2.`state` = 'open' AND ((A2.`state` = 'open' AND A1.`staff_id` = 1) OR A1.`dept_id` IN ('1'))) GROUP BY A4.`staff_id`, A1.`staff_id`, A1.`isoverdue`, A1.`team_id`, A1.`ticket_id`, A1.`number`, A2.`subject`, A6.`address`, A1.`source`, A3.`priority_color`, A3.`priority_desc`, A1.`status_id`, A7.`name`, A7.`state`, A1.`dept_id`, A8.`name`, A5.`name`, A1.`lastupdate`, A1.`isanswered`, B0.`firstname`, B0.`lastname`, B1.`name` ORDER BY A3.`priority_urgency` ASC, A1.`lastupdate` DESC] Table 'osticket_db1.ost_ticket__cdata' doesn't exist

 ---- Backtrace ----
 #0 (root)/include/mysqli.php(204): osTicket->logDBError('DB Error #1146', '[SELECT A4.`sta...')
 #1 (root)/include/class.orm.php(3133): db_query('SELECT A4.`staf...', true, true)
 #2 (root)/include/class.orm.php(3180): MySqlExecutor->execute()
 #3 (root)/include/class.orm.php(1865): MySqlExecutor->getArray()
 #4 (root)/include/class.orm.php(1815): HashArrayIterator->{closure}()
 #5 (root)/include/class.orm.php(1794): CallbackSimpleIterator->next()
 #6 (root)/include/class.orm.php(1803): CallbackSimpleIterator->rewind()
 #7 (root)/include/class.orm.php(1463): CallbackSimpleIterator->valid()
 #8 (root)/include/class.orm.php(1480): CachedResultSet->fillTo(9223372036854775807)
 #9 (root)/include/class.orm.php(1489): CachedResultSet->asArray()
 #10 (root)/include/staff/tickets.inc.php(506): CachedResultSet->getIterator()
 #11 (root)/scp/tickets.php(492): require_once('/var/www/html/o...')
 #12 {main}

Logdatum: 06/23/2017 11:59:59 AM IP-adres: 192.168.1.101`

**Comment by ntozier** [comment]
Please downgrade MySQL to any version pre 5.7 and see if that helps.
Also a lot of people on the forums have reported issues with running XAMPP I presume its something to do with how they configure things.  I always recommend that people install their own software rather than have someone else package it together and install that when it comes to osTicket..

**Comment by Bram0194** [comment]
I appreciate your reply, however the exact same error occurs using our own ubuntu 16.04 server. I can't downgrade MySQL due to other applications running on the server.

**Comment by ntozier** [comment]
Then I guess that I cannot assist in troubleshooting this then.  Maybe one of the devs will be able to.

**Comment by JediKev** [comment]
Yea I just installed the Dutch Language Pack on my v1.10 install on a CentOS server and it's working just fine. Please post a screenshot of **Admin Panel > Dashboard > Information**.

**Comment by Bram0194** [comment]
https://www.screencast.com/t/hiPiOFy2

**Comment by JediKev** [comment]
Try installing PHP's intl extension, restart your apache, reinstall the language pack and retry.

**Ubuntu (PHP 7.0):**
```shell
$ sudo apt-get install php7.0-intl
```

**Comment by Bram0194** [comment]
Just did. Nothing changed sadly..
Thank you.

**Comment by JediKev** [comment]
Are you getting any errors in your PHP or Apache error logs when you click a tab that won't work?

**Comment by Bram0194** [comment]
Where are those logs located? Using ubuntu 16.04 with php7 and apache2

**Comment by JediKev** [comment]
https://askubuntu.com/questions/14763/where-are-the-apache-and-php-log-files

**Comment by Bram0194** [comment]
Looks like this is appearing whenever I click on the not-working tabs.


`[Fri Jun 23 16:16:58.298932 2017] [:error] [pid 21861] [client 192.168.1.101:22437] PHP Warning:  Declaration of AssignmentForm::render($options) should be compatible with Form::render($staff = true, $title = false, $options = Array) in$
[Fri Jun 23 16:16:58.298985 2017] [:error] [pid 21861] [client 192.168.1.101:22437] PHP Warning:  Declaration of TransferForm::render($options) should be compatible with Form::render($staff = true, $title = false, $options = Array) in /$
[Fri Jun 23 16:17:01.829197 2017] [:error] [pid 21861] [client 192.168.1.101:22437] PHP Fatal error:  Uncaught InvalidArgumentException: List indices should be integers in /var/www/html/osticket2/include/class.util.php:149\nStack trace:$
[Fri Jun 23 16:17:09.998825 2017] [:error] [pid 21870] [client 192.168.1.101:22440] PHP Fatal error:  Uncaught InvalidArgumentException: List indices should be integers in /var/www/html/osticket2/include/class.util.php:149\nStack trace:$
[Fri Jun 23 16:17:12.975869 2017] [:error] [pid 21870] [client 192.168.1.101:22440] PHP Fatal error:  Uncaught InvalidArgumentException: List indices should be integers in /var/www/html/osticket2/include/class.util.php:149\nStack trace:$
[Fri Jun 23 16:20:18.783921 2017] [:error] [pid 21865] [client 192.168.1.101:22567] PHP Fatal error:  Uncaught InvalidArgumentException: List indices should be integers in /var/www/html/osticket2/include/class.util.php:149\nStack trace:$
[Fri Jun 23 16:20:23.018114 2017] [:error] [pid 21871] [client 192.168.1.101:22568] PHP Warning:  Declaration of AssignmentForm::render($options) should be compatible with Form::render($staff = true, $title = false, $options = Array) in$
[Fri Jun 23 16:20:23.018160 2017] [:error] [pid 21871] [client 192.168.1.101:22568] PHP Warning:  Declaration of TransferForm::render($options) should be compatible with Form::render($staff = true, $title = false, $options = Array) in /$
[Fri Jun 23 16:20:23.854058 2017] [:error] [pid 21872] [client 192.168.1.101:22569] PHP Fatal error:  Uncaught InvalidArgumentException: List indices should be integers in /var/www/html/osticket2/include/class.util.php:149\nStack trace:$
[Fri Jun 23 16:20:24.428422 2017] [:error] [pid 21872] [client 192.168.1.101:22569] PHP Fatal error:  Uncaught InvalidArgumentException: List indices should be integers in /var/www/html/osticket2/include/class.util.php:149\nStack trace:$
[Fri Jun 23 16:20:24.964045 2017] [:error] [pid 21872] [client 192.168.1.101:22569] PHP Fatal error:  Uncaught InvalidArgumentException: List indices should be integers in /var/www/html/osticket2/include/class.util.php:149\nStack trace:$
[Fri Jun 23 16:20:25.363825 2017] [:error] [pid 21872] [client 192.168.1.101:22569] PHP Fatal error:  Uncaught InvalidArgumentException: List indices should be integers in /var/www/html/osticket2/include/class.util.php:149\nStack trace:$
[Fri Jun 23 16:20:25.628434 2017] [:error] [pid 21872] [client 192.168.1.101:22569] PHP Fatal error:  Uncaught InvalidArgumentException: List indices should be integers in /var/www/html/osticket2/include/class.util.php:149\nStack trace:$
[Fri Jun 23 16:20:25.860374 2017] [:error] [pid 21872] [client 192.168.1.101:22569] PHP Fatal error:  Uncaught InvalidArgumentException: List indices should be integers in /var/www/html/osticket2/include/class.util.php:149\nStack trace:$`

**Comment by JediKev** [comment]
You are downloading the latest language pack from [http://osticket.com/download](http://osticket.com/download), right?

**Comment by Bram0194** [comment]
Yes I am.

**Comment by Bram0194** [comment]
Also a weird thing I noticed is that if I prepare a full clean install, put the nl.phar inside the i18n folder, open osticket/setup/install.php and then I see English and Dutch in the dropdown menu. If I choose English, it still installs in Dutch but not everything is translated. stuff like priorities and templates  are not translated, but most pages are dutch. The tabs are working then. Very weird.

**Comment by JediKev** [comment]
Wait....you are _installing_ osTicket under a different language?? Or just installing a new language on osTicket?

**Comment by Bram0194** [comment]
I want osTicket to be fully in Dutch. I am installing osTicket with the Dutch language pack.

**Comment by JediKev** [comment]
That's your issue. You have to install osTicket in English with no language packs THEN install the language pack after you install and configure osTicket.

**Comment by Bram0194** [comment]
Are you sure? Ntozier said different here: http://osticket.com/forum/discussion/84873/how-to-set-global-default-language

**Comment by Bram0194** [comment]
Also, if I install osTicket in Dutch, absolutely everything is translated. When I use language pack afterwards basically nothing is.

**Comment by JediKev** [comment]
After you install osTicket, you install the language pack. After the install of the pack you go to **Admin Panel > Settings > System** and change **Primary Language** to **Dutch**. If it saves and nothing is translated clear all your cache and reload the page. Now your whole system will be in Dutch 😄

**Comment by ntozier** [comment]
@JediKev previously JAred has posted saying that if people want to use a language pack they should install it at the time of installation and select it because there were some things that were not being handled gracefully (aka working right) when it was installed after the fact if they wanted it to be the Default language out of the box.

**Comment by JediKev** [comment]
I did not know this, where did he post this? I've heard nothing but issues when installing with a language pack lol

**Comment by Bram0194** [comment]
@JediKev @ntozier When I do it as you said JediKev. Not everything is translated. Things such as priority levels, help topics and stuff are not translated. https://www.screencast.com/t/rkaB1ySf6

**Comment by Bram0194** [comment]
And when I do it @ntozier way, the tabs dont work. Should I just live with the fact that not everything is translated?

**Comment by JediKev** [comment]
>Should I just live with the fact that not everything is translated?

No, because those words are actually translated in the language pack but not showing up as translated.

>And when I do it @ntozier way, the tabs dont work.

I'll get these errors and look over them with the other developers. This shouldn't be happening.

**Comment by JediKev** [comment]
Okay, so I just installed a new osTicket v1.10 with the Dutch language chosen and everything is translated/working fine...I would suggest trying to downgrade PHP to 5.6 or MySQL to pre-5.7.
My PHP: version 5.6
My MariaDB: version 5.5.50

**Comment by Bram0194** [comment]
I could try downgading PHP. I can't modify the MySQL installation sadly.

**Comment by JediKev** [comment]
Please do that and get back to us!

>I can't modify the MySQL installation sadly.

I saw that previously, I just mentioned it because that's the only two suggestions I have right now.

**Comment by Bram0194** [comment]
Apparently PHP5 is not available for Ubuntu 16.04

**Comment by JediKev** [comment]
It is available for 16.04, you just have to add a repository that has it first. You can google "how to install PHP 5.6 on Ubuntu 16.04" and many sites will pop up. Make sure you add a trusted and popular repository for best results.

**Comment by JediKev** [comment]
I'll have to install Ubuntu and test then. All is fine on CentOS.

**Comment by Bram0194** [comment]
Please try and let me know! it wont take long for you, it took me like 20 mins to set this up at home to test it. let me know! I cant wait to know whats causing this

**Comment by Bram0194** [comment]
Here more people with the same problem:

http://osticket.com/forum/discussion/89665/missing-save-button-in-settings-tickets

http://osticket.com/forum/discussion/90096/button-save-changes-is-missing-on-ticket-settings
(This guy gives a solution but I don't really get it)

http://osticket.com/forum/discussion/89462/tabs-ticket-configuration-doesn-t-have-save-button

**Comment by JediKev** [comment]
Okay so after some testing I have concluded the following:
- Ubuntu 16.04 (or CentOS 7) osTicket v1.10 installed in English works just fine, everything is perfect.
- Ubuntu 16.04 (or CentOS 7) osTicket v1.10 installed in Dutch (or any other language, also tested in Norwegian) messes up a lot. Some forms/fields are not generated, some buttons are non-functional, and much much more.

I need to see if this is a PHP issue or an osTicket installer issue.

**Ubuntu 16.04 (English):**
<img width="864" alt="screen shot 2017-06-23 at 15 40 23" src="https://user-images.githubusercontent.com/11823401/27500133-a4d70cd2-582c-11e7-91c2-51c8fc01e595.png">
<img width="962" alt="screen shot 2017-06-23 at 15 55 49" src="https://user-images.githubusercontent.com/11823401/27500139-ae184d06-582c-11e7-9074-2d00e2e8aa6b.png">

**Ubuntu 16.04 (Dutch):**
<img width="768" alt="screen shot 2017-06-23 at 15 40 45" src="https://user-images.githubusercontent.com/11823401/27500141-b08faea8-582c-11e7-8cc8-c2d95d7a7803.png">
<img width="959" alt="screen shot 2017-06-23 at 15 56 07" src="https://user-images.githubusercontent.com/11823401/27500145-b8993d4e-582c-11e7-9736-5af94bc72d4b.png">

**CentOS 7 (Dutch):**
<img width="960" alt="screen shot 2017-06-23 at 16 06 33" src="https://user-images.githubusercontent.com/11823401/27500435-2158a7b0-582e-11e7-848c-5879e551a0e1.png">
<img width="960" alt="screen shot 2017-06-23 at 16 06 54" src="https://user-images.githubusercontent.com/11823401/27500439-24dfa8de-582e-11e7-9208-009dfa25cd5a.png">

**Comment by Bram0194** [comment]
Okay, but if I want to set up a Dutch ticket system I'm better off choosing something else then osticket for now? Any suggestions?

**Comment by JediKev** [comment]
No I would use osTicket. It'd be a little bit of a manual process to be fully translated but I think you'd love the system once completed. I would install in English, install language pack, then translate every form, template, help topic and system page (Admin Panel > Manage > Pages) that isn't translated. Once a fix is out you can reinstall in Dutch and import your old data! I apologize that the different language install is borked right now.

**Comment by Bram0194** [comment]
Alright, how does the importing work and when do you estimate a fix?

**Comment by gabrielmsf** [comment]
I did this in Portuguese, didn't know that I could install already translated. In an hour, maybe less, it was all translated. worth it

**Comment by JediKev** [comment]
@Bram0194 - importing is easy, you'll dump the data from the old database via MySQL dump command and then import the dump into the new database via MySQL import command. I don't have an estimated fix date as this will take a while to debug and sort through.

@gabrielmsf - That's great to hear!

**Comment by Bram0194** [comment]
@gabrielmsf you mean you did the manual translating of everything that failed to translate?

@jedikev alright. I thought translated data was installed in the MySQL database too, or is that the case? Can u be more detailed? I'd love to understand the process. Thanks so much

**Comment by gabrielmsf** [comment]
@Bram0194 yeah, it´s not that much...

**Comment by Bram0194** [comment]
@gabrielmsf ok! Did you translate the ticket priority levels too for example via mysql database?

**Comment by JediKev** [comment]
>@JediKev alright. I thought translated data was installed in the MySQL database too, or is that the case? Can u be more detailed? I'd love to understand the process. Thanks so much

When you install in English then translate afterwards, _most_ non-translated data is data in the database. Once you translate everything manually (Help Topics, Templates, etc.), all data in the db will be translated. Once a fix is out you reinstall in Dutch then import all your old data to the new Dutch system. Since your data was translated previously it will remain translated and since you installed in Dutch the entire system will be in Dutch. Does that make sense?

**Comment by Bram0194** [comment]
It does. I get that some of my translationd will be a little differebt than what the fixed translation will be like. Will this be some kind if problem that will cause conflicts or anything like that?

Example of manual translate: osticketdb > ost_priority (i think thats what the table is called) > priority_desc. I change High to Hoog and it will be fine? Or do I need to change something else than the "priority_desc"? I tried this yesterday and when I selected English language pack in settings again, the manual translated words were still dutch.

Sorry if im confusing!

**Comment by Bram0194** [comment]
@greezybacon @rayfoss Hi guys, could anyone give me some advice on how to proceed with this? I'd love to keep using osticket.

**Comment by JediKev** [comment]
@Bram0194 You'll be happy to know that we have finally found a fix. I have been looking through so many files and functions over the past few weeks and realized that the files downloaded from Crowdin are not formatted correctly. With incorrectly formatted files the installation script can't read them properly and it freaks out. We should be updating the files very soon and I'll let you know when we do!

Cheers.

**Comment by Trebornide** [comment]
Hi!
I'm about to set up a site in "swedish only" and would love to see working non english installation work :)
@JediKev: Any update available on the statement  "We should be updating the files very soon" ?

**Comment by JediKev** [comment]
@Trebornide still waiting. Will post here when I have updates.

**Comment by mikelgusev** [comment]
Copying without comma “,” before FROM to MySQL CLI and run make my day.

**Comment by ohmer1** [comment]
So you found what's the problem a year ago and the bug is still not resolved?  

Is there a workaround? Installing in english and changing the language after is not because the in-database data still in english.

Is it fixed in 1.11-rc? I'm willing to use that version if it is fixed. Where can I download the language pack for this version?

**Comment by JediKev** [comment]
@ohmer1 

Not fixed yet...we've been busy addressing much bigger issues and doing a whole lot of other things.  Will revisit this in time. Stay tuned!

Cheers.

**Comment by Trebornide** [comment]
Pleased to see this issue comimg to life again. As long as it is not fixed we will have to stick to a simple shared mail-box. Sigh... Pls let us in the non-english world in to use OSTicket in our native language again :)

**Comment by JediKev** [comment]
@Trebornide 

There is a workaround already posted...simply install osTicket in English then install the language pack afterwards...then you can simply generate all email templates in the chosen language and everything should be translated...what's not translated you can translate yourself as the code is free and open source.

Cheers.

**Comment by ohmer1** [comment]
Can you say what's wrong with the Crowdin files? Maybe I could manually fix them?

**Comment by JediKev** [comment]
@ohmer1 

Changed formatting. We are looking into changing the way we read the format and/or changing the format of the files.

Cheers.

**Comment by ohmer1** [comment]
Is  there a way I can help by contributing some code?
