### ISSUE TITLE
Can't set time to 24h format

### ISSUE THREAD

**Issue by Bram0194** [osTicket/osTicket#3866]
### Description

When setting time format to 24h in Admin portal settings, it doesn't do anything. Everrything stays in AM/PM format.

### Steps to Reproduce

1. Go to admin panel > settings > system
2. Set date and time format to Local defaults, 24h time format.
3. Nothing changes.

**Expected behavior:** [What you expected to happen]
Time such as ticket creation time displays in 24h format.

**Actual behavior:** [What actually happened]
Time such as ticket creation time still displays in AM/PM 12h format.

### Versions
osTicket Version	v1.10 (901e5ea) —  Up to date
Web Server Software	Apache/2.4.18 (Ubuntu)
MySQL Version	5.7.18
PHP Version	5.6.30-12~ubuntu16.04.1+deb.sury.org+1

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.
Windows 10, Chrome.

**Comment by ntozier** [comment]
And whats your Agent Time Format set to in the account profile?

**Comment by Bram0194** [comment]
Hi ntozier,

You mean this? https://www.screencast.com/t/FQ9v366X Tried both options but it did not make a difference.
I was able to fix this problem though by setting this in admin panel:

https://www.screencast.com/t/Vrk4jv9gf
