### ISSUE TITLE
Images on Page not showing

### ISSUE THREAD

**Issue by Bram0194** [osTicket/osTicket#3869]
### Description

Image on the ''We are offline'' page is not showing up correctly.

### Steps to Reproduce

Add image on Offline Page.

**Expected behavior:** [What you expected to happen]
Expect image to show up correctly.
**Actual behavior:** [What actually happened]
Image doesnt show up correctly. See: https://www.screencast.com/t/IIR9uKRB
### Versions

osTicket versie	v1.10 (901e5ea) —  Bij de tijd
Web Server Software	Apache/2.4.18 (Ubuntu)
MySQLversie	5.7.18
PHPversie	5.6.30-12~ubuntu16.04.1+deb.sury.org+1
Admin panel -> Dashboard -> Information which also additionally gives you information about you server.

Using Windows 10. Browser doesn't matter, tried IE, Chrome, Firefox.

**Comment by ntozier** [comment]
Ummm.  There is no image on that page by default, so did you add one?

**Comment by PeopleInside** [comment]
Maybe is for this issue?
https://github.com/osTicket/osTicket/pull/3469

**Comment by Bram0194** [comment]
Yeah I added one through here as you can see: https://www.screencast.com/t/XtFSpz9J85wX

**Comment by ntozier** [comment]
Then please see: #3469

**Comment by Bram0194** [comment]
Thank you. I don't really know what to do right now. First time using github.

**Comment by ntozier** [comment]
You can do one of the following: 
- download the 15 files that the Pull Request updated
- wait until 1.11 is released with the updated code
- Manually make the edits to the 15 files that the Pull Request updated

**Comment by Bram0194** [comment]
Ok thanks! Will try option 1.

**Comment by ntozier** [comment]
It looks like you have to click on Files Changed.
then view each file and save it.  I dont see the option to download all the changed files at once.

**Comment by Bram0194** [comment]
I am doing it right now :) Will post back. Do you know if this problem https://github.com/osTicket/osTicket/issues/3865 has a pull request or that if the devs plan on fixing this issue?

**Comment by ntozier** [comment]
If it does then it is linked in the comment thread.

**Comment by Bram0194** [comment]
I replaced all the 15 files, restarted apache and re-added the image to the offline page but it still doesn't show up correclty.

**Comment by PeopleInside** [comment]
Please @Bram0194  use an incognito window because you may have old cache in the browser.

**Comment by Bram0194** [comment]
I did that. I even tried on another PC and tried Ctrl+f5. No difference.

**Comment by JediKev** [comment]
Thanks for the find! I have submitted a Pull request that should fix your issue. 👍
Please make the changes in the pull request and let me know if it fixes this!

**Comment by JediKev** [comment]
@Bram0194 did my pull request fix your issue? If so, can you please close this issue?
