### ISSUE TITLE
Server disables LOGIN, no recognized SASL authenticator

### ISSUE THREAD

**Issue by Siriuo** [osTicket/osTicket#3870]
Hi,

I seem to be getting the message "Server disables LOGIN, no recognized SASL authenticator" every time osticket checks for emails. 

Nothing has changed in terms of settings on the web server or our exchange 2010 server.

Any suggestions on how I can resolve this?

PHP - Version 5.6.30

Regards

**Comment by ntozier** [comment]
https://github.com/osTicket/osTicket/issues/1367

**Comment by Siriuo** [comment]
I have indeed performed a telnet from the web server to the exchange server and that works correctly. I can also confirm the firewall is not the issue as I have specifically disabled windows firewall to confirm.

In terms of the setup everything is installed via yum's remi repo and everything has been working completely on Friday afternoon.

In terms of php error log displayed is: PHP Warning:  mail(/home/root/logs): failed to open stream: No such file or directory in /var/www/html/domain.co.uk/ticket/include/pear/Mail/mail.php on line 156, referer: https://domain.co.uk/ticket/scp/emails.php?id=7

**Comment by Siriuo** [comment]
Think I may have found a solution. Looks like something to do with the imap authentication setting within exchange.
