### ISSUE TITLE
Edición de un ticket

### ISSUE THREAD

**Issue by dgismondi** [osTicket/osTicket#3871]
Hola, al editar un ticket el sistema cierra sesión y vuelve al inicio para login. Es incomodo y no se si es bug o configuración. Gracias !

v1.10

**Comment by ntozier** [comment]
Google Translate:
Hello, when editing a ticket the system closes session and returns to the beginning to login. It is uncomfortable and I do not know if it is a bug or configuration. Thank you !

V1.10
END Google Translate

Do you mean this?
https://github.com/osTicket/osTicket/issues/3454

**Comment by dgismondi** [comment]
Hola, he leido el caso pero en mi hosting la versión mas reciente de php es 5.6. Alguna sugerencia ??


gracias

**Comment by ntozier** [comment]
Google Translate: 
Hello, I have read the case but in my hosting the latest version of php is 5.6. Any suggestions ??
END Google Translate

I would recommend adding your information to the existing thread and close this duplicate one.
