### ISSUE TITLE
Avoid saving dates/timestamps with value 0000-00-00 00:00:00

### ISSUE THREAD

**Issue by lourdas** [osTicket/osTicket#3873]
I've successfully installed v.1.10 in a server of mine, however, at the periodic scheduled task of backing up and analyzing the database (it's in InnoDB format), the analyzing fails because it finds timestamps with 0000-00-00 00:00:00 values. It fails in three tables so far, ost_thread_entry, ost_ticket_status and ost_sequence. The sql mode for the MariaDB 5.5 database is:

`NO_AUTO_VALUE_ON_ZERO, STRICT_TRANS_TABLES, NO_ZERO_DATE, ERROR_FOR_DIVISION_BY_ZERO, NO_AUTO_CREATE_USER, NO_ENGINE_SUBSTITUTION`

MySQL is not famous for storing valid data, but that doesn't mean the developers should code with invalid data like 0000-00-00 00:00:00 in their application logic. So, I suggest using NULL values for these cases where 0000-00-00 00:00:00 is stored.

Thanks.

**Comment by lourdas** [comment]
And the resolution of this issue is...?

**Comment by robintoy** [comment]
Nothing has been fixed, @JediKev is just spaming the crap out of people and I have reported him for abuse

**Comment by JediKev** [comment]
@lourdas 

This has been closed due to it being older than a year and hasn't been updated in a year. If this is still an issue please reopen.

Cheers.
