### ISSUE TITLE
Valid CSRF Token Required Error

### ISSUE THREAD

**Issue by ClepToManix** [osTicket/osTicket#3879]
Hello,

i installed a fresh instance of osticket 1.10 on my ubuntu 16.04 with php 7.1
After the installationwizard i get an error while logging in scp.

I have found no solution that works for me. I read about to change the php version but this is not possible for me because my other systems need php 7.1

Hope anyone can help me

**Comment by ntozier** [comment]
osTicket is not compatible with PHP7.1.x at this time.
Downgrade your PHP to 7.0.x or even better 5.6.x, or install a second version.
(You can have more than one version of osTicket installed.)

**Comment by ClepToManix** [comment]
Okay thank you, solution works for me :)
