### ISSUE TITLE
Custom form only for admins!

### ISSUE THREAD

**Issue by jighem** [osTicket/osTicket#3880]
Is it possible to create custom form only for staff who are admin can update?
Tried with custom form but general staff also can update the same in the ticket.

for e.g. internal rating to be added for each ticket which will be checked by Team Leaders and then update their comment and rating for the support given in the ticket.

These scores should not be editable by general staff only admin should have access.

Please help me someone in this regard.

**Comment by JediKev** [comment]
At this time you cannot restrict custom forms to **Admin Agents**. You can only restrict them to either **Users and Agents** or just **Agents**. Please close this thread as it is not an issue or feature request. Thank you.

**Comment by jighem** [comment]
can we consider it as feature request?
