### ISSUE TITLE
Bug : Attachments / logos - DB Error #1062

### ISSUE THREAD

**Issue by Tho276** [osTicket/osTicket#3881]
**### Prerequisites**

* [ Yes] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ No] Do you have any errors in the PHP error log, or javascript console?
* [ Yes] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [ Yes] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

**### Description**
The bug concerns attachments images and logos.
First installation done on the server of DEV, everything is OK no problem, insertion of attachments or modification of image (Logo) this realizes correctly.

OsTicket on the prod server, the logo does not appear even after re-uploading the images, as soon as the installation inserts an image into a ticket as an attachment there is an error:
 **(DB Error #1062)**

After much research on the internet, the problem is still not resolved.

**DEV Server:**
Web Server	Apache/2.4.25 (Ubuntu)
Version MySQL	5.7.18
Version PHP	7.1.3

**PROD Server:**
Web Server	Apache/2.4.7 (Ubuntu)
Version  MySQL	5.5.28
Version PHP	5.6.7

### Steps to Reproduce

1. Installing OSTicket on the DEV server, everything is OK.

2. Installing OSTicket on the PROD server, BUG
3. Change logo in Admin, setting, company, logo. Upload logo, but does not display.
4. Inserting a photo into a ticket, the photos in attachments do not appear either and an error generates with each drag ** (DB Error # 1062) **.

**Expected behavior:** Add image OK, no display problem

**Actual behavior:** Does not display images (logo, attachment ...).

### Versions : v1.10 (901e5ea) —  Up to date

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

Windows 10 : Edge, Google Chrome

**Comment by JediKev** [comment]
Well being that your Dev server worked and your Dev/Production servers have different configurations, I would suggest copying the Dev server configurations on your Production server and see if that solves your issue.

**Comment by Tho276** [comment]
Hello JediKev,

Thanks for replying so fast, it is impossible to achieve the test, my production server is in production ...

**Comment by JediKev** [comment]
Do you get any errors (other than the DB error) in your PHP/Apache error logs?

**Comment by Tho276** [comment]
I don't have error apache in my logs error/access.

**Comment by Tho276** [comment]
UP

**Comment by JediKev** [comment]
The only thing I got at this point is to try upgrading your MySQL to the same version as production and try upgrading your PHP to the same version as your production. It worked before and it's the same code so It must be your environment configurations.

**Comment by Tho276** [comment]
Resolved.

**Comment by JediKev** [comment]
What did you do to resolve your issue? Other people might need help on this in the future and stumble across this thread!

**Comment by dbummy** [comment]
I would love to know what fixed this for Tho276!  Same problem here.
![2017-08-22 08_55_29-osticket __ admin control panel](https://user-images.githubusercontent.com/24436109/29569009-cf1ba89e-8717-11e7-83aa-225defd98098.png)

**Comment by Tho276** [comment]
Hello,

my problem solving is done by re-installing osticket.

Consider creating a backup of the ost-config.php file before deleting the folder. Then download it to your osticket directory, delete the setup and file the ost-config.php file and copy the previously saved file.

This allows a clean re-installation without erase database SQL.

Bye.

**Comment by JediKev** [comment]
@Tho276 thanks for reporting your fix!
