### ISSUE TITLE
E-Mail parse error (when email comes from office 365 and outlook 2016)

### ISSUE THREAD

**Issue by doganzorlu** [osTicket/osTicket#3884]
Hi,

We use osTicket 1.10. We have a strange problem if mail comes from office365 (users use outlook 2016). 

Mail body is not parsed correctly. 

Example here:
------------------------

--_006_DB5PR03MB173487DFD152E332B7E83414BCD50DB5PR03MB1734eurp_
Content-Type: multipart/alternative;
	boundary="_000_DB5PR03MB173487DFD152E332B7E83414BCD50DB5PR03MB1734eurp_"

--_000_DB5PR03MB173487DFD152E332B7E83414BCD50DB5PR03MB1734eurp_
Content-Type: text/plain; charset="iso-8859-9"
Content-Transfer-Encoding: quoted-printable

Ceylan Han=FDm merhaba,

Yaz=FDl=FDm hala ilgileniyor =E7=F6z=FCmlenmedi.

Sayg=FDlar=FDmla,
=DDyi =E7al=FD=FEmalar...

----------------------------------

we use php 5.4, apache 2.4 and OsTicket 1.10. is there any solution for this problem ? 

Note: The header of mail is parsed correctly.

**Comment by ntozier** [comment]
First thing that I would try to do is upgrade PHP to 5.6.

**Comment by doganzorlu** [comment]
I tried with php 5.6 and it doesn't work. And other solution ? If mail comes from exchange server this problem occurs. Other mail sources is working correctly.

**Comment by ntozier** [comment]
I dont have any other ideas.  We ran stand alone Exchange (various versions) and are running Exchange O365 and do not have that problem.  So it must be something with your configuration.

**Comment by JediKev** [comment]
I also piped this into my installation with no problem...maybe it's because I had faked the headers. So if you want to send me the full raw email with the headers (you can remove the email addresses) I can re-test this.

**Comment by doganzorlu** [comment]
Hi, i attached an example mail as raw format. It seems osticket can't parse multipart mail which in this format.

[sample_problem.txt](https://github.com/osTicket/osTicket/files/1142228/sample_problem.txt)

**Comment by JediKev** [comment]
Hmmm...I was able to pipe this in with no issues. (screenshot below)
Maybe it's something with fetching from Exchange specifically?

**Ticket Piped In:**
<img width="479" alt="screen shot 2017-07-12 at 10 35 20" src="https://user-images.githubusercontent.com/11823401/28126140-42ad2246-66ee-11e7-9689-3f19e5d89971.png">

**Comment by doganzorlu** [comment]
Found something...

`function getHeaderInfo($mid) {

        if(!($headerinfo=imap_headerinfo($this->mbox, $mid)) || !$headerinfo->from)
            return null;

        $raw_header = $this->getHeader($mid);
        $info = array(
            'raw_header' => &$raw_header,
            'headers' => $headerinfo,
            'decoder' => $this,
            'type' => $this->getMimeType($headerinfo),
        );`

in my case get header can't figure out type and subtype of the mail and getMimeType returns always TEXT/PLAIN...

Mail header contains;

Content-Type: multipart/alternative;
	boundary="_000_38018EB2132549C0BD4F8FBEF59E92C7doganzorlucom_"

but the mail parses text/plain. need fixup imap_headerinfo function.

**Comment by doganzorlu** [comment]
`
      // Parse MS TNEF emails
        if (($struct = imap_fetchstructure($this->mbox, $mid))
                && ($attachments = $this->getAttachments($struct))) {
            foreach ($attachments as $i=>$info) {
                if (0 === strcasecmp('application/ms-tnef', $info['type'])) {
                    try {
                        $data = $this->decode(imap_fetchbody($this->mbox,
                            $mid, $info['index']), $info['encoding']);
                        $tnef = new TnefStreamParser($data);
                        $this->tnef = $tnef->getMessage();
                        // No longer considered an attachment
                        unset($attachments[$i]);
                        // There should only be one of these
                        break;
                    } catch (TnefException $ex) {
                        // Noop -- winmail.dat remains an attachment
                    }
                }
            }
        }
`

the raw email i sent is multipart mail. but imap_fetchstructure returns type=0 and subtype=PLAIN and $attachments array returns null. So i can't fix php's inline functions. Any ideas ? Almost all smtp sources working well except office 365 (unfortunately we move on prem email system to office 365 :()

**Comment by JediKev** [comment]
Add the following lines to `include/class.mailfetch.php` starting on line `285` after `$mimeType`:
```php
ob_flush();
ob_start();
var_dump($struct);
file_put_contents("/path/to/osTicket/dump.txt", ob_get_flush());
```
Once you add these lines, replace `/path/to/osTicket/dump.txt` with the absolute path to your osTicket, save the file and try to re-fetch the problem mail.
After you fetch the mail post the `dump.txt` file here (make sure the file contains data first).

**Comment by doganzorlu** [comment]
I attached dumped variable here.
[dump.txt](https://github.com/osTicket/osTicket/files/1144116/dump.txt)

**Comment by doganzorlu** [comment]
And finally we figure out the problem. We use dovecot as imap server. If mail comes from office365 servers php's imap functions can't work correctly. Piping is an alternative but we choose change our imap server and problem is solved.

Thank you for your assistance.

**Comment by ntozier** [comment]
except that we use o365/Office2016 and IMAP to collect emails... and cannot replicate your issue.

**Comment by kosli** [comment]
@doganzorlu have you every found what exactly the issue is? Why it is not working via dovecot as IMAP server? 
I have the same issue, at least the mails are sent from an Outlook 2016 client via O365 and the mailserver where the mails are fetched by osticket is a dovecot IMAP server. I would be quite surprise if dovecot would be the problem?!
The problem is NOT with all mails from that client/domain. I tested with another account and could not reproduce the issue. I thought it may be related to rich text vs html mails, but that didn't make a difference.

**Comment by ericLemanissier** [comment]
Please re-open this ticket. I'm having a very similar situation here, with the protonmail-bridge server. struct has the following:
```
getPart struct: stdClass Object
(
    [type] => 0
    [encoding] => 4
    [ifsubtype] => 1
    [subtype] => HTML
    [ifdescription] => 0
    [ifid] => 0
    [lines] => 57
    [bytes] => 154
    [ifdisposition] => 1
    [disposition] => inline
    [ifdparameters] => 1
    [dparameters] => Array
        (
            [0] => stdClass Object
                (
                    [attribute] => UNKNOWN
                    [value] => UNKNOWN
                )

            [1] => stdClass Object
                (
                    [attribute] => UNKNOWN
                    [value] => UNKNOWN
                )

        )

    [ifparameters] => 1
    [parameters] => Array
        (
            [0] => stdClass Object
                (
                    [attribute] => charset
                    [value] => utf-8
                )

        )

)


```
It is of type 0, which means `TYPETEXT` (as opposed to `TYPEMULTIPART`). as a consequence, the structure has no `parts` object, and calling `imap_fetchbody` with section number 1 fails, and`imap_last_error()` returning "list message build: wrong section 1". In this case, `imap_body` has to be used instead of `imap_fetchbody`
