### ISSUE TITLE
default_email_id 0 prevents setting an email

### ISSUE THREAD

**Issue by Micke1101** [osTicket/osTicket#3886]
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch? **with auth-ldap**
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

If a user has default_email_id 0 in the table %prefix%_user, you will not be able to add/edit the email in the ui.

The reason we're getting default_email_id 0 seems to be 2 things.
1. It's a new user that have not been given an email yet in ldap, so when the user logs in to the system the email field is empty.
2. A staff member has created a ticket for a user that is not yet registered and then when the user logs in using ldap, it creates a different account and since the staff created account has the email, the user/ldap created account gets a error that the email is already in use.

### Steps to Reproduce

1. Create a user.
2. In the database go to the %prefix%_user table and change the users default_email_id to 0.
3. Go to the user in the UI and click on the name and try to enter any email for the user and press save.

**Expected behavior:** Try to fix the error by creating a new email entry (if it's not taken of course) if it's taken give an error that it's already taken.

**Actual behavior:** It gets stuck and loads infinitly and does not update the user.

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.
![image](https://user-images.githubusercontent.com/22049466/27945225-257fecb8-62ec-11e7-853f-e60c61310e75.png)

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.
Windows Server 2008 R2 Standard

Windows 7
Google Chrome 59.0.3071.115
Internet Explorer 11.0.9600.18697

**Comment by ntozier** [comment]
I would think that if you were having a problem with the auth ldap plugin ,that you would post an issue report on the plugin repo.

https://github.com/osTicket/osTicket-plugins

**Comment by Micke1101** [comment]
I'm not sure you could say that it's a problem with the ldap plugin tho, as it does read the data available and lets the user login.

The problem in the UI is seperate from the ldap problem, and maybe case 2 is more appropriate to refer to here.

**Comment by dcarniel-easy** [comment]
I concur with the previous comment, I had issues with my LDAP (Active Directory) in which some users didn't have email set properly. As a result some users were created without an email (hence notifications failed).

As it was only a handful I wanted to fix those manually and tried to update email in the users directory, I got the same never ending update and could find the following in the logs:
2018/07/09 17:17:47 [error] 52643#52643: *50324 FastCGI sent in stderr: "PHP message: PHP Warning:  Creating default object from empty value in /opt/osticket/public/include/class.user.php on line 515
PHP message: PHP Fatal error:  Uncaught Error: Call to a member function save() on null in /opt/osticket/public/include/class.user.php:516
Stack trace:
#0 /opt/osticket/public/include/ajax.users.php(166): User->updateInfo(Array, Array, true)
#1 /opt/osticket/public/include/class.dispatcher.php(145): UsersAjaxAPI->updateUser('9')
#2 /opt/osticket/public/include/class.dispatcher.php(38): UrlMatcher->dispatch('/9', Array)
#3 /opt/osticket/public/include/class.dispatcher.php(120): Dispatcher->resolve('/9', Array)
#4 /opt/osticket/public/include/class.dispatcher.php(38): UrlMatcher->dispatch('/users/9', NULL)
#5 /opt/osticket/public/scp/ajax.php(262): Dispatcher->resolve('/users/9')
#6 {main}
  thrown in /opt/osticket/public/include/class.user.php on line 516" while reading response header from upstream, client: 192.168.2.30, server: ticket.domain.local, request: "POST /scp/ajax.php/users/9 HTTP/1.1", upstream: "fastcgi://unix://opt/osticket/run/osticket_php.socket:", host: "ticket.domain.local", referrer: "https://ticket.domain.local/scp/users.php?id=9"

I ended up adding emails directly in the DB (and linking default_email_id in users table too) and all works fine now, I can update those users again. I can even update the email address.

There indeed seem to be an issue when the user lack the email address altogether, almost like it is the field used to retrieve the user object.

My 5 cents,
Denis

**Comment by JediKev** [comment]
@dcarniel-easy 

This prevents uploading Users with no email via CSV file:
https://github.com/osTicket/osTicket/pull/4330

Maybe this will help somehow?

Cheers.
