### ISSUE TITLE
Auto-reopening of the ticket after closing if an internal note is posted or even if it is transferred to other department.

### ISSUE THREAD

**Issue by parijathakumar** [osTicket/osTicket#3887]
OsTicket v1.10, Debian Jessie, PHP-5.6.3 and MySql-5.5.55

Use case: (This is only part of our actual use case. I can not reproduce it here completely as the information is classified.) We create and assign the tickets to the field engineers (FEs) to resolve issues with the remote satellite terminals we install for our customers. FE goes to the remote site, fixes the issues and calls us over phone to check if some satellite parameters are OK (which we can only check from here, at cenralised satellite hub). We check and close the ticket if we are satisfied.  But we require the FE to upload some photos or customer-signed copy of the case sheet to the same closed ticket after he comes back from the remote place.

Problem: Once the FE is uploading some photos and writing some notes, the ticket is getting automatically re-opened.

Requirement: 1) We need to stop the ticket from re-opening when any agent enters a comment for a closed ticket. 2) If required, we need to stop the agent for further entering any comments (may be after some period after ticket closure or so)

Is there any solution ?

**Comment by JediKev** [comment]
Are the "FEs" Users or Agents? Can you find their accounts under **Agent Panel > Users > User Directory** or **Admin Panel > Agents > Agents**?

**Comment by parijathakumar** [comment]
They are 'agents'. After googling I've found that by disabling the auto reopen in the 'Close' state of ticket status list, I can disable auto re-opening of closed tickets. I've done the change but yet to see if it stops reopening of closed tickets if the agents post any notes or attach anything to the ticket after it is closed.

**Comment by parijathakumar** [comment]
After the above setting, now tickets are not getting auto-reopened after posting internal note. But when transferring the department of a closed ticket, the problem still persists.

**Comment by JediKev** [comment]
This is because once you transfer the ticket to another department the system assumes it needs more work (hence the transfer). After the transfer you can simply close it again!

**Comment by parijathakumar** [comment]
Yah, that's logical. But I wish if there is a setting to configure it. Is there something I am missing ?
In our use case, the 'closing date and time' should not be changed after a ticket's closure because the time taken for resolution is chargeable (we pay to a third party based on the resolution time).

**Comment by JediKev** [comment]
There is no setting to configure this. You can just set Closed to non-reopenable and don't transfer after it's Closed (transfer the ticket before closure)! That way once it's Closed it will stay Closed unless an Agent re-opens the ticket or transfers the ticket.

**Comment by akash65** [comment]
can anyone tellme i'm not getting transfer option why?

**Comment by ntozier** [comment]
@akash65 why are you cross posting?  Also your response does not appear to be on topic for this issue report. I expect that it is because your account does not have "transfer" privileges. I would invite you to seek your support experience at the support forums. http://osticket.com/forums
