### ISSUE TITLE
[Enhancement Request] Set an optional CC address to a customer notification email

### ISSUE THREAD

**Issue by Takuji-S** [osTicket/osTicket#3894]
### Prerequisites

* [--] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [--] Do you have any errors in the PHP error log, or javascript console?
* [Yes] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [Yes] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description
Set an optional CC address to a customer notification email excluding the password reset email.

Typical our customer wants to share a ticket status with their specific internal team by email.
They usually request me to send a notification email to a group address also as cc in order to share and manage the ticket status.  However the current osTicket seems to do not support to set CC for a customer notification email...

As a best and easy way is that I think the cc address field adds to user_email table as default field.  But if it is difficult thing, I want you to add cc email address picker in the notification email creation logic.  

As one of exsamle as My idea 
![osticket02 fw](https://user-images.githubusercontent.com/17108836/28205259-39105c88-68bc-11e7-8a99-8b00ab89ccc9.png)

![osticket01 fw](https://user-images.githubusercontent.com/17108836/28205270-457d4206-68bc-11e7-85b3-4e9a2c241797.png)

### Versions
1.10

![osticket05](https://user-images.githubusercontent.com/17108836/28205276-5056f49c-68bc-11e7-892f-30ec6c2cb477.PNG)

Regards,
Takuji Suzuki

**Comment by JediKev** [comment]
I do get what you're saying but the User can simply forward the notification email to whomever they'd like from their mailbox.

**Comment by Micke1101** [comment]
How about creating an organization for them and have them added to the organization and then create a fictive account with the group email as the primary contact and then have primary contacts automaticly added?

![image](https://user-images.githubusercontent.com/22049466/28246007-cf8a8088-6a12-11e7-8fc8-559b2e210c08.png)

**Comment by Takuji-S** [comment]
Thanks for the information.  I guess it seems to be able to be a workaround.
I have seemed to misunderstand the Primary Contact feature.  I am going to test the primary contact again.
