### ISSUE TITLE
1.9.14 Maximum open ticket reached

### ISSUE THREAD

**Issue by cervedgroup** [osTicket/osTicket#3905]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [X] Do you have any errors in the PHP error log, or javascript console?
* [ X] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [ X] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

A user have only 15 opened tickets, but i found in the system log  
(We only use email to open tickets)

 Ticket denied - mxxxx.mxxxxx@cxxxx.com
Max open tickets (200) reached for mxxxx.mxxxxx@cxxxx.com
the ticket remain in the inbox 
and also other 2 events are written in the log 
Mail processing exeption
Mailbox: sxxxxx@cxxxx.com | Error(s): Array ( [err] => You've reached the maximum open tickets allowed. )

Mail Fetcher
Excessive errors processing emails for imap.cxxxxxxxx.com/cxxxxxx\osxxxxx. Please manually check the inbox.

I suppose that a counter or something like that report a wrong value in the db. Which table/field osticket check in order to see how many tickets was opened by a user ? or the counter is the result of a query ?
thank you!
We using osticket since 3 years and have around 200k tickets managed. This is the first time we have that kind of problem.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.
1.9.14

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.
windows server 2008R2 - mariadb 5.5 (x64) - php 5.5.11

**Comment by JediKev** [comment]
Check **Admin Panel > Settings > Tickets > Settings > Maximum Open Tickets**.

**Comment by cervedgroup** [comment]
it say 200

**Comment by ntozier** [comment]
Set it to 0 to disable it?

**Comment by JediKev** [comment]
So lookup that User's email address in your database under the `%prefix%_user_email` table. Next copy the email's `user_id` and go to the `%prefix%_ticket` table. Now search that table by `user_id` with the `user_id` you copied and see how many tickets show up. If there are 200 tickets then that's your issue. If not then there is an incorrect query somewhere.

**Comment by cervedgroup** [comment]
the query found a total of 61 tickets.
7 with status_id = 1
54 with status_id = 3
that is, in this moment, the same things that i found into the scp web site, looking for open ticket (7) and closed (54) from that user....

we can't set the max ticket to 0 to disable it.
Do you know where in the php osticket does this check ? which file ? in order to try to reproduce the query that return a number of 200 ticket ?
thank you

**Comment by JediKev** [comment]
Look at `include/class.ticket.php`.

**Comment by cervedgroup** [comment]
i fount that the function that count open tickets is getNumOpenTickets , but this function is not present in that file ... do you know where the function is ? thank you

**Comment by ntozier** [comment]
Go to github.
Search the repo for the function name.
find it in less then the two hours it took me to reply.
https://github.com/osTicket/osTicket/search?utf8=%E2%9C%93&q=getNumOpenTickets&type=

:)
