### ISSUE TITLE
New Ticket retains Issue Details from last Ticket created

### ISSUE THREAD

**Issue by rsanet** [osTicket/osTicket#3908]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [NO ] Do you have any errors in the PHP error log, or javascript console?
* [ Yes] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [ Yes] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description
After creation of a new ticket by an agent, and assignment  to an agent - the next new ticket created has the details of the last ticket automatically entered after selecting and using the 'Help Topic' pull down

### Steps to Reproduce

1. Agent Creates and assigns a ticket to another agent
2. Agent selects New Ticket
3. Agent selects Cancel on 'Lookup or Create a user'
4. Agent enters email address 
5. Agent enters Name
6. Agent selects 'send alert to user
7. Agent selects ticket source 'email'
8. Agent selects Help Topic '

At this point in the ticket details section the details from the prior ticket (created in #1 above) are populated into the details section of the NEW ticket

What is expected is the details to remain blank until the agent fills out the other required fields and then enters the details of THIS Ticket

### Versions

Windows Server 2016 Datacenter
Apache 2.4.5
PHP 5.6.30
MySQL 5.7.18
osTicket v1.10
![screen shot 07-27-17 at 01 36 pm](https://user-images.githubusercontent.com/30506366/28684711-62a1250c-72d3-11e7-8cf3-dedb8d63edc1.JPG)
![screen shot 07-27-17 at 01 31 pm](https://user-images.githubusercontent.com/30506366/28684710-62a0b82e-72d3-11e7-9b1e-5d3bc2796a85.JPG)

issue has ocured in both Firefox and Chrome browsers

**Comment by ntozier** [comment]
Sounds to me like your web browser saved the information and is re-populating the form.

I would recommend that you try a different web browser and see if you can replicate that behavior.

**Comment by rsanet** [comment]
That was my thought initially – so after upgrading the browser I had created the ticket in (Chrome), and then clearing cache in Chrome, it still occurs

So I tried it in Firefox – first clearing the cache – signing back in – and it still occurred

The only thing I did notice was on the manage - ticket form details – the ‘Issue Details’ is showing as ‘Thread Entry’ and is greyed out and I am not sure what that means

Sam Todd
Ross Sinclaire & Associates
513-381-3939
513-381-0124 (fax)
