### ISSUE TITLE
Simultaneous login of staff

### ISSUE THREAD

**Issue by jighem** [osTicket/osTicket#3911]
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [x] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. Login with some staff login detalis (for eg. admin)
2. Login from other machine with same staff login (admin)
3. Activities to be done from both the browser

**Expected behavior:** It should ideally not allow login with same username to other machine when the login is active in the system or it should discontinue the previous login session

**Actual behavior:** Both person from same staff login can work

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.
![image](https://user-images.githubusercontent.com/24699194/28817387-b1bc8ae6-76c5-11e7-9b6a-6dfc51ca1927.png)

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

Windows 2012 R2 Wamp Server
Client Windows 10 Chrome browser

**Comment by philbertphotos** [comment]
I actually like the ability to login multiple devices.

**Comment by ntozier** [comment]
As do I.  I'm usually logged in at work and on my phone.

**Comment by jighem** [comment]
is there any way to restrict the same?
If I want to logout once logged in from other system
as my staff forget their logins on their machine and other people responds from their names which makes confusion whether its replied by whom?
They do not have habit of logout and login
hence I want application to change its behaviour that If I log in to other browser its will close previous session
I am very weak in PHP programming but as per me I think staff.inc.php is the file where we need to make changes but need help!
Thanks in advance

**Comment by philbertphotos** [comment]
Sounds like bad user habits ... Just make login sessions shorter...

**Comment by jighem** [comment]
can we restrict simultanious login from same user?

**Comment by ntozier** [comment]
No.
