### ISSUE TITLE
Feature Request - Allow saving of searches to appear on toolbar

### ISSUE THREAD

**Issue by Mollsmolyneux** [osTicket/osTicket#3912]
We run a very small company and use OS ticket to manage the support box. It's not worth having different teams to run different support boxes, so we all muck in together.

We have two different products and I have created two different support boxes (pulled from two different emails to deal with them). Because everyone who uses OS ticket is assigned to both Support Box teams all the tickets appear together, but I'd like to keep two distinct boxes. One for product 1 and one for product 2.

So I was wondering if it was already possible to add more options to the toolbar copied below. So it would read: 

Open (All) - Open (Product 1) - Open (Product 2) - My Tickets etc.

I've saved these as searches for the moment, but I would love to be able to add those search to the toolbar so they're permanently displayed for all agents. 

![selection_128](https://user-images.githubusercontent.com/25902705/28883593-e6ac3e36-77a6-11e7-9db4-a42873fce508.png)

**Comment by ntozier** [comment]
Altering the ticket list etc is one of the most asked about question on the forums.

This thread has directions for most contemporary versions of osTicket.  
http://osticket.com/forum/discussion/75457/a-better-ticket-list

Alternatively there is the forthcoming "Custom Queues" feature here:
https://github.com/osTicket/osTicket/pull/2577

Personally I would just wait for the Custom Queues feature due out in 1.11, or use the feature from github in it's current alpha state.

**Comment by markus4000** [comment]
@protich , @greezybacon unfortunately it is unclear what "wait" for the 1.11 means... it can be weeks, months, years.,.. or never?
I'd love to read some news about the plans of the future of osTicket....

**Comment by ntozier** [comment]
@markus4000 Sounds to me like you are hijacking @Mollsmolyneux thread. 1.11 should be out some time this year.  There is no place public that you can go to read some news about future plans other than the forums and here.  Where things are generally only hinted at.

**Comment by JediKev** [comment]
@markus4000 
>I'd love to read some news about the plans of the future of osTicket....

Unfortunately at this time we do not have a public Road map. 

>unfortunately it is unclear what "wait" for the 1.11 means... it can be weeks, months, years.,.. or never?

We do not have a set release date for 1.11 so all you can do at this time is just wait. We have sooooo many features we are working on as well as features waiting to be developed so we can never pin point an exact release date for anything. We do hope to improve on this in the future by creating a public roadmap for osTicket and hopefully provide _estimated_ release dates for features and versions. Stay tuned!

**Comment by Mollsmolyneux** [comment]
Thanks for the suggestion about custom queues. We're going to try the addon and then look forward to new the version of OS ticket when it comes!

Ed

**Comment by markus4000** [comment]
Thanks @JediKev  , I can wait. no Problem. osTicket is it worth, no question. I'd just love to have some sings of live from time to time.... also to keep the great osTicket community!
