### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by NachoEM** [osTicket/osTicket#3913]
I get this error on the log, Any ideas on what might be causing it?

03-Aug-2017 07:22:54 UTC] PHP Fatal error:  Uncaught exception 'InconsistentModelException' with message 'Unable to prepare query:  SELECT COUNT(*) FROM (SELECT A1.`ticket_id` FROM `ost_ticket` A1 JOIN `ost_form_entry` A2 ON (A2.`object_type` = 'T' AND A1.`ticket_id` = A2.`object_id`) LEFT JOIN `ost_form_entry_values` A3 ON (A2.`id` = A3.`entry_id`) WHERE A1.`status_id` IN (1) AND A1.`dept_id` IN (1) AND A1.`staff_id` IN (62, 7) AND (A3.`field_id` = '44' AND )) __' in C:\inetpub\wwwroot\ticketspec\upload\include\class.orm.php:3134
Stack trace:
#0 C:\inetpub\wwwroot\ticketspec\upload\include\class.orm.php(3189): MySqlExecutor->execute()
#1 C:\inetpub\wwwroot\ticketspec\upload\include\class.orm.php(2644): MySqlExecutor->getRow()
#2 C:\inetpub\wwwroot\ticketspec\upload\include\class.orm.php(1193): MySqlCompiler->compileCount(Object(QuerySet))
#3 C:\inetpub\wwwroot\ticketspec\upload\scp\tickets.php(422): QuerySet->count()
#4 {main}

  thrown in C:\inetpub\wwwroot\ticketspec\upload\include\class.orm.php on line 3134
----
[SELECT COUNT(*) FROM 

(SELECT A1.`ticket_id` FROM `ost_ticket` A1 JOIN `ost_form_entry` A2 ON

(A2.`object_type` = 'T' AND A1.`ticket_id` = A2.`object_id`) 

LEFT JOIN `ost_form_entry_values` A3 ON 
(A2.`id` = A3.`entry_id`) 
WHERE (A3.`field_id` = '44' AND )) __]

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')) __' at line 1<br /> <br />
---- Backtrace ----<br />
#0 C:\inetpub\wwwroot\ticketspec\upload\include\mysqli.php(204): osTicket->logDBError('DB Error #1064', '[SELECT COUNT(*...')<br />
#1 C:\inetpub\wwwroot\ticketspec\upload\include\class.orm.php(3133): db_query('SELECT COUNT(*)...', true, true)<br />
#2 C:\inetpub\wwwroot\ticketspec\upload\include\class.orm.php(3189): MySqlExecutor->execute()<br />
#3 C:\inetpub\wwwroot\ticketspec\upload\include\class.orm.php(2644): MySqlExecutor->getRow()<br />
#4 C:\inetpub\wwwroot\ticketspec\upload\include\class.orm.php(1193): MySqlCompiler->compileCount(Object(QuerySet))<br />
#5 C:\inetpub\wwwroot\ticketspec\upload\scp\tickets.php(422): QuerySet->count()<br />
#6 C:\inetpub\wwwroot\ticketspec\upload\scp\index.php(17): require('C:\\inetpub\\wwwr...')<br />
#7 {main}

**Comment by NachoEM** [comment]
Ok, solved. 
It was caused by an advanced search

**Comment by timonkiper** [comment]
Hi,
I have the same error and i know that its was caused by an advanced search.
How did you solve it?

**Comment by kkbits** [comment]
Hello.
I have the same problem.
I know, that it causes with advanced search.

But how did you solved it ?
But i cant get into OS-ticket.
I cant do anything !

**Comment by ntozier** [comment]
If you are having a problem I would recommend that you seek support at the [support forums](https://forum.osticket.com/).  

If you think that you are experiencing a bug posting to a closed issue probably is not going to garner the results that you are looking for.  Maybe open your own issue report?

Which ever you decide please post meaningful information about your server environment, software versions, what you are experiencing, screen shots, and how to reproduce if possible.
