### ISSUE TITLE
Clients response showed as System Note

### ISSUE THREAD

**Issue by alfie013** [osTicket/osTicket#3914]
Hi Support,

We are having an issue where if the ticket is closed and the client respond on the closed tickets, it shows as an System Note and no notification receive for the assigned Team and Collaborators.

Here is a sample scenario:

1. Colleague A created a Ticket via email and BCC'd the Client.
2. Colleague B added the Dispatch Distro as Collaborator and assigned it to an Agent and Team
3. Colleague A closed the ticket and posted an Internal Note for the resolution of the ticket.
4. Client respond on the ticket but it shows as a **System Note** and no **New Message Template** was received even though it was enabled on the Admin Settings.

Server Information: 
osTicket Version ------------------ v1.10 (901e5ea) —  Up to date
Web Server Software  ------------ Microsoft-IIS/8.5
MySQL Version ------------------- 5.7.17
PHP Version ---------------------- 7.0.15

Thank you,

**Comment by ntozier** [comment]
I would bet that 1. Colleague A created the ticket incorrectly [did not make the ticket in the clients name/email]

**Comment by alfie013** [comment]
Hello @ntozier,

Thanks for your response. Even though it was created incorrectly, why we did not receive any notification after the clients respond on the closed ticket and also why it showed as a System Note?

**Comment by ntozier** [comment]
BEcause they have an agent account.

**Comment by alfie013** [comment]
@ntozier,

Hmm. Since I am not good in coding. Can you help me that if the ticket is reopened by replying via email, we can still receive a notification?

Regards,

**Comment by ntozier** [comment]
Agent responses to the user is not a feature in osTicket at this time.  There are some threads on the forums about how to do it, but I'm not sure which versions they were for.

**Comment by alfie013** [comment]
@ntozier,

Can you help us find the condition in the code when the email update shows as system note in the ticket thread?

Regards,
![1](https://user-images.githubusercontent.com/25225267/29810794-1d22732c-8c56-11e7-8fa0-7a73152cc815.png)
