### ISSUE TITLE
Attachment removed after edit thread

### ISSUE THREAD

**Issue by juraganerka** [osTicket/osTicket#3921]
In new version (1.10) my attachment removed after editing thread. Previously version did not happen.
I see another thread in #2888 and #3139 there is updating code in class.thread.action,but still not working.
This happen if i place attachment in dynamic form. When attachment being part of ticket details there is no problem. Please anyone help me.

**Comment by ntozier** [comment]
dupe thread. 
Please close.

**Comment by mtitter** [comment]
Any movement on this issue? Still having this happen to us on v1.10.1

**Comment by alanwlchan** [comment]
I think It is a bug.

**Comment by softdevwai** [comment]
Also having the same issue (v1.10). Happens when another user edits a ticket, the attachment gets automatically removed. The ticket thread says:

> Created by xx xxx 11/20/17 10:49:29
Updated by yy yyy 11/24/17 11:51:34 — Add Attachment removed 0, Separate rooms? set to Yes

**Comment by alanwlchan** [comment]
The problem also happens after the same user logout and then login to edit the ticket.

**Comment by etcb11** [comment]
I am running v1.10.1 (9ae093d) and having the same issue. Any updates? This is a pretty significant issue.
