### ISSUE TITLE
Upgrade script not working for upgrade from 1.8-git version to 1.10

### ISSUE THREAD

**Issue by webunraveling** [osTicket/osTicket#3923]
I originally installed from version 1.8-git and have downloaded the latest release (1.10), extracted it on the server and have run `rsync -avz v1.10/* currentInstallDir/`. The command executed successfully but when I go to `mysite.com/scp/upgrade.php` it gives me the message "Nothing to do! System already upgraded to 1.8-git with no pending patches to apply."

I assume this is because I'm running the git version rather than an official release or pre-release but figured I'd post here just in case. Will I have to just start from a fresh install and then import the DB tables that contain users and tickets? Or is the upgrade script supposed to work here?

**Comment by ntozier** [comment]
"1.8-git" isn't a real version.  You'r probably already running the latest version since Git is beyond 1.10 at this point.

**Comment by webunraveling** [comment]
> 1.8-git" isn't a real version...

Thanks I suspected it might be something like that.
