### ISSUE TITLE
Translation file disrupts the install process [PL]

### ISSUE THREAD

**Issue by esamo** [osTicket/osTicket#3926]
I cannot install a new 1.10 version of the OSTicket with the language file (pl.phar) selected. The process halts at some point with 500 internal, not finishing the database (mainly the forms are missing) and with broken pages by missing translations, the non-integer indices exception:
http://i.imgur.com/PC0gwYQ.png

With the default EN language selected, everything works fine. Relatively. Some stuff doesn't get translated like templates, pages, statuses etc...

Regards & respect

**Comment by mfelber** [comment]
My understanding is that this a known bug with the installer of osticket 1.10:
https://github.com/osTicket/osTicket/issues/3865

When you use a language pack during the install of osticket 1.10 the installation process will not work correctly..

**Comment by esamo** [comment]
Sure it is
