### ISSUE TITLE
OSTicket 1.10 - Cannot create custom forms

### ISSUE THREAD

**Issue by AdeliavanTonder** [osTicket/osTicket#3929]
[class.format.zip](https://github.com/osTicket/osTicket/files/1239083/class.format.zip)
Hi Guys
Let me start by saying I am not a developer or programmer, merely a user trying to help someone.  We have moved our ticket system from one server to another and since then have had various issues.  Most of them I have been able to resolve with my limited knowledge but this one I cannot seem to sort out.  We get the following error when creating new custom forms:

Catchable fatal error: Object of class SqlFunction could not be converted to string in /home/studiemeesterhul/public_html/include/class.format.php on line 365

I have attached everything that I think might be able to help:

- Copy of my class.format.php file

![image](https://user-images.githubusercontent.com/2185570/29523787-697c9dd8-868e-11e7-9027-459cb12e6511.png)

I can reproduce this problem every time, from various browsers. 
I have reinstalled - replaced the files for OS Ticket with new source code from the OS Ticket website.

At this stage I should also mention that I can create new Help Topics but then have to manually add a Topic ID to the DB as it is created with an ID of 0. 

I do not know if something went wrong during the restore of the db, but any help would be appreciated.

Kind Regards
Adelia

**Comment by JediKev** [comment]
What was the MySQL version of the old server?

**Comment by AdeliavanTonder** [comment]
@JediKev , thanks for the reply.

It was originally installed on MySQL 4.6.6, moved to Hetzner hosting version 4.2.9 and moved back to Hostking on version 4.6.6

Can I provide any other relevant information?

Just as a side note: We have noticed that the setting to assign the re-opened tickets to the last respondend is also not working. I do not know if this is in any way related or not. This however is working on my other ticket system (using the same version of OS Ticket)

I appreciate your time with this.

**Comment by AdeliavanTonder** [comment]
Good Day @JediKev 

Please ignore my previous comment with regards to the version. I was provided with the incorrect information.  Herewith two screenshots with the two server MySQL versions. The first is the original and the second is the new hosting

OLD SERVER
![old](https://user-images.githubusercontent.com/2185570/29606775-947ad1dc-87ef-11e7-97af-b5611e0b0661.png)

NEW SERVER
![new](https://user-images.githubusercontent.com/2185570/29606784-9a0168dc-87ef-11e7-948b-fb2944b82102.png)

Thanks

**Comment by JediKev** [comment]
Ahh. Well this does not seem like an osTicket issue, more of an environment issue. If it works on the old server perfectly then something has to be wrong with the new server environment. I would try to mimic the environment of the old server on the new server to see if that fixes the issue. Cheers.
