### ISSUE TITLE
MySQL Version(s) supported is NOT correct

### ISSUE THREAD

**Issue by fraser125** [osTicket/osTicket#3930]
OSTicket Version: v1.10 (901e5ea)
Web Server Software | Microsoft-IIS/7.0
MySQL Version | 5.0.84
PHP Version | 5.5.11

These dependencies, primarily the MySQL version result in a broken Ticket search from the Agent list screen and this causes multiple error emails to be sent to me (admin) daily. Email Error Message below, but first my conclusion:

This error message (from email)

> You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NATURAL LANGUAGE MODE)) 

Quote from the [MySQL 5.1 reference manual](https://downloads.mysql.com/docs/refman-5.1-en.pdf) Page 1154

> The IN NATURAL LANGUAGE MODE and IN NATURAL LANGUAGE MODE WITH QUERY EXPANSION modifiers were added in MySQL 5.1.7.

Please update the required dependencies to reflect this.
[http://osticket.com/download](http://osticket.com/download)
[http://osticket.com/wiki/Installation](http://osticket.com/wiki/Installation)
[http://osticket.com/faq](http://osticket.com/faq)
Maybe other places too.

This issue and fix has already been identified here:
[http://osticket.com/forum/discussion/90415/resolved-db-error-1064](http://osticket.com/forum/discussion/90415/resolved-db-error-1064)

The full contents of the error email:
[SELECT A3.`address` AS `user__default_email__address`, A1.`number` AS `number`, 1 AS tickets, 1 AS __relevance__ FROM `ost_ticket` A1 JOIN `ost_user` A2 ON (A1.`user_id` = A2.`id`) LEFT JOIN `ost_user_email` A3 ON (A2.`default_email_id` = A3.`id`) WHERE (A1.`staff_id` = 33 OR A1.`team_id` IN (SELECT A1.`team_id` FROM `ost_team_member` A1 WHERE A1.`staff_id` = 33) OR A1.`dept_id` IN ('1')) AND A1.`number` LIKE '366003%' GROUP BY A3.`address`, A1.`number` UNION ALL (SELECT A3.`address` AS `user__default_email__address`, null AS number, COUNT(DISTINCT A1.`ticket_id`) AS `tickets`, Z1.`relevance` AS `__relevance__` FROM `ost_ticket` A1 JOIN `ost_user` A2 ON (A1.`user_id` = A2.`id`) LEFT JOIN `ost_user_email` A3 ON (A2.`default_email_id` = A3.`id`) JOIN (SELECT COALESCE(Z3.`object_id`, Z5.`ticket_id`, Z8.`ticket_id`) as `ticket_id`, SUM(MATCH (Z1.title, Z1.content) AGAINST (366003 IN NATURAL LANGUAGE MODE)) AS `relevance` FROM `ost__search` Z1 LEFT JOIN `ost_thread_entry` Z2 ON (Z1.`object_type` = 'H' AND Z1.`object_id` = Z2.`id`) LEFT JOIN `ost_thread` Z3 ON (Z2.`thread_id` = Z3.`id` AND Z3.`object_type` = 'T') LEFT JOIN `ost_ticket` Z5 ON (Z1.`object_type` = 'T' AND Z1.`object_id` = Z5.`ticket_id`) LEFT JOIN `ost_user` Z6 ON (Z6.`id` = Z1.`object_id` and Z1.`object_type` = 'U') LEFT JOIN `ost_organization` Z7 ON (Z7.`id` = Z1.`object_id` AND Z7.`id` = Z6.`org_id` AND Z1.`object_type` = 'O') LEFT JOIN ost_ticket Z8 ON (Z8.`user_id` = Z6.`id`) WHERE MATCH (Z1.title, Z1.content) AGAINST (366003 IN NATURAL LANGUAGE MODE) GROUP BY `ticket_id`) Z1 WHERE (A1.`staff_id` = 33 OR A1.`team_id` IN (SELECT A1.`team_id` FROM `ost_team_member` A1 WHERE A1.`staff_id` = 33) OR A1.`dept_id` IN ('1')) AND A1.`ticket_id` = Z1.`ticket_id` GROUP BY A3.`address` LIMIT 25) LIMIT 25]

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NATURAL LANGUAGE MODE)) AS `relevance` FROM `ost__search` Z1 LEFT JOIN `ost_thre' at line 1<br />
<br />
---- Backtrace ----<br />
#0 C:\inetpub\wwwroot\osticket\include\mysqli.php(204): osTicket->logDBError('DB Error #1064', '[SELECT A3.`add...')<br />
#1 C:\inetpub\wwwroot\osticket\include\class.orm.php(3133): db_query('SELECT A3.`addr...', true, true)<br />
#2 C:\inetpub\wwwroot\osticket\include\class.orm.php(3180): MySqlExecutor->execute()<br />
#3 C:\inetpub\wwwroot\osticket\include\class.orm.php(1865): MySqlExecutor->getArray()<br />
#4 C:\inetpub\wwwroot\osticket\include\class.orm.php(1815): HashArrayIterator->{closure}()<br />
#5 C:\inetpub\wwwroot\osticket\include\class.orm.php(1794): CallbackSimpleIterator->next()<br />
#6 C:\inetpub\wwwroot\osticket\include\class.orm.php(1803): CallbackSimpleIterator->rewind()<br />
#7 C:\inetpub\wwwroot\osticket\include\class.orm.php(1463): CallbackSimpleIterator->valid()<br />
#8 C:\inetpub\wwwroot\osticket\include\class.orm.php(1480): CachedResultSet->fillTo(2147483647)<br />
#9 C:\inetpub\wwwroot\osticket\include\class.orm.php(1489): CachedResultSet->asArray()<br />
#10 C:\inetpub\wwwroot\osticket\include\ajax.tickets.php(79): CachedResultSet->getIterator()<br />
#11 [internal function]: TicketsAjaxAPI->lookup()<br />
#12 C:\inetpub\wwwroot\osticket\include\class.dispatcher.php(145): call_user_func_array(Array, Array)<br />
#13 C:\inetpub\wwwroot\osticket\include\class.dispatcher.php(38): UrlMatcher->dispatch('lookup', Array)<br />
#14 C:\inetpub\wwwroot\osticket\include\class.dispatcher.php(120): Dispatcher->resolve('lookup', Array)<br />
#15 C:\inetpub\wwwroot\osticket\include\class.dispatcher.php(38): UrlMatcher->dispatch('/tickets/lookup', NULL)<br />
#16 C:\inetpub\wwwroot\osticket\scp\ajax.php(262): Dispatcher->resolve('/tickets/lookup')<br />
#17 {main}

**Comment by ntozier** [comment]
I've been asking that the page be updated directly for many months now.  It should probably read:

PHP 5.4 - 7.0   (recommended 5.6)
MySQL 5.1+    (recommended 5.5)
