### ISSUE TITLE
Bug, osticket 1.10: set default department to private fails with an warning that does not help

### ISSUE THREAD

**Issue by mfelber** [osTicket/osTicket#3934]
### Prerequisites

* [y ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [n] Do you have any errors in the PHP error log, or javascript console?
* [y ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [y ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

If you try to set the default department to "private" it fails with an error message that will not help you: "Unable to update this department. Correct any errors below and try again."

### Steps to Reproduce

1. Set the default department to "Private" and click "Save Changes:

![error private](https://user-images.githubusercontent.com/5539456/29741254-37930b70-8a69-11e7-94af-9687bae7003f.png)

**Expected behavior:** The warning should inform you about the "errors" and give you an advice how to avoid these "errors".

**Actual behavior:** The warning doesn't help you because the cause of the "error" is missing. There should be a hint why this occurs to avoid it.
### Versions
Server Information
osTicket Version | 1.8-git (?)  Upgrade— 901e5ea is available Web Server Software | Apache MySQL Version | 5.6.26 PHP Version | 5.6.12
gdlib | Used for image manipulation and PDF printing imap | Used for email fetching xml | XML API xml-dom | Used for HTML email processing json | Improves performance creating and processing JSON mbstring | Highly recommended for non western european language content phar | Highly recommended for plugins and language packs intl | Highly recommended for non western european language content fileinfo | Used to detect file types for uploads APCu | Improves overall performance Zend Opcache | Improves overall performance
cgi.fix_pathinfo | "1" is recommended if AJAX is not working date.timezone | Europe/Berlin
Schema | osticket110 (localhost) Schema Signature | 98ad7d550c26ac44340350912296e673 Space Used | 2.45 MiB Space for Attachments | 0.01 MiB Timezone | CEST (Interpreted as Europe/Berlin)
OS: ubuntu 14.04 Browser: Chrome 60.0.3112.101, Safari 10.1.2 (12603.3.8)

**Comment by JediKev** [comment]
Are you trying to make the "Default" Department Private? If so that's why it's throwing the error. You cannot make a Default Department Private 😃

**Comment by mfelber** [comment]
Yes, but normally the error message gives you a hint why the error occurs so you could avoid it. Here you see only "Correct any errors below and try again" and the cause (making default department to private) or focus to the problematic field is missing.

**Comment by JediKev** [comment]
Yea I'm looking into why it's not showing errors now but that's why you are getting it 😃

**Comment by JediKev** [comment]
I have found and fixed this issue with [this pull request](https://github.com/osTicket/osTicket/pull/3939). Please test it for me and let me know! Cheers.

**Comment by mfelber** [comment]
Works fine 😀 Thank, you! I will close the issue report.
