### ISSUE TITLE
Bug, osticket 1.10: „Configure Alerts & Notices“-Link in help tip popup is outdatet

### ISSUE THREAD

**Issue by mfelber** [osTicket/osTicket#3935]
### Prerequisites

* [y ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [n] Do you have any errors in the PHP error log, or javascript console?
* [y ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [y] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

When you navigate via the „Configure Alerts & Notices“-Link you will redirected to the wrong page.

### Steps to Reproduce

Go to a department and click on the link in the help tip popup: 

![wrong link](https://user-images.githubusercontent.com/5539456/29741348-f296b4fc-8a6a-11e7-9a31-20ace53cf007.png)

**Expected behavior:** I guess the (outdatet) link should be replaced with two new links like http://.../osticket-110/scp/settings.php?t=tickets#alerts and http://.../osticket-110/scp/settings.php?t=tasks#alerts that should redirect you to the alert and notices page from tickets and tasks.

**Actual behavior:** You will be redirected to the settings page (http://.../scp/settings.php?t=alerts): 

![landing](https://user-images.githubusercontent.com/5539456/29741362-4914b73e-8a6b-11e7-8b64-d7bf47e938b3.png)

### Versions

Server Information
osTicket Version | 1.8-git (?)  Upgrade— 901e5ea is available Web Server Software | Apache MySQL Version | 5.6.26 PHP Version | 5.6.12
gdlib | Used for image manipulation and PDF printing imap | Used for email fetching xml | XML API xml-dom | Used for HTML email processing json | Improves performance creating and processing JSON mbstring | Highly recommended for non western european language content phar | Highly recommended for plugins and language packs intl | Highly recommended for non western european language content fileinfo | Used to detect file types for uploads APCu | Improves overall performance Zend Opcache | Improves overall performance
cgi.fix_pathinfo | "1" is recommended if AJAX is not working date.timezone | Europe/Berlin
Schema | osticket110 (localhost) Schema Signature | 98ad7d550c26ac44340350912296e673 Space Used | 2.45 MiB Space for Attachments | 0.01 MiB Timezone | CEST (Interpreted as Europe/Berlin)
OS: ubuntu 14.04 Browser: Chrome 60.0.3112.101, Safari 10.1.2 (12603.3.8)

**Comment by JediKev** [comment]
I have found and fixed this issue with [this pull request](https://github.com/osTicket/osTicket/pull/3940). Please pull and test for me. Cheers.

**Comment by mfelber** [comment]
Yes, this issue is also fixed 😀. But this would only affect the english language pack. 
I guess the other language pack must also be adjusted..

**Comment by JediKev** [comment]
Yes 😁

**Comment by mfelber** [comment]
Ok, who will do this? Is this possible by the community via crowdin or will somebody from osticket does this? 

Should I close this issue report or let it open until I get the feedback that this is fixed for the other languages as well?

**Comment by JediKev** [comment]
Once we apply this fix, push the new files to Crowdin, and do another upload to osticket.com/download all language files will have the fix.

You can close it because the fix will automatically apply to all languages once the above happens.  👍

**Comment by mfelber** [comment]
Ok, I understand. Thank you.
