### ISSUE TITLE
Default From Name system default setting missing from Admin Panel

### ISSUE THREAD

**Issue by rcup** [osTicket/osTicket#3938]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

The **Default From Name** setting in **Agent Preferences** has a **System Default** option. However, there doesn't appear to be any way to set this default value in the Admin Panel.

### Steps to Reproduce
1. Go to Agent Profile > Preferences
2. Default From Name can be changed to 'My Name' from system default (for current agent only)
3. Go to Admin Panel > Agents > Departments
4. Select a department

**Expected behavior:**
Expect to see a Default From Name somewhere on Department page, like under Outgoing Email Settings.

**Actual behavior:**
There is no option to change the system/department default.

### Versions
osTicket v1.10 (901e5ea)

**Comment by clonemeagain** [comment]
Can confirm, there doesn't appear to be a setting for this. 

Thread: http://osticket.com/forum/discussion/90992/default-from-name-system-default
