### ISSUE TITLE
No Commits since May. Is this project abandoned?

### ISSUE THREAD

**Issue by SysEngDan** [osTicket/osTicket#3945]
I've used osTicket for years and had up/down experiences with it. I'm evaluating to use it again for a big project, but noticed there haven't been any commits since May. That's a long time for such a big project. Is this still actively being developed and big-fixed?

**Comment by Chefkeks** [comment]
Just take a look here ;)
https://github.com/osTicket/osTicket/issues/3936

**Comment by ntozier** [comment]
@umuzidan 
Yes.

**Comment by Chefkeks** [comment]
Just to be clear and to avoid misunderstandings, @ntozier answered 'Yes' to your question 'Is this still actively being developed and big-fixed?' and not to the question in the issue title ('Is this project abandoned?')

**Comment by ntozier** [comment]
Q:  Is this still actively being developed and big-fixed?
A: Yes.

**Comment by kclubok** [comment]
I had the same confusion.  It appears that all the current development is being held up as pull requests.  There are currently 227 outstanding pull requests, the last one dated yesterday.  So it is clear that development is active.  Once the pull requests get merged, the commits will look a lot more current.
