### ISSUE TITLE
1.10 unpacked translation does not work

### ISSUE THREAD

**Issue by esamo** [osTicket/osTicket#3947]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Steps to Reproduce

1. Fresh install of the latest stable version of the osTicket.
2. Add the original unpacked translation files (language: PL).
3. Chose the language as a system default.

**Expected behavior:** 
Whole system should be translated, like when using pl.phar file.

**Actual behavior:**
System does not get translated. Only the popup details are showing up in the chosen language. Example: http://take.ms/I0jbP

The other thing is that I'm not using the phar file because on the server I get white page without any error even with error_reporting and display_errors set, the response code is 200.
Locally on my machine I haven't such issue.
Definitely osTicket could be improved against the problem that is happening.

### Versions
osTicket v1.10
Apache 2
PHP 5.5.38

**Comment by JediKev** [comment]
Have you cleared your browser cache?

**Comment by esamo** [comment]
> Have you cleared your browser cache?
I used Shift+Ctrl+R on Chrome and checked on other browsers (FF, IE) that didn't open the website before - no change.

**Comment by JediKev** [comment]
What do you mean by "unpacked translation files"?

**Comment by esamo** [comment]
> What do you mean by "unpacked translation files"?

http://i18n.osticket.com/project/osticket-official/pl#
I tried like it is, tried merging with dir `1.10.x`, tried alone dir and without it - no difference.

**Comment by JediKev** [comment]
After some testing the language pack has to be in `.phar` format to work properly. 👍 
Why can't you use the `.phar` file? Everyone I know that uses language packs uses the `.phar` file.

**Comment by esamo** [comment]
I have described the problem with phar file in the second paragraph of the "Actual behavior"
 section.

**Comment by esamo** [comment]
I saw many similar issues regarding the phar file but no where the actual solution is presented (this is why I've tried unpacked translation archive).
I guess I have to fiddle with server settings or osticket phar file handling to make it working.

**Comment by JediKev** [comment]
That's odd... 🤔 

I don't think this is an osTicket issue as I have tested this with v1.10 and the official Polish language pack from http://osticket.com/download and everything works fine. 

Could you post a screenshot of **Admin Panel > Dashboard > Information**?

**Comment by esamo** [comment]
Sure, here it is:
http://take.ms/Gzduw

**Comment by esamo** [comment]
But this is with unpacked language. With the phar file active I can do nothing at all in the system. As I said I get white page with status code 200.

**Comment by esamo** [comment]
The german language doesn't work as well so the phar file doesn't matter. It is about handling it.

**Comment by JediKev** [comment]
Right, are you using Ubuntu or?

**Comment by mfelber** [comment]
Some hosters doesn't allow using phar files. In my hosting package I must allow it via a special setting in the hosting interface.
I can normally use extracted language packs with osticket 1.10 as long as they are named correctly. The german language pack folder for example has to named "de" .

**Comment by mfelber** [comment]
Have never tried to use extracted language packs from crowdin (i18). I guess they are not ready to use.

I download a phar-file from osticket.com and unphar it myself (for example with http://empir.sourceforge.net or https://github.com/koto/phar-util or http://unphar.com).

**Comment by esamo** [comment]
Admin of the server has solved the issue, it was related to a suhosin lib.

**Comment by JediKev** [comment]
Ahhhh, that'll definitely do it! Thanks for posting the fix as other Users with the same issue might stumble across this one day! Cheers. 🍻

**Comment by esamo** [comment]
Here is exact solution http://osticket.com/forum/discussion/80012/resolved-blank-page

**Comment by JediKev** [comment]
Wow. Even better. Thanks a million @esamo 🎉
