### ISSUE TITLE
Locating the exact path for cron.php in linux 

### ISSUE THREAD

**Issue by PMAX-Jason-Racines** [osTicket/osTicket#3949]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [ ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

**Comment by JediKev** [comment]
@jason-pmaxglobal 

**Via Terminal:**
- ssh to server
- `cd` to the osTicket/api/ directory
- run the following command:
```bash
$ pwd
```
This will give you the full path to the `api` directory in which the `cron.php` file lives. So now you just tack the `cron.php` on the end and you have the full path to the file.

**Example:**
If the full path to the folder is `/var/www/osTicket/api/` then the full path to the file is `/var/www/osTicket/api/cron.php`. 👍

**Comment by jason-pmaxglobal** [comment]
Hi @JediKev 

Thanks for your reply. 

When accessing the ssh to server, the system responded, 

"the authenticity of host ('given ipaddress') can't be established. ECDSA key fingerprint is ...... Are you sure you want to continue connecting?"

will just simply type yes?

Thanks.

**Comment by JediKev** [comment]
@jason-pmaxglobal Yes.
