### ISSUE TITLE
database error creating a new filter (duplicate entry)

### ISSUE THREAD

**Issue by wesyah234** [osTicket/osTicket#3950]
I was creating my first filter and I received this message via email:

[INSERT INTO ost_filter_rule SET created=NOW(), filter_id=2,  updated=NOW() ,what='',how='',val='',isactive=1]

Duplicate entry '2---' for key 'filter'<br />
<br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(204): osTicket->logDBError('DB Error #1062', '[INSERT INTO os...')<br />
#1 (root)/include/class.filter.php(668): db_query('INSERT INTO ost...')<br />
#2 (root)/include/class.filter.php(641): FilterRule::save(0, Array, Array)<br />
#3 (root)/include/class.filter.php(452): FilterRule::create(Array, Array)<br />
#4 (root)/include/class.filter.php(515): Filter::save_rules(2, Array, Array)<br />
#5 (root)/include/class.filter.php(373): Filter::save(0, Array, Array)<br />
#6 (root)/scp/filters.php(42): Filter::create(Array, Array)<br />
#7 {main}

The only filter in the system is the one I just created, #2 

osTicket Version | v1.10 (901e5ea)     —  Up to date
-- | --
Web Server Software | Apache/2.2.15 (Red Hat)
MySQL Version | 5.5.56
PHP Version | 5.4.45

**Comment by iHunt101** [comment]
What filter did you set?

**Comment by wesyah234** [comment]
sorry but I don't remember, it was a month ago.  I can however give you the contents of the ost_filter_rule table right now:

hope that helps.

```
id filter_id what    how    val              isactive notes created             updated             
-- --------- ------- ------ ---------------- -------- ----- ------------------- ------------------- 
1  1         email   equal  test@example.com true           2017-08-30 13:25:28 2017-08-30 13:25:28 
8  2         field.1 starts *                true           2017-09-08 11:01:00 2017-09-08 11:01:00 

```
