### ISSUE TITLE
Response/Reply Template thread.lastmessage issue

### ISSUE THREAD

**Issue by aalaily** [osTicket/osTicket#3951]
### Description

In the "Response/Reply Template", using %{ticket.thread.lastmessage} only picks up the last message that the client has posted.  Not the agent's last message.... although the agent message is part of the thread.

### Steps to Reproduce

1. Go to => Admin Panel => Emails => Templates => [Select your messages] => Response/Reply Template 
2. Add %{ticket.thread.lastmessage} to the body
3. Submit a ticket and reply as an agent

**Expected behavior and Actual behavior:**
You would expect to see the agent reply in the notification sent to the user, but instead, you only get the message that was submitted by the client.

### Versions

OSTicket Version: v1.10 (901e5ea) —  Up to date
OS: Ubuntu 16.04

**Comment by ntozier** [comment]
I think that your looking for the last Agent response.  Which is %{response}

**Comment by aalaily** [comment]
@ntozier thanks for the quick reply!

I will definitely try %{response.body} but since the agent message is added to the thread - hopefully it works; however, since the agent's response was last added to the message thread, the expected behavior of %{ticket.thread.lastmessage} is to extract that message.

For instance, if the client replies twice to the message and then the agent replies five times, %{ticket.thread.lastmessage} actually fetches the second message from the client.... not the fifth message  from the agent (the fifth message from the agent is actually the seventh message overall).

I will let you know if the %{response.body} does what I'm looking for.

Thanks.

**Comment by ntozier** [comment]
I did not say %{response.body}.  I said %{response}.
Your understanding of what a response and what a message is appears to be incorrect.
The last "message" is in fact the last User message.
The last "response" would be the last Agent response.

**Comment by aalaily** [comment]
Using %{response} prints exactly the same thing as %{response.body}, so they seem to be equivalent.  In addition, it appears as though %{response} does in fact print out the last message in the thread - so thank you for that.

I appreciate the clarification on "message" and "response".

**Comment by ntozier** [comment]
Any time. :)  Have a great weekend! (logging out in 26 minutes if you have another issue or question after that I will like not see it until monday)

**Comment by aalaily** [comment]
Awesome.  Thanks.

**Comment by vollkommenIrrelevant** [comment]
Hve a look here:
https://github.com/osTicket/osTicket/pull/3646
