### ISSUE TITLE
Autoresponser based on working date and time

### ISSUE THREAD

**Issue by amnkh** [osTicket/osTicket#3954]
Hi everybody,
Thanks a lot for developing such an awesome ticketing system, I appreciate every seconds and minutes you spend on helping others.

We have osTicket (v1.10) installed on our server. 

We need a feature to autorespond all new tickets created after 4 PM to 9 AM every day and also in weekends.

For example: 

A user create a ticket on Saturday (not a working day) or after 4 PM in a working day, osTicket autorespond this message:

"It's not a working time, we will follow your issue tomorrow between 9 AM and 4 PM"

I read too many topics and searched a lot but couldn't find any solution, Please tell me if you have any idea.

Thanks a lot and best wishes for osTicket team.

-

P.S.:  Excuse me for not using default issue template, I couldn't create new topic on [forum](http://osticket.com/forum) and I have now idea if it's a proper place to ask or not.

Please close this issue if you thinks it's not a proper place to ask.

Thanks.

**Comment by perryk** [comment]
Hi amnkh,

You may have already been directed to this, however, if not there is a plugin for this here:
https://github.com/clonemeagain/osticket-plugin-responder

If this works ok for you it is likely a good idea for you to close this as being an issue,

Cheers.

**Comment by amnkh** [comment]
Thanks perryk,
I installed it and works fantastic.

**Comment by perryk** [comment]
Great, thanks @clonemeagain for the plugin :)

**Comment by clonemeagain** [comment]
Hey, you're welcome!
