### ISSUE TITLE
Mobile Friendly

### ISSUE THREAD

**Issue by husseinsheikh** [osTicket/osTicket#3961]
When are you going to make it mobile friendly or responsive as it would really help? 

### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [ ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

**Comment by JediKev** [comment]
This will be part of a near future release. I can't say much else but we have big plans for this coming up. So please stay tuned! 

Please close this as this is not an issue report nor feature request.

Thanks.

**Comment by husseinsheikh** [comment]
Can't wait, is it coming out on Christmas?

**Comment by JediKev** [comment]
It will be some time next year. We have another major release due before we start on it but it'll be totally worth the wait.

**Comment by Dubz** [comment]
Does this include the admin panel?

My coworkers would be thrilled if it were, since that's the majority of the system that'll be used (if anyone even uses the client side and not just email).

**Comment by husseinsheikh** [comment]
Still not mobile friendly, any updates on when will this be done?

**Comment by Dubz** [comment]
I wouldn't hold your breath for it if it's not out already. It's been over a year and a half since they said it was in the works to be added.
Nb4devrant, I know it doesn't happen overnight, or even in a month. There has been plenty of time for this to be added though.
