### ISSUE TITLE
Nginx CSP

### ISSUE THREAD

**Issue by HiTm4n** [osTicket/osTicket#3963]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
YES
* [ ] Do you have any errors in the PHP error log, or javascript console?
NO (if i'm not wrong..)
* [ ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
YES
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?
YES

### Description

Hello !
While i'm in the Administration Panel, everytime i switch between tabs screen is freezing in loading...
I use a Reverse proxy with Nginx.
When i disable CSP policies : 
<code>
add_header Content-Security-Policy "default-src 'self' https://osticket.condorscan.pro/ https://*.gravatar.com https://*.gstatic.com https://*.googleapis.com https://ssl.google-analytics.com https://s-static.ak.facebook.com https://www.google-analytics.com data: 'unsafe-inline' 'unsafe-evali'";
</code>
the problem disappears. 
So my question is which CSP policies do you use ?

Sorry for my english, and hope you have some answers for me :)

Osticket version :  v1.10-73-g973110fd (973110f)
OS version : Debian 9

**Comment by ntozier** [comment]
osTicket does not support nginx so I would recommend that you search the existing nginx threads here on github.  There are a number of them, and you may find an answer to your question that way.  Or perhaps this will assist you: https://github.com/osTicket/osTicket/issues/3810

**Comment by iHunt101** [comment]
Please refer to the [requirements](https://github.com/osTicket/osTicket#requirements).
