### ISSUE TITLE
Language change in profile setting not saved

### ISSUE THREAD

**Issue by jochenwezel** [osTicket/osTicket#3964]
### Description

At https://yourdomain/osticket/scp/profile.php#preferences there is the following language setting in osTicket (v1.10):
![image](https://user-images.githubusercontent.com/3033827/30533740-3c4d5702-9c5b-11e7-8ca3-7ae5cb466c18.png)

The setting seems to be saved when clicking on the Okay button below, but when revisiting the page, the setting is on its origin value again.

**Comment by ropaha** [comment]
You have to click twice the OK button to save your changes.

**Comment by mfelber** [comment]
I don't see there any "OK" button.

When I click on "Save Changes" after changing the preferred language the setting is written to the database. Revisiting the page does not change the value. I only click one time to save the changes. Can't replicate what you are describing..
