### ISSUE TITLE
unable to add category  (not the one in  knowledgebase)  in osticket 

### ISSUE THREAD

**Issue by Rudranii** [osTicket/osTicket#3965]
Hi, I'm unable to add category in osticket. If someone help it here, that would be very great !!

**Comment by ntozier** [comment]
I think that you might be better served by making a post on the support forums. You haven't really provided us with enough information to assist you.  Please help us to help you by reading and following the posting guidelines located in this thread: [Please read before requesting assistance](http://www.osticket.com/forum/discussion/77765/please-read-before-requesting-assistance#latest).  The more information you give us the better we will be able to assist you. Thank you.
