### ISSUE TITLE
Main user and collaborators receive separate emails when responding to ticket

### ISSUE THREAD

**Issue by JonM20** [osTicket/osTicket#3967]
### Prerequisites

* [y] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [n] Do you have any errors in the PHP error log, or javascript console?
* [y] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [y] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description
When responding to a user's ticket, osTicket generates individual emails to user AND each collaborator rather than retaining their CC status in one email. Collaborators then think that the response was incorrectly sent to them (as they're the only ones listed in the To: field) instead of the main user who logged the ticket.

### Steps to Reproduce

1. User sends email to target email address that osticket creates tickets from and CCs in 1+ other recipient.
2. Ticket gets created with the CC'd collaborators correctly included.
3. Respond to ticket in osTicket, allowing collaborators to be included (default behaviour).

**Expected behavior:** 
User and the collaborators receive single email (User listed in To: field and collaborators in CC: field) 

**Actual behavior:**
User and each collaborator receives an email that just has themselves in the To: field and no mention of any other recipients (either in To: or CC: fields). 

### Versions
v1.10 (901e5ea)
Apache/2.4.6 (Red Hat Enterprise Linux) OpenSSL/1.0.1e-fips PHP/5.4.16
Chrome Version 60.0.3112.113

**Comment by ntozier** [comment]
The actual behavior you are experiencing, is the way that it was designed and implemented on purpose.

**Comment by mfelber** [comment]
You could inform the recipients with this variable in the email template %{ticket.recipients}
https://github.com/osTicket/osTicket/issues/1764#issuecomment-76430726

**Comment by mlipok** [comment]
"was designed and implemented on purpose"
Could you and talk about the detalis ?

**Comment by sjregan** [comment]
It would be very useful for us if there was an option to control this behaviour. We would like only one outgoing email to be sent with all collaborators CC'd.
