### ISSUE TITLE
Feature Request : Assign Ticket to task

### ISSUE THREAD

**Issue by F3000** [osTicket/osTicket#3970]
Is there a feature which automatically assign a ticket to a task when a specific help topic is used ?

**Comment by ntozier** [comment]
Tasks are independent sets of things that need to be done.  Tickets are not assigned to tasks.  Its the other way around Tasks are linked to Tickets.  However no there is currently no way to do this by using Help Topics.

**Comment by iHunt101** [comment]
@ntozier  was right. You can use task if their is another work to be done to resolved the issue.
