### ISSUE TITLE
Remove Canned Response section from Open a New Ticket Screen

### ISSUE THREAD

**Issue by steveearle86** [osTicket/osTicket#3971]
Is it possible to remove the Canned Response section from the "Open a New Ticket" screen? It is not a feature we are intending to use

osTicket Version | v1.10.1 (9ae093d) 
Web Server Software | Apache/2.4.25 (Win32) OpenSSL/1.0.2j PHP/7.1.4
MySQL Version | 10.1.22
PHP Version | 7.1.4
Windows 7
Google Chrome

**Comment by JediKev** [comment]
You can remove the Canned Response field for Agent Replies but not for the Open A New Ticket page. To do this go to **Admin Panel > Settings > Knowledgebase** and disable **Enable Canned Responses**.

**Comment by steveearle86** [comment]
Thanks. Can this be added as a feature request?

**Comment by JediKev** [comment]
I have fixed this issue with my [pull request here](https://github.com/osTicket/osTicket/pull/4020). Please make the changes, test, and let me know how it goes! Cheers.

**Comment by steveearle86** [comment]
Yes, that has fixed it. Thanks!
