### ISSUE TITLE
See All Tickets

### ISSUE THREAD

**Issue by steveearle86** [osTicket/osTicket#3972]
Is there a way I can see all tickets in the system?

It appears that if I create a ticket and allocate it to another agent, only that agent can see it through their tickets tab. I can allocate to a group and then all the agents in that group can see it.

What I would like to do, if possible is allocate to an agent and have any of the agents be able to see the ticket in the tickets tab

Is there a way to do this?

osTicket Version | v1.10.1
Web Server Software | Apache/2.4.25 (Win32) OpenSSL/1.0.2j PHP/7.1.4
MySQL Version | 10.1.22
PHP Version | 7.1.4
Windows 7
Google Chrome

**Comment by ntozier** [comment]
Q: Is there a way I can see all tickets in the system?
A: Sure.  Add yourself to all Departments.

**Comment by steveearle86** [comment]
I've done the following but can't get it to work:

Admin Panel
Agents Tab
Departments Tab
Click the relevant department
Update Department Screen
Access tab
Select agent name from dropdown
Click Add
Choose "All Access" From dropdown list
Do the above for all agents in system
Go back to agent panel
Tickets tab
Click new ticket
Select user
Fill out ticket details (Select the department added above)
Assign to a different agent to myself but one that has been added to the department
Click Open
Go to tickets tab
The ticket is not there

What am I doing wrong?

**Comment by bbct** [comment]
Now that you are in all the departments, go to Search Advanced, and what I did was create a search that shows all tickets where the status is... Then select ALL of the statuses.  On the right you can then type a name for this query (ALL Tickets for instance), and click to save it.  So next time you just click this name, click Load, and then the Search button...

**Comment by steveearle86** [comment]
I think I've got it!
Thanks for the help

**Comment by mlipok** [comment]
It is a bit irrational that the manager, admin, owner ... could not easily monitor changes in the helpdesk.

Please look here:
http://osticket.com/forum/discussion/90986/activity-stream

**Comment by ruzinaleksandar** [comment]
Log in as an Administrator. Go to  Admin Panel -> Settings -> Tickets
Uncheck: Assigned Tickets: | Exclude assigned tickets from open queue.
