### ISSUE TITLE
OSticket v1.10.1 blank popup Apache Error 400 Bad Request

### ISSUE THREAD

**Issue by Rivamario81** [osTicket/osTicket#3974]
Versione osTicket | v1.10.1 (9ae093d)     —  Aggiornato
-- | --
Web Server Software | Apache
Versione MySQL | 5.5.35
Versione PHP | 5.5.9

![catturae](https://user-images.githubusercontent.com/11990922/30852008-b06bb2f0-a2aa-11e7-92bd-5f995a20408c.PNG)

### Description

[Description of the bug or feature]
![cattura](https://user-images.githubusercontent.com/11990922/30849478-c689a91e-a2a2-11e7-98d7-9b6598f9e1c9.PNG)

How to solve?

Please help me.

regards,

Mario

**Comment by JediKev** [comment]
What errors do you get in your Apache error logs?

**Comment by Rivamario81** [comment]
I've only access to FTP folder on server. is there a way to Apache Logs through PHP or some other way?

**Comment by JediKev** [comment]
Contact your host and get them to send you the error logs.

**Comment by JediKev** [comment]
@Rivamario81 what hosting company do you use?
