### ISSUE TITLE
Increase Issue Summary length

### ISSUE THREAD

**Issue by yafp** [osTicket/osTicket#3978]
### Description
The issue summary is currently limited to 50 characters.
That is kinda limiting ...at least for me ;)

### Versions
1.9.12

**Comment by ntozier** [comment]
1.9.12 is really old.  This is also not a bug.

**Comment by yafp** [comment]
> This is also not a bug.

True, it's a feature request

**Comment by fdellwing** [comment]
You can change the limit in your formular settings (at least in 1.10), so please close this issue.

**Comment by yafp** [comment]
worked - thanks for the pointer
