### ISSUE TITLE
Choose correct SLA for the choosen category if agent opens ticket

### ISSUE THREAD

**Issue by fdellwing** [osTicket/osTicket#3979]
![osticket1](https://user-images.githubusercontent.com/22813377/30969132-c2d45272-a461-11e7-862e-eaa53d72a850.png)

Expected behaviour:

1. Click "New ticket"
2. Choose any category that has a not default SLA
3. The SLA should be automatically changed

Actual behaviour:

3. The SLA stays on system default

**Comment by iHunt101** [comment]
I think you can set this to your form.

**Comment by fdellwing** [comment]
Please read the issue (point 2.) ;)

I did this, and it is working fine if a user opens the ticket. But it doesnt work if an agent opens the ticket.

**Comment by JediKev** [comment]
@fdellwing Thanks for the report. I fixed it with [this pull request](https://github.com/osTicket/osTicket/pull/4012). Please pull the changes, test, and let me know how it goes! Cheers.

**Comment by fdellwing** [comment]
Works :+1:

**Comment by JediKev** [comment]
@fdellwing Nice! Again, thanks for the report! Cheers.

**Comment by akash65** [comment]
SLA plan is not changing when i assign ticket to other agent..why?

**Comment by ntozier** [comment]
Agents do not have SLAs.  Why would it change if you assigned it to another agent?
