### ISSUE TITLE
The ticket was transfered to admin after closing instead to agent.

### ISSUE THREAD

**Issue by iHunt101** [osTicket/osTicket#3984]
### Description

I set a resolved status with a state of closed. Admin was assigned to close the ticket after agent changed it to resolved. But in the report, all of the tickets was owned by Admin instead of the agent. 

**Expected behavior:** The tickets should be owned by agent not Admin

**Actual behavior:** All tickets was owned by admin in the reports 

### Versions

osTicket (v1.10)
Windows Server
Google Chrome Version 58.0.3029.110

**Comment by ntozier** [comment]
This is not a bug and how it works.  Who ever actually closes [sets to **Closed**, not a custom status of Resolved] the ticket gets the credit for closing the ticket.

**Comment by iHunt101** [comment]
How about the closed date? The system log the last closed status in the report extraction instead of the first closed status..

**Comment by JediKev** [comment]
> How about the closed date? The system log the last closed status in the report extraction instead of the first closed status..

@iHunt101 could you show an example? I'm not really following.

**Comment by iHunt101** [comment]
Closing this. This is how ost works.
