### ISSUE TITLE
Feature Request/Question: Auto assign organization to team

### ISSUE THREAD

**Issue by Dubz** [osTicket/osTicket#3986]
Is it possible to assign an entire organization to a team, so if anyone from that organization opens a ticket it's automatically assigned to the correct team? In other words, any user in organization A, B, or C gets their ticket assigned to team 1 automatically, and those agents would get an alert (rather than the entire department).

I cannot do this by domain, since our system is internal and all runs off the same domain.

**Comment by ntozier** [comment]
Do you have a list of the org members?  You could set up Ticket Filters so that any time that staff opens a ticket the rule assigns their ticket to the correct department (or Team)

**Comment by Dubz** [comment]
I found it. I guess it would help if I actually opened the new ticket filter view to see what options were available. I just matched it by organization name and assigned it to their team. I already added the users to their own organization.

Is it possible to get a list of users not in any organizations? That way I can see if any of them got skipped over.

**Comment by ntozier** [comment]
the only way I can think to do that would be at the SQL level.  Something like:

SELECT name FROM ost_user WHERE ord_id='0';

**Comment by JediKev** [comment]
@ntozier I think you meant `WHERE org_id='0';` 😉

**Comment by Dubz** [comment]
Shouldn't be an issue for me since I have access, but maybe it could be added to the system in case someone who doesn't have access wants to see.

Thanks though!

**Comment by ntozier** [comment]
Oops... I typo-ed. :P
