### ISSUE TITLE
Feature Request: Add custom form field to ticket preview

### ISSUE THREAD

**Issue by Dubz** [osTicket/osTicket#3987]
Pretty simple, and I'm modifying my install at the moment to do this, but I'm too new to the system to make sure it's efficient enough to make a pull request for it.

Basically, if I were to add a custom form field to a ticket I could mark it to show on the ticket preview. That way, when I'm in the ticket list view, I can simply hover over the ticket number and see the data for that ticket. It's not hard to add in, but like I said I'm not too thorough with osTicket just yet to make it efficiently.

Here's an example of it. Pretty basic:
https://ss.dubzone.co/1507294807-LnGcnce5.png

**Comment by JediKev** [comment]
I have made this into a pull request here: https://github.com/osTicket/osTicket/pull/4016

Please check it out, test, and let me know how it goes! Cheers.

**Comment by Dubz** [comment]
Looks good to me, awesome!

I'll probably have to modify it though for my situation, since I generate one of the field's values with a JSON string. If there was a way to have quantity to an item added and also show here, that'd be perfect since that's what I need for my current situation.


Here's an example of what I see with your version:
https://ss.dubzone.co/1508500647-Ldxr49RJ.png

Here's the version I whipped up before you did yours:
https://ss.dubzone.co/1508500794-QinZIlrH.png


If you do find a way to add quantity options for a list rather than just the multi select from a list, that would be perfect. It could basically be a two column table, with a single select option on the left (similar to how it is now), and a quantity input on the right. Then all you would need is a + below the last row to add more rows to the list to add more items.

If I get some free time enough to look into doing it myself I might, but that might take some time and I'm still not familiar with all of the classes and methods of the system.
