### ISSUE TITLE
Issue: "My Tickets" view showing all tickets for all teams, not ones I'm in

### ISSUE THREAD

**Issue by Dubz** [osTicket/osTicket#3988]
I signed into a test account with an agent on one team, with one ticket assigned to that team. When I click the "My Tickets" link, however, it's showing multiple tickets. They're all under the same department, but not the same team. Am I doing this incorrectly, or is there a way to fix this? I assumed the "Open" view would show all tickets for the department, and the "My Tickets" would show personal ones/team ones.

https://ss.dubzone.co/1507299921-0uELLnoq.png

(Ignore the red exclamation mark, it's a mod I'm working on for our setup).

**Comment by ntozier** [comment]
"My Tickets" is all tickets that the Agent is assigned directly, or are assigned to a Department or Team that the Agent has access to.

**Comment by Dubz** [comment]
Is there a way to separate them? I know there's the option to limit agent to just tickets assigned to them, but we'd like to be able to see each others in a separate view if possible ("Open" view I'd assume).

Or, if there's an alternative route. The only other thing I could think of is making multiple departments so each one has their own team, then just ignore the teams part, but that seems like it'd be the wrong route, and end users may get confused if there's a bunch of options (if they even use the panel instead of just email).

**Comment by mlipok** [comment]
Please read this:
http://osticket.com/forum/discussion/91195/how-to-manage-tickets-assigned-to-agent#latest

**Comment by perryk** [comment]
I've noticed that "My Tickets" is showing tickets assigned to teams I am not a member of also.

Well, it shows any tickets which are assigned only to a team (that I'm not a member of) and **not** assigned to a person, however the ticket is for the same department as me.

As soon as the ticket is assigned to both a team (that I'm not a member of) and a specific person (other than me), it not longer shows in "My Tickets".

I was expecting "My Tickets" to show tickets which are assigned to teams I'm a member of, that is ok.
