### ISSUE TITLE
Issue: Buttons don't work entirely properly

### ISSUE THREAD

**Issue by Dubz** [osTicket/osTicket#3989]
Some of the buttons, for instance the edit ticket button, have their HTML flopped and in turn makes half of the button not work. If you press the button, but not the icon inside the button that's linked, nothing happens.

Here's the script I'm talking about:
https://ss.dubzone.co/1507313686-BbSxyMxC.png
Notice how the anchor is binded to the <i> tag since that's what's inside it, rather than the button. I'm not sure if anyone else has caught on to this issue, but it took me a minute to realize what was actually going on and I remember myself doing this a few years back.

The fix is rather simple. All that needs to happen is the button needs to go inside the anchor element, rather than the anchor in the button. That way the entire button is linked rather than just the icon. I'm still learning the system, so I'm not quite ready to make any pull requests, although I could probably for this.

**Comment by jdelhome3578** [comment]
Try #3453

**Comment by Dubz** [comment]
Looks great! Works correctly now
