### ISSUE TITLE
Ticket not automatically change status

### ISSUE THREAD

**Issue by iHunt101** [osTicket/osTicket#3992]
### Description

After i received the ticket, i assigned it to my agent, and it seems done if i check to assigned info. But still the ticket status did not change.

### Steps to Reproduce

1. Select the ticket number
2. Click assigned to Agent
3. Select the Agent and click assign button

**Expected behavior:** I expect that the ticket status was also changed from "**open**" into "**assigned**" since i already assigned the ticket to my agent.

**Actual behavior:** The ticket was assigned but the status did not changed into assigned.

### Versions

osTicket (v1.10)
Windows Server
Google Chrome Version 58.0.3029.110

**Comment by fdellwing** [comment]
I'm pretty sure the "assigned" status is a custom status, as I know no such thing in osTicket.

**Comment by JediKev** [comment]
@fdellwing is right. There is no `assigned` ticket status in osTicket.
