### ISSUE TITLE
OsTicket 1.10.1 HTTP 500 error on IIS

### ISSUE THREAD

**Issue by nicolafarina** [osTicket/osTicket#3993]
Hi all,

trying updating my osTicket to latest 1.10.1 on IIS 8 (php 5.3), I get an HTTP 500 error.

It seems that "main.inc.php" file is causing the issue.

Anyone else? Any help?

Thank you.

**Comment by JediKev** [comment]
Yea, you can't use PHP 5.3.x with osTicket v1.10.1... You'll have to use PHP version 5.4.x, 5.6.x, or 7.0.x! Cheers.
