### ISSUE TITLE
DNS issue with incorrect domain in email

### ISSUE THREAD

**Issue by Micke1101** [osTicket/osTicket#3995]
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [x] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

We currently have an email form that a seperate project is using to create tickets into osticket, this form lets users type in their own email address and then it sends an email from that email.
A user typed in an email like this **username@??domain.com** and whenever a staff member is trying to look at this ticket, all they get is a blank page with the warning message from the php error log.
**[09-Oct-2017 10:38:10 UTC] PHP Warning:  dns_get_record(): DNS Query failed in <osTicket path>\include\class.validator.php on line 164**
As soon as the question mark is removed in the database the staff member can see the ticket as normal.
I've tested commenting out line 164-165 just to make sure that these 2 lines were the culprit and also corrected the email address in the database and the behaviour is correct after doing either.

### Steps to Reproduce

1. Send an email using the php mail function from an email address that contains 2 question marks (haven't checked if that is needed but that's what we had) https://www.w3schools.com/php/func_mail_mail.asp example 2.
2. Import the email using a cron job
3. Try opening the ticket as a staff member

**Expected behavior:** 
I expect to see the ticket as normally but maybe see a warning or highlight of sort on the email that is not a correct email.
Maybe that the ticket gets rejected.

**Actual behavior:** 
The ticket gets accepted but staff members are presented with a white screen and a error message.

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.
![image](https://user-images.githubusercontent.com/22049466/31443056-a4c1b662-ae98-11e7-9d6b-bb680b2cc090.png)

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.
Windows 7
Internet explorer 11
Google Chrome 61

**Comment by JediKev** [comment]
In your form, is the email field an actual email field or is it a textbox field?

**Side Note:**
When I lived in Norway we had a saying that went "Yay for Norge! Boo for Sverige!"
We watched football too much lol 😂

**Comment by Micke1101** [comment]
It's just a textbox field so I'll tell them to change it to an email field, so that should solve the issue from that project but it's still a weird behaviour in my opinion :).

Yea the nordic countries rivalry is ancient, so I'm not surpriced!

**Comment by JediKev** [comment]
I totally agree. We should just reject the ticket or throw an error rather than killing the page lol

Yea, the person I was living with, her Mom's Boyfriend was from Sweden and everyone else was from Norway so we said that to him all the time to make him upset lol
