### ISSUE TITLE
Deleting organization Internal Note - Bug?

### ISSUE THREAD

**Issue by lawsangel** [osTicket/osTicket#3999]
Hello
Not sure if its a bug, but i can't seem to be able to delete internal notes under organization section.
There is a delete button, but it doesnt do anything.
Nothing major, just thought id point it out.

osTicket vv1.10.1 (9ae093d)
Windows 2012 R2 - Web Server Software - Microsoft-IIS/8.5
MariaDB - MySQL Version 5.5.37
PHP Version - 5.6.31 
Tried with both Internet Explorer, FIrefox and Safari on my iPhone.

**Comment by JediKev** [comment]
@lawsangel Mine is working just fine. It seems like AJAX isn't working because that button uses and AJAX request to delete the note.

**Comment by lawsangel** [comment]
Sorry for the late reply.
i use firefox, hope this helps....
![bug](https://user-images.githubusercontent.com/32745015/32440253-4fb6237c-c2ea-11e7-908b-c43c735d53d8.PNG)

**Comment by JediKev** [comment]
@lawsangel was that request Successful or Unsuccessful? Look for a status code on the request and post it here. Cheers.

**Comment by lawsangel** [comment]
Where do I find that on Firefox?

**Comment by JediKev** [comment]
Click on the **Network** tab instead of watching it on the **Console**. In this tab, whenever the request pops up, click on the request and it should give you the **Status Code** above the **Response Headers** section.

**Comment by lawsangel** [comment]
Status code: 404 not found.

**Comment by JediKev** [comment]
Yea Ajax seems to messing up...

Can you hover over a help tip anywhere in the system and see the help tip or is it just blank?

**Comment by lawsangel** [comment]
help tips seem to be working ok.
Just hovered over lots of them and all working.

**Comment by ntozier** [comment]
@JediKev I just confirmed that this is the same behavior on my installation.

**Comment by JediKev** [comment]
@lawsangel try looking [at this link](https://stackoverflow.com/questions/28568292/web-api-jquery-ajax-delete-request-returning-404) and see if this works for you. Cheers.

**Comment by lawsangel** [comment]
@JediKev i've looked at the link, but i'm not entirely sure what it's asking me to do :(

**Comment by JediKev** [comment]
@lawsangel It's basically telling you to compare your `Web.config` file's `system.webServer` section with the `system.webServer` section on the site and add some lines that yours does not have. Remember to keep track of the changes so you can revert back if anything goes wrong. Cheers.

**Comment by lawsangel** [comment]
Sorry, i'm really not good with this sort of stuff.

So this is my web.config file which i've opened with Notepad++

<?xml version="1.0" encoding="UTF-8"?>
<configuration>

    <system.webServer>
        <directoryBrowse enabled="false" />
        <rewrite>
            <rules>
                <rule name="HTTP api" stopProcessing="true">
                    <match url="^(.*/)?api/(.*)$" ignoreCase="true"/>
                    <conditions>
                        <add input="{REQUEST_FILENAME}" matchType="IsFile"
                            ignoreCase="false" negate="true" />
                        <add input="{REQUEST_FILENAME}" matchType="IsDirectory"
                            ignoreCase="false" negate="true" />
                    </conditions>
                    <action type="Rewrite" url="{R:1}api/http.php/{R:2}"/>
                </rule>
                <rule name="Site pages" stopProcessing="true">
                    <match url="^(.*/)?pages/(.*)$" ignoreCase="true"/>
                    <conditions>
                        <add input="{REQUEST_FILENAME}" matchType="IsFile"
                            ignoreCase="false" negate="true" />
                        <add input="{REQUEST_FILENAME}" matchType="IsDirectory"
                            ignoreCase="false" negate="true" />
                    </conditions>
                    <action type="Rewrite" url="{R:1}pages/index.php/{R:2}"/>
                </rule>
                <rule name="Staff applications" stopProcessing="true">
                    <match url="^(.*/)?scp/apps/(.*)$" ignoreCase="true"/>
                    <conditions>
                        <add input="{REQUEST_FILENAME}" matchType="IsFile"
                            ignoreCase="false" negate="true" />
                        <add input="{REQUEST_FILENAME}" matchType="IsDirectory"
                            ignoreCase="false" negate="true" />
                    </conditions>
                    <action type="Rewrite" url="{R:1}scp/apps/dispatcher.php/{R:2}"/>
                </rule>
            </rules>
        </rewrite>
        <defaultDocument>
            <files>
                <remove value="index.php" />
                <add value="index.php" />
            </files>
        </defaultDocument>
    </system.webServer>

</configuration>


Do i need to add this from the site into my web.config file?

<system.webServer>
    <handlers>
      <remove name="ExtensionlessUrlHandler-ISAPI-4.0_32bit" />
      <remove name="ExtensionlessUrlHandler-ISAPI-4.0_64bit" />
      <remove name="ExtensionlessUrlHandler-Integrated-4.0" />
      <add name="ExtensionlessUrlHandler-ISAPI-4.0_32bit" path="*." verb="GET,HEAD,POST,DEBUG,PUT,DELETE,PATCH,OPTIONS" modules="IsapiModule" scriptProcessor="%windir%\Microsoft.NET\Framework\v4.0.30319\aspnet_isapi.dll" preCondition="classicMode,runtimeVersionv4.0,bitness32" responseBufferLimit="0" />
      <add name="ExtensionlessUrlHandler-ISAPI-4.0_64bit" path="*." verb="GET,HEAD,POST,DEBUG,PUT,DELETE,PATCH,OPTIONS" modules="IsapiModule" scriptProcessor="%windir%\Microsoft.NET\Framework64\v4.0.30319\aspnet_isapi.dll" preCondition="classicMode,runtimeVersionv4.0,bitness64" responseBufferLimit="0" />
      <add name="ExtensionlessUrlHandler-Integrated-4.0" path="*." verb="GET,HEAD,POST,DEBUG,PUT,DELETE,PATCH,OPTIONS" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0" />
    </handlers>
  </system.webServer>

**Comment by JediKev** [comment]
@lawsangel Same here, as I've NEVER used IIS lol

Add the entire `<handlers>` section into your `system.webServer` section.

**Comment by lawsangel** [comment]
Is there a specific line i should be pasting it into?
I tried putting it under </defaultDocument> which ended up breaking OST.
I've now removed it.
Sorry my knowledge in coding of any type is pretty much 0

**Comment by JediKev** [comment]
Add it after `</defaultDocument>`.

>Sorry my knowledge in coding of any type is pretty much 0

It's okay, I just have 0% knowledge in Microsoft IIS so all of this is guessing based on the errors/facts presented. 😅

**Comment by lawsangel** [comment]
OK tried that, but it doesn't work, get an error 500 - internal server error. :(
No worries, not a huge deal i suppose.

**Comment by lawsangel** [comment]
So......
We never did use OSTicket in the end, i've however been asked to revisit it.
So, brand new install, new server and everything and i'm still having this exact same issue, can't delete an Organization note.

**Comment by JediKev** [comment]
@lawsangel 

I cannot replicate this error when using Apache, osTicket v1.10.4 and PHP v5.6. More details? (a screenshot of `Admin Panel > Dashboard > Information` would be nice)

**Questions:**
- Are there any errors via IIS/PHP error logs?
- Are there any errors in the database error logs?
- Are there any errors in osTicket System Logs?
- Are there any browser console errors?
- What are the exact steps to replicate this issue?
- Have you tried upgrading to 1.10.4 to see if that resolves your issue?

Cheers.

**Comment by lawsangel** [comment]
> 
> 
> @lawsangel
> 
> I cannot replicate this error when using Apache, osTicket v1.10.4 and PHP v5.6. More details? (a screenshot of `Admin Panel > Dashboard > Information` would be nice)
> 
> **Questions:**
> 
>     * Are there any errors via IIS/PHP error logs?
> 
>     * Are there any errors in the database error logs?
> 
>     * Are there any errors in osTicket System Logs?
> 
>     * Are there any browser console errors?
> 
>     * What are the exact steps to replicate this issue?
> 
>     * Have you tried upgrading to 1.10.4 to see if that resolves your issue?
> 
> 
> Cheers.

Are there any errors via IIS/PHP error logs?
Don't think so, looking at the log and it looks like it's attempting it (Assuming i'm looking at the right thing?
Replaced my IP with xx
2019-01-08 12:44:59 xxx.xxx.xxx.xxx DELETE /helpdesk/scp/ajax.php/note/2 - 9677 - xxx.xxx.xxx.xxx Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64;+rv:64.0)+Gecko/20100101+Firefox/64.0 http://xxx.xxx.xxx.xxx:port/helpdesk/scp/orgs.php?id=2 405 0 1 0

Are there any errors in the database error logs?
Not sure how to check that but i'll look into it now.

Are there any errors in osTicket System Logs?
No

Are there any browser console errors?
Just like before in the firefox network tab: Status code: 404 not found.

What are the exact steps to replicate this issue?
It doesn't matter which organizations i choose, when i create a note it will let me write, edit and save it, but when i hit the trashcan icon to delete it nothing happens, no error or mailtips, not even a rollover icon as if it's getting pressed, just nothing.

Have you tried upgrading to 1.10.4 to see if that resolves your issue?
It's a brand new fresh install of 1.10.4

**Comment by ntozier** [comment]
@JediKev clicking the delete icon on orgs in my 1.10.4 IIS 8.5 instance does nothing.

@lawsangel Do you have the DELETE verb enabled in your IIS?

**Comment by lawsangel** [comment]
I can PM you the url if you want to see whats happening (or not in this case)
It's not for production use, purely to demo to my boss.

**Comment by lawsangel** [comment]
> 
> 
> @JediKev clicking the delete icon on orgs in my 1.10.4 IIS 8.5 instance does nothing.
> 
> @lawsangel Do you have the DELETE verb enabled in your IIS?

I'll go give it a try

**Comment by JediKev** [comment]
@lawsangel 

So it appears IIS has issues with AJAX as it cannot find the path from the URL. Does anyone else have issues with IIS and AJAX that could chime in here?

When you click the Trash Can Icon the browser makes an AJAX request like below:
```
DELETE => /scp/ajax.php/note/(note_id) => scp/ajax.php => deleteNote()
Request Type => Request URL => File Triggered For Path Lookup & Function Calling => Function Called
```

It looks at the `scp/ajax.php` file, matches the path from the URL, calls the appropriate function and returns the results. If you click it and nothing happens then that means it cannot lookup or match the AJAX URL.

Cheers.

**Comment by ntozier** [comment]
@JediKev I can also tell you that the chrome console tells me:

``DELETE http://support.domain.tld/scp/ajax.php/note/2 404 (Not Found)    jquery-1.11.2.min.js?035fd0a:4``
![2019-01-08_1143](https://user-images.githubusercontent.com/1315768/50845342-9c21c300-133a-11e9-99f0-70dcd1f296af.png)

``2019-01-08 16:40:51 192.168.45.6 DELETE /scp/ajax.php/note/2 - 80 - 96.67.63.253 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/70.0.3538.110+Safari/537.36 http://support.domain.tld/scp/orgs.php?id=1 404 0 2 125``

Nothing appears in the PHP error log.

**Comment by lawsangel** [comment]
Assuming i'm doing the correct thing here...
Changed the request restrictions in "PHP_via_FastCGI" from GET,HEAD,POST to "All verbs"
Now i get a 500 error when clicking the delete icon in the firefox network tab.

**Comment by ntozier** [comment]
Yes that is how you do it.  But you have to stop/start the site after the change.
Enabling the DELETE verb made it so I can delete notes.

**Comment by lawsangel** [comment]
Just to confim that adding DELETE into PHP_via_FastCGI has fixed the issue.
I can now delete notes.
Thanks again for your help :)
