### ISSUE TITLE
Wrong number of open tickets (1.9.14)

### ISSUE THREAD

**Issue by cervedgroup** [osTicket/osTicket#4006]
### Prerequisites

* [ X] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [ X] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [ X] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description
Open ticket number is wrong
The number of open tickets, show in the "open" queue is wrong.

[Description of the bug or feature]

### Steps to Reproduce
Open the staff console and watch the numeber near "open" queue.
The numebr is not correct 
**Expected behavior:** [What you expected to happen]
Correct number of open tickets
**Actual behavior:** [What actually happened]
random number of open tickets

### Versions
1.9.14
see the image : 
it reports 21 open tickets, but only 2 are open

![image](https://user-images.githubusercontent.com/6535381/31664114-7a6e1382-b344-11e7-9474-2dcf8ad5dec0.png)

**Comment by JediKev** [comment]
Go to **Admin Panel > Agents > Agents > click your name > Access** and see if you have access to all Departments in the helpdesk. If not, add yourself to all Departments and retest.

**Comment by cervedgroup** [comment]
obviusly i need the correct number of the department that i have access to and not the open tickets at all departements

**Comment by JediKev** [comment]
It's because you have the `Exclude assigned tickets from open queue.` setting enabled and the `Exclude answered tickets from open queue.` setting disabled. Go to **Admin Panel > Settings > Tickets**, enable the `Exclude answered tickets...` setting, Save Changes and retest.

**Side Note:** Don't get upset when someone tries to help you...that _really_ made me not want to help you.

**Comment by cervedgroup** [comment]
My intention was not to get upset, maybe the problem was my "limited" english . 
Thank you for your help!

**Comment by JediKev** [comment]
@cervedgroup Did this work for you?

**Comment by cervedgroup** [comment]
i'm testing, seems working ...

**Comment by JediKev** [comment]
Awesome! Please let us know if you encounter any more issues with this. Thanks for the report!
