### ISSUE TITLE
Cookies not HTTPOnly

### ISSUE THREAD

**Issue by k3an3** [osTicket/osTicket#4015]
https://github.com/osTicket/osTicket/blob/55dc25ace736baeaf224ee608cfabc0218022036/include/class.ostsession.php#L56

It's 2017, there are very few reasons to not set the cookies as HttpOnly. Why not enable it by default? Just add `true` as the last parameter in the call to set the cookie.

**Comment by JediKev** [comment]
First of all, thanks for the report! I guess this is one of those things that were meant to be implemented but forgotten about for a while. I have made a pull request that fixes this issue [here](https://github.com/osTicket/osTicket/pull/4017). It should be merged into the next release and all future versions will include the fix. Thanks again! Cheers.
