### ISSUE TITLE
Last update field alway empty

### ISSUE THREAD

**Issue by cervedgroup** [osTicket/osTicket#4022]
### Prerequisites

upgraded osticket from 1.9.14 ... 

* [x ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [ ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [ ]x Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

Last update field empty

**Expected behavior:** [What you expected to happen]
last update field with correct date and time of last update (open o rely to ticket)
**Actual behavior:** [What actually happened]
empty field
### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.
1.10.1
iis 7.5
mysql 5.5.32
php 5.5.11
Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.
win7 / chrome / IE

![image](https://user-images.githubusercontent.com/6535381/32000954-9112fe68-b998-11e7-8730-be8134fb5ac0.png)

**Comment by JediKev** [comment]
You messed up your time formatting somehow. Please post a screenshot of **Admin Panel > Settings > System > Date & Time Options**.

**Comment by cervedgroup** [comment]
![image](https://user-images.githubusercontent.com/6535381/32006367-f1a6127a-b9a6-11e7-9c93-8945ba3101bf.png)

**Comment by cervedgroup** [comment]
lol solved changing H:mm in HH:mm in date and time format !
thank you

**Comment by JediKev** [comment]
Yea...that's why..

Glad you got it working! Please close this issue.
