### ISSUE TITLE
Assigning a ticket hangs on "Loading"

### ISSUE THREAD

**Issue by cervedgroup** [osTicket/osTicket#4023]
### Prerequisites

* [ x] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [ ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [ x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

when assign a ticket to another operator, the ticket was assigned but the intrface hangs on "Loading" until ESC is pressed.
Tryed with CHROME 62.0.3202.62 (32bit)
Explorer 11.0.9600.18816 
on windows 7

 
Admin panel -> Dashboard -> Information which also additionally gives you information about you server.
1.9.10
iis 7.5
mysql 5.5.32
php 5.5.11

![image](https://user-images.githubusercontent.com/6535381/32008190-e53e5470-b9ab-11e7-99f9-a7c820c1e607.png)

**Comment by JediKev** [comment]
This does not happen for me...please update to version 1.9.15 or 1.10.1 and retest. Cheers.

**Comment by cervedgroup** [comment]
we have latest version 1.10.1

**Comment by cervedgroup** [comment]
it hangs when i ticket that is assigned to me is going to be assigned to another operator
if the ticket is assigned to another operator and i'm going to assign to me, it works correctly

**Comment by JediKev** [comment]
You said `1.9.10` here:
```
1.9.10
iis 7.5
mysql 5.5.32
php 5.5.11
```

Post a screenshot of **Admin Panel > Dashboard > Information**.

**Comment by cervedgroup** [comment]
correct,  we have 2 installations, production and test
now i'm testing the "TEST" with 1.10.1 .
Tryed from 2 different clients, with chrome and IE same result :(

![image](https://user-images.githubusercontent.com/6535381/32009312-0dea56be-b9af-11e7-967e-e515374f5861.png)

**Comment by JediKev** [comment]
Try installing the APCu and Zend Opcache PHP extensions and re-test.

**Comment by cervedgroup** [comment]
ehm ... do you know wich ones ? 
![image](https://user-images.githubusercontent.com/6535381/32009475-88e6d7de-b9af-11e7-9194-3ae57d25ee95.png)

**Comment by JediKev** [comment]
The APCu extension will have to be downloaded from PHP's site and added via PHP Manager.

Zend Opcache is the `php_opcache.dll` one...after you enable it you have to edit your `php.ini` file, add `zend_` to the beginning of the `extension=php_opcache.dll` to make it `zend_extension=php_opcache.dll`.

**Comment by cervedgroup** [comment]
thanks i'll try and let u know..

**Comment by JediKev** [comment]
@cervedgroup also hover over a Help Tip anywhere in the helpdesk and see if you see some content. If you get just a blank popup then AJAX is the issue.

**Comment by cervedgroup** [comment]
ajax seems ok, the help tips opens correctly.
after installed zend_extension , now  Admin Panel > Dashboard > Information after some minutes , 
show this error : PHP Fatal error:  Maximum execution time of 30 seconds exceeded in C:\Osticket\upload\include\mysqli.php on line 192

**Comment by cervedgroup** [comment]
solved the timeout problem setting in php.ini : max_execution_time = 360
Installed and enabled apcu (php_apcu-4.0.10-5.5-ts-vc11-x86), but the osticket system info shows 
![image](https://user-images.githubusercontent.com/6535381/32050541-6f129eb8-ba51-11e7-96f2-e96dc58a5ac3.png)

and iis 
![image](https://user-images.githubusercontent.com/6535381/32050363-d1ef0dba-ba50-11e7-8dc6-6ea1709a7744.png)

"loading hangs" problem, still present

**Comment by cervedgroup** [comment]
okay, tryed the php_apcu-4.0.10-5.5-nts-vc11-x86 and now the osticket system info shows 
![image](https://user-images.githubusercontent.com/6535381/32051882-a33ff500-ba56-11e7-98d3-0d8abacb547f.png)
but the problem is still present :(

**Comment by cervedgroup** [comment]
also clicking on username inside of ticket, hangs on "loading" ....
![image](https://user-images.githubusercontent.com/6535381/32052197-c108e758-ba57-11e7-8f3b-b437f9d0cc7a.png)

**Comment by cervedgroup** [comment]
just to let you know, i've solved upgrading php to latest version available from web platform installer.
seems that the php 5.5 is not fully compatible with new version of osticket  :+1: 
![image](https://user-images.githubusercontent.com/6535381/32054573-14637cf4-ba5f-11e7-8dac-a55a77b3a8e4.png)

**Comment by JediKev** [comment]
@cervedgroup 
>seems that the php 5.5 is not fully compatible with new version of osticket 

That is incorrect as I have PHP 5.4 and it works with 1.10.1 perfectly. Maybe it was the way your IIS compiled PHP that didn't play well with v1.10.1? Anyways, glad you got this working! Cheers.
