### ISSUE TITLE
How Assign Account Manager in Organization

### ISSUE THREAD

**Issue by vieckzand** [osTicket/osTicket#4025]
I want to ask how to assign account manager in organization?
![2017-10-27_09-35-02](https://user-images.githubusercontent.com/1054904/32085643-a0f4c948-bafa-11e7-8c22-5c10d3227f64.jpg)
Thank you

**Comment by JediKev** [comment]
Click the Org name above that field then click Settings. Cheers.

**Comment by vieckzand** [comment]
Thank for your help :)
