### ISSUE TITLE
1.10.1 - Wrong text editing ticket

### ISSUE THREAD

**Issue by cervedgroup** [osTicket/osTicket#4028]
### Prerequisites

* [ x] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [ ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [ x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description
Editing ticket , this text is present 
"Internal Note: Reason for editing the ticket (required)  "
but the Reason is not required, it is possible to edit ticket without writing any text in the note (and this is good)
Is possible to change the text ? how to change the text in localized language ?
Thank you !

**Comment by JediKev** [comment]
Download a language pack: osticket.com/download

**Comment by JediKev** [comment]
Are you saying that the string **Internal Note: Reason for editing the ticket (required)** is not translated when using the language pack? Or are you saying that the string _is_ translated, you just want to change it in the language pack?

**Comment by cervedgroup** [comment]
The string is incorrect in both versions (translated and not ), beacause filling the form is not mandatory.
I need to know how to change the translated version.
thank you

**Comment by cervedgroup** [comment]
i've tryed , but after changing this line in
'Reason for editing the ticket (required)' => 'Motivo della modifica del Ticket (opzionale)',
with notepad ++ , the system goes in english and the only way to get back to italian is downloading and replacing the it.phar ... seems that the modify corrupt the file , is possible ?

**Comment by JediKev** [comment]
Of course it's possible. I can edit my file just fine but I have a _totally_ different setup then you. Your best bet would be to suggest the changes on i18n.osticket.com and wait for them to be merged into the next lang pack build. Cheers.

**Comment by cervedgroup** [comment]
ok, but i suppose u need to change also the english string because is wrong .
thank you

**Comment by JediKev** [comment]
I'm making the pull request as we speak. Cheers.
