### ISSUE TITLE
Is osticket alive?

### ISSUE THREAD

**Issue by antgel** [osTicket/osTicket#4029]
It seems unusual that there are 247 open PRs, indicating a lot of momentum / desire to contribute code, but relatively few commits going into the develop branch, and nothing on master since 2016.

**Comment by JediKev** [comment]
Yet there was a new release September 14th...?

We can't just blindly merge everything into `master`. Plus we don't really push to `master`, only `develop`. Also, there has to be complete testing on each pull request (making sure it doesn't break anything) and making sure that it fits our code style and the future vision of osTicket. We would like to go through each one and merge and release more often but we are a _very_ small team and have so many things going on. Not only do we develop osTicket, we also do our cloud hosted option SupportSystem and do all kinds of professional support, migrations, etc. We plan to set aside specific days to go through the pull requests in the future so you'll start seeing more recent commits.

As always, just be patient. We have big releases and features coming soon. Cheers.

**Comment by antgel** [comment]
Great to hear. I didn't see the release, I just looked at `master:HEAD`. Thanks a lot for the information!
