### ISSUE TITLE
Password reset page is not showing

### ISSUE THREAD

**Issue by dmnc-net** [osTicket/osTicket#4030]
http://myserver/osticket-latest/pwreset.php redirects me directly to index.php without desired page

v1.10.1 (9ae093d) and v1.10-78-gacac370 (acac370)

**Comment by JediKev** [comment]
Works fine for me on v1.10.1. Any errors?

**Comment by dmnc-net** [comment]
just HTTP 302 in the apache's log

**Comment by JediKev** [comment]
Try putting `AcceptPathInfo On` in your main `.htaccess` file, restart Apache and re-test. Let me know how this goes. Cheers.

**Comment by dmnc-net** [comment]
@JediKev `AcceptPathInfo` doesn't affect the behavior but I found some problem. Since I'm using LDAP Authentication and Lookup plugin I've disabled Allow Password Resets (scp/settings.php?t=agents) which is related to Staff only. But I realized this affects users too. When this option is Enabled, redirection (pwreset.php#L76) didn't occur.

**Comment by JediKev** [comment]
Ahhh I see the issue now. It seems like the User's page is checking that option as well. I'm going to look into this shortly.

**Comment by dmnc-net** [comment]
I just found that this issue has been found by users and documented on the [forum](http://osticket.com/forum/discussion/comment/115922/) ... a few moths before my issue but no one created the issue here. Hope github issues has bigger priority in dev than discussion because a long time ago someone redirected me from the forum to github.

**Comment by JediKev** [comment]
@dmnc-net here is the pull request that fixes this issue: https://github.com/osTicket/osTicket/pull/4082

Cheers.

**Comment by dmnc-net** [comment]
@JediKev sorry for my ignorance but what is the best practice here, creator of the ticket closes it when PR is solving the issue or better to wait for the PR merge or someone else will close this? I'm confused from the PR which is still open and I understand this like "not implemented in the main code". So due to this I think it is better to let this issue opened/unresolved.

**Comment by JediKev** [comment]
@dmnc-net it's whatever you feel like doing. Cheers.

**Comment by lucize** [comment]
I have issues with password reset on agents, I made some local authenticated agents and without setting a password and it sent an email invite, after the agent is entering the email address the page will do nothing, only it will not show to enter the user or email address
Also if I select an agent and try to reset a password via email, the password change menu will show only if the agent logs on with user and password (and it will ask the old password)
tried on latest stable 10.x and latest git 11.x

**Comment by dmnc-net** [comment]
pwd reset page is ok in v.1.12 (a076918)
