### ISSUE TITLE
Osticket 1.9.16: Frontend Issue In Organisation Section

### ISSUE THREAD

**Issue by ATalker** [osTicket/osTicket#4036]
### Prerequisites

* [N] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [N] Do you have any errors in the PHP error log, or javascript console?
* [Y] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [Y] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description
**Is it Bug or Feature?** 
There are no two things in Users->Organisations->My Organisation->Tickets Tab 

1. Columns headers are not clickable and you can not sort ticket per column
![ot1916_org_section_1](https://user-images.githubusercontent.com/13776659/32220682-10ed780e-be4c-11e7-9612-15a4058d40d8.jpeg)
2. There is no footer with pages and ticket export  like in Ticket Section
![ot1916_org_section_2](https://user-images.githubusercontent.com/13776659/32220899-d8ed11a2-be4c-11e7-89e6-e6d2e318bd83.jpeg) Btw for example: If custom company create 800 tickets, Osticket will draw long ticket list  here without paging

**Server**
Apache/2.4.6
PHP 5.6.31

**Client:**
OS: Debian 9.0
Browser:  Firefox 56.0.2

**Comment by JediKev** [comment]
**Issue 1:**
This is just how it is. Maybe turn this one into a Feature Request.

**Issue 2:**
This is fixed in v1.10.1. I would suggest upgrading to the latest release of the v1.10.x series.

**Comment by ATalker** [comment]
Thank you  for feedback.
But in my mind Osticket 1.10.1 is still far from stable state and last release ( 1.10.1 ) is still beta.
Btw I think that Osticket 1.9.12 is the most stable release now.

**Comment by ntozier** [comment]
Your response makes no sense to me.  The last beta was 1.10-rc3... which is ancient.
1.10.1 is the latest stable version.
1.9.12 is old.
1.9.16 is a maintenance release and the latest stable in the 1.9 tree, but not the latest stable version (which is of course 1.10.1).

**Comment by JediKev** [comment]
@ATalker what..?

**Comment by ATalker** [comment]
@ntozier why no sense? Use brain)
My bug request is about 1.9.16
It has issues.
1.9.16 is maintenance release. 
So it makes sense to hope that issues will be fixed

**Comment by ATalker** [comment]
@ntozier Great to hear that!  I agree with you that factually 1.10.1 is stable. But also i wrote that **in my mind** ot 1.10.1 is still far from stable state. This is my opinion. 

I agree with with you and JediKev about first issue. But for second ( wrong footer ), it seems to that developers just forgot "to attach" correct js+css+template fro this section or something like that.

**Comment by JediKev** [comment]
@ATalker 

>You suggest 1.10.1. But for me this is not an option. Because i think that 1.10 is still very unstable. That is all.

That is your opinion and you are allowed to have that. You'll just miss out on a lot of new features thinking this way.

>Also we have 1.9.16, it is Maintenance Release. For me maintenance is fixing presenting bugs.

This is true, but it doesn't mean it'll fix EVERY SINGLE existing bug. That's why a software have _multiple_ maintenance releases.

>what about 1.9.16 for this issue? no hope for fixing ?

We usually don't backport 1.10.x series features for the 1.9.x series. The only thing the 1.9.x series will get is more maintenance releases, no new features.

>I agree with with you and JediKev about first issue. But for second ( wrong footer ), it seems to me that developers just forgot "to attach" correct js+css+template for this section or something like that.

That's why we added it to the 1.10.x series. In order to get this feature you'll have to upgrade.

P.S. Your feature request for **Issue 1** will be added to the 1.10.x series or the series after that, not the 1.9.x series. (just letting you know)
