### ISSUE TITLE
Attach / Upload file - 403 Forbidden

### ISSUE THREAD

**Issue by sandeepts** [osTicket/osTicket#4038]
I am using 
Osticket v1.10 (901e5ea)

When I upload file for new ticket as a customer/agent, I get this error
Can you please suggest what really causing here?

![image](https://user-images.githubusercontent.com/3186692/32251652-f4109128-beb7-11e7-9036-8eb70c548204.png)

**Comment by JediKev** [comment]
What's your max upload size and how big is the file you are attaching?

**Comment by sandeepts** [comment]
32kb file

**Comment by JediKev** [comment]
Try updating `pptx, docx, doc, pdf, png` to `.pptx, .docx, .doc, .pdf, .png`.

**Comment by sandeepts** [comment]
changed extension, but same issue. 
![image](https://user-images.githubusercontent.com/3186692/32252420-56902086-bebb-11e7-8bdf-166bdc13c387.png)

When I try to ticket with attachement using email then it works. Only through web forms is not working. Does FileInfo is mandatory?

**Comment by sandeepts** [comment]
Please suggest?

**Comment by JediKev** [comment]
Judging by what the extension is used for I'd say yes in this case. Add that extension and test again.

**Comment by sandeepts** [comment]
Ok. But files being saved when i do email to create a ticket?

**Comment by JediKev** [comment]
I cannot replicate this issue at all, and being that I don't have access to your stuff and there are no errors I'm just making educated guesses. Try adding the extension and test again.

**Comment by EliteSir** [comment]
Hallo everyone,

i have now the same error. It was before upload erorr: 500 now 403. Any sugesstion ?
