### ISSUE TITLE
Feature: Support for ticket variables in department signatures

### ISSUE THREAD

**Issue by Ketrel** [osTicket/osTicket#4041]
### Description

It could be useful to allow for ticket variables to be used in department signatures
An example use case could be

`Support Department,`
`A reminder, your ticket is: %{ticket.status}`

Useful for if it's pending approval, needing customer input, etc.

### Versions

Currently not present in 1.9 nor 1.10

**Comment by JediKev** [comment]
Just curious. Why put the variable in the Dept. signature when you can add it to any existing template? (eg. Response/Reply Template) This way every response has `A reminder, your ticket is: %{ticket.status}` in it.

**Comment by Ketrel** [comment]
Because there's cases where you might not want that to show, which if in the signature, you can choose to omit, but if in the template, you cannot.

**Comment by JediKev** [comment]
Gotcha! Just wondering.

**Comment by JediKev** [comment]
A workaround, for now, would be to add `A reminder, your ticket is: %{ticket.status}` to a canned response. This way when you're done writing your response and you want to add that variable to it you can simply choose the canned response and it'll automatically add the variable wherever your cursor is.

### Example

**Canned Response:**
![screen shot 2017-11-02 at 09 55 14](https://user-images.githubusercontent.com/11823401/32332641-fc8887e6-bfb3-11e7-88f5-4e2512da9726.png)

**Using Canned Response:**
![canned_status](https://user-images.githubusercontent.com/11823401/32332660-0af06bd2-bfb4-11e7-98c0-139b512b8d09.gif)

**Comment by Ketrel** [comment]
That's what I currently do, but that has the unfortunate downside of requiring the agents to be proactive...which is to say, it only happens when I'm the agent in question.
