### ISSUE TITLE
User registration form validation issue

### ISSUE THREAD

**Issue by giannicuccu** [osTicket/osTicket#4043]
### Prerequisites

* [Y] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [N] Do you have any errors in the PHP error log, or javascript console?
* [Y] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [Y] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description
osTicket (v1.10.1)
On  the public user registration form the validation control of required fields fails  if the user provide just the 2 password fields. 

### Steps to Reproduce

1. access to the public user registration page (account.php?do=create)
2. fill just the password fields with valid data
3. click register

**Expected behavior:** 
validation error for required fields (at least email and name)

**Actual behavior:** 
no validation errors are returned, registration took place with missing user data

### Versions

![ost](https://user-images.githubusercontent.com/2619767/32370728-6efd8ad0-c08e-11e7-8b13-9e4e739b12bf.png)

**Comment by ntozier** [comment]
confirmed on 1.10 also.

**Comment by JediKev** [comment]
@giannicuccu @ntozier Could one of you make the changes in [this pull request](https://github.com/osTicket/osTicket/pull/4045), test it again, and let me know if this solved it. Cheers.

**Comment by ntozier** [comment]
confirm that this PR https://github.com/osTicket/osTicket/pull/4045 fixes the issue.

**Comment by JediKev** [comment]
Awesome! Thanks @ntozier, you da' bomb!
