### ISSUE TITLE
Question about db tables in 1.10.1

### ISSUE THREAD

**Issue by cervedgroup** [osTicket/osTicket#4051]
Searched in wiki and other issues, with no luck ...

Please i need to know how to find a thread entry starting from a ticket_id in ost_ticket table.
I have the "ticket_id" from ost_ticket and found that it is the same of the fied "object_id" in ost_thread , i can't found how is linked in ost_thread_entry
I need this info to extract stats from the db , in 1.9.14 tables and fields was different

Thank you

**Comment by JediKev** [comment]
@cervedgroup Look at the `ost_thread` table, find the thread associated with the ticket by searching for the `ticket_id` in the `object_id` column (`object_type` has to be `T` for ticket), then get the thread's `id` and look up the thread in the `ost_thread_entry` table by `thread_id`. Now you'll get all the thread entries associated with the ticket. Easy as pie! 👍

Cheers.

**Comment by JediKev** [comment]
@cervedgroup Look at the ost_thread table, find the thread associated with the ticket by searching for the ticket_id in the object_id column (object_type has to be T for ticket), then get the thread's id and look up the thread in the ost_thread_entry table by thread_id. Now you'll get all the thread entries associated with the ticket. Easy as pie! 👍

Cheers.
