### ISSUE TITLE
Email non sent if a user reopen a ticket - 1.10.1

### ISSUE THREAD

**Issue by cervedgroup** [osTicket/osTicket#4052]
### Prerequisites

* [X ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [ ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [X ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

If a user reopen a closed ticket , by email, the email was not sent to staff (in 1.9.14 this issue was not present).
The email is correctly sent opening new tickets via email

### Steps to Reproduce
user reply to a closed ticket
no email was sent to operator 
**Expected behavior:** [What you expected to happen]
A warning email was sent to operator

**Actual behavior:** [What actually happened]
no email sent to operator

**Comment by JediKev** [comment]
I cannot replicate this on my v1.10.1 install...make sure you have all the correct Alert settings and check your spam box. Maybe some of your alerts are going to spam?

**Comment by cervedgroup** [comment]
no spam/antispam for that kind of emails .. this is our settings 
![image](https://user-images.githubusercontent.com/6535381/32504407-05c2dde0-c3e0-11e7-8c59-9c10a3ede8fb.png)

the normal opening ticket email and also email when customer reply to a ticket, are delivered ...

**Comment by JediKev** [comment]
Which of the above alerts are you expecting to go to the Agent when an End-User re-opens the ticket via email?

**Comment by cervedgroup** [comment]
i suppose "Avviso di nuovo messaggio" , that is set to "the operator/team assigned" so in this case , that have closed the ticket.

**Comment by JediKev** [comment]
Yea, I'm getting the email just fine with exactly your settings...are you getting any osTicket errors or PHP/Apache errors?

**Comment by cervedgroup** [comment]
no errors found in osticket log  and on iss, php shows a lot of warnings
[PHP56_errors.rar.zip](https://github.com/osTicket/osTicket/files/1456834/PHP56_errors.rar.zip)
