### ISSUE TITLE
Adding collaborators  - search works only with name e not surname - 1.10.1

### ISSUE THREAD

**Issue by cervedgroup** [osTicket/osTicket#4053]
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [ ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

[Description of the bug or feature]
Adding collaborators , trying to search, found the user only searching it by name and not by surname.

search by  surname (no results)
![image](https://user-images.githubusercontent.com/6535381/32487984-763d9248-c3ab-11e7-8fae-75f1a736051e.png)

search by name 
![image](https://user-images.githubusercontent.com/6535381/32488290-6c57a1a0-c3ac-11e7-9d97-9d80b0c9c2bf.png)

### Steps to Reproduce

try to add a collaborator and search it by surname, no result

**Expected behavior:** [What you expected to happen]
find the collaborator by surname

**Actual behavior:** [What actually happened]
collaborator not found

**Comment by JediKev** [comment]
@cervedgroup I cannot replicate this on my v1.10.1 install...I can look up the User by first and last name with no issues. Post a screenshot of **Admin Panel > Settings > Users > Name Formatting**, this way I can try to replicate this exactly.

**First Name Search:**
![screen shot 2017-11-07 at 09 20 26](https://user-images.githubusercontent.com/11823401/32501206-0b7b6560-c39d-11e7-95b8-b0de82f9a84e.png)

**Last Name Search:**
![screen shot 2017-11-07 at 09 20 18](https://user-images.githubusercontent.com/11823401/32501216-13081184-c39d-11e7-82d1-be8f2d27f4b3.png)

**Comment by cervedgroup** [comment]
here it is 
![image](https://user-images.githubusercontent.com/6535381/32594677-3a90f5ea-c52d-11e7-9b24-d9494c51d85a.png)

**Comment by cervedgroup** [comment]
@JediKev have u replicated the issue ? thank you

**Comment by JediKev** [comment]
@cervedgroup I cannot replicate this issue. I have made the name formatting just like yours and I'm able to search by both names just fine. Are you getting any errors via osTicket, PHP, or Apache?

**Comment by ntozier** [comment]
@cervedgroup versions of apache? php? mysql?
@JediKev same question.

**Comment by cervedgroup** [comment]
we use IIS 7.5.7600.16385
PHP 5.6
Mysql : Server version: 5.5.32-MariaDB

**Comment by JediKev** [comment]
CentOS 7
PHP 5.4
MariaDB 5.5.52

**Comment by cervedgroup** [comment]
doing some test ... seems that for a newly created user (from USER tab), the search found the user.
for a users that are automatically created from an incoming mail (that are 100% of our users) the search did not found anything ... i've analyzed the ost_user and ost_user_cdata and found no differences ... any ideas?
thank you

**Comment by JediKev** [comment]
If all the records are the same in both tables then I'm not sure what the heck is wrong...are you getting any errors via osTicket, PHP, or Apache?

**Comment by JediKev** [comment]
Users that are created via email are no different than Users created by the Staff. Do the Users that are being found have a record in the `ost_user_account` table? Or do all the Users have records there?

**Comment by mfelber** [comment]
Could be a bug in MariaDB 5.5.32, the release is from 18 Jul 2013.

**Comment by cervedgroup** [comment]
mmm a bug that only affects that query ?

**Comment by JediKev** [comment]
@cervedgroup it's possible...I've seen some crazy things.

Are you using LDAP or anything like that to Authenticate Users or are you using the default Authentication? If you're using the default Auth then I have no idea what's wrong as you aren't getting errors and it's working just fine for me with the same settings.

**Comment by cervedgroup** [comment]
we are only using the ldap plugin to authenticate the staff in the scp panel.

**Comment by JediKev** [comment]
Ahhhh that could be the issue then. Unfortunately, I do not have LDAP installed and can't test this to debug.

**Comment by cervedgroup** [comment]
but the ldap is only to authenticate staff at the login, no other things is done via ldap ...
we are searching collaborator in the local db , i'll try to authenticate a local user and see if this is the probl.

**Comment by JediKev** [comment]
Oh, my apologies. I misread your response. I was thinking you were using LDAP for both Agents _and_ Users. Hmm...I'm not really sure then.

**Comment by cervedgroup** [comment]
i don't know how is possible to link the users to ldap ... is it possible ? our users db is populated with the data that come from emails, beacause we only open tickets by mail

**Comment by JediKev** [comment]
It's possible, just go to the LDAP config and Enable Auth for Users. (very end of page)

Yea that should be fine as that's how mine is...I'm just baffled that it's not working for you but for me it does with basically the same settings...

**Comment by cervedgroup** [comment]
tryed to 
upgraded to mariadb 10.2 
login with local auth.
still not working ... i'll try to upgrade to php 7 ...

**Comment by JediKev** [comment]
PHP 7 might break osTicket...especially on IIS. You can try it but don't freak out if it blows up everything lol

**Comment by cervedgroup** [comment]
funny ... i'm in testing enviroment :)

**Comment by cervedgroup** [comment]
php 7.0.21 , adding collaborator search, don't work at all (not by name or surname). this kind of error is written in php log
UrlMatcher->dispatch('', Array)
#3 C:\Osticket\upload\include\class.dispatcher.php(120): Dispatcher->resolve('', Array)
#4 C:\Osticket\upload\include\class.dispatcher.php(38): UrlMatcher->dispatch('/users', NULL)
#5 C:\Osticket\upload\scp\ajax.php(262): Dispatcher->resolve('/users')
#6 {main}
  thrown in C:\Osticket\upload\include\class.orm.php on line 1283
[17-Nov-2017 16:36:43 UTC] PHP Warning:  Declaration of AssignmentForm::render($options) should be compatible with Form::render($staff = true, $title = false, $options = Array) in C:\Osticket\upload\include\class.forms.php on line 4367
[17-Nov-2017 16:36:43 UTC] PHP Warning:  Declaration of TransferForm::render($options) should be compatible with Form::render($staff = true, $title = false, $options = Array) in C:\Osticket\upload\include\class.forms.php on line 4487
[17-Nov-2017 16:36:44 UTC] PHP Fatal error:  Uncaught OrmException: Union queries must have matching values counts in C:\Osticket\upload\include\class.orm.php:1283
Stack trace:
#0 C:\Osticket\upload\include\ajax.users.php(89): QuerySet->union(Object(QuerySet))
#1 C:\Osticket\upload\include\class.dispatcher.php(145): UsersAjaxAPI->search()
#2 C:\Osticket\upload\include\class.dispatcher.php(38): UrlMatcher->dispatch('', Array)
#3 C:\Osticket\upload\include\class.dispatcher.php(120): Dispatcher->resolve('', Array)
#4 C:\Osticket\upload\include\class.dispatcher.php(38): UrlMatcher->dispatch('/users', NULL)
#5 C:\Osticket\upload\scp\ajax.php(262): Dispatcher->resolve('/users')
#6 {main}
  thrown in C:\Osticket\upload\include\class.orm.php on line 1283
[17-Nov-2017 16:36:47 UTC] PHP Warning:  Declaration of AssignmentForm::render($options) should be compatible with Form::render($staff = true, $title = false, $options = Array) in C:\Osticket\upload\include\class.forms.php on line 4367
[17-Nov-2017 16:36:47 UTC] PHP Warning:  Declaration of TransferForm::render($options) should be compatible with Form::render($staff = true, $title = false, $options = Array) in C:\Osticket\upload\include\class.forms.php on line 4487
[17-Nov-2017 16:36:48 UTC] PHP Fatal error:  Uncaught OrmException: Union queries must have matching values counts in C:\Osticket\upload\include\class.orm.php:1283
Stack trace:
#0 C:\Osticket\upload\include\ajax.users.php(89): QuerySet->union(Object(QuerySet))
#1 C:\Osticket\upload\include\class.dispatcher.php(145): UsersAjaxAPI->search()
#2 C:\Osticket\upload\include\class.dispatcher.php(38): UrlMatcher->dispatch('', Array)
#3 C:\Osticket\upload\include\class.dispatcher.php(120): Dispatcher->resolve('', Array)
#4 C:\Osticket\upload\include\class.dispatcher.php(38): UrlMatcher->dispatch('/users', NULL)
#5 C:\Osticket\upload\scp\ajax.php(262): Dispatcher->resolve('/users')
#6 {main}
  thrown in C:\Osticket\upload\include\class.orm.php on line 1283

**Comment by cervedgroup** [comment]
php 7.1.7 search only works with name ... not surname .. no error logged

**Comment by mfelber** [comment]
I have seen this type of error (PHP Fatal error:  Uncaught exception 'OrmException' with message 'Union queries must have matching values counts') in this github issue https://github.com/osTicket/osTicket/issues/3544 which is linked to a fix https://github.com/osTicket/osTicket/pull/3456 from @ntozier .

**Comment by JediKev** [comment]
@mfelber OOO!! You're right!!

@cervedgroup try #3456 and see if that fixes your issue!!

**Comment by cervedgroup** [comment]
DAMN ! i found the correct "bug" ... in production enviroment and also in testing ... if i search a surname "Trump" the search gives me no response ... if i search a surname "rump" the search found "Trump" !

**Comment by JediKev** [comment]
@cervedgroup Have you tried #3456 yet? If not try this and let us know! Cheers.

**Comment by cervedgroup** [comment]
applyed #3456 and now it works !!! problem solved , thank you!
