### ISSUE TITLE
Knowledge Base API for the integration 

### ISSUE THREAD

**Issue by kanikashetty** [osTicket/osTicket#4054]
We have our own software for the front end creation of ticket but we also need integration for OsTicket Knowledge Base. Is there any API to access the knowledge Base??

**Comment by mfelber** [comment]
As far as I know there is only API access to create tickets and tasks:
https://github.com/osTicket/osTicket/blob/develop/setup/doc/api.md

One developer has mentioned a complete revamp of the api will come but there is no more information yet what will be included and when it will come: https://github.com/osTicket/osTicket/issues/3973#issuecomment-335810796

**Comment by ntozier** [comment]
@mfelber is correct.
