### ISSUE TITLE
Feature Request Visible field but only fillable for agents 

### ISSUE THREAD

**Issue by luiizfenix** [osTicket/osTicket#4055]
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

[Description of the bug or feature]

Option to avoid EndUsers to fill certain field in the form but make it only fillable for agents so it can be shown as a "status information info" in the Ticket information. 

For Example: My Case, 

I'm using a form to have customers request for spare parts they provide all the information regarding this also the shipping address and after i process the request i need to provide them with a tracking number for they to keep track of the delivery, currently i just send it as a reply but it might get lost if the issue has multiples replies after that. 
I want it to be with all the ticket information. 

### Steps to Reproduce

Actual options are: 

> -Enable
> -Visible        For EndUsers      For Agents
> -Required         For EndUsers      For Agents
> -Editable         For EndUsers      For Agents
> -Data Integrity    Require entry to close a thread

If used:
    
>  Visible: for both, 
>      Required: none 
>      Editable only for agents. 

It can be first filled by the user and not only for agents 
Obviously the EndUser can't edit it anymore but still if the EndUser fills the field it will contain information not relevant. 

**Expected behavior:** [What you expected to happen]
Field only fillable by staff
**Actual behavior:** [What actually happened]
Field is also fillable for EndUser

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.

osTicket Version | v1.10.1 (9ae093d)
Apache Version | 2.4.23
PHP Version | 5.6.26
MySQL Version | 5.6.33
Architecture | x86_64
Operating System | linux

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

OS: Windows 10 Home 64 bit
Browser: Google Chrome Version 61.0.3163.100 (Official Build) (64-bit)

**Comment by JediKev** [comment]
This actually isn't a feature request, it's a bug. You see we were checking `elseif (!$field->isVisibleToUsers() && !$field->isEditableToUsers())` when it should've been `elseif (!$field->isVisibleToUsers() || !$field->isEditableToUsers())`. I'm making a pull request that fixes this issue. Once done I will post the link here for you to make the changes and test again. Cheers.

**Comment by JediKev** [comment]
The pull request is here: https://github.com/osTicket/osTicket/pull/3888

Please make the changes, test them, and let me know if this works for you. Cheers.

**Comment by luiizfenix** [comment]
Hi JediKev, 

In fact your pull request fixed the issue but now a different issue appeared after the fix. 

Information Field is missing from EndUser create ticket mode. 
I was using it as a Disclaimer but after aplying this fix it suddenly dissapeared from form. 

It shows as Visible for EndUser and Agents in configuration but as i think its happening it is validating the "editable for EndUser" to show in the form.

**Comment by luiizfenix** [comment]
sorry hit the wrong button. 
@JediKev 
Hope you can help with the above message.

**Comment by JediKev** [comment]
Change `include/client/templates/dynamic-form.tmpl.php` line 25 from `elseif (!$field->isVisibleToUsers() || !$field->isEditableToUsers()) {` to `elseif (!$field->isVisibleToUsers() && !$field->isEditableToUsers()) {`. Also add the following after line 19:
```
elseif (!$field->isEditableToUsers())
    continue;
```

Test this and see if your Information field comes back and your other field disappears like you want. Cheers.

**Comment by luiizfenix** [comment]
Hi @JediKev it kinda worked but now is showing again the field that we were previously triying to hide from creation mode. End user can still fill it while creating. 

Is there any way to call for $type so it can be validated for field type like 
```
elseif (!$type->info() ) 
     continue;
```

I'm really new to this so is my only aproach on how to fix it. 
since Info field only has Visible permision

**Comment by luiizfenix** [comment]
Hi @JediKev , 

any help here?

**Comment by JediKev** [comment]
@luiizfenix look at my [pull request here](https://github.com/osTicket/osTicket/pull/3888) again and make the appropriate changes. I've updated it to work as intended:
- If the Field is marked **Visible** for Users but **Not Editable** for Users then the User will be able to see and input to the field upon creation and will be able to see the field and data in the ticket view but the User will not be able to see/edit the field when they click Edit.
- If the Field is marked **Visible** and **Editable** then the User will be able to see/edit the field in all states of the ticket.
- If the Field is marked **Non-Visible** and **Non-Editable** to Users then the User will not be able to see/edit the field at all in any state of the ticket.

I know it's a lot but I hope this makes sense! Cheers.

**Comment by luiizfenix** [comment]
Hi @JediKev ok noted about how it is visioned to work by your team, but how about some other permission or something that prevents user to fill the field and only allow the agent to fill it while making it visible to the user if provided by the agent. 

See again my example, that's why i meant this to be a "Feature Request"
I'm having a spare part request by a form and a helptopic but i need to provide a tracking number to the customer while storing it in a variable inside the database so i can search for it later if needed. 
The issue is that if the field "isVisible" while in create 'mode' the Enduser has the ability to fill the field that is meant to be filled by the agent once the request is processed. 
If the Field is not visible to the Enduser, it doesnt show while on create 'mode' but also it doesnt show while in view 'mode' or status mode. 

Maybe it is not really a useful feature for everyone but it is for me. 

If you can point to me the right direction i can edit it myself to my needs but i don't know what else i can edit to make it behave the way i want. 

Best Regards,

**Comment by JediKev** [comment]
Maybe add a condition that checks for the field's name then you could exclude that field specifically from the create mode? Like this, `include/client/templates/dynamic-form.tmpl.php` lines 17-20:
```php
if (isset($options['mode']) && $options['mode'] == 'create') {
    if ($field->get('name') == 'name_of_field')
        continue;
    elseif (!$field->isVisibleToUsers() && !$field->isRequiredForUsers())
        continue;
}
```

The `'name_of_field'` is pulled from the `ost_form_field` table's `name` column.

Hope this helps! Cheers.

**Comment by luiizfenix** [comment]
Hi @JediKev Actually that didn't solve my problem but it pointed me to the appropiate resolution i'll post it here in case anyone wants to implement something similar. 
on `include/client/templates/dynamic-form.tmpl.php`
add the following after line 19:

```
elseif (!$field->isEditableToUsers())
    continue;
```
then After: 
```        
elseif (isset($options['mode']) && $options['mode'] == 'edit') {
            if (!$field->isEditableToUsers())
                continue;
			}
```
add the following:

```
elseif ($field->get('name') == 'name_of_field') {
			continue;
		}
```
The `'name_of_field'` is pulled from the `ost_form_field` table's `name` column.
I noticed that if i add this lines inside the `if (isset($options['mode']) && $options['mode'] == 'create') {`
it doesn't have any effect so i took it out and voilá.

and changing line 30(for me):
`elseif (!$field->isVisibleToUsers() && !$field->isEditableToUsers()) {`
to:
`elseif (!$field->isVisibleToUsers() && (!$field->isEditableToUsers() xor $field->get('type') == 'info')) {`

Now "Tracking number" field is hidden to the user on creation mode while visible if having any data when ticket is reviewed by the Enduser, and also stored in the database for easy search. 

Thanks for the help, i'll close this.
