### ISSUE TITLE
Custom forms can't be deleted after saving in User Directory - Manage Forms

### ISSUE THREAD

**Issue by dmnc-net** [osTicket/osTicket#4059]
SCP > Users > User Directory > [user] > ⚙ More - Manage Forms
- add custom forms
- save
- once saved, added forms can't be deleted

v1.10.1 (9ae093d)

**Comment by ntozier** [comment]
Confirmed in v1.10.1

![4059](https://user-images.githubusercontent.com/1315768/32553944-4204297c-c466-11e7-8590-f44226b2ad97.PNG)

Clicking the trash can does nothing.
mousing over the trashcan results in a url of osticketurl.tld/scp/users.php?id=9999#   (where 9999 is the actual user id#)
Nothing gets logged to the PHP error log.

**Comment by JediKev** [comment]
You gotta try this pull request: https://github.com/osTicket/osTicket/pull/3543

**Comment by ntozier** [comment]
https://github.com/osTicket/osTicket/pull/3543 fixes this in my environment.
