### ISSUE TITLE
SMTP Authentication Error: OSTicket 1.10.1

### ISSUE THREAD

**Issue by lewishackfath** [osTicket/osTicket#4062]
Whenever I try to use SMTP with authentication i get the following error:

authentication failure [SMTP: Invalid response code received from server (code: 535, response: Incorrect authentication data)]

I have extensively checked all the credentials and everything is correct.

My server configuration is as follows:

Server Information
--
osTicket Version | v1.10.1 (9ae093d) —  Up to date
Web Server Software | Apache/2.4.25 (Unix) OpenSSL/1.0.1e-fips mod_bwlimited/1.4
MySQL Version | 5.5.58
PHP Version | 5.5.38
--
I have tried with multiple different SMTP servers and credentials which i know work as I have used them on other sites not using OS ticket. Can anybody please help this is causing a lot of headaches.

**Comment by mfelber** [comment]
Normally the osticket forum (http://osticket.com/forum/categories/osticket-1-10-troubleshooting-and-problems) is a better place to get questions answered about the usage of osticket.

Also I would suggest to use PHP 5.6 it works better with osticket and has not the disadvantage that it has reached its end of life. PHP 5.5 reached its end of life in the mid of last year. This means it doesn't get bug fixes and security fixes which is important to support you and and for the security of your system. This behavior could for example be a bug or incompatibility with this old PHP version.

Posting screenshots of your mail account config in osticket would also be helpful to understand what could be the reason of this problem.
