### ISSUE TITLE
gtld name with more than 4 characters is not properly supported

### ISSUE THREAD

**Issue by gregoiregentil** [osTicket/osTicket#4063]
See attached screenshot:
![domain-name-long](https://user-images.githubusercontent.com/486156/32592264-cde6898c-c4d7-11e7-8254-9a698f63f2b1.png)

I have a gtld domain name .tennis and all emails are cut off after 4 character in the hyperlink

**Comment by gregoiregentil** [comment]
Yes, it seems to fix the situation. You can close my issue if you want. Thanks.

**Comment by mfelber** [comment]
I'm only an user ;-) I think when you created this github issue than you can close it by yourself.
When I create a github issue and it is solved, I close it too by myself. It think this is the intended process.
