### ISSUE TITLE
Blank attached .eml file in MS Outlook

### ISSUE THREAD

**Issue by kekaru** [osTicket/osTicket#4064]
Hi,

I have an issue with attached .eml file in osticket v1.10. 

Here's the scenario:

1. I've replied to the ticket with an attached .eml file on it. (Posted a reply using OSTicket portal)
2. The collaborators were able to receive an email with regards to that ticket. They viewed the attached .eml file directly on their MS Outlook app and it shows blank.

![image](https://user-images.githubusercontent.com/26477153/32599984-13d3adb6-c579-11e7-8e30-8fe667c25339.png)

I've tried to send the .eml file directly to someone's email address and he was able to view the content of the .eml file.

It seems there's something wrong with sending emails from OSTicket with attached .eml files.

Looking forward to your swift response!

Thanks,

**Comment by ntozier** [comment]
Might be related to https://github.com/osTicket/osTicket/issues/1711
or this might help: https://github.com/osTicket/osTicket/pull/3418

**Comment by kekaru** [comment]
Hi, thanks for your swift response. However, the fixes mentioned in #3418 were already included in v1.10.

The attachment link on the ticket thread on emails is working. But, the attachment on MS Outlook is always blank when viewed. Please refer to my screenshot below.
![image](https://user-images.githubusercontent.com/26477153/32642853-0d60dec4-c612-11e7-9289-e62d2f2049f3.png)

![image](https://user-images.githubusercontent.com/26477153/32642869-29823850-c612-11e7-8390-9cb4163b9951.png)

Thank you,

**Comment by mfelber** [comment]
@kekaru 

I think you are mistaken: the fixes mentioned in https://github.com/osTicket/osTicket/pull/3418 are not included in osTicket 1.10 or 1.10.1. 

This pull request is open and therefore it is not included yet.

**Comment by kekaru** [comment]
My bad! I wasn't informed that one of my devs modified the codes. Unfortunately, these modifications still coludn't fix this issue. :(

**Comment by mfelber** [comment]
Maybe this helps you https://github.com/osTicket/osTicket/issues/3278#issue-166250038

**Comment by vsousariv** [comment]
This is exactly what is happening in my system. all I could find is for people on v1.10. here are my details. Please point me the right direction if there's a fix I blindly couldn't find. 
![image](https://github.com/user-attachments/assets/ccbe147e-0ab8-431e-bd33-07a1bd4fa0dd)

**Comment by JediKev** [comment]
@vsousariv 

You can’t find a fix because this hasn’t been an issue in quite a while. You are seemingly the only report on 1.18.x so far. You should really start your own thread [on the Forum](https://forum.osticket.com) and post the full raw email including headers (censor any sensitive information) so we can test. We can look into it on the Forum then open a new Issue here if we determine it’s an actual bug.

Cheers.
