### ISSUE TITLE
Newly created teams not shown in Teams assignment (1.10.1)

### ISSUE THREAD

**Issue by cervedgroup** [osTicket/osTicket#4065]
### Prerequisites

* [ x] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [ ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [ x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description
![image](https://user-images.githubusercontent.com/6535381/32612360-60171ad4-c568-11e7-9b29-60ac0b3994d8.png)

where is the "Helpdesk-Backlog" team ?
![image](https://user-images.githubusercontent.com/6535381/32612452-a979f160-c568-11e7-862c-e4bf0514b4e1.png)

thank you

**Comment by JediKev** [comment]
Add yourself to the new teams and try again 😉  Cheers.

**Comment by ntozier** [comment]
I was about to ask if the team had anyone in it.

**Comment by cervedgroup** [comment]
yes, there is one operator in the team
![image](https://user-images.githubusercontent.com/6535381/32613655-c80b7eca-c56b-11e7-9091-9005a8654bec.png)

**Comment by JediKev** [comment]
Add **_yourself_** to the department and re-try. Cheers.

**Comment by cervedgroup** [comment]
"Team Helpdesk" has noone inside and i can assign a ticket to it

**Comment by cervedgroup** [comment]
with me inside the team i can assign ... so i need to be a member of a team to assign ticket to it ?
why other teams has no that limitation ?

**Comment by JediKev** [comment]
>with me inside the team i can assign ... so i need to be a member of a team to assign ticket to it ?

Of course.

>why other teams has no that limitation ?

I have no idea...what are the settings of the "other teams"?

**Comment by cervedgroup** [comment]
same settings .. this one has no members inside 
![image](https://user-images.githubusercontent.com/6535381/32613986-8651b8b8-c56c-11e7-9faa-ddf2ebdb9e2f.png)

![image](https://user-images.githubusercontent.com/6535381/32614006-95359d54-c56c-11e7-80ef-aabd63192c0a.png)

**Comment by cervedgroup** [comment]
old teams was created with 1.9.14 before the migration to 1.10.1 ...

**Comment by JediKev** [comment]
Could you post a screenshot of records in the `ost_team` and `ost_team_member` tables in the database?

**Comment by JediKev** [comment]
@cervedgroup Also, are you sure that you can assign tickets to `Team HelpDesk`? Because from your earlier screenshots I don't see `Team HelpDesk` listed as a choice in the Assignment dropdown.

**Comment by cervedgroup** [comment]
![image](https://user-images.githubusercontent.com/6535381/32735578-67fd4054-c895-11e7-88b1-4b4631f45628.png)

![image](https://user-images.githubusercontent.com/6535381/32735591-723b2892-c895-11e7-9a88-d172c09eab09.png)

**Comment by cervedgroup** [comment]
maybe i've deleted the Team Helpdesk , btw i can assing to 
![image](https://user-images.githubusercontent.com/6535381/32735676-af836e62-c895-11e7-828a-97d2656c2c0d.png)

**Comment by JediKev** [comment]
I was mistaken in my following response:
>>with me inside the team i can assign ... so i need to be a member of a team to assign ticket to it ?

>Of course.



It turns out you don't have to be a member of the team in order for you to assign to them (at least on my installation). The team just needs to have at least 1 active agent in it and anyone should be able to assign to that team.

You're saying that no-one is a part of the `Team HelpDesk` team but you can still assign to it, right? Judging from your screenshots that is incorrect. As you see there is no `staff_id` associated with `5` (the `Team HelpDesk` team's `team_id`) and I don't see `Team HelpDesk` in the Assignment dropdown.

So, what's the issue?

**Comment by cervedgroup** [comment]
you u right!
