### ISSUE TITLE
HTML/XML Code gets parsed even if wrapped in code formatting

### ISSUE THREAD

**Issue by fdellwing** [osTicket/osTicket#4069]
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

The response field for agents parses every HTML/XML code inserted, even if you wrap the code in code (pre) formatting.

### Steps to Reproduce

1. Parse some XML code in a response
2. Select the text and choose "code" from formatting options
3. Save the response
4. All entered start and end tags are gone, only text remains (if you enter HMTL code, it gets interpreted)

**Expected behavior:** 
Not f***ing touching my code in a code formatting

**Actual behavior:** 
I'm getting angry and want to destroy my keyboard

### Versions
![ost18](https://user-images.githubusercontent.com/22813377/32648830-e1504d2a-c5f7-11e7-8a9d-b570f5f31e4e.png)

**Comment by mfelber** [comment]
Could this be related to the htmlLawed-configuration?
https://github.com/osTicket/osTicket/pull/3691

Maybe you just have to add xml like a-schild added tel and sip.
Don't know how this will affect the security..

**Comment by fdellwing** [comment]
I think you dont understand the problem: Code wrapped in code formatting should be displayed as text and never get touched.

Here is some code to test the problem:

```xml
<Gesundheits_Krankenpfleger>
<Personalerfassung>
<Anzahl_VK>542,03</Anzahl_VK>
<Beschaeftigungsverhaeltnis>
<Personal_mit_direktem_BV>
<Anzahl_VK>525,69</Anzahl_VK>
</Personal_mit_direktem_BV>
<Personal_ohne_direktem_BV>
<Anzahl_VK>16,34</Anzahl_VK>
</Personal_ohne_direktem_BV>
</Beschaeftigungsverhaeltnis>
<Versorgungsform>
<Ambulante_Versorgung>
<Anzahl_VK>9,86</Anzahl_VK>
</Ambulante_Versorgung>
<Stationaere_Versorgung>
<Anzahl_VK>532,17</Anzahl_VK>
</Stationaere_Versorgung>
</Versorgungsform>
</Personalerfassung>
[...]
</Gesundheits_Krankenpfleger>
```

**Comment by mfelber** [comment]
Now I can understand a little bit better what you mean. 

But if htmlLawed is configured not to allow "xml" how will it decide that the tags you are using is not xml and should be not stripped out? 
I guess it only looks after <> </> tags which are characteristic for xml and filter them out. Does this make sense? Have you tried to add xml in the configuration to see if it makes a difference?

**Comment by fdellwing** [comment]
I tried it, and it does not make any difference.

**Comment by mfelber** [comment]
Sorry, just wanted to help. But now I think this is a thing that a developer or moderator could better understand who is knowing more about the redactor plugin of osticket. Maybe @JediKev or @ntozier have an idea..

**Comment by fdellwing** [comment]
Thanks for trying @mfelber this problem really goes on my nerves.

**Comment by mfelber** [comment]
Can understand that. Such things are puzzles in my head that I want to solve ;-)
In the js-folder there is a config-file for the html editor (redactor from imperavi).
It is called redactor.min.js. In that file there is an allowedTag-Section.

Maybe this is the place where the stripping out could be handled.
At least it sound so..

**Comment by mfelber** [comment]
Here is a documentation I found: https://imperavi.com/assets/pdf/redactor-documentation-10.pdf
It looks to me that you have to define each tag name which should be allowed.

For example when <Gesundheits_Krankenpfleger> should not be stripped out you must add Gesundheits_Krankenpfleger to the section. Oh god, this is not very flexible. Maybe there is an on/off switch for the filtering..

**Comment by mfelber** [comment]
Seems that it uses either an whitelist (allowedTags) or a blacklist (deniedTags). Both is not possible.
Switching to use the black list will be more flexible (like is wanted in your case) but offer less security.

**Comment by Micke1101** [comment]
@mfelber is correct, it's htmlawed that is filtering out your xml
You can read the following 2 topics on the forum for a little explanation
http://osticket.com/forum/discussion/90583/bug-sanitzing-with-hmlawed-redactor-and-js-code-tag-in-frontend-is-ignored-and-will-be-rendered
http://osticket.com/forum/discussion/comment/116484/#Comment_116484
