### ISSUE TITLE
Ticket list > DIV instead of A wrapping subject field

### ISSUE THREAD

**Issue by esamo** [osTicket/osTicket#4070]
Middle (or Ctrl) clicking won't work as expected (we want new tab) when A is mistagged as DIV
http://take.ms/hyZqB

Works alright when fixed as on the screen above. Exact place in back-end code is pointed out.

---

Config & versions
http://take.ms/xmqOJ

**Comment by jdelhome3578** [comment]
PR #3795 fixes this issue
