### ISSUE TITLE
Improper date column sort param while default sorting

### ISSUE THREAD

**Issue by esamo** [osTicket/osTicket#4072]
When the default sort is applied at Open tickets list, the date column header has improper sort param attached (the same as default sort 'priority,date') instead of 'date', so staff experiences it as a bug.
Staff thinks it should sort by date when clicking on date.
http://take.ms/u6RVJ

---

Config and versions http://take.ms/xmqOJ

**Comment by JediKev** [comment]
Try this pull request: https://github.com/osTicket/osTicket/pull/4060

Cheers.

**Comment by esamo** [comment]
Nope :(. I've posted an answer in the mentioned pull request page.
