### ISSUE TITLE
Checkbox `send_login_errors` not affecting the mails being sent

### ISSUE THREAD

**Issue by esamo** [osTicket/osTicket#4073]
With the checkbox `send_login_errors` unchecked I still get this info sent to the mailbox.
Same with info about `client_max_logins` limit reached. I don't think I can disable those mails?

---

Config & versions http://take.ms/xmqOJ

**Comment by JediKev** [comment]
@esamo I have made a pull request that fixes this issue: https://github.com/osTicket/osTicket/pull/4086

Please make the changes, test, and get back to me. Cheers.
