### ISSUE TITLE
Forms field management gets wider than the website

### ISSUE THREAD

**Issue by esamo** [osTicket/osTicket#4074]
There's a screen shot. I can provide more info as this happens every time.
http://take.ms/adA58

---

Config & versions http://take.ms/xmqOJ

**Comment by ntozier** [comment]
Version of osTicket?
Other environment details?
Does it also happen when not using Language packs?

**Comment by esamo** [comment]
I've already pasted the whole versions info page in the original post as a link.

For the original English language the problem stays the same, a bit better though.
http://take.ms/nhIWg

**Comment by esamo** [comment]
By the way I couldn't find the place to report translation issues. Can anybody point me the right way?

**Comment by mfelber** [comment]
I can only replicate this behavior with safari (Version 11.0.1 (13604.3.5)
With chrome (62.0.3202.89) and firefox (56.0.2 (64-Bit)) the layout is fine.

**Comment by esamo** [comment]
So have you made the same fields as I have? It would not be really a fine layout if it breaks as soon as fields are added :D.

The problem will disappear with lower 'size' param set to test input fields. First has 32 and the second 20.

I'm on Chrome v62.0.3202.89.

**Comment by mfelber** [comment]
I don’t created any field. Just a fresh install. Nothing was changed after the install. 

Seems a layout incompability with safari.

**Comment by esamo** [comment]
But it happens on Chrome with the fields already presented in the screen shot.

**Comment by mfelber** [comment]
Maybe there are more than one side effects.

**Comment by esamo** [comment]
Size param for field width is not a cross-browser solution anyway
https://stackoverflow.com/questions/27313704/cross-browser-setting-input-size-attribute
