### ISSUE TITLE
Uncaught exception in admin after upgrade: 1.9.14 -> 1.10.1

### ISSUE THREAD

**Issue by Deewde** [osTicket/osTicket#4075]
Can't see the Custom List Items in admin after upgrading from 1.9.14 to 1.10.1. The Manage->Lists->[Ticket Statuses list]->List page dies with the PHP error below:

PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'List indices should be integers' in /var/www/osticket/new/include/class.util.php:149
Stack trace:
#0 /var/www/osticket/new/include/class.forms.php(81): ListObject->offsetExists('state')
#1 /var/www/osticket/new/include/class.list.php(1047): Form->getField('state')
#2 /var/www/osticket/new/include/class.list.php(1078): TicketStatusList->getConfigurationForm()
#3 /var/www/osticket/new/include/staff/templates/list-items.tmpl.php(64): TicketStatusList->getSummaryFields()
#4 /var/www/osticket/new/include/staff/dynamic-list.inc.php(226): include('/home/provenda/...')
#5 /var/www/osticket/new/scp/lists.php(202): require('/home/provenda/...')
#6 {main}
  thrown in /var/www/osticket/new/include/class.util.php on line 149

Web Server Software | Apache
MySQL Version | 5.6.38
PHP Version | 5.6.32

Installed Language Packs
English - US (English) —
en_US — include/i18n/en_US

**Comment by ntozier** [comment]
unable to reproduce this in my upgraded 1.10.1 installation.

**Comment by mfelber** [comment]
This look to me like the problem with the wrong string conversion:https://github.com/osTicket/osTicket/issues/3397

Are you able to open the tab properties tab (../scp/lists.php?id=1#properties) where you can configure the properties of the list and check if some are disabled? If so try to enable them and see if this makes the list available again:

![enable properties](https://user-images.githubusercontent.com/5539456/32718726-49ae68b2-c85e-11e7-9f06-0057cc6ee298.png)

When this is not possible look into your database and check if some flags for the properties have weird values like "0". This is a screenshot from a working fresh install (this values are showing the correct value for enabled properties):

![enabled flags](https://user-images.githubusercontent.com/5539456/32718756-62751ff8-c85e-11e7-8b17-117faded6b93.png)

**Comment by Deewde** [comment]
Opening the properties tab is not possible. Looking in the **ost_form_field** table I see these values:

```
SELECT DISTINCT flags FROM `ost_form_field`;

489251
13057
12289
489249
292641
30465
290977
282867

```

**Comment by mfelber** [comment]
Looks ok for me. Maybe the wrong flags are in other tables or a in a field from a linked form. Not easy to find the source of this problem. Is the custom list used in a form and is there something disabled?

**Comment by Deewde** [comment]
As I see it, it's not actually a custom list in the true sense, like when you create a new custom list altogether. This is the default undeletable **Ticket Status** list, which doesn't store its data in the _ost_list_items_ table, but in the _ost_ticket_status_ table.

```
SELECT DISTINCT flags FROM `ost_ticket_status`;

0
```

**Comment by mfelber** [comment]
In my installation all flags for this table are showing the value "0" too. So far I have no problems noticed but It was afresh install and not an upgrade from 1.9.14 like in your case. I can normally open the "Ticket Status List" after adding a new list item. Weird. Maybe on of the developers like @JediKev has a hint for you how to to do further research for this issue. I have no ideas more so far.
Another user in the forum has made the same experience: http://osticket.com/forum/discussion/91356/issue-after-upgrading-1-9-14-to-v1-10-1-9ae093d#latest
So I guess the source of the problem is coming from upgrading osTicket version 1.9.14 to 1.10.1.

**Comment by Deewde** [comment]
Bringing the ost_ticket_status over to a fresh installation makes the page work. Could it be related to a form entry then?

**Comment by mfelber** [comment]
Then I would think the wrong value is somewhere else in the database.

**Comment by JediKev** [comment]
@Deewde So you're saying you moved the `ost_ticket_status` table and records from a fresh install to your upgraded instance and now it's working?

**Comment by mfelber** [comment]
@JediKev I think he did the opposite to check if the error is in the ost_sticket_status-table. But let's wait what he will answer..

**Comment by Deewde** [comment]
No, quite the opposite. I brought the `ost_ticket_status` table from the upgraded instance to the fresh installation and it works.

**Comment by mfelber** [comment]
@Deewde Little hint for your issue comments: "it works" sounds like the issue is solved. But I guess you would only say that you checked the source of the problem is not in the ticket_status_table and the issue is still there, which is more precise and could not be misinterpreted so easy..

**Comment by Deewde** [comment]
@mfelber You are correct, apologies for the confusion

**Comment by mfelber** [comment]
@Deewde Don't worry. My comments are sometimes too a little bit confusing ;-)

**Comment by JediKev** [comment]
@Deewde Have you tried pointing the new install's `include/ost-config.php` to your upgraded db and test that way? If not, I would suggest doing this and get back to me with the results. If the old database works with the new code then it's definitely the old code that's messed up and replacing it with the new version's code should fix it. If not then it's definitely something with the db.

**Comment by Deewde** [comment]
@JediKev Yes, I've already done that. The new install's files pointed to the old upgraded database fail to display the lists.php page with the error in the original post. The new install's files pointed to the new database it has just created, but with the `ost_ticket_status` I've copied from the upgraded database works.

So yes, it's definitely something with the database.

**Comment by JediKev** [comment]
I'm not really sure then....post a screenshot of the `State` and `Description` records from the `ost_form_field` table. (make sure they have the same `form_id`; should be `6` or something)

**Comment by Deewde** [comment]
The upgraded database (which fails with the error in the OP) has an ost_form.id of 5, but has no corresponding rows in the `ost_form_field` table.

The fresh database (which doesn't fail) has an ost_form.id of 6 and has the two rows you're asking about:

![untitled](https://user-images.githubusercontent.com/30693478/32742136-21218494-c8b1-11e7-89dd-5b2a20273896.png)

Could these two missing rows be causing this?

**Comment by JediKev** [comment]
YES. Those are the fields for the State and Description of the Ticket Statuses! I wonder why the upgrader didn't upgrade/removed those fields?

**Comment by Deewde** [comment]
The old (1.9.14) installation didn't have these rows in the `ost_form_field` table either.

**Comment by Deewde** [comment]
I've created the two missing rows and the issue is now fixed. Thank you!

**Comment by JediKev** [comment]
@Deewde Dude, awesome! I'm glad that worked for you! Cheers.
