### ISSUE TITLE
Overdue tickets , delete the SLA (1.10.1)

### ISSUE THREAD

**Issue by cervedgroup** [osTicket/osTicket#4078]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [ ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [ x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description
Ticket is modified with a SLA (eg. 4 hours) assigned
when the ticket goes to overdue, the sla is deleted
I don't' know if this is "by design", but could be very usefull to know wich sla was assigned without reading all the system internal notes in the ticket

**Comment by ntozier** [comment]
So I'm not sure what you mean since in my implementation (1.10.1) the SLA is not deleted.  It at the top of the ticket in the left hand column 6th item down.

![sla](https://user-images.githubusercontent.com/1315768/32787872-ad008c02-c925-11e7-9fc1-15f39c11302c.png)

**Comment by cervedgroup** [comment]
you apllyed the Default SLA, please can u try with a custom SLA assigned, let the ticket go in overdue and then view if the sla is still applyed ?

**Comment by JediKev** [comment]
Yes, my custom SLA plan is still there after going Overdue. Are you getting any errors?

**Comment by cervedgroup** [comment]
okay i've done more tests about that, and i found the issue , a ticket is opened at 02:00 AM , the operator set the SLA on 08:00AM at 4 hours, but osticket accept the setting, set the ticket overdue and suddently remove it because , i suppose, the due time should be 02:00AM + 4 hours 06:00AM that is before the actual time
