### ISSUE TITLE
Opening ticket with a long email (with tables) cause a cut thread (1.10.1)

### ISSUE THREAD

**Issue by cervedgroup** [osTicket/osTicket#4079]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [ ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description
An emails was sent to open a ticket, with around 10 tables, only the first 4 are on the ticket, the others the isn't on the osticket.
Checked the email in the osticket department mailbox , and is complete

Tell me where i can send u that email (or the entry in the osticket db) to replicate the issue.
thank you

**Comment by JediKev** [comment]
This is a known issue, and the "workaround" for now is to go to the db and change `body` column in the `ost_thread_entry` table from `TEXT` to `MEDIUMTEXT` or `LONGTEXT`. This should help for now until we figure out how we are going to handle this issue. Cheers.

**Comment by cervedgroup** [comment]
@JediKev thnak you , i've mod the column
