### ISSUE TITLE
Filesize of attachment (1.10.1)

### ISSUE THREAD

**Issue by cervedgroup** [osTicket/osTicket#4080]
In previous version of osticket, we can set the limit to file attach to 4mb, in this version the max is 2mb.
How can we set back the 4mb limit ?

thank you

**Comment by nicoletta-maia** [comment]
Hi @cervedgroup, in the help popup there is written that "The upper limit is controlled by PHP's upload_max_filesize setting. [PHP ini settings](http://php.net/manual/en/ini.core.php#ini.upload-max-filesize)"
Hope this can help you

**Comment by ntozier** [comment]
nicoletta is correct.

**Comment by cervedgroup** [comment]
yep thank you, the pop-up was  empty in my installation
