### ISSUE TITLE
PHP Fatal error when delete a custom field referenced from a ThreadEvent

### ISSUE THREAD

**Issue by nicoletta-maia** [osTicket/osTicket#4087]
### Prerequisites

* [X] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [X] Do you have any errors in the PHP error log, or javascript console?
* [X] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [X] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

Deleting a custom field that is referenced from a ThreadEvent cause a _PHP Fatal error_.

### Steps to Reproduce

1) Create a custom field into **Ticket Details** form.
2) Edit a ticket setting a value into your new custom field.
![osticketissueevent](https://user-images.githubusercontent.com/30795814/32963912-c789352a-cbd1-11e7-9554-3078b19108b5.jpg)

3) Delete now your custom field with "Remove all data entered for _Example field_ ?" **enabled**.
4) Come back to your ticket previously edited; ThreadEvent and the page area below aren't visible
![osticketissueevent2](https://user-images.githubusercontent.com/30795814/32963924-cd26887a-cbd1-11e7-96f3-867939895d8a.jpg)

**Expected behavior:**

I expected that the ThreadEvent no longer has reference to custom field.

**Actual behavior:**

The ThreadEvent has still a reference to deleted custom field into _data_ column so we get an error: "_Call to a member function getImpl() on null in include/class.thread.php:1950_"

### Versions

osTicket Version | v1.10.1
Web Server Software | Apache/2.4.18 (Ubuntu)
MySQL Version | 5.7.20
PHP Version | 7.0.22-0ubuntu0.16.04.1

**Comment by JediKev** [comment]
@nicoletta-maia 

Addressed with:
https://github.com/osTicket/osTicket/pull/4413

Cheers.

**Comment by nicoletta-maia** [comment]
Thanks @JediKev, I tested it in v1.10.5 and it works
