### ISSUE TITLE
Error on ticket assign

### ISSUE THREAD

**Issue by glennbogaertsbossit** [osTicket/osTicket#4089]
I have an error on assigning a ticket: GET http://osticket/scp/ajax.php/tickets/5/assign/agents?_uid=1511341977221 500 (Internal Server Error)
Osticket displays:
![image](https://user-images.githubusercontent.com/33894113/33119253-a924340e-cf6e-11e7-9159-2b51c55cf393.png)

This is my config:
![image](https://user-images.githubusercontent.com/33894113/33119280-be8c66e0-cf6e-11e7-8f5a-b973d32f5564.png)

Can anyone direct me toward a solution?

Kind regards,

Glenn

**Comment by ntozier** [comment]
Do you also get white bars like that on other things?
(user lookup on ticket open, etc) I ask because it looks like an AJAX issue.
Seeing any errors in your PHP error logs or Apache error logs?
Have you tried downgrading to PHP 5.6?

**Comment by glennbogaertsbossit** [comment]
No all other popups like a new ticket work fine. 
PHP errorlog refers to the problem:
#7 {main}
  thrown in /var/www/html/osticket/upload/include/class.forms.php on line 4338
[22-Nov-2017 09:14:13 UTC] PHP Fatal error:  Uncaught Exception: FormUtils: Unknown template style  in /var/www/html/osticket/upload/include/class.forms.$
Stack trace:
#0 /var/www/html/osticket/upload/include/staff/templates/assign.tmpl.php(48): AssignmentForm->render(Array)
#1 /var/www/html/osticket/upload/include/ajax.tickets.php(474): include('/var/www/html/o...')
#2 /var/www/html/osticket/upload/include/class.dispatcher.php(145): TicketsAjaxAPI->assign('5', 'teams')
#3 /var/www/html/osticket/upload/include/class.dispatcher.php(38): UrlMatcher->dispatch('5/assign/teams', Array)
#4 /var/www/html/osticket/upload/include/class.dispatcher.php(120): Dispatcher->resolve('5/assign/teams', Array)
#5 /var/www/html/osticket/upload/include/class.dispatcher.php(38): UrlMatcher->dispatch('/tickets/5/assi...', NULL)
#6 /var/www/html/osticket/upload/scp/ajax.php(262): Dispatcher->resolve('/tickets/5/assi...')
#7 {main}
  thrown in /var/www/html/osticket/upload/include/class.forms.php on line 4338
[22-Nov-2017 09:18:46 UTC] PHP Fatal error:  Uncaught Exception: FormUtils: Unknown template style  in /var/www/html/osticket/upload/include/class.forms.$
Stack trace:
#0 /var/www/html/osticket/upload/include/staff/templates/assign.tmpl.php(48): AssignmentForm->render(Array)
#1 /var/www/html/osticket/upload/include/ajax.tickets.php(474): include('/var/www/html/o...')
#2 /var/www/html/osticket/upload/include/class.dispatcher.php(145): TicketsAjaxAPI->assign('5', 'agents')
#3 /var/www/html/osticket/upload/include/class.dispatcher.php(38): UrlMatcher->dispatch('5/assign/agents', Array)
#4 /var/www/html/osticket/upload/include/class.dispatcher.php(120): Dispatcher->resolve('5/assign/agents', Array)
#5 /var/www/html/osticket/upload/include/class.dispatcher.php(38): UrlMatcher->dispatch('/tickets/5/assi...', NULL)
#6 /var/www/html/osticket/upload/scp/ajax.php(262): Dispatcher->resolve('/tickets/5/assi...')
#7 {main}
  thrown in /var/www/html/osticket/upload/include/class.forms.php on line 4338

**Comment by mfelber** [comment]
I have seen this before: http://osticket.com/forum/discussion/91058/ajax-form-assign-ticket-doesnt-work-because-of-failed-template-info

**Comment by glennbogaertsbossit** [comment]
Hi mfelber, the "dirty" fix indeed resolved my problem.

**Comment by bguebert** [comment]
A cleaner fix was posted here:
https://github.com/VelkyVenik/osTicket/commit/9a46fd9439fe8f69369174e9af8e39e3e154b183
You probably changed your class.forms.php render function definitions and didn't update their calls in assign.tmpl.php and transfer.tmpl.php.
