### ISSUE TITLE
APIKey is misleading on documentation.

### ISSUE THREAD

**Issue by pedro-lb** [osTicket/osTicket#4091]
Hello,

While using the osTicket API to create new tickets, by any means (JSON, XML, Email), the API Key does not work as said in the documentation, **because it should be lowercase**.

According to the documentation:

> Example:
> X-API-Key: BA00B76BAA30F62E1940B46CC1C3C73C

While it should be:

> Example:
> x-api-key: BA00B76BAA30F62E1940B46CC1C3C73C

A small problem that can waste some time.

Best regards,
Pedro Bini.

**Comment by ntozier** [comment]
I can't fix this with out a link to where you see the typo.

**Comment by pedro-lb** [comment]
Sorry, my bad.

Here's the link:
https://github.com/osTicket/osTicket/blob/develop/setup/doc/api.md

**Comment by ntozier** [comment]
change made and pull request created. 
Thanks for letting us know!

**Comment by pedro-lb** [comment]
Thank you very much.
