### ISSUE TITLE
Alerts not being send automatically

### ISSUE THREAD

**Issue by nicolascanal** [osTicket/osTicket#4095]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
Yes i can
* [ ] Do you have any errors in the PHP error log, or javascript console?
No
* [ ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
Yes, didn´t found my error.
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?
No.

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

The problem happends when a ticket SLA is meet. At this stage the notification via mail should occur but only happens when the user log in the app.

[Description of the bug or feature]

### Steps to Reproduce

1. Open a ticket
2. Wait for SLA to happen
3. If no mail is send, log on to the application to se the behaviour.

**Expected behavior:** [What you expected to happen]
The idea is when the SLA is meet a mail goes off automatically to the user involved independant if the user is logged in or not.

**Actual behavior:** [What actually happened]
The mail goes off after user log on is done.

### Versions
My version is osTicket (v1.9.12)
Admin panel -> Dashboard -> Information which also additionally gives you information about you server.

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

My OS version is windows 10 x64 and is was tested on every normally used web browser such us firefox, chrome and edge.

Thanks

**Comment by sperows** [comment]
This does sound like you need to fix your cron settings :) I bet you have enabled Fetch on auto-cron under Emails > Settings. 

The info note tells you:
> Enables periodic email fetching using an internal task manager triggered by Agents' activity. 
> 
> Please note that emails will not be fetched if no one is logged in to Staff Control Panel. External task scheduler is highly recommended for predictable fetch intervals.

The info note also suggests to take a look here:
http://osticket.com/wiki/POP3/IMAP_Setting_Guide

If this is not the case, then you will need to dig in deep to find the problem.
