### ISSUE TITLE
File attach not working with Firefox 57

### ISSUE THREAD

**Issue by jabrugger** [osTicket/osTicket#4096]
Log in as a representative. Try to attach a file to a ticket by selecting it. File selection window never opens up.
Use Firefox 57 to reproduce the issue.

**Comment by ntozier** [comment]
Version of osTicket?

If you are only having this problem with Firefox and not other browsers then i think it's pretty clear that this is a Firefox issue.

**Comment by perryk** [comment]
I've tried as both agents and users and am able to use Firefox 57.0 (on Linux) bring up the file selection and successfully save file attachments. Are you able to confirm your trouble on other installations and/or other operating systems ?

**Comment by JediKev** [comment]
@jabrugger I tried with Firefox 57.0 (Mac) and got the same result as @perryk. I would like to know the same as @perryk:
>Are you able to confirm your trouble on other installations and/or other operating systems ?

**Comment by jabrugger** [comment]
It seems to be a hard-to-reproduce issue. Most times work fine, some doesn't. I´ll try to find a sequence of steps to reproduce and I´ll inform it.
