### ISSUE TITLE
400 error from ajax

### ISSUE THREAD

**Issue by denisgolius** [osTicket/osTicket#4099]
**GET https://ip:13142/scp/ajax.php/help/tips/settings.system 400 (Bad Request)**
(anonymous) @ VM1480:1
send @ jquery-1.11.2.min.js?9ae093d:4
ajax @ jquery-1.11.2.min.js?9ae093d:4
(anonymous) @ tips.js?9ae093d:66
(anonymous) @ tips.js?9ae093d:151
dispatch @ jquery-1.11.2.min.js?9ae093d:3
r.handle @ jquery-1.11.2.min.js?9ae093d:3
**VM1480:1 GET https://ip:13142/scp/ajax.php/help/tips/settings.ticket 400 (Bad Request)**
(anonymous) @ VM1480:1
send @ jquery-1.11.2.min.js?9ae093d:4
ajax @ jquery-1.11.2.min.js?9ae093d:4
(anonymous) @ tips.js?9ae093d:66
(anonymous) @ tips.js?9ae093d:151
dispatch @ jquery-1.11.2.min.js?9ae093d:3
r.handle @ jquery-1.11.2.min.js?9ae093d:3
**VM1480:1 GET https://ip:13142/scp/ajax.php/form/field-config/21 400 (Bad Request)**

Also I get:
[27/Nov/2017:13:55:13 +0100] "GET /scp/ajax.php/form/field-config/21 HTTP/1.1" 400 17 "https://ip
![default](https://user-images.githubusercontent.com/5650611/33267850-a34e3566-d383-11e7-8657-01c6f5123a83.png)
:13142/scp/settings.php?t=tickets" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53
7.36 (KHTML, like Gecko) Ubuntu Chromium/62.0.3202.94 Chrome/62.0.3202.94 Safari/537.36"

**Comment by ntozier** [comment]
nginx is not a support webserver for osTicket.

Please either switch to Apache or read the many other nginx threads here on githug to see if you can resolve your issue.  Also are you running anything like SELinux, mod_security, etc?

**Comment by denisgolius** [comment]
It's clear nginx 1.12 and php 7.0
Also I can say - BIG FACEPALM! 

Osticket support only apache2... guys, WTF? And there is no one firewall or mod_security... double facepalm..

**Comment by sperows** [comment]
The only /facepalm is your attitude when asking for help... :)

**Comment by ntozier** [comment]
Technically Apache and IIS.  I guess that you didn't read the system require,ents before you installed?  They are a little outdated on the page but are at: http://osticket.com/faq

 You will need to read through the other nginx threads here to resolve your configuration issue to make things work.

**Comment by denisgolius** [comment]
Maybe you will try to make normal nginx supporting?

**Comment by ntozier** [comment]
I doubt it will be for 1.11.  Maybe when 2.0 is released.

**Comment by denisgolius** [comment]
So add this into your site and say that it works fine on Ubuntu Server 16.04, nginx 1.12 and php7.0!
`server {
	listen server_ip:443 ssl;
        server_name osticket;

        root   /var/www/osticket/upload;
        index index.php;

        log_not_found off;
        access_log /var/log/nginx/osticket.access.log;
        error_log /var/log/nginx/osticket.error.log error;

        ssl_certificate /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_prefer_server_ciphers on;
        ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';
        ssl_session_timeout 1d;
        ssl_session_cache shared:SSL:360m;
        #ssl_stapling on;
        ssl_stapling_verify on;
        add_header Strict-Transport-Security "max-age=31536000; includeSubdomains; preload";

        client_max_body_size 2000M;
	add_header X-Frame-Options DENY;
	add_header X-Content-Type-Options nosniff;
	add_header cache-control    "public, max-age=1800";
        client_body_buffer_size 100M;
        client_header_buffer_size 10M;
        large_client_header_buffers 2 10M;

        client_body_timeout 12;
        client_header_timeout 12;
        keepalive_timeout 70;
        send_timeout 10;

        gzip             on;
        gzip_comp_level  2;
        gzip_min_length  1000;
        gzip_proxied     expired no-cache no-store private auth;
        gzip_types       text/plain application/x-javascript text/xml text/css application/xml;

        set $path_info "";

        location ~ /include {
            deny all;
            return 403;
        }

        if ($request_uri ~ "^/api(/[^\?]+)") {
        set $path_info $1;
	}

        location ~ ^/api/(?:tickets|tasks).*$ {
            try_files $uri $uri/ /api/http.php?$query_string;
        }

        if ($request_uri ~ "^/scp/.*\.php(/[^\?]+)") {
            set $path_info $1;
        }

        location ~ ^/scp/ajax.php/.*$ {
            try_files $uri $uri/ /scp/ajax.php?$query_string;
        }

        location / {
            try_files $uri $uri/ index.php;
        }

        location ~ \.php$ {
            fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
            include fastcgi_params;
            fastcgi_pass unix:/run/php/php7.0-fpm.sock;
            fastcgi_param  PATH_INFO    $path_info;
        }
}`

![default](https://user-images.githubusercontent.com/5650611/33274345-712a84f8-d398-11e7-8dd5-3530220b2c1a.png)
