### ISSUE TITLE
Advanced search with custom choices field not working

### ISSUE THREAD

**Issue by ramalhoruben** [osTicket/osTicket#4100]
### Description

Advanced search with a field of type "choices" doesn't seem to work. After inspecting the 'ost_ticket__cdata' I shed some light over the reasons why it doesn't work, my custom field values are all taking the value 0 and advanced search seems to use this table to filter results. 
The interesting part is that if I make changes to the form, example change 'variable' name, the materialized view gets recreated, the field values become correct and everything works as intended.

I think the problem is in the materialized view. This limitations also prevents custom choice fields from being displayed in queue fields, as the table needs to be in line with the ticket form field to be of any use. 

No php or mysql errors whatsoever.

PS: I am using the choices field as intended, represented as "key: value" pairs. This choices field has over 200 different options, if that might be the issue. But.. similar behaviors were reported on smaller lists.

Related:
#https://github.com/osTicket/osTicket/issues/2625
#https://github.com/osTicket/osTicket/issues/4071
#https://github.com/osTicket/osTicket/pull/357/commits/1bc059453365ee6d91b49d888d4b102b7d5c556b

### Versions

osTicket | v1.10.1 (9ae093d)
MySQL | 5.6.38
PHP | 5.5.38

OS: Ubuntu 14.04.5 LTS (GNU/Linux 4.4.0-31-generic x86_64)
Browser: Mozilla Firefox 57

**Comment by ntozier** [comment]
duplicate bug report to https://github.com/osTicket/osTicket/issues/4071. Please close.

**Comment by ramalhoruben** [comment]
The underlying issue is the same. Still I hope a second opinion (my confirmation) over the same problem could be useful for you guys. Closed.

**Comment by JediKev** [comment]
@ramalhoruben Also, your problem is that you need to have keys for _all_ options listed in the Choices configuration. Once you have keys for all the options and you create a new ticket with a Choice selected you should be able to see the result in the Advanced Search. 👍 
There is a pull request in the issue that @ntozier referenced that should "force" keys for your Choice fields.

**Comment by ramalhoruben** [comment]
Yes, I tried List as a work around and it works much better. They also have their own limitations regarding huge lists tough.. Thanks

**Comment by JediKev** [comment]
I have created this pull request that should solve this issue: #4124

**Note:** If you're using a Choices field, every choice HAS to have a key associated with them (mentioned in the helptext).
<img width="320" alt="screen shot 2017-12-14 at 13 38 51" src="https://user-images.githubusercontent.com/11823401/34011146-ab99f346-e0d4-11e7-8337-c9cb1ee40e71.png">

**Comment by Lurch440** [comment]
Regression in 1.11
I get the "Each choice requires a key ..." in red.

My list in the form of:
1:value
2:yada yada ..

**Comment by dustinparkerfb** [comment]
Enter One Key at a time and save after each one.

**Comment by JediKev** [comment]
@Lurch440 @dustinparkerfb 

Have you tried this:
#4847 

Cheers.

**Comment by dustinparkerfb** [comment]
No but good to know. Thanks!

**Comment by TrueType** [comment]
try here #5376 ?
