### ISSUE TITLE
Custom list, manual sorting unusable for large lists 

### ISSUE THREAD

**Issue by ramalhoruben** [osTicket/osTicket#4102]
Custom lists provide the option to customize the order in which items are listed, but pagination breaks this feature badly as a item can't be moved between different pages. At least it isn't clear in the UI on how to do it.

Still regarding custom lists. I created a custom queue where a custom list field is displayed next to each ticket, is it possible with the (key, value) representation to implement (efficiently or not) sorting by list values (alphabetical order). 
If I just sort by the field, tickets are sorted according to the list keys instead of their corresponding values (expected behavior), is there any known workaround for the problem?
Thanks

# Versions

osTicket | v1.10.1 (9ae093d)
MySQL | 5.6.38
PHP | 5.5.38

OS: Ubuntu 14.04.5 LTS (GNU/Linux 4.4.0-31-generic x86_64)
Browser: Mozilla Firefox 57

**Comment by ntozier** [comment]
I have no idea what you are trying to say.  Why would pagination break the function of a form drop down list?  What do you mean by breaks a drop down?  The drop down doesn't work?

"I created a custom queue"  Are you saying that you installed the Custom Queues [unreleased alpha] feature due out in 1.11?  And created a queue based on a List?

**Comment by ramalhoruben** [comment]
It doesn't break the functionality of a dropdown list, that's not what i mean. The custom list has three modes of ordering, sorted alphabetically, sorted alphabetically (reverse) and manually ordering. What I am trying to explain is that the third mode is broken since the drag and drop functionality to customize the ordering isn't viable to large lists since pagination is in place.

Regarding the second question I mean that I made modifications to the default queue and added a new field with a custom list value contents. Everything works as intended and things are displayed correctly but sorting based on the field doesn't work as intended due to the underlying representation of list items (key, value) pairs. 

Cheers

**Comment by JediKev** [comment]
@ramalhoruben 

How many records does it show on one page and what is your `Maximum Page Size` setting in **Agent Panel > Profile > Preferences**?

For the filtering to work, you'll have to either modify the code yourself to make it work like you want or wait until the Custom Columns/Custom Queues feature is released (v1.11).

Cheers.

**Comment by ramalhoruben** [comment]
The max page size is set to 25.

Yep, that's exactly what I was expecting, thank you.

**Comment by JediKev** [comment]
So how many records is it showing per page in the List?

**Comment by ramalhoruben** [comment]
Sorry I missed that question, also 25.

**Comment by JediKev** [comment]
Ahhhh, so try bumping that setting up in your profile and see if you see all the records!

**Comment by ramalhoruben** [comment]
I already tried it, the max page size is about 100 and I have over 200 records. :-/
I think a toggle in this menu to disable pagination would be the most appropriate solution, until then I can live with a alphabetically sorted list. :-)

Thanks

**Comment by JediKev** [comment]
In the meantime you could modify the `Maximum Page Size` setting to include `250` or something. Cheers. 👍
