### ISSUE TITLE
Locking feature don't seems to work correctly ..

### ISSUE THREAD

**Issue by cervedgroup** [osTicket/osTicket#4105]
Seems that the "locking ticket" feature, works only in the "on modify" setting.
If i set the locking parameter "on viewing" and  If an operator is viewing a ticket and another operator open the ticket, the warning that someone else is working on the ticket is not shown. The warning is only shown if the other operator starts to write somethning in the ticket (but not if the operator edit the ticket to change for example the priority or the category)

1.10.1 version .

**Comment by JediKev** [comment]
I have a pull request you should check out: #3924

It addresses the part about requiring locks for ticket actions but idk if it helps with the "on viewing" issue.

**Comment by cervedgroup** [comment]
i'll test it in next days and let you know, thank you!!

**Comment by cervedgroup** [comment]
GREAT ! now the lock works correctly :+1:  @JediKev

**Comment by cervedgroup** [comment]
last question .. how/which files to edit ,  to change the  avatar in this message ?
![image](https://user-images.githubusercontent.com/6535381/33709070-85c0307e-db3c-11e7-8965-5573ded017c5.png)

**Comment by perryk** [comment]
I have wondered this myself so I have taken a look, it isn't all that straightforward.

First, there is a file: [scp/images/oscar-avatars.png](  https://github.com/osTicket/osTicket/blob/55dc25ace736baeaf224ee608cfabc0218022036/scp/images/oscar-avatars.png) <-click to see the image

This contains not 1 but 10 avatars.

Then there are some lines of CSS in this file: [scp/css/scp.css](https://github.com/osTicket/osTicket/blob/55dc25ace736baeaf224ee608cfabc0218022036/scp/css/scp.css#L2660-L2674)  <- click to see the specific lines

Which give a definition to each part of the image, it is interesting that only 2 out of the 10 avatars are defined currently.

Finally, there is a function in this file: [scp/scp.php](https://github.com/osTicket/osTicket/blob/770174cffaba74fae171bd3ec859491f42fdd4e1/scp/js/scp.js#L790)  <- click to see the specific line

Where the avatar can be set.

I wonder what the original author named each avatar. "oscar-girl" is an easy one to guess. Maybe someone could make an "oscar-santa" ?

I don't mind it too much, a little bit of levity just for agents. Maybe it is something you can change to see if any agents notice, mess with them a bit :)

**Comment by cervedgroup** [comment]
i've modified all the avatars in  the .png , but oscar is still there ...

**Comment by JediKev** [comment]
YOU NO LIKE MY 8 BIT OSCAR?!?!? JK, it's fine lol 😉
