### ISSUE TITLE
Feature Request: Agent edit button while on view mode. 

### ISSUE THREAD

**Issue by luiizfenix** [osTicket/osTicket#4107]
Is it possible to add a button next to the ticket field for agents so if they need to edit only one field, it can be done faster?

something like configuration mode for admins but instead to configure the field, it will edit its content.

**Comment by luiizfenix** [comment]
so far a few months it seems no one is interested in this feature, not even to reply, a workaround or a "it is not possible at the moment because...." 

osticket is kinda abandoned or it seems to be like that.

**Comment by ntozier** [comment]
Just because no one else seems to be interested in your feature request does not in fact correlate to the project being abandoned.  It does however indicate a lack of interest in your feature request.

**Comment by ntozier** [comment]
Well closing the feature request guarantees that no one will look at it. (cept me of course...)

**Comment by luiizfenix** [comment]
Something similar(inline edit) was achieved with the newest release, so
that's why I closed it.

Best regards
