### ISSUE TITLE
Ticket Filter Email Arrays

### ISSUE THREAD

**Issue by thejordanaustin** [osTicket/osTicket#4108]
### Description

I found a couple forum posts about this (86698, 89917), so I know this isn't specific to me, but can't find any bug reports about it.

If you create a ticket filter, and set it to "Send to Email" the arrays for ticket information are not working. You cannot include the ticket number, ticket name, ticket message, etc in the email. They just come through as "array" on the email.

### Steps to Reproduce

1. Create a Ticket Filter. For example, emergency tickets, send to email.
2. Set some arrays in the email. For example, From: %{ticket.name} Department: %{ticket.dept.name} Agent: %{ticket.assigned} Subject: %{ticket.subject}
3. Create a ticket, triggering the filter. The email sent will not include a ticket number, name, department, subject, or anything. It will just say "array" in each of those variables.

### Versions
v1.10 (901e5ea)
CentOS. Verified with latest Chrome.

**Comment by JediKev** [comment]
@thejordanaustin The reason this is happening is because filters are ran right before tickets are created, therefore filters will not have access to ticket variables yet. Cheers.

**Comment by heyheyhey173** [comment]
Just wanted to add on that I am able to pass the %{ticket.subject} variable successfully when used in the subject line of the Send to Email filter action.  However, when using %{message} in the body, it just sends '%{message}'.  Other variables produce the Array message as described above.

I'm just wondering why it works for the subject line, but not in the body.  And if there is any way to get the body of the incoming email to pass through.  Thanks.

**Comment by rowright** [comment]
If you check the ost_filter_action table, what gets stored appears to drop out the .message from the variable when it's saved.

I changed the message object in the stored JSON in the database to be `"message":"%{ticket.message}"` and then ran a test ticket and it worked and showed the message body. I think when it's being parsed and stored by osTicket when editing or creating the filter rule, it's deleting this.

**Comment by brunomilet** [comment]
I would like to reopen this issue. OK? Or should I create another one?

I tried to send an email by filter like this:

- Ticket number: %{ticket.number} (It works)
- Ticket date and time: %{ticket.create_date}  (It works)
- User: %{ticket.user.name} (It works)
- Email: %{ticket.user.email}  (It works)
- Subject: %{ticket.subject} (It **doesn't** work)
- Message: %{message} (It **doesn't** work)


Thanks!
