### ISSUE TITLE
Quick search seems to output inconsistent results (1.10.1)

### ISSUE THREAD

**Issue by cervedgroup** [osTicket/osTicket#4110]
some results is correct , but many others have not the searched string (also have not the searched string in name or surname) ...
![image](https://user-images.githubusercontent.com/6535381/33710240-3bf73fc4-db40-11e7-80da-649d0f8907cb.png)

**Comment by JediKev** [comment]
I cannot replicate this at all...maybe it's due to LDAP again?

**Comment by cervedgroup** [comment]
https://github.com/osTicket/osTicket/issues/4053 was solved with a patch , no ldap problem ..

**Comment by cervedgroup** [comment]
any ideas about that ? that problem is very annoying... thank you

**Comment by cervedgroup** [comment]
sorry to bother you again , any ideas to investigate this problem ?
thank you

**Comment by JediKev** [comment]
Are those Users LDAP Users or were they created by LDAP?

**Comment by cervedgroup** [comment]
no, those users are created automatically by the system, getting the info from the emails of the users that created the tickets

**Comment by JediKev** [comment]
Wait....are you searching on the Open Ticket Queue or in the User Directory?

**Comment by cervedgroup** [comment]
in the open ticket queue

**Comment by JediKev** [comment]
@cervedgroup 

I figured this out. Since you are searching on the Ticket Queue for 'giorgio', it will search for all Users with the name or email containing 'giorgio' **AND** it will search the ticket threads for 'giorgio'. The Users that do not have 'giorgio' in their name or email but is still showing up in the typeahead means that they have tickets that contain 'giorgio'. It will even tell you how many tickets contain the keyword you searched for:
![screen shot 2018-02-15 at 10 11 01](https://user-images.githubusercontent.com/11823401/36267083-aebc4c50-1238-11e8-978d-570e9479fa74.png)

**Comment by cervedgroup** [comment]
ok assuming that this is correct, but if i select concetto.xxxxxx (1) i receive in output 27 ticket (not 1) ...

**Comment by JediKev** [comment]
Exactly, because they actually have 27 Tickets not just 1. The typeahead just shows you how many of their tickets contain the keyword you search for. Makes sense?

**Comment by cervedgroup** [comment]
yes, but wich one of the 27 tickets have "giorgio" in the thread ? should i open 27 tickets to found the correct one ?

**Comment by JediKev** [comment]
Precisely.

When you click on the User in the typeahead it will show you all the tickets related to the User, not just the ticket with the keyword.

**Comment by cervedgroup** [comment]
do you think that is a correct result of search ? is this the expected behavior ? 
i think that the quick search should be limited to sendername/email and subject of the ticket , OR search everywhere but show only the ticket with the keyword...

**Comment by JediKev** [comment]
It's working like expected.

**Comment by cervedgroup** [comment]
can you please tell me, which file(s) has the code that search in the whole thread ? 
i'll like to mod them in order to search only in the user / subject fields . The quicksearch results is also very slow in this moment.
thank you!

**Comment by cervedgroup** [comment]
can someone please tell me, which file(s) has the code that search in the whole ticket thread ?
i need to mod it in order to search only in sender / Subject fields. 
Thank you!
