### ISSUE TITLE
Why is there no default website icon (favicon.ico)

### ISSUE THREAD

**Issue by netbrothers-tr** [osTicket/osTicket#4112]
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

There is no default website icon.

### Steps to Reproduce

1. Install and configure osTicket.
2. Load the start page or really any osTicket page in the browser.

**Expected behavior:**

I'd expect a default icon to appear as the page icon in tabs and in the browser's bookmarks. It's true that you could customize it, but being able to visually recognize the website quickly via the icon in your tabs and in your bookmarks should be, IMHO, an out-of-the-box feature.

**Actual behavior:**

There is no icon.

### Versions

v1.10 (901e5ea) and higher running on Ubuntu Server 16.04.3 LTS using latest Firefox and Chrome browsers on different client platforms.

## Remarks

I will do the necessary work (Icon, PR) if this issue finds support in the community. :heart:

**Comment by perryk** [comment]
I have a branch on my fork which does this: https://github.com/perryk/osTicket/tree/mod-add-favicon

To use this you should be able to do either one of the following:
```
git fetch https://github.com/perryk/osTicket.git mod-add-favicon:mod-add-favicon
git merge mod-add-favicon
```
or
```
git pull https://github.com/perryk/osTicket.git mod-add-favicon
```
It was one of the first things I knocked together and it seems there are multiple ways to add favicons to webpages. I wasn't sure if the approach was sound so I didn't add this in as a PR to the main branch. Certainly it all works ok for me however.

If anyone else wants to test and confirm it is ok I'll make it a PR to the main OsTicket github repo.

The icon is this one, and it is set for both the user and agent pages:

![osticket_favicon](https://user-images.githubusercontent.com/806269/33765879-be9f7938-dc66-11e7-801b-e51fe79ebf93.png)

**Comment by JediKev** [comment]
@netbrothers-tr Here you go mate: https://github.com/osTicket/osTicket/pull/4117

Cheers.

**Comment by perryk** [comment]
oh nice! Thanks @JediKev, I'll change to using this.

**Comment by JediKev** [comment]
@perryk You don't have to if you don't want to mate, you've got your own 😉

**Comment by perryk** [comment]
All good, I'm happy to include this with my other PRs applied and keep an eye on anything that creates merge conflicts etc. No biggie, cheers :)

**Comment by netbrothers-tr** [comment]
THANK YOU @perryk AND @JediKev !!!
