### ISSUE TITLE
User Organization 2nd page above bug

### ISSUE THREAD

**Issue by johnkalangha** [osTicket/osTicket#4116]
OSTICKET ver. 1.10.1

We have a user organization with lots of members (probably 35 members and above). In AGENT panel under organization, the list of user in the certain organization correctly displays the first page, but if you click the other page below ex. page 2 and above the display redirects to the all user page 2 instead of the 2nd page of the users with that specific organization.

PHP Version: 5.6
WEBSERVER: Microsoft IIS version 10

**Comment by sperows** [comment]
You mean this? https://github.com/osTicket/osTicket/pull/4042

**Comment by johnkalangha** [comment]
thanks for this
