### ISSUE TITLE
Empty user name/email for posted info

### ISSUE THREAD

**Issue by asdil12** [osTicket/osTicket#4120]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [ ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

![image](https://user-images.githubusercontent.com/725608/33937798-256a0010-e005-11e7-8c45-7438a09c3307.png)

### Steps to Reproduce

1. Create ticket via Web or via E-Mail without sending the Name (`User Name <user@email.de>`)
2. The ticket looks like in the image above

**Expected behavior:** The Name should be taken from the user-db or as fallback the email should be shown

**Actual behavior:** The ticket looks like in the image above: no user name/email is shown

### Versions

v1.10.1 (9ae093d)

**Comment by ntozier** [comment]
I've never experienced what you are describing.  It sounds to me like the user doesn't have a name in the database to me.

**Comment by asdil12** [comment]
At least on the screenshot it has a name - See "User:"

**Comment by JediKev** [comment]
@asdil12 How was the ticket created (API, Email Fetch, Client Portal, an Agent)? Also do you see any errors in your osTicket logs or Apache/PHP error logs?
