### ISSUE TITLE
Time Wrong - How to Change OSTicket Database Time Zone????? 

### ISSUE THREAD

**Issue by fileadda** [osTicket/osTicket#4121]
Hi...

**Tickets Time wrong.** 
under **Database Information Usage Options--> Timezone = IST (Interpreted as Asia/Jerusalem)...**
this caused **+3:30 hours forwarded from Current Timezone (Asia/Kolkata)(+)5:30)**

how to change this?  

anybody guide me? 

currently my **MySql server showing timezone is +5:30, means (IST Asia/Kolkata)**

**but in osticket not reflect?**

**i want to set my current time_zone  Asia/Kolkata (+5:30)
How?**

![screen shot 2017-12-13 at 7 00 12 pm](https://user-images.githubusercontent.com/20986701/33942924-8445bcea-e03d-11e7-824a-ffbe5799f1ef.png)

**Comment by JediKev** [comment]
You'll need to set it explicitly via MySQL: `mysql> SET @@global.time_zone, @@session.time_zone = 'Asia/Kolkata';`

If that command does not work you'll have to populate MySQL's timezone tables and then run the command again. Here is a helpful link: https://dev.mysql.com/doc/refman/5.7/en/time-zone-support.html

You may close this as well as this is not an osTicket issue rather a server/database issue. Cheers.

**Comment by vikramsra** [comment]
Doing this also does not solve the problem
