### ISSUE TITLE
API method to get tickets, need some help

### ISSUE THREAD

**Issue by koichirose** [osTicket/osTicket#4122]
I'm in the process of developing an API method to get tickets (and then I'll work on API methods to get a single ticket, reply, etc). See: https://github.com/osTicket/osTicket/issues/3973#issuecomment-351436081

This is my first time working on osTicket's code, so I'd like some guidance...

For now, I'm getting tickets by user email address only, like this in `api.tickets.php`, TicketApiController:
```php
    function get($format) {
        if(!($key=$this->requireApiKey()))
            return $this->exerr(401, __('API key not authorized'));

        $request = $this->getRequest($format);
        if (array_key_exists('email', $request)) {
            $tickets = Ticket::getByEmail($request['email']);
            $this->response(200, json_encode($tickets));
        }
        else {
            $this->response(400, json_encode(array('error' => 'missing parameters')));
        }
    }
```

And in `class.ticket.php`:
```php
    static function getByEmail($email) {
        $query = static::objects()
            ->filter(array('user__emails__address' => $email));

        return $query->values()->all();
    }
```

I tried using `Ticket::lookup(['email' => $email]);` but I get a query error.

Now, this works, but I'm missing some information (like the ticket subject).
Plus, I'm pretty sure that it could be done a little better, by using existing methods, but I'm finding it hard to navigate the codebase.

Can someone point me in the right direction?

**Comment by Jarvvski** [comment]
@koichirose They've mentioned already in the other issue you comment in (https://github.com/osTicket/osTicket/issues/3973) that they're working on something already, and they'll share it in good time.

Not only that, but your PR will be a tad pointless as if you look their dev work as moved internally and is no longer on here. In fact, they have nearly 300 open PR's so don't expect a quick review+merge!

**Comment by koichirose** [comment]
@Jarvvski with or without a PR, I need this functionality...
Just looking for some pointers to save some time implementing it.

**Comment by frumbert** [comment]
@koichirose I've also come here looking for an api method to grab tickets - how you going with yours?

**Comment by koichirose** [comment]
This is what I have right now, in `include/api.tickets.php`
```php
    function get($format) {
        if(!($key=$this->requireApiKey())) {
            return $this->exerr(401, __('API key not authorized'));
        }

        $request = $this->getRequest($format);

        if (!array_key_exists('email', $request)) {
            $this->response(400, json_encode(array('error' => 'missing email parameter')));
            return;
        }

        TicketForm::ensureDynamicDataView();
        $query = TicketModel::objects();
        $tickets = [];
        if (array_key_exists('email', $request)) {
            $query
                ->filter(array('user__emails__address' => $request['email']));
        }

        if (array_key_exists('status', $request)) {
            $query
                ->filter(array('status__state' => $request['status']));
        }

        if (array_key_exists('deptId', $request)) {
            if (!is_array($request['deptId'])) {
                $request['deptId'] = [$request['deptId']];
            }
            $query
                ->filter(array('dept_id__in' => $request['deptId']));
        }

        $tickets = $query->values(
            'ticket_id', 'number', 'created', 'isanswered', 'source', 'status_id',
            'status__state', 'status__name', 'cdata__subject', 'dept_id',
            'dept__name', 'dept__ispublic', 'user__default_email__address', 'lastupdate'
        );

        $count_tickets = $tickets;
        $count = $count_tickets->count();

        $tickets->order_by('-created');
        $tickets->annotate(array(
            'thread_count' => SqlAggregate::COUNT('thread__entries'),
        ));

        $tickets = $tickets->all();

        $response = array(
            'total' => $count,
            'tickets' => $tickets,
        );

        $this->response(200, json_encode($response));
    }
```

You can filter by email, status, or department.
You also need to add the following to the $dispatcher in `api/http.php`
```php
url_get("^/tickets\.(?P<format>json)$", array('api.tickets.php:TicketApiController','get')),
```
