### ISSUE TITLE
[feature request] add option for https redirect 

### ISSUE THREAD

**Issue by waspinator** [osTicket/osTicket#4123]
### Description

Add an option to force HTTPS to the admin panel. This would make it easy for users to enable HTTPS without having to manually edit files.

```

if($cfg->isHttpsForced() && $_SERVER['SERVER_PORT'] != 443) {
   header("HTTP/1.1 301 Moved Permanently");
   header("Location: https://".$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI']);
   exit();
}
```

include/class.config.php
```
var $defaults = array(
...
'force_https' =>     false,
...
)

function isHttpsForced() {
     return $this->get('force_https');
}
```

**Comment by Nick-C** [comment]
Another option would be to use the HSTS header and modern browsers should auto redirect and restrict comms to HTTPS only then (defining both would cover both modern and legacy browsers though).

**Comment by JediKev** [comment]
@waspinator @Nick-C 

This should do it:
- https://github.com/osTicket/osTicket/pull/5270

Cheers.
