### ISSUE TITLE
PHP 7.2 Fatal error

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket#4125]
`PHP Fatal error:  Declaration of CachedResultSet::count() must be compatible with BaseList::count($mode = COUNT_NORMAL) in C:\inetpub\osTicket\DPR\include\class.orm.php on line 1662`

Server Information
--
osTicket Version | v1.10.1 (9ae093d) —  Up to date
Web Server Software | Microsoft-IIS/8.5
MySQL Version | 5.7.20
PHP Version | 7.2

**Comment by susieq8** [comment]
Hi,

I don't know if I need to open a new thread, but I get this error too:

PHP Fatal error: Declaration of CachedResultSet::count() must be compatible with BaseList::count($mode = COUNT_NORMAL) in C:\inetpub\osTicket\DPR\include\class.orm.php on line 1662

The only steps done were to upgrade from osTicket 1.9.12 to 1.11.0-rc1.

It works under Php 7.0 but gives the above error message under Php 7.2

Thank you!
