### ISSUE TITLE
PHP 7.1 Warnings

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket#4126]
`PHP Warning:  Declaration of AssignmentForm::render($options) should be compatible with Form::render($staff = true, $title = false, $options = Array) in C:\inetpub\osTicket\DPR\include\class.forms.php on line 4587`
`PHP Warning:  Declaration of TransferForm::render($options) should be compatible with Form::render($staff = true, $title = false, $options = Array) in C:\inetpub\osTicket\DPR\include\class.forms.php on line 4707`

Server Information
--
osTicket Version | v1.10.1 (9ae093d) —  Up to date
Web Server Software | Microsoft-IIS/8.5
MySQL Version | 5.7.20
PHP Version | 7.1.12

**Comment by Wikibear** [comment]
Get this warning also with PHP Version => 7.0.22-0ubuntu0.16.04.1

**Comment by JediKev** [comment]
This is exactly the same as: https://github.com/osTicket/osTicket/issues/3033
