### ISSUE TITLE
Typo in SQL Command

### ISSUE THREAD

**Issue by AisoPlee** [osTicket/osTicket#4128]
### Description

There seems to be a typo in a stored SQL Command. Here it is:

```
[CREATE TABLE IF NOT EXISTS `ost_ticket__cdata` (PRIMARY KEY
(ticket_id)) DEFAULT CHARSET=utf8 AS SELECT entry.`object_id` as `ticket_id`,  FROM ost_form_entry entry
JOIN ost_form_entry_values ans ON ans.entry_id = entry.id
JOIN ost_form_field field ON field.id=ans.field_id
WHERE entry.object_type='T' GROUP BY entry.object_id]

You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'FROM ost_form_entry entry
JOIN ost_form_entry_values ans ON ans.entr' at line 2
```

The Comma in line 2 (stright before FROM) is wrong - you need to delete it :)
### Steps to Reproduce

1. Install new osTicket instance (use MariaDB10)
2. Create a Ticket as guest user including some cdata (Comments)
3. The error is thrown.

**Expected behavior:** [What you expected to happen]
The Table should be created

**Actual behavior:** [What actually happened]
The error is thrown

### Versions
osTicket: 1.10.1
MariaDB 10
Apache 2.3.29
PHP 5.6.31
Server Operating System: Synology DSM 6.1
OsTicket Source: From official Repository (if the error isn't in the source, i'll need to contact Package maintainer)

**Comment by JediKev** [comment]
Not getting this error at all with fresh install...wonder what happened to your install?

**Comment by Micke1101** [comment]
Is this a completely clean install or have you modified any forms?
I agree that osTicket should take into account if there is no dynamic fields, but it's strange that you would have no dynamic fields on a clean install.

**Comment by AisoPlee** [comment]
Yes - i used a custom Form i created my selfe, as you ask now. How ever - this still should not happen right?
I reproduced the same issue on a CentOS issue using the real PHP files directly from github. I also used MySQL 5.7 this thime to exclude issue with Database provider.

So again what i do:
1) Install osTicket 1.10.1
2) Login as Admin 
3) Create a Custom Form with a "Long Answer Field"
4) Create a Custom Category and use my Form.
5) Log out
6) Fill a Bug as unregistered user in the Category i just created, My custom Form is beeing displayed. i fill something in the "Long answer field"
7) Submit the ticket
8) The Webpage brakes
9) i get a mail with the SQL Command above, telling me this isnt Valid SQL code.

**Comment by Micke1101** [comment]
Ok i just tested the steps that you suggested on my test machine and I'm not getting the error that you're suggesting.

I'll setup a centos machine and see if i can replicate it there with a completely clean install.

![image](https://user-images.githubusercontent.com/22049466/35042698-f930f6f2-fb89-11e7-9b20-8ec2a2e2a6b7.png)

![image](https://user-images.githubusercontent.com/22049466/35042719-061cc06c-fb8a-11e7-9c16-c7eeb8c5607d.png)

![image](https://user-images.githubusercontent.com/22049466/35042791-3bc22bb2-fb8a-11e7-97ea-a3b7a08ae28f.png)

![image](https://user-images.githubusercontent.com/22049466/35042781-34d8a7d6-fb8a-11e7-8dd2-82ad944d6481.png)

![image](https://user-images.githubusercontent.com/22049466/35042830-641c2ec8-fb8a-11e7-9eb5-28af024fc451.png)

**Comment by JediKev** [comment]
@AisoPlee Do you have a variable set for the field? If not, add one and re-try this.
