### ISSUE TITLE
LDAP user login Access deined

### ISSUE THREAD

**Issue by jianfzhu** [osTicket/osTicket#4129]
### Description

I setup LDAP plugin, for agents users, it's working, can login with AD user. but for user, i add it and select authorization is LDAP. it can't login , display access denied.  if i change to local authorization, user can set password and login normally.  where is wrong?

### Steps to Reproduce
in ost_user_account table.  backend = ldap.client

### Versions

Osticket 1.10.1
php 5.6.32
mariadb: 10.1

**Comment by ntozier** [comment]
Please see: https://github.com/osTicket/osTicket/pull/3456
There is also a second fix in the comments for user search.

**Comment by jianfzhu** [comment]
@ntozier  i change it follow your advise.   #3456 , osTicket/osTicket-plugins#128 . still not work.

**Comment by ntozier** [comment]
And the second fix in the comments?
This issue is still a duplicate and should be closed.  Please close it and continue the discussion in the original report.
