### ISSUE TITLE
Email validation error when subdomains.

### ISSUE THREAD

**Issue by sistemasad** [osTicket/osTicket#4130]
### Prerequisites

* [- ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ No] Do you have any errors in the PHP error log, or javascript console?
* [ Yes] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [Yes ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description
When using email addresses like  something@sub.domain.com, the input mail validation fails with the message "enter a valid email address".

### Steps to Reproduce
Try to fill any mail address format field with something with the format aaaaaa@bb.ccccccc.ddd

**Expected behavior:** [What you expected to happen]
It's a valid email address, it should be accepted.
**Actual behavior:** [What actually happened]
"enter a valid email address" message is shown.
This issue is browser independent.

### Versions

osTicket Version | v1.10.1 (9ae093d)
Web Server Software
Apache/2.2.15 (CentOS)
MySQL Version | 5.1.73
PHP Version | 5.6.31

**Comment by mixrat** [comment]
Same for me on v1.9.14

**Comment by CyberVerme** [comment]
Same for me on v1.10.1 (9ae093d)

cannot create agent with email useragent@subdomain.domain.com

**Comment by ntozier** [comment]
Have you three tried shutting off email validation?

Admin -> Manage -> Forms -> Contact Information.
Click on config button to the right of Email Address.
Change Validator to none.
