### ISSUE TITLE
best email settings to avoid outgoing messages going to spam

### ISSUE THREAD

**Issue by nigelfish** [osTicket/osTicket#4135]
Hi,
We have had many reports of our emails from our osticket ending up in spam. Does anyone have a similar issue? Can anyone advise the best settings to minimise our emails going to spam?

We only use 1 booking email address, it is being fetched by POP3 with a cron job, and emails are sent from osTicket with SMTP.

Below are the settings for our booking email address (booking@twofishdivers.com)

![screen shot 2018-01-15 at 4 51 40 pm](https://user-images.githubusercontent.com/35448712/34934376-3688dc04-f9d2-11e7-9d06-e23b3c425310.png)
![screen shot 2018-01-15 at 4 52 21 pm](https://user-images.githubusercontent.com/35448712/34934377-36bead8e-f9d2-11e7-8591-5c105069f789.png)
![screen shot 2018-01-15 at 4 52 35 pm](https://user-images.githubusercontent.com/35448712/34934378-36f52698-f9d2-11e7-9b7c-5a0735732b0e.png)

Our installation details are:
![screen shot 2018-01-15 at 4 49 04 pm](https://user-images.githubusercontent.com/35448712/34934108-24a247ec-f9d1-11e7-86e2-d9f9de5dc8f9.png)

**Comment by ntozier** [comment]
This does not appear to be an issue report, and probably would be best posted to the support forums.
http://osticket.com/forum

There is no specific configuration that you would do in osTicket to avoid emails ending up in spam boxes.  That would be handled by the mail server(s) and/or spam firewall(s) and/or DNS.

**Comment by JediKev** [comment]
@nigelfish Also, you should try Enabling the setting `Header Spoofing: Allow for this Email Address`.

**Comment by nigelfish** [comment]
@ntozier my bad, it was one of those that fell into a grey area - could be support but could also be an issue. Will be more careful next time.

@JediKev Thanks for the suggestion!! I have enabled this as I am sure that will not do any harm and so could only help.

**Comment by ntozier** [comment]
@nigelfish no worries! :)

**Comment by ramonfincken** [comment]
Still this is not an Osticket issue, you should talk to your SMTP host and check if DNS for email SPF and DKIM are in order.

**Comment by mehov** [comment]
> Also, you should try Enabling the setting `Header Spoofing: Allow for this Email Address`.

Hello @JediKev, can you please elaborate on how this affects spam? The help box says:

> Enable this to allow sending emails via this mail box from an address other that the one given in the Email Address setting above.
> 
> This advanced setting is generally used when sending mail from aliases of this mail box.

So I initially thought it's the other way around, and if I don't use any aliases, and have only main support e-mails, then actually better not touch this.

**Comment by JediKev** [comment]
@mehov 

I was wrong when I said that back then. It doesn’t really affect spam. As the help tip says it’s only useful for sending mail as another address than what’s listed.

Cheers.
