### ISSUE TITLE
how to send emails using Exchange Web Services (EWS) in Exchange 2010

### ISSUE THREAD

**Issue by ahmedosama80** [osTicket/osTicket#4136]
Dears
some MS exchange servers are using a high security polices which prevent using a direct connetion (POP,smtp,imap.....etc) but instead of that i uses a Exchange Web Services (EWS) for that connection,
so i need to know how to use the EWS in osTicket , there is already some PHP modules (at github) supporting EWS
thanks

**Comment by ntozier** [comment]
This is not a feature of osTicket at this time.  

You will have to utilize: POP; IMAP; or Piping (But if your running Exchange you cannot do Piping)

**Comment by geo782** [comment]
Hi,
MS exchange server should enable smtp for sending. Pop, imap is disabled for security.
1. Create a middle mail server in the intranet, that supports imap, pop3. 
2. Create a mail account in the new mail server with simular name as original mail account
3. Add original email to osticket only for sending with SMTP settings
4. Add new email account only for receiving with pop, imap settings
5. Forward emails from exchange to the new email account

George
