### ISSUE TITLE
Create ticket via fetching email from predefined domain list

### ISSUE THREAD

**Issue by host138** [osTicket/osTicket#4137]
It would be nice to put this option in the mail settings so that specify a list of domain names for which osticket can create a ticket.
Also good to have a possible choice a folder with which can fetch emails, not just from inbox folder.

**Comment by ntozier** [comment]
What are Ticket Filters?

**Comment by host138** [comment]
Yes, sorry email filters are great for this purpose, then there remains the second item

**Comment by ntozier** [comment]
Sorry i didn't notice the second question when i read it originally.
"Also good to have a possible choice a folder with which can fetch emails, not just from inbox folder."
This is not an option at this time, and I highly doubt that you will get any traction on adding this as a feature.
