### ISSUE TITLE
ROOT_PATH

### ISSUE THREAD

**Issue by c0nfus3d** [osTicket/osTicket#4139]
https://github.com/osTicket/osTicket/blob/acac370761c17f1b9d25f0ff55a31ffd36e2d8ba/bootstrap.php#L338

The line above is being run before this line below

https://github.com/osTicket/osTicket/blob/acac370761c17f1b9d25f0ff55a31ffd36e2d8ba/main.inc.php#L24

Which means `ROOT_PATH` will always be undefined if it's defined in `ost-config.php` -- which is where it says to define it.

**Comment by JediKev** [comment]
@c0nfus3d Have you tried this yet: https://github.com/osTicket/osTicket/pull/4101

**Comment by c0nfus3d** [comment]
Apparently redefining a CONSTANT is not something you should be doing.

It is not allowing `ost-config.php` to redefine `ROOT_PATH` since it was already set.

**Comment by JediKev** [comment]
It's not "re-defining" if it's not already defined. I'm almost certain you can `define()` a CONSTANT if it's not already defined. Are you running into an issue where this is triggering an error? If so please post some errors from your logs so we can look into the issue.

**Comment by JediKev** [comment]
Sorry I get it now...I thought you were saying that the line in `bootstrap.php` couldn't define it. Hmm...

**Comment by JediKev** [comment]
I believe this is how it works:
You're only supposed to define `ROOT_PATH` in the `ost-config.php` if your server can't discover the URL path of your osTicket installation ([explained here](https://github.com/osTicket/osTicket/blob/develop/include/ost-sampleconfig.php#L98-L100)). The line in the `bootstrap.php` does exactly that; it gets the directory name of your install and sets it as `ROOT_PATH`. So if this fails then `ROOT_PATH` will not be set and you should set it in `ost-config.php`. We could add a line to the `ost-config.php` to check if it's already defined to protect against re-defines though. 👍

**Comment by c0nfus3d** [comment]
Well I needed to redefine it, not because the server could not discover the URL, it's that it was discovering the wrong URL... reverse proxy case.
