### ISSUE TITLE
Fatal error:  Uncaught Error: Call to a member function getAllItems() on null

### ISSUE THREAD

**Issue by just-a-jerry** [osTicket/osTicket#4141]
### Prerequisites

* [Y ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [N ] Do you have any errors in the PHP error log, or javascript console?
* [Y ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [Y ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

[Description of the bug or feature]
Im using osTicket v 1.10 with the additions of the Time Tracking files to track Time Spent. I went into Admin Panel>Settings>Time and i checked all the boxes related to showing time on a ticket. The "Time Spent" and "Time Type" options now show on an open ticket, but when i select the dropdown menu for "Time Type", there are no options. When i inspect the dropdown element i get an error:

 Fatal error:  Uncaught Error: Call to a member function getAllItems() on null in /home/kopcosof/public_html/liftruck/webERP/osticket/include/staff/ticket-view.inc.php:764
Stack trace:
#0 /home/kopcosof/public_html/liftruck/webERP/osticket/scp/tickets.php(492): require_once()
#1 {main}
  thrown in /home/kopcosof/public_html/liftruck/webERP/osticket/include/staff/ticket-view.inc.php on line 764

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

**Comment by JediKev** [comment]
Since this is an issue with custom files, you should post this issue on the mod page itself. You will not get help here as it's not due to the core code so please Close this issue. Cheers.
