### ISSUE TITLE
Blank New Ticket and Create User Popup

### ISSUE THREAD

**Issue by Benareli** [osTicket/osTicket#4147]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
javascript no error, php log =
 tail -f php7.0-fpm.log
[31-Jan-2018 22:07:55] NOTICE: fpm is running, pid 21498
[31-Jan-2018 22:07:55] NOTICE: ready to handle connections
[31-Jan-2018 22:07:55] NOTICE: systemd monitor interval set to 10000ms
[31-Jan-2018 23:27:23] NOTICE: Terminating ...
[31-Jan-2018 23:27:23] NOTICE: exiting, bye-bye!
[31-Jan-2018 23:27:23] NOTICE: configuration file /etc/php/7.0/fpm/php-fpm.conf test is successful

[31-Jan-2018 23:27:23] NOTICE: fpm is running, pid 22213
[31-Jan-2018 23:27:23] NOTICE: ready to handle connections
[31-Jan-2018 23:27:23] NOTICE: systemd monitor interval set to 10000ms
^C

* [ ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
Yes, no solution
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?
Yes, try some solution, not work

### Description

Blank pop up in almost any menu (New Ticket, Create new User, etc)

### Steps to Reproduce

Open admin panel, create new ticket, or agent panel and create new user

**Expected behavior:**

New Ticket Pop Up Screen

**Actual behavior:**

Blank Pop up

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.

Here is the admin Panel
==========================================
osTicket Version 	v1.10-rc.3 (907ec36) — v1.10.1 is available
Web Server Software 	nginx/1.10.3
MySQL Version 		5.7.21
PHP Version 		7.0.22-0ubuntu0.16.04.1
PHP Extensions
gdlib 			Used for image manipulation and PDF printing
imap 			Used for email fetching
xml 			XML API
xml-dom 		Used for HTML email processing
json 			Improves performance creating and processing JSON
mbstring 		Highly recommended for non western european language content
phar 			Highly recommended for plugins and language packs
intl 			Highly recommended for non western european language content
fileinfo 		Used to detect file types for uploads
APCu 			Improves overall performance
Zend Opcache 		Improves overall performance
PHP Settings
cgi.fix_pathinfo 	"1" is recommended if AJAX is not working
date.timezone 		Setting default timezone is highly recommended
Database Information and Usage
Schema 			osticketdb (localhost)
Space Used 		4.67 MiB
Space for Attachments 	0.01 MiB
Timezone 		UTC 
==========================================

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

Server is
==========================================
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
==========================================

nginx/sites-enabled/osticket
==========================================
server {
  listen 80;
        server_name 188.166.178.100;

        root   /var/www/html/osticket/upload/;

        access_log  /var/log/nginx/access.log;
        error_log  /var/log/nginx/error.log;

        index index.php;
        client_max_body_size 2000M;
        client_body_buffer_size 100M;
        client_header_buffer_size 10M;
        large_client_header_buffers 2 10M;
        client_body_timeout 12;
        client_header_timeout 12;
        keepalive_timeout 15;
        send_timeout 10;
        gzip   on;
        gzip_comp_level  2;
        gzip_min_length  1000;
        gzip_proxied     expired no-cache no-store private auth;
        gzip_types       text/plain application/x-javascript text/xml text/css $

        set $path_info "";

        location ~ /include {
          deny all;
          return 403;
       }

       if ($request_uri ~ "^/api(/[^\?]+)") {
         set $path_info $1;
       }

       location ~ ^/api/(?:tickets|tasks).*$ {
        try_files $uri $uri/ /api/http.php?$query_string;
       }

       if ($request_uri ~ "^/scp/.*\.php(/[^\?]+)") {
          set $path_info $1;
       }

       location ~ ^/scp/ajax.php/.*$ {
          try_files $uri $uri/ /scp/ajax.php?$query_string;
       }

       location / {
          try_files $uri $uri/ index.php;
       }

       location ~ \.php$ {
           fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
           include        fastcgi_params;
           include snippets/fastcgi-php.conf;
           fastcgi_pass unix:/run/php/php7.0-fpm.sock;
           fastcgi_param  PATH_INFO    $path_info;

      }
}
==========================================

Browser is Firefox 57

**Comment by sperows** [comment]
Hello, most likely without upgrading to stable version of 1.10.1 (from release candidate 1.10-rc.3) nobody will look into this as you are using unfinished product at your own peril :)

**Comment by Benareli** [comment]
using version 1.10 and 1.10.1 with same problem. now try the rc3. same problem.

**Comment by perryk** [comment]
Try with Apache instead of Nginx. The rc3 release is older than 1.10.1 so stick with 1.10.1.

**Comment by ntozier** [comment]
Your problem is this:
Web Server Software nginx/1.10.3

osTicket does not support nginx.  You will need to read through the other nginx threads here on github to change your configuration to make it work, or switch to a supported webserver (Apache or IIS).  

Either way this is a duplicate error report please close it.
