### ISSUE TITLE
Office 365 Email Configuration Not Possible

### ISSUE THREAD

**Issue by consultpc** [osTicket/osTicket#4150]
### Prerequisites

MS Office 365 Email Account (Outlook)
osTicket 1.10

### Description
Users cannot setup any of the email features using an MS Office 365 account, because the system doesn't support TLS/ STARTTLS encryption protocol. The TLS 1.2 protocol has become mandatory (announced by Microsoft in December 2017 with the implementation date on March 1, 2018) as MS is phasing out support for previous protocols TLS1.0, TLS 1.1.

https://support.microsoft.com/en-us/help/4057306/preparing-for-tls-1-2-in-office-365

### Steps to Reproduce
Hostname |  outlook.office365.com
Port Number |  995
Mail Box Protocol | — Select protocol:   IMAP + SSL ; IMAP ; POP + SSL ; POP

**Expected behavior:** Normally, an POP + TLS should also exist
**Actual behavior:** There are no 'TLS' options

### MS Office 365 Settings:
POP Settings:
Server name: outlook.office365.com
Port: 995
Encryption method: TLS

IMAP Settings:
Server name: outlook.office365.com
Port: 993
Encryption method: TLS

SMTP Settings:
Server name: smtp.office365.com
Port: 587
Encryption method: STARTTLS

The encryption method and Ports cannot be changed in the O365 Account Settings.

### Versions

Server Information
--
osTicket Version | v1.10.1 (9ae093d) —  Up to date
Web Server Software | Apache
MySQL Version | 5.6.36
PHP Version | 7.1.12

gdlib | Used for image manipulation and PDF printing
imap | Used for email fetching
xml | XML API
xml-dom | Used for HTML email processing
json | Improves performance creating and processing JSON
mbstring | Highly recommended for non western european language content
phar | Highly recommended for plugins and language packs
intl | Highly recommended for non western european language content
fileinfo | Used to detect file types for uploads
APCu | Improves overall performance
Zend Opcache | Improves overall performance

Browser/ OS independent.

**Comment by Wintekso** [comment]
For a temporary work around we have found creating an email account on the server/external provider which has emails forwarded to from office 365, then create emails with the email address/password and smtp settings for outbound emails.

We found setting up a user which has access to shared mailboxes the easiest/highest score with emails.

an example:

Inbound email (Local):

email: tickets@in.domain.com
username:tickets@in.domain.com
password: email password
IMAP/POP: enabled
SMTP: disabled
 
outbound email (Office 365):

email: shared mailbox email 
username: office 365 user email
password: office 365 password

IMAP/POP: disabled
SMTP: enabled

Hope this helps!
