### ISSUE TITLE
See all tickets in search results, regardless of access not providing results for Agents

### ISSUE THREAD

**Issue by ewinter777** [osTicket/osTicket#4154]
Os ticket V1.10 
See all tickets in search results, regardless of access not showing results for agents. 
If I am logged in as administrator that sees everything I can search for it. If I log in as agent Color Lab you can see it produces no results

![screen shot 2018-02-09 at 8 38 25 am](https://user-images.githubusercontent.com/36306362/36038905-d6b11a32-0d75-11e8-9a10-9c06b0a0eda9.png)
![screen shot 2018-02-09 at 8 43 16 am](https://user-images.githubusercontent.com/36306362/36038906-d6cc2a52-0d75-11e8-9a31-5087626f1c5a.png)
![screen shot 2018-02-09 at 8 44 13 am](https://user-images.githubusercontent.com/36306362/36038907-d6e4096a-0d75-11e8-9154-59fa62f13419.png)
![screen shot 2018-02-09 at 8 43 23 am](https://user-images.githubusercontent.com/36306362/36038910-d70441a8-0d75-11e8-9fb3-c4173ee90cba.png)
![screen shot 2018-02-09 at 8 43 39 am](https://user-images.githubusercontent.com/36306362/36038911-d71dde10-0d75-11e8-9104-d51165f0b51c.png)

**Comment by ntozier** [comment]
your images show a bunch of searching... but you never actually show to us that the ticket number in the two of the images (725955) actually exists.  You do show us that the ticket 778145 exists.  So it looks to me like you are searching for oranges, and showing us that you have apples.
