### ISSUE TITLE
Osticket 1.10.1 multiselect fields always empty on user / ticket creation

### ISSUE THREAD

**Issue by aandrade1234** [osTicket/osTicket#4156]
### Prerequisites

* [YES] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [NO] Do you have any errors in the PHP error log, or javascript console?
* [YES] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [YES] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

I made a fresh osticket install on a new database. It worked very well but select fields with multiple selection option doesn't work. As workaround I have to create an user or ticket, save it and then fill it the multiselect fields. Otherwise it will get blank values. The same occurs with API ticket creation. The multiselect fields are always blank.

Here my enviroment

![capturar](https://user-images.githubusercontent.com/2529546/36075718-edd11116-0f39-11e8-938e-ea0763e8b128.PNG)

### Steps to Reproduce

1. Setup a form field as select and mark as multiselect
2. Create a ticket or user filled the multiselect fields
3. After saving or creating the ticket or user by API check the record and the field will be empty

**Comment by ntozier** [comment]
nginx is not a supported webserver by osTicket.  Please read all the other nginx threads here on github to see what you need to change in your nginx configs to make it work or switch to Apache.

**Comment by aandrade1234** [comment]
Hi @ntozier I made all recomended changes on nginx configuration. Bellow my nginx configuration.

`
server {
        listen                  80;
        server_name             crm.xxxx;
        keepalive_timeout       70;
        root                    /var/www/osticket-1.10.1;
        set                     $path_info "";
        client_max_body_size    20M;

        location ~ /include {
            deny all;
            return 403;
        }

        if ($request_uri ~ "^/api(/[^\?]+)") {
            set $path_info $1;
        }

        location ~ ^/api/(?:tickets|tasks).*$ {
            try_files $uri $uri/ /api/http.php?$query_string;
        }

        if ($request_uri ~ "^/scp/.*\.php(/[^\?]+)") {
            set $path_info $1;
        }

        if ($request_uri ~ "^/.*\.php(/[^\?]+)") {
            set $path_info $1;
        }
        location ~ ^/scp/ajax.php/.*$ {
            try_files $uri $uri/ /scp/ajax.php?$query_string;
        }

        location ~ ^/ajax.php/.*$ {
            try_files $uri $uri/ /ajax.php?$query_string;
        }

        location / {
            try_files $uri $uri/ index.php;
        }

        location ~ .php$ {
                fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
                include        fastcgi_params;
                fastcgi_param  PATH_INFO        $path_info;
                fastcgi_pass   unix:/var/run/php-fpm/php-fpm.sock;
        }
}
`

**Comment by ntozier** [comment]
Did that fix your issue?  I dont use nginx and osTicket doesn't support it so I'm not real sure what all that means.

**Comment by aandrade1234** [comment]
Hi @ntozier  I just installed Apache and I get the same behavior.

![capturar](https://user-images.githubusercontent.com/2529546/36112576-4b287386-1011-11e8-8525-ab472d0d682b.PNG)

**Comment by ntozier** [comment]
screen shots?
PHP errors?

**Comment by aandrade1234** [comment]
@ntozier  No Browser message at console and no error message at server logs.
