### ISSUE TITLE
Is ban reason & created_by deprecated?

### ISSUE THREAD

**Issue by esamo** [osTicket/osTicket#4157]
Hello.

Another thing Staff is complaining about is that in previous version of osTicket there was an input field for reason while created a ban. Now I cannot see this 'reason' field. Is there an easy workaround to bring it back and display it on the ban list as well?

Same about information who have created the ban entry.

So far I've enabled access to the ban list for every user that has ban management privilege.

Regards & respect.

**Comment by JediKev** [comment]
@ntozier I wish I could 🙄
