### ISSUE TITLE
Unable to log in. Check SMTP settings.

### ISSUE THREAD

**Issue by ajiprasetyo** [osTicket/osTicket#4158]
I have an issue when i try to configure SMTP with gmail always show error.
I have done try solve the issue with http://osticket.com/wiki/Email_settings#POP3.2FIMAP_Polling but still not working.

1. Error log : "Failed to connect to tls://smtp.gmail.com:587 [SMTP: Failed to connect socket: stream_socket_client(): unable to connect to tls://smtp.gmail.com:587 (Unknown error) (code: -1, response: )]"
2. Apache : Apache 2.4.18
2. PHP Version 7.0.8
3. MySql : Version 10.1.13
4. OSticket : v1.10.1

Anybody can help ?

**Comment by ntozier** [comment]
OS?
openssl extension enabled in PHP?  (Apache service restarted after php.ini edit?)
checked your firewall?

**Comment by ajiprasetyo** [comment]
I'm running in localhost, OS Windows 10, it's working when change ssl://smtp.gmail.com with smtp.gmail.com, or i should run on the server with ssl ?

**Comment by ajiprasetyo** [comment]
Finally i can solve my issue with run on the server, but when tried send email to another user show error
![capture](https://user-images.githubusercontent.com/16343123/36132728-6f3753f6-10ab-11e8-931a-79e02b2be1a6.PNG)

**Comment by ajiprasetyo** [comment]
[SOLVED] 
1. OS : Ubuntu
2. Enable openssl extension
3. Check "yes" Authentication Required

**Comment by ntozier** [comment]
Great, I'm glad to hear that. Can you close this issue/bug report please.
