### ISSUE TITLE
Fail to manage end user/customer logins 

### ISSUE THREAD

**Issue by tejastank** [osTicket/osTicket#4159]
### Description
1. unable to register new user as customer, it just ask password and singup done for new user. So not working 
![sdesk](https://user-images.githubusercontent.com/311413/36094762-84970f5c-1015-11e8-8005-dd56b3576cc2.png)

2. in admin panel/ agent panel unable to create user, becuase complete form comes blank.
![osticket staff control panel](https://user-images.githubusercontent.com/311413/36094706-4f0ad076-1015-11e8-84ea-f8d9039acf7e.png)

[Description of the bug or feature]
https://www.youtube.com/watch?v=oMOWZOyBGwI
Exact same issue face

### Steps to Reproduce
Video steps for issue.
https://www.youtube.com/watch?v=oMOWZOyBGwI

**Comment by ntozier** [comment]
environment details?

Admin panel -> Manage -> Forms -> Built In form: Contact Information.
Check the fields and make sure that they are enabled by:
click on the config button to the right of the "Type" drop down for each one.
Click on Settings.
