### ISSUE TITLE
Creating a ticket with status "Closed" will set team_id to "0"

### ISSUE THREAD

**Issue by dwergman25** [osTicket/osTicket#4163]
### Prerequisites

* [YES ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [NO] Do you have any errors in the PHP error log, or javascript console?
* [YES] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [YES] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

When creating a new ticket with status "closed", the team_id will be set to 0 instead of the original team_id that's put into the "create a new ticket" form. This causes problems for us when a customer responds to a ticket and the ticket reopends with team_id 0 (unnasigned). 

The problem will not occur when you create a ticket with the status "Open" and after the ticket creation you change the status to "Closed". 

### Steps to Reproduce
Open a new ticket and assign a team and choose status "Closed".
![image](https://user-images.githubusercontent.com/36265880/36152499-9000f50e-10cb-11e8-8187-48f3cc733f8e.png)

**Expected behavior:**  
In ost_team i can see that the expected team_id would be "48" for this team.
![image](https://user-images.githubusercontent.com/36265880/36153148-9c49dbbc-10cd-11e8-856c-9b265b9edd80.png)

**Actual behavior:**
However in ost_ticket i can see that the team_id is set to "0".
![image](https://user-images.githubusercontent.com/36265880/36153304-1e7842ea-10ce-11e8-8f7f-33b69082c1a1.png)

### Versions
Windows Server 2012 R2
osTicket v1.10
MySQL 5.7.19
PHP version 7.1.7
IIS Manager 8.5

**Comment by mwhitneysdsu** [comment]
This is probably caused by the following code:

https://github.com/osTicket/osTicket/blob/c4669d777d88e6b2b0e8f0c42377ac9a85aec6dd/include/class.ticket.php#L3445

`        // Only do assignment if the ticket is in an open state
        if ($ticket->isOpen()) {
            // Assign ticket to staff or team (new ticket by staff)
            if ($vars['assignId']) {`

**Comment by dwergman25** [comment]
Thanks, 

We tried some changes in there and we got it working. But with this solution when the ticket closes, it immediately sets the status to "open" again..
