### ISSUE TITLE
Square ???? @@@ weird Char When Ticket Created From Replying Email

### ISSUE THREAD

**Issue by tomzquad** [osTicket/osTicket#4165]
Hi All,

Can you help me with this issue.
When Ticket Created From Replying Email (email has table), the ticket always shown weird char like square, question mark, @, etc. (see attachment).

Please help me.

Server Information
--
osTicket Version | v1.10.1 (9ae093d) —  Up to date
Web Server Software | Apache/2.4.6 (CentOS) mod_fcgid/2.3.9 PHP/5.6.32
MySQL Version | 5.5.56
PHP Version | 5.6.32

![screenshot_4](https://user-images.githubusercontent.com/32896238/36187883-e25f7f28-117a-11e8-874c-1fc9b2f42a8d.png)

**Comment by ntozier** [comment]
It looks more to me like someone has attached a JFIF file as an attachment, or inline, and your seeing the raw file instead of the email.  Can you post the raw email with headers so that we can try importing it?

**Comment by protich** [comment]
@ntozier is indeed correct. The image is an inline image on a long body - that got stored as an attachment. 

We have a fix already - will make a pull request for it.

**Comment by tomzquad** [comment]
Hi @ntozier 

Is this what you mean ?

Received: from SG2PR01MB0669.apcprd01.prod.exchangelabs.com (2603:1096:3::31)
 by HK2PR0101MB1124.apcprd01.prod.exchangelabs.com with HTTPS via
 SG2PR0601CA0021.APCPRD06.PROD.OUTLOOK.COM; Thu, 15 Feb 2018 02:13:59 +0000
Authentication-Results: binus.edu; dkim=none (message not signed)
 header.d=none;binus.edu; dmarc=none action=none header.from=binus.edu;
Received: from SG2PR01MB0688.apcprd01.prod.exchangelabs.com (10.169.51.146) by
 SG2PR01MB0669.apcprd01.prod.exchangelabs.com (10.169.51.139) with Microsoft
 SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P256) id 15.20.506.20; Thu, 15
 Feb 2018 02:13:58 +0000
Received: from SG2PR01MB0688.apcprd01.prod.exchangelabs.com
 ([fe80::283a:c27:face:57d1]) by SG2PR01MB0688.apcprd01.prod.exchangelabs.com
 ([fe80::283a:c27:face:57d1%14]) with mapi id 15.20.0506.016; Thu, 15 Feb 2018
 02:13:57 +0000
Content-Type: application/ms-tnef; name="winmail.dat"
Content-Transfer-Encoding: binary
From: Riyn Winesdyo Winarko <riyn.winarko@binus.edu>
To: Thomas Marsetyo G.S. <thomas.marsetyo@binus.edu>
Subject: FW: Data Change - Insert Manual Registrasi 3+1 1720
Thread-Topic: Data Change - Insert Manual Registrasi 3+1 1720
Thread-Index: AdOlOFnJzrOMTQXQTiyzPlIyX5Q5AQAyjU8g
Date: Thu, 15 Feb 2018 02:13:57 +0000
Message-ID: <SG2PR01MB068882EBE3F91858C7B7BE2286F40@SG2PR01MB0688.apcprd01.prod.exchangelabs.com>
Accept-Language: en-US
Content-Language: en-US
X-MS-Has-Attach: yes
X-MS-Exchange-Organization-SCL: -1
X-MS-TNEF-Correlator: <SG2PR01MB068882EBE3F91858C7B7BE2286F40@SG2PR01MB0688.apcprd01.prod.exchangelabs.com>
MIME-Version: 1.0
X-MS-Exchange-Organization-MessageDirectionality: Originating
X-MS-Exchange-Organization-AuthSource: SG2PR01MB0688.apcprd01.prod.exchangelabs.com
X-MS-Exchange-Organization-AuthAs: Internal
X-MS-Exchange-Organization-AuthMechanism: 04
X-Originating-IP: [110.136.43.61]
X-MS-Exchange-Organization-Network-Message-Id: 04d3c8b2-de8a-4ac8-0f73-08d57419c523
X-MS-PublicTrafficType: Email
X-Microsoft-Exchange-Diagnostics: 1;SG2PR01MB0688;35:8NEjTZI1CTrjWg3O/TsAvR3Cp5KJxtzpsn51FOeYuVlh0ML6k6i8vkuVobknYY+zfoh80orpgamgRtK2vVMViw==;20:L/sc2iMUxGhGm+xNwARsjoMe3+Pg/oHi3PMXx3ijsucpD0p0CIfKGlVV0cqmgn+bwehNs/tF7mpcRijrBtFve5eO72QKspEVO9VctAkNh6iPGtGf9/ttwUqoS1wnLu+qvzyk3fS9MGHyzgqjhprSSk3veQI+QFZswdIoyGiZ8tnT8ZUTRUHtwc4hRjBhJlrA7W6zZQTIQ+/QwjKY5tPDGrFmsxCqCvyC+tCI0VH7MrZetJvYrfW5gVVbdWJWVS4OSb6kYc/0PdI1Flntlb4bHMJZADsJO5MMPUh/q/wbDAJTqlKmbsvKFSFA5ga/2ukhYBoIyEwvR7Z9Yov3bXhObRVMpASmuzel3q0sishZfVb8AWl51fe79lz7rMTWrBPyaZtZjRSaZZNMUItyVnyR9VKCPvJdpaU5n3XZMmXL+JzLZfVml26ybWCgLrtKelLFQojC0IuXOdApKdrLS6QOR0CVQ77p7ulQrOJ98Usv4K9ePKGypcTWtxTHZE8APQUw
X-MS-Exchange-Antispam-SRFA-Diagnostics: SSOS;SSOR;
X-MS-Exchange-Organization-AVStamp-Service: 1.0
Return-Path: riyn.winarko@binus.edu
X-MS-Office365-Filtering-Correlation-Id: 04d3c8b2-de8a-4ac8-0f73-08d57419c523
X-Microsoft-Antispam: UriScan:;BCL:0;PCL:0;RULEID:(7020095)(4652020)(5600026)(4604075)(3008032)(2017052603307)(7153060)(49563074)(7193020);SRVR:SG2PR01MB0669;
X-Microsoft-Exchange-Diagnostics: 1;SG2PR01MB0669;3:MebJzIR0trYn/nIw0BlLCCAMydZAyPGCgicAgftmJxyNjK0RBJ9RMuJ6HvqDJMUNo3FGVJQcgF+8CYxpSIIGElllYJLHrsjiOgFpsBUSOH7axhi85iiSJr/RDxyTDSphq60bqwRdYUoi7rizbgIxZkSyc7T74Go0/syMFHtB8VOztjQ2mop5jC2AJLu0Z+cqYo4d9dYYuEsfqO8HkRpb55UlEr/9hf0QN9Ysx0LScnSbAmQZ/4MO4nn5onU+/eT3;25:Zh+O0BHWbsSvrRy3yL+my9JIw1LMNH6ZWGK7mXutAIUXsj9RMKpDH9PJIdw7VjJ3mmPHgz/+kW7hWzlPnZQatOiywisPu12yCUoI5TfjXTjwJcfUjanu5EgRqRmJaUxz0N+ma4BQSIrAOsg3QqGhLedn00EAU8iTpzsk+uDPBY66VVjiZp9bFnMxVUe1W7b44rIxy9Pt0iBnnKabsrVhHDWG0d6BSpbd5MPEMZwBCRrJKh5foCGuIILCXYJfCrCIXnh9/I3wv6ygHXwM9fTGItW9F1AiT+wzvTJ5flxzjVFGUZ8GXSUW33ciFUx2WmvHOVnyU7WVL3lGX2ZBZBMcFg==;31:SaRHuGoDL2VKD0VFPvyYl2DxmgUJKLwf4n08KvRocXZWk40sWhhzkMu72xuA7zNfDJGgwbCW/vsuWpBWqzFo/tD8lfURrX+5d3e/WcnctHd818kStr/+4qf8CwvyE+rcUuAcHY3nDkjRB3bpVO6YWl5ReZ/KbNMMbyjurwGMeD89exhqM0JUodEZBDbEhkcNDl3atAyRHdOyYOvZFIG4Ex5mLbUrsyos0oUWTvi6DBY=
X-MS-TrafficTypeDiagnostic: SG2PR01MB0669:
X-Exchange-Antispam-Report-Test: UriScan:(28532068793085)(43178223235956)(21748063052155);
X-Exchange-Antispam-Report-CFA-Test: BCL:0;PCL:0;RULEID:(102415395)(9101524173)(2401047)(8121501046)(3002001)(10201501046)(3231101)(944501161)(93006095)(93001095)(201708071742011);SRVR:SG2PR01MB0669;BCL:0;PCL:0;RULEID:;SRVR:SG2PR01MB0669;
X-Microsoft-Exchange-Diagnostics: 1;SG2PR01MB0669;4:FbF9ELNg0wYc6JzYhUYz/MFAb21mVtPac5Hfceo7DwQgHGwhpV1XG9IC+YL0iPV+p95BrTkF7q8GC4Fq8THtYcm+fPpuKQWMSn499+U4TIoCZARUJ95CU5wW0FlhiA8Hvbg6BTzLctSRoj2nSLZJkWYUN5+262awBnqeikcnQnIOnFJ9eiGsAzI3ZBz23WW1ERERaoQOkMyX2NL812gHtYKGyoBbQMi1F84TsqFtmaQ2iYMYst/TKsBolckT/ThL/9VKHKZ0qw3/Et8qg5dto09I5PflWraWSxUDyBa4bjSVtXKRrg9ZZytZnr0GsNpBVihFtYtqFD3Cbnky8GGmg8YXR37w7sphHqgimgblYiNBYxCu9BYMZ2UcV7cSEDQv;23:4UL1jaboSEh6I6FjTAoi0GoLP1fws1mhUlbHXSw2QIsRJvaqWrOoIgNiySVVbt1QHERQPaNcdEutxn4rw9If01HDU5On0Zk2nRdB7YzIWmdXPTeNsrEPIzOVvXWNYHQuGOVlG6Lj0XCNIldeVh3RodxvHkyPXdxX1OLI0CqDZqw=
X-Forefront-Antispam-Report: SFV:SKI;SFS:;DIR:INB;SFP:;SCL:-1;SRVR:SG2PR01MB0669;H:SG2PR01MB0688.apcprd01.prod.exchangelabs.com;FPR:;SPF:None;LANG:id;
X-Microsoft-Exchange-Diagnostics: 1;SG2PR01MB0669;6:CHh0KG+Tz72y+FIUd7Lx1YdP+fgMiWUwnbc/aC+vq9yVmTNITjlW9TFn6A3oO5YE2t1kXh6bRHWpc0pePbEKTfTdg0VHd9zbDtkoip8zE5tTT36sRP+RQDxZlkR4S3pQXmNBnWwBMBms8EOVrBwFPn5UtLHbgHWNTSY4OoZc8hDmwq71i3SAd/4uHvtxwqJ9i/54HQmNcv2u+mOtcbkb5ch78gjqA7kEjg+/6R4xaNgxThgVwOo8/lS88b/EE/UONE48xoiM2dqzxNrwQCoRJ35RNKr1NFq3e+St40Omq/Ln/r+I11y715tWaU4WYragZei02+w2PuayRmEXVfgF81HvnrIWXKfWs3z+RDW8hsFKxk2cKIbg1J1Tjb7o8Xbqeovf8VjEyHC+G065lRla4A==;5:YRUXgo5PqPFd/b29kRtoopNpm1vkrAvshwaQuf+v0br3Nd54dX8emPrp3p33sUhj9GCThVRXClTfL5olYZ+z7M72E0JWaJFPIkEQZXvOs0dQEBwcNiltrWOFqhlNAUtVmihoChQZUhcGbDynW8kZ9fnLEnDjGvbCtTqAnCqyYds=;24:z1T6zcF5WVsNB2wSvPupnZQy2rOpLH6UazjpQNeepFmYPZhvUWINOUtIps5N5TvrHNKvyMx2DDoZ/CG4v/5ZItjdHCU+QVbWrCBJukQ5c0I=
X-MS-Exchange-ABP-GUID: f53d4609-7f57-450e-b8cf-bd66a0e4b557
SpamDiagnosticOutput: 1:0
X-Microsoft-Exchange-Diagnostics: 1;SG2PR01MB0669;7:MRl8PvvRBXWcC7sXqnqUXH6E3cVrOMwS2WDS4jELR9zPxNEJUlboskYlRNw9U5rSI1D6TweHyO146vEgCOLph94Y7QMtHz58G8aSN2m3b/inh2fJkNgDvaCCptf8BlyuRvGnmtUpD4c4KLMUcCl9MRLQX46vUCcJHhulSFXHA+c0umj5Z8rRVOF+YnhtCKiynTrmcJPas3xe7IBnKu1pKWl0xVbKkeYaFEwFaKZlqyAYyqE3XY1qphom2n/n/L8B
X-MS-Exchange-CrossTenant-OriginalArrivalTime: 15 Feb 2018 02:13:57.2425
 (UTC)
X-MS-Exchange-CrossTenant-FromEntityHeader: Hosted
X-MS-Exchange-CrossTenant-Id: 3485b963-82ba-4a6f-810f-b5cc226ff898
X-MS-Exchange-CrossTenant-Network-Message-Id: 04d3c8b2-de8a-4ac8-0f73-08d57419c523
X-MS-Exchange-Transport-CrossTenantHeadersStamped: SG2PR01MB0669
X-MS-Exchange-Transport-EndToEndLatency: 00:00:02.3717175
X-MS-Exchange-Processed-By-BccFoldering: 15.20.0485.002
X-Microsoft-Antispam-Mailbox-Delivery:
	ex:0;auth:0;dest:I;ENG:(400001000128)(400125000095)(750103)(520011016)(706028)(400001001318)(400125100095)(61617190)(400001002128)(400125200095);
X-Microsoft-Exchange-Diagnostics:
	1;HK2PR0101MB1124;9:vYPuWCZh7NXPocG5AN4FpVBX63lilgjgVWnPPsk4TzowUSJDRXf92ZrnHYQ8AqNYU+RzP/NKXgr8I8mnx2la9VeUwOcGUy2CAfQWvM8ZXgB3ZKSz/0SIGeYl62EoX8NgHeF2lV2GzICqympHiTiKBHal4aW8Uyj4YW8w4nhPWitEpAFz9AssPEnq8j6Dt2VvaHZQhoep4fi8JnFn01irVsuz1Od/pMF4F52asdCSf2igkFRvTuuHSbZUzNh6bqWJuuO4EiVkwo7MNH2IOme3rjxUPmBQUlChpxr2rCSKMeTqyvbKHGX6fKvmyPTT/14zdvo5jvoVxH15sJ6JqmkDKlPLO0hc0tKU3XBhIU8FRitOMRUL0+1awnDC1ZIGbkA/W6THlP46CKtvWnHV/ClJkKfIIHeu6d4SB1I66FCbjBz0nZu8HBh2EakIczJLRBWuh2Q782uzyRzMtuMt1fCPGFrZyVeWvQLJ8/WS/JI2+w3zJjUV6lWoDkz9KcXdQeKVo/RF7wzzvRlJt9fhzttR6D9bMnC9hqR1V2avCUwIBJ8=
X-Microsoft-Antispam-Message-Info:
	e7p3JwzXp3ZzUmMXR0Th3R5d9BSTifeDRj1itJ9zwCdl4Zdaj+HROwKDXL3MS5pNWu3V9n1+76Fpk4H0t0RXT0UKo5N+259b3xZhT7IxW8s=
X-Microsoft-Exchange-Diagnostics:
	1;HK2PR0101MB1124;27:rGytQHp6txXX/bhUrP10kB6/HX4UWBVqwTnf0gGuJClboGacKu85tnMz/6BsUZ6Yg268St8ZSngLnKBXSB+avb5c4lF/P4rE6Xy2NTK+ttE0vZmsYEz2s5TvNyl3bJ/7
