### ISSUE TITLE
SLA with Business Hours

### ISSUE THREAD

**Issue by cervedgroup** [osTicket/osTicket#4166]
It could be very usefull to have a SLA that are calculated in the business hours (for example excluding saturday/sunday and night hours).

Thank you!

**Comment by ntozier** [comment]
You might want to edit the title to include the words "Feature Request".

Although i think that this would be covered by:
https://github.com/osTicket/osTicket/issues/2131
-or-
https://github.com/osTicket/osTicket/issues/1168

**Comment by cervedgroup** [comment]
LOL yes is like a mantra .. i hope to see it before leaving this world :-)

**Comment by mlipok** [comment]
I want to SET Bussiness Hours by:

- Users
- Departments
- Teams

If I have few users with different Bussiness Hours and ticket is set to Department then Business Hours should be taken from department.
If ticket is assinged to specyfic User then Bussiness Hours should be set to User Bussiness Hours

But if user is in Vacation Mode then SLA should still running as client can't wait so long, and this is the case for manager to move some tickets internally beetwen Users in our Company.

**Comment by F3000** [comment]
That is a great feature . For its missing also

**Comment by protich** [comment]
Sorry it took forever to implement the feature - but Business Hours is now a reality - see #4984
