### ISSUE TITLE
Wrong ost_ticket__cdata table and thus some tickets are missing from 'advanced search' results

### ISSUE THREAD

**Issue by parijathakumar** [osTicket/osTicket#4169]
**In a nutshell :** _ost_ticket__cdata table's data is inconsistent with that of ost_form_entry_values table for custom fields of 'Ticket Details' form. For some tickets, the custom field values are either 0 or blank in ost_ticket__cdata table where as the same fields have values in the ost_form_entry_values table for those tickets. Such tickets are missing from the search results._

### Description

Recently I've found that advanced search based on custom fields of 'Ticket Details' form is missing some tickets in the search results. After digging through this github and osticket forums, I inferred that the search results are based on the 'ost_ticket__cdata' table which is dynamically created/deleted. Then I've found that in my case, the ost_ticket__cdata table's data is inconsistent. I mean for some tickets (which are missing from the search results) the values of the custom fields are either blank or 0 in the ost_ticket__cdata table where as the ost_form_entry_values table has correct values. That's why some tickets are missing from the search results.

Can anyone help me to resolve this ? 

### Versions

![screenshot_20180218_001433](https://user-images.githubusercontent.com/883045/36344496-36e5629c-1441-11e8-9140-6aa8fa951ae3.png)

My server setup:
I am running it in two docker containers one for mysql and another for osticket-v-10.1. The docker image is https://github.com/CampbellSoftwareSolutions/docker-osticket.

**Comment by parijathakumar** [comment]
I am closing this issue. I was able to solve my issue by dropping the ost_ticket__cdata table directly. The table is automatically created after logging in (in fact opening the 'open' tickets que). Subsequently the 'advanced search' is also working fine.

**Comment by parijathakumar** [comment]
I am reopening the issue. Because deleting the ost_ticket__cdata has solved the problem only for once. For subsequent modifications/new-entries of tickets, again the same problem persists ... the cdata table is not getting updated properly and thus some tickets are missing from the search results.

As a temporary and immediate workaround for my production server, I am going to write a bash script to automatically drop the cdata table twice or thrice a day as per our requirement.

Can someone direct me in the right way where to look for possible solutions for this issue ?

**Comment by ntozier** [comment]
You are the only person that has ever reported this issue to us, so no I dont think that I can point you in the right direction.  I have no idea why your table is not dropping and regenerating by itself... unless maybe your DB user doesn't have the proper privs to do it?

**Comment by JediKev** [comment]
Also, do you have all the necessary required stock fields that ship with the default Ticket Details template? If the Ticket Details template is missing a required stock field it will break the cdata table causing it not to be created properly. Just throwing that out there.

**Comment by swshivam** [comment]
Hi @ntozier I too am facing this issue. Upon diggin I've come across as possible cause for this as GTID compatiability. I'm using Google Cloud SQL and facing the same issue
