### ISSUE TITLE
include/class.thread.php story body as attachment

### ISSUE THREAD

**Issue by sperows** [osTicket/osTicket#4170]
Hello, I have a question regarding these lines in include/class.thread.php. 

I had a problem where I received a ticket and the start of the ticket thread had hundreds of lines of gibberish text. This indicated some kind of problem, so I was investigating what could have caused it and I stumbled upon this piece of code (while looking at #3757):
https://github.com/osTicket/osTicket/blob/c4669d777d88e6b2b0e8f0c42377ac9a85aec6dd/include/class.thread.php#L1410-L1420

As you can see, this part of the code is used to convert body into attachment if it exceeds 65k length, which is very specific length and I thought it was linked to column type, so if it exceeds then it stores it as attachment.
I took a look at MySQL field sizes in the MySQL [documentation](https://dev.mysql.com/doc/refman/5.7/en/string-type-overview.html) 
- TINYTEXT: 255 (2 8−1) bytes
- **TEXT: 65,535 (216−1) bytes = 64 KiB**
- MEDIUMTEXT: 16,777,215 (224−1) bytes = 16 MiB
- LONGTEXT: 4,294,967,295 (232−1) bytes =  4 GiB

**So the question is:**
Shouldn't mb_strlen($body) be set to **16000000** from **65000**, because %_thread_entry.body type is **MEDIUMTEXT** , not **TEXT**?

Sorry for the odd question :) However, it _did_ solve my issues with storing long emails with excel charts and png pictures (or it could have been this PR #3244 that did the trick).

P.S. This might be related: #4165

**Comment by JediKev** [comment]
@sperows

It wasn’t the pull that fixed it, it was bumping the column to `MEDIUMTEXT` that did it. We’ve seen this issue pop up a lot more recently and have been playing with the idea of possibly chunking the thread body like we do attachments.

Note:
This is just an idea we have right now, nothing more.

Thanks for the issue report. Cheers.

**Comment by sperows** [comment]
@ JediKev,

Yes, you are correct, it due to MEDIUMTEXT, for some reason I was looking at most recent backup, which already included my fix, sorry for the silly mistake. I checked vanilla DB and indeed it has TEXT.

I will close this issue as it is not an issue really, it is known limitation and fix might be incoming in future anyway, as you have a plan :)
