### ISSUE TITLE
How to fetch existing emails using osTicket

### ISSUE THREAD

**Issue by ergoderaja** [osTicket/osTicket#4171]
I am using osTicket v1.10.1 with php 7.
Need to fetch existing email from gmail (IMAP).
Thanks for the help in advance

**Comment by JediKev** [comment]
Mark them as Unread and make sure they are within the fetch limit. Cheers.

**Comment by ntozier** [comment]
This does not appear to be a bug/issue report.  Please close this.

Also read:
http://osticket.com/wiki/Email_settings
and
http://osticket.com/wiki/POP3/IMAP_Setting_Guide

**Comment by ergoderaja** [comment]
Hi All,
Issue resolved as i have created a label under inbox and moved after pulled the mail.
Thanks for the help.
