### ISSUE TITLE
Username limited to 32 characters

### ISSUE THREAD

**Issue by franklupo** [osTicket/osTicket#4185]
Hi,
Why is the username limited to 32 characters?

Best regards

**Comment by ntozier** [comment]
ThisISaReallyLongUsernameRight

Who uses usernames that long?  
You aren't wrong it should probably be 256 characters to mimic Windows max length (although windows also has a 20 max size for backwards compatibility with nt4).

I would guess that it has something to do with email rfc.
https://stackoverflow.com/questions/386294/what-is-the-maximum-length-of-a-valid-email-address

**Comment by franklupo** [comment]
Hi
the usernames we use are e-mails that instead of at the time we put the point.

**Comment by ntozier** [comment]
Well then I guess you know what the problem is.  You're trying to use the field in a way that it wasn't intended.  The email field is intended for email addresses.

**Comment by franklupo** [comment]
Ok for unique usename the my idea is:
email pippo@pippo.it
username pippo.pippo.it

Best regards

**Comment by plenaerts** [comment]
We use auth-passthru for SSO with our central authentication platform. Our identifiers are UUID's. For now I've altered table ost_agent in our deploys.

`ALTER TABLE ost_staff MODIFY username VARCHAR(64);
`
