### ISSUE TITLE
How translate Tickets activity board

### ISSUE THREAD

**Issue by DonCep** [osTicket/osTicket#4189]
Hi, everyone

How can I translate Tickets activity words. I can't find it on phar file.
Attach photo and marked where.

Thanks for help.
![fiksavimas3](https://user-images.githubusercontent.com/19191111/37022232-ffb673be-212a-11e8-92df-11b56eb05894.PNG)

**Comment by ntozier** [comment]
The translation project has not been completed. The Dashboard was not translated.  Thus it isn't in the language packs (.phar ).  The Dashboard was scheduled for a revamp but I'm unsure where it is in the scheme of things.

**Comment by DonCep** [comment]
Ok, thanks for answer. 
But if I want translate, I need to change in many places, for example in DB ?

**Comment by ntozier** [comment]
most of the translation is in the code.

**Comment by mwhitneysdsu** [comment]
I think the question of where to change them might be the reason they haven't been translated, yet. [getPlotData()](https://github.com/osTicket/osTicket/blob/c4669d777d88e6b2b0e8f0c42377ac9a85aec6dd/include/class.report.php#L78) pulls them from the database if they're in use and [$.drawPlots()](https://github.com/osTicket/osTicket/blob/c4669d777d88e6b2b0e8f0c42377ac9a85aec6dd/scp/js/dashboard.inc.js#L2) outputs them in the graph.

There might be an easy way to do it, but in the short time I've looked at this code, and without doing some testing, I don't see it.

**Comment by DonCep** [comment]
hmm, I almost made it, I change data Enum value on ost_thread_event table, "state" column, and change in class.report.php file. And everything translated ok, but when creating new ticket it not apear in dasboard. In database ost_thread_event table state column get blank value.
