### ISSUE TITLE
Feature Request - ticket advanced search options

### ISSUE THREAD

**Issue by deon42** [osTicket/osTicket#4193]
It would be beneficial to add additional options under the advanced search. 

Assigned to, closed by and date range

**Comment by perryk** [comment]
Does this get you close ?

![screenshot from 2018-03-09 00-42-15](https://user-images.githubusercontent.com/806269/37156767-c6ac7a32-2332-11e8-88b8-2c41c9ba32c1.png)

When you close a ticket, you become the assignee, so perhaps you don't need the "closed by" option ?

I haven't tried it, just putting up what I think should work.

**Comment by deon42** [comment]
Yes that would work. Thank you.
