### ISSUE TITLE
Prevent expiration of PDF attached in ticket thread

### ISSUE THREAD

**Issue by iHunt101** [osTicket/osTicket#4196]
After a certain period of time, the attached PDF files is automatically delete

Can we set not to delete the attacjed PDF files or do not automatically set expiration date. SO if user need the files it will still available for theme.

**Comment by ntozier** [comment]
Huh?

I have .pdf, .png, jpg, .xls, .doc, and dozens of other attachments dating back to 2012.  Attachments do not expire and never have.

**Comment by iHunt101** [comment]
I am using the plugin [storage-fs](https://github.com/osTicket/osTicket-plugins/tree/develop/storage-fs) and when i try to access the attached file, it will give an error

**Comment by JediKev** [comment]
Then something is wrong with the file, the plugin, or your configuration. Are you getting any errors in your Apache/PHP logs?

**Comment by ntozier** [comment]
It might be helpful to know the following:
version of osTicket
environment details
error your receiving
size and type of file
permission on file
If you go to the web server and drill down to the file can you open it?

**Comment by iHunt101** [comment]
I cant pull out any PHP error, but upon checking after the ticket is getting old so far no issues have been encountered.
