### ISSUE TITLE
LDAP Plugin activated = user search fail

### ISSUE THREAD

**Issue by EnisKirgoer** [osTicket/osTicket#4198]
Hi,

I got osticket 1.10.1 and if i activate the ldap plugin i cant search available user to create a new ticket. Only when the ldap plugin ist deactivated i can search available users. is this a bug or how can i fix it?

**Comment by ntozier** [comment]
https://github.com/osTicket/osTicket/pull/3456
and the one in the comments.

**Comment by EnisKirgoer** [comment]
i remove    ->annotate(array('__relevance__' => new SqlCode(1))) but still not working

**Comment by ntozier** [comment]
"and the one in the comments."
^^^ this.
