### ISSUE TITLE
Is OsTicket now compatible with PHP 7+

### ISSUE THREAD

**Issue by EnisKirgoer** [osTicket/osTicket#4203]
Hallo, 

i just want to know is the latest stable version osticket now compatible with php 7?

Dears

**Comment by ntozier** [comment]
I run 1.10.1 under 7.0.
7.1 is not supported at this time.

**Comment by boxdude** [comment]
At he the first page of installation of osticket 1.10.1; it was able to detect the version of php installed (7.2.3) and didn't complain that it wouldn't be compatible... can't they ad an IF condition and tell the user that this version is not compatible before and not after installation.

**Comment by ntozier** [comment]
I took a quick peek under the hood and the way it is written now that's not as easy to do as you seem to think.  I understand that v2.0 will deprecate this issue also.
