### ISSUE TITLE
Roadmap 2018 and next updates

### ISSUE THREAD

**Issue by F3000** [osTicket/osTicket#4207]
When will you release the next updates ? 

What is the plan for 2018 (features)?

**Comment by JediKev** [comment]
Next updates coming VERY soon. The future plans are kinda in-house only at the moment but we will release a roadmap publicly in the future. Stay tuned!

**Comment by F3000** [comment]
Fast answer :) 

We can I exspect the update ? 
In the summer or end of year ? 

Maybe you can reveal if there might be a newer PHP version is supported etc. 

I plan to setup a new ticket system for a company

**Comment by JediKev** [comment]
By the end of next week hopefully. Yes, we plan on supporting the latest version of PHP in the near future. Have to get some things straight before then. 👍🏻

**Comment by F3000** [comment]
Nice to hear :) 

Where I can follow you to read about the release ? 
On your twitter account ?

**Comment by JediKev** [comment]
You can follow our github page for releases, check our blog at osticket.com/blog (haven’t updated it in a while but we will be posting there more often), or sign up for our forums at osticket.com/forum. Our community on the forums and on here is really amazing and helpful with anything you need.

**Comment by F3000** [comment]
Thanks for the tips . You can close it here

**Comment by JediKev** [comment]
No problem! You close it by clicking “Close and Comment” at the bottom 👍🏻
