### ISSUE TITLE
Custom form permissions

### ISSUE THREAD

**Issue by cjacksonuk** [osTicket/osTicket#4208]
### Prerequisites

* [n/a] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [no ] Do you have any errors in the PHP error log, or javascript console?
* [yes ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [yes ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

When using a custom form, and changing the permissions so that an end user cannot edit the value, the end user is still able to change the value.

.

**Comment by JediKev** [comment]
Test this and let me know: https://github.com/osTicket/osTicket/pull/3888
