### ISSUE TITLE
Ban email adresses with arabic characters

### ISSUE THREAD

**Issue by F3000** [osTicket/osTicket#4220]
At the moment i can only add a specific mail address to the ban list.

I dont find any function or filter to block email addresses with arabic characters. For us this feature can decrease al lot of work

**Comment by JediKev** [comment]
You can do this already just not in osTicket. You can go to the mailbox you're fetching from and have a rule that filters emails based on a certain email address and move them to a box/folder other than the Inbox. osTicket will only fetch Un-Read emails from the Inbox so if they go to a separate box/folder they should not be fetched.

Cheers.

**Comment by F3000** [comment]
Ok . We use exchange 2010 as a mail server. I wil speak with my colleague who better knows the Staten than i do . 

I will let this ticket open for your multilingual process :)
