### ISSUE TITLE
No Collaborators created from mail's CC

### ISSUE THREAD

**Issue by rktrevor** [osTicket/osTicket#4222]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [ ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

When Ticket is logged via email, the CC emails address are not being added as Collaborators.

### Steps to Reproduce

1. Send and email to OSTicket with CC email addresses
2. Go to newly created ticket and the Collaborators do not show as all

**Expected behavior:** [What you expected to happen]

The Collaborators to show in the Reply section so show that Collaborators have been added

**Actual behavior:** [What actually happened]

No Collaborators are added.

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.

Server Information
--
osTicket Version | v1.10.1 (9ae093d) —  Up to date
Web Server Software | Microsoft-IIS/10.0
MySQL Version | 5.7.19
PHP Version | 7.0.21

gdlib | Used for image manipulation and PDF printing
imap | Used for email fetching
xml | XML API
xml-dom | Used for HTML email processing
json | Improves performance creating and processing JSON
mbstring | Highly recommended for non western european language content
phar | Highly recommended for plugins and language packs
intl | Highly recommended for non western european language content
fileinfo | Used to detect file types for uploads
APCu | Improves overall performance
Zend Opcache | Improves overall performance

cgi.fix_pathinfo | "1" is recommended if AJAX is not working
date.timezone | Europe/Minsk

Schema | is_support (localhost:3306)
Schema Signature | 98ad7d550c26ac44340350912296e673
Space Used | 1056.20 MiB
Space for Attachments | 892.13 MiB
Timezone | South Africa Standard Time (Interpreted as Africa/Johannesburg)

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

Windows 10
Outlook 2016
Chrome Browser

**Comment by ntozier** [comment]
We have an almost identical setup (you have a newer version of IIS and MySQL).  Please submit an email that gave you this behavior with full headers for testing.

**Comment by rktrevor** [comment]
Here you go
[Ticket Header.txt](https://github.com/osTicket/osTicket/files/1882701/Ticket.Header.txt)

[Test Mail.zip](https://github.com/osTicket/osTicket/files/1882702/Test.Mail.zip)

**Comment by rktrevor** [comment]
Hi There, 

Is there any update to this, it seems to be very hit and miss with out OsTickert box as sometime is happens and sometime it does not

**Comment by ntozier** [comment]
@JediKev ping

**Comment by JediKev** [comment]
@rktrevor 

Will test this in just a moment.

Cheers.

**Comment by rktrevor** [comment]
@JediKev 

We will wait for the upgrade, Thanks for the feedback.

Kind Regards

**Comment by JediKev** [comment]
@rktrevor

CC feature has basically been done in the `1.11.x` branch.

As for the progress of 1.11.0, we should be releasing RC2 soon. Stay tuned.

Cheers.
