### ISSUE TITLE
Task template in v1.10.2

### ISSUE THREAD

**Issue by Rujinraj** [osTicket/osTicket#4223]
Hello Team,

I am new to this forum. 

Do we have task template( canned task) option in version v1.10.2

As of now i am using v.1.10.1

Regards
Raj

**Comment by ntozier** [comment]
I'm not sure what you are asking, but this does not appear to be a bug report and 1.10.2 has not been released.  If you are looking for support please post on the support forums at: http://osticket.com/forum

**Comment by JediKev** [comment]
>and 1.10.2 has not been released.

and 1.10.2 has not been _officially_ released.

It was a "soft" release under the tag `1.10.2`. We will officially release and publicly announce it within the next few weeks.

Cheers.

**Comment by Rujinraj** [comment]
Thanks for the update. Its not an issue. Its a query regarding whether "canned task" option will be included in this 1.10.2 version?

**Comment by Rujinraj** [comment]
I found task-templates.php file in one of the version, how should i include this feature in version v1.10.2

**Comment by ntozier** [comment]
Q: Its not an issue. Its a query regarding whether "canned task" option will be included in this 1.10.2 version?
A: No.  
1.10.2 will be a security update and will not include new features.
It will also not be in 1.11 which will introduce new features.
It should be included in the Task revamp which will take place after 2.0 is released.  No we do not have a release date for that.

Q: I found task-templates.php file in one of the version, how should i include this feature in version v1.10.2
A: You should probably refer to where or who ever you got that file from for support, it is not part of the official release.  You haven't really given us any information on this file other than its file name, and I dont think that anyone can help you with the information you have provided.

**Comment by Rujinraj** [comment]
closing this
