### ISSUE TITLE
Simple search does not filter staff responses

### ISSUE THREAD

**Issue by esamo** [osTicket/osTicket#4224]
Hi there.

What can I do to make the simple search filter staff responses?
Currently it will not find tickets that contain given phrase in the staff response.

So far I've only found the query responsible in the MysqlSearchBackend->find():
```
(
	SELECT 
		COALESCE(
			Z3.`object_id`, Z5.`ticket_id`, Z8.`ticket_id`
		) as `ticket_id`, 
		SUM({}) AS `relevance` 
	FROM 
		`:_search` Z1 
		LEFT JOIN `:thread_entry` Z2 ON (
			Z1.`object_type` = 'H' 
			AND Z1.`object_id` = Z2.`id`
		) 
		LEFT JOIN `:thread` Z3 ON (
			Z2.`thread_id` = Z3.`id` 
			AND Z3.`object_type` = 'T'
		) 
		LEFT JOIN `:ticket` Z5 ON (
			Z1.`object_type` = 'T' 
			AND Z1.`object_id` = Z5.`ticket_id`
		) 
		LEFT JOIN `:user` Z6 ON (
			Z6.`id` = Z1.`object_id` 
			and Z1.`object_type` = 'U'
		) 
		LEFT JOIN `:organization` Z7 ON (
			Z7.`id` = Z1.`object_id` 
			AND Z7.`id` = Z6.`org_id` 
			AND Z1.`object_type` = 'O'
		) 
		LEFT JOIN : ticket Z8 ON (Z8.`user_id` = Z6.`id`) 
	WHERE 
		{} 
	GROUP BY 
		`ticket_id`
) Z1
```

> 

Where is this in the code, screenshot: http://take.ms/MT8V5

---

System info screenshot: http://take.ms/9xRoe

**Comment by ntozier** [comment]
Most likely that exact query is not in the code.  osTicket was moving toward using an ORM interface with the database.  So a lot of the time it constructs queries on the fly and runs them.

**Comment by esamo** [comment]
Any ideas how to make the simple search go through staff responses as well?
