### ISSUE TITLE
[question] Making Users

### ISSUE THREAD

**Issue by moo1210** [osTicket/osTicket#4225]
Is there a way in PHP to make a user or using the API to do so? I wanting to do this for my help desk.

**Comment by JediKev** [comment]
No, you can only create tickets or tasks via API. For more information on the API view this link: https://docs.osticket.com/en/latest/Developer%20Guide/API%20Docs.html

You do have the option of importing users via a CSV file or a new line list by going to **Agent Panel > Users > User Directory > Import**.

You may close this issue.

Cheers.
