### ISSUE TITLE
[Feature request][1.10.2] Team statistics in dashboard

### ISSUE THREAD

**Issue by jishvi** [osTicket/osTicket#4226]
Does anyone know how do I add teams statistics in the dashboard?
(It should look like the image I have attached)

![ost](https://user-images.githubusercontent.com/10036266/38486482-d7e03cb8-3bfa-11e8-9085-080f8f3866d0.png)

**Comment by jishvi** [comment]
Hi @JediKev , I wasn't talking about the faulty dashboard. I wanted to add a new tab called "Teams" which would show the statistics of each team. Is there any way that can be accomplished?
Excited about v1.11 though. Can you confirm if customizable ticket queues (#2577) is going to be in that version?

**Comment by JediKev** [comment]
Oh, that screenshot threw me off I thought we had that already lol You’d have to look at how the other tabs are built and implement the same thing for teams.

Yes Custom Columns & Custom Queues will be included in the new version.

Cheers.

**Comment by jishvi** [comment]
Okay great! I'll close this issue now.
