### ISSUE TITLE
osTicket v1.10.1 - Unable to disable the ability to edit ticket

### ISSUE THREAD

**Issue by aswadsun** [osTicket/osTicket#4228]
I have unticked "Edit Tickets" and "Edit thread" permissions in the role. But when the agent login, he/she can still edit his/her posts. Please tell me how to disable the agent ability to edit tickets.

Thanks
Aswad

**Comment by JediKev** [comment]
@aswadsun 

I have tested this and cannot replicate what you are saying. If the Agent in question has access to more than one Department then you need to make sure they have the same permissions for all Departments.

Cheers.
