### ISSUE TITLE
Thousands of user to register

### ISSUE THREAD

**Issue by johnkalangha** [osTicket/osTicket#4231]
Good day, i just want to ask how can i easily register my 12500+ user with all same password?

anyone can help me? TIA

**Comment by ntozier** [comment]
The import feature.
Agent panel -> Users -> Import.
Guest users dont have passwords however.  They use the email and ticket#.

**Comment by ntozier** [comment]
I'm not sure but I believe that they would have to confirm their accounts for that.

It's not something I've ever worried about because we use the Authentication::LDAP/AD plugin.  So importing the accounts means that they can authenticate using that plugin.

**Comment by johnkalangha** [comment]
how to use Authentication::LDAP/AD plugin? do you have any sources can i use too? thanks in advance

**Comment by ntozier** [comment]
Go to osticket.com/download
download the plugin.
Install the plugin
Configure the plugin.
enable the plugin.

Just like any other plugin in osTicket.
