### ISSUE TITLE
osTicket: Bootstrap User, Agent and Admin View

### ISSUE THREAD

**Issue by jonahbohlmann** [osTicket/osTicket#4232]
Hi,

I want to support osTicket to make it better, faster and more user friendly. 

What about a bootstrap v4 implementation for the Three important view?

- User View
- Agent View
- Admin View

Is there any bootstrap implementation in work or planned? If not, I will add a fork and pull request the implementation.

Please let me know if you're interested in my help.

**Comment by johnkalangha** [comment]
thats nice, can you help me sir to change the design of my osticket?

**Comment by Eiskaltereistee** [comment]
Just a minute ago I created a fork and branch for the bootstrap-v4 implementation.

I will add instructions how to update (for testing) your installation with the bootstrap theme and also fill the two projects boards.

Hope you will follow my changes and would be happy if you support it!

**Comment by johnkalangha** [comment]
i will, thanks for this sir

**Comment by JediKev** [comment]
@Eiskaltereistee 

>Is there any bootstrap implementation in work or planned? If not, I will add a fork and pull request the >implementation.

We do have plans to _completely_ revamp the UI/UX of osTicket to make it more modern and wayyy more mobile friendly. I can't tell you our exact plans just yet but I can tell you that Bootstrap is _not_ what we will be using.

Cheers.

**Comment by iHunt101** [comment]
I did this @Eiskaltereistee  just have a head start and i will help you.
