### ISSUE TITLE
osTicket: PHP 7.2

### ISSUE THREAD

**Issue by jonahbohlmann** [osTicket/osTicket#4233]
Hi,

I want to support osTicket to make it better, faster and more user friendly. 

What about a php 7.2 update?

Is there any php 7.2 implementation in work or planned? If not, I will add a fork and pull request the update.

Please let me know if you're interested in my help.

**Comment by ntozier** [comment]
This does not appear to be an issue report.  I would recommend that you post questions to the forums. http://osticket.com/forums

My understanding is that v2.0 when it is released will support php7.1+.

**Comment by seeb73** [comment]
PHP 7.0 is end of life!

**Comment by JediKev** [comment]
@seeb73 

Your statement is untrue...it's marked as "Security fixes only" NOT "End of life".

Cheers.

**Comment by seeb73** [comment]
Sec fixes to 8 september 2018 saying on my system.

**Comment by JediKev** [comment]
@seeb73 

Your system is incorrect...see PHP's site:
http://php.net/supported-versions.php

Cheers.

**Comment by kclubok** [comment]
While it's true that PHP 7.0 isn't EOL yet, there's a really short runway.  It will be EOL by the end of the year, as will PHP 5.6.  

In the meantime, OSTicket's response to related questions seems to be: "We'll support it in 2.0," and "2.0 will be released when it's ready."  Furthermore, I haven't even seen a release candidate for 2.0.  This leads me to suspect that it will soon be impossible to use an officially supported version of OSTicket with an officially supported version of PHP.  

To be sure, mitigating strategies exist.  But for some organizations, this may be an untenable situation, depending on their software maintenance policies.  And I can't imagine that this won't discourage adoption by new organizations.

**Comment by JediKev** [comment]
@kclubok 

We are aiming to support PHP **7.1.x** by-or-in `1.11` stable and _should_ support PHP **7.2.x** in `1.12` or `2.0`.

There is no release candidate for `2.0` because development hasn't started on that yet.. and this is because we haven't even released `1.11` stable yet.

There will be little-to-no issues using osTicket with _an_ officially supported version of PHP after `1.11` stable... Please stay tuned.

Cheers.

**Comment by ntozier** [comment]
@kclubok it will be released when it is ready.  devs do not give release dates.

**Comment by JediKev** [comment]
@kclubok 

The recent data from PHP's site says `7.0.x` will be EOL starting `Dec 1 2018`, at which point `5.6.x` will still be supported oddly enough (until `Jan 19 2019`). No guarantees, but we _hope_ to release `1.11` stable before the end of the year.

Cheers.
