### ISSUE TITLE
osTicket Vagrant Box / Docker Container

### ISSUE THREAD

**Issue by jonahbohlmann** [osTicket/osTicket#4234]
Hi,
I want to support osTicket to make it better, faster and more user friendly.

To support and develop on a correct way, I need a development VM / Container. Is there something available? 

If not, I recommend to create at least one of the following:
- docker container
- vagrant box

I think it could be my first work to create the vagrant and maybe the docker container too. I will inform you on any changes.

Please let me know if you're interested in my work.

**Comment by Eiskaltereistee** [comment]
I've added a simple documentation page for the vagrant VMs: https://github.com/Eiskaltereistee/osTicket/wiki/Test-Environment

Also I added the boxes to the vagrant cloud.

Please not that I haven't push any box to the cloud, It's currently just a empty holder.

**Comment by perryk** [comment]
Hi, I have a Vagrant setup here which is working well for myself.

https://github.com/perryk/perryk-vagrant-osticket

**Comment by JediKev** [comment]
We plan on releasing an Ansible/Packer/Vagrant box setup one day for osTicket users.

Cheers.

**Comment by perryk** [comment]
There is another Vagrant setup here: https://github.com/clonemeagain/osticket-vagrant
