### ISSUE TITLE
Login Page -> Firefox warn Notification

### ISSUE THREAD

**Issue by F3000** [osTicket/osTicket#4238]
See this picture: 

Every time when i open i get the little notofication : Firefox preventing the site from reload.
![bildschirmfoto 2018-04-12 um 21 36 36](https://user-images.githubusercontent.com/8161283/38700030-0de70304-3e9a-11e8-80a0-06e58709960f.png)

Can i disable that ? 

OsTicket: 1.10.1
Firefox 59
OSX 10.13.3

**Comment by ntozier** [comment]
Sounds like a firefox setting to me.

**Comment by F3000** [comment]
I have the solution. Your Link is for FF Versions before 56. 

This is the correct link:
https://support.mozilla.org/de/questions/1172024#answer-1016935

Solution: 
go to `about:config` and search for `accessibility.blockautorefresh`

When it looking like that : 
![bildschirmfoto 2018-04-12 um 21 57 10](https://user-images.githubusercontent.com/8161283/38700914-d275f642-3e9c-11e8-842a-d242a121a591.png)

Double click on the bolded line. 

After that i looks like this:
![bildschirmfoto 2018-04-12 um 21 57 24](https://user-images.githubusercontent.com/8161283/38700933-e47c3cac-3e9c-11e8-854b-43fcf341fc5a.png)

Now i dont see this behavoiur. 

But i dont know why i see this etc...
