### ISSUE TITLE
rich text and angular brackets

### ISSUE THREAD

**Issue by sharmay** [osTicket/osTicket#4240]
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description
When Rich Text is enabled  Admin Panel -> Settings -> System -> Enable Rich Text:
Post reply from osticket dashboard truncate any angular brackets

### Steps to Reproduce

Post a reply to ticket and body add some code have <> (not equal)
1. Try with html mode and use real angular bracket
2. Try with html mode convert angular brackets to ampersand tags
3. Try without html mode and use real angular bracket
4. Try without html mode convert angular brackets to ampersand tags 

### Expected 
Angular brackets are preserved.

May be a good idea to use a special tag, <preserve_block>....</preserver_block> and whatever is between tags is preserved as is. 

### version 1.10.1

Host OS Linux CentOS 7.x Latest
Apache server
Client Chrome latest on Fedora 27

**Comment by JediKev** [comment]
@sharmay 

This is by design....to remove any chance of XSS.

We hope to address this in v2.0.

Cheers.

**Comment by greezybacon** [comment]
I for one find this quite frustrating. I think it must be a bug in the combination of the Redactor editor and the htmLawed scrubbing system. Somehow the angle brackets should be properly encoded rather than removed along with their content.

**Comment by greezybacon** [comment]
So it seems this is the line of code causing the frustration:
```patch
diff --git a/include/class.format.php b/include/class.format.php
index 27497d3d..859ca27c 100644
--- a/include/class.format.php
+++ b/include/class.format.php
@@ -292,7 +292,7 @@ class Format {
                     'balance' => 1,
                     // Decoding special html char like &lt; and &gt; which
                     // can be used to skip cleaning
-                    'decode' => true
+                    'decode' => false
                     ),
                 $options);
 
```
Does anybody know why this is done? htmLawed, with `safe` setting set does not consider `&lt;` and friends as a threat. How can they be used to skip cleaning?

**Comment by JediKev** [comment]
@greezybacon 

This is why it was added: https://github.com/osTicket/osTicket/commit/46c705f44e1683abf407bf78e0108eaf1dff81fe

Cheers.

**Comment by greezybacon** [comment]
@jedikev, thanks for the research. I guess I was looking for a stronger defense on why it was added—specifically, •how• could the cleaning be bypassed by using the xml entities, and is that truly a valid concern.

**Comment by greezybacon** [comment]
[According to htmLawed](http://www.bioinformatics.org/phplabware/internal_utilities/htmLawed/htmLawed_README.htm#s3.2) (the HTML scrubbing system used by osTicket),  entities are scrubbed as part of the scrubbing process.

One could test using their [online test tool](http://www.bioinformatics.org/phplabware/internal_utilities/htmLawed/htmLawedTest.php) and using an invalid entity in the input,
```
And for some html-ish code<br>&lt;sarcasm&gt;<br>This should be supported<br>&lt;/sarcasm&gt;&qqt;
```
see that it is scrubbed to
```
And for some html-ish code<br />&lt;sarcasm&gt;<br />This should be supported<br />&lt;/sarcasm&gt;&amp;qqt;
```
and the invalid HTML tags ("sarcasm") are not removed.

I wonder if this was more of a concern for text-based (non-HTML) systems where HTML is not normally intended to be included with plain text?
