### ISSUE TITLE
Reloading after reply -> Same message added again

### ISSUE THREAD

**Issue by Af0x** [osTicket/osTicket#4241]
Hello,
if a customer replies to a ticket and reloads the page after, the same reply gets added to the ticket again.
osTicket 1.10.1, Firefox 59.0.2
Regards,
Af0x

**Comment by Af0x** [comment]
The same behaviour also exists for newly created tickets.

**Comment by Af0x** [comment]
hello, why close? Is this resolved?

**Comment by JediKev** [comment]
@Af0x 

Closed because it was old and not updated in the past year. If this is still an issue please re-open.

Cheers.

**Comment by Af0x** [comment]
I wonder if anyone ever tried to reproduce it...

**Comment by JediKev** [comment]
@Af0x 

Yes, this is a known issue for a while and has been reported on the forum a few times as well. We have a fix in place that needs to be refactored/rethought since the codebase has changed.

Cheers.

**Comment by Af0x** [comment]
Well until then I´d like to keep this open but I don´t have the permission to reopen.

**Comment by Af0x** [comment]
Can you please reopen this or has it been fixed?
