### ISSUE TITLE
Check Ticket Status fails when collaborator is also agent

### ISSUE THREAD

**Issue by Tauwasser** [osTicket/osTicket#4243]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [x] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

I added myself as a collaborator by adding my email address. I tried to get a collaborator link via the Check Ticket Status page. We have email confirmation enabled for that. I experienced a white page.

I got the following error log:

> [Tue Apr 17 20:43:45.945404 2018] [:error] [pid 29902] [client 172.17.0.71:44770] PHP Fatal error:  Uncaught Error: Call to a member function sendAccessLink() on null in /srv/ticket.example.com/osTicket-v1.10/login.php:93\nStack trace:\n#0 {main}\n  thrown in /srv/ticket.example.com/osTicket-v1.10/login.php on line 93, referer: https://ticket.example.com/view.php

I suspect it has to do with [login.php#L89](https://github.com/osTicket/osTicket/blob/develop/login.php#L89):

`
// This will succeed as it is checked in the authentication backend
$ticket = Ticket::lookupByNumber($_POST['lticket'], $_POST['lemail']);
`

which calls to `Ticket::lookupByNumber`, which calls `static Ticket::getIdByNumber` [class.ticket.php#L2878](https://github.com/osTicket/osTicket/blob/develop/include/class.ticket.php#L2878), which performs a query:

`
        $query = static::objects()
            ->filter(array('number' => $number));
        if ($email)
            $query->filter(array('user__emails__address' => $email));
`

I suspect the second filter actually makes `Ticket::lookupByNumber` fail, even though the authentication backend returns a user. However, I understand too little of osTicket to actually find out what query is being built and if I'm in a user table even though I'm an agent :-/

I unfortunately cannot spend the time to test the current develop branch to see if this error is gone. I also might update to v1.10.1 in the future, but as the relevant source files are the same, I suspect the bug is still there.

### Steps to Reproduce

1. Add collaborator to a ticket using email address.
2. Go to Check Ticket Status page while logged out. I used a Firefox Private Window.
3. Enter email address and ticket ID and click "Email Access Link"

**Expected behavior:**

I expected to be mailed a collaborator email access link.

**Actual behavior:**

White page, because of a php error.

### Versions

osTicket Version     v1.10 (901e5ea)
Web Server Software  Apache/2.4.25 (Debian)
MySQL Version        10.1.26
PHP Version          7.0.27-0+deb9u1

**Comment by JediKev** [comment]
@Tauwasser 

You're an Agent with access to the ticket queues...why do you need an access link to the ticket when you can search for the ticket in the queues and view it there?

Cheers.

**Comment by Tauwasser** [comment]
Because we had an issue with auth tokens not working, probably because of a literal plus sign sneaking into the url on the user's side (either mail client or browser).

So I wanted a genuine collaborator link to see if that worked and I used my own email address to do so :)

**Comment by JediKev** [comment]
@Tauwasser 

Ahhh, you can use a personal email address or add a `+` to your email like: `normal+added@gmail.com`. That's what we do for testing here.

Cheers.

**Comment by JediKev** [comment]
@Tauwasser 

Basically this is failing because you don't have a User account associated with your email address. Normally when you add a Collaborator it adds a User account for them in the system so it can lookup that User later for the auth tokens etc. You can add yourself as a User using your Agent email but I wouldn't recommend that because the system could potentially get confused if you were assigned a ticket from yourself and the alerts would be going crazy etc. So it's best to add yourself as a User using the above method for the email address (your email `+` something) so it's a clear separation from your actual Agent email. (It's actually best to use a personal email not in the system but either way works)

Cheers.

**Comment by ntozier** [comment]
In other words.  Collaborators are always and only Users.  We create User accounts for all our agents to over come this (and have for quite some time now).  A long time ago @greezybacon said that there would be a feature like Collaborators for Agents forth coming, but I haven't seen it yet.
