### ISSUE TITLE
Unable to transfer Claimed Ticket to Another Department

### ISSUE THREAD

**Issue by Acu2Ind** [osTicket/osTicket#4246]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch? Yes
* [ ] Do you have any errors in the PHP error log, or javascript console? No
* [ ] Did you check the [osTicket forums](http://osticket.com/forum/categories) ? Yes
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported? Yes

### Description

Unable to transfer a Claimed Ticket to Another Department

### Steps to Reproduce

1. Create a ticket as an agent and assign it to own department,for which the creating agent is primary 
2. The ticket gets created and shows under Open Ticket
3. Claim the Ticket
4. Transfer the ticket to a new Department
5. Even though the Department in the ticket changes, the ticket does NOT appear when the agent for the new department logs in. The ticket continues to show under first claiming agent.

**Expected behavior:** [What you expected to happen]
The ticket should move to the new dept and should be accessible to agent from the new department

**Actual behavior:** [What actually happened]
The ticket continues to show under first claiming agent.

### Versions
![information](https://user-images.githubusercontent.com/30118379/38952477-71b87f4c-4369-11e8-9729-1bc02c890f6c.png)

**Comment by ntozier** [comment]
Step 3.  you claimed the ticket.  So it's your ticket.
Then you Step 4 transfer it to another department.
The state of the ticket is that it has been transferred to another department AND is assigned to you.

**Comment by Acu2Ind** [comment]
Thanks for your response.

The idea is the first claiming agent has played his/her part on the ticket. And then the ticket must be transferred to next department, for further action from another agent in the transferred department.

**Comment by ntozier** [comment]
Then the claiming agent should assign it to another agent.
Or get the Department Manager to un-assign it from them.

**Comment by Acu2Ind** [comment]
Thanks again. 

Checking the option of “”Restrict ticket assignment to department members, during department creation helped me accomplish the required results (though I wonder how come!)

Closing this.
