### ISSUE TITLE
SLA Assignment

### ISSUE THREAD

**Issue by akash65** [osTicket/osTicket#4249]
i'm having issue with SLA assignment.
can anyone say that if i assign ticket from one agent to another agent does the SLA plan will change according to department?

But i have error in it..please help me..

**Comment by ntozier** [comment]
This does not appear to be a issue/bug report.  I would invite you to seek your support experience at the support forums.  http://osticket.com/forums

version of osTicket?
System Environment Details?
what is the "error in it"?
Steps to reproduce issue?
department settings for starting and destination department?
