### ISSUE TITLE
TLS/SSL failure for mail.domain.xxx : SSL negotiation failed

### ISSUE THREAD

**Issue by mariamghalleb** [osTicket/osTicket#4252]
### Prerequisites
* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
- [x] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
- [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already 

reported?

### Description
I migrated Osticket from a server to another everything works fine except: 
All the emails that used to work in the other server are now facing this issue:  
![capture04](https://user-images.githubusercontent.com/28814080/39247579-772b10f0-48a2-11e8-8a69-b9c537211d29.PNG)

### Steps to Reproduce

1. Migrate an osticket from a server to another 

**Expected behavior:** A working osticket. 

**Actual behavior:** Mail Fetch Errors and Unability to add a new email fetching email via IMAP or POP.

![capture07](https://user-images.githubusercontent.com/28814080/39246832-5bb9924e-48a0-11e8-9a1e-c7161ae25c9c.PNG)

I tried to add a new email but i keep getting the same error (See attachment 1)

### Versions

Osticket v1.9.14,
Web Server Apache, 
Php 5.6, MySql 5.6

> Please note that I had no problem with any of this in the first server.

**Comment by JediKev** [comment]
@mariamghalleb 

This is a duplicate of #1132. Please close this and continue the conversation on the original thread.

Cheers.

**Comment by mariamghalleb** [comment]
My solution was to put the server's url in the hostname (instad of mail.xxxx.com i did S1.xxxx.com) with imap+sssl and 993 as the port number.

**Comment by mariamghalleb** [comment]
close #4252

**Comment by mariamghalleb** [comment]
My solution was to put the server's url in the hostname (instad of mail.xxxx.com i did S1.xxxx.com) with IMAP + SSL and 993 as the port number.

**Comment by mariamghalleb** [comment]
My solution was to put the server's url in the hostname (instad of mail.xxxx.com i did S1.xxxx.com) with IMAP+SSL and 993 as the port number.
