### ISSUE TITLE
The links in my emails are all not working

### ISSUE THREAD

**Issue by kukunda** [osTicket/osTicket#4255]
Installed OsTicket 1.10.1 and it was working fine. the links in the email stopped working all of a sudden. 
osTicket Version | v1.10.1 (9ae093d) 
Web Server Software | Apache/2.4.26 (Win32) OpenSSL/1.0.2l PHP/5.6.31
MySQL Version | 10.1.25
PHP Version | 5.6.31
Yes i checked the osticket forums all the provided solutions didnt help. checked my class.thread and class.variable code and it was all fine.
Please help

**Comment by ntozier** [comment]
This does not appear to be a bug report.  I would invite you to seek your support experience at the support forums at: http://osticket.com/forums

You will want to include the information you posted above and:
define "not working".
What do they look like?
Where do they go?
What happened to the server recently? (software upgrades, IP changes, name changes, etc).

**Comment by kukunda** [comment]
Thank You ntozier for the response.
Kindly help with this as i forward it to the support forum.
The links provided in the customer emails send an error 404
the access link displays this in the browser: http://ticket.use.or.ug/view.php?auth=o1xaqaaaad3aaaaaoQhrhCAQh%2F0vHA%3D%3D
Error 404
the response email to the customer: link http://ticket/ats_ticket/upload/view.php?auth=o1xaiaaaaakaaaaaPR6pTFOdmo5Mcg%3D%3D
Error 404
No changes to the server have made.

**Comment by ntozier** [comment]
This link doesn't have a domain.
http://**ticket/ats_ticket/**upload/view.php?auth=o1xaiaaaaakaaaaaPR6pTFOdmo5Mcg%3D%3D
