### ISSUE TITLE
"git clone https://www.example.com/repository" and return 503 error

### ISSUE THREAD

**Issue by luoyixin** [osTicket/osTicket#4258]
"git clone https://www.example.com/repository" and return 503 error

rebooting the server does not solve the problem. 
Run ''ghe-cluster-config-apply' solved the issue.

**Comment by JediKev** [comment]
....wut?

**Comment by ntozier** [comment]
This doesn't appear to be related to this project, so I am unsure what you are opening a bug report for it.
