### ISSUE TITLE
Bug in getLastMessage()

### ISSUE THREAD

**Issue by host138** [osTicket/osTicket#4261]
`PHP Catchable fatal error:  Object of class AnnotatedModel could not be converted to string`
class.ticket.php -> Ticket->getLastMessage()
Temporaly solution is: 
```
if($this->last_message instanceof AnnotatedModel){
     $this->last_message = $this->last_message->model;
 }
```
Caller: Ticket->onAssign()
ObjectThread->getLastMessage() can return AnnotatedModel

**Comment by JediKev** [comment]
@host138 

What PHP version are you using?

Cheers.

**Comment by host138** [comment]
@JediKev 
PHP 7.0.28
