### ISSUE TITLE
Advanced search - Wrong date formats

### ISSUE THREAD

**Issue by geo782** [osTicket/osTicket#4264]
Hi,
I have a problem with dates in advanced search. I want to get a list with all tickets that created and closed 60 days ago, so i opened the advanced search, added the Closed date in the criteria and for both Closed and Created date fields, i selected BEFORE and from calendar i selected 04/03/2018 (4th March). 

When i run the search, the results are wrong. I go back to advanced search and both fields are now 03/04/2018 (3th April). It seems that when the search is running it converts date to mm/dd/yyyy. I tried to write date manually but it doesn't change anything.

In admin settings 
I have : 
Locate : Greek
Default time zone : Europe - Athens
Date format : dd/MM/y
Date and time format : dd/MM/y h:mm a
Day, Date and Time Format: EEE, MMM d y h:mm a

1.10.1 version

Regards
George

**Comment by JediKev** [comment]
@geo782 

I'm unable to replicate this with the latest version of v1.10.2 (v1.10.1 with security patches). I have set my **Date Format** explicitly to `dd/MM/y`, created an advanced search, set the **Created** and **Closed** date to be **Before** `07/05/2018` (today), and clicked Search. This gave me the correct results. When I go back and edit the fields in the Advanced Search they still show as `07/05/2018`.

One thing to note is upon selecting the dates, whilst creating the Advanced Search, it set as `07/05/2018` before I clicked Search so if it's showing you `05/07/2018` after you select it then something is wrong with the formatter. I'm using the default version of v1.10.2 with no customizations and it's working just fine.

Cheers.

**Comment by geo782** [comment]
Thanks for the reply,
I have also 1.10.1 with security patches (1.10.2)
For me, i Select 07/05/2018 from calendar and text field is 07/05/2018 (Correct). When i press "Search", the results are for 05/07/2018 (wrong). If i return to advanced search, field is displayed as 05/07/2018 (wrong).
Its the only place i have problem with dates. List date columns, ticket dates are all correct.
This is simular with this old post http://osticket.com/forum/discussion/80397/date-range-advanced-search

**Comment by geo782** [comment]
Today I did some tests again and i found that I have to manually insert dates like '2018-03-04' to make the search work. Also if use the calendar and select 14/05/2018 i get a 500 error, i think because there is a problem with value 14 as month!

Anyway, i checked also timezones:

Software | Default timezone |  
mysql date time? | EEST (Interpreted as Europe/Helsinki) | (because of same Hours as Athens)
php date   time? | Europe/Athens |  
server os date time? | Δευ 14 Μάι 2018 02:50:11 μμ EEST |  
agent profile date time? | Europe/Athens |  
osticket date time? | Europe/Athens |  

In #1848 you give a fix but the first line that you add, i cannot find the code where i have to add it.


Regards
George

**Comment by JediKev** [comment]
@geo782 

Please post a screenshot of the entire **Admin Panel > Settings > System > Date and Time Options** section.

Cheers.

**Comment by geo782** [comment]
![faidra_date_time_settings](https://user-images.githubusercontent.com/14315511/40099628-724cb1ae-58e9-11e8-9086-c66de5726bbe.jpg)

**Comment by JediKev** [comment]
@geo782 

Hmm...I have replicated your _exact_ setup on my v1.10.2 instance and cannot replicate this issue at all.

Have you made any modifications to your installation or have you implemented any pull requests that haven't been merged to the codebase yet?

Also, do you have any errors via Apache/PHP error logs?

Cheers.

**Comment by geo782** [comment]
@JediKev 

All modifications are small fixes + 1.10.2 security patch, but nothing that has to do with dates. Also I haven't touch search/advanced search files.
No errors in apache/php error logs.

By saying exact setup, do you mean having the same msql/server timezones ?

thanks
George

**Comment by JediKev** [comment]
@geo782 

The timezones have nothing to do with the date format as the system uses the format from **Admin Panel > Settings > System > Date and Time Options**.

By exact setup I mean the exact setup that was in the picture you posted above that contained the _Date and Time Options_ section. I changed my installation to use exactly what was in the picture of the _Date and Time Options_ and mine still worked fine. (**Default Locale**, **Default Timezone**, **etc.**)

Is this a new installation of v1.10.2 or is this an upgrade? Have you tried replicating this on a completely blank and new installation of v1.10.2?

Cheers.

**Comment by geo782** [comment]
@JediKev 

Installed fresh 1.10.2 and it works fine. I'll have to compare files and report back.

**Comment by geo782** [comment]
I found the problem... in include/class.forms.php i had added class="form-control" to all inputs. I removed it from line 3759 and now it works fine.

**Comment by JediKev** [comment]
@geo782 

Ahhhh, that'll do it! I'm glad you've resolved the issue! 👍

Cheers.

**Comment by geo782** [comment]
@JediKev 

I have found a new problem in advanced search. If you use the "Created" field and select "on" and then select date, i get white screen with 500 error. If i select "before" or "between", no problem.   Tested on my site and fresh 1.10.2 installation. 

Regards
George

**Comment by JediKev** [comment]
@geo782 

Pretty much all of the Advanced Search issues are addressed in `v1.11.0rc-1`, including this issue. Below are some screenshots from `v1.11.0rc-1` to show that this issue has in fact been mitigated.

**Search Criteria:**
![screen shot 2018-05-22 at 08 24 19](https://user-images.githubusercontent.com/11823401/40365255-bc45f392-5d99-11e8-8114-15f5c9bb9573.png)

**Search Results:**
![screen shot 2018-05-22 at 08 24 30](https://user-images.githubusercontent.com/11823401/40365258-bf6507f2-5d99-11e8-9c2f-c614c59d1004.png)

Cheers.
