### ISSUE TITLE
PHP Fatal error on install [1.10.1]

### ISSUE THREAD

**Issue by hinnerkweiler** [osTicket/osTicket#4271]
### Prerequisites

* [ x] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ x] Do you have any errors in the PHP error log, or javascript console?
* [ x] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [ x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

Hi,
I am trying to install osTicket (fresh install) but the installation procedure terminates in a blank page.  Php Error Log shows:

```
[08-May-2018 16:55:02 UTC] PHP Warning:  Declaration of AssignmentForm::render($options) should be compatible with Form::
render($staff = true, $title = false, $options = Array) in [serverpath]/include/class.forms.php on line 436
7
[08-May-2018 16:55:02 UTC] PHP Warning:  Declaration of TransferForm::render($options) should be compatible with Form::re
nder($staff = true, $title = false, $options = Array) in [serverpath]/include/class.forms.php on line 4487
[08-May-2018 16:55:05 UTC] PHP Fatal error:  Uncaught InvalidArgumentException: List indices should be integers in [serverpath]/support/include/class.util.php:149
Stack trace:
#0 [serverpath]/include/class.forms.php(81): ListObject->offsetExists('name')
#1 [serverpath]/include/class.ticket.php(3004): Form->getField('name')
#2 [serverpath]/include/class.ticket.php(3182): Ticket::filterTicketData('api', Array, Array, NULL)
#3 [serverpath]/setup/inc/class.installer.php(293): Ticket::create(Array, Array, 'api', false, false)
#4 [serverpath]/setup/install.php(52): Installer->install(Array)
#5 {main}
  thrown in [serverpath]/include/class.util.php on line 149  
```
### Steps to Reproduce

1. well ... fill out the Information
2. click continue

**Expected behavior:** [What you expected to happen]
successful install
 
**Actual behavior:** [What actually happened]
installation unusable
### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

PHP version | 5.6 (tryed also in 7.2)
MySQL version | 5.6.38
shared host
Firefox 59

**Comment by JediKev** [comment]
This is a known issue with a temporary fix here: https://github.com/osTicket/osTicket/pull/3349/files

Don’t make the change on line 2284 though, it’s not necessary.

We are going to support PHP 7.x+ in v2.0 so stay tuned.

Cheers.

**Comment by hinnerkweiler** [comment]
Thanks for the hint. The installation was supposed to be on a PHP 5.6 but `phpinfo()` revealed I forgot the addhandler in htaccess. Now it's `PHP Version 5.6.32-nmm1`.

 However, the Warnings are gone now but they were not my biggest problem: The installer still dies on a blank page:
```
[08-May-2018 19:38:27 UTC] PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'List indices should be integers' in /www/htdocs/anholt/support/include/class.util.php:149
Stack trace:
#0 /www/htdocs/anholt/support/include/class.forms.php(81): ListObject->offsetExists('name')
#1 /www/htdocs/anholt/support/include/class.ticket.php(3004): Form->getField('name')
#2 /www/htdocs/anholt/support/include/class.ticket.php(3182): Ticket::filterTicketData('api', Array, Array, NULL)
#3 /www/htdocs/anholt/support/setup/inc/class.installer.php(293): Ticket::create(Array, Array, 'api', false, false)
#4 /www/htdocs/anholt/support/setup/install.php(52): Installer->install(Array)
#5 {main}
  thrown in /www/htdocs/anholt/support/include/class.util.php on line 149
```

**Comment by JediKev** [comment]
@hinnerkweiler 

I believe you're trying to install it with a language pack. Please install osTicket in English, add the language pack afterwards, and configure it to be the Primary Language. We hope to fix this bug soon.

Cheers.

**Comment by hinnerkweiler** [comment]
Lovely! That was the cause. Thanks for your patience :) I should have mentioned that I did so. It installed perfectly in english!
