### ISSUE TITLE
<style> in email templates

### ISSUE THREAD

**Issue by ThomasKlijnman** [osTicket/osTicket#4272]
### Description

I did not find it on the forums. But I wanted to remove the "remove <style> function from osTicket. Because I wanted to add my own CSS to the template. But even putting it in the database directly doesn't remove the feature. Anyway possible? to just disable the "remove <style>" function?

### Version

osTicket 1.10

**Comment by ThomasKlijnman** [comment]
![image](https://user-images.githubusercontent.com/15871270/39782410-62bae918-5312-11e8-9f33-0fb483d79f4e.png)
It's in dutch but you see the body padding? That is in code on <style> but turns into this..

**Comment by JediKev** [comment]
@ThomasKlijnman

You have to click the HTML button `<>` and then type HTML/CSS code. Once finished click the button again, Save Changes, and all should be fine.

Cheers.

**Comment by ThomasKlijnman** [comment]
Not to be fun killer. But that is what I did..... I added all the code via the HTML <> area. 
![image](https://user-images.githubusercontent.com/15871270/39782898-c6531e54-5313-11e8-816c-95406877403c.png)
The <style> gets removed when saving...

**Comment by JediKev** [comment]
Hmmm... Don’t use `<style>` tags instead wrap everything in `<div style=“”></div>` tags.

Cheers.

**Comment by ThomasKlijnman** [comment]
So : "<span style="     body{padding-top:20px;padding-bottom:20px}.header,.marketing,.footer{padding-right:15px;padding-left:15px}.header{padding-bottom:20px;border-bottom:1px solid #e5e5e5}.header h3{margin-top:0;margin-bottom:0;line-height:40px}.footer{padding-top:19px;color:#777;border-top:1px solid #e5e5e5}
@media(min-width:768px){.container{max-width:730px}}.container-narrow>hr{margin:30px 0}.jumbotron{text-align:center;border-bottom:1px solid #e5e5e5}.jumbotron.btn{padding:14px 24px;font-size:21px}.marketing{margin:40px 0}.marketing p+h4{margin-top:28px}
@media screen and(min-width:768px){.header,.marketing,.footer{padding-right:0;padding-left:0}.header{margin-bottom:30px}.jumbotron{border-bottom:0}}">{HTML HERE?!}</span>

**Comment by ntozier** [comment]
It's probably being stripped by htmLawed.
/include/htmLawed.php

**Comment by ThomasKlijnman** [comment]
So I need to remove htmlLawed.php but how? I cant just remove it? hahaa right?

**Comment by ntozier** [comment]
You would edit the file I gave you. :)

You can get more information about htmLawed here:
http://www.bioinformatics.org/phplabware/internal_utilities/htmLawed/
