### ISSUE TITLE
Wrong timezone in Excessive login attempts email

### ISSUE THREAD

**Issue by iHunt101** [osTicket/osTicket#4273]
Excessive login attempts by an agent?
Username: user
IP: 127.0.0.1
Time: May 9, 2018, 2:50 am UTC

Attempts: 23
Timeout: 5 minutes

This is the email i received from the system. But it gives a wrong data of time.
Email data of time is different from the system time.

**Comment by JediKev** [comment]
@iHunt101 

You are probably seeing the time in the system being translated to your timezone whereas the time in the email is in UTC.

Cheers.

**Comment by JediKev** [comment]
@iHunt101 

The line referenced below is what generates the timestamp in the email. This uses PHP's built-in `date()` function which uses the timezone from either `date_default_timezone_set()` or the server's timezone. What timezone do you have set for PHP (**Admin Panel > Dashboard > Information > PHP Settings > `date.timezone`**)? 
https://github.com/osTicket/osTicket/blob/55dc25ace736baeaf224ee608cfabc0218022036/include/class.auth.php#L887

Cheers.

**Comment by iHunt101** [comment]
Hi @JediKev , my Database Information and Usage timezone is different from my PHP timezone, how to sync this two settings?
