### ISSUE TITLE
View the Assigned agent/dept by end user

### ISSUE THREAD

**Issue by Rujinraj** [osTicket/osTicket#4277]
Hello Team,

I have a query regarding the user ticket interface, we can see the option like Basic Ticket Information ,User Information ,Ticket Details etc. I could see created by with user name. 

Is there any way to see the ticket assigned agent/dept by end user. If yes where I need to modify this.

Kindly help.

Version : 1.10.2

page: Ticket.php

**Comment by JediKev** [comment]
@Rujinraj 

The only easy way to accomplish this at the moment is by adding a Custom Field to the Ticket Details Form. Make this Custom Field an 'Assignee' field, have it Visible to both Agents & Users, and have it only Editable to Agents. Now, when an Agent is working on a Ticket they can click 'Edit' and add the Assigned Agent in your Assignee Custom Field and Save Changes. At that point when a User looks at their ticket via the Client Portal they should see the Assignee Field and who is assigned.

You could also modify the source code to allow the Original Assignee field to be displayed on the Client Side but you're on your own on this one.

Cheers.

**Comment by Rujinraj** [comment]
Thanks
