### ISSUE TITLE
Attachments on the filesystem not working!

### ISSUE THREAD

**Issue by shenol** [osTicket/osTicket#4278]
When I want to view pictures, I get the following error.

This file format may not be supported.

**Comment by ntozier** [comment]
This does not appear to be a bug report. I would invite you to seek your support experience at the support forums at: http://osticket.com/forums.  Please help us to help you by reading and following the posting guidelines located in this thread: [Please read before requesting assistance.](http://www.osticket.com/forum/discussion/77765/please-read-before-requesting-assistance#latest)  The more information you give us the better we will be able to assist you. Thank you.

**Comment by shenol** [comment]
@ntozier 

I did a standard setup. I get this error.


[Tue May 15 17:27:06.867746 2018] [:error] [pid 12912] [client 213.14.88.10:41310] PHP Fatal error:  Uncaught exception 'InconsistentModelException' with message 'Unable to prepare query:  SELECT A1.* FROM `ss_file` A1 WHERE A1.`key` = 'btffkbe9_hgxrofdi\xfdouoqlk\xfdxctn8zs'' i
