### ISSUE TITLE
Duplicate day issue 

### ISSUE THREAD

**Issue by tgbles** [osTicket/osTicket#4279]
When a new ticket is opened from the front page (without logging in), the user is met with an empty ticket inluding date input. When a date is picked from the calender, the output is wrong showing dayday.month.year (example: 1111.may.2018). 

1. System configurations:
![s3](https://user-images.githubusercontent.com/31822891/39915580-9b904434-5508-11e8-8f0f-be5dd89105da.png)
Set at default. Same problem happens with advanced date setting.

2. Open new ticket:
![s4](https://user-images.githubusercontent.com/31822891/39915736-ff50cec6-5508-11e8-8baf-876dcc7d3440.png)
This occurs when a new ticket is opened from the main page (without logging in)
When the user is logged in and opens a new ticket from the ticket page, the date shows correct format.

3. Day shows twice
![s5](https://user-images.githubusercontent.com/31822891/39915938-8976e270-5509-11e8-9137-3ba61dd3f5d6.png)
Picking a date from the calender gives a wrong date format.

Osticket version: osTicket (v1.10.1)
PHP version: 7.0.22-0ubuntu0.16.04.1

**Comment by ntozier** [comment]
Regarding your first problem, I'm not real sure what you mean since the screen shot that you provided does not appear to be "the user is met with an empty ticket inluding date input." and has no date on it.

As far as the second issue I believe that is addressed in v1.11rc-1 which is supposed to be released soon.

**Comment by JediKev** [comment]
@tgbles 

The fix for this is here: https://github.com/osTicket/osTicket/pull/3623

This is merged into v1.11rc-1, as @ntozier said, and will be released soon. Please close this issue.

Cheers.

**Comment by tgbles** [comment]
Thank you for your replies.

Cheers

**Comment by Richies97** [comment]
Did this fix help you, cause when i add it the error style occurs
