### ISSUE TITLE
Long query running ...

### ISSUE THREAD

**Issue by cervedgroup** [osTicket/osTicket#4282]
Latest version of osticket .. running this command con mysql " SHOW FULL PROCESSLIST;" 
 we have this query running since 30 mins ...
command : query
state : copying to tmp table
progress 0,000

SELECT distinct f.id, COALESCE(a.type, f.ft), a.`name` FROM ost_file f LEFT JOIN ost_attachment a ON (a.file_id = f.id)
            WHERE ((a.`type` IN ('C', 'F', 'T', 'P') AND a.`inline` = 1) OR f.ft = 'L') AND f.`type` LIKE 'image/%' UNION SELECT f.id, a.`type`, a.`name` FROM ost_thread t
                JOIN ost_thread_entry th ON (th.thread_id = t.id)
                JOIN ost_attachment a ON (a.object_id = th.id AND a.`type` = 'H')
                JOIN ost_file f ON (a.file_id = f.id)
                WHERE a.`inline` = 1 AND t.id=234152

is that normal ?

**Comment by JediKev** [comment]
@cervedgroup 

>is that normal ?

A single query running for over 30min+? Not normal at all.

That is due to this function though:
https://github.com/osTicket/osTicket/blob/55dc25ace736baeaf224ee608cfabc0218022036/include/ajax.draft.php#L331-L369

I hope this helps. Cheers.

**Comment by cervedgroup** [comment]
i found on internet that that problem could be on innodb buffer or some other settings related to innodb.. 
this is the status of our innodb ... have you some ideas about ?
thank you


=====================================
180516 15:57:03 INNODB MONITOR OUTPUT
=====================================
Per second averages calculated from the last 5 seconds
-----------------
BACKGROUND THREAD
-----------------
srv_master_thread loops: 72622 1_second, 72621 sleeps, 7013 10_second, 2553 background, 2553 flush
srv_master_thread log flush and writes: 80261
----------
SEMAPHORES
----------
OS WAIT ARRAY INFO: reservation count 12293, signal count 245054
Mutex spin waits 5756578, rounds 4522233, OS waits 3440
RW-shared spins 138992, rounds 394282, OS waits 6701
RW-excl spins 13876, rounds 340578, OS waits 2041
Spin rounds per wait: 0.79 mutex, 2.84 RW-shared, 24.54 RW-excl
--------
FILE I/O
--------
I/O thread 0 state: native aio handle (insert buffer thread)
I/O thread 1 state: native aio handle (log thread)
I/O thread 2 state: native aio handle (read thread)
I/O thread 3 state: native aio handle (read thread)
I/O thread 4 state: native aio handle (read thread)
I/O thread 5 state: native aio handle (read thread)
I/O thread 6 state: native aio handle (write thread)
I/O thread 7 state: native aio handle (write thread)
I/O thread 8 state: native aio handle (write thread)
I/O thread 9 state: native aio handle (write thread)
Pending normal aio reads: 0 [0, 0, 0, 0] , aio writes: 0 [0, 0, 0, 0] ,
 ibuf aio reads: 0, log i/o's: 0, sync i/o's: 0
Pending flushes (fsync) log: 0; buffer pool: 0
1210032 OS file reads, 278173 OS file writes, 81802 OS fsyncs
0.00 reads/s, 0 avg bytes/read, 20.80 writes/s, 2.60 fsyncs/s
-------------------------------------
INSERT BUFFER AND ADAPTIVE HASH INDEX
-------------------------------------
Ibuf: size 1, free list len 3, seg size 5, 321 merges
merged operations:
 insert 343, delete mark 31, delete 5
discarded operations:
 insert 0, delete mark 0, delete 0
Hash table size 10624951, node heap has 4576 buffer(s)
30704.86 hash searches/s, 1010.80 non-hash searches/s
---
LOG
---
Log sequence number 2443889515032
Log flushed up to   2443889515032
Last checkpoint at  2443889487710
Max checkpoint age    84223550
Checkpoint age target 81591565
Modified age          27322
Checkpoint age        27322
0 pending log writes, 0 pending chkp writes
69124 log i/o's done, 1.80 log i/o's/second
----------------------
BUFFER POOL AND MEMORY
----------------------
Total memory allocated 5512888320; in additional pool allocated 0
Total memory allocated by read views 1768
Internal hash tables (constant factor + variable factor)
    Adaptive hash index 159977008 	(84999608 + 74977400)
    Page hash           5313416 (buffer pool 0 only)
    Dictionary cache    42961786 	(42501104 + 460682)
    File system         83536 	(82672 + 864)
    Lock system         13286112 	(13281976 + 4136)
    Recovery system     0 	(0 + 0)
Dictionary memory allocated 460682
Buffer pool size        327679
Buffer pool size, bytes 1073725440
Free buffers            1
Database pages          323102
Old database pages      119250
Modified db pages       24
Pending reads 0
Pending writes: LRU 0, flush list 0, single page 0
Pages made young 832375, not young 0
0.00 youngs/s, 0.00 non-youngs/s
Pages read 1210021, created 9159, written 201768
0.00 reads/s, 0.00 creates/s, 18.40 writes/s
Buffer pool hit rate 1000 / 1000, young-making rate 0 / 1000 not 0 / 1000
Pages read ahead 0.00/s, evicted without access 0.00/s, Random read ahead 0.00/s
LRU len: 323102, unzip_LRU len: 0
I/O sum[357]:cur[0], unzip sum[0]:cur[0]
--------------
ROW OPERATIONS
--------------
0 queries inside InnoDB, 0 queries in queue
3 read views open inside InnoDB
2 transactions active inside InnoDB
2 out of 1000 descriptors used
---OLDEST VIEW---
Normal read view
Read view low limit trx n:o C201BA2A
Read view up limit trx id C201BA29
Read view low limit trx id C201BA2A
Read view individually stored trx ids:
Read view trx id C201BA29
-----------------
Main thread id 4608, state: flushing log
Number of rows inserted 27488, updated 46286, deleted 3277, read 7556379851
0.20 inserts/s, 1.00 updates/s, 0.00 deletes/s, 90177.96 reads/s
------------
TRANSACTIONS
------------
Trx id counter C201BA45
Purge done for trx's n:o < C201B84F undo n:o < 0
History list length 336
LIST OF TRANSACTIONS FOR EACH SESSION:
---TRANSACTION C201BA38, not started
MySQL thread id 26160, OS thread handle 0x6d8, query id 1076224811 sql01mi.cervedgroup.com 10.16.16.48 root
---TRANSACTION C201BA2B, not started
MySQL thread id 15052, OS thread handle 0x1360, query id 1076218140 sql01mi.cervedgroup.com 10.16.16.48 root
---TRANSACTION C201BA2C, not started
MySQL thread id 11841, OS thread handle 0x1360, query id 1076218142 sql01mi.cervedgroup.com 10.16.16.48 root
---TRANSACTION C201BA32, not started
MySQL thread id 8290, OS thread handle 0x1360, query id 1076218151 sql01mi.cervedgroup.com 10.16.16.48 root
---TRANSACTION C201BA2D, not started
MySQL thread id 2091, OS thread handle 0x1360, query id 1076218144 sql01mi.cervedgroup.com 10.16.16.48 root
---TRANSACTION C201BA3A, not started
MySQL thread id 2052, OS thread handle 0x1360, query id 1076227011 sql01mi.cervedgroup.com 10.16.16.48 root
---TRANSACTION C201BA35, not started
MySQL thread id 2048, OS thread handle 0x6d8, query id 1076218155 sql01mi.cervedgroup.com 10.16.16.48 root
---TRANSACTION C201BA37, not started
MySQL thread id 2046, OS thread handle 0x6d8, query id 1076222591 sql01mi.cervedgroup.com 10.16.16.48 root
---TRANSACTION C1EB8456, not started
MySQL thread id 246, OS thread handle 0x6d8, query id 1076239840 localhost 127.0.0.1 root
show engine innodb status
---TRANSACTION C201BA3F, ACTIVE 0 sec fetching rows
mysql tables in use 1, locked 0
MySQL thread id 2047, OS thread handle 0x1360, query id 1076229947 sql01mi.cervedgroup.com 10.16.16.48 root Sending data
select count(*) from view_TicketHelpdesk where created BETWEEN '2018-01-01 00:00:01' AND '2018-05-16 23:59:59'
Trx read view will not see trx with id >= C201BA40, sees < C201BA29
---TRANSACTION C201BA29, ACTIVE 1 sec 
mysql tables in use 2, locked 0
MySQL thread id 2051, OS thread handle 0x1264, query id 1076239882 sql01mi.cervedgroup.com 10.16.16.48 root Sending data
SELECT AVG(rowsPerDay) AS avgPerDay
                                                FROM ( SELECT 
                                                COUNT(*) AS rowsPerDay
                                                from view_tickethelpdesk
                                                where created BETWEEN '2018-01-01 00:00:01' AND '2018-05-15 23:59:59'
                                                and IsWorkingDay(created) = true
                                                GROUP BY DATE(created)) AS a
Trx read view will not see trx with id >= C201BA2A, sees < C201BA2A
----------------------------
END OF INNODB MONITOR OUTPUT
============================

**Comment by cervedgroup** [comment]
i found on the net that this kind of problem could be related to innodb settings...
this is our innodb status and settings, have you some ideas ?
thank you

```
`
=====================================
180516 15:57:03 INNODB MONITOR OUTPUT
=====================================
Per second averages calculated from the last 5 seconds
-----------------
BACKGROUND THREAD
-----------------
srv_master_thread loops: 72622 1_second, 72621 sleeps, 7013 10_second, 2553 background, 2553 flush
srv_master_thread log flush and writes: 80261
----------
SEMAPHORES
----------
OS WAIT ARRAY INFO: reservation count 12293, signal count 245054
Mutex spin waits 5756578, rounds 4522233, OS waits 3440
RW-shared spins 138992, rounds 394282, OS waits 6701
RW-excl spins 13876, rounds 340578, OS waits 2041
Spin rounds per wait: 0.79 mutex, 2.84 RW-shared, 24.54 RW-excl
--------
FILE I/O
--------
I/O thread 0 state: native aio handle (insert buffer thread)
I/O thread 1 state: native aio handle (log thread)
I/O thread 2 state: native aio handle (read thread)
I/O thread 3 state: native aio handle (read thread)
I/O thread 4 state: native aio handle (read thread)
I/O thread 5 state: native aio handle (read thread)
I/O thread 6 state: native aio handle (write thread)
I/O thread 7 state: native aio handle (write thread)
I/O thread 8 state: native aio handle (write thread)
I/O thread 9 state: native aio handle (write thread)
Pending normal aio reads: 0 [0, 0, 0, 0] , aio writes: 0 [0, 0, 0, 0] ,
 ibuf aio reads: 0, log i/o's: 0, sync i/o's: 0
Pending flushes (fsync) log: 0; buffer pool: 0
1210032 OS file reads, 278173 OS file writes, 81802 OS fsyncs
0.00 reads/s, 0 avg bytes/read, 20.80 writes/s, 2.60 fsyncs/s
-------------------------------------
INSERT BUFFER AND ADAPTIVE HASH INDEX
-------------------------------------
Ibuf: size 1, free list len 3, seg size 5, 321 merges
merged operations:
 insert 343, delete mark 31, delete 5
discarded operations:
 insert 0, delete mark 0, delete 0
Hash table size 10624951, node heap has 4576 buffer(s)
30704.86 hash searches/s, 1010.80 non-hash searches/s
---
LOG
---
Log sequence number 2443889515032
Log flushed up to   2443889515032
Last checkpoint at  2443889487710
Max checkpoint age    84223550
Checkpoint age target 81591565
Modified age          27322
Checkpoint age        27322
0 pending log writes, 0 pending chkp writes
69124 log i/o's done, 1.80 log i/o's/second
----------------------
BUFFER POOL AND MEMORY
----------------------
Total memory allocated 5512888320; in additional pool allocated 0
Total memory allocated by read views 1768
Internal hash tables (constant factor + variable factor)
    Adaptive hash index 159977008 	(84999608 + 74977400)
    Page hash           5313416 (buffer pool 0 only)
    Dictionary cache    42961786 	(42501104 + 460682)
    File system         83536 	(82672 + 864)
    Lock system         13286112 	(13281976 + 4136)
    Recovery system     0 	(0 + 0)
Dictionary memory allocated 460682
Buffer pool size        327679
Buffer pool size, bytes 1073725440
Free buffers            1
Database pages          323102
Old database pages      119250
Modified db pages       24
Pending reads 0
Pending writes: LRU 0, flush list 0, single page 0
Pages made young 832375, not young 0
0.00 youngs/s, 0.00 non-youngs/s
Pages read 1210021, created 9159, written 201768
0.00 reads/s, 0.00 creates/s, 18.40 writes/s
Buffer pool hit rate 1000 / 1000, young-making rate 0 / 1000 not 0 / 1000
Pages read ahead 0.00/s, evicted without access 0.00/s, Random read ahead 0.00/s
LRU len: 323102, unzip_LRU len: 0
I/O sum[357]:cur[0], unzip sum[0]:cur[0]
--------------
ROW OPERATIONS
--------------
0 queries inside InnoDB, 0 queries in queue
3 read views open inside InnoDB
2 transactions active inside InnoDB
2 out of 1000 descriptors used
---OLDEST VIEW---
Normal read view
Read view low limit trx n:o C201BA2A
Read view up limit trx id C201BA29
Read view low limit trx id C201BA2A
Read view individually stored trx ids:
Read view trx id C201BA29
-----------------
Main thread id 4608, state: flushing log
Number of rows inserted 27488, updated 46286, deleted 3277, read 7556379851
0.20 inserts/s, 1.00 updates/s, 0.00 deletes/s, 90177.96 reads/s
------------
TRANSACTIONS
------------
Trx id counter C201BA45
Purge done for trx's n:o < C201B84F undo n:o < 0
History list length 336
LIST OF TRANSACTIONS FOR EACH SESSION:
---TRANSACTION C201BA38, not started
MySQL thread id 26160, OS thread handle 0x6d8, query id 1076224811 xxxxx.group.com 10.x.x.x root
---TRANSACTION C201BA2B, not started
MySQL thread id 15052, OS thread handle 0x1360, query id 1076218140 xxxxx.group.com 10.x.x.x root
---TRANSACTION C201BA2C, not started
MySQL thread id 11841, OS thread handle 0x1360, query id 1076218142 xxxxx.group.com 10.x.x.x root
---TRANSACTION C201BA32, not started
MySQL thread id 8290, OS thread handle 0x1360, query id 1076218151 xxxxx.group.com 10.x.x.x root
---TRANSACTION C201BA2D, not started
MySQL thread id 2091, OS thread handle 0x1360, query id 1076218144 xxxxx.group.com 10.x.x.x root
---TRANSACTION C201BA3A, not started
MySQL thread id 2052, OS thread handle 0x1360, query id 1076227011 xxxxx.group.com 10.x.x.x root
---TRANSACTION C201BA35, not started
MySQL thread id 2048, OS thread handle 0x6d8, query id 1076218155 xxxxx.group.com 10.x.x.x root
---TRANSACTION C201BA37, not started
MySQL thread id 2046, OS thread handle 0x6d8, query id 1076222591 xxxxx.group.com 10.x.x.x root
---TRANSACTION C1EB8456, not started
MySQL thread id 246, OS thread handle 0x6d8, query id 1076239840 localhost 127.0.0.1 root
show engine innodb status
---TRANSACTION C201BA3F, ACTIVE 0 sec fetching rows
mysql tables in use 1, locked 0
MySQL thread id 2047, OS thread handle 0x1360, query id 1076229947 xxxxx.group.com 10.x.x.x root Sending data
select count(*) from view_TicketHelpdesk where created BETWEEN '2018-01-01 00:00:01' AND '2018-05-16 23:59:59'
Trx read view will not see trx with id >= C201BA40, sees < C201BA29
---TRANSACTION C201BA29, ACTIVE 1 sec 
mysql tables in use 2, locked 0
MySQL thread id 2051, OS thread handle 0x1264, query id 1076239882 xxxxx.group.com 10.x.x.x root Sending data
SELECT AVG(rowsPerDay) AS avgPerDay
                                                FROM ( SELECT 
                                                COUNT(*) AS rowsPerDay
                                                from view_tickethelpdesk
                                                where created BETWEEN '2018-01-01 00:00:01' AND '2018-05-15 23:59:59'
                                                and IsWorkingDay(created) = true
                                                GROUP BY DATE(created)) AS a
Trx read view will not see trx with id >= C201BA2A, sees < C201BA2A
----------------------------
END OF INNODB MONITOR OUTPUT
============================
`
```
