### ISSUE TITLE
User Tickets Search Option

### ISSUE THREAD

**Issue by Rujinraj** [osTicket/osTicket#4286]
### Prerequisites
Hello All,

I am using V1.10.2 facing the issue in search option in user login.

Its not working based on the keyword which i entered.

Kindly help

**Comment by ntozier** [comment]
Please provide more details as to what your problem is and what your setup is.

Version of PHP?
System environment?
PHP errors?
[unknown webserver] errors?
Search term?
Do you actually mean the User side?  Or are you talking about the Agent side?

**Comment by Rujinraj** [comment]
User Side
