### ISSUE TITLE
class Signal pass by reference still not working

### ISSUE THREAD

**Issue by aburets-sc** [osTicket/osTicket#4287]
Original issue and fix #1014.
Was merged in #1037.
Steps to reproduce are the same.

**Comment by JediKev** [comment]
@aller

What is the version of PHP you're running?

Cheers.

**Comment by aller** [comment]
@JediKev 

osTicket running on 5.6.21

The code below was tested on 5.2.14, 7.1.15 and http://phpfiddle.org:

```
function abc($obj, &$data) {
    $data['var1'] = 2;
}

class A {
    function a1 (&$data){
        call_user_func_array("abc", array($this, $data));
    }
}

$data = array(
    'var' => 1,
    'var1' => 1,
    'var2' => 1,
    'var3' => 1,
);

$a = new A();
var_dump($data);
$a->a1($data);
var_dump($data);
```

In all cases it doesn't work and I got warning:
E_WARNING : type 2 -- Parameter 2 to abc() expected to be a reference, value given -- at line 9

So, Signal class will works as expect only if pass $data by reference forcibly:
call_user_func_array($callable, array($object, &$data));

Thanks a lot!

**Comment by aller** [comment]
@JediKev

I guess I found the problem - master branch is different than develop or 1.8.x
https://github.com/osTicket/osTicket/blob/8840eb14b94413bf51ee766cd6d20a69df54be22/include/class.signal.php#L98
and
https://github.com/osTicket/osTicket/blob/da684b948f2c1a8596da4ec328725d160dedde56/include/class.signal.php#L98
