### ISSUE TITLE
Closed Ticket - header name "Date closed" - issue with sorting

### ISSUE THREAD

**Issue by mlipok** [osTicket/osTicket#4288]
### Prerequisites

* [ Y ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ N ] Do you have any errors in the PHP error log, or javascript console?
* [ Y ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [ Y ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

Header "Date closed" is changing his name after sorting

### Steps to Reproduce

1. Go to "Closed Tickets"
2. Chceck name of second column is it "Date closed" == YES
3. Sort by Ticket numbers
4. Chceck name of second column is it "Date closed" == **NO**

**Expected behavior:** [What you expected to happen]
after sorting, the name of second column should not change

**Actual behavior:** [What actually happened]
The second column name is changing

### Versions

Wersja osTicket	v1.10.1 (9ae093d) —  Aktualny=Current
Oprogramowanie serwera WWW	Apache
Wersja MySQL	10.0.32
Wersja PHP	7.0.30-1+0~20180505045929.18+jessie~1.gbpcfecb9

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

**OS and browser is not related to this ticket**

**Comment by JediKev** [comment]
@mlipok 

This has been addressed in `v1.11.0rc-1`, please stay tuned for this release.

Cheers.

**Comment by mlipok** [comment]
Thanks for this news
