### ISSUE TITLE
Problems with the language in the “Sign-in-Page”

### ISSUE THREAD

**Issue by marsabu** [osTicket/osTicket#4291]
### Prerequisites

* [Y] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [N] Do you have any errors in the PHP error log, or javascript console?
* [Y] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [Y] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

Hi,
We have detected a problem: 
Although sign-in page has been configured in different languages, the same is always displayed, even if the user changes the selection

 (Sign-in Page in **_Users/templates_**)
![imatge](https://user-images.githubusercontent.com/39549909/40469870-20cde696-5f32-11e8-9806-bffc7e64d2f8.png)

The sign-in Page in **Catalan** (result in the user form)
 
![imatge](https://user-images.githubusercontent.com/39549909/40469876-28519778-5f32-11e8-9c69-9421d42b8170.png)

Sign-in Page in **English** (result in the user form)
 
![imatge](https://user-images.githubusercontent.com/39549909/40469920-4d6104b8-5f32-11e8-8ca4-9f6efb82711e.png)

### Versions

OsTicket | v1.10.1 (9ae093d)
Web Server Software | Apache/2.4.18 (Ubuntu)
Versió MySQL | 5.7.20
Versió PHP | 7.0.22-0ubuntu0.16.04.1

Language installed

català —
ca — include/i18n/ca.phar
Versió: 148432, for version v1.10
Creat: Fri, 13 Jan 17 17:14:08 +0000

English (United States) (anglès (Estats Units)) — ca_ES
en_US — include/i18n/en_US

español (España) (espanyol (Espanya)) — ca_ES
es_ES — include/i18n/es_ES.phar
Versió: 148432, for version v1.10
Creat: Fri, 13 Jan 17 17:13:33 +0000

**Comment by qatuno** [comment]
On my fresh installation i also got this trouble. Into the Editor the text will be shown, but only on one page the translation is not shown as into the editor field putted in. All other switches onto the page show the right translation, when pushed. / my have some different Version running, but have still 
"cgi.fix_pathinfo" marked as "!"  at the Server Information Side 


| v1.10.1 (9ae093d)     —  Aktuell 
Server-Software | Apache/2.4.18 (Ubuntu)
MySQL-Version | 5.7.22
PHP-Version | 7.0.30-0ubuntu0.16.04.1

**Comment by JediKev** [comment]
@qatuno 

The fix for this is here:
https://github.com/osTicket/osTicket/pull/3878

It has been merged into `v1.11.0rc-1` so please stay tuned for this release.

Cheers.
