### ISSUE TITLE
Advanced Search Datepicker broken when using 'between'

### ISSUE THREAD

**Issue by chrisscotweb** [osTicket/osTicket#4292]
### Description

Neither of the 2 datepickers that appear for the 'between' comparison in an advanced ticket search work.

### Steps to Reproduce

1. Open advanced search on Tickets
2. Select a field in 'Add Other Field'
3. Change the dropdown to 'between'
4. Select a date in the datepicker

**Expected behavior:** Datepicker closes with selected date

**Actual behavior:** Datepicker closes and input field remains blank

### Versions

OSTicket: v1.10.1-86-g1c14290 (1c14290)
OS: Linux (Ubuntu 16.04, Ubuntu 18.04)
Browser: Chrome 66, Firefox 60

**Comment by JediKev** [comment]
@chrisscotweb 

This has been addressed in `v1.11.0rc-1`. Please stay tuned!

Cheers.
