### ISSUE TITLE
Login page is not Authenticating

### ISSUE THREAD

**Issue by iHunt101** [osTicket/osTicket#4296]
I try to login as agent in the system. After successfully login i try to view my tickets.. It seems to be good so far.
But here is what i discover, even i am already login in the system, i try to access the login area again. It show to me the form and asking me 

> Authentication required

 even if i already done this. Looks like the login page does not check if the user trying to access is already login or not..  

Windows 10
Chrome version: 10682.0.0
Ostv 1.10.1

**Comment by JediKev** [comment]
@iHunt101

This doesn’t really matter. The only way you get to the login page again is if you manually type it in. I can add a check though.

Cheers.

**Comment by iHunt101** [comment]
Yes @JediKev  i think in some matter we need it so agents will not confuse if they were login already or not.. Can you make a it?
