### ISSUE TITLE
V1.11.x - Ticket creation fail if User member of an organisation setup to add Primary contacts to all tickets

### ISSUE THREAD

**Issue by tomlaf** [osTicket/osTicket#4300]
### Description

When the user is member of an organisation with "Primary Contacts: | Add to all tickets from this organization " activated ticket creation fail with this error : 

"Warning: Creation default object from epty value in (…)\include\class.thread.php on line 2128 Fatal error: Call to underfined method stdClass::set() in (…)\include\class.orm.php on line 2101.

All so the ticket look like it was created as the statistic show ticket creation (as the email was reprocess at each pull)

### Steps to Reproduce

1. Ass user to organisation and set organisation to "Primary Contacts: | Add to all tickets from this organization"
2. Create a ticket
3. It fail with the error
4. Remove option to all primary contact to the ticket 
5. create a ticket
6. it work!

**Expected behavior:** Ticket creation and primary contact added to it with out issues

**Actual behavior:** Ticket fail, but are still log in statistique (so I suspect they are partially created in the DB)

### Versions

Last 1.11.x from GitHub

On IIS 7 with PHP 

Web Server Software | Microsoft-IIS/8.5
MySQL Version | 5.7.11
PHP Version | 5.6.16
Schema Signature | 70921d5c3920ab240b08bdd55bc894c8

**Comment by JediKev** [comment]
@tomlaf

This branch isn’t complete yet and hasn’t even been released. Please close this Issue and only re-open if this issue persists after the official release.

Cheers.

**Comment by tomlaf** [comment]
Ok perfect I will close and reopen later on. But at least you know about it.
