### ISSUE TITLE
addExtraHeader call on null $ost upon login

### ISSUE THREAD

**Issue by shanept** [osTicket/osTicket#4306]
### Prerequisites

* [X] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [X] Do you have any errors in the PHP error log, or javascript console?
* [X] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [X] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

Upon logging into the staff section, I am presented with an error:

`PHP Fatal error: Call to a member function addExtraHeader() on null in /var/www/html/scp/staff.inc.php on line 104`

The fix is to add a `global $ost` before this line. Upon applying this fix the following error is logged:

`PHP Fatal error: Call to a member function isHelpDeskOffline() on null in /var/www/html/scp/staff.inc.php on line 120`.

The fix for this one is to add a `global $cfg` line before this line.

### Steps to Reproduce

1. `tail -f` web server error logs
2. Log into the staff portal.

**Expected behavior:**
Nothing should be logged in the error log.

**Actual behavior:**
See above

### Versions

osTicket Version | v1.10.1 (9ae093d) —  Up to date
Web Server Software | Apache/2.4.6 (CentOS) PHP/5.6.36
MySQL Version | 5.5.56
PHP Version | 5.6.36
CentOS 7.5.1804 (Core)

**Comment by JediKev** [comment]
@shanept 

I am definitely not seeing this issue...I tested on `v1.10.2`, `v1.10.3`, and `v1.11.0rc-1` (not out yet).

Cheers.

**Comment by shanept** [comment]
That's very bizarre, I had this on a fresh install of the above.

How close was your environment to mine? I'm thinking it may be a bizarre very specific issue related to my environment?
It is also slightly possible my PHP repo is not official CentOS, I shall check it out on Monday.

**Comment by JediKev** [comment]
@shanept

Basically the same as yours except the version. But the version shouldn’t matter because `1.10.2-1.10.3` is `1.10.1` with security patches.

Cheers.

**Comment by shanept** [comment]
@JediKev 

```
[root@rt ~]# php -v
PHP 5.6.36 (cli) (built: Apr 25 2018 10:02:39)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

I can confirm that this is from the Remi repository:

```
php.x86_64                          5.6.36-1.el7.remi                @remi-php56
php-cli.x86_64                      5.6.36-1.el7.remi                @remi-php56
php-common.x86_64                   5.6.36-1.el7.remi                @remi-php56
php-gd.x86_64                       5.6.36-1.el7.remi                @remi-php56
php-imap.x86_64                     5.6.36-1.el7.remi                @remi-php56
php-intl.x86_64                     5.6.36-1.el7.remi                @remi-php56
php-ldap.x86_64                     5.6.36-1.el7.remi                @remi-php56
php-mbstring.x86_64                 5.6.36-1.el7.remi                @remi-php56
php-mysqlnd.x86_64                  5.6.36-1.el7.remi                @remi-php56
php-opcache.x86_64                  5.6.36-1.el7.remi                @remi-php56
php-pdo.x86_64                      5.6.36-1.el7.remi                @remi-php56
php-pecl-apcu.x86_64                4.0.11-2.el7.remi.5.6            @remi-php56
php-pecl-jsonc.x86_64               1.3.10-2.el7.remi.5.6            @remi-php56
php-pecl-zip.x86_64                 1.15.2-1.el7.remi.5.6            @remi-php56
php-xml.x86_64                      5.6.36-1.el7.remi                @remi-php56
```

```
[remi-php56]
name=Remi's PHP 5.6 RPM repository for Enterprise Linux 7 - $basearch
#baseurl=http://rpms.remirepo.net/enterprise/7/php56/$basearch/
#mirrorlist=https://rpms.remirepo.net/enterprise/7/php56/httpsmirror
mirrorlist=http://cdn.remirepo.net/enterprise/7/php56/mirror
# NOTICE: common dependencies are in "remi-safe"
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-remi
```

Perhaps this may be part of the issue - different compilation flags.  
I can not determine the compilation flags from this binary, however.
