### ISSUE TITLE
Referral event is empty.

### ISSUE THREAD

**Issue by Micke1101** [osTicket/osTicket#4308]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

Event referred does not get logged properly as the enum filter is preventing due to a typo.

### Steps to Reproduce

1. Install osTicket **1.11 branch**
2. Open the default ticket.
3. Press the referral button.
4. Go to the refferal tab.
5. Select department.
6. Select maintanence.

The problems seems to be here: https://github.com/osTicket/osTicket/blob/1.11.x/setup/inc/streams/core/install-mysql.sql#L721

**Expected behavior:** [What you expected to happen]
A new event in the thread that describes the referral.

**Actual behavior:** [What actually happened]
An empty event line in the thread. (should empty events not be created?)

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.
![image](https://user-images.githubusercontent.com/22049466/40828123-0463e24a-6580-11e8-8c67-25ae7c3b4391.png)
(I know it says it's 1.8-git but it's actually https://github.com/osTicket/osTicket/tree/1.11.x c9322f5

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

**Comment by JediKev** [comment]
@Micke1101

The branch `v1.11.x` isn’t complete and doesn’t include all of the updates/fixes we have made for the version so please close this issue and only reopen if the issue appears in the official release.

Cheers.
