### ISSUE TITLE
Fatal error: Uncaught exception 'InconsistentModelException' 

### ISSUE THREAD

**Issue by helen2018rgt** [osTicket/osTicket#4318]
anyone have the idea how to solve this errors occurs? This errors occurs after i fill out the information (database name,....etc)> Doing stuff, please wait.....> then come out with this error. 

Fatal error: Uncaught exception 'InconsistentModelException' with message 'Unable to prepare query: Table 'D:\xampp\tmp\#sqlc80_32_0' is read only SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ost_RGT_2018_t1_staff_dept_access' AND TABLE_SCHEMA = DATABASE() ORDER BY ORDINAL_POSITION' in D:\xampp\htdocs\upload\include\class.orm.php:3134 Stack trace: #0 D:\xampp\htdocs\upload\include\class.orm.php(3189): MySqlExecutor->execute() #1 D:\xampp\htdocs\upload\include\class.orm.php(2932): MySqlExecutor->getRow() #2 D:\xampp\htdocs\upload\include\class.orm.php(276): MySqlCompiler->inspectTable('ost_RGT_2018_t1...') #3 D:\xampp\htdocs\upload\include\class.orm.php(228): ModelMeta->inspectFields() #4 D:\xampp\htdocs\upload\include\class.orm.php(2702): ModelMeta->getFieldNames() #5 D:\xampp\htdocs\upload\include\class.orm.php(1393): MySqlCompiler->compileSelect(Object(QuerySet)) #6 D:\xampp\htdocs\upload\include\class.orm.php(1761): QuerySet->getQuery() #7 D:\xampp\htdocs\upload\include\class.orm.php(1458): Mo in D:\xampp\htdocs\upload\include\class.orm.php on line 3134

**Comment by JediKev** [comment]
@helen2018rgt 

Make sure your MySQL installation is owned by mysql user and group. Then restart MySQL and try again. This link will help you:
https://stackoverflow.com/questions/17629407/mysql-error-1036-table-is-read-only/35741325

Cheers.
