### ISSUE TITLE
Upgrade from v1.10.2 to v1.10.3 - wrong Version number

### ISSUE THREAD

**Issue by vollkommenIrrelevant** [osTicket/osTicket#4320]
Hello,
after upgrade from v1.10.2 to v1.10.3 osticket shows on Settings->System "Version v1.10.8". What's going wrong?
regards

**Comment by ntozier** [comment]
Well 1.10.2 hasn't technically been released yet... and 1.10.3 certainly hasn't either.

Official releases are done here:
http://osticket.com/download

**Comment by vollkommenIrrelevant** [comment]
Official releases should be here:
[https://github.com/osTicket/osTicket/releases](https://github.com/osTicket/osTicket/releases)
[https://help.github.com/articles/creating-releases/](https://help.github.com/articles/creating-releases/)

**Comment by JediKev** [comment]
@vollkommenIrrelevant 

We cut them here first but push them to the website for Official Releases.

Cheers.

**Comment by ntozier** [comment]
@vollkommenIrrelevant and i would also point out that your links do not have the version taht you say that you upgraded to...

**Comment by vollkommenIrrelevant** [comment]
![grafik](https://user-images.githubusercontent.com/25504254/41474108-6b8c9296-70bb-11e8-928b-3c59c9129c8e.png)

**Comment by vollkommenIrrelevant** [comment]
something new about this issue? A possibility would be a info that v.1.10.3. is currently in development or something else...

**Comment by vollkommenIrrelevant** [comment]
@ntozier ntozier
new Version released

**Comment by ntozier** [comment]
![2018-09-12_0925](https://user-images.githubusercontent.com/1315768/45427830-e5ecec00-b66d-11e8-8063-98b7c5cc265f.png)

1.10.4 is current.

**Comment by vollkommenIrrelevant** [comment]
sherlock holmes.... That's why I closed the ticket.
