### ISSUE TITLE
Tickets Limit ticket access

### ISSUE THREAD

**Issue by iHunt101** [osTicket/osTicket#4321]
I checked the 

> Limit ticket access to ONLY assigned tickets

in agent settings and the function to restrict not her tickets works fine. 
Here is the thing. If agent change the link in the browser like this from

> scp/index.php or scp/tickets.php

to

> scp/tickets.php?id=7

they will get a full access in a certain ticket by changing the id number. Is this really a function of the osT or is it forgotten to secure tickets limit access?

**Expected behavior:** All tickets will not display by a certain agent which is restricted to access the tickets.

**Actual behavior:** All agents that will change the link will have a full access to any tickets..

### Versions

v1.10
Windows 10
Chrome Latest

**Comment by JediKev** [comment]
@iHunt101 

I have made a pull request for this, so it will most likely be merged in the `v1.11.0rc-1` release.

Cheers.

**Comment by iHunt101** [comment]
Hi @JediKev ,

All of the agents can see tickets using the link. They are not Department manager.

**Comment by perryk** [comment]
I think I saw this yesterday myself however I was just randomly testing stuff in a dev setup.

I can test it out on a more stable instance if you would like further verification.

**Comment by iHunt101** [comment]
Yes they are part of the team. I an using v1.10

**Comment by JediKev** [comment]
@iHunt101 

Then that's why...it's assigned to the team and everyone in the Team has access..

Cheers.

**Comment by ntozier** [comment]
This is not a feature in osTicket at this time.  If you want only the person who its assigned to to see it (walled garden) then you would need to create departments to transfer the tickets to that only that single agent has access to.  I would not recommend it.

**Comment by JediKev** [comment]
@iHunt101 

We do have this setting under every Agent's account settings (**Admin Panel > Agents > Agents > click name > Status and Settings > Limit ticket access to ONLY assigned tickets**):
<img width="330" alt="screen shot 2018-07-27 at 08 54 45" src="https://user-images.githubusercontent.com/11823401/43324990-170ce5b4-917b-11e8-91a0-04a6c22b6d59.png">

Cheers.

**Comment by perryk** [comment]
I'm not able to replicate this now, most likely I was using an account which had more access than I thought.

I see "access denied" where I expect it.

**Comment by iHunt101** [comment]
Hi @JediKev,
I already try "Limit ticket to ONLY assigned tickets", but i can still see the ticket by adding ticket id at the end of the link. I think @ntozier  was right, this is not a feature of osTicket this time.
