### ISSUE TITLE
Add new field in ticket

### ISSUE THREAD

**Issue by Rujinraj** [osTicket/osTicket#4323]
Hello Team,

I am using the below Version of OS ticket. Is there any way to add another column(ticket status like open,resolved,closed) in the main page of open tickets.

As of now it shows the below field now. I need to add/remove another field. Help me.

Number | Last Updated | Subject | From | Priority | Assigned To

osTicket Version | v1.10.2 (8c848b5) 
Web Server Software | Microsoft-IIS/8.5
MySQL Version | 5.7.21
PHP Version | 5.6.32

![osticket](https://user-images.githubusercontent.com/35999582/41763574-300aadd2-761c-11e8-8eef-17d5c2e84653.JPG)

**Comment by JediKev** [comment]
@Rujinraj 

Custom Columns/Custom Queues is coming in `v1.11.0rc-1` (soon). Stay tuned!

Cheers.

**Comment by Rujinraj** [comment]
Thanks
