### ISSUE TITLE
Language pack locale codes mismatch 

### ISSUE THREAD

**Issue by stevland** [osTicket/osTicket#4325]
I have confirmed that this issue is affecting other users and have reproduced it using an install of the `develop` branch.

I cannot find any indication that this bug has been reported anywhere else.

In **Agent Panel > Dashboard > Information** the locale code for the first language is displayed next to the second language, etc. 

![Image of screenshot](https://osticketawesome.com/wp-content/uploads/aaac.png)

I believe this issue is independent of any specific environment, but for the record I am using

Apache / CentOS 7
PHP 5.6.36
Chrome (up-to-date)

**Comment by JediKev** [comment]
@stevland

This should fix your issue: https://github.com/osTicket/osTicket/pull/4326

Cheers.

**Comment by stevland** [comment]
Amazing response time @JediKev.

I have no experience with GitHub. Should your fix already be integrated into the `develop` branch? Because, if yes, then the issue persists.

[Here is a fresh install](https://osticketawesome.com/develop/scp/system.php) of `develop` with unmodified language packs from the source. (username: demo  password: demodemo).

**Comment by JediKev** [comment]
@stevland 

No it will be merged before a next major release. You will have to either manually make the changes to your installation _(your best bet)_, if your codebase is a git repo then you can pull the pull request from github and merge it into your codebase, or you can just wait until it is merged into a version and officially released.

Cheers.

**Comment by stevland** [comment]
Thank you for the explanation, @JediKev.
