### ISSUE TITLE
Arab language pack flag mismatch

### ISSUE THREAD

**Issue by stevland** [osTicket/osTicket#4327]
Within the current releases and develop branch the Arab language pack, when installed, is represented throughout osTicket with the Argentinian flag.

In other words, the html as it is currently written uses the following class for both Arab language (ar.phar) and Spanish, Argentina (es_AR.phar):

`<span class="flag flag-ar"></span>`

**Comment by JediKev** [comment]
@stevland 

So what you do is you un-install the language pack real quick and then you rename the language pack to be `ar_` + language code (all caps) + `.phar`. For example, if you want the Qatar flag to show then you would name the language pack `ar_QA.phar` and then install it. If you want the Saudi Arabia flag to show you would rename the language pack to `ar_SA.phar`.

If you need a list of language codes then please use this link and look at the `LCID String` column:
https://www.science.co.il/language/Locale-codes.php

Cheers.

**Comment by stevland** [comment]
That's an interesting tip... it helps me understand how locale codes work.

But I had already fixed this for my own purposes through CSS. 

`.flag.flag-ar {
    [argentina flag]
}`
`a[href="#translation-ar"] .flag.flag-ar {
    [saudi arabia flag]
}`

My only purpose in submitting this ticket was to help osTicket development.

As the Arabic translation is actually _Saudi Arabian_ Arabic, wouldn't you want the SA flag to show by default without any end-user tweaks?

Again, I'm only trying to help. Feel free to close this issue either way.

**Comment by JediKev** [comment]
@stevland 

Yes, what I suggested is just a temporary fix until we add the proper locales ourselves in the future.

Cheers.

**Comment by stevland** [comment]
Gotcha!
