### ISSUE TITLE
ERROR 500 when filtring tickets by a specific date

### ISSUE THREAD

**Issue by ahmedhannachi** [osTicket/osTicket#4328]
When i tried to filter tickets using a specific date using the advanced form, the application responds only with 500 error.

**Comment by ntozier** [comment]
Version of osTicket?
Version of PHP?
Webserver and Version?

**Comment by JediKev** [comment]
@ahmedhannachi 

This has been addressed in version `1.11.0rc-1` which will be released soon. Please stay tuned!

Cheers.
