### ISSUE TITLE
Updating Email address..~LOADING Only~

### ISSUE THREAD

**Issue by johnkalangha** [osTicket/osTicket#4329]
Hello guys, need help.. i use import in creating user, but suddenly I forgot to include one email address in csv file... when i need to insert/add email of that user it always loading.. no processing happen.. any solution?? thanks in advance..

**Comment by JediKev** [comment]
@johnkalangha 

Are you talking about updating an email in **Admin Panel > Emails > Emails**? If so, this indicates an error with the credentials or the connection. Please ensure the credentials are indeed correct and you can access the ports on your server. If every thing checks out okay, please wait for the loading to crash and look for any errors. If you do not find any errors on the page please check your Apache/PHP error logs for any related errors.

Cheers.

**Comment by JediKev** [comment]
@johnkalangha 

Please check your Apache/PHP error logs for any related errors and post them here.

Cheers.

**Comment by JediKev** [comment]
@johnkalangha 

I have created a pull request that should fix the import with no email issue:
https://github.com/osTicket/osTicket/pull/4330

Now if you import Users via CSV and there is no email for one it will fail out and let you know beforehand.

**Note:**
For the current users with no emails, you will have to delete them and re-add them.

Cheers.

**Comment by johnkalangha** [comment]
thanks for this sir.. god bless

**Comment by johnkalangha** [comment]
hello sir, when i try to import a csv file its always say that email and name must be not be empty... although may csv file are filled with name and email till 40th row of excel.. i think when i change the code it read all rows of excel?

**Comment by JediKev** [comment]
@johnkalangha

Of course it reads the whole file. The CSV file should ONLY contain users and all of them have to have name and email.

Cheers.
