### ISSUE TITLE
Cross site scripting,Blind sql injection attack found in osticket

### ISSUE THREAD

**Issue by asha42** [osTicket/osTicket#4331]
[mission.pdf](https://github.com/osTicket/osTicket/files/2174855/mission.pdf)

**Comment by JediKev** [comment]
@asha42 

Thank you for the report. Unfortunately almost all of the things it's complaining about are things that Server Admins should do or things that should be ignored (although there are a few issues we can look into). I have attached a document containing my response to each warning. Below is a summary of the attached document.


### Attachment
[xss_response.txt](https://github.com/osTicket/osTicket/files/2176752/xss_response.txt)



### Attachment Summary

**Things We Need To Look Further Into:**
- [High] Parameter System Call Code Injection _**(Fabric.js; not us but we will see how they addressed this)**_
- [Low] Unsafe third-party link (target="_blank") _**(not really necessary but will look into it just in case)**_
- [Medium] Cross-Site Request Forgery _**(look into validating the referrer)**_
- [Low] Unsafe third-party link (target="_blank") _**(add 'rel="noopener noreferrer"' to the links with 'target="_blank"')**_

**Things Server Admins Should Do:**
- [High] Unencrypted Login Request _**(Configure an SSL certificate for your server and force all traffic/requests to use HTTPS.)**_
- [Medium] Authentication Bypass Using HTTP Verb Tampering _**(Configure your server to allow only required HTTP methods.)**_
- [Low] Missing "X-XSS-Protection" header _**(Configure your server to use the "X-XSS-Protection" header.)**_
- [Low] Missing Cross-Frame Scripting Defence _**(Configure your server to use the "X-Frame-Options" header.)**_
- [Low] Missing "Content-Security-Policy" header _**(Configure your server to use the "Content-Security-Policy" header.)**_
- [Low] Missing "X-Content-Type-Options" header _**(Configure your server to use the "X-Content-Type-Options" header.)**_

**Things To Ignore:**
- [Low] Permanent Cookie Contains Sensitive Session Information
- [Information] Email Address Pattern Found _**(osTicket is an email-based system so of course you will find email addresses in some responses.)**_
- [Low] Autocomplete HTML Attribute Not Disabled for Password Field _**(Some people like password autofill and some people don’t.)**_
- [Information] Internal IP Disclosure Pattern Found _**(Don’t use an IP for your helpdesk url.)**_
- [Low] Direct Access to Administration Pages _**(The response is always “302” NOT 200 like this PDF says, and nothing appears in the response or curl request so everything here is fine.)**_
- [Information] HTML Comments Sensitive Information Disclosure _**(There is no sensitive information in the comments.)**_
- [Information] Application Error _**(500 errors should not display sensitive data.)**_
- [High] Cross-Site Scripting _**(They are all properly scrubbed/parsed.)**_

**Things Already Addressed:**
- [Low] Missing HttpOnly Attribute in Session Cookie _**(This has already been addressed in `v1.10.2`)**_


I hope this helps.

**Comment by asha42** [comment]
Thank you for your response. It is really helpful for me, it is requested to kindly check the following pdf report also if possible from your side. 
[Mission_Admin_L2_24may2018 Security Report.pdf](https://github.com/osTicket/osTicket/files/2178851/Mission_Admin_L2_24may2018.Security.Report.pdf)
