### ISSUE TITLE
Problem assigning a department to an email

### ISSUE THREAD

**Issue by scellu** [osTicket/osTicket#4333]
Hi, I notice that I can't assign a department with dept_Id greater then 255 to an email account. This is probably because the dept_Id in email table is a TINYINT(3) instead of INT(11) as declared in department table. 

Regards, 
Alessandro

osTicket Version | v1.10 (901e5ea)
Web Server Software | Apache/2.2.15 (CentOS)
MySQL Version | 5.5.47
PHP Version | 5.6.30

**Comment by ntozier** [comment]
Sounds like you want to change your database structure like you indicated.
