### ISSUE TITLE
Installer footer: Copyright © 2013

### ISSUE THREAD

**Issue by stevland** [osTicket/osTicket#4339]
I just noticed that the current (v1.10.1) installer says 

Copyright © 2013 osTicket.com

I hope I don't seem nitpicky for pointing this out... I just don't think it would inspire a lot of confidence in a new user.

**Comment by JediKev** [comment]
@stevland

Oops. On it. Thanks!!

Cheers.

**Comment by protich** [comment]
@stevland - we install like it is  2013!  ;) - On a serious note, thanks you for the comment, pull request addressing the issue merged.
