### ISSUE TITLE
Topic Name

### ISSUE THREAD

**Issue by johnkalangha** [osTicket/osTicket#4345]
Can anyone help me how to increase the character value of the topic name? by default it is only 32 digit.. hot to increase that number by 40 character?
thanks in advance

**Comment by JediKev** [comment]
@johnkalangha 

In the database:
`ost_help_topic` table -> `topic` column

Please note that once you change the `topic` column structure it will change for ALL `topic` column values. BE CAREFUL.

Cheers.

**Comment by johnkalangha** [comment]
Thanks Boss
