### ISSUE TITLE
v1.11.0-rc1 When open ticket from SCP, white page at answer

### ISSUE THREAD

**Issue by vpetre** [osTicket/osTicket#4347]
### Prerequisites

* [X ] Do you have any errors in the PHP error log, or javascript console?

### Description

When you create a ticket from SCP on behalf of other person and try to replay to it, its ending into a white page. 

Error returned on php_error_log : 

PHP Fatal error:  Call to a member function getId() on a non-object in D:\xampp\htdocs\include\class.thread.php on line 2864

### Steps to Reproduce

1. Agent Panel 
2. New Ticket
3. Create the ticket and try to post replay ( internal note is working ) not able to answer.

**Expected behavior: To post answer
**Actual behavior: Show a white Page.

### Versions

v1.11.0-rc1 (e321982)  on Firefox 52.9.0 

Apache/2.4.29 (Win32) OpenSSL/1.0.2n PHP/5.5.38

**Comment by vpetre** [comment]
Issue fixed by

**Comment by vpetre** [comment]
Issue seems to be generated by    **$vars['pid'] = $this->getLastMessage()->getId();**
`function addResponse($vars, &$errors) {
        $vars['threadId'] = $this->getId();
        $vars['userId'] = 0;
	$vars['pid'] = $this->getLastMessage()->getId();`

**Comment by JediKev** [comment]
@vpetre 

I have addressed this issue. It should be merged and repackaged soon. In the meantime, below is a diff file containing the changes to fix this issue:
[getId.txt](https://github.com/osTicket/osTicket/files/2211663/getId.txt)

Cheers.

**Comment by brzmarou** [comment]
Wersja osTicket | v1.11.0-rc1 (e321982) —  Aktualny
-- | --
Oprogramowanie serwera WWW | Apache
Wersja MySQL | 5.5.58
Wersja PHP | 7.0.30-1+0~20180505045929.18+jessie~1.gbpcfecb9

didn't work... :/
