### ISSUE TITLE
email content messed up 

### ISSUE THREAD

**Issue by jabrugger** [osTicket/osTicket#4348]
Please check the following screenshot
![imagen](https://user-images.githubusercontent.com/21174632/42956913-9148566c-8b57-11e8-8c6e-620b29006829.png)
The original reply was:
![imagen](https://user-images.githubusercontent.com/21174632/42956961-aa115784-8b57-11e8-8dd6-35bafcc88adb.png)
Reply email code:
![imagen](https://user-images.githubusercontent.com/21174632/42957082-f8335f70-8b57-11e8-9e3d-2f3e2de2f2f7.png)

OSTicket 1.10.4 on Linux (PHP 7)

This issue does not appear in previous 1.10.1

**Comment by JediKev** [comment]
@jabrugger 

Please test this with `1.10.3` instead of `1.10.4`. Maybe it's something with the sanitizing update in `1.10.4`.

Cheers.

**Comment by JediKev** [comment]
@jabrugger 

Okay, that means it's an issue with 1.10.4. Could you please retest this on 1.10.4 but this time make the below changes first:
<br>
Open `include/class.thread.php` and change the following line:
```
return  Format::htmlchars(Format::stripEmptyLines(parent::getClean()), true);
```
to:
```
return  Format::stripEmptyLines(parent::getClean());
```

Once you do this Save Changes, retest and get back to me. If that's the issue then I will debug this further.
<br>

Also, could you post that raw email + headers here (stripping out any sensitive information) so we can test internally?

Cheers.

**Comment by danielw0581** [comment]
@JediKev

I am finding a similar issue on 1.11.0-rc1. HTML based emails maintain their format but text based emails make one long line and do not hold carriage returns. I have not had a chance to try the above yet but will do so tomorrow.

**Comment by jabrugger** [comment]
@JediKev Tested the proposed change wirh 1.10.4 and it works fine. 
In my original report I´ve posted the raw email. If you want or need another email, please tell me which one.
Thanks!

**Comment by JediKev** [comment]
@jabrugger 

But it's an image...I can't copy an image lol I need the text version of it so I can copy it and test it.

Cheers.

**Comment by jabrugger** [comment]
@JediKev Here is the complete message (as text ;) ) sent to the support address. if I can help in something else just tell me.

```
From - Fri Jul 20 08:38:36 2018
X-Mozilla-Status: 0001
X-Mozilla-Status2: 00800000
X-Mozilla-Keys:                                                                                 
Subject: Re: [#645735] test
To: Soporte <soporte@dasu.com.ar>
References: <Bfr22NV-LDt0M-DwEAANGTAADMRgAAVTawfsga-soporte@dasu.com.ar>
From: =?UTF-8?Q?Jorge_Andr=c3=a9s_Brugger?= <jbrugger@gmx.net>
Message-ID: <be809737-955a-bdee-bfa9-11e5fdeb6f0f@gmx.net>
Date: Fri, 20 Jul 2018 08:38:32 -0300
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko/20100101
 Thunderbird/52.9.1
MIME-Version: 1.0
In-Reply-To: <Bfr22NV-LDt0M-DwEAANGTAADMRgAAVTawfsga-soporte@dasu.com.ar>
Content-Type: text/plain; charset=utf-8; format=flowed
Content-Transfer-Encoding: 8bit
Content-Language: es-AR

one more reply


El 20/07/2018 a las 08:37 a.m., Soporte escribió:
> line 1
> line 2
> line 3
>
> ----------------------------------------
> Ver el ticket online: 
> http://extranet.dasu.com.ar/soporte/view.php?auth=o1xb2aqaagyfeaaaiwAzl1Mm04MLug%3D%3D
>
> Jorge Andrés Brugger
> DASU Informática
>
> --
> Antes de imprimir este mensaje, piense si es verdaderamente necesario 
> hacerlo.

-- 
Jorge Andrés Brugger

```

**Comment by nsl-94** [comment]
Hello.

I had the same problem as @danielw0581 in 1.11.0-rc1


@JediKev 
used your solution in 1.11.0-rc1 and it treats HTML formated e-mails and text formated e-mails correctly.

Thank you
Nuno

**Comment by JediKev** [comment]
@jabrugger  @nsl-84

So the official fix for this issue is here: https://github.com/osTicket/osTicket/pull/4355

I hope this helps! Cheers.
