### ISSUE TITLE
DB error after upgrade to 1.11.0 rc1

### ISSUE THREAD

**Issue by rebeluca** [osTicket/osTicket#4349]
After upgrade to version 1.11.0 rc1, I get the following DB error:
```
[CREATE TABLE IF NOT EXISTS `ost_user__cdata` (PRIMARY KEY (user_id)) DEFAULT CHARSET=utf8 AS SELECT entry.`object_id` as `user_id`, MAX(IF(field.id='1', coalesce(ans.value_id, ans.value), NULL)) as `email`, MAX(IF(field.id='2', coalesce(ans.value_id, ans.value), NULL)) as `name`, MAX(IF(field.id='3', coalesce(ans.value_id, ans.value), NULL)) as `phone`, MAX(IF(field.id='4', coalesce(ans.value_id, ans.value), NULL)) as `notes` FROM ost_form_entry entry JOIN ost_form_entry_values ans ON ans.entry_id = entry.id JOIN ost_form_field field ON field.id=ans.field_id WHERE entry.object_type='U' GROUP BY entry.object_id] Statement violates GTID consistency: CREATE TABLE ... SELECT.

 ---- Backtrace ----
 #0 (root)/include/mysqli.php(199): osTicket->logDBError('DB Error #1786', '[CREATE TABLE I...')
 #1 (root)/include/class.dynamic_forms.php(293): db_query('CREATE TABLE IF...')
 #2 (root)/include/class.dynamic_forms.php(286): DynamicForm::buildDynamicDataView(Array)
 #3 (root)/include/staff/users.inc.php(5): DynamicForm::ensureDynamicDataView()
 #4 (root)/scp/users.php(197): require('/www/helpdesk.l...')
 #5 {main}
```
It seems to be related to replication configuration. Since I'm using Google Cloud Platform DB replication, I can't change anything on that side.

**Comment by JediKev** [comment]
@rebeluca 

Hmm... I have not run across this error and I upgraded all the way from `1.6 ST` to `1.11.0rc-1`. Could you try running the Upgrade again to see if maybe it was just a fluke the first time?

Cheers.

**Comment by rebeluca** [comment]
Hello,
I've tried to update it again, and I did not get any error. Maybe you are right, it's just a fluke. Sorry for having opened an issue.

Luca

**Comment by the-binder** [comment]
I can also state that I upgraded to 1.11.0 RC1 and did not get DB errors.

**Comment by Panduin** [comment]
@ntozier i tried your solution but when there was no `ost_user__cdata` table and i tried to search for a User i got an DB Error and could not find anything. Only creating a User solved it for me.

I also use http passthru & ldap Plugins. Dont know if this has anything to do with this.

**Comment by ntozier** [comment]
I said to truncate the table, not drop the table.
