### ISSUE TITLE
Users Information bug

### ISSUE THREAD

**Issue by johnkalangha** [osTicket/osTicket#4357]
Good Day, anyone help me regarding in configuration of forms..
in users information i disable the editable  
![users tranx](https://user-images.githubusercontent.com/30627667/43042796-07b0c8fe-8db8-11e8-9e95-afa16df13495.PNG)

but in profile in users.. it can edit and update.. how to disable that?
![users tranx](https://user-images.githubusercontent.com/30627667/43042805-44d9faf2-8db8-11e8-98af-b3207a62826c.PNG)

Thanks in Advance

**Comment by JediKev** [comment]
I have a pull request for this here: https://github.com/osTicket/osTicket/pull/3888

Unfortunately it doesn’t allow you to disable the Full name or email address as they are Required fields and need to be there for the POST.

Cheers.

**Comment by johnkalangha** [comment]
hello sir, i already did you're instruction but still i will allow the users to update there account even though they have no privilege/uncheck the Editable in the form..

**Comment by johnkalangha** [comment]
up.. please help me sir
