### ISSUE TITLE
API information missing

### ISSUE THREAD

**Issue by cervedgroup** [osTicket/osTicket#4358]
osTicket (v1.10.1)
how can we add response in a ticket using API (or other method from external systems?), i cannot find any documentation about using APIs

thank you

**Comment by cervedgroup** [comment]
@JediKev 
if i insert a record in that table (like a reply), also the mail was sent to the user ?

**Comment by JediKev** [comment]
@cervedgroup 

No...you'd have to trigger that yourself.

Cheers.

**Comment by cervedgroup** [comment]
@JediKev thank you!!
