### ISSUE TITLE
Understanding of active branches and development

### ISSUE THREAD

**Issue by perryk** [osTicket/osTicket#4365]
I'm having a little difficulty understanding the use of the currently active branches and how they are being used for development.

Perhaps someone can help me clear this up a little, I'm aware I likely don't need to know all the details and that likely it is all ok and working as intended by the devs.

The main concern I have is when I do an initial "git clone" which gives the "develop" branch and I do a "less WHATSNEW.md" it has entries only up to 1.10.2 .

I can checkout the "v1.10.4" tag, this takes me to commit ```035fd0a``` , here I can see the WHATSNEW.md file shows notes for 1.10.4 .

From here, however, I am having trouble applying the latest PRs such as 4363, this fails to merge due to I assume it wanting to bring in everything now added to the develop branch after the v1.10.4 tag.

It fails to merge a bunch of PRs until I go back to 4351, interestingly this is the last PR merged into develop, and when it merges it does bring in a whole bunch of stuff, not just the PR itself which is a single line change relating to the copyright in the footer.

```
21:59:19 [osticket@osticket-dev:~/osTicket] 035fd0a* ± git pull --no-edit origin refs/pull/4351/head
From https://github.com/osTicket/osTicket
 * branch            refs/pull/4351/head -> FETCH_HEAD
Auto-merging include/class.forms.php
Merge made by the 'recursive' strategy.
 include/ajax.orgs.php    |  2 +-
 include/ajax.tickets.php |  2 +-
 include/ajax.users.php   |  2 +-
 include/class.forms.php  | 10 +++++-----
 include/class.list.php   |  2 +-
 scp/js/scp.js            |  2 ++
 setup/inc/footer.inc.php |  2 +-
 7 files changed, 12 insertions(+), 10 deletions(-)
```

Now, after this I can start applying the newer PRs such as 4363 and still retain the notes on 1.10.4 in the WHATSNEW.md file.

Maybe I should always be applying PRs from oldest to newest anyway ? 

Maybe using git pull the way I have been doing so isn't right ?

Maybe there is something to do with the newer branches "1.10.x and 1.11.x" which I should be using ?

I've noticed "develop-next" branch is active now also.

Hopefully just a little bit of info will help me along here and get me going again.

Cheers.

**Comment by JediKev** [comment]
@perryk 

`develop` should be inline with the latest `1.10.x` release (`1.10.4`) plus a few extra commits (minus the release notes).

`develop-next` should be inline with the latest `1.11.x` release (`1.11.0rc-1`) plus a few extra commits.

If you want to test specific versions only then you can use the release tags.

If a pull request is specific to `1.11.x` then you should use `develop-next` to test. If a pull is made for `1.10.x` you can test it on `develop` first then `develop-next`.

Cheers.

**Comment by perryk** [comment]
Great, thanks for the info.

I'll give develop a shot and just not worry about the release notes, if that has any merging troubles perhaps I do need to consider the order I'm doing the pulls to bring in the different PRs.

**Comment by JediKev** [comment]
@perryk 

Btw `develop` has the release notes now 😉

Cheers.

**Comment by perryk** [comment]
Oh awesome, thanks.

Actually, it is great to see bunches of your PRs all being merged in, it is making things cleaner and saving me trouble on this end :)
