### ISSUE TITLE
Send user password reset email and send user activation email don't work

### ISSUE THREAD

**Issue by nsl-94** [osTicket/osTicket#4366]
Hello all.

Whenever I try to send the _"user password reset email"_ or the _"user activation email"_, I allways get a blank page (in Chrome and in Firefox), and the user never gets the email.

When I try to make the same in Edge or in Internet Explorer I get this message:

![image](https://user-images.githubusercontent.com/10809276/43266698-f3271328-90e3-11e8-8265-e76a4548960a.png)

Although I have the osTicket Default Log level in debug, there are no errors in the log.

I don't know how to check if I have php errors in my system.

My configuration is the following:

![image](https://user-images.githubusercontent.com/10809276/43266070-50a35b94-90e2-11e8-964f-4725653e6fdd.png)

![image](https://user-images.githubusercontent.com/10809276/43266115-6af9f2d2-90e2-11e8-96b7-38f63c5fb472.png)

Thank you
Nuno Lopes

**Comment by JediKev** [comment]
@nsl-94 

Thank you...on it!

Cheers.

**Comment by ntozier** [comment]
While you wait for Kevin to try to replicate the issue:
Please update to PHP 5.6.
Look at your php.ini and determine where your error logs are and see whats there.

Are running any plugins?
How do you have email configured?

**Comment by nsl-94** [comment]
Hello ntozier.

I will update php to 5.6, in a couple of hours. Can't do it right now, sorry :)

The only pluggin I am using is attachments on the filesystem.
I Have several accounts configured in my instalation (notifications and departments) all of them working correctly when sending and recieving emails.

Thank you
Nuno

Thank you again.

Nuno

**Comment by JediKev** [comment]
@nsl-94 

I have made a pull request to address this issue:
https://github.com/osTicket/osTicket/pull/4368

Please test this and get back to me. 

Cheers.

**Comment by nsl-94** [comment]
Hello @JediKev 

I've tested and both _user password reset email_ and _send user activation email_ work correctly.

I will close this issue now.

Thanks for all the support
Nuno Lopes
