### ISSUE TITLE
BUG: User Responses via Web Portal Create Second Bounce Email

### ISSUE THREAD

**Issue by mikshepard** [osTicket/osTicket#4370]
### Description

When a ticket is created and user responds to an agent via the web portal, a second email alert is created with a non-existant destination (ex. ""@localhost).  The message still gets posted to the agent ticket thread, and the agent still gets notified of the message.  In our case, out spam filter catches this second email alert due to the bunk recipient email sent by osticket and bounces it back, causing osticket to create a new ticket from the bounce-email.  Email responses from users do not do this, they function as expected.

Here is the mail log, showing osticket generating a second email to "@localhost.osticket.testdomain.org", which should be "bobj@testdomain.org" (never localhost) and is properly sent at the same time:

> 8179-Jul 26 16:00:02 osticket postfix/smtp[23590]: B7D5087BD9: to=<bobj@testdomain.org>, relay=mail.testdomain.org[X.X.X.X]:25, delay=0.16, delays=0.05/0.06/0/0.05, dsn=2.6.0, status=sent (250 2.6.0 <BetXbNk-vqHNH-EwAAAGr4AAD5HwAAU77Fyb6z-osticket@testdomain.org> [InternalId=12451110191285, Hostname=MX-01.testdomain.org] Queued mail for delivery)
> 8542:Jul 26 16:00:02 osticket postfix/smtp[23589]: B2A5787BD7: to=<@localhost.osticket.testdomain.org>, orig_to=<@localhost>, relay=mail.testdomain.org[X.X.X.X]:25, delay=0.2, delays=0.02/0.04/0/0.13, dsn=2.6.0, status=sent (250 2.6.0 <BetXbNk-8ewa3-AAAAAGr4AAD5HwAATTgCc48T-osticket@testdomain.org> [InternalId=12451110191284, Hostname=MX-01.testdomain.org] Queued mail for delivery)

Here is the header from our spam filter, showing the non-existant reciepient created.

> Received: 	from mx.testdomain.org (X.X.X.X) by
> mx.testdomain.org (X.X.X.X) with Microsoft SMTP Server (TLS) id
> 15.0.1367.3; Thu, 26 Jul 2018 16:00:14 -0500
> Received: 	from osticket.testdomain.org (X.X.X.X) by
> mail.testdomain.org (X.X.X.X) with Microsoft SMTP Server id
> 15.0.1367.3 via Frontend Transport; Thu, 26 Jul 2018 16:00:14 -0500
> Received: 	from localhost (osticket.testdomain.org [X.X.X.X])
> by osticket.testdomain.org (Postfix) with ESMTP id 48967806A9
> for <""@localhost>; Thu, 26 Jul 2018 16:00:14 -0500 (CDT)
> Content-Type: 	multipart/alternative;
> boundary="=_8704298ba03c711cebcce4b69ae90df8"
> MIME-Version: 	1.0
> From: 	Support <osticket@testdomain.org>
> Subject: 	Re: Testing Something for Bob J. Again [#758061]
> Date: 	Thu, 26 Jul 2018 21:00:14 +0000
> Message-ID: 	<BetXbNk-HHbqF-AAAAAIv4AAADIAAATefuJ5aZ-osticket@testdomain.org>
> X-Mailer: 	osTicket Mailer
> To: 	Undisclosed recipients:;
> Return-Path: 	osticket@testdomain.org

Please let me know if you need more info:

### Steps to Reproduce

1. User creates a ticket
2. Agent responds to ticket asking a question
3. User responds to ticket via web portal
4. Email alert is created to fake email address, as well as agent.

**Expected behavior:** [What you expected to happen]

Agent is notified of user response.

**Actual behavior:** [What actually happened]

Agent is notified of user response, and second email is generated without a percipient and sent out.

### Versions

1.8-git (b7339959)  (git v1.11.x)

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

Debian jessie, php 5.6.36, mysql 5.7.22

**Comment by mikshepard** [comment]
@JediKev , I had not.  After pulling the commit, initial tests seem good!  I'll hammer the system in the morning and let you know for sure this is resolved.   Thanks for the quick reply.

**Comment by mikshepard** [comment]
@JediKev Issue still remains, logs are showing this same.  If it helps, this issue was not present on a pull I did from 7/4/18.

**Comment by JediKev** [comment]
@mikshepard 

Okay will have to dig deeper!

Cheers.

**Comment by JediKev** [comment]
@mikshepard 

Could you post a screenshot of your **Admin Panel > Emails > Templates > click template set currently being used > Response/Reply Template**?

Also, have you tried pulling from the latest `develop-next` and testing with that? I used to be able to replicate this issue but since I pulled from `develop-next` today and retested, I cannot get it to replicate anymore.

Cheers.

**Comment by mikshepard** [comment]
Also, this issue was not present on a git pull from 7/4.

**Comment by JediKev** [comment]
@mikshepard 

Here is the pull request that should fix your issue:
https://github.com/osTicket/osTicket/pull/4380

Please test and let me know! Cheers.

**Comment by mikshepard** [comment]
@JediKev 

Looks like that did it, the issue appears to be gone now.  

Thanks for fixing this!
-Mike

**Comment by iHunt101** [comment]
@JediKev  does this PR also applies with other release other that 10.4?

**Comment by JediKev** [comment]
@iHunt101

Yes, it’s made for the `1.11.x` and `develop-next` branch (v1.11.0rc-1).

Cheers.
