### ISSUE TITLE
Help Topic as a Top Parent 

### ISSUE THREAD

**Issue by johnkalangha** [osTicket/osTicket#4371]
Good Day, May I request regarding in this customization in HELP TOPICS
Please see the Picture if it is possible?
![1](https://user-images.githubusercontent.com/30627667/43303022-6b714b16-91a0-11e8-90d0-447763522ad9.PNG)
![4](https://user-images.githubusercontent.com/30627667/43303021-6b703fd2-91a0-11e8-880b-67af4a09253c.jpg)

**Comment by ntozier** [comment]
Thank you for the Feature Request.  I have added it to the Feature Request document I maintain for the devs.
