### ISSUE TITLE
Redactor not clickable in Ticket filters

### ISSUE THREAD

**Issue by iHunt101** [osTicket/osTicket#4372]
![filter](https://user-images.githubusercontent.com/16589622/43305452-6f1e3b20-91aa-11e8-9e72-0f612859f92d.JPG)
### Description

In ticket filters, i try to add one and also the
 action if it meet the condition, i try the "Send an Email". But the redactor is not clickable unlike the recepients and subject field.

### Steps to Reproduce
**Expected behavior:** I should click the redactor so i can add message for the email or any detail i want to add that is available.

**Actual behavior:** The whole email filter action is dragable and not as expected to put saome text in redactor.

### Versions
osTicket Version | v1.11.0-rc1 (e321982) —  Up to date
Web Server : IIS
Web Server Software : Apache
MySQL Version : 5.5.46
PHP Version : 5.4.45
Browser: Google Chrome Latest.

**Comment by JediKev** [comment]
@iHunt101 

Thank you, will work on this.

Cheers.

**Comment by JediKev** [comment]
@iHunt101 

Here is the pull request that should fix this issue:
https://github.com/osTicket/osTicket/pull/4381

Please test this and let me know. Cheers.

**Comment by iHunt101** [comment]
Hi @JediKev 

I apply your PR and it works fine.

Thanks!
