### ISSUE TITLE
Restriction of agent to others agen

### ISSUE THREAD

**Issue by johnkalangha** [osTicket/osTicket#4373]
How can i change the settings in admin,..for example.. agent 1 can see all closed at answered ticket of agent 2, which not necessary to view that ticket.. only team lead can see all ticket of there member? please help me

**Comment by ntozier** [comment]
Sorry but I don't get what your trying to ask.  
osTicket doesn't have Team Leads.
Maybe a screen shot would help?
Also what version are you running?

**Comment by johnkalangha** [comment]
I already figure out sir.. thanks

**Comment by johnkalangha** [comment]
Sorry not for Answered Tab.. For Closed Ticket only..  other agents cant see the closed ticket of another agent

**Comment by johnkalangha** [comment]
i will close this because the request or issue are resolve in v 1.11 thanks
