### ISSUE TITLE
Issue: Set Agent Password Manually(Mutiple Times Before it can Access)

### ISSUE THREAD

**Issue by johnkalangha** [osTicket/osTicket#4374]
Good day.. need help with this issue, when i create an agent and i set agent password manually after i save and ttry the account of the agent..it always access denied. so i tried to enter the password manually for the second time before it can log in..

**Comment by johnkalangha** [comment]
![image](https://user-images.githubusercontent.com/30627667/43361992-fd0e9160-9311-11e8-8ab8-9aec13814fe4.png)
Thank You in Advance

**Comment by JediKev** [comment]
@johnkalangha

First thing I notice is that you are using PHP 7.2.x which is not supported. Please test this using PHP 5.6.x. In the meantime do you see any errors in you Apache/PHP error logs? Can you see in the database that the password is indeed updated?

Cheers.

**Comment by johnkalangha** [comment]
i also try php 5.6 same issue.. and there is no error in logs indicated..

**Comment by johnkalangha** [comment]
@iHunt101  yes sir

**Comment by ntozier** [comment]
PHP error logs?
MySQL Error logs?
