### ISSUE TITLE
How to update version of osticket in linux?

### ISSUE THREAD

**Issue by johnkalangha** [osTicket/osTicket#4376]
Present Version:
OSticket: v1.10.4
Mysql
PHP 7.2
OS: Linux

To Upgrade OSticket V.1.11 rc1

Issue: When i try to update the version, i copy the whole folder from site then copy to my folder where my site is located (it is in installation) but when i try to open the site, it is a blank, no view.. just a white scree only...

**Comment by JediKev** [comment]
@johnkalangha

Any Apache, PHP, or MySQL errors? You do still have an `include/ost-config.php` file right? And everything has the correct permissions and is owned by the Apache user/group right?

Cheers.

**Comment by johnkalangha** [comment]
No Error pop up.. yes the ost-config.php is still in the file .... and permission i dont anything change from the previous one

**Comment by johnkalangha** [comment]
Do i need to restart the apache?

**Comment by ntozier** [comment]
Sounds like you copied things into the wrong place.   Consult your Apache error logs to see whats going on.

**Comment by JediKev** [comment]
@johnkalangha

Somewhere, something went wrong. Me and almost everyone else testing `1.11.0rc-1` is able to upgrade. I’ve even upgraded from `1.6 ST` (the oldest supported version for upgrading) to the latest.

You have to have errors somewhere as it’s a white screen indicating issues, which would throw errors. Have you tried enabling errors via the `bootstrap.php` file? You change `display_errors` and `display_startup_errors` to `1` and retry.

Cheers.

**Comment by johnkalangha** [comment]
same sir no display error pop up.. huhu

**Comment by johnkalangha** [comment]
or do you have step by step how to upgrade osticket in linux ubuntu?

**Comment by ntozier** [comment]
Maybe the problem is that you are running PHP 7.2

**Comment by johnkalangha** [comment]
Maybe, but i tried using my laptop and install the older version of osticket using xampp as server and php7. 2 and mysql database, and upgrade to 1.11 and its work, i dont why it didnt works in linux server

**Comment by telx85** [comment]
I would definitely try it using PHP 7.0. While it might not be the issue, it will eliminate that for the dev's.
Look here #4360

**Comment by johnkalangha** [comment]
I will try this sir tomorrow, thanks

**Comment by JediKev** [comment]
@johnkalangha 

Our upgrade guide can be found here:
https://docs.osticket.com/en/latest/Getting%20Started/Upgrade%20and%20Migration.html

>i dont why it didnt works in linux server

I only use Linux (specifically CentOS) and I'm able to upgrade just fine from any version. It has to be something with your particular environment/setup. I would second @ntozier and @telx85 that PHP 7.2 might indeed be the issue as we don't fully support PHP v7.x+.

Please let us know the results after your testing tomorrow.

Cheers.

**Comment by theking81** [comment]
I use CentOS and PHP v7.0 and the upgrade from 1.10.4 to 1.11 was done in under 1 minute with success.

**Comment by johnkalangha** [comment]
there is an error in php 7.2.
here are the errors 
![image](https://user-images.githubusercontent.com/30627667/43555910-8fd305d8-962f-11e8-9ea2-6458e698ae37.png)

**Comment by JediKev** [comment]
@johnkalangha

Thank you for theses errors. But as I said earlier, PHP 7+ is not fully supported at this time. We hope to address these issues soon. In the meantime use PHP 5.6.

Cheers.

**Comment by johnkalangha** [comment]
yes sir.. i will thanks a lot sir

**Comment by JediKev** [comment]
@johnkalangha

You could actually try this pull request with PHP 7.1 and let me know if it works for you:
https://github.com/osTicket/osTicket/pull/4344

Cheers.
