### ISSUE TITLE
Custom form choices variable replacement issue

### ISSUE THREAD

**Issue by kest874** [osTicket/osTicket#4379]
### Prerequisites

* [Y ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [N] Do you have any errors in the PHP error log, or javascript console?
* [ Y] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [Y] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

When you add a Choices field to a custom form with a key:value pair and try to use it as a variable in either an email template or a canned response the variable is replaced with only the key and not the variable.

**Expected behavior:**
Value should be displayed  ie. key:value (1:First Choice) variable should returned as First Choise

**Actual behavior:** 

Key was displayed ie. key:value (1:Choice 1) variable returned as 1

### Versions
1.10 and 1.11

Note that this may effect the default form as well (untested)

**Comment by JediKev** [comment]
@kest874 

This has already been fixed and merged into `develop`:
https://github.com/osTicket/osTicket/pull/4359

Cheers.

**Comment by kest874** [comment]
Awesome thanks, missed the commit.  Confirmed fixed.
