### ISSUE TITLE
SLA change Hours to Minutes

### ISSUE THREAD

**Issue by johnkalangha** [osTicket/osTicket#4382]
Osticket Version: v1.10
Mysql
Php 7.2
apache server

anyone can help me regarding in here issue.. my boss want to change all our SLA Help topics for about to 10 mins to 20 mins ...

**Comment by JediKev** [comment]
@johnkalangha

That is not a feature of osTicket at this time.

Cheers.

**Comment by johnkalangha** [comment]
huhu, is there any solution even though for temporary?

**Comment by JediKev** [comment]
@johnkalangha

Not that I know of. You can search around on our Forum here for any possible temporary, third-party workaround:
http://osticket.com/forum

Cheers.

**Comment by johnkalangha** [comment]
Copy sir, thanks and god bless
