### ISSUE TITLE
Spanish language I select it and it continues in English

### ISSUE THREAD

**Issue by amoyat** [osTicket/osTicket#4384]
https://user-images.githubusercontent.com/24636584/43474559-4576d4e8-94c1-11e8-8693-74e6f254251e.png

Hello I have the Spanish language I select it and it continues in English, it does not change language. What can be?

**Comment by JediKev** [comment]
@amoyat

Have you cleared your browser cache and cookies? Also, have you changed your language setting in your Profile?

Cheers.

**Comment by amoyat** [comment]
I deleted the cookies and cache. I entered the browser in incognito mode and nothing. And I'm in the admin profile trying to change the language.   Version osTicket Core, v1.10.4

**Comment by JediKev** [comment]
@amoyat 

I have just tested this on `1.10.4` with the Spanish language pack and I'm able to see the translations just fine. Please post a screenshot of **Admin Panel > Dashboard > Information** so we can get more information on your environment.

Did you download a new language pack from http://osticket.com.download recently or are you using an old one you had from a previous version? If using an old one you will need to re-download a new one and re-install the language pack.

Cheers.

**Comment by JediKev** [comment]
@amoyat 

>And I'm in the admin profile trying to change the language

I meant your Agent Profile. Click **Profile** in the top-right corner of the screen next to Logout. Now click **Preferences** and change **Preferred Language** to Español.

Cheers.

**Comment by diegoale1994** [comment]
I had that problem, the solution was changing php version to 5.6.38
