### ISSUE TITLE
Filter list TICKET "Organization - Account Manager"

### ISSUE THREAD

**Issue by brunotda** [osTicket/osTicket#4386]
v1.11.0
I need to show in "My Tickets", all tickets assigned to me or the "account manager organization" is me.

**Comment by JediKev** [comment]
@brunotda 

Unfortunately, we do not have the concept of "OR" statements for Custom Queues nor Advanced Search.

Cheers.

**Comment by brunotda** [comment]
It's possible create filter "account manager organization is me"? I did not find.

**Comment by JediKev** [comment]
@brunotda 

You would use the `User / Organization / Name` option > `contains` > the name of the Organization you are the Manager of. If you are the Manager of more than one Organization then you could use the `matches` option and create a regex for `name1 or name 2` -> `/(name1|name2)/`

Cheers.

**Comment by brunotda** [comment]
Not very useful with many account managers, you know what files are created filters? I can try to customize it.

**Comment by JediKev** [comment]
@brunotda 

Start here: `include/class.filter.php`

Cheers.

**Comment by JVC-MSF-OCB** [comment]
Hey @brunotda have you managed to get the ticket list filter for Account Managers in the end?
