### ISSUE TITLE
Sort Tasks by Priority?

### ISSUE THREAD

**Issue by leeryanrs** [osTicket/osTicket#4387]
Is it possible to achieve sorting tasks by priority?

I've made a couple of edits to "tasks.inc.php" and "task-view.inc.php" and ended up with this. 

But I need to display the actual priority in the column. ( The sorting is working at least)..

![osticket tasks](https://user-images.githubusercontent.com/36628948/43513829-0ec912e4-957f-11e8-9825-08a603d2550c.JPG)

**Comment by JediKev** [comment]
@leeryanrs 

Please don't post issues with custom modifications on Github, rather you should post them on our [Forum](http://osticket.com/forum). Only post issues on here that are with osTicket's core codebase not with modifications you've made to the codebase.

Cheers.
