### ISSUE TITLE
[core]: Upgrader Error (1.10 to 1.11

### ISSUE THREAD

**Issue by stf675** [osTicket/osTicket#4391]
### Prerequisites

* [ X] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ X] Do you have any errors in the PHP error log, or javascript console?
* [ X] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [X ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

**Install new OS 1.11  ->  restore 1.10 data -> got prompted for updater -> Run Upgrader**

[core]: Upgrader Error | Error | 08/01/18 15:15:25 | 10.8.4.51

 Upgrader - 0ca85857 applied | Debug | 08/01/18 15:15:25 | 10.8.4.51

 Upgrader - ad9d0a5f (task pending). | Debug | 08/01/18 15:15:12 | 10.8.4.51

 Upgrader - ad9d0a5f applied | Debug | 08/01/18 15:15:12 | 10.8.4.51

 Upgrader - 934b8db8 applied

Error:

`[/** * @signature 86707325fc571e56242fccc46fd24466 * @version v1.11.0 * @title Add ticket referral * * This patch adds a table for thread referral as well as thread event states of referred and deleted */ CREATE TABLE `ost_thread_referral` ( `id` int(10) unsigned NOT NULL AUTO_INCREMENT, `thread_id` int(11) unsigned NOT NULL, `object_id` int(11) unsigned NOT NULL, `object_type` char(1) NOT NULL, `created` datetime NOT NULL, PRIMARY KEY (`id`), UNIQUE KEY `ref` (`object_id`, `object_type`, `thread_id`), KEY `thread_id` (`thread_id`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8] Table 'ost_thread_referral' already exists`

XAMPP with PHP 7.0

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

**Comment by JediKev** [comment]
@stf675 

You've somehow managed to run the upgrader twice it seems. I did not run into this error but I will test again to make sure.

Cheers.

**Comment by stf675** [comment]
I ran "upgrade now" few times, no go
then dropped the table mentioned - no go
I dropped all tables, set "installed" to false and recreate 1.11
logged in fine, restored backup, got kicked back to login screen, login again got prompted for upgrader, no go

**Comment by ntozier** [comment]
So when you say 1.10 to 1.11 what do you actually mean?

You downloaded from osticket.com?  or github?
1.10.0?  1.10.1? 1.10.2? 1.20.3? 1.10.4?
1.11rc1?

Your server environment details?
(such as OS, webserver and ver? PHP ver? etc)

**Comment by stf675** [comment]
I migrated  1.10.0 to new server (dev) and upgraded to 1.10.4

When I try to upgrade to 1.11, I got declaration error due to php7.2

I reinstall XAMPP using version with PHP 7.0.32 and install fresh 1.11.

When I restored my 1.10 data I got prompt for upgrade, and then I was getting error mentioned in beginning.

old server

![image](https://user-images.githubusercontent.com/1325814/43588053-440f9e70-9631-11e8-9535-da96eeb259ba.png)


new server

![image](https://user-images.githubusercontent.com/1325814/43588442-23c1dfba-9632-11e8-9475-00d9df6a5608.png)

**Comment by JediKev** [comment]
@stf675 

PHP 7.x+ IS NOT SUPPORTED AT THIS TIME. Please test using PHP 5.6.

Cheers.

**Comment by stf675** [comment]
I got that, but the error I am getting is not caused by PHP, but has to do with SQL tables.  
In the past  when I went to 1.10 and had SQL errors it was caused by custom forms I had, it was IDed by devs and fixed.  thew whole point of RC1 is to start ironing out small bugs. Unless it hard to fix, the final recommendation could be "update to latest 1.10 first"

**Comment by ntozier** [comment]
As a side note you do realize that 1.11rc1 is a release candidate and really shouldnt be used in production right?

**Comment by stf675** [comment]
@ntozier  I do, That why I am testing it on separate system.  Since I need to keep all my data - I need upgrade to work.  

@JediKev  version 1.10 has a bug with PHP 5.6, the only time format we can use is 24h.  When we choose am/pm time goes blank everywhere.  When I migrated 1.10 to my dev server with php 7.2 - Time display issue went away.  I have no problems testing it with PHP 5.6  But the issue is with upgrade script.
It trying to create "thread_referral' table but since it already there it gives 
`Table ost_thread_referral already exists`.  
It seems like error handling is not working correctly in SQL script.


(on non related note, My personal host provider now charging extra if I choose PHP 5 instead of PHP 7)

**Comment by JediKev** [comment]
@stf675 

I have never heard of time formats not working at all...ever...unless it was referring to duplicated days in the format (fixed with [this](https://github.com/osTicket/osTicket/pull/3623)).

As for the upgrader, no one has experienced this issue except you. The `1.10.x` series and below does not have an `ost_thread_referral` table so the question is how do you have that table on 1.10.x? Did you modify the database? Did you apply a patch previously? Because that's what's causing your issue (having the table before upgrading)...not the upgrader.

Cheers.

**Comment by ntozier** [comment]
@stf675 ok good.  Just wanted to make sure :)

**Comment by stf675** [comment]
@JediKev 

I...
1. install fresh 1.11 (logged in successful)
2. restored 1.10 database.  
3. Was logged out by OST, when I login back, I got prompt for database upgrade 
4. Execute it, two scripts where successful, 3rd one error out.

**Comment by JediKev** [comment]
@stf675 

Please check your restored, 1.10 database and see if there is an `ost_thread_referral` table. If so that's your problem.

Cheers.

**Comment by stf675** [comment]
@JediKev 
There is not, but emty table was created by 1.11 install.  Dropping that table did not help.
I am trying to find that SQL script to look into the code.  (they all have random alphanumeric names)

**Comment by stf675** [comment]
`/**
 * @signature 86707325fc571e56242fccc46fd24466
 * @version v1.11.0
 * @title Add ticket referral
 *
 * This patch adds a table for thread referral as well as thread event states of referred and deleted
 */

CREATE TABLE `%TABLE_PREFIX%thread_referral` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `thread_id` int(11) unsigned NOT NULL,
  `object_id` int(11) unsigned NOT NULL,
  `object_type` char(1) NOT NULL,
  `created` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ref` (`object_id`,`object_type`,`thread_id`),
  KEY `thread_id` (`thread_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

ALTER TABLE `%TABLE_PREFIX%thread_event`
  CHANGE `state` `state` enum('created','closed','reopened','assigned','transferred', 'referred', 'overdue','edited','viewed','error','collab','resent', 'deleted') NOT NULL;


 -- Finished with patch
UPDATE `%TABLE_PREFIX%config`
    SET `value` = '86707325fc571e56242fccc46fd24466'
    WHERE `key` = 'schema_signature' AND `namespace` = 'core';
`

When I run it directly on SQL using phpMyAdmin
I am getting the following:  

![image](https://user-images.githubusercontent.com/1325814/43594810-c808d11a-9640-11e8-8d08-b6376e86677d.png)


Also on navigation pane it created table 
![image](https://user-images.githubusercontent.com/1325814/43594848-df6b630e-9640-11e8-8435-e4e8a2452abd.png)  instead of ost_thread_referral

Is it possible that updater run scripts in wrong order?  Or I cant really run those scripts with phpMyAdmin?

**Comment by JediKev** [comment]
@stf675 

....change `%TABLE_PREFIX%` to `ost_`.

Cheers.

**Comment by stf675** [comment]
actually I see them in other view

![image](https://user-images.githubusercontent.com/1325814/43595162-92dc4ec6-9641-11e8-8320-788764dcc426.png)

as well as

![image](https://user-images.githubusercontent.com/1325814/43595183-a4aea2e8-9641-11e8-9327-e01c71e9709e.png)

strange

**Comment by stf675** [comment]
SOLVED:

After I deleted "create table" section, upgrade process passed that script, but stuck on next.
So I dropped all tables from DB, restored 1.10, and was able to upgrade successfully.

Look  like upgrade scripts failing if new 1.10 tables already exist.
