### ISSUE TITLE
Custom form attach files to new ticket email

### ISSUE THREAD

**Issue by kest874** [osTicket/osTicket#4393]
Is it not possible to attach files as a variable in the email templates?

When the email sends the variable gets replaced by the filename however the actual file is not attached.

**Comment by ntozier** [comment]
You haven't told us what version of osTicket that you are running or what variable you are using.  Are you using %{message.files}?

**Comment by kest874** [comment]
1.10, it's a custom form so %{ticket.supportfiles}  the field has supportfiles as it's variable name in the form setup.  When the email comes it show the filename, and nothing is attached.

**Comment by kest874** [comment]
Adding .files at the end includes the attachment. i.e.  %{ticket.supportfiles.files}
