### ISSUE TITLE
Help [CSS] Redesign the front-end for new ticket

### ISSUE THREAD

**Issue by johnkalangha** [osTicket/osTicket#4402]
anyone can help redesigning the front end for new ticket just like this in the pic

![image](https://user-images.githubusercontent.com/30627667/43625484-d9de2608-971f-11e8-9a4e-8179c3f1dcd9.png)

**Comment by JediKev** [comment]
@johnkalangha

Please do not post questions about customizations on GitHub as it’s for reporting bugs with the core codebase or to request features only. If you would like to ask questions about customizations please post on our Forum here:
http://osticket.com/form

Please close this as this is not an issue.

Cheers.
