### ISSUE TITLE
Bugs in end users replying

### ISSUE THREAD

**Issue by johnkalangha** [osTicket/osTicket#4404]
PHP 7.0
OSTicket version 1.11 Rc
Mysql 5.6

When i replying as a end user after i click the button submit.. white screen appear and not transfer to ticket itself.. but ticket is received by an agent.. thanks

**Comment by JediKev** [comment]
@johnkalangha 

I'm unable to replicate this with the latest pull from `develop-next`. Please use the latest pull from `develop-next`, retest and let me know.

What errors are you getting via Apache, PHP, browser console, osTicket, and MySQL error logs?

**Note:**
Your issue might be due to PHP 7.0 as it's not fully supported.

Cheers.

**Comment by johnkalangha** [comment]
![image](https://user-images.githubusercontent.com/30627667/43671933-439c757a-97d6-11e8-89d0-b45965cb0cd2.png)
here is the error sir

**Comment by johnkalangha** [comment]
![image](https://user-images.githubusercontent.com/30627667/43671994-62f99bf4-97d7-11e8-89e2-f4d069c6d51d.png)

**Comment by johnkalangha** [comment]
![image](https://user-images.githubusercontent.com/30627667/43672012-e0ce0218-97d7-11e8-86a0-0c987dfafcbe.png)

**Comment by JediKev** [comment]
@johnkalangha 

You are using the package downloaded from our website. Please test this using the latest pull from `develop-next` as it contains fixes we’ve found and fixed since the website release.

Cheers.

**Comment by johnkalangha** [comment]
sir can i get the link for the develop next? thanks cheers

**Comment by JediKev** [comment]
@johnkalangha

It’s here on GitHub. Go to the main Code tab, change Branch to `develop-next`, click Clone or Download, and click Download ZIP.

Cheers.

**Comment by johnkalangha** [comment]
thanks sir cheers
