### ISSUE TITLE
[BUG] Ticket Statuses - Allow Reopen not working 

### ISSUE THREAD

**Issue by SalvatoreAzad** [osTicket/osTicket#4405]
### Prerequisites
* [Yes] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [No] Do you have any errors in the PHP error log or javascript console?
* [Yes] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [Yes] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description
Ticket Statuses, The Properties for Closed / Resolved are being ignored – The Allow Reopen is ticked to allow the tickets to be reopened by the end users however the system still prevents this and opens a new ticket.

### Steps to Reproduce
1. Open New Ticket
2. Close ticket with Resolved or Closed Status
3. Reply via email
4. A new ticket will be created

Expected behaviour: Ticket to be set back to Open status with a reply appended to the ticket.

Actual behaviour: A new ticket is created.

### Versions
osTicket Version: v1.11.0-rc1 (e321982) —  Up to date
Web Server Software: Apache
MySQL Version: 10.1.14
PHP Version: 7.0.31

![chrome_2018-08-03_15-41-11](https://user-images.githubusercontent.com/42069762/43649151-4d01575e-9734-11e8-9589-089a72cbb039.png)
![chrome_2018-08-03_15-41-29](https://user-images.githubusercontent.com/42069762/43649152-4d207706-9734-11e8-9756-b0580c8fab61.png)

**Comment by JediKev** [comment]
@SalvatoreAzad 

I cannot replicate this with the latest pull from `develop-next`. Please retest this with the latest pull from `develop-next` and let me know.

Cheers.

**Comment by SalvatoreAzad** [comment]
When I tried the develop-next on my current test install I get the below:

`
Warning: Declaration of AssignmentForm::render($options) should be compatible with Form::render($staff = true, $title = false, $options = Array) in /home/sites/4b/7/7df85e5486/public_html/email/include/class.forms.php on line 4900

Warning: Declaration of ReferralForm::render($options) should be compatible with Form::render($staff = true, $title = false, $options = Array) in /home/sites/4b/7/7df85e5486/public_html/email/include/class.forms.php on line 5150

Warning: Declaration of TransferForm::render($options) should be compatible with Form::render($staff = true, $title = false, $options = Array) in /home/sites/4b/7/7df85e5486/public_html/email/include/class.forms.php on line 5242

Warning: Declaration of QueueColumnListBroker::update($columns, &$errors, $options = Array) should be compatible with InstrumentedList::update(array $what) in /home/sites/4b/7/7df85e5486/public_html/email/include/class.queue.php on line 2473

Warning: Declaration of AdhocSearch::checkAccess($staff) should be compatible with CustomQueue::checkAccess(Staff $agent) in /home/sites/4b/7/7df85e5486/public_html/email/include/class.search.php on line 909

Warning: Declaration of TeamSelectionField::getSortKeys() should be compatible with FormField::getSortKeys($path) in /home/sites/4b/7/7df85e5486/public_html/email/include/class.search.php on line 1285

Warning: session_start(): Cannot send session cookie - headers already sent by (output started at /home/sites/4b/7/7df85e5486/public_html/email/include/class.forms.php:4900) in /home/sites/4b/7/7df85e5486/public_html/email/include/class.ostsession.php on line 86

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /home/sites/4b/7/7df85e5486/public_html/email/include/class.forms.php:4900) in /home/sites/4b/7/7df85e5486/public_html/email/include/class.ostsession.php on line 86

Warning: Cannot modify header information - headers already sent by (output started at /home/sites/4b/7/7df85e5486/public_html/email/include/class.forms.php:4900) in /home/sites/4b/7/7df85e5486/public_html/email/include/class.http.php on line 62`

**Comment by JediKev** [comment]
@SalvatoreAzad 

Ah, PHP 7.x+ is not _fully_ supported by us just yet. You can either [try this pull request](https://github.com/osTicket/osTicket/pull/4344) for PHP 7 or just downgrade to PHP 5.6.x.

Cheers.

**Comment by SalvatoreAzad** [comment]
@JediKev 

I have downloaded the develop-next, then download the develop-next and added the pull above however, the original issue is still occurring, Even if I create a new Status if I assign to closed, as soon as it's in the state it won't allow a reopen regardless of if the tick box allows it or not.

**Comment by JediKev** [comment]
@SalvatoreAzad

Then I suggest you test this with PHP 5.6.x.

Cheers.

**Comment by JtheBAB** [comment]
Hi

I have the same issue. I tried the latest develop-next release.


Web Server: Apache/2.4.10 (Debian) OpenSSL/1.0.1t
MySQL Version: 5.5.60
PHP Version: 5.6.36-0+deb8u1

When i go to Admin Panel --> Manage --> List --> Ticket Statuses --> Resolve and press "Save" i get this error within my apache error.log:

`PHP Warning:  Missing argument 2 for TicketStatus::update(), called in /srv/www/include/ajax.forms.php on line 180 and defined in /srv/www/include/class.list.php on line 1432`

Best regards

**Comment by JtheBAB** [comment]
@JediKev 

Works 👍 

Thanks.

**Comment by SalvatoreAzad** [comment]
@JediKev

Perfect - Thank You 🥇

Thanks.
