### ISSUE TITLE
Valid CSRF Token Required - OSTicket 1.10.4

### ISSUE THREAD

**Issue by linuxasapet** [osTicket/osTicket#4407]
Getting "Valid CSRF Token Required" on Fedora 28 x64 with fresh install of OSTicket 1.10.4. Running PHP 7.2.8 in conjunction with Apache 2.4.34 and MariaDB 10.2.16. Any ideas?

**Comment by JediKev** [comment]
@linuxasapet

There is already an Issue opened for this:
https://github.com/osTicket/osTicket/issues/3546

Please close this in favor of the original.

**Note
This should be fixed in `1.11.x` with this pull request:
https://github.com/osTicket/osTicket/pull/4344

Cheers.
