### ISSUE TITLE
Update Logo Issue

### ISSUE THREAD

**Issue by johnkalangha** [osTicket/osTicket#4408]
Osticket Version: v1.10.
PHP 5.6 
Mysql
Apache server

When i upload my logo in my site, always blank.. see the picture..

![image](https://user-images.githubusercontent.com/30627667/43683959-2450aa58-98c9-11e8-8bf6-082ba75d6e4d.png)
![image](https://user-images.githubusercontent.com/30627667/43683981-cc541348-98c9-11e8-9779-c30409d14fd7.png)

**Comment by ntozier** [comment]
It might be too big.  ALso please upgrade to 1.10.4 and test with the current stable.

**Comment by johnkalangha** [comment]
thanks for this sir

**Comment by JediKev** [comment]
@johnkalangha 

Cannot replicate this with `1.10.4` and PHP 5.6.x.

Cheers.

**Comment by johnkalangha** [comment]
its already solved sir thanks much
