### ISSUE TITLE
How can I get all tickets using api?

### ISSUE THREAD

**Issue by Anastasia-Gorobets** [osTicket/osTicket#4409]
How can I get all tickets using api? I need get all tickets and wrote it to my db. 
Thanks.

**Comment by JediKev** [comment]
@Anastasia-Gorobets

At this time the API can only create tickets or tasks. There are no GET methods. Below is a link to our API documentation:
https://docs.osticket.com/en/latest/Developer%20Documentation/API%20Docs.html

Cheers.

**Comment by JediKev** [comment]
@Anastasia-Gorobets

Not unless a member of the community has developed such feature or if you would like to develop it yourself. You may check here on GitHub or on our [Forum](http://osticket.com/forum) for such feature. With that being said, we do have plans to completely rewrite the API to make it fully RESTful in the future, so stay tuned.

Cheers.

**Comment by AdamDempsey** [comment]
@Anastasia-Gorobets You could look at #4361 which is a pull request to add retrieving ticket data to the API
