### ISSUE TITLE
How to disable this menu button

### ISSUE THREAD

**Issue by johnkalangha** [osTicket/osTicket#4417]
good day sir may i know how to disable this button the highlight one.. because it is not applicable in out end user to check there ticket without entering the site thanks u

![image](https://user-images.githubusercontent.com/30627667/43754346-e98f2f78-9a3c-11e8-8bff-834671d497bf.png)

**Comment by johnkalangha** [comment]
v1.10.4 my version of osticket

**Comment by perryk** [comment]
I have a branch you can apply which does this and a couple of other things for the exact same reason you have stated. We want our users to log in before they can do anything.

This branch does the following:

- Removes links to registration, note that this is still actually enabled, simply hidden.
- Remove links to and the whole page for check ticket status.
- Added info to the Help Topic choice to give expanded instructions.
- Changed the big green button on front page to a link to the knowledgebase instead.

You can see the exact changes here: https://github.com/perryk/osTicket/commit/3d1419798ee19eb959f417abc98e98bc416e0770

You can apply these changes with something like:
```
git remote add perryk https://github.com/perryk/osTicket.git
git pull --no-edit perryk mod-remove-rego-check-status-client-page
```

This is ok for use with v1.10.4, it might not work with v1.11.rc1 and newer versions however. This is the risk you take with applying modifications to the core files.

Cheers.
