### ISSUE TITLE
Feature: Multiple Recipients and multiple Collaborators (separated) for ticket.

### ISSUE THREAD

**Issue by Ajtak** [osTicket/osTicket#4430]
Hi. will be multiple recipients and multiple collaborators as separated? As it on screen. 
Because To is main recipients and cc is copy only.

#### My idea on staff panel:
![img1](https://user-images.githubusercontent.com/4963819/43914453-4077db2e-9c08-11e8-9911-9b63e54c2174.png)

#### My idea on email message:
![img2](https://user-images.githubusercontent.com/4963819/43914454-4098f034-9c08-11e8-82a6-cd5c44489277.png)

**Comment by ntozier** [comment]
The "To:" is ticket owner.  The person who's name/email was used to open the ticket.  In your example I think that would be Jakub.  You cannot have a ticket with multiple owners...

"CC:" are Collaborators.  Alice, Bob, Peter, Cyril.
