### ISSUE TITLE
'_' hardcoded in the search tableprefix

### ISSUE THREAD

**Issue by lucasjkr** [osTicket/osTicket#4433]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?

I had issues installing 1.11, so I'm giving 1.10 a test drive

* [ ] Do you have any errors in the PHP error log, or javascript console?

No errors, it works as expected, it's just weird that that table gets put out of order, since it's name becomes `ost__search` rather the the expected `ost_search`

I see a patch file that drops this table

* [ ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?

I checked the code, it's still present:

https://github.com/osTicket/osTicket/blob/develop/include/class.search.php

### Description

Search table has _ in the name resulting in the table name having two _'s if the default `ost_` prefix is used.

### Steps to Reproduce

Install

Look at database tables

**Comment by JediKev** [comment]
@lucasjkr

Lol the `ost__search` table is like that for a reason. This table gets dropped and recreated on the fly. This is expected behavior.

Cheers.

**Comment by lucasjkr** [comment]
All I can say is I can't wait to see why this is? And even if that behavior is correct, why it can't be named conventionally...

Oh well. I just installed it and am poking around. Sorry to be a bother.
