### ISSUE TITLE
Installing osTicket 1.8-git

### ISSUE THREAD

**Issue by Abdulmoneim** [osTicket/osTicket#4435]
On Finished install Screen 

```
Warning: Declaration of AssignmentForm::render($options) should be compatible with Form::render($staff = true, $title = false, $options = Array) in C:\AppServ\www\ts\osTicket\include\class.forms.php on line 4376

Warning: Declaration of TransferForm::render($options) should be compatible with Form::render($staff = true, $title = false, $options = Array) in C:\AppServ\www\ts\osTicket\include\class.forms.php on line 4496
```

And Login Error 

```
Warning: Declaration of AssignmentForm::render($options) should be compatible with Form::render($staff = true, $title = false, $options = Array) in C:\AppServ\www\ts\osTicket\include\class.forms.php on line 4376

Warning: Declaration of TransferForm::render($options) should be compatible with Form::render($staff = true, $title = false, $options = Array) in C:\AppServ\www\ts\osTicket\include\class.forms.php on line 4496

Warning: session_start(): Failed to read session data: user (path: C:/Users/xxxx/AppData/Local/Temp) in C:\AppServ\www\ts\osTicket\include\class.ostsession.php on line 86
Valid CSRF Token Required
```

php version 7.1.20
Apache Server 2.4.25
Windows 7

**Comment by JediKev** [comment]
@Abdulmoneim

Your issue is PHP 7.1.x. You may downgrade to PHP 5.6 or if you are testing 1.11.0rc-1 then you could try this pull:
https://github.com/osTicket/osTicket/pull/4344

Cheers.

**Comment by opensourcecompany** [comment]
This issue is also relevant to PHP 7.0 on Debian stable.
Maybe you should fix this issue by recommending not PHP 5.6 OR LATER.
Instead you should write, that your software is abandoned and only running with outdated PHP5.6.

**Comment by opensourcecompany** [comment]
Hello @JediKev , i didn't want to be rude, but most of the tickets exist due incompatibility to PHP7.
And as we know both, the end of PHP5.6 didn't come as a surprise.

So, in general: yes, i didn't have a look at the dev branch.
Yes, the unstable version supports PHP7.

But who wants to install a release candidate for production environment?
I know, this is open source. But you offer professional services/hosted versions.
And to be honest: i was thinking about booking this for a client, but after this "free community edition" i might consider another choice.

And yes, the readme is somewhat incorrect :-)

**Comment by JediKev** [comment]
@opensourcecompany

>... most of the tickets exist due incompatibility to PHP7.
And as we know both, the end of PHP5.6 didn't come as a surprise.

That’s why we are working on 1.11 ;)

>But who wants to install a release candidate for production environment?

The `1.11.x` branch is so close to being completely stable. We run a few instances of 1.11 in production and it’s just fine with PHP 7.1. Just saying lol

Cheers.
