### ISSUE TITLE
User Form Field Editability

### ISSUE THREAD

**Issue by johnkalangha** [osTicket/osTicket#4436]
OSTICKET V.1.11.1
php 5.6 
mysql 5.6
apache

when i tried to uncheck the editable for user and agent (only admin can edit email and name of user)

and i check the profile of user.. still can edit, how to edit that?

**Comment by JediKev** [comment]
@johnkalangha

There is already an issue opened for this. Also, we cannot allow email or name field on user side to be non-editable as A.) its a required field B.) Users should always be able to update this.

Cheers.

**Comment by ntozier** [comment]
Side note: there is no such release as 1.11.1.
