### ISSUE TITLE
More issues with Valid CSRF

### ISSUE THREAD

**Issue by askdata01** [osTicket/osTicket#4446]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [ ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

**Comment by JediKev** [comment]
@askdata01 

Please fill out the Issue form as we have no clue what you are talking about.

There are multiple Issues opened and multiple pull requests open to fix this. Please sort through these and apply them to address your issue.

Helpful pulls:
- https://github.com/osTicket/osTicket/pull/3955
- https://github.com/osTicket/osTicket/pull/4344

Please close this issue in favor of the original one opened:
https://github.com/osTicket/osTicket/issues/3546

Cheers.

**Comment by askdata01** [comment]
My apologies for not filling in the form.  I accidentally submitted the request.
None of the pulls or original apply.
OSTicket version 1.10.4ST
OS: CentOS7
Php: 5.6.37
MySQL: 5.7.23
Apache 2.4.6
This was an upgrade of an existing 1.6ST install but after upgrading the files, I can’t access the admin panel.  There are no errors logged in the Apache logs, mysql logs, php logs.  I turned error reporting on in the bootstrap.php but nothing except the valid CSRF message comes up.  Looking at the cookies path, it is the correct location of the installation.  I tried adding the code to the class.ostsession.php but that also did not resolve the issue.  I should mention that the 1.6ST installation is running on RHEL 6.5, php 5.6.33, Apache 2.2, and MySQL 5.1.73.
I did the MySQL update using mysqldump and the logical update procedure.  I tested the 1.6ST on the new server after the updates and it ran fine.  It only broke after updating to the 1.10.4 ST version.
Thanks,
Steve

**Comment by JediKev** [comment]
@askdata01 

That's weird, as I've been able to upgrade from `1.6 ST` to `1.10.4` and even `1.11.0rc-1` just fine with no errors. There has to be a more descriptive error somewhere... if you are receiving the "Valid CSRF Token Required" error it means the system cannot validate your session. Have you tried refreshing the page or visiting the page in an Incognito window?

Cheers.

**Comment by cmadera** [comment]
I have the same issue, in my case I moved the application from an Ubuntu 16.04 with PHP 5 to Ubuntu 18.04 with PHP 5.7.
