### ISSUE TITLE
Bugs Post Reply in End USer

### ISSUE THREAD

**Issue by johnkalangha** [osTicket/osTicket#4447]
OSTicket Version 1.10.4
PHP 5.6
Mysql 
Apache

Help sir,, when i post a ticket in end user and post reply then refresh the page, my reply will be double, how to fix this?

**Comment by johnkalangha** [comment]
Picture 1 ill try to post reply to my ticket

![image](https://user-images.githubusercontent.com/30627667/44138996-579184d2-a0a8-11e8-8392-5c0a0f636ec3.png)

When i'll try to refresh my browser page.. pop out windows

Note: I will refresh my browser to check if there is reply from agent

![image](https://user-images.githubusercontent.com/30627667/44139029-75ef155c-a0a8-11e8-9840-931e2dc77feb.png)
 
Then another post created

![image](https://user-images.githubusercontent.com/30627667/44139056-864b583e-a0a8-11e8-8202-2cc6f59f3650.png)

**Comment by ntozier** [comment]
Don't refresh the page.

**Comment by johnkalangha** [comment]
> Don't refresh the page.
But i can't say that our customer/ end user will not use refresh button...

**Comment by johnkalangha** [comment]
up up up

**Comment by iHunt101** [comment]
@johnkalangha dont refresh the page, that`s it for now.

I thing it will better if the page reload after successfully submit the data..
