### ISSUE TITLE
Upgrade from 1.9.16 to 1.10 fails in Centos 7

### ISSUE THREAD

**Issue by jjarvela** [osTicket/osTicket#4448]
### Prerequisites

* [ X] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ X] Do you have any errors in the PHP error log, or javascript console?
* [ X] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [ X] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

Few times DB error #1146 with error message:
[SELECT A1.* FROM `ost_translation` A1 WHERE (A1.`lang` = 'en_US' AND A1.`type` = 'phrase')] Table 'osticket.ost_translation' doesn't exist. This does not stop upgrade.

After patch 9143a511 is succesfully applied upgrader fails with error message:

[core]: Upgrader Error

[UPDATE `ost_thread_event` A1 LEFT JOIN `ost__ticket_thread_evt` A2 ON (A1.`thread_id` = A2.`object_id`) SET A1.`thread_id` = A2.`id`] Unknown column 'ticket_id' in 'NEW'

Environment:

Centos 3.10.0-862.9.1.el7.x86_64
mysqld 10.0.29-MariaDB
PHP Version 5.6.37
mysqlnd 5.0.11-dev - 20120503

Client browser: Firefox Quantum 61.0.2

[Description of the bug or feature]

### Steps to Reproduce

Upgrade from 1.9.16 to with release tag 1.10 clone from Git-repository.

**Expected behavior:** [What you expected to happen]

Succesful upgrade

**Actual behavior:** [What actually happened]

Failed upgrade with database error.

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

**Comment by ntozier** [comment]
You should really use the official download version from http://osticket.com/download

**Comment by jjarvela** [comment]
Hi,

Unfortunately results are exacly same with v1.10.4 official download version.

**Comment by JediKev** [comment]
>[SELECT A1.* FROM ost_translation A1 WHERE (A1.lang = 'en_US' AND A1.type = 'phrase')] Table 'osticket.ost_translation' doesn't exist.

These errors are fine...ignore them.

>[UPDATE ost_thread_event A1 LEFT JOIN ost__ticket_thread_evt A2 ON (A1.thread_id = A2.object_id) SET A1.thread_id = A2.id] Unknown column 'ticket_id' in 'NEW'

This error does not make sense as there is no `ticket_id` in the query. Are there any more errors besides that one?

Cheers.

**Comment by JediKev** [comment]
@jjarvela 

Somethings not right here... We need to figure out where `Unknown column 'ticket_id' in 'NEW'` is _truly_ coming from as it's not in the query from the error.

>I guess we stick with 1.9.16 for now.

This is not recommended as the `1.9.x` series has already reached it's end of life.

Cheers.

**Comment by JediKev** [comment]
@jjarvela 

What's your table prefix in the database and what is your table prefix set to in your `include/ost-config.php` file? I see that you have two different prefixes in the error so something is up with your install and/or db.

Cheers.

**Comment by jjarvela** [comment]
@JediKev 
It's ost_ both in database and configuration files. That other one is created by stream patch for temporary table that is deleted later in the script.  Anyways, we are running out of time here, so we continue to use 1.9.16 for now and start looking for other solutions for our helpdesk ticket system. Thanks for your help!

**Comment by JediKev** [comment]
@jjarvela 

Ah, I see now. Just trying to rule everything I can out.

Is your installation out of the box or is it modified in any way? Do you have any extra columns, tables, etc.?

Cheers.
