### ISSUE TITLE
printed pdf is corrupted. 

### ISSUE THREAD

**Issue by khaledfarj** [osTicket/osTicket#4449]
---------------------------------------------
Hi,  I am experiencing problems when printing tickets as pdf files.
When i'm trying to print my ticket as PDF i get a weird square all over the pages. the language i use is Arabic, so only Arabic characters are printed as  square !!!! can you, please, help and tell me how I can overcome this problem,,?

**Comment by JediKev** [comment]
@khaledfarj 

This is an issue with the fonts that are used for mPDF. You can either mess with the mPDF files/fonts yourself or you may wait for a fix to be released. With this being said I have found no fix/workaround so far. I've even tried replacing the fonts, adding new ones, etc. So this will take some time...

Cheers.

**Comment by khaledfarj** [comment]
@JediKev , Thanks for your reply,
I just need to know how i can resolve it by modifying the mPDF files, please!!?

**Comment by khaledfarj** [comment]
any example could be useful for me, Thanks @JediKev

**Comment by JediKev** [comment]
@khaledfarj 

In my previous message I stated:
>With this being said I have found no fix/workaround so far. I've even tried replacing the fonts, adding new ones, etc. So this will take some time...

Cheers.

**Comment by khaledfarj** [comment]
Hi @JediKev ,
I got you said previously, and thanks for it, 
however, i would like, if possible, let me know how you add new fonts and modifying which file, as well, 
anyway, thanks,,

**Comment by JediKev** [comment]
@khaledfarj 

https://stackoverflow.com/questions/22221517/mpdf-not-supporting-arabic-and-chinese-fonts
https://mpdf.github.io/fonts-languages/fonts-in-mpdf-5-x.html

Cheers.

**Comment by khaledfarj** [comment]
i will read through it, and post any success i come up with.
thanks so much for the help, @JediKev

**Comment by JediKev** [comment]
@khaledfarj 

Good news! I finally fixed the issue:
https://github.com/osTicket/osTicket/pull/4455

Please test this and get back to me. Cheers.

**Comment by khaledfarj** [comment]
Hi @JediKev ,
what i understood from your message, that i added the following:
` $this->SetAutoFont();`
into include/class.pdf.php
and i added the following two files into  include/mpdf/ttfonts/XB Zar Bd.ttf  and include/mpdf/ttfonts/XB Zar.ttf

when i run the application i got this error:
mPDF Error - cannot find TTF TrueType font file - C:/xampp/htdocs/osTicket-v1.10.4/upload/include/mpdf/ttfonts/XB Riyaz.ttf

**Comment by JediKev** [comment]
@khaledfarj 

Oooo! Okay, go here and download the language pack that's missing:
https://github.com/carlholmberg/mpdf/tree/master/ttfonts

I'll update my pull request shortly.

Cheers.

**Comment by JediKev** [comment]
@khaledfarj 

Pull request updated. 👍 

Cheers.

**Comment by khaledfarj** [comment]
Ok, it is working finally,,,,,
Thanks so much @JediKev I am really so grateful to your help, thanks, thanks
