### ISSUE TITLE
Customized List in  Ticket Details cause issue in Export File

### ISSUE THREAD

**Issue by jromero72** [osTicket/osTicket#4454]
### Prerequisites
Create a Pesonalice List in Ticket  Details as a New Field.

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
Yes
* [ ] Do you have any errors in the PHP error log, or javascript console?
No
* [ ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
Yes.. Several persons reports oly a apart of the problem.
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?
Yes.. Several persons reports only a apart of the problem.

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

If you include a Customiced  List inthe Ticket Details, the file of export only shows the first two lines and dont include de new field value.

### Steps to Reproduce

1. [First Step]
Create a Custom List
2. [Second Step]
Add a new field in the Ticket Details using the Custom List in estep 1.
3. [Step 3]
Create a New Ticket and set a value tho de new field
3. [Step 4]
Try to export the list of ticket and you can see only two registers or none.

**Expected behavior:** [What you expected to happen]
The  exported file  must be contining all of register.
**Actual behavior:** [What actually happened]
The exported file only shows 2  registers  or none.
### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.

Versión osTicket | v1.10.1
-- | --

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.
Windows 10 and Google Chrome

**Comment by JediKev** [comment]
@jromero72 

This is already a known issue that has been opened here:
https://github.com/osTicket/osTicket/issues/3264

Please close this in favor of the original.

Cheers.

**Comment by jromero72** [comment]
Hi Jedikev, the #3264 do not explain the orgin of the problem:  this occurs when a custom list is added to the Ticket Details.   Are you agreed whit me?  Mi english is poor sorry. 
Thanks

**Comment by JediKev** [comment]
@jromero72 

Basically I was pointing you to that thread so you would see my comment:
https://github.com/osTicket/osTicket/issues/3264#issuecomment-405026040
> ... we have actually addressed these issues in v1.11.0rc-1 ... Along with addressing the original issue it adds the ability to customize what fields you want to export.

Cheers.

**Comment by jromero72** [comment]
Ok .. Thanks. I will close the issue.
