### ISSUE TITLE
Error page after post in a task v1.11.0-rc1

### ISSUE THREAD

**Issue by CashDesk** [osTicket/osTicket#4456]
###After posted in an existing task i get a error page.
I am using v1.11.0-rc1 but i couldn't find a possibility to give feedback on it

![osticket](https://user-images.githubusercontent.com/13085031/44267718-91517f00-a22f-11e8-8beb-bf414b3c2382.png)

**Comment by JediKev** [comment]
@CashDesk 

Please use the latest pull from `develop-next` and retest all your recent Task Issues (#4456, #4457, #4458). Please update each Issue to let me know if pulling the latest fixes it or not.

Cheers.

**Comment by JediKev** [comment]
@CashDesk 

Tested using latest pull from `develop-next` and it's working correctly:
<img width="960" alt="screen shot 2018-08-17 at 09 33 17" src="https://user-images.githubusercontent.com/11823401/44272195-c2b35600-a201-11e8-8cf3-e9e54d404f18.png">


Cheers.

**Comment by CashDesk** [comment]
I installed the develop-next just now.
After posting i get no error.
As soon as i add a recipient to a taks i get this error (see attached)

[Nieuw tekstdocument.txt](https://github.com/osTicket/osTicket/files/2798809/Nieuw.tekstdocument.txt)

**Comment by CashDesk** [comment]
@JediKev What Sorry for asking but what do  i need to do to get the changed file? Download development next again?

**Comment by JediKev** [comment]
@CashDesk

Yes.

Cheers.

**Comment by CashDesk** [comment]
@JediKev , great, thanks!

**Comment by CashDesk** [comment]
As i am not a programmer it sounds too risky for me.  
Lets hope and pray that version 1.11 will soon be live.
Any idea how long it takes?

**Comment by JediKev** [comment]
@CashDesk

It’s so easy to download the file and replace the one you currently have...even if you’re not a dev.

You go to the pull request, go to Files Changed tab, click View File, click the Raw button, **Mac:** Command + A | **Windows:** Ctrl + A (I think) to Select All, copy the selected text to your clipboard, open the same file from your current install in a text editor (many basic free ones online if you don’t have one like Notepad++ for Windows or Atom for Mac), delete everything in the file, and paste the Raw file contents that you copied to your clipboard. Scroll down to make sure everything is there and then Save Changes. 

Now you have the file with the appropriate Changes applied. Sounds like a lot but really it’s just clicking a few buttons, copying some text, and pasting it replacing the old contents. Simple 🙂

Cheers.

**Comment by JediKev** [comment]
@CashDesk 

Update: it appears as though it was just merged so you may download again and it should have the appropriate changes.

Cheers.

**Comment by CashDesk** [comment]
@JediKev downloaded, installed and working now! Thanks for your help
