### ISSUE TITLE
No message in task mail v1.11.0-rc1

### ISSUE THREAD

**Issue by CashDesk** [osTicket/osTicket#4457]
In a posting in a task the mail message is empty.
See link:

https://i.imgur.com/i9S5SXS.png

![osticket](https://user-images.githubusercontent.com/13085031/44267794-d4abed80-a22f-11e8-8001-e28729a46bb3.png)

**Comment by ntozier** [comment]
My "New Activity Alert" template has %{message} in it, but I am running 1.10.4 and do not use tasks.

I have no idea what you think .lastmessage is or where it came from you might want to edit your template and try a real variable.

**Comment by JediKev** [comment]
@CashDesk 

Tested using latest pull from `develop-next` and it's working correctly with the variable `%{message}`:
<img width="411" alt="screen shot 2018-08-17 at 09 40 56" src="https://user-images.githubusercontent.com/11823401/44272247-ebd3e680-a201-11e8-8eeb-f1bb01c6c490.png">


Cheers.

**Comment by CashDesk** [comment]
Solved after updating with develop next
