### ISSUE TITLE
Can't search on task number v1.11.0-rc1

### ISSUE THREAD

**Issue by CashDesk** [osTicket/osTicket#4458]
Can't search on task number v1.11.0-rc1
See attached screen. In this field i fill in an existing number but it can't find.

https://i.imgur.com/iStOt5B.png
![osticket](https://user-images.githubusercontent.com/13085031/44267938-54d25300-a230-11e8-863b-486473907150.png)

**Comment by ntozier** [comment]
This thread also doesn't show:
- what you searched for.
- what the result was.
- Apache or PHP error logs.
- task # format.

**Comment by JediKev** [comment]
@CashDesk 

Tested using latest pull from `develop-next` and it's working correctly:
<img width="960" alt="screen shot 2018-08-17 at 09 33 43" src="https://user-images.githubusercontent.com/11823401/44272285-04dc9780-a202-11e8-8d6f-9aa306441735.png">


Cheers.

**Comment by CashDesk** [comment]
I donwloaded the develop-next version but i have still the same problem:
![image](https://user-images.githubusercontent.com/13085031/44299325-d0e19f00-a2f3-11e8-9c44-9002bba727f7.png)

![image](https://user-images.githubusercontent.com/13085031/44299329-fff81080-a2f3-11e8-91bd-0a8e5d0e83da.png)

**Comment by CashDesk** [comment]
I search on task number but it doesnt show the right number

**Comment by JediKev** [comment]
@CashDesk

I’ve never seen this and I cannot replicate this internally. Are there any errors via Apache, PHP, MySQL, or osTicket? Is your installation modified at all? Is the database modified?

Cheers.

**Comment by CashDesk** [comment]
@JediKev It was working before correct. After installing version v1.11.0-rc1 it didn't work anymore.
We did not modify anything.

**Comment by JediKev** [comment]
@CashDesk

Try this:
https://github.com/osTicket/osTicket/pull/4453

Cheers.
