### ISSUE TITLE
Auto Collaborators

### ISSUE THREAD

**Issue by alfie013** [osTicket/osTicket#4460]
Hi,

Can you please help me to point what php file should I edit to put the collaborator permanently when creating a new ticket via email and osTicket? I tried using the Auto Collaborator in Organization but it is not working.

Server Information
--
osTicket Version | v1.11.0-rc1 (e321982) —  Up to date
Web Server Software | Apache
MySQL Version | 5.6.41
PHP Version | 5.6.30

Thank you,

**Comment by JediKev** [comment]
@alfie013 

I'm able to auto-add collaborators via Organization just fine:
![auto-collab](https://user-images.githubusercontent.com/11823401/44469668-9c206100-a5ed-11e8-962c-cf36cb05bb73.png)

You should retest this issue with the latest pull from `develop-next`.

Cheers.

**Comment by alfie013** [comment]
@JediKev 

Thanks for the information. Can you please show me how you do the auto-collab?

Regards,

**Comment by JediKev** [comment]
@alfie013

It’s easy. First, add all the Users you want the main Collaborator to be added on their tickets to an Organization. Next, you add the User you want to be the main Collaborator to the same Organization. Then you click the name of the Organization in the Organization list and click the name with the pencil icon. Click Settings tab and select the main Collaborator in the Primary Contact select box. Next check the box next to Primary Contacts under Automated Collaboration section and Save Changes. Now any ticket that the Users in the Organization create will have the Primary Contact added as a Collaborator.

Cheers.
