### ISSUE TITLE
Error accessing to osTicket using IP

### ISSUE THREAD

**Issue by nanoterremoto** [osTicket/osTicket#4463]
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch? Yes
* [x] Do you have any errors in the PHP error log, or javascript console? No
* [x] Did you check the [osTicket forums](http://osticket.com/forum/categories)? Yes
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported? Yes

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

Hi,

I´m having some errors when I try to access to my osticket. I use nginx as webserver because Apache2 doesn´t work. (Image attached https://ibb.co/eZXEdK)
When I access to osTicket at the localhost using nginx there is no problem but when I use the IP, ip_address/osticket/upload, I receive a 403 forbbiden error.

How could I repair this to access correctly to the app from all PC on my network?

Thanks.

### Steps to Reproduce

1. [First Step] I have installed a new VM with Ubuntu 16.04 and a new installation of osticket 1.10.1
2. [Second Step] Installation php, apache and nginx (problems with apache2) and mysql
3. [and so on...] I can access with nginx at the localhost but not from any other pc on the same network.

**Expected behavior:** [What you expected to happen]
I would like to connect to my osticket installation from every pc in my network

**Actual behavior:** [What actually happened]
If i use nginx, 403 fobbiden, if I use apache2, wierd characters (https://ibb.co/eZXEdK)
### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

I have used this guide to install osticket
https://www.vultr.com/docs/how-to-install-osticket-on-ubuntu-16-04

**Comment by JediKev** [comment]
@nanoterremoto 

Unfortunately, we do not support NGINX as a webserver. We only support Apache or IIS at the moment. Please refer to our System Requirements (under the "What's Next?" title):
http://osticket.com/download

If you would like to use NGINX anyways please surf our [Forum](http://osticket.com/forum) for posts that might help you or make a post yourself if you do not see what you are looking for (look very close before making your own post).

Please close this as this is an issue with an unsupported webserver.

Cheers.

**Comment by weedget** [comment]
Mess on screenshot look like you don't have enabled short tags in php configuration

**Comment by nanoterremoto** [comment]
@JediKev 

I know that nginx is not supported but Apache didn´t work. Anyway I´m going to close this thread because I fix the problema at last.

Thanks.
