### ISSUE TITLE
Email to ticket creator not sent if ticket is auto assigned.

### ISSUE THREAD

**Issue by dbinoj** [osTicket/osTicket#447]
If the ticket creator selects a help topic which has been configured to auto assign tickets to a team, the creator does not get an mail with ticket ID and other details. 
But if the ticket creator selects a help topic which is not configured to auto assign, the creator gets New Ticket Notice. I checked the settings 2-3 times, am I missing something?

**Comment by warry69** [comment]
i have same problem with @piotrczerwiec ... only not send to client who create new ticket... any solution?
