### ISSUE TITLE
New ticket submission error on topic set as site default

### ISSUE THREAD

**Issue by Shadow00Caster** [osTicket/osTicket#4473]
v1.11.0 rc1

When a help topic is set as default and a ticket submission is done, the page returns validation errors for required fields when submitting, upon filling the fields back in and submitting, it processes as expected.  If you switch topics from the drop down first and then select the topic that loaded with the open new ticket page (site default selected) it will work on first submit.

Setting no default site help topic eliminates the issue, but still exists none the less.

**Comment by ntozier** [comment]
There is no 1.11.1 version.
Please go to Admin panel -> Dashboard -> Information and provide environment details.

**Comment by Shadow00Caster** [comment]
@ntozier sorry v1.11.0 rc1, corrected original.

**Comment by JediKev** [comment]
@Shadow00Caster 

This should address the issue:
https://github.com/osTicket/osTicket/pull/4484

Please test and let me know.

Cheers.

**Comment by Shadow00Caster** [comment]
@JediKev 

Pulled latest develop-next and issue still persisted.

**Comment by JediKev** [comment]
@Shadow00Caster 

The pull I referenced is NOT merged yet....you'll have to apply the fix and then test.

Cheers.

**Comment by Shadow00Caster** [comment]
@JediKev 

Apologies, I made the change and that fixed the problem.
