### ISSUE TITLE
New tickets created - Open Dash Board go to middle of page

### ISSUE THREAD

**Issue by jaysydney** [osTicket/osTicket#4478]
#
Version 1.11-rc1 - When tickets are created in the OpenPage go to the middle of the page and dont go to the top of the page.
It use to default to newest ticket in, (last updated) now it goes in sequence of ticket number (which is not always in order of how you get a ticket in.

How to set it back as a default in open ticket page to go to "Last updated" without clicking on the arrow at the top under last updated. Default it back like it use to be!

**Comment by JediKev** [comment]
I don’t understand. Screenshots?

**Comment by jaysydney** [comment]
![issue](https://user-images.githubusercontent.com/42688497/44614805-7d7ccd00-a86e-11e8-802c-e5a3400d49bf.jpg)

**Comment by jaysydney** [comment]
see how its in ticket number default and not last updated. Unless everytime i click on "last updated" tab at the top it will default back to ticket number sequence. never use to be like that.

**Comment by JediKev** [comment]
@jaysydney

Click the setting wheel next to the queue name and then click Edit. Click Settings tab and change Default Sorting to whatever you want.

Cheers.

**Comment by JediKev** [comment]
@jaysydney

You’re using latest pull from `develop-next` right? If not, you should be using that to test. 

Cheers.

**Comment by jaysydney** [comment]
where is that at?

**Comment by JediKev** [comment]
@jaysydney

Here, on GitHub. Click Code tab, switch branch to `develop-next`, and clone via URL or click download.

Cheers.

**Comment by jaysydney** [comment]
done.. still same issue

**Comment by jaysydney** [comment]
anyone?
