### ISSUE TITLE
how to i edit "New Internal Activity Alert: " in Ticket Settings and Options (Under main Setting menu). i want to sent alert to All agent when anyone update in ticket. 

### ISSUE THREAD

**Issue by bdharmesh3** [osTicket/osTicket#4480]
how to i edit "New Internal Activity Alert: " in Ticket Settings and Options (Under main Setting menu). i want to sent alert to All agent when anyone update in ticket. 

my requirement is when every any one update the ticket public department agent get alret. 

![capture](https://user-images.githubusercontent.com/42741889/44662978-d7c38c80-aa2c-11e8-845d-b00a1ce29e90.JPG)

**Comment by JediKev** [comment]
@bdharmesh3 

As you can see from your screenshot you can only send the "New Internal Activity Alert" to either the Last Agent that responded on the ticket, the Agent/Team that's assigned to the ticket, and/or the Manager of the ticket's Department.

There is no option for "All Agents" as not all agents will have access to all Departments/tickets.

Cheers.

**Comment by bdharmesh3** [comment]
@JediKev 
Hi, 

Thanks your update, that point clearly understood but our requirement is like anyone like ticket creator or any agent sent / update ticket than pubilc (Top level Department) Agent will get a notification so they dont have to check every ticket. 

where we can find that kind of settings or menu. 

Thanks & Regards,

**Comment by bdharmesh3** [comment]
i forgot to mention that our public department agent have all department access(in our case there is 3 department). so they can see all department tickets.

**Comment by JediKev** [comment]
@bdharmesh3 

You could add all Agents you want to a Team and then automatically assign the team to every ticket via Help Topic or Ticket Filter. This way the alert will be sent out to the assigned Agent/Team which will be all the Agents you chose to be in the Team.

Cheers.

**Comment by bdharmesh3** [comment]
tanks Jedikev. 

My Issue is resolved.
