### ISSUE TITLE
dashboard not showing

### ISSUE THREAD

**Issue by adinos101** [osTicket/osTicket#4483]
I upgraded from 1.8 to 1.10.4 now the dashboard is not showing up.. Am i missing something?... I already checked the Stats on Agent, Permissions, miscellaneous. Thank you.

Server Information
--
osTicket Version | v1.10.4 (035fd0a) —  Up to date
Web Server Software | Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.23
MySQL Version | 10.1.13
PHP Version | 5.6.23

![image](https://user-images.githubusercontent.com/42767788/44713477-c9857700-aae5-11e8-8944-b935a2e91444.png)

![image](https://user-images.githubusercontent.com/42767788/44713542-ef128080-aae5-11e8-8e94-73d2403cf88a.png)

### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [ ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

**Comment by JediKev** [comment]
@adinos101 

I'm unable to replicate this issue with an upgraded 1.10.4 instance. I notice that the footer of the tabs is incomplete looking to me like there is an error causing the rest of the tabs template to not load. Please post any errors found in Apache error logs, PHP error logs, MySQL error logs, osTicket error logs, and/or browser console.

Cheers.

**Comment by JediKev** [comment]
@adinos101

There you go. Your issue is your PHP `max_execution_time` setting. Apparently you have a crap ton of data to sort through and it’s exceeding that limit. You could fix this temporarily by bumping up your PHP `max_execution_time` setting.

Just a side note, we have addressed some Dashboard performance issues in `1.11.0rc-1` which should make the Dashboard load a lot faster.

Cheers.

**Comment by adinos101** [comment]
Thank you so much Jedikev, it works now, set the execution time to 300 in php.ini.
