### ISSUE TITLE
New Ticket Name / phone number ignored for existing contact

### ISSUE THREAD

**Issue by duelafn** [osTicket/osTicket#4485]
### Prerequisites

* [X] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [X] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [X] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

The "Open a New Ticket" form for anonymous (not logged in) users includes a name and phone number field. Text entered into these fields are discarded if the email field matches an existing contact.

This results in customer confusion and we are receiving angry messages because we are not calling the correct phone number (a number which the customer did in fact enter into the form).

### Steps to Reproduce

1. Create a new ticket with Email: foo@example.com; Name: Alice; Phone: 555-5555
2. Create a new ticket with Email: foo@example.com; Name: Bob; Phone: 555-6666
3. Look at the tickets in the staff control panel

**Expected behavior:** Name and phone numbers provided are visible (somewhow) in each of the tickets.

**Actual behavior:** Both tickets are from "Alice" and the alice user has phone number 555-5555.

### Real Examples

There are a few ways in which this manifests for us:

* The first time a user files a ticket, they enter their office number, but on their second ticket they enter their cell number or another number (because they are out of office or at a client's location). In this case, we need the new phone number to appear on the ticket. Updating the user contact info wouldn't be bad, but is unsafe (see below)

* The user enters a shared email address (for instance, sales@example.com or service@example.com). In this case, we need both the name and phone number to be specific to the ticket and definitely do not want the user information to be updated.

* The first time the user files a ticket they leave the phone number blank, because they don't need a call-back. The second time they need a call-back, so they enter a phone number, but the ticket system doesn't save it. In this case, updating the user contact info would be useful and perhaps not too unsafe (see below).

### Avoiding data loss

I really am *not* asking for the user contact information to be updated each time a new name or number is entered into the new ticket form. This would be unsafe since it would allow anyone to overwrite an existing user's name or phone number just by knowing their email address. That would be bad. The only situation where I feel it might be acceptable to change the user record is when the phone number is blank and they provide a phone number on a later ticket.

I think the only reaonable way to preserve this information are as additional fields displayed in the ticket itself.

### Specific implementation suggestions

Our use case would prefer that the ticket "From" field (in in the ticket lists) still show the original user name and the per-ticket name and phone number shown underneath the User/Email fields in the ticket view. Of course, the name need only be shown if it differs from the user contact info.

An alternative would be to redesign the form field in such a way that it would avoid customer confusion, but added text isn't very user friendly and an (ajax) callback that queries whether the email exists opens the database up to email sniffing/harvesting (bad). Thus, we would prefer that the fields simply be added to the ticket data.

Thank you for your consideration!

### Versions

At least v1.9.12 (19292ad) through v1.11.0-rc1-200-g33daada

**Comment by ntozier** [comment]
That is because they have the same email address.  osTicket decides that it does not need to make a new account because accounts  are de-duplicated on email address.  This is on purpose.

**Comment by duelafn** [comment]
Yes, I'm aware of that and am not asking for that to change. However, these fields are being filled out by the customer and so they expect us to be able to see it. Since it is unsafe to update the user profile, I'm asking that the additional information be saved in the ticket itself since (as shown in the examples), this information is sometimes ticket-specific.

**Comment by duelafn** [comment]
Hello again, Today I looked into the code and table structures involved and have an idea of how this could actually be implemented within our framework.

The user view of opening a new ticket (when not logged in) is a combination of the "Contact Information" and "Ticket Details" forms, however, if the email address is already registered, the rest of the "Contact Information" form is discarded leading to a sub-optimal user experience (just rephrasing my original issue in the current language).

"Help Topics" are built from a collection of forms ("Ticket Details" and any custom forms). If the "Contact Information" form were one of the sub-forms of a help topic (either by default or as an option), then all or some of the contact fields could be included in the ticket.

In the UI, when opening a new ticket, the "Contact Information" form is already included, so it should not be included again, but as a help topic sub-form, a site administrator can configure which (if any) contact information fields are preserved in the ticket data.

Does this sound like a reasonable way to address this issue?

**Comment by JediKev** [comment]
@duelafn 

It will not work like this as the backend storage is completely different...

The Ticket Details and Custom form data is stored in `ost_form_entry_values` whereas Contact Information form data is stored in `ost_user__cdata`. You could update the user info each time they submit the ticket but then that would change the main-level account info as well. So if a user fills out new ticket Contact info with legit existing email but dummy data it'll overwrite the main account data. So keeping it as-is is best for now imo.

Cheers.
