### ISSUE TITLE
Creating new Ticket when User / Department transfer replay. 

### ISSUE THREAD

**Issue by bdharmesh3** [osTicket/osTicket#4489]
When we transfer a ticket to other department and they revert back on mail on that time its create a new ticket.

we have recently upgraded Os ticket from 1.9 to 1.10. in earlier version it's working but in new 1.10 it's not working.

Thanks in Advance

**Comment by ntozier** [comment]
Huh? revert?
Exact version of osTicket?
Environment details?

**Comment by bdharmesh3** [comment]
– Wampserver 3.1.0 64 bit x64 
– Apache 2.4.27 
– PHP 5.6.31, 7.0.23, 7.1.9 
– MySQL 5.7.19 
– MariaDB 10.2.8 
– PhpMyAdmin 4.7.4 
– Adminer 4.3.1 
– PhpSysInfo 3.2.7
– OS ticket 1.10 
– Operating system (Windows 2012 R2 x64 Bit)

**Comment by JediKev** [comment]
@bdharmesh3 

What exactly do you mean by the following???
>When we transfer a ticket to other department and they revert back on mail on that time its create a new ticket.

Cheers.
