### ISSUE TITLE
Sending activation email problem

### ISSUE THREAD

**Issue by Chest3r14** [osTicket/osTicket#4491]
### Prerequisites

* [N] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [Y] Do you have any errors in the PHP error log, or javascript console?
* [Y] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [Y] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

Hello,

I have some strange problem, with sending activation email for new created users. When I hit the "send activation email" button, I got error 500. I have some errors in my error log:

[Thu Aug 30 11:55:51.208759 2018] [:error] [pid 47917] [client xxx.xxx.xxx.xx:22442] PHP Fatal error:  Cannot use object of type EmailAddress as array in /var/www/html/osticket/upload/include/pear/Mail/mimePart.php on line 968, referer: https://site/scp/users.php?id=105
[Thu Aug 30 11:55:51.208812 2018] [:error] [pid 47917] [client xxx.xxx.xxx.xx:22442] PHP Stack trace:, referer: https://site/scp/users.php?id=105
[Thu Aug 30 11:55:51.208832 2018] [:error] [pid 47917] [client xxx.xxx.xxx.xx:22442] PHP   1. {main}() /var/www/html/osticket/upload/scp/users.php:0, referer: https://site/scp/users.php?id=105
[Thu Aug 30 11:55:51.208845 2018] [:error] [pid 47917] [client xxx.xxx.xxx.xx:22442] PHP   2. UserAccount->sendResetEmail() /var/www/html/osticket/upload/scp/users.php:70, referer: https://site/scp/users.php?id=105
[Thu Aug 30 11:55:51.208858 2018] [:error] [pid 47917] [client xxx.xxx.xxx.xx:22442] PHP   3. UserAccount->sendUnlockEmail() /var/www/html/osticket/upload/include/class.user.php:1137, referer: https://site/scp/users.php?id=105
[Thu Aug 30 11:55:51.208869 2018] [:error] [pid 47917] [client xxx.xxx.xxx.xx:22442] PHP   4. Email->send() /var/www/html/osticket/upload/include/class.user.php:1185, referer: https://site/scp/users.php?id=105
[Thu Aug 30 11:55:51.208881 2018] [:error] [pid 47917][client xxx.xxx.xxx.xx:22442] PHP   5. Mailer->send() /var/www/html/osticket/upload/include/class.email.php:180, referer: https://site/scp/users.php?id=105
[Thu Aug 30 11:55:51.208892 2018] [:error] [pid 47917] [client xxx.xxx.xxx.xx:22442] PHP   6. Mail_mime->headers() /var/www/html/osticket/upload/include/class.mailer.php:543, referer: https://site/scp/users.php?id=105
[Thu Aug 30 11:55:51.208904 2018] [:error] [pid 47917] [client xxx.xxx.xxx.xx:22442] PHP   7. Mail_mime->encodeHeaders() /var/www/html/osticket/upload/include/pear/Mail/mime.php:1114, referer: https://site/scp/users.php?id=105
[Thu Aug 30 11:55:51.208915 2018] [:error] [pid 47917] [client xxx.xxx.xxx.xx:22442] PHP   8. Mail_mime->encodeHeader() /var/www/html/osticket/upload/include/pear/Mail/mime.php:1328, referer: https://site/scp/users.php?id=105
[Thu Aug 30 11:55:51.208927 2018] [:error] [pid 47917] [client xxx.xxx.xxx.xx:22442] PHP   9. Mail_mimePart::encodeHeader() /var/www/html/osticket/upload/include/pear/Mail/mime.php:1352, referer: https://site/scp/users.php?id=105
[Thu Aug 30 11:55:51.208989 2018] [:error] [pid 47917] [client xxx.xxx.xxx.xx:22442] PHP  10. Mail_mimePart::explodeQuotedString() /var/www/html/osticket/upload/include/pear/Mail/mimePart.php:857, referer: https://site/scp/users.php?id=105

I do send and receive email for ticket creations, updates, closure and everything else, so the problem is not in my email settings.

Please, assist...

### Versions

osTicket Version | v1.11.0-rc1 (e321982) —  Up to date
Web Server Software | Apache/2.4.18 (Ubuntu)
MySQL Version | 10.0.34
PHP Version | 5.6.37-1+ubuntu16.04.1+deb.sury.org+1

**Comment by JediKev** [comment]
@Chest3r14 

Please use latest pull from `develop-next` and retest as we have addressed most of these issues already.

Cheers.
