### ISSUE TITLE
Attachements are not attached randomly 

### ISSUE THREAD

**Issue by huehnerhose** [osTicket/osTicket#4492]
Hi,

up front: I can't reproduce this issue, it happens randomly :( Best I hope for are hints where to look for a better understanding. That said:

We use template emails with pre attached files. Inside a ticket I try to answer by selecting the template. In the editor all files are shown. Hitting send is followed by two scenarios:
1st the spinner works a little bit and everything is sent. 
2nd the spinner is blazingly fast and no attachments are sent. Reopening the ticket there are no attachments at the bottom of my answer - like i never selected any file at all. 

When I add an additional file to the attachments, in the case of "template files are not sent" this additional file gets send. 

### Versions

osTicket-Version | v1.10.4 (035fd0a) 
-- | --
Server-Software | nginx/1.10.3
MySQL-Version | 5.7.23
PHP-Version | 7.0.28-0ubuntu0.16.04.1

**Comment by JediKev** [comment]
@huehnerhose 

One issue I see right off the bat is your PHP version. osTicket does not support PHP 7+ especially the `1.10.x` series. We hope to be compatible with at least PHP 7.1.x and down in the official, non-release candidate version of v1.11.0. (coming soon). In the meantime you can try downgrading to PHP 5.6.x and retest.

Another issue I see is your webserver. We do not support NGINX _at all_ (it takes some extra steps, setup, etc.). We only officially support Apache and IIS. I would try making an installation with Apache & PHP 5.6 and retest your issues. Please refer to our [Prerequisites here](http://osticket.com/download) under the System Requirements tab (right-hand sidebar).

Also, if you find any _**related**_ errors via PHP, Apache, MySQL, osTicket logs, or browser logs please post them here as they would greatly help us debug what's going on.

Cheers.

**Comment by huehnerhose** [comment]
Thanks for the answer, sorry for the long silence. 

I migrated osTicket, now I use:

osTicket-Version | v1.10.4 (035fd0a) —  Aktuell
-- | --
Server-Software | Apache/2.4.10 (Debian)
MySQL-Version | 10.3.9
PHP-Version | 5.6.37

Unfortunately there are no php or mysql errors at all. At the moment I can't send _any_ attachement from a template only newly uploaded files.

**Comment by JediKev** [comment]
@huehnerhose 

This is very strange... I was able to replicate this just now multiple times in a row, I added some debug info, tested it, and then I removed all my debug info (`var_dump`, `die`, etc.) it all works just fine again every time... super strange. Will keep looking at this to see if I can get it to replicate again.

Cheers.
