### ISSUE TITLE
Custom Forms not Rendering Correctly 1.10.4

### ISSUE THREAD

**Issue by Nick-C** [osTicket/osTicket#4493]
When creating a custom form you use the provided form which includes options for formatting such as lists, after saving this and applying it to a help topic the formatting doesn't get rendered but just presented as the underlying html - even pressing enter in the creation form results in a <br /> being entered thus there is no way to have a line break in a custom form (as attempting to add one results in the html tag showing).

This has also been mentioned on the forums and regarded as not a bug however since the formatting controls are provided in the creation page they should carry through to being displayed (currently you can't even have line breaks which definitely seems like a bug)

http://osticket.com/forum/discussion/92681/html-formatting-of-custom-forms-not-displaying-correctly

See below for examples and repro steps:

Create a new custom form and use the provided formatting options:

![chrome_2018-08-31_15-30-40](https://user-images.githubusercontent.com/45155/44918675-7c96e000-ad33-11e8-93ca-139893986ba7.png)

Then attach it to a help topic:

![chrome_2018-08-31_15-36-58](https://user-images.githubusercontent.com/45155/44918819-d13a5b00-ad33-11e8-9599-4a586d81f1b4.png)

And when creating a new ticket:

![chrome_2018-08-31_15-39-16](https://user-images.githubusercontent.com/45155/44918925-13fc3300-ad34-11e8-933a-73d84dfe9276.png)

**Comment by JediKev** [comment]
@Nick-C 

This should fix it:
https://github.com/osTicket/osTicket/pull/4494

Cheers.
