### ISSUE TITLE
How to change Date format

### ISSUE THREAD

**Issue by johnkalangha** [osTicket/osTicket#4497]
osticket V1.10.4
php 5.6 
apache

How to chnage dateformat of this datetime picker in ticket to MM/DD/YYYY or MMM/DD/YYYY

![image](https://user-images.githubusercontent.com/30627667/44943106-415be600-adf3-11e8-8dda-bc867f3b0af1.png)

**Comment by JediKev** [comment]
@johnkalangha 

Please don’t post questions on GitHub. This is a place for issues or feature requests only. If you would like to ask a question about configurations, etc. please post on our [Forum](http://osticket.com/forum).

With that being said it’s super easy:
**Admin Panel > Settings > System > Date and Time Options > Advanced > Date Format**
![c0f097d4-8769-4f14-9fef-9cc65cc6e507](https://user-images.githubusercontent.com/11823401/44947623-490c9200-add5-11e8-9806-ad0065840a5c.jpeg)

Cheers.

**Comment by johnkalangha** [comment]
thanks sir
