### ISSUE TITLE
Translation for required fields

### ISSUE THREAD

**Issue by nathaelr** [osTicket/osTicket#4499]
### Description

Very small error : required fields are not translated in alert message when not filled.

### Steps to Reproduce

1. Create translation of a required field for a ticket
![image](https://user-images.githubusercontent.com/17726890/45019415-9171bd00-b02c-11e8-8a88-ef34b8554dea.png)

2. Connect to portal, create new ticket in the other language
3. Don't fill the required field
4. In the message "[field] is mandatory" the field is not translated.

![capture](https://user-images.githubusercontent.com/17726890/45019319-5079a880-b02c-11e8-9472-04b8cee02143.PNG)

### Versions
version d'osTicket | v1.10.4 (035fd0a) 
Logiciel serveur Web | Microsoft-IIS/10.0
Version de MySQL | 5.7.23
Version PHP | 5.6.31

**Comment by JediKev** [comment]
@nathaelr 

There is already a fix for this here:
https://github.com/osTicket/osTicket/pull/4049

**Note:**
Before submitting an issue report, please do a recursive search on Github as well as our Forum for an existing issue report/fix. This is to prevent making duplicate issue reports and to prevent re-opening an issue that has already been addressed.

Cheers.
