### ISSUE TITLE
Can't install osTicket on apache server using Xampp

### ISSUE THREAD

**Issue by MrSigne** [osTicket/osTicket#4505]
### 

- Prerequisite

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [ ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

[After filling the osTickect installaton form, my web brower always shows me the error message "Apache can't handle this request". I've downloaded several versions of osticket but i always have the same error.]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [I expected it to go to the admin configuration panel.]

**Actual behavior:** [Showed me the error message "apache can't handle this request"]

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.
[I'm using windows 8.1 (64bit) and google chrome Version 68.0.3440.106]

**Comment by JediKev** [comment]
@MrSigne 

You have not provided all the appropriate information. What version of osTicket are you trying to install? Where did you download it from? What version of PHP, MySQL, and Apache are you using? Any errors via PHP, MySQL, and/or Apache error logs? What about errors in the browser console?

Cheers.

**Comment by MrSigne** [comment]
It's OK. I've succeeded in resolving my problem though I don't really know
how.
Thanks
