### ISSUE TITLE
can we add default view setting to 90 % on below path so every one can view full page ticket page.

### ISSUE THREAD

**Issue by bdharmesh3** [osTicket/osTicket#4506]
https://github.com/osTicket/osTicket/blob/cd104aac9a254cd5fa1c194db8383dde7f8495f8/scp/css/scp.css#L127

#container {
    width:90%;
    margin:0 auto 20px auto;
}

**Comment by JediKev** [comment]
@bdharmesh3

Not at the moment. UI/UX changes are coming in 2.0. Stay tuned.

Cheers.
