### ISSUE TITLE
PDF attachment get broken on upload

### ISSUE THREAD

**Issue by tong2x** [osTicket/osTicket#4507]
### Prerequisites

* [n/a] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [n] Do you have any errors in the PHP error log, or javascript console?
* [y] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [y] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

PDF attachment gets broken on upload. but other files (and other PDFs) are ok not really sure why certain pdf are broken on upload but the file is readable. the same file if sent via say gmail is ok but not with osticket develop-next built 09/10/18

### Versions
 osticket develop-next built 09/10/18

Web Server Software | Apache
MySQL Version | 10.0.35
PHP Version | 7.0.31
windows 8.1
[forAA.pdf](https://github.com/osTicket/osTicket/files/2366072/forAA.pdf)

**Comment by JediKev** [comment]
@tong2x 

Unfortunately, I cannot replicate this issue using latest `develop-next`.

**Response w/ Attachment:**
<img width="423" alt="screen shot 2018-09-17 at 15 17 08" src="https://user-images.githubusercontent.com/11823401/45648044-09100500-ba8d-11e8-8889-fd779f6f3804.png">

**Email w/ Attachment:**
<img width="256" alt="screen shot 2018-09-17 at 15 17 15" src="https://user-images.githubusercontent.com/11823401/45647983-e54cbf00-ba8c-11e8-9a1a-8d1b9528c566.png">

Cheers.

**Comment by tong2x** [comment]
copy I think same with my other issue, will wait for rc2 and retest
thank you JediKev
