### ISSUE TITLE
authentication tokens / Require email verification

### ISSUE THREAD

**Issue by tong2x** [osTicket/osTicket#4510]
### Prerequisites
* [n/a ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [n] Do you have any errors in the PHP error log, or javascript console?
* [y] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [y] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description
department notice setting not being followed

### Steps to Reproduce
admin panel-> setting-> users-> settings
Authentication Token: [check] Enable use of authentication tokens to auto-login users
Client Quick Access: [uncheck] Require email verification on "Check Ticket Status" page

**Expected behavior:** [What you expected to happen]
click on email link should open the ticket.

**Actual behavior:** [What actually happened]
just shows, a user and password prompt
even the check ticket status, seems not sending email token or link

### Versions
osTicket Version | v1.11.0-rc1 (e321982) —  Up to date
Web Server Software | Apache
MySQL Version | 10.0.35
PHP Version | 7.0.31
windows 8.1

**Comment by JediKev** [comment]
@tong2x 

I replicated your exact settings and cannot reproduce this issue using latest pull from `develop-next`. I did notice [in the code](https://github.com/osTicket/osTicket/blob/develop-next/include/class.client.php#L63) that if the ticket has _any_ collaborators it will not send out the auth token as the collaborator(s) could potentially login as and fake the real User.

Basically, just make sure the ticket has no collaborators and it will work just fine (tested this using latest `develop-next` and it works perfectly).

Cheers.
