### ISSUE TITLE
Keep <style> tag on HTML email templates

### ISSUE THREAD

**Issue by adamjamespotter** [osTicket/osTicket#4511]
Hi,

Is there a way in which I can stop the <style> tag from being removed from email templates?

Thanks

**Comment by JediKev** [comment]
@adamjamespotter 

Remove the sanitizing or add style tags to be allowed in HTMLawed...but then you'll be vulnerable to XSS. Good luck!

Cheers.

**Comment by adamjamespotter** [comment]
Could you point me to where the sanitising happens for the email templates?

Thanks

**Comment by JediKev** [comment]
@adamjamespotter 

**Sanitization On Save:**
https://github.com/osTicket/osTicket/blob/develop/include/class.template.php#L634

**Sanitization Method:**
https://github.com/osTicket/osTicket/blob/develop/include/class.format.php#L338-L347

This method of course calls other methods, which calls other methods, etc. running the template through a whole slew of sanitization.

Cheers.

**Comment by adamjamespotter** [comment]
Hi Kev,

Thanks for the prompt reply.

Rather that removing the sanitation, are there any other alternatives for getting the emails to pull CSS, for instance could I create a new CSS file and link the new CSS file to the SCP header file?

At present do the email templates pull any CSS from any files in osTicket?

I've read all the previous "issues" regarding custom email templates but I just need to know if there are any simple workaround to adding media queries to the email templates.

Thanks Again,
Adam

**Comment by JediKev** [comment]
@adamjamespotter 

>At present do the email templates pull any CSS from any files in osTicket?

The only styling used in templates currently are things like `<strong>`, `<em>`, `<h3>`, etc.

You may add styling to any block of text by simply adding `<div style=""></div>` around the text and adding the styling to the `style` attribute. 👍 (this only works for templates currently)

Cheers.
