### ISSUE TITLE
[HELP] Installing and Connecting to mysql

### ISSUE THREAD

**Issue by johnkalangha** [osTicket/osTicket#4518]
hello anyone can help me, im just trying to install osticket in my VMware, this is the scenario

2 servers im using, 1 server is for osticket web server and the other 1 is for mysql database

when i tried to setup it always not connected to mysql and i try to connect in navicat but this is the error

**

> 2013 lost connection to mysql server at 'reading initial communication packet', system error 2 "no such file or directory"

please help mo

**

**Comment by JediKev** [comment]
@johnkalangha

This is a server/mysql configuration (environment) issue. I would’ve posted this on the forums...

Anyways, try the below links for possible resolution:
- https://www.google.com/amp/s/redhatme.wordpress.com/2015/03/23/how-to-solve-lost-connection-to-mysql-server-at-reading-initial-communication-packet-system-error-0/amp/
- https://stackoverflow.com/questions/21091850/error-2013-hy000-lost-connection-to-mysql-server-at-reading-authorization-pa
- https://stackoverflow.com/questions/5755819/lost-connection-to-mysql-server-at-reading-initial-communication-packet-syste/46480791

Cheers.

**Comment by johnkalangha** [comment]
thanks sir
