### ISSUE TITLE
Can not send confirmation email

### ISSUE THREAD

**Issue by ldecoker** [osTicket/osTicket#4519]
### Description

It's not possible to send confirmation email to end user as an agent.
Issue seems to come from the function sendUnlockEmail in class.user.php : 
`$email->send($this->getUser()->getEmail(),
            Format::striptags($msg['subj']), $msg['body']);` 

The first parameter is a EmailAdsress object but the send function is expected a string:

```
function send($to, $subject, $message, $attachments=null, $options=null, $cc=array()) {

        $mailer = new Mailer($this);
        if($attachments)
            $mailer->addAttachments($attachments);

        return $mailer->send($to, $subject, $message, $options, $cc);
    }
```

### Steps to Reproduce

1. Create a user as an agent
2. Send confirmation email to the user

**Expected behavior:** [What you expected to happen]
Mail should be sent out to the user.

**Actual behavior:** [What actually happened]
PHP Fatal error:  Cannot use object of type EmailAddress as array in include/pear/Mail/mimePart.php on line 968

### Versions

osTicket : v1.11.0-rc1 (e321982)
OS: CentOS 7.2
Mysql: MariaDB 10.1.35
PHP: 5.6.37

**Comment by JediKev** [comment]
@ldecoker 

Please use the latest pull from `develop-next` as we have addressed a _ton_ of RC 1 issues in it.

Cheers.

**Comment by ldecoker** [comment]
Look like the code for this class is the same on develop-next.

**Comment by JediKev** [comment]
@ldecoker 

That doesn't mean anything...other files could be using the function output differently... please retest using the latest pull from `develop-next`.

Cheers.

**Comment by ldecoker** [comment]
Ok done it and you were right. Problem was fixed in the develop-next branch. Thx ! I will close this issue.
