### ISSUE TITLE
Display user name based on Name formatting

### ISSUE THREAD

**Issue by ldecoker** [osTicket/osTicket#4520]
### Description

In admin panel, you can configure the user name formatting "Settings -> Users -> Settings -> General Settings". But this does not seem to be used.

#### Steps to reproduce

1. define name formatting to "First Last"
2. go to user panel. Only the lastname is displayed (the name field from the ost_user table)
3. go to agent panel. Check the users list (Users -> User Directory). In the Name column, only the lastname is displayed.

**Expected behavior:** [What you expected to happen]
Display user name based on name formatting.

**Actual behavior:** [What actually happened]
Only the name field is displayed.

### Versions

Osticket : Develop-next.

**Comment by JediKev** [comment]
@ldecoker 

I cannot reproduce this using the latest `develop-next`. It works as intended for me..

**Name Formatting:**
<img width="364" alt="screen shot 2018-09-17 at 13 22 22" src="https://user-images.githubusercontent.com/11823401/45642700-a0219080-ba7e-11e8-93d3-7c4d4efdbdbb.png">

**Client Portal:**
[Header]
<img width="415" alt="screen shot 2018-09-17 at 13 30 42" src="https://user-images.githubusercontent.com/11823401/45642694-95ff9200-ba7e-11e8-9b7c-a91a746609ec.png">

[Thread Entry]
<img width="340" alt="screen shot 2018-09-17 at 13 30 53" src="https://user-images.githubusercontent.com/11823401/45642688-91d37480-ba7e-11e8-884a-506f9a6003ff.png">

**Ticket Queue:**
<img width="159" alt="screen shot 2018-09-17 at 13 22 30" src="https://user-images.githubusercontent.com/11823401/45642685-8e3fed80-ba7e-11e8-8169-a4c54d38780d.png">

**User Directory:**
<img width="575" alt="screen shot 2018-09-17 at 13 22 45" src="https://user-images.githubusercontent.com/11823401/45642683-8aac6680-ba7e-11e8-814d-16e1fc0c3faa.png">

Cheers.

**Comment by ldecoker** [comment]
hum not in my case. Could you please tell me what you have in database in the user table - field "name" ? Thx!

**Comment by ldecoker** [comment]
I indeed did not changed anything

**Comment by JediKev** [comment]
@ldecoker 

_Someone_ must have changed it as the installer is indeed correct:
https://github.com/osTicket/osTicket/blob/develop/include/i18n/en_US/form.yaml#L50-L57

Cheers.

**Comment by ldecoker** [comment]
I am the only one accessing my servers so believe me, no one changed it ;)

**Comment by ldecoker** [comment]
could it be because of the french language pack?

**Comment by JediKev** [comment]
@ldecoker 

Did you _install_ in French? If so, yes that's the issue...as of now you cannot install osTicket under a different language as it messes up due to the format of the YAML files (we are working on this). You have to install in English first THEN add the language pack afterwards.

I would suggest that you start over from English install as your DB is still messed up.

Cheers.

**Comment by ldecoker** [comment]
I am quite sure to have installed it first in english and then I have added the french package. In the doubt, I will redo it completely.

Thx!
