### ISSUE TITLE
OsTicket Version  (v1.11.0-rc1 - develop-next )  - Cann´t Post Reply

### ISSUE THREAD

**Issue by meinsteren** [osTicket/osTicket#4522]
Hello everyone,

Cann´t "Post Reply".
---------------------------------------------------------------------------------
Server Information
OsTicket Version  (v1.11.0-rc1 - develop-next ) 
commit 4081007fa915c37eb9892d31af7fa5200354882f
Web Server Software Apache/2.4.33 (Win32) OpenSSL/1.0.2n PHP/5.6.35
MySQL Version 10.1.31
PHP Version 5.6.35
![version](https://user-images.githubusercontent.com/22029754/45745463-6c667800-bbf0-11e8-983f-1077236e2bce.png)

Apache Error Log:
there is no message......

![print](https://user-images.githubusercontent.com/22029754/45745860-48effd00-bbf1-11e8-9c46-cec4186cc2f8.jpg)

**Comment by JediKev** [comment]
@meinsteren 

The issue is caused by you merging an unfinished pull request.

Please revert your changes back to the tip of `develop-next`.

Cheers.
