### ISSUE TITLE
Select Query Statement to get additional data

### ISSUE THREAD

**Issue by mohankarunasiri** [osTicket/osTicket#4527]
Hi All,
Please guide me to link following tables from MYSQL Select query 

1.  ost_list_items

2. ost_ticket

My version

v1.10.4 (035fd0a)

**Comment by mohankarunasiri** [comment]
Thanks JediKev but at this time I need a MYSQL query, 

 have created following custom forms forms in osTicket.
![custom forms-01](https://user-images.githubusercontent.com/18019138/45926781-8f24c380-bf45-11e8-9f61-b09efb2636b9.png)

And attached custom list
![issue details-02](https://user-images.githubusercontent.com/18019138/45926790-ce531480-bf45-11e8-8d35-47bbceedf194.png)
![purchased details-03](https://user-images.githubusercontent.com/18019138/45926795-d8751300-bf45-11e8-9bc9-012a7f2dc5ce.png)

Finally above forms attached with Help Topic
![help topic attached forms-04](https://user-images.githubusercontent.com/18019138/45926807-ff334980-bf45-11e8-9c5e-94bafb9b0b62.png)

I need a query to pull data as follows.
TICKET ID      ISSUE    PRODUCT NAME     LOCATION

**Comment by JediKev** [comment]
@mohankarunasiri

You should be able to build a query from the information I provided. 

Like I said before, I would use PHP objects instead as you can do something simple like `$form->getFields();`, loop through the fields, find the one you want, and then display that field’s data by `$field->getValue();`.

Also, this is not an issue report, rather a question or post for help. Please close this and post questions or posts for help on our [Forum](http://osticket.com/download).

Cheers.

**Comment by mohankarunasiri** [comment]
Thanks, JediKev
