### ISSUE TITLE
Customize contact form. Can I add currency textbox with validation ?

### ISSUE THREAD

**Issue by johnkalangha** [osTicket/osTicket#4529]
Hello,

I want to add currency text box with following validation

1. decimal numbers
2. $ sign should be allowed within the textbox or $ should be added in placeholder

Can you please suggest the solution

Thanks

**Comment by ntozier** [comment]
You would need to: 
write your own validators.
add them to the system for forms.
add the form field, and select the validator for it.

**Comment by johnkalangha** [comment]
hello sir @ntozier  it is in Manage>>Form>>Custom Name Form>> Example Label is AMOUNT>>Click Config and Add Validation Error.. is this correct sir? 

but it is work? for example: the user enter the amount of 500 then the agent it should be $500.00 without editing or will automatically generated

**Comment by johnkalangha** [comment]
or $ should be added in placeholder

Can you please suggest the solution

this sir?

**Comment by ntozier** [comment]
It's your mod so its your decision. I would personally just store the number.

**Comment by johnkalangha** [comment]
how sir? i dont get it sorry..
