### ISSUE TITLE
Cannot close ticket, required field missing

### ISSUE THREAD

**Issue by geo782** [osTicket/osTicket#4536]
### Description

- I have created a custom field in ticket details form and in field's settings, I have selected Data Integrity:Require entry to close a thread. 
- I go to a Help Topic's Settings and in Forms, I uncheck this field
- I create a new ticket in this Help Topic and this field is missing (OK)
- I open then the ticket for view and at the bottom, I get the message "Ticket is missing data on one or more required fields and cannot be closed". 
- In Edit ticket screen, i cannot see the required field, so i cannot close the ticket.
 
- I return to help topic settings, and i check the field.
- I return to previous ticket and field is still missing, so i cannot close the ticket.
- If I create a new ticket, field is now visible, but only for new tickets.

**Expected behavior:** [What you expected to happen]
If a field is not enabled in the help topic, it shouldn't be required to close ticket.

### Versions
1.10.4 (1.10.1 updated with patches)
MySQL | 10.2.14
PHP | 7.0.27-0+deb9u1

**Comment by ntozier** [comment]
If you check "Data Integrity:Require entry" it is required to close the ticket.
You need to make sure that it is visible so that it can be populated.

**Comment by geo782** [comment]
Hi ntozier,
This field is used in 20 Help Topics. 2 new topics have nothing to do with this field so its useless to have it visible and required. Also i cannot remove the "required to close ticket" because agents will then close tickets without filling field in the rest topics.

**Comment by JediKev** [comment]
@geo782 

I think this might be a bug where we are not checking if it's disabled if it's required. I'll have to see if I can replicate it.

Cheers.

**Comment by erictioh** [comment]
this is due to exisiting ticket which created before the new custom is added doesnt have data in ost_form_entry table, thus closing a ticket does not get that validated. 

my workaround is everytime i added new custom field, i will do one time insert for all existing ticket which doesnt have this field.
