### ISSUE TITLE
v1.10.4 tickets display miss information

### ISSUE THREAD

**Issue by jianfzhu** [osTicket/osTicket#4537]
I test new version v1.10.4, find the tickets display miss information, like below. how to change display as old version?
#######################
Open(3)   Closed  New Ticket
#######################
for old version v1.9.14, is display as below.  it will display closed numbers, answered, overdue numbers
#######################
Open(3)  Answered(4)  Overdue(3) Closed(100)  New Ticket
#######################

**Comment by jianfzhu** [comment]
ok, thanks, is there any way to change? I like the old display. it's clear.

**Comment by ntozier** [comment]
Sure.  You would alter the code on your install by editing the core files.
Of course every time that you upgrade you would have to re-apply the patch that you made.
