### ISSUE TITLE
Cannot use object of type EmailAddress as array in /include/pear/Mail/mimePart.php on line 968

### ISSUE THREAD

**Issue by aybanhoe** [osTicket/osTicket#4543]
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [x] Do you have any errors in the PHP error log, or javascript console?
* [ ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

[Description of the bug or feature]
"Http Error 500 when sending an activation email"

### Steps to Reproduce

1. Add User on the Agent Panel
2. Select the user and Send an activation email/Register
3. [and so on...]

**Expected behavior:** [What you expected to happen]
 An email would be sent to the email address provided
**Actual behavior:** [What actually happened]
A http error 500 appears

### Versions
v1.11 rc1

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.

![image](https://user-images.githubusercontent.com/43878638/46530654-0d318480-c8cd-11e8-858e-c8992e5f6137.png)

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

**Comment by JediKev** [comment]
@aybanhoe 

This _should_ be addressed in the latest pull from `develop-next`.

Cheers.

**Comment by aybanhoe** [comment]
Hi Sir @JediKev ,

Could you guide me on how can i fix this error?


Thanks.

**Comment by JediKev** [comment]
@aybanhoe

Yes, download and install the `develop-next` branch.

Cheers.

**Comment by aybanhoe** [comment]
@JediKev 

Thanks. Will Try this. I ll Just overwrite the existing files.

**Comment by JediKev** [comment]
@aybanhoe

Make a backup of the db just in case.

Cheers.

**Comment by aybanhoe** [comment]
@JediKev 

Hi Sir, just solved the issue. Thanks for the help. :)
