### ISSUE TITLE
Error when exporting tickets with custom field of custom list type (1.11RC1)

### ISSUE THREAD

**Issue by SFKS** [osTicket/osTicket#4546]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [X] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [X] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

1.11RC1
Error "File not found" when exporting tickets that have a custom field of a custom list type. 

### Steps to Reproduce

1. Our custom list
![captura01](https://user-images.githubusercontent.com/16702686/46674684-15473800-cbdd-11e8-81b4-df0c06b9e7f0.PNG)
![captura02](https://user-images.githubusercontent.com/16702686/46674692-1aa48280-cbdd-11e8-9089-918d7d896a25.PNG)

2. Added to our ticket form
![captura03](https://user-images.githubusercontent.com/16702686/46674716-2bed8f00-cbdd-11e8-8e54-8b3039588c4c.PNG)

3.  Exporting without our custom list field
![captura04](https://user-images.githubusercontent.com/16702686/46674736-39a31480-cbdd-11e8-9695-42ae1aebf29f.PNG)
![captura05](https://user-images.githubusercontent.com/16702686/46674740-3ad44180-cbdd-11e8-8021-748b103d1e66.PNG)

4. Exporting with our custom list field selected
![captura06](https://user-images.githubusercontent.com/16702686/46674782-4fb0d500-cbdd-11e8-99d0-e4fa6aadb620.PNG)
![captura07](https://user-images.githubusercontent.com/16702686/46674781-4fb0d500-cbdd-11e8-893b-f50a38f4e9b7.PNG)

**Expected behavior:** 
To export ok, like the text custom fields.

**Actual behavior:** 
The file not found page error.

### Versions

![captura08](https://user-images.githubusercontent.com/16702686/46675049-e9788200-cbdd-11e8-92aa-27f5894e2ae7.PNG)

Firefox 62.0.3

**Comment by JediKev** [comment]
@SFKS 

Please retest using the latest pull from `develop-next`. We have addressed a lot of the `1.11.x` issues in this branch.

Cheers.

**Comment by SFKS** [comment]
I have tried and I get few warnings in the panel. I'm going to try a fresh install with the latest pull tomorrow, thank you.

**Comment by JediKev** [comment]
@SFKS 

(I can't see the warnings.. but)
The warnings you are experiencing are _most likely_ due to PHP 7.0.x which we don't _fully_ support yet. We are aiming to support up to PHP 7.1.x in `1.11` stable release.

Cheers.

**Comment by SFKS** [comment]
Thank you for the advice.

I have tested with php 5.6 and develop-next:

![image](https://user-images.githubusercontent.com/16702686/46725542-ad482e80-cc7c-11e8-9bb7-512ec1f67d89.png)

There are some openbasedir warnings, but I did the test. Without the custom list type the export works, with the custom list type now i get this in the file:

`"Número de Ticket";"Fecha de creación";Asunto;De;"De correo electrónico";Prioridad;Departamento;"Temas de ayuda";Fuente;"Estado actual";"Última actualización";"SLA Due Date";"Fecha de Vencimiento";"Fecha de cierre";Atrasado;Respondió;"Agente asignado";"Equipo asignado";"Cuenta de hilos";"Reopen Count";"Recuento de datos adjuntos";"Tiempo empleado (en horas)";Materiales;"Coste (en euros)";Lugar
<br />
<b>Fatal error</b>:  Uncaught exception 'InconsistentModelException' with message 'Unable to prepare query: Commands out of sync; you can't run this command now SELECT A1.* FROM `ost_email` A1 WHERE A1.`email_id` = '2'' in /home/admin/web/mantenimiento.musikene.es/public_html/include/class.orm.php:3413
Stack trace:
#0 /home/admin/web/mantenimiento.musikene.es/public_html/include/class.orm.php(3459): MySqlExecutor-&gt;execute()
#1 /home/admin/web/mantenimiento.musikene.es/public_html/include/class.orm.php(1969): MySqlExecutor-&gt;getArray()
#2 /home/admin/web/mantenimiento.musikene.es/public_html/include/class.orm.php(2013): ModelInstanceManager-&gt;{closure}()
#3 /home/admin/web/mantenimiento.musikene.es/public_html/include/class.orm.php(1992): CallbackSimpleIterator-&gt;next()
#4 /home/admin/web/mantenimiento.musikene.es/public_html/include/class.orm.php(2001): CallbackSimpleIterator-&gt;rewind()
#5 /home/admin/web/mantenimiento.musikene.es/public_html/include/class.orm.php(1673): CallbackSimpleIterator-&gt;valid()
#6 /home/admin/web/mantenimient in <b>/home/admin/web/mantenimiento.musikene.es/public_html/include/class.orm.php</b> on line <b>3413</b><br />`

Thanks.
