### ISSUE TITLE
While clicking on assign then clicking on agent and clicking transfer shows the error please help

### ISSUE THREAD

**Issue by mayank1012** [osTicket/osTicket#4547]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
Request URL: https://track.chaayos.com/ticket/scp/ajax.php/tickets/15277/assign/teams?_uid=1539166833206
Request Method: GET
Status Code: 404 
* [ ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.
![image](https://user-images.githubusercontent.com/13532411/46730341-7c302400-cca5-11e8-9a4d-b88e78a2c536.png)

**Comment by ntozier** [comment]
@mayank1012 It appears that you skipped all the information of your issue report.  Please provide version of osTicket, environment details, etc.

**Comment by mayank1012** [comment]
@ntozier please find the details

osTicket Version | v1.10.3-32-ga31e8ea (a31e8ea)
Web Server Software | nginx/1.10.3
MySQL Version | 5.7.23
PHP Version | 7.0.32-0ubuntu0.16.04.1

**Comment by ntozier** [comment]
Please upgrade to 1.10.4 (current stable) and Apache.  Nginx does is not currently supported and does not work out of the box.  There are a number of Nginx configuration changes that you will have to make to get it to work, you should consult the numerous Nginx threads here for how other people got it to work.

**Comment by mayank1012** [comment]
Thanks it worked , issue is resolved
