### ISSUE TITLE
Error sending mail  from task version 1.11

### ISSUE THREAD

**Issue by CashDesk** [osTicket/osTicket#4548]
After adding a message to a task i get this error:

Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Email Recipient expected' in /home/osticketcd/support.cd.nl/include/class.util.php:227 Stack trace: #0 /home/osticketcd/support.cd.nl/include/class.user.php(1363): MailingList->add(Object(Collaborator)) #1 /home/osticketcd/support.cd.nl/include/class.thread.php(257): UserList->add(Object(Collaborator)) #2 /home/osticketcd/support.cd.nl/include/class.task.php(1192): Thread->getParticipants() #3 /home/osticketcd/support.cd.nl/include/class.task.php(981): Task->notifyCollaborators(Object(ResponseThreadEntry), Array) #4 /home/osticketcd/support.cd.nl/scp/tasks.php(82): Task->postReply(Array, Array) #5 {main} thrown in /home/osticketcd/support.cd.nl/include/class.util.php on line 227

**Comment by JediKev** [comment]
@CashDesk 

You have not provided any details about your environment. Also, are you using `1.11rc-1` from the website? If so, please use the latest pull from `develop-next` to retest.

Cheers.

**Comment by CashDesk** [comment]
Hi and thanks for your fast reply.
I downloaded the develop-next and installed it.
This error appears after posting an update in a task

Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Email Recipient expected' in /home/osticketcd/support.cd.nl/include/class.util.php:227 Stack trace: #0 /home/osticketcd/support.cd.nl/include/class.user.php(1363): MailingList->add(Object(Collaborator)) #1 /home/osticketcd/support.cd.nl/include/class.thread.php(257): UserList->add(Object(Collaborator)) #2 /home/osticketcd/support.cd.nl/include/class.task.php(1192): Thread->getParticipants() #3 /home/osticketcd/support.cd.nl/include/class.task.php(981): Task->notifyCollaborators(Object(ResponseThreadEntry), Array) #4 /home/osticketcd/support.cd.nl/scp/tasks.php(82): Task->postReply(Array, Array) #5 {main} thrown in /home/osticketcd/support.cd.nl/include/class.util.php on line 227

**Comment by CashDesk** [comment]
@JediKev , any idea?

**Comment by JediKev** [comment]
@CashDesk 

Will have to try and replicate this and get back to you later.

Cheers.

**Comment by matuscak** [comment]
I have the same problem. It appears only if you post update to the task where you have collaborators added. Without collaborators posting task update works normally.

I'm tracking 1.11.x branch, actual version I have is v1.11.0-rc1-333-ge7793c95 (e7793c9)
Running on PHP 5.6

My error with stacktrace:
Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'Email Recipient expected' in /www/ost/include/class.util.php:227
Stack trace:
#0 /www/ost/include/class.user.php(1363): MailingList-&gt;add(Object(Collaborator))
#1 /www/ost/include/class.thread.php(257): UserList-&gt;add(Object(Collaborator))
#2 /www/ost/include/class.task.php(1192): Thread-&gt;getParticipants()
#3 /www/ost/include/class.task.php(981): Task-&gt;notifyCollaborators(Object(ResponseThreadEntry), Array)
#4 /www/ost/scp/tasks.php(82): Task-&gt;postReply(Array, Array)
#5 {main}
  thrown in /www/ost/include/class.util.php on line 227

**Comment by CashDesk** [comment]
Solved after updating develop next
