### ISSUE TITLE
Uploading attachments not working

### ISSUE THREAD

**Issue by jjjj12212** [osTicket/osTicket#4550]
Hi Everyone,

We encountered an issue recently with our current version of osTicket (1.10-rc.2) and Tested both a fresh install of version 1.11-rc1 and a upgraded version and it continues to happen on all three situations.

When we try to attach a .jpg, .jpeg, or  .pdf (what we tested so far) Google Chrome (version 69.0.3497.100) reports a Javascript error:

Failed to load resource: net::ERR_EMPTY_RESPONSE

We also tried Firefox (62.0.3) and Safari (12.0) and even though nothing shows up on the javascript console, the attach request isn't returning a status of 200 (no status comes back).

to reproduce:
1. fresh install osTicket 1.11-rc1
2. create a new ticket
3. click "Choose them", pick a file

We will either get a blue loading bar that is full and won't go away or an empty bar that will not fill in.

Our backend server is Centos 7 64-bit with your usual Apache PHP MySQL stack.
Note that we do not have the following PHP extensions:
IntI
APCu
Zend OPCache

This issue is intemittant, it failed 90% of the time where has 10%, it actually responds back with a status 200 with the file attached.

Does anybody have any suggestions? Again, this just started happening all of a sudden with our current system.

Thanks,

jjjj12212

**Comment by JediKev** [comment]
@jjjj12212

Are you using any storage plugins? Any other errors via Apache, PHP, or MySQL?

Cheers.

**Comment by jjjj12212** [comment]
@JediKev 

We are not using any storage plugins, just the default.
I checked the PHP + Apache + mysql logs but they don't show any errors regarding this process.

We tested three browsers:

Google Chrome (version 69.0.3497.100) 
Firefox (62.0.3)
Safari (12.0)

Thanks,

jjjj12212

**Comment by jjjj12212** [comment]
Hi Everyone,

I just noticed that its working much better on Windows rather than the Mac OS Mojave.

This issue actually got noticed when we upgraded to Mac OS Mojave but I didn't know it would be related but somehow it is since a Windows PC is working Fantastically.

Is anyone out there with Mojave experiencing the same issue?

**Comment by JediKev** [comment]
@jjjj12212 

Haven't upgraded yet (never like to upgrade because I might lose all my Chrome tabs lol) but will try soon.

Cheers.
