### ISSUE TITLE
Change Position of Avatar in thread/.

### ISSUE THREAD

**Issue by johnkalangha** [osTicket/osTicket#4552]
Hi, is there a way to change the position of avatar in thread view, for example in messenger when im the owner of the account the avatar in the messages/thread should be in the right corner, and when i received a messages the avatar of the sender should be the in the left, but in osticket case it is the opposite? how should i fix this? thanks much a lot

**Comment by JediKev** [comment]
@johnkalangha 

This is not an issue report...please close this and post it on the [Forum](https://forum.osticket.com/) for further assistance.

Cheers.
