### ISSUE TITLE
New Message Activity not received on 3rd reply from Client.

### ISSUE THREAD

**Issue by dharsini3118** [osTicket/osTicket#4553]
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch? Yes 
* [x] Do you have any errors in the PHP error log, or javascript console? No
* [x] Did you check the [osTicket forums](http://osticket.com/forum/categories)? Yes
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported? not completely similar

### Description

New Message Activity not received on 3rd reply from Client.

### Steps to Reproduce

1. Client send support Request via Mail ["1st post client"]
2. New ticket has been created on system and Auto assignment alert is sent to all department agents.
3. Agent 1 has reply ["1st reply Agent"] (other agents has received new activity alert)
4. Client respond ["2nd client post"] (all agents has received new activity alert)
5. Agent 1 has reply ["2nd Agent reply"] (other agents has received new activity alert)
6. Client respond ["3rd client post"] - No one receive alert

**Expected behavior:**
All agents was expecting new activity alert on the 3rd post by the client

**Actual behavior:**
Nobody receive the alert

### Versions
Osticket version 1.10
php version 5.5.38

Attached is the scenario screen shots[
![lastmailactivityfromagent](https://user-images.githubusercontent.com/40055311/46856592-e963c680-ce17-11e8-8a2c-d87429dd910a.jpg)
![lastmailactivityfromclient](https://user-images.githubusercontent.com/40055311/46856593-e963c680-ce17-11e8-828f-b8f397d3c97a.jpg)
![001_3rdmessagealertnotreceived](https://user-images.githubusercontent.com/40055311/46856595-e9fc5d00-ce17-11e8-8d35-131364b200d2.jpg)

](url)

**Comment by JediKev** [comment]
@dharsini3118 

Any errors via Apache, PHP, MySQL, osTicket, or the browser? Weird, because I always get the alerts and notices.

Also, please try upgrading to v1.10.4 as it includes the latest bug fixes and security patches for the `1.10.x` series.

Cheers.

**Comment by dharsini3118** [comment]
Hi JediKev,

I found what as causing this issue. But couldn't understand why. Could you please explain?

Here is the setting which was causing this issue:
Agents - Departments - Alerts and Notices
Previously it was: 
![image](https://user-images.githubusercontent.com/40055311/47063531-73cb7200-d1ec-11e8-85ac-5d62c6266ef6.png)

Now I have change it to :
![image](https://user-images.githubusercontent.com/40055311/47063510-55fe0d00-d1ec-11e8-8547-77c95c3b8d15.png)

Please explain the differences between these two option

**Comment by ntozier** [comment]
It's pretty self explainatory.

First one is Department members and anyone that has extended access to the department.

Second is only Department members.  

See the little ? after the drop down, it likely explains.

**Comment by dharsini3118** [comment]
Hi @ntozier , the issue was i didn't understand why this config leading the issue describe above. Anyway, thanks. This thread can now be closed.
