### ISSUE TITLE
how to set the number of ticket to no.1

### ISSUE THREAD

**Issue by johnkalangha** [osTicket/osTicket#4554]
hello can anyone help me how to truncate the database and the number of ticket back to 1...  i already truncate the ost_ticket table but when i add number it continuous the previous ticket number

**Comment by JediKev** [comment]
@johnkalangha 

I'm starting to feel like a broken record here....but here it goes again:

**This is not an issue report rather a question or post for help. If you would like further assistance, please close this and post on our [Forum](https://forum.osticket.com/) as this is not a proper issue report.**

Cheers.
