### ISSUE TITLE
Cannot install plugins: "Install" button does nothing

### ISSUE THREAD

**Issue by gstrub** [osTicket/osTicket#4555]
Hi,

I am having issues with the installation of plugins with the latest develop-next branch. The plugins (I tried both PHAR and folder-based plugins) are detected and listed in the "Install a new plugin" page (.../scp/plugins.php?a=add), but when clicking the "Install" button on any of the listed plugins, I get back to the "Currently Installed Plugins" page and no plugin is installed. 
There is no error message in osTicket, nor in the php logs.

Steps to reproduce:
- upload plugins to include/plugins
- go to admin panel/manage/plugins
- add new plugin
- click install on any of the listed plugins
- the plugin is not install and no error message is given

I am running osTicket v1.11.0-rc1-254-gbc7b5a4d (bc7b5a4) and I can reproduce this issue under Firefox 62.0.3 (64-bit) and Microsoft Edge 42.17134.1.0

I dug a bit into the source code, and the installation fails (silently) because $_POST['install_path'] is not set. Indeed, upon checking the post request data using the Firefox developer tools, only the 'do' and '__CSRFToken__' are set in the post data. 

Poking around a bit, the culprit seems to be that the submit buttons are disabled while showing the overlay (scp.js, lines 167 to 169):
`// Disable staff-side Post Reply/Open buttons to help prevent`
`// duplicate POST`
`$(':submit', $(this)).attr('disabled', true);`

Commenting this line fixes the issue and the plugin installs successfully

**Comment by ntozier** [comment]
Environment details? (like Version of PHP?)

**Comment by JediKev** [comment]
@gstrub 

That doesn't make too much sense though as the code only disables the button _after_ clicking it...so that means the request is still sent through you just can't click the button again.

Cheers.

**Comment by gstrub** [comment]
@ntozier My environment is the following:
OS: Debian 9 64-bit
Web Server Software: Apache/2.4.25 (Debian)
MySQL Version: 10.1.26 (MariaDB)
PHP Version: 5.6.38-2+0~20181015120829.6+stretch~1.gbp567807

@JediKev 
Yes, the request is indeed sent (after the hook function is called), but without the 'install_path' field as the submit control is disabled. It seems that disabled inputs in forms do not get passed in the request:
https://stackoverflow.com/questions/7357256/disabled-form-inputs-do-not-appear-in-the-request
https://www.w3schools.com/tags/att_input_disabled.asp

**Comment by JediKev** [comment]
@gstrub

Gotcha. Will update this soon. Thanks for the report!

Cheers.

**Comment by JediKev** [comment]
@gstrub 

Here you go:
#4568

Cheers.

**Comment by gstrub** [comment]
@JediKev Thank you, that fixed it !
On a side note, I had to apply the fix "manually" as the pull request seems to be for another branch (develop) than the one I am currently running (develop-next).

**Comment by JediKev** [comment]
@gstrub 

Correct, `develop-next` is `develop` with more commits.

Think of it this way:
`develop` => Development branch for `1.10.x` series
`develop-next` => Development branch for `1.11.x` series

When we merge something to `develop` we then merge `develop` into `develop-next` giving `develop-next` the commit as well.

Cheers.
