### ISSUE TITLE
Printing tickets in PDF

### ISSUE THREAD

**Issue by wifixcort** [osTicket/osTicket#4557]
### Prerequisites

* [ Yes] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [No ] Do you have any errors in the PHP error log, or javascript console?
* [ Yes] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [ Yes] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

[Failed to load PDF document.]

### Steps to Reproduce

1. [Create a ticket]
2. [Go to view ticket state page]
3. [Fill the form and go to your email to open the ticket as a client]
4.[Try to print the ticket with the button provided]

**Expected behavior:** [What you expected to happen]
The page create a pdf and download it, then you open your pdf file

**Actual behavior:** [What actually happened]
The pdf is corrupted, it can not be opened 

###Fixing the problem
Inside the pdf file say 
`
<b>Warning</b>:  Declaration of mPDFWithLocalImages::WriteHtml($html) should be compatible with mPDF::WriteHTML($html, $sub = 0, $init = true, $close = true) in <b>/var/www/html/osTicket/include/class.pdf.php</b> on line <b>21</b><br />
`
If you go to that file and add ", $sub = 0, $init = true, $close = true" on line 22 it works!!!

**Comment by JediKev** [comment]
@wifixcort

Even though you provided no environment details whatsoever, it _sounds_ like you’re using PHP 7+ which is not supported, please downgrade to PHP 5.6 to resolve the issue. We aim to support up to PHP 7.1.x in the stable release of 1.11. Stay tuned.

Cheers.

**Comment by wifixcort** [comment]
Thanks @JediKev you are totally right, I use PHP7, but I provide the solution too :) it could help to the developers

**Comment by JediKev** [comment]
@wifixcort

Overlooked that, my bad. Thank you for that. I think we already addressed that though in our “support PHP 7.1” commit but I’ll double check to make sure. If not I’ll suggest the changes.

Cheers.
