### ISSUE TITLE
Error mailserver  

### ISSUE THREAD

**Issue by johnkalangha** [osTicket/osTicket#4559]
When i open my site it always show this error
MYSQL : 5.7
server: IIS
php. 5.6

PHP Warning:  mail(): Failed to connect to mailserver at &quot;localhost&quot; port 587, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in C:\inetpub\wwwroot\include\pear\Mail\mail.php on line 153
PHP Fatal error:  Call to undefined function _S() in C:\inetpub\wwwroot\include\class.mailer.php on line 573

**Comment by ntozier** [comment]
It sounds like your php.ini is misconfigured.
The error specifically says: "verify your "SMTP" and "smtp_port" setting in php.ini"
Version of osTicket?

**Comment by johnkalangha** [comment]
v1.10.4 (035fd0a) — Up to date  here sir

**Comment by johnkalangha** [comment]
any help?

**Comment by ntozier** [comment]
Did you verify your SMTP and smtp_port settings in your php.ini?

**Comment by johnkalangha** [comment]
yes in php.ini it is 587, it is refresh install for may testing vm,

**Comment by ntozier** [comment]
587?  I'm not sure how multiple settings can be a single number.
