### ISSUE TITLE
osticket.com SSL cert has no valid root CA = updater broken?

### ISSUE THREAD

**Issue by jakubeliasz** [osTicket/osTicket#4560]
Hi,

osTicket tells me I'm "Up to date" while I'm on v1.10.1 (9ae093d)
Clearly there seems to be a problem with this check/update function.

Quick debug leads me to believe it is caused by a broken SSL implementation:

$ wget osticket.com
--2018-10-23 10:31:53--  http://osticket.com/
Resolving osticket.com (osticket.com)... 96.126.117.188
Connecting to osticket.com (osticket.com)|96.126.117.188|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://osticket.com/ [following]
--2018-10-23 10:31:54--  https://osticket.com/
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Connecting to osticket.com (osticket.com)|96.126.117.188|:443... connected.
**ERROR: The certificate of ‘osticket.com’ is not trusted.
ERROR: The certificate of ‘osticket.com’ hasn't got a known issuer.**

https://www.ssllabs.com/ssltest/analyze.html?d=osticket.com

If this is indeed the case, could someone give this webserver/proxy some love, pretty please?

**Comment by JediKev** [comment]
@jakubeliasz

Already aware of this. Reported internally. Should be addressed soon.

Cheers.

**Comment by lakridserne** [comment]
This ought to be closed.

**Comment by maltfield** [comment]
Please don't close this, the issue still persists.

 * https://docs.osticket.com

```
Websites prove their identity via certificates. Firefox does not trust docs.osticket.com because its certificate issuer is unknown, the certificate is self-signed, or the server is not sending the correct intermediate certificates.
 
Error code: SEC_ERROR_UNKNOWN_ISSUER
```

@JediKev any update on this. Can you just switch to the same Let's Encrypt cert? It's very hard for me to convince my org to use a product whoose docs domain cert has been broken for years.

It's a pretty big, red security flag.

**Comment by maltfield** [comment]
Also, the forums have the same issue

 * https://forum.osticket.com/

```
 
Websites prove their identity via certificates. Firefox does not trust forum.osticket.com because its certificate issuer is unknown, the certificate is self-signed, or the server is not sending the correct intermediate certificates.
 
Error code: SEC_ERROR_UNKNOWN_ISSUER
```

You can get a free wildcard cert from Let's Encrypt and fix all these issues.

**Comment by JediKev** [comment]
@maltfield 

After further review on our side the certificates are in fact valid and do not need updating. Both the Documentation site and the Forum show as valid and have a while before they expire (even the root certificate). I have visited both sites using Firefox and it shows `Connection Secure`:
<img width="561" alt="Screen Shot 2021-01-08 at 11 12 51" src="https://user-images.githubusercontent.com/11823401/104044621-2a87e400-51a3-11eb-91d7-a149e00d419a.png">
<img width="560" alt="Screen Shot 2021-01-08 at 11 13 04" src="https://user-images.githubusercontent.com/11823401/104044663-2d82d480-51a3-11eb-86d2-78b316b8c8a6.png">

You may need to contact your IT Team to update the trusted root certificates on your side. After that your browser should show valid certificates for both sites.

>You can get a free wildcard cert from Let's Encrypt and fix all these issues.

They are both Let's Encrypt  😉 

Cheers.

**Comment by antiuser** [comment]
so for advice, you have a ISP that changed SSL certificate via DPI )))))))))))))))))

**Comment by JediKev** [comment]
@maltfield 

We dug deeper and we had a COMODO cert that expires in February, 2021 (still valid) still being served. We have removed it and ensured that only Let's Encrypt is being served. Please check again and get back to us.

Cheers.

**Comment by maltfield** [comment]
I don't think my ISP was MITM'ing my connection and actively altering the cert ;)

> We dug deeper and we had a COMODO cert

Yes. Though I didn't download the old cert or its fingerprints, I do remember that firefox said the issuer was COMODO before. Today they read Let's Encrypt, and they work fine in firefox.

My best-guess is that COMODO had some history of recklessness (far too common for CAs) that got them on a ban list in firefox or something.

Thank you for fixing this; I think the ticket can be closed.
