### ISSUE TITLE
Email - SMTP error

### ISSUE THREAD

**Issue by emlk530** [osTicket/osTicket#4565]
Hai all,

My alerts and mails are working except outlook/office 365. I have checked in diagnostic tab all mails are successfully going but not receiving. So upgraded the system with RC version still the problem existing.

I went through this forum and tried a lot with some SMTP solutions but all are not working for me. But at the same time clients and staffs who have gmail ids they are receiving the alerts and all.

i have searched and tried everything : 
1. https://github.com/osTicket/osTicket/issues/3726
2. https://github.com/osTicket/osTicket/issues/3726#issuecomment-344383132

also i tried with and without tls://, ssl://, tlsver1.2:// etc

Still am facing the same problem...mails are going to outlook/office365 but not receiving nor i cant craete any SMTP instead than php_mail. 

Server Information
--
osTicket Version | v1.11.0-rc1 (e321982) —  Up to date
Web Server Software | Apache
MySQL Version | 5.6.41
PHP Version | 5.4.45

Please help me to solve this.
Thank you.

**Comment by ntozier** [comment]
> PHP Version | 5.4.45

I am running multiple instances of 1.10.4 with O365 and send/receive mail just fine.  I would not recommend that you run 1.11rc1 in a production environment, and upgrade PHP to 5.6.

**Comment by emlk530** [comment]
@ntozier thank you for your reply.

osTicket Version | v1.10.4 (035fd0a) —  Up to date
-- | --
Web Server Software | Apache
MySQL Version | 5.6.41
PHP Version | 5.6.37

Still the same i can't create a single smtp...but in local at least i could create gmail smtp.
I doubt its because of open ssl in php.in. Right now its disabled..

could please tell me which settings works for u...?

**Comment by ntozier** [comment]
IMAP
enabled
Hostname: outlook.office365.com
port: 993
Mailbox Protocol: IMAP+SSL

SMTP
enabled
Hostname: smtp.office365.com
Port: 587
Authentication Required: Yes
Header spoofing: unchecked.

**Comment by emlk530** [comment]
Hai,

Now i think it could because of the php of the hosting panel. Because the following config is working in my localhost running on php 5.5 on wamp. And am not using POP/IMAP right now.

SMTP
enabled
Hostname: smtp-mail.outlook.com
Port: 587
Header spoofing: unchecked.

SMTP
enabled
Hostname: smtp.gmail.com
Port: 465
Header spoofing: unchecked.

Here am pasting my php config(Dynamic Extensions):
**php.ini(5.6) in host:**
;extension=php_bz2.dll
;extension=php_curl.dll
;extension=php_fileinfo.dll
;extension=php_gd2.dll
;extension=php_gettext.dll
;extension=php_gmp.dll
;extension=php_intl.dll
;extension=php_imap.dll
;extension=php_interbase.dll
;extension=php_ldap.dll
;extension=php_mbstring.dll
;extension=php_exif.dll      ; Must be after mbstring as it depends on it
;extension=php_mysql.dll
;extension=php_mysqli.dll
;extension=php_oci8.dll      ; Use with Oracle 10gR2 Instant Client
;extension=php_oci8_11g.dll  ; Use with Oracle 11gR2 Instant Client
extension=php_openssl.dll
;extension=php_pdo_firebird.dll
;extension=php_pdo_mysql.dll
;extension=php_pdo_oci.dll
;extension=php_pdo_odbc.dll
;extension=php_pdo_pgsql.dll
;extension=php_pdo_sqlite.dll
;extension=php_pgsql.dll
;extension=php_pspell.dll
;extension=php_shmop.dll

; The MIBS data available in the PHP distribution must be installed.
; See http://www.php.net/manual/en/snmp.installation.php
;extension=php_snmp.dll

;extension=php_soap.dll
;extension=php_sockets.dll
;extension=php_sqlite3.dll
;extension=php_sybase_ct.dll
;extension=php_tidy.dll
;extension=php_xmlrpc.dll
;extension=php_xsl.dll
;extension=php_zip.dll

**php.ini (5.5) in my localhost:**
extension=php_bz2.dll
extension=php_curl.dll
extension=php_com_dotnet.dll
extension=php_fileinfo.dll
extension=php_gd2.dll
extension=php_gettext.dll
extension=php_gmp.dll
extension=php_intl.dll
extension=php_imap.dll
;extension=php_interbase.dll
extension=php_ldap.dll
extension=php_mbstring.dll
extension=php_exif.dll      ; Must be after mbstring as it depends on it
extension=php_mysql.dll
extension=php_mysqli.dll
;extension=php_oci8.dll      ; Use with Oracle 10gR2 Instant Client
;extension=php_oci8_11g.dll  ; Use with Oracle 11gR2 Instant Client
extension=php_openssl.dll
;extension=php_pdo_firebird.dll
extension=php_pdo_mysql.dll
;extension=php_pdo_oci.dll
;extension=php_pdo_odbc.dll
;extension=php_pdo_pgsql.dll
extension=php_pdo_sqlite.dll
;extension=php_pgsql.dll
extension=php_shmop.dll

; The MIBS data available in the PHP distribution must be installed. 
; See http://www.php.net/manual/en/snmp.installation.php 
;extension=php_snmp.dll

extension=php_soap.dll
extension=php_sockets.dll
extension=php_sqlite3.dll
;extension=php_sybase_ct.dll
;extension=php_tidy.dll
extension=php_xmlrpc.dll
extension=php_xsl.dll

When i replace the local php.ini with hosted one my other instances not working. Can you help me to fix this which require fro os ticket only??

**Comment by JediKev** [comment]
@emlk530

The following extensions are _disabled_ in your hosts’s `php.ini` but _enabled_ in your local `php.ini`:
```
;extension=php_bz2.dll
;extension=php_curl.dll
;extension=php_fileinfo.dll
;extension=php_gd2.dll
;extension=php_gettext.dll
;extension=php_gmp.dll
;extension=php_intl.dll
;extension=php_imap.dll
;extension=php_ldap.dll
;extension=php_mbstring.dll
;extension=php_exif.dll
;extension=php_mysql.dll
;extension=php_mysqli.dll
;extension=php_pdo_mysql.dll
;extension=php_pdo_sqlite.dll
;extension=php_pspell.dll
;extension=php_shmop.dll
;extension=php_soap.dll
;extension=php_sockets.dll
;extension=php_sqlite3.dll
;extension=php_xmlrpc.dll
;extension=php_xsl.dll
;extension=php_zip.dll
```

Take a look at `Admin Panel > Dashboard > Information` for the recommended extensions for osTicket, uncomment those extensions in your host’s `php.ini`, restart your web server or php-fpm, and retest.

Cheers.

**Comment by emlk530** [comment]
Hello,
i have changed as you guided me. But same result. Here am attaching both server information.

Localhost: SMTP WORKING
![screensh](https://user-images.githubusercontent.com/44433727/47629460-9cd8f480-db54-11e8-98e4-9d89e4fb188f.png)


Bluehost: SMTP NOT WORKING
![screenshot](https://user-images.githubusercontent.com/44433727/47629470-ac583d80-db54-11e8-9ffc-1888bb6b8d6c.png)




`

**Comment by emlk530** [comment]
Update from bluehost:

> I can see Unfortunately it would not be possible to use external SMTP servers within your BlueHost account. Ports 465 and 587 are already reserved on the server for our mail services, so you would not be able to connect to another service on these ports. 

What to do next....??

**Comment by JediKev** [comment]
@emlk530 

Bluehost just told you... They don't allow SMTP from ports 465 and 587 as those are reserved for their own mail services. I don't like Bluehost for this reason specifically..they don't allow you to send mail or fetch mail from any mail server except theirs. This means you cannot use Gmail with Bluehost, you can only use Bluehost email with Bluehost.

With this being said, it looks like you have two options:
1.) You can use your Bluehost email to send mail.
2.) Switch to a different provider that allows connections to outside mail servers like Gmail.

Your host might have specific instructions on how to configure Gmail but I could not find any _(this does not mean there isn't any just means I couldn't find any)_.

Cheers.

**Comment by guidokuehler** [comment]
We have migrate our osTicket MySQL-Database from an MySQl-System with version 5.5.60 to a new MySQL-Server-System with Version 8.0.13 without any Errors but we receive now the followed Error below in osTicket-Logs. 


[SELECT team.*, count(m.staff_id) as members, CONCAT_WS(" ", lead.firstname, lead.lastname) as team_lead FROM ost_osticket_team team LEFT JOIN ost_osticket_team_member m ON(m.team_id=team.team_id) LEFT JOIN ost_osticket_staff lead ON(lead.staff_id=team.lead_id) WHERE 1 GROUP BY team.team_id ORDER BY team.name ASC ] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'lead ON(lead.staff_id=team.lead_id) WHERE 1 GROUP BY team.team_id ORDER BY team' at line 1 

---- Ablaufverfolgung ---- 
#0 (root)/include/mysqli.php(177): osTicket->logDBError('DB Error #1064', '[SELECT team.*, ...') 
#1 (root)/include/staff/teams.inc.php(35): db_query('SELECT team.*, c...') 
#2 (root)/scp/teams.php(118): require('/var/www/it-pow...') 
#3 {main} 


Have any Person an Tipp for us to resolve this? 

Best Regards! 

Guido

**Comment by JediKev** [comment]
@emlk530 

No problem at all! I hope you find a great host that allows external email communication and has awesome support! 😃 

Cheers.

**Comment by JediKev** [comment]
@guidokuehler 

It appears your post has nothing to do with this thread so please open your own Issue Report (if there isn't one opened for the issue you're experiencing already). Don't forget to include system information (Admin Panel > Dashboard > System Information), server information (OS, Apache/IIS, PHP version), exact steps to replicate the issue, etc.

Cheers.

**Comment by emlk530** [comment]
@JediKev @ntozier 

Running successfully at a2hosting....Happy to inform you guys.
