### ISSUE TITLE
Online and Office Support.

### ISSUE THREAD

**Issue by bdharmesh3** [osTicket/osTicket#4566]
Hello Team, 

Currently, we have 2 shift in our organization. Morning and Evening for that we had set up two different email id. 
we want to setup like from morning 8 AM To 8 PM if we get ticket email receive on abc@gmail.com and after 8 PM if anyone generates ticket we get mail on abc@gmail.com and xyz@gmail. com 

Thanks in advance

**Comment by ntozier** [comment]
This does not appear to be a bug / issue report.  I would recommend that you seek support at the support forums. https://forum.osticket.com/

Please close this.

**Comment by bdharmesh3** [comment]
thanks will do.
