### ISSUE TITLE
v1.10.4 Cannot send e-mails from tickets

### ISSUE THREAD

**Issue by osTicketRocks** [osTicket/osTicket#4573]
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [x] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

Out host provider just changed the PHP version to 7.0 yesterday and because of it we had to get our osTicket an update to the latest v1.10.4.
When someone is answering a ticket and want to send an e-mail to its recipient, the answer is going into the database but the e-mail won't be sent.
We get a blank tickets.php, but with error logging enabled we get some more informations.

> Warning: Missing argument 1 for AnnotatedModel::get(), called in /is/htdocs/XXX/include/class.variable.php on line 95 and defined in /is/htdocs/XXX/include/class.orm.php on line 688

> Fatal error: Uncaught OrmException: ThreadEntry: : field not defined in /is/htdocs/XXX/include/class.orm.php:382 Stack trace: #0 /is/htdocs/XXX/include/class.orm.php(691): VerySimpleModel->get(NULL, NULL) #1 /is/htdocs/XXX/include/class.variable.php(95): AnnotatedModel->get() #2 /is/htdocs/XXX/include/class.variable.php(101): VariableReplacer->getVar(Object(AnnotatedModel), NULL) #3 /is/htdocs/XXX/include/class.variable.php(134): VariableReplacer->getVar(Object(Ticket), 'lastmessage') #4 /is/htdocs/XXX/include/class.variable.php(168): VariableReplacer->_resolveVar('ticket.lastmess...') #5 /is/htdocs/XXX/include/class.variable.php(115): VariableReplacer->_parse(' <strong>Beteil...') #6 [internal function]: VariableReplacer->replaceVars(' <strong>Beteil...') #7 /is/h in /is/htdocs/XXX/include/class.orm.php on line 382

It doesn't matter if we enter text on our own or we choose one of the templates - the result is the same.
We can send an test e-mail in diagnosis without any problems.

I really hope someone can help us?

Thank you very much!

### Versions

v1.10.4
Our webspace is hosted by Host Europe hence we don't know exaclty on what platform it's installed on.

**Comment by JediKev** [comment]
@osTicketRocks 

Unfortunately, the `1.10.x` branch does not support PHP 7+. You'll have to downgrade to PHP 5.6.x or upgrade to `1.11-rc1`. Please note that `1.11-rc1` is still a Release Candidate and should not be used with extreme caution.

Cheers.

**Comment by osTicketRocks** [comment]
Thanks for your quick reply.

But why does people say otherwise?
https://forum.osticket.com/d/92229-php-7172
https://forum.osticket.com/d/91098-support-for-php-7x

Both threads say that PHP 7.0.x is supported with v1.10.x.
We already downgraded from PHP 7.2 to 7.0 just to get osTicket running.


Thanks a lot! :-)

**Comment by JediKev** [comment]
@osTicketRocks 

I guess I should've said:
>`1.10.x` doesn't **_FULLY_** support PHP 7+

.. instead. You still might experience issues with PHP 7 and version `1.10.4`. We are going to support up to PHP 7.1 in the `1.11` stable release coming soon.

Cheers.

**Comment by osTicketRocks** [comment]
Thanks again. :-)

Well, that means it could work but it doesn't have to?
I'm asking this kind of dumb question because one of my customers is using osTicket excessively in their business and not being able to send e-mails to their customers is deadly for them.
We also don't have any choice to downgrade any futher than PHP 7.0 because the hoster said goodbye to PHP 5.6 yesterday.


Thanks a lot once again!

**Comment by JediKev** [comment]
@osTicketRocks 

"We do not FULLY support PHP 7+" means just that, it's not _fully_ supported. It might work well for most things but other things might break/error out. "Fully supported" means you can use osTicket with the PHP version and have no issues, unless it's a bug in osTicket.

I've seen some people use PHP 7 and osTicket 1.10.4 with no issues at all and I've seen others that cannot use osTicket with PHP 7 whatsoever. So it's a hit or a miss.

Cheers.

**Comment by osTicketRocks** [comment]
Is there any timeframe when the next release (1.11.x) is final?

**Comment by JediKev** [comment]
@osTicketRocks 

Unfortunately, we never have set release/development dates. Soon is all I can say!

Cheers.
