### ISSUE TITLE
Adding new member with extended access - DB Error

### ISSUE THREAD

**Issue by JtheBAB** [osTicket/osTicket#4578]
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [ ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

When i create a user with a primary department and a extended access to another department i get a DB Error.

### Steps to Reproduce

1. Add new Agent
2. Fill the necessary information
3. Access Tab --> Select the primary department
4. Access Tab --> Add another department as extended access

**Expected behavior:** No Database error

**Actual behavior:** 
DB Error:

```
[INSERT INTO `ost_staff_dept_access` SET `dept_id` = '5', `role_id` = '10', `flags` = 1]

Duplicate entry '0-5' for key 'PRIMARY'<br />
<br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(199): osTicket->logDBError('DB Error #1062', '[INSERT INTO `o...')<br />
#1 (root)/include/class.orm.php(3454): db_query('INSERT INTO `os...', true, true)<br />
#2 (root)/include/class.orm.php(658): MySqlExecutor->execute()<br />
#3 (root)/include/class.staff.php(1182): VerySimpleModel->save()<br />
#4 (root)/include/class.staff.php(1098): Staff->updateAccess(Array, Array)<br />
#5 (root)/scp/staff.php(47): Staff->update(Array, Array)<br />
#6 {main}
```

User is created but without the extended access. You can add the extended access without any problem.

### Versions

Server Information
osTicket Version	develop-next Commit:  14b5ba5
Web Server Software	Apache/2.4.10 (Debian) OpenSSL/1.0.1t
MySQL Version	5.5.60
PHP Version	5.6.38-0+deb8u1

Client:
Chrome 62
Windows 10

**Comment by JediKev** [comment]
@JtheBAB 

Cannot replicate this with the latest pull from `develop-next`. Try pulling the latest changes and then try again.

Cheers.

**Comment by JtheBAB** [comment]
It was with the latest pull. I tried again and now it is working....
