### ISSUE TITLE
staff opening ticket for client -> staff name variables do not populate.

### ISSUE THREAD

**Issue by ntozier** [osTicket/osTicket#458]
Peter on the forums you posted in:
http://www.osticket.com/forum/discussion/76015/email-template-not-showing-staff-name-that-answer-the-customers#latest

So I decided to check out those two vars you mention and hunt a little for some of the others. I figured that perhaps you had used essentially the same format for staff.  So I went into supportcenter logged in as staff and changed my templates.  I threw this into "New Ticket Notice".

TEST ----=[ remove this after ]=----

Client Names VARS
first: %{ticket.name.first}
last: %{ticket.name.last}
lastfirst: %{ticket.name.lastfirst}
short: %{ticket.name.short}
shortformal: %{ticket.name.shortformal}
full: %{ticket.name.full}
original: %{ticket.name.original}
formal: %{ticket.name.formal}
initials: %{ticket.name.initials}
legal: %{ticket.name.legal}

Staff Name VARS
first: %{staff.name.first}
last: %{staff.name.last}
lastfirst: %{staff.name.lastfirst}
short: %{stafff.name.short} .

shortformal: %{staff.name.shortformal}
full: %{staff.name.full}
original: %{staff.name.original}
formal: %{staff.name.formal}
initials: %{staff.name.initials}
legal: %{staff.name.legal}

staff name: %{staff.name}
staff first: %{staff.name.first}
staff last: %{staff.name.last}

END TEST ----=[ remove before after ]=----

I then opened a ticket for on behalf of a client.  Below you will see what the email that this generated.  Please note that I was logged in as my staff and clicked new ticket.

HOWEVER!!!

After that I altered the "Response/Reply Template" and "New Message Auto-response" [which appear to be the same things to me, perhaps we should clarify ] the same way and posted a response.  This second email is below after the header ========== 2nd message =========.  As you can see it populated most of the variables that I speculated it would.  So I guess the question is why didn't it populate it in the initial email.  My guess is because no one had "actually responded yet" that it bases the results of those variables off who the ticket is assigned to.  I'm not real sure if that was intentional or not, but you may want to consider making it  default to logged in user if a ticket is being created by staff for client.

---------- Forwarded message ----------
From: Support support@xxxxxxxxxxxx.supportsystem.com
Date: Thu, Jan 23, 2014 at 10:34 AM
Subject: vars test
To: email@gmail.com

-- do not edit --

We're Here For YouSupport Desk

Dear Neil,

Our customer care team has created a ticket, #XXXXXX on your behalf, with the following details and summary:

Topic: General Inquiry
Subject: vars test

TEST ----=[ remove this after ]=----

Client Names VARS
first: Neil
last: Tozier
lastfirst: Tozier, Neil
short: Neil T.
shortformal: N. Tozier
full: Neil Tozier
original: Neil Tozier
formal: Tozier
initials: NT
legal: Neil Tozier

Staff Name VARS
first: %{staff.name.first}
last: %{staff.name.last}
lastfirst: %{staff.name.lastfirst}
short: %{stafff.name.short} .

shortformal: %{staff.name.shortformal}
full: %{staff.name.full}
original: %{staff.name.original}
formal: %{staff.name.formal}
initials: %{staff.name.initials}
legal: %{staff.name.legal}

staff name: %{staff.name}
staff first: %{staff.name.first}
staff last: %{staff.name.last}

END TEST ----=[ remove before after ]=----

This is a test ticket to test new ticket vars.

If need be, a representative will follow-up with you as soon as possible. You can also view this ticket's progress online.

Your Harbor Homes, Inc. Team,
If you wish to provide additional comments or information regarding the issue, please do not send another email. Instead, reply to this email or login to your account for a complete archive of all your support requests and responses.

Powered by SupportSystem

========== 2nd message =========

-- do not edit --

Support Desk
We're Here For You
Dear Neil Tozier,

This is a test repsonse. This is only a test response.
This is a test repsonse. This is only a test response.

TEST ----=[ remove this after ]=----

Client Names VARS
first: Neil
last: Tozier
lastfirst: Tozier, Neil
short: Neil T.
shortformal: N. Tozier
full: Neil Tozier
original: Neil Tozier
formal: Tozier
initials: NT
legal: Neil Tozier

Staff Name VARS
first: Neil
last: Tozier
lastfirst: Tozier, Neil
short: %{stafff.name.short} .

shortformal: N. Tozier
full: Neil Tozier
original: Neil Tozier
formal: Tozier
initials: NT
legal: Neil Tozier

staff name: Neil Tozier
staff first: Neil
staff last: Tozier

**Comment by MelArlo** [comment]
Any word on making these variables available during new ticket creation? I have a situation where I would like to include the staff member's name in the new ticket notice email template and so far have been unable to find a workaround for this. Any updates would be appreciated.
