### ISSUE TITLE
error with cron.php using cli for appended messages

### ISSUE THREAD

**Issue by curciosobrinho** [osTicket/osTicket#4592]
I am running 1.11
When I run cron.php (using cli), it works for new Ticket and I get notified. But when it is a added message to existing ticket, I get:
PHP Fatal error:  Uncaught Error: Call to a member function getEmail() on null in /home/curcio/www/ticket/include/class.ticket.php:1681
Stack trace:
#0 /home/curcio/www/ticket/include/class.ticket.php(2752): Ticket->notifyCollaborators(Object(MessageThreadEntry), Array)
#1 /home/curcio/www/ticket/include/class.ticket.php(3082): Ticket->postMessage(Array, 'Email')
#2 /home/curcio/www/ticket/include/class.thread.php(545): Ticket->postThreadEntry('M', Array)
#3 /home/curcio/www/ticket/include/class.thread.php(813): Thread->postEmail(Array, Object(ThreadEntry))
#4 /home/curcio/www/ticket/include/class.mailfetch.php(785): ThreadEntry->postEmail(Array)
#5 /home/curcio/www/ticket/include/class.mailfetch.php(857): MailFetcher->createTicket(2)
#6 /home/curcio/www/ticket/include/class.mailfetch.php(937): MailFetcher->fetchEmails()
#7 /home/curcio/www/ticket/include/class.cron.php(25): MailFetcher::run()
#8 /home/curcio/www/ticket/include/class.cron.php(105): Cron::MailFetcher()
#9 /home/curcio/www/ticket/include/api.cron.php(19): Cron:: in /home/curcio/www/ticket/include/class.ticket.php on line 1681

**Comment by JediKev** [comment]
@curciosobrinho

Try again with the latest pull from `1.11.x` Branch.

Cheers.

**Comment by curciosobrinho** [comment]
It did not solve and it added many Warning messages (even being display=off in php.ini), so there is some file that is forcing it to display.
