### ISSUE TITLE
Unknown column 'dst' in 'field list'

### ISSUE THREAD

**Issue by emilyplusplus** [osTicket/osTicket#4596]
Getting seemingly random/arbitrary errors in logs for multiple osTicket installations (v1.10). See error below:

```
[UPDATE `ostou_user_account` SET `timezone` = 'America/Los_Angeles', `dst` = 1, `lang` = 'en_US', `passwd` = '$2a$08$mSKLhafMJKte6/ni9rtGNOBV4wMfa0c2LyVf.1dAvmXbxVoe9LwWW', `status` = 1 WHERE `ostou_user_account`.`id` = 10 LIMIT 1]

Unknown column 'dst' in 'field list'<br />
<br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(204): osTicket->logDBError('DB Error #1054', '[UPDATE `ostou_...')<br />
#1 (root)/include/class.orm.php(3133): db_query('UPDATE `ostou_u...', true, true)<br />
#2 (root)/include/class.orm.php(597): MySqlExecutor->execute()<br />
#3 (root)/include/class.user.php(1019): VerySimpleModel->save(false)<br />
#4 (root)/include/class.client.php(459): UserAccount->save()<br />
#5 (root)/profile.php(27): ClientAccount->update(Array, Array)<br />
#6 (root)/client.inc.php(87): require('/home/redpil9/p...')<br />
#7 (root)/secure.inc.php(18): require_once('/home/redpil9/p...')<br />
#8 (root)/profile.php(19): require('/home/redpil9/p...')<br />
#9 {main}
```

**Comment by emilyplusplus** [comment]
Is anyone even monitoring this issue tracker at this point??

**Comment by emilyplusplus** [comment]
@JediKev

**Comment by ntozier** [comment]
Yes, people are on here daily.

You didn't follow the posting guidelines.  Which includes a number of questions that you have not answered.  Such as version you are running, etc.  I would recommend that you answer those if you would like someone to assist you.

It looks to me like your SQL error says there is no column "dst".  This is correct.  There has never been a dst column in _user_account to my knowledge.  Did you mod your instance?  Are you using develop-next (unreleased version 1.11)?

**Comment by emilyplusplus** [comment]
@ntozier @JediKev I did put version number in there, but it was kind of hidden, my apologies for not following template format, I will be sure to do that if I have any further questions! Thanks you both for all your help! I'll see if #4599 helps :)
