### ISSUE TITLE
hello. advanced search issue.  on and not on of created and due date are not working

### ISSUE THREAD

**Issue by BatunaAz** [osTicket/osTicket#4597]
i have osticket v1.10.4 and php v7.0.32 and mysql5.6.40
![screen shot 2018-11-06 at 12 04 23](https://user-images.githubusercontent.com/41317761/48042467-8ec24e00-e1bc-11e8-9bdf-d16ae7deecf4.png)
![screen shot 2018-11-06 at 12 04 38](https://user-images.githubusercontent.com/41317761/48042471-94b82f00-e1bc-11e8-85bd-16765cd422a0.png)

### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [ ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

**Comment by osTicketRocks** [comment]
I've got the same problem with v1.10.4. :-(
