### ISSUE TITLE
Latest stable version (1.10.4) doesn't work with any maintained PHP versions

### ISSUE THREAD

**Issue by pieleric** [osTicket/osTicket#4598]
At the beginning of December (2018), the PHP versions 5.6 and 7.0 will be not be officially supported anymore by the PHP community: https://secure.php.net/supported-versions.php
So, only PHP versions 7.1 and 7.2 will be supported. However, the latest stable version (1.10.4) doesn't support any of these versions.

Interestingly, we've tried running the unstable v1.11.x branch, and it doesn't support PHP 7.2, and even for the PHP 7.1 support a couple of extra fixes are required. It'd be nice to at least have some official release candidate of v1.11 with full support for PHP 7.1 before beginning of December 2018.

**Comment by JediKev** [comment]
@pieleric 

This has been mentioned many..._many_ times in many..._many_ threads...but I'll go over it here (again):
osTicket `1.10` or lower only supports PHP 5.6.x.
osTicket `1.11` stable will support UP TO PHP 7.1.x.
osTicket `1.12`+ _should_ hopefully support UP TO PHP 7.2.x.

Cheers.

**Comment by vollkommenIrrelevant** [comment]
When will you release v1.11. stable?

**Comment by vollkommenIrrelevant** [comment]
bump

**Comment by martinvonwittich** [comment]
@JediKev I'm currently evaluating help desk systems for our company, and I find it unfortunate that the PHP requirements aren't clearly specified in the [documentation](https://docs.osticket.com/en/latest/Getting%20Started/Installation.html) - there it just says "PHP 5.6 (or better)", which one could falsely interpret as PHP 7.x support. It would be helpful if the docs could be updated to clarify this.

**Comment by ntozier** [comment]
@vollkommenIrrelevant When it is ready.  The devs will not give you a better answer than "soon".

@martinvonwittich I agree.  The docs and FAQ should say php 5.6 - php 7.0.x.  That being said the over view that @JediKev posted is the most accurate.

**Comment by vollkommenIrrelevant** [comment]
@ntozier 
In 10 days php7.0 will be end of life, so - what do you suggest if someone use v1.10?

**Comment by ntozier** [comment]
Use the recommended version of 5.6?  Which has support until Dec 31st.  Which is what we are doing.

Of course there are web hosts that still have 5.4 installed and support for that ended 2015.  So I dont know why you are that concerned.

Maybe the devs are planning on giving us an early xmas present.

**Comment by lewiscawte** [comment]
> Of course there are web hosts that still have 5.4 installed and support for that ended 2015. So I dont know why you are that concerned.

I must be misinterpreting this, because surely you are not implying that people use software that is out of date just because other people are using more out of date software? Or that you should use software down to the minute it becomes unsupported when there are newer versions available?

**Comment by ntozier** [comment]
@lewiscawte I'm saying software fast release cycles does not always translate to fast acceptance and use.  People use what works, and many people don't like changing things when they already work. The old "Why fix it if it isn't broke" mentality. Is it security minded?  No.  But the latest and greatest seems to rarely be that.  It is sort of the way of the world tech industry and has been for a long time.  You might not like it.  I might not like it.  But it is what it is.

**Comment by fredriksknese** [comment]
one.com has stopped supporting PHP 5.6 and now only supports PHP 7.1, 7.2 and 7.3
1.5 million potential customers whom can not use osTicket anymore.

Anyone know a hosting provider that support insecure version php 5.6?

**Comment by ntozier** [comment]
Just throwing this out here:
https://www.zdnet.com/article/around-62-of-all-internet-sites-will-run-an-unsupported-php-version-in-10-weeks/

**Comment by damongant** [comment]
You say that as if it is a justification to run on an unsupported version; it is not.

Of course nobody is entitled to free updates and support in an open source project, but to day that it is okay to run outdated software because so many other people do it is not okay.

**Comment by JediKev** [comment]
Geez...this thread -.-

Just go look at the multiple PHP 7 threads on our GitHub to see what you need to do in order to run osTicket on PHP 7 (use `1.11.x`/`develop-next`latest with the PHP 7 Support pull #4344).

Cheers.

**Comment by lewiscawte** [comment]
> Geez...this thread -.-
> 
> Just go look at the multiple PHP 7 threads on our GitHub to see what you need to do in order to run osTicket on PHP 7 (use `1.11.x`/`develop-next`latest with the PHP 7 Support pull #4344).
> 
> Cheers.

psssttt. You could probably quash the majority of this PHP7 if you threw together say... a fairly simple documentation page and linked to it in a few visible places?

I know writing documentation is **boring** but is getting all of these emails/notifications not worse? 5-minute job, and then on the reduced occasion these threads spawn, you could just blanket link there, closing most of your duplication PHP7+ threads.

**Comment by vollkommenIrrelevant** [comment]
something new on this?
