### ISSUE TITLE
1.10.4: Missing line breaks (\n)

### ISSUE THREAD

**Issue by killerbees19** [osTicket/osTicket#4600]
Forget it, this is already fixed with d8abe105ec04b7750fcd119bf79edb2b01808cd7.

Sorry! :-(

**Comment by ntozier** [comment]
Thanks for letting us know.  @JediKev

**Comment by killerbees19** [comment]
Oops, I've erroneously linked to the "right" bugfix…

This is **already** fixed in 1.10.x branch: d8abe105ec04b7750fcd119bf79edb2b01808cd7

Sorry guys. I should go to bed for now… 😳
