### ISSUE TITLE
In agent panel --> open tickets column shows all tickets

### ISSUE THREAD

**Issue by akash65** [osTicket/osTicket#4602]
Hello everyone,

I want to see respective department tickets in "open ticket column" in AGENT dashboard but these system shows all departments tickets in "open ticket"...can anyone please help me

![screenshot 238](https://user-images.githubusercontent.com/12798776/48197868-0f2fad00-e37d-11e8-9480-d94d9ddc52ea.png)
![screenshot 240](https://user-images.githubusercontent.com/12798776/48198022-8bc28b80-e37d-11e8-8fe4-0d082bf1396c.png)

**Comment by ntozier** [comment]
It appears that you cross posted on the forums and explained your issue two different ways,
https://forum.osticket.com/d/93149-agent-panel-open-tickets-column-shows-all-department-tickets

**Comment by JediKev** [comment]
@akash65

@ntozier is correct. Also, please refrain from posting questions/configuration issues on GitHub as this is a place to report Bugs/Issues/Feature Requests only. 

P.S.
You should check your post on the forum as it now has 3 answers. 😉

Cheers.

**Comment by akash65** [comment]
Thanks
