### ISSUE TITLE
Search quick results displays multiple lines for each user. (1.11.x)

### ISSUE THREAD

**Issue by themunchkinman** [osTicket/osTicket#4603]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch? YES
* [ ] Do you have any errors in the PHP error log, or javascript console? NO
* [ ] Did you check the [osTicket forums](http://osticket.com/forum/categories)? YES
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported? YES

### Description

Quick search result overlay displays multiple lines for a single user, one line per ticket instead of a single line for the user with the number of total/matching tickets.

### Steps to Reproduce

1. Begin typing in the search box on the Tickets tab.
2. Wait for the "quick results" to display in the overlay.

**Expected behavior:** Display list with email with one line per email address and the total number of tickets for that email address.

**Actual behavior:** Displays list with multiple lines for the same email address with a count of "1" next to each.

### Versions

1.11.x -
Variants of this issue appear to present since 10-30-2018. Most recently observed in latest (11-07-2018).
Additional behavior previously included that the search results (after pressing enter/return or clicking the search icon) would have duplicate entries for the same ticket.  This appears to be possibly resolved.

Windows Server 2012 R2 / IIS 8.5
MySQL 5.5.44
PHP 5.6.31

Tested in all browsers.

### Other notes

Could be a simple order of operations error in the function collecting the results, instead of iterating the total number, it simply adds a new line for each result.

### Screenshot

![image](https://user-images.githubusercontent.com/17258272/48204804-53e12700-e330-11e8-9e09-da01b8b53400.png)

**Comment by JediKev** [comment]
@themunchkinman 

This is a known issue that we are actively addressing. The fix will either be in the `RC2` release or the stable release of `1.11`.

Cheers.

**Comment by themunchkinman** [comment]
Thanks @JediKev .
Sorry if I duplicated an issue.  Thank you for the quick response.
