### ISSUE TITLE
Collaborator in organization causes ticket creation to fail

### ISSUE THREAD

**Issue by cdkading** [osTicket/osTicket#4605]
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch? Dont have another install
* [x] Do you have any errors in the PHP error log, or javascript console? Yes
* [x] Did you check the [osTicket forums](http://osticket.com/forum/categories)? Yes
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported? Yes

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

Whenever the Primary Contacts: | Add to all tickets from this organization is checked and the collaborator is set to anyone except the user who is the primary contact -- adding a new ticket fails and drops to a white screen.

Error below.

[09-Nov-2018 20:43:57 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method stdClass::set() in /home/nrthwind/public_html/support/include/class.orm.php:2101
Stack trace:
#0 /home/nrthwind/public_html/support/include/class.thread.php(2106): InstrumentedList->add(Object(stdClass))
#1 /home/nrthwind/public_html/support/include/class.thread.php(182): ThreadEvents->log(NULL, 'collab', '{"add":{"1316":...')
#2 /home/nrthwind/public_html/support/include/class.ticket.php(1113): Thread->addCollaborator(Object(User), Array, Array, true)
#3 /home/nrthwind/public_html/support/include/class.ticket.php(3856): Ticket->addCollaborator(Object(User), Array, Array)
#4 /home/nrthwind/public_html/support/include/class.ticket.php(4063): Ticket::create(Array, Array, 'staff', false)
#5 /home/nrthwind/public_html/support/scp/tickets.php(410): Ticket::open(Array, Array)
#6 {main}
  thrown in /home/nrthwind/public_html/support/include/class.orm.php on line 2101

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

v1.11.0-rc1 (e321982)

Web Server Software | Apache
MySQL Version | 5.7.24
PHP Version | 7.0.32

CENTOS 7.5 virtuozzo

All browsers

**Comment by JediKev** [comment]
@cdkading 

Please retest using latest pull from `1.11.x` branch. Report back if issues still occurs.

Cheers.
