### ISSUE TITLE
Cron::MailFetcher throws DoesNotExist exception

### ISSUE THREAD

**Issue by AlexeyDemidov** [osTicket/osTicket#4606]
### Prerequisites

* [?] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [x] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

Many incoming emails cause cron mail fetcher to throw exception and stop process remaining emails from specific inbox.

```
Uncaught DoesNotExist in /srv/www.domain.com/osticket/public/include/class.orm.php:1174
Stack trace:
0 /srv/www.domain.com/osticket/public/include/class.orm.php(630): QuerySet->one()
1 /srv/www.domain.com/osticket/public/include/class.ticket.php(2740): VerySimpleModel->save(true)
2 /srv/www.domain.com/osticket/public/include/class.ticket.php(3373): Ticket->save()
# 3 /srv/www.domain.com/osticket/public/include/class.mailfetch.php(796): Ticket::create(Array, Array, 'Email')
# 4 /srv/www.domain.com/osticket/public/include/class.mailfetch.php(845): MailFetcher->createTicket(4)
# 5 /srv/www.domain.com/osticket/public/include/class.mailfetch.php(925): MailFetcher->fetchEmails()
# 6 /srv/www.domain.com/osticket/public/include/class.cron.php(25): MailFetcher::run()
# 7 /srv/www.domain.com/osticket/public/include/class.cron.php(105): Cron::MailFetcher()
# 8 /srv/www.domain.com/osticket/public/include/api.cron.php in /srv/www.domain.com/osticket/public/include/class.orm.php on line 1174                                  
```

### Steps to Reproduce

**Expected behavior:** 

Cron mail fetcher is supposed to retrieve and process all emails from all configured mailboxes

**Actual behavior:** 

On many emails cron mail fetcher throws exception and stops processing remaining emails in a mailbox

### Versions

osTicket Version v1.10.4 (035fd0a) 
Web Server Software Apache
MySQL Version 10.1.26
PHP Version 7.0.30-0+deb9u1

**Comment by JediKev** [comment]
@AlexeyDemidov 

Please downgrade to PHP 5.6 and retest. Version 1.10.x and below only supports PHP 5.4-5.6 and version 1.11.x will support UP TO PHP 7.1.x. Please stay tuned! 

Cheers.

**Comment by AlexeyDemidov** [comment]
@JediKev 

Moved to PHP 5.6.38, getting the same error.

```
[18-Dec-2018 16:36:04 UTC] PHP Fatal error:  Uncaught exception 'DoesNotExist' in /srv/www.domain.com/osticket/include/class.orm.php:1174
Stack trace:
#0 /srv/www.domain.com/osticket/include/class.orm.php(630): QuerySet->one()
#1 /srv/www.domain.com/osticket/include/class.ticket.php(2740): VerySimpleModel->save(true)
#2 /srv/www.domain.com/osticket/include/class.ticket.php(3373): Ticket->save()
#3 /srv/www.domain.com/osticket/include/class.mailfetch.php(796): Ticket::create(Array, Array, 'Email')
#4 /srv/www.domain.com/osticket/include/class.mailfetch.php(845): MailFetcher->createTicket(5)
#5 /srv/www.domain.com/osticket/include/class.mailfetch.php(925): MailFetcher->fetchEmails()
#6 /srv/www.domain.com/osticket/include/class.cron.php(25): MailFetcher->run()
#7 /srv/www.domain.com/osticket/include/class.cron.php(105): Cron->MailFetcher()
#8 /srv/www.domain.com/osticket/include/api.cron.php(19): Cron->run()
#9 /srv/www.domain.com/osticket/include/api.cron.php(40): CronApiController->run()
#10 /srv/www.domain.com/osticket/api/cron.php(23): LocalCronApiCon in /srv/www.domain.com/osticket/include/class.orm.php on line 1174
```

**Comment by JediKev** [comment]
@AlexeyDemidov 

Can you confirm the ticket is created in the database? It looks like it's trying to re-fetch the newly created record and it does not exist.
```
Uncaught exception 'DoesNotExist' in include/class.orm.php:1174
|__ #0 /srv/www.domain.com/osticket/include/class.orm.php(630): QuerySet->one()
```
https://github.com/osTicket/osTicket/blob/develop/include/class.orm.php#L1171-L1174

Cheers.

**Comment by AlexeyDemidov** [comment]
@JediKev no, tickets are not created, at least they are not visible in the interface.

**Comment by JediKev** [comment]
@AlexeyDemidov

Then that’s were the “DoesNotExost” error comes from. Now find out why it’s not creating the tickets. Check Apache/PHP error logs and/or osTicket system logs.

Cheers.

**Comment by AlexeyDemidov** [comment]
@JediKev I have already provided appropriate PHP error log excerpt. There is nothing in osTicket logs. Apache logs are irrelevant as it is `api/cron.php` called from cron.

**Comment by JediKev** [comment]
@AlexeyDemidov

You’ve only posted a “DoesNotExist” error...this only states that the ticket does not exist, not why it was not created. We will need more info/errors in order to debug/help.

Cheers.

**Comment by AlexeyDemidov** [comment]
@JediKev  it is the only error message produced by `api/cron.php`.  Can you tell which additional information I can provide and where I can get it?

**Comment by JediKev** [comment]
@AlexeyDemidov

I can not reproduce this issue so it’s going to be difficult.

Can you confirm that the PHP version has indeed changed and all the appropriate extensions are installed/enabled?

You could try var_dump in the Ticket create function in multiple places to see if it has the appropriate info, it actually gets created, etc.

Cheers.
