### ISSUE TITLE
Answer by email

### ISSUE THREAD

**Issue by darouca** [osTicket/osTicket#4607]
Hi.

I have a question.
When they open a Ticket, I get an email.

Is it possible for me to respond to this email and my client receive the response?

Today, I respond, but create an internal note.

Tks

**Comment by JediKev** [comment]
@darouca 

This is not possible at this time. You are correct, when an agent responds via email the system will only add it as an internal note. We have plans to implement this feature in future versions so please stay tuned!

Cheers.

**Comment by darouca** [comment]
Tks @JediKev and @perryk 
:)
