### ISSUE TITLE
Php print excel

### ISSUE THREAD

**Issue by BatunaAz** [osTicket/osTicket#4608]
function exportTableToExcel(tableID, filename = ''){
        var downloadLink;
        var dataType = 'application/vnd.ms-excel';
        var tableSelect = document.getElementById(tableID);
        var tableHTML = tableSelect.outerHTML.replace(/ /g, '%20');
        
        // Specify file name
        filename = filename?filename+'.xls':'excel_data.xls';
        
        // Create download link element
        downloadLink = document.createElement("a");
        
        document.body.appendChild(downloadLink);
        
        if(navigator.msSaveOrOpenBlob){
                var blob = new Blob(['\ufeff', tableHTML], {
                        type: dataType
                });
                navigator.msSaveOrOpenBlob( blob, filename);
        }else{
                // Create a link to the file
                downloadLink.href = 'data:' + dataType + ', ' + tableHTML;
        
                // Setting the file name
                downloadLink.download = filename;
                
                //triggering the function
                downloadLink.click();
        }
    }

result is:
![screen shot 2018-11-14 at 11 01 05](https://user-images.githubusercontent.com/41317761/48457165-a1f89d80-e7fc-11e8-9f1e-a2d268e256c4.png)

how can i fix this

**Comment by JediKev** [comment]
@BatunaAz 

It appears that is custom code which you will not get help with here. Instead you should close this and post on our [Forum](https://forum.osticket.com) where you will be assisted by the community.

Cheers.
