### ISSUE TITLE
Advance search bug 1.10.4

### ISSUE THREAD

**Issue by ramrajone** [osTicket/osTicket#4609]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
Not tried
* [x] Do you have any errors in the PHP error log, or javascript console?

 "POST /scp/ajax.php/tickets/search HTTP/1.1" 200 35 "http://domain.com/scp/tickets.php?status=answered" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36"
::1 - - [14/Nov/2018:10:38:41 -0500] "GET /scp/tickets.php?advanced HTTP/1.1" 500 93 "http://domain.com/scp/tickets.php?status=answered" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36"

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

When logged in as Agent doing an Advance search and selecting "Created">on>then any date
it gives error ":-(
Not sure what happened.. something broke though."

The session times out and have to clear the cookies to login back

### Steps to Reproduce

1. tried: 
When logged in as Agent doing an Advance search and selecting "Created">on>then any date

2.tried: 
logged in as Agent doing an Advance search and selecting "Due Date">not on>then any date

3.tried: 
When logged in as Agent doing an Advance search and selecting "Created">not on>then any date

**Expected behavior:** [What you expected to happen]
Get search result back

**Actual behavior:** [What actually happened]
it gives error ":-(
Not sure what happened.. something broke though."

### Versions
osTicket Version	v1.10.4 (035fd0a) —  Up to date
Web Server Software	Apache/2.4.29 (Win32) OpenSSL/1.0.2l PHP/7.0.31

I am using Windows 10 Pro, Google Chrome Version 70.0.3538.102 (Official Build) (64-bit)
tried on IE: ver. 11.345.17134.0

**Comment by JediKev** [comment]
@ramrajone

This was temporarily fixed with #4014 but will be permanently addressed in `1.11.x`.

Cheers.

**Comment by ramrajone** [comment]
Thank you, this worked
Line 2032 in include/class.forms.php:
replacing:
: $value;
with:
:(is_object($value) ? $value : new DateTime($value));
