### ISSUE TITLE
Email Configuration

### ISSUE THREAD

**Issue by arashk72** [osTicket/osTicket#4610]
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch? yes
* [ ] Do you have any errors in the PHP error log, or javascript console? no
* [x] Did you check the [osTicket forums](http://osticket.com/forum/categories)? yes
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported? yes

### Description

Hi,
First of all thanks for your nice project and active community.
It looks very simple, but I couldn't find any solution with searching. 
Simply, I don't know where should I set email configurations. And if I cannot set email configuration, nobody can register into the system.
Your help is really appreciated if you tell me where can I configure email settings.
I have installed the software on ubuntu 16.04, and my php version is 7.0.
Thanks.

**Comment by JediKev** [comment]
@arashk72 

Please refrain from posting questions about configurations on Github as this is a place to report Bugs and/or Feature Requests and to submit Pull Requests only. If you would like to ask a question about configurations please post on our [Forum](https://forum.osticket.com).

I'll go ahead and answer you here though so you don't have to wait:
You simply go to **Admin Panel > Emails > Emails > Add New Email** and fill out the appropriate information. If you see an email that's in the system already that you'd like to use simply click that email and fill out the appropriate information. Once you have an email fully configured (IMAP/POP and SMTP) you may set the **Default System Email** and **Default MTA** under **Admin Panel > Emails > Settings**. 

Cheers.

**Comment by arashk72** [comment]
Thank you very very much.
