### ISSUE TITLE
New Message Alert not obtain when transfer a ticket a another team

### ISSUE THREAD

**Issue by dharsini3118** [osTicket/osTicket#4614]
### Description

When a ticket is transfer to another team , " New Message Alert" is longer received.

### Steps to Reproduce
- One department 
- Two Teams: Team A and Team B
- Several Agents: 
   Team A - Agent 1, Agent 2, Agent 3
   Team B - Agent 1, Agent 4, Agent 5

Test Procedures:
1) Client 1, send an email to test@example.com
2) New Ticket is created in OsTicket - Team A receive Ticket Assignment Alert.
3) Agent 2 from Team A replies to the ticket - client and other Agent receive new Activity alert
4) Client 1 reply back through mail - new content is appended to the ticket correctly. - New Message Alert is received by all agents in Team A.
5) Agent 2 - assign the ticket to Team B - New ticket assignment is received by Team B
6) Agent 4 - replies to client 1
7) Client 1 - replies back again - no New Message alert receive by any agent
8) Agent 4 - replies to client 1
9) Client 1 - replies back again - no New Message alert receive by any agent
10) Agent 1 - assign the ticket to Team A - New ticket assignment is received by Team A
11) Agent 4 - replies to client 1
12) Client 1 - replies back again - no New Message alert receive by any agent

**Expected behavior:** 
Agent is expecting a New Message alert
- Problem is Agents doesn't check osticket until they receive an alert, hence we are getting a lot of ticket overdue, when we don't get New Message Alert.
-However when a ticket is manage within a single team, all alert works perfectly.
-It only happens when a ticket is manage by two teams

**Actual behavior:** [What actually happened]
No alerts is received

### Versions
Osticket version 1.10
Php version 5.5.38

###Current setting
![image](https://user-images.githubusercontent.com/40055311/48823032-b3035a80-ed78-11e8-8a48-0c4a2d75b861.png)

![image](https://user-images.githubusercontent.com/40055311/48823100-fbbb1380-ed78-11e8-88ef-1a007d3f321b.png)

**Comment by dharsini3118** [comment]
@ntozier @JediKev  Can you please try to reproduce this scenario at your end?

**Comment by ntozier** [comment]
I would recommend that you update to current stable 1.10.4 and PHP 5.6 and retest.
