### ISSUE TITLE
Alerts Checkbox - Extended Access

### ISSUE THREAD

**Issue by bcowman** [osTicket/osTicket#4615]
Alerts checkbox state in Extended Access of Manage Agent does not save.

![image](https://user-images.githubusercontent.com/6651942/48844411-accda800-ed91-11e8-9ea2-fd4f6ad9db3f.png)

I add a new department and uncheck Alerts, then save the changes.  When I open the record the Alerts checkbox is still checked.  If I uncheck and save again then the state saves correctly.

Happens in version 1.10.4 and 1.11.0-rc1

### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [ ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

**Comment by JediKev** [comment]
@bcowman

It does save just doesn’t reload. Save, reload, and voila.

Cheers.
