### ISSUE TITLE
New Internal Activity Alert (1.10.4)

### ISSUE THREAD

**Issue by geo782** [osTicket/osTicket#4617]
Hi,
In 1.10.4 (1.10.1 updated), I have recently enabled "New Internal Activity Alert" and selected "Assigned Agent / Team". 
Yesterday, an agent (A) that is not assigned in a specific ticket, got an alert that an another agent (B) replies to ticket XXXXX. From ticket history,  I see that ticket was first assigned to a team that the agent(A) belongs to, but after this assignment, ticket was then assigned to another agent(B), who also replied and closed the ticket.  That means that agent(A) should not get the notification email, because ticket wasn't assigned to the team anymore. Is this a bug?
Also there is a problem in greek translation of New Internal Activity Alert explanation. In english it says "Alert sent out to Agents when internal activity such as an _internal note_ or an _agent reply_ is appended to a ticket." but in greek it says only for _internal note_ or _ticket assignment_. 

Web Server Software | Apache/2.4.25 (Debian)
MySQL Version | 10.2.13
PHP Version | 7.0.27-0

George

**Comment by AdamDempsey** [comment]
I believe this is because a ticket can be assigned to both a team and an agent, assigning to an agent doesn't remove it from the team, which is why Agent A received the alert.

**Comment by ntozier** [comment]
Tickets can be assigned to an agent.
Tickets are also assigned to a Department -or- Team.
If you do not want the agent to have access to it you will have to assign it to a different Department -or- Team.

**Comment by geo782** [comment]
@AdamDempsey @ntozier thanks for the replies. I thought that if a ticket is assigned to a team and then assign it to an agent, team is then removed from assignement. I dont understand why team should get an email for a ticket that they dont care about.

George

**Comment by ntozier** [comment]
> I thought that if a ticket is assigned to a team and then assign it to an agent, team is then removed from assignement.

Nope.  It's still assigned to the Team AND the agent
