### ISSUE TITLE
Iframe Issue

### ISSUE THREAD

**Issue by MuTahan** [osTicket/osTicket#4618]
Hello
I'm trying to display the system inside iframe in sharepoint environment but and error occurred and display this error "Refused to display 'https://xxxxxx.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'." so kindly advice for that problem.

**Comment by JediKev** [comment]
@MuTahan 

I've explained this on multiple threads I believe but I'll post it once more here:

We have a security patch that prevents ClickJacking and this fix disallows any iFrames on sites that are not on the same origin. I am creating a workaround for this soon so be on the lookout. In the meantime you can use the API to submit form data to the helpdesk to create tickets. All of that is explained in the API docs [here](https://docs.osticket.com/en/latest/Developer%20Documentation/API%20Docs.html).

Cheers.

**Comment by MuTahan** [comment]
@JediKev Hello i figured out another solution for this case i added the domain i need to add the solution is by configuring the htaccess by this header
<httpProtocol>
<customHeaders>
<add name="X-Frame-Options" value="ALLOW-FROM https://the_other_domain.com"  />
<remove name="X-Frame-Options" /> 
</customHeaders>
</httpProtocol> 

or you can configure the apache server like this 
Header set X-Frame-Options "allow-from https://The_target_domian.com"

**Comment by JediKev** [comment]
@MuTahan 

Correct, although you might want to remove the old name first, before adding the new one.

Cheers.
