### ISSUE TITLE
consult tickets only by Ticket number

### ISSUE THREAD

**Issue by diegoale1994** [osTicket/osTicket#4619]
Hello Everyone, Can consult tickets only by Ticket number and avoid the email in end user interface?, I know that actually is not a functionality, but do u know how to disable email address verification in code?

**Comment by JediKev** [comment]
@diegoale1994 

osTicket is an email-based system...I don't think you'll be able to get around this unless you customize it to use fake email addresses...then you'll have to worry about the alerts and such too. Long story short, you can't unless you customize it.

Cheers.
