### ISSUE TITLE
Duplicate Tickets and Ticket-Answers when Refreshing the Page 

### ISSUE THREAD

**Issue by jthakilla9** [osTicket/osTicket#4620]
When i refresh the page, it creates a ticket from the previous session.  I found out that there is a script for temporally fix. 

This is the script: 

<div id="msg_notice"><?php echo $msg; ?></div>
<script type="text/javascript">setTimeout(function(){ window.location.href = "tickets.php?id=<?php echo $ticket->getId(); ?>";}, 1200);</script>

I implemented this in the file 'client\view.inc.php'.

But it didnt work.

This is where i put the script in.

<?php
if(!defined('OSTCLIENTINC') || !$thisclient || !$ticket || !$ticket->checkUserAccess($thisclient)) die('Access Denied!');

$info=($_POST && $errors)?Format::htmlchars($_POST):array();
$dept = $ticket->getDept();

!<div id="msg_notice"><?php echo $msg; ?></div>
<script type="text/javascript">setTimeout(function(){ window.location.href = "tickets.php?id=<?php echo $ticket->getId(); ?>";}, 1200);</script>!

Is there some other solution or script, or did i do something wrong?

**Comment by JediKev** [comment]
@jthakilla9 

This will be addressed in the `1.11` series when #4509 is accepted and merged.

Cheers.
