### ISSUE TITLE
Error while upgrading v1.10.4 to v1.11 RC1

### ISSUE THREAD

**Issue by luiizfenix** [osTicket/osTicket#4621]
### Prerequisites

* [ X ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ X ] Do you have any errors in the PHP error log, or javascript console?
* [ X ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [ X ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

While upgrading to new v.1.11 rc1 downloaded from osticket.com on step 3 i get a something went wrong error and upgrader seems to complete the upgrade process "succesfully". 
But anytime while accesing agents panel i get the following error:

":-(
Not sure what happened.. something broke though."

on the php log error i get the following: 
"26-Nov-2018 17:41:41 UTC] PHP Fatal error:  Class name must be a valid object or a string in /home2/kgtech/file/include/class.forms.php on line 1088"

No other error, i can access all other configurations or tabs on the osticket but cannot access ticket list. 

### Steps to Reproduce

1. backup ost-config.php file and /include/plugin folder and delete everything else 
2. extract new osticket v1.11 rc1 
3.  go into osticket webpage to enter upgrader
4. All green, start upgrade process
5. step 3 gets error but upgrader was "successful" 
6. Click on Agent panel
7. Error shows on the screen
![image](https://user-images.githubusercontent.com/32772585/49033774-0d882680-f17e-11e8-96bd-d166ca1363e4.png)
![image](https://user-images.githubusercontent.com/32772585/49033794-1bd64280-f17e-11e8-9d08-5fb5de10ccdc.png)

**Expected behavior:** [What you expected to happen]
Upgrade sucessfully 

**Actual behavior:** [What actually happened]
Cannot use newer version 

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.
new
![image](https://user-images.githubusercontent.com/32772585/49033459-44117180-f17d-11e8-82dd-ba9672076e85.png)

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

CentOS 6.6 (x86_64 bit)
Google Chrome 70.0.3538.102

**Comment by JediKev** [comment]
@luiizfenix 

Please restore from backup and use the latest pull from the `1.11.x` branch, as this includes the most recent fixes/patches.

Cheers.

**Comment by luiizfenix** [comment]
same behavior but a different error, 

"Class name must be a valid object or a string in /home2/kgtech/file/include/class.forms.php on line 1110"

Still getting something went wrong while updating

**Comment by JediKev** [comment]
@luiizfenix

Did you restore from backup and use latest pull from 1.11.x branch?

Cheers.

**Comment by luiizfenix** [comment]
yes i restored from backup and used latest pull by then (nov 26th) 
Maybe it is something related to my tickets? i tried searching that line of code (class.forms.php on line 1110) but i cant trace back what its trying to do. 

> 1106`    function getImpl($parent=null) {`
> 1107`        // Allow registration with ::addFieldTypes and delayed calling`
> 1108`        $type = static::getFieldType($this->get('type'));`
> 1109`        $clazz = $type[1];`
> **1110`        $inst = new $clazz($this->ht);`**
> 1111`        $inst->parent = $parent;`
> 1112`        $inst->setForm($this->_form);`
> 1113`        return $inst;`
> 1114`    }`

when i update from 1.10.4 with blank database it works but again i cant seem to find a way to migrate my data to this new build. 

What should i look on my data to migrate my system?

**Comment by JediKev** [comment]
@luiizfenix

To get around this error you could dump the queue sorts table, truncate it, upgrade and then add them back.

Cheers.

**Comment by luiizfenix** [comment]
@JediKev

Ill try and let you know.

Best Regards

**Comment by luiizfenix** [comment]
Hi @JediKev, thanks for the help. 
I tried above, with newest 1.12, but after it pass that error now i get: 

> Core: Upgrader Error

> [/** * @signature 0ca8585781bc6656f3ca008212554441 * @version v1.11.0 * @title Add recipients field and collaborator flags * * This patch adds a new field called recipients to the thread entry table * allowing agents to see a list of recipients for any thread entry where * an email was involved (agent or user generated) * * It also adds a flags field to the thread_collaborator table which * tracks whether or not the collaborator is active. As a result, we can * remove the isactive field */ ALTER TABLE `ost_thread_entry` ADD `recipients` text AFTER `ip_address`] Duplicate column name 'recipients'

any help will be greatly appreciated.

**Comment by luiizfenix** [comment]
> Hi @JediKev, thanks for the help.
> I tried above, with newest 1.12, but after it pass that error now i get:
> 
> > Core: Upgrader Error
> 
> > [/** * @Signature 0ca8585781bc6656f3ca008212554441 * @Version v1.11.0 * @title Add recipients field and collaborator flags * * This patch adds a new field called recipients to the thread entry table * allowing agents to see a list of recipients for any thread entry where * an email was involved (agent or user generated) * * It also adds a flags field to the thread_collaborator table which * tracks whether or not the collaborator is active. As a result, we can * remove the isactive field */ ALTER TABLE `ost_thread_entry` ADD `recipients` text AFTER `ip_address`] Duplicate column name 'recipients'
> 
> any help will be greatly appreciated.

I realized, somehow ost_thread_entre already had recipient column, so i deleted it and the upgrade completed with error, it said successful upgrade, but befor that the message: an error ocurred. 

After that same behavior as before when accesing agent panel. 

> ":-(
> Not sure what happened.. something broke though."

php error log:
`[17-Jun-2019 17:44:37 UTC] PHP Fatal error:  Class name must be a valid object or a string in /home2/kgtech/file/include/class.forms.php on line 1110`

might be something with custom forms? 

any help will be greatly appreciated.

**Comment by JediKev** [comment]
@luiizfenix 

>":-(
Not sure what happened.. something broke though."

This is an error from a 3rd party mod/plugin that you've implemented (reason I know is because I've seen it before). There is nothing we can do about this error. Instead you should contact the creator of the 3rd party plugin/mod for additional assistance.

>PHP Fatal error: Class name must be a valid object or a string in /home2/kgtech/file/include/class.forms.php on line 1110

This has nothing to do with custom forms rather the fields themselves. The error states that "Class name must be a valid object or a string". This means that you're system is trying to call a class by name and the name is not a valid object or string. This happens because we try to generate an implementation instance of each field by the `type` column in the database (you can read more about this [here](https://github.com/osTicket/osTicket/blob/develop-next/include/class.forms.php#L1094-L1105)). I have a sneaking suspicion that one or more of your fields are not valid, core fields meaning that one or more of your `type` values are not actually valid. I would look at every record in your `ost_form_field` table to make sure all the values in the `type` column are [in this array](https://github.com/osTicket/osTicket/blob/develop-next/include/class.forms.php#L555-L569) or this list (`priority`, `department`, `assignee`, `list-X`, `state`). If a field's type is not in the array or list, then you need to go into the system (before attempting an upgrade) and delete the field (make sure to check the box to "delete all data" as well). After this you may try to upgrade again.

Cheers.

**Comment by luiizfenix** [comment]
Hi @JediKev actually, that helped! Thanks. 

Deleted field, but needed to make it from database since werent showing on main UI. 
Also on ost_forms there was 4 hidden forms with type inline, from previous testing. they also didnt show on main UI so i had to erase them from the database, and erase all the ost_form_entry_values asociated to the fields from type inline. 

after that upgrade was done without any issue. 

Thanks consider it closed.
