### ISSUE TITLE
Unable to sort by Due Date header in lastest git pull

### ISSUE THREAD

**Issue by the-r0cket06** [osTicket/osTicket#4624]
### Prerequisites

* [Yes] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [Yes] Do you have any errors in the PHP error log, or javascript console?
* [Yes] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [Yes] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

Sorting by Due Date in a queue displays nothing, and triggers a DB error in the system log

### Steps to Reproduce

1. Go to Tickets -> My Tickets
2. Click on Due Date header, page refreshes and ticket queue is gone
3. Using Ticket, Last Update and Priority sorting methods all work.
4. If I use the Sort button and select Due Date from the drop down it works as expected.

**Expected behavior:** [What you expected to happen]
Sort ticket queue by Due Date 

**Actual behavior:** [What actually happened]
Sorting by Due Date causes no tickets to appear and a DB error in system log

### Versions
osTicket Version | v1.11.0-rc1-344-gc0baa320 (c0baa32)     —  Up to date
Web Server Software | Apache/2.4.29 (Ubuntu)
MySQL Version | 5.7.23
PHP Version | 5.6.38-3+ubuntu18.04.1+deb.sury.org+1

Ubuntu 18.04.01 - up-to-date as of today

*** System log ***
DB Error #1054

[SELECT A1.`number` AS `number`,  A1.`ticket_id` AS `ticket_id`,  A1.`source` AS `source`,  A3.`name` AS `user__name`,  A4.`subject` AS `cdata__subject`,  A1.`isoverdue` AS `isoverdue`,  A1.`duedate` AS `duedate`,  A1.`est_duedate` AS `est_duedate`,  A1.`lastupdate` AS `lastupdate`,  A1.`dept_id` AS `dept_id`,  A5.`name` AS `dept__name`,  A4.`priority` AS `cdata__priority`,  A1.`isanswered` = '0' AS `2GkBZxz`,  (SELECT COUNT(R0.`id`) AS `count` FROM `ost_thread` Q7 JOIN `ost_ticket` Q8 ON (Q7.`object_type` = 'T' AND Q7.`object_id` = Q8.`ticket_id`) LEFT JOIN `ost_thread_collaborator` R0 ON (Q7.`id` = R0.`thread_id`) WHERE Q8.`ticket_id` = A1.`ticket_id`) AS _collabs,  (SELECT COUNT(R0.`id`) AS `count` FROM `ost_thread` Q7 JOIN `ost_ticket` Q8 ON (Q7.`object_type` = 'T' AND Q7.`object_id` = Q8.`ticket_id`) LEFT JOIN `ost_thread_entry` R0 ON (Q7.`id` = R0.`thread_id`) WHERE Q8.`ticket_id` = A1.`ticket_id` AND NOT R0.`flags` & 4 != 0) AS _thread_count,  (SELECT COUNT(R1.`id`) AS `count` FROM `ost_thread` Q7 JOIN `ost_ticket` Q8 ON (Q7.`object_type` = 'T' AND Q7.`object_id` = Q8.`ticket_id`) LEFT JOIN `ost_thread_entry` R0 ON (Q7.`id` = R0.`thread_id`) LEFT JOIN `ost_attachment` R1 ON (R1.`type` = 'H' AND R0.`id` = R1.`object_id`) WHERE Q8.`ticket_id` = A1.`ticket_id` AND R1.`inline` = 0) AS _att_count,  A6.`expire` > NOW() AND NOT A6.`staff_id` = 2 AS `_locked`,  COALESCE(A1.`duedate`,  A1.`est_duedate`,  'zzz') AS `C9` FROM `ost_ticket` A1 JOIN (SELECT Q7.`ticket_id` FROM `ost_ticket` Q7 JOIN `ost_ticket_status` Q8 ON (Q7.`status_id` = Q8.`id`) LEFT JOIN `ost_thread` R0 ON (R0.`object_type` = 'T' AND Q7.`ticket_id` = R0.`object_id`) LEFT JOIN `ost_thread_referral` R1 ON (R0.`id` = R1.`thread_id`) LEFT JOIN `ost_staff` R2 ON (R1.`object_type` = 'S' AND R1.`object_id` = R2.`staff_id`) LEFT JOIN `ost_team` R3 ON (R1.`object_type` = 'E' AND R1.`object_id` = R3.`team_id`) LEFT JOIN `ost_department` R4 ON (R1.`object_type` = 'D' AND R1.`object_id` = R4.`id`) WHERE (Q7.`team_id` IN (1,  2) OR Q7.`staff_id` IN (2)) AND Q8.`state` = 'open' AND ((Q8.`state` = 'open' AND (Q7.`staff_id` = 2 OR R2.`staff_id` = 2 OR Q7.`team_id` IN (1,  2) OR R3.`team_id` IN (1,  2))) OR Q7.`dept_id` IN (1,  4,  5) OR R4.`id` IN (1,  4,  5)) ORDER BY Q7.`C9` DESC LIMIT 50) A2 JOIN `ost_user` A3 ON (A1.`user_id` = A3.`id`) LEFT JOIN `ost_ticket__cdata` A4 ON (A1.`ticket_id` = A4.`ticket_id`) JOIN `ost_department` A5 ON (A1.`dept_id` = A5.`id`) LEFT JOIN `ost_lock` A6 ON (A1.`lock_id` = A6.`lock_id`) WHERE A1.`ticket_id` = A2.`ticket_id`] Unknown column 'Q7.C9' in 'order clause'

 ---- Backtrace ----
 #0 (root)/include/mysqli.php(199): osTicket->logDBError('DB Error #1054',  '[SELECT A1.`num...')
 #1 (root)/include/class.orm.php(3454): db_query('SELECT A1.`numb...',  true,  true)
 #2 (root)/include/class.orm.php(3501): MySqlExecutor->execute()
 #3 (root)/include/class.orm.php(2085): MySqlExecutor->getArray()
 #4 (root)/include/class.orm.php(2035): HashArrayIterator->{closure}()
 #5 (root)/include/class.orm.php(2014): CallbackSimpleIterator->next()
 #6 (root)/include/class.orm.php(2023): CallbackSimpleIterator->rewind()
 #7 (root)/include/class.orm.php(1695): CallbackSimpleIterator->valid()
 #8 (root)/include/class.orm.php(1705): CachedResultSet->fillTo(9223372036854775807)
 #9 (root)/include/class.orm.php(1721): CachedResultSet->asArray()
 #10 (root)/include/staff/templates/queue-tickets.tmpl.php(225): CachedResultSet->getIterator()
 #11 (root)/scp/tickets.php(525): require_once('/var/www/suppor...')
 #12 {main}
Log Date: 12/03/2018 01:17:26 PM

*** PHP Error Logs ***
PHP Fatal error:  Uncaught exception 'InconsistentModelException' with message 'Unable to prepare query:  SELECT A1.`number` AS `number`, A1.`ticket_id` AS `ticket_id`, A1.`source` AS `source`, A3.`name` AS `user__name`, A4.`subject` AS `cdata__subject`, A1.`isoverdue` AS `isoverdue`, A1.`duedate` AS `duedate`, A1.`est_duedate` AS `est_duedate`, A1.`lastupdate` AS `lastupdate`, A1.`dept_id` AS `dept_id`, A5.`name` AS `dept__name`, A4.`priority` AS `cdata__priority`, A1.`isanswered` = '0' AS `2GkBZxz`, (SELECT COUNT(R0.`id`) AS `count` FROM `ost_thread` Q7 JOIN `ost_ticket` Q8 ON (Q7.`object_type` = 'T' AND Q7.`object_id` = Q8.`ticket_id`) LEFT JOIN `ost_thread_collaborator` R0 ON (Q7.`id` = R0.`thread_id`) WHERE Q8.`ticket_id` = A1.`ticket_id`) AS _collabs, (SELECT COUNT(R0.`id`) AS `count` FROM `ost_thread` Q7 JOIN `ost_ticket` Q8 ON (Q7.`object_type` = 'T' AND Q7.`object_id` = Q8.`ticket_id`) LEFT JOIN `ost_thread_entry` R0 ON (Q7.`id` = R0.`thread_id`) WHERE Q8.`ticket_id` = A1.`ticket_id` AND NOT R0.`flags` & 4 != 0) AS _t in /var/www/support/include/class.orm.php on line 3455, referer: https://domain/scp/tickets.php?queue=3&sort=9&dir=1&_pjax=%23pjax-container

**Comment by ntozier** [comment]
I think that @JediKev would say if you are going to run 1.11-rc1 then please pull the most recent version of git and retest.  There have been a large number of bug fixes for this piece of non-stable software and it might have already been addressed.

And I would say that people should not run RC's in production and should only run stable versions. (1.10.4 as of this writing).

**Comment by the-r0cket06** [comment]
This was the most recent pull from the develop-next branch when I opened this ticket/bug report.

This is a small deployment with just myself as a user, so I don't mind running bleeding edge stuff, with the occasional bug.
