### ISSUE TITLE
Notification of New Response to Ticket  | Internal Messages Missing

### ISSUE THREAD

**Issue by jonub** [osTicket/osTicket#463]
When a ticket is transferred, for example from First Level Support (responsible for direct contact with client) to Technical Support, it often seems the case that when Technical support responds with an internal message, the  First Level Support transferer does not get a notification. When there is a large number of open tickets the only way to determine if there has been an internal response on any ticket is to go through each one - very time consuming.

In addition to receiving a notification, it would be useful if a ticket was "flagged" on the list of open tickets to indicate updated information - either from the client or a new internal message has been added.

v1.8.0.1

**Comment by jameswhittington3** [comment]
Holy crap, the tickets waiting on support to respond are in bold? I never noticed until I read this post.
In our case we took this knowledge and targeted that field to make the ticket stand out more.
We added this to scp.css
/* CSS TO Highlight tickets not responded to*/
.ticketPreview b{
    background: rgb(255, 226, 231);
    color: rgb(174, 0, 0);
    display: inline-block;
    padding: 3px;
}

So now they look like this:

![clip_image002](https://cloud.githubusercontent.com/assets/9636067/6755778/dbc18a04-cefb-11e4-99cc-8e13f342da4a.gif)

**Comment by jonub** [comment]
That looks ideal jameswhittington3.
Apart from the css, what code did you use to generate the status column and responses?

**Comment by AndrewJordaan** [comment]
jameswhittington3 does your code rotate the status buttons ? if so that would be perfect. . . 
Also  where does the  "ticketPreview " pull the status from to activate, thanks for the css code

**Comment by AndrewJordaan** [comment]
Here is Darshan's solution that notifies you of a customer response 

http://osticket.com/forum/discussion/85378/change-status-when-client-replies-via-email#latest

Works well for me !
