### ISSUE TITLE
A GET request for file.php where the "key" parameter is an array causes osTicket to email a backtrace to the administrator

### ISSUE THREAD

**Issue by synappnz** [osTicket/osTicket#4637]
### Description

When a GET request is made to file.php where the "key" parameter is an array, osTicket emails a backtrace to the administrator.

### Steps to Reproduce

1. GET /file.php?key%5Bid%60%3D1%20AND%202735%3D2735%23]=1&signature=1&expires=15104725311

**Expected behavior:** Unknown or invalid file page returned without emailing administrator with backtrace

**Actual behavior:** Unknown or invalid file page returned and backtrace is emailed to the administrator and logged with DB Error #1054

### Versions v1.9.14

Server Information
--
osTicket Version | v1.9.14 (8b927a0)                Upgrade        — v1.9.15 is available
Web Server Software | Apache
MySQL Version | 5.6.34
PHP Version | 5.6.36

**Comment by ntozier** [comment]
You are running an out of date and no longer supported version of osTicket.  I would recommend that you update and see if you can replicate the issue.

**Comment by synappnz** [comment]
This issue has been resolved in 1.10.4.
