### ISSUE TITLE
Unable to search by name when creating a new ticket

### ISSUE THREAD

**Issue by c0nfus3d** [osTicket/osTicket#4686]
### Description

On the new ticket page, `/scp/tickets.php?a=open`, we are unable to search by a users name. If you type in a full email address, the search returns a result, but simply typing a name produces an error.

**Browser console:**
`jquery-1.11.2.min.js?9ae093d:4 GET .../scp/ajax.php/users?q=tiffany 500 (Internal Server Error)`

**Apache error log:**
```Fatal error: Uncaught exception 'OrmException' with message 'Union queries must have matching values counts' in /var/www/html/osticket/upload/include/class.orm.php:1283 Stack trace: #0 /var/www/html/osticket/upload/include/ajax.users.php(90): QuerySet->union(Object(QuerySet)) #1 [internal function]: UsersAjaxAPI->search() #2 /var/www/html/osticket/upload/include/class.dispatcher.php(145): call_user_func_array(Array, Array) #3 /var/www/html/osticket/upload/include/class.dispatcher.php(38): UrlMatcher->dispatch(false, Array) #4 /var/www/html/osticket/upload/include/class.dispatcher.php(120): Dispatcher->resolve(false, Array) #5 /var/www/html/osticket/upload/include/class.dispatcher.php(38): UrlMatcher->dispatch('/users', NULL) #6 /var/www/html/osticket/upload/scp/ajax.php(262): Dispatcher->resolve('/users') #7 {main} thrown in /var/www/html/osticket/upload/include/class.orm.php on line 1283```

### Versions

osTicket Version	v1.10.1 (9ae093d) —  Up to date
Web Server Software	Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/5.4.16
MySQL Version	5.5.60
PHP Version	5.4.16

![osticket-user-search-error](https://user-images.githubusercontent.com/3581118/52219510-66e99180-2862-11e9-8716-7c4e1599b1d5.png)

**Comment by JediKev** [comment]
@c0nfus3d 

You're using an old version (1.10.1). Please upgrade to the latest stable version of v1.10.4 and retest.

**P.S.**
I tested this with 1.10.4 and 1.11-rc1 and _cannot_ reproduce your issue.

Cheers.

**Comment by trendchiller** [comment]
We also had this problem and switched to php7 - after the update - then the error was away...
BUT: with php7 we were not able to upgrade to v1.11 (0f229ae) - this needed php5.6.

**Comment by c0nfus3d** [comment]
I have upgraded a couple of things, same issue. 

osTicket Version | v1.10.5
Web Server Software | Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/5.6.40
MySQL Version | 5.5.60
PHP Version | 5.6.40

**Comment by c0nfus3d** [comment]
Still same issue.. :(


osTicket Version | v1.10.5
Web Server Software | Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.3.2
MySQL Version | 5.5.60
PHP Version | 7.3.2

**Comment by c0nfus3d** [comment]
OK so this is dumb.

.../scp/ajax.php/users?q=tiffany

Produces the error. But

.../scp/ajax.php/users?q=adam

Works?

Maybe there is something invalid with our data? Will get back to you..

**Comment by c0nfus3d** [comment]
Interesting development.

The users that were added via an Active Directory sync are the ones who produce errors.

Users who were manually added or added because they sent an email ticket, it works fine.

**Comment by JediKev** [comment]
@c0nfus3d

I have openLDAP so I can test this and try to reproduce. I’ll post back when I have an update.

Cheers.

**Comment by ntozier** [comment]
I just tested this in my environment (we happened to have a new AD user get setup yesterday who hasn't emailed a ticket in yet) and it appears to work okay for us.  Searched by both Name (only first name) and username.

**Comment by c0nfus3d** [comment]
This is the weirdest issue..

Only one user has the first and last name.. so searching for either, she should be the only result.

Searching for the first name, Tiffany, we get an error. Searching by her last name, and she pulls right up as expected.

**Comment by ntozier** [comment]
Look at the ost_user table.  Whats her name in the name field?  Maybe her first name is spelled wrong or something?

**Comment by c0nfus3d** [comment]
The name in the _ost_user.name_ field is spelled correctly **Firstname Lastname** with no special characters or anything suspicious looking

**Comment by c0nfus3d** [comment]
After throwing in a couple of _var_dump()_ and _die()_ statements, I have found the following out..

When searching for the **firstname**, it is going in to the following IF statement, which is what is erroring out.

_(ajax.users.php:86-94):_
```
// Omit already-imported remote users
if ($emails = array_filter($emails)) {
  $users->union(User::objects()
    ->values_flat('id', 'name', 'default_email__address')
    ->annotate(array('__relevance__' => new SqlCode(1)))
    ->filter(array(
      'emails__address__in' => $emails
  )));
}
```

But when searching for the **lastname**, it does not go in to that IF statement, which is when it works.

**Comment by JediKev** [comment]
@c0nfus3d 

Have you tried this yet:
#3456

Cheers.

**Comment by c0nfus3d** [comment]
OMG that did it!

I removed line 87 from _ajax.users.php_, `->annotate(array('__relevance__' => new SqlCode(1)))` and it worked
