### ISSUE TITLE
Formular issue

### ISSUE THREAD

**Issue by Af0x** [osTicket/osTicket#4693]
Hello,

after upgrading from 1.11rc1 to 1.11, input-fields are not displayed anymore, for example when a customer wants to open a new ticket the input-fields for email address and complete name are not shown.

PHP 7.0.33, MariaDB 10.1.37, Apache 2.4.25

German language pack.

Best regards,

Af0x

**Comment by JediKev** [comment]
@Af0x 

I do not have this issue. Any errors via Apache, PHP, database, browser, osTicket error logs?

Cheers.

**Comment by ntozier** [comment]
Do you have the problem if you switch to English?  (wondering if the problem is an outdated German Language pack.)

**Comment by Af0x** [comment]
I don´t think it´s an outdated language pack or a setup issue as it worked in rc1. In my version I can´t do anything with the named fields as they are mandatory to everyone.

**Comment by JediKev** [comment]
@Af0x 

Sorry about that. Here you go:
https://github.com/osTicket/osTicket/pull/4694

Cheers.

**Comment by Af0x** [comment]
lgtm, ty
