### ISSUE TITLE
1.11: Upgrade Issue

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket#4699]
When upgrading from 1.10.4 the saved searches are converted to queues. The queues must not be converted correctly because it throws a `DB Error #1064`:
[SELECT COUNT(DISTINCT CASE WHEN  THEN A1.`ticket_id` END) AS `q15`, COUNT(DISTINCT CASE WHEN (A1.`team_id` IN (2, 5) OR A1.`staff_id` IN (1)) THEN A1.`ticket_id` END) AS `q17`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' THEN A1.`ticket_id` END) AS `q1`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A2.`state` = 'open' AND A1.`isanswered` = '0' THEN A1.`ticket_id` END) AS `q2`, COUNT(DISTINCT CASE WHEN (A1.`team_id` IN (2, 5) OR A1.`staff_id` IN (1)) AND A2.`state` = 'open' AND (A1.`team_id` IN (2, 5) OR A1.`staff_id` IN (1)) AND A2.`state` = 'open' AND A1.`staff_id` IN (1) THEN A1.`ticket_id` END) AS `q6`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-02-07 00:00:00' AND '2019-02-07 23:59:59' THEN A1.`ticket_id` END) AS `q9`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A2.`state` = 'open' AND A1.`isanswered` = '1' THEN A1.`ticket_id` END) AS `q3`, COUNT(DISTINCT CASE WHEN (A1.`team_id` IN (2, 5) OR A1.`staff_id` IN (1)) AND A2.`state` = 'open' AND (A1.`team_id` IN (2, 5) OR A1.`staff_id` IN (1)) AND A2.`state` = 'open' AND NOT A1.`staff_id` IN (1) THEN A1.`ticket_id` END) AS `q7`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-02-06 00:00:00' AND '2019-02-06 23:59:59' THEN A1.`ticket_id` END) AS `q10`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A2.`state` = 'open' AND A1.`isoverdue` = '1' THEN A1.`ticket_id` END) AS `q4`, COUNT(DISTINCT CASE WHEN (A1.`team_id` IN (2, 5) OR A1.`staff_id` IN (1)) AND A2.`state` = 'open' THEN A1.`ticket_id` END) AS `q5`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-02-04 00:00:00' AND '2019-02-10 23:59:59' THEN A1.`ticket_id` END) AS `q11`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' THEN A1.`ticket_id` END) AS `q8`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-02-01 00:00:00' AND '2019-02-28 23:59:59' THEN A1.`ticket_id` END) AS `q12`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-01-01 00:00:00' AND '2019-03-31 23:59:59' THEN A1.`ticket_id` END) AS `q13`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-01-01 00:00:00' AND '2019-12-31 23:59:59' THEN A1.`ticket_id` END) AS `q14` FROM `ost_ticket` A1 JOIN `ost_ticket_status` A2 ON (A1.`status_id` = A2.`id`) LEFT JOIN `ost_thread` A3 ON (A3.`object_type` = 'T' AND A1.`ticket_id` = A3.`object_id`) LEFT JOIN `ost_thread_referral` A4 ON (A3.`id` = A4.`thread_id`) LEFT JOIN `ost_staff` A5 ON (A4.`object_type` = 'S' AND A4.`object_id` = A5.`staff_id`) LEFT JOIN `ost_team` A6 ON (A4.`object_type` = 'E' AND A4.`object_id` = A6.`team_id`) LEFT JOIN `ost_department` A7 ON (A4.`object_type` = 'D' AND A4.`object_id` = A7.`id`) WHERE (A2.`state` = 'open' AND (A1.`staff_id` = 1 OR A5.`staff_id` = 1 OR A1.`team_id` IN (2, 5) OR A6.`team_id` IN (2, 5))) OR A1.`dept_id` IN (3, 7) OR A7.`id` IN (3, 7)]

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'THEN A1.`ticket_id` END) AS `q15`, COUNT(DISTINCT CASE WHEN (A1.`team_id` IN (2,' at line 1<br />
<br />
---- Backtrace ----<br />
#0 C:\inetpub\osTicket\Live\include\mysqli.php(199): osTicket->logDBError('DB Error #1064', '[SELECT COUNT(D...')<br />
#1 C:\inetpub\osTicket\Live\include\class.orm.php(3454): db_query('SELECT COUNT(DI...', true, true)<br />
#2 C:\inetpub\osTicket\Live\include\class.orm.php(3501): MySqlExecutor->execute()<br />
#3 C:\inetpub\osTicket\Live\include\class.orm.php(2085): MySqlExecutor->getArray()<br />
#4 C:\inetpub\osTicket\Live\include\class.orm.php(2035): HashArrayIterator->{closure}()<br />
#5 C:\inetpub\osTicket\Live\include\class.orm.php(2014): CallbackSimpleIterator->next()<br />
#6 C:\inetpub\osTicket\Live\include\class.orm.php(2023): CallbackSimpleIterator->rewind()<br />
#7 C:\inetpub\osTicket\Live\include\class.orm.php(1695): CallbackSimpleIterator->valid()<br />
#8 C:\inetpub\osTicket\Live\include\class.orm.php(1705): CachedResultSet->fillTo(2147483647)<br />
#9 C:\inetpub\osTicket\Live\include\class.orm.php(1328): CachedResultSet->asArray()<br />
#10 C:\inetpub\osTicket\Live\include\class.orm.php(1351): QuerySet->all()<br />
#11 C:\inetpub\osTicket\Live\include\class.search.php(922): QuerySet->one()<br />
#12 C:\inetpub\osTicket\Live\scp\autocron.php(51): SavedQueue::counts(Object(StaffSession), false)<br />
#13 {main}

PHP 5.6.38
IIS

**Comment by JediKev** [comment]
@jdelhome3578 

Right, most of them will not convert correctly. Too many backend changes to the formats of the data. Most will be lost upon upgrade.

Cheers.

**Comment by jdelhome3578** [comment]
@JediKev Should that not just be dropped then during upgrade so that it does not cause errors?
