### ISSUE TITLE
1.11: Annotation Avatar

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket#4700]
When trying to use Avatar as an annotation php error: `PHP Fatal error:  Call to undefined method LocalAvatar::setSize() in C:\inetpub\osTicket\Live\include\class.staff.php on line 303`

php 5.6.38
IIS

**Comment by JediKev** [comment]
@jdelhome3578 

I do not receive this error when using Avatar annotation. I am using PHP 5.6 as well. Where are you putting it? How are you using it?

Cheers.

**Comment by jdelhome3578** [comment]
@JediKev  In the ticket number column and using the built-in oscar for staff.

**Comment by JediKev** [comment]
@jdelhome3578 

Thank you. I can replicate this now.

Cheers.

**Comment by JediKev** [comment]
@jdelhome3578 

**Update:**
I fixed the error but the local avatars are not resized to fit as they weren't meant to be used here so I have to fix this. Will update when I make a pull.

Cheers.

**Comment by JediKev** [comment]
@jdelhome3578 

Here you go:
#4721

Cheers.
