### ISSUE TITLE
automail.php broken?

### ISSUE THREAD

**Issue by Af0x** [osTicket/osTicket#4715]
Hello, it seems the automail.php is broken. Please correct me if I am wrong.

Regards,

Af0x

**Comment by ntozier** [comment]
Version of PHP, osTicket, etc?

What makes you think that it is broken?

**Comment by Af0x** [comment]
osTicket 1.11
PHP 7.0.33, MariaDB 10.1.37, Apache 2.4.25
actually I am searching for someone who can tell me the difference so the issue would be on my side. But as I search the internet for solutions I can´t find anyone who got it working with this, for example: https://serverfault.com/questions/758889/creating-tickets-with-email-in-osticket

**Comment by JediKev** [comment]
@Af0x

Have you tried using PHP 5.6?

Cheers.

**Comment by Af0x** [comment]
nope, it´s not available on my distro anymore and has reached EOL :D

**Comment by Af0x** [comment]
one of guesses was also that the htaccess is not compatible with apache 2.4 but as i reviewed it kinda looks good.

**Comment by Af0x** [comment]
wtf this close and comment button, sorry

**Comment by JediKev** [comment]
Have you checked your Apache/PHP error logs?

You can also try changing your log level to DEBUG in osTicket to see if that throws anything in the osTicket logs.

Cheers.

**Comment by Af0x** [comment]
I enabled DEBUG Log Level but not a bit showing there.
In Apache Log "other_vhosts_access.log" I found the following:
"POST /api/tickets.email HTTP/1.1" 301 570 "-" "osTicket API Client v1.7"

**Comment by JediKev** [comment]
@Af0x

Access logs are typically not that helpful, especially in this case. We need an error, so check the Error Logs, not access logs. (If you don’t know how contact your host)

I do see that the response code was 301 which is Move Permanently. Have you ensured that your Apache has mod_rewrite enabled?

Cheers.

**Comment by Af0x** [comment]
ok, i thought it was enabled. now I got:
"Got error 'Primary script unknown\n'"

**Comment by JediKev** [comment]
@Af0x 

This definitely sounds like a server config issue. You can either google the error and implement a fix or you can ask your hosting provider for assistance.

Maybe this will help?
http://www.coders.pro/2017/01/got-error-primary-script-unknown-update-php-fpm-apache-2-4/

Cheers.

**Comment by Af0x** [comment]
can you tell by this error that the issue is on API-side or on the remote-side?

**Comment by Af0x** [comment]
if I wanted to post a mail to the API directly (without rewrite), what would be the correct url/destination?

**Comment by Af0x** [comment]
After posting directly to pipe.php I got this:
"POST /api/pipe.php HTTP/1.1" 200 275 "-" "osTicket API Client v1.7"

**Comment by Af0x** [comment]
when I post directly to http.php I get
"cannot open input" as reply in a MAILER-DAEMON message

**Comment by Af0x** [comment]
hello, sorry to write again but I updated my last comment with more info and wanted to ask if anyone got it working to create tickets from remote with PHP 7.0 or higher.

**Comment by JediKev** [comment]
@Af0x 

My piping is working just fine minus the no `status_id` issue. Check your db to see if they are actually created and you just don't see them in the UI. If so, then close this and follow [og thread](https://github.com/osTicket/osTicket/issues/4720). If not, then I'm not sure what's going on with your install.

Cheers.

**Comment by Af0x** [comment]
in my db there is no tickets in the ost_tickets column except for the "osTicket Upgraded" Tickets created by the installer.

**Comment by JediKev** [comment]
@Af0x 

Yea, I'm not sure what your issue is then...Have you tried a fresh install on a different server?

Cheers.

**Comment by Af0x** [comment]
not yet. Could a configured open_basedir prevent the script from working?

**Comment by Af0x** [comment]
another idea could be that I use php-fpm. Maybe our setup differ in this way?

**Comment by JediKev** [comment]
@Af0x 

Nah, I'm using PHP v7.2, NGINX, and MariaDB (better fork of MySQL).

Did you try this yet?
#4731

Cheers.

**Comment by Af0x** [comment]
so the big difference would be apache vs nginx and php 7.0 vs 7.2.

I tried the fix and if I post directly to http.php the "Primary script unknown" error is gone and in access-log I get:
"POST /api/http.php HTTP/1.1" 400 455 "-" "osTicket API Client v1.7"

On the other hand if I post to tickets.email the "Primary script unknown" issue is back again and access log says:
"POST /api/tickets.email HTTP/1.1" 404 190 "-" "osTicket API Client v1.7"

MAILER-DAEMON for both cases says: "cannot open input"

**Comment by JediKev** [comment]
@Af0x 

I guess I'm confused on how you're actually attempting to create tickets...can you post exact instructions?

Cheers.

**Comment by Af0x** [comment]
sure:
1. take automail.php out of the /setup/scripts folder,
2. edit URL and API-key and
3. call it with Postfix

Expected behaviour would be that the piped mail gets transformed into a ticket.

**Comment by Af0x** [comment]
are you doing it the same?

**Comment by JediKev** [comment]
@Af0x 

No, I will have to configure mine like this and test when I have time.

Cheers.

**Comment by Af0x** [comment]
any update to this?

**Comment by JediKev** [comment]
@Af0x

Like I said, I’ll have to setup an environment with postfix and configure it with osTicket to test when I have time.

Cheers.

**Comment by Af0x** [comment]
I understand you need time to setup this but maybe someone else is able to try this out?

**Comment by JediKev** [comment]
@Af0x 

Yes, please. If you have anyone else that can test this please do as I really never have much free time.

Cheers.

**Comment by Af0x** [comment]
I personally don´t know anyone using osticket.
What would also work is that you instruct me in debugging this on my system. I already posted the content of a testmail passed by the script (https://github.com/osTicket/osTicket/issues/4715#issuecomment-462177851). If this looks good maybe there is other stuff I can check for you. But I would need noob-proof instructions ^^

**Comment by Af0x** [comment]
Is there by any chance anyone who can test this. This file is shipped with osticket by default so it should work or be removed if nobody has time to fix it.

**Comment by JediKev** [comment]
@Af0x 

It does work.

**Example:**
I created a `.txt` file and inserted raw email content.
```
$ vim mail.txt
```
<img width="575" alt="Screen Shot 2019-06-27 at 14 28 41" src="https://user-images.githubusercontent.com/11823401/60295045-653f6980-98e8-11e9-99a0-b27e240f3d73.png">

I then created an API Key for my server's local address (127.0.0.1) since I'm calling it from cli. I then added the API Key and URL to the `automail.php` script like so:
<img width="906" alt="automail-php" src="https://user-images.githubusercontent.com/11823401/60294712-9c614b00-98e7-11e9-9fc3-32f321fbe33d.png">

After this I ran the following command:
```
$ php setup/scripts/automail.php < mail.txt
```
...  and a ticket was successfully created.
![Screen Shot 2019-06-27 at 14 28 09](https://user-images.githubusercontent.com/11823401/60295034-5d7fc500-98e8-11e9-8a05-a2fd33badd4c.png)

Cheers.

**Comment by Af0x** [comment]
thanks, what php version did you use?

**Comment by Af0x** [comment]
please allow me one more question: does the posting user has to be the same as owner of the api-files? Because in my case they differ. Setting 777 for the api-files and the automail.php did not change anything.

**Comment by Af0x** [comment]
rewrite-Logging result:
> [proxy_fcgi:error] AH01071: Got error 'Primary script unknown\n'
[rewrite:trace3] [rid##########/initial] [perdir /path/to/ticketsystem/api/] strip per-dir prefix: /path/to/ticketsystem/api/tickets.email -> tickets.email
[rewrite:trace3] [rid##########/initial] [perdir /path/to/ticketsystem/api/] applying pattern '^(.*)$' to uri 'tickets.email'
[rewrite:trace2] [rid##########/initial] [perdir /path/to/ticketsystem/api/] rewrite 'tickets.email' -> '/api/http.php/tickets.email'
[rewrite:trace2] [rid##########/initial] [perdir /path/to/ticketsystem/api/] trying to replace context docroot /path/to/ticketsystem/ with context prefix 
[rewrite:trace1] [rid##########/initial] [perdir /path/to/ticketsystem/api/] internal redirect with /api/http.php/tickets.email [INTERNAL REDIRECT]
[rewrite:trace3] [rid###########/initial/redir#1] [perdir /path/to/ticketsystem/api/] add path info postfix: /path/to/ticketsystem/api/http.php -> /path/to/ticketsystem/api/http.php/tickets.email
[rewrite:trace3] [rid###########/initial/redir#1] [perdir /path/to/ticketsystem/api/] strip per-dir prefix: /path/to/ticketsystem/api/http.php/tickets.email -> http.php/tickets.email
[rewrite:trace3] [rid###########/initial/redir#1] [perdir /path/to/ticketsystem/api/] applying pattern '^(.*)$' to uri 'http.php/tickets.email'
[rewrite:trace1] [rid###########/initial/redir#1] [perdir /path/to/ticketsystem/api/] pass through /path/to/ticketsystem/api/http.php

**Comment by Af0x** [comment]
are there any special requirements for the host that exceed the regular requirements of osticket to make this work?

**Comment by JediKev** [comment]
@Af0x

There are no special requirements, if there was they’d be listed in the docs. No they don’t have to be the same User just ensure the user calling the files can read and execute the files.

I would start by researching the errors you are receiving and then go from there. "Primary Script Unknown" is typically due to Apache config issues as it can’t find the files (but they obviously exist).

Cheers.

**Comment by Af0x** [comment]
ok, thank you. maybe this is an Apache issue as I am using Version 2.4.25, see:
https://serverfault.com/questions/847312/rewriting-urls-while-using-mod-proxy-fcgi-and-path-info-ends-up-with-error-404/847750#847750
My script returns 404.

May I ask what webserver you were testing on? If you used apache2, what version did you use?
Thanks & regards

**Comment by Af0x** [comment]
After disabling php-fpm the ticket-creation via automail.php is working. So I close this issue and thank you for assistance.
Regards,
Af0x
