### ISSUE TITLE
Ajax.reports.php Not found

### ISSUE THREAD

**Issue by OgundareIbukun** [osTicket/osTicket#4717]
### Description

In a bid to add "Teams" tab to the Dashboard. I need to make changes to a file named "ajax.reports.php" which cannot be found both on OSticket 1.10.4 and 1.11.x (stable).

I'd like to ask if it was removed, or there is an alternative file in place of it.

Thank you, Looking forward to any available information that'd help.

### Versions : Osticket 1.10.4, 1.11.x (stable)

Admin panel -> Dashboard -> I

OS- windows 10
Browser - Google chrome

**Comment by JediKev** [comment]
@OgundareIbukun 

This is not an issue rather a request for customization assistance. Unfortunately, this is not the place for that. If you would like assistance with customizing osTicket you should post on our [Forum](https://forum.osticket.com) instead. So please close this and post on the Forum.

With that being said I'll go ahead and provide an answer here:
Yea, we don't use that file anymore. You can start here:
https://github.com/osTicket/osTicket/blob/develop/scp/dashboard.php

Cheers.

**Comment by OgundareIbukun** [comment]
Thank you
