### ISSUE TITLE
Plugin uninstall PHP 7.2.

### ISSUE THREAD

**Issue by ntozier** [osTicket/osTicket#4718]
osTicket 1.11 under PHP 7.2.15, uninstalling a plugin [via ui] produces a PHP error:

[11-Feb-2019 15:50:41 America/New_York] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Plugin::uninstall(), 0 passed in C:\inetpub\wwwroot\support\scp\plugins.php on line 43 and exactly 1 expected in C:\inetpub\wwwroot\support\include\class.plugin.php:414
Stack trace:
#0 C:\inetpub\wwwroot\support\scp\plugins.php(43): Plugin->uninstall()
#1 {main}
  thrown in C:\inetpub\wwwroot\support\include\class.plugin.php on line 414

disabling plugin works fine.  It is when you select Delete afterwards that it blows up.  @JediKev confirmed this bug.  This works under PHP 5.6 just fine.

**Comment by TechCare-Aus** [comment]
I don't know if this is related, but I'm seeing errors in my php log stating:

`PHP Warning:  array_merge(): Argument #2 is not an array in /home/USERNAME/public_html/support/include/class.plugin.php on line 290`

that code is

`$info = array_merge($defaults, (@include $path . '/plugin.php'));`

**Comment by JediKev** [comment]
@ntozier 

Here you go:
#4722 

Cheers.

**Comment by ntozier** [comment]
@JediKev confirmed that this fixes the issue.
