### ISSUE TITLE
1.11: No save in notes

### ISSUE THREAD

**Issue by TechCare-Aus** [osTicket/osTicket#4725]
osTicket Version | v1.11 (7b1eee8) —  Up to date
Web Server Software | Apache
MySQL Version | 10.2.22
PHP Version | 7.2.14

**Issue with notes:**

- No save button appears when editing an existing note.
- Also when you click the edit button it brings the web page up to the top of the page again.
- [FEATURE REQUEST] when you click delete first pop open a window that asks for confirmation??

Error message via the console in Chrome shows redactor issues, but I don't know if that is related.

[osTicket_notes_chrome.log](https://github.com/osTicket/osTicket/files/2859314/osTicket_notes_chrome.log)

PHP error log just shows this ... a lot:

`[13-Feb-2019 07:46:58 UTC] PHP Warning:  array_merge(): Argument #2 is not an array in /home/USERNAME/public_html/support/include/class.plugin.php on line 290`

**Comment by JediKev** [comment]
@TechCare-Aus 

Here you go:
#4732

Cheers.

**Comment by TechCare-Aus** [comment]
@JediKev 

Am I meant to also apply the fixes that @greezybacon has made in relation to redactor?? Because applying your fix didn't work :(
Actually made it worse, after editing a fresh note (using Chrome in incognito mode) and clicking create, then trying to edit the note nothing happens.

[osTicket_v1-11_notes_save_issue.log](https://github.com/osTicket/osTicket/files/2863223/osTicket_v1-11_notes_save_issue.log)

**Comment by JediKev** [comment]
Pull the latest and apply the fix. It fixes the issue and throws no more errors in the console. I can edit, delete, create just fine.

Cheers.

**Comment by JediKev** [comment]
@TechCare-Aus

Excuse my ignorance. I left out the freaking `e`...I’ll update tomorrow. Sorry about that.

Cheers.

**Comment by TechCare-Aus** [comment]
@JediKev 

No drama at all mate.

Now to forgive my ignorance (and detract somewhat), but is there a straight forward way to utilise git pull? I am using cPanel but I do have shell access. ATM I rely on manually making the changes.

**Comment by JediKev** [comment]
@TechCare-Aus 

I updated my pull request so it should work properly now.

Also, the best way is to clone to a "staging" folder so you can make changes, etc. without affecting production. So git clone to any directory you want, cd into that directory, checkout 1.11.x, make changes by pulling the pull and merging it or apply it as a hot-fix via git patch/diff, then use our CLI to deploy the code to your HTML dir. 
- `$ mkdir /path/to/hold/osTicket-git/`
- `$ git clone https://github.com/osTicket/osTicket.git  /path/to/hold/osTicket-git/`
- `$ cd /path/to/hold/osTicket-git/`
- `$ git fetch origin`
- `$ git checkout 1.11.x`
- `$ git fetch origin pull/4732/head:JediKev/pull-4732`
- `$ git merge JediKev/pull-4732`
- `$ php manage.php deploy /path/to/html/ -v`

Cheers.

**Comment by TechCare-Aus** [comment]
You sir are a legend. Thank you very much. 

Both the updated commit #4732 and your git walk through are amazing!
