### ISSUE TITLE
1.11: Unable to update or delete Tasks.

### ISSUE THREAD

**Issue by btoddnstar** [osTicket/osTicket#4727]
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about you server.

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

**Comment by JediKev** [comment]
Uhhhh more info? You didn’t fill out the form.

Cheers.

**Comment by btoddnstar** [comment]
Just get "Loading" when trying to delete or update 
a task

**Comment by ntozier** [comment]
Actual version of osTicket? 
Version of PHP?
Webserver and version?
^ all this can be found at admin panel -> Dashboard -> Information.

PHP error log messages?
Browser console errors?
Web browser being used?

**Comment by JediKev** [comment]
https://github.com/osTicket/osTicket/pull/4689

Cheers.

**Comment by btoddnstar** [comment]
Sorry. Sending it soon

**Comment by btoddnstar** [comment]
Server Information
--
osTicket Version | v1.11 (d4e240b) —  Up to date
Web Server Software | Apache/2.4.34 (Win32) OpenSSL/1.0.2o PHP/5.6.38
MySQL Version | 10.1.36
PHP Version | 5.6.38

gdlib | Used for image manipulation and PDF printing
imap | Used for email fetching
xml | XML API
xml-dom | Used for HTML email processing
json | Improves performance creating and processing JSON
mbstring | Highly recommended for non western european language content
phar | Highly recommended for plugins and language packs
intl | Highly recommended for non western european language content
fileinfo | Used to detect file types for uploads
APCu | Improves overall performance
Zend Opcache | Improves overall performance

cgi.fix_pathinfo | "1" is recommended if AJAX is not working
date.timezone | Europe/Berlin

Schema | support (localhost)
Schema Signature | 00c949a623b82848baaf3480b51307e3
Space Used | 65.95 MiB
Space for Attachments | 24.31 MiB
Timezone | Eastern Standard Time (Interpreted as America/New_York)

**Comment by btoddnstar** [comment]
Here is the error from PHP

[Wed Feb 13 13:47:05.858313 2019] [:error] [pid 4572:tid 1908] [client 192.168.10.111:35602] PHP Fatal error:  Uncaught exception 'ObjectNotUnique' with message 'One object was expected; however multiple objects in the database matched the query. In fact, there are 2 matching objects.' in C:\\xampp\\htdocs\\support\\include\\class.orm.php:1355\nStack trace:\n#0 C:\\xampp\\htdocs\\support\\include\\class.orm.php(606): QuerySet->one()\n#1 C:\\xampp\\htdocs\\support\\include\\class.thread.php(3038): VerySimpleModel::lookup(Array)\n#2 C:\\xampp\\htdocs\\support\\include\\class.orm.php(381): ObjectThread::lookup(Array)\n#3 C:\\xampp\\htdocs\\support\\include\\class.orm.php(417): VerySimpleModel->get('thread', NULL)\n#4 C:\\xampp\\htdocs\\support\\include\\class.task.php(389): VerySimpleModel->__get('thread')\n#5 C:\\xampp\\htdocs\\support\\include\\class.task.php(1361): Task->getThread()\n#6 C:\\xampp\\htdocs\\support\\include\\ajax.tasks.php(479): Task->delete(Array, Array)\n#7 [internal function]: TasksAjaxAPI->massProcess('delete')\n#8 C:\\xampp\\htdocs\\support\\include\\class.dispatcher.php(145): call_user_func_array(Array, Array)\n#9 C:\\xampp\\htdocs\\support\\include\\class. in C:\\xampp\\htdocs\\support\\include\\class.orm.php on line 1355, referer: https://service.norstar.net/support/scp/tasks.php?status=closed

**Comment by btoddnstar** [comment]
Using Chrome however I tired from Firefox and Edge. Same results. Just get the spinner with Loading. Only way out is to click back on the browser and that's what generates the PHP error

**Comment by JediKev** [comment]
@btoddnstar 

This means that there are more two records in the database matching the criteria when there should only be one record matching. Basically, you have duplicate IDs somewhere in your database and when the system tries to lookup the thread entries (ie. messages/responses) for the Task there are two records with duplicate IDs which is not supposed to happen hence the ObjectNotUnique error.

Cheers.

**Comment by btoddnstar** [comment]
Ok. So when viewing the records, I don't see any duplicate records. Any way to try and track it down so I can delete it? I am using HeidiSQL

**Comment by btoddnstar** [comment]
So. Because we just started using Tasks, there were only 3 records in the data base. I deleted all 3 from the d-base and now everything works fine. Thank you for pointing me to the issue. Closing the ticket.
