### ISSUE TITLE
I have a problem with the installation of osticket V1.11

### ISSUE THREAD

**Issue by LeopoldoZD** [osTicket/osTicket#4747]
![problem](https://user-images.githubusercontent.com/16768191/53131848-8d325100-3533-11e9-985e-2e9c64a10a14.png)
I'm installing osticket v1.11, but when I enter the ip address, I can not do it and I get "access denied"
Use this tutorial to install it, but this error occurs.
https://technologyrss.com/how-install-osticket-ubuntu-18-04/

**Comment by JediKev** [comment]
@LeopoldoZD

That appears to be a permissions issue. We have a bug/issue with our website where the permissions are removed on the files (but strangely not the directories) in the download. All you need to do is run the following commands and you should be fine:
```
$ find /path/to/osticket/ -type d -exec chmod 755 {} \;
$ find /path/to/osticket/ -type f -exec chmod 644 {} \;
$ chown www-data:www-data -R /path/to/osticket/
```

Cheers.

**Comment by LeopoldoZD** [comment]
it is written like this? 
 /var/www/html/upload/include/ -type d -exec chmod 755 {}\;

**Comment by LeopoldoZD** [comment]
how is the path of the directories in the tutorial are the same as used

**Comment by LeopoldoZD** [comment]
thanks, it works
