### ISSUE TITLE
Wrong ticket count for Advanced Search

### ISSUE THREAD

**Issue by shaderecker** [osTicket/osTicket#4750]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

When an advanced search is performed, the ticket counter in the bottom right corner is wrong 

Note: This ONLY happens in the Advanced Search list, other lists e.g. Open, Closed display the right count numbers.

Tested on multiple fresh installations of 1.11: bug appears
Tested on develop branch: works correctly

### Steps to Reproduce

1. Navigate to Tickets --> Search
2. Choose any Criteria you like (e.g. TicketStatus --> is --> Open)
3. Results show the wrong counter

![peek 2019-02-21 11-33](https://user-images.githubusercontent.com/16366556/53162619-b05d0f00-35cc-11e9-8936-caccd20a6809.gif)

**Expected behavior:**
Right counter in the bottom right corner.

**Actual behavior:**
Wrong counter in the bottom right corner. (Always: 1 - 25 of 500)

### Versions

![image](https://user-images.githubusercontent.com/16366556/53161917-337d6580-35cb-11e9-959e-bf326c7e04da.png)

Server-OS: Ubuntu 18.04.1
Browser: Chromium Version 71.0.3578.98

**Comment by theking81** [comment]
Yes I tested this and I have the same output as above.
So this is a bug.

Server Information
--
osTicket Version | v1.11
Web Server Software | Apache
MySQL Version | 5.7.25
PHP Version | 7.2.15

**Comment by TheHADILP** [comment]
Found a hard-coded 500 in include/class.search.php.
Pull request will follow.

**Comment by theking81** [comment]
Yes this issue now its fixed thanks @TheHADILP

**Comment by shaderecker** [comment]
Closing this in favor of #4972
