### ISSUE TITLE
V1.11 Ticket overview From field empty

### ISSUE THREAD

**Issue by Mad-Piggy** [osTicket/osTicket#4768]
Hi All

I recently updated my osTicket 1.10.2 to 1.11
Upon updating we encountered the from field not being shown correctly in the ticket overview.
<img src="https://i.ibb.co/fpSs27N/Naamloos.png"  />

A retry with new pull from 1.11.x did not resolve the issue.
Also changing browsers and updating the Ubuntu server did not make any change.
<img src="https://i.ibb.co/hcQVMSb/osticket-insall.png" />

**Comment by JediKev** [comment]
@Mad-Piggy

Try latest develop-next. I cannot replicate the same issue.

Cheers.

**Comment by ntozier** [comment]
Actually someone else reported the same thing on the forums.  

Here is the thread and what they did to fix it:
https://forum.osticket.com/d/93600-solved-from-field-username-not-showing-in-lists

**Comment by Mad-Piggy** [comment]
@ntozier thanks this did resolve the issue.

**Comment by ntozier** [comment]
Very welcome. :)
