### ISSUE TITLE
OsTicket inability to import mass number of Users

### ISSUE THREAD

**Issue by OgundareIbukun** [osTicket/osTicket#4770]
[Description of the bug or feature]

I'm currently using OsTicket version 1.11 stable release but i have been encountering some issue. 
I can not import mass user of 20,000 rows from an excel-sheet CSV file. It triggers a 404 error.

Later on, i reduced the rows to 500, After uploading, it indicates 'Successfully imported 498 end users' but only uploads 1 user.

Please i need help with this.

### Versions

 osTicket (v1.11)
![Uploading osticket_image.png…]()

**Comment by JediKev** [comment]
Errors from the php/Apache Error Logs would be nice.

Cheers.

**Comment by OgundareIbukun** [comment]
No Error Logs really.

It eventually worked by having to upload 1000 rows batch by batch, 20 times.

If i may ask, is there any way to make email optional while trying to import mass users.

**Comment by ntozier** [comment]
There is not.  Each user must have a unique email address.
