### ISSUE TITLE
Tickets created with 0 status

### ISSUE THREAD

**Issue by lewiscawte** [osTicket/osTicket#4773]
### Description
My email tickets (pulled by cron) are being added to the database correctly, but, it seems they are being set with a status_id of 0 (in the ticket table) and this causes them not show up in the interface. Replies work as expected.

I've been "fixing" this by running `update osticket_ticket set status_id="1"  where status_id=0;` every once in a while to get my new tickets.

**Expected behavior:** Script to pull new email as per settings, and a ticket to appear in the open feed.

**Actual behavior:** Script pulls emails as per settings, adds it to the database, but does not appear in the interface.

### Versions
Running the latest 1.11.x branch commit (eebef639)
```
Web Server Software | nginx/1.10.3
MySQL Version | 10.1.34
PHP Version | 7.0.33-0ubuntu0.16.04.1
```

**Comment by JediKev** [comment]
@lewiscawte

I guess you didn’t search and see this:
https://github.com/osTicket/osTicket/pull/4758

Cheers.

**Comment by lewiscawte** [comment]
> I guess you didn’t search and see this:
> #4758
I searched, just didn't see it!

**Comment by lewiscawte** [comment]
I applied that patch, and it doesn't fix whatever _this_ is.

**Comment by TechCare-Aus** [comment]
@lewiscawte any logs? PHP logs? Cron output logs? Also don't know if it is related but Nginx is not supported by osTicket at this time.

**Comment by tjouno** [comment]
It seem to be the problem come from APCU with PHP-CLI :

https://github.com/osTicket/osTicket/issues/4720

I'm trying this solution and it seem to be great.
