### ISSUE TITLE
Have osTicket at root of subdomain?

### ISSUE THREAD

**Issue by ovrdrvn** [osTicket/osTicket#4775]
Currently, we have our setup as helpdesk.domain.com/osTicket so users must go to https://helpdesk.comain.com/osTicket

Can we move all of the files inside the osTicket directory to the root of the helpdesk directory so users can type https://helpdesk.domain.com ?

**Comment by ntozier** [comment]
Yes.  You would need to change the Help Desk URL in the Admin panel.

**Comment by ovrdrvn** [comment]
Worked!
