### ISSUE TITLE
Link not works

### ISSUE THREAD

**Issue by DarWiM** [osTicket/osTicket#4776]
https://github.com/osTicket/osTicket/blob/eebef639044674d2bbf7d98664a3e5b4b27d4591/include/class.organization.php#L492

Need replace with this:

`return ROOT_PATH . sprintf('scp/orgs.php?id=%s', $id);`

**Comment by JediKev** [comment]
@DarWiM 

https://github.com/osTicket/osTicket/pull/4755 😉

Cheers.
