### ISSUE TITLE
Custom Fields with checkboxes can't be unchecked

### ISSUE THREAD

**Issue by gitsnow** [osTicket/osTicket#4782]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [X] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [X] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

Custom Fields with checkboxes can't be unchecked.  This issue occurs because both posting and serializing forms don't account for unchecked inputs.

### Steps to Reproduce

1. Add Custom Field with type checkbox to any form
2. Edit the form field and check the checkbox and Save.
3. Edit the form field again, uncheck the field and try to Save.  You will receive an error that the field "is already assigned this value".  If the entire form instead of just the field is edited, the Save will complete successfully, but the field will still be checked.

**Expected behavior:** [What you expected to happen]
Field should be saved with the unchecked value

**Actual behavior:** [What actually happened]
Field is not updated and error pops up

### Versions
osTicket 1.11.0
PHP 7.2.15
Ubuntu 18.04

### Fix
I was able to create a workaround that checks unchecked checkboxes, but sets their values to 0.  This works even though custom checkbox fields have their values set to their ID.  I also hid the inputs before submission to avoid the user seeing all checkboxes as checked.

### Edit scp/js/scp.js

Change Line 702 from
```
function(e) { submit_button = $(this); });
```
to
```
function(e) { submit_button = $(this); uncheckedPrep(); });
```

Add this to bottom of scp/js/scp.js
```
function uncheckedPrep() {
    $("form").submit(function () {
        var form = $(this);
        form.find('input[type="checkbox"]').each(function () {
            var currentCheckbox = $(this);
            currentCheckbox.hide();
            if (currentCheckbox.is(':checked') == false) {
                currentCheckbox.prop('checked', true);
                currentCheckbox.attr('value', '0');
            }
        });
    });
}
uncheckedPrep();
```

**Comment by JediKev** [comment]
@gitsnow

I’ll try to reproduce this tomorrow. You shouldn’t have to add a whole new function, it’s most likely a bug or maybe something that needs updating to the new jQuery standards.

Cheers.

**Comment by gitsnow** [comment]
@JediKev 

I figured as much because this issue looks to have been fixed in past versions.  I just provided my workaround until a more elegant solution could be put into place.

Thanks for the quick reply!

**Comment by JediKev** [comment]
@gitsnow 

Pull request is here:
#4798

Cheers.

**Comment by gitsnow** [comment]
I tested out the official fix and it works!
