### ISSUE TITLE
Unable to view new tickets created for Osticket v.1.11

### ISSUE THREAD

**Issue by Alstondesouza** [osTicket/osTicket#4784]
I have done a lot of research on this issue and unfortunately haven't managed to find the solution , so basically i have upgraded from Osticket v.1.10.5 to 1.11 lately and also upgrade to PHP 7.1 as mentioned in the website 

After doing so i am unable to view any new ticket sent but if i search the ticket number i am able to see the ticket but if i view the searched ticket i get the a message "Access denied. Contact admin if you believe this is in error" i have attached a couple of screenshots.

I have also tried PHP 7.2, 7.3 as well had the same issue thinking it was related to the version.

**Error message when i search the ticket** 
![new ticket access denied](https://user-images.githubusercontent.com/20253302/54029573-c22fdc00-41a0-11e9-9494-87ce5f96f7c5.PNG)

**Searched ticket with ticket number**
![new ticket search](https://user-images.githubusercontent.com/20253302/54029574-c22fdc00-41a0-11e9-980d-395403b6991b.PNG)

**List of all tickets/ Created ticket wont display 858599**
![new ticket](https://user-images.githubusercontent.com/20253302/54029575-c22fdc00-41a0-11e9-982e-f8435bb530dc.PNG)

**Comment by ntozier** [comment]
PHP error logs?
Do you have any saved searches?
Does your user account actually have access to the department that the ticket is in?

**Comment by Alstondesouza** [comment]
Apologies i had not not given agent account permission for that department thank you @ntozier
