### ISSUE TITLE
DB Error after udpate to 1.11

### ISSUE THREAD

**Issue by nielsq** [osTicket/osTicket#4791]
Hey 

after my osticket update I get continuily two different DB Errors at the same time

DB Error #1064
[SELECT COUNT(*) FROM (SELECT A1.`ticket_id` FROM `ost1911_ticket` A1 WHERE AND NOT A1.`topic_id` = 0) __] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND NOT A1.`topic_id` = 0) __' at line 1

 ---- Ablaufverfolgung ----
 #0 (root)/include/mysqli.php(199): osTicket->logDBError('DB Error #1064', '[SELECT COUNT(*...')
 #1 (root)/include/class.orm.php(3454): db_query('SELECT COUNT(*)...', true, true)
 #2 (root)/include/class.orm.php(3510): MySqlExecutor->execute()
 #3 (root)/include/class.orm.php(2940): MySqlExecutor->getRow()
 #4 (root)/include/class.orm.php(1372): MySqlCompiler->compileCount(Object(QuerySet))
 #5 (root)/include/class.search.php(857): QuerySet->count()
 #6 (root)/include/class.search.php(925): SavedQueue->getTotal()
 #7 (root)/include/class.search.php(865): SavedQueue::counts(Object(StaffSession), true)
 #8 (root)/include/staff/templates/queue-tickets.tmpl.php(96): SavedQueue->getCount(Object(StaffSession))
 #9 (root)/scp/tickets.php(525): require_once('/var/www/html/o...')
 #10 (root)/scp/index.php(17): require('/var/www/html/o...')
 #11 {main}

DB Error #1064
[SELECT COUNT(DISTINCT CASE WHEN AND NOT A1.`topic_id` = 0 THEN A1.`ticket_id` END) AS `q15`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' THEN A1.`ticket_id` END) AS `q1` FROM `ost1911_ticket` A1 JOIN `ost1911_ticket_status` A2 ON (A1.`status_id` = A2.`id`) LEFT JOIN `ost1911_thread` A3 ON (A3.`object_type` = 'T' AND A1.`ticket_id` = A3.`object_id`) LEFT JOIN `ost1911_thread_referral` A4 ON (A3.`id` = A4.`thread_id`) LEFT JOIN `ost1911_staff` A5 ON (A4.`object_type` = 'S' AND A4.`object_id` = A5.`staff_id`) LEFT JOIN `ost1911_department` A6 ON (A4.`object_type` = 'D' AND A4.`object_id` = A6.`id`) WHERE (A2.`state` = 'open' AND (A1.`staff_id` = 9 OR A5.`staff_id` = 9)) OR A1.`dept_id` IN (1, 4, 6) OR A6.`id` IN (1, 4, 6)] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND NOT A1.`topic_id` = 0 THEN A1.`ticket_id` END) AS `q15`, COUNT(DISTINCT CASE' at line 1

 ---- Ablaufverfolgung ----
 #0 (root)/include/mysqli.php(199): osTicket->logDBError('DB Error #1064', '[SELECT COUNT(D...')
 #1 (root)/include/class.orm.php(3454): db_query('SELECT COUNT(DI...', true, true)
 #2 (root)/include/class.orm.php(3501): MySqlExecutor->execute()
 #3 (root)/include/class.orm.php(2085): MySqlExecutor->getArray()
 #4 (root)/include/class.orm.php(2035): HashArrayIterator->{closure}()
 #5 (root)/include/class.orm.php(2014): CallbackSimpleIterator->next()
 #6 (root)/include/class.orm.php(2023): CallbackSimpleIterator->rewind()
 #7 (root)/include/class.orm.php(1695): CallbackSimpleIterator->valid()
 #8 (root)/include/class.orm.php(1705): CachedResultSet->fillTo(2147483647)
 #9 (root)/include/class.orm.php(1328): CachedResultSet->asArray()
 #10 (root)/include/class.orm.php(1351): QuerySet->all()
 #11 (root)/include/class.search.php(922): QuerySet->one()
 #12 (root)/include/class.search.php(865): SavedQueue::counts(Object(StaffSession), true)
 #13 (root)/include/staff/templates/queue-tickets.tmpl.php(96): SavedQueue->getCount(Object(StaffSession))
 #14 (root)/scp/tickets.php(525): require_once('/var/www/html/o...')
 #15 (root)/scp/index.php(17): require('/var/www/html/o...')
 #16 {main}

I couldn't find any solution jet.

**Comment by nielsq** [comment]
after updating everything, switching to mariaDB everything is working again

**Comment by lourdas** [comment]
Same error here. I'm with MariaDB 5.5.61 and the error persists.
