### ISSUE TITLE
something Error 

### ISSUE THREAD

**Issue by johnkalangha** [osTicket/osTicket#4802]
MYSQL : 5.7
server: IIS
php. 5.6
osticket version: 1.10.4

anyone can help me, i cant see the php logs even i change my php.ini settings  error_logs, and when i browse my osticket or check any tab its always show this error, but i dont know how to fix this i cant see the php error logs.. 

![image](https://user-images.githubusercontent.com/30627667/54473587-c5683f00-4814-11e9-81ce-d0fa542c99ca.png)

**Comment by johnkalangha** [comment]
Version=1
EventType=APPCRASH
EventTime=131972054454882685
ReportType=2
Consent=1
UploadTime=131972054457183000
ReportIdentifier=9fb56712-47d5-11e9-ba72-005056abe6f5
IntegratorReportIdentifier=bde13748-9f39-457a-bf6d-72385c3ed5a8
NsAppName=php-cgi.exe
AppSessionGuid=00001314-0000-000f-0167-4f60e2dbd401
TargetAppId=W:0006cac7841c977cc494156ad65254e640a800000904!00006c580311883a661621aa3ee26a61f23d3a9bf077!php-cgi.exe
TargetAppVer=2019//01//09:23:12:08!18b11!php-cgi.exe
BootId=4294967295
Response.BucketId=2d5946af97c28f3ffa1431708039b201
Response.BucketTable=4
Response.LegacyBucketId=1879181303777702401
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=php-cgi.exe
Sig[1].Name=Application Version
Sig[1].Value=5.6.40.0
Sig[2].Name=Application Timestamp
Sig[2].Value=5c367fc8
Sig[3].Name=Fault Module Name
Sig[3].Value=ntdll.dll
Sig[4].Name=Fault Module Version
Sig[4].Value=10.0.14393.2608
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=5bd133d4
Sig[6].Name=Exception Code
Sig[6].Value=c0000005
Sig[7].Name=Exception Offset
Sig[7].Value=000000000006bbe3
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.14393.2.0.0.272.7
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=13321
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=bfe8
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=bfe83e6da8927bf1fc70f58204be27d9
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=2660
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=26600d329c0a6793e4694aac69d764b1
UI[2]=C:\PHP\php-cgi.exe
UI[5]=Check online for a solution (recommended)
UI[6]=Check for a solution later (recommended)
UI[7]=Close
UI[8]=CGI // FastCGI stopped working and was closed
UI[9]=A problem caused the application to stop working correctly. Windows will notify you if a solution is available.
UI[10]=&Close
LoadedModule[0]=C:\PHP\php-cgi.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\System32\KERNEL32.DLL
LoadedModule[3]=C:\Windows\System32\KERNELBASE.dll
LoadedModule[4]=C:\Windows\system32\apphelp.dll
LoadedModule[5]=C:\Windows\AppPatch\AppPatch64\AcLayers.DLL
LoadedModule[6]=C:\Windows\System32\msvcrt.dll
LoadedModule[7]=C:\Windows\System32\USER32.dll
LoadedModule[8]=C:\Windows\System32\win32u.dll
LoadedModule[9]=C:\Windows\System32\GDI32.dll
LoadedModule[10]=C:\Windows\System32\gdi32full.dll
LoadedModule[11]=C:\Windows\System32\SHLWAPI.dll
LoadedModule[12]=C:\Windows\System32\combase.dll
LoadedModule[13]=C:\Windows\System32\ucrtbase.dll
LoadedModule[14]=C:\Windows\System32\RPCRT4.dll
LoadedModule[15]=C:\Windows\System32\bcryptPrimitives.dll
LoadedModule[16]=C:\Windows\SYSTEM32\sfc.dll
LoadedModule[17]=C:\Windows\SYSTEM32\WINSPOOL.DRV
LoadedModule[18]=C:\Windows\SYSTEM32\bcrypt.dll
LoadedModule[19]=C:\Windows\SYSTEM32\sfc_os.DLL
LoadedModule[20]=C:\Windows\System32\WS2_32.dll
LoadedModule[21]=C:\Windows\System32\sechost.dll
LoadedModule[22]=C:\PHP\php5.dll
LoadedModule[23]=C:\Windows\System32\ADVAPI32.dll
LoadedModule[24]=C:\Windows\SYSTEM32\MSVCR110.dll
LoadedModule[25]=C:\Windows\System32\ole32.dll
LoadedModule[26]=C:\Windows\SYSTEM32\ODBC32.dll
LoadedModule[27]=C:\Windows\SYSTEM32\DNSAPI.dll
LoadedModule[28]=C:\Windows\System32\NSI.dll
LoadedModule[29]=C:\Windows\SYSTEM32\DPAPI.dll
LoadedModule[30]=C:\Windows\SYSTEM32\IPHLPAPI.DLL
LoadedModule[31]=C:\PHP\ext\php_bz2.dll
LoadedModule[32]=C:\PHP\ext\php_curl.dll
LoadedModule[33]=C:\Windows\System32\WLDAP32.dll
LoadedModule[34]=C:\PHP\libssh2.dll
LoadedModule[35]=C:\Windows\System32\Normaliz.dll
LoadedModule[36]=C:\PHP\LIBEAY32.dll
LoadedModule[37]=C:\PHP\SSLEAY32.dll
LoadedModule[38]=C:\Windows\System32\CRYPT32.dll
LoadedModule[39]=C:\Windows\System32\MSASN1.dll
LoadedModule[40]=C:\PHP\ext\php_fileinfo.dll
LoadedModule[41]=C:\PHP\ext\php_gd2.dll
LoadedModule[42]=C:\PHP\ext\php_gettext.dll
LoadedModule[43]=C:\PHP\ext\php_intl.dll
LoadedModule[44]=C:\PHP\icuuc57.dll
LoadedModule[45]=C:\PHP\icuin57.dll
LoadedModule[46]=C:\PHP\icuio57.dll
LoadedModule[47]=C:\Windows\SYSTEM32\MSVCP110.dll
LoadedModule[48]=C:\PHP\icudt57.dll
LoadedModule[49]=C:\PHP\ext\php_imap.dll
LoadedModule[50]=C:\Windows\SYSTEM32\WINMM.dll
LoadedModule[51]=C:\Windows\SYSTEM32\Secur32.dll
LoadedModule[52]=C:\Windows\SYSTEM32\WINMMBASE.dll
LoadedModule[53]=C:\Windows\System32\cfgmgr32.dll
LoadedModule[54]=C:\Windows\SYSTEM32\SSPICLI.DLL
LoadedModule[55]=C:\PHP\ext\php_mbstring.dll
LoadedModule[56]=C:\PHP\ext\php_exif.dll
LoadedModule[57]=C:\PHP\ext\php_mysql.dll
LoadedModule[58]=C:\PHP\ext\php_mysqli.dll
LoadedModule[59]=C:\PHP\ext\php_openssl.dll
LoadedModule[60]=C:\PHP\ext\php_pdo_mysql.dll
LoadedModule[61]=C:\PHP\ext\php_pdo_sqlite.dll
LoadedModule[62]=C:\PHP\ext\php_apcu.dll
LoadedModule[63]=C:\Windows\system32\mswsock.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=CGI // FastCGI
AppPath=C:\PHP\php-cgi.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=AE94FBD181C93807AD330841483F6217
MetadataHash=-764937988

**Comment by JediKev** [comment]
@johnkalangha

Looking at the error from the second post it appears your PHP CGI stopped working which is causing the app to crash. Once you address the CGI issues you should be fine.

Cheers.

**Comment by johnkalangha** [comment]
Is that correct because of cgi crash thats why the error display?, sir do you have any idea about that error? 
    On Saturday, 16 March 2019, 10:52:56 pm GMT+8, JediKev <notifications@github.com> wrote:  
 
 
@johnkalangha

Looking at the error from the second post it appears your PHP CGI stopped working which is causing the app to crash. Once you address the CGI issues you should be fine.

Cheers.

**Comment by johnkalangha** [comment]
anyone can help me?

**Comment by JediKev** [comment]
@johnkalangha 

If you read the error you posted it says:
>UI[8]=CGI // FastCGI stopped working and was closed
UI[9]=A problem caused the application to stop working correctly. Windows will notify you if a solution is available.
...
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=CGI // FastCGI
AppPath=C:\PHP\php-cgi.exe

So yes, FAST CGI is the culprit. Fix this and you should be good.

Cheers.
