### ISSUE TITLE
Organization page table doesn't sort correctly by Users

### ISSUE THREAD

**Issue by gitsnow** [osTicket/osTicket#4803]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [X] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [X] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

On the Organizations page, the table does not sort correctly by Users.

### Steps to Reproduce

1. Create multiple orgs with different amounts of users
2. Go to the Organizations page and sort table by Users

**Expected behavior:** [What you expected to happen]
Org table should sort by number of Users

**Actual behavior:** [What actually happened]
Orgs are not sorted correctly by Users

### Versions
osTicket v1.11
PHP 7.2.15-0ubuntu0.18.04.1
Ubuntu 18.04

### Fix
I found that the arrays that are created for each Org to populate the table have a key of user_count and not users.  Changing the line in include/staff/orgs.inc.php seems to correct the issue.

Change **Line 21** in **include/staff/orgs.inc.php**

from
```
'users' => 'users',
```
to
```
'users' => 'user_count',
```
Updated code should look like this now
```
$sortOptions = array(
        'name' => 'name',
        'users' => 'user_count',
        'create' => 'created',
        'update' => 'updated'
        );
```

**Comment by JediKev** [comment]
@gitsnow 

Thanks for reporting! Pull is here:
#4806

Cheers.

**Comment by gitsnow** [comment]
Thanks for the quick turnaround!
