### ISSUE TITLE
After Upgrade to 1.11.0 from 1.11.0 RC1 Many MYSQL Queries are slow

### ISSUE THREAD

**Issue by mujizac** [osTicket/osTicket#4805]
### Prerequisites

* [Unknown ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [NO] Do you have any errors in the PHP error log, or javascript console?
* [YES] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [YES] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. Click on various elements in the menus, perform regular tasks inside of osticket
2. Page takes many times longer than normal to load.
3. HTOP shows mysql processes taking 100% of CPU load
4. With slow-query log turned on in mysql we see things like this:
# Time: 2019-03-18T18:19:13.838324Z
# User@Host: root[root] @ localhost []  Id:   109
# Query_time: 153.573105  Lock_time: 0.000282 Rows_sent: 1  Rows_examined: 77897099
SET timestamp=1552933153;
SELECT COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A1.`isanswered` = '0' THEN A1.`ticket_id` END) AS `q1`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A1.`isanswered` = '1' THEN A1.`ticket_id` END) AS `q2`, COUNT(DISTINCT CASE WHEN A1.`staff_id` IN (6) AND A2.`state` = 'open' THEN A1.`ticket_id` END) AS `q3`, COUNT(DISTINCT CASE WHEN NOT (A1.`team_id` = 0 AND A1.`staff_id` = 0) THEN A1.`ticket_id` END) AS `q5`, COUNT(DISTINCT CASE WHEN A1.`isoverdue` = '1' THEN A1.`ticket_id` END) AS `q6`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A1.`ticket_id` = Z1.`ticket_id` THEN A1.`ticket_id` END) AS `q8`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' THEN A1.`ticket_id` END) AS `q4` FROM `ost_ticket` A1 JOIN `ost_ticket_status` A2 ON (A1.`status_id` = A2.`id`) LEFT JOIN `ost_thread` A3 ON (A3.`object_type` = 'T' AND A1.`ticket_id` = A3.`object_id`) LEFT JOIN `ost_thread_referral` A4 ON (A3.`id` = A4.`thread_id`) LEFT JOIN `ost_staff` A5 ON (A4.`object_type` = 'S' AND A4.`object_id` = A5.`staff_id`) LEFT JOIN `ost_department` A6 ON (A4.`object_type` = 'D' AND A4.`object_id` = A6.`id`) LEFT JOIN (SELECT COALESCE(Z3.`object_id`, Z5.`ticket_id`, Z8.`ticket_id`) as `ticket_id`, Z1.relevance FROM (SELECT Z1.`object_id`, Z1.`object_type`, MATCH (Z1.title, Z1.content) AGAINST ('Data Sheet' IN NATURAL LANGUAGE MODE) AS `relevance` FROM `ost__search` Z1 WHERE MATCH (Z1.title, Z1.content) AGAINST ('Data Sheet' IN NATURAL LANGUAGE MODE) ORDER BY relevance DESC) Z1 LEFT JOIN `ost_thread_entry` Z2 ON (Z1.`object_type` = 'H' AND Z1.`object_id` = Z2.`id`) LEFT JOIN `ost_thread` Z3 ON (Z2.`thread_id` = Z3.`id` AND Z3.`object_type` = 'T') LEFT JOIN `ost_ticket` Z5 ON (Z1.`object_type` = 'T' AND Z1.`object_id` = Z5.`ticket_id`) LEFT JOIN `ost_user` Z6 ON (Z6.`id` = Z1.`object_id` and Z1.`object_type` = 'U') LEFT JOIN `ost_organization` Z7 ON (Z7.`id` = Z1.`object_id` AND Z7.`id` = Z6.`org_id` AND Z1.`object_type` = 'O') LEFT JOIN `ost_ticket` Z8 ON (Z8.`user_id` = Z6.`id`)) Z1  ON ((A2.`state` = 'open' AND A1.`ticket_id` = Z1.`ticket_id`)) WHERE (A2.`state` = 'open' AND (A1.`staff_id` = 6 OR A5.`staff_id` = 6)) OR A1.`dept_id` IN (1, 4) OR A6.`id` IN (1, 4);

5. After query finishes, OS ticket moves on.  No errors on screen, nothing logged in php.
**Expected behavior:** Page loads quickly and easily

**Actual behavior:** Pages load slowly, over 60 seconds.

### Versions
1.11.0 via git as of last week.

Web Server Software | Apache/2.4.29 (Ubuntu)
MySQL Version | 5.7.25
PHP Version | 7.2.15-0ubuntu0.18.04.1

Ubuntu 18.04 LTS

**Comment by JediKev** [comment]
@mujizac 

Do you have all standard queues or custom ones as well? If you have custom ones, do you have any with keyword searching? If so this will DRAMATICALLY slow down the queue counts as it has to look through all the records in full-text search. I would recommend deleting the queue with keyword search and everything should be a lot faster.

**Note:**
I do see a queue with keyword searching. Find the queue that's trying to search for "Data Sheet" and remove that text search option or delete the whole queue altogether.

Cheers.

**Comment by mujizac** [comment]
Fair enough.  I believe that you are right.  In my case, I had a queue that I knew wasn't default, but it was "disabled" so I didn't look into it.  Previous to this I deleted a few other queues that we had tried to make and in fact I found that the issue was much better.
So yeah: OSticket causing mysql to do long queries?  Check if you have ticket queues using keywords.
