### ISSUE TITLE
client search not function well

### ISSUE THREAD

**Issue by johnkalangha** [osTicket/osTicket#4813]
![image](https://user-images.githubusercontent.com/30627667/54826779-82faa280-4ceb-11e9-8404-038d94270334.png)

when i search in client only the ticket number is accepted or successfully show..but when i search like the help topic name all the ticket will show...

**Comment by JediKev** [comment]
@johnkalangha 

Uhhhh...what? Please fill out the entire Issue Template so we can get all the information necessary. Please include the exact steps to replicate as well as screenshots to show what you mean.

Cheers.

**Comment by ntozier** [comment]
Also as a side note that version is pretty old you might want to consider upgrading.

**Comment by johnkalangha** [comment]
The search filter does not work in client side..

**Comment by johnkalangha** [comment]
> 
> 
> Also as a side note that version is pretty old you might want to consider upgrading.

maybe if i already integrate all my changes in design in latest version but for now only this version i will use

**Comment by JediKev** [comment]
@johnkalangha 

>The search filter does not work in client side..

I asked that you please fill out the entire Issue Template so we can get all the pertinent information to try and replicate this.

You will need to fill this out before getting assistance as we need all the appropriate information.

Cheers.
