### ISSUE TITLE
Massive Duplicates in number of User profiles after a CSV mass upload

### ISSUE THREAD

**Issue by OgundareIbukun** [osTicket/osTicket#4821]
### Description

I tried uploading a certain amount (700) of users via CSV file, but in return the system uploaded duplicates summing up to over 20,000 in the database

Please, i need help on what could have caused it and the reason. Thank you.

**Expected behavior:** [What you expected to happen]

Upload precise amount of users as indicated in the excel sheet

**Actual behavior:** [What actually happened]

I tried uploading 700 Users but in return over 20000 were uploaded into the database

### Versions
Window Server - OsTicket v1.11 - Google Chrome

**Comment by ntozier** [comment]
Version of osTicket?

I sync all my users every 4 hours using the function in osTicket that the importer uses and I do not have the problem that you described.  Users are unique by email address.  Even re-running the same list just updates the existing users.

**Comment by OgundareIbukun** [comment]
I'm using the stable version, 1.11

**Comment by ntozier** [comment]
Downloaded from osticket.com/downloads?

**Comment by JediKev** [comment]
@OgundareIbukun 

Just tested this with latest develop-next and cannot replicate this issue. The only User accounts created were those in the CSV, no extras.

Is it possible you reloaded the page a few times? This _might_ replay the request before the others finished causing duplicates but I don't see how it would jump from 700 to 20,000.

Cheers.

**Comment by OgundareIbukun** [comment]
I guess its some manual errors. Will look for a way to fix it.
