### ISSUE TITLE
Agent email added to collaborators 

### ISSUE THREAD

**Issue by hans-chen** [osTicket/osTicket#4830]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [*] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [*] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

While the new ticket created by Email and agents' emails were in cc field of that Email.
The agents' emails would be created as new users and added to collaborators list.

**Expected behavior:** 
In case agents' email addresses in cc, not created new user and not listed as collaborators.

Can any one suggest the location in source code which I can twist to stop adding agent to collaborator?

### Versions

osTicket Version | v1.11 (d4e240b) —  Up to date
Web Server Software | nginx/1.12.2
MySQL Version | 5.6.43
PHP Version | 7.1.27

**Comment by JediKev** [comment]
@hans-chen 

This is how the system works. If someone is in the TO or CC fields then they will be added as a User in the system, if not created already.

You'll have to look at the `Ticket::create()` function to see what function creates the User accounts. This will be done at your own risk of course as you're going against the way the system is intended to work.

Cheers.

**Comment by hans-chen** [comment]
@JediKev 

> someone is in the TO or CC fields then they will be added as a User in the system
I fully agree, but agents should be excepted from this rule. 
it doesn't make sense to add Agent's Email to User, Agent is known to system not unknown.

That is why I posted here. If you don't agree, I will close this issue.

**Comment by JediKev** [comment]
@hans-chen 

If _anyone_ sends an email to the support email they are considered a User (even agents), it's just how the system works.

Cheers.

**Comment by hans-chen** [comment]
Thanks.
