### ISSUE TITLE
Ability to Create a ticket on behalf of several users (not collaborators)

### ISSUE THREAD

**Issue by OgundareIbukun** [osTicket/osTicket#4833]
I don't know if i should label this a feature request or probably its something that's in existent already.

I'm looking at creating a single ticket and being able to attach many users to it (This is different from the way collaborators work.).  It create several ticket instances according to the numbers of users included, which means i will be able to attach several users just like the collaborators form.

For instance, i create 1 ticket on behalf of 10 users (attaching their names to it), then it generates 10 different types of tickets, with each belonging to different users.

Is there anyway to do this at the moment? or this could be added as a feature for the next release.

_Thanks to you guys, most especially @JediKev and @ntozier, i'd like to appreciate the support being provided here, so accurate and timely._

**Comment by JediKev** [comment]
@OgundareIbukun 

I appreciate your words of kindness. It means a lot!

>For instance, i create 1 ticket on behalf of 10 users (attaching their names to it), then it generates 10 different types of tickets, with each belonging to different users.

At this time there is no way to do so as we don't have a box to input multiple Users. With this being said you can request this as a feature. With feature requests, each one requested is added to our list of requested features. There is no guarantee that the requested feature will make it in the software soon or even at all though, it just means that we recognize it and will discuss the possibilities of the feature in future versions.

Cheers.

**Comment by OgundareIbukun** [comment]
Alright. thanks.

**Comment by OgundareIbukun** [comment]
Please i'm in dire of help with this issue @JediKev @protich . My job is on the line for this.

I actually considered another option of creating tickets on behalf of collaborators ( since it allows more than one input of users). 

Made some changes in _class.ticket.php_,  it creates multiple tickets based on the number of collaborators but it only fully update the _ost_ticket_ table according to the number of collaborators assigned  while it sends only one instance of the ticket to _ost_ticket__cdata_. which results to only one ticket showing on the Interface. 

I'd appreciate any insight or  new solution with this really. Thanks
