### ISSUE TITLE
"Allow ticket on this status to be reopened by end-users" hangs on Loading....

### ISSUE THREAD

**Issue by vegax87** [osTicket/osTicket#4837]
### Prerequisites

* [✔️ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ❌] Do you have any errors in the PHP error log, or javascript console?
* [✔️ ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [ ✔️] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description
Everytime I go in:   Admin Panel > Lists > Ticket Statuses > Closed > "Item Properties" Tab and I remove the tick on "Allow tickets on this status to be reopened by end users" and click on Save, it hangs on "Loading..." window

### Steps to Reproduce

1. Go to Admin Panel > Lists > Ticket Statuses > Closed > "Item Properties" Tab
2. Remove the tick on "Allow tickets on this status to be reopened by end users"
3. click Save Button

**Expected behavior:** It should save the settings without any issue

**Actual behavior:** When I click Save button, it hangs on "Loading..." window

**Screenshots**

[https://imgur.com/oBd2x9T](https://imgur.com/oBd2x9T) 

[https://imgur.com/a/g8WjuEm](https://imgur.com/a/g8WjuEm)

### Versions

**OSTicket**: 1.11
**OS**: Linux
**WebServer**: Apache
**MariaDB**: 10.1.36
**PHP**: 7.1.27

**Comment by JediKev** [comment]
@vegax87 

I guess you didn't do a recursive search on here (Github) first before creating the issue. Below is a fix for this issue that has already been merged to `develop-next` and, I think, `1.11.x`:
https://github.com/osTicket/osTicket/pull/4758

Cheers.
