### ISSUE TITLE
Malware in osticket.com

### ISSUE THREAD

**Issue by amfolgar** [osTicket/osTicket#4842]
I don't know if this is the correct place to notify, but when entering to osticket.com it redirects to a malicious site. Also, the package in Github was updated 16 hours ago, so I think it could have been compromised.

**Comment by JediKev** [comment]
@amfolgar 

We are aware. We fixed this yesterday and it happened again today.

Cheers.

**Comment by JediKev** [comment]
@amfolgar 

>Also, the package in Github was updated 16 hours ago, so I think it could have been compromised.

I don't see any package on Github that was update 16hours ago...where do you see this?

Cheers.

**Comment by knels** [comment]
https://github.com/osTicket/osTicket/pull/4841 matches the timing @amfolgar mentioned, but it doesn't look like it is malicious.  Was that ACL addition pushed in response to something specific?

**Comment by JediKev** [comment]
@knels 

No...it's a pull request made by me yesterday for something completely unrelated. If he was talking about the pull request then he's just misunderstanding.

Cheers.

**Comment by knels** [comment]
@JediKev, His initial post had me concerned because we're about to roll out an osticket update and I wanted to make sure our timing wasn't terrible and seeing that as the only request in the timeframe he mentioned I felt reassured that it looks like the incident seemed to be limited to the WP install on the main website.

**Comment by JediKev** [comment]
@knels 

Yes, it is only limited to our site...that's why I was like "huh?" when he said something on here was updated lol

Cheers.

**Comment by amfolgar** [comment]
Thanks for the response, I saw the update 16 hours ago here: https://github.com/osTicket, next to the osTicket package and that's why I thought that it could have been compromised. Sorry for the confusion caused.
