### ISSUE TITLE
osTicket website infected with adware

### ISSUE THREAD

**Issue by kawaii** [osTicket/osTicket#4846]
Hello,

It seems that the osTicket website is somehow infected with adware. Each time I visit the site I am redirected to what you see in the screenshot below.

![image](https://user-images.githubusercontent.com/12242877/56023788-986d5600-5d06-11e9-834b-0839511d39f8.png)

This only happens when visiting https://osticket.com and any URI on that domain, the docs site for example is unaffected.

**Comment by uok** [comment]
thanks for reporting, seems to be a hacked Wordpress plugin that is affecting many websites

**Comment by JediKev** [comment]
@kawaii 

Thank you for reporting this. We are already aware and have taken appropriate actions so that this won't happen again (hopefully). 🤞

Cheers.
