### ISSUE TITLE
API Unexpected Data receive email in PHP7.2

### ISSUE THREAD

**Issue by visimitra** [osTicket/osTicket#4852]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
actually test on osticket 1.11, but checking within forum no suceed
* [ ] Do you have any errors in the PHP error log, or javascript console?
no, maillog don't show any error
* [ ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
checking forum, reported ref: https://forum.osticket.com/d/93197-api-unexpected-data
yes, applied fix from:
issue: PHP 7.2 Ticket Status #4758
issue: APC CLI #4731
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?
yes, already

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

[Description of the bug or feature]
create new ticket via email show system log error with API Unexpected Data
thread_entry_recipients: Unexpected data received in API request
system_emails: Unexpected data received in API request
### Steps to Reproduce

1. create ticket via email, sending from email client Android gmail
2. check in the Admin Panel, Dashboard, System Logs

**Expected behavior:** [What you expected to happen]
now error log should be shown, and ticket created already successfully

**Actual behavior:** [What actually happened]
ticket created but there is an error API Unexpected Data

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about your server.
osTicket 1.11
PHP 7.2

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.
Centos 7.x
Google Chrome

**Comment by lkrms** [comment]
I'm observing this on v1.12 too.

The fields being reported as "unexpected" are "thread_entry_recipients" and "system_emails".

On further investigation, these errors are being raised by ApiController::validateRequestStructure because both of those fields are being parsed as arrays, but TicketApiController::getRequestStructure provides no array structure for them.

Good news: this is just a non-strict validation failure. Everything works regardless (as best I can tell, anyway).

To fix it, TicketApiController::getRequestStructure will need to be patched with the structures that were adopted in 731c9fe9 and b7fee361.

**Comment by JediKev** [comment]
@lkrms

I guess you didn’t see this:
#4861

Cheers.

**Comment by lkrms** [comment]
@JediKev guilty as charged! I should have looked through the PRs. Nice one.

**Comment by JediKev** [comment]
@lkrms

No worries at all brother. Just wanted to let you guys know. 🙂

Cheers.

**Comment by visimitra** [comment]
checking 4 days ago, it show another error
thread_entry_recipients/cc/2: Unexpected data received in API request
thread_entry_recipients/cc/1: Unexpected data received in API request

but ticket is still created

**Comment by visimitra** [comment]
checking with osticket 1.12 problem still persist

**Comment by JediKev** [comment]
@visimitra

Please next time do a recursive search in the pull requests. If you did you would’ve seen these:
- https://github.com/osTicket/osTicket/pull/4861
- https://github.com/osTicket/osTicket/pull/4888

Cheers.

**Comment by visimitra** [comment]
@JediKev thankss, resolved.
