### ISSUE TITLE
Forwarded Attached (*.eml) gets lost on ticket creation or reply

### ISSUE THREAD

**Issue by Retr0Pixel** [osTicket/osTicket#4854]
### Prerequisites
* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
I'm using the develop branch and it is a fresh installation.
* [ ] Do you have any errors in the PHP error log, or javascript console?
No errors at all.
* [ ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
I did, they told me to come here and take a look.
https://forum.osticket.com/d/93821-forwarded-attached-email-removed
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?
I did and i could not find a fitting issue report for my problem.

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description
customer sends an email to the mailbox that is used to pull the tickets from.
if he attaches files to it, they get attached to the ticket in the attachment tab.
if he attaches another email (*.eml), that files text is written into the ticket right below the text of the email itself.
at first, i had the cropping feature enabled that cropped everything after the line "answer above this line". that did not only crop previous answers but any (even newly) attached (*.eml) text.
to have the text not being cropped, i disabled that feature, tested and the text of attached emails remains in the ticket now, regardless if the initial email or any reply had the (*.eml) attached, it was put below the origin text.
until i recieved a ticket mentioning an "attached email" that was neither attached in the ticket nor was the text put below the originating email.
that is my problem - this only seems to occur with (*.eml) files attached. every other file gets attached to the ticket fine, regardless of the cropping feature enabled or disabled and regardless if they are attached to the initial email or any reply. i would prefer to have the (*.eml) files handled as attachment as well, since they were attachments in the first place.

### Steps to Reproduce
1. Customer sends an email to the mailbox that is used to pull the tickets from
2. Cronjob executes, pulls emails and creates Tickets
3. Attached Files are put into ticket as Attachment

**Expected behavior:**
Every attached File should be attached as an attachment to the ticket, even .eml

**Actual behavior:**
Forwarded attached .eml files are not attached to the ticket. their text is put below the actual email text. But not consistently. There are customer Mails (most likely sent by Outlook) with a forwarded Email attached to them, and the attachment gets lost completely.

Every other Files are attached as an attachment.

### Versions
osTicket-Version | osTicket FREE v1.11.0 (d4e240b)
Server-Software | Apache
MySQL-Version | 10.1.37
PHP-Version | 7.0.33-0+deb9u3
Debian 9 "Stretch"

**Comment by JediKev** [comment]
@Retr0Pixel 

Yes, we have a patch we are submitting soon. Stay tuned.

Cheers.

**Comment by Retr0Pixel** [comment]
Thank you very much! :)

**Comment by JediKev** [comment]
@Retr0Pixel 

As promised, here it is:
https://github.com/osTicket/osTicket/pull/4857

Cheers.

**Comment by Retr0Pixel** [comment]
Hey, it works perfectly, thank you very much for the quick fix :)
