### ISSUE TITLE
Template set: internal notes won't be saved

### ISSUE THREAD

**Issue by jochenwezel** [osTicket/osTicket#486]
Whatever I do: the notes won't be saved here:
![osticket_bug_template_note_field](https://f.cloud.github.com/assets/3033827/2018854/df107d1e-8816-11e3-8beb-2b56c4586f50.PNG)

Doesn't work for text or html mail template set.

**Comment by CarlosMoraRoa** [comment]
PR => https://github.com/osTicket/osTicket/pull/3901
