### ISSUE TITLE
Mobile Friendly Interface

### ISSUE THREAD

**Issue by husseinsheikh** [osTicket/osTicket#4873]
The osTicket Core, v1.12 is still not mobile friendly so was wondering when would this be developed as it was mentioned in 2017 that it would come in 2018!

**Comment by JediKev** [comment]
@husseinsheikh 

Unfortunately, we never give release dates or predicted release dates, especially for roadmap features (as they are just on the roadmap). With this being said mobile friendly layout is on the roadmap and slated for later versions; that’s all we can say right now.

Please close this as there is a feature request already opened here:
#4214

Cheers.

**Comment by Mistic92** [comment]
Still no update? This software looks like from 2010

**Comment by ntozier** [comment]
@Mistic92 people generally do not look at or update closed issue reports...

**Comment by Mistic92** [comment]
Yep, sorry. But from linked issue I see that people are not looking also at open issues :)

**Comment by fre2mansur** [comment]
You can use the ost-responsive plug-in untill then.
