### ISSUE TITLE
Cron Job on Windows Server 2012 R2

### ISSUE THREAD

**Issue by husseinsheikh** [osTicket/osTicket#4874]
Could you please advise on how to make the cron job work as I have a batch file on Windows Server but it doesn't work. It only works if I login through staff panel then only I get email notification for new tickets. What are the files in Script folder?

**Comment by JediKev** [comment]
@husseinsheikh

This does not appear to be an issue report rather a request for help. GitHub is for reporting bugs, submitting feature requests, or submitting pull requests.

Your request for help is more suitable for our [Forum here](https://forum.osticket.com). Please close this and open a new post on the Forum instead; there you will find the help you need.

Cheers.

**Comment by JediKev** [comment]
@husseinsheikh

I forgot to mention that the way you accomplish a Cron job on Windows is via a Windows Scheduled Task. More information can be found here:
https://docs.osticket.com/en/latest/Getting%20Started/POP3-IMAP%20Settings.html#schedule-polling

Cheers.
