### ISSUE TITLE
ID on queue-count-bucket reused and removing queue count

### ISSUE THREAD

**Issue by 01271** [osTicket/osTicket#4881]
### Description

I have an issue and a feature request.

Issue: the queue-count-bucket id is reused and it's not valid html to have several of the same ID on the page, it should be a class.

Feature request: An option to hide or remove the queue-count-bucket and queue-count elements from OsTicket so that they do not get in the way. Having the queues show how many tickets are closed makes it so that other categories are pushed off of the navbar. 

### Versions

osTicket Version | v1.12 (a076918)     —  Up to date
Web Server Software | Apache
MySQL Version | 5.6.41
PHP Version | 5.6.30

**Comment by JediKev** [comment]
@01271 

You can disable them....**Admin Panel > Settings > Tickets > Settings > Top-Level Ticket Counts > Disable**.

Cheers.
