### ISSUE TITLE
Security: Issue - Private KB articles show up under search results in the user portal

### ISSUE THREAD

**Issue by joeldeteves** [osTicket/osTicket#4889]
### Prerequisites

* [ Y ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ N ] Do you have any errors in the PHP error log, or javascript console?
* [ Y ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [ Y ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

Private articles appear in public portal search results.

### Steps to Reproduce

1. Publish an article as "private"
2. Open the user portal in a private or separate tab or else log out of osTicket
3. Search for keywords that are in private articles

**Expected behavior:** Only public articles should appear in search results

**Actual behavior:** Both private and public articles are showing up under search results

**Note:** When you click on one of the articles in question, nothing happens - so it appears they are not totally accessible publicly, but the titles themselves still show up under the user's search results. This can be a risk because under some circumstances the titles may display sensitive information. Private implies private - articles marked as such should not appear in the public portal PERIOD. Further, reading the titles tells an attacker what kind of data is contained within the knowledgebase.

### Versions

v1.11

Ubuntu 18.04 Host / Docker + Alpine Linux container running NGINX + PHP 7 / FPM

**Comment by magikstm** [comment]
I can't reproduce this in v1.12.

I believe it was fixed in https://github.com/osTicket/osTicket/pull/4771

**Comment by joeldeteves** [comment]
Thank you. I don't know how I missed this when I did a cursory search.

However, I can confirm the issue is solved in v1.12.

Cheers,
