### ISSUE TITLE
Email Fetch Fallback

### ISSUE THREAD

**Issue by eBounc** [osTicket/osTicket#489]
Not used GitHub before, hopefully this is OK.

I have downloaded and installed osTicket and I currently testing.  I have configured the fetch email and everything is working as expected except in the following scenario.

A dummy customer is using a browser based email client which does not seem to populate the references field in the email header.  Consequently the replies are treated as new support tickets - not ideal.

So a couple of questions:
1. Is it possible to activate a fall back, so when the references field is not populated, the body of the email/subject line is scanned to see if this may relate to an existing ticket, especially if the sender email address already exists in the DB.
2. Is there a way of allocating the new ticket so that it can be merged with an existing support ticket?

**Comment by Marterrez89** [comment]
@greezybacon  I'm new to GitHub and I hope not to put a finger on the pain, I'm running OSticket v 1.10 and I would like to know if there's a way to add the ticket subject as a reference so the system can track a ticket if the user decides to actually reply on an entirely different email( it has happened very often to us). Thanks and I hope you can help.

**Comment by ntozier** [comment]
@Marterrez89 It's highly unlikely that will happen.  (Especially since your commenting on a closed issue report)

**Comment by Marterrez89** [comment]
@ntozier  I figured that'll be a very long shot but this post is the closest reference I found about what I wanted to try to do. Thanks anyhow, I'll guess in the future I'll open a new thread.
