### ISSUE TITLE
FEATURE REQUEST: Manage users and organizations via API

### ISSUE THREAD

**Issue by antiuser** [osTicket/osTicket#4890]
Hi! I have a latest version osTickets installation. We have a billing system in our ISP, and we can export users from this system. How can we automate import thousand clients to osTickets?

P. S. We maybe doesnt have email of this users, but we can insert it by ACCOUNT_BILL_ID at ISP dot COM
Thank you!

**Comment by JediKev** [comment]
@antiuser

Write a bash script to pipe a CSV file containing User data to the user-importer CLI and trigger the script with a cron job or something.

Since this is not an issue report, rather a request for help/guidance, please close this and post on the Forum to get further assistance.

Cheers.
