### ISSUE TITLE
Custom List - Add Item - Stuck Loading Dialog

### ISSUE THREAD

**Issue by JoshuaGarrison27** [osTicket/osTicket#4891]
### Prerequisites

* [ N/A ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ Yes ] Do you have any errors in the PHP error log, or javascript console?
* [ Yes ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [ Yes] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

Loading dialog stuck when trying to add a new item to a custom list. This is a fresh install of the latest version of OSTicket ( *v1.12 (a076918)* ).

### Steps to Reproduce

1. Open a custom list (such as Ticket Status)
2. Click 'Add New Item'
3. Type a value for your new item
4. Click Save

**Expected behavior:** Either give an error that you need to select a state or add the item.

**Actual behavior:** Gets stuck at the spinning loading dialog and does not allow you to close the window. You have to refresh the whole page to get out of it. The item does not get added either.

![image](https://user-images.githubusercontent.com/1706923/57706859-88fa6900-7634-11e9-9e86-525cfc315ad9.png)

Browser Console Error:
~~~
Uncaught Error: Syntax error, unrecognized expression: a[href^=#item-properties]
    at Function.se.error (jquery-3.4.0.min.js?a076918:2)
    at se.tokenize (jquery-3.4.0.min.js?a076918:2)
    at se.select (jquery-3.4.0.min.js?a076918:2)
    at Function.se [as find] (jquery-3.4.0.min.js?a076918:2)
    at k.fn.init.find (jquery-3.4.0.min.js?a076918:2)
    at new k.fn.init (jquery-3.4.0.min.js?a076918:2)
    at k (jquery-3.4.0.min.js?a076918:2)
    at HTMLDivElement.<anonymous> (scp.js?a076918:743)
    at Function.each (jquery-3.4.0.min.js?a076918:2)
    at k.fn.init.each (jquery-3.4.0.min.js?a076918:2)
~~~

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about your server.
![image](https://user-images.githubusercontent.com/1706923/57706568-feb20500-7633-11e9-85e6-79e9bd76867f.png)

Windows Server 2016
Tested on the following browsers:
* Google Chrome | 74.0.3729.131 (Official Build) (64-bit) (cohort: Stable)
* IE | 11.1087.16299.0

**Comment by matzneda** [comment]
Confirming this error on v1.11 and v1.12 using MySQL 5.7.26 and PHP 7.2.16.

How to prevent this error and save the list item (Ticket Status) successfully:
You need to select a "State" (mandatory field) of the Ticket before saving (2nd Tab "Item Properties")
![Add State](https://user-images.githubusercontent.com/5678296/57782208-11a80080-772c-11e9-8269-aeb0fbfbce78.jpg)

**Comment by JoshuaGarrison27** [comment]
Yeah, I can confirm that @matzneda's workaround does work.

Obviously still a problem and I hope it gets fixed. If developers need any more information, I am happy to provide it.

**Comment by JediKev** [comment]
@JoshuaGarrison27 

@matzneda wasn't suggesting a workaround, that's the actual workflow. The `State` field is _mandatory_ so you _must_ fill it out before submitting the modal.

I do however agree that the modal spinning and not displaying an error message is a bug. Will eventually look into this.

Cheers.
