### ISSUE TITLE
Database connection information Unable to connect to MySQL server: Server sent charset unknown to the client. Please, report to the developers

### ISSUE THREAD

**Issue by crqcastro** [osTicket/osTicket#4893]
When I install the osticket it appears the error "Database connection information Unable to connect to MySQL server: Server sent charset unknown to the client. Please, report to the developers";
PHP Version 7.0.1
Server version: 8.0.12 MySQL Community Server
Server AP: Apache 2.0

**Comment by JediKev** [comment]
@crqcastro 

This is a known MySQL bug. What's all your character sets for your server? They all need to be `UTF8` _not_ `UTF8mb4`.

Take a look at the following documents, update all necessary settings, and you should be okay.
- https://stackoverflow.com/questions/43437490/pdo-construct-server-sent-charset-255-unknown-to-the-client-please-rep
- https://bugs.mysql.com/bug.php?id=85946

Cheers.
