### ISSUE TITLE
Sort ticket by priority

### ISSUE THREAD

**Issue by g4b0** [osTicket/osTicket#4903]
### Description

Is it possible to let the user view and sort by priority in Tickets list (/tickets.php), just like operators can do in /scp/tickets.php?

### Steps to Reproduce

Operator
![osticket-op](https://user-images.githubusercontent.com/2427390/58428496-fc739000-80a2-11e9-9228-90b545462a6e.png)

User
![osticket-us](https://user-images.githubusercontent.com/2427390/58428510-05fcf800-80a3-11e9-8e0b-163fdd560102.png)

### Versions

osTicket v1.12
ubuntu 16.04
apache 2.4
php 7.0

**Comment by JediKev** [comment]
@g4b0 You would have to accomplish this by customizing the code. Customizations are more suitable for the [Forum](https://forum.osticket.com). I'm closing this so you may post it on the Forum. Re-open if necessary.

Cheers.

**Comment by g4b0** [comment]
Thanks for the hint, but if I customize the code I will loose the possibility to upgrade osTicket without patch it every time...

**Comment by JediKev** [comment]
@g4b0 

You are correct. Typically, you'd create a patch so you can re-apply the changes after upgrade. If you don't want to do that you'll just wait for a feature like this to be built/released. There are no plans currently to develop such feature so there's no telling when it will be developed/released. With this being said it's on our List of Requested/Suggested Features.

Cheers.

**Comment by g4b0** [comment]
Ok, thanks.

Cheers.
