### ISSUE TITLE
Missing RCRON

### ISSUE THREAD

**Issue by Naeksu** [osTicket/osTicket#4918]
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

[Missing RCRON Files]

### Steps to Reproduce

1. [There's no RCRON files]
2. [There's no Script folder]
3. [There's no api/task folder]

**Expected behavior:** [To have an RCRON file]

**Actual behavior:** [Nothing, missing file]

### Versions
Latest Version

Admin panel -> Dashboard -> Information which also additionally gives you information about your server.

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

**Comment by JediKev** [comment]
@Naeksu 

Please, next time look though the code. If you did you would've found this:
https://github.com/osTicket/osTicket/blob/develop/setup/scripts/rcron.php

You can even use the search feature to find the file:
https://github.com/osTicket/osTicket/search?q=rcron.php&unscoped_q=rcron.php

AND even the "Find File" feature:
https://github.com/osTicket/osTicket/find/develop

Cheers.
