### ISSUE TITLE
Sorting / Asigned options

### ISSUE THREAD

**Issue by Naeksu** [osTicket/osTicket#4920]
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Change sorting order / Asigned

It's not a bug persé, I just need help figuring out how to add a button for sorting on Ticket Status/Department or how to activate/change current ones.

### Steps to Reproduce

So my question here is really. There's 2 options on our old osTicket system that's:
Sort by "Assigned"
Sort by Date/Due Date/Created etc

**Expected behavior:** I would like to have an option to sort on Statuses/Departments, I can't seem to find any option for where this is done

**Actual behavior:** Not the above

### Runing latest version

Admin panel -> Dashboard -> Information which also additionally gives you information about your server.

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

**Comment by JediKev** [comment]
@Naeksu 

Being that this is not an issue report or feature request I will direct you to post this on our [Forum](https://forum.osticket.com). There you may ask any questions and receive community assistance.

With this being said I'll give you a starting point, edit the queue and add a new Sort criteria.

Cheers.
