### ISSUE TITLE
The source list for Content Security Policy directive 'frame-ancestors' contains an invalid source

### ISSUE THREAD

**Issue by stevland** [osTicket/osTicket#4928]
I am struggling to set up an iFrame on my website to pipe content from my osTicket 1.12 installation.

As per [iframe: Allow Multiple iFrame Domains #4781](https://github.com/osTicket/osTicket/pull/4781) I have added my domain to the _Allow iFrames_ field.

Console:
`The source list for Content Security Policy directive 'frame-ancestors' contains an invalid source: ''https://rede.ca''. It will be ignored.`

I don't know if it is relevant, but when I paste the console log here it looks like https;//redec.ca is encased in double quotes ("), but they are actually two single quotes (' ') on either end.

**Comment by JediKev** [comment]
@stevland 

I've noticed this in some cases and actually have a fix for this coming very shortly.

Cheers.

**Comment by stevland** [comment]
Incredibly fast response! 

Sorry to be a pain, but I am actually setting this up for a third-party who just upgraded from 1.10 to 1.12. He relies on iFrame-piped forms for his business. Can you suggest a quick work-around (such as adding some code to include/client/header.inc.php) that doesn't involve using the API?

We sure would appreciate it.

Failing that, I guess I'll have to roll up my sleeves and try to figure out the API.

**Comment by JediKev** [comment]
@stevland 

Actually about to submit it so give me a few ;)

Cheers.

**Comment by stevland** [comment]
You, sir, are a god among geeks.

**Comment by JediKev** [comment]
@stevland 

My memory is failing me.. I had already submitted a fix for this that has been merged already (should already be in v1.12). Look to see if you have these changes already as it's supposed to be fix this issue:
https://github.com/osTicket/osTicket/pull/4844

I even tested that domain with my installation and it works without a hitch! It prints:
```
Content-Security-Policy: frame-ancestors https://rede.ca;
```

Cheers.

**Comment by stevland** [comment]
Awesome! If this comes up for anyone else in the near future, all I had to do was change

**include/client/header.inc.php**  line 9  from:

`header("Content-Security-Policy: frame-ancestors '".$cfg->getAllowIframes()."';");`

to:

`header("Content-Security-Policy: frame-ancestors ".$cfg->getAllowIframes().";");`

Thank you for your help, Kev.

**Comment by JediKev** [comment]
Closing, re-open if necessary.
