### ISSUE TITLE
1.10: ticket closed email notification

### ISSUE THREAD

**Issue by zzaazh01** [osTicket/osTicket#4933]
Hi guys

I found that ticket status changed by agent will not be notified to user by email ,at the same time no any email templates about close ticket notification. could you advise me how to do with it ?
If the ticket closed by agent, how can the system automatic notify user the ticket status change ?

**Comment by ntozier** [comment]
osTicket does not have a "status change" or "Closed" notification.
Your agents would have to reply to the user at the same time that they change the status or close the ticket.  We use "Canned Responses" for this purpose.
