### ISSUE TITLE
ReplyTo-Filter does not use ReplyTo-Name

### ISSUE THREAD

**Issue by Af0x** [osTicket/osTicket#4935]
Hello,

I activated the ReplyTo-Filter to use the information out of this header, if present.

The problem is it does not use the ReplyTo-Name for ticket creation. Instead it just uses the senders name.

Is this a bug or working as desired?

Would it be possible to use that name instead? If yes, can someone please tell me how?

Thanks & regards,

Af0x

**Comment by JediKev** [comment]
@Af0x 

I cannot reproduce your issue using latest pull from `develop-next` (which is `v1.12`). I added a Reply-To header to my email, added a "Use Reply-To Header" filter, and everything worked as expected.

Any errors in your error logs?
What does your Reply-To header look like?

Cheers.

**Comment by Af0x** [comment]
maybe I have to add that I use the automail.php to create the ticket via API.
The ReplyTo-Section looks like this: 
ReplyTo: Full Name <user@domain.tld>
Regards

**Comment by Af0x** [comment]
I updated my previous answer a little

**Comment by JediKev** [comment]
@Af0x

What exactly is the name that is used in the header? It shouldn’t matter how the ticket is created as they all go through the same process.

Cheers.

**Comment by Af0x** [comment]
In my test there was an
> é
in that name.

**Comment by Af0x** [comment]
but even if I remove that letter, there is no change. The Full Name out of the Reply-To-Header is not used.

**Comment by Af0x** [comment]
ok, I´m digging deeper. As the first submitted name seems to be the one used in any further support requests from that e-mail address, my prior statement is wrong as the name is used if no special character is contained in that Full Name.
The Full Name with special character befor was something like this:
`=?iso-8859-1?Q?Full=E9_Name?=`
what should read like this: Fullé Name
The subject also contained this Full Name but was transferred correctly
`=?iso-8859-1?Q?Request_from_Full=E9_Name?=`
what should read like this: Request from Fullé Name

**Comment by JediKev** [comment]
@Af0x

I figured as much that’s why I asked. We have a pull for this here:
https://github.com/osTicket/osTicket/pull/4894

If the name contains a special char it’s supposed to be quoted (this is an email standard everyone is supposed to follow). If not it usually breaks email parsers. Whatever you used to send that email is not formatting the name properly which breaks in osT. That’s fine though because the pull formats it correctly if incorrectly formatted.

Cheers.

**Comment by Af0x** [comment]
I applied that fix and everything is fine. Very nice! Thank you so much.
Regards
