### ISSUE TITLE
Adding collaborator AFTER typing a blurb loses blurb

### ISSUE THREAD

**Issue by TechCare-Aus** [osTicket/osTicket#4941]
### Description

If you start typing a response to a ticket. Then decide to add another collaborator, everything you have typed that doesn't get saved as a draft is lost.

### Steps to Reproduce

1. Start typing in a response to a Support Ticket
2. Add a new collaborator
3. Click Save
4. Response is lost

**Expected behavior:**
I expect that pressing save does NOT refresh the page. Or if it does refresh the page it actually SAVES the typed blurb FIRST!

**Actual behavior:**
Response is lost!

### Versions

osTicket Version | v1.12 (a076918) —  Up to date
Web Server Software | Apache
MySQL Version | 10.3.16
PHP Version | 7.2.19

**Comment by JediKev** [comment]
@TechCare-Aus

This is not a bug. You have to let a draft save first. When you add a collaborator the page reloads and when a page reloads any unsaved data is lost. Since you didn’t let the draft save the content was lost. In order to let a draft save you must wait 30 seconds after typing.

Cheers.

**Comment by TechCare-Aus** [comment]
Ok I get that it might not be a "bug" in your eyes. But it makes for a huge annoyance. In 30 seconds I can type a lot of stuff. Is there a way that I can change 30 seconds to be 1 second?

**Comment by JediKev** [comment]
@TechCare-Aus

It’s not every 30 seconds, only 30 seconds after you stop typing. You can take a look at the redactor JS code under `js/` to change this behavior. I wouldn’t recommend 1 second though as that will be a ton of requests going to the server and database per Agent responding.

Cheers.

**Comment by TechCare-Aus** [comment]
Ok. Well when I use Gmail and I'm typing away it saves what I'm typing in drafts automatically as soon as there is a delay after me typing. So if I were to make it 5 seconds, would that be safer?

**Comment by JediKev** [comment]
@TechCare-Aus

That’s exactly what we do except when there is a 30 second delay after typing. Yes, 5-15 seconds would be the sweet-spot I’d say as it won’t be too many requests and it will be much quicker.

Cheers.

**Comment by TechCare-Aus** [comment]
Lolz... here is the PR #4955

**Comment by JediKev** [comment]
@TechCare-Aus Yes, we decided to improve on this after all as we received more reports of it. 👍🏻

**Comment by TechCare-Aus** [comment]
@JediKev very much appreciated mate. Love osTicket!
