### ISSUE TITLE
[1.12] Answer on closed ticket does not reopen it

### ISSUE THREAD

**Issue by Af0x** [osTicket/osTicket#4944]
hello,
using osticket 1.12 if a customer answers to a closed ticket, the ticket does not get reopened and instead a new ticket is created.

Also on the webview the customer has no possibility to answer on a closed ticket. It appears a red bordered yellow backgrounded box that says 
> This ticket is marked as closed and cannot be reopened.

Is there any option I may have missed?

Regards,

Af0x

**Comment by JediKev** [comment]
@Af0x

Please refrain from posting questions on GitHub. This is a place to report bugs with the code, to make feature requests, to report security issues, and to submit pull requests. If you would like to post questions like this please post on the [Forum](https://forum.osticket.com) instead where you will receive community assistance. I would also encourage you to review our documentation [here](https://docs.osticket.com) when you have configuration questions like this as the docs explain all the settings and new features in the software.

I will go ahead and answer your question here though. Go to `Admin Panel > Manage > Lists > Ticket Statuses > click Closed status > Item Properties > Enable the option for Allow Reopen > Save Changes`. If you have this option disabled then a Closed ticket cannot be reopened unless an agent manually changes the status.

Cheers.

**Comment by Af0x** [comment]
thank you, the box was checked by default so the described behaviour is still occurring. Also in my installation I only have the choice of 2 Statuses (open and closed).

**Comment by JediKev** [comment]
@Af0x

Check the database because the box explicitly says “the ticket is marked closed and cannot be reopened” which means the status is set to not reopen.

You should also do some checking around the below lines of code to see what’s going on:

Client View
https://github.com/osTicket/osTicket/blob/e3f6c6ace66d9dda18b27e9408222dca73a42168/include/client/view.inc.php#L8

TicketStatus::isReopenable()
https://github.com/osTicket/osTicket/blob/e3f6c6ace66d9dda18b27e9408222dca73a42168/include/class.list.php#L1138-L1149

Cheers.

**Comment by Af0x** [comment]
After resaving this option it now works. But still I only have 2 options (open and close) for Status when answering to a ticket.

**Comment by JediKev** [comment]
@Af0x

Do you mean you have more than 2 statuses under Lists > Ticket Statuses but only two are appearing? If so, check to see if the others are enabled as you can disable Statuses.

Cheers.

**Comment by Af0x** [comment]
yes, there are in total 5 Statuses (open, resolved, closed, archived, deleted), when answering to a ticket the only options are open and close. I deactivated all of them and reactivated them again but still no change.

**Comment by JediKev** [comment]
@Af0x

Archived and Deleted are placeholder Statuses that cannot be used currently. But Resolved should be an option.

Cheers.

**Comment by Af0x** [comment]
I thought so. But unfortunately it´s not :(

**Comment by Af0x** [comment]
Please note my updated information. Thank you

**Comment by JediKev** [comment]
@Af0x

Could be but doubt it. 

Then something must be up with the resolves status. Compare the records in the db to see if there is anything out of place. Look for errors in your Apache/PHP logs.

Cheers.

**Comment by Af0x** [comment]
no errors in logs. Db looks like attached image (table ost_ticket_status):

![ticket_status](https://user-images.githubusercontent.com/7013929/60760783-a4359380-a03b-11e9-9ed5-392fc4eef84e.png)

**Comment by Af0x** [comment]
Any further ideas? I am using PHP 7.0.33-0, MySQL-MariaDB 5.5.5-10.1.38, Apache 2.4.25. 
Regards

**Comment by Af0x** [comment]
The list was created 2016-09-03 if this is relevant. Since then I only upgraded my helpdesk. I hope to fix this without reinstall.

**Comment by JediKev** [comment]
@Af0x

What’s `Gel\u00...` i see in the `Properties` column?? Can you send a screenshot of the full properties and post a screenshot of the properties when you edit the list item in the UI??

Cheers.

**Comment by Af0x** [comment]
Screenshots attached

before:

![before_edit](https://user-images.githubusercontent.com/7013929/60837322-336fb200-a1c8-11e9-9e01-4af020814d4e.png)

after:

![after_edit](https://user-images.githubusercontent.com/7013929/60837321-336fb200-a1c8-11e9-8402-69ac2299c0f5.png)

**Comment by JediKev** [comment]
@Af0x

I would assume it’s the `\u00f6` part in the properties that’s causing Resolved to not appear. I’d change the text to something without special chars to see if that’s the cause.

Cheers.

**Comment by Af0x** [comment]
Already tried it. Unfortunatley it didn´t change anything.

**Comment by JediKev** [comment]
@Af0x 

Just got back to my computer so I can now check my instance. 👍

Try setting the `mode` for Resolved to `1` and retest.

Cheers.

**Comment by Af0x** [comment]
nothing :(
tried deactivating and reactivating, if I now try to edit the text of that status it is showing infinite loading animation.

**Comment by JediKev** [comment]
@Af0x 

Then there is an error being thrown that you need to look at/post. Check Apache/PHP error logs.

Cheers.

**Comment by Af0x** [comment]
error log has no new entries. Earlier there was an ajax error but I don´t think it´s related to this issue:
> script '/path/to/ticketsystem/kb/ajax.php' not found or unable to stat, referer: https://ticketsystemurl.tld/kb/index.php

**Comment by JediKev** [comment]
@Af0x 

I think the issue lies with the `state` of Resolved status being set to `resolved`. There is no State option called `resolved` so this would be an invalid state which would make the status not appear in the status list. Change the `state` for the Resolved status to `closed` and retest.

Cheers.

**Comment by Af0x** [comment]
I left the `mode` at `1` and changed to closed and now it shows :)

**Comment by JediKev** [comment]
@Af0x 

Awesome. Don't know how it was changed but being that `resolved` isn't even a valid `state` I'm thinking someone manually updated the `state` value via the database.

Cheers.

**Comment by Af0x** [comment]
can I leave the `mode` at `1` (don´t know what it does)?

**Comment by JediKev** [comment]
@Af0x 

Yes, it's supposed to be `1`, only for Resolved though...all other statuses are set to `3`. 👍 

Cheers.

**Comment by Af0x** [comment]
thank you so much. I also don´t know how it became like this and can´t remember changing anything in this table.
Regards
