### ISSUE TITLE
Potential version issue?

### ISSUE THREAD

**Issue by TechCare-Aus** [osTicket/osTicket#4949]
G'day guys,

I'm running the latest git using develop-next. These are my commands:

```
cd /home/USER/osTicket-git
git checkout develop-next
git fetch origin
git merge
php manage.php deploy /home/USER/public_html/support/ -v
```

If I check my version it shows up as:
v1.11-214-gb5fbfccb (b5fbfcc) —  Up to date

Isn't it meant to be v1.12??

**Comment by protich** [comment]
You're not matching correctly.  It should be `git merge origin/develop-next`

**Comment by TechCare-Aus** [comment]
Thanks mate. Shows up properly now. Cheers!
