### ISSUE TITLE
Support for PHP 7.3?

### ISSUE THREAD

**Issue by Lars1963** [osTicket/osTicket#4966]
Up front:
1. PHP 5.X and 7.0 have reached there EOL 6 months ago
2. PHP 7.1 is reaching his EOL in 4 months from now
3. PHP 7.2 end of active support is also reaching in 4 months from now

Question:
Because of security issues: Isn't it time to stop supporting PHP <7.0, use PHP 7.3 as recommend and start the support for PHP 7.4?

**Comment by JediKev** [comment]
@Lars1963

We already support PHP 7.3...it just so happens that our code still works with PHP 5.6 as well. You obviously don’t have to use 5.6-7.2 if you don’t want to. We can update our docs so this is not a big deal.

We will start PHP 7.4 support once it’s time.

Cheers.

**Comment by Lars1963** [comment]
@JediKev 
Thx for your answer. Yes, the docs are not clear here, so updating them seems a good idea to me.

Nevertheless: imo support for php <7.0 really should be dropped.
