### ISSUE TITLE
Feature Request : for Custom SLA configuration

### ISSUE THREAD

**Issue by gaursh** [osTicket/osTicket#4969]
Hi All,

Is there any configuration available in OSticket1.12 to only keep running SLA timer for Client working hrs only, Which should exclude others than office hrs and client holidays and Saturday sunday exlcusion.

If its there, please let me know from where i can change that, or it should be part of next delivery. Without that it might be difficult to manage SLAs.

SLA custimization should have feature 
1> to set Client working hrs 
2> Exclude any Client Holdidays
3> Exclude Weekends(Saturday Sunday)

** If its not, kindly request to add this feature in Osticket, this is affecting the SLAs during outside office hrs, in weekends and in client holiday.**

Thanks

**Comment by gaursh** [comment]
Once Set any SLA with these filter, All open ticket with this custom SLA PLAN should follow that set time Limit.

**Comment by protich** [comment]
I'm currently working on a feature to add Business Hours & Holidays via schedule - I'll have a preview PR in the coming weeks.

**Comment by gaursh** [comment]
Thanks

**Comment by johnkalangha** [comment]
Wow, waiting for this feature, god bless

**Comment by protich** [comment]
PR #4984
