### ISSUE TITLE
DB Error #1054

### ISSUE THREAD

**Issue by ikolubr** [osTicket/osTicket#4987]
Hi guys,
Just starting to get these errors on a 1.12.2 install:

[SELECT COUNT(DISTINCT CASE WHEN A1.`ip_address` IS NOT NULL AND A1.`ticket_id` = Z1.`ticket_id` THEN A1.`ticket_id` END) AS `q15`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' THEN A1.`ticket_id` END) AS `q1`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A2.`state` = 'open' AND A1.`isanswered` = '0' THEN A1.`ticket_id` END) AS `q2`, COUNT(DISTINCT CASE WHEN (A1.`team_id` IN (1) OR A1.`staff_id` IN (6)) AND A2.`state` = 'open' AND (A1.`team_id` IN (1) OR A1.`staff_id` IN (6)) AND A2.`state` = 'open' AND A1.`staff_id` IN (6) THEN A1.`ticket_id` END) AS `q6`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-08-14 00:00:00' AND '2019-08-14 23:59:59' THEN A1.`ticket_id` END) AS `q9`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A2.`state` = 'open' AND A1.`isanswered` = '1' THEN A1.`ticket_id` END) AS `q3`, COUNT(DISTINCT CASE WHEN (A1.`team_id` IN (1) OR A1.`staff_id` IN (6)) AND A2.`state` = 'open' AND (A1.`team_id` IN (1) OR A1.`staff_id` IN (6)) AND A2.`state` = 'open' AND NOT A1.`staff_id` IN (6) THEN A1.`ticket_id` END) AS `q7`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-08-13 00:00:00' AND '2019-08-13 23:59:59' THEN A1.`ticket_id` END) AS `q10`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A2.`state` = 'open' AND A1.`isoverdue` = '1' THEN A1.`ticket_id` END) AS `q4`, COUNT(DISTINCT CASE WHEN (A1.`team_id` IN (1) OR A1.`staff_id` IN (6)) AND A2.`state` = 'open' THEN A1.`ticket_id` END) AS `q5`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-08-12 00:00:00' AND '2019-08-18 23:59:59' THEN A1.`ticket_id` END) AS `q11`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' THEN A1.`ticket_id` END) AS `q8`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-08-01 00:00:00' AND '2019-08-31 23:59:59' THEN A1.`ticket_id` END) AS `q12`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-07-01 00:00:00' AND '2019-09-30 23:59:59' THEN A1.`ticket_id` END) AS `q13`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-01-01 00:00:00' AND '2019-12-31 23:59:59' THEN A1.`ticket_id` END) AS `q14` FROM `really_ticket` A1 JOIN `really_ticket_status` A2 ON (A1.`status_id` = A2.`id`) LEFT JOIN `really_thread` A3 ON (A3.`object_type` = 'T' AND A1.`ticket_id` = A3.`object_id`) LEFT JOIN `really_thread_referral` A4 ON (A3.`id` = A4.`thread_id`) LEFT JOIN `really_staff` A5 ON (A4.`object_type` = 'S' AND A4.`object_id` = A5.`staff_id`) LEFT JOIN `really_team` A6 ON (A4.`object_type` = 'E' AND A4.`object_id` = A6.`team_id`) LEFT JOIN `really_department` A7 ON (A4.`object_type` = 'D' AND A4.`object_id` = A7.`id`) WHERE (A2.`state` = 'open' AND (A1.`staff_id` = 6 OR A5.`staff_id` = 6 OR A1.`team_id` IN (1) OR A6.`team_id` IN (1))) OR (A2.`state` IN ('open', 'closed') AND (A1.`dept_id` IN (1, 2, 3, 4) OR A7.`id` IN (1, 2, 3, 4)))]

Unknown column 'Z1.ticket_id' in 'field list'<br />
<br />
---- Backtrace ----<br />
#0 (raiz)/include/mysqli.php(199): osTicket->logDBError('DB Error #1054', '[SELECT COUNT(D...')<br />
#1 (raiz)/include/class.orm.php(3455): db_query('SELECT COUNT(DI...', true, true)<br />
#2 (raiz)/include/class.orm.php(3502): MySqlExecutor->execute()<br />
#3 (raiz)/include/class.orm.php(2085): MySqlExecutor->getArray()<br />
#4 (raiz)/include/class.orm.php(2035): HashArrayIterator->{closure}()<br />
#5 (raiz)/include/class.orm.php(2014): CallbackSimpleIterator->next()<br />
#6 (raiz)/include/class.orm.php(2023): CallbackSimpleIterator->rewind()<br />
#7 (raiz)/include/class.orm.php(1695): CallbackSimpleIterator->valid()<br />
#8 (raiz)/include/class.orm.php(1705): CachedResultSet->fillTo(9223372036854775807)<br />
#9 (raiz)/include/class.orm.php(1328): CachedResultSet->asArray()<br />
#10 (raiz)/include/class.orm.php(1351): QuerySet->all()<br />
#11 (raiz)/include/class.search.php(925): QuerySet->one()<br />
#12 (raiz)/scp/autocron.php(51): SavedQueue::counts(Object(StaffSession), false)<br />
#13 {main}

Could anyone help?

**Comment by JediKev** [comment]
@ikolubr 

Delete Queue with ID of `15`.

Cheers.

**Comment by ikolubr** [comment]
Thank you. But do you have any idea how that line ended up there?

**Comment by JediKev** [comment]
@ikolubr 

If you upgraded from a previous version then it's due to old saved searches that didn't convert to the new queue system properly. It happens.

Cheers.

**Comment by ikolubr** [comment]
Right on it!
Also, if you don’t mind and if you know... after I upgraded, the from column in the ticket lists doesn’t populate.. any ideas why!?

And also, but not mega important, after the update, when inside a ticket, of I click on the number of tickets a specific user has it doesn’t take me to the ticket list of that user, like it was before. Instead, it take me to the all ticket list. Annoying.

Thank you,

**Comment by JediKev** [comment]
@ikolubr 

I would like to direct you to our [Community Supported Forum](https://forum.osticket.com) where these questions have most likely been asked/answered already. If you see that no one has asked a specific question you have in your mind you may create a free account and post your question(s). 👍 

Cheers.

**Comment by ikolubr** [comment]
I already did... no answers for the last couple days, that’s why I asked you. ;)

But thank you so much,

**Comment by JediKev** [comment]
@ikolubr 

Blank From Column:
- https://forum.osticket.com/d/94009-blank-from-column-in-search-results/38

User Ticket Count Shows All Tickets:
- When you hover over the ticket count you're supposed to see a URL in the corner that looks something like the below image.
![Screen Shot 2019-08-14 at 14 25 56 (2)](https://user-images.githubusercontent.com/11823401/63050671-40578380-bea1-11e9-9117-26248a977db2.png)

Once the URL is visited you should be shown an Advanced Search with the appropriate results. I tested this on my installation and it works just fine.

If you are still having issues create a post on the Forum so we and the community can help you debug it.

Cheers.

**Comment by ikolubr** [comment]
Duuuuuuuuuuuuuuuuuuuude! Thank u so much! The flag thing fixed both issues!

God bless,
