### ISSUE TITLE
Feature Request: Standard Ticket Filters for High and Low Prio

### ISSUE THREAD

**Issue by jochenwezel** [osTicket/osTicket#499]
There could be 2 standard ticket filters when osTicket has been installed from scratch:
1. Incoming E-Mails with High-Prio mark in mail heders could be marked with ("High Prio" or) "Emergency priority"
2. Incoming E-Mails with Low-Prio in mail headers mark could be marked with "Low priority"

**Comment by greezybacon** [comment]
@jochenwezel I believe you are correct. The value in the filter *equal* box should be the osTicket priority name.

**Comment by jochenwezel** [comment]
I think both make sense: filtering for osticket priority as well as mail headers's priority field
