### ISSUE TITLE
Accessing form variables

### ISSUE THREAD

**Issue by phillf** [osTicket/osTicket#4998]
### Prerequisites

* [N] Can you reproduce the problem in a fresh installation of the "develop" branch? No
* [N] Do you have any errors in the PHP error log, or javascript console?
* [Y] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [Y] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

Unsure if related: Warning: Use of undefined constant EmailTemplateGroup - assumed 'EmailTemplateGroup' (this will throw an Error in a future version of PHP) in /home/winterhill/servicedesk.whscorp.org/include/staff/tpl.inc.php on line 4

### Steps to Reproduce

1. Create a form similar to this: https://i.imgur.com/d4nQN9B.png
2. Create a help topic and call it "Change Request".
3. Clone the default template set and name the clone "Change Request".
4. Create a department (name doesn't matter) and set it's template set to "Change Request".

**Expected behavior:** 

When email is sent from the "User Support & Services" department using the "Change Request" template set it would use this template. 

Expected Email: https://i.imgur.com/scYCkIE.png
(I set the above as every single template body in the "Change Request" set and still no change)

**Actual behavior:**
Resulting email is based on default templates.

Some Variable not valid context: https://i.imgur.com/yKBvgzh.png
Form Section: https://i.imgur.com/d4nQN9B.png
Resulting Email: https://i.imgur.com/KiAAe7v.png

### Versions

Server Information
--
osTicket Version | v1.12 (a076918) —  Up to date
Web Server Software | Apache
MySQL Version | 10.3.17
PHP Version | 7.2.21
CentOS 7 / cPanel 

Windows 10 for Workstations, x64
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36

### Question

I probably misunderstood but I thought it was possible to access the data in the form fields by doing %{ticket.variable}. Does this not apply to email templates? Have I royally screwed up the configuration?

**Comment by JediKev** [comment]
@phillf 

**Note:**
Please upgrade to `v1.12.2` ASAP as there were some security vulnerabilities in `v1.12` and `v1.12.1`.

>Unsure if related: Warning: Use of undefined constant EmailTemplateGroup - assumed 'EmailTemplateGroup' (this will throw an Error in a future version of PHP) in /home/winterhill/servicedesk.whscorp.org/include/staff/tpl.inc.php on line 4

This is just a warning that can be ignored. If this has not been fixed already in v1.12.2 then you are welcome to make a pull request or wait until a fix is released in upcoming versions.

>Some Variable not valid context: https://i.imgur.com/yKBvgzh.png

Any Custom Form field variables will be seen as "Invalid" but they are fine, just ignore.

>Resulting Email: https://i.imgur.com/KiAAe7v.png

Did you add a custom Template Set? If so you have to set the Department(s) to use this Template Set instead of the default set.

>I probably misunderstood but I thought it was possible to access the data in the form fields by doing %{ticket.variable}. Does this not apply to email templates?

Yes, doing `%{ticket.variable}` will give you the data for that field in the Ticket (if the ticket has data for it).

Cheers.
