### ISSUE TITLE
Datepicker am/pm error for 24h time format

### ISSUE THREAD

**Issue by antiuser** [osTicket/osTicket#5004]
### Prerequisites
* [x] Can you reproduce the problem in a fresh installation of the "develop" branch?
No
* [x] Do you have any errors in the PHP error log, or javascript console?
No
* [x] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
Yes, and we are confirm this issue
https://forum.osticket.com/d/94560-osticket-1-12-2-date-time-picker/9
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?
Yes, but not found this
For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description
Datepicker show me 12h time format, even in my settings im using 24h time format.

### Steps to Reproduce
Create new ticket, call datepicker on custom field (maybe on a stanard field this issue seen, for example - Due Date field), and see that i have only 0..12 hours, instead of 0..23 hours, in settings i have 24h format.

**Expected behavior:** [What you expected to happen]
When call datepicker i want to see hours range from 00 to 23 (when i have 24h format in settings). 

**Actual behavior:** [What actually happened]
Im assume, this is upgraded datepicker plugin, because this feature was rebase in 0.12.2 version, but 24h format in datepicker was correct in 0.12 version

### Versions
0.12.2

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.
Debian 9 x64, Google Chrome 76.0.3809.100

**Comment by protich** [comment]
This is indeed due to the new date time picker. I'll look into addressing it in the next version.

**Comment by antiuser** [comment]
Thank you much!

**Comment by protich** [comment]
This issue is addressed in PR #5076 - thanks for raising it.
