### ISSUE TITLE
Wrong Queue for Today/Yesterday

### ISSUE THREAD

**Issue by philbertphotos** [osTicket/osTicket#5016]
The default queues seem to be off since tickets opened today is showing up in yesterdays Queue. 

OSticket recently updated to 1.12.2.
osTicket Version | v1.12.2 (a5d898b)     —  Up to date
Web Server Software | Apache/2.4.18 (Ubuntu)
MySQL Version | 5.7.26
PHP Version | 7.2.2

![image](https://user-images.githubusercontent.com/2892474/64057786-5aff4d00-cb6f-11e9-9df9-de85106fc8db.png)

**Comment by ntozier** [comment]
You're not looking at tickets opened today or yesterday.
You are looking at ticket CLOSED yesterday or today.
So I do not follow you...

**Comment by philbertphotos** [comment]
@ntozier the closed tickets in question were 8/30/2019 closed that day but shows up in the Yesterday Queue sorry for the confusion it does the same inour Open Queue after a few hours it moves to yesterdays queue even if its the middle of the afternoon

**Comment by protich** [comment]
Question - What time zone do you have set on your profile? Asking because it does affect the day cutoff times.

**Comment by philbertphotos** [comment]
@protich From what I can tell the times on tickets just created are pretty accurate.
![image](https://user-images.githubusercontent.com/2892474/64305177-76e26480-cf5c-11e9-81ae-c134aec0a2fa.png)

**Comment by protich** [comment]
I'll look into it and get back to you - thanks.

**Comment by protich** [comment]
Bro! I'll someday admit date time is confusing and hard! 

Try the patch below (if it applies) and let me know if it addresses the issue. I'll make an official PR tomorrow. 

```diff 

diff --git a/include/class.forms.php b/include/class.forms.php
index 2bfa740..93f691c 100644
--- a/include/class.forms.php
+++ b/include/class.forms.php
@@ -2452,18 +2452,14 @@ class DatetimeField extends FormField {
                 "{$name}__gte" => $now->plus($interval),
             ));
         case 'period':
-            // Get the period range boundaries - timezone doesn't matter
-            $period = Misc::date_range($value, Misc::gmtime('now'));
+            // User's effective timezone
             $tz = new DateTimeZone($cfg->getTimezone());
-            // Get datetime boundaries in user's effective timezone
-            $tz = new DateTimeZone($cfg->getTimezone());
-            $start = new DateTime($period->start->format('Y-m-d H:i:s'),
-                    $tz);
-            $end = new DateTime($period->end->format('Y-m-d H:i:s'), $tz);
+            // Get the period range boundaries in user's tz
+            $period = Misc::date_range($value, Misc::gmtime('now'), $tz);
             // Convert boundaries to db time
             $dbtz = new DateTimeZone($cfg->getDbTimezone());
-            $start->setTimezone($dbtz);
-            $end->setTimezone($dbtz);
+            $start = $period->start->setTimezone($dbtz);
+            $end = $period->end->setTimezone($dbtz);
             // Set the range
             return new Q(array(
                 "{$name}__range" => array(
diff --git a/include/class.misc.php b/include/class.misc.php
index aa75bc5..0569237 100644
--- a/include/class.misc.php
+++ b/include/class.misc.php
@@ -147,12 +147,13 @@ class Misc {
     }
 
     // Date range for the period in a given time
-    function date_range($period, $time=false) {
+    function date_range($period, $time=false, $tz=null) {
         $time = $time ?: self::gmtime();
         if (!($dt = Format::parseDateTime($time)))
             return null;
-        // Force UTC
-        $dt->setTimezone(new DateTimeZone('UTC'));
+        // Force UTC if timezone is not provided
+        $tz = $tz ?: new DateTimeZone('UTC');
+        $dt->setTimezone($tz);
 
         // Make dt Immutable.
         $dt = DateTimeImmutable::createFromMutable($dt);

```

**Comment by philbertphotos** [comment]
Will update this and let you know...

**Comment by philbertphotos** [comment]
@protich ok verified the patch works!
Thanks.
You can close it after do what ever clean up needed for next release.

**Comment by philbertphotos** [comment]
@protich spoke too soon it work for more hours this time .. its now 8:30pmand now they moved to Yesterday. I assuming Yesterday is after midnight.

![image](https://user-images.githubusercontent.com/2892474/64392528-2ed64700-d01b-11e9-850b-485079479390.png)

**Comment by protich** [comment]
Can you post the config for the queue?  Looks like it’s not one of the standard core queues we ship.

**Comment by philbertphotos** [comment]
I have added some stuff but its all standard... This was happening before and added the other custom stuff.
Today and Yesterday were never changed.
![image](https://user-images.githubusercontent.com/2892474/64456420-27b44500-d0be-11e9-916b-2852bc1c29f6.png)
![image](https://user-images.githubusercontent.com/2892474/64456447-369af780-d0be-11e9-80fe-0345d437f060.png)
![image](https://user-images.githubusercontent.com/2892474/64456469-47e40400-d0be-11e9-89cc-d95b04ea204c.png)

**Comment by protich** [comment]
Interesting - perhaps you jumped on custom queues before we finalized them. I was specifically asking for the criteria set for Today & Yesterday queues.

I don't recall us shipping with Today and Yesterday as sub-queues for Open. Below is the layout we have as an example - 

<img width="555" alt="Screen Shot 2019-09-06 at 5 59 30 PM" src="https://user-images.githubusercontent.com/31067/64465124-78cd3480-d0d0-11e9-9c5b-31097bbbb493.png">

And here is the configuration for Today queue. 

<img width="788" alt="Screen Shot 2019-09-06 at 6 01 33 PM" src="https://user-images.githubusercontent.com/31067/64465123-78349e00-d0d0-11e9-85c4-5c8935b923f1.png">

**Comment by philbertphotos** [comment]
..I copied the same values that I saw in Closed. Closed with the default does the same thing,
![image](https://user-images.githubusercontent.com/2892474/64466885-44627400-d0e2-11e9-99e2-43ce03af4646.png)

**Comment by protich** [comment]
Apply the patch below - click on one or more of the queues, multiple times,  when results are off and then post the var_dumps before discarding the patch. Thanks in advance.

```diff
diff --git a/include/class.forms.php b/include/class.forms.php
index 8bc21f2..8b5610f 100644
--- a/include/class.forms.php
+++ b/include/class.forms.php
@@ -2453,10 +2453,12 @@ class DatetimeField extends FormField {
             $tz = new DateTimeZone($cfg->getTimezone());
             // Get the period range boundaries in user's tz
             $period = Misc::date_range($value, Misc::gmtime('now'), $tz);
+            var_dump($period);
             // Convert boundaries to db time
             $dbtz = new DateTimeZone($cfg->getDbTimezone());
             $start = $period->start->setTimezone($dbtz);
             $end = $period->end->setTimezone($dbtz);
+            var_dump($start, $end);
             // Set the range
             return new Q(array(
                 "{$name}__range" => array(
```

**Comment by philbertphotos** [comment]
object(stdClass)#2338 (2) { ["start"]=> object(DateTimeImmutable)#2336 (3) { ["date"]=> string(26) "2019-09-07 00:00:00.000000" ["timezone_type"]=> int(3) ["timezone"]=> string(3) "UTC" } ["end"]=> object(DateTimeImmutable)#2337 (3) { ["date"]=> string(26) "2019-09-07 23:59:59.000000" ["timezone_type"]=> int(3) ["timezone"]=> string(3) "UTC" } } object(DateTimeImmutable)#2341 (3) { ["date"]=> string(26) "2019-09-07 19:59:59.000000" ["timezone_type"]=> int(3) ["timezone"]=> string(16) "America/Anguilla" } 

object(stdClass)#2990 (2) { ["start"]=> object(DateTimeImmutable)#2988 (3) { ["date"]=> string(26) "2019-09-07 00:00:00.000000" ["timezone_type"]=> int(3) ["timezone"]=> string(3) "UTC" } ["end"]=> object(DateTimeImmutable)#2989 (3) { ["date"]=> string(26) "2019-09-07 23:59:59.000000" ["timezone_type"]=> int(3) ["timezone"]=> string(3) "UTC" } } object(DateTimeImmutable)#2993 (3) { ["date"]=> string(26) "2019-09-07 19:59:59.000000" ["timezone_type"]=> int(3) ["timezone"]=> string(16) "America/Anguilla" }

**Comment by protich** [comment]
Based on above it looks like the system still thinks your timezone is UTC - I suspect you didn't apply the initial patch correctly on both files.

**Comment by philbertphotos** [comment]
Actually I did apply the patches it did help but not completely

**Comment by protich** [comment]
Assuming you did apply the patches correctly - what timezone do you have in Profile > Preference?

Also post results of below var_dump.

```diff 

diff --git a/include/class.forms.php b/include/class.forms.php
index 8bc21f2..bc19d82 100644
--- a/include/class.forms.php
+++ b/include/class.forms.php
@@ -2453,6 +2453,7 @@ class DatetimeField extends FormField {
             $tz = new DateTimeZone($cfg->getTimezone());
             // Get the period range boundaries in user's tz
             $period = Misc::date_range($value, Misc::gmtime('now'), $tz);
+            var_dump($period, $tz);
             // Convert boundaries to db time
             $dbtz = new DateTimeZone($cfg->getDbTimezone());
             $start = $period->start->setTimezone($dbtz);
```

**Comment by philbertphotos** [comment]
![image](https://user-images.githubusercontent.com/2892474/64498734-e79ebf00-d283-11e9-939c-394f490a99d6.png)

**Comment by philbertphotos** [comment]
object(stdClass)#2456 (2) { ["start"]=> object(DateTimeImmutable)#2454 (3) { ["date"]=> string(26) "2019-09-09 00:00:00.000000" ["timezone_type"]=> int(3) ["timezone"]=> string(3) "UTC" } ["end"]=> object(DateTimeImmutable)#2455 (3) { ["date"]=> string(26) "2019-09-09 23:59:59.000000" ["timezone_type"]=> int(3) ["timezone"]=> string(3) "UTC" } } NULL

**Comment by ntozier** [comment]
As a side note:
Your screen shot is Admin panel ->Settings  -> System.
He (Peter) asked for Profile -> Preferences.

**Comment by philbertphotos** [comment]
![image](https://user-images.githubusercontent.com/2892474/64499291-7280b900-d286-11e9-925e-3af05a5d3c49.png)

**Comment by protich** [comment]
@philbertphotos - thanks for the info, that helped.  One last debug.
```diff

diff --git a/include/class.forms.php b/include/class.forms.php
index 8bc21f2..d350570 100644
--- a/include/class.forms.php
+++ b/include/class.forms.php
@@ -2451,6 +2451,7 @@ class DatetimeField extends FormField {
         case 'period':
             // User's effective timezone
             $tz = new DateTimeZone($cfg->getTimezone());
+            var_dump($cfg->getTimezone());
             // Get the period range boundaries in user's tz
             $period = Misc::date_range($value, Misc::gmtime('now'), $tz);
             // Convert boundaries to db time
```

**Comment by philbertphotos** [comment]
string(21) "America/Santo_Domingo"

**Comment by philbertphotos** [comment]
I started from scratch and redid patches. (just incase)

**Comment by protich** [comment]
I replicated your settings and mine is working as expected. See var_dump of period below.

`
object(stdClass)#824 (2) { ["start"]=> object(DateTimeImmutable)#822 (3) { ["date"]=> string(26) "2019-09-10 00:00:00.000000" ["timezone_type"]=> int(3) ["timezone"]=> string(21) "America/Santo_Domingo" } ["end"]=> object(DateTimeImmutable)#821 (3) { ["date"]=> string(26) "2019-09-10 23:59:59.000000" ["timezone_type"]=> int(3) ["timezone"]=> string(21) "America/Santo_Domingo" } 
`

I was thinking you perhaps need to update `timezonedb` but you can already select the timezone in question. It's impossible for me to debug further without access to your system. 

That said, the initial report helped us fix a bug - so thank you!

**Comment by philbertphotos** [comment]
I will know by tonight ... I redid the patch from scratch just to be sure.

**Comment by philbertphotos** [comment]
no ... Thank you for taking the time to look at this its been quite helpful 👍

**Comment by philbertphotos** [comment]
@protich  ok confirmed fixed. waited till 11:59 and it was correct and as soon as 12am hit it updated as it should. Thanks for the fix.!

**Comment by protich** [comment]
@philbertphotos - Thank you!! I thought I was going crazy not seeing the issue!

Cheers,
