### ISSUE TITLE
Develop-Next database upgrade failure

### ISSUE THREAD

**Issue by TechCare-Aus** [osTicket/osTicket#5028]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [X] Do you have any errors in the PHP error log, or javascript console?
* [ ] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [X] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

Latest fetch using origin/develop-next requires database upgrade, but it fails.

### Steps to Reproduce

1. git fetch
2. git merge origin/develop-next
3. php manage.php deploy /home/USERNAME/public_html/help/ -v
4. access https://help.domain.com/scp
5. log in
6. run upgrade
7. fails with error

> [core]: Upgrader Error
> [ALTER TABLE `os_ticket` ADD `sort` int(11) unsigned NOT NULL DEFAULT '0' AFTER `flags`] Unknown column 'flags' in 'os_ticket'

This is what shows up in logs just before the error:

> Upgrader - 8b923d61 (task pending).
> The ScheduleCreator task reports there is work to do
> 
> Upgrader - 8b923d61 applied
> Patch 00c949a6-8b923d61 applied successfully (v1.14.0)

**Expected behavior:** 
Successfully upgrade database

**Actual behavior:**
Fatal error, unable to access osTicket

### Versions

v12.2 
PHP v7.1
CentOS

**Comment by protich** [comment]
Not sure why your ticket table is missing flags field - it's been a standard field for a while now.

**Comment by TechCare-Aus** [comment]
Hmmm. Any ideas on how to fix?

I'm happy to start a completely new osTicket running v1.14 but would need to know how to import data from the existing database.

**Comment by TechCare-Aus** [comment]
Looks like the database between my running one and the new is very different.
Just spun up a new osTicket v1.12 - maybe a failed database upgrade from way back then? I think I've got data going back to 2013.
![osTicket_db_issues](https://user-images.githubusercontent.com/2740134/64467384-96d77b00-d14a-11e9-94c4-e7c34ea5ed4b.PNG)

**Comment by TechCare-Aus** [comment]
Fixed my issue.
Ran this SQL command:
`ALTER TABLE `os_ticket` ADD `flags` INT(10) UNSIGNED NOT NULL DEFAULT 'NOT NULL' AFTER `lock_id`;`
Now it upgraded fine. Appears that there was flags in other sections of the database but not the os_ticket one.

Now to find out where you can use that merge ticket function :-/

**Comment by protich** [comment]
We figured out it was our fault - new recent installs have flags field but old ones don't. We will address it in one of the patches. Thanks again!
