### ISSUE TITLE
Hi Jedikev,

### ISSUE THREAD

**Issue by greenlanegreb** [osTicket/osTicket#5029]
Hi Jedikev, 

Thank you for this! What you instructed me to do is what I have been doing but, when I log in, it's still got the old version in the admin section so I guess it's not updating! Sorry about posting here and thank you again!

_Originally posted by @greenlanegreb in https://github.com/osTicket/osTicket/issues/4921#issuecomment-502197943_

**Comment by JediKev** [comment]
@greenlanegreb 

This is not an issue report nor a feature request so I'm going to close this. Please re-post on the [Forum](https://forum.osticket.com).

With this being said I will go ahead and answer you here:
If you copy over the new files on top of the old files and you still see the old version then something is not right with how you're doing it. Maybe you aren't actually replacing the files? We will get more info on the Forum.

Cheers.
