### ISSUE TITLE
Adding collaborators purges response field

### ISSUE THREAD

**Issue by FG-Lars** [osTicket/osTicket#5041]
I know I should be doing this the other way around, but sometimes you forget... And I'm surely not the only one.

**So here is the scenario:**
1) I write my long fancy reply text
2) Before hitting post reply, I realize other people should be involved and see my reply as well
3) I add one or more collaborators
4) The response field is now reset/purged (fancy reply text gone)
5) Some faul language is spoken, mumbled or even shouted
6) Start from the beginning and write my fancy reply again

I know, copy the text before adding collaborators. But in the heat of the day, you migth just make this mistake as well.

So I purpose a change! Could you please preserve the text when adding collaborators?

**Comment by aydreeihn** [comment]
This is actually already addressed in this pull request: #4955
