### ISSUE TITLE
[Feature Request] Expanded logic options for queues

### ISSUE THREAD

**Issue by phillf** [osTicket/osTicket#5070]
Quite simply put, expanded logic capabilities for ticket queues. As of the current version at the time of this request (1.12.2) queues only use _AND_. Having the ability to combine AND, OR, ANDOR, etc... would be appreciated.

The current approach makes it challenging to build queues where the parent has Help Topics and Departments included but each child queue needs to be able to filter based on certain custom fields but _AND_ makes this impossible. _OR_ would allow for more flexible filtering.

**Comment by JediKev** [comment]
@phillf

Thank you for your feedback. This is a feature that has been suggested quite a bit now. You’ll be happy to know that this is on our roadmap for future development.

Cheers.

**Comment by phillf** [comment]
@JediKev, thank you! Can't wait. Having multi-tiered queue with one logic operator is a nightmare.
