### ISSUE TITLE
Issue DashBoard Statistic

### ISSUE THREAD

**Issue by johnkalangha** [osTicket/osTicket#5071]
osticket version 1.10.4
environment: production
mysql 5.6
php 5.6

I have 2 department, IT department and HR department

for IT department we already have 10 help topic, each topic routing will be the it department
for HR department we already have 3 help topics, 

Issue: When i tried to Open the account of HR in agent , in dashboard i can see all the helptopics including for IT department, which is supposed to be, he/she cant view, only there topic.

PS: im a also planning to upgrade to 1.14 after i will release and maybe next year, because i have so many modification, but please help me with this because is this urgent thank  you

**Comment by johnkalangha** [comment]
how to integrated this in osticket v1.10.7 there is an error if i used copy and paste

![image](https://user-images.githubusercontent.com/30627667/65813868-3a2d2480-e20d-11e9-8d30-37c6b836c58a.png)

**Comment by johnkalangha** [comment]
the picture is from osticket 1.14

**Comment by JediKev** [comment]
@johnkalangha

You cannot just copy a diff from a new version and apply it to an older codebase. There are many reasons why you probably couldn’t apply the changes, either the line numbers are different, the codebase changed so the lines you are looking for are non-existing, etc. You can try to work out the diff yourself to see if you can backport the changes but you will more than likely have to upgrade to address this issue.

Cheers.
