### ISSUE TITLE
Unexpected THIS_VERSION value

### ISSUE THREAD

**Issue by stevland** [osTicket/osTicket#5084]
bootstrap.php, Line 340

Expected:
define('THIS_VERSION', '1.12.3'); // Set by installer

Actual:
define('THIS_VERSION', '1.12-git'); // Set by installer

---

Admin Panel > Settings > System 

Expected:
System Settings and Preferences — osTicket (1.12.3)

Actual:
System Settings and Preferences — osTicket (1.12-git)

---

Intentional?

**Comment by JediKev** [comment]
We are looking into it.

**Comment by JediKev** [comment]
@stevland 

Issue addressed on the packaging side with:
- https://github.com/osTicket/osTicket/pull/5085

However you will have to wait for the ZIPs to be updated on the website.

Cheers.

**Comment by PeopleInside** [comment]
Why the issue is closed if the fix on the website where we can download the packange is still be affected? When the issue will be fixed in the website?

**Comment by JediKev** [comment]
@PeopleInside

We are currently re-uploading them. 

Cheers.

**Comment by PeopleInside** [comment]
Hi @JediKev , when the upload is finish i will download it if you alert me so i can fix the issue created from the update. Many thanks. Hope this will not happen again in future update.
Thanks :)

**Comment by JediKev** [comment]
@PeopleInside 

> Hope this will not happen again in future update.

It will not happen again, that's what the pull request mentioned above addresses.

Cheers.

**Comment by JediKev** [comment]
@PeopleInside @stevland 

Files on website will not be updated until a bit later. In the meantime you can download them here:
- https://github.com/osTicket/osTicket/releases/tag/v1.12.3
- https://github.com/osTicket/osTicket/releases/tag/v1.14-rc2

Cheers.

**Comment by stevland** [comment]
Thanks once again for all of your work and your **_incredibly fast_** response times, @JediKev

**Comment by joeldeteves** [comment]
Hello @JediKev we are still getting the wrong version. We use a custom Docker image that pulls latest like this:

    `git clone -b v${OSTICKET_VERSION} --depth 1 https://github.com/osTicket/osTicket.git \`

Where ${OSTICKET_VERSION} is specified as 1.12.3, etc.

We haven't had this issue with past upgrades.

Per @ntozier's comment in https://forum.osticket.com/d/95656-new-version-1-12-3-install-issue-version-github-from-the-osticket-website/5 it's not feasible for us to download the latest from the website (cause it uses a randomized AWS link).

I tested the command manually and it does appear to pull down 1.12.3 (looking at the WHATSNEW file)

Thank you,

**Comment by JediKev** [comment]
@joeldeteves 

Are you pulling latest `develop` or are you using the `v1.12.3` version tag? You will need this I believe:
- https://github.com/osTicket/osTicket/pull/5085


Also, if you download and use straight from github it will show as `1.x-git`, always. However, if you _deploy_ the code from the git repo to your html directory you will have the full version. This is best practice anyways so that you can mess with git without affecting production. So, basically you will need to clone from Github to a directory, then run `$ php /path/to/clone/manage.php deploy -v /path/to/html/dir/`, and then you should have the full version number.

Cheers.

**Comment by joeldeteves** [comment]
Thanks Kev, yes we are using the deploy command in our Dockerfile.

I will give that other tag a try.

EDIT: I cloned from the develop branch and checked out the merge request and that solved the issue:

```
   git clone https://github.com/osTicket/osTicket.git \
   && cd osTicket \
   && git checkout 759cdbdaab3bf0945d50c99d1ae271c15cab9cfd \
   && php manage.php deploy -sv /data/upload
```

Thank you,
