### ISSUE TITLE
Upgrade page show good resource in red with a red X. Why?

### ISSUE THREAD

**Issue by PeopleInside** [osTicket/osTicket#5086]
Upgraded to the last version but upgrade.php show good resource in red with X graphic near.
Why? Is this a bug?

![SharedScreenshot](https://user-images.githubusercontent.com/5006150/66083690-21a26e80-e56d-11e9-925f-c64504f7ce1d.jpg)

**Comment by JediKev** [comment]
@PeopleInside 

Not sure, doesn't happen to me:
<img width="698" alt="Screen Shot 2019-10-02 at 16 40 16" src="https://user-images.githubusercontent.com/11823401/66084073-627d9180-e533-11e9-99be-355cb1c61cc5.png">

Are you having caching issues or something? Can you restart the server and try another browser?

Cheers.

**Comment by PeopleInside** [comment]
Hi @JediKev , thanks for the response.
I restarted Apache and PHP used the incognito mode in a different Firefox version.
Same issue.
Let try in Edge browser: same

![SharedScreenshot](https://user-images.githubusercontent.com/5006150/66084577-45ff4a80-e56f-11e9-8b1f-2f2d9be345e2.jpg)

**Comment by JediKev** [comment]
@PeopleInside 

I'm not seeing the same results at all...even when using PHP 7.2..

Do you actually need to upgrade? Can you go to Admin Panel or Agent Panel and click around without being kicked back to the Upgrader?

Cheers.

**Comment by PeopleInside** [comment]
I am able to use OsTicket. I forced the address scp/upgrade.php manually and found this issue. Is strange because version in the panel is correct and I replaced all file. I can simply ignore this just want to report this.. I have no idea why I see this

**Comment by JediKev** [comment]
@PeopleInside

Ahh that’s why. You are all the way up to date so the upgrader will be like that. You only visit the upgrader if you actually need an upgrade otherwise it will appear like that. If you run the same codebase on an install that actually needs the upgrade you’ll see it works fine.

Cheers.
