### ISSUE TITLE
[BUG] 24h format not correct in 1.12.3

### ISSUE THREAD

**Issue by antiuser** [osTicket/osTicket#5088]
Hi there! I saw that you are working on enhancement for 24h format in datepicker.

After upgrading to 1.12.3 i see incorrect hour and minute row
![Выделение_040](https://user-images.githubusercontent.com/5499424/66198140-338f2900-e6b5-11e9-8942-abba3548d0a5.png)
![Выделение_042](https://user-images.githubusercontent.com/5499424/66198304-8bc62b00-e6b5-11e9-8360-70e2cff97587.png)
![Выделение_045](https://user-images.githubusercontent.com/5499424/66198425-d6e03e00-e6b5-11e9-9dfc-57d91fb28ee6.png)

Elements are very strange :) 

Also, im testing this bug on fresh installation of 1.12.3 version, same issue

**Comment by protich** [comment]
What's your date / time format set to? Post a screenshot of Admin Panel > Settings > System > Dates section.

**Comment by antiuser** [comment]
So, same issue on 1.14rc2
![Снимок экрана_2019-10-04_21-47-43](https://user-images.githubusercontent.com/5499424/66224963-b41f4b00-e6f0-11e9-9bd1-62581309e4b1.png)

**Comment by antiuser** [comment]
also, im testing these on German language

**Comment by protich** [comment]
Thanks for the info - please apply the patch below and let me know if it solves the issue.
```diff

diff --git a/include/class.format.php b/include/class.format.php
index b7872a8..4bf497b 100644
--- a/include/class.format.php
+++ b/include/class.format.php
@@ -817,6 +817,7 @@ class Format {
         'Y' => 'y',
         // Time
         'a' => 'tt',
+        'HH' => 'H',
         'H' => 'HH',
         );
 
```

**Comment by antiuser** [comment]
Splendid, this fix issue.
But i found another issue with different time on tickets queue and inside tickets, i will create a new issue on github later.
Thank you, Peter!
