### ISSUE TITLE
After Upgrade to 1.12.3, Datetime bug Duedate

### ISSUE THREAD

**Issue by helloost** [osTicket/osTicket#5091]
Hello,
i updated my osticket from 1.12.2 to 1.12.3.

Now i have found a Datetime bug at the duedate

Where can ich change this?
![grafik](https://user-images.githubusercontent.com/56261202/66316278-b1eb0580-e917-11e9-8308-8311ad1db61c.png)
![grafik](https://user-images.githubusercontent.com/56261202/66316300-b9aaaa00-e917-11e9-833f-dbfcca74ac49.png)

My settings are:
![grafik](https://user-images.githubusercontent.com/56261202/66316321-c4fdd580-e917-11e9-9f71-4e5fd3fb676e.png)

Thanks
Regards Helloost

**Comment by protich** [comment]
PR #5092  addresses this issue

**Comment by helloost** [comment]
Okay, thank you
