### ISSUE TITLE
Call to undefined function openssl_pkey_get_public() when installing a Language Pack

### ISSUE THREAD

**Issue by bes-19** [osTicket/osTicket#5095]
### Prerequisites

* [Y] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [Y] Do you have any errors in the _PHP error log_ (IIS Failed Request Logging!)?
[W3SVC1.zip](https://github.com/osTicket/osTicket/files/3707959/W3SVC1.zip)
Did not upload a Video because of the FileSize...
Files can be opened with Internet Explorer 11 (Doubleclick the xml Files)
* [Y] Did you check the osTicket forums?
* [Y] Did you perform a cursory search to see if your bug or enhancement is already reported?

### Description

Installing a Language pack (tested it with 10 different Language Packs from osticket.com/download) causes to crash the system.php Site.

### Steps to Reproduce

1. Put a Language Pack of your Choice in the include/i18n folder
2. Open _localhost_/scp/system.php

**Expected behavior:** [What you expected to happen]
Showing the Site correctly

**Actual behavior:** [What actually happened]
Showing a HTTP 500 Error with attached PHP Error

### Versions

osTicket: 1.12-git (develop branch downloaded on 09.10.2019 16:40 UTC+2)
Webserver: IIS 10.0
mySQL: 8.0.17
PHP: 7.3.8
Firefox Browser 69.0

**Comment by JediKev** [comment]
@bes-19 

>Call to undefined function openssl_pkey_get_public()

This means you do not have the OpenSSL library installed on your server. More information on this here:
- https://www.openssl.org/

With this being said we will add a check for OpenSSL Library and if it's not available we just won't run the corresponding methods. 👍

Cheers.

**Comment by JediKev** [comment]
@bes-19 

Here you go:
- https://github.com/osTicket/osTicket/pull/5096

Cheers.

**Comment by bes-19** [comment]
Thanks JediKev.

Maybe add the OpenSSL Extension to the PHP Extensions Table:
![OpenSSL](https://user-images.githubusercontent.com/54275066/66546491-6fa30d80-eb3d-11e9-94cb-e73f41a6aa6e.PNG)
(Also in install.php...)

**Comment by JediKev** [comment]
@bes-19 

Well, to be fair, OpenSSL is not a PHP extension. OpenSSL is a Software Library and is not required to use osTicket.

Cheers.

**Comment by bes-19** [comment]
Hm ok... Don't know this much about Programming :)
Thanks for Explanation :)
