### ISSUE TITLE
question or bugs regarding View ticket in client 

### ISSUE THREAD

**Issue by johnkalangha** [osTicket/osTicket#5101]
hi i just want to ask this issue,this is my setup i have 2 department for agent
department
IT - default
Care Dept

organization
care dept

after i create a ticket in client under care dept, the routing of that ticket is under care dept also, but when the view of ticket in client, the IT dept will show which is the default, i change the code to this in view,inc.php

![image](https://user-images.githubusercontent.com/30627667/66626442-d18d7100-ec2a-11e9-8438-e902bb240128.png)
but this is for when i open a ticket, i dont know, how to change in the list of open ticket in client, its still it dept thank you

**Comment by JediKev** [comment]
@johnkalangha 

This is not the place to post customization questions. You will need to post this on the Forum instead.

Cheers.

**Comment by johnkalangha** [comment]
hello sir, this is not a customize code, i just a questionm what should the department name place in client pc, because when i create a ticket always IT dept i see, even the routing is for another dept,

**Comment by JediKev** [comment]
@johnkalangha

Okay, so describe how you have your routing configured. Remember, screenshots are always helpful in visualizing your setup.

Cheers.

**Comment by johnkalangha** [comment]
heres my help topic setting
![image](https://user-images.githubusercontent.com/30627667/66691947-9e9bb980-eccc-11e9-9b52-8f9d6d8d94ca.png)
but when i create a ticket as user/client in my ticket view, its always an IT department 
![image](https://user-images.githubusercontent.com/30627667/66692056-69439b80-eccd-11e9-9bdb-1ea32db7531f.png)
note that i change the design but the php code is the same thank you sir

**Comment by protich** [comment]
It's important to note that a department **must be public to show up in client portal**, otherwise default department (which is public) is used.

**Comment by johnkalangha** [comment]
i see thank you for saving me, i didnt notice that in creating my department, thank you very much

    On Saturday, 12 October 2019, 8:57:00 pm GMT+8, Peter Rotich <notifications@github.com> wrote:  
 
 
It's important to note that a department must be public to show up in client portal, otherwise default department (which is public) is used.
