### ISSUE TITLE
core: Unknown or invalid schema signature

### ISSUE THREAD

**Issue by StaNov** [osTicket/osTicket#511]
I just downloaded latest version (1.8.0.2) and uploaded it to my webhosting.

The installation keeps telling me this:

 **core: Unknown or invalid schema signature (6de40a4d5bad7a2923e769a4db1ff3b9 .. 833a0f36e10d073fb9e7fb3c8db4e8ef)**

![snmek obrazovky pozen 2014-02-01 13 20 24](https://f.cloud.github.com/assets/4697446/2057597/667f6e0e-8b3c-11e3-90b6-b773c08285a2.png)

| Running: | &nbsp; |
| --- | --- |
| PHP | 5.3 |
| MySQL | 5.6.14 |

I have googled solution for osticket 1.7, but it was not suitable for me.

Thanks for help.

**Comment by c0nfused** [comment]
I just had the same issue in osTicket 1.8-git

When I open the `setup/inc/streams/core/install-mysql.sql` file and compare my local copy to the current file at https://github.com/osTicket/osTicket-1.8/blob/develop/setup/inc/streams/core/install-mysql.sql

Mine is 853 lines long, and the one on github is 852 lines. A blank line is being added to the bottom of the file, and that is throwing the md5 hash off.

**Comment by c0nfused** [comment]
@greezybacon May I ask your OS/editor of choice? I would guess Linux or Mac? Also, can you not simply add a new line to the file in the repo with the updated md5 to correct this issue on all platforms?

**Comment by vikas-DabKick** [comment]
I downloaded it as zip and installed as per procedure no problem has occured.. but when I tried to install using a cloned copy I faced this problem

download the code as a zip file and unzip and try to install.

**Comment by ntozier** [comment]
@vikas-DabKick cross posting.  Naughty.
I'm quite sure that you did not download 1.8.0.2 since it has not been available for download at osticket.com/download for around 2 years now.  Please download current from http://osticket.com/download and try again.

**Comment by amitarunabh** [comment]
Just change the second part of signatures in the file-
include\upgrader\streams\core.sig

**Comment by stamminator** [comment]
> Just change the second part of signatures in the file-
> include\upgrader\streams\core.sig

This worked for me. I pasted in the second signature that it was failing to match against. I truly have no clue what I'm doing, but hey, "it worked"! 
¯\\\_(ツ)_/¯

**Comment by andriitukai** [comment]
> > Just change the second part of signatures in the file-
> > include\upgrader\streams\core.sig
> 
> This worked for me. I pasted in the second signature that it was failing to match against. I truly have no clue what I'm doing, but hey, "it worked"!
> ¯\_(ツ)_/¯

that worked, thanks

**Comment by ghost** [comment]
> I downloaded it as zip and installed as per procedure no problem has occured.. but when I tried to install using a cloned copy I faced this problem
> 
> download the code as a zip file and unzip and try to install.

same for me.

**Comment by JediKev** [comment]
@augustineashal 

I assume that when you cloned the repo you did not switch to the appropriate branch. In this case you'd clone it and use the `1.16.x` branch as this contains the latest release v1.16.1.

Cheers.

**Comment by sbocel** [comment]
Why does the signature change?

**Comment by JediKev** [comment]
@sbocel 

The Schema Signature is an MD5 hash of the `setup/inc/streams/core/install-mysql.sql` file. As new database tables and columns are added/modified/removed the aforementioned file changes so that new installs have the new, updated schema (structure). Naturally, when the file changes the MD5 hash changes. So you can think of it as like a serial number for a specific database schema. Now, with this in mind, we use the Schema Signature to check what your schema is and when you go to upgrade we can see what database patches/tasks need to be ran.

Cheers.
