### ISSUE TITLE
"From" column data blank

### ISSUE THREAD

**Issue by kirby15143** [osTicket/osTicket#5110]
Version 1.14-RC.2 The data is missing in the "From" column on the main ticket screen. If you open a ticket the user who created the ticket is listed correctly. It happens in all browsers on both a Mac and a PC.
![Screen Shot 2019-10-16 at 3 56 19 PM](https://user-images.githubusercontent.com/56655742/66958936-561b2d80-f037-11e9-85c1-4373df29abe8.png)

**Comment by JediKev** [comment]
@kirby15143

Please see this forum post for the solution:
- https://forum.osticket.com/d/94009-blank-from-column-in-search-results/38

Please re-open if this does not resolve the issue.

Cheers.
