### ISSUE TITLE
"My Tickets" not displaying

### ISSUE THREAD

**Issue by kirby15143** [osTicket/osTicket#5113]
OS Ticket 1.14rc - All browsers - I have noticed when I click on "My Tickets" that nothing shows up. If I create a manual search it will work but not when I go to the default area.

**Comment by JediKev** [comment]
@kirby15143 

I'm not seeing the same issue. Have you checked the Criteria for that queue?

Cheers.

**Comment by kirby15143** [comment]
It is the default settings.
![Screen Shot 2019-10-17 at 10 39 24 AM](https://user-images.githubusercontent.com/56655742/67019340-7b0cb080-f0ca-11e9-8edc-bc4886276f21.png)

**Comment by JediKev** [comment]
@kirby15143 

Are you actually Assigned to Tickets? If so, are the Assigned Tickets Open?

Cheers.

**Comment by kirby15143** [comment]
Yes...it's not critical because the search can be manually created. I was just giving feedback while testing.

**Comment by JediKev** [comment]
@kirby15143 

If this is an actual issue we need to address it but I cannot replicate your claims to do so. Can you do the search and show me screenshots of the Search Criteria and Search Results?

Also, do you see any errors via Browser Console, Apache logs, PHP logs, MySQL logs, etc. when visiting the My Tickets queue?

Also, click the Edit cogwheel on the queue in the Agent Panel and see if your Account has any custom criteria that's overriding the Global criterial.

Cheers.

**Comment by kirby15143** [comment]
Here is the search criteria on the one the search I created that works. There is no custom criteria on my account.
![Screen Shot 2019-10-17 at 11 14 00 AM](https://user-images.githubusercontent.com/56655742/67022541-65e65080-f0cf-11e9-9598-df1960f37ce4.png)

**Comment by JediKev** [comment]
@kirby15143 

If you notice in your Search Criteria you do not have `Assignee > One of My Teams`...Do you have any Teams? If so, are they Active?

Cheers.

**Comment by kirby15143** [comment]
I don't have any teams so I didn't add it to the search.

**Comment by JediKev** [comment]
@kirby15143 

That's most likely why it's crashing...add an Active Team and see if that addresses the My Tickets queue issue. If so we will create a fix.

Cheers.

**Comment by kirby15143** [comment]
That was it. Thanks!
