### ISSUE TITLE
[Issue/Question] Login

### ISSUE THREAD

**Issue by johnkalangha** [osTicket/osTicket#5122]
Hi, i just want to ask in login wherever it is user or staff login, If my email as space before and after the email, it will have an error access denied, i think it is need to modify like in gmail or yahoo, in the first place username and gmail/yahoo is not allowed to use space in registration, so it is okey not to read the space in login, thanks

**Comment by JediKev** [comment]
@johnkalangha

I will make a pull tomorrow that will trim the rogue spaces.

Cheers.

**Comment by johnkalangha** [comment]
Thank you sir

**Comment by JediKev** [comment]
@johnkalangha 

Here you go:
- https://github.com/osTicket/osTicket/pull/5124

Cheers.
