### ISSUE TITLE
Attachment filters are not filtering extensions, banned attachments are still coming through

### ISSUE THREAD

**Issue by hot-steamer** [osTicket/osTicket#5123]
### Prerequisites

* [NA] Can you reproduce the problem in a fresh installation of the "develop" branch? Issue was reproduced by Kevin and confirmed. See this forum post:
https://forum.osticket.com/d/95746-attachments-are-not-being-filtered-in-v1-12
* [N] Do you have any errors in the PHP error log, or javascript console?
* [Y] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [Y] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

A ticket filter has been setup to reject all but a list of acceptable extensions.  However, I can send in an attachment that should have been blocked and it was allowed through.

### Steps to Reproduce

1. Enable attachments and set a few allowable extensions.
2. I sent a word doc from gmail to the ticket system's email address

**Expected behavior:**
I expected to see the attachment blocked and a note on the ticket stating such.

**Actual behavior:**
Attachment was added to the ticket.

### Versions
osTicket Version | v1.12 (a076918) —  Up to date
Web Server Software | Apache/2.2.15 (CentOS)
MySQL Version | 5.1.66
PHP Version | 5.6.40
Chrome

### Troubleshooting
For testing, I added some logging to the PHP to see where in the code it got with an attachment that should have been blocked. I can see it throw the exception when it processes the extensions, but it still adds it to the ticket.  I did not debug it past this point.

![image](https://user-images.githubusercontent.com/4528005/67499128-c7616e80-f63d-11e9-8974-01e78e7e971d.png)

**Comment by JediKev** [comment]
@hot-steamer 

Here you go:
- https://github.com/osTicket/osTicket/pull/5133

Cheers.

**Comment by visiniaga** [comment]
@JediKev, test with osticket 12.2.3 with php 7.2.x, 
sending attachment with extension ods, is still acceptable, while in filter only accept some file extension
![Screenshot 2019-10-29 at 06 51 20](https://user-images.githubusercontent.com/43309334/67726579-d9198c00-fa18-11e9-9966-6f16a3194f2c.png)

![Screenshot 2019-10-29 at 06 54 06](https://user-images.githubusercontent.com/43309334/67726596-f4849700-fa18-11e9-9480-4e1b92829b1b.png)

**Comment by hot-steamer** [comment]
@JediKev 
Looks great, I made the code change and it is now rejecting the attachment as it should.

@visimitra 
This bug-fix is not available in any releases or even the development branch yet.  You will need to apply these code changes manually or wait till it has been merged into a release.

**Comment by JediKev** [comment]
@hot-steamer 

Be on the look out as that pull will change a little. I will update here once I pushed the final changes.

Cheers.
