### ISSUE TITLE
don't send new ticket autorespond to the user

### ISSUE THREAD

**Issue by segal90** [osTicket/osTicket#513]
Version: 1.8.1 rc1

If set "Auto Response Email:" to "--- Department Email (above) ---" in a department's options page and a user create a ticket then the user don't get the new ticket autoresponder. But if I set the "Auto Response Email:" option to a fix email, everything OK.

In class.ticket.php file line 872: $email=$dept->getAutoRespEmail() can't create the object.

**Comment by greezybacon** [comment]
I think this is fixed in the latest versions of 1.8.x and 1.9.x. Can anyone confirm if the issue still exists?

**Comment by lifeofguenter** [comment]
Autoresponder emails not working on 1.9.12 - sending out emails works - so not a mail server misconfiguration.

**Comment by infectormp** [comment]
@lifeofguenter Autoresponder emails work fine on 1.9.12
