### ISSUE TITLE
Fatal error: Uncaught DoesNotExist in /var/www/html/include/class.orm.php:1353 

### ISSUE THREAD

**Issue by Fayazahmadmohmand** [osTicket/osTicket#5130]
Dear Support,
after delete the orgnization the web page showing given below error who i can fix?

Fatal error: Uncaught DoesNotExist in /var/www/html/include/class.orm.php:1353 Stack trace: #0 /var/www/html/include/class.orm.php(721): QuerySet->one() #1 /var/www/html/include/class.orm.php(338): VerySimpleModel->refetch() #2 [internal function]: VerySimpleModel->__wakeup() #3 /var/www/html/include/class.ostsession.php(86): session_start() #4 /var/www/html/include/class.ostsession.php(130): osTicketSession->__construct(86400) #5 /var/www/html/include/class.osticket.php(60): osTicketSession::start(86400) #6 /var/www/html/include/class.osticket.php(628): osTicket->__construct() #7 /var/www/html/main.inc.php(33): osTicket::start() #8 /var/www/html/client.inc.php(21): require_once('/var/www/html/m...') #9 /var/www/html/index.php(16): require('/var/www/html/c...') #10 {main} thrown in /var/www/html/include/class.orm.php on line 1353

**Comment by JediKev** [comment]
@fayazmohmand 

This is an issue that is addressed by:
- https://github.com/osTicket/osTicket/pull/4740

Please use the pull with caution as it has not been approved/merged yet.

Cheers.

**Comment by Fayazahmadmohmand** [comment]
how i can fix i did not understand what should i do??

**Comment by JediKev** [comment]
@fayazmohmand 

You can clear your Session via browser or database (`ost_session` table) and you will be able to login. To prevent this issue from occurring in the future you can apply the pull request mentioned above until a fix is merged in a stable release.

Cheers.

**Comment by Fayazahmadmohmand** [comment]
thank you issue resolved.
