### ISSUE TITLE
editor does not accept notes: link

### ISSUE THREAD

**Issue by helloost** [osTicket/osTicket#5134]
### Description
i copy a documentlink from Lotus Notes to the editor.
![grafik](https://user-images.githubusercontent.com/56261202/67774850-5fa48c80-fa5e-11e9-98bb-c25a2cdd861a.png)

After i created the Answer it will be a denied in the link
![grafik](https://user-images.githubusercontent.com/56261202/67774989-95497580-fa5e-11e9-8532-0b3f84f2bff8.png)

I think it is a similiar issue as this:
https://github.com/osTicket/osTicket/issues/3681

![grafik](https://user-images.githubusercontent.com/56261202/67775032-a6928200-fa5e-11e9-8342-52acf04daf8a.png)
Thank you

**Comment by JediKev** [comment]
@helloost 

`NOTES://asdfasdf` is not a valid link nor is `NOTES://` a supported protocol. You will need to use an actual link for it to be accepted (eg. `HTTPS://domain.tld`, `HTTP://domain.tld`, etc.).

Cheers.

**Comment by helloost** [comment]
hm okay, thank you. i will look, if notes this will support

**Comment by JediKev** [comment]
@helloost 

The following href schemes are the only ones allowed:
- aim
- feed
- file
- ftp
- gopher
- http
- https
- irc
- mailto
- news
- nntp
- sftp
- ssh
- telnet

If you want to allow the `notes` scheme you can edit htmLawed and add `notes` to the schemes:
- https://github.com/osTicket/osTicket/blob/develop/include/htmLawed.php#L47

Cheers.

**Comment by helloost** [comment]
Oh nice,
i edit the htmlawed.php, added "Notes", but still denied.
iisreset done, hm
