### ISSUE TITLE
Advance Search Count

### ISSUE THREAD

**Issue by brunelle25** [osTicket/osTicket#5147]
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

When doing an advanced search the count is always 500 no matter the number of tickets that are found, which also affects the pagination since you get a bunch of blank pages. I've tested this on osTicket 1.12.3 and 1.14-RC2. Both Firefox v70.0.1 and Chrome v77.0.3865.120, also on PHP versions 7.1.21, 7.1.33 and 7.3.11. The results are always the same.

I also found this article referencing the same issue, said it was solved, https://github.com/osTicket/osTicket/issues/4750. I checked the fixed for this and this code issue has been cleared up so this must be a new issue.

### Steps to Reproduce
1. Click advanced search from the ticket list.
2. Fill out any criteria and click Search.

**Expected behavior:** I expect it to function like using a saved queue.
![2019-11-05_13-16-36](https://user-images.githubusercontent.com/46716846/68234136-9cc4cd80-ffce-11e9-91e4-2c26ce7ed63a.png)

**Actual behavior:** Getting a count of 500 and a bunch of blank pages no matter the number of results.
![2019-11-05_13-18-42](https://user-images.githubusercontent.com/46716846/68234316-f3caa280-ffce-11e9-9e16-d33e9aef0d97.png)

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about your server.
![2019-11-05_13-20-30](https://user-images.githubusercontent.com/46716846/68234370-0fce4400-ffcf-11e9-8f6b-3bb9c7498c16.png)

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.
Windows 10 v1803
Google Chrome v77.0.3865.120
Mozilla Firefox v70.0.1

**Comment by JediKev** [comment]
@brunelle25 

This has been mentioned countless times in many other threads. This is a temporary patch in place until we address the underlying issue. This will be addressed in future versions, stay tuned.

Cheers.
