### ISSUE TITLE
[1.14rc2] resolved tickets trigger an overdue alert

### ISSUE THREAD

**Issue by stultitiophobia** [osTicket/osTicket#5153]
I have upgraded an existing osTicket v1.12.3 Installation to the osTicket v1.14-rc2 release.

Now since immediately after the upgrade i get overdue mails for tickets that are already in the state "resolved".

In the ticket it reads:
closed by xxx with status resolved at 06.09.2018 9:32
marked overdue by the system at 07.11.2019 14:03

it's the same problem on around 260 tickets resulting in 260 mails.

I would expect resolved mails to not trigger a mail.

**Comment by JediKev** [comment]
@trendchiller 

This was mentioned in another thread. You’ll need this PR:
- https://github.com/osTicket/osTicket/commit/de7271d1de8fd951d387e3039763241fb062fc13

Cheers.

**Comment by stultitiophobia** [comment]
thanks for your fast help !
