### ISSUE TITLE
DB Error #1054

### ISSUE THREAD

**Issue by eduard9411** [osTicket/osTicket#5154]
Hello good day

I have problems with my osticket platform and I get the following error

[SELECT COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A2.`state` = 'open' AND A2.`id` IN (1) AND A2.`state` = 'open' AND A1.`dept_id` = 1 AND NOT (A1.`team_id` = 0 AND A1.`staff_id` = 0) AND NOT (A1.`team_id` = 0 AND A1.`staff_id` = 0) AND A1.`ticket_id` = Z1.`ticket_id` THEN A1.`ticket_id` END) AS `q15`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' THEN A1.`ticket_id` END) AS `q1`, COUNT(DISTINCT CASE WHEN A1.`staff_id` IN (1) AND A2.`state` = 'open' THEN A1.`ticket_id` END) AS `q5`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' THEN A1.`ticket_id` END) AS `q8` FROM `ost1_ticket` A1 JOIN `ost1_ticket_status` A2 ON (A1.`status_id` = A2.`id`) LEFT JOIN `ost1_thread` A3 ON (A3.`object_type` = 'T' AND A1.`ticket_id` = A3.`object_id`) LEFT JOIN `ost1_thread_referral` A4 ON (A3.`id` = A4.`thread_id`) LEFT JOIN `ost1_staff` A5 ON (A4.`object_type` = 'S' AND A4.`object_id` = A5.`staff_id`) LEFT JOIN `ost1_department` A6 ON (A4.`object_type` = 'D' AND A4.`object_id` = A6.`id`) WHERE (A2.`state` = 'open' AND (A1.`staff_id` = 1 OR A5.`staff_id` = 1)) OR A1.`dept_id` IN (6, 7) OR A6.`id` IN (6, 7)]

Unknown column 'Z1.ticket_id' in 'field list'<br />
<br />
---- Recular ----<br />
#0 (raíz)/include/mysqli.php(199): osTicket->logDBError('DB Error #1054', '[SELECT COUNT(D...')<br />
#1 (raíz)/include/class.orm.php(3455): db_query('SELECT COUNT(DI...', true, true)<br />
#2 (raíz)/include/class.orm.php(3502): MySqlExecutor->execute()<br />
#3 (raíz)/include/class.orm.php(2085): MySqlExecutor->getArray()<br />
#4 (raíz)/include/class.orm.php(2035): HashArrayIterator->{closure}()<br />
#5 (raíz)/include/class.orm.php(2014): CallbackSimpleIterator->next()<br />
#6 (raíz)/include/class.orm.php(2023): CallbackSimpleIterator->rewind()<br />
#7 (raíz)/include/class.orm.php(1695): CallbackSimpleIterator->valid()<br />
#8 (raíz)/include/class.orm.php(1705): CachedResultSet->fillTo(9223372036854775807)<br />
#9 (raíz)/include/class.orm.php(1328): CachedResultSet->asArray()<br />
#10 (raíz)/include/class.orm.php(1351): QuerySet->all()<br />
#11 (raíz)/include/class.search.php(925): QuerySet->one()<br />
#12 (raíz)/include/class.search.php(865): SavedQueue::counts(Object(StaffSession), true)<br />
#13 (raíz)/include/staff/templates/queue-tickets.tmpl.php(96): SavedQueue->getCount(Object(StaffSession))<br />
#14 (raíz)/scp/tickets.php(526): require_once('/var/www/html/S...')<br />
#15 {main}
 
Any solution with which you can help me?

**Comment by JediKev** [comment]
@eduard9411 

Go to `ost_queue` table and delete record with `id = 15`.

Cheers.
