### ISSUE TITLE
[Feature request] Date mail on mailfetch instead of date at moment of fetch

### ISSUE THREAD

**Issue by ghost** [osTicket/osTicket#5171]
Feature request ..
Is it possible to let the system check maildate on mail check instead of data and time of mailfetch ?

**Comment by JediKev** [comment]
@bernardflach 

The point of `Create Date` is that it's the time the Ticket was created in the Helpdesk, not when the email was sent. If you have piping (aka real-time ticket creation) the `Create Date` should be the time the email was delivered to your mailbox.

Cheers.
