### ISSUE TITLE
[feature request] - used queue/menu option in bold or other color

### ISSUE THREAD

**Issue by ghost** [osTicket/osTicket#5172]
I like to soo see witch option/queue (under tab Tickets) is open. 
Example : 
- open queue is selected, show "open" in menu in bold or other color
- If a subqueue of open slecten , show "open" in menu in bold or other color

**Comment by JediKev** [comment]
@bernardflach 

This is already a thing:
<img width="127" alt="Screen Shot 2019-11-14 at 08 33 47" src="https://user-images.githubusercontent.com/11823401/68866129-92cf5880-06b9-11ea-996c-c23e5c1c0416.png">
<img width="203" alt="Screen Shot 2019-11-14 at 08 34 03" src="https://user-images.githubusercontent.com/11823401/68866137-9531b280-06b9-11ea-8f05-7d194304477b.png">

Cheers.

**Comment by ghost** [comment]
the selected queue yes , however not the main (top) queue .. in your example thew label in the tab "tickets"

**Comment by JediKev** [comment]
@bernardflach 

The only queue that is Bold is the one you are currently on. It'd be super confusing if the top level queue and the sub queue was bold.

Cheers.

**Comment by ghost** [comment]
if youclick the logo you allways return to the last opened queue ... witch one is it ? you can't tell  :)

![Schermafdruk van 2019-11-14 15-46-12](https://user-images.githubusercontent.com/49860071/68867385-03946600-06f6-11ea-8fc9-03032e704685.png)

**Comment by JediKev** [comment]
@bernardflach 

Then name them differently so you can tell the difference :)

Cheers.

**Comment by ghost** [comment]
the selection/queue you see in the screenshot is in fact a underlying queue (named to to late)... (Open/ To Late)
You cannot see that this queue is selected ;)

**Comment by JediKev** [comment]
@bernardflach 

The queue in the screenshot is "Open"...not "To Late"...? You can tell what queue you are on by also looking at the queue name under the search box.

Cheers.

**Comment by ghost** [comment]
ill try something else ...;) 
thanks for replying @JediKev ....

in your words ... cheers ;)

**Comment by protich** [comment]
Just to clarify the queue naming is totally my fault - but for historical reasons. We've traditionally used "Open" to mean open and unanswered - this is in the olden days before Custom Queues when queues were limited to `Open | Answered | Closed` .

With introduction of Custom Queues and sub queues we tried to maintain the same interface and hence confusing "Open > Open" naming (alternative was to name the sub queue as Unanswered but who needs such negativity). 

As Kevin mentioned you can change the queue name to whatever you want.

**Comment by ghost** [comment]
i think somehere today I "wrecked" my testing installation :) Will redeploy RC2 from scratch.

I use now the (extra)custom status "Open/Waiting" and "Open/Planned" Just open and just close did not cut it. 

@JediKev and @protich Thanks for the replies :) :)
