### ISSUE TITLE
clickable URLs in ticket message miss some characters

### ISSUE THREAD

**Issue by kopitoshka** [osTicket/osTicket#5176]
### Description

I use plain text messages in osticket and they do not parse full URLs sometimes when the following characters are used in URL: [, ], /

My osticket is v1.12, but it seems the issue is still there (I have checked the files from the master branch).

### Broken URLs

https://test.com/cart/add?vendorid=123&PRODUCT[123]=3

https://www.test.com/index.php?route=marketplace/extension/info&extension_id=123

### How to fix

I fixed it in 
include/class.format.php

In function clickableurls.

A fix is attached, but I don't want to create a fork to pull the request, sorry.
[url_parsing_fix.txt](https://github.com/osTicket/osTicket/files/3849061/url_parsing_fix.txt)

**Comment by JediKev** [comment]
@kopitoshka 

Thank you for reporting this. I can indeed replicate the same issues. I see that you only added `\[\]\/` to the regex which is perfect, no over-kill with extra characters that are not needed 👍

I have made the pull request here:
- https://github.com/osTicket/osTicket/pull/5190

Cheers.
