### ISSUE TITLE
v1.12.3 (bcf1a6f) Does not load open tickets on the screen

### ISSUE THREAD

**Issue by ottogiraldo** [osTicket/osTicket#5181]
Regards:

In days past from one moment to another Osticket does not load open tickets on the screen. However, the configuration is as follows:

osTicket Version | v1.12.3 (bcf1a6f)     —  Up to date
Web Server Software | Apache
MySQL Version | 10.3.20
PHP Version | 7.0.33

PHP.INI => memory_limit = -1, post_max_size = 8M

In system logs shows the following records:

DB Error #1064

[SELECT COUNT(*) FROM (SELECT A1.`ticket_id` FROM `eticosin_ticket` A1 WHERE ) __] You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') __' at line 1
  ---- Backtrace ----
 #0 (root)/include/mysqli.php(199): osTicket->logDBError('DB Error #1064',  '[SELECT COUNT(*...')
..."

y " [SELECT COUNT(DISTINCT CASE WHEN THEN A1.`ticket_id` END) AS `q15`,  COUNT(DISTINCT CASE WHEN THEN A1.`ticket_id` END) AS `q16`,..."

I appreciate if you can help me, since Osticket has been a very useful application and I have been working for 3 years without problems.

Thank you very much for your attention and help.

**Comment by JediKev** [comment]
@ottogiraldo 

You have to paste the full error. You just need to delete a queue but we need to figure out which one.

Cheers.

**Comment by ottogiraldo** [comment]
In system logs:

- Registro 1 -
 DB Error #1064

[SELECT COUNT(*) FROM (SELECT A1.`ticket_id` FROM `eticosin_ticket` A1 WHERE ) __] You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') __' at line 1
 
 ---- Backtrace ----
 #0 (root)/include/mysqli.php(199): osTicket->logDBError('DB Error #1064',  '[SELECT COUNT(*...')
 #1 (root)/include/class.orm.php(3455): db_query('SELECT COUNT(*)...',  true,  true)
 #2 (root)/include/class.orm.php(3511): MySqlExecutor->execute()
 #3 (root)/include/class.orm.php(2941): MySqlExecutor->getRow()
 #4 (root)/include/class.orm.php(1372): MySqlCompiler->compileCount(Object(QuerySet))
 #5 (root)/include/class.search.php(857): QuerySet->count()
 #6 (root)/include/class.search.php(928): SavedQueue->getTotal()
 #7 (root)/include/class.search.php(865): SavedQueue::counts(Object(StaffSession),  true)
 #8 (root)/include/staff/templates/queue-tickets.tmpl.php(102): SavedQueue->getCount(Object(StaffSession))
 #9 (root)/scp/tickets.php(531): require_once('/home/eticosin/...')
 #10 (root)/scp/index.php(17): require('/home/eticosin/...')
 #11 {main}

----------------------------------------------
- Registro 2 -

DB Error #1064

[SELECT COUNT(DISTINCT CASE WHEN THEN A1.`ticket_id` END) AS `q15`,  COUNT(DISTINCT CASE WHEN THEN A1.`ticket_id` END) AS `q16`,  COUNT(DISTINCT CASE WHEN A1.`staff_id` IN (8) AND A1.`topic_id` = 12 THEN A1.`ticket_id` END) AS `q17`,  COUNT(DISTINCT CASE WHEN A1.`topic_id` = 12 THEN A1.`ticket_id` END) AS `q18`,  COUNT(DISTINCT CASE WHEN A1.`topic_id` = 12 THEN A1.`ticket_id` END) AS `q21`,  COUNT(DISTINCT CASE WHEN A1.`topic_id` = 13 THEN A1.`ticket_id` END) AS `q22`,  COUNT(DISTINCT CASE WHEN A1.`topic_id` = 12 THEN A1.`ticket_id` END) AS `q24`,  COUNT(DISTINCT CASE WHEN A1.`topic_id` = 12 THEN A1.`ticket_id` END) AS `q25`,  COUNT(DISTINCT CASE WHEN A2.`state` = 'open' THEN A1.`ticket_id` END) AS `q1`,  COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A2.`state` = 'open' AND A1.`isanswered` = '0' THEN A1.`ticket_id` END) AS `q2`,  COUNT(DISTINCT CASE WHEN (A1.`team_id` IN (1) OR A1.`staff_id` IN (10)) AND A2.`state` = 'open' AND (A1.`team_id` IN (1) OR A1.`staff_id` IN (10)) AND A2.`state` = 'open' AND A1.`staff_id` IN (10) THEN A1.`ticket_id` END) AS `q6`,  COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-11-15 05:00:00' AND '2019-11-16 04:59:59' THEN A1.`ticket_id` END) AS `q9`,  COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A2.`state` = 'open' AND A1.`isanswered` = '1' THEN A1.`ticket_id` END) AS `q3`,  COUNT(DISTINCT CASE WHEN (A1.`team_id` IN (1) OR A1.`staff_id` IN (10)) AND A2.`state` = 'open' AND (A1.`team_id` IN (1) OR A1.`staff_id` IN (10)) AND A2.`state` = 'open' AND NOT A1.`staff_id` IN (10) THEN A1.`ticket_id` END) AS `q7`,  COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-11-14 05:00:00' AND '2019-11-15 04:59:59' THEN A1.`ticket_id` END) AS `q10`,  COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A2.`state` = 'open' AND A1.`isoverdue` = '1' THEN A1.`ticket_id` END) AS `q4`,  COUNT(DISTINCT CASE WHEN (A1.`team_id` IN (1) OR A1.`staff_id` IN (10)) AND A2.`state` = 'open' THEN A1.`ticket_id` END) AS `q5`,  COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-11-11 05:00:00' AND '2019-11-18 04:59:59' THEN A1.`ticket_id` END) AS `q11`,  COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' THEN A1.`ticket_id` END) AS `q8`,  COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-11-01 05:00:00' AND '2019-12-01 04:59:59' THEN A1.`ticket_id` END) AS `q12`,  COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-10-01 05:00:00' AND '2020-01-01 04:59:59' THEN A1.`ticket_id` END) AS `q13`,  COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2019-01-01 05:00:00' AND '2020-01-01 04:59:59' THEN A1.`ticket_id` END) AS `q14` FROM `eticosin_ticket` A1 JOIN `eticosin_ticket_status` A2 ON (A1.`status_id` = A2.`id`) LEFT JOIN `eticosin_thread` A3 ON (A3.`object_type` = 'T' AND A1.`ticket_id` = A3.`object_id`) LEFT JOIN `eticosin_thread_referral` A4 ON (A3.`id` = A4.`thread_id`) LEFT JOIN `eticosin_staff` A5 ON (A4.`object_type` = 'S' AND A4.`object_id` = A5.`staff_id`) LEFT JOIN `eticosin_team` A6 ON (A4.`object_type` = 'E' AND A4.`object_id` = A6.`team_id`) LEFT JOIN `eticosin_department` A7 ON (A4.`object_type` = 'D' AND A4.`object_id` = A7.`id`) WHERE (A2.`state` = 'open' AND (A1.`staff_id` = 10 OR A5.`staff_id` = 10 OR A1.`team_id` IN (1) OR A6.`team_id` IN (1))) OR (A2.`state` IN ('open',  'closed') AND (A1.`dept_id` IN (1,  4,  5,  6) OR A7.`id` IN (1,  4,  5,  6)))] You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'THEN A1.`ticket_id` END) AS `q15`,  COUNT(DISTINCT CASE WHEN THEN A1.`ticket_id`' at line 1
 
 ---- Backtrace ----
 #0 (root)/include/mysqli.php(199): osTicket->logDBError('DB Error #1064',  '[SELECT COUNT(D...')
 #1 (root)/include/class.orm.php(3455): db_query('SELECT COUNT(DI...',  true,  true)
 #2 (root)/include/class.orm.php(3502): MySqlExecutor->execute()
 #3 (root)/include/class.orm.php(2085): MySqlExecutor->getArray()
 #4 (root)/include/class.orm.php(2035): HashArrayIterator->{closure}()
 #5 (root)/include/class.orm.php(2014): CallbackSimpleIterator->next()
 #6 (root)/include/class.orm.php(2023): CallbackSimpleIterator->rewind()
 #7 (root)/include/class.orm.php(1695): CallbackSimpleIterator->valid()
 #8 (root)/include/class.orm.php(1705): CachedResultSet->fillTo(9223372036854775807)
 #9 (root)/include/class.orm.php(1328): CachedResultSet->asArray()
 #10 (root)/include/class.orm.php(1351): QuerySet->all()
 #11 (root)/include/class.search.php(925): QuerySet->one()
 #12 (root)/include/class.search.php(865): SavedQueue::counts(Object(StaffSession),  true)
 #13 (root)/include/staff/templates/queue-tickets.tmpl.php(102): SavedQueue->getCount(Object(StaffSession))
 #14 (root)/scp/tickets.php(531): require_once('/home/eticosin/...')
 #15 (root)/scp/index.php(17): require('/home/eticosin/...')
 #16 {main}

**Comment by JediKev** [comment]
@ottogiraldo 

The first error is not complete for some reason so I can’t say what queue in particular that’s complaining about. As for the second error you need to go to `eticosin_queue` table and delete queues with `id` of 15 and 16.

You can take a backup of the table if you wish before deleting the two queues.

Cheers.
