### ISSUE TITLE
Assigned To Me View is empty + Reason

### ISSUE THREAD

**Issue by mburamorde** [osTicket/osTicket#5184]
Hi,

I use the latest RC an have the problem, that the "Assigned to Me" View is empty!

The Cause of the Problem is  **A1.`team_id` IS NULL**. It needs to be changed to ** A1.`team_id`=0**

>WHERE
    **A1.`team_id` IS NULL** AND A2.`state` = 'open' AND A1.`staff_id` IN(1) AND(
        (
            A2.`state` = 'open' AND(
                A1.`staff_id` = 1 OR A5.`staff_id` = 1 OR A6.`object_type` = 'C' AND A8.`staff_id` = 1
            )
        ) OR A1.`dept_id` IN(1) OR B0.`id` IN(1) OR A6.`object_type` = 'C' AND B1.`id` IN(1)
    ) AND A3.`object_type` = 'T'
GROUP BY

**Comment by protich** [comment]
We have a pull request (#5177) that addresses the issue.

**Comment by mburamorde** [comment]
I patched my version with pullrequest #5177 and this does'nt fixes this problem.

I'f an user is'nt assigned to the team he has an empty "Assigned to me" Queue.

**Comment by JediKev** [comment]
@mburamorde 

I tested this in v1.12.5 and it's no longer an issue. If you continue to experience this issue after upgrading to v1.12.5 or v1.14.1, please reopen.

Cheers.
