### ISSUE TITLE
Can't add a second "once only" holiday in holiday schedule

### ISSUE THREAD

**Issue by stuart-elliott-70** [osTicket/osTicket#5198]
I added a holiday in the schedule, with a repeat option of "once", which it accepted, created another with a different name and date, but it claims an entry already exists, which it doesn't, if I change the repeat to anything other than "once", then it saves no problem.

If I had to guess, the repeats value "never" in ost_schedule_entry is what is triggering the assumed duplication.

**Comment by protich** [comment]
Thank you for the report...  I have a PR referenced above addressing the issue. 

Please note that the system doesn't currently consider time boundaries - you can technically have multiple entries on the same day but on different timespans! However, I didn't think it was worth the effort for schedules as designed.
