### ISSUE TITLE
1.12.4 displays version as 1.12-git

### ISSUE THREAD

**Issue by RobbyZ** [osTicket/osTicket#5199]
Version downloaded from https://github.com/osTicket/osTicket/archive/v1.12.4.tar.gz displays version as '1.12-git' in the system settings admin panel.

**Comment by JediKev** [comment]
@RobbyZ 

How are you even downloading that? You are supposed to either download from the Release itself (Assets > osTicket-v1.12.4.zip):
- https://github.com/osTicket/osTicket/releases/tag/v1.12.4

Or download from our website:
- https://osticket.com/download

If you download an archive from Github or clone the repo then yes it will show git as you are using the git version...

Cheers.

**Comment by RobbyZ** [comment]
I downloaded it from the release assets page.  I downloaded the .tar.gz because I was deploying to a linux system.  

It's kinda confusing if there's assets in releases that aren't intended to be deployed...

Are there any important differences versus the .zip version (can I get away without doing a re-deploy & retest ;))?

**Comment by JediKev** [comment]
@RobbyZ 

The other two assets are added by GitHub automatically. If you download from git the best thing to do is download the repo somewhere and then actually deploy the code to the html directory with the following command from within the repo:
```
php manage.php deploy -v /path/to/html/dir/
```

Cheers.
