### ISSUE TITLE
audit log issue

### ISSUE THREAD

**Issue by johnkalangha** [osTicket/osTicket#5211]
![image](https://user-images.githubusercontent.com/30627667/69470402-67dbb780-0dd1-11ea-8e15-a558d8b0b782.png)

when i open audit issue log in specific, there are 2 pages, but when open second it direct to ticket page 2...

![image](https://user-images.githubusercontent.com/30627667/69470441-a2ddeb00-0dd1-11ea-8386-42a522e83985.png)
![image](https://user-images.githubusercontent.com/30627667/69470470-c99c2180-0dd1-11ea-9108-9a5310a28217.png)

**Comment by JediKev** [comment]
@johnkalangha 

This has been addressed in subsequent updates. If you continue to experience this issue with v1.12.5 or v1.14.1 please reopen.

Cheers.
