### ISSUE TITLE
Unable to export Ticket CSV

### ISSUE THREAD

**Issue by cc-cnc** [osTicket/osTicket#5212]
Server Information
--
osTicket Version | v1.14.1 (f1e9e88)     —  Up to date
Web Server Software | Microsoft-IIS/10.0
MySQL Version | 5.5.45
PHP Version | 7.3.10

![CSV Export Error](https://user-images.githubusercontent.com/58097440/69472208-087ba880-0dcd-11ea-8160-f611a4f0d21a.jpg)

**Comment by JediKev** [comment]
@cc-cnc 

Check your IIS logs, MySQL logs, PHP logs, browser console, and osTicket System Logs for any related errors.

Cheers.

**Comment by cc-cnc** [comment]
Thank you. Issue on PHP. I have upgrade the PHP. Working fine now.

**Comment by scarcamo-eyg** [comment]
@cc-cnc from what version to what php version ? Thanks.

**Comment by JediKev** [comment]
@scarcamo-eyg 

I don't know what version he upgraded _from_ but he upgraded _to_ PHP 7.3.10 (as seen in his initial comment).

Cheers.

**Comment by scarcamo-eyg** [comment]
@JediKev Oh I See, thank you.
I was asking because I'm troubleshooting same issue

**Comment by JediKev** [comment]
@scarcamo-eyg 

If you are getting a blank white popup box after clicking Export then see:
- https://github.com/osTicket/osTicket/issues/5303#issuecomment-585410716

If you are getting the same error as the OP (`Unable to prepare the export`) then try upgrading PHP to v7.0+ (preferably 7.3).

Cheers.
