### ISSUE TITLE
Due date issue with Schedule Entry 1st Saturday Every Month

### ISSUE THREAD

**Issue by cc-cnc** [osTicket/osTicket#5213]
Working Hours Timeline
--
*** Add 24 Working Hours to 2019-11-23 08:55:00 ***
### **2019-11-02 -> Apply 4.000000 Working Hours from Working Saturday 1                         - **2019-11-02 13:00:00 (4)****
2019-11-23 -> Apply 4.000000 Working Hours from Saturday                         - 2019-11-23 13:00:00 (8)
2019-11-25 -> Apply 9.000000 Working Hours from Monday                         - 2019-11-25 17:00:00 (17)
2019-11-26 -> Apply 9.000000 Working Hours from Tuesday                         - 2019-11-26 17:00:00 (26)
2019-11-26 -> Backtrack 2.000000 Hours  2019-11-26 15:00:00 (24)
*** Final Datetime  2019-11-26 15:00:00 ***

![image](https://user-images.githubusercontent.com/58097440/69472380-69a47b80-0dcf-11ea-90f7-9fbd5d14a700.png)

Server Information
--
osTicket Version | v1.14.1 (f1e9e88)     —  Up to date
Web Server Software | Microsoft-IIS/10.0
MySQL Version | 5.5.45
PHP Version | 7.3.10

**Comment by protich** [comment]
@cc-cnc - that's the only schedule entry?

**Comment by cc-cnc** [comment]
No it has weekly Monday to Friday 8.00 am to 5.00 pm schedules as well.

**Comment by protich** [comment]
I can confirm the issue - I'll have a fix later today. Thanks for the report.

**Comment by cc-cnc** [comment]
Thank  you

**Comment by protich** [comment]
Below is a patch to address the issue - please apply and let me know the results on your end.

I had failed to consider the start date of the schedule entry when determining the initial occurrence.

```diff
diff --git a/include/class.schedule.php b/include/class.schedule.php
index 4881e08..ddbc266 100644
--- a/include/class.schedule.php
+++ b/include/class.schedule.php
@@ -788,15 +788,18 @@ class ScheduleEntry extends VerySimpleModel {
 
     function getCurrent($from=null) {
         if (!isset($this->_current) || $from) {
+            // Figure out starting  point (from)
+            $from = is_object($from) ? clone $from : Format::parseDateTime($from ?: 'now');
+            $start =  $this->getStartsDatetime();
+            if ($start->getTimestamp() > $from->getTimestamp())
+                $from = clone $start;
             // Check to make sure we're still in scope
-            $start = is_object($from) ? clone $from : Format::parseDateTime($from ?: 'now');
             $stop = $this->getStopsDatetime();
-            if ($stop && $stop->getTimestamp() < $start->getTimestamp())
+            if ($stop && $stop->getTimestamp() < $from->getTimestamp())
                 return null;
-
             // Figure out start time for the entry.
-            $start->modify($this->getIntervalSpec($start));
-            $this->_current = clone $start;
+            $from->modify($this->getIntervalSpec($from));
+            $this->_current = clone $from;
         }
         return $this->_current;
     }
```

Please note that start date on a monthly frequency is ignored - month of the date is what matters.

**Comment by cc-cnc** [comment]
Thank you. How should I apply this patch?

**Comment by JediKev** [comment]
@cc-cnc 

Use the command in the docs below:
- https://git-scm.com/docs/git-apply

Or apply them manually.

Cheers.

**Comment by cc-cnc** [comment]
@JediKev 
I am not a programmer. How can I apply them manually?

**Comment by JediKev** [comment]
@cc-cnc 

Open the files in a text editor and make the changes manually or download the files from github and replace your current ones. If you don’t know how there are many guides online. You could also wait for the patch to be merged into core and for a new version to be released but that might take some time.

Cheers.

**Comment by protich** [comment]
What @JediKev mentioned are possibilities - you can also [download](https://raw.githubusercontent.com/osTicket/osTicket/3a41b0925be1847f3cd54c90f675ddd06c64f748/include/class.schedule.php) just the changed file and replace the local one.

**Comment by cc-cnc** [comment]
@protich Thank you it is working fine now.

**Comment by cc-cnc** [comment]
@protich Thank you it is working fine now.

**Comment by cc-cnc** [comment]
Still having the same issue. Works once the start on date moved to Jan 4, 2020.

![image](https://user-images.githubusercontent.com/58097440/70411259-b2b72980-1a77-11ea-91c5-f19123c59cf0.png)

![image](https://user-images.githubusercontent.com/58097440/70411427-38d37000-1a78-11ea-8767-c63234c44553.png)

![image](https://user-images.githubusercontent.com/58097440/70411287-c6fb2680-1a77-11ea-9983-29e70f0a6afc.png)


![image](https://user-images.githubusercontent.com/58097440/70411332-e8f4a900-1a77-11ea-81dc-ee3937dfab38.png)

**Comment by cc-cnc** [comment]
@protich Your assistance in this matter is greatly appreciated.

**Comment by protich** [comment]
Can you be a little specific on what's not working?

**Comment by cc-cnc** [comment]
After the last fixed, I have set the Starts on date as 12/7/19 and till then the schedule entry works well. But, SLA expiring issue again starts after 12/8/19.

It is working, once the start date manually change to the next month.

https://github.com/osTicket/osTicket/issues/5213#issuecomment-563078264

**Comment by protich** [comment]
PR #5279 addresses the issue -  here is the [raw file](https://github.com/osTicket/osTicket/blob/78df051b571600861bc10afcb49f1990bd9e1e21/include/class.schedule.php) with the fix you can download.

**Comment by cc-cnc** [comment]
with new raw file, due date getting change 24 hours + SLA.

eg:
SLA  - High - Grace Period is 4 hour.
After placing new raw file.
When ticket creates at 12/17/19 12:49 PM. Due date shows as 12/18/19 12:30 PM

**Comment by protich** [comment]
Looking into it - thanks.

**Comment by protich** [comment]
I believe I've resolved the issue for realz this time. But the changes spans 3 files - which you'll need to download and replace on your local install.

https://github.com/osTicket/osTicket/blob/3da5bd7a59c8b7d7dd055549480208fdad2c05dc/include/class.businesshours.php
https://github.com/osTicket/osTicket/blob/3da5bd7a59c8b7d7dd055549480208fdad2c05dc/include/class.schedule.php
https://github.com/osTicket/osTicket/blob/3da5bd7a59c8b7d7dd055549480208fdad2c05dc/include/staff/templates/schedule-diagnostic.tmpl.php

Please report back after some testing.

**Comment by cc-cnc** [comment]
@protich it is working fine now. Thank you and appreciate your support.
