### ISSUE TITLE
Cannot Add Active Directory Users to Ticket If User is Surname, Name

### ISSUE THREAD

**Issue by asprofridis** [osTicket/osTicket#5231]
I am trying to open a new ticket and add a new user to my ticket via the "lookup or create a user" window.

Although it finds the user successfully on the active directory, it cannot add it to the ticket if I click on the name:

![import](https://user-images.githubusercontent.com/58257513/69723232-bf578b80-1121-11ea-9157-ad1ec8042ccc.gif)

After a lot of tests I noticed this happens because all my users appear on the active directory as Surname, Name :

![import2](https://user-images.githubusercontent.com/58257513/69723334-f9289200-1121-11ea-8ad6-e84395445864.gif)

My current configuration is:

osTicket Version | v1.14.1 (f1e9e88)   
Web Server Software | Microsoft-IIS/10.0
MySQL Version | 5.5.45
PHP Version | 7.3.7
Server | Windows Server 2019 Datacenter

**Comment by asprofridis** [comment]
Dear All,

any news regarding this issue?

**Comment by JediKev** [comment]
@asprofridis 

You just need to click Add User. If a User does not have an account in osTicket, once you click the user in the dropdown the system will auto-fill their information in the fields and then you are supposed to click Add User to add the User to the system. Once you click Add User it should add the User and add them as the owner of the ticket. After you've added the User once, you shouldn't have to do it again.

Please reopen if you have anymore issues.

Cheers.

**Comment by asprofridis** [comment]
Hi JediKev,

Maybe I was not clear enough with my issue. Let me re describe it : 

1) I have the user demo, user with display name "demo, user" (please check attached pic1")
![pic1](https://user-images.githubusercontent.com/58257513/74417607-a8d2ed80-4e4f-11ea-9ae8-850f4ad0a358.JPG). 
The user is new and doesn't exist on os ticketing.

2)I open a new ticket, i click "add new" next to user, I type his name, Os ticket finds him, I click on the name it finds, but it doesn't fills the email address and the full name on the "create new user fields"  so as to click on the "add user"(please check attached pic2).

![pic2](https://user-images.githubusercontent.com/58257513/74417976-50502000-4e50-11ea-97bf-68d48f82ed6d.JPG)

3) If I rename the user on the domain controller and change it to " Demo User" (without the comma) 
and follow the same steps (open a a new ticket, click "add new" next to user, type his name and click on the name it finds) email address and full name fields will be completed successfully and I will be able to add user (please check pic3)
![pic3](https://user-images.githubusercontent.com/58257513/74419414-87273580-4e52-11ea-88d4-24e64fa8404c.JPG)

My problem is that all my domain users have been created as "surname, name" so  I cant add them as new users on my system

Your help is Highly appreciated !!!!!

**Comment by asprofridis** [comment]
Hi jediKev,

thx for replying to my issue!

unfortunately I cant reopen it but i commented below your answer.

thx in advanced

**Comment by JediKev** [comment]
@asprofridis 

Again, I tested this and do not have the same issues. I have a user in OpenLDAP called `Last, First` and if I click their name, the system autofills their information in the Add User modal.
<img width="358" alt="Screen Shot 2020-02-12 at 16 00 52" src="https://user-images.githubusercontent.com/11823401/74449970-fac14680-4e42-11ea-8190-7776381cd745.png">
<img width="634" alt="Screen Shot 2020-02-12 at 16 01 00" src="https://user-images.githubusercontent.com/11823401/74449977-fc8b0a00-4e42-11ea-8a08-dddf8b1e45a0.png">

Maybe you need to change some settings in LDAP or mess with your search base settings for the plugin in osTicket?

Cheers.
