### ISSUE TITLE
Edit topic name/title - size / maxlength

### ISSUE THREAD

**Issue by mlipok** [osTicket/osTicket#5237]
### Prerequisites

* [ y ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ n ] Do you have any errors in the PHP error log, or javascript console?
* [ y ] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [ y ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description
in this Issue:
https://github.com/osTicket/osTicket/issues/2931
This clearly states that topic names have 255 chars for length.
But when you have to edit the old topic title, the osTicket interface limits the agents to 50 chars.
Moreover, the interface has not relevant width/size.

[Description of the bug or feature]

**FEATURE REQUEST:**
Change the **size** property of <input> TAG from 40 to 100
Change the **maxlength** property of <input> TAG from 50 to 255
Take a look in attached screenshot.

### Steps to Reproduce

1. go to any ticket, with a long ticket name/title (longer than 50 chars)
2. when the ticket is opened, click "edit ticket properties" to change ticket name/title
3. try to change the name/title by adding more chars

**Expected behavior:** [What you expected to happen]
The agent should be able to make a longer ticket name/title exactly 255 chars long.
The size of <input> should show as many chars as possible in this case size should be =100 (at the moment until GUI is not fully responsive).

**Actual behavior:** [What actually happened]
Size is only = 50 so the agent does not see too much from the ticket name/title.
The "maxlength" property is to short, so when anybody creates a ticket via email and the ticket name/title is already longer than 50 chars, then the agent which wants to edit the title, could not do this properly.

**I have done some tests.**
![osTicke Topic Name size](https://user-images.githubusercontent.com/11089482/69946227-89345600-14eb-11ea-9ab5-61cc20deea88.png)

If I manually change the parameters then for this moment I see longer text, and I can edit longer ticket names/titles, and finally, the changes provided in time when the agent add new chars to the ticket name/title all correctly saved to the database, so it looks like the only problem is in FrontEnd not in the database or logic engine.

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about your server.

osTicket=v1.14.1 (f1e9e88)
WWWServerSoftware=Apache
MySQL=10.0.38
PHP=7.2.25-1+0~20191128.32+debian8~1.gbp108445
Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

**Comment by JediKev** [comment]
@mlipok 

I do not see the same issues with `v1.14.1`. Below is what I see:

#### Size and MaxLength (default)
<img width="940" alt="Screen Shot 2019-12-02 at 09 51 51" src="https://user-images.githubusercontent.com/11823401/69973664-7d479480-14e9-11ea-91d3-176e2f798f6d.png">
<img width="1152" alt="Screen Shot 2019-12-02 at 09 52 28" src="https://user-images.githubusercontent.com/11823401/69973762-a9fbac00-14e9-11ea-9162-c6d63a88f73d.png">

#### 250 Characters in Ticket Title
<img width="962" alt="Screen Shot 2019-12-02 at 09 50 17" src="https://user-images.githubusercontent.com/11823401/69973786-b122ba00-14e9-11ea-9606-07dd89700ed2.png">


If you want to change any of this behavior for any field then you must edit the Field Configurations under **Admin Panel > Manage > Forms**. For the Issue Summary specifically go to  **Admin Panel > Manage > Forms > Ticket Details > Issue Summary > Config**. Here you can edit the **Size** and **Max Length** properties to your liking.
<img width="382" alt="Screen Shot 2019-12-02 at 09 54 39" src="https://user-images.githubusercontent.com/11823401/69974193-5d64a080-14ea-11ea-84fb-be580ba64945.png">

**Size** is the size of the field in the Ticket Edit View and **Max Length** is the amount of characters it will accept and save in the database.

Cheers.

**Comment by mlipok** [comment]
Thanks for you answer - this solves this problem.
osTicket is Awesome.
