### ISSUE TITLE
ticket create API: custom field of custom form

### ISSUE THREAD

**Issue by npeditto** [osTicket/osTicket#5244]
### Prerequisites

* Can you reproduce the problem in a fresh installation of the "develop" branch?
calling create-ticket API specifing a field of a custom form

* Do you have any errors in the PHP error log, or javascript console?
NO

* Did you check the [osTicket forums](https://forum.osticket.com/)?
no solution found

* Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?
I found this issues:
  - https://github.com/osTicket/osTicket/issues/1083
  - https://github.com/osTicket/osTicket/pull/1105

  But the solution was already merged 

### Description
When a I call the API for ticket creation ( [POST] /api/tickets.json ) with a custom field (es: "group_id") that it is in a custom form, the API creates successfully the new ticket but without the custom field; in osticket System logs I see:
```
API Unexpected Data
group_id: Unexpected data received in API request
```

NB: all the custom fields that I added in the default form "Ticket Details" are correctly added in the new ticket.

How can I specify in my API request these kind of fields of custom forms?

### Versions
v1.14.1

**Comment by JediKev** [comment]
@npeditto 

Post a screenshot of your form field as well as an example of your request.

Cheers.

**Comment by npeditto** [comment]
![image](https://user-images.githubusercontent.com/5755178/70155741-1aa1f480-16b3-11ea-970e-101a492738d6.png)

[POST] http://<OST-IP>/api/tickets.json
Header: 
```
X-API-Key: <OST-KEY>
Content-Type:application/json
```
Body:
```
{
    "alert": true,
    "autorespond": false,
    "source": "API",
    "name": "Smith",
    "email": "test@test.io",
    "phone": "+39000000000",
    "subject": "Testing Alert",
    "message": "data:text/html, Help <b>ALERT</b>",
    "topicId": 12,
    "group_id": "B10066",
    "attachments": [
    ]
}
```

**Comment by JediKev** [comment]
@npeditto 

I see you have `topic_id` of `12`, is the Custom Form attached to the Help Topic with `id` of `12`?

Cheers.

**Comment by JediKev** [comment]
@npeditto 

Also, in our [documentation](https://docs.osticket.com/en/latest/Developer%20Documentation/API/Tickets.html#create-a-ticket) it says to use `topicId` not `topic_id`. I would first ensure that the Custom Form is attached to the Help Topic with `id` of `12`, then I'd change the variable name of `topic_id` to `topicId` in your requests and lastly retest.

Cheers.

**Comment by npeditto** [comment]
I was using 

> "topicId": 12,

not "topic_id"; the problem was related to the Custom Form not attached to Help Topic.

Thank you for your support!

Nicola
