### ISSUE TITLE
[Feature Request] Set default sort order for a Default Sort Column

### ISSUE THREAD

**Issue by abramesd** [osTicket/osTicket#5254]
### Prerequisites

* [Y] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [N] Do you have any errors in the PHP error log, or javascript console?
* [Y] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [Y] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

In release 1.14.1 the new "Assign to me" My Tickets list has a new "Settings" options link.  There are three tabs and on the tab labeled "Settings" {see attached screen capture), I can choose the default column to sort on.  However I want to sort the "Due Date" column in Ascending order but the default sort column is sorted in Descending order.  I would like to request that an option be added so allow for changing the default sort order of the default sort column, maybe a checkbox to select "Ascending" and if the checkbox is not checked then the order would be "Descending". 

![OSTicket-Default_Sort_Column](https://user-images.githubusercontent.com/46332931/70344572-059aa200-1828-11ea-9a5d-57ae50e916cd.png)

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]
{Feature Request] Would like an option to allow choosing the default sort order of the default sort column

**Actual behavior:** [What actually happened]
Currently the default sort column is only sorting in descending order

### Versions
1.14.1

Admin panel -> Dashboard -> Information which also additionally gives you information about your server.

SEE ATTACHED FILE
![OSTicket-Dashboard-Information](https://user-images.githubusercontent.com/46332931/70344571-059aa200-1828-11ea-8c72-492e0ae7d1e5.png)

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

Windows 10 Enterprise 64 bit
Vivaldi Browser 

- > Vivaldi | 2.8.1664.40 (Stable channel) (64-bit)
- > -- | --
- > Revision | 3ceb1e00616d447249d27368e347561bc737a2e0
- > OS | Windows 10 OS Version 1909 (Build 18363.476)
- > JavaScript | V8 7.7.299.11
- > Flash | 32.0.0.293 C:\WINDOWS\system32\Macromed\Flash\pepflashplayer64_32_0_0_293.dll
- > User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.93 Safari/537.36 Vivaldi/2.8.1664.40
- > Command Line | "C:\Users\abramesd\AppData\Local\Vivaldi\Application\vivaldi.exe" --profile-directory=Default --app-id=mpognobbkildjkofajifpdfhcoklimli --flag-switches-begin --flag-switches-end --ppapi-flash-path="C:\WINDOWS\system32\Macromed\Flash\pepflashplayer64_32_0_0_293.dll" --save-page-as-mhtml
- > Executable Path | C:\Users\abramesd\AppData\Local\Vivaldi\Application\vivaldi.exe
- > Profile Path | C:\Users\abramesd\AppData\Local\Vivaldi\User Data\Default
- >

**Comment by mlipok** [comment]
I agree that this feature will be very handy.

**Comment by JediKev** [comment]
@abramesd @mlipok 

This is already a thing, see the below comment:
- https://github.com/osTicket/osTicket/issues/5364#issuecomment-582477727

Here is a screenshot to show what I mean:
<img width="963" alt="Screen Shot 2020-02-12 at 16 30 12" src="https://user-images.githubusercontent.com/11823401/74383734-6361e200-4db5-11ea-89de-bc0a98c3510d.png">

Please re-open if you experience any issues.

Cheers.
