### ISSUE TITLE
Organizations - adding selected user from users list

### ISSUE THREAD

**Issue by mlipok** [osTicket/osTicket#5261]
### Prerequisites

* [ Y ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ N ] Do you have any errors in the PHP error log, or javascript console?
* [ Y ] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [ Y ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description
https://forum.osticket.com/d/96488-adding-selected-user-to-organization

[Description of the bug or feature]

### Steps to Reproduce
Just go to ..../scp/users.php
Select few users, and then click "More" >> "Add to organization" >> "Continue"

**Expected behavior:** [What you expected to happen]
All selected user should be added to selected organizations

**Actual behavior:** [What actually happened]
Nothing happened

### Versions
v1.14.1 (f1e9e88)

**Comment by JediKev** [comment]
@mlipok 

You'll need this:
- https://github.com/osTicket/osTicket/pull/5241

Cheers.
