### ISSUE TITLE
webpage has a wrong format

### ISSUE THREAD

**Issue by sjxiong** [osTicket/osTicket#5275]
V1.14.1
Description
![image](https://user-images.githubusercontent.com/15185770/70811902-d60b0d00-1dc6-11ea-903c-703e9703f5c6.png)

[Description of the bug or feature]
see picture above, when I add more collumns to the queue, the table is not aligned with the rest of the page. looks bit annoying...

**Comment by ntozier** [comment]
It seems that you edited the queue or made a custom queue and did not adjust the size of your columns.

**Comment by sjxiong** [comment]
Does it not change automatically? do I need to change code for that? I'm not a programmer...that's a bit difficult for me.

**Comment by ntozier** [comment]
Column width is in the queue settings.  It does not change automatically.

![2019-12-13_1049](https://user-images.githubusercontent.com/1315768/70812748-35045e00-1d96-11ea-901a-d6854e265bff.png)

**Comment by sjxiong** [comment]
ah, thank you!!!!

**Comment by ntozier** [comment]
Very welcome.

Please feel free to post on the forums for questions like this.
Also please close this issue report. :)

**Comment by sjxiong** [comment]
ok
