### ISSUE TITLE
Question : About customization

### ISSUE THREAD

**Issue by cervedgroup** [osTicket/osTicket#5277]
Version 1.12.5
how can we modify that fields ?
![image](https://user-images.githubusercontent.com/6535381/70910532-304ade80-2010-11ea-8e42-2f0cff251ae7.png)

in previous version we made the customize, editing the user.tmpl.php , but now can't find the point anymore.
We need to add some lines and some data in that form...
thank u for you help

**Comment by ntozier** [comment]
This does not appear to be an issue report and should probably be asked on the forums.

That being said go to **Admin panel -> Manage -> Forms -> Contact Information**
The form can be edited there.

Once it is setup the way you want it, you can go to **Agent panel -> Users** click on the user that you want to edit or Click on the edit button on the screen that you showed us.

![2019-12-16_1003](https://user-images.githubusercontent.com/1315768/70917544-848f9780-1feb-11ea-8077-93573620fca5.png)

Please close this issue report.
