### ISSUE TITLE
First Agent Response Timestamp in export Excel file

### ISSUE THREAD

**Issue by ffsab00070875** [osTicket/osTicket#5278]
Dear all,

I'm using 1.14.1. (PHP 7, Ubuntu 18)

In our system, agent need to calculate the average time from "first agent response time" to "close ticket time".
So they need to export ticket with this column, but I don't have any idea to do this.

Thanks!

BRs,

**Comment by JediKev** [comment]
@ffsab00070875 

Please open this on the Forum as that is the appropriate place to ask questions. Github is a place to report an actual issue with the software, to make a feature request, or to submit a pull request. Being that this is none of the above you will need to ask this on the Forum here:
- https://forum.osticket.com

Cheers.

**Comment by ffsab00070875** [comment]
Thanks JediKev
