### ISSUE TITLE
Custom Queue in Ticket Queues

### ISSUE THREAD

**Issue by ffsab00070875** [osTicket/osTicket#5286]
I find nothing to mod this block, I want to customize source code for last response to create "first response" for my system.

![12345](https://user-images.githubusercontent.com/18123688/71061079-3244a700-21a2-11ea-845a-714a239c7d3a.JPG)

I just find something about it in queue-columns.tmpl.php
But have no idea to customize it.
![123](https://user-images.githubusercontent.com/18123688/71061087-396bb500-21a2-11ea-9c10-5b25a0b7560b.JPG)

BRs,

**Comment by JediKev** [comment]
@ffsab00070875 

Post this on the forum.
