### ISSUE TITLE
Attachments Crashing Stream

### ISSUE THREAD

**Issue by EIJason** [osTicket/osTicket#5292]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch? No fresh install of osticket seems ok v1.14
* [ ] Do you have any errors in the PHP error log, or javascript console? not on php but i do get the following javascript Error when trying to send an attachment from osticket...

POST 500
 https://sales.europeincoming.com/scp/tickets.php?id=261 
/scp/tickets.php?id=261#reply:1

Navigated to https://sales.europeincoming.com/scp/tickets.php?id=261
Navigated to chrome-error://chromewebdata/

* [x] Did you check the [osTicket forums](https://forum.osticket.com/)? Yes Cant Find anything
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported? I did...

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### After upgrading to Osticket 1.14 File attachements seem to crash ostick stream when sending from osticket, when recieving via email I get a system error saying unable to save attachment? I have deleted all plugins as that was the only difference between my test fresh install and my current beside the fact the current running ones were upgraded from a previous version? Any Ideas why this is happening?

[Description of the bug or feature]

### Steps to Reproduce

1. Upgrade from 1.12 to 1.14
2. Email an Attachment to a mailbox which gets checked with Imap
3. Add an attachment and send from Osticket via smtp

**Expected behavior:** Attachment get sent and recieved and attached to thread.

**Actual behavior:**Crash on sending Http Error 500, On recieving file is unable to be saved system message in thread

### Versions
1.14 Upgrade from 1.12

Admin panel -> Dashboard -> Information which also additionally gives you information about your server.

Server Information
--
osTicket Version | v1.14.1 (f1e9e88) —  Up to date
Web Server Software | LiteSpeed
MySQL Version | 10.2.30
PHP Version | 7.3.12

gdlib | Used for image manipulation and PDF printing
imap | Used for email fetching
xml | XML API
xml-dom | Used for HTML email processing
json | Improves performance creating and processing JSON
mbstring | Highly recommended for non western european language content
phar | Highly recommended for plugins and language packs
intl | Highly recommended for non western european language content
fileinfo | Used to detect file types for uploads
zip | Used for ticket and task exporting
APCu | Improves overall performance
Zend Opcache | Improves overall performance

cgi.fix_pathinfo | "1" is recommended if AJAX is not working
date.timezone | Europe/London

Schema | europein_os1 (localhost)
Schema Signature | 4bd47d94b10bd8a6bab35c119dadf41f
Space Used | 0.79 MiB
Space for Attachments | 0.33 MiB
Timezone | GMT (Interpreted as Europe/London)

Window 10 Google Chrome browser

**Comment by EIJason** [comment]
![image](https://user-images.githubusercontent.com/55503152/71190976-72c52300-227d-11ea-9926-4ca5720922de.png)

**Comment by JediKev** [comment]
@EIJason 

I do not see the same issues with v1.14.1 and PHP 7.3. Is the file type allowed? What type of file is it? How are you attaching it (inline or file upload)? Do you have all of the PHP extensions installed/enabled on the server?

Cheers.

**Comment by JediKev** [comment]
The only way you get `Unable to save file` is if `AttachmentFile::create()` fails here:
### include/class.forms.php#L3686-L3687
```
         if (!$F = AttachmentFile::create($file))
             throw new FileUploadError(__('Unable to save file'));
```

Cheers.

**Comment by EIJason** [comment]
It does matter the type of file it seems to be happening on pdf, xls, png, jpg coming in from mail? could it be something with the database when upgrading from previous versions?

I did  a seperate test install and it seems to be working in the separate fresh install but that wasnt upgraded from a previous version?

**Comment by EIJason** [comment]
doesnt matter i mean?

**Comment by JediKev** [comment]
@EIJason 

I'd check the `AttachmentFile::create()` function to see where it's failing and go from there.

Cheers.

**Comment by EIJason** [comment]
Excuse my ignorance? no PHP errors are being thrown from what I can see, so how would i check that?

**Comment by JediKev** [comment]
@EIJason 

By doing `var_dump(something);` at the start of the function and working your way down by each line to see where it fails. Once you know where it fails you can keep tracing it back to the root of the issue.

Cheers.

**Comment by EIJason** [comment]
So it wouldnt be related to the database at all then? It could be code? so if i were to copy this file from my test installation it may fix it?

**Comment by protich** [comment]
I'll say check  Attachment Storage settings in Admin Panel. v1.14 fixed an issue where whitelisted file types weren't being enforced.

**Comment by EIJason** [comment]
![image](https://user-images.githubusercontent.com/55503152/71192270-da7c6d80-227f-11ea-805f-6bb1f66c5384.png)
that the only setting i can find for  attachments i deleted the file system storage attachment thingking it could be that?

**Comment by JediKev** [comment]
@EIJason 

He meant go to `Admin Panel > Settings > Tickets > Settings > Ticket Attachment Settings > Config`:
<img width="804" alt="Screen Shot 2019-12-19 at 10 53 10" src="https://user-images.githubusercontent.com/11823401/71192472-f6671b80-224d-11ea-843a-ccdc729a1dee.png">

Cheers.

**Comment by EIJason** [comment]
![image](https://user-images.githubusercontent.com/55503152/71192646-98076080-2280-11ea-81d6-d1cbbd3c50e2.png)
This looks ok right?

**Comment by JediKev** [comment]
@EIJason 

Yea looks fine to me. Can you try restoring from backup and re-applying the upgrade? Maybe the upgrade didn't go as it should've.

Cheers.

**Comment by EIJason** [comment]
I will lose allot of data? The upgrade didnt produce any errors it said it was fine? Ok so let me try trace this problem... restoring I will have allot of work to do following.... What if I copied all the files from the test installation over then it would be down to database issue right?

**Comment by EIJason** [comment]
![image](https://user-images.githubusercontent.com/55503152/71193275-c174bc00-2281-11ea-90cd-31fc911c4c9f.png)
I cant find the function defination in this file? this is the only occurance of it? To to that var dump, I should add it to the function right?

**Comment by JediKev** [comment]
@EIJason 

Backup your production files to a safe location, copy over all files from your test install (minus the config file of course and attachment folder [if you have it configured]) to the production location. Then copy over your production config and see if this works. If so then most likely you didn't have all the new files copied over.

Cheers.

**Comment by EIJason** [comment]
I think it may be related to disabling the inline attachment plugin after using it? I enable or the plugins again and that fixed those....

**Comment by EIJason** [comment]
Enabled all attachment plugins including store attachements on file system.... and view inline attachments...

**Comment by JediKev** [comment]
@EIJason 

"Inline attachment plugin" is not a core plugin so please raise the issue with the plugin developer. Inline attachments are supported in the system already so not sure why you would need that plugin?

Cheers

**Comment by EIJason** [comment]
Actually I assumed it was fixed but still note working, 

I use inline attachments so i can view the documents in the stream like pdf's excel word etc... if needed without having to open the app...

**Comment by EIJason** [comment]
I also copied the test files accross then copied the production config file that changed nothing... adding the plugins back fixed the sending of attachments, but recieving via mail still producing that error... Ok so i need to do the var dump the error has to be in the database somewhere? Or could it be somewhere else?

**Comment by ntozier** [comment]
I think what @JediKev is saying is disable the 3rd party plugin [inline attachment plugin]and see if you still have a problem.

**Comment by EIJason** [comment]
i did I even disabled it and that didn't change a thing then I deleted all the plugins that didn't change a thing.... So not sure what else it could be, must be something in the database... I tried to actually clear the cache also... but that didn't fix anything... I will do some more testing...

**Comment by EIJason** [comment]
If you have any suggestions let me know  ;)

**Comment by EIJason** [comment]
Good morning so it looks like attachments coming in are not working on the fresh installation too...
So i thought maybe a php version problem so i downgraded to 5.6 and still no success. Our hosting service has php7.4 now tried upgrading to that... then replies from osticket produce an HTTP 500 error and dont work so back to PHP 7.3 trying to get an error somewhere out of the system but I cant seem to get errors, I even tried marking the attachment directory with 777 permission to see if that helps... I am at a loose end here? Point me in the direction of how i can diagnose this problem? I will try that Var Dump but where can I put this, not sure where the definition of the function and class declaration is?

**Comment by EIJason** [comment]
Profit by Agent.xlsx: Project-Id-Version: osticket-official
X-Osticket-Major-Version: 1.10
POT-Create-Date: 2019-02-06 20:46 +0000
Report-Msgid-Bugs-To: support@osticket.com
Language: en_GB
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
X-Generator: crowdin.com
Plural-Forms: nplurals=2; plural=(n != 1);
X-Crowdin-Project: osticket-official
X-Crowdin-Language: en-GB
X-Crowdin-File: /1.11.x/LC_MESSAGES/messages.po
Last-Translator: greezybacon <jared>
Language-Team: English, United Kingdom
PO-Revision-Date: 2019-02-06 21:45</jared>

That a Var Dump of the file that failed to upload from incoming email...

**Comment by EIJason** [comment]
Ok so what I thought i would do is install a brand new version clean version of osticket 1.14.1 

And guess what the attachments fail coming in from emails? Any Ideas what the problem could be?

So we have illuminated it being the upgrade no completing correctly? could it be something to do with the Imap logon that has a slash in the username, How do you get the attachment from the Imap?

**Comment by JediKev** [comment]
@EIJason 

>could it be something to do with the Imap logon that has a slash in the username

No, as you're able to fetch mail..

>How do you get the attachment from the Imap?

You are getting the attachment from IMAP as you get `Unable to save file` error..

>And guess what the attachments fail coming in from emails? Any Ideas what the problem could be?

Can you post an example email? It has to be the full RAW email including headers. This way I can pipe it and try to replicate the issue.

Cheers.

**Comment by JediKev** [comment]
@EIJason 

Also, try to apply these changes and see if this addresses the issue:
- https://github.com/osTicket/osTicket/pull/5293

Cheers.

**Comment by EIJason** [comment]
Received: from SrvCSExchMB03.cloudserv.pro (172.16.10.63) by
 SrvCSExchMB03.cloudserv.pro (172.16.10.63) with Microsoft SMTP Server
 (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256) id 15.1.1466.3
 via Mailbox Transport; Fri, 20 Dec 2019 15:48:54 +0000
Received: from SrvCSExchMB03.cloudserv.pro (172.16.10.63) by
 SrvCSExchMB03.cloudserv.pro (172.16.10.63) with Microsoft SMTP Server
 (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256) id
 15.1.1466.3; Fri, 20 Dec 2019 15:48:54 +0000
Received: from SrvCSExchMB03.cloudserv.pro ([fe80::f9f3:d379:8471:62ca]) by
 SrvCSExchMB03.cloudserv.pro ([fe80::f9f3:d379:8471:62ca%5]) with mapi id
 15.01.1466.012; Fri, 20 Dec 2019 15:48:54 +0000
Content-Type: application/ms-tnef; name="winmail.dat"
Content-Transfer-Encoding: binary
From: Jason Kisogloo <jason@europeincoming.co.uk>
To: Support EI <support@europeincoming.co.uk>
Subject: Test Email
Thread-Topic: Test Email
Thread-Index: AdW3TNytgjE/UeJrSUuETUjI4MTeSQ==
Date: Fri, 20 Dec 2019 15:48:54 +0000
Message-ID: <b0ca72086b9f45cead8f7d288551ff88@europeincoming.co.uk>
Accept-Language: en-GB, en-US
Content-Language: en-US
X-MS-Has-Attach: yes
X-MS-Exchange-Organization-SCL: -1
X-MS-TNEF-Correlator: <b0ca72086b9f45cead8f7d288551ff88@europeincoming.co.uk>
MIME-Version: 1.0
X-MS-Exchange-Organization-MessageDirectionality: Originating
X-MS-Exchange-Organization-AuthSource: SrvCSExchMB03.cloudserv.pro
X-MS-Exchange-Organization-AuthAs: Internal
X-MS-Exchange-Organization-AuthMechanism: 04
X-Originating-IP: [172.22.0.40]
X-MS-Exchange-Organization-Network-Message-Id: ff7aaee4-5dda-46a6-4982-08d785641e49
Return-Path: jason@europeincoming.co.uk
X-MS-Exchange-Transport-EndToEndLatency: 00:00:00.3220693
X-MS-Exchange-Processed-By-BccFoldering: 15.01.1466.011

This is all i can get out of outlook...

**Comment by EIJason** [comment]
Applied those fixes no luck... still same problem...

**Comment by JediKev** [comment]
@EIJason 

>This is all i can get out of outlook...

Yea, that doesn't help..

>Applied those fixes no luck... still same problem...

So this has to be an environment issue then. I cannot replicate this at all. Have you tried a different server setup to see if it's something with your current setup?

Cheers.

**Comment by EIJason** [comment]
There was no issue in the v1.12 attachments were fine and nothing changed besides upgrading to 1.14

If you have an email address I can send the saved outlook file to you it wont allow me to upload it here?

Is there any PHP functions that may need to be unblocked or any apache modules that need to be added or anything like that?

Let me know an email address I can send that outlook file to maybe you can get more out of it...

**Comment by EIJason** [comment]
[RE osTicket Installed! #807196.zip](https://github.com/osTicket/osTicket/files/3989346/RE.osTicket.Installed.807196.zip)

**Comment by EIJason** [comment]
Thats the outlook file zipped if it helps?

**Comment by JediKev** [comment]
@EIJason 

I can't use `.msg`, can you convert that to `.eml` or download an `.eml`?

Cheers.

**Comment by EIJason** [comment]
[RE osTicket Installed! #807196 (2).zip](https://github.com/osTicket/osTicket/files/3989452/RE.osTicket.Installed.807196.2.zip)

**Comment by JediKev** [comment]
@EIJason 

That's not a real `.eml` file, it doesn't even contain the attachment.

Cheers.

**Comment by EIJason** [comment]
[RE osTicket Installed! #807196.zip](https://github.com/osTicket/osTicket/files/3989463/RE.osTicket.Installed.807196.zip)

**Comment by EIJason** [comment]
ok this should be had to use an online converter

**Comment by JediKev** [comment]
@EIJason 

Unfortunately, that's the same as the above. Just body text with no attachment and incomplete headers.

Cheers.

**Comment by JediKev** [comment]
@EIJason 

Please create a post of this on the Forum with a link back to here. This way we don't keep clogging up Github with debug stuff. When you create a post, put the link to it here.

Cheers.

**Comment by EIJason** [comment]
Hopefully this forward helps

...

**Comment by JediKev** [comment]
@EIJason 

That didn't contain an attachment so I removed it for you due to security reasons. Please refer to my comment above:
- https://github.com/osTicket/osTicket/issues/5292#issuecomment-568012301

Cheers.

**Comment by EIJason** [comment]
[Test Email.zip](https://github.com/osTicket/osTicket/files/3989512/Test.Email.zip)

**Comment by EIJason** [comment]
I created a link on the forum ;)
@JediKev 

https://forum.osticket.com/d/96568-attachments-sent-in-email-are-not-being-attached

Have you been able to find anything that could be causing the problem?

**Comment by EIJason** [comment]
@JediKev Need your help see forum

**Comment by JediKev** [comment]
@EIJason 

Is this resolved now as per the convo on the Forum? If so I will go ahead and close this. Also, if it is resolved it would be nice to share your fix here as well so others can benefit in the future.

Cheers.
