### ISSUE TITLE
Search suggestion box shouldn't be the default value when pressing enter.

### ISSUE THREAD

**Issue by Mike-Benoit** [osTicket/osTicket#5297]
### Description

When typing in the search box, as soon as the suggestion dropdown box appears the "Enter" key will automatically select the first value in that box, and apply it to the search field, removing what the user typed. 

This is especially confusing to users since often the suggestion box is completely different than what they were searching for. So pressing the "Enter" key ends up with vastly different results depending on many factors, including how fast or slow the suggestion box results are returned from the server.

### Steps to Reproduce

Issue 1:
  - Start typing "John" (without quotes) in the search box, then press enter really fast before the suggestion box appears (setting network conditions in the browser to slow 3g helps replicate this), and the search term will be what you expect "John".
  - However do the same thing, only wait for the suggestion box to appear, then press enter. This often results in some completely different search for the first result in the suggestion box that matches "John", which in our case is actually an email address that doesn't contain "John" anywhere in it whatsoever, and the search term gets changed to something like: "jdonavue@company.com". 

Combine this with users who may not touch-type, therefore they don't look at the screen when typing and its completely confusing since they type one thing and press enter, then look up to find the result is something completely different.

Issue 2:
  - Type "John Doe" (without quotes) into the search field, wait for the suggestion box to appear which often shows some completely unrelated term, then press enter. It switches the search term for the unrelated one. The only way to actually search for what you are typing once the suggestion box appears is to not use the enter key and instead click the magnify glass search icon.

**Expected behavior:** [What you expected to happen]

This is extremely unintuitive to the user, since I fail to find any mainstream search facility that defaults values to something other than what the user typed (ie: what appear in the suggestion box). Usually the user has to perform an additional action (click, tab, down arrow, etc...) to use the suggestion box value rather than the other way around. 

This problem is further exasperated by the fact that timing of the suggestion box can completely change behavior.

Unfortunately most of our users have completely given up on the search in osTicket since its so unpredictable as to what it may return. :(

### Versions
v1.12 on Ubuntu 18.04

**Comment by JediKev** [comment]
@Mike-Benoit 

This is due the typeahead suggestions. When pressing enter with the suggestions it will enter in on the first item. This is how the suggestion drop down works. When you press enter before the suggestions pop up it presses the search button which shows you search results. If you want it to search and not pull up the first result then click the Search icon.

Cheers.

**Comment by Mike-Benoit** [comment]
@JediKev Exactly my point, its unintuitive to the user and different than any other moderately popular search system out there, which users are comfortable with.

It would be one thing if the behavior was an improvement, but in the vast majority of cases its impossible for it to be an improvement, since the suggestion box results are extremely poor, especially when given things like email addresses. 

There is no scenario where a user searching for "john@company.com" (without quotes) actually intended to search for "jdonavue@someothercompany.com". Which is what they get more often than not in osTicket.
