### ISSUE TITLE
Ticket queue subject field empty if issue summary form field disabled

### ISSUE THREAD

**Issue by ca2kjet** [osTicket/osTicket#5298]
I'm not sure if this is a bug or the way it's meant to work going forward. 

After upgrading to 1.14.1 from 1.12.2 the ticket queue subject line was blank. I checked the queue settings and discovered the Primary Data Source drop down for the subject field was "none". I finally determined that if the Ticket Form > Ticket Details > Issue Summary field is disabled then it also disables the option from the queue sources. Now, that does make sense but without that enabled there's no way to display the subject from tickets created from e-mails nor is there way a to edit the subject line from e-mails.

I have not had the chance to do a fresh install of 1.14.1 to see if the issue exists from a non-upgrade. Hoping someone else can at least confirm that the same thing is happening to them. I've tested this in my production environment using 1.14.1 as well as a my test environment running the latest git download from develop-next.

**Comment by JediKev** [comment]
@ca2kjet 

Well, if the global Issue Summary field is disabled then not even emails would display a subject in the queue as the field is disabled. When we display the "subject" in the queue column we check to see if the form field (Issue Summary) is Enabled, if it's not Enabled then we don't display the value. If you had the field disabled for web forms and you didn't disable the global field then emails would show the Issue Summary. I will do some testing to confirm this though.

**Update:**
If you disable the field via web forms (ie. disable the field per Help Topic) tickets generated via Web (Client Portal) would show the Help Topic as the value in the column as Users cannot enter a value for it so it defaults to Help Topic. So basically, if you disable the global field nothing will show in the column. If you disable the field per Help Topic then tickets created via web shows Help Topic and tickets created via email would show the email's subject as the value.

Cheers.

**Comment by ca2kjet** [comment]
@JediKev 

That's how it was working in 2.12.2. In the ticket queue I could see the subject from an e-mail or the help topic (as the subject) from the submitted web form with the ticket issue summary field disabled.

However, in 2.14.1 the default option to display the subject field completely disappears from the available sources blanking out the default subject column. The only alternative is to choose help topic as the source. There's no way to see the e-mail subject and/or help topic on the queue anymore.

I haven't been able to track down what changed between the two versions that would be causing this.


**With the issue summary field enabled everything shows properly;**

![001](https://user-images.githubusercontent.com/38137333/71327679-5ae9db00-24d9-11ea-9ac9-203ec2dd73f7.png)
![002](https://user-images.githubusercontent.com/38137333/71327680-5ae9db00-24d9-11ea-8a6f-27d226d62191.png)


**With the issue summary field disabled the subject column goes blank;**

![003](https://user-images.githubusercontent.com/38137333/71327681-5ae9db00-24d9-11ea-8fbc-c5de53c884db.png)
![004](https://user-images.githubusercontent.com/38137333/71327682-5ae9db00-24d9-11ea-8b96-21222fab97eb.png)

**Comment by JediKev** [comment]
@ca2kjet 

Yes that’s how it functions. With the new queue system we check to see if the field's data source is enabled and if so we show the value or if it's disabled then we don’t show the value. You will have to Enable the global field in order to show values in the queue columns.

Cheers.

**Comment by ca2kjet** [comment]
@JediKev 

The global field you're referring to is under Ticket Details form, correct? Are there other locations to enable/disable the subject variable or is that the only place?

**Comment by ca2kjet** [comment]
I'm an idiot... I figured it out. I need to leave the default issue summary field on the forms enabled and then under Help Topics > "help topic title" > Forms > uncheck Issue Summary to disable the use of it on the form but not disable it globally.
