### ISSUE TITLE
Inline edit of Help Topic doesn't refresh Ticket Status options.

### ISSUE THREAD

**Issue by Mike-Benoit** [osTicket/osTicket#5316]
### Prerequisites

* [Yes] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [No] Do you have any errors in the PHP error log, or javascript console?
* [Yes] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [Yes] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

If you have the setting enabled that requires a help topic to be specified before a ticket can be closed, and you use the inline edit to set the help topic, you still can't close the ticket until you refresh the page. 

Unfortunately this makes the newly added feature of inline help topic selection (#4985) almost useless with this setting. Which means the user can easily lose their reply when they try to set the help topic without using inline edit, since the entire page is refreshed. :(

### Steps to Reproduce

1. Turn on "Require Help Topic to Close" setting.
2. Create ticket without help topic.
3. View ticket, notice the "This ticket is missing a Help Topic and cannot be closed" message at the bottom. Also any of the "Closed/Resolved" options aren't even available to select.
4. Using inline edit set a help topic.
4. Notice the Ticket Status dropdown box at the bottom doesn't show any options to close/resolve the ticket.

**Expected behavior:** [What you expected to happen]
When the help topic is updated, it should refresh the Ticket Status dropdown box and remove the warning message about no help topic being selected.

**Actual behavior:** [What actually happened]
See above steps to reproduce. 

### Versions
v1.14.1

**Comment by JediKev** [comment]
@Mike-Benoit 

Thank you for the report. We will do some testing and attempt to replicate the issue.

Cheers.

**Comment by JediKev** [comment]
@Mike-Benoit 

This should address your issue:
- https://github.com/osTicket/osTicket/pull/5322

Cheers.

**Comment by Mike-Benoit** [comment]
We recently pulled develop-next and this bug seems to have appeared again. I manually checked the files and the code is definitely there. Are you able to replicate this bug again?
