### ISSUE TITLE
Merging tickets doesn't play nice with "Require Help Topic to Close" 

### ISSUE THREAD

**Issue by Mike-Benoit** [osTicket/osTicket#5317]
### Prerequisites

* [Yes] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [No] Do you have any errors in the PHP error log, or javascript console?
* [Yes] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [Yes] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

Merging tickets doesn't handle "Require Help Topic to Close"  properly if there is no help topic specified.

### Steps to Reproduce

1. Enable "Require Help Topic to Close" 
2. Create a parent ticket, and specify the help topic.
3. Create a new ticket without a help topic.
4. Merge the new ticket (without a help topic) to the parent ticket, and when doing so, set the "Child Status" dropdown box to "Resolved". 

**Expected behavior:** [What you expected to happen]
Child ticket should be resolved, or the user should be prompted that they can't change the status on the child ticket without setting a help topic before the changes are saved.

Personally since the child ticket is being merged anyways, I think it should force the ticket status to resolved regardless of the Help Topic not being specified, since the parent help topic is going to be the more useful one anyways. My understanding is the only reason to keep the child ticket around is to route new replies to it to the parent ticket.

**Actual behavior:** [What actually happened]
Child ticket is not resolved.

### Versions
v1.14.1

**Comment by JediKev** [comment]
@Mike-Benoit 

This should resolve your issue:
- https://github.com/osTicket/osTicket/pull/5321

Cheers.
