### ISSUE TITLE
HELP!!! Crypto Malware attack damage helpdesk Attachments

### ISSUE THREAD

**Issue by philbertphotos** [osTicket/osTicket#5323]
I need help from the devs ... Ticket system was compromised.  We did get the system back up and all is working (we had a database backup) but no attachments. We can live with that but the issue is that now the logs and emails get full with attachment not found errors.

I wondering is there a way to replace all attachments with dummy default files/images?  I just need some direction in how I would accomplish this I can code something only own.

**Comment by protich** [comment]
How was it compromised? You can shoot me an email at peter -at- osticket.com if you prefer private channel.

**Comment by ntozier** [comment]
@philbertphotos 
> I wondering is there a way to replace all attachments with dummy default files/images?
I can think of two ways to alleviate this.

The first (and easiest) would be to drop the contents of the ost_attachment, ost_file, and ost_file_chunk tables.  This may have the undesirable effect of nuking your custom images, so make sure that you back them up so you can re-add them.

note: you can look at the ost_attachment table and see any object id 0 and not nuke it or the corresponding entry in the ost_file table with the id=object_id.

The second [ONLY if you are storing attachments/file on the filesystem via the Attachment::Filesystem plugin] is to write a script that reads the ost_file table key column and have it re-create the folder and file structure. [note: I have not dug into this a lot so I could be mistaken!!!] I think that the key field first letter is the name of the folder, and the full key field is the name of the file.

@jediKev please correct me if I am wrong in any of this.
