### ISSUE TITLE
Message and activity alert notification e-mails not sending to agents

### ISSUE THREAD

**Issue by DoctorOctagonapus** [osTicket/osTicket#5338]
### Description

Logging a new message or internal note on a ticket assigned to an agent does not send an e-mail notification to the agent. Other e-mails are sending correctly (new ticket e-mails, e-mails to users, etc.), as are e-mails sent through the built-in mail test tool. It's as though they've been disabled in Alerts and Notices.

### Steps to Reproduce

1. Have open ticket assigned to agent
2. Either the user or another agent logs a message or internal note on that ticket

**Expected behavior:** [What you expected to happen]
Alert sent over e-mail to the assigned agent with either a new message alert or new internal activity alert

**Actual behavior:** [What actually happened]
Activity/message is logged in the ticket but no message is ever sent. No errors logged.

### Versions
osTicket Version: 1.14.1, though problem also observed in 1.12.3

![osticketversion](https://user-images.githubusercontent.com/6576477/72433958-68ba1580-3792-11ea-9fa3-edc1e555fd0f.PNG)

Server OS: Windows Server 2016

**Comment by JediKev** [comment]
@DoctorOctagonapus 

So, if a New Message from the Enduser is added to a ticket the Alert setting responsible for this is called **New Message Alert**. If an Internal Note or Reply is added to a ticket the Alert setting responsible for these is called **New Internal Activity Alert**. Both of these settings can be found under **Admin Panel > Settings > Tickets > Alerts & Notices**.

If you have this setup properly and the Assigned Agent is still not receiving New Message Alerts, there are a few places to check. Under **Admin Panel > Agents > Agents > click an Agent > Access** you will see Alert checkboxes next to each Department, make sure these are Enabled. Next, you can check a specific Department under **Admin Panel > Agents > Departments** and see if **New Message Alert** is Disabled there as well. Lastly, you can check the Department's **Alerts and Notices** dropdown on the same page and ensure it's being sent to **Primary and Extended Access Members**. If this is set to **No One** then no one will receive alerts, if set to **Admin Email** only the Admin will get Alerts, if set to **Primary Members** then only Primary Members will receive alerts, and if set to **Primary and Extended Access Members** then all Agents that have access to the Department will receive alerts.

I hope this clears things up for you.

Cheers.

**Comment by DoctorOctagonapus** [comment]
Hey thanks for that. I've checked all those sections and everything's set to enabled as you described. Still no e-mails though.

**Comment by JediKev** [comment]
@DoctorOctagonapus 

Have you checked the templates themselves to see if there is something in them causing them to fail and not send? Things such as broken images, etc.

Try creating a new template set, make sure Template Set to Clone is set to `-- Stock Templates --` set, make this new template set the default for a Department, and retest.

Cheers.

**Comment by DoctorOctagonapus** [comment]
Hm that's a thought, I'll have to check them. Would there be anything logged anywhere if there was an element in one of the templates that was causing it to break?

**Comment by DoctorOctagonapus** [comment]
Hi I've found the problem. For those with the same problem when updating from 1.12.x to 1.14.1, some of the template variables have changed. Here are the ones I had to change to get our install to work:

- %{ticket.name} is now %{ticket.user}
- %{ticket.dept.name} is now %{ticket.dept}
- %{note.message} is now %{note}

I'll say this though, it's a bit rubbish that it doesn't seem to log anything anywhere unless I've missed something. Maybe it's the fact that we use SMTP rather than php_mail.

**Comment by DoctorOctagonapus** [comment]
OK I was wrong. Reopening because I've discovered today that e-mails for those two templates have once again stopped.

To summarise: the server can definitely e-mail, as all other e-mails are being sent except for New Message Alerts and New Internal Activity Alerts to agents. For these, the server doesn't appear to make any attempt to send any e-mails. Nothing reaches our Exchange server, no errors are logged anywhere. Everything is enabled in the relevant sections of the Admin panel, but the server appears to be ignoring those settings.

**Comment by JediKev** [comment]
@DoctorOctagonapus 

So, you checked all the relevant settings in _each_ Department's Settings and Access tabs? Did you also ensure each Department's Alert & Notices Recipients is set appropriately? Did you clone the Stock Templates and use those to test with to ensure the issue occurs with stock templates? I cannot replicate this issue at all so it has to be a setting you're missing somewhere.

Cheers.

**Comment by harbpaul** [comment]
I'm having the same problem.  If I set the DEFAULT ALERT EMAIL to "Use Default System Email (above)" it works fine.  If I use any other email, it doesn't work.  The other emails work fine when I try them with the Diagnostic Tool.
