### ISSUE TITLE
Merged tickets, but not all thread entries displayed.

### ISSUE THREAD

**Issue by Mike-Benoit** [osTicket/osTicket#5339]
### Prerequisites

* [Yes] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [No] Do you have any errors in the PHP error log, or javascript console?
* [Yes] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [Yes] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

We have a case where we took a parent ticket, and merged two child tickets into it, one at a time. When viewing the parent ticket, the "Related Tickets" tab shows the two child tickets correctly merged, but the thread entries only display from the parent and the 1st child ticket, not the 2nd child ticket. 

### Steps to Reproduce

**We are unable to reproduce this consistently yet, it seems to only happen sporadically.

1. Create parent ticket.
2. Merge 1st child ticket to parent.
3. Merge 2nd child ticket to parent (2nd child ticket does have two attachments, not sure if that makes any difference). 
4. View parent ticket, Related Tickets tab should show both child tickets, and it should display thread entries from all three tickets.

Its parent ticket #298159 on our end that is exhibiting this behavior. Since every time we display the parent ticket its not showing all the thread entries, is there any debugging we could do on our end to help determine what may be going on here?

### Versions
v1.14.1

**Comment by aydreeihn** [comment]
What type of environment is your helpdesk running on? You can see the details of what I'm testing on below from Admin Panel | Dashboard | Information.

<img width="807" alt="Screen Shot 2020-01-15 at 2 10 19 PM" src="https://user-images.githubusercontent.com/22985133/72467623-eb49d180-37a0-11ea-98ac-c757af2ae1eb.png">

My test results:

<img width="966" alt="Screen Shot 2020-01-15 at 2 12 07 PM" src="https://user-images.githubusercontent.com/22985133/72467675-0ddbea80-37a1-11ea-9d02-369eda7b5a61.png">

**Comment by Mike-Benoit** [comment]
![osticket_system_info](https://user-images.githubusercontent.com/4147850/72469546-7b354e80-3794-11ea-9336-57e93f13edba.png)

Just throwing this out there, while the tickets are different I wonder if its somehow related to this:
https://forum.osticket.com/d/96658-can-t-view-new-tickets-after-upgrade-to-v1-14-1/4

**Comment by aydreeihn** [comment]
Out of curiosity, which commit is your codebase on? Have you tried refetching the latest code? Or do you have customizations in your codebase? Just trying to narrow down why you're seeing so many differences in your instance compared to ours.

**Comment by Mike-Benoit** [comment]
We do have some customizations, but mostly adding signals for a plugin and improving the search/typeahead find functionality to be significantly more useful and consistent. 

We use the develop-next branch from our own Github fork, so you can see the exact differences here: https://github.com/osTicket/osTicket/compare/develop-next...Mike-Benoit:develop-next

If it helps at all, since the upgrade to v1.14 we have been going back and merging historical tickets to the tune of about 50-100 per day, so we are exercising the functionality quite a lot.

**Comment by Mike-Benoit** [comment]
Haven't seen this issue for a while, my best guess it was related to: #5379
