### ISSUE TITLE
[Feature Request] Clean HTML structure and classes to allow theme customization

### ISSUE THREAD

**Issue by ghost** [osTicket/osTicket#5342]
There is already a plan to make osTicket themeable from version 2 on, as I read a few times in the official [osTicket forum](https://forum.osticket.com).

That is something that will take a lot of efforts, and I strongly believe that until this is implemented, a clean approach to allow better customization is to clean the HTML structure and classes in the current version (maybe following [BEM pattern](http://getbem.com/introduction/) or whatever similar alternative).

Currently, there are some available Responsive "themes" that are in fact a modified version of the original osTicket.

But no good option is available for the recent version (1.14.1) for free.

I tried to make the current version responsive without touching the core PHP files, just by editing the theme.css file and nothing else, and already managed to get a [clean and responsive theme ](https://github.com/alvarofranz/osTicketResponsiveTheme/)(which I will be updating during the following times).

This is something that could be done without loads of complex efforts, and I myself could help with it.

**Comment by JediKev** [comment]
@alvarofranz 

We are holding the theme-ability and responsiveness for v2.0 as we are completely switching the front end/backend code. We aren’t going to make huge theme changes to the legacy codebase as it will be implemented with v2.0.

Cheers.

**Comment by ghost** [comment]
@JediKev Perfect. In that case I will keep modifying the current theme.css file and upload it for those who want the current version to be responsive. Really appreciate your effort and amazing work.

All the best.
