### ISSUE TITLE
edit overdue ticket in database

### ISSUE THREAD

**Issue by malikymarn** [osTicket/osTicket#5343]
Hello guys

Please help me
I want to edit the database in the table which contains overdue tickets,

so mean that when it has done it will affect to the dashboard of Osticket in UI interface

Thank for your response

**Comment by JediKev** [comment]
@malikymarn 

This is a question that is best suited for our Community Supported [Forum here](https://forum.osticket.com). Please open a discussion there asking the same question.

For future reference, if you want to ask questions please go to the Forum. If you want to report a bug or submit a Feature Request then you use Github.

Cheers.

**Comment by malikymarn** [comment]
oh Understand thank you

Best,
