### ISSUE TITLE
DB Error #1054

### ISSUE THREAD

**Issue by stultitiophobia** [osTicket/osTicket#5344]
Hi !
My Log is flooded by these entries:
I searched a few issues and found "delete queue id 15" but is this the same here ?

[SELECT COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A1.`team_id` = 0 AND A1.`staff_id` = 0 THEN A1.`ticket_id` END) AS `q7`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A1.`staff_id` IN (31) THEN A1.`ticket_id` END) AS `q9`, COUNT(DISTINCT CASE WHEN B4.`server` LIKE '%*%' THEN A1.`ticket_id` END) AS `q12`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A2.`state` = 'open' AND A2.`id` IN (7) AND A3.`object_type` = 'T' THEN A1.`ticket_id` END) AS `q13`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A1.`staff_id` IN (3) AND A1.`created` BETWEEN '2019-01-01 00:00:00' AND '2019-12-31 23:59:59' THEN A1.`ticket_id` END) AS `q20`, COUNT(DISTINCT CASE WHEN A1.`ticket_id` = Z1.`ticket_id` THEN A1.`ticket_id` END) AS `q21`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A2.`state` = 'open' AND A2.`id` IN (8) AND A3.`object_type` = 'T' THEN A1.`ticket_id` END) AS `q22`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A2.`state` = 'open' AND A1.`dept_id` = 6 AND A3.`object_type` = 'T' THEN A1.`ticket_id` END) AS `q26`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A1.`staff_id` IN (12) THEN A1.`ticket_id` END) AS `q31`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A1.`staff_id` IN (31) AND A1.`created` BETWEEN '2018-01-01 00:00:00' AND '2018-12-31 23:59:59' THEN A1.`ticket_id` END) AS `q32`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A1.`staff_id` IN (31) AND A1.`created` BETWEEN '2019-01-01 00:00:00' AND '2019-12-31 23:59:59' THEN A1.`ticket_id` END) AS `q33`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A1.`staff_id` IN (3) AND A1.`created` BETWEEN '2019-01-01 00:00:00' AND '2019-12-31 23:59:59' THEN A1.`ticket_id` END) AS `q34`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A3.`object_type` = 'T' THEN A1.`ticket_id` END) AS `q1`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A2.`state` = 'open' AND A2.`state` = 'open' AND A1.`team_id` = 0 AND A1.`staff_id` = 0 AND A3.`object_type` = 'T' THEN A1.`ticket_id` END) AS `q8`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A2.`state` = 'open' AND A1.`isanswered` = '1' AND A3.`object_type` = 'T' THEN A1.`ticket_id` END) AS `q2`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A2.`state` = 'open' AND NOT (A1.`team_id` = 0 AND A1.`staff_id` = 0) AND A3.`object_type` = 'T' THEN A1.`ticket_id` END) AS `q5`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A2.`state` = 'open' AND A1.`isoverdue` = '1' AND A3.`object_type` = 'T' THEN A1.`ticket_id` END) AS `q6`, COUNT(DISTINCT CASE WHEN (A1.`team_id` IN (4) OR A1.`staff_id` IN (31)) AND A2.`state` = 'open' AND A3.`object_type` = 'T' THEN A1.`ticket_id` END) AS `q3`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A3.`object_type` = 'T' THEN A1.`ticket_id` END) AS `q4` FROM `ost_ticket` A1 JOIN `ost_ticket_status` A2 ON (A1.`status_id` = A2.`id`) LEFT JOIN `ost_thread` A3 ON (A3.`object_type` = 'T' AND A1.`ticket_id` = A3.`object_id`) LEFT JOIN `ost_thread_referral` A4 ON (A3.`id` = A4.`thread_id`) LEFT JOIN `ost_staff` A5 ON (A4.`object_type` = 'S' AND A4.`object_id` = A5.`staff_id`) LEFT JOIN `ost_thread` A6 ON (A1.`ticket_id` = A6.`object_id` AND A6.`object_type` = 'C') LEFT JOIN `ost_thread_referral` A7 ON (A6.`id` = A7.`thread_id`) LEFT JOIN `ost_staff` A8 ON (A7.`object_type` = 'S' AND A7.`object_id` = A8.`staff_id`) LEFT JOIN `ost_team` B0 ON (A4.`object_type` = 'E' AND A4.`object_id` = B0.`team_id`) LEFT JOIN `ost_team` B1 ON (A7.`object_type` = 'E' AND A7.`object_id` = B1.`team_id`) LEFT JOIN `ost_department` B2 ON (A4.`object_type` = 'D' AND A4.`object_id` = B2.`id`) LEFT JOIN `ost_department` B3 ON (A7.`object_type` = 'D' AND A7.`object_id` = B3.`id`) LEFT JOIN `ost_ticket__cdata` B4 ON (A1.`ticket_id` = B4.`ticket_id`) WHERE ((A2.`state` = 'open' AND (A1.`staff_id` = 31 OR A5.`staff_id` = 31 OR A6.`object_type` = 'C' AND A8.`staff_id` = 31 OR A1.`team_id` IN (4) OR B0.`team_id` IN (4) OR A6.`object_type` = 'C' AND B1.`team_id` IN (4))) OR (A2.`state` IN ('open', 'closed') AND (A1.`dept_id` IN (1, 6) OR B2.`id` IN (1, 6))) OR A6.`object_type` = 'C' AND B3.`id` IN (1, 6))] Unknown column 'Z1.ticket_id' in 'field list'

**Comment by ntozier** [comment]
This is a question that is best suited for our Community Supported Forum [here](https://forum.osticket.com/). For future reference, if you want to ask questions please go to the Forum. If you want to report a bug or submit a Feature Request then you use Github.

That being said your error corresponds to here:
`COUNT(DISTINCT CASE WHEN A1.ticket_id = Z1.ticket_id THEN A1.ticket_id END) AS **q21**`

So you would want to look at the queue 21 make note of what it does and delete it.

Please close this issue report.

**Comment by stultitiophobia** [comment]
Thanks a lot, that was the issue !
