### ISSUE TITLE
Double quotes in name clear email field

### ISSUE THREAD

**Issue by djohnson1865** [osTicket/osTicket#5345]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

Adding Quotes in a name causes the email address for a user to disappear. 

### Steps to Reproduce

1. Add user with name including quotes and email address example: firstname "nickname" lastname
2. Save user

**Expected behavior:**
I would expect the email address to show up appropriately.

**Actual behavior:**
The email address shows up as '@'

### Versions
Reproduced in both OSTicket 1.12.2 and OSTicket 1.14.1

Seems to be browser agnostic in my testing. 

In addition, escaping the quotes as in 'firstname \"nickname\" lastname' prevents the bug. But the name shows the escape characters.

**Comment by JediKev** [comment]
@djohnson1865 

Thanks for the report. We will look into this.

Cheers.

**Comment by JediKev** [comment]
@djohnson1865 

Here you go:
- https://github.com/osTicket/osTicket/pull/5395

Cheers.
