### ISSUE TITLE
Custom Fields with checkboxes can't be unchecked (Previously Fixed)

### ISSUE THREAD

**Issue by gitsnow** [osTicket/osTicket#5346]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [X] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [X] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

Unable to uncheck checkbox on custom fields

### Steps to Reproduce

1. Add Custom Field with type checkbox to any form
2. Edit the form field and check the checkbox and Save.
3. Edit the form field again, uncheck the field and try to Save. You will receive an error that the field "is already assigned this value". 

**Expected behavior:** Field should be unchecked

**Actual behavior:** Field errors out

### Versions
osTicket Version | v1.14.1 (f1e9e88)
Web Server Software | nginx/1.17.3
MySQL Version | 10.4.11
PHP Version | 7.4.1
Ubuntu 18.04

This is a bug that was reported and fixed in previous versions, but the old fix no longer works in version 1.14

[Previous Ticket #4782](https://github.com/osTicket/osTicket/issues/4782)

**Comment by gitsnow** [comment]
Wondering if anyone has had time to look at this issue?

**Comment by JediKev** [comment]
@gitsnow 

Not yet, but we'll get to it in time.

Cheers.

**Comment by gitsnow** [comment]
No prob.  Thanks for the update

**Comment by JediKev** [comment]
@gitsnow 

I just noticed that you are using PHP v7.4 which we haven't even looked at yet so it might be incompatible. For now, I'd suggest retesting this with PHP 7.0-7.3 and confirming this is an issue with supported versions.

Cheers.

**Comment by gitsnow** [comment]
I downgraded my test site to PHP 7.3 and I'm still unable to uncheck a custom checkbox field.

**Comment by JediKev** [comment]
@gitsnow 

Yea I was able to replicate it a little after my post. We are working on it.

Cheers.

**Comment by JediKev** [comment]
@gitsnow 

Here you go:
- https://github.com/osTicket/osTicket/pull/5380

Cheers.
