### ISSUE TITLE
Reset Dashboard Ticket Activity

### ISSUE THREAD

**Issue by josehizon** [osTicket/osTicket#5347]
Hi guys,

I just tested osticket and I want to reset the dashboard and statistics back to zero. How can I do that? Thank you.

**Comment by ntozier** [comment]
This is not a bug/issue report.  Please post general questions on the forums instead.

That being said please see:
https://forum.osticket.com/d/93048-reset-dashboard-stats
https://forum.osticket.com/d/94088-reset-dashboard-back-to-zero

Please close this issue report.
