### ISSUE TITLE
Ticket creation not adding collaborators

### ISSUE THREAD

**Issue by bertaviader** [osTicket/osTicket#5352]
### Prerequisites

* [Y] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [N] Do you have any errors in the PHP error log, or javascript console?
* [Y] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [Y] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

When the ticket is created via email and the email arrive directly to the mailbox configured in the instance, the ticket adds correctly the collaborators. But if the ticket, it's exported from another mailbox to the mailbox configured, the collaborators are not added, although they are on the TO: field.

### Steps to Reproduce

1. Send an email to the mailbox not configured on ostickets. The mail has other senders in the TO field.
2. Put this email to the other mailbox, the one configured on osticket, manually. 

**Expected behavior:** 
The ticket is created and the collaborators are added. 

**Actual behavior:** 
The ticket is created, but the collaborators are not added

### Versions

![72533948-4e596800-3876-11ea-8a32-13df4aef6bf1](https://user-images.githubusercontent.com/18306366/73271832-9d41be80-41e1-11ea-85c1-a3f63930fb4f.png)

Ubuntu 16.04
Chrome Version 65.0
Firefox 72.0.1

**Comment by ntozier** [comment]
Senders in the To field do not matter for adding collaborators.  The From and CC are the important fields.

If the FROM address is not a user depending on how you have User registration configured it will reject the ticket or accept it.  It sounds like you require people to register before opening a ticket.

If a ticket is created (based on above) then it will add the CC users as Collaborators.

**Comment by bertaviader** [comment]
Thanks for the quick response!
We will try it with the CC field, rather the TO.
Thanks again I will close the issue then.

**Comment by bertaviader** [comment]
I really wanted to close this, but with CC is happening the same.
I'm guessing that the Delivered-To field in the headers, must be the same as the mailbox configured in the instance to work properly.

I was searching for the code that parse the collaborators, can you help me? Maybe I can understand better why the collaborators are not added when we move the mail from another mailbox to the one configured in the instance. 

Thanks a lot,
Berta

**Comment by ntozier** [comment]
If the FROM is not a valid user and you require registration to open a ticket, it will reject the ticket.

The TO does not matter as it will be the ticket system.

**Comment by bertaviader** [comment]
The FROM it's a valid user, the ticket is created, the problem is that the collaborators are not added.

**Comment by ntozier** [comment]
And the CC people are also valid users?

**Comment by bertaviader** [comment]
Yes, are guest users.

**Comment by JediKev** [comment]
@bertaviader 

Okay, so, add whatever email address the emails arrive to _originally_ as a System Email under **Admin Panel > Emails > Emails > Add New Email**. All you have to do is add the email, do not configure IMAP/SMTP, just add the email.

The issue is the `Delivered-To` is not a system email hence the system doesn't know where or how the email arrived in the mailbox. With that being said, in order to prevent loops, etc. we drop all recipients except the original sender (`From:`).

**Edit:**
The code for this is here:
- https://github.com/osTicket/osTicket/blob/develop/include/class.ticket.php#L2728-L2733

Cheers.

**Comment by bertaviader** [comment]
Okay, thanks!
