### ISSUE TITLE
Client get's wrong link to activate account

### ISSUE THREAD

**Issue by mrEckendonk** [osTicket/osTicket#5355]
### Prerequisites

* [X] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [X] Do you have any errors in the PHP error log, or javascript console?
* [X} Did you check the [osTicket forums](https://forum.osticket.com/)?
* [X] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description
Client gets wrong link to activate account

### Steps to Reproduce

1. New client creates ticket
2. New client receives email
3. New client creates account and receives email with wrong link to activate account (has to remove first part of link)

**Expected behavior:** [What you expected to happen]
https://ticket.domain.com/pwreset.php?token=Cx01uXiRBPMJrYIU0MTc8g3PXvYGHZCBNmd2vhxAoNae8ZfO
**Actual behavior:** [What actually happened]
https://ticket.comdain.com/scp/https://ticket.domain.com/pwreset.php?token=Cx01uXiRBPMJrYIU0MTc8g3PXvYGHZCBNmd2vhxAoNae8ZfO
### Versions

Server Information
--
osTicket Version | v1.14.1 (f1e9e88) —  Up to date
Web Server Software | nginx/1.17.8
MySQL Version | 10.3.22
PHP Version | 7.4.2

** APCu | Improves overall performance (great pref. without)

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

Centos 7.7 x64

**Comment by ntozier** [comment]
Sounds like your email template for that item is incorrect.

Go to: 
**Admin panel -> Settings -> Users**
Click on the Templates tab.
Click on Account Confirmation Email.

It should look like this
![2020-01-30_0934](https://user-images.githubusercontent.com/1315768/73458774-cbd7aa80-4343-11ea-9722-8754036c0247.png)

Also this question appears to be better suited for the Forums.  Please ask questions on the forums.  Github is for reporting bugs.

**Comment by mrEckendonk** [comment]
Don't know if it's a bug, but I keep getting a strange result thge URL* Link turns to %%7Blink%7D
![github131](https://user-images.githubusercontent.com/30936842/73473670-e1f96100-436b-11ea-88fe-6d691e58249b.png)

**Comment by mrEckendonk** [comment]
Fixed

**Comment by mrEckendonk** [comment]
Selecting %{link} instead of edit link was the fix
