### ISSUE TITLE
Blank Pop up boxes on NGINX

### ISSUE THREAD

**Issue by unixbird** [osTicket/osTicket#5363]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

When adding users I get a blank pop up boxes. 

### Steps to Reproduce
Highlight any of the help boxes and they're blank same with adding a password to a user or when you click new ticket

### Versions
Running this on Turnkey GNU/Linux debian Stretch 9.11
PHP 7.0
NGINX
OsTicket 1.14.1

I have read the fixes with Nginx you need to have osticket running but I can't seem to get them working. 

Here is my code: https://pastebin.com/1Par26ap

**Comment by JediKev** [comment]
@unixbird 

osTicket doesn't officially support NGINX so this could be part of the reason. If you must use NGINX with osTicket you'll have to do some extra configurations in the NIGNX conf file. Here is a good guide to get you started:
- https://www.nginx.com/resources/wiki/start/topics/recipes/osticket/

Cheers.

**Comment by unixbird** [comment]
I actually followed that and it always errors out saying certain elements aren't supposed to be there. If you look at my config I actually have most of that recipe inside of it

**Comment by JediKev** [comment]
@unixbird 

Using osTicket v1.14.1 with PHP 7.3 and Apache works just fine for me. Maybe there are some extra configs for NGINX you must apply before AJAX works properly? The Help Tips use AJAX requests to retrieve the tip contents so I do believe AJAX is not working as it should be.

Cheers.

**Comment by unixbird** [comment]
@JediKev I wouldn't be sure where to start. I've exhausted pretty much all solutions people have found on here and none of them seem to work for me

**Comment by guidokuehler** [comment]
The Config below work on our Systems with OsTicket 1.14.1, PHP7 and NGINX. 

Please look the red part is different from yours! 

--------------- 

set $path_info ""; 

location ~ /include { 
deny all; 
return 403; 
} 

if ($request_uri ~ "^/api(/[^\?]+)") { 
set $path_info $1; 
} 

location ~ ^/api/(?:tickets|tasks).*$ { 
try_files $uri $uri/ /api/http.php?$query_string; 
} 

if ($request_uri ~ "^/scp/.*\.php(/[^\?]+)") { 
set $path_info $1; 
} 

if ($request_uri ~ "^/*\.php(/[^\?]+)") { 
set $path_info $1; 
} 

location ~ ^/scp/ajax.php/.*$ { 
try_files $uri $uri/ /scp/ajax.php?$query_string; 
} 

location ~ ^/ajax.php/(.*)$ { 
try_files $uri $uri/ /ajax.php?query_string; 
} 

location / { 
try_files $uri $uri/ index.php; 
} 

location ~ \.php$ { 
fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name; 
include fastcgi_params; 
fastcgi_param PATH_INFO $path_info; 
# PHP 7 
fastcgi_pass 127.0.0.1:9007; 
} 



Best Regards 
Guido 


Von: "JediKev" <notifications@github.com> 
An: "osTicket/osTicket" <osTicket@noreply.github.com> 
CC: "Subscribed" <subscribed@noreply.github.com> 
Gesendet: Mittwoch, 5. Februar 2020 16:53:08 
Betreff: Re: [osTicket/osTicket] Blank Pop up boxes on NGINX (#5363) 



@unixbird 

osTicket doesn't officially support NGINX so this could be part of the reason. If you must use NGINX with osTicket you'll have to do some extra configurations in the NIGNX conf file. Here is a good guide to get you started: 

    * https://www.nginx.com/resources/wiki/start/topics/recipes/osticket/ 



Cheers.

**Comment by unixbird** [comment]
I just quickly put up a new LAMP stack with osticket and it works now. I have some other issues with apache indexing but I will see if I can fix that myself before making another issue. Thanks for the help everyone!

**Comment by danielrussob** [comment]
This is the corret NGINX.conf file

```
server {
        server_name CHANGE_SERVER_NAME_HERE;
        root /var/www/osticket;

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;
        index index.php index.html index.htm;

        index index.php;
        client_max_body_size 2000M;
        client_body_buffer_size 100M;
        client_header_buffer_size 10M;
        large_client_header_buffers 2 10M;
 
        client_body_timeout 12;
        client_header_timeout 12;
        keepalive_timeout 15;
        send_timeout 10;
 
        gzip             on;
        gzip_comp_level  2;
        gzip_min_length  1000;
        gzip_proxied     expired no-cache no-store private auth;
        gzip_types       text/plain application/x-javascript text/xml text/css application/xml;
 
	set $path_info "";
 
	# Deny access to all files in the include directory
	location ~ ^/include {
		deny all;
		return 403;
	}

	# Deny access to apache .ht* files (nginx doesn't use these)
	location ~ /\.ht {
		deny all;
	}

	# Requests to /api/* need their PATH_INFO set, this does that
	if ($request_uri ~ "^/api(/[^\?]+)") {
		set $path_info $1;
	}

	# /api/*.* should be handled by /api/http.php if the requested file does not exist
	location ~ ^/api/(tickets|tasks)(.*)$ {
		try_files $uri $uri/ /api/http.php;
	}

	# /scp/ajax.php needs PATH_INFO too, possibly more files need it hence the .*\.php
	if ($request_uri ~ "^/scp/.*\.php(/[^\?]+)") {
		set $path_info $1; 
	}

	# Make sure requests to /scp/ajax.php/some/path get handled by ajax.php
	location ~ ^/scp/ajax.php/(.*)$ {
		try_files $uri $uri/ /scp/ajax.php;
	}

	if ($request_uri ~ "^/ajax.php(/[^\?]+)") {
		set $path_info $1;
	} 

	location ~ ^/ajax.php/.*$ {
		try_files $uri $uri/ /ajax.php;
	}

	location / {
		index index.php;
		# try_files $uri $uri/ /index.php$is_args$args;
	}

	location ~ \.php$ {
		try_files $uri =404;
		# fastcgi_split_path_info ^(.+\.php)(/.+)$;
		fastcgi_pass unix:/run/php/php7.4-fpm.sock;
		fastcgi_index index.php;
		include fastcgi_params;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		fastcgi_param SCRIPT_NAME $fastcgi_script_name;
		fastcgi_param PATH_INFO $path_info;
	}

       listen 443 ssl; # managed by Certbot
       ssl_certificate /etc/letsencrypt/live/CHANGE_SERVER_NAME_HERE/fullchain.pem; # managed by Certbot
       ssl_certificate_key /etc/letsencrypt/live/CHANGE_SERVER_NAME_HERE/privkey.pem; # managed by Certbot
       include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
       ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = CHANGE_SERVER_NAME_HERE) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

        listen 80;
        server_name CHANGE_SERVER_NAME_HERE;
        return 404; # managed by Certbot
}
```

**Comment by superiorzeus** [comment]
@danielrussob You are a life saver. Thanks so much 🙏
