### ISSUE TITLE
First Click Sort Direction

### ISSUE THREAD

**Issue by TetraAsh** [osTicket/osTicket#5364]
When in osTicket (1.14-git), when in the queue/ticket view, looking at the list of tickets. 
The default sort order when you single click a column header is Desc whereas Asc would be more logical.

https://domain/scp/tickets.php?queue=1&dir=1&sort=4&_pjax=%23pjax-container

**Comment by JediKev** [comment]
@TetraAsh 

This can be configured. Go to **Admin Panel > Settings > Tickets > Queues**, click any Queue, and go to the **Sort** tab. Here you can configure all the sort options as well as the default order (ASC/DESC).

Cheers.

**Comment by Demarcation** [comment]
sorry, didnt see first comment, its not the default sort order of the queue thats the issue, i have a queue setup with default sort order of last updated, but when i click the organisation column, it sorts z to a not a to z

**Comment by JediKev** [comment]
@Demarcation 

You can click it again to reverse the order. So when you click Organization Column and it sorts from Z to A, click it again and it will sort from A to Z.

Cheers.

**Comment by TetraAsh** [comment]
yeah, I understand you can click again, it just seems odd, would most people not want the first click to be a to z? no other site starts with z to a.
also, if you have any ideas on the files that control this, can you nudge me in that direction so i can find and update it on my own git, cheers!

**Comment by JediKev** [comment]
@TetraAsh 

I see. You would need to look at `include/staff/templates/queue-tickets.tmpl.php`. All headers go through the same `foreach` so if you change this it will change for all column headers (unless you put a special case for the field type or something). Just note that when you make this change it will most likely affect Ticket Numbers, Dates, etc. where you would want to sort most recent first.

Cheers.
