### ISSUE TITLE
Stripping < & > when downloading text/plain emails

### ISSUE THREAD

**Issue by rsclmumbai** [osTicket/osTicket#5368]
Server Information
--
osTicket Version | v1.14.1 (f1e9e88) —  Up to date
Web Server Software | Apache/2.4.6 (CentOS) PHP/7.3.5
MySQL Version | 5.5.60
PHP Version | 7.3.5

### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch?
Yes, send a text/plain email with the content having any content enclosed in <>
example: &lt;whatIsthis&gt;
Content between <> is stripped.

* [ ] Do you have any errors in the PHP error log, or javascript console?
None.

* [ ] Did you check the [osTicket forums](https://forum.osticket.com/)?
Yes. https://forum.osticket.com/d/96862-html-tags-are-getting-stripped

* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?
Yes. No joy.

### Description
Emails with content in <> is getting stripped. As mentioned in the OSTicket forum, I have managed to find the code which prevents this from happening in text/html emails but I'm not able to do the same for text/plain emails.

### Steps to Reproduce
See above.

**Expected behavior:** [What you expected to happen]
< & > should be relaplaced with &lt; &gt;
I understand OSTicket is using external libraries to sanitize content. Can you tell him what change can I make to avoid the stripping of content.

Thanks!!

**Comment by JediKev** [comment]
@rsclmumbai 

This is a question best suited for our Community Supported Forum. Please make a post on the Forum for further assistance. Please ensure you include the exact steps to replicate the issue, a screenshot of your Dashboard > Information page, and explain how your email is routed to the system (Fetching, Piping [Remote/Local], API). Also, I'd _assume_ that it's `html_balance()` fault as we run this on the Message when adding it to the Thread. `html_balance()` assumes data inside `<>` is an HTML tag and it tries to balance the HTML. If it cannot balance the tag then it gets stripped.

**Edit:**
Of course you don't want to disable the `html_balance()` function itself as it's used elsewhere. You'd want to remove it from `getClean()` for `class TextThreadEntryBody`. Doing this however will potentially leave you vulnerable to XSS and other attacks (not good at all) so I do not recommend this.

Cheers.

**Comment by thctlo** [comment]
any update on this code scripping.. 
Even if i send plain text mail, but with contect having <> still script things out. 
It renders my tickets system useless..  :-(  

i already changed a bit in the function getClean but it does not give the result as we need. 
Sure, removing this enables XSS attack options, but can at least have a an option to choose this.. 
just a "enable/disable" scripting code would be very nice. 

*( running  v1.15.8 )
