### ISSUE TITLE
authentication failure [SMTP: STARTTLS failed (code: 220, response: Ready to start TLS)]

### ISSUE THREAD

**Issue by ParmaU** [osTicket/osTicket#5370]
Hello
The system information as follow:

64bit Linux Mint 18.1 Serena
PHP 7.3.4
osTicket version v1.14.1 (f1e9e88)
ServerDB 10.1.38-MariaDB
lotus SMTP server

I have updated the system from the previous version to the current one, after this update it no longer sends any email of any kind (reply, notification, test)
going to check the settings and saving the configuration it signals me an authentication error.
no changes have been made on the mail server side and the credentials are valid
gives the same error if I use it as a Gmail or GMX server
What could it be?
![ost](https://user-images.githubusercontent.com/2841933/74143062-65cc0c80-4bfa-11ea-8164-965317a0a33d.JPG)

**Comment by JediKev** [comment]
@ParmaU 

This question is best suited for our [Community Supported Forum](https://forum.osticket.com). Github is a place for Bugs with the software, Feature Requests, and Pull Requests.

With this being said, it looks like you are trying to use port 25 which is a relay port in pretty much all cases. You will need to use port 465 or 587 and Enable Authentication Required.

Cheers.

**Comment by ParmaU** [comment]
what you say is true, but the local server does not use encrypted protocols, but the server responds to the standard SMTP port (25)
as mentioned, presents this problem after updating the OSTCKET system

if I have to go to the forum there is no problem but I thought it was a bugs
