### ISSUE TITLE
[Feature Request] Adjust Email Template

### ISSUE THREAD

**Issue by ke1v3y** [osTicket/osTicket#5371]
### Description
When sending emails out of osTicket to clients, we have found a couple of pain points with regard to readability / prominence of attachments. It would be beneficial if there were a way to adjust the email formatting. In lieu of this, it would be helpful if we could move the attachments from the bottom of the email to the top. Currently, it is easy to overlook them when sent.

![image](https://user-images.githubusercontent.com/42303322/74153019-905b9c80-4bdd-11ea-9f32-ba4e592c417f.png)

**Comment by JediKev** [comment]
@ke1v3y 

Are you talking about attachments in the Full Thread Template Variable? Or the Template itself? Cause the screenshot is showing the Full Thread Template Variable but you are saying the Email Template so I want to make sure we are looking at the same thing. 

Cheers.

**Comment by JediKev** [comment]
@ke1v3y 

I do believe you are talking about the Full Thread Template Variable. In this case you will want to edit file `include/client/templates/thread-export.tmpl.php` and move the `<p>` tag that houses the Attachments above the body of the email.

Let me know if this is what you are looking for and I'll close this.

Cheers.

**Comment by ke1v3y** [comment]
@JediKev - That did the trick. That was exactly what I was looking for. Thank you!
