### ISSUE TITLE
authentication failure [SMTP: STARTTLS failed (code: 220, response: 2.0.0 SMTP server ready)]

### ISSUE THREAD

**Issue by kimreq** [osTicket/osTicket#5392]
i dont know y I'm getting this error eveything is correct authentication and all are perfect?
please solve this issue and i want that is this because of version differences????
![Screenshot (84)](https://user-images.githubusercontent.com/36020960/75769500-4abd6a00-5d6c-11ea-8963-6500bbc5c7b3.png)

**Comment by JediKev** [comment]
@coopjab 

Did Microsoft make the switch for your account and force you to use OAuth while disabling the Legacy Authentication?

If so, you will have to wait until we implement OAuth for email authentication.

If not, please post any related errors from your mail server and webserver error logs.

Cheers.

**Comment by kimreq** [comment]
yes forced to use OAuth

**Comment by kimreq** [comment]
@JediKev 
hey OAuth is disabled and there no authentication in office 365 when i opened mail directly account opened without OAuth .......

help me please where im doing wrong???

**Comment by coopjab** [comment]
hey OAuth is disabled and there no authentication in office 365 when i opened mail directly account opened without OAuth help me please where im doing wrong???

**Comment by JediKev** [comment]
@coopjab 

For the SMTP Hostname instead of `smtp.office365.com` use `tls://smtp.office365.com` and retry.

Cheers.

**Comment by ntozier** [comment]
We use:
![2020-03-04_1010](https://user-images.githubusercontent.com/1315768/75893214-738f3f00-5e00-11ea-881b-8426ff12ec84.png)

So maybe the problem is the account being used, or environment based.  Here is our environment:
![2020-03-04_1011](https://user-images.githubusercontent.com/1315768/75893317-9d486600-5e00-11ea-9b21-fb3f3d675535.png)

**Comment by kimreq** [comment]
@JediKev @ntozier 
 when i was creating db for os ticket in heidi sql i got this error Acess denied root@localhost (password=yes)
after that i tried to create new in fresh machine and still I'm getting stucked in this error 
please help me ? where I'm doing wrong 
![Screenshot (87)](https://user-images.githubusercontent.com/36020960/76054726-9e5fcb80-5f97-11ea-8d00-5d162cbc64f4.png)

**Comment by JediKev** [comment]
@coopjab 

From first glance, it looks like the credentials you are trying to use are incorrect. Access Denied typically means authentication credentials are incorrect but it could also mean a few other things so you should consult the MySQL error logs and documentation. This unfortunately falls outside the scope of our support so I really wouldn’t be able to help you with this.

Cheers.

**Comment by ntozier** [comment]
@coopjab as a side note you probably do not want to use the MySQL/MariaDB root user as your database user.  If that account ever got compromised it would compromise your entire SQL server.  Where as if you use one specific for the osTicket database if that got compromised it would only compromise that database.

As a second note: Depending on how your MySQL/MariaDB server was setup, you might have to use the account locally to create a database.  I presume that you are not running the HeidiSQL on the server and are running it on your desktop, which would mean that your root user doesn't have privs to be used remotely. This is a security thing on your root account, and one I recommend that you not remove.

**Comment by kimreq** [comment]
@ntozier 

thanks man i gotcha ... everything is working fine

**Comment by ntozier** [comment]
If you are all set then place close this issue report. :)

**Comment by JediKev** [comment]
@coopjab Should I close this issue now?

**Comment by kimreq** [comment]
thanks man i will close @JediKev
