### ISSUE TITLE
Ticket search issues with partial words

### ISSUE THREAD

**Issue by ffsab00070875** [osTicket/osTicket#5394]
Hi all,

Information: PHP7.2, MySQL5.1.7, osTicket v1.14.1

I think this issue is not resolve now.

I wanna search a word (e.g., document), but if I search "documen", it will not match "document".

BRs,

**Comment by ntozier** [comment]
Have you tried searching for `documen*`?

**Comment by JediKev** [comment]
@ffsab00070875 

You will need to use MySQL `BOOLEAN MODE` logic in addition to wildcard. If you want to search a partial word do `+Partial*`.

**Example:** `+documen*` will match `document`, `documentation`, etc.

Cheers

**Comment by ffsab00070875** [comment]
OMG, It works! Thanks a lot!

But task search still not working, do you know why?

BRs,

**Comment by JediKev** [comment]
@ffsab00070875 

We use different searching for Tasks. When searching Tasks we will see if any number starts with the search criteria and we search the Task Titles for the search criteria. These both use MySQL `LIKE` comparison operator so `BOOLEAN MODE` logic, wildcards, etc. will not apply.

**Example:** 
Search for `documen`:
```sql
SELECT A1.* FROM `ost_task` A1 JOIN `ost_task__cdata` A2 ON (A1.`id` = A2.`task_id`) WHERE (A1.`number` LIKE 'documen%' OR A2.`title` LIKE '%documen%');
```

Cheers.

**Comment by ffsab00070875** [comment]
Dear JediKev,

I just put those in search field.
But still not working.

Could you please describe more detail?
Can task search by date range or dept?

Thanks!

**Comment by JediKev** [comment]
@ffsab00070875 

>Could you please describe more detail?

`+Partial*` will not work for task searching. When you search tasks we only search if the number starts with or if the Task Title contains the partial word. We do not search the Task body nor any of the thread entries for Tasks.

You can see the query I posted above and for number we do `number LIKE 'documen%'` and for title we do `title LIKE '%documen%'`.

> Can task search by date range or dept?

Not at this time, no. We hope to add Advanced Search for Tasks later on down the line.

Cheers.

**Comment by ffsab00070875** [comment]
@JediKev 
>`+Partial*` will not work for task searching. When you search tasks we only search if the number starts with or if the **Task Title contains the partial word**. We do not search the Task body nor any of the thread entries for Tasks.

I have try to search "documen" or "document", this word is in my task title, but it will not match correctly.

Can I just put `SELECT A1.* FROM `ost_task` A1 JOIN `ost_task__cdata` A2 ON (A1.`id` = A2.`task_id`) WHERE (A1.`number` LIKE 'documen%' OR A2.`title` LIKE '%documen%');` in task search field?


I'm sorry I have no enough knowhow.

**Comment by JediKev** [comment]
@ffsab00070875 

Well, first ensure the `ost_task__cdata` table exists. Then take a look at the table and ensure a record exists with the `title` column containing `document`. You can run the following query (assuming your tables start with `ost_`):
```sql
SELECT * FROM `ost_task__cdata` WHERE `title` LIKE '%document%';
```

Cheers.

**Comment by ffsab00070875** [comment]
@JediKev 

It works!

Another question, can search both title & task_id in search field at the same time?  

Best regards,

**Comment by JediKev** [comment]
@ffsab00070875 

>Another question, can search both title & task_id in search field at the same time?

Unfortunately, not at this time. Whatever you put in the search box for tasks will become one search string. 

**Example:**
Searching for `777011 Title` will result in:
```sql
SELECT A1.* FROM `ost_task` A1
    JOIN `ost_task__cdata` A2 ON (A1.`id` = A2.`task_id`)
    WHERE (A1.`number` LIKE '777011 Title%' OR A2.`title` LIKE '%777011 Title%');
```

Cheers.

**Comment by JediKev** [comment]
Closing because the Original post is solved.
