### ISSUE TITLE
your site is down. SSL invalid

### ISSUE THREAD

**Issue by mariusa** [osTicket/osTicket#5397]
https://osticket.com/
![Screenshot from 2020-03-06 20-08-25](https://user-images.githubusercontent.com/1283842/76109986-4603ea80-5fe6-11ea-90f2-a7b5e8cfc28d.png)

**Comment by JediKev** [comment]
@mariusa 

Looks like your browser cached an old certificate or something as when I visit the site works and I see a cert valid through `February 20, 2021`:
<img width="486" alt="Screen Shot 2020-03-06 at 12 12 14" src="https://user-images.githubusercontent.com/11823401/76110220-bb020080-5fa3-11ea-9dbf-e9dd2db66848.png">

Cheers.

**Comment by ntozier** [comment]
Site works for me.
No SSL cert issues when i go there.
![2020-03-06_1313](https://user-images.githubusercontent.com/1315768/76110282-41badb80-5fac-11ea-984d-279d7feffdec.png)

**Comment by mariusa** [comment]
Interesting. I'll close then, maybe it's my Chrome.
