### ISSUE TITLE
Translate Osticket 1.14

### ISSUE THREAD

**Issue by gamefrancisco18** [osTicket/osTicket#5406]
I want to install a translation of osticket (i have the files but the translation version is not verification in official site, but it's 100% of translation)https://crowdin.com/project/osticket-official/es-ES#
I download this files, but i don't know how to install it. (if I pack it in a .phar file??? online or in another packer, it will work?)

**Comment by JediKev** [comment]
@gamefrancisco18 

You have two options:
- Wait for a new build of the language pack to be released
- Use the standalone files from crowdin until the new build is released

All you need to do is move the folder from crowdin to the `include/i18n/` folder.

**Note:**
In the future you should post stuff like this on the [Forum here](https://forum.osticket.com). Github is the place to report issues/bugs and feature requests. The Forum is for anything else like questions, general how-to, etc.

Cheers.
