### ISSUE TITLE
DELAY READ EMAIL

### ISSUE THREAD

**Issue by EdoardoMDP** [osTicket/osTicket#5407]
There is a huge delay in OsTickets even when Fetching is set on every minute. OsTickets create a ticket for every support mail that comes in but sometimes the ticket and mail to the Agent only gets delivered the next day or next hours which is not good for out support service.

The email came in around 10th of March 2020 20:36, but the message only come in on OsTickets on the 11th of March 2020 09:12.

php version: PHP 7.2.24
osTicket version: 1.141

Can help me?
Thanks

**Comment by JediKev** [comment]
@EdoardoMDP 

You need to setup a cron job:
- https://docs.osticket.com/en/latest/Getting%20Started/POP3-IMAP%20Settings.html#schedule-polling

#### Excerpt from the Documentation:
**IMPORTANT:** Simply checking `Admin Panel => Settings => Email Settings => Enable POP/IMAP email fetch` will not cause osTicket to automatically poll a mailbox for new messages. Account polling, unlike email piping, requires that a mail fetcher (script) be scheduled for repeated execution.

Cheers.

**Comment by JediKev** [comment]
@EdoardoMDP 

Did you ever get the cron job/task scheduler working? If so, can I close this?

Cheers.

**Comment by EdoardoMDP** [comment]
yes now it works...thanks !
