### ISSUE TITLE
Emails from agents are not converted into thread entries, if they did not create the ticket.

### ISSUE THREAD

**Issue by marchermans** [osTicket/osTicket#5408]
### Prerequisites

* [X] Can you reproduce the problem in a fresh installation of the "develop" branch? => Yes
* [X] Do you have any errors in the PHP error log, or javascript console? => No
* [X] Did you check the [osTicket forums](https://forum.osticket.com/)? => Yes
* [X] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported? => Could not find anything similar

### Description
It does not seem to be possible for an Agent (None creator of a Ticket) to write a message or at least an internal note via EMail. 

### Steps to Reproduce
1. Setup OsTicket with one user and one Agent
2. Create a ticket via the user.
3. Send an email with the Ticket number in the subject, it will get appended to the original ticket as message.
4. Send an email with the Ticket number in the subject from an Agent email adress. Notice the System creating a new Ticket instead of appending it to the original ticket thread.

**Expected behavior:**
Agents being able to send a message to the Email System and it either appending it as an internal note or a message to the client.

**Actual behavior:** [What actually happened]
Agents, as long as they did not create a ticket in their own Name, Always create a new ticket.
### Versions

System info:
![image](https://user-images.githubusercontent.com/5585406/76405820-06902200-6389-11ea-9bc6-6a4b5399c0dc.png)

Browser info:
Chrome 80

**Comment by JediKev** [comment]
@OrionDevelopment 

We’ve never supported agent responses via email threading on tickets. If the headers are correct it will add as an internal note but that’s it.

Cheers.

**Comment by JediKev** [comment]
@OrionDevelopment 

Here is the section of code that should add the email as an internal note (if from Agent):
- https://github.com/osTicket/osTicket/blob/develop/include/class.mailfetch.php#L868-L877
- https://github.com/osTicket/osTicket/blob/develop/include/class.mailfetch.php#L886-L892

If the headers do not match an existing thread then we create a new ticket. So I would assume when your agent replies their headers do not match an existing thread.

Cheers.

**Comment by marchermans** [comment]
Yes they do not, because it is simply a new email. Something for example from the conversation with a client outside of OsTicket. The behavior is inconsistent here. If I create a ticket in my name as an agent it works, if the ticket is not mine it does not. It would be amazing if the agent could mail to the system to add a response or internal note as if it was added through the ui, just as the creator of the message can.

**Comment by JediKev** [comment]
@OrionDevelopment 

> It would be amazing if the agent could mail to the system to add a response or internal note as if it was added through the ui, just as the creator of the message can.

This is something that has been requested many times before and is on our Feature Request List.

Also, as I mentioned before, if the headers of the agent’s email matches a previous thread it _will_ add as an Internal Note so we do support this currently.

_Side Note:_
If the agent creates a new email with no references in the headers (ie. no In-Reply-To header, no References header, or no Ticket Number in the Subject - see [lookupByEmailHeaders()](https://github.com/osTicket/osTicket/blob/develop/include/class.thread.php#L1323-L1461)) how are you supposed to know what thread it should belong to?

Cheers.

**Comment by marchermans** [comment]
The ticket number is in the Subject of the email. We tested all kinds of variants from: [#000000] To Ticket #000000 none works. The system does not detect an email coming from an agent as being attached to a thread if he or she did not create the ticket for himself. If however the agent replies to an email coming from the system (aka it having the correct headers) then it works, but as stated not with a new email.

**Comment by ntozier** [comment]
@OrionDevelopment yes that is how the system is designed to work.

**Comment by JediKev** [comment]
@OrionDevelopment 

Looking deeper at the code, the Ticket Number matching only works for Users, not Agents. So the only option for Agents is to have matching email headers (ie. `Message-ID`, `In-Reply-To` and/or `References`).

Cheers.

**Comment by marchermans** [comment]
@ntozier @JediKev Would it be possible to extend this to be able to accept this from agents as well?

**Comment by JediKev** [comment]
@OrionDevelopment 

Eventually, yes, this is why it is on our Feature Request List.

Cheers.

**Comment by marchermans** [comment]
Okey, I would be willing to PR this in. If i get a couple of pointers. In particularly how do i check if a given Staff Agent is allowed to write to a given thread? Since it should be as simple as extending this: https://github.com/osTicket/osTicket/blob/d8eefa1e2bbc0794874c1b3d8ce3a0f7ba0dc671/include/class.thread.php#L1453 with the relevant check logic that grabs the agent from the senders email address and validate that he is allowed to write to the thread, no?

**Comment by protich** [comment]
Matching emailed conversations just on ticket numbers, for agents, is not supported (and will probably never be) because it's a security vulnerability that opens up the system to message injection purpoting to be from an agent. 

Let me explain -- Anyone can spoof email headers (to be from an agent) and simply automate adding ticket numbers to the subject based on your numbering sequence and _boom_ - now you have thread entry injection.

To protect against such injections we strictly match on reflected email headers which are encoded with thread info. This is necessary especially for agents since an agent has one-to-many relation to tickets in the system.

A PR to add the injection won't be merged - but you're welcome to mod your own installation.

**Comment by marchermans** [comment]
Okey understood.

**Comment by JediKev** [comment]
@OrionDevelopment 

I'm closing this as this was determined to be intended behavior.

Cheers.
