### ISSUE TITLE
Some words in agent menu are in English

### ISSUE THREAD

**Issue by pivettamarcos** [osTicket/osTicket#5416]
1. Moved phar files to include/i18n
3. Setup server
2. Added language and set to Portuguese Brazilian

![image](https://user-images.githubusercontent.com/24397077/76825147-d5d04280-67f7-11ea-8308-d2d6e4f525a9.png)

I'd expect to see these words translated to portuguese, like "Open" and "My Tickets", but they aren't. Server is running on a raspbian distro, using chrome as browser.
It seems as if the phar files for the translations are version "1.10" and not "1.14" (image below). If that's the problem, how to download version 1.14 of the translations? The crowdin project seems to have the 1.14 file for pt_BR, and it`s 100% complete.

Here is the server info.
![image](https://user-images.githubusercontent.com/24397077/76824801-fea40800-67f6-11ea-9ee5-4c9efe3679bf.png)

**Comment by JediKev** [comment]
@pivettamarcos 

You can change the Queue Names to anything you want via **Admin Panel > Settings > Tickets > Queues**. See:
- https://forum.osticket.com/d/96814-resolved-menu-translations/2

**Note:**
We hope to add inline translations to Queue Names in future updates, so please stay tuned.

Cheers.

**Comment by pivettamarcos** [comment]
Thank you @JediKev.
But what about this text here? ("Welcome to the Support Center... )

![image](https://user-images.githubusercontent.com/24397077/76876012-1491e700-6850-11ea-8dc9-07977344fd35.png)

**Comment by JediKev** [comment]
@pivettamarcos 

You are supposed to translate Pages yourself. Go to **Admin Panel > Manage > Pages > Landing** and there you can switch between languages and add your own translations:
<img width="567" alt="Screen Shot 2020-03-17 at 11 26 17" src="https://user-images.githubusercontent.com/11823401/76878099-57e55900-6842-11ea-9de9-beed9de8eff8.png">

Cheers.

**Comment by pivettamarcos** [comment]
Solved
