### ISSUE TITLE
PHP Notice in ORM

### ISSUE THREAD

**Issue by kler** [osTicket/osTicket#5432]
### Prerequisites

* [X] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [X] Do you have any errors in the PHP error log, or javascript console?
* [X] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [X] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

There are unnecessary notice in ORM.

    PHP Notice:  Trying to access array offset on value of type bool in /srv/osticket-sys/upload/include/class.orm.php on line 2267

### Steps to Reproduce

1. Make sure you are tailing error output somehow
2. Do any operation in the UI
3. PHP Notice will be displayed

**Expected behavior:** [What you expected to happen]

No notice is printed.

**Actual behavior:** [What actually happened]

Notice is printed.

### Versions

All recent, all OS and browsers.

**Comment by JediKev** [comment]
@kler 

What version of PHP did you test this with?

Cheers.

**Comment by kler** [comment]
The error was confirmed in php 7.2.
The fix however was tested in all versions using 3v4l.org: https://3v4l.org/HiON6
So should be a safe addition to the project.
