### ISSUE TITLE
unable to select one or more rules...

### ISSUE THREAD

**Issue by dasnoopy** [osTicket/osTicket#5436]
### Description

![image](https://user-images.githubusercontent.com/296922/77916033-be359700-7298-11ea-994c-5c4ad00d3f01.png)

### Steps to Reproduce

1. login with and admin account
2. go to In admin panel / Agents / Roles
3. notice checkboxes in the first column

**Expected behavior:** [What you expected to happen]
all checkboxes near Roles name should be visibile then should be possible select one or more or all rules

**Actual behavior:** [What actually happened]

some checkboxes are not visbile then the e.g. is not possible delete a role or enable/disable it

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about your server.
![image](https://user-images.githubusercontent.com/296922/77915491-dd7ff480-7297-11ea-950d-507970372fbb.png)

- Ubuntu server 18.04.4 LTS and Mozilla Firefox 74 or new Microsoft Edge (Chromium based)

Regards

**Comment by JediKev** [comment]
@dasnoopy 

Lol this just means that it’s used as someone’s Primary Role for their Primary Department. You cannot delete Roles that are used as someone’s Primary Role.

Cheers.

**Comment by dasnoopy** [comment]
... arghhhh sorry !!!   you are completely right  :+1:  and I'm a completely  idiot :smile: 

Thanks for the quick response
I'm going to close the issue

Regards
Andrea

**Comment by JediKev** [comment]
@dasnoopy 

Nah, it's not like that! It's one of the more lesser known functions of the software, so don't feel bad! :)

Cheers.
