### ISSUE TITLE
SMTP: correct configuration, code -1, times out.

### ISSUE THREAD

**Issue by mehov** [osTicket/osTicket#5439]
### Prerequisites

* [?] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [-] Do you have any errors in the PHP error log, or javascript console?
* [+] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [+] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

_Admin_ → _Email_ → _Update Email Address_ times out (HTTP 504) on saving. Narrowed that down to "*Sending Email via SMTP*": when disabled, it saves just fine. I'm guessing this could be something specific to my osTicket VPS, but I'm out of ideas where to look.

First of all, checked telnet:
````
$ telnet email-smtp.eu-west-1.amazonaws.com 465
Trying 52.19.16.61...
Connected to email-smtp.eu-west-1.amazonaws.com.
Escape character is '^]'.
````

[Made sure `openssl` is enabled](https://github.com/osTicket/osTicket/issues/4158#issuecomment-364966834):

````
# php -i  |  grep -i openssl
SSL Version => OpenSSL/1.1.1d
openssl
OpenSSL support => enabled
OpenSSL Library Version => OpenSSL 1.1.1d  10 Sep 2019
OpenSSL Header Version => OpenSSL 1.1.1d  10 Sep 2019
Openssl default config => /usr/lib/ssl/openssl.cnf
openssl.cafile => no value => no value
openssl.capath => no value => no value
Native OpenSSL support => enabled
````
The timeout happens precisely on [include/pear/Net/SMTP.php:448](https://github.com/osTicket/osTicket/blob/43bf186db9e85c8ec218158ea4c0bc3e90bbe3eb/include/pear/Net/SMTP.php#L448):
````
        if (PEAR::isError($error = $this->parseResponse(220))) {
            return $error;
        }
````
Right above it, I can still `var_dump($this);exit;`, and it looks like:
````
object(Net_SMTP)#193 (15) {
  ["host"]=>
  string(34) "email-smtp.eu-west-1.amazonaws.com"
  ["port"]=>
  string(3) "465"
  ["localhost"]=>
  string(9) "localhost"
  ["auth_methods"]=>
  array(4) {
    ["DIGEST-MD5"]=>
    array(2) {
      [0]=>
      *RECURSION*
      [1]=>
      string(13) "authDigestMD5"
    }
    ["CRAM-MD5"]=>
    array(2) {
      [0]=>
      *RECURSION*
      [1]=>
      string(11) "authCramMD5"
    }
    ["LOGIN"]=>
    array(2) {
      [0]=>
      *RECURSION*
      [1]=>
      string(9) "authLogin"
    }
    ["PLAIN"]=>
    array(2) {
      [0]=>
      *RECURSION*
      [1]=>
      string(9) "authPlain"
    }
  }
  ["pipelining"]=>
  bool(false)
  ["pipelined_commands":protected]=>
  int(0)
  ["debug":protected]=>
  bool(false)
  ["debug_handler":protected]=>
  NULL
  ["socket":protected]=>
  object(Net_Socket)#192 (14) {
    ["fp"]=>
    resource(9) of type (stream)
    ["blocking"]=>
    bool(true)
    ["persistent"]=>
    bool(false)
    ["addr"]=>
    string(14) "52.209.165.250"
    ["port"]=>
    int(465)
    ["timeout"]=>
    int(20)
    ["lineLength"]=>
    int(2048)
    ["newline"]=>
    string(2) "
"
    ["_debug"]=>
    bool(false)
    ["_default_error_mode"]=>
    NULL
    ["_default_error_options"]=>
    NULL
    ["_default_error_handler"]=>
    string(0) ""
    ["_error_class"]=>
    string(10) "PEAR_Error"
    ["_expected_errors"]=>
    array(0) {
    }
  }
  ["socket_options":protected]=>
  array(1) {
    ["ssl"]=>
    array(1) {
      ["verify_peer_name"]=>
      bool(false)
    }
  }
  ["timeout":protected]=>
  int(0)
  ["code":protected]=>
  int(-1)
  ["arguments":protected]=>
  array(0) {
  }
  ["greeting":protected]=>
  NULL
  ["esmtp":protected]=>
  array(0) {
  }
}
````

- I tried using another major SMTP server (not Gmail) which normally works, but in this case it also didn't, so this must be not the case of some ISP-specific configuration (e.g. Gmail's less secure apps control)
- Tried ports 25, 465, 587 - all work with Telnet, but not here
- This is not a matter of incorrect SMTP credentials, as [those are validated later](https://github.com/osTicket/osTicket/blob/43bf186db9e85c8ec218158ea4c0bc3e90bbe3eb/include/pear/Mail/smtp.php#L373) and only if *Authentication Required* is set to yes.

### Steps to Reproduce

(I'm not sure if this can be reproduced.)

1. Went to https://example.com/scp/emails.php?id=1
2. Entered the credentials and enabled SMTP

**Expected behavior:** No timeout

**Actual behavior:** `2020/03/31 11:21:27 [error] 3924#3924: *54953 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 1.1.1.1, server: example.com, request: "POST /scp/emails.php?id=1 HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.3-fpm.sock", host: "example.com", referrer: "https://example.com/scp/emails.php?id=1"`

### Versions

- osTicket Version | v1.12.5-88-g4b93cb7d (4b93cb7) —  Up to date
- Web Server Software | nginx/1.16.1
- MySQL Version | 10.3.18
- PHP Version | 7.3.14-1~deb10u1

### Environment

- Server: Linux VPS
- OS: Debian 10

**Comment by JediKev** [comment]
@mehov 

First, ensure there is no 2-Factor auth or anything like that. Next, when you insert the SMTP info, ensure Authentication Required is checked/enabled and retest. If you still get an error put the hostname as `ssl://email-smtp.eu-west-1.amazonaws.com`, port `465`, auth required yes, and retest. If that doesn't work hostname `email-smtp.eu-west-1.amazonaws.com`, port `587`, auth yes, and retest. Lastly, if that doesn't work hostname as `tls://email-smtp.eu-west-1.amazonaws.com`, port `587`, auth yes, and retest. If you still have issues after trying all this it would be definitely be worth looking at your mailserver error/debug logs for more detailed errors of why auth is failing (see your hosts documentation for more info on checking mailserver logs).

Cheers.

**Comment by mehov** [comment]
Prefixing with `ssl://` did it! Thank you so very much for a prompt and detailed reply! 😀

(And sorry I came back with a confirmation this late)

**Comment by simongcc** [comment]
@JediKev I just encounter the same and find out this before reading your reply.
I also find out the reason behind by reading the source code and post the explanation in their official forum.
https://forum.osticket.com/d/100417-sending-email-via-smtp-always-smtp-invalid-response-code-received-from-server

Just add here as notes and for future development reference.
