### ISSUE TITLE
Translation issue - LC_Messages - Hungarian

### ISSUE THREAD

**Issue by ustix** [osTicket/osTicket#5452]
### Prerequisites
* [ x ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ x ] Do you have any errors in the PHP error log, or javascript console?
* [ x ] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [ x ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description
**Translation file issue:**
The messages.po.php is not used from neither of the .phar or the exctracted folder, only in the case, when I install osTicket and select the language, but then install.php fails, and a lot of bugs happening.

[Description of the bug or feature]
The following php error happens, when i try to install osTicket 1.14 with the latest Crowdin language directory (hu or hu_HU folder created in the i18n folder):
```
[09-Apr-2020 06:59:11 UTC] PHP Fatal error:  Uncaught InvalidArgumentException: List indices should be integers in /opt/lampp/htdocs/osTicket/include/class.util.php:205
Stack trace:
#0 /opt/lampp/htdocs/osTicket/include/class.forms.php(84): ListObject->offsetExists('name')
#1 /opt/lampp/htdocs/osTicket/include/class.ticket.php(3893): Form->getField('name')
#2 /opt/lampp/htdocs/osTicket/include/class.ticket.php(4069): Ticket::filterTicketData('api', Array, Array, NULL)
#3 /opt/lampp/htdocs/osTicket/setup/inc/class.installer.php(307): Ticket::create(Array, Array, 'api', false, false)
#4 /opt/lampp/htdocs/osTicket/setup/install.php(52): Installer->install(Array)
#5 {main}
  thrown in /opt/lampp/htdocs/osTicket/include/class.util.php on line 205
```
### Steps to Reproduce

1. Install osTicket 1.14 selecting Hungarian language and using crowdin Hungarian language directory
2. ...
3. Profit!

**Expected behavior:** [What you expected to happen]
A lot of Hungarian text.
**Actual behavior:** [What actually happened]
A lot of Hungarian text with a lot of error in the program, when installing, and using features (like opening a ticket, or creating new users)

### Versions
Ubuntu Mate 19.10 (64bit)
Firefox 74.0.1 (64bit)
LAMPP 7.4.4:
Apache/2.4.41 (Unix) OpenSSL/1.1.1e
PHP/7.4.4 mod_perl/2.0.8-dev Perl/v5.16.3
SQL/10.4.11-MariaDB

I tried creating phar files, I have used poedit and class.translation to create the messages.po.php, restarted server after pasting messages.po.php, used the folder version, used the original hu language pack phar (but that is for version 1.11, so that is reeeaally outdated). I have installed bz2 for phar files, no error on configuration, so the system met the requirements.
For phar files i have used: [this](https://phar.scer.io/)

**Comment by ustix** [comment]
@greezybacon @ntozier Maybe you can help me, I hope so.

**Comment by JediKev** [comment]
@ustix 

You can’t install osTicket in any language except English. After installing in English you can add language packs. This is a bug that will eventually be addressed but for now you have to install in English.

You are also using PHP 7.4 which we don’t fully support just yet. You should downgrade to PHP 7.3.

Cheers.

**Comment by ustix** [comment]
Thanks for the fast reply, I will try it, then tell you about it.

**Comment by ustix** [comment]
It is still not working as intended. I can see a lot of translation in the file, but nowhere in the site. Something is translated according to the folder (i'm using the folder, from Crowdin, not the phar, because that is even worse), but something is not. Messages.mo.php is not working. Can you test the Hungarian language pack, and look if there is any translation (like the profile.php) working? Because I think that php file is just not used at all.

**Comment by JediKev** [comment]
@ustix 

Didn’t see that you were using 1.14.. the language packs aren’t complete for 1.14 yet. We are updating them soon so please stay tuned.

Cheers.

**Comment by shteevy** [comment]
Hello, is there any update for this language's pack compatibility in 1.14.x ?

**Comment by JediKev** [comment]
@shteevy 

We should be releasing new builds of language packs and plugins today or tomorrow so stay tuned.

Cheers.

**Comment by JediKev** [comment]
@shteevy @ustix 

New builds of Language Packs are available [on our website](https://osticket.com/download). They are updated for `1.14.x` series so they should work no matter what version you're using.

Cheers.

**Comment by ustix** [comment]
@JediKev 
I really appreciate your effort to notify us. Thanks man!
Keep up the good work!

**Comment by shteevy** [comment]
Hello :) many thanks. It works. Have a nice day,
Steve
