### ISSUE TITLE
schedule's description is cleared on edit+save

### ISSUE THREAD

**Issue by matthiasradde** [osTicket/osTicket#5468]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch? (not tested)
* [x] Do you have any errors in the PHP error log, or javascript console? (no errors)
* [x] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description
Updating a schedule with a description clears the description.

### Steps to Reproduce

1. Create a schedule of your choice and save it
2. edit this schedule and modify the description
3. save schedule

**Expected behavior:** [What you expected to happen]
the new/modified description is saved to database (table "ost_schedule", field "description")

**Actual behavior:** [What actually happened]
an empty description is saved to database (table "ost_schedule", field "description")

### Versions
osTicket-Version | v1.14.1 (f1e9e88)
Server-Software | Apache/2.4.38 (Debian)
MySQL-Version | 10.3.22
PHP-Version | 7.3.14-1~deb10u1

Client
Windows 10 x64 using Chrome or Firefox (up-to-date) as browser

**Comment by JediKev** [comment]
@matthiasradde 

Thanks for the report. Here is the patch for the issue:
- https://github.com/osTicket/osTicket/pull/5469

Cheers.

**Comment by matthiasradde** [comment]
@JediKev
Thank you - patch is working as expected :-).

**Comment by JediKev** [comment]
@matthiasradde Again, thank you for the report.

Closing: This has been resolved with #5469.
