### ISSUE TITLE
Question: Can or does OSTicket support Sender Rewriting Scheme (SRS) in Office 365

### ISSUE THREAD

**Issue by jimjimbojimbob** [osTicket/osTicket#5473]
I don't think this is something OSTicket can handle I just wanted to ask the question. Trying to avoid fetching the e-mail if at all possible.

Email sent to Office 365 hosted domain and subsequently forwarded back out to on prem application server results, as per Microsoft article [here](https://docs.microsoft.com/en-us/office365/troubleshoot/antispam/sender-rewriting-scheme) in the sending address being rewritten into format:

`<Forwarding Mailbox Username>+SRS=<Hash>=<Timestamp>=<Original Sender Domain>=<Original Sender Username>@<Forwarding Mailbox Domain>`

i.e. 

An email from user@sender.com sent to receivingaddress@receivingdomain.com is forwarded out by Office 365 to receivingaddress@otherreceivingdomain.com

'Envelope from' address is changed to be:

`receivingaddress+SRS=<HASH>=<TIME>=sender.com=user@receivingdomain.com`

However the 'display from' address remains the same user@sender.com

### Steps to Reproduce

1. Email a support ticket in. Email is received in Office 365 and forwarded back out to on prem server
2. Agent claims ticket.  Agent replies to ticket which correctly sends an e-mail to the owner
3. Owner of the ticket updates the ticket by replying to the email. The ticket correctly updates and the agent can see this but OSTicket does not send an email alert to the agent.

**Expected behavior:** E-mail alert is sent to the agent to tell them the ticket has been updated

**Actual behavior:** E-mail logs show that no e-mail alert is generated at all

### Versions

1.10.5

CentOS 7.7

**Comment by ntozier** [comment]
I do not know the answer to your question, but I did feel the need to point out that 1.10 is end of life and no longer supported.  You might want to upgrade and see if the behavior changes in a contemporary version.

**Comment by JediKev** [comment]
@jimjimbojimbob 

I apologize, but I'm a bit confused by this thread so bear with me if I'm misinterpreting something. 

>'Envelope from' address is changed to be:
>
>receivingaddress+SRS=\<HASH\>=\<TIME\>=sender.com=user@receivingdomain.com
>
>However the 'display from' address remains the same user@sender.com

So, basically what you're saying is with SRS the `From` address is changed to the Forwarding address but you want to keep the Original Sender as the creator of the ticket, right? Do the email headers contain the original Sender address in the `Reply-To` header? I would assume so, and if that's the case, then you can setup a Ticket Filter to use the address in `Reply-To` as the creator/owner of the ticket.
<img width="620" alt="Screen Shot 2020-04-23 at 13 04 52" src="https://user-images.githubusercontent.com/11823401/80133569-0af05300-8563-11ea-9d6c-a86f02467a01.png">


>Owner of the ticket updates the ticket by replying to the email. The ticket correctly updates and the agent can see this but OSTicket does not send an email alert to the agent.
>
>Expected behavior: E-mail alert is sent to the agent to tell them the ticket has been updated
>
>Actual behavior: E-mail logs show that no e-mail alert is generated at all

So if the Agent isn't receiving an alert when a new User Message is added to the ticket, you need to ensure that the New Message Alert is Enabled (**Admin Panel > Settings > Tickets > Alerts and Notices**) and has the appropriate recipients enabled (see **Image 1** below). Next, you will need to go to their Agent account under **Admin Panel > Agents > Agents**, go to the Access tab, and ensure they have Alerts enabled for the Ticket's Department (see **Image 2** below). Next, you need to ensure the Department Alert Recipients isn't Disabled or set to Admin Email Only by going to **Admin Panel > Agents > Departments > select Ticket's Department > Alerts and Notices > Recipients**. Lastly, you need to check the New Message Alert template in **Admin Panel > Emails > Templates** to make sure it has no issues/errors or incorrect variables.

### Image 1
<img width="255" alt="Screen Shot 2020-04-23 at 12 48 30" src="https://user-images.githubusercontent.com/11823401/80132778-cf08be00-8561-11ea-896e-ebafaca44d0b.png">

### Image 2
<img width="586" alt="Screen Shot 2020-04-23 at 12 50 06" src="https://user-images.githubusercontent.com/11823401/80132780-d203ae80-8561-11ea-8ac8-7372591d4e7d.png">

Cheers.

**Comment by jimjimbojimbob** [comment]
@ntozier whilst we are in the process of testing a supported version, unfortunately the quick and simple answer in this case is to simply use an alternative domain that does not get forwarded out with an altered envelope.  Apologies for not following up @JediKev and thanks for the replies. I'll close the issue.
