### ISSUE TITLE
Attempting to generate a PDF only shows a blank web page

### ISSUE THREAD

**Issue by ozinfotech** [osTicket/osTicket#5479]
### Prerequisites

* [Y] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [Y] Do you have any errors in the PHP error log, or javascript console?
`[28-Apr-2020 17:54:57 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Mpdf\mb_regex_encoding() in /home/www/domain.com/include/mpdf/vendor/mpdf/mpdf/src/Mpdf.php:1097
Stack trace:
#0 /home/www/domain.com/include/class.pdf.php(76): Mpdf\Mpdf->__construct(Array)
#1 /home/www/domain.com/include/class.ticket.php(3129): Ticket2PDF->__construct(Object(Ticket), 'Letter', NULL, NULL)
#2 /home/www/domain.com/scp/tickets.php(503): Ticket->pdfExport('Letter', NULL, NULL)
#3 {main}
  thrown in /home/www/domain.com/include/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 1097
[28-Apr-2020 17:55:02 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Mpdf\mb_regex_encoding() in /home/www/domain.com/include/mpdf/vendor/mpdf/mpdf/src/Mpdf.php:1097
Stack trace:
#0 /home/www/domain.com/include/class.pdf.php(76): Mpdf\Mpdf->__construct(Array)
#1 /home/www/domain.com/include/class.ticket.php(3129): Ticket2PDF->__construct(Object(Ticket), 'Letter', NULL, NULL)
#2 /home/www/domain.com/scp/tickets.php(503): Ticket->pdfExport('Letter', NULL, NULL)
#3 {main}
  thrown in /home/www/domain.com/include/mpdf/vendor/mpdf/mpdf/src/Mpdf.php on line 1097
`
* [Y] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [Y] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

Attempting to generate a PDF only shows a blank web page.

### Steps to Reproduce

1. Attempt to print any ticket

**Expected behavior:** [What you expected to happen]
Was hoping to get a PDF file.

**Actual behavior:** [What actually happened]
Blank web page popped up.

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about your server.
osTicket Version: v1.12.5
Web Server Software: Apache
MySQL Version: 10.0.38
PHP Version: 7.4.5

All PHP extensions installed except for **APCu**.

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.
CENTOS 7.7 v86.0.18
Google Chrome Browser Version 81.0.4044.122 (Official Build) (64-bit)
Mozilla Firefox Browser Version 75.0 (32-bit)

**Comment by JediKev** [comment]
@ozinfotech 

Ensure you have the `mbstring` PHP Extension installed and enabled.

Cheers.

**Comment by JediKev** [comment]
@ozinfotech 

Make sure you read the _entire_ article; don't skim through:
- https://mpdf.github.io/about-mpdf/requirements-v7.html

Cheers.

**Comment by ozinfotech** [comment]
When I downgraded to PHP 7.3, it started working. Thanks @JediKev for the link to the requirements!
