### ISSUE TITLE
Creating new ticket from email and using replies, are not working

### ISSUE THREAD

**Issue by ustix** [osTicket/osTicket#5483]
**My issue:**
Creating new ticket from email and using replies to emails, are not working.

**My configuration:**
![image](https://user-images.githubusercontent.com/63343687/80587728-56997580-8a17-11ea-9d16-21bc5fb57d75.png)

**Working things about emails:**
Sending out emails is working, on all sides, for end-user and for agents too.
There is no errors anywhere, not even here:
![image](https://user-images.githubusercontent.com/63343687/80587961-c3ad0b00-8a17-11ea-8b89-d9677a6eb1de.png)
osTicket can even make its own folders using IMAP (OSTICKET folder has been created by osTicket itself - also OSTICKET-REPLY).

So I don't get what's wrong if it can even make folders, but can't read mails. They are coming to that directory (I have a rule which makes all the emails going to the OSTICKET folder and the rule is working).

I have searched the forum, but haven't found the same issue, just similar ones, which are not helping me.

**Comment by TechCare-Aus** [comment]
First up I would upgrade to 1.14.2 - https://forum.osticket.com/d/97449-osticket-v1-12-6-v1-14-2-available

Secondly I use Office 365 too and this works for me:

![image](https://user-images.githubusercontent.com/2740134/80593527-fa087b80-8a53-11ea-9e23-6226032765df.png)

Thirdly can you try leaving the email in **INBOX** and then clearing the field that says **Mail Folder**, then try send a new email. 

Also while I'm going about it do you have cron setup properly?

**Comment by ustix** [comment]
I didn't have cron setup properly, ty for your help!
