### ISSUE TITLE
ModSecurity OWASP + OsTicket = update failed

### ISSUE THREAD

**Issue by mainmind83** [osTicket/osTicket#5521]
### Prerequisites

* [X] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [X] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [X] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description
Trying to update from 1.10.1 to 1.12.6 with ModSecurity
OWASP CRS 3.2.0 intercepted

### Steps to Reproduce

1. Working osTicket 1.10.1
2. Normal process to 1.12.6
3. Popup window close with no errors on database or php log

**Expected behavior:** finish upgrade process

**Actual behavior:** deactivated modsecurity

Message: Access denied with code 403 (phase 1). Match of "rx ^%{tx.allowed_request_content_type_charset}$" against "TX:1" required. [file "C:\/Program Files (x86)/Plesk/ModSecurity/rules/modsecurity_crs-plesk/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "944"] [id "920480"] [msg "Request content type charset is not allowed by policy"] [data "utf-8"] [severity "CRITICAL"] [ver "OWASP_CRS/3.2.0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "OWASP_CRS"] [tag "OWASP_CRS/PROTOCOL_VIOLATION/CONTENT_TYPE_CHARSET"] [tag "WASCTC/WASC-20"] [tag "OWASP_TOP_10/A1"] [tag "OWASP_AppSensor/EE2"] [tag "PCI/12.1"]

**Comment by JediKev** [comment]
@mainmind83 

This does not appear to be an issue with osTicket, rather a security software problem. It looks like you need to update the OWASP rule to allow/whitelist the request. It says `Request content type charset is not allowed by policy` so maybe you just need to add the Request Content-Type Charset to the rule?

Cheers.

**Comment by mainmind83** [comment]
@JediKev 
Is the rule correct and is the parameter submission method insecure or is it overprotective?

**Comment by JediKev** [comment]
@mainmind83 

I haven't seen the request nor the rule so 🤷🏼‍♂️

Cheers.

**Comment by mainmind83** [comment]
POST and GET to /scp/upgrade.php

    POST /scp/ajax.php/upgrader HTTP/1.1
    Connection: close
    Content-Length: 103
    Content-Type: application/x-www-form-urlencoded; charset=UTF-8
    Accept: text/plain, */*; q=0.01
    Accept-Encoding: br, gzip, deflate
    Accept-Language: es-ES,es;q=0.8,en-US;q=0.5,en;q=0.3

    GET /scp/upgrade.php?_pjax=%23pjax-container HTTP/1.1
    Connection: close
    Content-Type: application/x-www-form-urlencoded; charset=UTF-8
    Accept: text/html, */*; q=0.01
    Accept-Encoding: br, gzip, deflate
    Accept-Language: es-ES,es;q=0.8,en-US;q=0.5,en;q=0.3

**Comment by JediKev** [comment]
@mainmind83 

So, it looks like OWASP is denying the request because of the `charset=UTF-8` part in the `Content-Type: application/x-www-form-urlencoded; charset=UTF-8` header. We've always used this header and haven't had/seen any issues. I would say this is a false positive as far as osTicket is concerned. This rule is surely useful in all other sites so I would configure Apache to remove/whitelist the rule (`SecRuleRemoveById 920480`) for this specific request/site.

Cheers.

**Comment by mainmind83** [comment]
Perfect, thanks!
