### ISSUE TITLE
OSTicket issues after upgrading: requested to deleted a setup folder and our email template no longer works

### ISSUE THREAD

**Issue by StewAlexander-com** [osTicket/osTicket#5529]
Hi,

We just upgraded from 1.10 to the following version, and we are seeing 2 issues:
![image](https://user-images.githubusercontent.com/48565067/83557806-483fed00-a4e0-11ea-9bdb-128d66e9d64a.png)

![image](https://user-images.githubusercontent.com/48565067/83557870-60b00780-a4e0-11ea-87cf-af98e4eb4f67.png)

1. How do we delete the setup directory?
2. What are the variable names now? Is there a list somewhere?

**Comment by StewAlexander-com** [comment]
I figured out how to resolve the setup folder issue, however our email template is giving us errors, see here:

![image](https://user-images.githubusercontent.com/48565067/83560091-a6220400-a4e3-11ea-889b-e53e5efb30c7.png)

We're seeing the ticket users phone number in place of the ticket number, and when I check here:
https://docs.osticket.com/en/latest/Admin/Emails/Templates.html

The template variables appear to be correct, any ideas?

Please let us know thanks

**Comment by JediKev** [comment]
@StewAlexanderACC 

>... however our email template is giving us errors, see here:

Just ignore the `Some variables may not be a valid ...` warning, the `%{response}` variable will still work in this template (we do some magic in the backend).

>We're seeing the ticket users phone number in place of the ticket number, ...

You most likely have a Custom Field with the variable name of `number` which is overwriting the Ticket Number variable. You must change the variable name of the Custom Field to something else, then you should see the Ticket Number where `%{ticket.number}` is placed. The Custom Field should be located in the Ticket Details Form (**Admin Panel > Manage > Forms**).

Cheers.

**Comment by StewAlexander-com** [comment]
I wasn't the original person who set this up, I don't see what you are suggesting

![image](https://user-images.githubusercontent.com/48565067/83561859-8dffb400-a4e6-11ea-9807-8022cfa8f526.png)

**Comment by JediKev** [comment]
@StewAlexanderACC 

The first value in the **Form Fields** section called **Contact Phone Number** is what I'm talking about. You see the Variable name for this field is `number`, which it cannot be otherwise it will override the `%{ticket.number}` variable. You will need to change the Variable name of `number` to something else.

Cheers.

**Comment by StewAlexander-com** [comment]
Ahh ok, changed it to phone_number

![image](https://user-images.githubusercontent.com/48565067/83562066-f058b480-a4e6-11ea-9a11-b563d6239e04.png)

**Comment by StewAlexander-com** [comment]
Thanks for the help awaiting confirmation of the fix, then will close out this ticket

**Comment by JediKev** [comment]
@StewAlexanderACC 

Any update on if this resolved the issue or not?

Cheers.

**Comment by StewAlexander-com** [comment]
Appears fixed, apparently we had the ticket phone number as the same alias as the ticket number, to correct the problem assigned the ticket phone number to "ticket.phone_number".

Haven't heard any gripes, so believe this resolved the issue, thanks for the support.
