### ISSUE TITLE
Username fields not populating correctly

### ISSUE THREAD

**Issue by unixbird** [osTicket/osTicket#5530]
### Description

Whenever I go to add a collaborator it doesnt search for all users and asks to instead make a new user. This also happens when creating a new ticket and acts like there isn't any other users in the system. I have tried this in a docker instance as well (test environment) and it does the same thing. This was working in 1.14.1 and has just recently stopped working.

I checked system logs and it doesn't give any logs concerning this (only me having login issues at one point)

### Versions
Osticket - 1.14.2
Apache - latest in debian 9
MySQL - 10.1.44
PHP - 7.0.33

This seems to occur in Chrome, Firefox, and QuteBrowser.

**Comment by JediKev** [comment]
@unixbird 

So you're saying the User Lookup is not returning results? I'm trying to understand what you mean exactly.

Cheers.

**Comment by unixbird** [comment]
@JediKev Sorry yes that is correct

**Comment by JediKev** [comment]
@unixbird 

What are you searching for? A name, email address? Could you give me exact steps to replicate?

Cheers.

**Comment by unixbird** [comment]
@JediKev I have tried both Email and username and it does not populate with suggestions and if you click add it errors out and says that I need to populate the name and email fields (when I go to search for a user in creating a ticket for example)

**Comment by JediKev** [comment]
@unixbird 

Do you use the LDAP plugin by chance?

Cheers.

**Comment by unixbird** [comment]
@JediKev It is enabled but has not yet been setup so all fields regarding that are blank

**Comment by JediKev** [comment]
@unixbird 

That's _probably_ the issue. Disable it and retest to confirm.

Cheers.

**Comment by unixbird** [comment]
@JediKev weeeeeell that was definitely it. I guess it was searching for AD users when it didn't have the information to look up those users

Thanks again!

**Comment by JediKev** [comment]
@unixbird 

Not a problem! Was wondering because I could not replicate this at all lol

Cheers.

**Comment by unixbird** [comment]
@JediKev weeeeeell that was definitely it. I guess it was searching for AD users when it didn't have the information to look up those users

Thanks again! 

EDIT: forgot to close issue
