### ISSUE TITLE
Expand signature field when Department signature is set

### ISSUE THREAD

**Issue by jokkz** [osTicket/osTicket#5531]
### Description

I've installed osticket 1.14 php7.3 and I look upon it's new features.
But what I've noticed is when the agent hangs on on the department signature with the mouse pointer when replying on the ticket it does not extend to see the whole signature like it was on 1.10.4.
Can someone point me how to get the same feature back? or is it some option in the settings which I'm missing

### Steps to Reproduce

On 1.10.4
![2OwXyLQC3F](https://user-images.githubusercontent.com/43546909/83652653-25363b80-a5bb-11ea-983b-0665a5545682.gif)

On 1.14.1
![gHvcDxQcHN](https://user-images.githubusercontent.com/43546909/83652712-38e1a200-a5bb-11ea-8333-6db5d322a9ee.gif)

Osticket - 1.14.1
PHP - 7.3

**Comment by JediKev** [comment]
@jokkz 

Here you go 🙂:
- https://github.com/osTicket/osTicket/pull/5534

Cheers.

**Comment by jokkz** [comment]
Great.
Tested and it works good. 
Cheers.
