### ISSUE TITLE
This action requires a lock. Please try again! osticket 1.14.2

### ISSUE THREAD

**Issue by cervedgroup** [osTicket/osTicket#5533]
Everytime i try to add response to a ticket i receive This action requires a lock. Please try again!  
Just upgraded and the problem was born 

The time of the lock is set to 1 min , i've tryed the lock in view and on activity mode , same result...

the timezone in osticket and on the server is the same

Web Server Software | Microsoft-IIS/8.5
MySQL | 10.3.14
PHP | 7.3.18

please help thank you

**Comment by cervedgroup** [comment]
in the ost_lock table the record is inserted when i try to edit a ticket, the time set in the record is correct ... 
but i can't add a response, everytime the "This action requires a lock. Please try again" show ...

**Comment by JediKev** [comment]
@cervedgroup 

This error occurs when Locks are enabled but no lock was created/returned. Since you say you see records being created in the db then something could be failing and causing `$ticket->getLock();` to return nothing. I would start by `var_dump()`ing in `function getLock` in `include/class.ticket.php`. My guess is that you have a timezone mismatch so when we call getLock the lock is "expired" so nothing is returned. 

Cheers.

**Comment by cervedgroup** [comment]
sorry @JediKev , where can i check the timezone mismatch ? 
should i have to put var_dump() in the function getlock in the include/class.ticket.php ? and then what i'll have to see ?

thank you

**Comment by cervedgroup** [comment]
@JediKev var_dump($lock) in the function getlock , return NULL

**Comment by cervedgroup** [comment]
when i insert a reply, 3 records are written in ost_lock and now it say "someone else could be working on the ticket"

![image](https://user-images.githubusercontent.com/6535381/83777099-4ebd9880-a689-11ea-895c-b81bcaa4d00a.png)

**Comment by JediKev** [comment]
@cervedgroup 

Three records created within 1ms of each other? That's _very_ strange. Can you TRUNCATE the lock table and see if it happens again? (be sure to clear all browser cache, etc.)

Cheers.

**Comment by cervedgroup** [comment]
@JediKev 
truncated the table, same result, 3 records created
![image](https://user-images.githubusercontent.com/6535381/83780031-f092b480-a68c-11ea-8899-f7c25474c2ab.png)

**Comment by cervedgroup** [comment]
we upgrated from v1.10.7 , maybe upgrading from that version is not supported ?

**Comment by JediKev** [comment]
@cervedgroup 

We support upgrading from 1.6 ST all the way to v1.14.2 so it is definitely supported. I don't know why 3 records are being created within milliseconds of each other...

I cannot replicate this with v1.14.2 (upgraded + fresh install), PHP 7.4 (and PHP 5.6), and MySQL 8.0 (and MySQL 5.5).

Cheers.

**Comment by cervedgroup** [comment]
@JediKev i followed the usual procedure to update .. we have a 55GB database and never had a problem like that ... i'll retry the operation, trying to truncate the ost_lock before the upgrade.... do you have any suggestions ?

**Comment by JediKev** [comment]
@cervedgroup 

Try it from multiple Staff Accounts from different computers/devices to see if it’s just you or multiple people.

Cheers.

**Comment by cervedgroup** [comment]
@JediKev hi, i've re-restored the db on the test vm , and all has gone without errors, in this case i've haven't upgraded the php (before the upgrade) that is still at 5.6 version. 
Can i leave this version of php or i 've to upgrade to 7.3 ?

**Comment by cervedgroup** [comment]
@JediKev i'm testing all the stuff after the upgrade, now i'm unable to assign a ticket assigned to me to another operator
![image](https://user-images.githubusercontent.com/6535381/84292895-49f45b00-ab47-11ea-8eaa-5276f2a53516.png)

if a claim an unassigned ticket , i can assign it to other operators ... the problem seems only for ticket already assigned to me before the upgrade

problem is present for all operators , not only my account ...
maybe if the smtp server is unreachable, the ticket reassigning fails ? the test server has no access to the mail server
