### ISSUE TITLE
Cannot Register user as there isn't an option to do so

### ISSUE THREAD

**Issue by unixbird** [osTicket/osTicket#5536]
### Description

A user has brought up that they werent able to login as they haven't registered. Me and another coworker found that there isn't a link to actually register a username. I found that we were missing the link by running a fresh install of osticket via docker. It had the link http://localhost:8080/account.php?do=create while our production install does not. If i try to insert my domain into that along with the account.php?do=create it takes me back to the create ticket screen. I'm not seeing any logs inside of osticket regarding this either but i did check the doc root and found that accounts.php does exist

### Versions
Osticket - 1.14.2
Apache - latest in debian 9
MySQL - 10.1.44
PHP - 7.0.33

This seems to occur in all browsers as well

![whatitssupposedtolooklike](https://user-images.githubusercontent.com/13972473/83810690-2ed4a780-a67e-11ea-96ba-755387b3c0c2.PNG)
![whatitcurrentlylookslike](https://user-images.githubusercontent.com/13972473/83810700-33995b80-a67e-11ea-84c8-88a9e9010e21.PNG)

**Comment by JediKev** [comment]
@unixbird 

Do you have your Registration Method set to Public so Users can register their own accounts, or do you have it set to Private which means only Agents can register User accounts, or do you have it set to Disabled which means registration is disabled? (**Admin Panel > Settings > Users > Settings > Authentications Settings > Registration Method**)

**Note:**
Github is a place to report bugs with the code, to create feature requests, or to make pull requests. Configuration related stuff like this, general questions, etc. should be posted on our [Forum](https://forum.osticket.com/) where our Community can assist you. If on there you find out it's a bug, then you can report it here.

Cheers.

**Comment by unixbird** [comment]
@JediKev 
Thats the setting that was missed wonder why some are registered and some arent already.. Roger on that will use forums next time. 

closing
