### ISSUE TITLE
Canned response enables WYSIWYG editor

### ISSUE THREAD

**Issue by killerbees19** [osTicket/osTicket#5547]
## Prerequisites
* [x] Can you reproduce the problem in a fresh installation of the "develop" branch? (YES)
* [x] Do you have any errors in the PHP error log, or javascript console? (NO)
* [x] Did you check the [osTicket forums](https://forum.osticket.com/)? (YES)
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported? (YES)

## Description
HTML editor mode gets enabled by canned response.

## Steps to Reproduce
1. Admin Panel » System » Enable Rich Text: Disabled
2. Open a ticket and scroll down to `Response` field
3. Select a canned response from dropdown list

**Expected behavior:** Insert canned response and stay in plaintext editor mode.

**Actual behavior:** Insert canned response and switch to WYSIWYG (HTML) editor mode.

![Bildschirmfoto_2020-06-15_22-20-49](https://user-images.githubusercontent.com/21372289/84703654-e60fcf00-af58-11ea-93ad-2a7ca9986c87.gif)

After submitting the reply you can see the HTML reply as plaintext above. Same applies for outgoing mail. The original quoted message ("Last Message") from customer was plaintext btw.

### Server
* Operating System: Debian 10
* osTicket Version: 1.14-git (741122a614ce61f998aabf8982d3bcbd6e376aaa)
* Web Server Software: nginx/1.14.2
* MySQL Version: 10.3.22 (MariaDB)
* PHP Version: 7.3.14-1~deb10u1 (but 5.6 - 7.4 from deb.sury.org available for tests)

#### PHP Extensions
* [x] gdlib
* [x] imap
* [x] xml
* [x] xml-dom
* [x] json
* [x] mbstring
* [x] phar
* [x] intl
* [x] fileinfo
* [x] zip
* [x] APCu
* [x] Zend Opcache

#### PHP Settings
* [x] cgi.fix_pathinfo
* [ ] date.timezone

### Client
* Operating System: Xubuntu 18.04
* Browser: Chromium 83.0.4103.61
* Browser addons disabled

**Comment by JediKev** [comment]
@killerbees19 

Thanks for the report. We will attempt to replicate this and get back to you.

Cheers.

**Comment by ajnyga** [comment]
Was this fixed in a newer version?

**Comment by killerbees19** [comment]
> Was this fixed in a newer version?

Seems to be true, can't reproduce at v1.16.x! 🥳
