### ISSUE TITLE
System Miss ticket.

### ISSUE THREAD

**Issue by jianfzhu** [osTicket/osTicket#5566]
we setup osticket fetching mail to create ticket. most time it work fine, but sometimes it will miss create ticket. user send mail can find in mail box and already moved to finished folder. but ticket system not create the ticket. no error message in system logs. what's problem? is it an issue in osticket?

**Comment by ntozier** [comment]
This does not appear to be a bug report and appears to be a question that would be better suited for the support forums at: https://forum.osticket.com

Please help us to help you by reading and following the posting guidelines located in this thread: [Please read before requesting assistance](https://forum.osticket.com/d/89131-please-read-before-requesting-assistance).  The more information you give us the better we will be able to assist you. Thank you.

Please include:
- Environment details (see **Admin panel -> Dashboard -> Information**)
- Mention any plugins that you are using.
- Any pertinent [unknown] webserver logs, PHP logs, etc.

Please close this bug report.
