### ISSUE TITLE
Security Issues found: Medium Severity

### ISSUE THREAD

**Issue by PeopleInside** [osTicket/osTicket#5578]
Hi, please compile the GitHub section telling how is possible to report security Issues!
Actually I found more than one Medium security issue on OsTicket.

I need understand how to report to you!

https://github.com/osTicket/osTicket/security

**Comment by JediKev** [comment]
@PeopleInside 

Please send all POCs to security[at]osticket[dot]com. We will also look into the security page.

Cheers.

**Comment by PeopleInside** [comment]
I will do immediately. Hope in a fix soon as I'm vulnerable...

**Comment by PeopleInside** [comment]
https://github.com/osTicket/osTicket/pull/5579

**Comment by PeopleInside** [comment]
@JediKev Security email report sent. Thank you, will wait from you a feedback.
