### ISSUE TITLE
Custom Field > Long Answer > links mangled

### ISSUE THREAD

**Issue by stevland** [osTicket/osTicket#5581]
v1.14.2

A custom form with a Long Answer field is added to the Ticket Details.

When the client adds more than one link to the Long Answer field, only one link is displayed.

**_Client submits:_**

![long-answer](https://stevland.com/misc/Image%20001.png)

**_Agents see:_**

![long-answer](https://stevland.com/misc/Image%20002.png)

Further, the Edit icon doesn't work when clicked.

It is apparent when looking at the source code that the Edit button is becoming entangled with the mangled code that results from more than one link.

![long-answer](https://stevland.com/misc/Image%20003.png)

**Comment by JediKev** [comment]
@stevland 

We've changed the way RichText fields work in the ticket view. You can upgrade to `v1.14.3` or apply the changes outlined in the following pull request:
- https://github.com/osTicket/osTicket/pull/5562

Cheers.

**Comment by JediKev** [comment]
Addressed with #5562
