### ISSUE TITLE
After OSTicket assisted us to upgrade emails are not being sent to 1 of our 2 domains

### ISSUE THREAD

**Issue by StewAlexander-com** [osTicket/osTicket#5592]
Hi all, after we purchased support for OSTicket to upgrade us from ```1.10.1``` to ```1.14.1``` emails are not being sent to one of our two domains.

What I mean is before we had tickets opened by people at @alamancecc.edu and and @access.alamancecc.edu and they would get automatic emails as updates were applied to the tickets.

Now, only people at our @alamancecc.edu are getting these automatic email from ticket updates.

How can we fix this?

**Comment by JediKev** [comment]
Relay access is denied at mail server level.
