### ISSUE TITLE
[BUG] Edit issue summary is broken

### ISSUE THREAD

**Issue by TechCare-Aus** [osTicket/osTicket#5601]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [x] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

Latest git commits (as of 07/AUG/2020). 
Issue changing the name of a support ticket. Everything appears to work like normal, but no change is made.

### Steps to Reproduce

1. Edit any support ticket
2. Change the issue summary
3. Save
4. No change is made

**Expected behavior:** [What you expected to happen]

Issue summary to change from old to new.

**Actual behavior:** [What actually happened]

Nothing changes. Although it does get recorded but where it normally says the change = nothing.

![image](https://user-images.githubusercontent.com/2740134/89605825-1b71d280-d8a1-11ea-9bd1-54709521422b.png)

### Versions

osTicket Version | v1.14.2-100-g46d2ea5f (46d2ea5) —  Up to date
Web Server Software | Apache
MySQL Version | 10.3.23
PHP Version | 7.3.20

I was running on PHP v7.4 but changed to v7.3 in case that was the problem. Still an issue.
No errors in PHP log.
No errors in the log inside osTicket.
No errors shown using the development options in Edge.
I've tried using Edge, Edge In Private, Chrome, FireFox Incognito. All experience the same issue.

**Comment by TechCare-Aus** [comment]
I believe something in the latest commit changes has caused this issue. Because it was working a day ago and I just updated to the latest commits this morning.

**Comment by TechCare-Aus** [comment]
@aydreeihn - is there anything I can do to help with this? Super annoying that I cannot change the Issue Summary at the moment. Totally get it that it's my own fault for running git version to by the way so no issue there :)

**Comment by aydreeihn** [comment]
@TechCare-Aus PR #5610 addresses the issue with being able to save fields at least. I am also working on a fix that will correct the thread events at the bottom of the ticket.

**Comment by TechCare-Aus** [comment]
@aydreeihn - just confirming that the #5610 has fixed the issue experienced. Thank you for that.
