### ISSUE TITLE
Reset user password for the first time

### ISSUE THREAD

**Issue by ThierryVerreyt** [osTicket/osTicket#5607]
### Prerequisites

* [ YES] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [ ] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

DB Error #3692

[DELETE `ost_session`.* FROM `ost_session` WHERE `ost_session`.`user_id` = 0 AND `ost_session`.`session_data` REGEXP '_auth\\|.*\"user\";[a-z]+:\\[0-9]+:{[a-z]+:[0-9]+:\"id\";[a-z]+:20']

Incorrect description of a {min,max} interval.<br /> <br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(200): osTicket->logDBError('DB Error #3692', '[DELETE `ost_se...')<br />
#1 (root)/include/class.orm.php(3466): db_query('DELETE `ost_ses...', true, true)<br />
#2 (root)/include/class.orm.php(1534): MySqlExecutor->execute()<br />
#3 (root)/include/class.auth.php(1380): QuerySet->delete()<br />
#4 (root)/include/class.signal.php(98): PasswordPolicy::cleanSessions(Object(User), NULL)<br />
#5 (root)/include/class.user.php(1213): Signal::send('auth.clean', Object(User))<br />
#6 (root)/include/class.user.php(1307): UserAccount->setPassword('Super-1')<br />
#7 (root)/include/class.client.php(425): UserAccount->update(Array, Array)<br />
#8 (root)/include/ajax.users.php(225): ClientAccount->update(Array, Array)<br />
#9 (root)/include/class.dispatcher.php(145): UsersAjaxAPI->manage('20')<br />
#10 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/20/manage', Array)<br />
#11 (root)/include/class.dispatcher.php(120): Dispatcher->resolve('/20/manage', Array)<br />
#12 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/users/20/manag...', NULL)<br />
#13 (root)/scp/ajax.php(311): Dispatcher->resolve('/users/20/manag...')<br />
#14 {main}

https://192.168.68.155/osTicket

### Steps to Reproduce

1.  a new user send a mail to the helpdesk
2. the user is automatically created int oosTicket
3. He recieve a mail to reset his password and he click on Signin he recieve an error

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about your server.
1.14
Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.
Linux CentOS 7 Mysql 8.21

**Comment by JediKev** [comment]
@ThierryVerreyt 

Please try searching the existing Issues/Pull Requests before creating an Issue, as this has already been reported and addressed. A quick search would've brought you to the fix here:
- https://github.com/osTicket/osTicket/pull/5492

Cheers.

**Comment by ThierryVerreyt** [comment]
Thanks for this 

 

Where do I need to fix this issue ? on which php file do I need to change it ?
