### ISSUE TITLE
trello 

### ISSUE THREAD

**Issue by mgalejandra** [osTicket/osTicket#5630]
https://github.com/jatacid/trello-simple https://github.com/kyleladd/OSTicket-Trello-Plugin

Buenas tardes quisiera saber que cambia en estos plugins que ya no funcionan en la nueva versión de osticket 1.14.3, al instalarlos muestra error 500 . Por favor necesito su ayuda

**Comment by ntozier** [comment]
You would need to contact the author of that 3rd party plugin.  We do not support other peoples plugins.

**Comment by JediKev** [comment]
@mgalejandra 

We did not develop those plugins; they are considered 3rd party plugins and are not officially supported. You will need to contact the developers of the plugins for further assistance.

Cheers.
