### ISSUE TITLE
Merge Ticket / Link Ticket functionality appears to be broken in 1.14.3

### ISSUE THREAD

**Issue by PromoFaux** [osTicket/osTicket#5632]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [x] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

It seems that since updating to 1.14.3 that both the "Merge Ticket" and "Link Ticket" functionality is no longer working, with the following message in the javascript console when clicking `Add a Ticket`

I have rolled back our instance to 1.14.2 and it is working again. Currently I'm not set up to be able to spin up a copy of the dev branch for further troubleshooting, sorry!

```
tickets.php?id=4301:25 Uncaught TypeError: Cannot read property 'toString' of undefined
    at HTMLButtonElement.onclick
```

### Steps to Reproduce

1. Update to 1.14.3
2. Try to merge two tickets

**Expected behavior:** [What you expected to happen]

Tickets merged

**Actual behavior:** [What actually happened]

Tickets not merged...

![image](https://user-images.githubusercontent.com/1998970/93197683-d8c6d400-f743-11ea-8cd4-9704f5b643cf.png)

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about your server.

1.14.3

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

Deployed in Docker using https://github.com/devinsolutions/docker-osticket

**Comment by JediKev** [comment]
@PromoFaux 

Search is your best friend:
- https://github.com/osTicket/osTicket/pull/5618

Cheers.

**Comment by PromoFaux** [comment]
Thanks @JediKev I did try a cursory search via issues, though I admit I neglected to check PRs... Thanks for the pointer.
