### ISSUE TITLE
Incorrect page numbering (paging) on some sections

### ISSUE THREAD

**Issue by toxpal** [osTicket/osTicket#5637]
Installed the latest version to test and noticed some sections display incorrect number of pages. For example, if page contains just a single record, osticket still displays multiple pages at the bottom. See example - https://i.postimg.cc/g2CG9Hc1/numbers.png

If I click on any page number, I see "No records found!" message and these numbers disappear - https://i.postimg.cc/Xvkm2frf/numbers.png

Happens on some sections only. So far, noticed this bug on Email Templates and System Logs sections.

**Comment by JediKev** [comment]
@toxpal 

This has been answered in other threads on Github and on the Forum but I'll post it here as well. The pagination for some pages and Searches are _hardcoded_ for now. There is an underlying issue we need to resolve first and once that's taken care of we will be able to provide accurate pagination again. Please stay tuned.

Cheers.

**Comment by toxpal** [comment]
Thanks, didn't find it, but it means I didn't search enough. Closing the issue.

**Comment by JediKev** [comment]
@toxpal 

No problem. I will post the links to the explanation and the commit message below for your notes.

Here is the explanation:
- https://github.com/osTicket/osTicket/issues/4972#issuecomment-532714220
- https://github.com/osTicket/osTicket/issues/4972#issuecomment-545956548

Here is the commit message:
- https://github.com/osTicket/osTicket/commit/170709bb4dc2db75b3a5a5d338874fbc353e1b1c

Cheers.
