### ISSUE TITLE
E-Mailed tickets do not use the reply-to header

### ISSUE THREAD

**Issue by jevansfbcmb** [osTicket/osTicket#5650]
Hi,

We're using a web form that sends emails to a mailbox at the moment, we've changed it to send to osticket and i've set up the filter for using the reply-to address as the form sends as no-reply however osticket seems to be ignoring the reply-to and just using the from address.

Thanks,
Jacob

System info is below

Server Information
--
osTicket Version | v1.14.1 (f1e9e88) 
Web Server Software | Apache/2.4.6 (CentOS) PHP/7.2.26
MySQL Version | 5.5.64
PHP Version | 7.2.26

gdlib | Used for image manipulation and PDF printing
imap | Used for email fetching
xml | XML API
xml-dom | Used for HTML email processing
json | Improves performance creating and processing JSON
mbstring | Highly recommended for non western european language content
phar | Highly recommended for plugins and language packs
intl | Highly recommended for non western european language content
fileinfo | Used to detect file types for uploads
zip | Used for ticket and task exporting
APCu | Improves overall performance
Zend Opcache | Improves overall performance

cgi.fix_pathinfo | "1" is recommended if AJAX is not working
date.timezone | Setting default time zone is highly recommended

Schema | osticket_db (localhost)
Schema Signature | 4bd47d94b10bd8a6bab35c119dadf41f
Space Used | 114.29 MiB
Space for Attachments | 63.52 MiB
Timezone | BST (Interpreted as Europe/London)

**Comment by JediKev** [comment]
@jevansfbcmb 

Please upgrade to v1.14.3 and retest. Also post a screenshot of the raw headers so we can take a look (redact any sensitive info).

Cheers.

**Comment by protich** [comment]
osTicket doesn't use reply-to by default - you'll need to setup a filter to enable it.

**Comment by jevansfbcmb** [comment]
Hi Peter,

I do have a filter enabled for this, It just isn’t working.

JediKev has advised to update so I will try that.

Kind Regards,
Jacob

 Jacob Evans
 System Support and Development

**Comment by JediKev** [comment]
@jevansfbcmb 

If you upgrade and that doesn’t help please post screenshots of the entire filter. This includes the configuration, rules, and actions. You will also need to include a screenshot of the entire raw headers (redacting any sensitive info). Once we have this information we can better assist.

Cheers.

**Comment by jevansfbcmb** [comment]
Hi,

Okay no problem, will do.







 Jacob Evans
 System Support and Development

**Comment by toxpal** [comment]
I also had the same problem (using the latest version) - emails were not sent to Reply-To address from header even if filter is enabled. Also using custom form on website (Contact Form 7 for WordPress).

Here are email headers:

```
Return-Path: <accountname@server-hostname.com>
Delivered-To: my@email.com
Received: from server-hostname.com
	by server-hostname.com with LMTP
	(envelope-from <accountname@server-hostname.com>)
	for <my@email.com>; Mon, 19 Oct 2020 18:44:24 +0300
Return-path: <accountname@server-hostname.com>
Envelope-to: my@email.com
Delivery-date: Mon, 19 Oct 2020 18:44:24 +0300
Received: from accountname by server-hostname.com with local (Exim 4.93)
	(envelope-from <accountname@server-hostname.com>)
	for my@email.com; Mon, 19 Oct 2020 18:44:24 +0300
To: my@email.com
Subject: Email Subject
X-PHP-Script: www.website.com/index.php
X-PHP-Originating-Script: 1009:PHPMailer.php
Date: Mon, 19 Oct 2020 15:44:24 +0000
From: Client Name <my@email.com>
Reply-To: user@email.com
X-Mailer: PHPMailer 6.1.6 (https://github.com/PHPMailer/PHPMailer)
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
```

Tried these filters so far, but only one worked for some reason:

https://i.postimg.cc/FHW80dTL/1.png (worked)
https://i.postimg.cc/WzvHsM1Q/2.png (didn't work)
https://i.postimg.cc/J05d0Gyt/3.png (didn't work)

**Comment by JediKev** [comment]
@toxpal 

I assume that `my@email.com` in your example is configured as a System Email. If that’s the case, we do not match System Emails with the `Adressee (To and CC)` option. We do however match System Emails with the `User / Email Address` option so that’s why that Filter works and the other two don’t.

Cheers.

**Comment by JediKev** [comment]
@toxpal 

When using the `User / Email Address` Filter, does it use the Reply-To address as it should? Or even when using that filter it doesn’t use the Reply-To address?

Cheers.

**Comment by toxpal** [comment]
Yes, `my@email.com` is configured as system email (the one which osticket parses emails from).

When using the `User / Email Address` filter, it works properly. In other words, when I reply to the ticket from osticket, it properly sends a reply to email address specified in `Reply-To` header. Tested using 3 different emails so far, everything works fine.

**Comment by JediKev** [comment]
@toxpal 

Okay, awesome. Yea, I'm going to bet that's @jevansfbcmb issue as well, using the `Addressee (To and CC)` expecting it to match a System Email.

Cheers.

**Comment by jevansfbcmb** [comment]
@JediKev 

Thank You, That does indeed now seem to work for me.

Thanks
