### ISSUE TITLE
API attachments do not work in JSON

### ISSUE THREAD

**Issue by bandwidth543** [osTicket/osTicket#5672]
I have similar problem as in #3406.

I sent the following JSON to the osticket's API:
```
{"email":"test@email.com","name":"test name","subject":"test subject","message":"data:text\/plain,test message","attachments":{"testfile.txt":"data:text\/plain;charset=utf-8,content of attachment"}}
```

osticket's API created this ticket and returned an ID to me. `Ticket ID: 490139`

After logging into the system, the ticket attachment was not added. `SYSTEM; File Import Error; Unable to save file`

![1](https://user-images.githubusercontent.com/73256190/97112940-6c96a300-16e7-11eb-888e-25352ebbcd53.png)
![2](https://user-images.githubusercontent.com/73256190/97112941-6ef8fd00-16e7-11eb-967a-77aa3a4ac7cb.png)

What am I doing wrong? What causes this error?

**Comment by JediKev** [comment]
@bandwidth543 

Please go back and fill out the entire Issue Report template. We need essential information such as version of osTicket, PHP, etc. Without this information it will be difficult to accurately replicate and debug.

**Questions in the meantime:**
- Are you using a storage plugin such as Filesystem or S3?
- What are the contents of the file you’re posting? I see you’re trying to add a plaintext attachment, are you certain the contents are in fact plaintext?
- Do you see any related errors in any of your logs (server logs, Apache/IIS error logs, PHP error logs, MySQL/MariaDB error logs, osTicket system logs)?

Cheers.

**Comment by ntozier** [comment]
Two additional questions:
- whats the filesize of the attachment and is it larger then you have allowed at: **Admin panel -> Settings -> Tickets -> Attachments**
- is .txt configured as an allowed file type (same location)

**Comment by bandwidth543** [comment]
I'm sorry for the time and inaccurate information.

### Answers

> Are you using a storage plugin such as Filesystem or S3?

no

> What are the contents of the file you’re posting? I see you’re trying to add a plaintext attachment, are you certain the contents are in fact plaintext?

whole test file:

```
'testfile.txt', 'data:text/plain;charset=utf-8,content of attachment'
```

> Do you see any related errors in any of your logs (server logs, Apache/IIS error logs, PHP error logs, MySQL/MariaDB error logs, osTicket system logs)?

totally none

> whats the filesize of the attachment and is it larger then you have allowed at: Admin panel -> Settings -> Tickets -> Attachments

21 bytes; No, is set to 32 MB

> is .txt configured as an allowed file type (same location)

yes


### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch? **yes**
* [ ] Do you have any errors in the PHP error log, or javascript console? **no**
* [x] Did you check the [osTicket forums](https://forum.osticket.com/)? **yes**
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported? **yes**

### Steps to Reproduce

1. Create fresh osTicket's develop environment
2. Go to Admin Panel -> Settings -> Tickets -> Attachments -> Config

Max File Size: 32 MB
Restrict by File Type: Select all
Additional File Type Filters: .txt

3. Save
4. Go to Admin Panel -> Settings -> Tickets and write Maximum Open Tickets: 0
5. Save
6. Go to Admin Panel -> Manage -> API
Create new key with `Can Create Tickets` and `Can Execute Cron`
7. Create new ticket with code below (change url and api code)

**Expected behavior:** [What you expected to happen]

Create a new ticket with an attachment by API.

**Actual behavior:** [What actually happened]

I can't provide attachment by API. API return to me:

```
Ticket ID: 

Warning:  reset() expects parameter 1 to be array, string given in C:\xampp\htdocs\osTicket-develop\include\class.api.php on line 408



Warning:  key() expects parameter 1 to be array, string given in C:\xampp\htdocs\osTicket-develop\include\class.api.php on line 414

794116
```

### Versions
```
osTicket's Last commit: https://github.com/osTicket/osTicket/commit/5c1b3a1af5e23e25c0d5316af1c356f6db510b5d
XAMPP: 7.3.23 / PHP 7.3.23
PHP Version: 7.3.22 with Zend OPcache 7.3.22
Database: mySQL 10.4.14-MariaDB
System: Windows 10 build 18363 AMD64
Browser: Mozilla Firefox 82.0.2 (64 bits)
```
About this osTicket Installation:
```
osTicket Version: 1.14-git (?) — f4f5bc6 is available
Web Server Software: Apache/2.4.46 (Win64) OpenSSL/1.1.1g PHP/7.3.22
MySQL Version: 10.4.14
PHP Version: 7.3.22
Extensions enabled (all): gdlib imap xml xml-dom json mbstring phar intl fileinfo zip APCu Zend Opcache
cgi.fix_pathinfo = 1
date.timezone: Europe/Berlin
Schema: osticketdevelop (localhost)
Schema Signature: 4bd47d94b10bd8a6bab35c119dadf41f 
Space Used: 2.66 MiB
Space for Attachments: 0.03 MiB
Timezone: Europe/Berlin
```

### Source Code
```PHP
<?php

class Ticket {
    protected $settings;
    protected $data;

    function __construct($settings) {
        $this->settings = array();
        $this->settings['url'] = $settings['url'];
        $this->settings['key'] = $settings['key'];

        $this->data = array();
    }

    public function send_ticket() {
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_USERAGENT, 'osTicket API Client');
        curl_setopt($ch, CURLOPT_URL, $this->settings['url']);
        curl_setopt($ch, CURLOPT_HTTPHEADER, array('X-API-Key: ' .
          $this->settings['key']));
        curl_setopt($ch, CURLOPT_POST, TRUE);
        curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($this->data));
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
        curl_setopt($ch, CURLOPT_HEADER, FALSE);
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, FALSE);

        $result = curl_exec($ch);

        if($result === FALSE) {
            curl_close($ch);
            set_time_limit(30);
            return array(-1, NULL, NULL);
        }

        $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        curl_close($ch);

        if($code != 201) {
            set_time_limit(30); 
            return array(-2, $code, $result);
        }

        set_time_limit(30);

        return array(0, $code, $result);
    }

    public function set_email($str) {
        $this->data['email'] = $str;
    }

    public function set_name($str) {
        $this->data['name'] = $str;
    }
    
    public function set_subject($str) {
        $this->data['subject'] = $str;
    }
    
    public function set_message($str, $type='plain') {
        switch($type) {
            case 'plain': {
                $type = 'data:text/plain,';
                break;
            }

            case 'html': {
                $type = 'data:text/html,';
                break;
            }

            default: {
                return FALSE;
            }
        }

        $this->data['message'] = $type . $str;

        return TRUE;
    }

    public function add_attachment($filename, $raw_content) {
        if(!isset($this->data['attachments'])) {
            $this->data['attachments'] = array();
        }

        $this->data['attachments'][$filename] = $raw_content;
    }
}

/* ************************************************************************** */

$ticket = new Ticket(array(
    'url' => 'http://127.0.0.1/osticket-develop/api/tickets.json',
    'key' => '382A132BE130C47D5590549E5011B6FB'
));

$ticket->set_email('test@email.com');
$ticket->set_name('test name');
$ticket->set_subject('test subject');
$ticket->set_message('test message');
$ticket->add_attachment('testfile.txt',
    'data:text/plain;charset=utf-8,content of attachment');

$result = $ticket->send_ticket();

switch($result[0]) {
    case 0: {
        echo 'Ticket ID: ' . $result[2];
        break;
    }

    case -1: {
        echo 'cURL error';
        break;
    }

    case -2: {
        echo "osTicket's API error" . '<br>';
        echo "code: " . $result[1]  . '<br>';
        echo "msg: "  . $result[2]  . '<br>';
        break;       
    }
}
```

**Comment by JediKev** [comment]
@bandwidth543 

Ah, so the issue is that you are adding files directly inside the `$this->data['attachments']` array. The API actually expects each file to be it's own array. So in your script instead of doing:
```php
$this->data['attachments'][$filename] = $raw_content;
```
... you should be doing:
```php
$this->data['attachments'][] = array($filename => $raw_content);
```

Make that change, retest, and if confirmed that works, please close this issue. 🙂

Cheers.

**Comment by bandwidth543** [comment]
It works. Thank you very much for help.

I had not noticed this important detail before.
