### ISSUE TITLE
Upgrade to 1.15.0 - blank page

### ISSUE THREAD

**Issue by JtheBAB** [osTicket/osTicket#5707]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [X] Do you have any errors in the PHP error log, or javascript console?
* [X] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [X] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

When i upgrade from 1.14.4 to 1.15.0 i got a blank page as soon as i add my ost-config.php.

### Steps to Reproduce

1. Install 1.15.0
2. Webpage is there
3. copy ost-config.php from 1.14.4 back 
4. Webpage blank

**Expected behavior:** 
Webpage is here.

**Actual behavior:**
Webpage is blank and this error is logged:

PHP Parse error:  syntax error, unexpected '|', expecting variable (T_VARIABLE) in /srv/www/include/class.auth.php on line 1089

### Versions

Web Server Software | Apache/2.4.25 (Debian) OpenSSL/1.0.2u
MySQL Version | 10.1.47
PHP Version | 7.0.33-0+deb9u10

**Comment by JediKev** [comment]
@JtheBAB 

Strange...our lint tests didn't catch this 🤔 Go to `include/class.auth.php` line `1089` and add another `|` to make it `BadPassword || ExpiredPassword $ex`.

Cheers.

**Comment by JtheBAB** [comment]
unfortunately i got now:

PHP Parse error:  syntax error, unexpected '||' (T_BOOLEAN_OR), expecting variable (T_VARIABLE) in /srv/www/include/class.auth.php on line 1089

**Comment by JediKev** [comment]
@JtheBAB 

So I was informed that `|` is how you chain exceptions, so `BadPassword | ExpiredPassword $ex` was the correct way. I do not see this error in my local instance using PHP 7.4. Maybe try upgrading to PHP 7.1.x-7.4.x or above to see if that clears the error for you. If so we will update the Minimum Requirements on our website.

Cheers.

**Comment by JtheBAB** [comment]
@JediKev 

I can confirm that 1.15 is now working when i upgrade from debian stretch to buster. This upgrade changes my php version to 7.3.19-1~deb10u1 and with this 1.15 is working.

**Comment by francoisPE** [comment]
I confirm
php7.0 same issue
php7.4 no issue works well
May be on https://osticket.com/download/ : version 1.15 is written with php7.0 should be modified

**Comment by JediKev** [comment]
@JtheBAB 

Okie doke. We'll update the minimum requirements to say v1.15 requires at least PHP 7.1.

Cheers.

**Comment by kirilkorukov** [comment]
I had the same problem and upgrading the php version did indeed help. Thank you!

**Comment by surfaceHH** [comment]
got the same error under Ubuntu with PHP 7.4.13 (cli) (built: Nov 28 2020 06:24:43) ( NTS )
but I tested all versions from 7.1 to 7.4 :( any Ideas?

**Comment by ntozier** [comment]
@surfaceHH starting with 1.15 osTicket requires PHP 7.2 to 7.4.  If you upgraded your webservers PHP then I am sure that you restarted the webserver after each change, right?

**Comment by surfaceHH** [comment]
sure I'm trying updated from 1.14.1 to the latest Update so 1.15.1.
