### ISSUE TITLE
[BUG] Database error after installing Audit plugin

### ISSUE THREAD

**Issue by antiuser** [osTicket/osTicket#5719]
### Prerequisites

* [NO] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [NO] Do you have any errors in the PHP error log, or javascript console?
* [YES] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [YES] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

After installing Audit plugin i have a DB error in info panel
 DB Error #1062
[INSERT INTO `_event` VALUES ("", "login", ""), ("", "logout", ""), ("", "message", ""), ("", "note", "")] Duplicate entry 'login' for key 'name'

---- Трассировка ----
#0 (корень)/include/mysqli.php(201): osTicket->logDBError()
#1 phar://(корень)/include/plugins/audit.phar/class.audit.php(810): db_query()
#2 phar://(корень)/include/plugins/audit.phar/audit.php(162): AuditEntry::autoCreateTable()
#3 (корень)/scp/plugins.php(26): AuditPlugin->enable()
#4 {main}

### Steps to Reproduce

1. get plugin from osticket.com
2. place phar plugin file in include/plugins
3. install plugin over web interface
4. see an error in info panel

**Expected behavior:** [What you expected to happen]
install plugin without errors
**Actual behavior:** [What actually happened]
install plugin with error
### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about your server.
![Снимок экрана_2020-11-30_14-47-47](https://user-images.githubusercontent.com/5499424/100594086-0838b600-331b-11eb-940b-d6bb54ce2b9d.png)

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.
Debian x64

**Comment by aydreeihn** [comment]
The issue has now been addressed within the plugin, and the download is fixed on the website.

**Comment by antiuser** [comment]
@aydreeihn thank you, Adriane! :) This is fix problem
