### ISSUE TITLE
HTML Template "Powered by osTicket" image size issue (Outlook2013)

### ISSUE THREAD

**Issue by ntozier** [osTicket/osTicket#572]
osTicket Version: 1.8.0.1
New Ticket notification

I've been playing a lot with the HTML email templates in the last week (after finally switching over to them on my production server) and noticed that stock templates with the osTicket log do not look right under Outlook 2013 (see screen cap).

![ost-html-email-bottom-in-outlook2013](https://f.cloud.github.com/assets/1315768/2198339/1f313f1c-98c7-11e3-8a61-8cdb171424ea.png)

This appears to be caused by the html code for displaying the image:

_img style="width: 126px" alt="Powered By osTicket" src="cid:b56944cb4722cc5cda9d1e23a3ea7fbc@89940214d002" height="126" width="126"_

It's important to note that the width is being set twice (once as a css style, and once as an img width tag), one of these should be removed.  The root cause of the image being the wrong dimensions however appears to be the img height attribute.  The image itself is actually 239x36.

**Comment by Dorian-Grim** [comment]
This is fixed long since, you guys can close :D
