### ISSUE TITLE
What is IOException: Unable to read resource content

### ISSUE THREAD

**Issue by jevansfbcmb** [osTicket/osTicket#5721]
### Description

Apologies if this isn't the right place but What does the below mean?

/uploads/l/lIS05WcCrCncLCzMCQU9YPitjPTSKifM:Unable to open for reading

#0 (root)/include/class.file.php(472): FilesystemStorage->write('Received: from ...')
#1 (root)/include/class.forms.php(3686): AttachmentFile::create(Array)
#2 (root)/include/class.mailfetch.php(848): FileUploadField->uploadAttachment(Array)
#3 (root)/include/class.mailfetch.php(939): MailFetcher->createTicket(1)
#4 (root)/include/class.mailfetch.php(1019): MailFetcher->fetchEmails()
#5 (root)/include/class.cron.php(25): MailFetcher::run()
#6 (root)/include/class.cron.php(110): Cron::MailFetcher()
#7 (root)/include/api.cron.php(19): Cron::run()
#8 (root)/include/api.cron.php(40): CronApiController->run()
#9 (root)/api/cron.php(23): LocalCronApiController::call()
#10 {main}

### Versions

Server Information
--
osTicket Version | v1.14.1 (f1e9e88)  Upgrade— v1.14.4 is available
Web Server Software | Apache/2.4.6 (CentOS) PHP/7.2.26
MySQL Version | 5.5.64
PHP Version | 7.2.26

gdlib | Used for image manipulation and PDF printing
imap | Used for email fetching
xml | XML API
xml-dom | Used for HTML email processing
json | Improves performance creating and processing JSON
mbstring | Highly recommended for non western european language content
phar | Highly recommended for plugins and language packs
intl | Highly recommended for non western european language content
fileinfo | Used to detect file types for uploads
zip | Used for ticket and task exporting
APCu | Improves overall performance
Zend Opcache | Improves overall performance

cgi.fix_pathinfo | "1" is recommended if AJAX is not working
date.timezone | Setting default time zone is highly recommended

Schema | osticket_db (localhost)
Schema Signature | 4bd47d94b10bd8a6bab35c119dadf41f
Space Used | 132.08 MiB
Space for Attachments | 72.52 MiB
Timezone | GMT (Interpreted as Europe/London)

**Comment by JediKev** [comment]
@jevansfbcmb 

It means osTicket cannot find or open the file data for the attachment in question. Either the file data was never added to the filesystem or the permissions/ownership of the files are incorrect.

Cheers.

**Comment by jevansfbcmb** [comment]
Thanks for your help
