### ISSUE TITLE
Valid CSRF Token Required php 7.4

### ISSUE THREAD

**Issue by Ressy66** [osTicket/osTicket#5722]
[Description of the bug or feature]
unable to login after php and osticket upgrade

### Steps to Reproduce

1. []was on ost 1.10, upgraded to current version
2. [ upgraded php 5.6 to 7.4
3. [ try login to continue the upgrade process

results in    white screen of death displaying      Valid CSRF Token Required
**Expected behavior:** [What you expected to happen]

to be able to log in :)

**Actual behavior:** [What actually happened]

as above unable to login to continue upgrade process or do anything at all

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about your server.
cant login to get it, but - 
apache 2.4.46
php 7.4.12

Tue Dec 01 10:19:07.719685 2020] [php7:warn] [pid 1258:tid 139763705165568] [client x,x,x,x:35757] PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/helpdesk/include/class.osticket.php on line 439, referer: https://helpdesk.xxxxxxxxxxxxxxxx.xxx/scp/login.php

[Tue Dec 01 10:19:07.766509 2020] [php7:warn] [pid 1258:tid 139763705165568] [client x.x.x.x:35757] PHP Warning:  session_start(): Failed to read session data: user (path: ) in /var/www/helpdesk/include/class.ostsession.php on line 86, referer: https://helpdesk.xxxxxxxxxxxxxxxx.xxx/scp/login.php

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.
slackware -current

**Comment by JediKev** [comment]
@Ressy66 

I don’t know what version you attempted to upgrade to but both versions currently available on our website (v1.14.4 and v1.15) have a fix for the `continue 2` warning mentioned. See below:
- https://github.com/osTicket/osTicket/blame/develop/include/class.osticket.php#L439
- https://github.com/osTicket/osTicket/blame/v1.14.4/include/class.osticket.php#L439

I would highly suggest attempting the upgrade with the latest stable version v1.15. This will rule out using old code with PHP 7.4. Also, for good measure you should clear your cache and cookies. Sometimes browsers get stuck on bad sessions.

Cheers.

**Comment by Ressy66** [comment]
Hi JediKev,

strange, It was 1.15 - downloaded from the website just under 24 hours ago

uploaded all files over the top of existing from 1.10.7 (apart from scripts and ost config file as per upgrade instructions)
Ill flush caches too and report back.

Thanks

**Comment by Ressy66** [comment]
Ok everything flushed, yes, I get same error
is it safe to wipe out all directories  upload fresh and re-copy back the ost-config?

I also still get the session path error, it does point to a valid location, perms are correct as a blog can write to it

**Comment by Ressy66** [comment]
After searching the tree, the only files remain  with old timestamps are  css/redactor-font.eot
js/jquery-3.4.0.min.js   all other files except  include/ost-config.php hold Nov 17 timestamp, safe to delete those two files I guess?

**Comment by JediKev** [comment]
@Ressy66 

Nah you need those files. Interesting situation here. Can you open the file and go to the line shown in the error (`include/class.osticket.php` line `439`) and see if it says `continue 2;`?

Cheers.

**Comment by Ressy66** [comment]
@JediKev

It sure does.  could this be related to the other issue or you don't think they are? 

(I initially used the source tar.gz - but earlier today used the zip -almost identical, bootstrap file differs but only by spacing, but the error  remains after installing the zip contents over top of it anyway.)

cheers

**Comment by Ressy66** [comment]
Hrmm there is  a bare " continue "  at line 430 however?   But my php knowledge  is zilch so that may be normal

**Comment by Ressy66** [comment]
Resolved:   I wiped out the web dirs and started fresh extraction, this time it took scp took me to hte database migration, and all seems well, no idea what went wrong,  I uplaoded the "upload" stuff, twice now, no go,  rm -rf, and extract fresh, worked.
