### ISSUE TITLE
[BUG] Editing advanced search results in an empty window

### ISSUE THREAD

**Issue by antiuser** [osTicket/osTicket#5740]
### Prerequisites

* [YES] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [NO] Do you have any errors in the PHP error log, or javascript console?
* [YES] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [YES] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

When i create a standard advanced search with any creteria and then trying to edit this search i get blank stripe
### Steps to Reproduce

1. Create new advanced search and apply this
2. Click configure rightly of advanced search
3. Click Edit
4. Get blank stripe

**Expected behavior:** [What you expected to happen]
Get a window with editable params
**Actual behavior:** [What actually happened]
Get a white stripe

### Versions
check this issue on 1.15.0 and 1.15.1
Admin panel -> Dashboard -> Information which also additionally gives you information about your server.
![Снимок экрана_2020-12-08_12-34-03](https://user-images.githubusercontent.com/5499424/101453790-b4008800-3951-11eb-99ee-7e67219e64b2.png)

For more information i record gif
![qqq](https://user-images.githubusercontent.com/5499424/101454501-e8c10f00-3952-11eb-8bb3-9403f6b12312.gif)

Also nginx configuration:
````
set $path_info "";        # Deny access to all files in the include directory        

location ~ /include {
    deny all;
    return 403;
}

location / {
    try_files   $uri $uri/ index.php;
    index  index.php;
}
 
if ($request_uri ~ "^/api(/[^\?]+)") {
    set $path_info $1;
}
 
if ($request_uri ~ "^/scp/.*\.php(/[^\?]+)") {
    set $path_info $1;
}
 
if ($request_uri ~ "^/.*\.php(/[^\?]+)") {
    set $path_info $1;
}
 
location ~ ^/scp/ajax.php/.*$ {
    try_files $uri $uri/ /scp/ajax.php?$query_string;
}
 
location ~ ^/ajax.php/.*$ {
    try_files $uri $uri/ /ajax.php?$query_string;
}
 
location ~ ^/api/(?:tickets|tasks).*$ {
    try_files $uri $uri/ /api/http.php?$query_string;
}
 
# pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
# or a unix socket.
#
location ~ \.php$ {
    include             fastcgi_params;
    fastcgi_param       SCRIPT_FILENAME  $request_filename;
    # fastcgi_pass        127.0.0.1:9000;
    # The socket approach requires the module php5-fpm
    fastcgi_pass        unix:/var/run/php/php7.4-fpm.sock;
}
 
# deny access to .htaccess files, if Apache's document root
# concurs with nginx's one
#
location ~ /\.ht {
    deny  all;
}
````
Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.
Debian 9 x64

**Comment by JediKev** [comment]
@antiuser 

Two things:
1.) Check all error logs for related errors. (Server Logs, NGINX Error Logs, PHP Error Logs, MySQL Error Logs, osTicket System Logs, Browser Console Logs)
2.) Test the same with Apache as I can’t replicate this issue locally.

Cheers.

**Comment by antiuser** [comment]
@JediKev
No problem if using Apache, but im found problem in Chrome dev tools
```
GET http://test.osticket.local/scp/ajax.php/tickets/search/adhoc%2C2t7yY8bel8 400 (Bad Request)
send @ jquery-3.5.1.min.js?d5ee0df:2
ajax @ jquery-3.5.1.min.js?d5ee0df:2
S.fn.load @ jquery-3.5.1.min.js?d5ee0df:2
$.dialog @ scp.js?d5ee0df:658
(anonymous) @ scp.js?d5ee0df:731
dispatch @ jquery-3.5.1.min.js?d5ee0df:2
v.handle @ jquery-3.5.1.min.js?d5ee0df:2
```

May be you are know how to fix it?

**Comment by JediKev** [comment]
@antiuser 

That is not helpful unfortunately. You will need to check your NGINX error logs, PHP error logs, and MySQL error logs for any related errors. Typically when you get a blank popup there is a fatal error being thrown somewhere which should be logged in one of the above error logs.

Cheers.

**Comment by antiuser** [comment]
@JediKev 

Im extended nginx error log with notice and rewrite_log on;
After that im click on Advanced Search parameter to get blank screen and found something in error.log

````
2021/01/14 10:17:28 [notice] 22416#22416: *401679 "^/api(/[^\?]+)" does not match "/scp/ajax.php/tickets/search/adhoc%2C2t7yY8bel8", client: 10.232.1.37, server: test.osticket.local, request: "GET /scp/ajax.php/tickets/search/adhoc%2C2t7yY8bel8 HTTP/1.1", host: "test.osticket.local", referrer: "http://test.osticket.local/scp/tickets.php?queue=adhoc"
2021/01/14 10:17:28 [notice] 22416#22416: *401679 "^/scp/.*\.php(/[^\?]+)" matches "/scp/ajax.php/tickets/search/adhoc%2C2t7yY8bel8", client: 10.232.1.37, server: test.osticket.local, request: "GET /scp/ajax.php/tickets/search/adhoc%2C2t7yY8bel8 HTTP/1.1", host: "test.osticket.local", referrer: "http://test.osticket.local/scp/tickets.php?queue=adhoc"
2021/01/14 10:17:28 [notice] 22416#22416: *401679 "^/.*\.php(/[^\?]+)" matches "/scp/ajax.php/tickets/search/adhoc%2C2t7yY8bel8", client: 10.232.1.37, server: test.osticket.local, request: "GET /scp/ajax.php/tickets/search/adhoc%2C2t7yY8bel8 HTTP/1.1", host: "test.osticket.local", referrer: "http://test.osticket.local/scp/tickets.php?queue=adhoc"
2021/01/14 10:17:28 [notice] 22416#22416: *401679 "^/api(/[^\?]+)" does not match "/scp/ajax.php/tickets/search/adhoc%2C2t7yY8bel8", client: 10.232.1.37, server: test.osticket.local, request: "GET /scp/ajax.php/tickets/search/adhoc%2C2t7yY8bel8 HTTP/1.1", host: "test.osticket.local", referrer: "http://test.osticket.local/scp/tickets.php?queue=adhoc"
2021/01/14 10:17:28 [notice] 22416#22416: *401679 "^/scp/.*\.php(/[^\?]+)" matches "/scp/ajax.php/tickets/search/adhoc%2C2t7yY8bel8", client: 10.232.1.37, server: test.osticket.local, request: "GET /scp/ajax.php/tickets/search/adhoc%2C2t7yY8bel8 HTTP/1.1", host: "test.osticket.local", referrer: "http://test.osticket.local/scp/tickets.php?queue=adhoc"
2021/01/14 10:17:28 [notice] 22416#22416: *401679 "^/.*\.php(/[^\?]+)" matches "/scp/ajax.php/tickets/search/adhoc%2C2t7yY8bel8", client: 10.232.1.37, server: test.osticket.local, request: "GET /scp/ajax.php/tickets/search/adhoc%2C2t7yY8bel8 HTTP/1.1", host: "test.osticket.local", referrer: "http://test.osticket.local/scp/tickets.php?queue=adhoc"

````
Maybe this helped to solve this.
Thanks

**Comment by JediKev** [comment]
@antiuser 

Okay, so the issue is definitely looking like the NGINX side of things and not osTicket. You will most likely need to update your NGINX config FROM:
```
location ~ ^/scp/ajax.php/.*$ {
    try_files $uri $uri/ /scp/ajax.php?$query_string;
}
```
TO:
```
location ~ ^/scp/ajax.php/(.*)$ {
    try_files $uri $uri/ /scp/ajax.php?$query_string;
}
```

Apply the above changes, restart NGINX completely, and retest.

Cheers.

**Comment by JediKev** [comment]
@antiuser 

After looking deeper, the issue is due to NGINX double encoding the path info. To workaround this you can go to `scp/ajax.php` and change line `196` FROM:
```
url_get('^/adhoc,(?P<key>[\w=/+]+)$', 'getAdvancedSearchDialog'),
```
TO:
```
url_get('^/adhoc(,|%252C|%2C)(?P<key>[\w=/+]+)$', 'getAdvancedSearchDialog'),
```

Once you make those changes you should be able to edit the Advanced Search.

**P.S.**
This is why we don't recommend using NGINX as there are too many changes you have to make to the Recipe and the software itself just to get it to function. You should look into switching to Apache to avoid these types of issues.

Cheers.

**Comment by antiuser** [comment]
@JediKev thank you Kev! This change helped me.
I know that NGINX not supported officially, but our ISP has a standard using NGINX as web server.
Im assume we had not anymore problems with that.
