### ISSUE TITLE
/scp/login.php does not redirect if already logged in

### ISSUE THREAD

**Issue by sevmonster** [osTicket/osTicket#5741]
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

If you navigate back to `/scp/login.php` you will not be automatically redirected to `/scp/` if you are already logged in. This caused an issue with the CAS plugin [here](https://github.com/kevinoconnor7/osTicket-auth-cas/issues/28).

~This is a regression, as login.php would redirect you to `/scp/` in versions prior to 1.15.1. I do not know where exactly this change was introduced but I imagine it has something to do with all the 2FA changes.~ Apparently it was always broken.

### Steps to Reproduce

1. Sign in to the Staff Control Panel.
2. Navigate back to `/scp/login.php`.

**Expected behavior:** You are redirected to `/scp/`

**Actual behavior:** You are presented with the login page in full.

### Versions

![image](https://user-images.githubusercontent.com/16788697/101499268-b0a9d400-3932-11eb-8b0a-4a145c7bdc1f.png)
As usual, test commits on top of `develop` head fe1d1f82245da28197c9491f16ff751c2da30804

Vivaldi 3.5.2115.54 (Chromium 87.0.4280.66)
Windows 10

**Comment by JediKev** [comment]
@ds6 

Here is the patch:
- https://github.com/osTicket/osTicket/pull/5768

Btw, this has always been an issue. Every version I tested showed the same issue (`1.10.x`, `1.12.x`, `1.14.x`, `1.15.x`).

Cheers.

**Comment by sevmonster** [comment]
Thanks!

I could have sworn it worked in 1.14 with the CAS plugin.

I will test this when I get a chance to see if it solves the issue with the previous version of the plugin that does not redirect.

**Comment by sevmonster** [comment]
Tested on top of latest develop, this fixes the issue. Redirecting back to `scp/login.php` after completing a login with an external provider now redirects you to your original destination before login was prompted.
