### ISSUE TITLE
Enhancement: Allow `Organizations` as a collaborator.

### ISSUE THREAD

**Issue by jurajlutter** [osTicket/osTicket#5745]
Hi,

I've ran into a situation where I'd need also `Organization` to be an active collaborator, where all members of given `Organization` will have an access to the ticket(s) opened by other members of given `Organization`.

Is this possible and if not, would it be difficult to implement it?

Thanks.

**Comment by JediKev** [comment]
@jurajlutter 

No changes needed as this is already a core feature. First step is to add all required Users to an Organization. Next go to **Agent Panel > Users > Organizations**, click the Organization's name, click the Organization's name with the Edit Icon next to it in the header, and go to the **Settings** tab. Here you can enable **Automated Collaboration > Organization Members** (ie. check the box) and Save Changes. Once you do this, any tickets opened by any User in the Organization will auto-add all other Org members as collaborators.

You can also allow Users to see all tickets within their Org by setting **Ticket Sharing** to `All members see all tickets`.

Cheers.

**Comment by jurajlutter** [comment]
@JediKev thanks, this was it. For whatever reason the `Edit` icon is kinda subtle and it did not crossed my mind that I should even look there. I must go through all menus/icons once in a while :-)
