### ISSUE TITLE
Error show Dialog 

### ISSUE THREAD

**Issue by oviedo** [osTicket/osTicket#5746]
This error exist with all dialogs.

 
![image](https://user-images.githubusercontent.com/127291/101838367-15695800-3b06-11eb-8e02-bc6c91650483.png)

Steps:
![image](https://user-images.githubusercontent.com/127291/101838417-2d40dc00-3b06-11eb-8ca6-104a045b6e6a.png)

![image](https://user-images.githubusercontent.com/127291/101838442-392c9e00-3b06-11eb-8756-f3ceb56d97e3.png)

![image](https://user-images.githubusercontent.com/127291/101838491-52cde580-3b06-11eb-9bd6-68b076bbbd0c.png)

**Comment by ntozier** [comment]
You are running nginx.  osTicket does not support nginx.  Please see the various nginx threads here on github for all of the configuration changes that you have to do to nginx configuration(s) to make the product work with this unsupported webserver software.

**Comment by antiuser** [comment]
@oviedo 
hi! i cannot replicate this issue on my nginx installation.
Use my nginx config as example, im showing it on this page
https://github.com/osTicket/osTicket/issues/5740
