### ISSUE TITLE
osTicket API Integration Problem [ticketInfo]

### ISSUE THREAD

**Issue by krgsoft** [osTicket/osTicket#5752]
I am trying to retrieve ticket details from ticketNumber as below which is documented  at https://github.com/osTicket/osTicket/pull/4361.

osTicket API Integration have problem with /api/http.php/tickets/ticketInfo?ticketNumber=xxx. It says [URL not supported]. Have anyone integrated such API previously? Please share your idea...

**Comment by JediKev** [comment]
@krgsoft 

The link you referenced is a mod from a community member. It is not a part of the core code base. We do not have a fully RESTful API at this time, meaning, you can only create tickets and nothing more.

Github is a place to report issues/bugs, feature requests, and to make pull requests. If you would like to ask questions, etc. please use our [Forum](https://forum.osticket.com).

Cheers.
