### ISSUE TITLE
How to upgrade from ancient version

### ISSUE THREAD

**Issue by leifnel** [osTicket/osTicket#5757]
I have ancient v1.8.1-rc1, checked out over git?
How do I get up-to-date?
Which route should I take to get up-to-date?
I'm perfectly willing to upgrade one version a time, or in even more steps.

**Comment by JediKev** [comment]
@leifnel 

It’s very simple. You can upgrade all the way to the latest version without going one version at a time. We have a a full upgrade guide on our [Documentation site here](https://docs.osticket.com/en/latest/Getting%20Started/Upgrade%20and%20Migration.html). This also includes a link to a video on our YouTube channel if you’re more of a visual type.

Cheers.

**Comment by leifnel** [comment]
So this is not considered a discontinued version?

"We plan on supporting data migration from previous discontinued versions of osTicket as well as 3rd party help desks in the near future. Please check the forums for up to date discussions on the subject."

**Comment by JediKev** [comment]
@leifnel 

That is referring to versions that are pre 1.6 ST (1.4, 1.5, etc.).

Cheers.

**Comment by JediKev** [comment]
@leifnel 

You can see at the top we note:
>1. Only previous versions from version 1.6 RC1 can be upgraded to the current version.
>2. If your osTicket version is older than 1.6, you need to look into migration instead.

Cheers.

**Comment by leifnel** [comment]
Got so far. I copied everything to a new php7-server, and got so far as to the upgrade screen.

The upgrader does NOT support upgrading from the current patch [6de40a4d5bad7a2923e769a4db1ff3b9]!

Bummer.

**Comment by leifnel** [comment]
![image](https://user-images.githubusercontent.com/9819287/103449745-eed5b180-4cac-11eb-9f11-b677bf1894d7.png)

When the prerequisites are fulfilled, it's confusing it shows red X's not green checkmarks.

**Comment by JediKev** [comment]
@leifnel 

Odd, that is a valid schema signature that we do support upgrading from. I’ll have to look into why it would throw that error so we can pinpoint what could be happening.

Cheers.

**Comment by JediKev** [comment]
@leifnel 

Okay, what version are you trying to upgrade to and where did you download it from?

Cheers.

**Comment by leifnel** [comment]
BTW, I'm on 1.8-git.

**Comment by leifnel** [comment]
I downloaded https://github.com/osTicket/osTicket/releases/download/v1.15.1/osTicket-v1.15.1.zip

**Comment by leifnel** [comment]
I added debug to the isUpgradeable().
The stream it fails on is
`object(StreamUpgrader)#142 (13) {
  ["prefix"]=>
  string(4) "ost_"
  ["sqldir"]=>
  string(47) "/home/ticket/www/include/upgrader/streams/core/"
  ["signature"]=>
  string(32) "6de40a4d5bad7a2923e769a4db1ff3b9"
  ["state"]=>
  NULL
  ["mode"]=>
  string(4) "ajax"
  ["phash"]=>
  &NULL
  ["version"]=>
  string(7) "v1.15.1"
  ["version_verbose"]=>
  string(7) "v1.15.1"
  ["errors"]=>
  array(0) {
  }
  ["target"]=>
  string(32) "add628927ee030469f5d3272ebda1e16"
  ["upgrader"]=>
  object(Upgrader)#141 (4) {
    ["streams"]=>
    array(1) {
      ["core"]=>
      *RECURSION*
    }
    ["state"]=>
    &NULL
    ["mode"]=>
    &NULL
    ["current"]=>
    &NULL
  }
  ["name"]=>
  string(4) "core"
  ["migrater"]=>
  object(DatabaseMigrater)#165 (3) {
    ["start"]=>
    string(32) "6de40a4d5bad7a2923e769a4db1ff3b9"
    ["end"]=>
    string(32) "add628927ee030469f5d3272ebda1e16"
    ["sqldir"]=>
    string(47) "/home/ticket/www/include/upgrader/streams/core/"
  }
}
`

**Comment by leifnel** [comment]
If everything else fails, I could migrate. But I see no clear instructions how.

**Comment by leifnel** [comment]
Okay. I just renamed the webroot, extracted the new files to a new webroot, fired up the upgrader, and presto, it upgraded the database, and I'm now on 1.15

Nice.
