### ISSUE TITLE
List of agents sorted by staff id instead of user name

### ISSUE THREAD

**Issue by StephanReiners** [osTicket/osTicket#5769]
Hi guys,
I saw, that dropdown list of agents is sorted by staff id instead uf user name.

Reproduce;
-Open any ticket as an agent
-select "Assign" button in upper right part of screen, select "agent"
-separate window is opened titled "Ticket # ... Reassign an Agent"
-see sort order in drop down list "Assignee"

How can this be fixed?

BR
Stephan

**Comment by JediKev** [comment]
@StephanReiners 

This is a known issue that has already been addressed. Here is the patch:
- https://github.com/osTicket/osTicket/pull/5748

Please use Github Search feature next time. Remember, search is your best friend.

Cheers.
