### ISSUE TITLE
After update some (old/new) tickets not open (blank) or open partially

### ISSUE THREAD

**Issue by chumayu** [osTicket/osTicket#5775]
Log:

PHP Fatal error:  Uncaught ObjectNotUnique: One object was expected; however multiple objects in the database matched the query. In fact, there are 2 matching objects. in /home1/path/public_html/
Stack trace:
#0 /home1/path/include/class.orm.php(606): QuerySet->one()
#1 /home1/path/include/staff/templates/thread-entries.tmpl.php(37): VerySimpleModel::lookup(Array)
#2 /home1/path/include/class.thread.php(415): include('/home1/alphatmn...')
#3 /home1/path/include/staff/ticket-view.inc.php(773): Thread->render(Array, Array)
#4 /home1/path/scp/tickets.php(560): require_once('/home1/alphatmn...')
#5 {main}
  thrown in /home1/path/include/class.orm.php on line 1363

In attachment you can see how look like ticket
![firefox_2021-01-21_14-29-11](https://user-images.githubusercontent.com/10510718/105361057-19b38580-5c1b-11eb-8f73-9027a1b0414c.png)

I try install on another hosting (make backup database and website files) same.

Additional info
osTicket Version | v1.15.1 (fe1d1f8)
Web Server Software | Apache
MySQL Version | 5.7.23
PHP Version | 7.4.14

UPD #2:
BUT, when via "Thread preview" check corrupted ticket - show him correctly.

**Comment by JediKev** [comment]
@chumayu 

Please review this thread as it contains your exact problem with a resolution:
- https://forum.osticket.com/d/97956-cant-see-ticket-content/20

Cheers.

**Comment by chumayu** [comment]
@JediKev 

That help, thx man.
