### ISSUE TITLE
Problem with detach linked Tickets

### ISSUE THREAD

**Issue by PilarexX** [osTicket/osTicket#5811]
Hello,

I have four linked Tickets and I try to detach all, but I don't know why the last link stays.
![image](https://user-images.githubusercontent.com/11716578/108350983-2e1c7b00-71e5-11eb-9415-8aa82362d1a0.png)
After detach:
![image](https://user-images.githubusercontent.com/11716578/108351037-42607800-71e5-11eb-8635-26920a8121c6.png)

I don't know why this is happening ... maybe I'm doing something wrong?

**Comment by mlipok** [comment]
This is our common problem (we work together on the same osTicket instalation) and I just wanted to add that:
We expect that when we had selected all tickets and delete them from the list (marked on screenshot by green border) then all tickets should be unlikned, also this main/parent ticket, but currently how you can see on the second screenshot the main/parent ticket is still linked to himself.

**Comment by JediKev** [comment]
@PilarexX @mlipok 

There could've been an error or issue when unlinking the ticket. Please check all error logs for any related errors.

Cheers.

**Comment by mlipok** [comment]
Already fixed
https://github.com/osTicket/osTicket/commit/f5435565d54c076e17c015d94fc2cf8a2bf83945
how to close this issue ? or mark as resolved ?

**Comment by PilarexX** [comment]
Thank you for your help.
