### ISSUE TITLE
No notification for staff when piping mails

### ISSUE THREAD

**Issue by Af0x** [osTicket/osTicket#5818]
Hello,

when mails come in via pipe there seems to be no notification for department members although being set.

Either I made a mistake setting it up or it is just not working.

Best regards,

Af0x

**Comment by Af0x** [comment]
Hello, I want to come to this again. I only get a notification about expired tickets after I logged in. Best regards

**Comment by JediKev** [comment]
@Afox

Sounds like you have Autocron setup instead of configuring an actual Cron Job/Scheduled Task. You should read the email setup guide here:
- https://docs.osticket.com/en/latest/Getting%20Started/POP3-IMAP%20Settings.html#schedule-polling


You see, even though you are not fetching the TicketMonitor (that checks for Overdue Tickets) runs on Cron and if you are using Autocron it will only run when Agents login. If you setup a Cron Job/Scheduled Task, the TicketMonitor will be called every X minutes regardless of anyone being logged in or not.

Cheers.

**Comment by Af0x** [comment]
Thank you, I now set up the crontab for notifications. My other, initial problem was due to the fact that the department manager does not count as regular department member and has to be checked additionally to receive notifications.

**Comment by Af0x** [comment]
Sorry to come back to this again but I have the following error in my log immediately after running the cron.php:

> sendmail: fatal: open /etc/postfix/main.cf: No such file or directory

Does this mean my cron is not set up correctly or that cron.php requires a working sendmail environment to sent e.g. SLA notifications?

**Comment by JediKev** [comment]
@Af0x 

First question is do you have a system email configured to send alerts? (I would assume so as you get some alerts like overdue alerts, but please humor me here) Second question is, if so, does that system email configured to send alerts have SMTP enabled and fully working? If so, check all possible areas for configuring outgoing mail (email settings and all departments) to make sure they are all set properly.

If everything above checks out please contact your hosting provider for further assistance as there could be an issue with the cron job (like using the wrong version of PHP) or a different layer.

Cheers.

**Comment by Af0x** [comment]
Hello, just to get it straight: I don´t need the server itself to be able to sent mail and all configuration regarding sending mails can be done within the osticket webinterface, correct?
Because I don´t have postfix configured as you can see with the error message above.

Second I set the osticket alert mail the same as the system mail but still there is no mail sent although that mail is set up correctly to sent mails.

PHP Version 7.3

**Comment by Af0x** [comment]
Digging deeper I found 2 error messages in the logs of osticket:
1
> Unable to email via SMTP:mailserverdomain.tld:#Port# [address@domain.tld] Failed to set sender: address@domain.tld [SMTP: Invalid response code received from server (code: -1,  response: k?®ÈóöõA#¶)]

2

> Unable to email via php mail function:"Agent Name" mail() returned failure

**Comment by Af0x** [comment]
In the logfiles of the mailserver the error gets more concrete:

> SSL_accept error from ###: -1
warning: TLS library problem: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:../ssl/record/rec_layer_s3.c:1544:SSL alert number 48

And then it loses connection.

Detailed handshake:

> setting up TLS connection from ###
TLS cipher list "aNULL:-aNULL:HIGH:MEDIUM:+RC4:[at]STRENGTH"
SSL_accept:before SSL initialization
SSL_accept:before SSL initialization
SSL_accept:SSLv3/TLS read client hello
SSL_accept:SSLv3/TLS write server hello
SSL_accept:SSLv3/TLS write certificate
SSL_accept:SSLv3/TLS write key exchange
SSL_accept:SSLv3/TLS write server done
SSL3 alert read:fatal:unknown CA
SSL_accept:error in error
SSL_accept error from ###: -1
warning: TLS library problem: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:../ssl/record/rec_layer_s3.c:1544:SSL alert number 48:
lost connection after STARTTLS from ###

**Comment by Af0x** [comment]
Nevermind, it was not an issue related to osticket. I had to make another exception for my selfsigned cert within PHP (cli).
