### ISSUE TITLE
Unable to Add Organziation properties to the Export fields

### ISSUE THREAD

**Issue by ewhitmore** [osTicket/osTicket#5878]
### Prerequisites

* [X] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [X] Do you have any errors in the PHP error log, or javascript console? - No Errors found
* [X] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [X] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

Bug/Missing Feature - You can not currently add any organizational properties to the export fields in the queues.  Found workaround here: https://forum.osticket.com/d/94163-queue-export-add-field/18

### Steps to Reproduce

1. Open Admin Panel
2. Go to Settings, Tickets, Queues
3. Open a Queue
4. Click Export
5. Scroll to the bottom of the Field list
6. Try to add an Org Property/Field

**Expected behavior:** [To have all the organizational properties/fields available to add to the export

**Actual behavior:** Dropdown only had one entry: --Add other Field --

### Versions

Admin panel -> Dashboard -> 1.15-git (cb6766e5) — Up to date

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.
Ubuntu VERSION="18.04.5 LTS (Bionic Beaver)"
Tried on Firefox 88.0 & Chrome 90.0.4430.93

**Comment by JediKev** [comment]
@ewhitmore 

Yes, this is currently by design. You cannot add Organization data nor any Custom Form data to the Queue Exports at this time. We plan to expand the options for Queue Exports in future updates to the software.

Cheers.

**Comment by ewhitmore** [comment]
@JediKev - thanks for the quick response.
