### ISSUE TITLE
ost_chunk_files and ost_file tables not getting cleared after tickets deleted (even after few days)

### ISSUE THREAD

**Issue by ghost** [osTicket/osTicket#5892]
### Description
I have 2 instances of osticket running on same server. Second instance was created from the first.
Database dumped and imported to second database, created separate vhost, files from /var/www copied and reconfigured (ost-config file), so now I have 2 instances with same databases (same data, but different database). 

Now this second instance must be cleared by deleting some tickets which are irrelevant to it . We deleted about 10k tickets by GUI but database size is not getting smaller. Problematic ost_chunk_file table is still large (22gb, row count isn't reduced)
Deleting tickets won't delete entries in ost_file and ost_file_chunk, even after few days (we are running cron /api/cron.php every 5 minutes), after some reading this entries should be deleted after 24h but in our case from the delete time now have past more than 2 days.

### Steps to Reproduce

1. delete tickets by web gui
2. ticket deleted (checked also in database ost_ticket table)
3. ost_file and ost_file_chunk tables not cleared

**Expected behavior:** [What you expected to happen]
ost_file_chuk table size reduced

**Actual behavior:** [What actually happened]
ost_file_chunk is same size as before deleting tickets

### Versions
CentOS Linux release 7.4.1708
osTicket Version v1.10.1
php 5..4
mysql 10.1.28

osticket accessed via latest version of Firefox and Chrome

Currently there is no plan to upgrade, but if this issue was solved in later releases please suggest

**Comment by JediKev** [comment]
@goodguy88 

Well, you are using an extremely old, outdated, and unsupported version. I do believe this issue has already been resolved in later versions. Please upgrade to the latest version and retest.

Cheers.

**Comment by ntozier** [comment]
As a side note to update to the latest version you will also need to upgrade your PHP to a contemporary version also.

**Comment by ghost** [comment]
Ok, we will upgrade first then.
Can we upgrade to latest version in one step or we must follow upgrade path 1.11->1.12->...
We will also update php to 7.4

**Comment by ghost** [comment]
Ok I have test upgrade directly and it went trough with no issues
I will update when I test delete tickets if ost_file_chunk also will be cleared.

**Comment by ghost** [comment]
I can confirm that latest version of osticket now removes attachments and clears ost_file_chunk table.
I am closing this issue
