### ISSUE TITLE
Setup typo or just needs to be updated

### ISSUE THREAD

**Issue by drissical** [osTicket/osTicket#5930]
### Prerequisites

Standard setup from zip file

### Description

Not a major or even a minor bug but just a verbiage issue. Setting up a test instance of the software and I was just putting in a simple admin password of "admin" which the tooltip shows just needs to be 5 characters, however it fails because it is not 6 characters in the error message.  I moved the tooltip down in the image so that you can see the tooltip and the error message at the same time.

### Steps to Reproduce

Setup a new install and attempt to use a 5 character password for the password.

**Expected behavior:** Albeit bad practice to use a 5 character password, I still expected it to let me do it as that is what was described. 

**Actual behavior:** Better, requiring 6 characters with an error only having 5.

### Versions
osTicket 1.15.2
Debian Buster

![image](https://user-images.githubusercontent.com/8355446/127072124-9b295f3a-2a6f-4fd8-8df8-878e74ce37fc.png)

**Comment by JediKev** [comment]
@drissical 

Thank you for the report! Below is the pull to address the issue. It will soon be merged and packaged in a future release.
- https://github.com/osTicket/osTicket/pull/5931

Cheers.
