### ISSUE TITLE
External Auth not showing on Login Page for Clients

### ISSUE THREAD

**Issue by cslob** [osTicket/osTicket#5937]
### Description

After updating to v1.15.3, external auth plugin for Google OAuth not showing up. 

### Steps to Reproduce

1. Do the upgrade (done via git)
2. Check the client login page

**Expected behavior:**
Sign in with Google button should appear

**Actual behavior:**
Sign on with Google button is not there

I was able to work around the issue by removing the following lines from include/class.auth.php around line 853.
`{
        $service = sprintf('%s %s',
                __('Sign in with'),
                $this->getServiceName());`

**Comment by JediKev** [comment]
@cslob 

What is the exact plugin are you attempting to use?

Cheers.

**Comment by cslob** [comment]
The OAuth plugin
https://github.com/osTicket/osTicket-plugins/tree/develop/auth-oauth

**Comment by JediKev** [comment]
@cslob 

Yea…that plugin was never officially released and is really old. We don’t even maintain this plugin so it’s not recommended for use.

I’m closing this as this is not an officially released plugin.

Cheers.

**Comment by JediKev** [comment]
@cslob 

Re-opening as even though you mentioned a non-released plugin, this actually affects officially released plugins as well.

Cheers.

**Comment by JediKev** [comment]
Closing. Fixed by: #5938
