### ISSUE TITLE
[Feature Request] Combotree for Helptopic

### ISSUE THREAD

**Issue by chilladelphia24** [osTicket/osTicket#5951]
Greetings!

I was directed to create a Feature Request on github based on a Feature Request post I created in the osTicket Forum, below are the details of what I'm requesting, thank you.

-I've seen a couple of requests in regards to this feature, and there appears to be a modification that was created many years back in regards to a feature I'm requesting (https://github.com/kest874/osTicket-1.8/tree/feature/help-topic-dropdown). Unfortunately this old modification does not work well with the latest version of osTicket that I have installed (version 1.15.3).

So I was wondering if the developers can implement a combotree feature for the help topic on the next update (sometime soon???), or if someone can guide me on how I can implement the mod that was created by kest874; or if anyone has any other suggestions on how I can use something else besides a dropdown list. The reason for this request is due to helping make osTicket interface look much neater, especially on the client side. We have so many help topics that it makes it difficult for one to scroll through 30 different topics in order to find the right one.

Thanks!

**Comment by JediKev** [comment]
@chilladelphia24 

Thank you for creating this feature request. Unfortunately this has been opened before:
- https://github.com/osTicket/osTicket/issues/5677

I will close this in favor of the original as to refrain from duplicates. You can add your +1 in aforementioned thread.

If you are looking for assistance applying a mod, creating your own mod, suggestions, etc. the best place for that is our Forum that you’ve mentioned.

Cheers.

**Comment by chilladelphia24** [comment]
Will do thanks!
