### ISSUE TITLE
'Ticket Edit History / Original Thread Entry' only shows current entry, not the actual history/original

### ISSUE THREAD

**Issue by sophon48** [osTicket/osTicket#5954]
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [x] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

'View History' states 'original thread entry', implying that you are able to see the original message after an edit has been performed, but the edit pop-out simply displays the current (edited) message.

### Steps to Reproduce

1. Post response
2. Edit response
3. View response history -- displays current thread entry.

**Expected behaviour:** [What you expected to happen]
View original thread entry/history -- see the original thread entry or edit history.

**Actual behaviour:** [What actually happened]
View original thread entry/history -- see only the current post, in its edited form with no history or original.
### Versions
![](https://i.imgur.com/uxjF38E.png)

**Comment by sophon48** [comment]
As an update, the feature appears to work as expected on Internal Notes only.

**Comment by gerundt** [comment]
I know at least the problem!

The file `include/staff/templates/thread-entry-view.tmpl.php` includes on [line 17](https://github.com/osTicket/osTicket/blob/develop/include/staff/templates/thread-entry-view.tmpl.php#L17) a  condition, which is for messages always `true`:

```
&& $E->staff_id != $thisstaff->getId()
```

For a _internal note_ `$E->staff_id` returns the ID. But for messages it returns `NULL`. Because of this `$E->staff_id` is always different to `$thisstaff->getId()`.

In the DB the `thread_entry.staff_id` is filled. I understand at the moment not, why it is NULL for messages. 🤷‍♂️

**Comment by gerundt** [comment]
In the file `include/staff/templates/thread-entries.tmpl.php` on [line 32](https://github.com/osTicket/osTicket/blob/develop/include/staff/templates/thread-entries.tmpl.php#L32) seems the search to start.

The QuerySet runs the following SQL on my test ticket:
```
SELECT A1.`id`, A1.`pid`, A1.`thread_id`, A1.`staff_id`, A1.`user_id`, A1.`type`, A1.`flags`, A1.`poster`, A1.`editor`, A1.`editor_type`, A1.`source`, A1.`title`, A1.`body`, A1.`format`, A1.`ip_address`, A1.`extra`, A1.`recipients`, A1.`created`, A1.`updated`, COUNT(CASE WHEN A5.`inline` = 0 THEN 1 END) AS `has_attachments`, A2.`staff_id`, A2.`dept_id`, A2.`role_id`, A2.`username`, A2.`firstname`, A2.`lastname`, A2.`passwd`, A2.`backend`, A2.`email`, A2.`phone`, A2.`phone_ext`, A2.`mobile`, A2.`signature`, A2.`lang`, A2.`timezone`, A2.`locale`, A2.`notes`, A2.`isactive`, A2.`isadmin`, A2.`isvisible`, A2.`onvacation`, A2.`assigned_only`, A2.`show_assigned_tickets`, A2.`change_passwd`, A2.`max_page_size`, A2.`auto_refresh_rate`, A2.`default_signature_type`, A2.`default_paper_size`, A2.`extra`, A2.`permissions`, A2.`created`, A2.`lastlogin`, A2.`passwdreset`, A2.`updated`, A3.`id`, A3.`org_id`, A3.`default_email_id`, A3.`status`, A3.`name`, A3.`created`, A3.`updated`, A4.`id`, A4.`thread_entry_id`, A4.`email_id`, A4.`mid`, A4.`headers` FROM `thread_entry` A1 LEFT JOIN `staff` A2 ON (A1.`staff_id` = A2.`staff_id`) LEFT JOIN `user` A3 ON (A1.`user_id` = A3.`id`) LEFT JOIN `thread_entry_email` A4 ON (A1.`id` = A4.`thread_entry_id`) LEFT JOIN `attachment` A5 ON (A5.`type` = "H" AND A1.`id` = A5.`object_id`) WHERE A1.`thread_id` = 92 AND NOT A1.`flags` & 4 != 0 AND A1.`type` IN ("M", "R", "N") GROUP BY A1.id ORDER BY A1.`created` ASC, A1.`id` ASC
```
Running on phpMyAdmin I noticed two `staff_id` columns:

![image](https://user-images.githubusercontent.com/497880/134359864-e33c422a-bdef-4268-ab99-e45471ad54de.png)

The first one is valid and the second one has `NULL` value on the message.

But now I am out. This is to deep in the osTicket internals. 🙈

**Comment by JediKev** [comment]
@gerundt 

lol Thank you. We are going to investigate this. 😉 

Cheers.

**Comment by JediKev** [comment]
@gerundt 

Okay so after further review and testing only the OP of the entry can see all edits to the entry. If you are not the OP of the entry you will only be able to see the latest edit and any edits you've made yourself. We can see this even from the comments in the relevant code:
```php
// The current version is always visible
&& $i > 1
// If you originally posted it, you can see all the edits
&& $E->staff_id != $thisstaff->getId()
// You can see your own edits
&& ($E->editor != $thisstaff->getId() || $E->editor_type != 'S')
```

So, this is not a bug, this is working as intended.

Cheers.

**Comment by JediKev** [comment]
Also, to note, if you click **Save and Resend** then it will overwrite the entry you're editing (ie. it will not create a new entry).

**Comment by gerundt** [comment]
@JediKev

> So, this is not a bug, this is working as intended.

Mhh, I created just a ticket over the SCP page. After that I edited the message, created a first internal note, edited the note, wrote a first reply and edited the reply (with resend).

In the table `thread_entry` the message has a `staff_id = 0` while all other entries have my correct ID `1`:

![image](https://user-images.githubusercontent.com/497880/134475454-72e8240e-999c-4f88-a04d-d17356f7842a.png)

So you can never view the original message because the _invalid_ staff id!? Looks not like wanted behavir. 🤷‍♂️

**Comment by JediKev** [comment]
@gerundt 

The two entries with no `staff_id` have `type` set to `M` which means a User Message which means there is no `staff_id`. Everything looks correct in the screenshot.

Cheers.

**Comment by JediKev** [comment]
@gerundt 

I get it now. You are talking about editing messages, not internal notes. I don’t know how I overlooked that. Anyways, as you can see from your screenshot, the edited message has `editor` as the ID of the Staff and `editor_type` as `S` which means Staff.

The original entry will not have this info as it’s "from the User" (even if you created it on their behalf).

I need to retest with messages now.

Cheers.

**Comment by sophon48** [comment]
When I originally opened this, as per the description and title, the issue was that _no_ edits could be viewed on public-facing posts. It was not a case of not being able to see _all_ edits, just the inability to see any at all - as a staff user. (In hindsight, screenshots illustrating this may have focussed discussion/investigation).

This meant that it was impossible to see what an agent had originally posted, as 'history' showed the current post in its edited form as the original. Internal notes did work as intended and showed the original post.

This does not seem to be an issue anymore on the latest build, so I am closing this.
