### ISSUE TITLE
ost__search table is not recreate automatically

### ISSUE THREAD

**Issue by AlexanderB-C** [osTicket/osTicket#5970]
I am using osTicket (Awesome) 1.15.3.1.

I dropped table ost__search because I thought it could be responsible for some issues I had.
I thought from what I read in #2208 that the table is automatically rebuilt.
That issue thread is the first thing you find in Google when searching for "rebuild ost__search".

But it was not recreated automatically.
So I had to restore a backup.

Did the way to rebuild this table change since then?

**Comment by ntozier** [comment]
You would need to removed the 3rd party theme mod and retest.
