### ISSUE TITLE
%{comments} variable does not work in ticket assignment template

### ISSUE THREAD

**Issue by Af0x** [osTicket/osTicket#5978]
Hello,

the mailtemplate for the auto assignment of a ticket to a staff member does not seem to convert the %{comments} variable. 

The corresponding mail contains that variable %{comments} in its text.

osTicket v1.15.3.1 (65ca4e6)

Apache 2.4.48
MariaDB 10.5.11
PHP 7.4.21

Best regards,

Af0x

**Comment by ntozier** [comment]
Ignore me.  You are talking about assigning, not transferring.

Looking at this I see no comments being posted in the alert, but I do not see the %{comments} in the email either.

**Comment by Af0x** [comment]
Did you try to not add a comment? In my case the assignment was made by the system on creation. The assignment was configured within the help topic under
Manage->Help Topics->Select the topic->New ticket options->Auto-assign To

**Comment by JediKev** [comment]
@Af0x 

Just thinking about this, the system auto assignment doesn’t have comments so it wouldn’t be replaced, no? The only way it can have comments if it’s done manually and the agent doing the assignment adds a comment.

Cheers.

**Comment by Af0x** [comment]
Shouldn´t empty comments be filtered instead of displaying the plain variable? Also if I understand ntozier correctly even if you add a comment it doesn´t get included (didn´t test myself).

**Comment by JediKev** [comment]
@Af0x 

Tested using latest v1.15.3.1 and without adding a comment the variable was replaced (with nothing) and with adding a comment the variable was replaced (with the actual comments). Tested on two separate systems so seems like somethings going on with your install specifically.

Cheers.

**Comment by Af0x** [comment]
Did you also test the auto-assign via help topic like [described earlier](https://github.com/osTicket/osTicket/issues/5978#issuecomment-936491212)?

**Comment by JediKev** [comment]
@Af0x  No, looking into that part now.

**Comment by JediKev** [comment]
@Af0x 

Here you go:
- https://github.com/osTicket/osTicket/pull/5983

Cheers.

**Comment by Af0x** [comment]
Thank you
