### ISSUE TITLE
mail error was not sent by the system alert email.

### ISSUE THREAD

**Issue by sjxiong** [osTicket/osTicket#5992]
### Description

![image](https://user-images.githubusercontent.com/15185770/136572834-ec7d32ef-220b-4289-aaee-16ff938dd8c5.png)
sysstem errors should be sent to admin with alert emails.
But the mail error as below was never sent to me.
![image](https://user-images.githubusercontent.com/15185770/136573082-aef6ebf0-a619-47d9-9999-efe8f1dfddc7.png)

### Versions

![image](https://user-images.githubusercontent.com/15185770/136573240-9bced6ab-4544-44cc-933b-ff07b2c9b5b1.png)

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

**Comment by JediKev** [comment]
@sjxiong 

Are the Mailer Errors SMTP errors? If so, I bet that's why it wasn't sent (as SMTP is failing).

Cheers.

**Comment by ntozier** [comment]
Also please upgrade to current and retest.

**Comment by sjxiong** [comment]
system is upgraded, I'll close the issue now, thanks for the help!
