### ISSUE TITLE
mail error when no collaborator is selected.

### ISSUE THREAD

**Issue by sjxiong** [osTicket/osTicket#5993]
### Description

post reply when 0 collaborated is selected will fail, and no mail is sent via ticket system.

### Steps to Reproduce

1. unselect all collaborator.
![image](https://user-images.githubusercontent.com/15185770/136573839-51cd5eb7-d82a-49b4-a455-3ba7d7fbea14.png)

2. post reply

**Expected behavior:** mail sent to the ticket owner only because no collaborator is selectected.

**Actual behavior:** mail was not sent, but didn't receive any error alert. When I check in the admin panel-system logs, found mail error.
![image](https://user-images.githubusercontent.com/15185770/136574181-6db18f86-2222-4b57-82e3-77745f3c533f.png)

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about your server.
![image](https://user-images.githubusercontent.com/15185770/136574629-d5c5bc42-494c-4801-9a2f-e30b4996758d.png)

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.
windows 10

**Comment by JediKev** [comment]
@sjxiong 

As shown in your screenshot you have Mailer Errors which is indicative of SMTP not working, ergo no emails will be sent out (this has nothing to do with collaborators).

Cheers.

**Comment by sjxiong** [comment]
![image](https://user-images.githubusercontent.com/15185770/136575333-12b2a51b-dad7-4bcb-9d5d-1b2e10b13fba.png)
this is related to my other post.
I did a test, when I select one of the collaborator, the mail was sent without any problem. This error happens only when no collaborator is selected.

**Comment by JediKev** [comment]
@sjxiong 

Hmm, I cannot replicate with latest release of v1.15.4. Seems like the system is defaulting to PHP Mailer and not sending out.

Cheers.

**Comment by sjxiong** [comment]
> @sjxiong
> 
> Hmm, I cannot replicate with latest release of v1.15.4. Seems like the system is defaulting to PHP Mailer and not sending out.
> 
> Cheers.

Thanks, I'll try to upgrade the osticket then. finger crossed! :)

**Comment by sjxiong** [comment]
Hello, the system upgraded to v1.15.4. Problem solved!!! :)
