### ISSUE TITLE
Convert to Bootstrap

### ISSUE THREAD

**Issue by BoLaMN** [osTicket/osTicket#6]
Hey Guys,

not sure if i should post this here or if there is actually a place to post it.

just wondering if you would be interested in me starting to converting this over to bootstrap? or if you've already started too? 

i can see that the dashboard (stats page) is of course a start of bootstrap but was wondering you wanted help or needed some one too work on converting it?

ive had previous experience starting to convert it but its a very big job with the current type of repetitive code, ive already converted osticket to bootstrap for a client but i havent 100% converted it to use rows and spans.

Preview: 

http://img819.imageshack.us/img819/7822/c8so.png
http://imageshack.us/a/img33/6339/iqn1.png
http://imageshack.us/a/img194/5443/4g9a.png
http://imageshack.us/a/img713/7881/he3v.jpg
http://imageshack.us/a/img541/98/pzk0.png
http://imageshack.us/a/img541/3882/tohl.png
http://imageshack.us/a/img443/2316/p750.png
http://imageshack.us/a/img199/5594/6poi.png
http://imageshack.us/a/img694/3948/54d8.jpg
http://imageshack.us/a/img33/1296/28us.png
http://imageshack.us/a/img43/6358/e84f.png

of course i cant release that theme but id be happy to work on or with some one to get the theme in the 21st century.

Ive done some extra small mods to this version for the client as well such as select help topic and priority on reply to ticket i think this is much easier then actually having to edit the ticket and a setting in settings to enable being able to select department from open ticket on web. use AD to get location of client (windows ad). vbs script that runs as gpo login script to post to website to store ip of computer and then select this within the ticket screen aswell uses a reverse lookup on the email field in AD and gets account username to match.

this being said id be happy to help this open source and 1.8 with html threads and emails will look amazing! 

if your're not looking for help im happy that i at least asked.

Cheers

BoLaMN

**Comment by G3z** [comment]
+1

**Comment by PeopleInside** [comment]
In this Theme there is issue in Attachments.. i don't like to see normal button for Upload file is better as is now in non responsive where you can read you can select more than one or drop file.

**Comment by iJar82** [comment]
Just one question!
Where can I get this theme!!

**Comment by lello89pt** [comment]
send me a mail 
marcellosannai@gmail.com

**Comment by darinkr** [comment]
So is this bootstrap theme for osTicket available?  I would LOVE to have a clean, responsive theme for osTicket!

**Comment by kest874** [comment]
See this pull https://github.com/osTicket/osTicket-1.8/pull/2789 for the client side that I did.

**Comment by fproject** [comment]
+1

**Comment by nguyenbs** [comment]
Is there any update for this issue?

**Comment by tdefreest** [comment]
+1
