### ISSUE TITLE
Team members not notified about message from Ticket owner when Team and single Staff is assigned to a Ticket

### ISSUE THREAD

**Issue by veryslothysloth** [osTicket/osTicket#6000]
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch? yes (15.10.2021)
* [x] Do you have any errors in the PHP error log, or javascript console? yes, none
* [x] Did you check the [osTicket forums](https://forum.osticket.com/)? yes
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported? yes

### Description

When a Ticket is assigned to a single staff member and a team at once just the staff member gets an e-mail about a new message from the ticket owner.

### Steps to Reproduce

1. Assign a Ticket to a Team
2. Assing the same Ticket to a single staff member as well
3. Send a reply from the Ticket owner to the Ticket

**Expected behavior:** The single user and the team members will receive an e-amil

**Actual behavior:** just the single user received an e-mail

### Versions
![image](https://user-images.githubusercontent.com/62953102/137499172-d7ccfa83-36f0-4a66-b8ca-d00c9a783265.png)

**Comment by JediKev** [comment]
@veryslothysloth 

This is expected behavior. If an Agent and Team is assigned a Ticket, the New Message Alert will only be sent to the Agent, not the Team. If you want to have the alert go to the Team then the Ticket must not be assigned to an individual Agent.

You can view the bit of code responsible here:
- https://github.com/osTicket/osTicket/blob/develop/include/class.ticket.php#L3224-L3227

Cheers.

**Comment by veryslothysloth** [comment]
Okay, thank you for the info!

**Comment by veryslothysloth** [comment]
For anyone facing the same ""Issue"" as us. We fixed it by adding the following two lines in the code that Kev linked to above:
`if ($team = $ticket->getTeam())`
`$recipients = array_merge($recipients, $team->getMembersForAlerts());`

![image](https://user-images.githubusercontent.com/62953102/137686043-2ae3dc6b-4cd4-4b7c-92ac-18fd85deedcb.png)


_I didn't want to create a pull request since it would change intended behavior..._
