### ISSUE TITLE
No radio button for choosing signature in a ticket.

### ISSUE THREAD

**Issue by sjxiong** [osTicket/osTicket#6009]
Hi, after I upgrade the system I got a new problem as below:
![image](https://user-images.githubusercontent.com/15185770/139023891-f29c92e0-98ac-40b0-8b7e-646f764bcc6c.png)

those radio buttons are gone!

system information:
![image](https://user-images.githubusercontent.com/15185770/139024075-c22e222f-97e0-4487-802e-ddc202834a86.png)

**Comment by ntozier** [comment]
Have you tried clearing your cache?
What web browser are you using?

note: I upgraded several sites to running 1.15.4 and cannot replicate the issue that you are reporting.

**Comment by ChrisTG742** [comment]
Did you upgrade from a version that's supported by the migration scripts?
Did die upgrade-process actually start after login as admin?
(See https://docs.osticket.com/en/latest/Getting%20Started/Upgrade%20and%20Migration.html)

Else I'd second the suggestion from ntozier. Have you tried pressing Ctrl + F5 in you browser?

Is there any error in the apache-logs?

**Comment by sjxiong** [comment]
Hi, thanks for the tips. I didn't do anything and today it works suddenly normal again. so probably indeed clearing cashe would help!
