### ISSUE TITLE
Ticket numbers incorrect - "ticket_id" vs "number"

### ISSUE THREAD

**Issue by RikkiMasters** [osTicket/osTicket#6016]
See the screenshot below of how the ticket ID and ticket number are no longer synced.

![image](https://user-images.githubusercontent.com/11843864/139688006-cbd15a70-d233-4b95-a5a7-c00fe82634f6.png)

Since ticket 26589, the number has been +1 of the ticket ID.

![image](https://user-images.githubusercontent.com/11843864/139691304-303082a0-cfd9-4a31-a78e-d3743a5df7e6.png)

I'm still investigating what could have happened and what implications it has. If there is any info on this it would be of great help.

OST v1.15.2
PHP 7.3.11
MySQL 8.0.18

**Comment by protich** [comment]
It has no implication - ticket numbers can be literally anything you want. You can even configure custom ticket number sequence per help topic. You must now have it set to sequential.

**Comment by RikkiMasters** [comment]
Thanks @protich, will look deeper into this.

Still unsure how this happened in the first place as the sequence is set to increment by 1 and has never been changed.

**Comment by ntozier** [comment]
My guess would be someone deleted a ticket.

**Comment by RikkiMasters** [comment]
@ntozier have just tested that and it doesn't seem to be the issue. Will post back if I find anything but for now they're back in sync.

Thanks for the help

**Comment by protich** [comment]
The way the sequence generator works is not exactly precise. Curious why is it important to you that ticket numbers and ids are in sync?

**Comment by RikkiMasters** [comment]
@protich just because it confused staff members. We've run OST for many years so when they saw the ticket # not matching the id in the URL there was some concern.

It could be an issue if, for example, one staff member references the number in the title, then another typed that into the URL and amended the ticket, they would be editing the wrong ticket.

**Comment by JediKev** [comment]
@RikkiMasters 

You shouldn't really count on the IDs as stuff like this happens (or has the potential to). Best practice is to follow normal conventions of copying the ticket number, pasting it in the search box, and clicking the matching ticket in the results. That way regardless of if the IDs are out of sync there is no confusion.

Cheers.

**Comment by mlipok** [comment]
> The way the sequence generator works is not exactly precise. Curious why is it important to you that ticket numbers and ids are in sync?

We had the same problem in the past.
We solve them a year ago.
Do not remember how.

**Comment by mlipok** [comment]
> pasting it in the search box, and clicking the matching ticket in the results.

This way is confusing a bit, as it wont work well.

**Comment by RikkiMasters** [comment]
@JediKev That would be ideal but unfortunately not practical to enforce with lots of users who might be used to amending the URL on other systems (as I do too), or email links. Keeping them in sync works for me to eliminate this user error
