### ISSUE TITLE
[question] Upgrade osTicket

### ISSUE THREAD

**Issue by antiuser** [osTicket/osTicket#6020]
Hi there! I have installed osTicket version 1.15.1 and want to upgrade to 1.15.4.
Upgrade page said that im already on 1.15.4, is there no difference with SQL upgrades between this versions?

**Comment by JediKev** [comment]
@antiuser 

As this was a maintenance release there are no SQL changes. You only go through SQL changes when you're upgrading from one major version to the next like from 1.14.x -> 1.1.5.x.

Cheers.

**Comment by antiuser** [comment]
@JediKev thank you much! Any update for https://github.com/osTicket/osTicket/issues/5522 ?
We are waiting LTS issue xD

**Comment by JediKev** [comment]
@antiuser 

This is off-topic but I'll go ahead and respond anyways. No, if there were any updates they would be mentioned in the Issue thread.

Cheers.

**Comment by antiuser** [comment]
@JediKev you give me a chance to calm down if this is in your attention, so far I am correcting it from version to version with my patch. And sorry for my attention on this bug
