### ISSUE TITLE
Custom Field Label not applying to emails

### ISSUE THREAD

**Issue by JoKneeMo** [osTicket/osTicket#603]
I have created a custom "Contact Information" field labeled "Organization".

The variable is "org".

When I add the variable "ticket.org" to to an email, it does not add the value, it's blank. I know that if a variable is unknown it will show the variable text in the email. Since it's blank, I assume that it knows it exist, it just doesn't know where to get the data?

Is this a known issue or something unique to my situation? I'm using the latest git from the develop branch.

Thanks,

**Comment by swfideas** [comment]
Using here **v1.9.12** and as @moonman407 said, the var: `%{ticket.user.organization}` works fine, but isn't listed in the available variables.

**Comment by greezybacon** [comment]
@swfideas we addressed this in v1.10 by adding typeahead support to the editor which gives a far more comprehensive list and definition of variables availab.e
