### ISSUE TITLE
Custom Form list item only 2

### ISSUE THREAD

**Issue by ramrajone** [osTicket/osTicket#6030]
### Prerequisites
v1.15.4

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
Not sure, have not tried
* [ ] Do you have any errors in the PHP error log, or javascript console?
Nope
* [ ] Did you check the [osTicket forums](https://forum.osticket.com/)?
Yes, I have not seen the same issue
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?
Yes, none found
For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description
Custom Form created with list items to select from, but it only displays 2 on Agent side, on user side it shows all that was selected.

[Description of the bug or feature]
Example: Form 1 has options to select from a list of items let's say 5 of them, when a user submits, on their user port, it shows fine, but on the Agent side, it only displays 2, if Agent clicks on it, then it shows whatever user had selected.

### Steps to Reproduce

1. [First Step]
Submit a new ticket, with the customs form attached to Help Topic, which has lists of 5 or so items for end-users to select from
which user selects let's say 4 items and submit the ticket
2. [Second Step]
Agent gets the ticket, that list only shows 2, if Agent clicks on it, then it displays pop windows which show 4 items end-user submitted

**Expected behavior:** [What you expected to happen]
Expected to see all that was submitted

**Actual behavior:** [What actually happened]

### Versions
v1.15.4

Admin panel -> Dashboard -> Information which also additionally gives you information about your server.

Server Information
osTicket Version | v1.15.4 (6bd7884) —  Up to date
Web Server Software | Apache
MySQL Version | 5.7.36
PHP Version | 7.4.25

gdlib | Used for image manipulation and PDF printing
imap | Used for email fetching
xml | XML API
xml-dom | Used for HTML email processing
json | Improves performance creating and processing JSON
mbstring | Highly recommended for non western european language content
phar | Highly recommended for plugins and language packs
intl | Highly recommended for non western european language content
fileinfo | Used to detect file types for uploads
zip | Used for ticket and task exporting
APCu | Improves overall performance
Zend Opcache | Improves overall performance

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

**Comment by JediKev** [comment]
@ramrajone 

I am unable to replicate this issue using v1.15.4, Apache, MySQL 8, and PHP 7.4. I opened a Ticket as a User (via client portal) and selected 4 out of the 5 items in the list. As an Agent I click to view the Ticket and see all 4 items the User selected. Do you have any screenshots and example of the list content?

Cheers.

**Comment by ramrajone** [comment]
After looking closer, If I have within form like this it works
![image](https://user-images.githubusercontent.com/34359196/143945768-bed1abe6-fbe9-4388-be44-f2345a1a1f0d.png)

But, I have a form with another form that as a list which does not work
![image](https://user-images.githubusercontent.com/34359196/143946005-a7925025-261a-4b5e-82a9-ca97237d7940.png)

Choices works, Application which pulls list does not
![image](https://user-images.githubusercontent.com/34359196/143946160-25ab9c82-1f7b-47f8-b8a1-21317652076d.png)

![image](https://user-images.githubusercontent.com/34359196/143946449-bfbe60ce-4d92-43f1-978e-acc9fd7730e5.png)

**Comment by JediKev** [comment]
@ramrajone 

Apply this and retest:
- https://github.com/osTicket/osTicket/pull/5994

Cheers.

**Comment by ramrajone** [comment]
When I change it back to this displays fine, so it's broken on a newer version
Thank you

 function display() {

        return $this->getValue();
        //TODO: Allow for display mode (edit, preview or both)
        return sprintf('<a class="preview" href="#"
                data-preview="#list/%d/items/%d/preview">%s</a>',
                $this->getListId(),
                $this->getId(),
                $this->getValue()
                );
    }

**Comment by JediKev** [comment]
@ramrajone 

Exactly, you must not have applied the commit I posted above correctly as it reverts the new change back to the old way.

Cheers.

**Comment by ramrajone** [comment]
Got it, Thank you for your help
