### ISSUE TITLE
Wrong Country code / Flag for Khmer 

### ISSUE THREAD

**Issue by daw3b** [osTicket/osTicket#6031]
### Prerequisites

* [ ] Did you check the [osTicket forums](https://forum.osticket.com/)?
Yes
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?
Yes

### Description

Khmer language is correct but wrong country code (KM instead of KH) and wrong flag are shown

### Steps to Reproduce

1.  Download and install "Khmer (ខ្មែរ)" from osticket download

**Expected behavior:**
I expect to see Khmer language, Khmer code (KM) and Cambodian flag

**Actual behavior:** 

Wrong country code is selected (index.php?lang=km) and consequentially  the wrong flag is shown (KM is Comoros Island)

### Versions
osTicket Version | v1.15.4 (6bd7884)

### Workaround
I did set Cambodian flags with same coordinates of Comoros Island
.flag.flag-km {background-position: -64px -77px}
.flag.flag-kh {background-position: -64px -77px}

**Comment by JediKev** [comment]
@daw3b 

Below is a pull to address this issue:
- https://github.com/osTicket/osTicket/pull/6057

Thanks for the report! Cheers.
