### ISSUE TITLE
Duplicated subject & priority fields

### ISSUE THREAD

**Issue by Syphere** [osTicket/osTicket#6042]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [*] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [*] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

These seem to be multiple issues occurring at the same time and started showing up after editing ticket forms to not show a custom form.
Ticket lists do not show ticket titles. Opening the ticket page will show the title just fine.
When editing the ticket, the title and priority fields are shown twice and when editing these, the last set of fields take priority and saving with a title set in this field will also make it show up in the ticket lists. This does not happen when creating a new ticket and the fields are only shown once.

![image](https://user-images.githubusercontent.com/5692530/147916802-8bb64b89-3576-4f5e-89ca-fe77df58d5a7.png)
![image](https://user-images.githubusercontent.com/5692530/147916893-1a555f96-da9f-4d59-aaf1-fd8ce403b8be.png)
![image](https://user-images.githubusercontent.com/5692530/147916945-644b56e2-84ba-4011-a4a2-d28501f76b55.png)

### Steps to Reproduce

Unknown what exactly caused this to happen, but it has something to do with editing ticket forms.

**Expected behavior:** Fields only show once and title is visible in ticket list.

**Actual behavior:** Titles don't show and forms show twice.

### Versions
Server info:
osTicket: v1.15.4 (6bd7884)
Server: Apache/2.4.41 (Ubuntu)
MySQL: 10.3.32
PHP: 7.4.3

Browser: Chrome (latest)
OS: Windows 10 (21H1)

**Comment by JediKev** [comment]
@Syphere 

Please check all of your logs (general server logs, webserver error logs, PHP error logs, MySQL/MariaDB error logs, osTicket System Logs, Browser Console logs, etc.) to see if there are any related errors being thrown.

For the missing data in the queues, I would make sure the form field variable names didn't change and ensure the `ost_ticket__cdata` table exists with data.

Cheers.

**Comment by Syphere** [comment]
@JediKev Thanks for reminding me that I forgot to add that detail to the OP.
There are no errors thrown anywhere in any log file.

I also forgot to add that the ticket lists themselves are not modified and show the default data, the "subject" field is what is empty which can not be changed without some DB hackery and then some. But! after checking, the `ost_ticket__cdata` table seems to not contain the field data at all, even the priority field remains empty. There is an expiry date field that is filled in with a 0, but I have no idea where this field comes from.

**Comment by JediKev** [comment]
@Syphere 

You can completely drop the CDATA table (`DROP TABLE ost_ticket__cdata;`) and run cron manually via command line (`php /path/to/osticket/api/cron.php`). This will re-generate the table and add the first batch of data. **Note:** If you do not have a cron job setup you'll need to keep re-running cron manually until all data is added to the CDATA table.

Cheers.

**Comment by Syphere** [comment]
@JediKev
Thanks! That does add the titles of all currently opened tickets, and show the them in the ticket views. But new tickets will still have no subject until the table is dropped and cron is run once more.

Oddly enough, that other field hasn't returned in the table either. Wonder where that came from...

**Comment by Syphere** [comment]
Anyone have an other idea?
Having to set up a cron to wipe out the data and rebuild it isn't exactly something we can do. And the client complains that editing the topic after creating it is tedious (Understandable, really.)

**Comment by Syphere** [comment]
This issue has been resolved. Somehow, somewhere, data got duplicated within the `ost_form_entry` table. After deleting the duplicate rows, ticket topics were no longer blank after creating a new ticket, and the forms now only show once when editing.

I'm not able to figure out how this issue came to be, but I'm glad it's over!
