### ISSUE TITLE
New Ticket / User search / Unknown column 'A5.phone' in 'where clause'

### ISSUE THREAD

**Issue by mamo2021** [osTicket/osTicket#6043]
### Description

Error # 1054
Unknown column 'A5.phone' in 'where clause'

### Steps to Reproduce

Agent-Section:
1. Open new Ticket.
2. Enter something in Field User or Cc.

Expected: Display Searche-Results

### Versions

Admin panel -> Dashboard -> Information: 

Serverinformationen:
osTicket-Version | v1.15.4 (6bd7884)
Server-Software | Apache
MySQL-Version | 5.7.36
PHP-Version | 7.4.25

**Comment by JediKev** [comment]
@mamo2021 

This is a known issue that is on our bugsheet. There are many posts on [the Forum](https://forum.osticket.com) about this but I will answer here as well.

Please add a new dummy field to the Contact Information Form (**Admin Panel > Manage > Forms > Contact Information**), save changes, delete the newly created dummy field, save changes again, and search for a User in the User Directory (**Agent Panel > Users > User Directory**). This should drop and recreate the User CDATA table with the appropriate information. The search for the User should show results, if not, wait a few minutes, refresh the page, and try again.

Cheers.

**Comment by mamo2021** [comment]
That's it.
Thanks for the very fast answer!
