### ISSUE TITLE
Export Column "Code"

### ISSUE THREAD

**Issue by ADM-RMZ** [osTicket/osTicket#6044]
Hello everyone, I have a little problem when exporting.
icon code is exported

my version is
![image](https://user-images.githubusercontent.com/62133855/148223390-dae16a5c-8026-42d7-ae31-895bffce3a47.png)

![image](https://user-images.githubusercontent.com/62133855/148224272-bc666381-50c8-40a6-96bc-be670cb1d157.png)

![image](https://user-images.githubusercontent.com/62133855/148224992-4d5da319-e826-4b21-80ba-734a970ace34.png)

![image](https://user-images.githubusercontent.com/62133855/148229307-6c2d9188-bdd3-4c92-9055-0d4806f62510.png)

**Comment by JediKev** [comment]
@ADM-RMZ 

Search is your best friend:
- https://github.com/osTicket/osTicket/pull/5994

Cheers.

**Comment by ADM-RMZ** [comment]
@JediKev 
you're right.!!!
Happy New Year !!!
Cheers.
