### ISSUE TITLE
Ticket Thread displays wrong Filters actions or Stop processing filters not working

### ISSUE THREAD

**Issue by angelandasi** [osTicket/osTicket#6059]
### Prerequisites

* [x] Do you have any errors in the PHP error log, or javascript console? No
* [x] Did you check the [osTicket forums](https://forum.osticket.com/)? Yes, [77496](https://forum.osticket.com/d/77496-ticket-filter-stop-processing-not-working), which pointed to [#672](https://github.com/osTicket/osTicket/issues/672).
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported? Yes, currently open #5692 but my issue is a little bit different.

Previously referred to [#672](https://github.com/osTicket/osTicket/issues/672), [#802](https://github.com/osTicket/osTicket/issues/802), [#1644](https://github.com/osTicket/osTicket/pull/1644)

### Description

We have 7 filters with Execution Order set to 1 and all 7 filters have the option "Stop processing further on match!" checked.
Then we have 3 filters with Execution Order set to 2 and the option "Stop processing further on match!" unchecked.

Either the "Stop processing further on match!" doesn't work correctly or the Ticket Thread is not showing the correct actions applied by the filters on the ticket.

Today I realised this issue, but it is apparently happening for sometimes.

The involved filters have both the same Target Channel, our support e-mail address.

The NEW API Support Filter with Order 1 applies the following actions:
  Set Help Topic: To SUPPORT API
  Set Department: API SUPPORT
  Assign Team: API SUPPORT TEAM

The Support Filter with Order 2 applies the following actions:
  Set Help Topic: To REPORT A PROBLEM
  Set Department: SUPPORT
  Assign Team: SUPPORT TEAM

### Steps to Reproduce

**Expected behavior:**

What was expected is that the NEW API Support Filter with Order 1, get all the Rules matched, so it applied its actions.
Then other filters should not be launched because this filter has the option "Stop processing further on match!" checked.

So the Ticket Thread should have displayed only:

- NEW API Support Filter set Topic to Support API 04/02/2022 14:58
- NEW API Support Filter set Department to API Support 04/02/2022 14:58
- NEW API Support Filter set Team to API Support Team 04/02/2022 14:58

**Actual behavior:**

Despite the "stop processing further on match!" was checked, according to the ticket Thread, both filters seems to have been applied.
This is what was displayed on the Ticket Thread:

- NEW API Support Filter set Topic to Support API 04/02/2022 14:58
- NEW API Support Filter set Department to API Support 04/02/2022 14:58
- NEW API Support Filter set Team to API Support Team 04/02/2022 14:58
- Support Filter set Topic to Report a Problem 04/02/2022 14:58
- Support Filter set Department to Support 04/02/2022 14:58
- Support Filter set Team to Support Team 04/02/2022 14:58

But when I check the ticket details the three option seems to be set correctly according to the NEW API Support:

So it seems that the ticket Thread is not displaying correctly what was applied to the ticket, which is confusing.
I hope not all team members of both our support teams got the assignment notification but only our API Support team.

### Versions

Server Information

osTicket Version | v1.15.4 (6bd7884) —  Up to date
Web Server Software | Apache/2.4.37 () OpenSSL/1.1.1g Phusion_Passenger/6.0.6
MySQL Version | 5.7.34
PHP Version | 7.4.24

Browsers tested include:
Edge, Version 97.0.1072.76 (Version officielle) (64 bits)
Chrome, Version 97.0.4692.99 (Build officiel) (64 bits)

**Comment by JediKev** [comment]
@angelandasi 

Thank you for the report. Below is the patch to address this issue:
- https://github.com/osTicket/osTicket/pull/6108

Cheers.

**Comment by angelandasi** [comment]
@JediKev  

I did apply the patch you shared and it seems to works perfectly.

I guess I can close this issue.
Thank you a lot for your help.

Cheers,
