### ISSUE TITLE
"1" is recommended if AJAX is not working

### ISSUE THREAD

**Issue by smallfish01** [osTicket/osTicket#6062]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [ ] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

PHP settings error:"1" is recommended if AJAX is not working

### Steps to Reproduce

1. I just installed osTicket V1.15.4 in Centos 7.9, Apache version is 2.4.6, PHP version 7.4.27, Mysql version 5.5.68
2. Login to admin page, click Dashboard--Information, under PHP Settings-->cgi.fix_pathinfo: "1" is recommended if AJAX is not working
3. I have changed /etc/php.ini
cgi.fix_pathinfo=1
then restart Apache and reboot server, but the error not fixed.

Please check the screenshot.
![image](https://user-images.githubusercontent.com/4077255/153133087-2f694e5f-625f-4dd5-9519-0e44b89e2ed5.png)

![image](https://user-images.githubusercontent.com/4077255/153133305-86391cb3-f2b4-42ae-8d42-b4c03501ed83.png)

### Versions
V1.15.4
Admin panel -> Dashboard -> Information which also additionally gives you information about your server.

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

**Comment by ntozier** [comment]
cgi.fix_pathinfo is for IIS, not Apache.  You can ignore it as it doesn't do anything in Linux/Apache.  

It's more likely that since you are running CentOS which by default has SELinux is breaking your AJAX.

**Comment by smallfish01** [comment]
Hi Ntoier,

Got it. Thanks for your replied.
