### ISSUE TITLE
List of Ticket Status show empty

### ISSUE THREAD

**Issue by cayetano** [osTicket/osTicket#6063]
### Prerequisites

* [ Yes] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [NO ] Do you have any errors in the PHP error log, or javascript console?
* [YES ] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [ YES] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

The Admin Panel -> Manage -> List -> Titcket Statuses    :  Show empty

### Steps to Reproduce

1. Select option : Admin Panel -> Manage -> List -> Titcket Statuses

**Expected behavior:** [What you expected to happen]
Editable list of status and edit/add status items.
**Actual behavior:** [What actually happened]
![image](https://user-images.githubusercontent.com/851876/153208868-14a31aa9-e3e1-4c50-8ee5-2c38a81563c7.png)

### Versions
1.16 
Admin panel -> Dashboard -> Information which also additionally gives you information about your server.
![image](https://user-images.githubusercontent.com/851876/153209063-8912bb3d-a79c-4b45-8aef-1b4081144e95.png)

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.
Ubuntu 20.04 , Maria DB

**Comment by thecmdradama** [comment]
Just replicated this as well..
osTicket Version | v1.16 (27b8f55) —  Up to date
Web Server Software | Apache/2.4.52 (Ubuntu)
MySQL Version | 8.0.28
PHP Version | 8.0.14

In the apache error log I have 
`[Wed Feb 09 14:54:28.072938 2022] [proxy_fcgi:error] [pid 3711] [client x:0] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method TicketStatusList::getSortModes() in /var/www/html/support/include/staff/dynamic-list.inc.php:89\nStack trace:\n#0 /var/www/html/support/scp/lists.php(205): require()\n#1 {main}\n  thrown in /var/www/html/support/include/staff/dynamic-list.inc.php on line 89', referer: https://support.mydomain.com/scp/lists.php`

**Comment by JediKev** [comment]
@cayetano @thecmdradama 

Yep working on it now.

**Comment by ntozier** [comment]
Out of curiosity Is this happening on an upgraded system, a fresh install, or both?

**Comment by JediKev** [comment]
@ntozier It's both.

Here is the fix:
- https://github.com/osTicket/osTicket/pull/6064

@cayetano Thanks for the report.

Cheers.

**Comment by thecmdradama** [comment]
Working as expected now after adding that fix, thanks @JediKev

**Comment by JediKev** [comment]
@cayetano @thecmdradama Pull updated to match old behavior.

**Comment by cayetano** [comment]
HI,
This path work correctly for mi.

THAKNS!!!!!!

Regards,
Cayetano

**Comment by mrkylegp** [comment]
Can confirm I had this issue and #6064 solves this. Thanks a lot @JediKev!
