### ISSUE TITLE
Deleting email after piping

### ISSUE THREAD

**Issue by toxpal** [osTicket/osTicket#6067]
I'm not sure if this is a "problem" of osTicket or cPanel, so please accept my apologies if it has nothing to do with osTicket.

When using POP3 to fetch emails and convert them to tickets, there's option to auto-delete emails after fetching them, which is great. However, when using piping, all the emails still exist in inbox after converting them to tickets, which makes email box to grow in size every day and requires manual cleaning daily.

Is there a way to auto-delete piped emails (just like POP3 options works)?

**Comment by ntozier** [comment]
Generally piping functions in a way that instead of delivering an email to a mailbox, it is delivered to a script as an input.  This would mean that there should not be a local copy.  You would probably need to talk to your email host to find out why there is a copy being saved some where.

**Comment by JediKev** [comment]
@toxpal 

I think you would benefit from the Email Piping documentation below:
- https://docs.osticket.com/en/latest/Getting%20Started/Email%20Piping.html

Cheers.

**Comment by toxpal** [comment]
@JediKev

I checked the documentation and email piping itself works perfectly for me, but docs don't mention anything about deleting emails. Can you make a screenshot and mark the part which contains at least a small bit of information which I'm asking for?

Cheers.

**Comment by JediKev** [comment]
@toxpal 

The very first sentence reiterates what @ntozier said:
> The email piping is a technique of sending email message as an input to a program rather than appending the message to the mailbox file

Cheers.

**Comment by JediKev** [comment]
@toxpal 

Your host/CPanel could be potentially sending the mail to the script and the mailbox. You should contact your hosting provider to see if there is any way to prevent it from sending to the mailbox when piping.

Cheers.

**Comment by toxpal** [comment]
I have a VPS, but the strange part is that I also have another pipe script (same server, different domain) and it works fine (no emails left in inbox). That's why I'm confused if it has something to do with osTicket or server itself.

**Comment by JediKev** [comment]
@toxpal 

It's definitely on the server end of things. osTicket simply gets passed data, it does not have any control over the mail server and its settings.

Cheers.

**Comment by toxpal** [comment]
Closing the issue since it's probably related to server setup only.
