### ISSUE TITLE
Emails not fetching unless using cron job 1.16

### ISSUE THREAD

**Issue by cslob** [osTicket/osTicket#6069]
After I updated to 1.16 (and php 8) emails are no longer being fetched automatically. If I create a cron job and tick the "fetch on auto-cron" box, it does work. If I uncheck the box, just leaving email fetching enabled, no emails are pulled in. This was working in 15.4.

**Comment by JediKev** [comment]
@cslob 

Review your error logs for any related errors. Once found post them here.

Cheers.

**Comment by cslob** [comment]
@JediKev
I have debugging enabled and checked apache2/error.log and I am not seeing any errors. When I enable cron for email fetching there is a debug log that the job executed. Any additional log locations to check?

**Comment by JediKev** [comment]
@cslob 

I am unable to replicate the issue using Apache, PHP 8.0, MySQL 8, and v1.16. Please apply the following changes to see if they resolve your issue:
- https://github.com/osTicket/osTicket/pull/6065
- https://github.com/osTicket/osTicket/pull/6068

All of the above will be included in the next release.

Cheers.

**Comment by cslob** [comment]
@JediKev 

Those changes did not help. I did however notice PHP 8.1 was installed during the update, even though 8.0 was showing in the osTicket dashboard. I removed that version and email started fetching on their own.
