### ISSUE TITLE
API not creating ticket due to missing required field

### ISSUE THREAD

**Issue by cslob** [osTicket/osTicket#6070]
I have an API call that creates a ticket. After upgrading to 1.16 (the API call was working in 1.15.x) when the API call happens I get:

API Error (400)
Unable to create new ticket: validation errors: 36: Building is a required field *

I confirmed the building parameter is being passed in the JSON, but unless I make it not required for the end user, it no longer creates the ticket.

**Comment by JediKev** [comment]
@cslob 

Post a screenshot of your form, the field (and its configurations) it's complaining about, and an example API call that you make. With this information we can better track the issue.

Cheers.

**Comment by cslob** [comment]
I checked what php extensions were installed after upgrading to 8 and there were some 7.4 extensions still installed. Once the extensions were removed, the API behaved as expected.
