### ISSUE TITLE
Ticket status list not showing properties after upgrade to v1.16

### ISSUE THREAD

**Issue by mrkylegp** [osTicket/osTicket#6072]
After upgrading from v1.15.4 to v1.16, I can no longer edit my ticket statuses list because it does not display the properties.

I updated to PHP 8.1 and had the tick when upgrading to osticket v1.16.
This is not a browser or cache issue. How can I fix this?

See image:
![Screenshot 2022-02-12 165739](https://user-images.githubusercontent.com/52687659/153699102-3f49ea52-7565-4310-ae84-a7afdf12e063.png)

**Comment by JediKev** [comment]
@mrkylegp 

Search is your friend:
- https://github.com/osTicket/osTicket/pull/6064

Cheers.

**Comment by mrkylegp** [comment]
@JediKev Thanks a lot. #6064 solved the issue for me. Great work.
