### ISSUE TITLE
Form's to create new issues/feature request/bug reports

### ISSUE THREAD

**Issue by mlipok** [osTicket/osTicket#6073]
### Prerequisites

not related

### Description

please take a look here:
[BookStack example how to create new issue](https://github.com/BookStackApp/BookStack/issues/new/choose)

They have some kind of awesome form which automatically is created when you open new issue.

Are you able to do the same ?

**Comment by JediKev** [comment]
@mlipok 

Not at the moment, but we can look into this. We currently have a default template for Issues but not for feature requests. The only forms we'd have really is New Issue and Feature Request. Security vulnerabilities are reported externally to our email and everything else is covered by our Forum.

Cheers.
