### ISSUE TITLE
PHP Fatal Error con manage custom lists

### ISSUE THREAD

**Issue by medisoft** [osTicket/osTicket#6076]
### Prerequisites

* [Yes] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [Yes] Do you have any errors in the PHP error log, or javascript console?
* [Yes] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [Yes] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

When trying to edit the predefined Ticket Statuses the page is incomplete. When looking at server logs I found a PHP error

`[Tue Feb 15 04:41:43.895439 2022] [proxy_fcgi:error] [pid 100132] [client 2806:10be:8:3341:8252:71f3:3453:89b0:55606] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method TicketStatusList::getSortModes() in /var/www/tickets.domitai.com/include/staff/dynamic-list.inc.php:89\nStack trace:\n#0 /var/www/tickets.domitai.com/scp/lists.php(205): require()\n#1 {main}\n  thrown in /var/www/tickets.domitai.com/include/staff/dynamic-list.inc.php on line 89', referer: https://tickets.domitai.com/scp/lists.php`

![image](https://user-images.githubusercontent.com/5624499/153994353-f21a787c-d1ed-4ff7-b840-9c86f02b675c.png)

![image](https://user-images.githubusercontent.com/5624499/153994364-b387450a-db2b-43de-a3b2-7b4aecf57fc6.png)

### Steps to Reproduce

1. Login to admin panel, go to manage->lists and click Ticket Statuses

**Expected behavior:** 

Show the details of ticket statuses item

**Actual behavior:** 

Incomplete rendering of the page and fatal error in the server logs

### Versions

![image](https://user-images.githubusercontent.com/5624499/153994396-f894ad45-ef23-4825-945b-f6500d308b22.png)

Ubuntu 20.04, Chrome and Brave on linux too.

**Comment by JediKev** [comment]
@medisoft 

Search is your friend:
- https://github.com/osTicket/osTicket/pull/6064

Cheers.
