### ISSUE TITLE
Set table width via css instead of inline width attribute

### ISSUE THREAD

**Issue by roelvanmeer** [osTicket/osTicket#6077]
Currently the width of many of the main osTicket tables is hardcoded to 940px via an inline width attribute. If this width would come from css, it would be easier to change it, without having to change it in 83 places. Would you be interested in a patch that achieves this?

**Comment by JediKev** [comment]
@roelvanmeer 

There have been multiple pulls in the past to accomplish this. None of them have been accepted as we are sticking with the traditional layout in the legacy code. In v2.0 (full rewrite) it will be fully responsive, include all new UI, and will be theme-able. You can follow the v2.0 roadmap here:
- https://github.com/osTicket/roadmap

Cheers.

**Comment by roelvanmeer** [comment]
@JediKev I wasn't looking to change the layout itself, only to move the width styling from inline attributes to a css class. Would that perhaps be accepted?

**Comment by JediKev** [comment]
@roelvanmeer 

We are trying to refrain from any changes like that in the legacy code.

Cheers.

**Comment by roelvanmeer** [comment]
@JediKev Ah, too bad. Thanks!
