### ISSUE TITLE
1.16.1 working with php8.0-fpm / nginx?

### ISSUE THREAD

**Issue by kangaroo72** [osTicket/osTicket#6078]
I'm trying to run osTicket on Ubuntu 20.04LTS where NGINX as Reverse Proxy is running.
Here the vhost for osTicket

`server {
  listen 127.0.0.1:87;
        server_name default;

        root   /var/www/osticket/;

        access_log  /var/log/nginx/access.log;
        error_log  /var/log/nginx/error.log;

        index index.php;
        client_max_body_size 200M;
        client_body_buffer_size 100M;
        client_header_buffer_size 10M;
        large_client_header_buffers 2 10M;
        client_body_timeout 12;
        client_header_timeout 12;
        keepalive_timeout 15;
        send_timeout 10;
        gzip             on;
        gzip_comp_level  2;
        gzip_min_length  1000;
        gzip_proxied     expired no-cache no-store private auth;
        gzip_types       text/plain application/x-javascript text/xml text/css application/xml;

        set $path_info "";

        location ~ /include {
          deny all;
          return 403;
       }

I'm still getting 502 no Gateway.`

Is osTicket compatible with that setup?

**Comment by JediKev** [comment]
@kangaroo72 

osTicket does not support NGINX out of the box. You must look at guides/recipes online that show what configurations you need for NGINX.

Cheers.

**Comment by kangaroo72** [comment]
thx for quick reply - I'll try

**Comment by JediKev** [comment]
@kangaroo72 

Here is a recipe from the NGINX website:
- https://www.nginx.com/resources/wiki/start/topics/recipes/osticket/

Cheers.

**Comment by kangaroo72** [comment]
Thanks!!

**Comment by kangaroo72** [comment]
Yihaaaa

![grafik](https://user-images.githubusercontent.com/6906390/154165037-c4d27408-3fcb-42f4-9898-9dae53496dcb.png)

**Comment by kangaroo72** [comment]
urgs.... now white screen - I will investigate....

**Comment by kansoit** [comment]
Hello.
This used to be my nginx config. I hope this can help

```
server {

    listen 4500;
    listen [::]:4500;

    server_name  localhost  www.localhost;

    root /var/www/osticket;
    index index.php;

    access_log /var/log/nginx/osticket/access.log;
    error_log /var/log/nginx/osticket/error.log;

    set $path_info "";

    location ~ /include {
      deny all;
      return 403;
    }

    if ($request_uri ~ "^/api(/[^\?]+)") {
      set $path_info $1;
    }

    location ~ ^/api/(?:tickets|tasks).*$ {
      try_files $uri $uri/ /api/http.php?$query_string;
    }

    if ($request_uri ~ "^/scp/.*\.php(/[^\?]+)") {
      set $path_info $1;
    }

    if ($request_uri ~ "^/.*\.php(/[^\?]+)") {
      set $path_info $1;
    }

    location ~ ^/scp/ajax.php/.*$ {
      try_files $uri $uri/ /scp/ajax.php?$query_string;
    }
    location ~ ^/ajax.php/.*$ {
      try_files $uri $uri/ /ajax.php?$query_string;
    }

    location / {
      try_files $uri $uri/ index.php;
    }

    location ~ \.php$ {
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
      include fastcgi_params;
      #include snippets/fastcgi-php.conf;
      fastcgi_pass unix:/run/php/php7.4-fpm.sock;
      fastcgi_param PATH_INFO $path_info;
      #fastcgi_pass 127.0.0.1:8888; 
    }
}
```
