### ISSUE TITLE
Compatibility with systems without GLOB_BRACE and PHP8

### ISSUE THREAD

**Issue by adam-dej** [osTicket/osTicket#6079]
### Prerequisites

* [X] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [X] Do you have any errors in the PHP error log, or javascript console?
* [X] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [X] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

Constant `GLOB_BRACE` used by function `glob` is not available on some non-GNU systems, notably Alpine Linux. Use of this constant throws an error on PHP >= 8. After upgrading to osTicket v1.16.x, when trying to add plugins, an empty list of plugins is shown, and the following error is logged:

```
[16-Feb-2022 13:32:01 UTC] PHP Fatal error:  Uncaught Error: Undefined constant "GLOB_BRACE" in /var/www/html/include/class.plugin.php:254
Stack trace:
#0 /var/www/html/include/staff/plugin-add.inc.php(15): PluginManager::allInfos()
#1 /var/www/html/scp/plugins.php(66): require('/var/www/html/i...')
#2 {main}
  thrown in /var/www/html/include/class.plugin.php on line 254
```

If i remove `GLOB_BRACE` from `include/class.plugin.php`, the list works as expected. As path to plugins is hardcoded and does not contain any braces, `GLOB_BRACE` would seem to be a no-op in that file in the first place. However, it is also used in other files where it is not a no-op:

- `include/cli/modules/unpack.php`
- `include/cli/modules/deploy.php`

### Steps to Reproduce

1. Install osTicket on Alpine Linux using Docker image `php:8.0-fpm-alpine3.15`
2. Add plugins to `include/plugins` folder as instructed
3. Navigate to Admin Panel -> Manage -> Plugins -> "add one"

**Expected behavior:** List of available plugins is shown

**Actual behavior:** Empty list is shown, and the above error is logged

### Versions

  - osTicket Version: v1.16.1 (b42ddc7)
  - Web Server Software: nginx/1.20.2
  - MySQL Version: 5.7.37
  - PHP Version: 8.0.15

Running in Docker container based on official PHP image `php:8.0-fpm-alpine3.15`.

**Comment by joeldeteves** [comment]
After upgrading to 1.16.1 + PHP v8.0, I am having this problem as well.

**Comment by JediKev** [comment]
@adam-dej @joeldeteves 

Thank you both for the reports. Below is the patch to address the issue:
- https://github.com/osTicket/osTicket/pull/6115

We don't use it there anyways so we are completely removing it.

Cheers.

**Comment by joeldeteves** [comment]
> @adam-dej @joeldeteves
> 
> Thank you both for the reports. Below is the patch to address the issue:
> 
> * [issue: Undefined Constant GLOB_BRACE #6115](https://github.com/osTicket/osTicket/pull/6115)
> 
> We don't use it there anyways so we are completely removing it.
> 
> Cheers.

Thanks @JediKev and @adam-dej - I have temporarily patched my docker install using Adam's method for now (using 'patch' in Alpine is an elegant workaround and I've started using this to disable the IP filter on the API as well).

Glad to hear it's not needed and will be addressed in a future release.

Cheers,
