### ISSUE TITLE
Path traversal issue in security auditing. 

### ISSUE THREAD

**Issue by hitha** [osTicket/osTicket#6081]
/osticket/upload/js/./select2.min.js
osticket/upload/css//loadingbar.css
/osticket/upload/css/./loadingbar.css
osticket/upload/css//thread.css
osticket/upload/scp/css/./dropdown.css
osticket/upload/css//jquery-ui-timepicker-addon.css
/osticket/upload/scp/js//dashboard.inc.js
/osticket/upload/scp/js//dashboard.inc.js&ust=1644915720000
osticket/upload/scp/css/dropdown.css?cb6766e=%2Fdropdown.css

**Comment by JediKev** [comment]
@hitha 

Please read our security instructions:
- https://github.com/osTicket/osTicket/blob/develop/SECURITY.md

Cheers.
