### ISSUE TITLE
Form field type "Choices" show the key and should show the value

### ISSUE THREAD

**Issue by monkiki** [osTicket/osTicket#6082]
### Description
I've created a new Form Field type "Choices" and when I choose an option, the key is displayed and not the value.

### Steps to Reproduce
Create a Form Field type "Choice" whith these options:
```
t1:Tipo 1
t2:Tipo 2
t3:Tipo 3
```

Open a ticket and choose option "Tipo 2": once selected the value displayed is "t2". It should show the "Tipo 2" string.

### Versions
- osTicket (v1.15.4)

**Comment by ntozier** [comment]
Environment details?

That version is old.  You should upgrade to current and retest.

Also from the UI where you setup the Choices: "Note: If you have more than two choices, use a List instead."

**Comment by monkiki** [comment]
## Environment
- MariaDB 10.3.32
- PHP 7.4.3

The problem persist on osTicket v1.15.6.

About the message, I'm not sure what it means. Should I use a List field and not a Choice one? Where is the List field?
![image](https://user-images.githubusercontent.com/130590/154988465-a667fc89-42ca-4e3b-913e-b33d2145b42a.png)

**Comment by JediKev** [comment]
@monkiki 

Where are you seeing the key at exactly? On inline edit, in queues, etc.

Cheers.

**Comment by JediKev** [comment]
@monkiki 

I just tested this with v1.15.6 and using the same exact choices as you and cannot replicate this issue (on both Client Portal and Agent Panel). When a choice is selected when creating a new ticket it shows the proper value and even after creating the ticket.

### Creating Ticket
<img width="904" alt="Screen Shot 2022-02-21 at 10 03 02" src="https://user-images.githubusercontent.com/11823401/154990579-61a6471d-6da2-4dbb-8314-71655d0b3845.png">

### Ticket Created
<img width="281" alt="Screen Shot 2022-02-21 at 10 04 01" src="https://user-images.githubusercontent.com/11823401/154990617-e658d538-a9c3-440e-b2bb-88b75b5ff7bd.png">

Cheers.

**Comment by monkiki** [comment]
Yes, it works when creating the ticket but I've found that the problem occurs when you edit the choice from ticket view, once created,
![image](https://user-images.githubusercontent.com/130590/154991143-c85cd7e1-4199-4503-b528-a534340ae49f.png)

**Comment by JediKev** [comment]
@monkiki 

Refresh the page and it will be correct.

Cheers.

**Comment by monkiki** [comment]
Ups, this is a bit odd. I think it should show the value after editing, not the key. It's a quite confussing.

Cheers.

**Comment by nandi96** [comment]
@monkiki  Any solution?

**Comment by monkiki** [comment]
As told by @JediKev, just refresh the page.

**Comment by nandi96** [comment]
Ok, but it is annoying, when change the date and first show in wrong timezone, before refresh.
Thanks for the quick answer!

**Comment by monkiki** [comment]
Yes, it's but right now I can see any workaround.
