### ISSUE TITLE
Installer: Uncaught mysqli_sql_exception: Table [table name] doesn't exist in [path]\include\mysqli.php:189

### ISSUE THREAD

**Issue by coyoteteeth** [osTicket/osTicket#6083]
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [x] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

On install, after putting in the basic configuration information including the database and credentials, the following PHP Fatal Error is thrown upon submission of the form.

`
PHP Fatal Error:    Uncaught mysqli_sql_exception: Table 'ostickettest.ost_config' doesn't exist in C:\inetpub\osticket\include\msqli.php:189
Stack trace:
#0 C:\inetpub\osticket\include\mysqli.php(189): mysqli->query()
#1 C:\inetpub\osticket\setup\inc\class.installer.php(106): db_query()
#2 C:\inetpub\osticket\setup\install.php(52): Installer->install()
#3 {main}
    thrown in C:\inetpub\osticket\include\mysqli.php on line 189
`

I tried disabling all error logging and reporting in PHP to test, but the error was being thrown by the extension, not PHP itself, so these settings did not seem to have any effect.

The error can be stopped by adding `mysqli_report(MYSQLI_REPORT_ERROR);` to `include\mysqli.php`, after which the installer will run normally and complete the installation.

### Steps to Reproduce

1. Install IIS with CGI
2. Install & configure PHP
4. Install & configure required PHP extensions
5. Configure IIS for PHP
6. Install URL rewrite for IIS
7. Install MariaDB
8. Create database `ostickettest`
9. Create database user account and grant full access to `ostickettest`
10. Create Windows service user account
11. Create directory `c:\inetpub\osticket`
12. Move contents of `osTicket-v1.16.1\upload` to `c:\inetpub\osticket\`
13. Assign read permissions to service account for `c:\inetpub\osticket` and `c:\apps\php`
14. Verified subfolders and files are receiving inherited permissions correctly
15. Copying `ost-sampleconfig.php` to `ost-config.php` and assigning service account read/write permissions
16. Create new app pool in IIS, set `Process Model > Identity` to service account
17. Create to new site `osticket` in IIS with local path `c:\inetpub\osticket` and bind to localhost:80 (127.0.0.1 & ::1)
18. Start setup in browser

**Expected behavior:** [What you expected to happen]

The installer would to connect to the database and create the required tables automatically.

**Actual behavior:** [What actually happened]

Installer threw a PHP Fatal Error upon checking the database for the existence of the table `ostickettest.ost_config`.

### Versions

osTicket: 1.16.1 (b42ddc7)
Web server: Microsoft IIS 10.0.19041.1
PHP version: 8.1.3
MariaDB Version: 10.7.3
OS version: Windows 10 21H2
OS build: 19044.1526
Web browser: Mozilla Firefox 91.0.1 (64-bit)

Admin panel -> Dashboard -> Information which also additionally gives you information about your server.

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

**Comment by JediKev** [comment]
@coyoteteeth 

Please read the requirements. v1.16.1 only supports PHP 8.0.

Cheers.

**Comment by dasoe** [comment]
Hi all,

Thanks for the information. This is the case for 16.3 as well, I assume? As I have been running in the same problem.
I found and read these two sentences when downloading:

`To install osTicket, your web server must have PHP 8.0 and MySQL 5.0 (or better) installed. `

`Requirements: HTTP server running Microsoft® IIS or Apache, PHP version 8, MySQL database version 5.5 `

I did not really understand, that php 8.1 is not working. It would be great if you could be a bit more specific here.

**Thanks for your great work and have a good day!**
oe

**Comment by ntozier** [comment]
@dasoe 
So your saying here:
![D6g4VSlQjv](https://user-images.githubusercontent.com/1315768/185949238-71ba7f42-9746-4685-8990-7509511374a9.png)

@JediKev can we get the 8 changed to 8.0 please?

**Comment by dasoe** [comment]
Hello [ntozier](https://github.com/ntozier)!
Hello [JediKev](https://github.com/JediKev)!

yes, exactly, your image shows one of the sentences I read. The second is found in the [installation instructions](https://docs.osticket.com/en/latest/Getting%20Started/Installation.html#prerequisites) (sorry, I should have mentioned in the first place):

`To install osTicket, your web server must have PHP 8.0 and MySQL 5.0 (or better) installed. `

Here I wrongly assumed that the brackets ("or better") are valid for both php and mysql. My fault, but still maybe a bit mistakable.

Thanks a lot for your quick reaction!
oe
