### ISSUE TITLE
Upgrade from 1.15.4 to 1.16.1; login fails

### ISSUE THREAD

**Issue by alancunnane** [osTicket/osTicket#6085]
I duplicated our current osTicket setup, and updated from php7.4 to php8.0.  

I downloaded the files for 1.16.1 and unzipped them, and uploaded the files from the upload folder to the installation folder.  

When trying to access the control panel, the login page does not accept my username/password, and only refreshes to its blank state.

I have tried using the pwreset.php script, but that gives me the "Valid CSRF Token Required" error message when the form is submitted.  I have succeeded in connecting to the database from this server, so that isn't the problem.  

I was getting 500 errors, but deleting the plugins solved that issue for me.  I also had 422 errors; commenting out the line "Http::response(422);" in login.php (both of them) resolved that.

Apart from that, trawling the forums hasn't yielded anything I can use to resolve this.

OS: Ubuntu 20.04; PHP version 8.0.16.  Tested on Edge and Brave browsers.

Do you have any ideas?

Thanks,
Alan

**Comment by JediKev** [comment]
@alancunnane 

What plugins were you using? If you were using an authentication plugin it might be that your system/profile is still set to use the authentication plugin that is no longer available.

Cheers.

**Comment by alancunnane** [comment]
@JediKev 

The only plugins we were using were Slack Notifier and Ticket Closer.  Would removing these cause problems with authentication?

Alan

**Comment by JediKev** [comment]
@alancunnane 

Not that I know of, of course those are 3rd party plugins that are not supported by the core team.

Anyways, you should check your logs (general server logs, webserver error logs, PHP error logs, MySQL/MariaDB error logs, osTicket System Logs, Browser Console logs, etc.) to see if there are any related errors as I cannot replicate this issue.

Cheers.

**Comment by ntozier** [comment]
> updated from php7.4 to php8.0.

Did you confirm that the webserver was actually using PHP8 on the site?

**Comment by alancunnane** [comment]
![osticket-php-info](https://user-images.githubusercontent.com/35136516/155476312-8bf47d55-de6a-4e70-8731-188c235e1288.png)

**Comment by alancunnane** [comment]
I've tried installing osticket in a separate location, copying ost-config.php to /include/, and running the upgrade.  This failed with the attached error.
![upgrade-error](https://user-images.githubusercontent.com/35136516/155505568-1c0eee4e-1ca8-484c-918e-f149d39b4a9a.png)


The Apache error log had the following: 
 
[Thu Feb 24 10:13:59.807474 2022] [proxy_fcgi:error] [pid 53097:tid 140709110744832] [client 54.228.194.245:54982] AH01071: Got error 'PHP message: PHP Warning:  ini_set(): Session ini settings cannot be changed when a session is active in /var/www/html/support/bootstrap.php on line 19PHP message: PHP Warning:  session_cache_limiter(): Session cache limiter cannot be changed when a session is active in /var/www/html/support/bootstrap.php on line 21', referer: http://18.202.240.83/support/scp/upgrade.php?c=1&r=61

I've tried setting session.auto_start to 0 in php.ini, but that hasn't helped.

I'm still able to log into the old version of osticket on the original server, so the database is OK (so far).

**Comment by alancunnane** [comment]
Here are screenshots of the process - I don't know if any of this helps?

![image](https://user-images.githubusercontent.com/35136516/155557208-727af089-41d5-41cf-a566-8191ccb81572.png)

![image](https://user-images.githubusercontent.com/35136516/155557392-594bbdd5-ff85-4b04-8f65-2ceb3934f82d.png)

![image](https://user-images.githubusercontent.com/35136516/155557512-153d9bb4-0b90-43a0-b551-4c6469fdceca.png)

**Comment by JediKev** [comment]
@alancunnane 

Well the upgrade patch literally runs only two small statements. One alters the help_topic table and updates the length for the topic column. The other just updates the schema_signature in the config table. I don't see how those will fail. Please check your Apache, PHP, and MySQL error logs for any related errors. You can also login to the db and look at the syslog table to see if an error is being logged there.

Cheers.

**Comment by alancunnane** [comment]
Apache error.log: 

[Thu Feb 24 15:40:52.128373 2022] [proxy_fcgi:error] [pid 53097:tid 140708891518720] [client 54.228.194.245:50774] AH01071: Got error 'PHP message: PHP Warning:  ini_set(): Session ini settings cannot be changed when a session is active in /var/www/html/support/bootstrap.php on line 19PHP message: PHP Warning:  session_cache_limiter(): Session cache limiter cannot be changed when a session is active in /var/www/html/support/bootstrap.php on line 21', referer: http://18.202.240.83/support/scp/upgrade.php?c=1&r=80

[Thu Feb 24 15:40:52.128560 2022] [proxy_fcgi:error] [pid 53097:tid 140708891518720] [client 54.228.194.245:50774] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught ValueError: Path cannot be empty in /var/www/html/support/include/class.translation.php:568\nStack trace:\n#0 /var/www/html/support/include/class.translation.php(352): Translation->load_tables()\n#1 /var/www/html/support/include/class.translation.php(380): gettext_reader->get_plural_forms()\n#2 /var/www/html/support/include/class.translation.php(414): gettext_reader->select_string()\n#3 /var/www/html/support/include/class.i18n.php(576): gettext_reader->ngettext()\n#4 /var/www/html/support/include/staff/syslogs.inc.php(196): _N()\n#5 /var/www/html/support/scp/logs.php(56): require('...')\n#6 {main}\n  thrown in /var/www/html/support/include/class.translation.php on line 568', referer: http://18.202.240.83/support/scp/upgrade.php?c=1&r=80

Uploading en_GB.phar to the i18n folder seems to have resolved the second error, but the first keeps coming up.

Not sure where to go from here, though.  Would it be any use to run those two queries manually?

Thanks,
Alan

**Comment by JediKev** [comment]
@alancunnane 

Yea, you can.

Cheers.

**Comment by alancunnane** [comment]
Could you possibly share the queries with me?

Thanks.

**Comment by JediKev** [comment]
@alancunnane 

You can look at the commit history to find the Upgrader patch or just go to the `include/upgrader/streams/core/` directory and look at the most recent patch. With this being said, here is the file:
- https://github.com/osTicket/osTicket/blob/develop/include/upgrader/streams/core/add62892-c37e1656.patch.sql

Cheers.

**Comment by alancunnane** [comment]
Outstanding!  Those queries resolved my issues and I'm now able to log in!

Many thanks,
Alan

**Comment by JediKev** [comment]
@alancunnane 

Nice! Glad you got it resolved. I'm still confused as to why the upgrader failed for you but no worries now.

Cheers.
