### ISSUE TITLE
Can't send SMTP mail when `mbstring` is being used instead of `iconv`

### ISSUE THREAD

**Issue by jurajlutter** [osTicket/osTicket#6093]
### Prerequisites

* [X] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [X] Do you have any errors in the PHP error log, or javascript console?
* [X] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [X] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

When osTicket (1.16.1) wants to send an e-mail (using SMTP) and `mbstring` is being used instead of `iconv`, then the following error occurs:

```
2022/03/05 22:17:46 [error] 8471#100814: *474 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ValueError: mb_convert_encoding(): Argument #2 ($to_encoding) must be a valid encoding, "localhost" given in /usr/local/www/osticket/include/class.charset.php:64
Stack trace:
#0 /usr/local/www/osticket/include/class.charset.php(64): mb_convert_encoding()
#1 /usr/local/www/osticket/include/class.format.php(60): Charset::transcode()
#2 /usr/local/www/osticket/include/class.mailparse.php(584): Format::mimedecode()
#3 /usr/local/www/osticket/include/pear/Mail.php(255): Mail_Parse::parseAddressList()
#4 /usr/local/www/osticket/include/pear/Mail/smtp.php(291): Mail->parseRecipients()
#5 /usr/local/www/osticket/include/class.mailer.php(587): Mail_smtp->send()
#6 /usr/local/www/osticket/include/class.email.php(190): Mailer->send()
#7 /usr/local/www/osticket/scp/emailtest.php(38): Email->send()
#8 {main}
```

### Steps to Reproduce

1. Make an operation with ticket (with e-mail notification configure)
2. OR, send an e-mail using Diagnostics in Admin panel

**Expected behavior:** E-mail being sent

**Actual behavior:** Error is being generated and HTTP 500 is returned.

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about your server.

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

osTicket 1.16.1, PHP 8.1, FreeBSD 13.0

**Comment by JediKev** [comment]
@jurajlutter 

Please downgrade to PHP 8.0. None of the current osTicket versions support PHP 8.1.

Cheers.

**Comment by jurajlutter** [comment]
FYI, works with php 8.0.
