### ISSUE TITLE
REQ: Ticket History > Show matched filters

### ISSUE THREAD

**Issue by quadcom** [osTicket/osTicket#6098]
### Description
I've recently come across a series of error tickets from Zapier. I set up a filter to tag them as important and assign them to myself. For some reason, these tickets are getting grabbed by some other filter in some way but I am not sure WHICH filter is grabbing them. That filter is automatically closing the tickets!

It would be great if the ticket activity history showed which filter matched the ticket so that I can review the filter config to figure out why. 

![image](https://user-images.githubusercontent.com/7085931/158403840-1a2a5685-a2f9-4d85-809f-cba8d02da8c7.png)

**Comment by JediKev** [comment]
@quadcom 

This is already a thing in v1.15.6 and v1.16.1. Please upgrade to take advantage of this new feature.

You can see the merged pull here:
- #5947 

Cheers.
