### ISSUE TITLE
[Issue] 1.16.1 Fatal error in ajax.tickets.php

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket#6112]
[22-Mar-2022 20:02:07 UTC] PHP Fatal error:  Uncaught Error: preg_match(): Argument #3 ($matches) cannot be passed by reference in C:\inetpub\osTicket\Live\include\ajax.tickets.php:58
Stack trace:
#0 C:\inetpub\osTicket\Live\include\class.dispatcher.php(145): TicketsAjaxAPI->lookup()
#1 C:\inetpub\osTicket\Live\include\class.dispatcher.php(38): UrlMatcher->dispatch()
#2 C:\inetpub\osTicket\Live\include\class.dispatcher.php(120): Dispatcher->resolve()
#3 C:\inetpub\osTicket\Live\include\class.dispatcher.php(38): UrlMatcher->dispatch()
#4 C:\inetpub\osTicket\Live\scp\ajax.php(316): Dispatcher->resolve()
#5 {main}
  thrown in C:\inetpub\osTicket\Live\include\ajax.tickets.php on line 58

### Versions

Server Information
--
osTicket Version | v1.16.1 (b42ddc7) —  Up to date
Web Server Software | Microsoft-IIS/8.5
MySQL Version | 5.7.31
PHP Version | 8.0.17

Server 2012 R2

**Comment by JediKev** [comment]
@jdelhome3578 

Search is your friend 😉 
- https://github.com/osTicket/osTicket/pull/6080

Cheers.

**Comment by jdelhome3578** [comment]
@JediKev I guess I needed to look harder.
