### ISSUE TITLE
Translation on javascript level not working

### ISSUE THREAD

**Issue by empty88** [osTicket/osTicket#6113]
Any messages or captions in javascript are not translated. Tested on 1.15.6 with german phar file.
Even the jquery datepicker stays english, but the regional settings for datepicker and the phrases I testet are included in the phar file.

It seems that all is done to make this work, but it does not. $.oststrings variable is undefined.

**Comment by JediKev** [comment]
@empty88 

I just tested this and I can see the datepicker being translated with German PHAR (see image below). I can see that some strings are not translated though as the datepicker itself doesn't have those strings available (ie. `Time`, `Hour`, etc.). When we build language packs we fetch the i18n file from the datepicker repo on Github and just add it to our PHAR. For example, for German [we grab this file](https://raw.githubusercontent.com/jquery/jquery-ui/master/ui/i18n/datepicker-de.js) and add it to the `de.phar`.
<img width="737" alt="Screen Shot 2022-03-23 at 09 39 00" src="https://user-images.githubusercontent.com/11823401/159724990-c5dcca72-c554-4914-aad4-53b577dd3399.png">

Cheers.

**Comment by empty88** [comment]
I tried it now with a new webroot, fresh copy of 1.15.6, plugins auth-passthru and auth-ldap and new phar file from osticket.com and this is how it looks like:
![screenshot](https://user-images.githubusercontent.com/29315283/159738507-40ffa980-2c35-4103-9c63-d2b2e8362262.PNG)

Because osTicket is running on IIS i need to remove the provided web.config to be able to configure the site in IIS, otherwise it gives me errors. I saw there are URL-Rewriting rules in it. Could this be the problem?
PHP: 7.4.25

**Comment by JediKev** [comment]
@empty88 

I am unsure as I’m not able to replicate this.

Cheers.

**Comment by JediKev** [comment]
@empty88 

So I just tested this on IIS using v1.15.6, PHP 7.4, and the latest `de.phar` from the website and I'm able to see the translations just fine (see image below). I also do not have to remove the `web.config` file at all. Seems like your setup is having issues or something.
<img width="720" alt="Screen Shot 2022-03-23 at 16 01 56" src="https://user-images.githubusercontent.com/11823401/159795330-134e2e65-a9a8-42a1-86c3-b83826e66b0a.png">

Cheers.

**Comment by empty88** [comment]
Now I installed the IIS URL-Rewrite Module and *tada* i can use the provided web.config file. Maybe this is worth mentioning in installation instructions.
But unfortunately the datepicker is not translated into german. All queues and columns are labeled english too but I selected the german language in the initial setup process and I can see that the german translations for the queues and columns are included in the phar file. But in my case they are not used. I am clueless...

for any reason only the keyword translation in php works as espected. Every javascript generated content is english (e.g. "Your lock is expiring soon", unsaved changes warning and...the datepicker)

Is this the same phar file you are using, it seems to be quite old, but this is the one I downloaded recently:
de — include/i18n/de.phar
Version: 158808, für version v1.14
Erstellt: Fri, 01 May 20 17:54:37 +0000

@JediKev thanks for your effort so far!

**Comment by JediKev** [comment]
@empty88 

Glad to hear you got that sorted.

So the Queues and Columns aren't translated as they are dynamic, meaning they can change. You must add manual translations in **Admin Panel > Settings > Tickets  > Queues**. We have on our dreams list to use the default translations for dynamic content unless the content has been changed. This is only a dream item at the moment. Also, installing in another language is sorta borked currently, until we rebuild the lang packs. We had a bug that has since been addressed and we just need to rebuild them.

Yes, that is the same `de.phar` I'm using and all JS strings are translated. Since this is a JS issue I would say try a different browser or device altogether to make sure it's not a weird browser/device thing.

Cheers.

**Comment by empty88** [comment]
> So the Queues and Columns aren't translated as they are dynamic, meaning they can change. You must add manual translations in **Admin Panel > Settings > Tickets > Queues**. We have on our dreams list to use the default translations for dynamic content unless the content has been changed. This is only a dream item at the moment. Also, installing in another language is sorta borked currently, until we rebuild the lang packs. We had a bug that has since been addressed and we just need to rebuild them.

ok, I thought installing in another language should work, I did not know that.
> Yes, that is the same `de.phar` I'm using and all JS strings are translated. Since this is a JS issue I would say try a different browser or device altogether to make sure it's not a weird browser/device thing.

Tried different browsers and devices. Finally I added these to lines to /include/staff/footer.inc.php to include the JS files manually out of the extracted phar file data as a workaround:
`<script type="text/javascript" src="<?php echo ROOT_PATH; ?>include/i18n/de/js/osticket-strings.js"></script>`
`<script type="text/javascript" src="<?php echo ROOT_PATH; ?>include/i18n/de/js/jquery.ui.datepicker.js"></script>`

Now everything seems to be fine. All strings are translated.

**Comment by JediKev** [comment]
@empty88 

>ok, I thought installing in another language should work, I did not know that.

It normally would but as I mentioned above, installing in another language is kinda borked at the moment until we rebuild the language packs.

>Now everything seems to be fine. All strings are translated.

Nice, glad you got this resolved.

Cheers.
