### ISSUE TITLE
Error Object of class Ampache\Repository\Model\Song could not be converted to string

### ISSUE THREAD

**Issue by rockstar2020** [osTicket/osTicket#6116]
Posted by mistake.

**Comment by JediKev** [comment]
@rockstar2020 

I do not believe you meant to post this here. This repo is for osTicket, not "Ampache".

Cheers.

**Comment by rockstar2020** [comment]
I'm so sorry!

**Comment by JediKev** [comment]
@rockstar2020 

No problem at all! It happens from time to time. Good luck!

Cheers.
