### ISSUE TITLE
Issues clossing a ticket and changing admin password

### ISSUE THREAD

**Issue by eamanu** [osTicket/osTicket#6117]
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [x] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

In a new install of osticket with develop and with v1.15.6

![image](https://user-images.githubusercontent.com/7605307/160036929-229e3926-77ee-417b-914d-e6eed53a8d87.png)

If I want to change the status of a ticket, or for instance, change admin password A new pop up appear but
with the landing page. without option. The only solution is refresh the page, but I cannot change the status
of the ticket and neither the password. 

![image](https://user-images.githubusercontent.com/7605307/160036879-8298fe94-593b-430d-9e75-29f74201a634.png)

In js console I watch this:
![image](https://user-images.githubusercontent.com/7605307/160037127-96408553-51ea-4f23-b233-961f6753b2ae.png)

### Versions
Version 1.15.6 and develop
I'm in a dockerized Ubuntu 18.04.4 LTS (Bionic Beaver)

browser: Firefox 91.5.0esr (64-bit)

**Comment by JediKev** [comment]
@eamanu 

Since you didn’t provide full environment details I can only assume you’re using NGINX, am I correct?

Cheers.

**Comment by eamanu** [comment]
@JediKev 

Thnaks for your response. Yes. I'm running this docker https://github.com/pi0/osticket-docker 

cheers

**Comment by JediKev** [comment]
@eamanu 

That’s your issue. NGINX is not fully supported out of the box. You must review the many posts/guides online on how to get osTicket working with NGINX.

Cheers.
