### ISSUE TITLE
Error when open ticket detail

### ISSUE THREAD

**Issue by ELForcer** [osTicket/osTicket#6118]
### Prerequisites

* [ - ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ + ] Do you have any errors in the PHP error log, or javascript console?
 
```
[Fri Mar 25 09:30:40.662790 2022] [proxy_fcgi:error] [pid 5732] [client 10.18.200.112:53506] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, bool given in /var/www/html/ostickets/include/class.validator.php:187\nStack trace:\n#0 /var/www/html/ostickets/include/class.validator.php(201): Validator::is_email()\n#1 /var/www/html/ostickets/include/staff/ticket-view.inc.php(57): Validator::is_valid_email()\n#2 /var/www/html/ostickets/scp/tickets.php(561): require_once('...')\n#3 {main}\n  thrown in /var/www/html/ostickets/include/class.validator.php on line 187', referer: https://10.18.100.100:82/ostickets/scp/settings.php
[Fri Mar 25 09:30:53.636553 2022] [proxy_fcgi:error] [pid 5735] [client 10.18.200.112:53552] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, bool given in /var/www/html/ostickets/include/class.validator.php:187\nStack trace:\n#0 /var/www/html/ostickets/include/class.validator.php(201): Validator::is_email()\n#1 /var/www/html/ostickets/include/staff/ticket-view.inc.php(57): Validator::is_valid_email()\n#2 /var/www/html/ostickets/scp/tickets.php(561): require_once('...')\n#3 {main}\n  thrown in /var/www/html/ostickets/include/class.validator.php on line 187', referer: https://10.18.100.100:82/ostickets/scp/settings.php
```
* [ + ] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [ + ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

![image](https://user-images.githubusercontent.com/30798063/160063360-fcf54eab-8da3-4b09-aa75-22a262bc0be6.png)

When viewing a ticket, the content of the ticket is not displayed.
The following error appears in the PHP log (see error text above)

### Steps to Reproduce

1. Log in to the account "scp": https://SiteDomain/ostickets/scp/tickets.php?id=XXX
2. Open any created ticket

**Expected behavior:** 
View ticket details

**Actual behavior:** 
Empty "scp" page template without ticket details

### Versions

Server Information
--
osTicket Version | v1.16.1 (b42ddc7) —  Latest version
Web Server Software | Apache/2.4.38 (Debian)
MySQL Version | 8.0.28
PHP version | 8.0.17

**Comment by ELForcer** [comment]
Possibly an option issue: "Email Configuration and Configuration" - "Checking email addresses:" - "Checking the email domain"

If you turn it off, then the details of the ticket are opened.

**Comment by JediKev** [comment]
@ELForcer 

Search is your friend:
- https://github.com/osTicket/osTicket/pull/6089

Cheers.

**Comment by cryptosmiler** [comment]
@ELForcer 

Please check Validation:
https://github.com/osTicket/osTicket/pull/6089

Hope doing well.
