### ISSUE TITLE
Cannot access Admin panel -> Dashboard -> Information

### ISSUE THREAD

**Issue by theking81** [osTicket/osTicket#6130]
### Prerequisites

* [x ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [x ] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [x ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

When I navigate: Admin Panel > Dashboard > Information 

I get :
1.16-git ()
Fatal error: Uncaught Error: Call to undefined function shell_exec() in /home/support/public_html/support/include/staff/system.inc.php:14 Stack trace: #0 /home/support/public_html/support/scp/system.php(23): require() #1 {main} thrown in /home/support/public_html/support/include/staff/system.inc.php on line 14

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]
To bring the server information 

**Actual behavior:** [What actually happened]
Displays the error mentioned above.

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about your server.

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

osTicket Version: 1.16.1
PHP: 8.0
MySql: 5.7.37

**Comment by theking81** [comment]
I have installed also a fresh installation but the problem exists.
I only used my old osticket-config file. The rest of the files are new.

**Comment by JediKev** [comment]
@theking81 

It sounds like your PHP instance has the `shell_exec()` function disabled. If you are using a hosting provider you need to reach out to your provider for further assistance. If you are hosting your own server you need to check your PHP INI file and make sure the `disable_functions=` directive is not set, the `shell_exec()` function is removed from the directive, or the directive is completely commented out. If you still run into issues then you need to consult the online guides/forums on how to enable the `shell_exec()` function.

Cheers.

**Comment by theking81** [comment]
@JediKev yes after upgrading to 8.0 i had the shell_exec() disabled. 
What I found out is when installing 8.0 this in PHP-FPM is disabled by default. 
So anyone with this issue, they need to enable it from the server, note that some hosting options deny users from enabling it from php.ini (override), so keep this in mind. 

Thank you!
