### ISSUE TITLE
DB Error #1054

### ISSUE THREAD

**Issue by manzhakdotcom** [osTicket/osTicket#6143]
when I use user search I get an error. not "name" fields in db

[![FastPic.Ru](https://i117.fastpic.org/thumb/2022/0421/d5/cb1e19da3f5fe61b9b1fa4a592952ad5.jpeg)](https://fastpic.org/view/117/2022/0421/cb1e19da3f5fe61b9b1fa4a592952ad5.jpg.html)
[![FastPic.Ru](https://i117.fastpic.org/thumb/2022/0421/f7/f424e7af2fdbdc512e2931ab36f33df7.jpeg)](https://fastpic.org/view/117/2022/0421/f424e7af2fdbdc512e2931ab36f33df7.jpg.html)
[![FastPic.Ru](https://i117.fastpic.org/thumb/2022/0421/af/b8f47c5cb97898dc88b71d2be37e03af.jpeg)](https://fastpic.org/view/117/2022/0421/b8f47c5cb97898dc88b71d2be37e03af.jpg.html)

use Ubuntu 20 
db mariadb10.7.3

**Comment by JediKev** [comment]
@manzhakdotcom 

It looks like you are missing the phone field in the ost_user__cdata table. First go to the Contact Information Form (Admin Panel > Manage > Forms) and make sure you have the `phone` field. If you do then all you need to do is add a dummy field to the form, save changes, delete the dummy field, and the table should be recreated with the proper columns. Also, it could take a few cron runs for the data to fully repopulate.

Cheers.

**Comment by manzhakdotcom** [comment]
[![FastPic.Ru](https://i117.fastpic.org/thumb/2022/0421/67/72486457f2be0b669908c64f0b7f2867.jpeg)](https://fastpic.org/view/117/2022/0421/72486457f2be0b669908c64f0b7f2867.jpg.html)

**Comment by JediKev** [comment]
@manzhakdotcom 

Sorry, I'm not clicking on that to view it as it brings me to a different site. Please directly upload the images here on github.

Cheers.

**Comment by manzhakdotcom** [comment]
![image](https://user-images.githubusercontent.com/1816481/164471499-5a5a41b3-4b09-4937-8068-694daaa287fe.png)

**Comment by JediKev** [comment]
@manzhakdotcom 

Nice, you have the field. Now do what I mentioned above and you should be good.

Cheers.

**Comment by manzhakdotcom** [comment]
i ve done thank you
