### ISSUE TITLE
Attachment preview plugin: Missing show/hide button on osTicket 1.16

### ISSUE THREAD

**Issue by nandi96** [osTicket/osTicket#6147]
Hi,

The Hide Attachment / Show attachment buttons are disappeared after 1.16. update with PHP 8.0
(The Pdf viewer function still works correctly.)
Plugin: https://github.com/clonemeagain/attachment_preview
How Can I fix this problem?

**Comment by JediKev** [comment]
@nandi96 

Please reach out to the creator of the 3rd party mod for assistance. This has nothing to do with core osTicket nor the core osTicket Plugins.

Cheers.
