### ISSUE TITLE
Column conditions selection field too small

### ISSUE THREAD

**Issue by mrkylegp** [osTicket/osTicket#6158]
v1.16.2

Column conditions selection box for fields such as TicketStatus / Status are too small for easy selection of multiple entries. Should be resizable or have the height increased?

![Screenshot 2022-05-06 133831](https://user-images.githubusercontent.com/52687659/167063203-16eb7723-2bf9-49aa-affe-57c0b75eec4e.png)

**Comment by JediKev** [comment]
@mrkylegp 

This is what it's supposed to look like. Maybe this is an issue with your browser, browser extensions, etc.?
<img width="409" alt="Screen Shot 2022-05-06 at 08 40 43" src="https://user-images.githubusercontent.com/11823401/167144629-edbd2f14-702b-4b22-8f9e-03d65b2c3179.png">

Cheers.

**Comment by mrkylegp** [comment]
@JediKev Not sure. It's rendering like that in all browsers I test in, even without extensions and cleared cache. Now that you've shown me, yes, it used to look like that before I updated. Any ideas what I can check?

**Comment by JediKev** [comment]
@mrkylegp 

Sounds like maybe when you copied the new files over some didn't get copied all the way or there were conflicts or something. I'd fully backup your osTicket directory (so you can revert back if needed), clean all the files out, upload the new code, copy your config file, and retest.

Cheers.

**Comment by mrkylegp** [comment]
I literally did nothing this morning and now it's started working...really strange. Closing.
