### ISSUE TITLE
Table content in ticket not showing properly when printed

### ISSUE THREAD

**Issue by HonzaVe** [osTicket/osTicket#6159]
### Prerequisites

* [**Yes** ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [**no** ] Do you have any errors in the PHP error log, or javascript console?
* [ **yes**] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [ **yes in 2014**] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

When printing the ticket with table content, the output pdf file is distorded (only in table content part)

### Steps to Reproduce

1. Create table in base of knowlege / predefined answers
2. create ticket and include predefined answer
3. hit print button and export pdf

Actual web view:
![image](https://user-images.githubusercontent.com/105062999/167154097-d863dc0f-6ce6-4bd9-91ca-de4f72d77df6.png)

Real output:

![image](https://user-images.githubusercontent.com/105062999/167154202-3bdfa369-662b-4fea-836e-d1dae6af08c3.png)

**Expected behavior:** : correct table content view

**Actual behavior:** distorded table content

### Versions

Verze osTicket | v1.16.2 (39ab0c5)  
Software webserveru | Apache/2.4.6 (CentOS 7) PHP/8.0.18
Verze MySQL | 5.5.68
Verze PHP | 8.0.18

This behaviour is not happening on the other server in version:

Verze osTicket | v1.15.3.1 (65ca4e6)  Aktualizace— v1.15.7
Software webserveru | Apache/2.4.46 (Ubuntu 20)
Verze MySQL | 10.5.13
Verze PHP | 7.4.16

Table code:
`<div><table><thead><tr><th style="border-style:solid;border-width:1px" colspan="2">Provedená práce</th> <th style="border-style:solid;border-width:1px">Hod</th> <th style="border-style:solid;border-width:1px" colspan="2">Použitý materiál</th> <th style="border-style:solid;border-width:1px">Množství<br> (ks)</th> </tr></thead><tbody><tr><td style="border-style:solid;border-width:1px" colspan="2"><br><div>&nbsp;</div></td> <td style="border-style:solid;border-width:1px"><div><br>&nbsp;</div></td> <td style="border-style:solid;border-width:1px" colspan="2"><div><br>&nbsp;</div></td> <td style="border-style:solid;border-width:1px"><div><br>&nbsp;</div></td> </tr><tr><td style="border-style:solid;border-width:1px" colspan="2"><br><div>&nbsp;</div></td> <td style="border-style:solid;border-width:1px"><br><div>&nbsp;</div></td> <td style="border-style:solid;border-width:1px" colspan="2"><br><div>&nbsp;</div></td> <td style="border-style:solid;border-width:1px"><br><div>&nbsp;</div></td> </tr><tr><td style="border-style:solid;border-width:1px" colspan="2"><br><div>&nbsp;</div></td> <td style="border-style:solid;border-width:1px"><br><div>&nbsp;</div></td> <td style="border-style:solid;border-width:1px" colspan="2"><br><div>&nbsp;</div></td> <td style="border-style:solid;border-width:1px"><br><div>&nbsp;</div></td> </tr><tr><td style="border-style:solid;border-width:1px" colspan="2"><br><div>&nbsp;</div></td> <td style="border-style:solid;border-width:1px"><br><div>&nbsp;</div></td> <td style="border-style:solid;border-width:1px" colspan="2"><br><div>&nbsp;</div></td> <td style="border-style:solid;border-width:1px"><br><div>&nbsp;</div></td> </tr><tr><td style="border-style:solid;border-width:1px" colspan="2"><br><div>&nbsp;</div></td> <td style="border-style:solid;border-width:1px"><br><div>&nbsp;</div></td> <td style="border-style:solid;border-width:1px" colspan="2"><br><div>&nbsp;</div></td> <td style="border-style:solid;border-width:1px"><br><div>&nbsp;</div></td> </tr><tr><td style="border-style:solid;border-width:1px" colspan="2"><br><div>&nbsp;</div></td> <td style="border-style:solid;border-width:1px"><br><div>&nbsp;</div></td> <td style="border-style:solid;border-width:1px" colspan="2"><br><div>&nbsp;</div></td> <td style="border-style:solid;border-width:1px"><br><div>&nbsp;</div></td> </tr><tr><td style="border-style:solid;border-width:1px;width:45%" colspan="3" rowspan="2">Zhotovil:</td> <td style="border-style:solid;border-width:1px;width:35%">Doprava:</td> <td style="border-style:solid;border-width:1px;text-align:center;width:10%">ANO</td> <td style="border-style:solid;border-width:1px;text-align:center;width:10%">NE</td> </tr><tr><td style="border-style:solid;border-width:1px">počet kilometrů:</td> <td style="border-style:solid;border-width:1px"><div>&nbsp;</div></td> <td style="border-style:solid;border-width:1px"><div>&nbsp;</div></td> </tr><tr><td style="border-style:solid;border-width:1px">Datum zhotovení :</td> <td style="border-style:solid;border-width:1px" colspan="3">Provedenou práci převzal a s kompletností souhlasí:<br> ( podklad pro fakturaci)</td> <td style="border-style:solid;border-width:1px" colspan="2">Podpis:</td> </tr><tr><td style="border-style:solid;border-width:1px">čas odstranění poruchy</td> <td style="border-style:solid;border-width:1px" colspan="5">KONTROLA (datum + podpis):</td> </tr></tbody></table></div>`

**Comment by JediKev** [comment]
@HonzaVe 

The mPDF configs changed when we upgraded mPDF. The following pull should address the issue:
- https://github.com/osTicket/osTicket/pull/6160

Cheers.

**Comment by HonzaVe** [comment]
Worked as a charm. Thanks for quick response.

Jan
