### ISSUE TITLE
Socket Library version update suggestion to prevent same SMTP difficulties of new comers 

### ISSUE THREAD

**Issue by simongcc** [osTicket/osTicket#6161]
Since it is related to a few issues before but I am not sure which one to insert to.
I just open a new one with clear objective.

With referring to [#5439](https://github.com/osTicket/osTicket/issues/5439) and official forum question [Sending email via smtp - always SMTP: Invalid response code received from server](https://forum.osticket.com/d/100417-sending-email-via-smtp-always-smtp-invalid-response-code-received-from-server/4)

I suggest OSTicket to update the SMTP socket library.
According to the source code, it is a wrapper of Pear Mail.

The mentioned problem is due to a checking condition in PHP Version 4 of `Socket.php`
It will always convert a "hostname" to an IP.
For hosting with dedicated IP address, it should be running the same, for domain in shared hosting, it will run into problem because the server does not know which domain the IP means to point. So it results in "-1" from the server.

The suggested method in the #5439 of specifying the hostname with protocol together can be workaround because it fulfil the condition as string hostname instead of IP address.

I think updating it, in long run, could prevent future new comers from falling into the pitfall and saving time. 
I have described the problem in the mentioned forum before coming the idea to suggest for an update.

**Comment by JediKev** [comment]
@simongcc 

We are moving to laminas-mail and ditching pear library altogether with the upcoming v1.17 release. This is in response to the new Modern Auth changes most major mail providers are making in the coming months.

Cheers.
