### ISSUE TITLE
Installer on empty database incorrectly searches for existing table.

### ISSUE THREAD

**Issue by ghost** [osTicket/osTicket#6177]
### Prerequisites

* [] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [✓] Do you have any errors in the PHP error log, or javascript console?
* [✓] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [✓] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

When installing osTicket v1.16.3 using the approach mentioned on the front page (ie - download zip file, extract, put contents of upload/ in your HTML directory) and providing the installer with an empty database to use, the installer cannot complete due to an uncaught MySQLi exception.

At a cursory glance, this appears to be faulty logic in `setup/inc/class.installer.php`, starting from line 103, where the installer is verifying MySQL health. Link the exact line: https://github.com/osTicket/osTicket/blob/develop/setup/inc/class.installer.php#L105

This attempts detect the existence of a table by querying it, which seems like an odd thing to expect on a fresh database.

I was able to fix this for myself by clearing out the final `else` block, but that's not a proper solution.

### Steps to Reproduce

1. Create an empty database and a user will full privileges
2. Create an Apache site with dedicated webroot, copy files from /upload
3. Open osTicket web installer, follow instructions
4. Fill in the form and submit

**Expected behavior:**

The installer should move on to the final "Congratulations!" screen of the instaler

**Actual behavior:**

Error 500 is thrown and the following error can be found in the Apache log:
```
[Thu Jun 02 11:58:39.330065 2022] [php:error] [pid 148711] [client <scrubbed>] PHP Fatal error:  Uncaught mysqli_sql_exception: Table 'osticket.ost_config' doesn't exist in /var/www/html/osticket/include/mysqli.php:189\nStack trace:\n#0 /var/www/html/osticket/include/mysqli.php(189): mysqli->query()\n#1 /var/www/html/osticket/setup/inc/class.installer.php(106): db_query()\n#2 /var/www/html/osticket/setup/install.php(52): Installer->install()\n#3 {main}\n  thrown in /var/www/html/osticket/include/mysqli.php on line 189, referer: http://<scrubbed>/setup/install.php
```

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about your server.

Server Information
--
osTicket Version | v1.16.3 (e148727)     —  Up to date
Web Server Software | Apache/2.4.53 (Debian)
MySQL Version | 10.5.15
PHP Version | 8.1.6
Schema | osticket (localhost)
Schema Signature | c37e165651dc289240fee7d244990ac1
Space Used | 3.00 MiB
Space for Attachments | 0.03 MiB
Timezone | UTC

System information:
```
# Apache version
$ /usr/sbin/apache2 -v
Server version: Apache/2.4.53 (Debian)
Server built:   2022-03-14T16:28:35

# PHP version
$ php -v
PHP 8.1.6 (cli) (built: May 17 2022 16:48:41) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.6, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.6, Copyright (c), by Zend Technologies

# MySQL version
$ mysql --version
mysql  Ver 15.1 Distrib 10.5.15-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper
```

**Comment by JediKev** [comment]
@tdbpeytz 

Please read the requirements before installing. 1.16.x requires PHP 8.0. We are hoping to add PHP 8.1 support in the future. Once you downgrade PHP to meet the requirements and re-install you should be good.

Cheers.

**Comment by jjanderson** [comment]
I am getting the same error with php8.0

**Comment by ChrisTG742** [comment]
From my understanding, at the moment the code in line 105 is executed, the tables in the db should already exist (while being empty if a fresh install), so the query should be valid and just return no data.
So somethine else (probably not being fetched by proper error handling) must have gone wrong before.

**Comment by ghost** [comment]
> @tdbpeytz
> 
> Please read the requirements before installing. 1.16.x requires PHP 8.0. We are hoping to add PHP 8.1 support in the future. Once you downgrade PHP to meet the requirements and re-install you should be good.
> 
> Cheers.

Why do you not have any warning on the installer page? Everything looks good even on newer version of PHP. I have the same problem as @tdbpeytz
![os](https://user-images.githubusercontent.com/56940608/176763773-b32232ad-6f47-4efb-a414-73e7e980b4f4.png)

Be clear about your install requirements...

**Comment by JediKev** [comment]
@dynamiccontent 

The [`check_php()` method we use](https://github.com/osTicket/osTicket/blob/e1487278b710c54acea8479e0b51a0b85fa2ce42/include/class.setup.php#L93-L95) on the pre-requisite page is very basic and only checks if the version is equal to or greater than the PHP version set in our requirements. With this being said, we could definitely do a better job with this method to have a range of supported versions.

We try to be clear in the Requirements listed in the repo (in the `README.md` file), our documentation, and in the Requirements on the downloads page on our website.

Cheers.

**Comment by protich** [comment]
PR #6228 addresses the issue. The check is required to make sure we don't override existing osTicket install when tabe prefixes clash. Prior php version didn't cause fatal error, that's why the issue is coming up now.
