### ISSUE TITLE
osticket 1.15.2 %{recipient.ticket_link} not work

### ISSUE THREAD

**Issue by rocklee44** [osTicket/osTicket#6180]
Hi all.
I'm using osticket 1.15.2.
This is New Ticket Auto-response template:
```
Dear %{recipient.name.first},

Thank you for contacting IT Helpdesk.

Your request has been created and assigned ticket is #%{ticket.number} , Subject: %{ticket.subject}. Our representative will follow-up with you as soon as possible.

You can view this ticket's progress online here: %{recipient.ticket_link}.

If you wish to raise additional comments or information regarding this issue, please do not raise a new ticket. Simply go to above link, reopen the ticket to update

Thanks for your cooperation. We will always be glad to assist you.
```
When end-user send an email to helpdesk, it generates a ticket and send back an email to end-user:
```
Dear Jack, 


Thank you for contacting IT Helpdesk. 

Your request has been created and assigned ticket is #768755 , Subject: test 6/6 5:26 PM. Our representative will follow-up with you as soon as possible. 

You can view this ticket's progress online here: http://helpdesk.mydomain.com/view.php?auth=o1xayaaaagnimaaarbJiJ2TKyUtWfQ%3D%3D.

If you wish to raise additional comments or information regarding this issue, please do not raise a new ticket. Simply go to above link, reopen the ticket to update 

Thanks for your cooperation. We will always be glad to assist you.
```

End-user click on link and can access to website to view ticket status

This is Response/Reply Template 
```
Dear %{recipient.name},

Your support feedback:

%{response}

We hope this response has sufficiently answered your questions. If not, please do not send another email. Instead, reply to this email or login to your account for a complete archive of all your support requests and responses.

%{recipient.ticket_link}
```

When IT agent reply to a ticket , end-user receive a message like this
```
Dear Jessie,
Your support feedback: 
reply


We hope this response has sufficiently answered your questions. If not, please do not send another email. Instead, reply to this email or login to your account for a complete archive of all your support requests and responses. 

http://helpdesk.mydomain.com/view.php?id=17356 
```

The link above does not work (not include auth=xxxxx), end-user click on link and cannot view ticket status.
How can I fix it ? Please give me some advice, thank you very much.

**Comment by JediKev** [comment]
@rocklee44 

Please upgrade to v1.15.8 and retest. You also did not provide your environment details. A screenshot of Admin Panel > Dashboard > Information is best (censoring any sensitive info of course).

Cheers.

**Comment by rocklee44** [comment]
Hi JediKev, This is screenshots:
![1](https://user-images.githubusercontent.com/12525493/172288234-f1c72185-c651-46d4-a5f5-46c50c475400.PNG)
![2](https://user-images.githubusercontent.com/12525493/172288236-f7bde802-d9a9-4b31-9873-09ef5b4d08cb.PNG)

**Comment by JediKev** [comment]
@rocklee44 

Also, it will not include an Auth Token if there are Collaborators on the Ticket or if Auth Tokens are disabled (**Admin Panel > Settings > Users > Authentication Token**).

Cheers.

**Comment by rocklee44** [comment]
![3](https://user-images.githubusercontent.com/12525493/172289968-dcd519f8-f296-472f-87ba-f82ad6852279.PNG)
Yes, There are Collaborators on the Ticket, so that is how it works and nothing I can do for Collaborators can access ticket via link in reply message ?

**Comment by rocklee44** [comment]
An accepted solution is : Not Require email vertification when collaborators want to check/view ticket status 
Admin Panel > Settings > Users > Client Quick Access: uncheck Require email verification on "Check Ticket Status" page (enabled by default)
Note: Disabling email verification might allow third-parties (e.g. ticket collaborators) to impersonate the ticket owner.
Collaborators can access ticket status with ticker number id.
