### ISSUE TITLE
Random deadlock when deleting ticket message

### ISSUE THREAD

**Issue by enzopsc** [osTicket/osTicket#6182]
We're encountering problems lately. 
Whenever you delete whole form reply message, there's something that causes deadlock. 
It's not always but 50% of times it happens.

**Comment by enzopsc** [comment]
Updates:
Problem persists only in chrome browser. Using Firefox it doesn't happen. I didn't have chance to try any other browser tho.

**Comment by ntozier** [comment]
When you open a new issue there is a template that asks for a lot of information.  Did you search exisint issues of the forums?
Environment (version of PHP, version of osTicket, webserver, mysql version, web browser and version, etc), error log logs.  (mysql, php, etc).  *Note: you might need to turn on Mysql slow query logs.* As well as Exact Steps to reproduce the issue, and 
Please take the time to populate this thread with your information.

Without this information it would be really hard to help anyone.

**Comment by JediKev** [comment]
@enzopsc 

Also please perform a recursive search on here and the Forum as [this has already been addressed](https://github.com/osTicket/osTicket/pull/6166) in the latest versions. Please upgrade to one of the latest releases and the issues will be resolved.

Cheers.

**Comment by enzopsc** [comment]
Thank you for addressing me. It solves our problem.
