### ISSUE TITLE
OsTicket  v1.16.3 connect to MS SQL Server

### ISSUE THREAD

**Issue by WajahatRana789** [osTicket/osTicket#6184]
### Feature Request

is it possible to connect OsTicket Core, v1.16.3 to MS SQL Server

**Comment by JediKev** [comment]
@wijju 

Not at this time. osTicket is only compatible with MySQL and MariaDB. With v2.0 we will support more database backends.

Cheers.

**Comment by WajahatRana789** [comment]
@JediKev 
I appreciate you making the improvement and I'm so glad to hear that 👍
