### ISSUE TITLE
Unable to Manually Sort Help Topics - HTTP Error 500 occurs

### ISSUE THREAD

**Issue by mrkylegp** [osTicket/osTicket#6197]
### Description

When changing the sorting mode to Manually under Manage | Help Topics I am thrown a browser error HTTP Error 500.

![Screenshot 2022-07-11 012032](https://user-images.githubusercontent.com/52687659/178151112-736ab5ac-9561-4a63-a875-fa67b521cca1.png)

### Steps to Reproduce

1. Go to the admin panel, Manage, Help Topics.
2. Change the sorting mode drop down to "Manually"
3. Error 500 occurs.

**Expected behavior:** 
The list is able to be sorted manually.

**Actual behavior:** 
Error 500 and am unable to use manual sorting.

### Versions

v1.16.3.

Windows 10
Google Chrome Version 103.0.5060.114 (Official Build) (64-bit)

This issue was also discussed here: https://forum.osticket.com/d/101036-unable-to-manually-sort-help-topics

**Comment by JediKev** [comment]
@mrkylegp 

Here is the fix:
- https://github.com/osTicket/osTicket/pull/6200

Cheers.

**Comment by joeldeteves** [comment]
> @mrkylegp
> 
> Here is the fix:
> 
>     * [issue: Manually Sorted Topics #6200](https://github.com/osTicket/osTicket/pull/6200)
> 
> 
> Cheers.

Thanks, I just tested with a quick manual patch and I can confirm this fixed the issue for me
