### ISSUE TITLE
Default ticket queue - Missing help description

### ISSUE THREAD

**Issue by mrkylegp** [osTicket/osTicket#6198]
V1.16.3

The default ticket queue setting under Admin > Tickets > Settings is missing it's help text/description for the question mark.

![Screenshot 2022-07-11 023450](https://user-images.githubusercontent.com/52687659/178153590-b1fa58bb-541c-45ba-b730-1fb678f94f30.png)

**Comment by ntozier** [comment]
I can confirm its been this way for a while as it is also this way in 1.15.x.

**Comment by JediKev** [comment]
@ntozier @mrkylegp 

Here is the fix:
- https://github.com/osTicket/osTicket/pull/6199

Cheers.
