### ISSUE TITLE
Staff alerts not being sent out

### ISSUE THREAD

**Issue by ghost** [osTicket/osTicket#62]
I'm checking to see if staff alerts go out when they're supposed to.

Under Alerts and Notices, I've currently got every option selected for alerts to go out.  I've got all statuses set to enabled.  I am receiving the customer-side notices just fine, but the staff notices aren't going out.  I'm seeing this problem for the following categories-

New Ticket Alert
New Message Alert
New Internal Note Alert
Ticket Assignment Alert

I haven't tested SLA overdue yet, and I haven't expected a system alert email to be sent, so I can't speak to those two categories.

I  have created new tickets, assigned them to staff members, reassigned them to other staff members, posted internal notes as staff, and posted comments as the customer.  Customer side emails are working fine, but no staff-side alerts are sent out.

**Comment by mangocheeseshake** [comment]
Hi,

I'm not really a technical person but I have been playing with the osTicket and trying resolve the issue related to this thread.

I'm aware that AlertsandNotices are not working for tickets filtered by help topic and Ticket filter rules.  I have not setup any ticket filter for Department ABC i  created and and i sent a test email using may personal email (which means that no help topic will be used).  the result was the department members even the managers are not receiving any alert. I'm 100% that the alerts are notices are enabled.


Please I badly need help on this one so we could start using the osTicket system in my team.

**Comment by ntozier** [comment]
@mangocheeseshake this thread is from Oct 31, 2013.  I would invite you to read www.osticket.com/forum/discussion/77765/please-read-before-requesting-assistance
and post on the forums about your issue.  Please include information about your setup as described in that thread, how you have email configured, how you have alerts configured, how you have the department configured, also if your running anything other than the default English language pack please let us know.

I look forward to your post.
