### ISSUE TITLE
DB Error #1062 ost_thread_referral

### ISSUE THREAD

**Issue by enck19** [osTicket/osTicket#6202]
### Prerequisites

* [n] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [n] Do you have any errors in the PHP error log, or javascript console?
* [n] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [y] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

Error on system log like title DB Error #1062

### Steps to Reproduce

Create more ticket to test the system

**Expected behavior:**  no error

**Actual behavior:** mail with error

DB Error #1062

[INSERT INTO `ost_thread_referral` SET `thread_id` = 14, `object_id` = 1, `object_type` = 'D', `created` = NOW()]
Duplicate entry '1-D-14' for key 'ref'
include/mysqli.php(201): osTicket->logDBError('DB Error #1062', '[INSERT INTO `o...')<br />
include/class.orm.php(3468): db_query('INSERT INTO `os...', true, true)<br />
include/class.orm.php(658): MySqlExecutor->execute()<br />
include/class.thread.php(1961): VerySimpleModel->save()<br />
include/class.thread.php(380): ThreadReferral::create(Array)<br />
include/class.ticket.php(3039): Thread->refer(Object(Dept))<br />
include/class.thread.php(588): Ticket->systemReferral(Array)<br />
include/class.thread.php(910): Thread->postEmail(Array, Object(ThreadEntry))<br />
include/class.mailfetch.php(882): ThreadEntry->postEmail(Array)<br />
include/class.mailfetch.php(955): MailFetcher->createTicket(1)<br />
include/class.mailfetch.php(1035): MailFetcher->fetchEmails()<br />
include/class.cron.php(25): MailFetcher::run()<br />
scp/autocron.php(61): Cron::MailFetcher()<br />
{main}

### Versions
osTicket (v1.16.3)
Web Server Software | Apache/2.4.54
Debian 11.3
PHP 8.0.20
mysql  Ver 15.1 Distrib 10.5.15-MariaDB,

**Comment by ntozier** [comment]
Did you perhaps delete some tickets from the database manually?

**Comment by enck19** [comment]
> Did you perhaps delete some tickets from the database manually?

I deleted from web interface not from other tool like mysql command line

**Comment by ntozier** [comment]
> [INSERT INTO ost_thread_referral SET thread_id = 14, object_id = 1, object_type = 'D', created = NOW()]
Duplicate entry '1-D-14' for key 'ref'

Well it sounds like you had information in the table that you shouldn't.  Like things were deleted incorrectly.
You can manually edit the table to delete the duplicate key.
Or if you deleted all tickets you could just drop the contents of that table.

**Comment by enck19** [comment]
> > [INSERT INTO ost_thread_referral SET thread_id = 14, object_id = 1, object_type = 'D', created = NOW()]
> > Duplicate entry '1-D-14' for key 'ref'
> 
> Well it sounds like you had information in the table that you shouldn't. Like things were deleted incorrectly. You can manually edit the table to delete the duplicate key. Or if you deleted all tickets you could just drop the contents of that table.

Ok, i delete all record on table, thanks
