### ISSUE TITLE
v1.16.3 to v1.17-rc1 upgrader fails: CREATE TABLE `ost_plugin_instance`... Table 'ost_plugin_instance' already exists

### ISSUE THREAD

**Issue by sophon48** [osTicket/osTicket#6207]
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

When upgrading from 1.16.3 to 1.17rc1 (for OAuth2), the upgrader fails with the below error

[CREATE TABLE `ost_plugin_instance` ( `id` int(11) unsigned NOT NULL AUTO_INCREMENT, `plugin_id` int(11) unsigned NOT NULL, `flags` int(10) NOT NULL DEFAULT 0, `name` varchar(128) NOT NULL DEFAULT '', `config` text DEFAULT NULL, `notes` text DEFAULT NULL, `created` datetime NOT NULL, `updated` datetime DEFAULT NULL, PRIMARY KEY (`id`), KEY `plugin_id` (`plugin_id`) ) DEFAULT CHARSET=utf8] Table 'ost_plugin_instance' already exists

### Steps to Reproduce

1. Upload 1.17rc1 files
2. Start upgrader

### Versions

Server Information
--
osTicket Version | v1.16.3 (e148727) —  Up to date
Web Server Software | Apache/2.4.54 (Ubuntu)
MySQL Version | 10.3.34
PHP Version | 8.0.21

**Comment by JediKev** [comment]
@sophon48 

Did you already attempt to apply the patches before? Can you look your database backup from before the upgrade to confirm you don't actually have a `ost_plugin_instance` table yet?

Cheers.

**Comment by sophon48** [comment]
Hi @JediKev each time I have tried to upgrade to 1.17rc1 I have used a backup from last night, as if the upgrade fails it asks you to restore from backup in order to get the upgrade option back.

I don't already have an ost_plugin_instance table, only an ost_plugin table

I have additionally tried restoring to backup, disabling all plugins and then trying to upgrade from that.

**Comment by sophon48** [comment]
I've just done the exact same process for the eighth or so time, restoring from last nights backup and applying the update just to check the error message again.. and it has upgraded instantly with no error.

I'm even more puzzled than I was when I began looking at this earlier today.. I suppose this can be closed off, unless you want any further details.

**Comment by protich** [comment]
I'm puzzled as well - but I'm going to close the isssue until the issue resurfaces again. Thanks for the report.
