### ISSUE TITLE
Unable to Set SMTP Auth to None

### ISSUE THREAD

**Issue by RyanBlakeIT** [osTicket/osTicket#6209]
### Description

Unable to select Authentication -> None for Outgoing (SMTP)

### Steps to Reproduce

1. Log into the system and add an e-mail address (if applicable)
2. Go to the Outgoing (SMTP) and select Authentication: None - No Authentication Required
3. Make sure Status is Enabled and hit Save.

**Expected behavior:** Save successful

**Actual behavior:** Error message that states "Configure Authentication"

**Workaround:** Leave Status on Disabled and hit Save, then Enable and it will save successfully.

### Versions

<html>
<body>

Server Information
--
osTicket Version | v1.17-rc1 (9f51d46)  Upgrade— This osTicket version is no longer supported. Please consider upgrading
Web Server Software | Apache/2.4.54 (Rocky Linux) OpenSSL/1.1.1k mod_auth_gssapi/1.6.1
MySQL Version | 10.6.8
PHP Version | 8.0.21

</body>
</html>

Client: Windows 11 22H2 & Microsoft Edge 103.0.1264.62 (Official build) (64-bit)

**Comment by protich** [comment]
@RyanBlakeIT - Thanks for the report - the issue was addressed by commit fa6cc040
