### ISSUE TITLE
Unable to upgrade to 1.17-rc1

### ISSUE THREAD

**Issue by edgarnadal** [osTicket/osTicket#6210]
Hello,
After running the upgrade several times, this migration hasn't run successfully:

- v1.17: Move Plugin Config store back to central config

I get a 500 error after running it. What can I do to find the issue, system logs don't show anything.

**Comment by ntozier** [comment]
Environment details?
webserver?
version of PHP?

Have you consulted your PHP error logs?
[unknown] webserver error logs?

**Comment by edgarnadal** [comment]
Hello @ntozier ,

Env is docker, webserver is nginx, php 8.0.11, mysql 8.0.28.

Now i'm getting some errors on the system log:

DB Error #1054

`[SELECT * FROM ost_plugin_instance WHERE config IS NOT NULL] Unknown column 'config' in 'where clause'<br /> <br /> ---- Backtrace ----<br /> #0 (root)/include/mysqli.php(201): osTicket->logDBError('DB Error #1054', '[SELECT * FROM ...')<br /> #1 (root)/include/upgrader/streams/core/f0d2e14d-83a22ba2.task.php(10): db_query('SELECT * FROM o...')<br /> #2 (root)/include/class.upgrader.php(348): ConfigMigrater->run(30)<br /> #3 (root)/include/class.upgrader.php(121): StreamUpgrader->doTask()<br /> #4 (root)/include/ajax.upgrader.php(35): Upgrader->__call('doTask', Array)<br /> #5 (root)/include/class.dispatcher.php(151): UpgraderAjaxAPI->upgrade()<br /> #6 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/upgrader', NULL)<br /> #7 (root)/scp/ajax.php(326): Dispatcher->resolve('/upgrader')<br /> #8 {main}`

DB Error #1091

`[ALTER TABLE `ost_email_account` DROP COLUMN `username`, DROP COLUMN `passwd`] Can't DROP 'username'; check that column/key exists<br /> <br /> ---- Backtrace ----<br /> #0 (root)/include/class.setup.php(71): osTicket->logDBError('DB Error #1091', '[ALTER TABLE `o...', false)<br /> #1 (root)/include/class.setup.php(44): SetupWizard->load_sql('\nALTER TABLE `o...', 'ost_', false, true)<br /> #2 (root)/include/class.upgrader.php(433): SetupWizard->load_sql_file('(root)/includ...', 'ost_', false, true)<br /> #3 (root)/include/class.upgrader.php(355): StreamUpgrader->cleanup()<br /> #4 (root)/include/class.upgrader.php(121): StreamUpgrader->doTask()<br /> #5 (root)/include/ajax.upgrader.php(35): Upgrader->__call('doTask', Array)<br /> #6 (root)/include/class.dispatcher.php(151): UpgraderAjaxAPI->upgrade()<br /> #7 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/upgrader', NULL)<br /> #8 (root)/scp/ajax.php(326): Dispatcher->resolve('/upgrader')<br /> #9 {main}`

**Comment by edgarnadal** [comment]
This is the system logs:

![image](https://user-images.githubusercontent.com/1534538/180463984-5a11efa3-3bd5-40f9-b5b9-f7c8d903371e.png)

**Comment by edgarnadal** [comment]
Re run it several times and went ok. Thanks.
