### ISSUE TITLE
1.17RC API broken Cannot declare class TicketApiController, because the name is already in use

### ISSUE THREAD

**Issue by wuzhuoqing** [osTicket/osTicket#6218]
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch? Well this is about php8 and 1.17
* [X] Do you have any errors in the PHP error log, or javascript console?
* [X] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [X] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description
We are upgrading to 1.17RC to tryout the new OAuth2 for Office365. After upgrade php to 8.0 (8.1 has same issue) and upgrade. The API call is broken with error
```
Cannot declare class TicketApiController, because the name is already in use in /opt/osticket_rel2/include/api.tickets.php on line 0
PHP message: PHP Stack trace:
PHP message: PHP   1. {main}() /opt/osticket_rel2/api/http.php:0
PHP message: PHP   2. Dispatcher->resolve($url = '/tickets.json', $args = *uninitialized*) /opt/osticket_rel2/api/http.php:35
PHP message: PHP   3. UrlMatcher->dispatch($url = '/tickets.json', $prev_args = NULL) /opt/osticket_rel2/include/class.dispatcher.php:38
PHP message: PHP   4. UrlMatcher->apply_prefix() /opt/osticket_rel2/include/class.dispatcher.php:135" while reading response header from upstream
```
The issue seems to be [this line of code in class.dispatcher.php](https://github.com/osTicket/osTicket/blob/34c64f14b4ef7eee29b63e380fe75808c3e2d561/include/class.dispatcher.php#L169) where `include` instead of `include_once` is used. (Changed to `include_once` and API works). However same code works in previous versions and many other places still just use include. Maybe caused by some breaking change in php8.0

### Steps to Reproduce
Use API to create ticket

**Expected behavior:** [What you expected to happen]
API can create ticket
**Actual behavior:** [What actually happened]
API fail with 500
### Versions
v1.17-rc3 (34c64f1) On nginx 1.23, php8.0-fpm, ubuntu 20.04 LTS

**Comment by JediKev** [comment]
@wuzhuoqing 

Thank you for pointing out this issue! Below is the pull request to reflect the suggested changes:
- https://github.com/osTicket/osTicket/pull/6245

Please let us know if you see anything else!

Cheers.
