### ISSUE TITLE
email notifications for new tickets or reply are not sent 1.17RC

### ISSUE THREAD

**Issue by berkut85** [osTicket/osTicket#6219]
PHP Mail Function Invalid header value detected
![image](https://user-images.githubusercontent.com/110764689/183284775-3a9c5b82-a04b-4385-ad85-a63b84493a32.png)

**Comment by ntozier** [comment]
Hello there.  Github is generally used for reporting bugs.  This seems like your trying to troubleshoot something and have not confirmed a bug yet.  Please post on the support forums for assistance.  

Also as a side not you should read this first as you have not given us any information about your environment:
https://forum.osticket.com/d/89131-please-read-before-requesting-assistance

**Comment by protich** [comment]
This WAS indeed a bug - here is a PR #6254 that addresses the issue.
