### ISSUE TITLE
/htdocs/ vs /public_html/ ?

### ISSUE THREAD

**Issue by adim-att** [osTicket/osTicket#6220]
### Prerequisites

* [No] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [No] Do you have any errors in the PHP error log, or javascript console?
* [No] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [No] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

For the deployment of the script using commands, aren't some file systems use `public_html` as an entry to root directory, rather than htdocs ?
What if the deploy-er don't have `var/www/htdocs/`, what happens then ?

**Comment by JediKev** [comment]
@ushbyorg 

The README shows an example…you can change the path to whatever you want.

Also, GitHub is a place to report bugs, submit feature requests, or to submit pull requests. If you have a question please post on the [Forum](https://forum.osticket.com).

Cheers.
