### ISSUE TITLE
1.17RC3 OAuth2 Login Failure

### ISSUE THREAD

**Issue by greglloyd-t3** [osTicket/osTicket#6222]
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch? Bug found in 1.17RC3.
* [x] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

When logging in with the new Oauth2 Client plugin the user is redirected back to osTicket but is not logged in and the login page is shown but with a message that reads `Authentication Required` when logging in as an agent. If it is a normal user logging in they are simply redirected back to `/` after entering their credentials within the IDP.  

### Steps to Reproduce

1. Install the new OAuth2 Client plugin that is bundled with RC3 of 1.17
2. Add a new instance of the module of type `OAuth2 - Other`
3. Configure the instance with the following configuration: 
   1. Name - `OAuth2 Test`
   2. Type - `Authentication`
   3. Authentication Target - `Agents and End Users`
   4. Authentication Label - `OAuth2 Auth Test`
   5. Client ID - SCRUBBED
   6. Client Secret - SCRUBBED
   7. Callback Endpoint - `https://SCRUBBED/api/auth/oauth2`
   8. Authorization Endpoint - SCRUBBED
   9. Token Endpoint  - SCRUBBED
   10. Resource Details Endpoint  - SCRUBBED
   11. Scopes - `openid email profile`
   12. User identifier - `email`
   13. Given name - `given_name`
   14. Surname - `family_name`
   15. Email Address - `email`
17. Enable the instance of this module
18. Enable the module
19. Attempt to login to the site
20. Site redirects the user to the correct OAuth authentication page
21. After credentials are submitted the user is redirected back to osTicket but appears to be an unauthenticated user

When I login as an admin and select the user that attempted to login the audit history for that user shows that the user logged in successfully even though the user is still being asked to login after the redirect back to osTicket. If I login to the IDP it also shows a successful login of the user. 

Apache Logs: 
```
GET /login.php?do=ext&bk=oauth2.user.p36i6 HTTP/1.1" 302 601 "https://SCRUBBED/login.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
GET /api/auth/oauth2?state=ff4abb20c927c3c2f3f486bbec1d3bce&session_state=cb885893-e9cd-40d6-b6d4-ec27d75884a0&code=57a60c50-0d13-41fb-84c4-fa5caa835c09.cb885893-e9cd-40d6-b6d4-ec27d75884a0.f9bd2659-b97d-4278-858a-e6ab8293a9fa HTTP/1.1" 302 663 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
GET / HTTP/1.1" 200 2007 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
```

**Expected behavior:** The user is logged into the site after the IDP redirects the user back to osTicket. 

**Actual behavior:** The user is not authenticated even though the user Audit History says the user logged in.

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about your server.
![Screen Shot 2022-08-15 at 11 34 37 AM](https://user-images.githubusercontent.com/68752536/184666422-7758724b-6dd6-40fd-b969-96d2d39beb00.png)

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.
Debian 11 
Chrome Version 104.0.5112.79

**Comment by protich** [comment]
Which IdP are you using? Can you make sure the **User dentifier** attributes matches whats returned by IdP (perhaps it should be _emailaddress_ or _mail_ instead of _email_) ? It's also equally important to make sure Agents email matches email returned by IdP.

**Comment by greglloyd-t3** [comment]
Hi!

Keycloak is the IdP. 

I double checked the client scopes in use within Keycloak and noticed I incorrectly set Given Name and Surname. I have updated both of those values and am still experiencing the same issue.

**Comment by protich** [comment]
I don't have Keycloak setup to test with - I'll bet money that returned attributes don't match what's mapped. I'll happy to help debug further if you're willing to get on a call. Shoot an email to help [at] osticket.com  and mention this issue.

Thanks,

**Comment by blacknyrd** [comment]
I am having the same redirect back to the main home page. I have tried with 3 different IDPs and they all do the same thing. I was hoping to find a solution to this.

**Comment by JediKev** [comment]
@blacknyrd 

The community supported forum is at:
- https://forum.osticket.com

Cheers.
