### ISSUE TITLE
lets Login once only

### ISSUE THREAD

**Issue by ramrajone** [osTicket/osTicket#6223]
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch?
I cloned the "develop", but it's showing 1.16-git (?) — e148727 is available
This version works
![image](https://user-images.githubusercontent.com/34359196/185647238-05cd778f-b5aa-47fa-88ce-29d19b7758c9.png)

* [x] Do you have any errors in the PHP error log, or javascript console?
No errors, or on /scp/logs.php

* [x] Did you check the [osTicket forums](https://forum.osticket.com/)?
Yes

* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?
Yes

### Description
Fresh installation of v1.17-RC3
It lets login once, using the LDAP plugin, then just fails

[Description of the bug or feature]
When the user login first time, it registers the user, then the user signs out, tries to log in, it gives an error: Access denied

### Steps to Reproduce

1. [First Step]
Freshly installed, registered user
2. [Second Step]
Freshly installed, it lets login once, deleted user, then gives same error message: Access denied

**Expected behavior:** [What you expected to happen]
It should let the user login/out as normal

**Actual behavior:** [What actually happened]
It only allows user login once

### Versions
<html>
<body>

Server Information
--
osTicket Version | v1.17-rc3 (34c64f1)  Upgrade— This osTicket version is no longer supported. Please consider upgrading
Web Server Software | Apache/2.4.52 (Ubuntu)
MySQL Version | 8.0.30
PHP Version | 8.0.21

</body>
</html>

**Comment by ramrajone** [comment]
I cloned the "develop", but it's showing 1.16-git
and tested LDAP, which is working, so this means on v1.17-rc3 something with LDAP that gives an error: Access denied

**Comment by JediKev** [comment]
@ramrajone 

Yes, it's an issue where using autodetect adds `ldap.client.p3i22` as the `backend` for the user but that's not working for some reason. If you edit the related `ost_user_account` record and set `backend` to just `ldap.client` your user will be able to login. We are going to look into this soon.

Cheers.

**Comment by JediKev** [comment]
@ramrajone 

Okay so, this issue is now fixed in RC4. The cause was due to not adding the plugin and instance ID to the backend string (ie. `ldap.client` instead of `ldap.client.p123i456`) when getting the plugin/instance registry so the system couldn’t match the plugin and instance which results in authentication failure.

If you could possibly retest with RC4 (with a new user) and confirm everything is working correctly that'd be awesome and we could close this issue.

Cheers.

**Comment by ramrajone** [comment]
@JediKev 
I have tested RC4 and it's working now
Thank you
