### ISSUE TITLE
Missing function "logFetchError" in include/class.email.php on osTicket v1.17-rc3

### ISSUE THREAD

**Issue by CrazyLinuxNerd** [osTicket/osTicket#6225]
### Prerequisites

* [X] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [X] Do you have any errors in the PHP error log, or javascript console?
* [ ] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [X] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

In include/class.email.php, when a failed imap/pop3 fetch error/exception occurs (such as a failed login) the code is supposed to run the local function "logFetchError" at least according to the code at line 954 here:

https://github.com/osTicket/osTicket/blob/1.17.x/include/class.email.php

The problem is that a function/method named "logFetchError" simply doesn't exist in the file. And since the code is trying to run "$this->logFetchError", It can't find it. Which results in the following error in PHP error logs:

`[16-Aug-2022 23:31:12 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method MailBoxAccount::logFetchError() in /var/www/html/include/class.email.php:954
Stack trace:
#0 /var/www/html/include/class.mailfetch.php(160): MailBoxAccount->fetchEmails()
#1 /var/www/html/include/class.cron.php(25): osTicket\Mail\Fetcher::run()
#2 /var/www/html/scp/autocron.php(61): Cron::MailFetcher()
#3 {main}
  thrown in /var/www/html/include/class.email.php on line 954
`

This can be verified directly on github by simply searching for the function "logFetchError" in the file, it's simply not there. The closest function available in the file is logError() at line 651 so perhaps a typo? I don't know if that's the original intended function or not though (I don't know the code base well enough)

### Steps to Reproduce

1. Install osTicket
2. Enter incorrect login details for imap/pop3 using basic authentication
3. Try to fetch mail
4. Notice the error in logs

**Expected behavior:** An exception should occur and run the logFetchError function gracefully handling the failure

**Actual behavior:** An exception occurs and tries to run the logFetchError function, but fails because of the missing function.

### Versions

osTicket Version: v1.17-rc3 (https://github.com/osTicket/osTicket/commit/34c64f14b4ef7eee29b63e380fe75808c3e2d561)
Web Server Software: Apache/2.4.51 (Red Hat Enterprise Linux) OpenSSL/3.0.1
MySQL Version: 10.5.16
PHP Version: 8.0.13
Web Browser: Firefox 103.0.2 (64-bit) on OpenSUSE Tumbleweed

**Comment by protich** [comment]
Thanks again for the report - here is a commit [ab9a810](https://github.com/osTicket/osTicket/pull/6230/commits/ab9a8101811af9270e6ae7752c5ba1e8da8f132f) that addresses the issue.

**Comment by CrazyLinuxNerd** [comment]
Thank you! I've applied these fixes to my install :-)
