### ISSUE TITLE
iFrame SRC attribute being stripped out

### ISSUE THREAD

**Issue by sufimeister** [osTicket/osTicket#625]
I'm trying to display some content (server health stats) from a remote server via an iFrame on a custom page. When saving the page, the SRC attribute from the <iframe> tag gets stripped out.

A user on the discussion board seems to think this is a security measure enabled on the WYSIWYG editor.

Before saving changes
![before-saving](https://f.cloud.github.com/assets/6808903/2287276/275d01f0-9feb-11e3-8a91-5d761feffcda.png)

After saving changes
![after-saving](https://f.cloud.github.com/assets/6808903/2287277/275e0cf8-9feb-11e3-97d4-cfab5ca15356.png)

**Comment by steadhouse** [comment]
We started experiencing this issue on knowledge base pages. We'd really love to include embedded youtube videos (screencasts we made) along with the text instruction, but it seems that the embedded video shows up in preview, but then gets stripped out.

**Comment by steadhouse** [comment]
Also - the video is hosted on Youtube. Code for testing:
    <iframe width="560" height="315" src="https://www.youtube.com/embed/rVNif_UvUPY?list=PLM8KwAlSLV1UdvrGQm7_jkXdW20GamBQf" frameborder="0" allowfullscreen></iframe>

**Comment by greezybacon** [comment]
There's no reason the `src` attribute should be stripped. Just the `allowfullscreen`

**Comment by steadhouse** [comment]
We're seeing the full iframe code stripped (as provided by YouTube).

I did a fresh install this morning to see if our regular install was doing something funky, but the behavior appears on a fresh install of 1.9.12 as well:

Server Information
osTicket Version	v1.9.12 (19292ad) —  Up to date
Web Server Software	Apache
MySQL Version	5.1.56
PHP Version	5.6.10

Steps to reproduce:
1. Copy YouTube Embed code: ```<iframe width="560" height="315" src="https://www.youtube.com/embed/YDDEpLuPeqE" frameborder="0" allowfullscreen></iframe>```
2. Start a new Knowledge base article in osTicket
3. Add some basic intro text
4. Go to HTML editing mode
5. Paste YouTube Embed code
6. Go back to WYSIWYG mode, black box place holder for YouTube video appears
7. Save FAQ
8. Only basic intro text remains - youtube code has been stripped from the source

Thanks!

**Comment by astradslme** [comment]
I have the same problem with iframes. I also tried to insert a HTML5 video tag. The editor didnt save the content. 

Thank for help!

**Comment by tmiguens** [comment]
Would be great if same domain were allowed. I tried to embed a remote help session launcher (also on my domain) to the landing page. Looked pretty cool in the preview.

**Comment by protich** [comment]
PR #2940 addresses the issue of iframe getting stripped regardless of the src.  Enhancement to make src whitelisting configurable is [planned] (https://github.com/osTicket/osTicket-1.8/issues/1141#issuecomment-189445542)

**Comment by hdesouky** [comment]
i am using osticket 1.10 and when embedding youtube it strips out the allowfullscreen attribute

any relevant fix for this?
