### ISSUE TITLE
404 error when token returned to /api/auth/oauth using Microsoft AzureAD (local container env)

### ISSUE THREAD

**Issue by julianm-lrj** [osTicket/osTicket#6255]
### Prerequisites

* [*] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [*] Do you have any errors in the PHP error log, or javascript console?
* [*] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [*] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

Using a clean new install of v1.17-rc4 with the auth-oath plugin from ost in a local docker env, application receives 404 error when returning code from azure signin at http://localhost:8080/api/auth/oauth2 callback url.

### Steps to Reproduce

1. New image created -> php:8.0.18-apache -> installed plugins: mysqli gd intl apcu imap zip -> ost v1.17-rc4 copied to image -> plugin auth-oauth2 (from ost website) copied
2. Run container with mariadb:latest (docker-compose)
3. Complete setup
4. Enable oauth plugin
5. Configured to new test app & test secrets using Microsoft AzureAD -> correct endpoints
6. Signed out
7. signed in using ouath method (button)
8. Redirected to AZ login
9. Authorized access

**Expected behavior:** expected workflow to continue and sign in using oauth method

**Actual behavior:** workflow authenticated and code was returned to callback endpoint http://localhost:8080/api/auth/oauth but ost received 404 Error at callback url http://localhost:8080/api/auth/oauth2

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about your server.

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

![image](https://user-images.githubusercontent.com/83652147/191432244-264dcdbc-4896-4e17-9914-a5d9631173b8.png)
![image](https://user-images.githubusercontent.com/83652147/191432424-8e93d3f3-a938-4740-9d61-eda80ad1c615.png)

**Comment by JediKev** [comment]
@julianm-lrj 

You do not have URL Rewriting enabled for Apache. Please check Apache's documentation on how to enable URL Rewriting and retest.

Cheers.
