### ISSUE TITLE
Modern Authentication - Two Tenants one install of osTicket

### ISSUE THREAD

**Issue by worthy92** [osTicket/osTicket#6265]
This is a quick question as to whether the OAUTH plugin will allow us to configure one osTicket platform to fetch email from multiple tenants.

We are a school and also allow our osTicket system to be used by another school (with separate depts, access etc. configured). However, this school is on a completely separate tenant.

Will we be able to configure osTicket so that it can talk to the two tenants at the same time?

Many thanks.

**Comment by JediKev** [comment]
@worthy92 

Yes we now support multi-instance plugins which means you can setup as many OAuth2 instances as you’d like.

Cheers.

**Comment by worthy92** [comment]
Great stuff. Thank you. When will 1.17 be released?

**Comment by JediKev** [comment]
@worthy92 

This week sometime. We have some things to do beforehand but we will release this week.

Cheers.

**Comment by worthy92** [comment]
Great stuff - many thanks.
