### ISSUE TITLE
Emails sent to customer have poor SpamAssassin score, specifically with the date header (not RFC 2822)

### ISSUE THREAD

**Issue by wes-mcw** [osTicket/osTicket#6309]
### Description

OSTicket generated email back to the customer has a poor SpamAssassin score and is being rejected by gmail (for one, not sure what other email systems might also reject).

Gmail response was:

Remote Server returned '554 5.7.1 <gmail-smtp-in.l.google.com #5.7.1 SMTP; 550-5.7.1 [x.x.x.x] Our system has detected that this message is not RFC>'

Testing with another mail provider, the message was received, but looking at headers I see the SpamAssassin score is poor:
Content analysis details:   (2.3 points, 5.0 required)
  pts rule name              description
 ---- ---------------------- --------------------------------------------------
  0.0 URIBL_BLOCKED          ADMINISTRATOR NOTICE: The query to URIBL was
                             blocked.  See
                             http://wiki.apache.org/spamassassin/DnsBlocklists#dnsbl-block
                              for more information.
                             [URIs: mcw.edu]
  0.8 BAYES_50               BODY: Bayes spam probability is 40 to 60%
                             [score: 0.4972]
  1.1 INVALID_DATE           Invalid Date: header (not RFC 2822)
 -0.0 SPF_PASS               SPF: sender matches SPF record
  0.0 HTML_MESSAGE           BODY: HTML included in message
 -0.1 DKIM_VALID_AU          Message has a valid DKIM or DK signature from
                             author's domain
 -0.1 DKIM_VALID_EF          Message has a valid DKIM or DK signature from
                             envelope-from domain
 -0.1 DKIM_VALID             Message has at least one valid DKIM or DK signature
  0.1 DKIM_SIGNED            Message has a DKIM or DK signature, not necessarily
                             valid
  0.6 INVALID_MSGID          Message-Id is not valid, according to RFC 2822
  0.0 KAM_SHORT              Use of a URL Shortener for very short URL

Many of these are minor and/or not something that OSTicket can fix, but I'm just wondering if this one could be addressed:

1.1 INVALID_DATE           Invalid Date: header (not RFC 2822)

and I'm not sure on the INVALID_MSGID.... maybe that's our mail server and probably not OST

Thanks

### Steps to Reproduce

1. send email to create ticket
2. agent replies to ticket
3.look for response in customer email inbox

**Expected behavior:** [What you expected to happen]
email comes in with valid formatting that is not making it look like spam

**Actual behavior:** [What actually happened]
email comes in looking like spam

### Versions

1.17

**Comment by JediKev** [comment]
@wes-mcw 

Please do a recursive search before opening an issue. There is already an issue open for this and this has already been addressed with the below:
- https://github.com/osTicket/osTicket/pull/6296

You can follow the steps here:
- https://github.com/osTicket/osTicket/issues/6295#issuecomment-1272563459

Cheers.
