### ISSUE TITLE
Delete FAQ: Deletes without any confirmation

### ISSUE THREAD

**Issue by LeslieDesser** [osTicket/osTicket#6315]
V 1.17

I believe I reported this several years ago but the issue is still there.

One click and the FAQ in the Knowledgebase is gone for ever!

At the bottom left corner, when editing an FAQ - click the button and its all gone.

Been there and done it.

Please could there be a confirmation screen before the delete is actually done.

**Comment by JediKev** [comment]
@LeslieDesser 

Then why open a new, duplicate issue? Or do you mean you reported on forum or something and the “issue” is still present in the code? If it’s the former then just comment on the old one. This is on our Feature Request list for possible future development.

Cheers.

**Comment by LeslieDesser** [comment]
You are of course right but .. I did search but as a very infrequent user Github I did not get very far.  I was looking for a way to view my old tickets without success.
