### ISSUE TITLE
Draft Save Error

### ISSUE THREAD

**Issue by fabergf** [osTicket/osTicket#6318]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console? NO
* [ ] Did you check the [osTicket forums](https://forum.osticket.com/)? YES
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported? YES

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

Hello,
we have upgraded from 1.16 to 1.17 because we need OAuth2.
After that we have this issue:
Login as user, click on "New Ticket", Select Topic, Write title and now start writing body.
Whern we stop writing for some time, the message : Draft body not found in request Error code 422.

Thant after that every time I write something I get this error.
When this error appear and I change the topic the error stop to appear and draft will save correctly.

I try to debug and I found that the client make a POST call to the server with this URL:
http://ticket.xxxx.xxx/ajax.php/draft/ticket.client.2pmq84v0g2np

And payload is something like that
4f3c78c5c47365:<p>asdsad</p>
CSRFToken: 3e93926488867817f7fc5cecacd45c4d6fc54538

and as response we get :
{"error":"Progetto corpo non trovato nella richiesta","code":422} (Italian translation)

Server configuration is :

### Steps to Reproduce

1. Login as User
2. Open new Ticket
3. Select Topic
4. Start Write and wait 

**Expected behavior:** [What you expected to happen]
Save Draft

**Actual behavior:** [What actually happened]
Error: Draft body not found in request Error code 422.

1.17

Ubuntu 22
Php 8.0.24
Mysql 8

**Comment by nobe80** [comment]
Hi!

we have exactly the same issue with autosave.
Response is {
	"error": "Inhalt des Entwurfs wurde nicht in der Anfrage gefunden", (german translation)
	"code": 422
}

We have V1.17.2 with PHP 8.0.2 on debian apache 

Strange is when we reload the whole page by F5 and type new text it works.

Any help would be appreciate :)

**Comment by fabergf** [comment]
Hello, 
we have solved with solution proposed by developers Team:
https://forum.osticket.com/d/101760-draft-save-error/11

THe official FIX 
https://github.com/osTicket/osTicket/pull/6379

Best regards
