### ISSUE TITLE
DB Error #1064 from clear installation

### ISSUE THREAD

**Issue by ivanmankov** [osTicket/osTicket#6322]
Hello!

`[SELECT H.name, DATE_FORMAT(timestamp, '%Y-%m-%d'), COUNT(DISTINCT E.id) FROM osthd_thread_event E LEFT JOIN osthd_event H ON (E.event_id = H.id) WHERE E.timestamp BETWEEN FROM_UNIXTIME(1663275044) AND FROM_UNIXTIME(1665867044) AND NOT annulled AND E.event_id IN () GROUP BY E.event_id, DATE_FORMAT(E.timestamp, '%Y-%m-%d') ORDER BY 2, 1] You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') GROUP BY E.event_id, DATE_FORMAT(E.timestamp, '%Y-%m-%d') ORDER BY 2, 1' at line 2<br /> <br /> ---- Backtrace ----<br /> #0 (root)/include/mysqli.php(203): osTicket->logDBError()<br /> #1 (root)/include/class.report.php(103): db_query()<br /> #2 (root)/include/staff/dashboard.inc.php(182): OverviewReport->getPlotData()<br /> #3 (root)/scp/dashboard.php(50): require_once('...')<br /> #4 {main}`

![image](https://user-images.githubusercontent.com/35625651/196055962-3b6dbc64-3f93-4a4c-b625-c5f7382055bc.png)

Ideas why and how to fix?

**Comment by JediKev** [comment]
@ivanmankov 

`Event::getIds()` is returning nothing so you need to check your `ost_event` table to see if you have any events there (which I doubt). If you don’t have any events then you’ll need to add them manually:
- https://github.com/osTicket/osTicket/blob/1.17.x/include/i18n/en_US/event.yaml

Seems like the installer failed at inserting these for you for whatever reason.

Cheers.

**Comment by ivanmankov** [comment]
> @ivanmankov
> 
> `Event::getIds()` is returning nothing so you need to check your `ost_event` table to see if you have any events there (which I doubt). If you don’t have any events then you’ll need to add them manually:
> 
> * https://github.com/osTicket/osTicket/blob/1.17.x/include/i18n/en_US/event.yaml
> 
> Seems like the installer failed at inserting these for you for whatever reason.
> 
> Cheers.

Fixed. Thanks!
