### ISSUE TITLE
Choose which Tickets to merge into this one. The Ticket on top will be the Parent Ticket. Sort the order of the Tickets by clicking and dragging them.

### ISSUE THREAD

**Issue by stecca21** [osTicket/osTicket#6325]
When merging tickets the description says the top ticket would be the parent ticket, suggesting that this ticket would be at the top of the thread, but after the merge it displays on the bottom, and all child tickets follow the reverse order of the default thread view. 

This happens regardless of selecting multiple tickets from the list view and ordering them in the merge modal, or selecting the merge action on a single ticket, using ticket numbers for the tickets to merge, and ordering them in the merge modal.

 osTicket 1.17 (1d8b790) running on Ubuntu 22.04 LTS
Browser: Brave Version 1.44.108  Chromium: 106.0.5249.103 (Official Build)  (x86_64) on MacOS

**Comment by JediKev** [comment]
@stecca21 

That's not what that means. It means `The Ticket on top will be the Parent Ticket` meaning the Children Tickets will be merged into this main Parent Ticket. The Thread order will depend on the option you select:
**Combine Threads:** Threads from all Tickets will be displayed chronologically.
**Separate Threads:** Threads from Tickets will be displayed one Ticket at a time.

If you select Combine Threads then they will be mixed and ordered based on the timestamps of each individual entry and if you select Separate Threads then they will be separated and will order based on the timestamps as well.

Cheers.

**Comment by stecca21** [comment]
Ah I see. I selected combine threads. My issue then stems from tickets being created for multiple replies in reverse order, and not this function. I recently switched from another ticketing system, so I think this is just a one time issue.

Thanks for the quick response! I'm closing this out.
