### ISSUE TITLE
Emails coded on ISO-8859 get truncated

### ISSUE THREAD

**Issue by molul** [osTicket/osTicket#633]
Here's the email source code and a picture of how it looks in my osTicket installation:

MIME-Version: 1.0
Received: by 10.58.151.6 with HTTP; Thu, 27 Feb 2014 11:34:27 -0800 (PST)
Date: Thu, 27 Feb 2014 20:34:27 +0100
Delivered-To: luismorcillo@gmail.com
Message-ID: <CAPUXZb7257DPQmZA25qudD93P7+j2=Xh2ePGW02vtdP6fKXxqw@mail.gmail.com>
Subject: =?ISO-8859-1?Q?Ay=FAdame?=
From: Luis Morcillo luismorcillo@gmail.com
To: support18 support18@brainstorm.es
Content-Type: multipart/alternative; boundary=047d7bdc8c1acaccb204f368681a

--047d7bdc8c1acaccb204f368681a
Content-Type: text/plain; charset=ISO-8859-1
Content-Transfer-Encoding: quoted-printable

This is an ISO-8859 coded test email. 

The title has a spanish word with
accent, and due to that, the ticket subject will be renamed to "[No
subject]".

On the other side, the body will get truncated (not blank, just truncated)
if I post a word with tilde. Here it is: V=E1monos!

--=20
Luis Morcillo Luque

--047d7bdc8c1acaccb204f368681a
Content-Type: text/html; charset=ISO-8859-1
Content-Transfer-Encoding: quoted-printable

<div dir=3D"ltr"><div>This is an ISO-8859 coded test email. The title has a=
 spanish word with accent, and due to that, the ticket subject will be rena=
med to &quot;[No subject]&quot;.<br></div><div><br></div><div>On the other =
side, the body will get truncated (not blank, just truncated) if I post a w=
ord with tilde. Here it is: V=E1monos!</div>
<div><br></div>-- <br>Luis Morcillo Luque
</div>

--047d7bdc8c1acaccb204f368681a--

![iso-8859_error](https://f.cloud.github.com/assets/2084933/2286903/b1a39a04-9fe6-11e3-9cb8-c3bccac7114d.png)

Thanks in advance! :)

**Comment by simonkurka** [comment]
Hi,

I have the same problem and can trace the error to the exact same function. Is there any good reason why osTicket should rely on a PHP function which has a known bug since a long time?

May I start a Pull-Request for the suggestion of @molul ? I tested it and it works (latest Debian Wheezy packages)!
