### ISSUE TITLE
Canned response with auto selected ticket status

### ISSUE THREAD

**Issue by nandi96** [osTicket/osTicket#6336]
Hi,

How can I modify the class.ticket.php file in 1.17. to do this?
When I select the "Canned response 1", after set auto the ticket status to "Ticket Status Name1".

**Comment by JediKev** [comment]
@nandi96 

Please post [on our Forum](https://forum.osticket.com) instead. Github is a place to report Issues, make Feature Requests, and submit Pull Requests. Questions, how-tos, etc. need to be posted on our Forum.

Cheers.
