### ISSUE TITLE
Date not showed (completly) after ticket is created - Custom Fields

### ISSUE THREAD

**Issue by gkRichie97** [osTicket/osTicket#6340]
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

After creating a ticket with a Custom Date field, it does not show the date in the Overview of the Ticket. It just show the Timezome of the date that should be shown. For Both the customer page and the admin page.

Nevertheless, the date is saved in the database correctly and if you want to edit the date it is also shown in the correct way in the edit form (Picture below)

Customer Page:

<img width="605" alt="Bild_1" src="https://user-images.githubusercontent.com/53529023/199500983-10dec104-c6ad-4455-bc36-9f82b6d78b93.png">

Admin Page:

<img width="605" alt="Bild_2" src="https://user-images.githubusercontent.com/53529023/199499976-df8a063f-93fc-4458-b84e-00f4cfae5080.png">

Edit Form:

<img width="489" alt="Bild_3" src="https://user-images.githubusercontent.com/53529023/199503442-454622c4-e368-4340-ace1-12f12048c72b.png">

### Steps to Reproduce

1. Open Ticket with a Custom Field - which is a date
2. View or Edit the Ticket.

**Expected behavior:** The Custom field should show the Date like "dd.mm.yyyy (Timezone)"

**Actual behavior:**  Just show "(Timezone)"

### Versions

<html>
<body>

Serverinformationen
--
osTicket-Version | osTicket PLUS v1.17 (1d8b790) Patch-2 — Deutsche Version —  Aktuell
Server-Software | Apache
MySQL-Version | 10.3.23
PHP-Version | 8.0.24

</body>
</html>

**Comment by JediKev** [comment]
@gkRichie97 

This is not the standard osTicket, you are using a third-party build. You need to retest with vanilla osTicket. If you find this does not happen in vanilla osTicket then you’ll need to reach out to the makers of the third-party build.

I would also encourage you to review your system date/time formats.

Cheers.

**Comment by Tinnitus97** [comment]
Please contact us in the German forum and we will take a look at the problem.
The program code of the German version is partly based on the code of the English version but only partly.
(There are many functions that are only available in the German version. Therefore, the program code may differ greatly)

------------------------------------------------------------------------------------

Bitte melde dich dazu in deutschen Forum, dann schauen wir uns das Problem an.
Der Programmcodes der deutschen Version basiert zum Teil auf dem Code der englischen Version allerdings nur zum Teil.
(Es gibt viele Funktionen, die es nur in der deutschen Version gibt. Daher kann der Programmcode stark abweichen)
