### ISSUE TITLE
OAuth2 Authorization in osticket error.

### ISSUE THREAD

**Issue by jdl44lfhs** [osTicket/osTicket#6341]
I have all of the settings setup in osticket and from my azure ad website from microsoft.  I followed both of these links https://docs.osticket.com/en/latest/Guides/OAuth2%20Guide.html and https://docs.osticket.com/en/latest/OAuth2/Microsoft%20Authorization%20Guide.html  

The issue is when I click on Submit from the Oauth2 Authorization page, it loads the Microsoft authentication page, where I consent on behalf of my organization and then it brings up a 404 Not Found
nginx/1.18.0 (Ubuntu) . I have version 1.17 of Osticket, and everything is working, other then the error reported above.

**Comment by JediKev** [comment]
@jdl44lfhs 

NGINX is not fully supported out of the box. With NGINX you have to find (or make) a working site config. They have a good general/default [recipe on the NGINX website](https://www.nginx.com/resources/wiki/start/topics/recipes/osticket/) that should help you get started. We will be publishing an official NGINX config to our documentation in the future.

I believe if you look [on the Forum](https://forum.osticket.com) someone has posted their working NGINX config that works with OAuth2 as well.

Cheers.

**Comment by JediKev** [comment]
@jdl44lfhs 

Also, I will be closing this as this is more suited for the Forum.

Cheers.
