### ISSUE TITLE
PHP 8.1 compatibility

### ISSUE THREAD

**Issue by ogmueller** [osTicket/osTicket#6348]
PHP 8.1 has been released on 25th Nov 2021.

PHP 8.1 is not supported by osTicket 1.17.x and PHP 8.1 is standard in some of the current LTS linux distributions already (e.g. Ubuntu 22.04).

Active support for PHP 8.0 is going to end on 26th Nov 2022, which is in 3 weeks. Though security support will end a year later (26 Nov 2023), it might be a good idea to start supporting PHP 8.1 "soon".

**Comment by JediKev** [comment]
@ogmueller 

PHP 8.1 is fully supported with v1.17. No idea what you are talking about.

Cheers.

**Comment by ogmueller** [comment]
Ok, sorry for that. I read your project page and it only states PHP 8.0 as requirement not giving any clue, that PHP 8.1 is also supported, nor is it mentioned in any of the release notes.
