### ISSUE TITLE
Incorrect formatting for default MTA email address

### ISSUE THREAD

**Issue by CarlHenrik** [osTicket/osTicket#6351]
https://github.com/osTicket/osTicket/blob/bc017ecdb5aeead05c482e12b32893f515958373/include/staff/settings-emails.inc.php#L153

This appends an unwanted 'l' character at the end of the email address.
The formatting should really be `'%s &lt;%s&gt;'`

**Comment by JediKev** [comment]
@CarlHenrik 

Answered you on the Forum but will answer here as well. This has been reported before and will be addressed in the next release.

Cheers.

**Comment by CarlHenrik** [comment]
Cool. That's some impressive response time. Didn't realize you'd already answered it, sorry for duplicating.

**Comment by JediKev** [comment]
@CarlHenrik 

Here is the relevant pull (just made it so we don't forget):
- https://github.com/osTicket/osTicket/pull/6352

Cheers.
