### ISSUE TITLE
Class `SessionData` does not exist in `Auth`

### ISSUE THREAD

**Issue by rinkp** [osTicket/osTicket#6359]
In [class.auth.php:1597](https://github.com/osTicket/osTicket/blob/58bf538df9aeaf740142471c27a6f182a2f02326/include/class.auth.php#L1597) the class `SessionData` is still referenced. However in 47df2b440971457bc5c22197b5596f49a8b28317 this class was completely overhauled. Therefore this references a non-existing class and function.

**Comment by prbt2016** [comment]
Hello,

I was in the process of installation of OSticket 1.17.1 on Centos7 with PHP 8.0 , MYSQL 5.5, Apache 2.2. 

However, after entering the db details and admin details and clicking Install gives a blank page and after checking Apache logs , the following error is thrown i.e : 

```
[Fri Nov 11 01:08:00 2022] [error] [client {{IP-ADDRESS}}] 
PHP Fatal error:  Uncaught Error: Class "SessionData" not found in /{{PATH}}/{{TO}}/{{OSTICKET-DIR}}/include/class.auth.php:1597\n
Stack trace:\n#0 /{{PATH}}/{{TO}}/{{OSTICKET-DIR}}/include/class.signal.php(98): PasswordPolicy::cleanSessions(Object(Staff), NULL)\n
#1 /{{PATH}}/{{TO}}/{{OSTICKET-DIR}}/include/class.staff.php(302): Signal::send('auth.clean', Object(Staff), NULL)\n
#2 /{{PATH}}/{{TO}}/{{OSTICKET-DIR}}/setup/inc/class.installer.php(214): Staff->setPassword('{{PLAIN-TEXT-PASSWORD}}')\n
#3 /{{PATH}}/{{TO}}/{{OSTICKET-DIR}}/setup/install.php(52): Installer->install(Array)\n
#4 {main}\n  thrown in /{{PATH}}/{{TO}}/{{OSTICKET-DIR}}/include/class.auth.php on line 1597, referer: http:/{{URL}}/{{TO}}/{{OSTICKET-DIR}}/setup/install.php
```

Please fix this issue.

Regards.

**Comment by JediKev** [comment]
@prbt2016 

The fix is already referenced above. Here is the link again:
- https://github.com/osTicket/osTicket/pull/6360

Cheers.

**Comment by prbt2016** [comment]
Hello @JediKev ,

Thanks for your kind reply . When this patch is going to be launched?.
Any ETA for the same ?.

Cause many users would be facing the same issue.

Regards.

**Comment by nebulade** [comment]
We are also waiting on that fix to publish the next version of osTicket package for Cloudron :)

**Comment by JediKev** [comment]
@nebulade @prbt2016 

We are making a maintenance release today or tomorrow. Please stay tuned.

Cheers.

**Comment by prbt2016** [comment]
Hello @JediKev ,

Thanks a lot for the release 1.17.2 . The issue was fixed. :+1: 

Regards.
