### ISSUE TITLE
1.16.4 Client Portal > Tickets page crashes

### ISSUE THREAD

**Issue by stevland** [osTicket/osTicket#6364]
osTicket v1.16.4 
PHP 8.0.25 // MySQL 10.4.22 // Apache web server

Client > Tickets page crashes

![delete](https://user-images.githubusercontent.com/15148803/201260752-8e6c31a3-4aad-4f6b-a241-538d8d4bdf95.png)

`AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Error: Class "Html" not found in /redacted/include/client/tickets.inc.php:174\nStack trace:\n#0 /redacted/tickets.php(147): include()\n#1 {main}\n thrown in /redacted/include/client/tickets.inc.php on line 174', referer: https://redacted/login.php`

**Comment by JediKev** [comment]
@stevland 

Fix is here:
- https://github.com/osTicket/osTicket/pull/6363

Cheers.

**Comment by stevland** [comment]
Super fast response as per usual, thanks Kev.
