### ISSUE TITLE
Plugins don't show up in 1.8.1

### ISSUE THREAD

**Issue by Eric111** [osTicket/osTicket#637]
I have put the plugins auth-ldap.phar, auth-passthru.phar and storage-fs.phar in the folder /path/to/osticket/include/plugins. When i want to install them i get this error:

Install a new plugin
To add a plugin into the system, download and place the plugin into the include/plugins folder. Once in the plugin is in the plugins/ folder, it will be shown in the list below.

So osTicket doesn't see the plugins it seems...

**Comment by speedoo** [comment]
Had the same problem in latest version (feb 2015) but solution is to change permissions for plugins folder, it was 0751, so I changed to 0755 and plugins are now visible.

**Comment by VaderD** [comment]
I am trying to install the plugins in 1.10. I put the contents into the plugins folder but it does not see them ... 

Any clear instructions how to install them .?

**Comment by JediKev** [comment]
After putting them in the `include/plugins/` directory, you then click **Add New Plugin** under **Admin Panel > Manage > Plugins** and select the desired plugin. Cheers.

**Comment by VaderD** [comment]
OK ! Found it and yes it works now !

But when i upload file like Word/Excel and sometimes Images when i go to the ticket again i get errors that the file is corrupted... Why and how cani fix it ?

**Comment by ntozier** [comment]
It doesn't sound like this response has anything to do with the topic of this issue report.
You haven't given us any information about how you have attachments setup, or server environment, etc.
Please close this issue report as the original issue no longer exists for you.
