### ISSUE TITLE
Can't change user password

### ISSUE THREAD

**Issue by m4gn3to** [osTicket/osTicket#6372]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch? 
       No, I need v1.17 (oauth2)
* [ ] Do you have any errors in the PHP error log, or javascript console?
       Yes: POST https://serverdomain.com/soporte/scp/ajax.php/staff/7/change-password 500 (Internal Server Error)
* [ ] Did you check the [osTicket forums](https://forum.osticket.com/)?
       Yes. I didn't find anything 
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?
       Yes. I didn't find anything

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description
I'm stucked with user management. I can't change any password nor creating new ones.

[Description of the bug or feature]
When I try to reset any password (through the admin panel or the reset password link) I can't do anything. The web hangs in "Loading" and in the console I can only see the POST error: https://serverdomain.com/soporte/scp/ajax.php/staff/7/change-password 500 (Internal Server Error)

### Steps to Reproduce

1. Log in as admin
2. Go to Admin Panel
3. Go to Agents Panel
4. Select an active Agent
5. Click on the agent 
6. Click on "Set password"
7. Tried all the posibilities
8.1.- Send the agent a password reset email
8.2.- Set a new password and keep checked the "Require password change..."
8.3.- Set a new password and uncheck the "Require password change..." 

**Expected behavior:** [What you expected to happen]
The admin can change the password and the agent can login (changing the password if required)

**Actual behavior:** [What actually happened]
The admin can change the password but the agent never will log in

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about your server.
1.17.1

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.
Debian 11 running Osticket.

Tried in following browsers:
- Windows: Chrome, Firefox, Edge
- Linux: Chrome, Firefox

**Comment by DavidP-ZA** [comment]
Fixed With #6360
in [class.auth.php:1597](https://github.com/osTicket/osTicket/blob/58bf538df9aeaf740142471c27a6f182a2f02326/include/class.auth.php#L1597)
replace return `SessionData::objects()->filter($criteria)->delete();`
with `return DatabaseSessionRecord::objects()->filter($criteria)->delete();`

**Comment by JediKev** [comment]
@m4gn3to 

@DavidP-ZA is correct, we already have a pull for this.

Cheers.
