### ISSUE TITLE
Client Ticket View is Broken

### ISSUE THREAD

**Issue by tauthement** [osTicket/osTicket#6374]
### Prerequisites

* [ yes ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ yes ] Do you have any errors in the PHP error log, or javascript console?
* [ yes ] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [ yes ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

Hello,

I discovered a bug in the new version (1.17.1) in some code that was just added on Oct. 26, 2022. I believe the issue is just a typo in the code [at line 174 in include/client/tickets.inc.php](https://github.com/osTicket/osTicket/blame/1d11ee674f5e438efe5120f186afe4dd45ac8aba/include/client/tickets.inc.php#L174). Instead of referencing the Http class, the code is referencing an Html class, which doesn't exist.

This is the error I'm seeing in the PHP logs (edited my domain out):
[Mon Nov 14 13:59:30.999143 2022] [php:error] [pid 11010] [client 10.50.13.179:58363] PHP Fatal error:  Uncaught Error: Class "Html" not found in /var/www/helpdesk.domain.com/include/client/tickets.inc.php:174\nStack trace:\n#0 /var/www/helpdesk.domain.com/tickets.php(147): include()\n#1 {main}\n  thrown in /var/www/helpdesk.domain.com/include/client/tickets.inc.php on line 174, referer: https://helpdesk.domain.com/

This issue causes the client ticket page to not display any tickets to clients.  

### Steps to Reproduce

1. Login as a client.
2. Go to Tickets page.
3. The section that normally shows the tickets is blank.

**Expected behavior:** The client should see their open tickets.

**Actual behavior:** The clients are not seeing their open tickets.

### Versions

osTicket Version | 1.17-git (58bf538d) —  Up to date
Web Server Software | Apache
MySQL Version | 10.5.18
PHP Version | 8.0.25

Using RHEL 7 Linux for the server and Chrome as the browser.

**Comment by JediKev** [comment]
@tauthement 

Please do a recursive search on here before creating an issue. The fix was made last week:
- https://github.com/osTicket/osTicket/pull/6363

Cheers.
