### ISSUE TITLE
Ticket open Error 500 when user is member of organization

### ISSUE THREAD

**Issue by dbruecher** [osTicket/osTicket#6375]
Hi everyone,

I currently have an issue with the latest version v.1.17.1
When a user is member of an 'organization' and tries to submit a new ticket the web server throws an Error 500.
If you remove the user from the organization the error is gone.
I also tried creating a new organization, removed the user from the old one and added it to the newly created organization and still received the same error.

We receive the same error when an agent tries to open a ticket for these specific users. The agent also receives an error 500 on submit.
I don't see any errors in IIS, PHP or SQL. In the browser debugging I can see the request send and and the Status '500' for the page: https://<URL>/tickets.php?a=open 

Server: Windows 2019
PHP: tried with PHP '8.0.25' and PHP '8.1'
OsTicket version: v1.17.1
MariaDB: 10.4.24

Does anyone else experience the same issue with organizations?

![image](https://user-images.githubusercontent.com/95356298/201786943-f53bd270-a65b-40b4-a0f5-8e8c38f92596.png)

**Comment by JediKev** [comment]
@dbruecher 

Upgrade to v1.17.2 and retest. If you still run into the issue then look at your logs (general server logs, webserver error logs, PHP error logs, MySQL/MariaDB error logs, osTicket System Logs, Browser Console logs, etc.) for any related errors.

Cheers.

**Comment by dbruecher** [comment]
@JediKev
Thanks Jedi. I can confirm that the issue with the organization is fixed with the new version v1.17.2

**Comment by dbruecher** [comment]
Hi,

sorry, but I still have an Error 500 issue in OsTicket version v1.17.2 when users are a member of an organization.
When the user tries to open a ticket he receives an error 500 on submit.
No PHP errors and no SQL errors visible.

I am quite stuck. I removed all users from their organization as workaround.

**Comment by JediKev** [comment]
@dbruecher 

You will need to look at your logs (general server logs, webserver error logs, PHP error logs, MySQL/MariaDB error logs, osTicket System Logs, Browser Console logs, etc.) for any related errors.

Cheers.

**Comment by dbruecher** [comment]
Hi Jedi,

unfonrtunately I don't see any logs.
PHP - no errors
MariaDB - no errors
IIS webserver - FastCgiModule error 500 - Internal Server Error

A Request trace show the same. The errorcode is '0' and I don't know where exactly it failed.

Do you have any tips how to get more detailed logs?

![image](https://user-images.githubusercontent.com/95356298/201962045-4b6cbd86-7d11-4b1f-bd18-b7a329420508.png)

**Comment by dbruecher** [comment]
Hi,

The issue has been solved. 
We had to enable the logging in the bootstrap.php of Osticket to be able to see the log files.
The error message was related to the function phone() (in the format.php) which we customized in our environment. This function was not set to 'static' which resulted in a crash during ticket opening. Funny enough, the error only appeared if the user was a member of an organization. Without organization, ticket creation went fine.

It seems the phone() function is sometimes called statically.

**Comment by lukaspetr** [comment]
Hi, I am experiencing a similar error as was originally reported in this thread when creating a ticket via API:

> Unable to create new ticket :user
> Incomplete client information
> 

The error was somehow introduced in https://github.com/osTicket/osTicket/commit/d4d9c4242fa494e38eeafee7217cac267face450, it works with the codebase before this one.

**Comment by JediKev** [comment]
@lukaspetr 

Can you please provide a sample request with sample data so I can attempt to replicate your issue?

Cheers.

**Comment by protich** [comment]
@lukaspetr - Please apply #6399 and retest. Thanks.
