### ISSUE TITLE
Problem send emails

### ISSUE THREAD

**Issue by patolara** [osTicket/osTicket#6384]
### Prerequisites
I have copied this files from github

class.mail.php
class.mailer.php

Because i have received this messages from Gmail 
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

  [xxxxx@gmail.com](mailto:xxxx@gmail.com)
    host gmail-smtp-in.l.google.com [142.250.27.26]
    SMTP error from remote mail server after end of data:
    550-5.7.1 [192.254.146.198] This message is not RFC 5322 compliant, the issue
    550-5.7.1 is: duplicate headers. To reduce the amount of spam sent to Gmail,
    550-5.7.1 this message has been blocked. Please review
    550 5.7.1  RFC 5322 specifications for more information. t12-20020a056402240c00b00456964d3369si11393701eda.230 - gsmtp

then i thing that the new update fix the problema but i cant send emails with emailtest.php

* [x] Can you reproduce the problem in a fresh installation of the "develop" Branch?
i used Ubuntu server 20.04 and php 8.1.12 with apache2
* [x] Do you have any errors in the PHP error log, or javascript console?
* [x]  AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class "osTicket\\Mail\\Message" not found in /var/www/osticket/include/class.mailer.php:338\nStack trace:\n#0 /var/www/osticket/include/class.email.php(235): osTicket\\Mail\\Mailer->send()\n#1 /var/www/osticket/scp/emailtest.php(34): Email->send()\n#2 {main}\n  thrown in /var/www/osticket/include/class.mailer.php on line 338', referer: https://***/soporte/scp/emailtest.php
* [x] Did you check the [osTicket forums](https://forum.osticket.com/)? yes
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported? no

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description
i tried to send a test email to any recipient and then i get error 500
[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions
1.17
Admin panel -> Dashboard -> Information which also additionally gives you information about your server.

Also, please include the OS and what version of the OS you're running. As well as your browser and browser versión.
versión

**Comment by JediKev** [comment]
@patolara 

Upgrade to v1.17.2, install the latest build of the OAuth2 plugin, and retest.

Cheers.

**Comment by patolara** [comment]
Hi @JediKev i'm using my own email server i can send messages to Hotmail, yahoo, etc the problema is only i cant send email to Gmail, y not need OAuth2, Thank you for your help

**Comment by JediKev** [comment]
@patolara 

Did you upgrade to v1.17.2?

Cheers.

**Comment by patolara** [comment]
i do the upgrade but now the emails form appear in blank, i cant actívate the debug, the save changes button not appear

**Comment by JediKev** [comment]
@patolara 

Please post a screenshot of what you mean.

Also, this seems more suitable for [our Forum](https://forum.osticket.com). There we can debug without clouding/cluttering the Github repo and once we determine it's an actual bug on the Forum you can create an Issue report here.

However, since we're already here you can continue posting for now. Just know in the future use the Forum instead.

Cheers.

**Comment by patolara** [comment]
look the picture https://1drv.ms/u/s!AgHhUvCE6akWl1AqstdPZ2cBouYs?e=iVSpOl, some functions its not working now,

**Comment by JediKev** [comment]
@patolara 

Then you need to check your logs (general server logs, webserver error logs, PHP error logs, MySQL/MariaDB error logs, osTicket System Logs, Browser Console logs, etc.) for any related errors.

Also, make sure all the new files got copied over successfully.

Cheers.

**Comment by patolara** [comment]
Got error 'PHP message: PHP Fatal error:  Uncaught ValueError: Path cannot be empty in /var/www/osticket/include/class.translation.php:568\nStack trace:\n#0 /var/www/osticket/include/class.translation.php(352): Translation->load_tables()\n#1 /var/www/osticket/include/class.translation.php(380): gettext_reader->get_plural_forms()\n#2 /var/www/osticket/include/class.translation.php(414): gettext_reader->select_string()\n#3 /var/www/osticket/include/class.i18n.php(576): gettext_reader->ngettext()\n#4 /var/www/osticket/include/staff/syslogs.inc.php(196): _N()\n#5 /var/www/osticket/scp/logs.php(56): require('...')\n#6 {main}\n  thrown in /var/www/osticket/include/class.translation.php on line 568', referer: https://helpdesk.indoamerica.edu.ec/soporte/scp/system.php

This error i thing the error is the language package i was installed Spanish translation but now only english is available

**Comment by JediKev** [comment]
@patolara 

Sounds like you have a borked language pack or your system is set to use a language pack that you no longer have installed.

I would download and install the latest build of the Spanish language pack and retest.

Cheers.

**Comment by patolara** [comment]
The option for add a new language its not available, can i set manually or add the language package manually?

**Comment by JediKev** [comment]
@patolara 

What I mean by "install the language pack" is download the latest build from our website and then place it into the `include/i18n/` folder. Once you do that reload the site and see if that works.

Cheers.

**Comment by patolara** [comment]
perfect, now its working correctly thanking you for everthing

**Comment by JediKev** [comment]
@patolara 

Now, try sending another diagnostic email to see if the original issue is resolved too. If so I will close this issue.

Cheers.

**Comment by patolara** [comment]
now its working the messages for Gmail it was send correctly thank you,
