### ISSUE TITLE
cron.php Class "MOdule" not found

### ISSUE THREAD

**Issue by ebdavison** [osTicket/osTicket#6394]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

cron.php does not produce any results and no emails fetched when it is being run from cron.

Checking this on the CLI produces the following result which would indicate a dependency or import problem:

```
[root@valinor modules]# cd /var/www/osticket/include/cli/modules
[root@valinor modules]# /usr/bin/php cron.php
PHP Fatal error:  Uncaught Error: Class "Module" not found in /var/www/osticket/include/cli/modules/cron.php:3
Stack trace:
#0 {main}
  thrown in /var/www/osticket/include/cli/modules/cron.php on line 3
[root@valinor modules]#
```

### Steps to Reproduce

1. cd /var/www/osticket/include/cli/modules
2. /usr/bin/php cron.php

**Expected behavior:** [What you expected to happen]

cron.php executes and emails are fetched

**Actual behavior:** [What actually happened]

PHP fatal error thrown

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about your server.

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

server OS: Fedora 35
client OS: Fedora 36
client browser: firefox 107.0

Server Information
osTicket Version 	1.17-git (?)
— 8fbc7ee is available
Web Server Software 	nginx/1.22.1
MySQL Version 	10.4.7
PHP Version 	8.0.26
PHP Extensions
gdlib 	Used for image manipulation and PDF printing
imap 	Used for email fetching
xml 	XML API
xml-dom 	Used for HTML email processing
json 	Improves performance creating and processing JSON
mbstring 	Highly recommended for non western european language content
phar 	Highly recommended for plugins and language packs
intl 	Highly recommended for non western european language content
fileinfo 	Used to detect file types for uploads
zip 	Used for ticket and task exporting
APCu 	Improves overall performance
Zend Opcache 	Improves overall performance
PHP Settings
cgi.fix_pathinfo 	"1" is recommended if AJAX is not working
date.timezone 	US/Central
Database Information and Usage
Schema 	osticket (127.0.0.1)
Schema Signature 	83a22ba22b1a6a624fcb1da03882ac1b
Space Used 	3.16 MiB
Space for Attachments 	0.03 MiB
Timezone 	UTC

Installed Language Packs
English (United States)
en_US — include/i18n/en_US

**Comment by JediKev** [comment]
@ebdavison 

This is something we can look into however you should be running cron from `api/cron.php`.

Cheers.

**Comment by ebdavison** [comment]
Oh, I found that file (in a forum posting I think) and did not realize it was the wrong one.  Let me change it and see how that goes.

**Comment by ebdavison** [comment]
That fixed it!  Thanks.
