### ISSUE TITLE
Init Script seems broken - syntax error, unexpected '=' in /var/www/src/public/include/class.forms.php on line 4039

### ISSUE THREAD

**Issue by DumpName** [osTicket/osTicket#6401]
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [x] Do you have any errors in the PHP error log, or javascript console?
* [ ] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description
I treid setting up osTicket via a [docker container ](https://hub.docker.com/r/osticket/osticket).
However during the initialisation i will get the error message:
```
PHP Parse error:  syntax error, unexpected '=' in /var/www/src/public/include/class.forms.php on line 4039
Parse error: syntax error, unexpected '=' in /var/www/src/public/include/class.forms.php on line 4039
```

I do not have any experiance working with php however the line
```
        $config['size'] ??= $cfg->getMaxFileSize();
```
Does look broken to me.

### Steps to Reproduce

1. Run Docker Container via `docker run -it osticket/osticket /bin/bash` (including all needed env`s)
2. Run command `entrypoint`

**Expected behavior:** Normal and working initialisation of the container

**Actual behavior:** 

```
...
Install/Update osTicket
PHP Notice:  Constant INCLUDE_DIR already defined in /var/www/src/bootstrap.php on line 339
PHP Notice:  Constant SETUP_DIR already defined in /var/www/src/bootstrap.php on line 341
Configuring mail settings
OSTicket cron job is set to run every 5 minutes
Using external MySQL connection
Waiting for database TCP connection to become available...
Connecting to database mysql://osTicket@mySQL/osTicket
Using installation secret from INSTALL_SECRET environmental variable
Updating configuration file
Installing database. Please wait...
PHP Parse error:  syntax error, unexpected '=' in /var/www/src/public/include/class.forms.php on line 4039
Parse error: syntax error, unexpected '=' in /var/www/src/public/include/class.forms.php on line 4039
```

### Versions

osticket/osticket:latest

OS:
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  compose: Docker Compose (Docker Inc., v2.12.2)
  scan: Docker Scan (Docker Inc., v0.21.0)

Server:
 Containers: 10
  Running: 9
  Paused: 0
  Stopped: 1
 Images: 10
 Server Version: 20.10.21
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 770bd0108c32f3fb5c73ae1264f7e503fe7b2661
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.0-19-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.839GiB
 Name: docker0
 ID: *******
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: ********
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by JediKev** [comment]
@DumpName 

It appears your Docker container is not running PHP 7.4 or above as this is called Null Coalesce Equal Operator and was introduced in PHP 7.4:
- https://wiki.php.net/rfc/null_coalesce_equal_operator

Cheers.

**Comment by DumpName** [comment]
Just saw that the docker container I am using was not updated for 2 years...

**Comment by JediKev** [comment]
@DumpName 

That'll do it! Just to note, we do not have any official Docker containers at this time. The one listed under our official namespace is not us, rather, someone from the web who took our name before we could. So if you will be using a Docker container you will be using your own or a 3rd party one.

Cheers.
