### ISSUE TITLE
System log details not showing

### ISSUE THREAD

**Issue by zyatrnateks** [osTicket/osTicket#6417]
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [x] Do you have any errors in the PHP error log, or javascript console?
* [ ] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

System logs details became empty since this commit: https://github.com/osTicket/osTicket/commit/d4d9c4242fa494e38eeafee7217cac267face450

![image](https://user-images.githubusercontent.com/119404803/209106625-65af00f0-4db4-4b3b-9567-bdfd09b76484.png)

I have some php errors related:

`PHP Fatal error:  Declaration of ContentAjaxAPI::log($id) must be compatible with ApiController::log($title, $msg, $level = LOG_WARN) in /var/www/html/osTicket/include/ajax.content.php on line 22`

`PHP Fatal error:  Access level to LocalCronApiController::isCli() must be public (as in class ApiController) in /var/www/html/osTicket/include/api.cron.php on line 25`

### Steps to Reproduce

1. Install osTicket and apply commit d4d9c4242 or newer
2. Go to system logs
3. Click on a log

**Expected behavior:** 
Log details will appear

**Actual behavior:** 
Log details are empty

**Comment by JediKev** [comment]
@zyatrnateks 

This is fixed here:
- https://github.com/osTicket/osTicket/pull/6399

cheers.
