### ISSUE TITLE
Cron daemon error for denied ticket when fetching email

### ISSUE THREAD

**Issue by pmb399** [osTicket/osTicket#6418]
### Prerequisites

* [ v1.17.2 ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ N/A ] Do you have any errors in the PHP error log, or javascript console?
* [ Y ] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [ Y ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

The cron daemon for email fetching reports "Ticket denied" on every execution with an email originating from a blocked address. The email is left in the inbox.

### Steps to Reproduce

1. Setup fetching emails via cron job
2. Blacklist a specific email address
3. Receive email from blacklisted address
4. Cron Daemon throws "Ticket denied" error on every trigger as the email from the blocked address is not moved.

**Expected behavior:** 

Apply same rule as for other fetched emails (move to sub-folder in inbox), but deny ticket creation. This was the behaviour in previous versions.

**Actual behavior:**

The email is not moved. Hence, cron daemon reports "Ticket denied" on every execution after the email is received and is not manually deleted from inbox.

### Versions

osTicket | 1.17.2
Server-Software | Apache
MySQL-Version | 10.5.18
PHP-Version | 8.0.26

**Comment by JediKev** [comment]
@pmb399 

The fix is here:
- https://github.com/osTicket/osTicket/pull/6381

Cheers.

**Comment by pmb399** [comment]
Thanks for your quick reply @JediKev . I applied the patch but now I get the following email as osTicket sysadmin:

Excessive errors processing emails for ssl://mail.your-server.tld:993/IMAP (Support [<ticket@company.tld>](mailto:ticket@company.tld)).

Please manually check the Fetch Folder () [1/50 - 0/1]


New emails, other than the blacklisted, are processed as expected.

Also, this may need to go to a separate issue but the sender name (of the ticket system) is rendered with "=20" instead of an empty space in the Outlook App for Android, plus it has problems with colons ":" where everything to the left of ":" is chopped. It's looking fine in Thunderbird.

**Comment by JediKev** [comment]
@pmb399 

My apologies, I left one out, you also need this:
- https://github.com/osTicket/osTicket/pull/6409

As for the other issue you’ll need to provide more information as I’m not following.

Cheers.

**Comment by pmb399** [comment]
Ah yes, this does the trick! Thanks so much.

As for the other issue. In the emails/emails tab, I set the sender name (under email information and settings) to:

MY:AWESOME Company Here

When receiving an email from the ticket system in Thunderbird, the "FROM" field shows exactly that, i.e. "MY:AWESOME Company Here".
But in Outlook (for Android) the "FROM" display name is butchered to "AWESOME=20Company=20Here".

Probably some encoding issue, I suspect. This has been working fine in the previous releases. Do you want me to open a different issue for housekeeping purposes?

**Comment by JediKev** [comment]
@pmb399 

If you remove the `:` it should be fine afterwards.

Cheers.

**Comment by pmb399** [comment]
Yes, removing the colon solved the issue.

Thanks so much @JediKev.

Cheers,
Patrick.
