### ISSUE TITLE
PHP 8.2 Compatibility ?

### ISSUE THREAD

**Issue by go-ten** [osTicket/osTicket#6486]
Hello,

I can't find the information. Is the new version 1.17.3 compatible with PHP 8.2 ?

thks

**Comment by JediKev** [comment]
@go-ten 

You can find the information in the [README.md](https://github.com/osTicket/osTicket/blob/develop/README.md) file, on [the downloads page](https://osticket.com/download/) on our website, or in our [documentation here](https://docs.osticket.com/en/latest/Getting%20Started/Installation.html).

Cheers.

**Comment by Af0x** [comment]
Hi, the download page says
>PHP version 8.0-8.2

but the README.md and the documentation still say
>PHP version 8.0 - 8.1

Which one is correct? Is PHP8.2 supported? If so, please update the information at those places.

**Comment by JediKev** [comment]
@Af0x 

I guess you didn’t see this:
- https://github.com/osTicket/osTicket/pull/6562

…or this:
- https://github.com/osTicket/docs/pull/167

Please do a search before posting.

Cheers.

**Comment by go-ten** [comment]
Hello,

For your information, I have migrated to OSTicket 1.17.4 on Debian 12 (PHP 8.2), and everything is OK.
