### ISSUE TITLE
403 - Ajax Request

### ISSUE THREAD

**Issue by huyhoang8398** [osTicket/osTicket#6490]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

[Description of the bug or feature
403 POST ajax error

![image](https://user-images.githubusercontent.com/25379882/224741168-94922cbe-1ed5-49d6-97d7-b20af74ceb00.png)
 
![image](https://user-images.githubusercontent.com/25379882/224743196-410b2d65-6584-480a-94ab-1c0f1249dd48.png)

### Steps to Reproduce

1. Upload an image

**Expected behavior:** [What you expected to happen]
Upload image fine

**Actual behavior:** [What actually happened]
403 error ajax uploading

### Versions

osTicket (v1.15.7)
centos rhel fedora, kernel: 4.14.305-227.531.amzn2.x86_64
Browser: Chrome Version 111.0.5563.64 (Official Build) (64-bit)

**Comment by JediKev** [comment]
@huyhoang8398 

You are using an old, unsupported version of osTicket. Please upgrade to v1.16.6 or v1.17.3 and retest. If you still run into the same thing then re-open this issue with the new system information.

Cheers.
