### ISSUE TITLE
Contribution to codebase.

### ISSUE THREAD

**Issue by Malekhourani** [osTicket/osTicket#6509]
Hi, I'm trying to contribute to this project so i can add new features, but i'm literally lost and overwhelmed, because i don't know where to start from. 
Is there any glossary that explains terminologies that you are using? such as Backend, RegisteryService and others, or any point that is good to start with, and also what are the standards that you are following, and you want new contributors to follow?

**Comment by JediKev** [comment]
@Malekhourani 

We have a [Documentation site](https://docs.osticket.com/en/latest/) and a [Community Supported Forum](https://forum.osticket.com/). Other than that you are on your own with making changes/additions to the codebase. We don't have developer docs, developer guides, term glossary, or anything like that.

We hope to have some sort of developer documentation/guide with v2.0 so please stay tuned!

Cheers.
