### ISSUE TITLE
SLA Notes not updating in ticket note chain

### ISSUE THREAD

**Issue by jayavman** [osTicket/osTicket#6512]
Updating SLA notes does not reflect in ticket notes after updating SLA information
![Screenshot 2023-04-11 at 1 15 16 pm](https://user-images.githubusercontent.com/114973646/231047139-b98fdc3e-8b56-43a8-b9ec-091ebba063bb.png)
(notes in reason for update) - Does not reflect in ticket notes.
osTicket (v1.17.3)

**Comment by JediKev** [comment]
@jayavman 

To make sure we are on the same page, you’re saying if you change the SLA, put a note, and click Update you don’t see the note in the Ticket Thread? If so, in my testing it does get added however you have to refresh the page to see it.

Cheers.

**Comment by jayavman** [comment]
my bad, Had to refresh the ticket notes again and it came up :> thanks
