### ISSUE TITLE
Quick question: does oauth2 expire every 6 months?

### ISSUE THREAD

**Issue by wes-mcw** [osTicket/osTicket#6513]
We set up Microsoft Oauth2 back around October 6, 2022 (can't figure out the EXACT date) and then over this past weekend, around April 9, 2023, osticket stopped pulling tickets from the inboxes.  Went in to check the oauth2 config, and the last tab "token" had a red expires date of 4/9/23.  Went to the middle tab "IDP config" and clicked submit and re-authorized the account, and it started working again.  Our server administrator for the Exchange accounts says there's no 6 month expiration setting.  Is there anything in osticket that would cause the authorization to expire?  
We're on 1.17
Thanks!

**Comment by JediKev** [comment]
@wes-mcw 

This is an old issue that was resolved with v1.17.3 and the latest build of the OAuth2 plugin. You need to upgrade to v1.17.3, install the latest build of the OAuth2 plugin, and you will be good moving forward.

Essentially, we were not updating the Refresh Token properly so it would expire after the configured timeframe (default is 90 days).

Cheers.

**Comment by wes-mcw** [comment]
sounds good, thank you!
