### ISSUE TITLE
1.17.3. File Upload error: undefined 500

### ISSUE THREAD

**Issue by nandi96** [osTicket/osTicket#6516]
We get an error message after update 1.17.3, when try upload .csv format.

Error screenshots: https://imgur.com/a/ydJiqS4

We tried this modification, but no changes.
https://github.com/osTicket/osTicket/pull/6495/files

osTicket Version | v1.17.3 (ca95150) —  Up to date
Web Server Software | Apache
MySQL Version | 10.4.22
PHP Version | 8.0.28

@JediKev ?

**Comment by JediKev** [comment]
@nandi96 

Then the MIME type your browser is sending for the file does not match what PHP sees as the actual MIME type. For now you can disable the check but you'll likely open yourself up to security vulnerabilities.

If you want to look more into this you can look at the mime_type method for FileObject class:
- https://github.com/osTicket/osTicket/blob/develop/include/class.file.php#L1117

Cheers.

**Comment by nandi96** [comment]
@JediKev I know, that I can simply comment out this line from the source code, but not this the intent, so we are waiting.
