### ISSUE TITLE
[Feature Request] Time tracking

### ISSUE THREAD

**Issue by justfor-it** [osTicket/osTicket#6523]
Is it a possibility in the future that time can be written on a ticket. 
So that you can see per customer from a report how much time was written to bill this.

Thanks in advance

**Comment by JediKev** [comment]
@justfor-it 

Currently you can create a custom field and manually add time for each Ticket.

This feature has already been requested with [this pull](https://github.com/osTicket/osTicket/pull/3231).

Cheers.
