### ISSUE TITLE
Help Topic Forms not loading for Users on open.php

### ISSUE THREAD

**Issue by RussellLeVasseur** [osTicket/osTicket#6528]
### Prerequisites

* [X] Can you reproduce the problem in a fresh installation of the "develop" branch?
I did not try develop, but i did on a fresh install of 1.17.3

* [X] Do you have any errors in the PHP error log, or javascript console?
yes. 
![image](https://user-images.githubusercontent.com/58618324/235043496-cc8f9fa7-5d42-449e-8cf7-6d0bad332ba6.png)

* [X] Did you check the [osTicket forums](https://forum.osticket.com/)?
Yes, I have checked everything. All of my form items are enabled. The form works in the agent side just fine. 

* [X] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?
Yes, nothing was found. 

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

When opening a ticket as a user. The form fiels do not show when the help topic is selected. 

### Steps to Reproduce

1. Go to open ticket as logged in user
2. Select Help Topic (even the default ones do not load)
3. Fields to not load. 

**Expected behavior:** The fields to load. 

**Actual behavior:** The fields do not load
![image](https://user-images.githubusercontent.com/58618324/235044221-47a2d9d1-7ecb-4b93-81dc-d19ee7126bf4.png)

They do load when you hit Submit ticket and they are required fields. 
![image](https://user-images.githubusercontent.com/58618324/235044970-77ec5be7-49cc-4517-aedf-84e33da5edd1.png)

### Versions
![image](https://user-images.githubusercontent.com/58618324/235044019-7cfd4c88-d559-44e8-b755-298b750f0e0a.png)

I am using a theme. I have tried a vanilla installation and still get the same behavior.

**Comment by JediKev** [comment]
@RussellLeVasseur 

This is better suited for our [community supported Forum](https://forum.osticket.com). GitHub is a place for reporting bugs, requesting new features, or making a pull request.

Cheers.

**Comment by RussellLeVasseur** [comment]
> @RussellLeVasseur
> 
> This is better suited for our [community supported Forum](https://forum.osticket.com). GitHub is a place for reporting bugs, requesting new features, or making a pull request.
> 
> Cheers.

This is a bug. The forms are not loading.

**Comment by RussellLeVasseur** [comment]
> @RussellLeVasseur
> 
> This is better suited for our [community supported Forum](https://forum.osticket.com). GitHub is a place for reporting bugs, requesting new features, or making a pull request.
> 
> Cheers.

Did you even read the entire thing?

**Comment by JediKev** [comment]
@RussellLeVasseur 

1. Yes, read the whole thing.
2. You are using a custom theme. You need to test with vanilla osTicket. This GitHub is for vanilla osTicket, not modded installs.
3. This is almost guaranteed not a bug, rather an issue with the theme, setup, etc. You really need to check your logs for any errors. The browser console logs show JavaScript/jQuery not loading so there is a deeper issue at play.

Cheers.

**Comment by RussellLeVasseur** [comment]
> @RussellLeVasseur
> 
> 1. Yes, read the whole thing.
> 2. You are using a custom theme. You need to test with vanilla osTicket. This GitHub is for vanilla osTicket, not modded installs.
> 3. This is almost guaranteed not a bug, rather an issue with the theme, setup, etc. You really need to check your logs for any errors. The browser console logs show JavaScript not loading so there is a deeper issue at play.
> 
> Cheers.

If you read it, you would have seen i mentioned using vanilla install and the same behavior was observed.

**Comment by JediKev** [comment]
@RussellLeVasseur 

Then please continue on to point 3.

Cheers.

**Comment by RussellLeVasseur** [comment]
> @RussellLeVasseur
> 
> Then please continue on to point 3.
> 
> Cheers.

It appears this may be an issue with http requests, despite everything being configured for https?
![image](https://user-images.githubusercontent.com/58618324/235050553-6574fcfe-3f69-4ce8-a637-42ed57683c87.png)
