### ISSUE TITLE
 2FA :: Authenticator - problem

### ISSUE THREAD

**Issue by Raito00** [osTicket/osTicket#6529]
Hello!
Install plugin 2FA :: Authenticator but in User profile Default 2FA showing only Email authentication option. And 2FA (google) missing.
Nothing in system error logs ...

# My system
osTicket Core, v1.17.3
PHP 8.1
Apache2

**Comment by TechCare-Aus** [comment]
Have you read the Wiki? Read very carefully.

https://docs.osticket.com/en/latest/Plugins/Two%20Factor%20Authentication.html

**Comment by Raito00** [comment]
> Have you read the Wiki? Read very carefully.
> 
> https://docs.osticket.com/en/latest/Plugins/Two%20Factor%20Authentication.html

Yes of corse i read all wiki before ask here!

![image](https://user-images.githubusercontent.com/25778187/235834674-4f0f6597-c76d-430b-a637-103a17ebf611.png)

![image](https://user-images.githubusercontent.com/25778187/235834826-f03d56f7-20e4-4819-8f25-2c2af53e6138.png)

**Comment by TechCare-Aus** [comment]
I just configured a brand new test site and it works fine. You just need to configure per user I believe (It does need to be able to send an email however)

2nd pic you sent. Click Configure Options.

![image](https://user-images.githubusercontent.com/2740134/235854988-ab63446a-4491-464d-95e5-c5c956349a00.png)

Then fill in the details in the window that displays:

![image](https://user-images.githubusercontent.com/2740134/235855537-c32bbe94-75a8-41a6-96e4-3471338ee249.png)

Click next and it should send the code to your email (provided that is set up properly and working).

Enter that and now you should be able to select the option in Default 2FA (or maybe it does this automatically).

**Comment by Raito00** [comment]
> I just configured a brand new test site and it works fine. You just need to configure per user I believe (It does need to be able to send an email however)
> 
> 2nd pic you sent. Click Configure Options.
> 
> ![image](https://user-images.githubusercontent.com/2740134/235854988-ab63446a-4491-464d-95e5-c5c956349a00.png)
> 
> Then fill in the details in the window that displays:
> 
> ![image](https://user-images.githubusercontent.com/2740134/235855537-c32bbe94-75a8-41a6-96e4-3471338ee249.png)
> 
> Click next and it should send the code to your email (provided that is set up properly and working).
> 
> Enter that and now you should be able to select the option in Default 2FA (or maybe it does this automatically).

You can see it missing!
Email it is other authenticator option should be also second 2FA (google) like in wiki page!!!

![image](https://user-images.githubusercontent.com/25778187/235865106-d5f53495-d8e3-456b-9605-7cb2caccd885.png)

**Comment by TechCare-Aus** [comment]
I don't know why you are using exclamation marks (!!) are you ranting??

Anyway I re-read your OP and my apologies you are talking about the **authenticator app** option.

For that to work you need to go to the plugin and make sure it is set to enabled:

![image](https://user-images.githubusercontent.com/2740134/235866261-0bfb8087-7093-4b5a-b554-25c4f7386496.png)

Then:

![image](https://user-images.githubusercontent.com/2740134/235866362-c592fe8f-7001-4f7f-83c6-72c1ce21f207.png)

Then:

![image](https://user-images.githubusercontent.com/2740134/235867048-08299757-029e-4375-b361-6b84659f1937.png)


Then:

![image](https://user-images.githubusercontent.com/2740134/235866856-f25521bf-15a7-4c7f-8bb1-c9d514605073.png)

Then go to the user Profile:

![image](https://user-images.githubusercontent.com/2740134/235867320-5d55f8ee-67ea-4f0f-8aa0-32d571dbda3e.png)

And follow the prompts there. I just tried and it worked here too.

**Comment by Raito00** [comment]
> I don't know why you are using exclamation marks (!!) are you ranting??
> 
> Anyway I re-read your OP and my apologies you are talking about the **authenticator app** option.
> 
> For that to work you need to go to the plugin and make sure it is set to enabled:
> 
> ![image](https://user-images.githubusercontent.com/2740134/235866261-0bfb8087-7093-4b5a-b554-25c4f7386496.png)
> 
> Then:
> 
> ![image](https://user-images.githubusercontent.com/2740134/235866362-c592fe8f-7001-4f7f-83c6-72c1ce21f207.png)
> 
> Then:
> 
> ![image](https://user-images.githubusercontent.com/2740134/235867048-08299757-029e-4375-b361-6b84659f1937.png)
> 
> Then:
> 
> ![image](https://user-images.githubusercontent.com/2740134/235866856-f25521bf-15a7-4c7f-8bb1-c9d514605073.png)
> 
> Then go to the user Profile:
> 
> ![image](https://user-images.githubusercontent.com/2740134/235867320-5d55f8ee-67ea-4f0f-8aa0-32d571dbda3e.png)
> 
> And follow the prompts there. I just tried and it worked here too.

Thank YOU!
