### ISSUE TITLE
active ticket counter for users

### ISSUE THREAD

**Issue by two-bellies** [osTicket/osTicket#6533]
### Prerequisites

* [yes ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ no] Do you have any errors in the PHP error log, or javascript console?
* [ yes] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [ yesd] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description
im trying to achieve what this person asked but still cant get it to work
https://forum.osticket.com/d/92406-open-page-ticket-counter

### Steps to Reproduce
I have tried editing tickets.inc.php, tickets.php index.php to no avail I also tried getting chatgpt to help me out but got no where

**Expected behavior:** [What you expected to happen]
I would like the counter to just show open tickets 
**Actual behavior:** [What actually happened]
its showing all tickets including closed 
### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about your server.
v1.17.3
installed with xampp 
php web server 8.2
php my admin shows 5.2
Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.
win 11

**Comment by JediKev** [comment]
@two-bellies 

This post is better suited for our [Community Supported Forum](https://forum.osticket.com). GitHub is a place for reporting bugs, requesting new features, or making a pull request. If you need assistance with mods please use the Forum.

Cheers.
