### ISSUE TITLE
Dropdowns Hidden behind Other Objects

### ISSUE THREAD

**Issue by RussellLeVasseur** [osTicket/osTicket#6534]
When on the agent side, the dropdowns on notes are hidden behind other objects.

scp/tickets.php
![image](https://github.com/osTicket/osTicket/assets/58618324/e0c97d7f-5c73-411f-a047-bf9911408372)

Installation Information:
![image](https://github.com/osTicket/osTicket/assets/58618324/2a3aa10d-6a14-4830-81f9-e8a168a237d3)

**Comment by JediKev** [comment]
@RussellLeVasseur 

Did you try this?
- https://github.com/osTicket/osTicket/pull/6493

Cheers.

**Comment by RussellLeVasseur** [comment]
That fixed it. Thanks!!Sent from my iPhoneOn May 10, 2023, at 1:17 PM, JediKev ***@***.***> wrote:﻿
@RussellLeVasseur
Did you try this?

#6493

Cheers.
