### ISSUE TITLE
putenv in Translation::configureForUser causes blank install screen when disabled by php.ini

### ISSUE THREAD

**Issue by kryslt** [osTicket/osTicket#6564]
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

When trying to install osTicket on the webhosting server where putenv is disabled in php.ini due to security reasons (and cannot be enabled there, webhosting support says there is no way), the install screen is blank and no error is emitted.

### Steps to Reproduce

1. Disable putenv in php.ini (if not already disabled) of your server.
2. Copy installation to your server.
3. Run install script (setup/install.php).

**Expected behavior:** A way to disable putenv in Translation::configureForUser (include/class.translation.php), or any other PHP functions that might be disabled by the webhosting server because of security or similar reasons.

**Actual behavior:** Blank screen instead of install screen. had to comment out the line `putenv('LC_ALL=' . $info['code']);` to run install script.

### Versions

osTicket 1.18, Php 8.0.
PHP info says putenv is disabled (among many other functions).

**Comment by JediKev** [comment]
@kryslt 

How dare they! (just kidding) Thanks for the report. I will test this and make a patch so we can account for such cases.

Cheers.

**Comment by JediKev** [comment]
@kryslt 

As promised, here is the patch:
- https://github.com/osTicket/osTicket/pull/6566

Thanks again! Cheers.
