### ISSUE TITLE
lang GET parameter is not sanity checked before usage

### ISSUE THREAD

**Issue by fredricj** [osTicket/osTicket#6573]
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [x] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description
Making a request with the lang GET parameter set as an array trigger a Internal server error and only shows a blank page.
Logs the following stack trace:
NOTICE: PHP message: PHP Fatal error:  Uncaught TypeError: strtolower(): Argument #1 ($string) must be of type string, array given in /usr/local/osticket/www/include/class.i18n.php:254
Stack trace:
#0 /usr/local/osticket/www/include/class.i18n.php(254): strtolower()
#1 /usr/local/osticket/www/include/class.i18n.php(512): Internationalization::isLanguageInstalled()
#2 /usr/local/osticket/www/client.inc.php(55): Internationalization::setCurrentLanguage()
#3 /usr/local/osticket/www/index.php(16): require('/usr/local/osti...')
#4 {main}
  thrown in /usr/local/osticket/www/include/class.i18n.php on line 254

### Steps to Reproduce

Request the url (taken from our logs):  /index.php?setLang=gcards_dir_transversal.nasl&lang[gcards_dir_transversal.nasl][file]=..

**Expected behavior:** Gracefully handle the invalid parameter

**Actual behavior:** Creates an error in the log

### Versions
osTicket Version | v1.17.2
PHP 8.0.27

**Comment by JediKev** [comment]
@fredricj 

Thank you for the Issue report. With your information I was able to replicate the issue. Below is the official pull request that addresses this issue:
- https://github.com/osTicket/osTicket/pull/6704

**Please Note:** The pull request is subject to change as it goes through review, feedback, etc. Rest assured, the final version will be merged and included with the next set of releases so stay tuned!

Cheers.
