### ISSUE TITLE
Can I add a "Tickets" tab that displays the count of open tickets within specific queue count buckets?

### ISSUE THREAD

**Issue by Subrahmanyam-avance** [osTicket/osTicket#6584]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [ ] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

Admin panel -> Dashboard -> Information which also additionally gives you information about your server.

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.

**Comment by JediKev** [comment]
@Subrahmanyam-avance 

Thank you for the post, however, this is not the place to ask such questions. Github is a place to report actual Issues (bugs), to make Feature Requests, or to submit Pull Requests. If you would like to ask general questions, you can contact us through [our website](https://osticket.com/contact-us/) or use the [community supported Forum](https://forum.osticket.com/).

Cheers.
