### ISSUE TITLE
Repopulate user__cdata when creating a field form user ( Null or zero)

### ISSUE THREAD

**Issue by ASilvaBR** [osTicket/osTicket#6588]
### Prerequisites

* [  NO ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ NO  ] Do you have any errors in the PHP error log, or javascript console?
* [ YES  ] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [ YES ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

I have a problem when creating a field for the user form. I know that when creating a field, the user__cdata table is recreated and repopulated. However, when repopulating the user__cdata table the field values are coming as NULL or 0.

I made a php script to repopulate this data based on the form_entry_values table, which worked. But, when creating a new field, again the user__cdata table is repopulated with values in NULL or zero.

I searched the forum for a solution but I couldn't find it.

### Steps to Reproduce

1: Table user__cdata with data:

![print2](https://github.com/osTicket/osTicket/assets/48871027/c4c2c356-c26f-454d-82e0-8b2ade390023)

2: When I create a field in the user form, the data looks like this:
![print3](https://github.com/osTicket/osTicket/assets/48871027/f0413eb2-6f33-46c2-96ff-9c00614482dd)

### Versions

![print1](https://github.com/osTicket/osTicket/assets/48871027/d6450281-1b1e-417c-b86c-621f5e9ddb2d)

**Comment by JediKev** [comment]
@ASilvaBR 

You are running an old, unsupported version of osTicket. You need to upgrade to v1.18 (or v1.17.4) and retest. Here is a link to our Upgrade Guide:
- https://docs.osticket.com/en/latest/Getting%20Started/Upgrade%20and%20Migration.html

If you upgrade and continue to experience the same problem please reopen this issue.

Cheers.

**Comment by ASilvaBR** [comment]
Thanks @JediKev  for the answer. However upgrading is not an option for me at the moment as there are some features that have been customized. Do you have any suggestions where I should look or why this happens?

**Comment by JediKev** [comment]
@ASilvaBR 

We cannot provide support for unsupported versions; hence the "unsupported" part. You can look through the [Release Notes](https://github.com/osTicket/osTicket/releases) and apply any patches you see fit but since you are running such an old version we cannot help.

**Note:**
It’s very important to stay on top of updates so you have the latest bug fixes, security patches, and latest features. I will say this appears to be an old issue that has since been resolved.

Cheers.
