### ISSUE TITLE
Reset button doesn't work on page management

### ISSUE THREAD

**Issue by greezybacon** [osTicket/osTicket#66]

**Comment by ntozier** [comment]
After receiving a thread on the forums saying that they had reset button problems I've just test this on 1.9.7 and 1.10 and this appears to still be a thing.

To replicate:
go to the agent panel.
Click on any open ticket.
go to the bottom.
Type anything in the Post Reply -> Response Text Box.
Click Reset.

Nothing happens.

source: http://osticket.com/forum/discussion/89426/new-v1-10-install-multiple-bugs-issues-found-within-agent-panel

**Comment by balojs** [comment]
@balojs
