### ISSUE TITLE
No notification on task update

### ISSUE THREAD

**Issue by jpccaldas** [osTicket/osTicket#6607]
### Prerequisites

* [Yes] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [No] Do you have any errors in the PHP error log, or javascript console?
* [Yes] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [Yes] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

![image](https://github.com/osTicket/osTicket/assets/77206541/f7402e83-e13d-4e1a-ae24-ddf1fdff23cf)

Watching the image above, notifications for new task activities are turned on, but the assigned ticket agent does not receive the task updates on his email.
I see that a fix has been deployed already ([36fad11](https://github.com/osTicket/osTicket/commit/36fad111e6eb0b9bbccf31b369ab420267c639f7)), but it doesn't work on my end. Fresh develop build install.

### Steps to Reproduce

1. Fresh install (develop branch)
2. Configure SMTP
3. Enabled tasks notification (tried all turned on)
4. Assign the first ticket created by the setup
5. Create a task (notification works)
6. Update the task with a comment (no notification)

**Expected behavior:** I expect that a mail should arrive to the assignee agent.

**Actual behavior:** No notification to anyone.

### Versions

![image](https://github.com/osTicket/osTicket/assets/77206541/b37dec02-54ee-4ce6-8fda-eb66566a1b23)

Windows 11 Pro
Microsoft Edge (117.0.2045.43)

**Comment by JediKev** [comment]
@jpccaldas 

Are you the Assignee and the one posting the comment or is it a completely different Agent that’s Assigned?

Cheers.

**Comment by jpccaldas** [comment]
@JediKev

Yes, I'm the assignee, the task creator and replyer.

**Comment by JediKev** [comment]
@jpccaldas 

Then that makes this easy lol You will not receive an alert if you are the poster and Assignee. There is no need to alert yourself for a comment you posted yourself. If the Assignee was a different Agent they would receive the alert when you posted.

**Reference:**
- https://github.com/osTicket/osTicket/blob/develop/include/class.task.php#L1242-L1243

Cheers.

**Comment by jpccaldas** [comment]
@JediKev

Ok, I tested now with another agent.
I assigned the task to agent B, he answered the task and I still didn't receive the task update notification.

PS: The task is inside the ticket. Ticked assigned to me, task assigned to agent B.

Cheers.

**Comment by JediKev** [comment]
@jpccaldas 

Again, the system will not alert the poster if they are the Assignee. He must be assigned and you comment or you must be assigned and he comments.

Cheers.

**Comment by jpccaldas** [comment]
@JediKev

That's what I did. So:

Ticket 1 assigned to agent A
Task from ticket 1 assigned to agent B
Agent B updates the task
Agent A does not receive the mail notification about task update to, for example, close the ticket

Isn't supposed to agent A receive the updates to know whats happening with the ticket overall?

Thanks in advance!

**Comment by JediKev** [comment]
@jpccaldas 

No, Tasks and Tickets are completely separate. If you update a Task only the people on the Task will get an alert (ie. Last Respondent on the Task, Agent/Team Assigned to the Task, Department Manager of the Task's Department). If you update a Ticket only the people on the Ticket will get an alert (ie. Last Respondent on the Ticket, Agent/Team Assigned to the Ticket, Department Manager of the Ticket's Department).

Please review our Alerts Guide here:
- https://docs.osticket.com/en/latest/Guides/Alerts%20Guide.html

Cheers.
