### ISSUE TITLE
[Feature Suggestion] Extended REST API

### ISSUE THREAD

**Issue by markuzzi** [osTicket/osTicket#6619]
Hi maintainers, 

are you interested in merging the extended REST API into the core?

https://github.com/markuzzi/ExtendedApi

I could prepare a corresponding PR.

**Comment by JediKev** [comment]
@markuzzi 

Not in the current codebase, no. The current (legacy) codebase will only be receiving necessary dependency updates and security/maintenance releases moving forward. With this being said, we are working on a full codebase rewrite labeled v2.0 that will have a fully RESTful API so please stay tuned!

Cheers.
