### ISSUE TITLE
Not able to upgrade

### ISSUE THREAD

**Issue by michbsd** [osTicket/osTicket#6621]
I am not able to upgrade from 1.8-git to 1.18

php 8.1.24

I have added my existing database into a new database, extracted source files into a new docroot and added a new include/ost-config.php  (pointing to my new database)

When I go to /scp I see the following:
![Screenshot 2023-10-23 at 18 24 38](https://github.com/osTicket/osTicket/assets/8202334/90c848ff-812b-47d8-8cc2-7f8c4e840e9b)

What gives?

**Comment by JediKev** [comment]
@michbsd 

You are apparently on a hash that does not support upgrades. Maybe a DPR or RC or something. I cannot find this hash anywhere so not sure what version you are currently using. Please revert from backup and show screenshot of **Admin Panel > Dashboard > Information**.

Also, in the future, post issues like this [on the Forum](https://forum.osticket.com). GitHub is a place to report bugs, request new features, or submit a pull request. For help with upgrade issues, etc. always post on the Forum.

Cheers.

**Comment by michbsd** [comment]
Right, sorry. 
Backup won't help (even if I do daily DB backups) I would have to revert to the version prior to this release (which is at least a few years ago) 

This is the old running instance info:


<img width="952" alt="image" src="https://github.com/osTicket/osTicket/assets/8202334/639404f9-57c5-42e0-bd4a-adabacf14905">

**Comment by JediKev** [comment]
@michbsd 

Hmmm, that's not helping either as it doesn’t show the commit hash like it should (eg. `1.8-git (hash_here)`. If you do `git log --oneline` (after reverting codebase to what you were using) what’s the last commit hash you see?

Cheers.

**Comment by michbsd** [comment]
hmm.. doing a git describe shows

```
❯ git describe
v1.10-23-gb228eacb
```

```
❯ git log --oneline
b228eacb (HEAD -> pr-3494) Added SQL patch to support Help Topic Organization and Primary Contact Restrictions
4d8132a6 Merge branch 'develop' into feature/help-topic-organization-restrictions
11de92f7 Merge pull request #3446 from JediKev/issue/list-abbreviation
45af4b79 Merge pull request #3444 from jdelhome3578/issue/form-overlay
a80d9ed6 Loading Overlay
8513f137 List Item Abbreviation
901e5eae (tag: v1.10) Add release notes for v1.10
```

**Comment by JediKev** [comment]
@michbsd 

I see the issue now. It looks like [you merged this pull request](https://github.com/osTicket/osTicket/pull/3494) into your local branch. This pull request added an upgrade patch, added to the installer file, etc. to make DB changes which subsequently changed the DB schema signature. This pull was never merged into core and should've never been merged into your local branch as this very issue would occur next time you went to upgrade (hence why we are here). It is _never_ a good idea to merge a non-merged pull request _especially_ if it changes the schema signature and makes DB changes. If you do you will need to fix any issues yourself as it's no longer tracking core.

Regardless, I think you should be okay if you put your schema signature on `98ad7d550c26ac44340350912296e673` and retry the upgrade. So login to your DB, go to the `_config` table, update your `key` of `schema_signature`'s `value` to `98ad7d550c26ac44340350912296e673`, and retry the upgrade process.

Cheers.
