### ISSUE TITLE
Wrong dashboard data

### ISSUE THREAD

**Issue by jpccaldas** [osTicket/osTicket#6628]
### Prerequisites

* [ No ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ No ] Do you have any errors in the PHP error log, or javascript console?
* [ Yes ] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [ Yes ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

Dashboard does not reflect correct data.
![image](https://github.com/osTicket/osTicket/assets/77206541/8679f7db-85f1-45df-818f-c62ca134afc1)

I did some tests before put osTicket to production, then I reseted tables as showed here: https://forum.osticket.com/d/96785-reset-dashboard
Maybe that's the cause? Can this be resolved?

### Steps to Reproduce

1. View dashboard

**Expected behavior:** Show data as normal.

**Actual behavior:** Data does not match any reality.

### Versions

![image](https://github.com/osTicket/osTicket/assets/77206541/28ae9d34-ccab-4faf-aeb2-c7e347567ea8)

Server: Windows Server 2012 R2
Me: Windows 11, Microsoft Edge

**Comment by jpccaldas** [comment]
After some tests, I realized that the problem must be somewhere at the SQL tables. If I import the SQL from my production environment to the test one, the problem is reproduced.
If I truncate the `ost_thread`, `ost_thread_entry`, `ost_thread_event`, `ost_ticket` and `ost_ticket__cdata` the dashboard works again. The problem is that I can't lose this data 😢
Any clue?

**Comment by JediKev** [comment]
@jpccaldas 

I assume you are talking about the Plot Data (ie. the graph). If so, you can take a look at the code below to see how we generate that data:
- https://github.com/osTicket/osTicket/blob/develop/include/class.report.php#L85

This will also show the queries used so you can run those manually to see where the disconnect is.

Cheers.

**Comment by jpccaldas** [comment]
Hey @JediKev!

Thank you for your answer. I'm talking about the graph and the table below. All information except "closed" tickets are wrong 😢

**Comment by jpccaldas** [comment]
OK, after running that query I can see that the `name` column is filled with `NULL` except for `closed` event 😢
The question is: is there any query we can run to fix this? The `event` table has only one term in English, but I did not change this at any time on this instance, is that the cause of this problem?

**Comment by JediKev** [comment]
@jpccaldas 

If you are saying your `_event` table only has one record and it's for "closed" then yes that's a problem. The `_event` table should have all of the following records:
<img width="258" alt="Screen Shot 2023-10-26 at 15 46 23" src="https://github.com/osTicket/osTicket/assets/11823401/0f7a2b5c-e198-479f-901f-69149b125e6f">

Cheers.

**Comment by jpccaldas** [comment]
Not actually; my `events` table had this data:

![image](https://github.com/osTicket/osTicket/assets/77206541/57d94b4b-7df2-4bf4-b9ea-d71576283a0f)

And by this, only `closed` event (which has the ID 2) is shown on dashboard.

I installed osTicket with pt-PT lang by default and it seems to have translated some data at DB install phase...

**Comment by JediKev** [comment]
@jpccaldas 

Yea you need to convert those back to English. I’ve fixed all those for all language packs we just need to generate new packs eventually so this doesn’t happen on install. But yea once you convert them back to how my screenshot looks you should be good to go.

Cheers.

**Comment by jpccaldas** [comment]
Ok, that will solve the new tickets from now on. But is there something I can do to save all the old ones? The `event_id` field is full on `NULL` values (except the ones with ID 2, the closed ones) 😢

![image](https://github.com/osTicket/osTicket/assets/77206541/105b785f-d916-46d8-bea2-dffb813d3b12)

**Comment by JediKev** [comment]
@jpccaldas 

Not unless you manually add the correct `event_id` to each one.

Cheers.

**Comment by jpccaldas** [comment]
Jesus... Thanks for your answers. Keep up the good work.
