### ISSUE TITLE
Queues v1.18.1: Fatal Error with Priority Level criteria

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket#6638]
### Description

Fatal error when a queue search criteria has Priority Level includes or does not include items. This issue was introduced in v1.18.1 (0375576)

As you can see from the screenshot below a side issue is that it reads "Priority Level does not include array" instead of showing the selected items like Status Name.
![image](https://github.com/osTicket/osTicket/assets/5774055/6d3c024c-4c21-4a6d-9bb8-88377cad5c48)
![image](https://github.com/osTicket/osTicket/assets/5774055/2f74198d-e28c-46be-9be1-f871b1c4e36d)

``[22-Nov-2023 03:40:45 UTC] PHP Fatal error:  Uncaught InconsistentModelException: Unable to prepare query: Got error 'repetition-operator operand invalid' from regexp SELECT A1.`number` AS `number`, A1.`ticket_id` AS `ticket_id`, A1.`source` AS `source`, A1.`ticket_pid` AS `ticket_pid`, A1.`flags` AS `flags`, A1.`lastupdate` AS `lastupdate`, A3.`subject` AS `cdata__subject`, A1.`isoverdue` AS `isoverdue`, B6.`name` AS `user__name`, A3.`priority` AS `cdata__priority`, A2.`id` AS `status__id`, B7.`firstname` AS `staff__firstname`, B7.`lastname` AS `staff__lastname`, B8.`name` AS `team__name`, A1.`team_id` AS `team_id`, A1.`isanswered` = '0' AS `2GkBZxz`, A1.`created` BETWEEN (NOW() - INTERVAL '4' HOUR) AND NOW() AS `5o9I84X`, (SELECT COUNT(R0.`id`) AS `count` FROM `ost_thread` Q7 JOIN `ost_ticket` Q8 ON (Q7.`object_type` = 'T' AND Q7.`object_id` = Q8.`ticket_id`) LEFT JOIN `ost_thread_entry` R0 ON (Q7.`id` = R0.`thread_id`) WHERE Q8.`ticket_id` = A1.`ticket_id` AND NOT R0.`flags` & 4 != 0) AS _thread_count, (SELECT COUNT(R1.`id`) AS `count` FROM `ost_thread` Q7 JOIN `ost_ticket` Q8 ON (Q7.`object_type` = 'T' AND Q7.`object_id` = Q8.`ticket_id`) LEFT JOIN `ost_thread_entry` R0 ON (Q7.`id` = R0.`thread_id`) LEFT JOIN `ost_attachment` R1 ON (R1.`type` = 'H' AND R0.`id` = R1.`object_id`) WHERE Q8.`ticket_id` = A1.`ticket_id` AND R1.`inline` = 0) AS _att_count, C0.`expire` > NOW() AND NOT C0.`staff_id` = 1 AS `_locked`, (SELECT COUNT(R0.`id`) AS `count` FROM `ost_thread` Q7 JOIN `ost_ticket` Q8 ON (Q7.`object_type` = 'T' AND Q7.`object_id` = Q8.`ticket_id`) LEFT JOIN `ost_thread_collaborator` R0 ON (Q7.`id` = R0.`thread_id`) WHERE Q8.`ticket_id` = A1.`ticket_id`) AS _collabs, COALESCE(B7.`firstname`, B7.`lastname`, B8.`name`, 'zzz') AS `assignee` FROM `ost_ticket` A1 JOIN `ost_ticket_status` A2 ON (A1.`status_id` = A2.`id`) LEFT JOIN `ost_ticket__cdata` A3 ON (A1.`ticket_id` = A3.`ticket_id`) LEFT JOIN `ost_thread` A4 ON (A4.`object_type` = 'T' AND A1.`ticket_id` = A4.`object_id`) LEFT JOIN `ost_thread_referral` A5 ON (A4.`id` = A5.`thread_id`) LEFT JOIN `ost_staff` A6 ON (A5.`object_type` = 'S' AND A5.`object_id` = A6.`staff_id`) LEFT JOIN `ost_thread` A7 ON (A1.`ticket_id` = A7.`object_id` AND A7.`object_type` = 'C') LEFT JOIN `ost_thread_referral` A8 ON (A7.`id` = A8.`thread_id`) LEFT JOIN `ost_staff` B0 ON (A8.`object_type` = 'S' AND A8.`object_id` = B0.`staff_id`) LEFT JOIN `ost_team` B1 ON (A5.`object_type` = 'E' AND A5.`object_id` = B1.`team_id`) LEFT JOIN `ost_team` B2 ON (A8.`object_type` = 'E' AND A8.`object_id` = B2.`team_id`) LEFT JOIN `ost_department` B3 ON (A5.`object_type` = 'D' AND A5.`object_id` = B3.`id`) LEFT JOIN `ost_department` B4 ON (A8.`object_type` = 'D' AND A8.`object_id` = B4.`id`) LEFT JOIN `ost_ticket_priority` B5 ON (A3.`priority` = B5.`priority_id`) LEFT JOIN `ost_user` B6 ON (A1.`user_id` = B6.`id`) LEFT JOIN `ost_staff` B7 ON (A1.`staff_id` = B7.`staff_id`) LEFT JOIN `ost_team` B8 ON (A1.`team_id` = B8.`team_id`) LEFT JOIN `ost_lock` C0 ON (A1.`lock_id` = C0.`lock_id`) WHERE A2.`state` = 'open' AND A2.`state` = 'open' AND NOT A2.`id` IN (10, 12) AND NOT A3.`priority` REGEXP '\"?(?<![0-9])5(\"|,|$)' AND ((A2.`state` = 'open' AND (A1.`staff_id` = 1 OR A6.`staff_id` = 1 OR A7.`object_type` = 'C' AND B0.`staff_id` = 1 OR A1.`team_id` IN (2, 5, 7, 8, 9, 10) OR B1.`team_id` IN (2, 5, 7, 8, 9, 10) OR A7.`object_type` = 'C' AND B2.`team_id` IN (2, 5, 7, 8, 9, 10))) OR A1.`dept_id` IN (3, 6, 7, 9) OR B3.`id` IN (3, 6, 7, 9) OR A7.`object_type` = 'C' AND B4.`id` IN (3, 6, 7, 9)) AND (A1.`ticket_pid` IS NULL OR A1.`flags` & 8 != 0) GROUP BY A1.`ticket_id` ORDER BY B5.`priority_urgency` ASC, A1.`lastupdate` DESC LIMIT 50 in C:\inetpub\osTicket\Live\include\class.orm.php:3483
Stack trace:
#0 C:\inetpub\osTicket\Live\include\class.orm.php(3529): MySqlExecutor->execute()
#1 C:\inetpub\osTicket\Live\include\class.orm.php(2104): MySqlExecutor->getArray()
#2 C:\inetpub\osTicket\Live\include\class.orm.php(2054): HashArrayIterator->{closure}()
#3 C:\inetpub\osTicket\Live\include\class.orm.php(2033): CallbackSimpleIterator->next()
#4 C:\inetpub\osTicket\Live\include\class.orm.php(2042): CallbackSimpleIterator->rewind()
#5 C:\inetpub\osTicket\Live\include\class.orm.php(1713): CallbackSimpleIterator->valid()
#6 C:\inetpub\osTicket\Live\include\class.orm.php(1723): CachedResultSet->fillTo()
#7 C:\inetpub\osTicket\Live\include\class.orm.php(1739): CachedResultSet->asArray()
#8 C:\inetpub\osTicket\Live\include\staff\templates\queue-tickets.tmpl.php(258): CachedResultSet->getIterator()
#9 C:\inetpub\osTicket\Live\scp\tickets.php(569): require_once('...')
#10 {main}
  thrown in C:\inetpub\osTicket\Live\include\class.orm.php on line 3483``

### Steps to Reproduce

1. Add Priority Level to the queue search criteria
2. use include or does not include
3. select items

**Expected behavior:** The queue loads with the selected criteria.

**Actual behavior:** The queue does not load. A fatal error is in the log.

### Versions

Server Information
--
osTicket Version | v1.18.1 (0375576) —  Up to date
Web Server Software | Microsoft-IIS/10.0
MySQL Version | 5.7.41
PHP Version | 8.1.25
Server 2019

Client
Windows 10
Chrome Latest

**Comment by JediKev** [comment]
@jdelhome3578 

Can you try setting up a test environment with MySQL 8.0 and retest? I believe the issue is due to the MySQL version as post-5.7 (ie. 8.0+) they changed their REGEX engine from Henry Spencer's implementation to ICU implementation.

Cheers.

**Comment by jdelhome3578** [comment]
@JediKev 

MySQL 8.0 solved the fatal error.

Not sure what bug is causing the "Array" text.
![image](https://github.com/osTicket/osTicket/assets/5774055/442d8ddb-d51a-4510-a21c-2729bf085723)
