### ISSUE TITLE
Cannot login after enable Cloudflare proxy

### ISSUE THREAD

**Issue by huyhoang8398** [osTicket/osTicket#6645]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

After enabled Cloudflare proxy, I no longer can login into OSticket
### Steps to Reproduce

1. Enable Cloudflare proxy
2. Login to osticket via scp

### Versions

v1.15.7
Amazon Linux 2
Chrome/Firefox

**Comment by JediKev** [comment]
@huyhoang8398 

First off, you are using an old and unsupported version of osTicket. You will need to upgrade to the latest and retest. Secondly, when using a proxy it’s important you edit your `include/ost-config.php` file and modify this setting:
- https://github.com/osTicket/osTicket/blob/develop/include/ost-sampleconfig.php#L117-L136

Cheers.

**Comment by huyhoang8398** [comment]
Hi @JediKev , Thanks for your reply
yes since we are still using old server.

I have tried to set that parameter with  Wildcard "*" (not recommended) can be used to trust all chained IPs , also clear cached from Cloudflare and cookies, also session database, but I still cannot login

**Comment by JediKev** [comment]
@huyhoang8398 

Well, we can only help if you are using a supported version. At this point you’d have to look at your various logs in osTicket and on the server to see what’s going on.

Also, ensure that the requests come in with the appropriate headers outlined in the link above (ie. `HTTP_X_FORWARDED_FOR` and `HTTP_X_FORWARDED_PROTO`).

Cheers.

**Comment by huyhoang8398** [comment]
Just found that if i put in a separate domain, it will work but not if for example with wordpress site and /tickets is for osTicket. my .htaccess is default from wordpress

**Comment by JediKev** [comment]
@huyhoang8398 

Can you try changing the `SSL` setting to `Full Strict` in your [Cloudflare configuration](https://community.cloudflare.com/t/wordpress-hosted-website-stops-responding-when-dns-proxy-is-enabled/549771)?

You may also want to _disable_ the **Admin Panel > Settings > Agents > Bind Agent Session to IP** setting, clear all site cookies, and retest.

Cheers.

**Comment by huyhoang8398** [comment]
Thanks @JediKev , it works well by disabling `bind agent session to IP` now.
Have a great day
