### ISSUE TITLE
Docker Build - Deprecated issues

### ISSUE THREAD

**Issue by klap50** [osTicket/osTicket#6651]
### My docker repo: github[dot]com/klap50/osticket-publico

I am encountering a series of deprecated notices and warnings in my Docker container while running my OSTICKET application. These notices are related to deprecated PHP code and are triggered during the execution of my application. The specific warnings and deprecations include:

Deprecated parameters: The code includes deprecated parameters in function declarations, where optional parameters are declared before required parameters. This is no longer supported in modern PHP.

Return type declarations: Several functions and methods have return type declarations that are not compatible with their parent interfaces or classes. This results in PHP warnings related to return type compatibility.

Session-related warnings: There are warnings related to session configuration, specifically the use of ini_set() and session_cache_limiter(). These warnings indicate that session settings are being modified after headers have already been sent.

These deprecation notices and warnings can affect the stability and performance of the application and should be addressed to ensure that the application runs smoothly.

I have provided a link to my Docker repository on GitHub (github[dot]com/klap50/osticket-publico) for reference and context.

**Comment by klap50** [comment]
I try with PHP 7.4, 8.0, 8,1, 8.2 and 8.3 (in the web from osticket say 8.1 ... but dont work with that ver).

**Comment by JediKev** [comment]
@klap50 

Deprecations, Notices, and Warnings can be ignored by configuring your `error_reporting` INI directive and even in the included `bootstrap.php` file. You should always have `display_errors` and `display_startup_errors` disabled in production as well.

Apart from that we have shifted the majority of our focus to v2.0. If you would like to contribute to fixing the above warnings, etc. please feel free to do so and make a pull request. Otherwise you’ll have to wait until we can get to them.

Cheers.

**Comment by klap50** [comment]
"Thank you for your response and guidance regarding the deprecations, notices, and warnings. I understand the importance of configuring error_reporting and disabling display_errors and display_startup_errors in a production environment. I will make those adjustments to suppress the warnings.

However, I wanted to highlight another issue I'm facing with my Docker setup. The installation process doesn't seem to progress when I initiate it via the web interface. It appears to be stuck or not proceeding as expected. I suspect that the warnings related to session ini settings in the bootstrap.php file might be related to this issue. Is there anything specific I should check or configure to ensure the installation process runs smoothly?

Regarding the new version (v2.0) you mentioned, I'm definitely interested in contributing and trying to set up a Docker environment for it. While I may not have extensive expertise, I'm willing to explore and learn. If I come across any issues or have suggestions, I'll do my best to contribute and make a pull request.

Once again, thank you for your assistance, and I look forward to being part of the community and helping improve OSTICKET.

```
WARNINGS:

Warning: ini_set(): Session ini settings cannot be changed after headers have already been sent in /var/www/html/bootstrap.php on line 19

Warning: session_cache_limiter(): Session cache limiter cannot be changed after headers have already been sent in /var/www/html/bootstrap.php on line 21
```

**Comment by JediKev** [comment]
@klap50 

If installation does not progress you would need to look at your various log files to see if there are any related errors. If those warnings, etc. are shown on screen then that could cause issues as well. I’d recommend retesting after making the above adjustments.

Cheers.

**Comment by klap50** [comment]
i make work:
github[dot]com/klap50/osticket-publico

dockerhub:
hub[dot]docker[dot]com/r/klap50/osticket-enginex


i think we can close this! Thanks!
