### ISSUE TITLE
Add "Help Topic:" from api 

### ISSUE THREAD

**Issue by ilya-savichev** [osTicket/osTicket#6653]
Hi, how to write a value in the Help Topic field via API json?
![Uploading Screenshot_30.jpg…]()

**Comment by JediKev** [comment]
@ilya-savichev 

This is the wrong place to ask such questions. You will need to use [the Forum](https://forum.osticket.com) next time.

With that being said, you need to review the API documentation as it’s explained there:
- https://docs.osticket.com/en/latest/Developer%20Documentation/API/Tickets.html

Cheers.

**Comment by ilya-savichev** [comment]
Thank you 🙏🙏🙏
--
Отправлено из Mail.ru для Android четверг, 28 декабря 2023г., 17:28 +03:00 от JediKev  ***@***.*** :
