### ISSUE TITLE
Intended use of Alerts for "Assigned Agent/Assigned Team"  

### ISSUE THREAD

**Issue by digidigital** [osTicket/osTicket#6659]
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

The alerts guide https://docs.osticket.com/en/latest/Guides/Alerts%20Guide.html has this description for "New Internal Activity Alert":

> New Internal Activity Alert: Alert sent out to Agents when internal activity such as an internal note or an agent reply is appended to a ticket.This Alert is sent to ***all members enabled***; Duplicate alerts are not sent out.

further down..

> Internal Activity Alert for the Assigned Agent/Team is sent to the assigned agent ***or*** team if there is no response from another agent posted on the ticket or the alert for last respondent is not enabled.

Please note the "or".
 
As I understand it, this means that only the assigned agent receives an alert, except in cases where no agent is assigned but a team is. Then the team is alerted. 

According to this pull request the description in the guide may have matched the code in earlier versions (1.7.x) before it was "fixed" -> https://github.com/osTicket/osTicket/pull/6601/commits/6ffd57108bfad27bb6156d519ce20769ab201656  

At least in v1.18.1 the function onActivity works differently since "elseif ($team = $this->getTeam())" was changed to  "if ($team = $this->getTeam())" 
     
```
// Assigned staff / team
        if ($cfg->alertAssignedONTaskActivity()) {
            if (isset($vars['assignee'])
                    && $vars['assignee'] instanceof Staff)
                 $recipients[] = $vars['assignee'];
            elseif ($this->isOpen() && ($assignee = $this->getStaff()))
                $recipients[] = $assignee;

            if ($team = $this->getTeam())
                $recipients = array_merge($recipients, $team->getMembersForAlerts());
        }
```
- https://github.com/osTicket/osTicket/blob/develop/include/class.task.php#L1182
- https://github.com/osTicket/osTicket/blob/develop/include/class.ticket.php#L1958

### Use case

Setup:
- Department "IT"
  - Team "Servicedesk"
  - Team "Admin"
- Sub-Department "IT / Application A"
 
Configuration:
- Department "IT" is the default department
- Incoming Tickets get standard Help-Topic "Standard" 
- Help-Topic "Standard" tickets are assigned to team "Servicedesk" by default

Scenario:
- A ticket is received by email and automatically assigned to team "Servicedesk"

Variant A:
- An agent (Agent A) from Team "Servicedesk" is assigned to the ticket. (The ticket is now assigned to Agent A **AND** Team "Servicedesk" since team and agent assignments are independent from each other)
- Agent A does not reply to the ticket but creates a task (in the ticket) for an agent from Department "IT / Application A" (Agent B)
- Agent B completes the task an closes the task

**Expected behavior:** 
Only Agent A is notified about the closed task

**Actual behavior:** 
Agent A ***and*** all members of "Servicedesk" are notified

Variant B:
- The ticket is still assigned to team "Servicedesk" an has not been assigned to an individual  agent 
- The customer sends a reply to the auto-response
- The response is added to the ticket's thread

**Expected and actual behavior:** 
- All members of "Servicedesk" get the notification

### Suggested Solution(s)

Alternatives:
- Revert code back to be in line with documentation (fix the fix)
- Clarify documentation to be (more) in line with the current code (a feature not a bug)
- Add more notification options to cover more use cases: (new feature)
-- Split current configuration option in separate "Assigned Agent" and "Assigned Team" 
-- Add  "Cascaded Assigned Agent/Team" to cover the previously mention use case

Maybe related to https://github.com/osTicket/osTicket/issues/6473 ?

...at first I was a bit surprised that a ticket can be assigned to a team ***and*** an agent at the same time since the drop down in the "new ticket" form explicitly asks for an "agent ***or*** a team" 

### Versions
v 1.8.1

**Comment by JediKev** [comment]
@digidigital 

The merged fix was correct; we simply need to update the documentation. Thanks for the notice.

Just to note, you can assign both an Agent and a Team to a single Ticket/Task. It’s been like that for a _long_ time.

Cheers.

**Comment by JediKev** [comment]
@digidigital 

[This is now updated](https://github.com/osTicket/docs/pull/175) in the official public documentation. If you still see the old wording you may need to clear all cache/cookies/sessions and/or hard reload the browser.

Cheers.
