### ISSUE TITLE
unable to setup gmail stmp on osticket

### ISSUE THREAD

**Issue by Jlery** [osTicket/osTicket#6689]
I'm having this error in setting up email using gmail stmp

cannot connect to host; error = stream_socket_client(): Unable to connect to tcp://mail.gmail.com:587 (php_network_getaddresses: getaddrinfo for mail.gmail.com failed: Name or service not known) (errno = 0 )

**Comment by JediKev** [comment]
@Jlery 

This is the wrong place for this. Please use [the Forum](https://forum.osticket.com) instead.

Cheers.
