### ISSUE TITLE
Ticket Subject issue in Custom Form?

### ISSUE THREAD

**Issue by regorsec** [osTicket/osTicket#6691]
### Description: All tickets part of a specific help topic have a "Subject" equal to the Help Topic name, which isn't correct.
![image](https://github.com/osTicket/osTicket/assets/46014561/adcc28d6-96bf-49c0-8c8d-51840c005925)

### Screenshot of Default Field: 
![image](https://github.com/osTicket/osTicket/assets/46014561/915cbc50-3551-46a2-83d8-6d2c78bcc616)

### The Configuration:
1. Latest version of osTicket, I replicated on two brand new builds. 

2. I have a "Help Topic" with two forms:

- (Default) Contact Information
- (Custom) Supplies Request

My custom form has a field with a variable 'subject', I thought this would fix the issue. (Screenshot below)

![image](https://github.com/osTicket/osTicket/assets/46014561/00afcec7-4689-46c3-8c9d-17b00f71ac8c)

Any help is greatly appreciated.

### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch? (YES)
* [ ] Do you have any errors in the PHP error log, or javascript console? (NO)
* [ ] Did you check the [osTicket forums](https://forum.osticket.com/)? (YES)
* [ ] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported? (YES)

**Comment by JediKev** [comment]
@regorsec 

First thing, you posted this in the wrong place. You should use [the Forum](https://forum.osticket.com) for things like this. This is more of a user/setup issue not an actual issue with the codebase. Github is a place to report actual bugs with the codebase, to create feature requests, and to submit pull requests.

With this being said, I will provide an answer here for ease; just next time please use the Forum. Custom Form Fields cannot have the same Variable names as any other field. Variable names are not form-dependent so _all_ Variable names across _all_ Forms need to be _unique_. Simply change your Custom Field Variable to something else (eg. `subject_custom`), update the Custom Field Variable in your Email Templates (wherever you added it), and voila issue resolved.

You can find this information in our [documentation here](https://docs.osticket.com/en/latest/Admin/Emails/Templates.html?highlight=unique) (albeit it's a bit hidden). To note, we are refactoring Form Field Variables in v2.0 so stay tuned!

Cheers.

**Comment by regorsec** [comment]
Hello Jedi, thanks for your reply.

1. Apologies, will use The Forum future tense.

2. You mentioned "update the Custom Field Variable in your Email Templates" however my issue isn't related to email data. 

My goal is to get the ticket subject showing in the agent portal. Is there a way to modify the portal variable section highlighted in the below screenshot?

![image](https://github.com/osTicket/osTicket/assets/46014561/c0f8a9e1-48b7-4316-9a07-c1a1e0d729c4)

**Comment by JediKev** [comment]
@regorsec 

Navigate to **Admin Panel > Settings > Tickets > Queues**, click on the relevant Queue name, click **Columns**, click **Config** next to the **Subject** Column, and update the **Primary Data Source**.

**Reference:**
- [Custom Columns & Custom Queues (Admin)](https://docs.osticket.com/en/latest/Features/Custom%20Columns%20&%20Custom%20Queues%20(Admin).html)

Cheers.

**Comment by regorsec** [comment]
That worked perfect, Very Appreciated! Thanks so much!

<3

~Regor
