### ISSUE TITLE
Call to undefined function ctype_digit()

### ISSUE THREAD

**Issue by PPCM** [osTicket/osTicket#6701]
### Prerequisites

* [X] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [X] Do you have any errors in the PHP error log, or javascript console?
* [X] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [X] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

Hello the team,

I have the following error Excessive `errors processing emails for ssl://outlook.office365.com:993/IMAP` when it try to fetch emails
After lot of searches, many fixes where applyed, even this one
https://github.com/osTicket/osTicket/pull/6683
But it doesn't work better
(Each time I go back to the original version of files)

After enabling DEBUG logs, Mail Fetcher raises
`Call to undefined function ctype_digit()`

### Steps to Reproduce

3 emails are présent in the inbox of the Exchange 365 server, I keep them to make issue test

**Expected behavior:** Collect all emails

**Actual behavior:** 
For new email
- User is created
- Ticket is created
- Ticket and user are associated
- **The body of the email is not present in the ticket**

### Versions

- osTicket : v1.18.1 (0375576)
- Web server : Apache
- MariadBD : 11.3.2
- PHP : 8.2.18
- Alpine : 3.19.1

**Comment by JediKev** [comment]
@PPCM 

By doing a quick Google search it appears the cause of the `ctype_digit()` error is that your PHP installation has the `ctype` extension explicitly disabled. If you use a hosting provider please reach out to them and ask them to enable the `ctype` extension for your PHP installation.

**References:**
- https://stackoverflow.com/questions/47319212/unusual-error-in-code-igniter-system-file-when-deployed-to-a-vps-server
- https://www.php.net/manual/en/ctype.installation.php

Cheers.

**Comment by PPCM** [comment]
@JediKev A big thanks
Effectively, in Alpine PHP version ctype is not by default, the package was added and it works like a charm
Perhaps a new check is needed in setup information page to say if ctype is present or not...

**Comment by JediKev** [comment]
@PPCM 

Here is the official pull request that updates the prerequisites to include the `ctype` extension:
- https://github.com/osTicket/osTicket/pull/6703

Note, this updates the Installer Prerequisites, the System Information page, and the `README.md` file.

Thanks for the feedback. Cheers.
