### ISSUE TITLE
Oauth2 plugin gives "AUTHENTICATE failed." but succeeds in Azure logs

### ISSUE THREAD

**Issue by JCoupalK** [osTicket/osTicket#6715]
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ ] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

Oauth2 plugin with Microsoft gives me "AUTHENTICATE failed." but I see it succeeds in the Azure logs.

It worked on one of my emails addresses and on the second one where I setup the Oauth app exactly the same it just kept giving me this:
![image](https://github.com/osTicket/osTicket/assets/108779415/623198a1-719e-48a7-a2a0-0d4aad92be62)

Curious as to why I removed the one that worked and try to adding it again and now that one didn't work too...

Outside of those errors I don't see any osTicket system logs, browser console logs and didn't find anything relevant in the server logs.

It only gives me that error when I enable email fetching, I see the token in Config:
![image](https://github.com/osTicket/osTicket/assets/108779415/7331e3df-bdc5-438d-a8e3-f60ef4b2ae15)

The token also seems to be refreshing itself as it should.

Here is the Azure sign-in log:
![image](https://github.com/osTicket/osTicket/assets/108779415/68c01a9d-4943-405b-9a27-53a65ca6d05c)
![image](https://github.com/osTicket/osTicket/assets/108779415/cd09b15f-1218-411f-9d07-16f8f8afa539)

### Steps to Reproduce

1. Do the normal Oauth2 plugin install on a fresh osTicket instance.
2. Try to configure a Office 365 user mailbox inside of osTicket using a Oauth2 app.

**Expected behavior:** Be able to authenticate itself to then send and receive emails.
**Actual behavior:** Gives me the error "AUTHENTICATE failed.".

### Versions
![image](https://github.com/osTicket/osTicket/assets/108779415/2e736e9b-4014-473a-8673-5aa1fbfa673d)
![image](https://github.com/osTicket/osTicket/assets/108779415/a8256bf7-6c48-4992-b8f9-6f567a43bb60)

Running on Ubuntu 22.04 and my browser being Microsoft Edge but also tried on Firefox + Chrome.

**Comment by JCoupalK** [comment]
Forgot to include my App registration config screenshots:
![image](https://github.com/osTicket/osTicket/assets/108779415/5aebc926-e31f-4887-897d-bd6880037d58)
![image](https://github.com/osTicket/osTicket/assets/108779415/eff2c21c-1baf-4a48-a4cb-a06cd19895b7)
![image](https://github.com/osTicket/osTicket/assets/108779415/6b5c8a1f-85bf-4602-8959-8a78653ee30d)

**Comment by JediKev** [comment]
@JCoupalK 

1. You need to show your plugin config.
2. You need to provide admin consent to the permissions.

Cheers.

**Comment by JCoupalK** [comment]
@JediKev 
This is the config:
![image](https://github.com/osTicket/osTicket/assets/108779415/09e46ca9-7490-4733-8006-cccc44f4a809)

And you can see the admin consent for the permissions it asks already has been granted here:
![image](https://github.com/osTicket/osTicket/assets/108779415/e2ed854a-2d8d-4365-a510-70770b1821b9)

**Comment by JediKev** [comment]
@JCoupalK 

To me everything looks good so far minus the fact not all permissions have been granted admin consent yet. You will need to grant admin consent for all the permissions in your screenshot, delete the existing token via the Delete Token button (within the Token tab in the Authentication Config popup), retrieve a new token, and retest.

Cheers.

**Comment by JCoupalK** [comment]
Those are the only permissions it asks for consent though, they are defined here and I didn't change the default ones:
![image](https://github.com/osTicket/osTicket/assets/108779415/a50534f4-70d2-4515-b3f0-a9e347153268)

**Comment by JCoupalK** [comment]
And also if I do delete the token and redo it like I said before it says its succesful at first like so:
![image](https://github.com/osTicket/osTicket/assets/108779415/a32406c5-7b19-43a6-8b79-d1d43e82552b)

But the moment I'll enable email fetching it will give me the error:
![image](https://github.com/osTicket/osTicket/assets/108779415/612c5810-d670-41ab-9900-f126a0a717c8)

**Comment by JediKev** [comment]
@JCoupalK 

It doesn’t matter, in my (and many others in the community and beyond) experience you still need to provide admin consent for them, delete the existing token (if any), and retrieve a new one. That’s just Microsoft for you.

You could also try disabling IMAP in the User’s Mail settings in the Exchange Admin Center (or main Admin Center - I forget which one) and re-enabling it to see if that helps. Users on the Forum have reported this helps in some cases.

Cheers.

**Comment by JCoupalK** [comment]
Hi, you are right it works now. Thank you.

I added all of them to the scopes:
![image](https://github.com/osTicket/osTicket/assets/108779415/c7ea74bd-e1c1-421e-b556-a2c9ca222265)

So it would ask for consent for all of them right away:

That should probably be like that by default.

**Comment by JediKev** [comment]
@JCoupalK 

You're welcome. Trust me, I've been dealing with this for years now ;)

Oh, I totally forgot to mention. Since I was the subject of the Forum, this is where you should open such cases in the future. Github is a place to report actual bugs, request new features, or submit pull requests. If you need help with errors, configuration assistance, general how-to's, etc. you should use the [Community Supported Forum](https://forum.osticket.com) instead.

Cheers.

**Comment by JediKev** [comment]
@JCoupalK 

>That should probably be like that by default.

Oh, you don't actually need to update the scopes within osTicket at all. You simply needed to provide admin consent via the App Registration itself, then use the default scopes we ship with, and you will be good.

Cheers.
