### ISSUE TITLE
want api to update existing ticket with ticket number

### ISSUE THREAD

**Issue by atulmahankal** [osTicket/osTicket#6726]
I am trying to integrate Zabbix alert with osTicket.

I successfully integrated the Zabbix trigger to create a ticket with an API request. but I was stuck updating the ticket status with a message.

After all searches, I found that an update ticket is currently not available.

Please guide how can I update the existing ticket with API.

**Comment by JediKev** [comment]
@atulmahankal 

Please use the [Community Supported Forum](https://forum.osticket.com) for help requests such as this. GitHub is a place to report actual bugs, to request new features, and to submit pull requests. Additionally this has already been requested as a feature and is coming with or after v2.0.

I will say that the osTicket API (as it currently stands) is _super_ basic and only allows for Ticket creation. You cannot update Tickets via the API.

Cheers.
