### ISSUE TITLE
keycloak authentication for the osticket

### ISSUE THREAD

**Issue by vanshita12345** [osTicket/osTicket#6731]
Hi, i am trying to integrate keycloak with osticket, but after configure keycloak when i tried to login with keycloak user i am landing on same page. In keycloak client session the user vanshita is showing. can someone help me, i tried most of the things i got from this forum, but didn't work. i am using Oauth2 Client this plugin

**Comment by JediKev** [comment]
@vanshita12345 

You posted this in the wrong place. GitHub is a place to report actual bugs, request new features, or submit pull requests. This is more of a question/request for help. You should instead use the [Community Supported Forum](https://forum.osticket.com) for general questions and requests.

I will say that I’ve gotten Keycloak to work before with no issues.

Cheers.

**Comment by vanshita12345** [comment]
Hey we successfully authenticate osTicket using keycloak

**Comment by marcobaldiniinaf** [comment]
> Hey we successfully authenticate osTicket using keycloak
> […](#)

Hi [vanshita12345], could you share how you successfully logged in using Keycloak? I'm having trouble with the callback — it keeps failing.
