### ISSUE TITLE
Which version of OSTicket is "current"?

### ISSUE THREAD

**Issue by mo-g** [osTicket/osTicket#6744]
A little confusion at my end, sorry - 

- OSTicket branch 1.18.x hasn't had any commits since 1.18.1 was formally released in October; while 1.17.x has had a number of PR's merged since then. 
- The 1.18.x branch hasn't received a fix to make it possible to install it, so it still has to be hand-patched before deployment - the branch as it stands is broken.
- When the 1.18.x branch is installed it shows the following version string: `System Settings and Preferences — osTicket (v1.17.5-57-gc4e675cf)`

Should users be running 1.17.x instead of 1.18.x?

Is it safe to use an existing 1.18.x database with the 1.17.x codebase; if I need to drop down a version?

**Comment by JediKev** [comment]
@mo-g 

1. 1.18.x is greater than 1.17.x so 1.18.x branch is the latest branch. We always support two major versions at a time; in this case 1.17.x and 1.18.x. If an issue is present in both 1.17.x and 1.18.x pulls will be merged into 1.17.x then subsequently 1.17.x gets merged into 1.18.x. So it may appear as though 1.17.x is the “latest” but it’s technically not. Also, you shouldn’t really be using the unstable branches like 1.17.x/1.18.x/develop/etc. as those are development branches and are not considered stable. To use a stable version you should use a tag instead like v1.17.5 or v1.18.1.
2. I have no idea what you mean by 1.18.x can’t install. You would need to provide more information and any related errors.
3. If it shows “v1.17.5-xxx” after installing “1.18.x branch” then you obviously didn’t do something right. I would instead recommend using the [fully packaged releases from our website](https://osticket.com/download) if you don’t know how to use [git deployment/versioning](https://github.com/osTicket/osTicket?tab=readme-ov-file#deployment). We do have [documentation here](https://docs.osticket.com/en/latest/Getting%20Started/Installation.html) to help you with installation.

Also, there is no way to downgrade osTicket unless you manually revert any database patches that were ran and manually update the schema signature to its previous value. So you should always take full database backups and codebase backups before any upgrades in case you need to revert back for any reason.

Cheers.

**Comment by mo-g** [comment]
Thanks, Kev - I'll try switching to a tag, rather than the 1.18.x branch first, and see how that goes.

Here's why the 1.18.x branch can't install:

![image](https://github.com/user-attachments/assets/07839242-9fd1-4761-9c3a-a287289e889c)

The patch to fix that was only applied to develop, and not 1.18.x.

**Comment by mo-g** [comment]
Yep, checking out the tag instead of the devel branch included both the manage.php patch, and gave the correct version string. Thanks!
