### ISSUE TITLE
Is osTicket still maintained?

### ISSUE THREAD

**Issue by HusseinKabbout** [osTicket/osTicket#6746]
The last commit was pushed over a year ago. Is the development halted?

**Comment by JediKev** [comment]
@HusseinKabbout 

There have been many discussions on this topic; please go back and read them. Yes legacy is still in development but in maintenance mode whilst we focus on v2.0. You can follow the v2.0 roadmap here:
- https://github.com/osTicket/roadmap

Cheers.
