### ISSUE TITLE
osticket some pjax not work

### ISSUE THREAD

**Issue by luanzhiyong** [osTicket/osTicket#6747]
When I randomly click on a ticket num, it takes a bit slow to enter the inner page, usually taking more than 5 seconds. Upon checking, it shows that the pjax request has been automatically cancelled. I don't understand why, but all other links are working normally, just click preview ticket
![image](https://github.com/user-attachments/assets/019170b2-75ad-4c03-92fb-887d1044e640)

**Comment by luanzhiyong** [comment]
somebody can help me?

**Comment by JediKev** [comment]
@luanzhiyong 

This is not a support forum. GitHub is a place to report actual (replicable) bugs, to request new features, or to submit pull requests. If you have an issue or general questions you need to use the [Community Supported Forum](https://forum.osticket.com) instead.

Cheers.
