### ISSUE TITLE
SMTP Oauth Issues

### ISSUE THREAD

**Issue by ahmadfarhanzaki95** [osTicket/osTicket#6748]
Hi,

I am having error where osTicket email stopped working to send. I am using domain @outlook.com as sender email address.
Upon checking found out outlook is applying Oauth on their side. Is any way new version will release or temporary fix such as add on fix the issues.

<img width="467" alt="aaa" src="https://github.com/user-attachments/assets/1e92353b-7349-4e4b-b25c-e9b8f7d638b6">

**Comment by JediKev** [comment]
@ahmadfarhanzaki95 

[Upgrade osTicket](https://docs.osticket.com/en/latest/Getting%20Started/Upgrade%20and%20Migration.html) to v1.18.1 (or v1.17.5), download/install the [OAuth2 Plugin,](https://docs.osticket.com/en/latest/Guides/OAuth2%20Guide.html#setting-up-the-plugin) and follow the [OAuth2 Authorization Guide](https://docs.osticket.com/en/latest/OAuth2/Microsoft%20Authorization%20Guide.html) to setup OAuth2 authentication for your email address.

If you need further help or have further questions please use the [Community Supported Forum](https://forum.osticket.com). GitHub is a place to report actual/replicable bugs, to request new features, or to submit pull requests. The Forum is the place to ask generic questions, ask for general assistance, etc.

Cheers.

**Comment by ahmadfarhanzaki95** [comment]
Hi JediKev,

I encountered this issues when click add plugin.

![image](https://github.com/user-attachments/assets/6663d6ea-0e0a-4d99-a039-5a614559cd31)

Any possible solution for add plugin?

**Comment by JediKev** [comment]
@ahmadfarhanzaki95 

Please use the [Community Supported Forum](https://forum.osticket.com) for further assistance as previously stated.

Cheers.
