### ISSUE TITLE
Extremely slow 

### ISSUE THREAD

**Issue by Gaspar1146** [osTicket/osTicket#6749]
Hello osTicket Team and Community,

I'm encountering significant performance issues with my osTicket setup. Despite no apparent database problems (DB size is 110MiB, and attachments are on the filesystem), ticket operations are excessively slow. Whenever I open, update, or close tickets, the interface remains stuck on the loading screen. Strangely, changes are saved in the background, and tickets are created correctly; the problem seems isolated to the loading screen behavior.

Server Information:

    osTicket Version: v1.18.1 (0375576) — Up to date
    Web Server: Apache/2.4.52 (Ubuntu)
    MySQL Version: 10.6.18
    PHP Version: 8.3.11

This issue severely hampers usability, as it affects basic ticketing operations. Any advice or fixes would be greatly appreciated. Thank you for looking into this matter.

**Comment by JediKev** [comment]
@Gaspar1146 

1. Please read the requirements before upgrading/installing. You would’ve seen PHP 8.3 is not fully supported yet. Downgrade to PHP 8.2 ASAP.
2. Use the Forum for stuff like this. GitHub is a place to report actual bugs, request new features, or submit pull requests.


Cheers.

**Comment by Gaspar1146** [comment]
@JediKev 

1. The issue was present long before I upgrade to PHP 8.3, upgrading was a last resort to resolve the issue. 
2. This is an actual issue. 

Cheers.

**Comment by JediKev** [comment]
@Gaspar1146 

Yea, more than likely an issue with your setup. Again, please use the Forum for things like this.

Cheers.

**Comment by nandi96** [comment]
Please, read this, it will be help: https://forum.osticket.com/d/100445-scp-slow-log-on-verifying/2

**Comment by JediKev** [comment]
Keep in mind though that the referenced patch is really a bandaid for non-optimized databases and/or servers with not enough resources to handle the load of the potentially large count query.

If your database server has plenty of resources and the database is optimized to [MySQL](https://dev.mysql.com/doc/refman/8.4/en/optimization.html)/[MariaDB](https://mariadb.com/kb/en/optimization-and-tuning/) spec you should not need the patch.
