### ISSUE TITLE
Client portal ACL blocks file attachment downloads from the agent portal

### ISSUE THREAD

**Issue by jdhalbert** [osTicket/osTicket#6758]
### Prerequisites

* [ ] Can you reproduce the problem in a fresh installation of the "develop" branch? *Not attempted*
* [x] Do you have any errors in the PHP error log, or javascript console? *None*
* [x] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

### Description

ACL settings for the client portal can break file attachment downloads on the agent portal. 

### Steps to Reproduce

1. Have osTicket running with the "Attachments on the File System" plugin configured and the "Require login to view any attachments" box checked. (I have not tested the behavior with attachments in the database.)
2. Turn on the ACL for the "Client Portal" and set it to "0.0.0.0".
3. Log in as an agent and attempt to download a file attached to a ticket.
4. The file will appear to successfully download, but will be only 13 bytes in size.
5. Open the file in a text editor and see that it is a plain text file reading "Access Denied"
6. Turn off the ACL.
7. Re-download the file and see that it succeeds.

**Expected behavior:** Agents should be able to download file attachments from the admin portal regardless of ACL settings on the client portal.

**Actual behavior:** Agents using the agent portal cannot successfully download attachments if their IP is not on an ACL configured for the client portal.

### Versions

osTicket Version | v1.17.5 (7c20036) —  Up to date
Web Server Software | Apache/2.4.58 (Ubuntu)
MySQL Version | 8.0.39
PHP Version | 8.3.6

Browser: Brave v1.71.118

**Comment by JediKev** [comment]
@jdhalbert 

Thank you for the report. To note, the issue would be the same for both FS attachments and DB attachments; they both use `file.php`. We will look into this and make a pull soon.

Cheers.

**Comment by JediKev** [comment]
@jdhalbert 

Here is the pull that addresses this issue: #6765

It is subject to change as it's not fully approved/merged yet so just be aware of that.

This will be included in the next set of releases.

Thanks again for the report! Cheers.

**Comment by jdhalbert** [comment]
Thanks for addressing this so quickly!

Just a note-- as a side effect, this of course allows logged-in staff to access the client portal page too, regardless of the ACL. In my use case, I was intentionally denying access to that page to _everyone_ not on the ACL, including staff.

Granted, this may be uncommon. But if the client portal ACL will no longer apply to logged-in staff at all, that may be worth a note in the admin panel so logged-in admins trying to configure ACLs don't get confused when their ACL settings might look like they aren't working due to being logged in as staff.

Thanks again.
