### ISSUE TITLE
When i am Printing the ticket, the Arabic language is unreadable, osTicket (v1.17.5)

### ISSUE THREAD

**Issue by EmadSaleh07** [osTicket/osTicket#6760]
Dear All,
I am encountering an issue when attempting to print ticket threads, The Arabic text appears unreadable, as shown in the attached screenshot.
Could you kindly assist me in resolving this issue?
Thank you for your support.
osTicket (v1.17.5)

Best regards,

![Arabic Lang](https://github.com/user-attachments/assets/ba9ab3ba-ebb9-4517-9468-bd7efc9fa77a)

**Comment by JediKev** [comment]
@EmadSaleh07 

Search is your friend:
- https://github.com/osTicket/osTicket/pull/6684

Cheers.
