### ISSUE TITLE
No Image Link work

### ISSUE THREAD

**Issue by GamerClassN7** [osTicket/osTicket#6764]
### Prerequisites

* [X] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [X] Do you have any errors in the PHP error log, or javascript console?
* [X] Did you check the [osTicket forums](https://forum.osticket.com/)?
*  https://forum.osticket.com/d/105877-images-suddenly-stopped-displaying/7
* [X] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

No image is displayed on web .

### Steps to Reproduce

1. add image to thread
2. send the message
3. See the ticket no image will dispaly

**Expected behavior:** show the image

**Actual behavior:** no image link works

### Versions

![image](https://github.com/user-attachments/assets/8b1b666c-3e40-4978-93df-96f7db5237f1)
![image](https://github.com/user-attachments/assets/e097b168-c6ad-46a2-ab5a-e4af80f013a3)
![image](https://github.com/user-attachments/assets/31031d2b-204f-44c0-8bbc-64a4fc389316)

**Comment by GamerClassN7** [comment]
@JediKev  could you please look in to the issue ?  sinc this make os ticket unusable :/

**Comment by GamerClassN7** [comment]
it looks like something to do with https://github.com/osTicket/osTicket/blob/develop/include/class.file.php#L1109

since when i dump manually the content of getData() it cannot be decoded back to image, which is strange

**Comment by JediKev** [comment]
@GamerClassN7 

Search is your friend:
- https://github.com/osTicket/osTicket/pull/6624

Cheers.

**Comment by GamerClassN7** [comment]
> @GamerClassN7
> 
> Search is your friend:
> 
> * [issue: CSP Headers #6624](https://github.com/osTicket/osTicket/pull/6624)
> 
> Cheers.

Nice, Thank you i was unable to found it.

Any idea when correct fix will be relesed for 1.18. ?

**Comment by JediKev** [comment]
@GamerClassN7 

It will be included in the next set of releases coming very soon.

Cheers.

**Comment by GamerClassN7** [comment]
> @GamerClassN7
> 
> It will be included in the next set of releases coming very soon.
> 
> Cheers.

@JediKev 

BTW: not solve issue just checked my production and those headers are already there:
![image](https://github.com/user-attachments/assets/dc29782e-e3ac-4a23-beff-d2065ac8b693)

**Comment by GamerClassN7** [comment]
@JediKev  is there anything lese to try since, bug appeared out of nowhere.

**Comment by JediKev** [comment]
@GamerClassN7 

First thing is to move this to the Forum as we have not confirmed if this is an actual bug with the code or simply an issue with your setup, etc.

Cheers.

**Comment by GamerClassN7** [comment]
@JediKev  so when i have exactly same bug on different environment i tried to setup from scratch by tutorial on OST site, and i get same bug exactly same behavior.

**Comment by JediKev** [comment]
@GamerClassN7 

Hmm, I’m unable to replicate so let’s move this to the forum and there you can create a step-by-step guide on how you are able to replicate the issue. Including your environment details, what you did to install osTicket, what settings/configurations you changed in the system, where the file is coming from, how you are uploading it, etc.

Cheers.

**Comment by GamerClassN7** [comment]
there should be ob_clean(); on start of passthru function
![image](https://github.com/user-attachments/assets/0a4f4d42-1234-4145-aaf7-1aa761a6c7da)
