### ISSUE TITLE
support for php version 8.3 and greater for osticket v 1.18

### ISSUE THREAD

**Issue by Akif-Chishti** [osTicket/osTicket#6774]
faced lot of issues while installing php v8.3 on osticket v1.18 like imap on amazon linux 2023
Error: Unable to find a match: libc-client-devel libssl-devel
Error: Unable to find a match: php-pecl-apcu
Error: Unable to find a match: php-imap
![osticket](https://github.com/user-attachments/assets/f7adfe04-ff69-48b8-913a-730805e44442)

i have attached image saying **php imap extention** -- required for mail fetching
APCu Extention -- (faster performance)

**Comment by JediKev** [comment]
@Akif-Chishti 

You should always read the requirements before installing/upgrading. If you did so [you would’ve seen that PHP 8.3 is not supported yet](https://github.com/osTicket/osTicket?tab=readme-ov-file#requirements). Downgrade to PHP 8.2 and retest.

Always remember that search is your friend. [You can see from this pull](https://github.com/osTicket/osTicket/pull/6697) that PHP 8.3 support will be added next release.

Lastly, not all extensions are required; some are simply recommendations to improve the experience. [You can see from this pull](https://github.com/osTicket/osTicket/pull/6703) that `php-imap` was changed from required to optional. Also some distros of Linux, etc. simply don’t have the APCu extension available; that’s just how it is.

Cheers.

**Comment by Akif-Chishti** [comment]
i have installed php 8.2 but there were few commands where it automatically installed 8.3 also i have attached image should i proceed with installation will my incoming and outgoing emails still work? what about the faster performance ?
![osticket](https://github.com/user-attachments/assets/e0d8d0bc-4e3a-434b-b5c8-beb68d10886b)

**Comment by Akif-Chishti** [comment]
> @Akif-Chishti
> 
> You should always read the requirements before installing/upgrading. If you did so [you would’ve seen that PHP 8.3 is not supported yet](https://github.com/osTicket/osTicket?tab=readme-ov-file#requirements). Downgrade to PHP 8.2 and retest.
> 
> Always remember that search is your friend. [You can see from this pull](https://github.com/osTicket/osTicket/pull/6697) that PHP 8.3 support will be added next release.
> 
> Lastly, not all extensions are required; some are simply recommendations to improve the experience. [You can see from this pull](https://github.com/osTicket/osTicket/pull/6703) that `php-imap` was changed from required to optional. Also some distros of Linux, etc. simply don’t have the APCu extension available; that’s just how it is.
> 
> Cheers.

@JediKev please see my comment and guide
