### ISSUE TITLE
how to remove E-mail access link in OsTicket 1.8.1

### ISSUE THREAD

**Issue by MohamedFaisal** [osTicket/osTicket#678]
Hi everything is OK in 1.8.1.but is there any possibility to check the Ticket stayus without e-mail access link.

Regards,
Mohamed Faisal.

**Comment by mckaygerhard** [comment]
this doews not work without ldap. i make a new request for use cases when ldap are not used and still no feedback, i can edit the php files and post new feedback but please indicate me where and what!
