### ISSUE TITLE
change the placeholder on login page

### ISSUE THREAD

**Issue by EmadSaleh07** [osTicket/osTicket#6782]
I want change the text in placeholder at login page as showing in the attach file

![1734508628-779785-para](https://github.com/user-attachments/assets/9feeb8f5-fc89-4279-85d1-9b12c8e937f6)

**Comment by JediKev** [comment]
@EmadSaleh07 

First, you should use [the Forum](https://forum.osticket.com) for general questions. GitHub is a place to report bugs, request new features, and to submit pull requests.

With that being said I will go ahead and provide an answer while I’m already here. You will need to customize the codebase to accomplish this. When customizing the codebase you are on your own as you are deviating from core. I will say that GitHub has a great search feature, a code tree feature, and even code references feature. You will proceed at your own risk. Good luck!

Cheers.
