### ISSUE TITLE
invalid login check pop/imap/smtp settings

### ISSUE THREAD

**Issue by adamwbb** [osTicket/osTicket#723]
no matter what i try i keep getting the same error weather it be using pop/imap/smtp

no other error and nothing recored in logs.
i checked everything and all my settings for pop is matched up.

**Comment by osticketUser** [comment]
Hello, 
I am doing some tests on osticket, however i am getting same error in IMAP Settings and POP Too , Mail Account: Optional setting for fetching incoming emails. Mail fetching must be enabled with autocron active or external cron setup.   
[CLOSED] IMAP connection broken (server response)

Invalid login. Check IMAP settings

Any solution Please ? 

Thank you

**Comment by ntozier** [comment]
@osticketUser This appears to be a question better suited for the support forums at: http://osticket.com/forums.  That being said please help us to help you by providing us with more information about your setup.  Such as:

Version of osTicket?
Version of php?
What IMAP server are you using?
Are you using SSL?  Port #?
Depending on the mail server have you authorized the user to use IMAP, or the server to accept connections from your web server?

**Comment by osticketUser** [comment]
Hello,

Thank you for your response.

Version of osTicket : 1.9.12
Version of PHP : 5.5.12
IMAP Server : imap.gmail.com
Are you using SSL ? PORT ? : Yes, port 993

Regards,


On Fri, Jun 10, 2016 at 1:53 PM, ntozier <notifications@github.com> wrote:

> [image: Boxbe] <https://www.boxbe.com/overview> This message is eligible
> for Automatic Cleanup! (notifications@github.com) Add cleanup rule
> <https://www.boxbe.com/popup?url=https%3A%2F%2Fwww.boxbe.com%2Fcleanup%3Fkey%3D%252FvPgiTcw2AvLdpPANAeaPwJWMaQyuW0ImOC6uBVfoeM%253D%26token%3DAKBub9CYl%252BWfPiTHUgBJV3zbQfS9fUcILp%252FZsAhDLOXN%252Bkd70tUDMTVVoOm0z3WkqRrOSgyysdN%252FCj8AMMMpq7BoSc%252FdOoftEwFs0H7sootZHOuNHlN42tEltE228aPwYk1EkwyS6A0qKVpC%252B7%252BPSw%253D%253D&tc_serial=25713682302&tc_rand=1878629780&utm_source=stf&utm_medium=email&utm_campaign=ANNO_CLEANUP_ADD&utm_content=001>
> | More info
> <http://blog.boxbe.com/general/boxbe-automatic-cleanup?tc_serial=25713682302&tc_rand=1878629780&utm_source=stf&utm_medium=email&utm_campaign=ANNO_CLEANUP_ADD&utm_content=001>
>
> @osticketUser <https://github.com/osticketUser> This appears to be a
> question better suited for the support forums at:
> http://osticket.com/forums. That being said please help us to help you by
> providing us with more information about your setup. Such as:
>
> Version of osTicket?
> Version of php?
> What IMAP server are you using?
> Are you using SSL? Port #?
> Depending on the mail server have you authorized the user to use IMAP, or
> the server to accept connections from your web server?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/osTicket/osTicket/issues/723#issuecomment-225187714>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AS8AXKfdlda0XwFZsdgD4LxHfMosN_kjks5qKWxPgaJpZM4BsWZk>
> .
>
>


-- 

*         Soukaina MIHI*

*Ingénieur d'état en génie informatique*
*Master 2 spécialisé en informatique*

*Tél : (+212)670686510*
*Email : mihi.soukaina@gmail.com <mihi.soukaina@gmail.com>*
*Skype : souka.mihi*
*وَما نَيلُ المَطالِبِ بِالتَمَنّي.....وَلَكِن تُؤخَذُ الدُنيا غِلابا*
