### ISSUE TITLE
New Ticket User Auto response not sent to user (email tickets)

### ISSUE THREAD

**Issue by jonub** [osTicket/osTicket#726]
Current Version: V1.8.1.2.

When a user sends an email (uses email piping) to the support email, no New Ticket User Auto response is received by the user. The ticket is received ok. Other emails to the user are ok, for example when a reply is sent to the user they are received ok. 

The problem only exists if the ticket is initiated by email, as when a new ticket is initiated by the web,  a New Ticket User Auto response is received by the user ok, therefore supporting that all the appropriate autoresponse settings are ok. 

The only difference it seems between the email initiated new tickets and the web new ticket is that the web new ticket requires the user to specify a help.

Any suggestions would be most appreciated please

**Comment by Rahul-tyagi007** [comment]
Hello  greezybacon  need some help

**Comment by Rahul-tyagi007** [comment]
hello greezybacon

**Comment by ntozier** [comment]
@Rahul-tyagi007 you have not posted what you need help with.

**Comment by Rahul-tyagi007** [comment]
@ntozier  i want to know that ::

When client send mail on my mail id it receive automatic mail with ticket_id like you request has been receive and your ticket_id xyzzz ...

**Comment by ntozier** [comment]
Ummm.  I think that perhaps you should post a help thread at the forums.
You should explain your use case, your environment, and version of osTicket.
You would also want to explain why and how a client would be sending email using your user id.
Open ticket messages are enabled by default if you have configured a valid email in osTicket.

**Comment by Rahul-tyagi007** [comment]
Bro, 
if you have time then pls share which time you are free on India time(GMT) ... if you don't mine i explain all such things ...

**Comment by Rahul-tyagi007** [comment]
yeah ofcuise why not but when you free give me some time to explain these things or provide facebook id so that i connect with you if u dont mine..

**Comment by ntozier** [comment]
@Rahul-tyagi007 
Please utilize the support channels:
http://osticket.com/forum
-or-
http://osticket.com/commercial-support

**Comment by Rahul-tyagi007** [comment]
Hi,
Are you their ?? @ntozier

**Comment by Rahul-tyagi007** [comment]
@ntozier  Actuall i want to know how can client get autoreponse with ticket when client send mail on my support@xyz.com. the above two url is not straight forward can you pls provide good one or tell me scenerio for same .. thanks

**Comment by Rahul-tyagi007** [comment]
i m using linux centos server

**Comment by Rahul-tyagi007** [comment]
osTicket Version 	v1.9.12 (19292ad)
Upgrade
— This osTicket version is no longer supported. Please consider upgrading
Web Server Software 	Apache/2.2.15 (CentOS)
MySQL Version 	5.6.30
PHP Version 	5.3.3

**Comment by JoshSimerman** [comment]
Basically, O 365 Exchange distro groups cannot modify the default headers, or at least there were no power shell commands I could find that would work for a group. Certain transport rule actions are not available either. However, our Default domain settings for normal users is to allow all.

I removed the ticket system email as a member of the distro, and created a transport mail flow rule to add the ticket creation email address to the To: line when “the To: or CC: box contains” the support@mydomain address. 

I think, maybe if a user sends a new support request email while their OOF auto responder is on, then there is a chance for a mail storm loop to occur, or maybe if I reply from a ticket while the OOF is on. I’ll wait to see if it happens naturally.

**Comment by jezuk** [comment]
I've been looking at this issue again since migrating server and updating to OST 1.10

Back in June 2014 this was posted on the forum: http://osticket.com/forum/discussion/77588/resolved-fixed-auto-responses-not-sending-since-1-8-x

I've made the same mod and everything seems to be working fine.  However Peter warns this could cause an email loop, I'm not so sure?....

It seems the x-auto-response-suppress header is misunderstood.  Please check these posts as seen in other projects:

https://www.jitbit.com/maxblog/18-detecting-outlook-autoreplyout-of-office-emails-and-x-auto-response-suppress-header/

http://www.redmine.org/issues/19558

Interested to hear thoughts from those more experienced!
