### ISSUE TITLE
CSRF token broken when behind reverse proxy

### ISSUE THREAD

**Issue by ghost** [osTicket/osTicket#736]
Trying to use osTicket (v1.8.1-dpr) behind a reverse proxy, reliably getting 

```
 Invalid CSRF Token __CSRFToken__
Invalid CSRF token [b4cab350cfce13ee10a8cd27445e7f4466db039e] on
(redacted)
```

the cause seems to be the osticket javascript generating the token based off browser IP, which of course differs from the reverse proxy IP when the token is verified server-side.

Reverse proxy is an Apache instance on ec2

**Comment by webbe** [comment]
I know this post is over a year old, but popped up several times while trying to setup my reverse proxy with osTicket. I'm using NginX as my reverse proxy (I know, not supported, etc etc) with a few tweaks I was able to get passed the "Invalid CSRF Token" error.

in my location block I needed to add a few header settings:
```
 location / {
            proxy_set_header        Host            $host;
            proxy_set_header        X-Real-IP       $remote_addr;
            proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass_header       Set-Cookie;
            proxy_pass <Backend osTicket location>;
        }
```
The pass_header was what seemed to make it work, but the other settings will make sure your server receives the correct IP address. I believe you could set those settings in the server or http block as well, but this served my needs.

**Comment by greezybacon** [comment]
@webbe we don't officially support nginx as the server for osTicket. You can use whatever you want for the reverse proxy. Personally, I prefer HAProxy. Thanks for posting your configuration info.
