### ISSUE TITLE
Custom fields and JSON API error

### ISSUE THREAD

**Issue by greuff** [osTicket/osTicket#737]
Hello, I created a custom form which contains a custom field labelled and named "TestTest" and set it to required. Type is "short answer" and I assigned no validator. I assigned the custom form to a help topic. When I create a ticket using the JSON API with the correct topicId I always get the error "Unable to create new ticket: validation errors: 16: TestTest is a required field err: Missing or invalid data - check the errors and try again", although I submit data for this custom field named "TestTest". If I set the custom field to not required the ticket is created, however still no value is shown in the custom field. When I click edit on the ticket, however, I see the custom field and can assign data to it, so the help topic and custom forms assignment is correct. I don't really know what to try next. Please help, thank you.

osTicket 1.8.1.2

**Comment by comxd** [comment]
Hi,
Same issue ini 1.9.5.1. I try with label field, title and variable name but same error.

![image](https://cloud.githubusercontent.com/assets/9022239/6542431/27767ea4-c4f8-11e4-88d7-71cdefa0a978.png)

**Comment by comxd** [comment]
Update! That working good!

In my case (select list but that not allow multiple values) I need to send an array.

```php
   'product_type' => 6,

**Comment by Dusza** [comment]
thanks @comxd ..... that worked like a charm!
