### ISSUE TITLE
Automatically add Collaborators according to department

### ISSUE THREAD

**Issue by ghost** [osTicket/osTicket#770]
Hello,

Is-it possible to add collaborators automatically to a ticket according to the departments of creation. 

I mean that when I create a ticket through SCP as a staff member, I select a department, and I want to add collaborators automatically at the opening.

**Comment by ejc67** [comment]
We have a couple of departments we add a list of collaborators to - would it be easier to do the trigger or modify the PHP code.  If we do a trigger - I guess I could use an if statement to check which department id is being saved.
