### ISSUE TITLE
Add the collaborators field to the SCP ticket creation form

### ISSUE THREAD

**Issue by alexdel35** [osTicket/osTicket#771]
Hello,

I did not find how to add directly collaborators during the ticket creation. The collaborators field is not available. I have to come back in the ticket and add the collaborators later.

Is-it possible to add this field in this form?

**Comment by aravind089** [comment]
I have found a way for this.
Just add the email ids separated by comma in the new ticket creation form.
It works!

**Comment by henrycoule** [comment]
@aravind089 Your method did not work for me. New ticket creation form from the admin section or from the user sections

**Comment by timwhite** [comment]
@prasenjeetp If you could even post patch files, or a link to where your code has been implemented, then others can look at it and help get it into osTicket

**Comment by prasenjeetp** [comment]
My apologies. The teammate, that I had assigned this to, missed doing it. I
have forwarded the request to another and hope to get this done coming week.

**Comment by harvy76** [comment]
Hello, Any news with the add collaborator on Creation form from agent?
Thank you
Harvy76

**Comment by mckaygerhard** [comment]
a year was passed, any news here, @prasenjeetp if your have any modification for 1.9 osticket can send to my mail .. to avoid extra coding .. thanks in advance..

**Comment by dharsini3118** [comment]
Hello, i am using Osticket 1.10, any updates on how to add collaborators when clients creates a ticket from web panel?

**Comment by mckaygerhard** [comment]
issue created since 2014, 4 years right now! sit down and start to waith forever @dharsini3118

**Comment by alexdel35** [comment]
I am still waiting for that :)

**Comment by mckaygerhard** [comment]
yeah, as we already know there's nonsense make a issue here umm maybe i must take more seriusly tht and made my own patch in my fork..

unfortunatelly right now i not have 24/7 interent connection so well, @alexdel35 and @dharsini3118 i promise that i'll will work with that, take sure for due as noted i made some work in past months around some plugins.. so my next tarjet will be that for sure https://github.com/venenux/simpleticket109

**Comment by ntozier** [comment]
@mckaygerhard 
You want to clone osTicket and re-release it under your own name?  Fantastic. I wish you luck with your project.

You want to bad mouth the efforts here?  Not so fantastic.  Please do it some where else.

Stay on subject.  The subject of this thread is "Add the collaborators field to the SCP ticket creation form" not your personal clone of this project.

Thank you.

**Comment by JediKev** [comment]
@mckaygerhard I think @ntozier is right, in that you need to chill out a little. You get out what you put in to the community, and right now you're putting out _a lot_ of negativity.

@dharsini3118 @alexdel35 
This feature will be included in `v1.11.0rc1` so please stay tuned! 😃

Cheers.

**Comment by mckaygerhard** [comment]
hi @JediKev  **but many users are in disagree!** thanks for your comment, but i try in the past to apport inclusivelly made code, of course in that moment i not good programmer and i not a programmer, the need forced me to make as one..

about the previous comment, it's opensource right? so let me be!

**Comment by mckaygerhard** [comment]
andd another note: 
> @dharsini3118 @alexdel35 This feature will be included in v1.11.0rc1 so please stay tuned!

pufff 4 years more?

**Comment by JediKev** [comment]
@mckaygerhard I'm not even going to comment on that.... wow

**Comment by alexdel35** [comment]
After so long time, I can wait a little bit more.

osTicket provided us a good open source helpdesk solution for free si we CAN'T claim anything. We can just ask and wait. 

It is a good Platforms, maybe with an old look but most of the awaited features are already available.

**Comment by JediKev** [comment]
@alexdel35 

The UI/UX will completely change in the near future, so please stay tuned.

Cheers.

**Comment by ntozier** [comment]
@dharsini3118 the best answer that you will get to that question is "Soon"

**Comment by satyadev23** [comment]
Hi @ntozier , and does "Soon" means this year itself, please? 
Thanks for helping out.

**Comment by JediKev** [comment]
@satyadev23 

"Soon" as in by the middle/end of July.

Cheers.

**Comment by dharsini3118** [comment]
Hi @JediKev @ntozier , i have already install the new version 1.11, can you help on how to add cc on the web form when a client is creating a ticket?

**Comment by ntozier** [comment]
@dharsini3118 not sure how you installed a version that hasn't been released yet.
1.11rc1 is out, but that is just a buggy release candidate.

**Comment by mckaygerhard** [comment]
July was passed! the year are in lasted months! that "soon" seems "late"

i remenber that in the past when 1.10 still are "rc" the recomendation was "install most recent version 1.10" now that recents version are buggy?

**Comment by JediKev** [comment]
@dharsini3118

The ADD CC option is not for client portal, only Agent Panel.

Cheers.

**Comment by mckaygerhard** [comment]
hi @JediKev thank for clarify that point, it makes sense.. by example if any client can emite email and make tickets, or still are not registered! and if CC are capable for any client this sounds like a mail delivery interface!

**Comment by mckaygerhard** [comment]
i noited your "down hand" @JediKev , sorry for you but this issue and the question are for any mail collaborators.. that's why my downhand, also was posted that new version will comming "soon" and many months are passed away since that! ok @JediKev ?

**Comment by rolltidehero** [comment]
Is this going to be released when end-users can add collaborators at the ticket creation step just like Agents can when they create a ticket?

**Comment by JediKev** [comment]
@rolltidehero 

It is a feature on our development roadmap, so I'd say eventually, yes. There is no set develop date nor release date for this feature so, for now, it's just whenever we get around to it.

Cheers.

**Comment by JVC-MSF-OCB** [comment]
Hey @JediKev, any update concerning a release date for this fetaure?

**Comment by JediKev** [comment]
@logmsf 

Nah, it’s still on our list though. I believe we are not adding any new features (other than the ones we are currently working on) until after v2.0. We are rewriting the entire code base so once we finish that we will start adding new features in the new code base.

Cheers.
