### ISSUE TITLE
Allow full HTML control for email template

### ISSUE THREAD

**Issue by SCHOLAR-Graeme** [osTicket/osTicket#795]
Hi,
First of all thanks for the great work you guys have put into osTicket.

One feature that would be very handy for us is the ability to have more control over the email templates. To get our emails to match our site design and increase compatibility amongst different email clients and browsers we make use of email templates like the one used by [MailChimp ](https://github.com/mailchimp/Email-Blueprints) or [Antwork](https://github.com/internations/antwort).  Both of which make full use of HTML tags including HEAD, BODY and STYLE all of which are currently striped out of the email templates.

The tags are removed in two places, first within the [class.template.php](https://github.com/osTicket/osTicket-1.8/blob/develop/include/class.template.php#L500) file which sanitises the input: 

``` PHP
$vars['body'] = Format::sanitize($vars['body'], false);
```

The second place is within the [redactor-osticket.js](https://github.com/osTicket/osTicket-1.8/blob/develop/js/redactor-osticket.js#L211) file which sets the options for the Redactor editor. Here you can change the list of denied tags from its current default value of:

``` JavaScript
deniedTags: ["html", "head", "link", "body", "meta", "script", "style", "applet"]
```

To only script and applet:

``` JavaScript
deniedTags: ["script", "applet"]
```

My suggestion is therefore to create a new setting to control these changes. Let me know what you think and whether this would be something I would need to develop myself and bring in as a pull request?

Thanks

**Comment by PeopleInside** [comment]
In the HTML editor is no possible to resize text. Maybe should be a more full HTML editor :) Also check it works on mobile (user can write text from mobile).

Will be great implement HTML editor, more complete :)

**Comment by greezybacon** [comment]
@PeopleInside use the `<>` button. Edit the HTML

**Comment by vekexasia** [comment]
I'm also having real troubles with this. I wanted to have a full html with <style> in <head> section but redactor strips them away.

I'm using v1.9.9-1-gbe2f138 . I saw this ticket was marked for 1.9.1 and thought it would be possible to allow full html control over email templates.

Can someone confirm me it's actually impossible tu use a custom html template having <head> and <style> tags without getting stripped?

**Comment by ntozier** [comment]
Did you try what greezybacon said?

**Comment by vekexasia** [comment]
Of course i used the html. But when I hit save redactor switches back to "preview/design" mode and everything gets lost :(

**Comment by harnerdesigns** [comment]
Did this ever get implemented?
