### ISSUE TITLE
Show Organization in Ticket View instead of From

### ISSUE THREAD

**Issue by JoKneeMo** [osTicket/osTicket#833]
I've been anticipating v1.9 for many many commits. Thank you very much for your hard work!

With the addition of organization management, I'm sure there are lots of things that will be added. The main one that my users are request is an option in the admin panel to show the Organization instead of From on all ticket tables, much like the "Assigned To/Department" works today.

**Comment by emirfares** [comment]
Logscape -

here is a solution for listing problem

$qwhere = sprintf(' WHERE ( ticket.user_id=%d ) or ( ticket.user_id in ( select id from unds_supr_tch_user where org_id <> 0 AND org_id in (select org_id from unds_supr_tch_user where id = %d)))',
$thisclient->getId(), $thisclient->getId(), $thisclient->getId());

**Comment by denysvitali** [comment]
How is this going?

**Comment by ntozier** [comment]
@mnietz I do not see any one submitting any code for this since Dec 2015, so I would say no.
Have you seen the forth coming Custom Queues feature developed by @greezybacon ?

**Comment by mnietz** [comment]
@ntozier no, not yet, thanks for pointing out. Let's see if it's included in the next release.
