### ISSUE TITLE
Team Assigned and Staff Assigned Icons Missing in Ticket Queue View

### ISSUE THREAD

**Issue by pfurches** [osTicket/osTicket#846]
When you display the open tickets no icons appear next to the team or staff assignment.

/scp/css/scp.css
Line 360
.Icon.assignedTicket { background:url(../images/icons/assigned_ticket.gif) 0 0 no-repeat; }

I added these two lines to correct and display icons next to the user/team assignment:
.Icon.staffAssigned { background:url(../images/icons/assigned_ticket.gif) 0 0 no-repeat; }
.Icon.teamAssigned { background:url(../images/icons/assigned_ticket.gif) 0 0 no-repeat; }

I am not sure if these are the correct icons but I checked 1.8.1.2 and 1.9 RC and no icons appear next to the staff assignment.  I am guessing this was a simple oversight when teams were added.

Thanks for all your help!

**Comment by tilerans** [comment]
+1. Issue in v1.9.8 (9c6acce)

**Comment by ntozier** [comment]
Can you add an image displaying the behavior?  
I'm not real sure what you mean.

**Comment by opodecano** [comment]
Very helpfull @pfurches ..
