### ISSUE TITLE
imap processing error when "from" field is utf8 encoded

### ISSUE THREAD

**Issue by ericLemanissier** [osTicket/osTicket#850]
When an email is received with the "from" header encoded (for example "From: =?utf-8?q?D=C3=A9tection_de_spam_=3Cnoreply=401and1=2Efr=3E?="), the email is badly parsed, generating the following notification "Excessive errors processing emails for imap.1und1.de/support@xxx.com. Please manually check the inbox".

This is caused by the call of imap_headerinfo in class.mailfetch.php, returning a variable without any "from" nor "fromaddress" field.
In this case, the "from" can be read by calling imap_rfc822_parse_headers(imap_fetchheader(...)) which gives a result with the following fields:
...
  ["fromaddress"]=>
  string(69) "=?utf-8?q?D=C3=A9tection_de_spam_=3Cnoreply=401and1=2Efr=3E?=@UNKNOWN"
  ["from"]=>
  array(1) {
    [0]=>
    object(stdClass)#29 (2) {
      ["mailbox"]=>
      string(61) "=?utf-8?q?D=C3=A9tection_de_spam_=3Cnoreply=401and1=2Efr=3E?="
      ["host"]=>
      string(7) "UNKNOWN"
    }
  }
...

The from->mailbox and from->host would still have to be adapted after that

**Comment by sdolemelipone** [comment]
Can this issue be re-opened? This has been causing problems processing emails, in the meantime we have to maintain our own patch to osticket using ``imap_rfc822_parse_headers(imap_fetchheader($this->mbox, $mid))``
instead of ``imap_headerinfo``.
