### ISSUE TITLE
osticket 1.9 RC1 - need to have CAPTCHA available for registration

### ISSUE THREAD

**Issue by cube1us** [osTicket/osTicket#864]
Downloaded osticket 1.9 RC1 5/1/2014 to explore the new user registration feature.  Currently, unlike "guest" access, the registration process has no way to require a CAPTCHA test during user registration, leaving it open to serious spamming.  Suggest that either the field corresponding to Admin => Settings => Tickets => "Enable CAPTCHA on new web tickets", or  a new, similar configuration option for user registration be consulted in the user registration code.  [If there is a better place to submit this request, please advise.  Thanks.]

**Comment by clonemeagain** [comment]
@cube1us did you resolve this? I'm thinking of adding reCaptcha to mine but if you've already done it..

**Comment by cube1us** [comment]
This was a requirement for an outfit I was consulting for but not
involved with any more.  No, I did not do anything about it.

**Comment by clonemeagain** [comment]
Cheers!
