### ISSUE TITLE
Confirming ticket edits

### ISSUE THREAD

**Issue by henrycoule** [osTicket/osTicket#869]
Is there a way to not make putting in internal notes mandatory when editing tickets? Each time I edit a ticket I have to state why I edited the ticket. I don't want this to be a required option. I should be able to edit and save without having to enter any reason.

**Comment by henrycoule** [comment]
@greezybacon Do we have any updates to this ?

**Comment by greezybacon** [comment]
@henrycoule we've parked this for the time being. After the next major release, we hope to add the concept of audit events, system message, and comments to the ticket thread. Then we'd like to implement the auto messages as audit events, which we feel makes more sense than the internal notes.
