### ISSUE TITLE
Unable to login using AD user in OsTicket 1.9.1

### ISSUE THREAD

**Issue by MohamedFaisal** [osTicket/osTicket#977]
Hi,

I couldn't able to login using AD user in Osticket ticket creation or T.Check page.I have done the LDAP plugin page as guided in this URL http://osticket.com/forum/discussion/76358/how-to-configure-the-ldap-authentication-and-lookup-plugin.  Anybody can resolve this issue because I haven;t seen any fulfilled discussion regarding LDAP authendiation process and mechanism.

please help me ..

**Comment by vikipatil7233** [comment]
Default domain name: servername.domain.local (FQDN)
DNS server : IP of DNS server
LDAP servers: same as default domain name..
TLS : not required
search user: anyuser in AD(domain\anyuser)
password : password of the AD user mentioned above
Search Base: DC=domain,DC=local (based on your domain setup)
LDAP Schema: choose "Microsoft Active Directory"

its work on testing Lab

**Comment by ntozier** [comment]
It stands to reason that if this works on one server, but not on your production server that you have a configuration difference between the two. It could be as simple as your production server isn't allowed to talk to your AD server, or a firewall.

**Comment by greezybacon** [comment]
> Default domain name: servername.domain.local (FQDN)

This should just be `domain.local`, right?

**Comment by gartut** [comment]
no that would be "[Servername].[domain].local"

**Comment by ntozier** [comment]
Actually the default domain probably shouldn't be "[Servername].[domain].local".  Unless you happened to name your domain "[Servername].[domain].local".  And it's a happy coincidence.
Ours is corp.[domain].local currently, but would probably work with simply [domain].
you would want to use "[Servername].[domain].local" under LDAP servers.

**Comment by asra10** [comment]
here are my config but i cannot login with my AD credentials :
Default Domain : prodad02.sti.td
DNS Server : 10.20.50.155
LDAP Server : prodad02.sti.td
Search User : mydomain\adminitrateur
password : mypassword administrator
Serch Base : DC=sti,DC=td
LDAP SChema : Microsoft Active Directory

**Comment by ntozier** [comment]
@asra10 you might want to try posting your question on the support forums and not on a closed issue report.
The support forums are at: [https://forum.osticket.com/](https://forum.osticket.com/)
You will also likely want to read and follow the posting guidelines located in this thread: [Please read before requesting assistance](https://forum.osticket.com/d/89131-please-read-before-requesting-assistance).  The more information you give us the better we will be able to assist you. Thank you.

ps and gosh I hope that you are not running v1.9.1
